
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from eCP.AssessmentBasedTerminologyCode.AssessmentBasedTerminologyCodeManager
package eCP.AssessmentBasedTerminologyCode;

/**
 * Local-Home interface for AssessmentBasedTerminologyCode
 */
public interface AssessmentBasedTerminologyCodeLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/AssessmentBasedTerminologyCodeLocal";
    public static final String JNDI_NAME = "AssessmentBasedTerminologyCodeLocal";

    eCP.AssessmentBasedTerminologyCode.AssessmentBasedTerminologyCodeLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
