 /*
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Date			Edit History		Name			INC Number		Rev.Date	Rev.Name		Description
-------------------------------------------------------------------------------------------------------------------------------------------------------------

12/11/2014		AAKH_CRF_0057		Sakti Sankar	IN052312									Autoclaving function, option to select
																								Biological indicator , BMS Pass / Fail 
																								Both in Master as wel as Transaction function.
21/11/2014		AAKH_CRF_0057		Karthi			IN052312					Ramesh
31/08/2015		IN056823			Ramesh G		IN056823									The Owner Store users access the newly introduced  'Return Vendor Loan' functionality
15/10/2015		AAKH_CRF_0058.1		Badmavathi.B	IN057727									CSSD Stock Vendor Loan Details and  Vendor Loaned Items Report  
1/7/2021  		TFS:19249        	Shazana                      									ML-MMOH-CRF-1661-US001
--------------------------------------------------------------------------------------------------------------------------------------------------------------
*/

package eSS.resources;
 
import java.util.*;

public class Labels extends ListResourceBundle
{
public Object[][] getContents()
{
         return contents;
    }

static final Object[][] contents = 
{
	{"eSS.DocNo.label","Doc No"},
	{"eSS.DocDate.label","Doc Date"},
	{"eSS.ServiceLocation.label","Service Location"},
	{"eSS.SurgeryType.label","Surgery Type"},
	{"eSS.GroupType.label","Group Type"},  
	{"eSS.UsageType.label","Usage Type"},
	{"eSS.AlternateGroupCode.label","Alternate Group Code"},
	{"eSS.GroupCode.label","Group Code"},
	{"eSS.GroupDescription.label","Group Description"},
	{"eSS.AlternateGroupDescription.label","Alternate Group Description"},
	{"eSS.TrayNo.label","Tray No"},
	{"eSS.BinLocation.label","Bin Location"},
	{"eSS.DocRef.label","Doc Ref"},
	{"eSS.TotalValue.label","Total Value"},
	{"eSS.CutoffDate.label","Cutoff Date"},
	{"eSS.AutoclaveUnit.label","Autoclave Unit"},
	{"eSS.SterilizationType.label","Sterilization Type"},
	{"eSS.LoadNo.label","Load No"},
	{"eSS.UnitType.label","Unit Type"},
	{"eSS.LongDesc.label","Long Desc"},
	{"eSS.ShortDesc.label","Short Desc"},
	{"eSS.Temperature.label","Temperature"},
	{"eSS.UnitCondition.label","Unit Condition"},
	{"eSS.AutoclaveWashTest.label","Autoclave/Wash Test"},
	{"eSS.BatchID.label","Batch ID"},
	{"eSS.TestResult.label","Test Result"},
	{"eSS.ResultDate.label","Result Date"},
	{"eSS.AutoclaveWashUnit.label","Autoclave/Wash Unit"},
	{"eSS.TestDate.label","Test Date"},
	{"eSS.EnteredBy.label","Entered By"},
	{"eSS.EntryCompleted.label","Entry Completed"},
	{"eSS.Pass.label","Pass"},
	{"eSS.Fail.label","Fail"},
	{"eSS.Entry.label","Entry"},
	{"eSS.Notcompleted.label","Not completed"},
	{"eSS.AutoclaveWashUnit.label","Autoclave /Wash Unit"},
	{"eSS.AutoclaveWashingUnit.label","Autoclave/Washing Unit"},
	{"eSS.Autoclave.label","Autoclave"},
	{"eSS.Washing.label","Washing"},
	{"eSS.AutoclaveDate.label","Autoclave Date"},
	{"eSS.LoadStatus.label","Load Status"},
	{"eSS.OldLoadNo.label","Old Load No"},
	{"eSS.ROFDocType.label","ROF Doc Type"},
	{"eSS.ROFDocNo.label","ROF Doc No"},
	{"eSS.AutoclavingUnit.label","Autoclaving Unit"},
	{"eSS.LoadNumber.label","Load Number"},
	{"eSS.AutoclavingDate.label","Autoclaving Date"},
	{"eSS.PhysicalInvId.label","Physical Inv Id"},
	{"eSS.OwnerStore.label","Owner Store"},
	{"eSS.CurrentStore.label","Current Store"},
	{"eSS.Owner.label","Owner"},
	{"eSS.RequestedQuantity.label","Requested Quantity"},
	{"eSS.IssuedQuantity.label","Issued Quantity"},
	{"eSS.RequestedOn.label","Requested On"},
	{"eSS.RequestType.label","Request Type"},
	{"eSS.CancellationRemarks.label","Cancellation Remarks"},
	{"eSS.RequisitionbyStore.label","Requisition by Store"},
	{"eSS.RequisitiononStore.label","Requisition on Store"},
	{"eSS.RequestedbyStore.label","Requested by Store"},
	{"eSS.RequestedonStore.label","Requested on Store"},
	{"eSS.OldBinLocation.label","Old Bin Location"},
	{"eSS.NewBinLocation.label","New Bin Location"},
	//{"eSS.GroupType.label","GroupType"},
	{"eSS.TraySearch.label","Tray Search"},
	{"eSS.Set.label","Set"},
	{"eSS.Tray.label","Tray"},
	{"eSS.SoftPack.label","Soft Pack"},
	{"eSS.Linen.label","Linen"},//added for ML-MMOH-CRF-1661
	{"eSS.AutoclaveWashingTest.label","Autoclave/Washing Test"},
	{"eSS.WriteoffReason.label","Write off Reason"},
	{"eSS.SubClassification.label","Sub Classification"},
	{"eSS.SterilizationProcessStage.label","Sterilization Process Stage"},
	{"eSS.WashingType.label","Washing Type"},
	{"eSS.StatisticalGroup.label","Statistical Group"},
	{"eSS.CSSDStore.label","CSSD Store"},
	{"eSS.CSSDItem.label","CSSD Item"},
	{"eSS.CSSDGroup.label","CSSD Group"},
	{"eSS.SterilizationCost.label","Sterilization Cost"},
	{"eSS.AlternateGroup.label","Alternate Group"},
	{"eSS.GroupforStore.label","Group for Store"},
	{"eSS.ConfirmAuthorize.label","Confirm Authorize"},
	{"eSS.ConfirmCancel.label","Confirm Cancel"},
	{"eSS.ConfirmDelete.label","Confirm Delete"},
	{"eSS.DeleteAllItems.label","Delete All Items"},
	{"eSS.ConfirmFinalize.label","Confirm Finalize"},
	{"eSS.Finalize.label","Finalize"},
	{"eSS.DescrepancyEnteredAt.label","Descrepancy Entered At"},
	{"eSS.Discrepancy.label","Discrepancy"},
	{"eSS.DiscrepancyQty.label","Discrepancy Qty"},
	{"eSS.DiscrepancyType.label","Discrepancy Type"},
	{"eSS.DiscrepancyReason.label","Discrepancy Reason"},
	{"eSS.BillingType.label","Billing Type"},
	{"eSS.EnteredAt.label","Entered At"},
	{"eSS.SterReqDocType.label","Ster Req Doc Type"},
	{"eSS.SterReqDocNo.label","Ster Req Doc No"},
	{"eSS.Contaminated.label","Contaminated"},
	{"eSS.Sterilization.label","Sterilization"},
	{"eSS.Hold.label","Hold"},
	{"eSS.Dispatch.label","Dispatch"},
	{"eSS.DispatchDate.label","Dispatch Date"},
	{"eSS.ReturnFrom.label","Return From"},
	{"eSS.ReturnTo.label","Return To"},
	{"eSS.PrintSterilizationRequest.label","Print Sterilization Request"},
	{"eSS.WithDiscrepancy.label","With Discrepancy"},
	{"eSS.WithoutDiscrepancy.label","Without Discrepancy"},
	{"eSS.AlphaCode.label","Alpha Code"},
	{"eSS.Non-returnable.label","Non-returnable"},
	{"eSS.ItemClass.label","Item Class"},
	{"eSS.ItemAnalysis.label","Item Analysis"},
	{"eSS.Packing.labelSurgeryTypeLinkedToOT","Packing"},
	{"eSS.PackItem.label","Pack Item"},
	{"eSS.PackItemQty.label","Pack Item Qty"},
	{"eSS.PackAddlCost.label","Pack Addl Cost"},
	{"eSS.ItemQty.label","Item Qty"},
	{"eSS.Association.label","Association"},
	{"eSS.StoreCode.label","Store Code"},
	{"eSS.StoreDescription.label","Store Description"},
	{"eSS.Surgery.label","Surgery"},
	{"eSS.Usage.label","Usage"},
	{"eSS.NonReturable.label","Non-Returable"},
	{"eSS.Instrument.label","Instrument"},
	{"eSS.DiscrepancyQuantity.label","Discrepancy Quantity"},
	{"eSS.Del.label","Del"},
	{"eSS.InstrumentDescription.label","Instrument Description"},
	{"eSS.TrayNoSearch.label","Tray No Search"},
	{"eSS.ReqGroup.label","Req Group"},
	{"eSS.AuthGroup.label","Auth Group"},
	{"eSS.IssueGroup.label","Issue Group"},
	{"eSS.IssueCost.label","Issue Cost"},
	{"eSS.ReqDocType.label","Req Doc Type"},
	{"eSS.ReqDocNo.label","Req Doc No"},
	{"eSS.IssueStore.label","Issue Store"},
	{"eSS.ReceivingStore.label","Receiving Store"},
	{"eSS.PendingIssues.label","Pending Issues"},
	{"eSS.Consumable.label","Consumable"},
	{"eSS.Chargeable.label","Chargeable"},
	{"eSS.Remarks.label","Remarks "},
	{"eSS.ProcessStage.label","Process Stage"},
	{"eSS.ProcessRemarks.label","Process Remarks"},
	{"eSS.UserAccessforStoreList.label","User Access for Store List"},
	{"eSS.TrayDetails.label","Tray Details"},
	{"eSS.InstrumentsusedforPatientsList.label","Instruments used for Patients List"},
	{"eSS.TrayValues.label","Tray Values"},
	{"eSS.DepartmentChargeDetails.label","Department Charge Details"},
	{"eSS.ChargesSummary.label","Charges Summary"},
	{"eSS.AgeingAnalysis.label","Ageing Analysis"},
	{"eSS.PackCost.label","Pack Cost"},
	{"eSS.HoldReason.label","Hold Reason"},
	{"eSS.PackingDate.label","Packing Date"},
	{"eSS.Cost.label","Cost"},
	{"eSS.DiscrepancyDetails.label","Discrepancy Details"},
	{"eSS.Sterilize.label","Sterilize"},
	{"eSS.Wash.label","Wash"},
	{"eSS.Update.label","Update"},
	{"eSS.PackQty.label","Pack Qty"},
	{"eSS.CurrentProcessingMonthYear.label","Current Processing Month/Year"},
	{"eSS.Billing.label","Billing"},
	{"eSS.BillingService.label","Billing Service"},
	{"eSS.GeneralLedger.label","General Ledger"},
	{"eSS.PrepareGroup.label","Prepare Group"},
	{"eSS.RequestGroup.label","Request Group"},
	{"eSS.ReturnGroup.label","Return Group"},
	{"eSS.ReturnInstrument.label","Return Instrument"},
	{"eSS.TrayDiscrepancy.label","Tray Discrepancy"},
	{"eSS.WriteOff.label","Write Off"},
	{"eSS.Variance.label","Variance"},
	{"eSS.ProcessSterilizationRequest.label","Process Sterilization Request"},
	{"eSS.SterileLife.label","Sterile Life"},
	{"eSS.ItemImagePath.label","Item Image Path"},
	{"eSS.GenerateSterilizationRequestwhilepreparing.label","Generate Sterilization Request while preparing"},
	{"eSS.Interface.label","Interface"},
	{"eSS.DefaultDocumentTypes.label","Default Document Types"},
	{"eSS.OtherDefaults.label","Other Defaults"},
	{"eSS.StoreforPrepareGroup.label","Store for Prepare Group"},
	{"eSS.CurrentProcessMonthYear.label","Current Process Month/Year"},
	{"eSS.CountSheetDate.label","Count Sheet Date"},
	{"eSS.PhyInvID.label","Phy Inv ID"},
	{"eSS.AutoclavedDate.label","Autoclaved Date"},
	{"eSS.Finalized.label","Finalized"},
	{"eSS.AutoclaveWashTest.label","Autoclave Wash Test"},
	{"eSS.AutoclaveWashUnitCode.label","Autoclave Wash Unit Code"},
	{"eSS.ReportOrder.label","Report Order"},
	{"eSS.CutoffDate.label","Cut off Date"},
	{"eSS.InstrumentStatus.label","Instrument Status"},
	{"eSS.SterReqStatus.label","Ster Req Status"},
	{"eSS.StoreType.label","Store Type"},
	{"eSS.TrayStatus.label","Tray Status"},
	{"eSS.Unsterilized.label","Unsterilized"},
	{"eSS.Sterilized.label","Sterilized"},
	{"eSS.AtServiceLocation.label","At Service Location"},
	{"eSS.DocTypeCode.label","Doc Type Code"},
	{"eSS.EntryStatus.label","Entry Status"},
	{"eSS.FinalizedStatus.label","Finalized Status"},
	{"eSS.ReqQuantity.label","Req Quantity"},
	{"eSS.AvailableSterilizedQuantity.label","Available Sterilized Quantity"},
	{"eSS.Authorization.label","Authorization"},
	{"eSS.Issue.label","Issue"},
	{"eSS.ReqByStore.label","Req By Store"},
	{"eSS.ReqOnStore.label","Req On Store"},
	{"eSS.Requestquantity.label","Request Quantity"},
	{"eSS.RequestDetails.label","Request Details"},
	{"eSS.Entered.label","Entered"},
	{"eSS.Issued.label","Issued"},
	{"eSS.NotIssued.label","Not Issued"},
	{"eSS.FullyIssued.label","Fully Issued"},
	{"eSS.PartiallyIssued.label","Partially Issued"},
	{"eSS.Expired.label","Expired"},
	{"eSS.ChargeConsumables.label","Charge Consumables"},
	{"eSS.ReturnableInstrument.label","Returnable Instrument"},
	{"eSS.ChargeOption.label","Charge Option"},
	{"eSS.ReceiptReference.label","Receipt Reference"},
	{"eSS.Charge.label","Charge"},
	{"eSS.Deposit.label","Deposit"},
	{"eSS.ChgConsum.label","Chg Consum"},
	{"eSS.ReturnFromStore.label","Return From Store"},
	{"eSS.ReturnToStore.label","Return To Store"},
	{"eSS.SelectTrays-ReturnGroup.label","Select Trays - Return Group"},
	{"eSS.FromStore.label","From Store"},
	{"eSS.ToStore.label","To Store"},
	{"eSS.UnFinalized.label","UnFinalized"},
	{"eSS.GroupTrayNoItem.label","Group / Tray No / Item"},
	{"eSS.Damaged.label","Damaged"},
	{"eSS.ReturnQty.label","Return Qty"},
	{"eSS.ReturningStore.label","Returning Store"},
	{"eSS.EnteredDt.label","Entered Dt"},
	{"eSS.CheckedDt.label","Checked Dt"},
	{"eSS.WashedDt.label","Washed Dt"},
	{"eSS.PackedDt.label","Packed Dt"},
	{"eSS.AutoclavedDt.label","Autoclaved Dt"},
	{"eSS.DispatchedDt.label","Dispatched Dt"},
	{"eSS.Ack.Dt.label","Ack.Dt"},
	{"eSS.CheckedBy.label","Checked By"},
	{"eSS.WashedBy.label","Washed By"},
	{"eSS.PackedBy.label","Packed By"},
	{"eSS.AutoclavedBy.label","Autoclaved By"},
	{"eSS.DispatchedBy.label","Dispatched By"},
	{"eSS.Ack.By.label","Ack.By"},
	{"eSS.SterilizationRequestUserDetail.label","Sterilization Request User Detail"},
	{"eSS.ImagePreview.label","Image Preview"},
	{"eSS.ImageURL.label","Image URL"},
	{"eSS.InvalidPageCall.label","Invalid Page Call"},
	{"eSS.Countbycomponents.label","Count by components"},
	{"eSS.Countby.label","Count by"},
	{"eSS.Components.label","Components"},
	{"eSS.MonthlyServiceStatistics.label","Monthly Service Statistics"},
	{"eSS.MonthlyServiceStatisticsByStores.label","Monthly Service Statistics By Stores"},
	{"eSS.GroupMovementStatistics.label","Group Movement Statistics"},
	{"eSS.TraysUsageStatistics.label","Trays Usage Statistics"},
	{"eSS.AutoclavingLoadFailureStatistics.label","Autoclaving Load Failure Statistics"},
	{"eSS.TrayDiscrepancyStatistics.label","Tray Discrepancy Statistics"},
	{"eSS.MonthlyServiceStatisticsByGroups.label","Monthly Service Statistics By Groups"},
	{"eSS.SterileType.label","Sterile Type"},
	{"eSS.SterileCost.label","Sterile Cost"},
	{"eSS.SterileTypeDescription.label","Sterile Type Description"},
	{"eSS.SterilizationRequestList.label","Sterilization Request List"},
	{"eSS.PackingCheckList.label","Packing Check List"},
	{"eSS.SterileLabel.label","Sterile Label"},
	{"eSS.DispatchList.label","Dispatch List"},
	{"eSS.AcknowledgementList.label","Acknowledgement List"},
	{"eSS.PackLabel.label","Pack Label"},
	{"eSS.AutoclavingLoadDetails.label","Autoclaving Load Details"},
	{"eSS.AutoclaveWashUnitTestDetails.label","Autoclave/Wash Unit Test Details"},
	{"eSS.AutoclavingLoadSummary.label","Autoclaving Load Summary"},
	{"eSS.RequestOrderTraysStatus.label","Request Order Trays Status"},
	{"eSS.RequestOrderTraysStatusSummary.label","Request Order Trays Status Summary"},
	{"eSS.SterilizationRequestProcessTimingDetails.label","Sterilization Request Process Timing Details"},
	{"eSS.UseWithin.label","Use Within"},
	{"eSS.InServiceLocation.label","In Service Location"},
	{"eSS.SterilizationRequest.label","Sterilization Request"},
	{"eSS.Transaction.label","Transaction"},
	{"eSS.DiscReason.label","Disc Reason"},
	{"eSS.Returnable.label","Returnable"},
	{"eSS.Nonreturnable.label","Non returnable"},
	{"eSS.AtUnits.label","At Units"},
	{"eSS.AtOwner.label","At Owner"},
	{"eSS.TRNType.label","TRN Type"},
	{"eSS.DocTypeDescription.label","Doc Type Description"},
	{"eSS.TRNTypeDescription.label","TRN Type Description"},
	{"eSS.Prepare.label","Prepare"},
	{"eSS.Return.label","Return"},
	{"eSS.Write.label","Write"},
	{"eSS.Physical.label","Physical"},
	{"eSS.SterilizationRequestProcessing.label","Sterilization Request Processing"},
	{"eSS.UserAccessforStoreListing.label","User Access for Store Listing"},
	{"eSS.Instruments.label","Instruments"},
	{"eSS.off.label","off"},
	{"eSS.ReturnInstruments.label","Return Instruments"},
	{"eSS.PhysicalVariance.label","Physical Variance"},
	{"eSS.WashingUnit.label","Washing Unit"},
	{"eSS.WashingCompleted.label","Washing Completed"},
	{"eSS.SterilizationTypeDescription.label","Sterilization Type Description"},
	{"eSS.WriteOffCost.label","Write Off Cost"},
		{"eSS.FailureCount.label","Failure Count"},
	{"eSS.Lowest.label","Lowest"},
	{"eSS.Highest.label","Highest"},
	{"eSS.NoOfTraysPertainingTo.label","No Of Trays Pertaining To"},
	{"eSS.Before.label","Before"},
	{"eSS.Passed.label","Passed"},
	{"eSS.Failed.label","Failed"},
	{"eSS.TestCode.label","Test Code"},
	{"eSS.TestDescription.label","Test Description"},
	{"eSS.Autoclave.label","Autoclave"},
	{"eSS.GrandTotal.label","Grand Total"},
	{"eSS.InsCost.label","InsCost"},
	{"eSS.ConsCost.label","Cons Cost"},
	{"eSS.DepartmentTotal.label","Department Total"},
	{"eSS.StoreTotal.label","Store Total"},
	{"eSS.GrpType.label","Grp Type"},
	{"eSS.Expiry.label","Expiry"},
	{"eSS.ReceivedBy.label","Received By"},
	{"eSS.QtyOnHand.label","Qty On Hand"},
	{"eSS.GroupRemarks.label","Group Remarks"},
	{"eSS.PackComponents.label","Pack Components"},
	{"eSS.PrepareDate.label","Prepare Date"},
	{"eSS.SterileCount.label","Sterile Count"},
	{"eSS.LastIssueDate.label","Last Issue Date"},
	{"eSS.PresentSterCount.label","Present Ster., Count"},
	{"eSS.RequestOn.label","Request On"},
	{"eSS.IssueDate.label","Issue Date"},
	{"eSS.ImagFile.label","Imag File"},
	{"eSS.AuthorizedSignatory.label","Authorized Signatory"},
	{"eSS.ItemsPacksProcessedandIssuedDuringthePeriod .label","Items/Packs Processed and Issued During the Period"},
	{"eSS.OverallItemsPacksProcessed.label","Overall Items Packs/Processed"},
	{"eSS.TotalNoofSterilizationCycles.label","Total No of Sterilization Cycles"},
	{"eSS.DetailsoftheItemsPacksProcessed.label","Details of the Items/Packs Processed"},
	{"eSS.DetailsOftheTotalNumberofSterilizationCycles.label","Details Of the Total Number of Sterilization Cycles"},
	{"eSS.NoofCycles.label","No of Cycles"},
	{"eSS.SubClass.label","Sub Class"},
	{"eSS.QuantitySterilized.label","Quantity Sterilized"},
	{"eSS.Instrument.label","Instrument"},
	{"eSS.IssueDate.label","Issue Date"},
	{"eSS.TotalQty.label","Total Qty"},
	{"eSS.ReturnedQty.label","Returned Qty"},
	{"eSS.PendingQty.label","Pending Qty"},
	{"eSS.ReturnEnteredBy.label","Return Entered By"},
	{"eSS.PhysicalBinLocation.label","Physical Bin Location"},
	{"eSS.SystemStock.label","System Stock"},
	{"eSS.PhysicalStock.label","Physical Stock"},
	{"eSS.Surgery.label","Surgery"},
	{"eSS.Usage.label","Usage"},
	{"eSS.Cons.label","Cons"},
	{"eSS.StandQty.label","Stand.Qty"},
	{"eSS.CurrQty.label","Curr Qty"},
	{"eSS.OT.label","OT"},
	{"eSS.IN.label","IN"},
	{"eSS.OUT.label","OUT"},
	{"eSS.CSSD.label","CSSD"},
	{"eSS.EncounterLabel.label","Encounter Label"},
	{"eSS.PatientLabel.label","Patient Label"},
	{"eSS.Theater.label","Theater"},
	{"eSS.Surgeon.label","Surgeon"},
	{"eSS.PackedOn.label","Packed On"},
	{"eSS.RequestQty.label","Request Qty"},
	{"eSS.IssueQty.label","IssueQty"},
	{"eSS.WashEnteredDate.label","Wash Entered Date"},
	{"eSS.WashCompletedDate.label","Wash Completed Date"},
	{"eSS.LoadedDate.label","Loaded Date"},
	{"eSS.LoadCompletedDate.label","Load Completed Date"},
	{"eSS.AcknowledgementDate.label","Acknowledgement Date"},
	{"eSS.CheckingDt.label","Checking Dt"},
	{"eSS.Sterilize.label","Sterilize"},
	{"eSS.NoofTrays.label","No of Trays"},
	{"eSS.SterilizedBy.label","Sterilized By"},
	{"eSS.AllowedTransactions.label","Allowed Transactions"},
	{"eSS.ProcessROF.label","Process ROF"},
	{"eSS.Returnable.label","Returnable"},
	{"eSS.PreparedOn.label","Prepared On"},
	{"eSS.PreparedBy.label","Prepared By"},
	{"eSS.MonthYear.label","Month/Year"},
	{"eSS.SterilizeCount.label","Sterilize Count"},
	{"eSS.SurgeryCode.label","Surgery Code"},
	{"eSS.ConsValue.label","Cons Value"},
	{"eSS.InsValue.label","Ins Value"},
	{"eSS.SurgeryTypeDescription.label","Surgery Type Description"},
	{"eSS.ServiceLocationDescription.label","Service Location Description"},
	{"eSS.AutoclaveWashUnitDescription.label","Autoclave/Washing Unit Description"},
	{"eSS.NonOwner.label","Non Owner"},
	{"eSS.Store.label","Store"},
   	{"eSS.SterileLife.label","Sterile Life"},
   	{"eSS.UseWithin.label","Use Within"},
   	{"eSS.Readytouse.label","Ready to use"},
   	{"eSS.Notreadytouse.label","Not ready to use"},
   	{"eSS.AutoclaveWashingTestDescription.label","Autoclave / Washing Test Description"},
	{"eSS.TotalTray(s).label","Total Tray(s)"},
	{"eSS.WriteoffReasonDiscrepancy.label","Write off Reason/Discrepancy"},
	{"eSS.WriteoffReasonDiscrepancyDescription.label","Write off Reason/Discrepancy Description"},
	{"eSS.UsageTypeDescription.label","Usage Type Description"},
	{"eSS.SubClassificationCode.label","Sub Classification Code"},
    {"eSS.SubClassificationDescription.label","Sub Classification Description"},
    {"eSS.ProcessStageCode.label","Process Stage Code"},
    {"eSS.ProcessStageDescription.label","Process Stage Description"},
    {"eSS.WashingTypeDescription.label","Washing Type Description"},
    {"eSS.StatisticalGroupCode.label","Statistical Group Code"},
    {"eSS.StatisticalGroupDescription.label","Statistical Group Description"},
    {"eSS.Pack.label","Pack"},
    {"eSS.ImageFile.label","Image File"},
	{"eSS.NonConsumable.label","Non Consumable"},
	{"eSS.NonChargeable.label","Non Chargeable"},
	{"eSS.Only.label","Only"},
	{"eSS.UserID.label","UserID"},
	{"eSS.UserName.label","UserName"},
	{"eSS.AutoclaveWashUnit.label","Autoclave Wash Unit"},
	{"eSS.TRNDocType.label","TRN doc type"},
	{"eSS.Requestor.label","Requestor"},
	{"eSS.Inactive.label","Inactive"},
	{"eSS.UnitStatus.label","Unit Status"},
	{"eSS.IssueCount.label","Issue Count"},
	{"eSS.SystemDefined.label","System Defined"},
	{"eSS.Positive.label","Positive"},
	{"eSS.Negative.label","Negative"},
	{"eSS.Descrepancy.label","Descrepancy"},
	{"eSS.System.label","System"},
	{"eSS.Missing.label","Missing"},
	{"eSS.Moved.label","Moved"},
	{"eSS.CurrentProcessingMonth.label","Current Processing Month"},
	{"eSS.CurrentProcessingYear.label","Current Processing Year"},
	{"eSS.UserAccessforStore.label","User Access for Store"},
	{"eSS.ImageURL.label", "Image URL:"},
	{"eSS.WashUnit.label", "Wash Unit"},
	{"eSS.Required.label", "Required"},
	{"eSS.Requestby.label", "Request By"},
	{"eSS.Item.label", "Item"},
	{"eSS.Quantity.label", "Quantity"},
	{"eSS.ConfirmPrinting.label", "Confirm Printing"},
	{"eSS.PrintPackingLabel.label", "Print Packing Label"},
	{"eSS.CodeType.label", "Code Type"},
////Added By Sakti Sankar on 06/12/2012 against CRF#222
	{"eSS.Acknowledge.label", "Acknowledge"},
	{"eSS.Pending.label", "Pending"},
	{"eSS.Receive.label", "Receive"},
	{"eSS.Reject.label", "Reject"},
	{"eSS.AcknowledgementFor.label", "Acknowledgement For"},
	{"eSS.PendingForAcknowledgeQuantity.label", "Pending for Ackn./Conf. Quantity"},
	{"eSS.SeqNo.label", "Sequence No"},
//Added ends
    {"eSS.AcknowledgementStatus.label", "Acknowledgement Status"},
	{"eSS.BlockedQty.label", "Blocked Qty"},
	{"eSS.MinQty.label", "Minimum Quantity"},
	{"eSS.ConfirmAck.label", "Confirm Ack."},
	{"eSS.IssueReturn.label", "Issue Return"},
	{"eSS.UnderAcknowledgement.label", "Under Acknowledgement"},
	//Added by sakti against BRU-HIMS-CRF_360
	{"eSS.DisplayGroupsLinkedToPatient.label", "Display Groups Linked to patient"},
	{"eSS.IssDocNo.label","Issue Doc No"},
	{"eSS.PreDocNo.label","Prepare Doc No"},
	{"eSS.IssDocType.label","Iss Doc Type"},
	{"eSS.Reason.label","Reason"},
	{"eSS.SterilizationDocNo.label","Sterilization doc No"},
	{"eSS.AutoRequestGroup.label","Auto Request Group"},
	{"eSS.AutoRequestonStore.label","Auto Request On Store"},
	{"eSS.PendingAcknowledgement.label", "Pending Acknowledgement"},
	{"eSS.PendingReqQty.label", "Pending Request Qty"},
	{"eSS.ReorderLevel.label","Reorder Level"},
	{"eSS.ReorderQuantity.label","Reorder Quantity"},
	{"eSS.EnableAutoRequest.label","Enable Auto Request For Group based on Reorder Level of Non Owner Store"},
	{"eSS.Doctor.label","Doctor"},
	{"eSS.Out.label","Out"},
	{"eSS.GroupSearchAndSelect.label","Group Search and Select"},
	{"eSS.GroupItemDetails.label","Group Item Details"},
	{"eSS.MandatoryItem.label","Mandatory Item"},
		//Added by sakti against BRU-HIMS-CRF-372
	{"eSS.DispatchGroupDetails.label","Dispatch Group Details"},
	//Added by sakti against BRU-HIMS-CRF-372
	{"eSS.AcknowledgeGroupDetails.label","Acknowledge Group Details"},
	
	//Added by sakti against KDAH-CRF-0247
	{"eSS.SurgeryTypeLinkedToOT.label","Surgery Type linked to OT"},
	{"eSS.OTSurgeryName.label","OT Surgery Name"},
	{"eSS.SurgeryName.label","Surgery Name"},
	{"eSS.SurgeryNameShortDesc.label","Surgery Name(Short Desc.)"},
	{"eSS.SurgeryTypeCode.label","Surgery Type(Code)"},
	{"eSS.SurgeryTypeShortDesc.label","Surgery Type(Short Desc.)"},
	{"eSS.SurgeryNameCode.label","Surgery Name(Code)"},
	{"eSS.SurgeryNameShortDesc.label","Surgery Name(Short Desc.)"},
	{"eSS.CSSDSurgeryType.label","CSSD Surgery Type"},
	{"eSS.SurgeryType/Name.label","Surgery Type/Name"},
	{"eSS.NatureType.label","Nature Type"},
	{"eSS.Elective.label","Elective"},
	{"eSS.Emergency.label","Emergency"}, 
	//Added by sakti against BRU-HIMS-CRF-373
	{"eSS.ConsiderGroupsInTargetStore.label","Consider Groups in Target Store"},
	{"eSS.AvailableSterilized.label","Available Sterilized"},
	{"eSS.AuthorizedGroup.label"," Authorized Group"},
	{"eSS.RequestForLoan.label","Request For Loan"},  
	{"eSS.IssueAgainstLoan.label","Issue Against Loan"},
	{"eSS.ReturnOfLoan.label","Return Of Loan"},
	//Added by sakti against BRU-HIMS-CRF-376
	{"eSS.AckRemarks.label","Ack. Remarks"},
	{"eSS.TrayDiscrepancyRemarks.label","Tray Discrepancy Remarks"},
	{"eSS.ReturnRemarks.label","Return Remarks"},
	{"eSS.ReturnDiscrepancyRemarks.label"," Return Discrepancy Remarks"},
	//Added by sakti against BRU-HIMS-CRF-225
	{"eSS.IssueDocNo.label"," Issue Doc No"},
	//Added by sakti against BRU-HIMS-CRF-225.1 Starts
	{"eSS.RejectQuantity.label","Reject Quantity"},
	{"eSS.RequestorName.label","Requestor Name"},
	{"eSS.TimeOfRequest.label","Time Of Request"},
	{"eSS.DiscrepancyRemarks.label","Discrepancy Remarks"},
	{"eSS.ReturnDiscrepancy.label","Return Discrepancy"},
	//Added by sakti against BRU-HIMS-CRF-398 Starts
	{"eSS.Returned.label","Returned"},
	{"eSS.Acknowledged.label","Acknowledged"},
	{"eSS.PendingForAckConfirmation.label", "Pending for Ackn./Confirmation"},
	{"eSS.Rejected.label","Rejected"},
	{"eSS.ReturnedBy.label","Returned By"},
	{"eSS.ReturnDate.label","Return Date"},

	//Added by Sakti against  AAKH_CRF_0057  inc#52312
	{"eSS.BiologicalIndicator.label","Biological Indicator"},
	{"eSS.BMSPassFail.label","BMS Pass / Fail"},
	{"eSS.RoomTemperature.label","Room Temperature"},
	{"eSS.RelativeHumidity.label","Relative Humidity"},
   	{"eSS.NotApplicable.label","Not Applicable"},
	{"eSS.Yes.label","Yes"},
	{"eSS.No.label","No"},
	{"eSS.testdone.label","Test Done"},
	{"eSS.testnotdone.label","Test Not Done"},
	
	//Added ends
//Added by Badmavathi against AAKH-CRF-0057 for Log sheet for test performed on Sterilizer
	{"eSS.AutoclaveTest.label","Autoclave Test"},
	{"eSS.SterileGroup.label","Sterile Group"},//Added by shanal on 27-02-2015 against AAKH-CRF-0057
	//Added by Badmavathi against AAKH-CRF-0057  Inc 51898
	{"eSS.PeriodFromDate.label","Period From Date"},
	{"eSS.ConsiderReprintasOriginal.label","Consider Reprint as Original"},
	{"eSS.PrintAlertRequired.label","Print Alert Required"},
	//Added ends
	{"eSS.PrintDocumentLabel.label", "Print Document"},//Added by suresh.r on 06-04-2015 against Inc 54315
//Added for AAKH-CRF-0058 and inc#51899 By B.Badmavathi on 06-07-2015 
	{"eSS.RequestLoanFromVendor.label", "Request Loan From Vendor"},
	{"eSS.ReturnVendorLoan.label", "Return Vendor Loan"},
	{"eSS.VendorLoan.label", "Vendor Loan"},
//Added ends
//Added by suresh.r on 27-02-2015 against  AAKH-CRF-0058 beg
	{"eSS.RequestedonVendor.label","Requested on Vendor"},
	{"eSS.TotalAvailableQty.label","Total Available Quantity"},
	{"eSS.FromDate.label","From Date"},
	{"eSS.ToDate.label","To Date"},
	{"eSS.Requestedby.label","Requested By"},
	{"eSS.VendorLoanRequest.label","VendorLoanRequest"},
	{"eSS.RequestDocNo.label","Request Doc No"},
	{"eSS.FromVendor.label","From Vendor"},
	{"eSS.RequestFromDate.label","Request From Date"},
	{"eSS.RequestToDate.label","Request To Date"},
	{"eSS.IssueQtyAck.label","Issue Qty"},
	{"eSS.AcknRemarks.label","Acknowledge Remarks"},
	//Added by suresh.r on 27-02-2015 against  AAKH-CRF-0058 end
	//IN056823 Start.
	{"eSS.ToVendor.label","To Vendor"},
	{"eSS.Select.label","Select"},
	{"eSS.VendorLoanRequestDocNo.label","Vendor Loan Request Doc No"},
	{"eSS.VendorLoanRequestDocDate.label","Vendor Loan Request Doc Date"},
	{"eSS.RequestedType.label","Requested Type"},
	{"eSS.SurgeyType.label","Surgey Type"},
	{"eSS.SurgeyName.label","Surgey Name"},
	{"eSS.AckQty.label","Ack Qty"},
	{"eSS.AcknowledgementRemarks.label","Acknowledgement Remarks"},
	//IN056823 End.
	//Added by Badmavathi.B on 08/10/2015 against  AAKH-CRF-0058.1 beg
	{"eSS.Vendor.label","Vendor"},
	{"eSS.RequestOnVendor.label","Request On Vendor"},
	{"eSS.RequestingStore.label","Requesting Store"},
	{"eSS.RequestedSterileGroup.label","Requested Sterile Group"},
	{"eSS.VendorLoanRequestDocDate.label","Vendor Loan Request Doc Date"},
	{"eSS.VendorLoanRequestDocNo.label","Vendor Loan Request Doc No"},
	{"eSS.DocReferenceNo.label","Doc Reference No"},
	{"eSS.Detailed.label","Detailed"},
	//Added by Badmavathi.B on 08/10/2015 against  AAKH-CRF-0058.1 end

	//Added for ML-MMOH-CRF-1821
	{"eSS.Packing.label","Packing Label"},
	{"eSS.InstructionPacking.label","Instruction on Packing Label"},
	{"eSS.PrintPacked.label","Print Packed by in Label"},
	{"eSS.LabelSizeLinenGroupType.label","Label Size for Linen Group Type"},
	{"eSS.LabelSizeSetGroupType.label","Label Size for Set Group Type"},
	{"eSS.LabelSizeSingleGroupType.label","Label Size for Single Group Type"},
	{"eSS.LabelSizeSoftPackGroupType.label","Label Size for Soft Pack Group Type"},
	{"eSS.LabelSizeTraytGroupType.label","Label Size for Tray Group Type"},

	{"eSS.LabelFormat6X9.label","Label 6X9"},
	{"eSS.LabelFormat3X5.label","Label 3X5"},
	{"eSS.AllowMultiGroupTypes.label","Allow Multi Group Types in Sterilization Request"},
	{"eSS.GroupTypeMandatory.label","Group Type mandatory in Sterilization Request"}

	// ML-MMOH-CRF-1821 END
	};
}
