/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eRS.resources;

import java.util.*;

public class Labels_th extends ListResourceBundle
{
	public Object[][] getContents() 
	{
         return contents;
    }

	static final Object[][] contents = 
	{
		{"eRS.GradeLevel.label"," th Grade Level"},
		{"eRS.FTWorkHours.label"," th FT Work Hours"},
		{"eRS.GradeDescription.label"," th Grade Description"},
		{"eRS.GradeCode.label"," th Grade Code"},
		{"eRS.ConsiderForScheduling.label"," th Consider For Scheduling"},
		{"eRS.Level.label"," th Level"},
		{"eRS.ConsiderforScheduling.label"," th Consider for Scheduling"},
		{"eRS.FindGrade.label"," th Find Grade"},
		{"eRS.TrainingCode.label"," th Training Code"},
		{"eRS.FTHours.label"," th FTHours"},
		{"eRS.TrainingDescription.label"," th Training Description"},
		{"eRS.SkillCode.label"," th Skill Code"},
		{"eRS.SkillDescription.label"," th Skill Description"},
		{"eRS.Skill.label"," th Skill"},
		{"eRS.LicenseCode.label"," th License Code"},
		{"eRS.LicenseDescription.label"," th License Description"},
		{"eRS.StaffReviewOption.label"," th Staff Review Option"},
		{"eRS.WorkplaceCode.label"," th Workplace Code"},
		{"eRS.WorkplaceDescription.label"," th Workplace Description"},
		{"eRS.OperatingHours.label"," th Operating Hours"},
		{"eRS.From(hh:mi).label"," th From (hh:mi)"},
		{"eRS.To(hh:mi).label"," th To (hh:mi)"},
		{"eRS.WorkingDays.label"," th Working Days"},
		{"eRS.Non-WorkingDays.label"," th Non-Working Days"},
		{"eRS.Holidays.label"," th Holidays"},
		{"eRS.StaffUtilizationReviewOption.label"," th Staff Utilization Review Option"},
		{"eRS.DependencyBasedFTE.label"," th Dependency Based FTE"},
		{"eRS.FTE.label"," th FTE"},
		{"eRS.StafftoBedRatio.label"," th Staff to Bed Ratio"},
		{"eRS.StafftoPatientRatio.label"," th Staff to Patient Ratio"},
		{"eRS.OperatingDaysApplicabilityfortheWorkCycle.label"," th Operating Days Applicability for the Work Cycle"},
		{"eRS.WDay.label"," th WDay"},
		{"eRS.NWDay.label"," th NWDay"},
		{"eRS.HDay.label"," th HDay"},
		{"eRS.ByPosition.label"," th By Position"},
		{"eRS.BySkill.label"," th By Skill"},
		{"eRS.PositionCode.label"," th Position Code"},
		{"eRS.PositionDescription.label"," th Position Description"},
		{"eRS.StaffType.label"," th Staff Type"},
		{"eRS.Staff.label"," th Staff"},
		{"eRS.SkillForPosition.label"," th Skill For Position"},
		{"eRS.StaffId.label"," th Staff Id"},
		{"eRS.ProficiencyLevel.label"," th Proficiency Level"},
		{"eRS.FromDate.label"," th From-Date"},
		{"eRS.To-Date.label"," th To-Date"},
		{"eRS.TrainingProgram.label"," th Training Program"},
		{"eRS.Organisation.label"," th Organisation"},
		{"eRS.IssueDate.label"," th Issue Date"},
		{"eRS.Grade.label"," th Grade"},
		{"eRS.LicenseType.label"," th License Type"},
		{"eRS.In-house.label"," th In-house"},
		{"eRS.Local.label"," th Local"},
		{"eRS.Overseas.label"," th Overseas"},
		{"eRS.TrainingType.label"," th Training Type"},
		{"eRS.Certified.label"," th Certified"},
		{"eRS.FacilityType.label"," th Facility Type"},
		{"eRS.StaffProfile.label"," th Staff Profile"},
		{"eRS.Skills.label"," th Skills"},
		{"eRS.Experience.label"," th Experience"},
		{"eRS.Training.label"," th Training"},
		{"eRS.PrimarySpecialty.label"," th Primary Specialty"},
		{"eRS.StaffID.label"," th StaffID"},
		{"eRS.StaffName.label"," th Staff Name"},
		{"eRS.License.label"," th License"},
		{"eRS.Visitor.label"," th Visitor"},
		{"eRS.PartTime.label"," th Part Time"},
		{"eRS.FullTime.label"," th Full Time"},
		{"eRS.EmplStatus.label"," th Empl Status"},
		{"eRS.ExperienceDetails.label"," th Experience Details"},
		{"eRS.StaffDetails.label"," th Staff Details"},
		{"eRS.Licensure.label"," th Licensure"},
		{"eRS.ValidUntill.label"," th Valid Untill"},
		{"eRS.Organization.label"," th Organization"},
		{"eRS.StaffOtherDetails.label"," th Staff Other Details"},
		{"eRS.LicensureDetails.label"," th Licensure Details"},
		{"eRS.Issue.label"," th Issue"},
		{"eRS.Specialty.label"," th Specialty"},
		{"eRS.Tel.label"," th Tel"},
		{"eRS.Mobile.label"," th Mobile"},
		{"eRS.PractitionerDetails.label"," th Practitioner Details"},
		{"eRS.OtherStaffDetails.label"," th Other Staff Details"},
		{"eRS.Positions.label"," th Positions"},
		{"eRS.ByWorkplace.label"," th By Workplace"},
		{"eRS.ByStaff.label"," th By Staff"},
		{"eRS.StaffProfileSetup.label"," th StaffProfileSetup"},
		{"eRS.WorkplaceType.label"," th Workplace Type"},
		{"eRS.Proficiency.label"," th Proficiency"},
		{"eRS.SkillDetails.label"," th Skill Details"},
		{"eRS.Program.label"," th Program"},
		{"eRS.StaffForWorkplace.label"," th Staff For Workplace"},
		{"eRS.ShiftPattern.label"," th Shift Pattern"},
		{"eRS.ShiftPatternForWorkplace.label"," th Shift Pattern For Workplace"},
		{"eRS.ByShiftPattern.label"," th By Shift Pattern"},
		{"eRS.ShiftPatternID.label"," th Shift Pattern ID"},
		{"eRS.ShiftPatternDescription.label"," th Shift Pattern Description"},
		{"eRS.FindShiftPatternForWorkplace.label"," th Find Shift Pattern For Workplace"},
		{"eRS.WorkCycle.label"," th Work Cycle"},
		{"eRS.Pattern.label"," th Pattern"},
		{"eRS.Operating.label"," th Operating"},
		{"eRS.FindSkillForPosition.label"," th Find Skill For Position"},
		{"eRS.WorkCycleBasis.label"," th Work Cycle Basis"},
		{"eRS.Shifts.label"," th Shifts"},
		{"eRS.Key.label"," th Key"},
		{"eRS.FindShiftPattern.label"," th Find ShiftPattern"},
		{"eRS.WorkPlaceAllocation.label"," th WorkPlaceAllocation"},
		{"eRS.ViewOptions.label"," th View Options"},
		{"eRS.TotalByWorkPlace.label"," th Total By WorkPlace"},
		{"eRS.TotalByShift.label"," th Total By Shift"},
		{"eRS.TotalByPosition.label"," th Total By Position"},
		{"eRS.WorkplaceAllocationDetails.label"," th WorkplaceAllocation Details"},
		{"eRS.WorkPlaceRequirement.label"," th WorkPlaceRequirement"},
		{"eRS.requirement.label"," th requirement"},
		{"eRS.AllRequirement.label"," th All Requirement"},
		{"eRS.FeatureRequirement.label"," th Feature Requirement"},
		{"eRS.FindRequirement.label"," th Find Requirement"},
		{"eRS.WorkPlaceRequirementQryResult.label"," th WorkPlaceRequirementQryResult"},
		{"eRS.ByRatio.label"," th By Ratio"},
		{"eRS.ByFTE.label"," th By FTE"},
		{"eRS.Opt.label"," th Opt"},
		{"eRS.WDay.label"," th W Day"},
		{"eRS.NWDay.label"," th NW Day"},
		{"eRS.RequirementPeriod.label"," th Requirement Period"},
		{"eRS.FindWorkplace.label"," th Find Workplace"},
		{"eRS.RequirementDescription.label"," th Requirement Description"},
		{"eRS.AllowOverlapofShiftsinaWorkplace.label"," th Allow Overlap of Shifts in a Workplace"},
		{"eRS.PeriodaheadforWorkSchedulecreation.label"," th Period ahead for Work Schedule creation"},
		{"eRS.Maximumcontinuousdurationstaffcanwork.label"," th Maximum continuous duration staff can work"},
		{"eRS.StaffSubstitutionBasis.label"," th Staff Substitution Basis"},
		{"eRS.WithinsameGrade.label"," th Within same Grade"},
		{"eRS.LowtoHighGrade.label"," th Low to High Grade"},
		{"eRS.HightoLowGrade.label"," th High to Low Grade"},
		{"eRS.AttendanceFeatureRequired.label"," th Attendance Feature Required"},
		{"eRS.Maxdurationfromstartofshifttomarkattendance.label"," th Max duration from start of shift to mark attendance"},
		{"eRS.ValidatestaffaccessrightsbyAttendance.label"," th Validate staff access rights by Attendance"},
		{"eRS.ValidatestaffaccessrightsbyWorkSchedule.label"," th Validate staff access rights by Work Schedule"},
		{"eRS.Activitiesallowedonactiveshift.label"," th Activities allowed on active shift"},
		{"eRS.Durationfromstartofshift.label"," th Duration from start of shift"},
		{"eRS.Allocate.label"," th Allocate"},
		{"eRS.Swap.label"," th Swap"},
		{"eRS.Overtime.label"," th Overtime"},
		{"eRS.MaximumContinuousDurationStaffcanworkHours.label"," th Maximum Continuous Duration Staff can work Hours"},
		{"eRS.MaximumContinuousDurationStaffcanworkMinutes.label"," th Maximum Continuous Duration Staff can work Minutes"},
		{"eRS.Re-allocate.label"," th Re-allocate"},
		{"eRS.CancelSch.label"," th Cancel Sch"},
		{"eRS.SetUpReq.label"," th SetUp Req"},
		{"eRS.ShiftIndicator.label"," th Shift Indicator"},
		{"eRS.ProductiveFlag.label"," th Productive Flag"},
		{"eRS.ShiftCode.label"," th Shift Code"},
		{"eRS.ShiftDescription.label"," th Shift Description"},
		{"eRS.Productivity.label"," th Productivity"},
		{"eRS.ShiftsforLocation.label"," th Shifts for Location"},
		{"eRS.ExpiringWithin.label"," th Expiring Within"},
		{"eRS.ShiftTiming.label"," th Shift Timing"},
		{"eRS.ShiftPatternDetails.label"," th Shift Pattern Details"},
		{"eRS.ShiftForWorkplace.label"," th Shift For Workplace"},
		{"eRS.ByShift.label"," th By Shift"},
		{"eRS.RosterDetails.label"," th Roster Details"},
		{"eRS.OncallTimings.label"," th Oncall Timings"},
		{"eRS.ManageWorkSchedule.label"," th Manage Work Schedule"},
		{"eRS.WorkplaceID.label"," th Workplace ID"},
		{"eRS.DurationFrom.label"," th Duration From"},
		{"eRS.StaffType.label"," th Staff Type"},
		{"eRS.LicenseID.label"," th License ID"},
		{"eRS.BelowOptimal.label"," th Below Optimal"},
		{"eRS.Optimal.label"," th Optimal"},
		{"eRS.AboveOptimal.label"," th Above Optimal"},
		{"eRS.ExternelWorkplace(s).label"," th Externel Workplace(s)"},
		{"eRS.Unavailability.label"," th Unavailability"},
		{"eRS.AllocateNewShift.label"," th Allocate New Shift"},
		{"eRS.ViewSchedule.label"," th View Schedule"},
		{"eRS.End.label"," th End"},
		{"eRS.ScheduleDate.label"," th Schedule Date"},
		{"eRS.AlreadyAllocatedShifts.label"," th Already Allocated Shifts"},
		{"eRS.ChangeShift.label"," th Change Shift"},
		{"eRS.AllocatedShifts.label"," th Allocated Shifts"},
		{"eRS.NewShift.label"," th New Shift"},
		{"eRS.SwapShifts.label"," th Swap Shifts"},
		{"eRS.TransferShift.label"," th Transfer Shift"},
		{"eRS.TransferFrom.label"," th Transfer From"},
		{"eRS.TransferTo.label"," th Transfer To"},
		{"eRS.RecordOverTime.label"," th Record OverTime"},
		{"eRS.StaffUnavailability.label"," th Staff Unavailability"},
		{"eRS.LeavePeriod.label"," th Leave Period"},
		{"eRS.CancelShifts.label"," th Cancel Shifts"},
		{"eRS.MasterSchedule.label"," th Master Schedule"},
		{"eRS.AllStaff.label"," th All Staff"},
		{"eRS.AllocatedStaff.label"," th Allocated Staff"},	
		{"eRS.UnproductiveShift.label"," th Unproductive Shift"},
		{"eRS.Unproductive.label"," th Unproductive"},
		{"eRS.WorkingShifts.label"," th Working Shifts"},
		{"eRS.WorkingShift.label"," th Working Shift"},
		{"eRS.OncallShifts.label"," th Oncall Shifts"},
		{"eRS.OncallShift.label"," th Oncall Shift"},
		{"eRS.Oncall.label"," th Oncall"},
		{"eRS.Over.label"," th Over"},			
	   	{"eRS.WorkPlace.label"," th Work Place"},
		{"eRS.MasterScheduleByWorkplaceResultWeeklyFrames.label"," th Master Schedule By Workplace Result Weekly Frames"},
		{"eRS.DateTo.label"," th Date To"},
		{"eRS.GenerateWorkSchedule.label"," th GenerateWorkSchedule"},
		{"eRS.GenerateSchedule.label"," th Generate Schedule"},
		{"eRS.Working.label"," th Working"},
		{"eRS.OverTimeDuration.label"," th OverTime Duration"},
		{"eRS.ReasonforCancellation.label"," th Reason for Cancellation"},
		{"eRS.CancelSchedule.label"," th Cancel Schedule"},
		{"eRS.CancelWorkSchedule.label"," th CancelWorkSchedule"},
		{"eRS.Timings.label"," th Timings"},
		{"eRS.StepIn.label"," th Step In"},
		{"eRS.Fixed.label"," th Fixed"},
		{"eRS.StepOut.label"," th Step Out"},
		{"eRS.Workplace.label"," th Workplace"},
		{"eRS.Requirement.label"," th Requirement"},
		{"eRS.StaffID.label"," th Staff ID"},
		{"eRS.ShowWorkplaces.label"," th Show Workplaces"},
		{"eRS.ShowDetails.label"," th Show Details"},
		{"eRS.GenerateWorkSchedule.label"," th Generate Work Schedule"},
		{"eRS.SwapWith.label"," th Swap With"},
		{"eRS.AllWeeks.label"," th All Weeks"},
		{"eRS.ShowStaff.label"," th Show Staff"},
		{"eRS.ShowShifts.label"," th Show Shifts"},
		{"eRS.UnproductiveShifts.label"," th Unproductive Shifts"},
		{"eRS.ShowShiftPattern.label"," th Show ShiftPattern"},
		{"eRS.ShowSkills.label"," th Show Skills"},
		{"eRS.ShowPositions.label"," th Show Positions"},
		{"eRS.Show Workplace.label"," th Show Workplace"},
		{"eRS.ShowProfile.label"," th Show Profile"},
		{"eRS.SetupRequirement.label"," th Setup Requirement"}
		
		


		};
}

