/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eRS.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eRS.GradeLevel.label","级别"},
//		{"eRS.FTWorkHours.label","FT Work Hours"},
		{"eRS.GradeDescription.label","等级�??述"},
		{"eRS.GradeCode.label","等级代�?"},
		{"eRS.ConsiderForScheduling.label","考虑安排"},
		{"eRS.Level.label","级别"},
		{"eRS.ConsiderforScheduling.label","考虑调度"},
		{"eRS.FindGrade.label","查找等级"},
		{"eRS.TrainingCode.label","培训代�?"},
		{"eRS.FTHours.label","FTHours"},
		{"eRS.TrainingDescription.label","培训说明"},
		{"eRS.SkillCode.label","技能�?"},
		{"eRS.SkillDescription.label","技能说明"},
		{"eRS.Skill.label","技能"},
		{"eRS.LicenseCode.label","授�?��?"},
		{"eRS.LicenseDescription.label","授�?�说明"},
		{"eRS.StaffReviewOption.label","工作人员审查的选择"},
		{"eRS.WorkplaceCode.label","�?�业守则"},
		{"eRS.WorkplaceDescription.label","�?�业�??述"},
		{"eRS.OperatingHours.label","�?作时间"},
		{"eRS.From(hh:mi).label","从"},
		{"eRS.To(hh:mi).label","到"},
		{"eRS.WorkingDays.label","工作日"},
		{"eRS.Non-WorkingDays.label","�?�工作日"},
		{"eRS.Holidays.label","�?�期"},
//		{"eRS.StaffUtilizationReviewOption.label","Staff Utilization Review Option"},
//		{"eRS.DependencyBasedFTE.label","Dependency Based FTE"},
//		{"eRS.FTE.label","FTE"},
//		{"eRS.StafftoBedRatio.label","Staff to Bed Ratio"},
//		{"eRS.StafftoPatientRatio.label","Staff to Patient Ratio"},
//		{"eRS.OperatingDaysApplicabilityfortheWorkCycle.label","Operating Days Applicability for the Work Cycle"},
//		{"eRS.WDay.label","WDay"},
//		{"eRS.NWDay.label","NWDay"},
//		{"eRS.HDay.label","HDay"},
//		{"eRS.ByPosition.label","By Position"},
//		{"eRS.BySkill.label","By Skill"},
		{"eRS.PositionCode.label","�?��?代�?"},
		{"eRS.PositionDescription.label","�?��?类型"},
		{"eRS.StaffType.label","雇员类型"},
		{"eRS.Staff.label","雇员"},
		{"eRS.SkillForPosition.label","�?��?所需技能"},
		{"eRS.StaffId.label","雇员编�?�"},
		{"eRS.ProficiencyLevel.label","水平"},
		{"eRS.FromDate.label","从"},
		{"eRS.To-Date.label","到"},
		{"eRS.TrainingProgram.label","培训计划"},
		{"eRS.Organisation.label","组织"},
		{"eRS.IssueDate.label","�?��?�日期"},
		{"eRS.Grade.label","等级"},
		{"eRS.LicenseType.label","许�?��?类型"},
		{"eRS.In-house.label","在内部"},
		{"eRS.Local.label","地方"},
		{"eRS.Overseas.label","海外"},
		{"eRS.TrainingType.label","培训类型"},
		{"eRS.Certified.label","认�?"},
		{"eRS.FacilityType.label","设备类型"},
		{"eRS.StaffProfile.label","工作人员简介"},
		{"eRS.Skills.label","技能"},
		{"eRS.Experience.label","�?验"},
		{"eRS.Training.label","训练"},
		{"eRS.PrimarySpecialty.label","�?级专业"},
		{"eRS.StaffID.label","雇员编�?�"},
		{"eRS.StaffName.label","雇员姓�??"},
		{"eRS.License.label","授�?��?�"},
		{"eRS.Visitor.label","就诊者"},
		{"eRS.PartTime.label","兼�?�"},
		{"eRS.FullTime.label","全�?�"},
		{"eRS.EmplStatus.label","工作状�?"},
		{"eRS.ExperienceDetails.label","�?验�??述"},
		{"eRS.StaffDetails.label","雇员明细"},
		{"eRS.Licensure.label","执照"},
		{"eRS.ValidUntill.label","有效期至"},
		{"eRS.Organization.label","组织"},
		{"eRS.StaffOtherDetails.label","工作人员的其它细节"},
		{"eRS.LicensureDetails.label","执照详情"},
		{"eRS.Issue.label","问题"},
		{"eRS.Specialty.label","专业"},
		{"eRS.Tel.label","电�?"},
		{"eRS.Mobile.label","移动电�?"},
		{"eRS.PractitionerDetails.label","医生详细信�?�"},
		{"eRS.OtherStaffDetails.label","其它人事细节"},
		{"eRS.Positions.label","�?��?"},
		{"eRS.ByWorkplace.label","通过工作场所"},
		{"eRS.ByStaff.label","�?�工作人员"},
		{"eRS.StaffProfileSetup.label","�?�业简介设置"},
		{"eRS.WorkplaceType.label","�?�业类型"},
		{"eRS.Proficiency.label","熟练"},
		{"eRS.SkillDetails.label","技术细节"},
		{"eRS.Program.label","计划"},
		{"eRS.StaffForWorkplace.label","工作人员的工作场所"},
		{"eRS.ShiftPattern.label","转�?�模�?"},
		{"eRS.ShiftPatternForWorkplace.label","转�?�工作模�?"},
		{"eRS.ByShiftPattern.label","通过转�?�模�?"},
		{"eRS.ShiftPatternID.label","转�?�模�?编�?�"},
		{"eRS.ShiftPatternDescription.label","转�?�模�?说明"},
		{"eRS.FindShiftPatternForWorkplace.label","查找转�?�工作模�?"},
//		{"eRS.WorkCycle.label","Work Cycle"},
		{"eRS.Pattern.label","模�?"},
		{"eRS.Operating.label","�?作"},
		{"eRS.FindSkillForPosition.label","查找技能"},
//		{"eRS.WorkCycleBasis.label","Work Cycle Basis"},
		{"eRS.Shifts.label","移动"},
		{"eRS.Key.label","关键"},
//		{"eRS.FindShiftPattern.label","Find ShiftPattern"},
		{"eRS.WorkPlaceAllocation.label","替代工作场所"},
		{"eRS.ViewOptions.label","查看选项"},
		{"eRS.TotalByWorkPlace.label","总的工作场所"},
		{"eRS.TotalByShift.label","总的转�?�"},
		{"eRS.TotalByPosition.label","总的立场"},
		{"eRS.WorkplaceAllocationDetails.label","替代工作场所细节"},
		{"eRS.WorkPlaceRequirement.label","�?求替代工作场所"},
		{"eRS.requirement.label","�?求"},
		{"eRS.AllRequirement.label","所有�?求"},
		{"eRS.FeatureRequirement.label","功能需求"},
		{"eRS.FindRequirement.label","查找�?求"},
//		{"eRS.WorkPlaceRequirementQryResult.label","WorkPlaceRequirementQryResult"},
//		{"eRS.ByRatio.label","By Ratio"},
//		{"eRS.ByFTE.label","By FTE"},
//		{"eRS.Opt.label","Opt"},
//		{"eRS.WDay.label","W Day"},
//		{"eRS.NWDay.label","NW Day"},
		{"eRS.RequirementPeriod.label","需求时期"},
		{"eRS.FindWorkplace.label","�?�现工作场所"},
		{"eRS.RequirementDescription.label","�?求说明"},
//		{"eRS.AllowOverlapofShiftsinaWorkplace.label","Allow Overlap of Shifts in a Workplace"},
//		{"eRS.PeriodaheadforWorkSchedulecreation.label","Period ahead for Work Schedule creation"},
//		{"eRS.Maximumcontinuousdurationstaffcanwork.label","Maximum continuous duration staff can work"},
//		{"eRS.StaffSubstitutionBasis.label","Staff Substitution Basis"},
		{"eRS.WithinsameGrade.label","�?�一级别"},
		{"eRS.LowtoHighGrade.label","低于高级别"},
		{"eRS.HightoLowGrade.label","高于低级别"},
//		{"eRS.AttendanceFeatureRequired.label","Attendance Feature Required"},
//		{"eRS.Maxdurationfromstartofshifttomarkattendance.label","Max duration from start of shift to mark attendance"},
		{"eRS.ValidatestaffaccessrightsbyAttendance.label","验�?工作人员的访问�?��?"},
		{"eRS.ValidatestaffaccessrightsbyWorkSchedule.label","验�?工作人员的访问�?��?"},
//		{"eRS.Activitiesallowedonactiveshift.label","Activities allowed on active shift"},
//		{"eRS.Durationfromstartofshift.label","Duration from start of shift"},
		{"eRS.Allocate.label","分�?"},
		{"eRS.Swap.label","互�?�"},
		{"eRS.Overtime.label","加�?�"},
		{"eRS.MaximumContinuousDurationStaffcanworkHours.label","�?�员最长�?�以工作的时间"},
		{"eRS.MaximumContinuousDurationStaffcanworkMinutes.label","�?�员最长�?�以工作的时间"},
		{"eRS.Re-allocate.label","�?新分�?"},
		{"eRS.CancelSch.label","�?�消"},
		{"eRS.SetUpReq.label","安装请求"},
		{"eRS.ShiftIndicator.label","轮�?�指标"},
		{"eRS.ProductiveFlag.label","生产樯地"},
		{"eRS.ShiftCode.label","轮�?�代�?"},
		{"eRS.ShiftDescription.label","轮�?��??述"},
		{"eRS.Productivity.label","生产力"},
		{"eRS.ShiftsforLocation.label","轮�?��?置"},
		{"eRS.ExpiringWithin.label","任期"},
		{"eRS.ShiftTiming.label","轮�?�时间"},
		{"eRS.ShiftPatternDetails.label","轮�?�模�?细节"},
		{"eRS.ShiftForWorkplace.label","工作地点的轮�?�"},
		{"eRS.ByShift.label","轮�?�"},
		{"eRS.RosterDetails.label","列入�??册的详细资料"},
		{"eRS.OncallTimings.label","�?�?��?到时间"},
		{"eRS.ManageWorkSchedule.label","管�?�工作时间表"},
		{"eRS.WorkplaceID.label","�?�业编�?�"},
		{"eRS.DurationFrom.label","时间从"},
		{"eRS.StaffType.label","工作人员类型"},
		{"eRS.LicenseID.label","许�?��?编�?�"},
		{"eRS.BelowOptimal.label","下�?�优化"},
		{"eRS.Optimal.label","最优"},
		{"eRS.AboveOptimal.label","上述优化"},
		{"eRS.ExternelWorkplace(s).label","外部工作场所"},
		{"eRS.Unavailability.label","没有"},
		{"eRS.AllocateNewShift.label","分�?新�?�化"},
		{"eRS.ViewSchedule.label","查看附表"},
		{"eRS.End.label","末端"},
		{"eRS.ScheduleDate.label","日期"},
		{"eRS.AlreadyAllocatedShifts.label","已�?分�?的�?�化"},
		{"eRS.ChangeShift.label","改�?�轮�?�"},
		{"eRS.AllocatedShifts.label","分�?轮�?�"},
		{"eRS.NewShift.label","新一轮"},
		{"eRS.SwapShifts.label","�?��?�"},
		{"eRS.TransferShift.label","转�?��?�次"},
		{"eRS.TransferFrom.label","�?��?�"},
		{"eRS.TransferTo.label","转�?�"},
		{"eRS.RecordOverTime.label","加�?�记录"},
//		{"eRS.StaffUnavailability.label","Staff Unavailability"},
		{"eRS.LeavePeriod.label","�?�期间"},
		{"eRS.CancelShifts.label","�?�消轮�?�"},
		{"eRS.MasterSchedule.label","总表"},
		{"eRS.AllStaff.label","所有工作人员"},
		{"eRS.AllocatedStaff.label","分�?工作人员"},
		{"eRS.UnproductiveShift.label","�?�生产性轮�?�"},
		{"eRS.Unproductive.label","�?�生产性"},
		{"eRS.WorkingShifts.label","轮�?�工作"},
		{"eRS.WorkingShift.label","工作轮�?�"},
		{"eRS.OncallShifts.label","�?�?��?到轮�?�"},
		{"eRS.OncallShift.label","�?�?��?到轮�?�"},
		{"eRS.Oncall.label","�?�?��?到"},
		{"eRS.Over.label","超过"},
		{"eRS.WorkPlace.label","工作地点"},
//		{"eRS.MasterScheduleByWorkplaceResultWeeklyFrames.label","Master Schedule By Workplace Result Weekly Frames"},
		{"eRS.DateTo.label","日期"},
		{"eRS.GenerateWorkSchedule.label","生�?工作日程表"},
		{"eRS.GenerateSchedule.label","生�?附表"},
		{"eRS.Working.label","工作"},
		{"eRS.OverTimeDuration.label","加�?�时间"},
		{"eRS.ReasonforCancellation.label","�?�消原因"},
		{"eRS.CancelSchedule.label","�?�消附表"},
		{"eRS.CancelWorkSchedule.label","�?�消工作日程"},
		{"eRS.Timings.label","时�?"},
		{"eRS.StepIn.label","一步"},
		{"eRS.Fixed.label","固定"},
		{"eRS.StepOut.label","走出"},
		{"eRS.Workplace.label","工作场所"},
		{"eRS.Requirement.label","�?求"},
		{"eRS.StaffID.label","�?�业编�?�"},
		{"eRS.ShowWorkplaces.label","显示工作�?�所"},
		{"eRS.ShowDetails.label","显示细节"},
		{"eRS.GenerateWorkSchedule.label","生�?工作日程表"},
		{"eRS.SwapWith.label","互�?�"},
		{"eRS.AllWeeks.label","全周"},
		{"eRS.ShowStaff.label","查看工作人员"},
		{"eRS.ShowShifts.label","查看轮�?�"},
		{"eRS.UnproductiveShifts.label","�?�生产性轮�?�"},
		{"eRS.ShowShiftPattern.label","查看轮�?�模�?"},
		{"eRS.ShowSkills.label","查看技巧"},
		{"eRS.ShowPositions.label","查看�?��?"},
		{"eRS.Show Workplace.label","查看�?�场"},
		{"eRS.ShowProfile.label","查看简介"},
		{"eRS.SetupRequirement.label","安装需求"},
//Newly Added Legends on 21/10/09
		{"eRS.Activitiesallowedonactiveshift.label","�?许有效转�?�"},
{"eRS.AllowOverlapofShiftsinaWorkplace.label","�?许工作地点�?�?"},
{"eRS.AttendanceFeatureRequired.label","出席特�?必填"},
{"eRS.ByFTE.label","通过全�?�"},
{"eRS.ByPosition.label","通过�?置"},
{"eRS.ByRatio.label","通过速率"},
{"eRS.BySkill.label","通过技能"},
{"eRS.DependencyBasedFTE.label","�?�?�基本�?�能"},
{"eRS.Durationfromstartofshift.label","时间从开始转�?�"},
{"eRS.FindShiftPattern.label","查找移们模�?"},
{"eRS.FTE.label","全�?�"},
{"eRS.FTHours.label","全�?��?时数"},
{"eRS.FTWorkHours.label","全�?�工作�?时数"},
{"eRS.HDay.label","特定�?�期"},
{"eRS.MasterScheduleByWorkplaceResultWeeklyFrames.label","通过�?周工作框架建立时间表"},
{"eRS.Maxdurationfromstartofshifttomarkattendance.label","从开始到标志出席的最大时间"},
{"eRS.Maximumcontinuousdurationstaffcanwork.label","开始工作的最大�?续时间"},
{"eRS.NWDay.label","�?�工作日"},
{"eRS.NWDay.label","�?�工作日"},
{"eRS.OperatingDaysApplicabilityfortheWorkCycle.label","适用于工作周期的工作日"},
{"eRS.Opt.label","指定选项"},
{"eRS.PeriodaheadforWorkSchedulecreation.label","今天一段时间的工作安排"},
{"eRS.StaffSubstitutionBasis.label","工作人员替�?�基础"},
{"eRS.StafftoBedRatio.label","工作人员病床比率"},
{"eRS.StafftoPatientRatio.label","工作人员的病人比率"},
{"eRS.StaffUnavailability.label","工作人员利用率"},
{"eRS.StaffUtilizationReviewOption.label","工作人员利用回顾�?作"},
{"eRS.WDay.label","指定�?周一天"},
{"eRS.WDay.label","指定�?周一天"},
{"eRS.WorkCycle.label","工作周期"},
{"eRS.WorkCycleBasis.label","工作周期基础"},
{"eRS.WorkPlaceRequirementQryResult.label","工作人员的具体�?求"},


};
}
