
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteHomeInterfacePlugin from eCP.PositionForIntervention.PositionForInterventionManager
package eCP.PositionForIntervention;

/**
 * Home interface for PositionForIntervention
 */
public interface PositionForInterventionHome
extends javax.ejb.EJBHome {
    public static final String COMP_NAME = "java:comp/env/ejb/PositionForInterventionRemote";
    public static final String JNDI_NAME = "PositionForInterventionRemote";

    eCP.PositionForIntervention.PositionForInterventionRemote create() throws javax.ejb.CreateException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
