
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eCP.BuildLibrary.BuildLibraryManager
package eCP.BuildLibrary;

/**
 * Remote interface for BuildLibrary
 */
public interface BuildLibraryRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap AddModify(java.util.Properties properties, java.util.HashMap hashtable) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
