/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eOP.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
//		{"eOP.AcctDepartmentService.label","Acct Department/Service"},
//		{"eOP.addvisit.label","Add Visit"},
//		{"eOP.AllowAppointment.label","Allow Appointment"},
//		{"eOP.AllowConsultationOn.label","Allow Consultation On"},
//		{"eOP.AllowNonReferral.label","Allow Non-Referral"},
//		{"eOP.AllowReferral.label","Allow Referral"},
//		{"eOP.AllowVisitRegistration.label","Allow Visit Registration"},
//		{"eOP.AllowVisitRegWaitListInvwithoutAppt.label","Allow Visit Registration for Wait List Invitations without Appointment"},
//		{"eOP.AllowWalkin.label","Allow Walk-in"},
//		{"eOP.AlwVstRegForEmerSerPatients.label","Allow Visit Regn For Emergency Series Patients"},
//		{"eOP.ApplicableVisitTypeIndicator.label","Applicable Visit Type Indicator"},
//		{"eOP.ApplicableVisitTypeIndicators.label","Applicable Visit Type Indicators"},
		{"eOP.AppStatusOnTime.label","按时"},
		{"eOP.apptlist.label","预约列表"},
		{"eOP.apptstatus.label","预约状�?"},
//		{"eOP.ApptStatusEarly.label","Early"},
//		{"eOP.ApptStatusLate.label","Late"},
//		{"eOP.ApptStatusYettoCome.label","Yet to Come"},
//		{"eOP.ApptWalkin.label","Appointment / Walk-in"},
		{"eOP.arrived.label","抵达"},
		{"eOP.ArrivedAtNursStn.label","�?�到护�?�站"},
		{"eOP.AssignedQueues.label","分�?队列"},
		{"eOP.assignpractitioner.label","分�?医生"},
		{"eOP.AssignReAssign.label","分�?/�?新分�?"},
//		{"eOP.AtLocation.label","At Location"},
//		{"eOP.Attended.label","Attended"},
//		{"eOP.AutocloseEpisodes.label","Auto-close Episodes"},
		{"eOP.AutoCloseVisit.label","自动关闭就诊"},
		{"eOP.AutoComplete.label","自动完�?"},
		{"eOP.AutoCompleteVisits.label","自动结�?�就诊"},
//		{"eOP.AutoCompletionofincompletevisits.label","Auto Completion of incomplete visits"},
//		{"eOP.Autopsy.label","Autopsy"},
//		{"eOP.BaseSlotSlabTime.label","Base Slot/Slab Time"},
		{"eOP.BillingParameters.label","账�?��?�数"},
//		{"eOP.ByLocations.label","By Locations"},
//		{"eOP.ByServices.label","By Services"},
		{"eOP.ByVisitType.label","就诊类型"},
//		{"eOP.CaseDefinitions.label","Case Definitions"},
//		{"eOP.CheckedIn.label","Checked-In"},
//		{"eOP.Checked-inAt.label","Checked-in At"},
///		{"eOP.CheckinatIdentification.label","Check-in at Identification"},
	//	{"eOP.CheckinIdentification.label","Check-in Identification"},
	//	{"eOP.ClosureRuleMinelapseddaysfromlastvisit.label","Closure Rule - Min elapsed days from last visit"},
//		{"eOP.ComeBack.label","Come Back"},
//		{"eOP.ConcludeEpisode.label","Conclude Episode"},
//		{"eOP.ConsultationInProgress.label","Consultation In Progress"},
//		{"eOP.Controls.label","Controls"},
//		{"eOP.Coronerrelease.label","Coroner release"},
//		{"eOP.Cu-offDatewithoutFollowup.label","Cu-off Datewithout Followup"},
//		{"eOP.CurrentStatus.label","Current Status"},
//		{"eOP.currentSystemDate.label","Current System Date"},
//		{"eOP.CurrentVisit.label","Current Visit"},
//		{"eOP.CutoffDate.label","Cutoff Date"},
//		{"eOP.CutoffDateforAutoCloseEpisodes.label","Cutoff Datefor Auto Close Episodes"},
//		{"eOP.CutoffDateforAutoCompleteVisits.label","Cutoff Datefor Auto Complete Visits"},
//		{"eOP.CutoffDatewithFollowup.label","Cutoff Datewith Followup"},
//		{"eOP.DateTimeofReleases.label","Date Timeof Releases"},
///		{"eOP.DateTimeOfVisit.label","Date Time Of Visit"},
	//	{"eOP.DeathCertificateSigned.label","Death Certificate Signed"},
	//	{"eOP.DeceasedChecklist.label","Deceased Checklist"},
//		{"eOP.DelinkReferral.label","Delink Referral"},
//		{"eOP.Departed.label","Departed"},
		{"eOP.DepartmentDescription.label","部门�??述"},
//		{"eOP.DispDateTime.label","Disposition Date/Time"},
		{"eOP.EarliestApptDate.label","最早预约日期"},
//		{"eOP.EpisodeNotes.label","Episode Notes"},
//		{"eOP.EpisodeNoVisitNo.label","Episode No / Visit No"},
//		{"eOP.Episodes.label","Episodes"},
//		{"eOP.EpisodeVisitDetails.label","Episode Visit Details"},
		{"eOP.FileCurrentLocation.label","文件当�?�?置"},
		{"eOP.Filedoesnotexist.label","文件�?存在"},
		{"eOP.FirstTimeArrival.label","第一时间到达"},
//		{"eOP.ForMonthYear.label","For Month/Year"},
		{"eOP.ForSpecifiedService.label","专业�?务"},
//		{"eOP.FuneralHomeRelease.label","Funeral Home Release"},
//		{"eOP.IncludeCheckedoutPatients.label","Include Checked-out Patients"},
//		{"eOP.IncludeNoShow.label","Include No Show"},
//		{"eOP.InitChkUpORVtlSgnRec.label","Initial Check-Up/Vital Signs Recorded"},
//		{"eOP.IntheEventofDeath.label","In the Event of Death"},
//		{"eOP.InvitationPeriod.label","Invitation Period"},
//		{"eOP.ItemBatchResult.label","Item Batch Result"},
		{"eOP.LastVisitDate.label","最�?�就诊日期"},
//		{"eOP.LocationTypeDescription.label","Location Type Description"},
//		{"eOP.MaxApptDuration.label","Max Appt Duration"},
//		{"eOP.MaxApptSlots.label","Max Appt Slots"},
//		{"eOP.MaxNoofdaysforvisitcompletion.label","Max No of days for visit completion"},
//		{"eOP.MaxNoofdaysforvisitreviscancel.label","Max No of days for visit revising/cancelling"},
//		{"eOP.Minafterappointmenttime.label","Min after appointment time"},
///		{"eOP.Minbeforeappointmenttime.label","Min before appointment time"},
//		{"eOP.Minimumdayselapsedfromlastvisit.label","Minimum days elapsed from last visit"},
//		{"eOP.MovementDateTime.label","Movement Date/Time"},
//		{"eOP.MovementReason.label","Movement Reason"},
//		{"eOP.MovementType.label","Movement Type"},
//		{"eOP.MRN.label","MRN"},
//		{"eOP.NewEpisode.label","New Episode"},
//		{"eOP.NoFollowup.label","No Follow-up"},
//		{"eOP.NoRecords.label","No Records"},
//		{"eOP.NoshowApptstatus.label","No-show Appointment status If check-in is not within"},
//		{"eOP.notattended.label","Not Attended"},
//		{"eOP.NotCheckedOut.label","Not Checked Out"},
//		{"eOP.NotIdentifiable.label","Not Identifiable"},
//		{"eOP.NumberStart.label","Number Start"},
//		{"eOP.OntimeAppointmentstatusIfcheckinisatleast.label","On-time Appointment status If check-in is at least"},
//		{"eOP.OpenEpisodes.label","Open Episodes"},
//		{"eOP.OpentoallResources.label","Open to all Resources"},
//		{"eOP.OperatingTime.label","Operating Time"},
//		{"eOP.OrderableCriteria.label","Orderable Criteria"},
//		{"eOP.OrderCatalogNo.label","Order Catalog No"},
//		{"eOP.OrganDonors.label","Organ Donors"},
//		{"eOP.OtherResource.label","Other Resource"},
//		{"eOP.OtherResourceID.label","Other Resource ID"},
/*		{"eOP.otherrestype.label","Other Resource Type"},
		{"eOP.OutpatientEpisodes.label","Outpatient Episodes"},
		{"eOP.OverrideVisitTypecontrolonEpisode.label","Override Visit Type control on Episode"},
		{"eOP.PractitionerRoomPrivileges.label","Practitioner/Room Privileges"},
		{"eOP.PrimaryResourceClass.label","Primary Resource Class"},
		{"eOP.PrimaryResourceType.label","Primary Resource Type"},
		{"eOP.PrintAppointmentSlip.label","Print Appointment Slip"},
		{"eOP.PrintReferralLetter.label","Print Referral Letter"},
		{"eOP.PriorLocation.label","Prior Location"},
		{"eOP.ProcedureUnitCode.label","Procedure Unit Code"},
		{"eOP.ProcedureUnitDescription.label","Procedure Unit Description"},
		{"eOP.ProcedureUnitForClinic.label","Procedure Unit For Clinic"},
		{"eOP.ProcedureUnitType.label","Procedure Unit Type"},
		{"eOP.QueueID.label","Queue ID"},
		{"eOP.QueuePrefix.label","Queue Prefix"},
		{"eOP.ReasonForMovement.label","Reason For Movement"},
		{"eOP.ReasonForReviseVisit.label","Reason For Revise Visit"},
		{"eOP.reassignpractitioner.label","Re-Assign Practitioner"},
		{"eOP.RecallDetails.label","Recall Details"},
		{"eOP.recordvitalsigns.label","Record Vital Signs"},
		{"eOP.ReferralDestination.label","Referral Destination"},
		{"eOP.ReferralfoConsult.label","Referral for Consult"},
		{"eOP.Referrals.label","Referrals"},
		{"eOP.ReferralSourceCode.label","Referral Source Code"},
		{"eOP.RegnDateTime.label","Registration Date/Time"},
		{"eOP.RegnTime.label","Regn Time"},
		{"eOP.ResetNumber.label","Reset Number"},
		{"eOP.ResourceClassType.label","Resource Class/Type"},
		{"eOP.ResourceCriteria.label","Resource Criteria"},
		{"eOP.ResourcePrivileges.label","Resource Privileges"},
		{"eOP.ResourceTypeDescription.label","ResourceType Description"},
		{"eOP.ResourceUnit.label","Resource Unit"},
		{"eOP.RetFrmInvest.label","Returned from Investigation"},
		{"eOP.ReverttoCheckin.label","Revert to Check in"},
		{"eOP.RoomDescription.label","Room Description"},
		{"eOP.Seen.label","Seen"},
		{"eOP.SelectUnassignedPatients.label","Select Unassigned Patients"},
		{"eOP.StartNumber.label","Start Number"},
		{"eOP.StartofConsultation.label","Start of Consultation"},
		{"eOP.Statistic.label","Statistic"},
		{"eOP.StatisticsbyLocation.label","Statistics By Location"},
		{"eOP.StatisticsbyService.label","Statistics By Service"},
		{"eOP.StatisticsDate.label","Statistics Date"},
		{"eOP.StatisticsDateFrom.label","Statistics Date From"},
		{"eOP.StatisticsDateTo.label","Statistics Date To"},
		{"eOP.StatisticsMonthYear.label","Statistics Month/Year"},
		{"eOP.SubServiceCode.label","Sub-Service Code"},
		{"eOP.SystemCheckedOut.label","System Checked Out"},
		{"eOP.TabList.label","Tab List"},
		{"eOP.todayapptfor.label","Today's Appointments For"},
		{"eOP.UndergoingTrtORInvst.label","Undergoing Treatment/Investigation"},
		{"eOP.ValuablesReleased.label","Valuables Released"},
		{"eOP.VisitCompletion.label","Visit Completion"},
		{"eOP.VisitDue.label","Visit Due"},
		{"eOP.VisitDueDate.label","Visit Due Date"},
		{"eOP.VisitingPractitioner.label","Visiting Practitioner"},
		{"eOP.VisitNo.label","Visit No"},
		{"eOP.Visits.label","Visits"},
		{"eOP.VisitTypeIndicator.label","Visit Type Indicator"},
		{"eOP.Vital.label","Vital"},
		{"eOP.VitalSignRecorded.label","Vital Signs Recorded"},
		{"eOP.VitalSignsNursingMeasures.label","Vital Signs/ Nursing Measures"},
		{"eOP.Wait.label","Wait"},
		{"eOP.Walkins.label","Walk-ins"},
		{"eOP.WeekApplicable.label","Week Appllicable"},
		{"eOP.WorkingWeeksAppl.label","Working Weeks Appl"},
		{"eOP.Arrivedat.label","Arrived at"},
		{"eOP.Departedto.label","Departed to"},
		{"eOP.ToComeBackAfter.label","To Come Back After"},
		{"eOP.ViewPatientMovement.label","View Patient Movement"},
		{"eOP.QueueNumberingControls.label","Queue Numbering Controls"},
		{"eOP.NumberingApplicable.label","Numbering Applicable"},
		{"eOP.DiagnosisForThisEncounter.label","Diagnosis For This Encounter"},
		{"eOP.DispositionDetails.label","Disposition Details"},
		{"eOP.VS.label","VS"},
		{"eOP.PR.label","PR"},
		{"eOP.TR.label","TR"},
		{"eOP.WT.label","WT"},
		{"eOP.XT.label","XT"},
		{"eOP.QN.label","QN"},
		{"eOP.NS.label","NS"},
		{"eOP.VisitComplWithPract.label","Visit Completion with Practitioner"},
		{"eOP.AllowInvitationNo.label","Allow Invitation No"},
		{"eOP.OPBatchProcess.label","OP Batch Process"},
		{"eOP.AssignQueueNumberby.label","Assign Queue Number by"},
		{"eOP.OverrideWalkIn.label","Override Walk-In"},
		{"eOP.MaxWalkinPerDay.label","Max Walk-In Per Day"},
		{"eOP.OverridePractForAppt.label","Override Practitioner for Appointment Case"},
		{"eOP.MRSectionFileStorage.label","MR Section/File Storage"},
		{"eOP.AlwVstRegForInPatients.label","Allow Visit Registration for Inpatient"},
		{"eOP.InvokeVisRegnFromCA.label","Invoke Visit Registration/Manage Patient Queue from CA"},
		{"eOP.TotalUnclosedVisits.label","Total Unclosed Visits"},
		{"eOP.TotalAutoCloseVisits.label","Total Visits for Auto Close"},
		{"eOP.TotalManualVisits.label","Total Visits for Manual Close"},
		{"eOP.FollowUpVisitDuratin.label","Duration for Follow-up Visit"},
		{"eOP.NoofFollowUpVisitAllowed.label","No of Follow-up Visits Allowed"},
		{"eOP.VisitBackDays.label","Visit Backdate Days"},
		{"eOP.StatisticsBySplty.label","Statistics By Speciality"}*/
// Newly Added legends on 21/01/09
{"eOP.AcctDepartmentService.label","会计部门/�?务"},
{"eOP.addvisit.label","新增就诊病人"},
{"eOP.AllowAppointment.label","�?许预约"},
{"eOP.AllowConsultationOn.label","�?许就诊"},
{"eOP.AllowInvitationNo.label","�?许就诊�?�"},
{"eOP.AllowNonReferral.label","�?许�?�推�??"},
{"eOP.AllowReferral.label","�?许推�??"},
{"eOP.AllowVisitRegistration.label","�?许注册病人"},
{"eOP.AllowVisitRegWaitListInvwithoutAppt.label","未�?许未预约的病人就诊"},
{"eOP.AllowWalkin.label","�?许病人�?时就诊"},
{"eOP.AlwVstRegForEmerSerPatients.label","�?许登记急诊病人"},
{"eOP.AlwVstRegForInPatients.label","�?许登记�?院病人"},
{"eOP.ApplicableVisitTypeIndicator.label","适用的就诊类型指标"},
{"eOP.ApplicableVisitTypeIndicators.label","适用的就诊类型指标"},
{"eOP.ApptStatusEarly.label","早的"},
{"eOP.ApptStatusLate.label","迟的"},
{"eOP.ApptStatusYettoCome.label","尚未到达"},
{"eOP.ApptWalkin.label","预约/�?时"},
{"eOP.Arrivedat.label","到达时间"},
{"eOP.AssignQueueNumberby.label","是�?��?许分�?队列�?�"},
{"eOP.AtLocation.label","指定�?个�?置"},
{"eOP.Attended.label","病人总数"},
{"eOP.AutocloseEpisodes.label","Auto-close Episodes"},
{"eOP.AutoCompletionofincompletevisits.label","自动完�?未完�?就诊的病人"},
{"eOP.Autopsy.label","死�?�"},
{"eOP.BaseSlotSlabTime.label","基准时间"},
{"eOP.ByLocations.label","通过�?置"},
{"eOP.ByServices.label","通过�?务"},
{"eOP.CaseDefinitions.label","病例定义"},
{"eOP.CheckedIn.label","入区"},
{"eOP.Checked-inAt.label","入区时间"},
{"eOP.CheckinatIdentification.label","入区鉴定"},
{"eOP.CheckinIdentification.label","入区鉴定"},
{"eOP.ClosureRuleMinelapseddaysfromlastvisit.label","关闭规律-上次就诊�?�的最�?天数"},
{"eOP.ComeBack.label","�?诊日期"},
{"eOP.ConcludeEpisode.label","结�?�事件"},
{"eOP.ConsultationInProgress.label","就诊进行中"},
{"eOP.Controls.label","控制"},
{"eOP.Coronerrelease.label","验尸官�?�布"},
{"eOP.Cu-offDatewithoutFollowup.label","�?诊截止日期"},
{"eOP.CurrentStatus.label","当�?状�?"},
{"eOP.currentSystemDate.label","当�?系统日期"},
{"eOP.CurrentVisit.label","当�?就诊"},
{"eOP.CutoffDate.label","截止日期"},
{"eOP.CutoffDateforAutoCloseEpisodes.label","自动结�?�的截止日期"},
{"eOP.CutoffDateforAutoCompleteVisits.label","自动完�?就诊的截止日期"},
{"eOP.CutoffDatewithFollowup.label","�?诊的截止日期"},
{"eOP.DateTimeofReleases.label","�?�布日期时间"},
{"eOP.DateTimeOfVisit.label","病人就诊日期/时间"},
{"eOP.DeathCertificateSigned.label","签署死亡�?明书"},
{"eOP.DeceasedChecklist.label","病人死亡清�?�列表"},
{"eOP.DelinkReferral.label","去除链接"},
{"eOP.Departed.label","Departed"},
{"eOP.Departedto.label","�?往�?置"},
{"eOP.DiagnosisForThisEncounter.label","诊断"},
{"eOP.DispDateTime.label","处�?�日期/时间"},
{"eOP.DispositionDetails.label","处�?�明细"},
{"eOP.EpisodeNotes.label","案例备注"},
{"eOP.EpisodeNoVisitNo.label","就诊�?�"},
{"eOP.Episodes.label","一组案例"},
{"eOP.EpisodeVisitDetails.label","特殊就诊的明细显示"},
{"eOP.FollowUpVisitDuratin.label","�?诊周期"},
{"eOP.ForMonthYear.label","�?月报告标准"},
{"eOP.FuneralHomeRelease.label","�?��?到殡仪馆"},
{"eOP.IncludeCheckedoutPatients.label","包括出区病人"},
{"eOP.IncludeNoShow.label","包括显示标准�?�"},
{"eOP.InitChkUpORVtlSgnRec.label","�?始评估记录"},
{"eOP.IntheEventofDeath.label","死亡事件"},
{"eOP.InvitationPeriod.label","就诊期"},
{"eOP.InvokeVisRegnFromCA.label","从CA中引用登记/管�?�病人队列"},
{"eOP.ItemBatchResult.label","项目批次结果"},
{"eOP.LocationTypeDescription.label","�?置类型�??述"},
{"eOP.MaxApptDuration.label","最大预约周期"},
{"eOP.MaxApptSlots.label","最大预约间隔"},
{"eOP.MaxNoofdaysforvisitcompletion.label","最大就诊完�?�?�"},
{"eOP.MaxNoofdaysforvisitreviscancel.label","修改/�?�消的最大就诊�?�"},
{"eOP.MaxWalkinPerDay.label","�?天临时就诊病人"},
{"eOP.Minafterappointmenttime.label","Min after appointment time"},
{"eOP.Minbeforeappointmenttime.label","Min before appointment time"},
{"eOP.Minimumdayselapsedfromlastvisit.label","上次就诊�?�到目�?的最�?天数"},
{"eOP.MovementDateTime.label","病人转移日期/时间"},
{"eOP.MovementReason.label","病人转移原因"},
{"eOP.MovementType.label","病人转移"},
{"eOP.MRN.label","病历�?�"},
{"eOP.MRSectionFileStorage.label","病历科室/存储�?置"},
{"eOP.NewEpisode.label","新增"},
{"eOP.NoFollowup.label","�?诊�?�"},
{"eOP.NoofFollowUpVisitAllowed.label","�?许�?诊�?�"},
{"eOP.NoRecords.label","记录�?�"},
{"eOP.NoshowApptstatus.label","如果未入区,�?显示预约"},
{"eOP.notattended.label","未就诊"},
{"eOP.NotCheckedOut.label","未出区状�?"},
{"eOP.NotIdentifiable.label","�?能确定"},
{"eOP.NS.label","护�?�站"},
{"eOP.NumberingApplicable.label","适用编�?"},
{"eOP.NumberStart.label","开始�?�"},
{"eOP.OntimeAppointmentstatusIfcheckinisatleast.label","如果入区,按时预约状�?"},
{"eOP.OPBatchProcess.label","门诊批处�?�"},
{"eOP.OpenEpisodes.label","打开"},
{"eOP.OpentoallResources.label","打开所有资�?"},
{"eOP.OperatingTime.label","�?行时间"},
{"eOP.OrderableCriteria.label","医嘱标准"},
{"eOP.OrderCatalogNo.label","医嘱分类�?�"},
{"eOP.OrganDonors.label","器官�??赠�??�?�"},
{"eOP.OtherResource.label","其他资�?"},
{"eOP.OtherResourceID.label","其他资�?代�?"},
{"eOP.otherrestype.label","其他资�?类型"},
{"eOP.OutpatientEpisodes.label","门诊事件"},
{"eOP.OverridePractForAppt.label","Override Practitioner for Appointment Case"},
{"eOP.OverrideVisitTypecontrolonEpisode.label","Override Visit Type control on Episode"},
{"eOP.OverrideWalkIn.label","Override Walk-In"},
{"eOP.PR.label","PR"},
{"eOP.PractitionerRoomPrivileges.label","医生/房间�?��?"},
{"eOP.PrimaryResourceClass.label","主�?资�?分类"},
{"eOP.PrimaryResourceType.label","主�?资�?类型"},
{"eOP.PrintAppointmentSlip.label","打�?�预约间隔"},
{"eOP.PrintReferralLetter.label","打�?�推�??信"},
{"eOP.PriorLocation.label","之�?�?置"},
{"eOP.ProcedureUnitCode.label","就诊�?��?编�?"},
{"eOP.ProcedureUnitDescription.label","就诊�?��?�??述"},
{"eOP.ProcedureUnitForClinic.label","临诊就诊�?��?"},
{"eOP.ProcedureUnitType.label","就诊�?��?类型"},
{"eOP.QN.label","QN"},
{"eOP.QueueID.label","�?列�?�"},
{"eOP.QueueNumberingControls.label","�?列数控制"},
{"eOP.QueuePrefix.label","�?列�?缀"},
{"eOP.ReasonForMovement.label","转诊原因"},
{"eOP.ReasonForReviseVisit.label","修改就诊原因"},
{"eOP.reassignpractitioner.label","�?分�?医生"},
{"eOP.RecallDetails.label","记录明细"},
{"eOP.recordvitalsigns.label","记录生命体�?"},
{"eOP.ReferralDestination.label","转诊目的"},
{"eOP.ReferralfoConsult.label","转诊咨询"},
{"eOP.Referrals.label","推�??标准"},
{"eOP.ReferralSourceCode.label","推�??资�?代�?"},
{"eOP.RegnDateTime.label","登记日期/时间"},
{"eOP.RegnTime.label","登记时间"},
{"eOP.ResetNumber.label","�?置数�?"},
{"eOP.ResourceClassType.label","资�?分类/类型"},
{"eOP.ResourceCriteria.label","资�?标准"},
{"eOP.ResourcePrivileges.label","分�?资�?�?��?"},
{"eOP.ResourceTypeDescription.label","资�?类型�??述"},
{"eOP.ResourceUnit.label","资�?�?��?"},
{"eOP.RetFrmInvest.label","从调查返回"},
{"eOP.ReverttoCheckin.label","�?入区"},
{"eOP.RoomDescription.label","房间�??述"},
{"eOP.Seen.label","查看/核对"},
{"eOP.SelectUnassignedPatients.label","选择未分�?病人"},
{"eOP.StartNumber.label","开始�?�"},
{"eOP.StartofConsultation.label","就诊开始"},
{"eOP.Statistic.label","统计"},
{"eOP.StatisticsbyLocation.label","从�?置统计"},
{"eOP.StatisticsbyService.label","从�?务统计"},
{"eOP.StatisticsBySplty.label","从科室统计"},
{"eOP.StatisticsDate.label","统计日期"},
{"eOP.StatisticsDateFrom.label","开始统计日期"},
{"eOP.StatisticsDateTo.label","结�?�统计日期"},
{"eOP.StatisticsMonthYear.label","统计 月/年"},
{"eOP.SubServiceCode.label","�?�?务代�?"},
{"eOP.SystemCheckedOut.label","系统推出"},
{"eOP.TabList.label","标签"},
{"eOP.ToComeBackAfter.label","返回"},
{"eOP.todayapptfor.label","当天预约"},
{"eOP.TotalAutoCloseVisits.label","自动关闭就诊"},
{"eOP.TotalManualVisits.label","手动关闭就诊"},
{"eOP.TotalUnclosedVisits.label","总的未关闭就诊"},
{"eOP.TR.label","TR"},
{"eOP.UndergoingTrtORInvst.label","接收治疗/调查"},
{"eOP.ValuablesReleased.label","Valuables Released"},
{"eOP.ViewPatientMovement.label","�?览病人动�?�"},
{"eOP.VisitBackDays.label","就诊�?�追溯日期"},
{"eOP.VisitCompletion.label","完�?就诊"},
{"eOP.VisitComplWithPract.label","医生完�?就诊"},
{"eOP.VisitDue.label","访问截止"},
{"eOP.VisitDueDate.label","访问截止日期"},
{"eOP.VisitingPractitioner.label","就诊医生"},
{"eOP.VisitNo.label","就诊�?�"},
{"eOP.Visits.label","就诊"},
{"eOP.VisitTypeIndicator.label","就诊类型指�?"},
{"eOP.Vital.label","�?�?"},
{"eOP.VitalSignRecorded.label","生命体�?记录"},
{"eOP.VitalSignsNursingMeasures.label","生命体�?/护�?�记录"},
{"eOP.VS.label","生命体�?"},
{"eOP.Wait.label","检查过程中"},
{"eOP.Walkins.label","Walk-ins"},
{"eOP.WeekApplicable.label","Week Appllicable"},
{"eOP.WorkingWeeksAppl.label","Working Weeks Appl"},
{"eOP.WT.label","等待时间"},
{"eOP.XT.label","XT"},


};
}
