/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eOP.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
		{"eOP.AcctDepartmentService.label","اداره الحساب / الخدمة"},
{"eOP.addvisit.label","أضف زيارة"},
{"eOP.AllowAppointment.label","السماح بالمواعيد"},
{"eOP.AllowConsultationOn.label","السماح بالتشاور"},
{"eOP.AllowNonReferral.label","السماح بعدم الإحالة"},
{"eOP.AllowReferral.label","السماح بالإحالة"},
{"eOP.AllowVisitRegistration.label","السماح بتسجيل الزيارة"},
{"eOP.AllowVisitRegWaitListInvwithoutAppt.label","السماح بتسجيل الزيارة لدعوات قائمة الانتظار بدون موعد"},
{"eOP.AllowWalkin.label","السماح بالدخول"},
{"eOP.AlwVstRegForEmerSerPatients.label","السماح بزيارة Regn لمرضى سلسلة الطوارئ"},
{"eOP.ApplicableVisitTypeIndicator.label","مؤشر نوع الزيارة المطبق"},
{"eOP.ApplicableVisitTypeIndicators.label","مؤشرات نوع الزيارة المطبقة"},
{"eOP.AppStatusOnTime.label","في الوقت المحدد"},
{"eOP.apptlist.label","قائمة المواعيد"},
{"eOP.apptstatus.label","حالة التعيين"},
{"eOP.ApptStatusEarly.label","مبكرا"},
{"eOP.ApptStatusLate.label","متأخر"},
{"eOP.ApptStatusYettoCome.label","سيأتي"},
{"eOP.ApptWalkin.label","التعيين / الحضور"},
{"eOP.arrived.label","وصل"},
{"eOP.ArrivedAtNursStn.label","وصل إلى كاونتر التمريض"},
{"eOP.AssignedQueues.label","قوائم الانتظار المعينة"},
{"eOP.assignpractitioner.label","تعيين ممارس"},
{"eOP.AssignReAssign.label","تعيين / إعادة التعيين"},
{"eOP.AtLocation.label","في الموقع"},
{"eOP.Attended.label","حضرها"},
{"eOP.AutocloseEpisodes.label","حلقات الإغلاق التلقائي"},
{"eOP.AutoCloseVisit.label","زيارة الإغلاق التلقائي"},
{"eOP.AutoComplete.label","الإكمال التلقائي"},
{"eOP.AutoCompleteVisits.label","زيارات الإكمال التلقائي"},
{"eOP.AutoCompletionofincompletevisits.label","الإكمال التلقائي للزيارات غير المكتملة"},
{"eOP.Autopsy.label","تشريح الجثة"},
{"eOP.BaseSlotSlabTime.label","وقت الفتره الزمنيه"},
{"eOP.BillingParameters.label","معلمات الفواتير"},
{"eOP.ByLocations.label","حسب المواقع"},
{"eOP.ByServices.label","حسب الخدمات"},
{"eOP.ByVisitType.label","حسب نوع الزيارة"},
{"eOP.CaseDefinitions.label","تعريفات الحالة"},
{"eOP.CheckedIn.label","تم تسجيل الوصول"},
{"eOP.Checked-inAt.label","تم تسجيل الوصول في"},
{"eOP.CheckinatIdentification.label","تحقق في الهوية"},
{"eOP.CheckinIdentification.label","تعريف الهويه عند تسجيل الوصول"},
{"eOP.ClosureRuleMinelapseddaysfromlastvisit.label","قاعدة الإغلاق - الحد الأدنى من الأيام المنقضية من آخر زيارة"},
{"eOP.ComeBack.label","عد"},
{"eOP.ConcludeEpisode.label","اختتم الحلقة"},
{"eOP.ConsultationInProgress.label","الكشف لا زال قيد التنفيذ"},
{"eOP.Controls.label","ضوابط"},
{"eOP.Coronerrelease.label","الافراج عن الطبيب الشرعي"},
{"eOP.Cu-offDatewithoutFollowup.label","الموعد النهائي بدون متابعة"},
{"eOP.CurrentStatus.label","الحالة الحالية"},
{"eOP.currentSystemDate.label","تاريخ النظام الحالي"},
{"eOP.CurrentVisit.label","الزيارة الحالية"},
{"eOP.CutoffDate.label","تعدى التاريخ"},
{"eOP.CutoffDateforAutoCloseEpisodes.label","قطع التاريخ لحلقات الإغلاق التلقائي"},
{"eOP.CutoffDateforAutoCompleteVisits.label","تاريخ القطع لزيارات الإكمال التلقائي"},
{"eOP.CutoffDatewithFollowup.label","الموعد النهائي مع المتابعة"},
{"eOP.DateTimeofReleases.label","تاريخ / وقت الإصدار"},
{"eOP.DateTimeOfVisit.label","تاريخ / وقت الزيارة"},
{"eOP.DeathCertificateSigned.label","توقيع شهادة الوفاة"},
{"eOP.DeceasedChecklist.label","قائمة مرجعية المتوفى"},
{"eOP.DelinkReferral.label","إحالة Delink"},
{"eOP.Departed.label","الراحل"},
{"eOP.DepartmentDescription.label","وصف القسم"},
{"eOP.DispDateTime.label","تاريخ / وقت الترتيب"},
{"eOP.EarliestApptDate.label","أقرب موعد. تاريخ"},
{"eOP.EpisodeNotes.label","ملاحظات الزيارة"},
{"eOP.EpisodeNoVisitNo.label","رقم الزيارة"},
{"eOP.Episodes.label","الزيارات"},
{"eOP.EpisodeVisitDetails.label","تفاصيل الزيارة "},
{"eOP.FileCurrentLocation.label","موقع الملف الحالي"},
{"eOP.Filedoesnotexist.label","الملف غير موجود"},
{"eOP.FirstTimeArrival.label","وصول أول مرة"},
{"eOP.ForMonthYear.label","لشهر / سنة"},
{"eOP.ForSpecifiedService.label","للخدمة المحددة"},
{"eOP.FuneralHomeRelease.label","الإفراج عن جنازة "},
{"eOP.IncludeCheckedoutPatients.label","قم بتضمين المرضى المسجلين خروج"},
{"eOP.IncludeNoShow.label","تضمين عدم الحضور"},
{"eOP.InitChkUpORVtlSgnRec.label","الفحص الأولي / تسجيل العلامات الحيوية"},
{"eOP.IntheEventofDeath.label","في حالة الوفاة"},
{"eOP.InvitationPeriod.label","فترة الدعوة"},
{"eOP.ItemBatchResult.label","نتيجة تشغيله الصنف"},
{"eOP.LastVisitDate.label","تاريخ آخر زيارة"},
{"eOP.LocationTypeDescription.label","وصف نوع الموقع"},
{"eOP.MaxApptDuration.label","المده القصوي للموعد"},
{"eOP.MaxApptSlots.label","الحد الاقصي للفترات الزمنيه للمواعيد"},
{"eOP.MaxNoofdaysforvisitcompletion.label","عدد الأيام لاستكمال الزيارة"},
{"eOP.MaxNoofdaysforvisitreviscancel.label","الحد الأقصى لعدد أيام الزيارة المراجعة / الإلغاء"},
{"eOP.Minafterappointmenttime.label","الحد الادني من الوقت بعد الموعد"},
{"eOP.Minbeforeappointmenttime.label","الحد الادني من الوقت قبل الموعد "},
{"eOP.Minimumdayselapsedfromlastvisit.label","الحد الأدنى من الأيام المنقضية من آخر زيارة"},
{"eOP.MovementDateTime.label","تاريخ / وقت الحركة"},
{"eOP.MovementReason.label","سبب الحركة"},
{"eOP.MovementType.label","نوع الحركة"},
{"eOP.MRN.label","MRN"},
{"eOP.NewEpisode.label","زيارة جديدة"},
{"eOP.NoFollowup.label","لا متابعة"},
{"eOP.NoRecords.label","لا تسجيلات"},
{"eOP.NoshowApptstatus.label","حالة موعد عدم الحضور إذا لم يكن تسجيل الوصول في خلال"},
{"eOP.notattended.label","غير مقصود"},
{"eOP.NotCheckedOut.label","لم يتم تسجيل الخروج"},
{"eOP.NotIdentifiable.label","غير قابل للتحديد"},
{"eOP.NumberStart.label","رقم البداية"},
{"eOP.OntimeAppointmentstatusIfcheckinisatleast.label","حالة الموعد في الوقت المحدد إذا كان تسجيل الوصول على الأقل"},
{"eOP.OpenEpisodes.label","الزيارات المفتوحة"},
{"eOP.OpentoallResources.label","مفتوح لجميع الموارد"},
{"eOP.OperatingTime.label","وقت التشغيل"},
{"eOP.OrderableCriteria.label","معايير القابلة للطلب"},
{"eOP.OrderCatalogNo.label","رقم كتالوج الطلب"},
{"eOP.OrganDonors.label","المتبرعين بالأعضاء"},
{"eOP.OtherResource.label","موارد أخرى"},
{"eOP.OtherResourceID.label","معرف الموارد الأخرى"},
{"eOP.otherrestype.label","نوع الموارد الأخرى"},
{"eOP.OutpatientEpisodes.label","نوبات العيادات الخارجية"},
{"eOP.OverrideVisitTypecontrolonEpisode.label","تجاوز عنصر التحكم في نوع الزيارة في الزيارة"},
{"eOP.PractitionerRoomPrivileges.label","امتيازات الممارس / الغرفه"},
{"eOP.PrimaryResourceClass.label","فئة الموارد الأولية"},
{"eOP.PrimaryResourceType.label","نوع المورد الأساسي"},
{"eOP.PrintAppointmentSlip.label","طباعة قسيمة الموعد"},
{"eOP.PrintReferralLetter.label","طباعة خطاب الإحالة"},
{"eOP.PriorLocation.label","الموقع السابق"},
{"eOP.ProcedureUnitCode.label","كود وحدة الإجراءات"},
{"eOP.ProcedureUnitDescription.label","وصف وحدة الإجراءات"},
{"eOP.ProcedureUnitForClinic.label","وحدة الإجراءات للعيادة"},
{"eOP.ProcedureUnitType.label","نوع وحدة الإجراء"},
{"eOP.QueueID.label","معرف قائمة الانتظار"},
{"eOP.QueuePrefix.label","بادئة قائمة الانتظار"},
{"eOP.ReasonForMovement.label","سبب الحركة"},
{"eOP.ReasonForReviseVisit.label","سبب مراجعه الزياره"},
{"eOP.reassignpractitioner.label","إعادة تعيين ممارس"},
{"eOP.RecallDetails.label","استدعاء تفاصيل"},
{"eOP.recordvitalsigns.label","سجل العلامات الحيوية"},
{"eOP.ReferralDestination.label","وجهة الإحالة"},
{"eOP.ReferralfoConsult.label","الإحالة للكشف"},
{"eOP.Referrals.label","الإحالات"},
{"eOP.ReferralSourceCode.label","رمز مصدر الإحالة"},
{"eOP.RegnDateTime.label","تاريخ / وقت التسجيل"},
{"eOP.RegnTime.label","وقت التسجيل"},
{"eOP.ResetNumber.label","إعادة تعيين الرقم"},
{"eOP.ResourceClassType.label","فئة الموارد / النوع"},
{"eOP.ResourceCriteria.label","معايير الموارد"},
{"eOP.ResourcePrivileges.label","امتيازات الموارد"},
{"eOP.ResourceTypeDescription.label","وصف نوع المورد"},
{"eOP.Location.label","موقع"},
{"eOP.RetFrmInvest.label","عاد من الفحص"},
{"eOP.ReverttoCheckin.label","العودة لتسجيل الوصول"},
{"eOP.RoomDescription.label","وصف الغرفة"},
{"eOP.Seen.label","مرئي"},
{"eOP.SelectUnassignedPatients.label","حدد المرضى غير المعينين"},
{"eOP.StartNumber.label","رقم البداية"},
{"eOP.StartofConsultation.label","بدء الاستشارة"},
{"eOP.Statistic.label","إحصائية"},
{"eOP.StatisticsbyLocation.label","الإحصائيات حسب الموقع"},
{"eOP.StatisticsbyService.label","الإحصاء حسب الخدمة"},
{"eOP.StatisticsDate.label","تاريخ الإحصائيات"},
{"eOP.StatisticsDateFrom.label","تاريخ الإحصائيات من"},
{"eOP.StatisticsDateTo.label","تاريخ الإحصائيات إلى"},
{"eOP.StatisticsMonthYear.label","إحصائيات شهر / سنة"},
{"eOP.SubServiceCode.label","كود الخدمة الفرعية"},
{"eOP.SystemCheckedOut.label","تم الخروج"},
{"eOP.TabList.label","قائمة الجدولة"},
{"eOP.todayapptfor.label","مواعيد اليوم ل"},
{"eOP.UndergoingTrtORInvst.label","الخضوع للعلاج / الفحص"},
{"eOP.ValuablesReleased.label","الإفراج عن الأشياء الثمينة"},
{"eOP.VisitCompletion.label","انتهاء الزياره"},
{"eOP.VisitDue.label","زيارة موعد"},
{"eOP.VisitDueDate.label","تاريخ استحقاق الزيارة"},
{"eOP.VisitingPractitioner.label","الممارس الزائر"},
{"eOP.VisitNo.label","رقم زيارة"},
{"eOP.Visits.label","الزيارات"},
{"eOP.VisitTypeIndicator.label","مؤشر نوع الزيارة"},
{"eOP.Vital.label","حيوي"},
{"eOP.VitalSignRecorded.label","تم تسجيل العلامات الحيوية"},
{"eOP.VitalSignsNursingMeasures.label","العلامات الحيوية / إجراءات التمريض"},
{"eOP.Wait.label","انتظر"},
{"eOP.Walkins.label","عملاء بدون حجز"},
{"eOP.WeekApplicable.label","أسبوع قابل للتطبيق"},
{"eOP.WorkingWeeksAppl.label","تطبيق أسابيع العمل"},
{"eOP.Arrivedat.label","وصل في"},
{"eOP.Departedto.label","غادر إلى"},
{"eOP.ToComeBackAfter.label","بالعودة بعد"},
{"eOP.ViewPatientMovement.label","عرض حركة المريض"},
{"eOP.QueueNumberingControls.label","ضوابط ترقيم قائمة الانتظار"},
{"eOP.NumberingApplicable.label","ينطبق الترقيم"},
{"eOP.DiagnosisForThisEncounter.label","التشخيص لهذه الزياره"},
{"eOP.DispositionDetails.label","تفاصيل الترتيب"},
{"eOP.VS.label","ضد"},
{"eOP.PR.label","العلاقات العامة"},
{"eOP.TR.label","TR"},
{"eOP.WT.label","WT"},
{"eOP.XT.label","XT"},
{"eOP.QN.label","QN"},
{"eOP.NS.label","NS"},
{"eOP.VisitComplWithPract.label","إكمال الزيارة مع الممارس"},
{"eOP.AllowInvitationNo.label","السماح بترقيم الدعوه"},
{"eOP.OPBatchProcess.label","OP Batch Process"},
{"eOP.AssignQueueNumberby.label","تعيين رقم قائمة الانتظار من خلال"},
{"eOP.OverrideWalkIn.label","Override Walk-In"},
{"eOP.MaxWalkinPerDay.label","الحد الاقصي للعملاء بدون حجز في اليوم"},
{"eOP.OverridePractForAppt.label","تجاوز ممارس لحالة التعيين"},
{"eOP.MRSectionFileStorage.label","الرنين المغنطيسي قسم / ملف تخزين"},
{"eOP.AlwVstRegForInPatients.label","السماح بتسجيل الزيارة للمرضى الداخليين"},
{"eOP.InvokeVisRegnFromCA.label","استدعاء تسجيل الزيارة / إدارة قائمة انتظار المريض من CA"},
{"eOP.TotalUnclosedVisits.label","إجمالي عدد الزيارات غير المغلقة"},
{"eOP.TotalAutoCloseVisits.label","إجمالي عدد الزيارات للإغلاق التلقائي"},
{"eOP.TotalManualVisits.label","إجمالي عدد الزيارات للإغلاق اليدوي"},
{"eOP.FollowUpVisitDuratin.label","مدة زيارة المتابعة"},
{"eOP.NoofFollowUpVisitAllowed.label","عدد زيارات المتابعة المسموح بها"},
{"eOP.VisitBackDays.label","عدد ايام الاثر الرجعي للزياره"},
{"eOP.StatisticsBySplty.label","الإحصاء حسب التخصص"},
{"eOP.RegReflOnClsCons.label","تسجيل الاحاله فور اغلاق الكشف"},
{"eOP.ClosePatChart.label","أغلق مخطط المريض عند اغلاق الاستشارة / تسجيل خروج"},
{"eOP.VisitDtlsTemplate.label","نموذج تفاصيل الزياره"},
{"eOP.M.label","ذكر"},
{"eOP.F.label","انثي"},
{"eOP.Y.label","Y"},
{"eOP.ForTheMonth.label","لشهر"},
{"eOP.Appts.label","المواعيد"},
{"eOP.Side.label","الجانب"},
{"eOP.NonBedSide.label","غير جانب السرير"},
{"eOP.POfNoShows.label","٪ من عدم الحضور"},
{"eOP.PreConsultArrivedTime.label","وقت وصول ما قبل الاستشاره"},
{"eOP.Totalforthe.label","إجمالي"},
{"eOP.Totalfortheperiod.label","المجموع للفترة"},
{"eOP.PatientTypeFrom.label","نوع المريض من"},
{"eOP.U.label","U"},
{"eOP.ForTheWeek.label","للاسبوع"},
{"eOP.TotalAppts.label","مجموع المواعيد"},
{"eOP.ForTheMonth.label","لشهر"},
{"eOP.NewCases.label","حالات جديدة"},
{"eOP.FollowUpCases.label","حالات متابعه"},
{"eOP.TabListNo.label","رقم قائمة علامات التبويب "},
{"eOP.FollowupVisits.label","زيارات المتابعة"},
{"eOP.TotalVisits.label","إجمالي عدد الزيارات"},
{"eOP.ClinicWorkingDays.label","أيام عمل العيادة"},
{"eOP.OPDAttendance.label","حضور العيادات الخارجية"},
{"eOP.Dependants.label","المعالون"},
{"eOP.AveragePerformance.label","متوسط ​​الأداء"},
{"eOP.Entitled.label","مخول"},
{"eOP.NonEntitled.label","غير مخول"},
{"eOP.Civilians.label","مدنيون"},
{"eOP.TypeofMorbidity.label","نوع المرض"},
{"eOP.IncludeArrivedConsStartedPatients.label","تضمين المرضى الذين وصلوا و المرضي الذين بدأوا الكشف"},
{"eOP.TimePeriod.label","فترة زمنية"},
{"eOP.OTSpecific.label","الوقت الإضافي (محدد)"},
{"eOP.VisitTypeDerivationRule.label"," قاعدة اشتقاق نوع الزيارة "},
{"eOP.PractitionerBased.label","قائم على الممارس"},
{"eOP.ServiceBased.label","الخدمة القائمة"},
{"eOP.DefalutRuleID.label","معرف القاعدة الافتراضي"},
{"eOP.RuleID.label","معرف القاعدة"},
{"eOP.RuleDesc.label","وصف القاعدة"},
{"eOP.Followup.label","متابعة طبية أو أجتماعية"},
{"eOP.SecondaryVisit.label","زيارة ثانوية"},
{"eOP.NoofFollowupAllowed.label","عدد زيارات المتابعة المسموح بها"},
{"eOP.NoofSecondaryAllowed.label","عدد الزيارات الثانوية المسموح بها"},
{"eOP.CummulativevisitsAllowed.label","السماح بالزيارات التراكمية في الزيارة الثانوية"},
{"eOP.CancelledVisits.label","الزيارات الملغاة"},
{"eOP.NoCheckout.label","لم يتم تسجيل الخروج"},
{"eOP.Checkout.label","تم تسجيل الخروج"},
{"eOP.AutoCheckout.label","تسجيل خروج تلقائي السحب التلقائي"},
{"eOP.WaitTimeColorIndicator.label","معرف اللون لتحديد المريض إذا تجاوز وقت الانتظار"},
{"eOP.Mins.label","دقيقة"},
{"eOP.Colour.label","لون"},
{"eOP.QMS.label","واجهة QMS قابلة للتطبيق"},
{"eOP.CallTicket.label","اتصل بالمريض"},
{"eOP.ReCallTicket.label","أستدعاء المريض"},
{"eOP.CallRecall.label","سجل تجاري"},
{"eOP.AllowbackdatingVisitDateTime.label","السماح بالاثر الرجعي للتاريخ / وقت الزيارة"},
{"eOP.InsuranceGroup.label","خاص بمجموعه تامين"},
{"eOP.EpisodeClosureBy.label","اختتام الزيارة ب"},
{"eOP.ConsecutiveNoShows.label","عدد مرات عدم الحضور المتتالية"},
{"eOP.NoVisitsInLast.label","لا زيارة في الماضي"},
{"eOP.NoFutApptsIn.label","لا موعد مستقبلي في"},
{"eOP.in.label","في"},
{"eOP.ClosureRulebasedonNoshowslastvisitFutappt.label","قاعدة الإغلاق - بناءً على عدم الحضور"},
{"eOP.ActionUnsettledorUnbilledAmountfortheEncounter.label","الاجراء عند عدم تسوية / عدم دفع مبلغ الزياره"},
{"eOP.GoneforInvestigation.label","ذهب للتحقيق"},
{"eOP.AtDifferentLocation.label","(في موقع مختلف)"},
{"eOP.ActiononVisitRegistrationPractitionerScheduleisblocked.label","الإجراء الخاص بتسجيل الزيارة عندما يتم حظر جدول الممارس"},
{"eOP.DisplayInReportCustomerCode1.label","عرض في تقرير - رمز العميل 1"},
{"eOP.DisplayInReportCustomerCode2.label","عرض في تقرير - رمز العميل 2"},
{"eOP.DisplayInReportCustomerGroup1.label","عرض في تقرير مجموعة العملاء 1"},
{"eOP.DisplayInReportCustomerGroup2.label","عرض في تقرير مجموعة العملاء 2"},
{"eOP.VisitRegistrationBy.label","تسجيل الزياره بواسطة"},
{"eOP.VisitsConsulted.label","استشارة الزيارات"},
{"eOP.PendingConsult.label","استشارة معلقة"},
{"eOP.PractVisitLoad.label","زيارة الممارسين"},
{"eOP.calculateWaitTime.label","حساب وقت الانتظار على أساس الحالة"},
{"eOP.Walkin.label","ادخل"},
{"eOP.DispTypeForCloseConsCheckOut.label","نوع الترتيب لإغلاق الاستشارة / السحب"},
{"eOP.VisitAdmDate.label","تاريخ الزيارة / الدخول"},
{"eOP.diagnosisnotmandatory.label","التشخيص ليس إلزاميًا أثناء تسجيل المغادرة"},
{"eOP.NonMandatoryQueueNo.label","غير إلزامي لرقم الانتظار "},
{"eOP.ValidateNatIDRegVisit.label","التحقق من وجود بطاقة الهوية الوطنية أثناء زيارة التسجيل"},
{"eOP.DispTypeFOrOPEncounterRevokeDeath.label","نوع التصرف الافتراضي لإبطال الموت"},
{"eOP.ConsultationStarted.label","بدأت التشاور"},
{"eOP.ArrivedAtNursingCounter.label","وصل إلى كاونتر التمريض"},
{"eOP.clinic.label","عيادة"},
{"eOP.QueueNoMandate.label","رقم قائمة الانتظار إلزامي"}, 
{"eOP.UpdateQueueNumber.label","تحديث رقم قائمة الانتظار"}


	};
}
