/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eSM.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eSM.AccessLevel.label","访问级别"},
		{"eSM.AccessRightsforMenu.label","访问�?��?��?�利"},
		{"eSM.AccessRightsForMenuFunctions.label","访问�?��?�功能的�?�利"},
		{"eSM.AccessRightsforMenuSubFunctions.label","访问�?�?��?�的�?�利"},
//		{"eSM.AccountEntLongname.label","Accounting Entity Long Name"},
//		{"eSM.AccountEntShortname.label","Accounting Entity Short Name"},
//		{"eSM.AccountingEntityID.label","Accounting Entity ID"},
//		{"eSM.AccountingParameters.label","Accounting Parameters"},
		{"eSM.AddNewFunctions.label","增加新的功能"},
		{"eSM.AdhocMenu.label","临时�?��?��?"},
		{"eSM.AdhocMenuEffectiveDate.label","临时�?��?�有效日期"},
		{"eSM.ApplicationGroup.label","应用组"},
		{"eSM.ApplicationSecurity.label","应用安全"},
		{"eSM.ApplicationServerIPAddress.label","应用�?务器IP地�?�"},
		{"eSM.AssociatedFacilities.label","相关设施"},
		{"eSM.AssociatedMenuFunctions.label","相关�?��?��?功能"},
		{"eSM.AssociatedResponsibilities.label","相关责任"},
		{"eSM.AssociatedUsers.label","相关用户"},
		{"eSM.BackGroundProcesses.label","�?��?�进程"},
		{"eSM.Bitmap.label","�?图"},
		{"eSM.BitMappedReports.label","�?图报告"},
//		{"eSM.ByAccountEntity.label","By Accounting Entity"},
		{"eSM.ByResponsibility.label","通过责任"},
		{"eSM.Changes.label","�?�化"},
//		{"eSM.ChangeWSIdentificationatFacilityLevel.label","Change WS Identification at Facility Level"},
		{"eSM.Character.label","字符"},
		{"eSM.ClinicalSupport.label","临床支�?"},
		{"eSM.ConstructMenu.label","构建�?��?�"},
		{"eSM.CoreApplications.label","核心应用"},
		{"eSM.CreateMenu.label","创建�?��?�"},
		{"eSM.CurrencyName.label","货�?�??称"},
		{"eSM.CurrentFunctions.label","目�?的�?�能"},
		{"eSM.DatabaseResourceGroup.label","数�?�库资�?组"},
		{"eSM.DatabaseRoles.label","数�?�库角色"},
		{"eSM.DateDesc.label","日期"},
		{"eSM.DayNo.label","天"},
		{"eSM.DecimalName.label","�??进制�??称"},
		{"eSM.DefaultFileFormat.label","默认的档格�?"},
		{"eSM.DefaultPrinter.label","默认打�?�机"},
		{"eSM.DefaultReportMode.label","预设报告模�?"},
		{"eSM.DeleteAllowed.label","�?许删除"},
		{"eSM.DepartmentLength.label","部门长度"},
		{"eSM.DestCode.label","目标�?"},
		{"eSM.DestDesc.label","目标�??述"},
		{"eSM.DestLocn.label","目标�?置"},
		{"eSM.DisplaySiteName.label","显示岗站�??"},
//		{"eSM.DMP.label","DMP"},
//		{"eSM.down.label","Down"},
		{"eSM.EffectiveFromDate.label","影�?日期"},
		{"eSM.EffectiveToDate.label","影�?日期"},
		{"eSM.EnterpriseAdmin.label","�?业管�?�"},
		{"eSM.ExcludeRemoveSubmenuFunction.label","排除/删除�?�?��?�/功能"},
		{"eSM.Executable.label","�?�执行"},
		{"eSM.ExpirationPeriod.label","有效期"},
		{"eSM.ExternalInterfaces.label","外部接�?�"},
		{"eSM.Facilities.label","设施"},
		{"eSM.FacilitiesforUser.label","用户设施"},
		{"eSM.FacilitybasedReport.label","基础设施的报告"},
		{"eSM.FacilitybasedReportParameters.label","基础设施的报告�?�数"},
		{"eSM.FailedLoginAttempts.label","失败的登录�?试"},
		{"eSM.FailedProcessID.label","失财的进程�?�"},
		{"eSM.FinancialManagement.label","财务管�?�"},
		{"eSM.FinancialSetup.label","财务设置？"},
		{"eSM.Forms.label","形�?"},
		{"eSM.FrequentlyAccessedList.label","�?常访问的�??�?�"},
		{"eSM.FunctionalName.label","功能�??称"},
		{"eSM.FunctionalRoleDetails.label","功能角色详细"},
		{"eSM.FunctionalRoleType.label","功能角色类型"},
		{"eSM.FunctionalType.label","功能类型"},
		{"eSM.Functionsby.label","功能"},
		{"eSM.FunctionsbyResponsibilityGroup.label","功能组的功能"},
		{"eSM.GenerateFile.label","生�?檔"},
//		{"eSM.GraceTime.label","Grace Time"},
//		{"eSM.HeadoftheUnit.label","Head of the Unit"},
		{"eSM.HolidayorWorkingday.label","�?�日或工作一天"},
		{"eSM.HumanResourceManag.label","人力资�?管�?�"},
		{"eSM.Inkjet.label","喷墨打�?�机"},
		{"eSM.InsertAllowed.label","�?许播放"},
		{"eSM.InternalRequest.label","内部需求"},
		{"eSM.IPAddress.label","IP地�?�"},
//		{"eSM.Java.label","java"},
		{"eSM.JobQueue.label","工作队列"},
		{"eSM.LabelPrinter.label","�?�标打�?�机"},
		{"eSM.Laser.label","激光"},
		{"eSM.LicenseNo.label","授�?��?�"},
		{"eSM.ListofFunctions.label","功能列表"},
		{"eSM.ListofSubmenus.label","�?�?��?�列表"},
//		{"eSM.Logo.label","Logo"},
		{"eSM.MasterName.label","主�??称"},
		{"eSM.MaterialsManagement.label","�??料管�?�"},
		{"eSM.MenuAdminID.label","�?��?�管�?�编�?�"},
//		{"eSM.MenuAdministrator.label","Menu Administrator"},
		{"eSM.MenuAdminName.label","管�?��?��?��??称"},
		{"eSM.MenuName.label","�?��?��??称"},
		{"eSM.MenuPreview.label","�?��?�预览"},
//		{"eSM.MenuRestrictforResponsSubFunction.label","Menu Restriction for Responsibility Sub-Functions"},
		{"eSM.MenuRestrictionfor.label","�?��?��?制"},
		{"eSM.MenuRestrictionforResponsibility.label","�?��?�功能�?制"},
		{"eSM.Menus.label","�?��?�"},
		{"eSM.NextExecutionDateTime.label","下一步执行的日期/时间"},
		{"eSM.NonTranslated.label","未翻译"},
		{"eSM.NoofAccountingPeriods.label","第会计期"},
		{"eSM.NumberofCopies.label","份数"},
		{"eSM.NumberofDecimals.label","一些�?数"},
		{"eSM.Operational.label","业务"},
		{"eSM.OperationalStatus.label","业务状�?"},
		{"eSM.OrderofArea.label","命令区"},
		{"eSM.OrderofLine.label","命令行"},
//		{"eSM.OrderofPostalCode.label","Order of Postal Code"},
//		{"eSM.OrderofRegion.label","Order of Region"},
//		{"eSM.OrderofTown.label","Order of Town"},
		{"eSM.PasswordControl.label","密�?控制"},
		{"eSM.PasswordLockPeriod.label","密�?�?时期"},
		{"eSM.PINNo.label","密�?"},
		{"eSM.PreferredLanguage.label","首选语言"},
		{"eSM.PrefixDepartmentbyFacilityID.label","设施编�?�的�?缀部门"},
		{"eSM.PrintAllowed.label","�?许打�?�"},
		{"eSM.Printer.label","打�?�机"},
		{"eSM.PrinterDetails.label","打�?�机明细"},
		{"eSM.PrinterID.label","打�?�机编�?�"},
		{"eSM.PrinterName.label","打�?�机�??称"},
		{"eSM.Printers.label","打�?�机"},
		{"eSM.PrinterType.label","打�?�机类型"},
		{"eSM.PrintRouting.label","打�?�路由"},
		{"eSM.ProhibitReuse.label","�?止�?�?使用"},
		{"eSM.Prompts.label","�??示"},
		{"eSM.PurgePeriod.label","净化器"},
		{"eSM.PurgeProcessDetails.label","净化过程的细节"},
		{"eSM.Queries.label","查询"},
		{"eSM.QueryAllowed.label","�?许查询"},
		{"eSM.QueryonResponsibility.label","查询功能"},
		{"eSM.QueryonUsers.label","查询用户"},
		{"eSM.QueueName.label","队列�??称"},
		{"eSM.ReenterNewPassword.label","�?次输入新密�?"},
		{"eSM.ReportDetails.label","报告详细资料"},
		{"eSM.ReportGroup.label","报告组"},
		{"eSM.ReportGroupDesc.label","报告组�??述"},
		{"eSM.ReportGroupID.label","报告组编�?�"},
//		{"eSM.ReportNature.label","Report Nature"},
		{"eSM.ReportOutputDirectory.label","报告输出目录"},
		{"eSM.Reports.label","报告"},
		{"eSM.ReportService.label","报告�?务"},
		{"eSM.ReportServiceID.label","报告�?务编�?�"},
		{"eSM.ReportServiceName.label","报告�?务�??称"},
		{"eSM.ResourceGroup.label","资�?组"},
		{"eSM.ResourceGroupID.label","资�?组编�?�"},
		{"eSM.ResourceGroupName.label","资�?组�??称"},
		{"eSM.ResponsibilityforFacility.label","设备责任？"},
		{"eSM.ResponsibilityforUser.label","使用者的责任"},
		{"eSM.ResponsibilityGroup.label","责任组"},
		{"eSM.ResponsibilityGroupID.label","责任组编�?�"},
		{"eSM.ResponsibilityGroupName.label","责任组�??称"},
		{"eSM.ResponsibilityIDFrom.label","责任编�?�"},
		{"eSM.ResponsibilityList.label","责任清�?�"},
		{"eSM.RestrictedSubmenuFunctionDetls.label","�?��?制的�?/功能细节"},
		{"eSM.Reuse.label","�?利用"},
		{"eSM.ReuseOption.label","�?利用�?作"},
		{"eSM.RoleName.label","角色�??称"},
//		{"eSM.SearchFacility.label","Search Facility"},
		{"eSM.SearchResponsibility.label","查询功能"},
//		{"eSM.SelectFacility.label","Select Facility"},
		{"eSM.SiteID.label","网站编�?�"},
//		{"eSM.SMMasterCodeList.label","SM Master Code List"},
		{"eSM.SpecialtyServices.label","专业�?务"},
		{"eSM.StartFiscalMonth.label","开始财政年度"},
		{"eSM.StatusChangeAllowed.label","�?许改�?�状�?"},
		{"eSM.SubFunctionName.label","�?功能�??称"},
		{"eSM.Submenu.label","�?�?��?�"},
		{"eSM.Tool.label","工作"},
		{"eSM.ToolUsed.label","使用工具"},
		{"eSM.TransactionBased.label","基于事务"},
		{"eSM.TransBased.label","基于转�?�"},
		{"eSM.Translated.label","翻译"},
		{"eSM.TranslatedLanguage.label","翻译语言"},
		{"eSM.TranslationManager.label","翻译�?�?�"},
		{"eSM.UpdateAllowed.label","�?许更新"},
		{"eSM.UserIDFrom.label","用户编�?"},
		{"eSM.UserList.label","用户列表"},
		{"eSM.UserResponsibilityAccessList.label","用户功能清�?�"},
		{"eSM.Users.label","用户"},
		{"eSM.WeekAppl.label","周应用"},
		{"eSM.WorkStationIdentification.label","工作站鉴定"},
		{"eSM.WorkstationIdentificationBy.label","通过工作站鉴定"},
		{"eSM.ReportServerIPAddress.label","报告�?务器IP地�?�"},
		{"eSM.ForeignCurrency.label","外汇"},
		{"eSM.GenActPeriod.label","生�?的会计期间"},
		{"eSM.MaintainActPeriod.label","维护会计期"},
		{"eSM.CancelledDocuments.label","�?�消文檔"},
		{"eSM.DocumentTypes.label","文件类型"},
		{"eSM.AcctEntity.label","会计实体"},
		{"eSM.SysGenDocNo.label","系统生�?的文件�?�"},
		{"eSM.DocNoGen.label","档编�?�生�?"},
		{"eSM.StartDocNo.label","开始档�?�"},
		{"eSM.NextDocNo.label","下一文件�?�"},
		{"eSM.AutoPrint.label","自动打�?�"},
		{"eSM.EntryMode.label","进入模�?"},
		{"eSM.Online.label","在线"},
		{"eSM.DocNumber.label","文件�?�"},
		{"eSM.AccountYear.label","会计年度"},
		{"eSM.AccountPeriodYear.label","会计期一年"},
		{"eSM.AccountPeriodMonth.label","会计期一个月"},
		{"eSM.AccountPeriodSdate.label","会计期开始日期"},
		{"eSM.AccountPeriodEdate.label","会计期结�?�日期"},
		{"eSM.AccountPeriodDesc.label","会计期�??述"},
		{"eSM.CalenderYear.label","历年"},
		{"eSM.CalenderMonth.label","日历月"},
		{"eSM.CurrencyCode.label","货�?代�?"},
		{"eSM.ConversionRate.label","汇率"},
		{"eSM.ConversionOperator.label","转�?��?作"},
		{"eSM.ProductLineCode.label","产�?线代�?"},
		{"eSM.ProductGroupCode.label","产�?组代�?"},
		{"eSM.DepartmentCode.label","部门代�?"},
//		{"eSM.SubLedgerLineCode.label","Sub Ledger Line Code"},
//		{"eSM.SubLedgerGroupCode.label","Sub Ledger Group Code"},
		{"eSM.MainAccountCode2.label","主�?账户代�?1"},
		{"eSM.MainAccountCode1.label","主�?账户代�?2"},
//		{"eSM.FacImgFileName.label","Facility Logo Image File Name"},
//		{"eSM.LoginScrnImgFileName.label","Login Screen Image File Name"},
		{"eSM.SiteLogoLoginScreen.label","网站标志（登录�?幕）"},
//		{"eSM.HeaderLogoImageFileName.label","Header Logo Image File Name"},
		{"eSM.SiteLogoPageHeader.label","网站标志（页标题）"},
//Newly Added Legends on 21/01/09
		{"eSM.AccountEntLongname.label","会计实体详细�??称"},
{"eSM.AccountEntShortname.label","会计实体简短�??称"},
{"eSM.AccountingEntityID.label","会计实体编�?�"},
{"eSM.AccountingParameters.label","会计�?�数"},
{"eSM.ByAccountEntity.label","通过会计实体"},
{"eSM.ChangeWSIdentificationatFacilityLevel.label","在医院级别内改�?�工作站"},
{"eSM.DMP.label","DMP"},
{"eSM.down.label","�?�下"},
{"eSM.FacImgFileName.label","特殊部门标志的文件�??"},
{"eSM.GraceTime.label","�?外时间"},
{"eSM.HeaderLogoImageFileName.label","标志标题的文件�??"},
{"eSM.HeadoftheUnit.label","Head of the Unit"},
{"eSM.LoginScrnImgFileName.label","登录�?幕图�?的文件�??"},
{"eSM.MenuAdministrator.label","�?��?�管�?�"},
{"eSM.MenuRestrictforResponsSubFunction.label","�?功能的�?��?��?制"},
{"eSM.OrderofPostalCode.label","邮政编�?秩�?"},
{"eSM.OrderofRegion.label","地区秩�?"},
{"eSM.OrderofTown.label","城镇秩�?"},
{"eSM.ReportNature.label","报告"},
{"eSM.SearchFacility.label","查找部门"},
{"eSM.SelectFacility.label","选择部门"},
{"eSM.SMMasterCodeList.label","列表代�?"},
{"eSM.SubLedgerGroupCode.label","Sub Ledger Group Code"},
{"eSM.SubLedgerLineCode.label","Sub Ledger Line Code"},



};
}
