package eSM.resources;

import java.util.*;

public class  Labels_th  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
			{"eSM.AccessLevel.label","ระดับการเข้าถึงข้อมูล/ใช้งาน"},
			{"eSM.AccessRightsforMenu.label","สิทธิการดำเนินการ สำหรับรายการ"},
			{"eSM.AccessRightsForMenuFunctions.label","สิทธิการดำเนินการ สำหรับรายการ หน้าที่"},
			{"eSM.AccessRightsforMenuSubFunctions.label","สิทธิการดำเนินการ สำหรับรายการ หน้าที่ย่อย"},
			{"eSM.AccountEntLongname.label","ชื่อบัญชีอย่างยาว"},
			{"eSM.AccountEntShortname.label","ชื่อบัญชีอย่างสั้น"},
			{"eSM.AccountingEntityID.label","หมายเลขประจำงานคลัง"},
			{"eSM.AccountingParameters.label","Parameter งานคลัง"},
			{"eSM.AddNewFunctions.label","เพิ่มหน้าที่ใหม่"},
			{"eSM.ApplicationGroup.label","กลุ่มระบบการใช้งาน"},
			{"eSM.ApplicationSecurity.label","ความปลอดภัยระบบการใช้งาน"},
			{"eSM.ApplicationServerIPAddress.label","การสนับสนุน IP Address ของระบบการใช้งาน"},
			{"eSM.AssociatedFacilities.label","โรงพยาบาลที่เกี่ยวข้อง"},
			{"eSM.AssociatedMenuFunctions.label","เมนูหน้าที่การทำงานที่เกี่ยวข้อง"},
			{"eSM.AssociatedResponsibilities.label","หน้าที่รับผิดชอบที่เกี่ยวข้อง"},
			{"eSM.AssociatedUsers.label","ผู้ใช้งานที่เกี่ยวข้อง"},
			{"eSM.BackGroundProcesses.label","ขบวนการเบื้องหลัง"},
			{"eSM.ByAccountEntity.label","โดยบัญชี"},
			{"eSM.ByResponsibility.label","โดยหน้าที่/ความรับผิดชอบ"},
			{"eSM.Changes.label","การเปลี่ยนแปลง"},
			{"eSM.ChangeWSIdentificationatFacilityLevel.label","การเปลี่ยนแปลงการระบุ WS ที่ระดับโรงพยาบาล"},
			{"eSM.Character.label","ตัวอักษร"},
			{"eSM.ClinicalSupport.label","การสนับสนุนทางคลินิก"},
			{"eSM.ConstructMenu.label","สร้างรายการ"},
			{"eSM.CoreApplications.label","รายการหลัก"},
			{"eSM.CreateMenu.label","สร้างรายการ"},
			{"eSM.CurrencyName.label","ชื่อสกุล เงิน"},
			{"eSM.CurrentFunctions.label","หน้าที่ปัจจุบัน"},
			{"eSM.DatabaseResourceGroup.label","กลุ่ม"},
			{"eSM.DatabaseRoles.label","บทบาทข้อมูลพื้นฐาน"},
			{"eSM.DateDesc.label","วันที่ (คำอธิบาย)"},
			{"eSM.DayNo.label","จำนวนวัน"},
			{"eSM.DecimalName.label","หน่วยเงิน"},
			{"eSM.DefaultFileFormat.label","รูปแบบ"},
			{"eSM.DefaultPrinter.label","เครื่องพิมพ์เบื้องต้น"},
			{"eSM.DefaultReportMode.label","วิธีรายงานเบื้องต้น"},
			{"eSM.DeleteAllowed.label","อนุญาติให้ลบได้"},
			{"eSM.DepartmentLength.label","ความยาวของชื่อภาควิชา"},
			{"eSM.DestCode.label","รหัสสถานที่ปลายทาง"},
			{"eSM.DestDesc.label","คำอธิบายสถานที่ปลายทาง"},
			{"eSM.DestLocn.label","ตำแหน่งปลายทาง"},
			{"eSM.DisplaySiteName.label","ดูชื่อสถานที่"},
			{"eSM.DMP.label","DMP"},
			{"eSM.down.label","ลง"},
			{"eSM.EffectiveFromDate.label","มีผลตั้งแต่วันที่"},
			{"eSM.EffectiveToDate.label","มีผลถึงวันที่"},
			{"eSM.EnterpriseAdmin.label","การบริหารองค์กร"},
			{"eSM.ExcludeRemoveSubmenuFunction.label","ตัดออก/ย้ายเมนูย่อย/หน้าที่การทำงาน"},
			{"eSM.Executable.label","ตารางการปฏิบัติ"},
			{"eSM.ExpirationPeriod.label","ระยะเวลาหมดอายุ"},
			{"eSM.ExternalInterfaces.label","การเชื่อมโยงระบบภายนอก"},
			{"eSM.Facilities.label","สถานพยาบาล"},
			{"eSM.FacilitiesforUser.label","โรงพยาบาลสำหรับผู้ใช้งาน"},
			{"eSM.FacilitybasedReport.label","รายงานข้อมูลพื้นฐาน Facility"},
			{"eSM.FacilitybasedReportParameters.label","พารามิเตอร์รายงานจากสถานพยาบาล"},
			{"eSM.FailedLoginAttempts.label","ความพยายามที่จะเข้าระบบล้มเหลว"},
			{"eSM.FailedProcessID.label","หมายเลขประจำขั้นตอนการทำงานที่ล้มเหลว"},
			{"eSM.FinancialManagement.label","การจัดการการเงินการบัญชี"},
			{"eSM.FinancialSetup.label","การตั้งค่าการเงินการบัญชี"},
			{"eSM.Forms.label","รูปแบบ"},
			{"eSM.FrequentlyAccessedList.label","บัญชีความถี่ของการใช้งาน"},
			{"eSM.FunctionalName.label","ชื่อหน้าที่การทำงาน"},
			{"eSM.FunctionalRoleDetails.label","รายละเอียดบทบาทหน้าที่การทำงาน"},
			{"eSM.FunctionalRoleType.label","ชนิดบทบาทหน้าที่การทำงาน"},
			{"eSM.FunctionalType.label","ชนิดหน้าที่การทำงาน"},
			{"eSM.Functionsby.label","หน้าที่การทำงาน  โดย"},
			{"eSM.FunctionsbyResponsibilityGroup.label","ฟังก์ชั่นตามกลุ่มงาน/ความรับผิดชอบ"},
			{"eSM.GenerateFile.label","สร้างแฟ้ม"},
			{"eSM.GraceTime.label","เวลาผ่อนผัน"},
			{"eSM.HeadoftheUnit.label","หัวหน้าหน่วย"},
			{"eSM.HolidayorWorkingday.label","วันหยุด หรือวันทำการ"},
			{"eSM.HumanResourceManag.label","การจัดการทรัพยากรบุคคล"},
			{"eSM.Inkjet.label","เครื่องพิมพ์"},
			{"eSM.InsertAllowed.label","อนุญาติให้เพิ่ม"},
			{"eSM.InternalRequest.label","การร้องขอภายใน"},
			{"eSM.IPAddress.label","IP Address"},
			{"eSM.Java.label","java"},
			{"eSM.JobQueue.label","คิว"},
			{"eSM.LabelPrinter.label","เครื่องพิมพ์ป้าย"},
			{"eSM.Laser.label","เลเซอร์"},
			{"eSM.LicenseNo.label","หมายเลขใบอนุญาติ"},
			{"eSM.ListofFunctions.label","บัญชีของหน้าที่การทำงาน"},
			{"eSM.ListofSubmenus.label","บัญชีของเมนูย่อย"},
			{"eSM.Logo.label","สัญลักษณ์"},
			{"eSM.MasterName.label","ชื่อหลัก"},
			{"eSM.MaterialsManagement.label","การจัดการอุปกรณ์"},
			{"eSM.MenuAdminID.label","เมนูหมายเลขประจำการบริหารจัดการ"},
			{"eSM.MenuAdministrator.label","เมนูการบริหารจัดการ"},
			{"eSM.MenuAdminName.label","เมนูชื่อการบริหารจัดการ"},
			{"eSM.MenuName.label","ชื่อรายการ"},
			{"eSM.MenuPreview.label","ดูรายละเอียดเมนู"},
			{"eSM.MenuRestrictforResponsSubFunction.label","การจำกัดของเมนูสำหรับหน้าที่ความรับผิดชอบย่อย"},
			{"eSM.MenuRestrictionfor.label","การจำกัดของเมนูสำหรับ"},
			{"eSM.MenuRestrictionforResponsibility.label","ข้อจำกัดรายการสำหรับหน้าที่/ความรับผิดชอบ"},
			{"eSM.Menus.label","รายการ"},
			{"eSM.NextExecutionDateTime.label","วัน เวลาการปฎิบัติถัดไป"},
			{"eSM.NonTranslated.label","ไม่แปล"},
			{"eSM.NoofAccountingPeriods.label","จำนวนของระยะเวลาทางการบัญชี"},
			{"eSM.NumberofCopies.label","จำนวนของ ชุด"},
			{"eSM.NumberofDecimals.label","จำนวนทศนิยม"},
			{"eSM.Operational.label","การปฏิบัติการ"},
			{"eSM.OperationalStatus.label","สถานะการปฏิบัติการ"},
			{"eSM.OrderofArea.label","ลำดับของพื้นที่"},
			{"eSM.OrderofLine.label","ลำดับของเชื้อสาย"},
			{"eSM.OrderofPostalCode.label","ลำดับของรหัสไปรษณีย์"},
			{"eSM.OrderofRegion.label","ลำดับของภาค"},
			{"eSM.OrderofTown.label","ลำดับของเมือง"},
			{"eSM.PasswordControl.label","ควบคุมรหัสผ่าน"},
			{"eSM.PasswordLockPeriod.label","ช่วงเวลาที่ lock รหัสผ่าน"},
			{"eSM.PINNo.label","หมายเลข PIN"},
			{"eSM.PreferredLanguage.label","ภาษาที่เลือกใช้"},
			{"eSM.PrefixDepartmentbyFacilityID.label","คำนำหน้าภาควิชาโดยหมายเลขประจำโรงพยาบาล"},
			{"eSM.PrintAllowed.label","อนุญาติให้พิมพ์"},
			{"eSM.Printer.label","เครื่องพิมพ์"},
			{"eSM.PrinterDetails.label","รายละเอียดเครื่องพิมพ์"},
			{"eSM.PrinterID.label","หมายเลขประจำเครื่องพิมพ์"},
			{"eSM.PrinterName.label","ชื่อเครื่องพิมพ์"},
			{"eSM.Printers.label","เครื่องพิมพ์"},
			{"eSM.PrinterType.label","ชนิดเครื่องพิมพ์"},
			{"eSM.PrintRouting.label","เส้นทางการพิมพ์"},
			{"eSM.ProhibitReuse.label","การยับยั้งการนำกลับมาใช้งาน"},
			{"eSM.Prompts.label","พร้อม"},
			{"eSM.PurgePeriod.label","ระยะเวลาลบล้าง"},
			{"eSM.PurgeProcessDetails.label","รายละเอียดขั้นตอนการลบล้าง"},
			{"eSM.Queries.label","สืบค้น"},
			{"eSM.QueryAllowed.label","อนุญาติให้รียกดู"},
			{"eSM.QueryonResponsibility.label","เรียกดูตามหน้าที่รับผิดชอบ"},
			{"eSM.QueryonUsers.label","เรียกดูตามผู้ใช้งาน"},
			{"eSM.QueueName.label","ชื่อคิว"},
			{"eSM.ReenterNewPassword.label","ใส่รหัสผ่านใหม่อีกครั้ง"},
			{"eSM.ReportDetails.label","รายละเอียดรายงาน"},
			{"eSM.ReportGroup.label","กลุ่มรายงาน"},
			{"eSM.ReportGroupDesc.label","คำอธิบายกลุ่มรายงาน"},
			{"eSM.ReportGroupID.label","หมายเลขประจำกลุ่มรายงาน"},
			{"eSM.ReportNature.label","รูปแบบรายงาน"},
			{"eSM.ReportOutputDirectory.label","กลุ่มรายงาน"},
			{"eSM.Reports.label","รายงาน"},
			{"eSM.ReportService.label","รายงานบริการ"},
			{"eSM.ReportServiceID.label","หมายเลขประจำรายงานบริการ"},
			{"eSM.ReportServiceName.label","ชื่อรายงานบริการ"},
			{"eSM.ResourceGroup.label","กลุ่มการบริการ"},
			{"eSM.ResourceGroupID.label","หมายเลขประจำกลุ่มการบริการ"},
			{"eSM.ResourceGroupName.label","ชื่อกลุ่มการบริการ"},
			{"eSM.ResponsibilityforFacility.label","หน้าที่รับผิดชอบสำหรับโรงพยาบาล"},
			{"eSM.ResponsibilityforUser.label","หน้าที่รับผิดชอบสำหรับผู้ใช้งาน"},
			{"eSM.ResponsibilityGroup.label","กลุ่มหน้าที่รับผิดชอบ"},
			{"eSM.ResponsibilityGroupID.label","หมายเลขประจำกลุ่มของหน้าที่รับผิดชอบ"},
			{"eSM.ResponsibilityGroupName.label","ชื่อกลุ่มหน้าที่รับผิดชอบ"},
			{"eSM.ResponsibilityIDFrom.label","หมายเลขประจำของหน้าที่รับผิดชอบ ตั้งแต่"},
			{"eSM.ResponsibilityList.label","รายการหน้าที่รับผิดชอบ"},
			{"eSM.RestrictedSubmenuFunctionDetls.label","จำกัด menuย่อย/รายละเอียดการทำงาน"},
			{"eSM.Reuse.label","นำมาใช้ใหม่"},
			{"eSM.ReuseOption.label","ทางเลือกการนำกลับมาใช้ใหม่"},
			{"eSM.RoleName.label","ชื่อบทบาท"},
			{"eSM.SearchFacility.label","หาโรงพยาบาล"},
			{"eSM.SearchResponsibility.label","หาหน้าที่รับผิดชอบ"},
			{"eSM.SelectFacility.label","เลือกโรงพยาบาล"},
			{"eSM.SiteID.label","หมายเลขประจำสถานที่ตั้ง"},
			{"eSM.SMMasterCodeList.label","รายการรหัสหลักสำหรับ การจัดการระบบ"},
			{"eSM.SpecialtyServices.label","งานบริการสำหรับ"},
			{"eSM.StartFiscalMonth.label","เริ่มต้นเดือนประจำปีงบประมาณ"},
			{"eSM.StatusChangeAllowed.label","อนุญาติให้มีการเปลี่ยนสถานะ"},
			{"eSM.SubFunctionName.label","ชื่อหน้าที่ย่อย"},
			{"eSM.Submenu.label","รายการย่อย"},
			{"eSM.Tool.label","เครื่องมือ"},
			{"eSM.ToolUsed.label","เครื่องมื่อที่ถูกใช้"},
			{"eSM.Translated.label","แปล"},
			{"eSM.TranslatedLanguage.label","ภาษาที่แปล"},
			{"eSM.TranslationManager.label","ผู้จัดการ การแปล"},
			{"eSM.UpdateAllowed.label","ยินยอมให้มีการปรับปรุง"},
			{"eSM.UserIDFrom.label","หมายเลขประจำตัวผู้ใช้งาน ตั้งแต่"},
			{"eSM.UserList.label","รายการ ผู้ใช้งาน"},
			{"eSM.UserResponsibilityAccessList.label","รายการการเข้าถึงข้อมูลของผู้ใช้/ภาระงาน"},
			{"eSM.Users.label","ผู้ใช้งาน"},
			{"eSM.WorkStationIdentification.label","ระบุตำแหน่งการทำงาน"},
			{"eSM.WorkstationIdentificationBy.label","ระบุตำแหน่งการทำงาน โดย"}
 	};
}
