/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from eAM.ReferralIDNumbering.ReferralIDNumberingManager
package eAM.ReferralIDNumbering;

/**
 * Local-Home interface for ReferralIDNumbering
 */
public interface ReferralIDNumberingLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/ReferralIDNumberingLocal";
    public static final String JNDI_NAME = "ReferralIDNumberingLocal";

    eAM.ReferralIDNumbering.ReferralIDNumberingLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
