/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eXH.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    } 


	static final Object[][] contents = {
		{"eXH.AbouttoSplit.Label","关于分裂"},
		{"eXH.AbouttoStop.Label","关于�?�止"},
		{"eXH.Abouttoprocess.Label","关于处�?�"},
		{"eXH.AccessionNumber.Label","�?许访问�?�"},
//		{"eXH.Acknowledged.Label","Acknowledged"},
//		{"eXH.AckDir.Label","Acknowlege Directory"},
//		{"eXH.AcknowlegementType.Label","Acknowlegement Type"},
		{"eXH.AddedDate.Label","新增日期"},
		{"eXH.AddedID.Label","新增编�?�"},
//		{"eXH.AddedWSNo.Label","Added WS No"},
		{"eXH.Always.Label","总是"},
		{"eXH.APIBased.Label","基于API"},
		{"eXH.APICode.Label","API编�?"},
		{"eXH.APIType.Label","api类型"},
		{"eXH.ApplicationCrossReference.Label","应用交�?��?�考"},
		{"eXH.ApplicationMessage.Label","应用信�?�"},
		{"eXH.ApplicationKey.Label","应用关键"},
		{"eXH.ApplicationID.Label","应用程�?编�?�"},
		{"eXH.ApplicationName.Label","应用程�?�??称"},
		{"eXH.CtrlElementId.Label","控制�?�元编�?�"},
		{"eXH.ExpectedValue.Label","期望值"},
		{"eXH.ExpectedValue1.Label","期望值１"},
		{"eXH.ExpectedValue2.Label","预期值2"},
//		{"eXH.ApplicationwiseSegments.Label","Application wise Segments"},
		{"eXH.ArgSerialNo.Label","�?�数�?列�?�"},
		{"eXH.ArgID.Label","�?�数编�?"},
		{"eXH.ArgName.Label","�?�数�??称"},
		{"eXH.ASCIIFile.Label","ASCII文件"},
		{"eXH.AutomaticRestartType.Label","自动�?�动型"},
		{"eXH.AutomaticRestartTime.Label","自动�?新�?�动时间[时时：分分]"},
		{"eXH.Audit.Label","审计"},
		{"eXH.ByLocation.Label","�?置"},
		{"eXH.BYPatientType.Label","病人类型"},
		{"eXH.BYCategory.Label","类别"},
		{"eXH.BySubLocation.Label","�?�?置"},
		{"eXH.ByType.Label","按类型"},
		{"eXH.Client.Label","客户端"},
		{"eXH.ClientId.Label","客户编�?�"},
		{"eXH.CommunicationClient.Label","通信客户端"},
		{"eXH.CommunicationErrors.Label","通信错误"},
		{"eXH.CommunicationProcesSettings.Label","通信进程设置"},
		{"eXH.CommunicationSettings.Label","通信设置"},
		{"eXH.CommunicationMode.Label","通信模�?"},
		{"eXH.CommDataIOAPI.Label","数�?�通信的I / O API"},
		{"eXH.CommStatisticsAPI.Label","统计数�?�通信的API"},
		{"eXH.CommType.Label","通讯类型"},
		{"eXH.CommunicationType.Label","通讯类型"},
		{"eXH.CondForInsertUpdt.Label","�?�入更新的�?�件"},
		{"eXH.CondExpr.Label","�?�件�?�?�?�"},
		{"eXH.ConfigType.Label","�?置类型"},
		{"eXH.ConfigName.Label","�?置�??称"},
		{"eXH.ControlStructure.Label","控制结构"},
		{"eXH.CrossReference.Label","交�?�引用"},
		{"eXH.CrossReferenceCode.Label","交�?�引用代�?"},
		{"eXH.CrossReferenceDesc.Label","交�?�引用�??述"},
		{"eXH.Data.Label","数�?�"},
		{"eXH.ProcessDate.Label","zh_Process Date"},
//		{"eXH.IF.Label","IF"},
//		{"eXH.IF.Label","IF"},
//		{"eXH.AE.Label","AE"},
//		{"eXH.LTRIM.Label","LTRIM"},
//		{"eXH.RTRIM.Label","RTRIM"},
//		{"eXH.TRIM.Label","TRIM"},
//		{"eXH.SUBSTR.Label","SUBSTR"},
//		{"eXH.REPLACE.Label","REPLACE"},
//		{"eXH.Between.Label","Between"},
//		{"eXH.NotBetween.Label","Not Between"},
//		{"eXH.IN.Label","IN"},
//		{"eXH.NotIN.Label","Not In"},
//		{"eXH.Like.Label","Like"},
//		{"eXH.NotLike.Label","Not Like"},
		{"eXH.Prefix.Label","�?缀"},
		{"eXH.Suffix.Label","�?�缀"},
		{"eXH.PreSuffix.Label","�?�?��?�能"},
		{"eXH.UserDefinedFormat.Label","用户定义格�?"},
//		{"eXH.<>.Label","<>"},
//		{"eXH.=.Label","="},
//		{"eXH.<.Label","<"},
//		{"eXH.>.Label",">"},
//		{"eXH.<=.Label","<="},
//		{"eXH.>=.Label",">="},
//		{"eXH.ISNULL.Label","IS NULL"},
//		{"eXH.ISNOTNULL.Label","IS NOT NULL"},
		{"eXH.Position.Label","�?置"},
		{"eXH.DataInterval.Label","数�?�创作区间[时时：分分]"},
		{"eXH.DataSourceType.Label","数�?��?类型"},
		{"eXH.DateNumber.Label","日期�?��?"},
		{"eXH.DBConnectString.Label","数�?�库的IP地�?�"},
		{"eXH.DBConnectString1.Label","数�?�库端�?�"},
		{"eXH.DBConnectString2.Label","数�?�库TnsName"},
		{"eXH.DBCONNSTRING.Label","数�?�库连接字符串"},
		{"eXH.DBDRIVER.Label","数�?�库驱动程�?"},
		{"eXH.Debug.Label","调试"},
		{"eXH.Debugging.Label","调试"},
		{"eXH.DebugLog.Label","调试日志"},
		{"eXH.DefaultVal.Label","默认值"},
		{"eXH.Defered.Label","Defered"},
		{"eXH.DerivationType.Label","�?生类型"},
		{"eXH.Edit.Label","编辑"},
		{"eXH.EnableInterface.Label","�?�用界�?�"},
		{"eXH.EnableEventFiltering.Label","�?�用事件过滤"},
//		{"eXH.Elements.Label","Elements"},
//		{"eXH.ElementCode.Label","Element Code"},
//		{"eXH.ElementDesc.Label","Element Description"},
//		{"eXH.ElementPos.Label","Element Position"},
//		{"eXH.ElementSEQ.Label","Element Sequence"},
//		{"eXH.ElementType.Label","Element Type"},
//		{"eXH.ElementVal.Label","Element Value"},
		{"eXH.ErrorReject.Label","错误�?拒�?"},
//		{"eXH.EventwiseSegments.Label","Event wise Segments"},
		{"eXH.EventID.Label","事件编�?�"},
		{"eXH.EventName.Label","事件命�??"},
		{"eXH.ExecOrder.Label","执行顺�?"},
		{"eXH.ExecId.Label","段编�?"},
//		{"eXH.ExecNature.Label","Execution Nature"},
		{"eXH.ExpectedValue.Label","期望值"},
//		{"eXH.ExternalAccessionNumber.Label","External Accession Number"},
		{"eXH.FailedProcedure.Label","进程失败"},
		{"eXH.Fax.Label","传真�?�"},
		{"eXH.FaxSettings.Label","传真设置"},
		{"eXH.FieldSeparator.Label","文件分割"},
		{"eXH.File.Label","文件"},
		{"eXH.FileDirectory.Label","文件目录"},
		{"eXH.FileFormat.Label","文件格�?"},
		{"eXH.FileInterval.Label","文件建时间［hh:mm］"},
		{"eXH.FileNamingAPI.Label","文件命�??API"},
//		{"eXH.FileNamingConvention.Label","FileNamingConvention"},
		{"eXH.FileSettings.Label","文件设置"},
		{"eXH.FileType.Label","文件类型"},
		{"eXH.Filtering.Label","过滤"},
		{"eXH.FilterRules.Label","过滤规则"},
		{"eXH.FilterRuleType.Label","过滤规则类型"},
		{"eXH.FilterType.Label","过滤类型"},
		{"eXH.FilterSubType.Label","过滤�?类型"},
		{"eXH.FilterSub1Type.Label","过滤�?类型１"},
		{"eXH.FilterSub2Type.Label","过滤�?类型２"},
		{"eXH.FormatType.Label","格�?类型"},
		{"eXH.FromSleepTime.Label","休眠时间"},
		{"eXH.GeneralOrderMessaging.Label","通用订购信�?�"},
		{"eXH.HL7.Label","HL7标准"},
		{"eXH.HL7Version.Label","HL7标准版"},
		{"eXH.HL7Interface.Label","HL7标准接�?�"},
//		{"eXH.IBAeHis.Label","eHIS"},
		{"eXH.IdleTime.Label","空闲时间[分钟]"},
		{"eXH.Immediate.Label","立�?�"},
		{"eXH.InsertingStatement.Label","�?�入段"},
		{"eXH.Interfaced.Label","接�?�"},
		{"eXH.InterfacedApplications.Label","接�?�应用"},
//		{"eXH.Inbound.Label","Inbound"},
//		{"eXH.InboundAPI.Label","Inbound API"},
//		{"eXH.InboundSettings.Label","Inbound Settings"},
//		{"eXH.InboundDirectory.Label","Inbound Directory Name"},
		{"eXH.InputAPI.Label","输入API"},
		{"eXH.InsertQuery.Label","�?�入查询"},
		{"eXH.InUse.Label","在使用"},
		{"eXH.IPAddress.Label","IP地�?�"},
		{"eXH.JobQueue.Label","作业队列"},
		{"eXH.LastCommnTime.Label","最�?�Commn时间"},
//		{"eXH.LastOutboundRetries.Label","Last Outbound Retries"},
		{"eXH.LastMessageID.Label","上次讯�?�ID"},
		{"eXH.Log.Label","日志"},
		{"eXH.Loaded.Label","负载"},
		{"eXH.LoginName.Label","登录�??"},
		{"eXH.MailSettings.Label","邮件设置"},
		{"eXH.MasterFileNotification.Label","主文件的通知"},
		{"eXH.MaximumRetries.Label","最大的�?试次数"},
		{"eXH.ibaehisCode.Label","eHIS�?"},
		{"eXH.MEDICOMDesc.Label","IBAEHIS�??述"},
		{"eXH.MergedPatientID.Label","�?�并病人编�?�"},
		{"eXH.MessageAmended.Label","�?修正�?�的消�?�"},
		{"eXH.MessageReplayed.Label","消�?��?放"},
		{"eXH.MessageHeaderSegmentSettings.Label","邮件标题部分设置"},
		{"eXH.MessageID.Label","消�?�编�?�"},
		{"eXH.MessageNumber.Label","消�?�数�?"},
		{"eXH.MessageStatus.Label","讯�?�状�?"},
		{"eXH.MessageTriggerEvent.Label","消�?�触�?�事件"},
		{"eXH.MessageTriggerTime.Label","消�?�触�?�"},
		{"eXH.MessageTypes.Label","邮件"},
		{"eXH.ModifiedID.Label","修改编�?"},
		{"eXH.ModifiedDate.Label","修改日期"},
//		{"eXH.ModifiedWSNo.Label","Modified WS No"},
		{"eXH.ModuleId.Label","模�?�编�?�"},
		{"eXH.Module.Label","模�?�"},
		{"eXH.Move.Label","移动"},
		{"eXH.NextProcessDateTime.Label","下一步进程日期"},
		{"eXH.Never.Label","从�?"},
		{"eXH.NoAction.Label","�?采�?�任何行动"},
		{"eXH.NoteRequiredReason.Label","�?需�?�?�由"},
		{"eXH.NonTableValues.Label","�?�表值"},
		{"eXH.ObservationReporting.Label","观察报告"},
//		{"eXH.ODBC.Label","ＯＤＢＣ"},
		{"eXH.ODBCSettings.Label","ＯＤＢＣ设置"},
		{"eXH.OracleTable.Label","oracle表"},
		{"eXH.OracleTableQuery.Label","oracle表查询"},
		{"eXH.OracleTableInsertQuery.Label","oracle表�?�入查询"},
		{"eXH.OracleTableSettings.Label","oracle表设置"},
		{"eXH.OnOrder.Label","订购"},
		{"eXH.OnPatientArrival.Label","订购登记"},
		{"eXH.OperatedBy.Label","�?作"},
		{"eXH.OperatedDate.Label","�?作日期"},
		{"eXH.OtherInterface.Label","其它接�?�"},
		{"eXH.Outbound.Label","输出"},
		{"eXH.OutboundSettings.Label","输出设置"},
		{"eXH.OutboundDirectoryName.Label","输出目录�??称"},
		{"eXH.PatientAllergy.Label","过�?病人信�?�部分"},
//		{"eXH.Permanentpurgeinterval.Label","Permanent Purge Interval [days]"},
		{"eXH.Port.Label","端�?�?�（１�?２５～５�?�?�?）"},
		{"eXH.PortNumber.Label","端�?��?�"},
		{"eXH.Prev.Label","之�?"},
		{"eXH.ProcedureParameters.Label","程�?�?�数"},
		{"eXH.Processed.Label","处�?�"},
		{"eXH.ProcessingID.Label","处�?�编�?�"},
		{"eXH.ProcessBy.Label","处�?�"},
		{"eXH.ProcessEndTime.Label","进程结�?�时间"},
		{"eXH.ProcessStartTime.Label","进程�?�动时间"},
		{"eXH.ProcedureName.Label","进程�??称"},
		{"eXH.Production.Label","生产"},
		{"eXH.ProtocolLinkId.Label","�??义链接标识"},
		{"eXH.ProtocolLinkName.Label","�??议连结�??称"},
		{"eXH.ProtocolType.Label","类型"},
		{"eXH.QueryBased.Label","基于查询"},
		{"eXH.QueryDate.Label","查询日期"},
		{"eXH.QueryID.Label","查询编�?�"},
		{"eXH.QueryStatus.Label","查询状�?"},
		{"eXH.QueryText.Label","文本查询"},
		{"eXH.Referal.Label","推介"},
		{"eXH.Rebuild.Label","�?建"},
		{"eXH.Recently.Label","最近�?�用的内容"},
		{"eXH.Replay.Label","回放"},
		{"eXH.Restricted.Label","�?��?"},
		{"eXH.Retries.Label","�?试"},
		{"eXH.RetryInterval.Label","�?�?试间隔（秒）"},
		{"eXH.Row.Label","行"},
		{"eXH.Scheduling.Label","进度表"},
		{"eXH.Segments.Label","段"},
		{"eXH.SegmentID.Label","段编�?�"},
		{"eXH.SegmentName.Label","段�??称"},
		{"eXH.SegmentType.Label","段类型"},
		{"eXH.SetupMasterCodeMapping.Label","安装主代�?映射"},
		{"eXH.ServerError.Label","�?务器错误"},
		{"eXH.Standardcode.Label","标准代�?"},
		{"eXH.StandardType.Label","�?�准类型"},
		{"eXH.Statement.Label","陈述"},
		{"eXH.SysDefStr.Label","系统定义的结构"},
		{"eXH.MsgStart.Label","消�?��?�动"},
		{"eXH.MsgEnd.Label","消�?�结�?�"},
		{"eXH.PABX.Label","程控交�?�机"},
		{"eXH.SegStart.Label","段�?�动"},
		{"eXH.SegEnd.Label","段完�?"},
		{"eXH.FldSeparator.Label","字段分离"},
		{"eXH.ElmntSeparator.Label","无素分离"},
		{"eXH.StartedbyID.Label","开始编�?�"},
		{"eXH.StopAtCondFailure.Label","�?�留在失败的�?�件"},
		{"eXH.StopDateTime.Label","�?�止日期"},
		{"eXH.StoppedbyID.Label","�?�止编�?�"},
		{"eXH.StatusText.Label","状�?备注"},
		{"eXH.String.Label","字符"},
//		{"eXH.SubElement.Label","Sub Element"},
//		{"eXH.SubElementType.Label","Sub Element Type"},
//		{"eXH.Sub1Element.Label","Sub1 Element"},
//		{"eXH.Sub1ElementType.Label","Sub1 Element Type"},
//		{"eXH.Sub2Element.Label","Sub2 Element"},
//		{"eXH.Sub2ElementType.Label","Sub2 Element Type"},
		{"eXH.Sucessfull.Label","�?功"},
		{"eXH.TableValues.Label","表的值"},
		{"eXH.TCPIP.Label","TCP/IP�??议"},
		{"eXH.TCPIPSettings.Label","TCP/IP 设置"},
//		{"eXH.TCPIPAddress.LabelTCP/IP Address",""},
		{"eXH.Temporarypurgeinterval.Label","临时清洗间隔"},
		{"eXH.Timed.Label","定时"},
		{"eXH.ToSleepTime.Label","休眠时间"},
		{"eXH.TotalMessages.Label","总消�?�"},
		{"eXH.TransferFailed.Label","传输失败"},
		{"eXH.TransferSuccessful.Label","传输完�?"},
		{"eXH.Triggers.Label","触�?�器"},
		{"eXH.TriggeringCondition.Label","触�?��?�件"},
		{"eXH.TriggerEvent.Label","触�?�事件"},
		{"eXH.TriggerName.Label","触�?�器�??"},
		{"eXH.TriggerType.Label","触�?�类型"},
		{"eXH.TriggeringTable.Label","触�?�表"},
		{"eXH.Unprocessed.Label","未处�?�"},
		{"eXH.Unrestricted.Label","未�?制"},
		{"eXH.UpdateQuery.Label","更新查询"},
		{"eXH.ViewEvents.Label","查看事件"},
//		{"eXH.ViewPurgeEvents.Label","View Purge Events"},
//		{"eXH.ViewEpabxEvents.Label","View EPABX Events"},
		{"eXH.ViewMessage.Label","查看信�?�"},
//		{"eXH.ViewDebugLogInformation.Label","View Debug Log Information"},
		{"eXH.ViewCommunicationProcessErrors.Label","查看连接错误"},
//		{"eXH.ViewMessagesAuditLog.Label","View Messages Audit Log"},
//		{"eXH.ViewServerProcessErrors.Label","View Server Process Errors"},
//		{"eXH.SolicitedYN.Label","SolicitedYN"},
//		{"eXH.ProtocolLink.Label","Protocol Link"},
//		{"eXH.AccessionNumber.Label","Accession Number"},
		{"eXH.CommMode.Label","连接模�?"},
		{"eXH.SubDomain.Label","�?网域"},
//		{"eXH.ExtAccNo.Label","External Acc No"},
//		{"eXH.PurgeStatus.Label","Purge Status"},
		{"eXH.ModifiedFacilityID.Label","修改设备"},
		{"eXH.AddedFacility.Label","设备�?�"},
		{"eXH.ModifiedBy.Label","修改"},
		{"eXH.AddedBy.Label","增加"},
		{"eXH.SuccessfullyProcessed.Label","�?功处�?�"},
		{"eXH.TransmissionComplete.Label","传输完�?"},
		{"eXH.SuccessfullyLoaded.Label","�?功载入"},
		{"eXH.MessageDesc.Label","消�?��??述"},
		{"eXH.ADD.Label","增加"},
		{"eXH.Profile.Label","简介"},
		{"eXH.Short Description.Label","简短�??述"},
		{"eXH.Long Description.Label","长�??述"},
		{"eXH.Version Specific.Label","具体版本"},
		{"eXH.Geography specific.Label","特定的地�?�"},
//		{"eXH.Site specific.Label","Site specific"},
		{"eXH.Application specific.Label","具体应用"},
		{"eXH.TransactionLayer.Label","交易层"},
		{"eXH.Profile.Label","简介"},
		{"eXH.ProfileId.Label","简介"},
		{"eXH.Short Description.Label","简短�??述"},
		{"eXH.Long Description.Label","长�??述"},
		{"eXH.Version Specific.Label","具体版本"},
		{"eXH.Geography specific.Label","特定的地�?�"},
		{"eXH.Site specific.Label","具体�?置"},
		{"eXH.Application specific.Label","具体应用"},
		{"eXH.LevelNumber.Label","级别�?��?"},
		{"eXH.FilterTypedesc.Label","过滤类型�??述"},
		{"eXH.FilterTypeQuery.Label","过滤类型查询"},
		{"eXH.FilterSubDesc.Label","过滤�?类型�??述"},
		{"eXH.FiltersubTypeQuery.Label","过滤�?类型查询"},
		{"eXH.ElementQuery.Label","内容查询"},
//		{"eXH.GroupwiseFilterLevel.label","Group wise Filter Level"},
		{"eXH.Group.label","组"},
		{"eXH.FilterType.Label","过滤类型"},
		{"eXH.FilterSubType.Label","过滤�?类型"},
		{"eXH.InterfaceDomain.Label","界�?�域"},
		{"eXH.Solicited.Label","请求"},
		{"eXH.Repetition_Appl.Label","�?�?适用"},
		{"eXH.MessageControl.Label","消�?�控制"},
		{"eXH.FileCtrlType.Label","文件控制类型"},
		{"eXH.FileHeader.Label","文件头"},
		{"eXH.FileFooter.Label","文件尾"},
		{"eXH.TableBased.Label","基于表"},
//		{"eXH.API.Label","ＡＰＩ"},
		{"eXH.SubAPI.Label","�?API"},
		{"eXH.OutboundLog.Label","出站记录"},
		{"eXH.InboundLog.Label","呼入记录"},
		{"eXH.Protocol.Label","议定书"},
		{"eXH.DataGroup.Label","数�?�组"},
		{"eXH.AddDetails.Label","购买明细"},
//		{"eXH.NewFacility.Label","New Facility"},
//		{"eXH.SelectFromSM_PARAM.Label","Select From SM_PARAM"},
		{"eXH.Segment.Label","段"},
		{"eXH.RS232.Label","RS232界�?�"},
		{"eXH.SMS.Label","短信"},
//		{"eXH.FoxPro.Label","FoxPro Dbf"},
		{"eXH.XML.Label","XML"},
		{"eXH.MDB.Label","MDB"},
		{"eXH.Communicated.Label","连通"},
		{"eXH.NonCommunicated.Label","�?�连通"},
		{"eXH.AddIntDataCriteria.Label","新增接�?�数�?�标准"},
		{"eXH.QueryOption.Label","查询选项"},
		{"eXH.QueryProcessed.Label","查询处�?�"},
		{"eXH.QueryInitiated.Label","�?始化查询"},
		{"eXH.TransmissionError.Label","传动误差"},
		{"eXH.Validate.Label","验�?"},
		{"eXH.TotalLevels.Label","总级别"},
		{"eXH.DerivationLayer.Label","推导层"},
		{"eXH.EncodingLayer.Label","编�?层"},
//		{"eXH.RearrangementLayer.Label","???"},
		{"eXH.StandardLayer.Label","标准层"},
//		{"eXH.EncodDecodeAlg.Label","ENCOD_DECOD_ALGORITH"},
		{"eXH.UserDefStr.Label","用户自定义结构"},
//		{"eXH.SMPARAM.Label","Select From SM_PARAM"},
		{"eXH.Domain.Label","域"},
		{"eXH.Entity.Label","实体"},
		{"eXH.DataSourceMapping.Label","数�?��?的映�?"},
		{"eXH.Input.Label","输入"},
		{"eXH.QueryError.Label","查询错误"},
		{"eXH.AddField.Label","增加字段"},
		{"eXH.AddWhrClause.Label","增加where字�?�"},
//		{"eXH.FacilityBased.Label","Facility Based"},
		{"eXH.SelectedCols.Label","选择列"},
		{"eXH.AllCols.Label","所有列"},
		{"eXH.MasterName.Label","主表�??"},
		{"eXH.EncodingAlgorithem.Label","编�?算法"},
		{"eXH.AddProtocolLink.Label","增加�??议链接"},
		{"eXH.GlobalReferences.Label","全�?��?�考"},
		{"eXH.DataFieldRef.Label","数�?�域�?�?�考"},
		{"eXH.Message/QryID.Label","消�?�/查询标识"},
//		{"eXH.OutboundTrig.Label","Outbound Triggers"},
		{"eXH.EventCtrlMapping.Label","事件控制映射"},
//		{"eXH.OutboundEvents.label","Outbound Events"},
//		{"eXH.InboundEvents.label","Inbound Events"},
		{"eXH.SuccessfulCommunication.Label","�?功通信"},
		{"eXH.ResponseAcknowledged.Label","回应确认"},
		{"eXH.ResponseRejected.Label","拒�?�?应"},
		{"eXH.ProcessingError.Label","处�?�错误"},
		{"eXH.TransmissionPending.Label","待传输"},
		{"eXH.ProcessingPending.Label","待处�?�"},
		{"eXH.LoadingSuccessful.Label","待处�?�"},
		{"eXH.TransmissionSuccessful.Label","传输�?功"},
		{"eXH.TransmissionError.Label","传输错误"},
		{"eXH.ItemClass.Label","项目分类"},
		{"eXH.ItemType.Label","项目类型"},
		{"eXH.DefaultAttributes.Label","默认属性"},
//Newly Added legends on 21/01/09
{"eXH.AccessionNumber.Label","到达编�?�"},
{"eXH.AckDir.Label","直接接收"},
{"eXH.Acknowledged.Label","收到"},
{"eXH.AcknowlegementType.Label","收到类型"},
{"eXH.AddedWSNo.Label","增加工作站编�?�"},
{"eXH.ApplicationwiseSegments.Label","应用外部段"},
{"eXH.Defered.Label","延期"},
{"eXH.ElementCode.Label","信�?�代�?"},
{"eXH.ElementDesc.Label","信�?��??述"},
{"eXH.ElementPos.Label","信�?��?置"},
{"eXH.Elements.Label","信�?�字段"},
{"eXH.ElementSEQ.Label","信�?��?列�?�"},
{"eXH.ElementType.Label","信�?�类型"},
{"eXH.ElementVal.Label","信�?�值"},
{"eXH.EncodDecodeAlg.Label","编�?/解�?算法"},
{"eXH.EventwiseSegments.Label","内部事件"},
{"eXH.ExecNature.Label","执行"},
{"eXH.ExtAccNo.Label","外部应用编�?�"},
{"eXH.ExternalAccessionNumber.Label","外部应用编�?�"},
{"eXH.FacilityBased.Label","基于医院"},
{"eXH.FileNamingConvention.Label","文件命�??约定"},
{"eXH.GroupwiseFilterLevel.label","信�?�过滤"},
{"eXH.Inbound.Label","接收端"},
{"eXH.InboundAPI.Label","接收端应用程�?接�?�"},
{"eXH.InboundDirectory.Label","内部直接命�??"},
{"eXH.InboundEvents.label","接收端事件"},
{"eXH.InboundSettings.Label","接收端�?置"},
{"eXH.LastOutboundRetries.Label","最�?��?��?测试"},
{"eXH.ModifiedWSNo.Label","更改客户端编�?�"},
{"eXH.NewFacility.Label","新部门"},
{"eXH.OutboundEvents.label","�?��?端事件"},
{"eXH.OutboundTrig.Label","�?��?端触�?�"},
{"eXH.Permanentpurgeinterval.Label","永久删除间隔[天]"},
{"eXH.ProtocolLink.Label","链接�??议"},
{"eXH.PurgeStatus.Label","删除状�?"},
{"eXH.Site specific.Label","特定地点"},
{"eXH.SolicitedYN.Label","请求 Y/N"},
{"eXH.Sub1Element.Label","Sub1 Element"},
{"eXH.Sub1ElementType.Label","Sub1 Element Type"},
{"eXH.Sub2Element.Label","Sub2 Element"},
{"eXH.Sub2ElementType.Label","Sub2 Element Type"},
{"eXH.SubElement.Label","Sub Element"},
{"eXH.SubElementType.Label","Sub Element Type"},
{"eXH.TCPIPAddress.LabelTCP/IP Address","TCP/IP地�?�"},
{"eXH.ViewDebugLogInformation.Label","查看调试信�?�记录"},
{"eXH.ViewEpabxEvents.Label","查看 EPABX相关接�?�"},
{"eXH.ViewMessagesAuditLog.Label","查看邮件审计"},
{"eXH.ViewPurgeEvents.Label","查看清除事件"},
{"eXH.ViewServerProcessErrors.Label","查看�?务器进程错误"},
{"eXH.WEBSERIVCE.Label","zh_Webservice"},
{"eXH.SAPFunctions.Label","zh_SAP Functions"},
{"eXH.ErrorCode.Label","zh_Error Code"},
{"eXH.SSMonDPErr.Label","zh_SS Monthly Data Process Errors"},
{"eXH.CustomerGroup.Label","zh_Customer Group"},
{"eXH.ProcForDate.Label","zh_Process for date"},
{"eXH.ClearErrors.Label","zh_Clear Errors"},
{"eXH.AUTH_USER_ID.Label","zh_Authorized UserID"},
{"eXH.LAST_UPLOAD_DATE.Label","zh_Last Upload Date"},
{"eXH.DATA_UPLOAD.Label","zh_Data Upload"},
{"eXH.PROC_SOC_SEC_DATA.Label","zh_Process Social Security Data"},
{"eXH.CNF_ARC_SOC_SEC_DATA_PROC.Label","zh_Confirm and Archive Social Security Data Process"},
{"eXH.RP_OPEN_ENC_PRIV_UPDATE.Label","zh_Report Open Encounters During Privilege Update"},
{"eXH.RP_UNREG_SS_PAT_PRIV_UPDATE.Label","zh_Report Unregistered SS Patients During Privilege Update"},
{"eXH.OPD_SOC_SEC_PRIV_USAGE_MDB.Label","zh_OPD Social Security Privilege Usage Output(MDB file)"},
{"eXH.RP_IPD_SOC_SEC_PRIV_USAGE.Label","zh_Report IPD Social Security Privilege Usage Output"},
{"eXH.OP_Mon_Year.Label","zh_Output Month/Year"},
{"eXH.LAST_CFM_DATE.Label","zh_Last Confirmed Date"},
{"eXH.PAYER_CODE.Label","zh_Payer Code"},
{"eXH.NO_OF_PAT_PRIV.Label","zh_NO OF PATIENTS PRIVILEGE"},
{"eXH.EXTENDED.Label","zh_Extended"},
{"eXH.REMOVED.Label","zh_Removed"},
{"eXH.ADDED.Label","zh_Added"},
{"eXH.DATA_BYPASSED.Label","zh_Data Bypassed"},
{"eXH.PAYER_GROUP.Label","zh_Payer Group"},
{"eXH.POL_NUM_IND.Label","zh_Policy Number Indicator"},
{"eXH.REF_SUB_HOSP.Label","zh_Ref-SubHospital"},
{"eXH.SMAS_NAT_ID_NO.Label","zh_Same as National ID Number"},
{"eXH.SMAS_PAT_ID.Label","zh_Same as Patient ID"},
{"eXH.FIX_STR.Label","zh_Fixed String"},
{"eXH.UPLOAD.Label","zh_Upload"},
{"eXH.CONFIRMATION.Label","zh_Confirmation"},
{"eXH.DAILY_INVOICE.Label","zh_Daily Invoice"},
{"eXH.GEN_ACCPAC_INV_CSV_FILE.Label","zh_Generate ACCPAC Invoice as CSV file"},
{"eXH.CONSOLIDATE.Label","zh_Consolidate"},
{"eXH.REPLY_FILE_ID.Label","Reply File ID"},
{"eXH.REPLY_DATE.Label","Reply Date"},
{"eXH.DOC_REF_NO.Label","Document Ref No"},
{"eXH.STUDY_LOCATION.Label","zh_Study Location"},
{"eXH.COUNTER_NAME.Label","zh_Counter Name"},
{"eXH.QMS_SERVICE_ID.Label","zh_QMS Service ID"}
};
}
