/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eAE.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eAE.Abdomen.label","腹部"},
		{"eAE.Absent.label","缺席"},
		{"eAE.AccidentCase.label","事故案例"},
		{"eAE.AccidentType.label","事故类型"},
		{"eAE.AccompaniedBy.label","伴�?�?�"},
		{"eAE.AddedBy.label","增加"},
		{"eAE.AddedDateTime.label","新增日期时间"},
		{"eAE.AddrofEscortAmbulanceService.label","护�?地�?��?救护车�?务"},
		{"eAE.AEDetails.label","急诊细节"},
		{"eAE.AffectedSite.label","影�?�?置"},
		{"eAE.AgeLimits.label","年龄�?制"},
		{"eAE.AirEntryRight.label","？？？?"},
		{"eAE.Airway.label","气�?�（导气管？）"},
		{"eAE.AllowbackdatingofVisitDateTime.label","�?许回访日期�?时间"},
		{"eAE.AmbulanceDetails.label","救护详情"},
		{"eAE.AssessmentDateTime.label","评估日期�?时间"},
		{"eAE.AssignBedBaysForTreatmentArea.label","分�?治疗的床�?�?区域"},
		{"eAE.AssignedDateTime.label","指定日期�?时间"},
		{"eAE.AssignedPractitioner.label","指定医生"},
		{"eAE.AssignTreatArea.label","分�?治疗区域"},
		{"eAE.AssignTreatmentArea.label","分�?治疗区域"},
		{"eAE.AttendanceDate.label","出席日期"},
		{"eAE.AttendanceDateTo.label","出席日期 到"},
		{"eAE.AttendDateFrom.label","出席日期 从"},
		{"eAE.Autoclosed.label","自动关闭"},
		{"eAE.BedBay.label","床�?�?区域"},
		{"eAE.BedBayAvailabilityChart.label","床�?�?区域的�?�用图表"},
		{"eAE.BedBayNo.label","床�?�?区域�?�"},
		{"eAE.BedBayStatus.label","床�?�?区域状�?"},
		{"eAE.BedBayType.label","床�?�?区域类型"},
		{"eAE.BedBayTypeCode.label","床�?�?区域代�?"},
		{"eAE.BedBayTypeDesc.label","床�?�?区域�??述"},
		{"eAE.BillingInterface.label","结算界�?�"},
		{"eAE.BillingInterfaced.label","结算界�?�"},
		{"eAE.Blood.label","血液"},
		{"eAE.BloodAtMeatus.label","在导管的血液？？"},
		{"eAE.Blunt.label","�?的？感觉迟�?的？"},
		{"eAE.BonyCrepitus.label","骨摩擦音"},
		{"eAE.BonyCrepitusPos.label","骨摩擦音�?置"},
		{"eAE.Brachial.label","肱"},
		{"eAE.BreathDensity.label","烟密度？"},
		{"eAE.Breathing.label","呼�?�"},
		{"eAE.BreathSound.label","呼�?�音"},
		{"eAE.BreathType.label","呼�?�型"},
		{"eAE.Brisk.label","活跃"},
		{"eAE.BulbocavemousReflex.label","�?�海绵体�??射"},
		{"eAE.Burn.label","烧伤"},
		{"eAE.CapacityRefill.label","自动注射能力？？"},
		{"eAE.CapBloodSugar.label","CAP??血糖"},
		{"eAE.CapillaryBloodSugar.label","毛细血管糖"},
		{"eAE.CaseDetails.label","案例明细"},
		{"eAE.CaseofMLC.label","医疗法律顾问案例"},
		{"eAE.Catheterin.label","导管"},
		{"eAE.CauseofAccident.label","事故原因"},
		{"eAE.CervicalCollar.label","颈椎项圈"},
		{"eAE.Chest.label","胸"},
		{"eAE.ChestTubeinSitu.label","胸管原�?"},
		{"eAE.ChestTubeinSituVolLeft.label","胸管原�? 左声�?�"},
		{"eAE.ChestTubeinSituVolRight.label","胸管原�? �?�声�?�"},
		{"eAE.Circulation.label","循环"},
		{"eAE.Cold.label","冷"},
		{"eAE.ConditionCase.label","�?�件�?案例"},
		{"eAE.ContactTelNo.label","�?�系电�?"},
		{"eAE.Convulsion.label","惊厥"},
		{"eAE.CreateAttendanceDetails.label","创建出席明细？"},
		{"eAE.CSpineFracture.label","颈椎骨折"},
		{"eAE.CSpineTenderness.label","颈椎压痛"},
		{"eAE.Cutoffperiodforincluding.label","中断�?段就诊的时期"},
		{"eAE.Cyanotic.label","紫绀型"},
		{"eAE.DateTimeIn.label","日期/时间在"},
		{"eAE.Deep.label","深奥的"},
		{"eAE.DegreeofBurn.label","烧伤度"},
		{"eAE.Density.label","密度"},
		{"eAE.DetailsOfTheCaseMLCCase.label","医疗法律顾问案例明细"},
		{"eAE.Diffuse.label","弥漫性"},
		{"eAE.Diminished.label","�?少"},
		{"eAE.DisabilityCNS.label","残疾中枢神�?系统"},
		{"eAE.DisasterArea.label","�?�伤区域"},
		{"eAE.DisasterPatientRegistration.label","�?�伤病人登记"},
		{"eAE.DisasterType.label","�?�伤类型"},
		{"eAE.DisasterTypeCode.label","�?�伤类型代�?"},
		{"eAE.DisasterTypeDesc.label","�?�伤类型�??述"},
		{"eAE.DispositionCodeFrom.label","�?置代�? 从"},
		{"eAE.DispositionCodeTo.label","�?置代�? 到"},
		{"eAE.DispositionDate.label","�?置日期"},
		{"eAE.DispositionDateFrom.label","�?置日期 从"},
		{"eAE.DispositionDateTo.label","�?置日期 到"},
		{"eAE.DispositionTypeCode.label","�?置类型代�?"},
		{"eAE.Distended.label","腹胀"},
		{"eAE.Doneduring.label","在 期间所�?�"},
		{"eAE.Dry.label","干燥的"},
		{"eAE.Easy.label","容易的"},
		{"eAE.ECGMonitorBP.label","心电监护仪"},
		{"eAE.EID.label","内�?�"},
		{"eAE.Emergencyclinic.label","应急诊所"},
		{"eAE.Equal.label","等于"},
		{"eAE.EscAmbulanceContNo.label","护�?�?救护车 �?�系�?�"},
		{"eAE.Escort.label","护�?"},
		{"eAE.EscortDetail.label","护�?详情"},
		{"eAE.EscortName.label","护�?�??称"},
		{"eAE.ExamDateTime.label","考试 日期�?时间"},
		{"eAE.ExaminedBy.label","审查"},
		{"eAE.ExistingDetails.label","已存明细"},
		{"eAE.ExistingPatientID.label","已存病人明细"},
		{"eAE.ExpLengthOfStay.label","进出�?�的�?�留时间？？"},
		{"eAE.Extremities.label","四肢"},
		{"eAE.EyeResponse.label","眼�??应"},
		{"eAE.EyeResponseGCSDescription.label","眼�??应评分说明"},
		{"eAE.FacialFracture.label","�?�部骨折"},
//		{"eAE.FB.label","？"},
//		{"eAE.FBC.label","？"},
		{"eAE.Femoral.label","股骨"},
		{"eAE.FlailSegment.label","段连枷"},
		{"eAE.FlailSegPos.label","连枷部分的�?置"},
		{"eAE.Fracture.label","骨折"},
		{"eAE.FractureDislocation.label","骨折脱�?"},
		{"eAE.FracturesList.label","骨折列表"},
		{"eAE.GCS.label","格拉斯哥�?迷评分"},
		{"eAE.GCSCategory.label","GCS类别"},
		{"eAE.GCSCode.label","GCS代�?"},
		{"eAE.GCSCodes.label","GCS代�?"},
		{"eAE.GCSDesc.label","GCS�??述"},
		{"eAE.GCSDescription.label","GCS�??述"},
		{"eAE.GCSforResponse.label","GCS的�??应"},
		{"eAE.GCSforResponseCode.label","GCS的�??应代�?"},
		{"eAE.GCSResponseCode.label","GCS�??应代�?"},
		{"eAE.GCSResponseDesc.label","GCS�??应�??述"},
		{"eAE.GCSScore.label","GCS评分分数"},
		{"eAE.GenitoUrinary.label","生殖泌尿"},
		{"eAE.Good.label","良好的"},
		{"eAE.GrowthDevelMileStoneforAge.label","年龄的生长�?�?�展里程碑"},
//		{"eAE.GTubeNasal.label","G-Tube Nasal"},
//		{"eAE.GTubeOral.label","G-Tube Oral"},
//		{"eAE.GynaecDetail.label","Gynaec Detail"},
//		{"eAE.GynaecDetails.label","Gynaec Details"},
//		{"eAE.Haematura.label","Haematura"},
		{"eAE.HeadNeck.label","头颈部"},
		{"eAE.Hyper.label","超"},
		{"eAE.Immobilization.label","固定"},
		{"eAE.ImmobilizationCode.label","固定�?"},
		{"eAE.ImmobilizationDesc.label","固定�?�??述？？？"},
		{"eAE.ImmunizationuptoDate.label","�?疫行动日期"},
		{"eAE.Impaired.label","�?��?�"},
		{"eAE.IncludeCheckOutPat.label","包括检查病人"},
		{"eAE.Infant.label","婴幼儿"},
		{"eAE.InitialManagement.label","�?步管�?�"},
		{"eAE.InjuryCategory.label","�?�伤类别"},
		{"eAE.InjuryCategoryCode.label","�?�伤类别代�?"},
		{"eAE.InjuryCategoryDesc.label","�?�伤类别说明"},
		{"eAE.InjurySubcategory.label","�?�伤分类"},
		{"eAE.InjurySubcategoryCode.label","�?�伤分类代�?"},
		{"eAE.InjurySubcategoryDesc.label","�?�伤分类说明"},
		{"eAE.InjuryType.label","�?�伤类型"},
		{"eAE.InvokeVitalSignsfromQueue.label","从队列中调用生命体�?"},
		{"eAE.Irregular.label","�?规则"},
		{"eAE.JVP.label","颈�?�脉脉冲(jugular venous pulse)"},
		{"eAE.Laboured.label","辛勤"},
		{"eAE.LastVisitWithin24Hrs.label","上次访问在24�?时内。详情"},
		{"eAE.LimbColour.label","肢体颜色"},
		{"eAE.LLQ.label","低延迟队列（Low Latency Queuing）？"},
		{"eAE.LMPDate.label","LMP日期（调控细胞增殖和细胞凋亡�?��?效应的分�?机制）"},
		{"eAE.LocationofAccident.label","事故地点"},
		{"eAE.LUQ.label","LUQ"},
//		{"eAE.MaxAgeofcapturingpediatric.label","Max Age of the patient for capturing pediatric details"},
//		{"eAE.MaxNoofdayallowedforrevattenddetls.label","Max No of days allowed for revising attendance details"},
//		{"eAE.MaxNoofdaysallowedforRevising.label","Max No of days allowed for Revising Attendance"},
//		{"eAE.MechaofSubInjury.label","Mechanism of Sub-Injury"},
//		{"eAE.MinAgeofcapturingpediatric.label","Min Age of the patient for capturing pregnancy details"},
//		{"eAE.Motor Response GCS Description.label","Motor Response GCS Description"},
//		{"eAE.MotorResponse.label","Motor Response"},
		{"eAE.MovementHistory.label","�?动�?�"},
		{"eAE.NameofEscortService.label","护�?�??称/救护车�?务"},
		{"eAE.NasalAirway.label","鼻气�?�"},
		{"eAE.NewDetails.label","新细节"},
		{"eAE.NewPatientID.label","新病人编�?�"},
		{"eAE.NoControl.label","失控"},
		{"eAE.NoControlOn.label","失控"},
		{"eAE.NonCritical.label","�?�关键"},
		{"eAE.NonResp.label","�?回应"},
		{"eAE.NoofPatients.label","患者�?�"},
		{"eAE.NormalBedBay.label","标准床�?�?区域"},
		{"eAE.NursingDetails.label","护�?�细节"},
		{"eAE.Obstructed.label","阻挠"},
		{"eAE.ObstructedBy.label","阻挠"},
		{"eAE.OneBed.label","至少选择一个床�?"},
		{"eAE.OpenPneumothroax.label","开放性气胸"},
		{"eAE.OpenPneumothroaxPos.label","开放性所胸�?置"},
		{"eAE.OpentoAllPracLocation.label","对所有医生开放"},
		{"eAE.OpenWound.label","伤�?�"},
		{"eAE.OpenWoundPos.label","开放性伤�?�的�?置"},
		{"eAE.OpenWounds.label","开放性伤�?�"},
		{"eAE.OralAirway.label","�?�腔气�?�"},
		{"eAE.OrderByPriority.label","优先级"},
		{"eAE.OTDateTime.label","手术日期�?时间"},
		{"eAE.Pale.label","范围？"},
		{"eAE.PatientManagement.label","病人管�?�"},
		{"eAE.PatientPositionCode.label","病人身份代�?"},
		{"eAE.PatientPositionduringIncident.label","在事件中病人的身份"},
		{"eAE.PatientPriority.label","病人级别（优先�?�）"},
		{"eAE.PatientPriorityCode.label","病人级别代�?"},
		{"eAE.PatientsSeenDate.label","病人已就诊日期"},
		{"eAE.PatientsSeenDateFrom.label","病人已就诊日期 从"},
		{"eAE.PatientsSeenDateTo.label","病人已就诊日期 到"},
		{"eAE.PatientTypeFrom.label","病人类型： 从"},
		{"eAE.PatientTypeTo.label","病人类型：到"},
		{"eAE.PatPositionDesc.label","病人身份�??述"},
//		{"eAE.PatSecondaryTriageHistory.label","Patient Secondary Triage History"},
		{"eAE.Pedal.label","足的"},
		{"eAE.PediatricDetails.label","儿科情况"},
		{"eAE.Pelvis.label","骨盘"},
		{"eAE.Penetrating.label","穿�?能力"},
		{"eAE.Physician.label","医生"},
		{"eAE.Popliteal.label","腘"},
		{"eAE.PositionDesc.label","�?置�??述"},
		{"eAE.PostalCodeNo.label","邮政编�?"},
		{"eAE.Practitionerfor.label","从业者的"},
		{"eAE.PractitionerIDFrom.label","执业编�?� 从："},
		{"eAE.PractitionerIDTo.label","执业编�?� 到："},
		{"eAE.PreviousSurgery.label","术�?"},
		{"eAE.PrimaryAssessment.label","�?步评估"},
		{"eAE.PrimaryTriageDetails.label","主分�?细节"},
		{"eAE.PriorityDesc.label","优先�?��??述"},
		{"eAE.Prostrate.label","俯�?�"},
		{"eAE.ProtectiveDevice.label","�?护装置"},
		{"eAE.ProtectiveDeviceCode.label","�?护装置代�?"},
		{"eAE.ProtectiveDeviceDesc.label","�?护装置�??述"},
//		{"eAE.PseudoBedBay.label","Pseudo Bed/Bay"},
//		{"eAE.PseudoBedBays.label","Pseudo Bed/Bays"},
//		{"eAE.PseudoBeds.label","Pseudo Beds"},
//		{"eAE.PulsesRight.label","Pulses Right"},
		{"eAE.PupilReaction.label","瞳孔�??应"},
		{"eAE.PupilSize.label","瞳孔大�?"},
		{"eAE.PupilSizeLeft.label","左侧瞳孔大�?"},
		{"eAE.Radial.label","径�?�"},
		{"eAE.Reasons.label","原因"},
		{"eAE.ReassignTreatArea.label","�?新治疗领域"},
		{"eAE.RecordedDetails.label","详细记录"},
		{"eAE.Rectal.label","直肠癌"},
		{"eAE.RectalInjury.label","直肠�?�伤"},
		{"eAE.Reduced.label","�?少"},
		{"eAE.RegistrationType.label","注册类型"},
		{"eAE.Relation.label","关系"},
		{"eAE.ReservedBedBay.label","�?留床�?"},
		{"eAE.ReservedUntil.label","�?留直到"},
		{"eAE.ReserveUntil.label","�?留直到"},
		{"eAE.ResidenceAreaCodeFrom.label","�?宅区域代�? 从"},
		{"eAE.ResidenceAreaCodeTo.label","�?宅区域代�? 到"},
		{"eAE.Respiratory.label","呼�?�"},
		{"eAE.RespiratoryRate.label","呼�?�速率"},
		{"eAE.ResponseToPain.label","对疼痛的�??应"},
		{"eAE.ResponseToVerbal.label","言语�??应"},
		{"eAE.Responsiveness.label","�??应"},
		{"eAE.Resuscitation.label","�?�?"},
		{"eAE.RibFracture.label","肋骨骨折"},
		{"eAE.RibFracturePos.label","肋骨骨折的立场"},
		{"eAE.Right.label","�?�边"},
		{"eAE.Rigidity.label","刚度"},
		{"eAE.RLQ.label","�?�下腹（Right lower quadrant ）"},
//		{"eAE.RTA.label","？？？"},
		{"eAE.RUQ.label","�?�上腹（Right Upper Quadrant ）"},
		{"eAE.ScoreType.label","分数类型"},
		{"eAE.SecondaryTriage.label","二级分类"},
		{"eAE.Shallow.label","浅层"},
		{"eAE.SkinCondition.label","皮肤状况"},
		{"eAE.Sluggish.label","呆滞"},
		{"eAE.SpareBedBay.label","备用床"},
		{"eAE.Spine.label","脊柱"},
//		{"eAE.SpO2.label","？？？"},
		{"eAE.Spontaneous.label","自�?�性"},
		{"eAE.Stable.label","稳定"},
		{"eAE.SubCategoryCode.label","�?类别代�?"},
//		{"eAE.SubEmphysema.label","？？。肺气肿"},
		{"eAE.Suprapubic.label","耻骨"},
		{"eAE.Symptom.label","症状"},
		{"eAE.SystolicBP.label","收缩压"},
		{"eAE.Tenderness.label","嫩"},
		{"eAE.Tense.label","紧张"},
		{"eAE.TetanusVaccination.label","接�?破伤风疫苗"},
		{"eAE.Tone.label","声调"},
		{"eAE.Trachea.label","气管"},
		{"eAE.TracheaMidlineShifted.label","气管中线转移"},
		{"eAE.TracheaMidlineShiftTo.label","气管中线转移到："},
		{"eAE.TraumaAssessment.label","创伤评估"},
		{"eAE.TraumaDetails.label","外伤详情"},
		{"eAE.TraumaScore.label","创伤评分"},
		{"eAE.TreatmentAreaCode.label","治疗区域代�?"},
		{"eAE.TreatmentAreaDesc.label","治疗区域说明"},
		{"eAE.TreatmentAreaforLocation.label","治疗区域的�?置"},
		{"eAE.Triage.label","分�?"},
		{"eAE.UnassignedList.label","未指定�??�?�"},
		{"eAE.Unstable.label","�?稳定"},
		{"eAE.Vaccinated.label","接�?疫苗"},
		{"eAE.ValuableDetails.label","有用的详细资料"},
		{"eAE.Vascular.label","血管"},
//		{"eAE.VehicleRegNo.label","Motor Vehicle Registration No"},
		{"eAE.VerbalResponse.label","言语�??应"},
		{"eAE.VerbalResponseGCSDescription.label","言语�??应GCS说明"},
		{"eAE.VisitWithin24Hrs.label","24�?时内就诊"},
//		{"eAE.VolumeLeft.label","Volume Left"},
//		{"eAE.VolumeRight.label","Volume Right"},
		{"eAE.Vomits.label","呕�??"},
		{"eAE.Warm.label","暖和的"},
		{"eAE.Consulted.label","咨询"},
		{"eAE.AwaitingTreatment.label","等待处�?�"},
		{"eAE.AssignedtoTreatmentArea.label","分�?到治疗领域"},
		{"eAE.UndergoingTreatment.label","接�?�治疗"},
		{"eAE.ConsultationStarted.label","就诊开始"},
		{"eAE.TriageDateTime.label","分�?日期时间"},
		{"eAE.Screening.label","筛选"},
		{"eAE.MainComplaintAndKeyFindings.label","主投诉�?�关键�?�现"},
		{"eAE.NewProblems.label","新问题"},
//		{"eAE.TickApplicableCategory.label","？？？"},
		{"eAE.SpecialInvestigations.label","特别调查"},
		{"eAE.ReferToOtherFacility.label","�??�?�其它设施"},
		{"eAE.HealthcareProfessional.label","�?�生�?�?�专业"},
		{"eAE.PleaseSpecify.label","请指定"},
		{"eAE.Noproblemexists.label","�?存在问题"},
		{"eAE.DateTimeOfAccident.label","事件日期�?时间"},
		{"eAE.PlaceOfAccident.label","事故地点"},
		{"eAE.MotorVehicleAccident.label","机动车事故"},
		{"eAE.LocationOfLastVisit.label","上次就诊地点"},
		{"eAE.ScreeningData.label","筛选数�?�"},
		{"eAE.TriageLevel.label","分类级别"},
		{"eAE.TriageNurse.label","护士"},
		{"eAE.NursingQuickLook.label","急速护�?�"},
		{"eAE.NonAppointment.label","�?�预约"},
		{"eAE.OPD.label","门诊部"},
//		{"eAE.FastTrack.label","Fast track"},
//		{"eAE.TriageTime.label","Triage Time"},
//		{"eAE.NursingTriage.label","Nursing Triage"},
		{"eAE.BW.label","体�?"},
//		{"eAE.GmKg.label","gm/KG"},
//		{"eAE.Ht.label","Ht"},
//		{"eAE.T.label","T"},
//		{"eAE.P.label","P"},
//		{"eAE.RR.label","RR"},
//		{"eAE.BP.label","BP"},
//		{"eAE.mmHg.label","mmHg"},
//		{"eAE.02Sat.label","O2 Sat"},
//		{"eAE.O.label","O"},
///		{"eAE.I.label","I"},
		{"eAE.ExaminationTime.label","考试时间"},
		{"eAE.PrimarySurvey.label","�?步调查"},
		{"eAE.SecondarySurvey.label","二次调查"},
		{"eAE.PatientAllergies.label","过�?症患者"},
		{"eAE.NursingTreatment.label","护�?�治疗"},
		{"eAE.AllowRegAttendInpat.label","�?许病人注册�?院"},
		{"eAE.Consultation.label","咨询"},
//		{"eAE.EnableAccess.label","Enable Access Rights for Emergency Queue Management"}
//Newly added labels on 21/01/09
{"eAE.AirEntryRight.label","�?�气�?�"},
{"eAE.CapBloodSugar.label","毛细血管血糖"},
{"eAE.EnableAccess.label","�?许访问急诊管�?�队列的�?��?"},
{"eAE.FastTrack.label","快速通�?�"},
{"eAE.FB.label","空腹血糖"},
{"eAE.FBC.label","全血细胞计数"},
{"eAE.GTubeNasal.label","胃管-通过鼻"},
{"eAE.GTubeOral.label","胃管-通过�?�腔"},
{"eAE.GynaecDetail.label","妇产科细节"},
{"eAE.GynaecDetails.label","妇产科细节"},
{"eAE.Haematura.label","血尿"},
{"eAE.ImmobilizationDesc.label","固定�??述"},
{"eAE.MaxAgeofcapturingpediatric.label","�?�以�?��?�儿科细节的最大年龄"},
{"eAE.MaxNoofdayallowedforrevattenddetls.label","修改出席细节的最大天数"},
{"eAE.MaxNoofdaysallowedforRevising.label","�?�以修改出勤的最大天数"},
{"eAE.MechaofSubInjury.label","分�?�伤机制"},
{"eAE.MinAgeofcapturingpediatric.label","最低年龄的病人�?��?�怀孕细节"},
{"eAE.Motor Response GCS Description.label","�?动�??应GSC�??述"},
{"eAE.MotorResponse.label","�?动�??应"},
{"eAE.NursingTriage.label","护士分�?"},
{"eAE.PatSecondaryTriageHistory.label","病人的二次分�?"},
{"eAE.PseudoBedBay.label","床�?"},
{"eAE.PseudoBedBays.label","床�?"},
{"eAE.PseudoBeds.label","床�?"},
{"eAE.PulsesRight.label","�?�脉冲"},
{"eAE.RTA.label","RTA"},
{"eAE.SpO2.label","Sp02"},
{"eAE.SubEmphysema.label","皮下气肿"},
{"eAE.TickApplicableCategory.label","选择（剔除）适用类型"},
{"eAE.TriageTime.label","分�?时间"},
{"eAE.VehicleRegNo.label","机动车辆的登记�?��?"},
{"eAE.VolumeLeft.label","左肺声"},
{"eAE.VolumeRight.label","�?�肺声"},

};
}
