/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eAE.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
	    {"eAE.Abdomen.label","البطن"},
		{"eAE.Absent.label","غائب"},
		{"eAE.AccidentCase.label","حالة الحادث"},
		{"eAE.AccidentType.label","نوع الحادث"},
		{"eAE.AccompaniedBy.label","مصحوبا ب"},
		{"eAE.AddedBy.label","أضيفت من قبل"},
		{"eAE.AddedDateTime.label","تاريخ الإضافة"},
		{"eAE.AddrofEscortAmbulanceService.label","عنوان المرافقة / خدمة الإسعاف"},
		{"eAE.AEDetails.label","عنوان مرافقة التفاصيل"},
		{"eAE.AffectedSite.label","الموقع المتأثر"},
		{"eAE.AgeLimits.label","حدود السن"},
		{"eAE.AirEntryRight.label","حق دخول الهواء"},
		{"eAE.Airway.label","قناة هوائية"},
		{"eAE.AllowbackdatingofVisitDateTime.label","السماح بتأريخ تاريخ / وقت الزيارة"},
		{"eAE.AmbulanceDetails.label","تفاصيل سيارة الإسعاف"},
		{"eAE.AssessmentDateTime.label","تاريخ / وقت التقييم"},
		{"eAE.AssignBedBaysForTreatmentArea.label","تخصيص سرير / خلجان لمنطقة العلاج"},
		{"eAE.AssignedDateTime.label","التاريخ / الوقت المعين"},
		{"eAE.AssignedPractitioner.label","ممارس معين"},
		{"eAE.AssignTreatArea.label","تعيين منطقة العلاج"},
		{"eAE.AssignTreatmentArea.label","منطقة العلاج المخصصة"},
		{"eAE.AttendanceDate.label","تاريخ الحضور"},
		{"eAE.AttendanceDateTo.label","تاريخ الحضور حتى"},
		{"eAE.AttendDateFrom.label","تاريخ الحضور من"},
		{"eAE.Autoclosed.label","مغلق"}, 
		{"eAE.BedBay.label","سرير / خليج"},
		{"eAE.BedBayAvailabilityChart.label","مخطط توفر السرير / الخليج"},
		{"eAE.BedBayNo.label","سرير / خليج لا"},
		{"eAE.BedBayStatus.label","سرير / حالة خليج"},
		{"eAE.BedBayType.label","نوع السرير / الخليج"},
		{"eAE.BedBayTypeCode.label","كود نوع السرير / الخليج"},
		{"eAE.BedBayTypeDesc.label","نوع السرير / الخليج تنازلي"},
		{"eAE.BillingInterface.label","واجهة الفواتير"},
		{"eAE.BillingInterfaced.label","واجهات الفواتير"},
		{"eAE.Blood.label","دم"},
		{"eAE.BloodAtMeatus.label","الدم في اللحوم"},
		{"eAE.Blunt.label","حاد"},
		{"eAE.BonyCrepitus.label","عظمي كريبيتوس"},
		{"eAE.BonyCrepitusPos.label","موقف عظمي خرق"},
		{"eAE.Brachial.label","عضدي"},
		{"eAE.BreathDensity.label","كثافة التنفس"},
		{"eAE.Breathing.label","عمليه التنفس"},
		{"eAE.BreathSound.label","صوت التنفس"},
		{"eAE.BreathType.label","نوع التنفس"},
		{"eAE.Brisk.label","انتعش"},
		{"eAE.BulbocavemousReflex.label","منعكس بصلي"},
		{"eAE.Burn.label","حرق"},
		{"eAE.CapacityRefill.label","سعة إعادة التعبئة"},
		{"eAE.CapBloodSugar.label","سكر الدم"},
		{"eAE.CapillaryBloodSugar.label","سكر الدم الشعري"},
		{"eAE.CaseDetails.label","تفاصيل الحالة"},
		{"eAE.CaseofMLC.label","حالة MLC"},
		{"eAE.Catheterin.label","القسطرة"},
		{"eAE.CauseofAccident.label","سبب الحادث"},
		{"eAE.CervicalCollar.label","طوق عنق الرحم"},
		{"eAE.Chest.label","صدر"},
		{"eAE.ChestTubeinSitu.label","أنبوب الصدر في الموقع"},
		{"eAE.ChestTubeinSituVolLeft.label","أنبوب الصدر في الموقع. حجم اليسار"},
		{"eAE.ChestTubeinSituVolRight.label","أنبوب الصدر في الموقع. حجم اليمين"},
		{"eAE.Circulation.label","الدوران"},
		{"eAE.Cold.label","البرد"},
		{"eAE.ConditionCase.label","الحالة / الحالة"},
		{"eAE.ContactTelNo.label","رقم هاتف الاتصال"},
		{"eAE.Convulsion.label","تشنج"},
		{"eAE.CreateAttendanceDetails.label","إنشاء تفاصيل الحضور"},
		{"eAE.CSpineFracture.label","كسر العمود الفقري"},
		{"eAE.CSpineTenderness.label","ج- الرقة في العمود الفقري"},
		{"eAE.Cutoffperiodforincluding.label","فترة القطع لتضمين زيارات الأيام السابقة"},
		{"eAE.Cyanotic.label","مزرق"},
		{"eAE.DateTimeIn.label","التاريخ / الوقت في"},
		{"eAE.Deep.label","عميق"},
		{"eAE.DegreeofBurn.label","درجة الحرق"},
		{"eAE.Density.label","كثافة"},
		{"eAE.DetailsOfTheCaseMLCCase.label","تفاصيل الحالة / حالة MLC"},
		{"eAE.Diffuse.label","منتشر"},
		{"eAE.Diminished.label","تضاءل"},
		{"eAE.DisabilityCNS.label","إعاقة الجهاز العصبي المركزي"},
		{"eAE.DisasterArea.label","منطقة منكوبة"},
		{"eAE.DisasterPatientRegistration.label","تسجيل مرضى الكوارث"},
		{"eAE.DisasterType.label","نوع الكارثة"},
		{"eAE.DisasterTypeCode.label","رمز نوع الكارثة"},
		{"eAE.DisasterTypeDesc.label","وصف نوع الكارثة"},
		{"eAE.DispositionCodeFrom.label","من رمز الترتيب"},
		{"eAE.DispositionCodeTo.label","رمز الترتيب ل"},
		{"eAE.DispositionDate.label","تاريخ الترتيب"},
		{"eAE.DispositionDateFrom.label","تاريخ الترتيب من"},
		{"eAE.DispositionDateTo.label","تاريخ الترتيب حتى"},
		{"eAE.DispositionTypeCode.label","رمز نوع الترتيب"},
		{"eAE.Distended.label","منتفخ"},
		{"eAE.Doneduring.label","تم خلال"},
		{"eAE.Dry.label","جاف"},
		{"eAE.Easy.label","سهل"},
		{"eAE.ECGMonitorBP.label","جهاز مراقبة تخطيط القلب BP"},
		{"eAE.EID.label","EID"},
		{"eAE.Emergencyclinic.label","عيادة الطوارئ"},
		{"eAE.Equal.label","متساوي"},
		{"eAE.EscAmbulanceContNo.label","رقم الاتصال المرافق / سيارة الإسعاف"},
		{"eAE.Escort.label","مرافقة"},
		{"eAE.EscortDetail.label","التفاصيل مرافقة"},
		{"eAE.EscortName.label","اسم المرافقة"},
		{"eAE.ExamDateTime.label","تاريخ / وقت الاختبار"},
		{"eAE.ExaminedBy.label","فحص بواسطة"},
		{"eAE.ExistingDetails.label","التفاصيل الموجودة"},
		{"eAE.ExistingPatientID.label","معرف المريض الحالي"},
		{"eAE.ExpLengthOfStay.label","اكسب طول البقاء"},
		{"eAE.Extremities.label","الأطراف"},
		{"eAE.EyeResponse.label","استجابة العين"},
		{"eAE.EyeResponseGCSDescription.label","وصف استجابة العين GCS"},
		{"eAE.FacialFracture.label","كسر في الوجه"},
		{"eAE.FB.label","FB"},
		{"eAE.FBC.label","FBC"},
		{"eAE.Femoral.label","فخذي"},
		{"eAE.FlailSegment.label","قطعة سائب"},
		{"eAE.FlailSegPos.label","موقف الجزء السائب"},
		{"eAE.Fracture.label","كسر"},
		{"eAE.FractureDislocation.label","خلع الكسر"},
		{"eAE.FracturesList.label","قائمة الكسور"},
		{"eAE.GCS.label","GCS"},
		{"eAE.GCSCategory.label","فئة GCS"},
		{"eAE.GCSCode.label","رمز GCS"},
		{"eAE.GCSCodes.label","رموز GCS"},
		{"eAE.GCSDesc.label","GCS تنازلي"},
		{"eAE.GCSDescription.label","وصف GCS"},
		{"eAE.GCSforResponse.label","GCS للاستجابة"},
		{"eAE.GCSforResponseCode.label","GCS لرمز الاستجابة"},
		{"eAE.GCSResponseCode.label","رمز استجابة GCS"},
		{"eAE.GCSResponseDesc.label","وصف استجابة GCS"},
		{"eAE.GCSScore.label","نقاط GCS"},
		{"eAE.GenitoUrinary.label","الجهاز البولي التناسلي"},
		{"eAE.Good.label","حسن"},
		{"eAE.GrowthDevelMileStoneforAge.label","النمو / التنموي ميل ستون للعمر"},
		{"eAE.GTubeNasal.label","جي تيوب للأنف"},
		{"eAE.GTubeOral.label","G-Tube عن طريق الفم"},
		{"eAE.GynaecDetail.label","التفاصيل Gynaec"},
		{"eAE.GynaecDetails.label","تفاصيل Gynaec"},
		{"eAE.Haematura.label","هيماتورا"},
		{"eAE.HeadNeck.label","الرأس والرقبة"},
		{"eAE.Hyper.label","هايبر"},
		{"eAE.Immobilization.label","الشلل"},
		{"eAE.ImmobilizationCode.label","قانون الشلل"},
		{"eAE.ImmobilizationDesc.label","وصف الشلل"},
		{"eAE.ImmunizationuptoDate.label","التحصين حتى تاريخه"},
		{"eAE.Impaired.label","ضعف السمع"},
		{"eAE.IncludeCheckOutPat.label","تشمل فحص المريض"},
		{"eAE.Infant.label","رضيع"},
		{"eAE.InitialManagement.label","الإدارة الأولية"},
		{"eAE.InjuryCategory.label","فئة الإصابة"},
		{"eAE.InjuryCategoryCode.label","رمز فئة الإصابة"},
		{"eAE.InjuryCategoryDesc.label","وصف فئة الإصابة"},
		{"eAE.InjurySubcategory.label","فئة فرعية للإصابة"},
		{"eAE.InjurySubcategoryCode.label","إصابة رمز الفئة الفرعية"},
		{"eAE.InjurySubcategoryDesc.label","التصنيف الفرعي للإصابة"},
		{"eAE.InjuryType.label","نوع الإصابة"},
		{"eAE.InvokeVitalSignsfromQueue.label","استدعاء العلامات الحيوية من قائمة الانتظار"},
		{"eAE.Irregular.label","غير عادي"},
		{"eAE.JVP.label","JVP"},
		{"eAE.Laboured.label","جاهد"},
		{"eAE.LastVisitWithin24Hrs.label","آخر زيارة خلال 24 ساعة. تفاصيل"},
		{"eAE.LimbColour.label","لون الأطراف"},
		{"eAE.LLQ.label","LLQ"},
		{"eAE.LMPDate.label","تاريخ LMP"},
		{"eAE.LocationofAccident.label","موقع الحادث"},
		{"eAE.LUQ.label","LUQ"},
		{"eAE.MaxAgeofcapturingpediatric.label","الحد الأقصى لعمر المريض لالتقاط تفاصيل طب الأطفال"},
		{"eAE.MaxNoofdayallowedforrevattenddetls.label","الحد الأقصى لعدد الأيام المسموح بها لمراجعة تفاصيل الحضور"},
		{"eAE.MaxNoofdaysallowedforRevising.label","الحد الأقصى لعدد الأيام المسموح بها لمراجعة الحضور"},
		{"eAE.MechaofSubInjury.label","آلية الإصابة الفرعية"},
		{"eAE.MinAgeofcapturingpediatric.label","الحد الأدنى لعمر المريضة لالتقاط تفاصيل الحمل"},
		{"eAE.Motor Response GCS Description.label","وصف GCS للاستجابة الحركية"},
		{"eAE.MotorResponse.label","استجابة المحرك"},
		{"eAE.MovementHistory.label","تاريخ الحركة"},
		{"eAE.NameofEscortService.label","اسم المرافقة / خدمة الاسعاف"},
		{"eAE.NasalAirway.label","مجرى الهواء الأنفي"},
		{"eAE.NewDetails.label","تفاصيل جديدة"},
		{"eAE.NewPatientID.label","معرف المريض الجديد"},
		{"eAE.NoControl.label","لا تحكم"},
		{"eAE.NoControlOn.label","لا تحكم قيد التشغيل"},
		{"eAE.NonCritical.label","غير حرج"},
		{"eAE.NonResp.label","عدم الاستجابة"},
		{"eAE.NoofPatients.label","عدد المرضى"},
		{"eAE.NormalBedBay.label","سرير عادي / خليج"},
		{"eAE.NursingDetails.label","تفاصيل التمريض"},
		{"eAE.Obstructed.label","أعاقت"},
		{"eAE.ObstructedBy.label","أعاق من قبل"},
		{"eAE.OneBed.label","يجب اختيار سرير واحد على الأقل"},
		{"eAE.OpenPneumothroax.label","افتح استرواح الصدر"},
		{"eAE.OpenPneumothroaxPos.label","فتح موقف استرواح الصدر"},
		{"eAE.OpentoAllPracLocation.label","مفتوح لجميع ممارسي الموقع"},
		{"eAE.OpenWound.label","جرح مفتوح"},
		{"eAE.OpenWoundPos.label","فتح موضع الجرح"},
		{"eAE.OpenWounds.label","فتح الجروح"},
		{"eAE.OralAirway.label","مجرى الهواء الفموي"},
		{"eAE.OrderByPriority.label","ترتيب حسب الأولوية"},
		{"eAE.OTDateTime.label","تاريخ / وقت إضافي"},
		{"eAE.Pale.label","باهت"},
		{"eAE.PatientManagement.label","التعامل مع المرضى"},
		{"eAE.PatientPositionCode.label","رمز موقف المريض"},
		{"eAE.PatientPositionduringIncident.label","موقف المريض أثناء الحادث"},
		{"eAE.PatientPriority.label","أولوية المريض"},
		{"eAE.PatientPriorityCode.label","رمز أولوية المريض"},
		{"eAE.PatientsSeenDate.label","تاريخ / وقت رؤية المرضى"},
		{"eAE.PatientsSeenDateFrom.label","تاريخ رؤية المرضى / الوقت من"},
		{"eAE.PatientsSeenDateTo.label","تاريخ رؤية المرضى / الوقت إلى"},
		{"eAE.PatientTypeFrom.label","نوع المريض من"},
		{"eAE.PatientTypeTo.label","نوع المريض إلى"},
		{"eAE.PatPositionDesc.label","وصف موقف المريض"},
		{"eAE.PatSecondaryTriageHistory.label","تاريخ الفرز الثانوي للمريض"},
		{"eAE.Pedal.label","دواسة"},
		{"eAE.PediatricDetails.label","تفاصيل طب الأطفال"},
		{"eAE.Pelvis.label","الحوض"},
		{"eAE.Penetrating.label","مخترق"},
		{"eAE.Physician.label","الطبيب المعالج"},
		{"eAE.Popliteal.label","مأبضية"},
		{"eAE.PositionDesc.label","وصف الوظيفة"},
		{"eAE.PostalCodeNo.label","رقم الرمز البريدي"},
		{"eAE.Practitionerfor.label","ممارس ل"},
		{"eAE.PractitionerIDFrom.label","معرف الممارس من"},
		{"eAE.PractitionerIDTo.label","معرف الممارس ل"},
		{"eAE.PreviousSurgery.label","الجراحة السابقة"},
		{"eAE.PrimaryAssessment.label","التقييم الأولي"},
		{"eAE.PrimaryTriageDetails.label","تفاصيل الفرز الأولية"},
		{"eAE.PriorityDesc.label","وصف الأولوية"},
		{"eAE.Prostrate.label","سجد"},
		{"eAE.ProtectiveDevice.label","جهاز الحماية"},
		{"eAE.ProtectiveDeviceCode.label","كود جهاز الحماية"},
		{"eAE.ProtectiveDeviceDesc.label","وصف جهاز الحماية"},
		{"eAE.PseudoBedBay.label","سرير زائف / خليج"},
		{"eAE.PseudoBedBays.label","سرير / خلجان زائفة"},
		{"eAE.PseudoBeds.label","أسرة زائفة"},
		{"eAE.PulsesRight.label","البقول الحق"},
		{"eAE.PupilReaction.label","رد فعل بؤبؤ العين"},
		{"eAE.PupilSize.label","حجم بؤبؤ العين"},
		{"eAE.PupilSizeLeft.label","حجم بؤبؤ العين اليسار"},
		{"eAE.Radial.label","شعاعي"},
		{"eAE.Reasons.label","الأسباب"},
		{"eAE.ReassignTreatArea.label","إعادة تعيين منطقة العلاج"},
		{"eAE.RecordedDetails.label","التفاصيل المسجلة"},
		{"eAE.Rectal.label","المستقيم"},
		{"eAE.RectalInjury.label","إصابة المستقيم"},
		{"eAE.Reduced.label","انخفاض"},
		{"eAE.RegistrationType.label","نوع التسجيل"},
		{"eAE.Relation.label","علاقة"},
		{"eAE.ReservedBedBay.label","سرير / خليج محجوز"},
		{"eAE.ReservedUntil.label","محفوظة حتى"},
		{"eAE.ReserveUntil.label","احتياطي حتى"},
		{"eAE.ResidenceAreaCodeFrom.label","رمز منطقة الإقامة من"},
		{"eAE.ResidenceAreaCodeTo.label","رمز منطقة الإقامة إلى"},
		{"eAE.Respiratory.label","تنفسي"},
		{"eAE.RespiratoryRate.label","معدل التنفس"},
		{"eAE.ResponseToPain.label","الاستجابة للألم"},
		{"eAE.ResponseToVerbal.label","الرد اللفظي"},
		{"eAE.Responsiveness.label","إستجابة"},
		{"eAE.Resuscitation.label","إنعاش"},
		{"eAE.RibFracture.label","كسر الضلع"},
		{"eAE.RibFracturePos.label","موقف كسر الضلع"},
		{"eAE.Right.label","حق"},
		{"eAE.Rigidity.label","الاستعلاء"},
		{"eAE.RLQ.label","RLQ"},
		{"eAE.RTA.label","الاحاله إلى القبول"},
		{"eAE.RUQ.label","RUQ"},
		{"eAE.ScoreType.label","نوع النتيجة"},
		{"eAE.SecondaryTriage.label","الفرز الثانوي"},
		{"eAE.Shallow.label","أجوف"},
		{"eAE.SkinCondition.label","حالة الجلد"},
		{"eAE.Sluggish.label","بطيئا"},
		{"eAE.SpareBedBay.label","سرير احتياطي / خليج"},
		{"eAE.Spine.label","العمود الفقري"},
		{"eAE.SpO2.label","Sp02"},
		{"eAE.Spontaneous.label","من تلقاء نفسها"},
		{"eAE.Stable.label","مستقر"},
		{"eAE.SubCategoryCode.label","رمز الفئة الفرعية"},
		{"eAE.SubEmphysema.label","الفرعية. انتفاخ الرئة"},
		{"eAE.Suprapubic.label","فوق"},
		{"eAE.Symptom.label","علامة مرض"},
		{"eAE.SystolicBP.label","ضغط الدم الانقباضي"},
		{"eAE.Tenderness.label","الرقة والحنان"},
		{"eAE.Tense.label","توتر، متوتر، مشدود"},
		{"eAE.TetanusVaccination.label","التطعيم ضد التيتانوس"},
		{"eAE.Tone.label","نغمة، رنه"},
		{"eAE.Trachea.label","قصبة هوائية"},
		{"eAE.TracheaMidlineShifted.label","تحول منتصف القصبة الهوائية"},
		{"eAE.TracheaMidlineShiftTo.label","تحول منتصف القصبة الهوائية إلى"},
		{"eAE.TraumaAssessment.label","تقييم الصدمة"},
		{"eAE.TraumaDetails.label","تفاصيل الصدمة"},
		{"eAE.TraumaScore.label","نتيجة الصدمة"},
		{"eAE.TreatmentAreaCode.label","رمز منطقة العلاج"},
		{"eAE.TreatmentAreaDesc.label","منطقة المعالجة تنازليا"},
		{"eAE.TreatmentAreaforLocation.label","منطقة العلاج للموقع"},
		{"eAE.Triage.label","نخب"},
		{"eAE.UnassignedList.label","قائمة غير محددة"},
		{"eAE.Unstable.label","غير مستقر"},
		{"eAE.Vaccinated.label","تلقيح"},
		{"eAE.ValuableDetails.label","تفاصيل قيمة"},
		{"eAE.Vascular.label","الأوعية الدموية"},
		{"eAE.VehicleRegNo.label","رقم تسجيل المركبة الآلية"},
		{"eAE.VerbalResponse.label","الاستجابة اللفظية"},
		{"eAE.VerbalResponseGCSDescription.label","وصف الاستجابة اللفظية GCS"},
		{"eAE.VisitWithin24Hrs.label","زيارة في غضون 24 ساعة"},
		{"eAE.VolumeLeft.label","حجم اليسار"},
		{"eAE.VolumeRight.label","حجم الحق"},
		{"eAE.Vomits.label","يتقيأ"},
		{"eAE.Warm.label","دافيء"},
		{"eAE.Consulted.label","تشاور"},
		{"eAE.AwaitingTreatment.label","في انتظار العلاج"},
		{"eAE.AssignedtoTreatmentArea.label","مخصص لمنطقة العلاج"},
		{"eAE.UndergoingTreatment.label","الخضوع للعلاج"},
		{"eAE.ConsultationStarted.label","بدأت التشاور"},
		{"eAE.TriageDateTime.label","فرز التاريخ الوقت"},
		{"eAE.Screening.label","تحري"},
		{"eAE.MainComplaintAndKeyFindings.label","الشكوى الرئيسية والنتائج الرئيسية"},
		{"eAE.NewProblems.label","مشاكل جديدة"},
		{"eAE.TickApplicableCategory.label","علامة التصنيف المطبقة"},
		{"eAE.SpecialInvestigations.label","التحقيقات الخاصة"},
		{"eAE.ReferToOtherFacility.label","الرجوع إلى منشأة أخرى"},
		{"eAE.HealthcareProfessional.label","خبير في الرعاية الصحية"},
		{"eAE.PleaseSpecify.label","رجاء حدد"},
		{"eAE.Noproblemexists.label","لا توجد مشكلة"}, 
		{"eAE.DateTimeOfAccident.label","تاريخ / وقت وقوع الحادث"}, 
		{"eAE.PlaceOfAccident.label","مكان الحادث"},
		{"eAE.MotorVehicleAccident.label","حادث سيارة"},
		{"eAE.LocationOfLastVisit.label","موقع آخر زيارة"},
		{"eAE.ScreeningData.label","فحص البيانات"},
		{"eAE.TriageLevel.label","مستوى الفرز"},
		{"eAE.TriageNurse.label","ممرضة الفرز"},
		{"eAE.NursingQuickLook.label","نظرة سريعة للتمريض"},
		{"eAE.NonAppointment.label","عدم التعيين"},
		{"eAE.OPD.label","العيادات الخارجية"},
		{"eAE.FastTrack.label","المسار السريع"},
		{"eAE.TriageTime.label","وقت الفرز"},
		{"eAE.NursingTriage.label","فرز التمريض"},
		{"eAE.BW.label","BW"},
		{"eAE.GmKg.label","جم / كجم"},
		{"eAE.Ht.label","هت"},
		{"eAE.T.label","تي"},
		{"eAE.P.label","ص"},
		{"eAE.RR.label","RR"},
		{"eAE.BP.label","BP"},
		{"eAE.mmHg.label","مم زئبق"},
		{"eAE.02Sat.label","O2 Sat"},
		{"eAE.O.label","O"},
		{"eAE.I.label","I"},
		{"eAE.ExaminationTime.label","وقت الفحص"},
		{"eAE.PrimarySurvey.label","المسح الابتدائي"},
		{"eAE.SecondarySurvey.label","المسح الثانوي"},
		{"eAE.PatientAllergies.label","حساسية المريض"},
		{"eAE.NursingTreatment.label","العلاج التمريضي"},
		{"eAE.AllowRegAttendInpat.label","السماح بتسجيل الحضور للمرضى الداخليين"},
		{"eAE.Consultation.label","التشاور"},
		{"eAE.EnableAccess.label","تمكين حقوق الوصول لإدارة قائمة انتظار الطوارئ"},
		{"eAE.MinAgeofcapturingLMP.label","الحد الأدنى لعمر المريض لالتقاط تفاصيل دورة شهرية"},
		{"eAE.DisRegnReference.label","ديس. ريجن. المرجعي"},
		{"eAE.DisRegnReference1.label","ديس ريجن المرجع"},
		{"eAE.Cases.label","حالات"},
		{"eAE.The.label","ال"},
		{"eAE.Recall.label","اعد الاتصال"},
		{"eAE.EstdAge.label","العمر المقدر"},
		{"eAE.DisasterManag.label","ادارة الكوارث"},
		{"eAE.ObservationWardType.label","نوع جناح المراقبة"},
		{"eAE.NonEmergency.label","غير طارئ"},
		{"eAE.antipyretic.label", "خافض للحرارة"},
		{"eAE.tepid.label", "فاتر"},
		{"eAE.sponge.label", "اسفنجة"},
		{"eAE.DefUnknownAdultAge.label", "العمر الافتراضي للبالغين غير معروف"},
		{"eAE.NonAppt.label","عدم التعيين"},
		{"eAE.AllowAEchkoutWithBillSettle.label","السماح بدفع AE مع تسوية الفاتورة"},
		{"eAE.OutstandingBillsSettlement.label","تسوية الفواتير المعلقة"},
		{"eAE.ObservationWard.label","جناح المراقبة"},
		{"eAE.IncludeTreatAreaPat.label","تضمين المرضى المعينين في منطقة العلاج"},
        {"eAE.PromptMsgReAttnd.label","تنبيه إعادة حضور المريض في سجل الحضور داخل"},
        {"eAE.LevelsOfTriageApplicable.label","مستويات الفرز المطبقة"},
        {"eAE.DeadOnArrival.label","ميت عند الوصول"},
        {"eAE.ColorIndicator.label","مؤشر اللون"},
        {"eAE.EndNumber.label","رقم النهاية"},
        {"eAE.IncidentRegister.label","سجل الحوادث"},
        {"eAE.AmbulanceOdometer.label","عداد المسافات لسيارة الإسعاف"},
        {"eAE.RequestQueuePeriod.label","طلب فترة الانتظار"},
        {"eAE.IncidentNumberingBy.label","ترقيم الحادث بواسطة"},
        {"eAE.Displaypastrequestsfor.label","عرض الطلبات السابقة لـ"},
        {"eAE.Displayfuturerequestsfor.label","عرض الطلبات المستقبلية لـ"},
        {"eAE.OdometerUnits.label","وحدات عداد المسافات"},
        {"eAE.PrintCompletedTripSheet.label","طباعة ورقة الرحلة المكتملة"},
        {"eAE.AmbulanceType.label","نوع الإسعاف"},
        {"eAE.Make.label","يجعلون"},
        {"eAE.AvailableStaff.label","طاقم العمل المتاح"},
        {"eAE.StaffStartsWith.label","يبدأ الموظفون بـ"},
        {"eAE.DisplayContact.label","عرض جهة الاتصال"},
        {"eAE.AttachedEquipments.label","المعدات المرفقة"},
        {"eAE.AvailableEquipments.label","المعدات المتوفرة"},
        {"eAE.EquipmentsStartsWith.label","تبدأ المعدات بـ"},
        {"eAE.AssociatedStaff.label","طاقم العمل"},
        {"eAE.AmbulanceManagementDashboard.label","لوحة إدارة سيارات الإسعاف"},
        {"eAE.RequestedQueue.label","قائمة الانتظار المطلوبة"},
        {"eAE.AmbulanceChart.label","مخطط سيارة الإسعاف"},
        {"eAE.maintenance.label","اعمال صيانة"},
        {"eAE.find.label","تجد"},
        {"eAE.NatureOfCall.label","طبيعة النداء"},
        {"eAE.GoogleMap.label","خرائط جوجل"},
        {"eAE.Dispatched.label","أرسل"},
        {"eAE.RequesterName.label","اسم الطالب"},
        {"eAE.AttendedBy.label","حضره"},
        {"eAE.PickupLocation.label","اختر موقعا"},
        {"eAE.PickupTime.label","اختار المعاد"},
        {"eAE.Immediate.label","مباشر"},
        {"eAE.DroppingLocation.label","اسقاط الموقع"},
        {"eAE.AmbulanceServiceType.label","نوع خدمة الاسعاف"},
        {"eAE.OdometerStart.label","بدء عداد المسافات"},
        {"eAE.ExpectedDistance.label","المسافة المتوقعة"},
        {"eAE.StartDateTime.label","وقت تاريخ البدء"},
        {"eAE.DispatchRemarks.label","ملاحظات إيفاد"},
        {"eAE.OdometerEnd.label","نهاية عداد المسافات"},
        {"eAE.DistanceCovered.label","المسافة المقطوعة"},
        {"eAE.UnderRepair.label","تحت الاصلاح"},
        {"eAE.RecordUnderMaintenanceDetails.label","سجل تحت تفاصيل الصيانة"},
        {"eAE.RevokeUnderMaintenanceDetails.label","الإلغاء تحت تفاصيل الصيانة"},
        {"eAE.RevokeMaintenance.label","إبطال الصيانة"},
        {"eAE.UpdateAmbulanceStatus.label","تحديث حالة الاسعاف"},
        {"eAE.StartingMeter.label","بدء العداد"},
        {"eAE.Endmeter.label","عداد النهاية"},
        {"eAE.CustomizedPositionforGridtable.label","موقف مخصص لجدول الشبكة"},
        {"eAE.Choosewhichcolumnsyouwouldliketosee.label","اختر الأعمدة التي ترغب في رؤيتها"},
        {"eAE.NoOfPatientIDsToBePrinted.label","عدد معرفات المريض المطلوب طباعتها"},
        {"eAE.RecordDiagnosisNotMandatory.label","سجل التشخيص ليس إلزاميا"},
        {"eAE.PickupPlace.label","مكان الالتقاط"},
        {"eAE.DisasterReference.label","مرجع الكوارث"},
        {"eAE.Reattendance.label","إعادة الحضور"},
        {"eAE.SeenbyDoctorImmediately.label","تراه الطبيب على الفور؟"},
        {"eAE.Messagefrom.label","رسالة من"},
        {"eAE.Zone.label","منطقة"},
        {"eAE.DisplayAEattendanceregisteredwithinHrs.label","عرض مرضى AE مع تسجيل الحضور داخل"},
        {"eAE.PlaceOfOccurrenceCode.label","رمز مكان التواجد"},
        {"eAE.PlaceOfOccurrence.label","مكان التواجد"},
        {"eAE.DateTimeOfOccurrence.label","تاريخ / وقت الحدوث"},
        {"eAE.PlaceOfOccurrenceDesc.label","وصف مكان التواجد"},
        {"eAE.RegisterNewBornForAE.label","استدعاء سجل حديثي الولادة ل AE"},
        {"eAE.InvokeRegisterNewBorn.label","استدعاء سجل الوليد ل AE"},
        {"eAE.AllowbackdatingConsDateTime.label","السماح بالعودة تاريخ / وقت بدء الاستشارة"},
        {"eAE.InvokeRecallForAE.label","استدعاء خيار استدعاء AE"},
        {"eAE.ToComeAgain.label","TCA"},
        {"eAE.LinkDelink.label","رابط / ديلينك"},
        {"eAE.GroupbyTreatmentarea.label","تجميع حسب منطقة العلاج"},
        {"eAE.OandG.label","O & G"},
        {"eAE.MechOfMainInj.label","آلية الإصابة الرئيسية"},
        {"eAE.WaitingTimeExceeds.label","تجاوز وقت الانتظار"},
        {"eAE.WaitingTimeColorIndicator.label","مؤشر لون وقت الانتظار"},
        {"eAE.CBD.label","اتفاقية التنوع البيولوجي"},
        {"eAE.ChkForPendingOrdersBeforeAECheckout.label","تحقق من الطلبات المعلقة قبل الخروج من AE"},
        {"eAE.DonotallowAECheckout.label","لا تسمح بدفع AE"},
        {"eAE.AllowAECheckout.label","السماح بدفع AE"},
        {"eAE.ValidateNatIDRegAttn.label","التحقق من وجود بطاقة الهوية الوطنية أثناء تسجيل الحضور"},
        {"eAE.AERegistrationTypeAutoUpdate.label","AE نوع التسجيل التحديث التلقائي"},
        {"eAE.ReconfirmCOT.label","إعادة تأكيد حالة الصدمة"},
		{"eAE.PriorityZoneDesc.label","وصف منطقة الأولوية"},
        {"eAE.PriorityZoneCode.label","منطقة الأولوية"},
		// Added by lakshmanan for ML-MMOh-CRF-1973 on 01-07-2023 start
        {"eAE.AppearAsTab.label","تظهر كعلامة تبويب"}, 
        {"eAE.TabColour.label","لون علامة التبويب"}, 
		{"eAE.Purple.label","أرجواني"}, 
		{"eAE.Brown.label","بني"}, 
		{"eAE.Blue.label","أزرق"}, 
		{"eAE.Darkblue.label","أزرق غامق"}, 
		{"eAE.Magenta.label","أرجواني"}, 
		{"eAE.Pink.label","لون القرنفل"}, 
		{"eAE.Cyan.label","ازرق سماوي"}, 
		{"eAE.Grey.label","رمادي"},
		// Added by lakshmanan for ML-MMOh-CRF-1973 on 01-07-2023 end
        {"eAE.PriorityZoneColorDesc.label","وصف منطقة الأولوية"},
        {"eAE.PriorityZoneTabDesc.label","وصف علامة تبويب منطقة الأولوية"},
		{"eAE.EnableEmiratesID.label","تفعيل هوية الإمارات"},
		{"eAE.ForAdmission.label","للقبول"},
		{"eAE.EnableForAdmission.label","تمكين علامة التبويب القبول"},
		{"eAE.ModifyReferral.label","تعديل الإحالة"},
		{"eAE.WaitingForAdmission.label","في انتظار القبول"}
		

			}; 
}
