/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eMO.EmbalmRegistration.MOEmbalmRegnManager
package eMO.EmbalmRegistration;
/**
 * Remote interface for EmbalmRegistration
 */
 
 public interface MOEmbalmRegnRemote
 extends javax.ejb.EJBObject { 
 
 java.util.HashMap updateMOEmbalRegn(java.util.Properties properties, java.util.HashMap ht)throws java.rmi.RemoteException;
 java.util.HashMap insertMOEmbalRegn(java.util.Properties properties, java.util.HashMap ht)throws java.rmi.RemoteException;
 
 
 // ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
 }
