/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eIP.IPChangeAdmissionDetails.IPChangeAdmissionDetailsManager
package eIP.IPChangeAdmissionDetails;

/**
 * Remote interface for IPChangeAdmissionDetails
 */
public interface IPChangeAdmissionDetailsRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap updateAdmissionDetails(java.util.Properties p, java.util.HashMap Tabdata) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
