/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eFM.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
//		{"eFM.AcceptFileTypeandVolumeNoforAutoRequest.label","Accept File Type and Volume No for Auto Request"},
//		{"eFM.AccesstoallFSLocations.label","Access to all FS Locations"},
		{"eFM.AccountablePerson.label","负责人"},
//		{"eFM.AcrossFacility.label","Across Facility"},
//		{"eFM.ActiveVolumeNo.label","Active Volume No"},
		{"eFM.AppointmentDatefield.label","预约日期字段"},
		{"eFM.AppointmentDetail.label","预约明细"},
		{"eFM.ApptCancelled.label","�?�消预约"},
		{"eFM.ApptTransfered.label","转�?�预约"},
		{"eFM.Archeived.label","归档"},
		{"eFM.ArchiveDocumentstatus.label","归档文档状�?"},
		{"eFM.ArchiveFilesStatus.label","归档档状�?"},
		{"eFM.Assign.label","分�?"},
		{"eFM.AssignAllDocumentsTo.label","分�?所有文檔"},
		{"eFM.AssignAllFilesTo.label","分�?所有檔"},
//		{"eFM.AssignFSLocation.label","Assign FS Location"},
		{"eFM.AutoReceiptRules.label","自动接收规则"},
		{"eFM.AutoReceive.label","自动接收"},
		{"eFM.AutoTrackouttoIPW.label","自动跟踪�?院病区"},
		{"eFM.AutoTrackouttoOPD.label","自动跟踪门诊部门"},
//		{"eFM.BelongstoMRD.label","Belongs to MRD"},
		{"eFM.CancelledBooking.label","�?�消预订"},
		{"eFM.CancelRequestRemarks.label","�?求�?�消言论"},
//		{"eFM.CarriedBy.label","Carried By"},
		{"eFM.ChangeFileReturnDate.label","改�?�档归还日期"},
		{"eFM.ChangeFileReturnDateFilesNotAllowed.label","更改返回日期的檔-档�?�?许"},
		{"eFM.ChangeFileStatus.label","改�?�档的状�?"},
//		{"eFM.ChangeFSLocation.label","Change FS Location"},
		{"eFM.ClinicType.label","临床类型"},
		{"eFM.ConfirmedFiles.label","确认收到文件"},
		{"eFM.ConfirmFileReceipt.label","确认档案"},
		{"eFM.ConfirmPullingListRemarks.label","确认退出�??�?�言论"},
		{"eFM.ConfirmReceipt.label","确认收到"},
		{"eFM.ConfirmReturn.label","确认返回"},
//		{"eFM.ControlPullingListGenerationbyGender.label","Control Pulling List Generation by Gender"},
		{"eFM.CreateFileVolume.label","创建文件滚�?"},
		{"eFM.CurrentDocumentStatus.label","目�?文档状�?"},
//		{"eFM.CurrentFS.label","Current FS"},
//		{"eFM.CurrentFSLocation.label","Current FS Location"},
//		{"eFM.CurrentFSLocationIdentity.label","Current FS Location Identity"},
//		{"eFM.CurrentFSlocationoftheDocument.label","Current FS location of the Document"},
//		{"eFM.CurrentFSlocationoftheFile.label","Current FS location of the File"},
		{"eFM.CurrentStatusoftheDocument.label","现状文件"},
		{"eFM.CurrentStatusoftheFile.label","现状档案"},
		{"eFM.CurrrentVolumeNumber.label","当�?�?��?�"},
		{"eFM.CurrrentVolumeStatus.label","当�?�?�状�?"},
		{"eFM.DateofIssue.label","�?�行日期"},
		{"eFM.DateReported.label","报告日期"},
		{"eFM.DateResolvedCancelled.label","日期解决/�?�消"},
		{"eFM.DateTimeReported.label","日期/时间报告"},
		{"eFM.DateTimeResolvedCancelled.label","日期/时间分辨/�?�消"},
		{"eFM.DefaultSettings.label","默认设置"},
		{"eFM.Deficiencies.label","缺陷"},
		{"eFM.Deficiency.label","虚�?"},
		{"eFM.DeficiencyCode.label","虚�?代�?"},
		{"eFM.DeficiencyCriteria.label","虚�?标准"},
		{"eFM.DeficiencyDescription.label","虚�?�??述"},
		{"eFM.DeficiencyStatus.label","虚�?状�?"},
		{"eFM.DeficiencyType.label","虚�?类型"},
		{"eFM.De-Link.label","脱节"},
//		{"eFM.DestFSLocationIdentity.label","Dest FS Location Identity"},
		{"eFM.DocIssueDate.label","文件�?�行日期"},
		{"eFM.DocsSelectedforIssue.label","文件选定的问题"},
		{"eFM.DocStorageLocation.label","文件存储�?置"},
		{"eFM.DocumentCode.label","文件�?"},
		{"eFM.DocumentFolder.label","活页夹"},
		{"eFM.DocumentFolderDetails.label","档夹的细节"},
		{"eFM.DocumentFolderID.label","活页夹编�?�"},
		{"eFM.DocumentFolderInFSLocn.label","文件？"},
		{"eFM.DocumentFolderName.label","档的档夹�??称"},
		{"eFM.DocumentFolderType.label","活页夹类型"},
		{"eFM.DocumentID.label","文档编�?�"},
		{"eFM.DocumentName.label","文档�??称"},
		{"eFM.DocumentReturnDetails.label","文档返回细节"},
		{"eFM.Documentscannotberequested.label","文檔�?能被�?求"},
		{"eFM.DocumentscannotbeReturned.label","档�?能退还"},
		{"eFM.DocumentsinTransit.label","文档传输"},
		{"eFM.Documentspendingformorethan.label","待檔以上"},
		{"eFM.DocumentsRequestedin.label","檔�?求"},
		{"eFM.DocumentStatus.label","档状�?"},
		{"eFM.DocumentstobeReturned.label","文件归还"},
		{"eFM.DocumentTypeCode.label","档类型代�?"},
		{"eFM.DocumentTypeinFolder.label","文件类型的活页夹"},
		{"eFM.DocumentTypeName.label","档类型�??称"},
		{"eFM.DTParameter.label","�?�物疗法�?�数"},
		{"eFM.Dueforreturn.label","由于返回"},
		{"eFM.EncounterDeficiencyStatus.label","�?�到缺陷状�?"},
		{"eFM.FileCreationDate.label","档创建日期"},
		{"eFM.FileinPermanentLoc.label","档案永久存放"},
		{"eFM.FileInTransit.label","文档传输"},
		{"eFM.FileisArchived.label","文件存盘"},
		{"eFM.FileisLost.label","档丢失"},
		{"eFM.FileisOutside.label","文件外部"},
		{"eFM.FileIssueDate.label","文件�?�行日期"},
		{"eFM.FileMovement.label","文件移动"},
		{"eFM.FileNoPatientDetails.label","档�?��?病人细节"},
		{"eFM.FileOutsideMRD.label","档以外的病历细节"},
		{"eFM.FileRequiredOn.label","所需的文件"},
		{"eFM.FileReturnDetails.label","文件详细返回"},
		{"eFM.FilesCannotbeIssued.label","档�?能�?�放"},
		{"eFM.Filescannotberequested.label","檔�?能�?求"},
		{"eFM.FilescannotbeReturned.label","檔�?能返回"},
		{"eFM.FilesinTransit.label","文件传输"},
//		{"eFM.Filespendingformorethan.label","Files pending for more than"},
		{"eFM.FilesRequestedin.label","檔�?求"},
		{"eFM.FilesSelectedforIssue.label","选定的档案问题"},
		{"eFM.FileStatus.label","档状�?"},
		{"eFM.FilestobeReturned.label","档案归还"},
		{"eFM.FileStorageLocationDesc.label","文件存储�?置�??述"},
		{"eFM.FileTransportDetails.label","档传输的细节"},
		{"eFM.FileTransportModeDescription.label","文件传输模�?说明"},
//		{"eFM.FileTypeforFSLocation.label","File Type for FS Location"},
		{"eFM.FileTypeVolumeNo.label","文件类型/�?��?�"},
		{"eFM.FileVolume.label","文件�?�"},
		{"eFM.FMFileType.label","FM文件类型"},
		{"eFM.FMParameter.label","FM�?�数"},
		{"eFM.FMUserAccess.label","FM用户访问"},
		{"eFM.FolderName.label","档夹�??称"},
		{"eFM.FollowingFilesReturnDatecannotbeChanged.label","下列档返回日期�?能改�?�的"},
/*		{"eFM.Found.label","Found"},
		{"eFM.FromLocationCode.label","From Location Code"},
		{"eFM.FromLoggedInFacility.label","From Logged In Facility"},
		{"eFM.FromOtherFacilities.label","From Other Facilities"},
		{"eFM.FromTO.label","From / To"},
		{"eFM.FSLocation.label","FS Location"},
		{"eFM.FSLocationCode.label","FS Location Code"},
		{"eFM.FSLocationDescription.label","FS Location Description"},
		{"eFM.FSLocationIdentity.label","FS Location Identity"},*/
		{"eFM.GeneratedBy.label","产生"},
		{"eFM.HolderName.label","�?有人姓�??"},
		{"eFM.HolderPhoneNo..label","�?有人的电�?�?�"},
//		{"eFM.InactiveFSLocation.label","Inactive FS Location"},
		{"eFM.InactiveIn.label","无所作为"},
		{"eFM.InactivePeriod.label","�?�用期"},
//		{"eFM.InactiveVolumeNo.label","Inactive Volume No"},
		{"eFM.IncludeInpatients.label","包括�?院"},
//		{"eFM.IncompleteFSLocation.label","Incomplete FS Location"},
		{"eFM.InOtherFacility.label","在其它设施"},
		{"eFM.InpatientDetails.label","�?院详情"},
//		{"eFM.InReqFSLocation.label","In Req FS Location"},
		{"eFM.InvalidFile.label","无效档"},
		{"eFM.IPConfirmedFileList.label","�?院病人确认文件列表"},
		{"eFM.IPPullingList.label","�?院病人拖拉清�?�"},
		{"eFM.IPTracerCard.label","�?院病人跟踪�?�"},
		{"eFM.IssueDateTime.label","�?�行日期/时间"},
//		{"eFM.IssuedDSLocation.label","Issued DS Location"},
//		{"eFM.IssuedFSLocation.label","Issued FS Location"},
		{"eFM.Issuedon.label","�?�表"},
		{"eFM.IssueFile.label","�?�行文件"},
		{"eFM.IssueFileToOtherFacilities.label","�?�行文件的其它设施"},
		{"eFM.IssueFileWithinFacility.label","问题的文件内设施"},
//		{"eFM.IssueFSLocation.label","Issue FS Location"},
		{"eFM.IssueTracerCard.label","问题跟踪�?�"},
//		{"eFM.IssuingFSLocation.label","Issuing FS Location"},
		{"eFM.LinkBetweenFileandEncounterRequired.label","档和�?�到的需求之间的�?�系"},
		{"eFM.LocationReason.label","地点/原因"},
		{"eFM.LostDocumentstatus.label","丢件档状�?"},
		{"eFM.LostFilesStatus.label","丢失的档状�?"},
//		{"eFM.LostFSLocation.label","Lost FS Location"},
		{"eFM.MandatoryStatutory.label","强制性/法定"},
		{"eFM.ManualEntry.label","手动输入"},
		{"eFM.ManualRequest.label","手册�?求"},
		{"eFM.ManualRequestYN.label","手动需求 是�?�?�"},
		{"eFM.MedicalRecordDept.label","病历部门"},
		{"eFM.MedicoLegalCase.label","医院法律案例"},
		{"eFM.MonitorDeficiency.label","监控缺失"},
		{"eFM.MonitorFileDeficiency.label","监测档案�?足"},
		{"eFM.Narration.label","�?�事"},
		{"eFM.NarrationCode.label","�?�事�?"},
		{"eFM.NarrationDescription.label","�?�事�??述"},
		{"eFM.NarrationforAutoTrackouttoOPD.label","�?�事的自动跟踪至门诊"},
		{"eFM.NarrForReturnFileToMRD.label","为返还档到病历部门的述事"},
//		{"eFM.NewFSLocation.label","New FS Location"},
		{"eFM.NewStatusoftheDocument.label","档新状�?"},
		{"eFM.NewStatusoftheFile.label","档新状�?"},
		{"eFM.NewVolumeNumber.label","新�?��?�"},
//		{"eFM.NIADueDate.label","NIA Due Date"},
//		{"eFM.NonPermanentDepartment.label","Non-Permanent Department"},
		{"eFM.NoofDaystoReturn.label","返回天数"},
//		{"eFM.NoofDaysuptowhichtocheckforappointmentsinFileInquiry.label","No of Days up to which to check for appointments in File Inquiry"},
//		{"eFM.NoofDaysuptowhichtocheckforbookingsinFileInquiry.label","No of Days up to which to check for bookings in File Inquiry"},
//		{"eFM.NoofDocs.label","No of Docs"},
//		{"eFM.NoofFiles.label","No of Files"},
//		{"eFM.NoofHourstoReturn.label","No of Hours to Return"},
		{"eFM.OnlineReport.label","在线报告"},
		{"eFM.OPConfirmedFileList.label","门诊确认文件列表"},
		{"eFM.OPDAppointmentfor.label","门诊部预约"},
		{"eFM.OPPullingList.label","门诊拖拉列表"},
		{"eFM.OPTracerCard.label","门诊跟踪�?�"},
		{"eFM.OtherRules.label","其它规则"},
//		{"eFM.OutstandingFrom.label","Outstanding From"},
//		{"eFM.OutstandingFSLocation.label","Outstanding FS Location"},
//		{"eFM.OutstandingRequest.label","Outstanding Request"},
//		{"eFM.OutstandingRequestSearchCriteria.label","Outstanding Request Search Criteria"},
//		{"eFM.OverDueforreturn.label","Over Due for return"},
		{"eFM.PeriodSpecific.label","特定时期"},
		{"eFM.PermanentDepartment.label","常驻部"},
//		{"eFM.PermanentFSLocation.label","Permanent FS Location"},
//		{"eFM.PlannedAdmissionFSLocation.label","Planned Admission FS Location"},
		{"eFM.PractitionerResponsible.label","从业者负责"},
		{"eFM.PreferredTime.label","推�??时间"},
		{"eFM.PreviousDocumentStatus.label","以�?的档状�?"},
		{"eFM.PreviousFileStatus.label","以�?的档状�?"},
//		{"eFM.PreviousFSLocation.label","Previous FS Location"},
		{"eFM.PrintBarCode.label","�?�形�?打�?�"},
		{"eFM.PrintPullingList.label","打�?�拖�?列表"},
		{"eFM.PrintTelNoinPullingList.label","在拖�?清�?�中打�?�电�?�?��?"},
		{"eFM.PrintTracerCard.label","打�?�跟踪�?�"},
		{"eFM.PrintTracerCardonIssueof.label","打�?�跟 踪�?��?�行"},
		{"eFM.Pull.label","拉"},
		{"eFM.PullingListType.label","拖�?列表�?�型"},
		{"eFM.ReasonForBorrowing.label","借款原因"},
		{"eFM.Receive.label","接收"},
		{"eFM.ReceivedDetails.label","收到详细说明"},
		{"eFM.Receivedon.label","收到"},
		{"eFM.ReceiveFile.label","接收文件"},
		{"eFM.ReceiveFileatMRD.label","从病历部门接收档"},
		{"eFM.ReceiverName.label","接收部门�??称"},
//		{"eFM.ReceivingFSLocation.label","Receiving FS Location"},
//		{"eFM.ReceivingFSLocationIdentity.label","Receiving FS Location Identity"},
//		{"eFM.ReceivingFSLocn.label","Receiving FS Locn"},
		{"eFM.RecordChangeDeficiencydetail.label","记录/改�?�缺陷明细"},
		{"eFM.RegisterFileNotPulled.label","登记档�?拖�?"},
		{"eFM.ReportedDateFrom.label","报告选项"},
		{"eFM.ReportOptionBy.label","报告日期"},
		{"eFM.RequestedDocumentDetails.label","�?求的档详细"},
		{"eFM.RequestedFileDetails.label","请求的档的细节"},
		{"eFM.RequestedFiles.label","檔�?求"},
		{"eFM.RequestedFrom.label","�?求"},
		{"eFM.RequestedOnDate.label","�?求日期"},
		{"eFM.RequesterDetails.label","请求细节"},
		{"eFM.RequestFileFromOtherFacilities.label","从其它设施请求文件"},
		{"eFM.RequestFileWithinFacility.label","申请文件内设施"},
		{"eFM.RequestFrom.label","�?求"},
		{"eFM.Requesting.label","请求"},
		{"eFM.RequestModeDescription.label","申请方�?说明"},
		{"eFM.RequestofDocumentsFrom.label","�?求文檔"},
		{"eFM.RequestRemarks.label","申请备注"},
		{"eFM.RequestTo.label","�?求"},
		{"eFM.ResponsiblePractitioner.label","负责医师"},
//		{"eFM.RestrictionacrossFSLocnIdentities.label","Restriction across FS Locn Identities"},
		{"eFM.ReturnDate.label","返回日期"},
		{"eFM.ReturnDueDate.label","返回截止日期"},
		{"eFM.ReturnDueDateTime.label","返回截止日期/时间"},
		{"eFM.ReturnFile.label","返回文件"},
		{"eFM.ReturnFileatMRD.label","返回档给病历部门"},
		{"eFM.ReturnFromArchived.label","返回存档"},
		{"eFM.Returning.label","返回"},
//		{"eFM.ReturningFSLocation.label","Returning FS Location"},
		{"eFM.ReturnRemarks.label","返回备注"},
		{"eFM.ScheduleCancelled.label","�?�消排�?�表"},
		{"eFM.SecurityAccesstobeenforced.label","安全访问强制执行"},
		{"eFM.SecurityRules.label","安全规则"},
		{"eFM.Specialitys.label","专业"},
		{"eFM.Statutory.label","法定"},
		{"eFM.Supplementary.label","补充"},
		{"eFM.ThirdPartyName.label","第三方�??称"},
//		{"eFM.ToFSLocation.label","To FS Location"},
		{"eFM.ToLocationCode.label","所在地代�?"},
		{"eFM.ToOtherFacilities.label","其它设施"},
//		{"eFM.TotalNoofDocuments.label","Total No of Documents"},
//		{"eFM.TotalNoofFiles.label","Total No of Files"},
		{"eFM.TracerCard.label","跟踪�?�"},
		{"eFM.TrackedoutBy.label","传输"},
		{"eFM.TrackoutfilestoOPD.label","传输文件到门诊部"},
		{"eFM.TrackoutOuttoOPD.label","传输到门诊部"},
		{"eFM.TransferFile.label","传输文件"},
		{"eFM.TransferFileoutsideMRD.label","传输档到病历部门"},
		{"eFM.Transferof.label","转让"},
		{"eFM.Transit.label","过境"},
		{"eFM.TransportDetail.label","交通详情"},
		{"eFM.UpdatedBy.label","更新"},
		{"eFM.UpdatedDate.label","更新日期"},
		{"eFM.VolumeNo.label","�?��?�"},
//		{"eFM.WithInFacility.label","With In Facility"},
		{"eFM.TrackOut.label","传输"},
		{"eFM.FileisInside.label","内部文件"},
		{"eFM.ShowAllFiles.label","显示所有文件"},
		{"eFM.Files.label","档案"},
		{"eFM.ClinicName.label","诊所�??称"},
		{"eFM.QIDno.label","QID�?�"},
		{"eFM.TotalNoOfBookings.label","总数预订"},
		{"eFM.PrintPullingLable.label","打�?�拖拉标签"},
		{"eFM.PrintIdentificationLabel.label","打�?�识别标签"},
//		{"eFM.NeverTobeArchived.label","Never To be Archived"},
//		{"eFM.AutoTrackOutUponCnPL.label","Auto Track Out Upon Confirm Pulling List"},
//		{"eFM.AcceptOutsideTransitFiles.label","Accept Outside & In Transit Files Directly in Receive File at MRD"}
//Newly added codes on 21/01/09
		{"eFM.AcceptFileTypeandVolumeNoforAutoRequest.label","自动接收文件类型和�?��?�"},
		{"eFM.AcceptOutsideTransitFiles.label","病历部门接收外部文件"},
		{"eFM.AccesstoallFSLocations.label","指定文件存放�?置"},
		{"eFM.AcrossFacility.label","整个医院"},
		{"eFM.ActiveVolumeNo.label","活动�?��?�"},
		{"eFM.AssignFSLocation.label","分�?文件存储�?置"},
		{"eFM.AutoTrackOutUponCnPL.label","自动跟踪确认拖拉清�?�"},
		{"eFM.BelongstoMRD.label","属于病历部门"},
		{"eFM.CarriedBy.label","采�?�"},
		{"eFM.ChangeFSLocation.label","文件存放�?置"},
		{"eFM.ControlPullingListGenerationbyGender.label","基于性别生�?拖拉列表"},
		{"eFM.CurrentFS.label","当�?文件存储"},
		{"eFM.CurrentFSLocation.label","文件当�?存储�?置"},
		{"eFM.CurrentFSLocationIdentity.label","当�?存储�?置标识"},
		{"eFM.CurrentFSlocationoftheDocument.label","当�?文档的存储�?置"},
		{"eFM.CurrentFSlocationoftheFile.label","当�?文件存储�?置"},
		{"eFM.DestFSLocationIdentity.label","定义文件存储�?置标识"},
		{"eFM.Filespendingformorethan.label","文件超过"},
		{"eFM.FileTypeforFSLocation.label","文件存储�?置的文件类型"},
		{"eFM.Found.label","查找文件"},
		{"eFM.FromLocationCode.label","文件开始�?置"},
		{"eFM.FromLoggedInFacility.label","从登录部门查找"},
		{"eFM.FromOtherFacilities.label","从其他部门查找"},
		{"eFM.FromTO.label","从/到"},
		{"eFM.FSLocation.label","文件存储�?置"},
		{"eFM.FSLocationCode.label","存储�?置代�?"},
		{"eFM.FSLocationDescription.label","文件存储�?置�??述"},
		{"eFM.FSLocationIdentity.label","文件存储�?置标识"},
		{"eFM.InactiveFSLocation.label","无效的存储地点"},
		{"eFM.InactiveVolumeNo.label","无效的�?��?�"},
		{"eFM.IncompleteFSLocation.label","�?完全的文件存储�?置"},
		{"eFM.InReqFSLocation.label","在请求存储�?置"},
		{"eFM.IssuedDSLocation.label","�?�出文档存储�?置"},
		{"eFM.IssuedFSLocation.label","�?��?�文档存储�?置"},
		{"eFM.IssueFSLocation.label","�?��?�文件存储�?置"},
		{"eFM.IssuingFSLocation.label","�?��?�文件存储�?置"},
		{"eFM.LostFSLocation.label","丢失文件存储�?置"},
		{"eFM.NeverTobeArchived.label","从未存档"},
		{"eFM.NewFSLocation.label","新文件存储�?置"},
		{"eFM.NIADueDate.label","NIA Due Date"},
		{"eFM.NonPermanentDepartment.label","临时部门"},
		{"eFM.NoofDaysuptowhichtocheckforappointmentsinFileInquiry.label","�?�以�??�?查询预约的天数"},
		{"eFM.NoofDaysuptowhichtocheckforbookingsinFileInquiry.label","�?�以�??�?查询入�?的天数"},
		{"eFM.NoofDocs.label","文档�?�"},
		{"eFM.NoofFiles.label","文件�?�"},
		{"eFM.NoofHourstoReturn.label","返回时间�?�"},
		{"eFM.OutstandingFrom.label","待解决文件"},
		{"eFM.OutstandingFSLocation.label","待解决文件存放�?置"},
		{"eFM.OutstandingRequest.label","待解决请求"},
		{"eFM.OutstandingRequestSearchCriteria.label","请求的查询标准"},
		{"eFM.OverDueforreturn.label","文件超过返回时间"},
		{"eFM.PermanentFSLocation.label","永久文件存放�?置"},
		{"eFM.PlannedAdmissionFSLocation.label","计划入院文件存储�?置"},
		{"eFM.PreviousFSLocation.label","之�?文件存放�?置"},
		{"eFM.ReceivingFSLocation.label","接收文件存放�?置"},
		{"eFM.ReceivingFSLocationIdentity.label","接收文件存储�?置编�?�"},
		{"eFM.ReceivingFSLocn.label","接收文件存储�?置"},
		{"eFM.RestrictionacrossFSLocnIdentities.label","�?制文件存储�?置标识"},
		{"eFM.ReturningFSLocation.label","返回文件存储�?置"},
		{"eFM.ToFSLocation.label","到文件的存储�?置"},
		{"eFM.TotalNoofDocuments.label","总的文档数"},
		{"eFM.TotalNoofFiles.label","总的文件数"},
		{"eFM.WithInFacility.label","在一个医院内"},


	};
}
