/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eFM.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
{"eFM.AcceptFileTypeandVolumeNoforAutoRequest.label","اقبل نوع الملف ورقم المجلد للطلب التلقائي"},
{"eFM.AccesstoallFSLocations.label","الوصول إلى جميع مواقع FS"},
{"eFM.AccountablePerson.label","شخص مسؤول"},
{"eFM.AcrossFacility.label","عبر المنشأة"},
{"eFM.ActiveVolumeNo.label","رقم المجلد النشط"},
{"eFM.AppointmentDatefield.label","حقل تاريخ الموعد"},
{"eFM.AppointmentDetail.label","تفاصيل الموعد"},
{"eFM.ApptCancelled.label","تم إلغاء الموعد"},
{"eFM.ApptTransfered.label","تم تحويل الموعد"},
{"eFM.Archeived.label","مؤرشفة"},
{"eFM.ArchiveDocumentstatus.label","حالة المستند المؤرشف"},
{"eFM.ArchiveFilesStatus.label","حالة الملف المؤرشفة"},
{"eFM.Assign.label","تعيين"},
{"eFM.AssignAllDocumentsTo.label","تعيين كافة المستندات إلى"},
{"eFM.AssignAllFilesTo.label","تعيين كافة الملفات إلى"},
{"eFM.AssignFSLocation.label","تعيين موقع FS"},
{"eFM.AutoReceiptRules.label","قواعد الاستلام التلقائي"},
{"eFM.AutoReceive.label","استلام تلقائي"},
{"eFM.AutoTrackouttoIPW.label","تعقب تلقائي إلى IPW"},
{"eFM.AutoTrackouttoOPD.label","التتبع التلقائي للعيادات الخارجية"},
{"eFM.BelongstoMRD.label","ينتمي إلى MRD"},
{"eFM.CancelledBooking.label","الحجز الملغى"},
{"eFM.CancelRequestRemarks.label","ملاحظات إلغاء الطلب"},
{"eFM.CarriedBy.label","يحملها"},
{"eFM.ChangeFileReturnDate.label","تغيير تاريخ إرجاع الملف"},
{"eFM.ChangeFileReturnDateFilesNotAllowed.label","تغيير تاريخ إرجاع الملف - الملفات غير مسموح بها"},
{"eFM.ChangeFileStatus.label","تغيير حالة الملف"},
{"eFM.ChangeFSLocation.label","تغيير موقع FS"},
{"eFM.ClinicType.label","نوع العيادة"},
{"eFM.ConfirmedFiles.label","تأكيد استلام الملف"},
{"eFM.ConfirmFileReceipt.label","الملفات المؤكدة"},
{"eFM.ConfirmPullingListRemarks.label","ملاحظات تأكيد قائمة السحب"},
{"eFM.ConfirmReceipt.label","تأكيد استلام"},
{"eFM.ConfirmReturn.label","تأكيد الإسترداد"},
{"eFM.ControlPullingListGenerationbyGender.label","التحكم في سحب القائمة حسب النوع"},
{"eFM.CreateFileVolume.label","إنشاء مجلد ملف"},
{"eFM.CurrentDocumentStatus.label","حالة المستند الحالية"},
{"eFM.CurrentFS.label","FS الحالي"},
{"eFM.CurrentFSLocation.label","موقع FS الحالي"},
{"eFM.CurrentFSLocationIdentity.label","هوية موقع FS الحالية"},
{"eFM.CurrentFSlocationoftheDocument.label","موقع FS الحالي للمستند"},
{"eFM.CurrentFSlocationoftheFile.label","موقع FS الحالي للملف"},
{"eFM.CurrentStatusoftheDocument.label","الوضع الحالي للوثيقة"},
{"eFM.CurrentStatusoftheFile.label","الوضع الحالي للملف"},
{"eFM.CurrrentVolumeNumber.label","رقم المجلد الحالي"},
{"eFM.CurrrentVolumeStatus.label","حالة المجلد الحالي"},
{"eFM.DateofIssue.label","تاريخ الإصدار"},
{"eFM.DateReported.label","تاريخ التقرير"},
{"eFM.DateResolvedCancelled.label","تاريخ الحل / الإلغاء"},
{"eFM.DateTimeReported.label","تاريخ / وقت الإبلاغ"},
{"eFM.DateTimeResolvedCancelled.label","التاريخ / الوقت الذي تم حله / إلغاؤه"},
{"eFM.DefaultSettings.label","الإعدادات الافتراضية"},
{"eFM.Deficiencies.label","أوجه القصور"},
{"eFM.Deficiency.label","عجز"},
{"eFM.DeficiencyCode.label","كود العجز"},
{"eFM.DeficiencyCriteria.label","معايير العجز"},
{"eFM.DeficiencyDescription.label","وصف العجز"},
{"eFM.DeficiencyStatus.label","حالة العجز"},
{"eFM.DeficiencyType.label","نوع العجز"},
{"eFM.De-Link.label","فك الربط"},
{"eFM.DestFSLocationIdentity.label","هوية موقع الوجهة FS"},
{"eFM.DocIssueDate.label","تاريخ إصدار الوثيقة"},
{"eFM.DocsSelectedforIssue.label","تم تحديد المستندات للإصدار"},
{"eFM.DocStorageLocation.label","موقع تخزين المستندات"},
{"eFM.DocumentCode.label","رمز الوثيقة"},
{"eFM.DocumentFolder.label","مجلد المستند"},
{"eFM.DocumentFolderDetails.label","تفاصيل مجلد المستند"},
{"eFM.DocumentFolderID.label","معرف مجلد المستند"},
{"eFM.DocumentFolderInFSLocn.label","مجلد المستندات في موقع FS"},
{"eFM.DocumentFolderName.label","اسم مجلد المستند"},
{"eFM.DocumentFolderType.label","نوع مجلد المستند"},
{"eFM.DocumentID.label","معرف المستند"},
{"eFM.DocumentName.label","اسم الملف"},
{"eFM.DocumentReturnDetails.label","تفاصيل إعادة المستند"},
{"eFM.Documentscannotberequested.label","لا يمكن طلب المستندات"},
{"eFM.DocumentscannotbeReturned.label","لا يمكن إرجاع المستندات"},
{"eFM.DocumentsinTransit.label","المستندات قيد النقل"},
{"eFM.Documentspendingformorethan.label","المستندات المعلقة لأكثر من"},
{"eFM.DocumentsRequestedin.label","المستندات المطلوبة في"},
{"eFM.DocumentStatus.label","حالة المستند"},
{"eFM.DocumentstobeReturned.label","المستندات المطلوب إرجاعها"},
{"eFM.DocumentTypeCode.label","رمز نوع المستند"},
{"eFM.DocumentTypeinFolder.label","نوع المستند في المجلد"},
{"eFM.DocumentTypeName.label","اسم نوع المستند"},
{"eFM.DTParameter.label","إعدادات DT"},
{"eFM.Dueforreturn.label","مستحق الإرجاع"},
{"eFM.EncounterDeficiencyStatus.label","حالة عجز الزيارة"},
{"eFM.FileCreationDate.label","تاريخ إنشاء الملف"},
{"eFM.FileinPermanentLoc.label","ملف في موقع دائم"},
{"eFM.FileInTransit.label","ملف قيد النقل"},
{"eFM.FileisArchived.label","الملف مؤرشف"},
{"eFM.FileisLost.label","الملف مفقود"},
{"eFM.FileisOutside.label","الملف بالخارج"},
{"eFM.FileIssueDate.label","تاريخ إصدار الملف"},
{"eFM.FileMovement.label","حركة الملف"},
{"eFM.FileNoPatientDetails.label","رقم الملف / بيانات المريض"},
{"eFM.FileOutsideMRD.label","ملف خارج MRD"},
{"eFM.FileRequiredOn.label","الملف مطلوب في"},
{"eFM.FileReturnDetails.label","تفاصيل إعادة الملف"},
{"eFM.FilesCannotbeIssued.label","لا يمكن إصدار الملفات"},
{"eFM.Filescannotberequested.label","لا يمكن طلب الملفات"},
{"eFM.FilescannotbeReturned.label","لا يمكن إرجاع الملفات"},
{"eFM.FilesinTransit.label","الملفات في العبور"},
{"eFM.Filespendingformorethan.label","الملفات المعلقة لأكثر من"},
{"eFM.FilesRequestedin.label","الملفات المطلوبة بتنسيق"},
{"eFM.FilesSelectedforIssue.label","الملفات المختارة للمشكلة"},
{"eFM.FileStatus.label","حالة الملف"},
{"eFM.FilestobeReturned.label","يتم إرجاع الملفات"},
{"eFM.FileStorageLocationDesc.label","وصف موقع تخزين الملفات"},
{"eFM.FileTransportDetails.label","تفاصيل نقل الملف"},
{"eFM.FileTransportModeDescription.label","وصف وضع نقل الملفات"},
{"eFM.FileTypeforFSLocation.label","نوع الملف لموقع FS"},
{"eFM.FileTypeVolumeNo.label","نوع الملف / رقم المجلد"},
{"eFM.FileVolume.label","حجم الملف"},
{"eFM.FMFileType.label","نوع ملف FM"},
{"eFM.FMParameter.label","معلمة FM"},
{"eFM.FMUserAccess.label","وصول مستخدم FM"},
{"eFM.FolderName.label","إسم الملف"},
{"eFM.FollowingFilesReturnDatecannotbeChanged.label","لا يمكن تغيير تاريخ إرجاع الملفات التالية"},
{"eFM.Found.label","وجدت"},
{"eFM.FromLocationCode.label","من كود الموقع"},
{"eFM.FromLoggedInFacility.label","من منشأة تسجيل الدخول"},
{"eFM.FromOtherFacilities.label","من منشأة أخرى"},
{"eFM.FromTO.label","من / الى"},
{"eFM.FSLocation.label","موقع FS"},
{"eFM.FSLocationCode.label","رمز موقع FS"},
{"eFM.FSLocationDescription.label","وصف موقع FS"},
{"eFM.FSLocationIdentity.label","هوية موقع FS"},
{"eFM.GeneratedBy.label","تم إنشاؤها بواسطة"},
{"eFM.HolderName.label","اسم المالك"},
{"eFM.HolderPhoneNo..label","رقم هاتف المالك"},
{"eFM.InactiveFSLocation.label","موقع FS غير نشط"},
{"eFM.InactiveIn.label","غير نشط في"},
{"eFM.InactivePeriod.label","فترة غير نشطة"},
{"eFM.InactiveVolumeNo.label","رقم المجلد غير النشط"},
{"eFM.IncludeInpatients.label","تضمين المرضى الداخليين"},
{"eFM.IncompleteFSLocation.label","موقع FS غير مكتمل"},
{"eFM.InOtherFacility.label","في منشأة أخرى"},
{"eFM.InpatientDetails.label","تفاصيل المرضى الداخليين"},
{"eFM.InReqFSLocation.label","في طلب موقع FS"},
{"eFM.InvalidFile.label","ملف غير صالح"},
{"eFM.IPConfirmedFileList.label","قائمة الملفات المؤكدة للمرضى الداخليين"},
{"eFM.IPPullingList.label","قائمة سحب المرضى الداخليين"},
{"eFM.IPTracerCard.label","بطاقة تتبع المرضى الداخليين"},
{"eFM.IssueDateTime.label","تاريخ / وقت الإصدار"},
{"eFM.IssuedDSLocation.label"," موقع DS المصدر"},
{"eFM.IssuedFSLocation.label"," موقع FS المصدر"},
{"eFM.Issuedon.label","الصادر في"},
{"eFM.IssueFile.label","الملف الصادر"},
{"eFM.IssueFileToOtherFacilities.label","إصدار ملف إلى منشأة أخرى"},
{"eFM.IssueFileWithinFacility.label","إصدار ملف بداخل المنشأة"},
{"eFM.IssueFSLocation.label","موقع اصدار FS"},
{"eFM.IssueTracerCard.label","إصدار بطاقة التتبع"},
{"eFM.IssuingFSLocation.label","موقع اصدار FS"},
{"eFM.LinkBetweenFileandEncounterRequired.label","مطلوب الربط بين الملف و الزيارة"},
{"eFM.LocationReason.label","الموقع / السبب"},
{"eFM.LostDocumentstatus.label","حالة المستند المفقود"},
{"eFM.LostFilesStatus.label","حالة الملفات المفقودة"},
{"eFM.LostFSLocation.label","موقع FS مفقود"},
{"eFM.MandatoryStatutory.label","إلزامي / قانوني"},
{"eFM.ManualEntry.label","الإدخال اليدوي"},
{"eFM.ManualRequest.label","طلب يدوي"},
{"eFM.ManualRequestYN.label","طلب يدوي نعم / لا"},
{"eFM.MedicalRecordDept.label","قسم السجلات الطبية"},
{"eFM.MedicoLegalCase.label","حالة طبية قانونية"},
{"eFM.MonitorDeficiency.label","مراقبة العجز"},
{"eFM.MonitorFileDeficiency.label","مراقبة نقص الملفات"},
{"eFM.Narration.label","السرد"},
{"eFM.NarrationCode.label","كود السرد"},
{"eFM.NarrationDescription.label","وصف السرد"},
{"eFM.NarrationforAutoTrackouttoOPD.label","السرد للتتبع التلقائي لقسم العيادات الخارجية"},
{"eFM.NarrForReturnFileToMRD.label","السرد لإرجاع الملفات إلى MRD"},
{"eFM.NewFSLocation.label","موقع FS جديد"},
{"eFM.NewStatusoftheDocument.label","الوضع الجديد للوثيقة"},
{"eFM.NewStatusoftheFile.label","الوضع الجديد للملف"},
{"eFM.NewVolumeNumber.label","رقم المجلد الجديد"},
{"eFM.NIADueDate.label","تاريخ استحقاق NIA"},
{"eFM.NonPermanentDepartment.label","قسم غير دائم"},
{"eFM.NoofDaystoReturn.label","عدد أيام العودة"},
{"eFM.NoofDaysuptowhichtocheckforappointmentsinFileInquiry.label","عدد الأيام حتى يتم التحقق من المواعيد في الاستعلام عن الملف"},
{"eFM.NoofDaysuptowhichtocheckforbookingsinFileInquiry.label","عدد الأيام التي يتم فيها التحقق من الحجوزات في الاستعلام عن الملف"},
{"eFM.NoofDocs.label","عدد المستندات"},
{"eFM.NoofFiles.label","عدد الملفات"},
{"eFM.NoofHourstoReturn.label","عدد ساعات الإسترداد"},
{"eFM.OnlineReport.label","تقرير عبر الانترنت"},
{"eFM.OPConfirmedFileList.label","قائمة الملفات المؤكدة للمرضى الخارجيين"},
{"eFM.OPDAppointmentfor.label","تعيين قسم العيادات الخارجية ل"},
{"eFM.OPPullingList.label","قائمة السحب للمرضى الخارجيين"},
{"eFM.OPTracerCard.label","بطاقة تعقب المرضى الخارجيين"},
{"eFM.OtherRules.label","قواعد أخرى"},
{"eFM.OutstandingFrom.label","المعلق من"},
{"eFM.OutstandingFSLocation.label","موقع FS معلق"},
{"eFM.OutstandingRequest.label","طلب معلق"},
{"eFM.OutstandingRequestSearchCriteria.label","معايير بحث الطلبات المعلقة"},
{"eFM.OverDueforreturn.label","انتهى موعد الإرجاع"},
{"eFM.PeriodSpecific.label","فترة محددة"},
{"eFM.PermanentDepartment.label","قسم دائم"},
{"eFM.PermanentFSLocation.label","موقع FS دائم"},
{"eFM.PlannedAdmissionFSLocation.label","موقع FS للدخول المتوقع"},
{"eFM.PractitionerResponsible.label","طبيب مسؤول"},
{"eFM.PreferredTime.label","الوقت المفضل"},
{"eFM.PreviousDocumentStatus.label","حالة المستند السابقة"},
{"eFM.PreviousFileStatus.label","حالة الملف السابقة"},
{"eFM.PreviousFSLocation.label","موقع FS السابق"},
{"eFM.PrintBarCode.label","طباعة الرمز الشريطي"},
{"eFM.PrintPullingList.label","طباعة قائمة السحب"},
{"eFM.PrintTelNoinPullingList.label","اطبع رقم الهاتف في قائمة السحب"},
{"eFM.PrintTracerCard.label","طباعة بطاقة التتبع"},
{"eFM.PrintTracerCardonIssueof.label","طباعة بطاقة التتبع عند إصدار"},
{"eFM.Pull.label","سحب"},
{"eFM.PullingListType.label"," نوع قائمة السحب"},
{"eFM.ReasonForBorrowing.label","سبب الاقتراض"},
{"eFM.Receive.label","تسلم"},
{"eFM.ReceivedDetails.label","تفاصيل الإستلام"},
{"eFM.Receivedon.label","تم الإستلام في"},
{"eFM.ReceiveFile.label","الملف المستلم"},
{"eFM.ReceiveFileatMRD.label","استلام ملف في MRD"},
{"eFM.ReceiverName.label","اسم المستلم"},
{"eFM.ReceivingFSLocation.label","موقع استلام FS"},
{"eFM.ReceivingFSLocationIdentity.label","استلام هوية موقع FS"},
{"eFM.ReceivingFSLocn.label","موقع FS المستلم"},
{"eFM.RecordChangeDeficiencydetail.label","تسجيل / تغيير تفاصيل العجز"},
{"eFM.RegisterFileNotPulled.label","لم يتم سحب ملف التسجيل"},
{"eFM.ReportedDateFrom.label","تاريخ الإبلاغ من"},
{"eFM.ReportOptionBy.label","اختيار الإبلاغ من قبل"},
{"eFM.RequestedDocumentDetails.label","تفاصيل المستند المطلوب"},
{"eFM.RequestedFileDetails.label","تفاصيل الملف المطلوب"},
{"eFM.RequestedFiles.label","الملفات المطلوبة"},
{"eFM.RequestedDetails.label","التفاصيل المطلوبة"},
{"eFM.RequestedFrom.label","مطلوب من"},
{"eFM.RequestedOnDate.label","طلبت في التاريخ"},
{"eFM.RequesterDetails.label","تفاصيل مقدم الطلب"},
{"eFM.RequestFileFromOtherFacilities.label","طلب ملف من منشأة أخرى"},
{"eFM.RequestFileWithinFacility.label","طلب ملف داخل منشأة"},
{"eFM.RequestFrom.label","طلب من"},
{"eFM.Requesting.label","جاري الطلب"},
{"eFM.RequestModeDescription.label","وصف وضع الطلب"},
{"eFM.RequestofDocumentsFrom.label","طلب مستند (مستندات) من"},
{"eFM.RequestRemarks.label","ملاحظات الطلب"},
{"eFM.RequestTo.label","طلب إلى"},
{"eFM.ResponsiblePractitioner.label","طبيب مسؤول"},
{"eFM.RestrictionacrossFSLocnIdentities.label","القيود عبر هويات FS موقع"},
{"eFM.ReturnDate.label","تاريخ الإرجاع"},
{"eFM.ReturnDueDate.label","تاريخ استحقاق الإرجاع"},
{"eFM.ReturnDueDateTime.label","تاريخ / وقت الاستحقاق للإرجاع"},
{"eFM.ReturnFile.label","إرجاع الملف"},
{"eFM.ReturnFileatMRD.label","إرجاع الملف في MRD"},
{"eFM.ReturnFromArchived.label","الإرجاع من الأرشيف"},
{"eFM.Returning.label","إرجاع"},
{"eFM.ReturningFSLocation.label","إرجاع موقع FS"},
{"eFM.ReturnRemarks.label","ملاحظات الإرجاع"},
{"eFM.ScheduleCancelled.label","الجدول ملغى"},
{"eFM.SecurityAccesstobeenforced.label","يتم فرض الوصول الأمني"},
{"eFM.SecurityRules.label","قواعد الأمان"},
{"eFM.Specialitys.label","التخصصات"},
{"eFM.Statutory.label","قانوني"},
{"eFM.Supplementary.label","تكميلي"},
{"eFM.ThirdPartyName.label","اسم الطرف الثالث"},
{"eFM.ToFSLocation.label","إلى موقع FS"},
{"eFM.ToLocationCode.label","إلى رمز الموقع"},
{"eFM.ToOtherFacilities.label","إلى منشأة أخرى"},
{"eFM.TotalNoofDocuments.label","العدد الإجمالي للوثائق"},
{"eFM.TotalNoofFiles.label","إجمالي عدد الملفات"},
{"eFM.TracerCard.label","بطاقة التتبع"},
{"eFM.TrackedoutBy.label","تم التعقب بواسطة"},
{"eFM.TrackoutfilestoOPD.label","ملفات التعقب إلى العيادات الخارجية"},
{"eFM.TrackoutOuttoOPD.label","تعقب إلى العيادات الخارجية"},
{"eFM.TransferFile.label","نقل الملف"},
{"eFM.TransferFileoutsideMRD.label","نقل الملف خارج MRD"},
{"eFM.Transferof.label","نقل"},
{"eFM.Transit.label","نقل"},
{"eFM.TransportDetail.label","تفاصيل النقل"},
{"eFM.UpdatedBy.label","تم التحديث بواسطة"},
{"eFM.UpdatedDate.label","تاريخ التحديث"},
{"eFM.VolumeNo.label","رقم وحدة التخزين"},
{"eFM.WithInFacility.label","في المنشأة"},
{"eFM.TrackOut.label","التعقب"},
{"eFM.FileisInside.label","الملف بالداخل"},
{"eFM.ShowAllFiles.label","إظهار كافة الملفات"},
{"eFM.Files.label","الملفات"},
{"eFM.ClinicName.label","اسم العيادة"},
{"eFM.QIDno.label","رقم QID"},
{"eFM.TotalNoOfBookings.label","إجمالي عدد الحجوزات"},
{"eFM.PrintPullingLable.label","طباعة ملصق السحب"},
{"eFM.PrintIdentificationLabel.label","طباعة بطاقة التعريف"},
{"eFM.NeverTobeArchived.label","أبدا لا يتم أرشفتها"},
{"eFM.AutoTrackOutUponCnPL.label","تتبع تلقائي عند تأكيد قائمة السحب"},
{"eFM.AcceptOutsideTransitFiles.label","قبول الملفات الخارجية و قيد النقل مباشرة في تلقي ملف في MRD"},
{"eFM.EnableMonitorFileDefFSLocation.label","قم بتمكين مراقبة عجز الملفات عند عدم تحديد موقع FS غير مكتمل"},
{"eFM.AutoCheckPrintPatientFileRequestSlip.label","الفحص التلقائي لطباعة قسيمة طلب ملف المريض في ملف الطلب"},
{"eFM.IncludePreviousDayRequest.label","قم بتضمين طلب اليوم السابق"},
{"eFM.not.label","ليس"},
{"eFM.Movement.label","حركة"},
{"eFM.Defined.label","يعرف"},
{"eFM.Tracked.label","مجنزرة"},
{"eFM.Nat.label","نات"},
{"eFM.forwhom.label","لمن"},
{"eFM.pullinglist.label","قائمة السحب"},
{"eFM.FS.label","FS"},
{"eFM.OPDFile.label","ملف قسم العيادات الخارجية"},
{"eFM.IPDFile.label","ملف قسم المرضى الداخليين"},
{"eFM.RequireonDate.label","مطلوب في التاريخ"},
{"eFM.ConfirmPullingList.label","تأكيد قائمة السحب "},
{"eFM.TrackoutfilestoIPW.label","تعقب الملفات إلى IPW"},
{"eFM.PrintPatientFileRequestSlip.label","طباعة قسيمة طلب ملف المريض"},
{"eFM.FileCreatedDate.label","تاريخ إنشاء الملف"},
{"eFM.RequiredOnDate.label","مطلوب في التاريخ"},
{"eFM.BookingReqSlip.label","قسيمة طلب الحجز"},
{"eFM.AppointmentReqSlip.label","قسيمة طلب موعد"},
{"eFM.RequestingPractitioner.label","الطبيب الطالب"},
{"eFM.RequestedDate/Time.label","التاريخ / الوقت المطلوب"},
{"eFM.AdmitDateTime.label","تاريخ / وقت الدخول"},
{"eFM.RequiredonDate/Time.label","مطلوب في التاريخ / الوقت"},
{"eFM.RefreshIntervalforIssuefile.label","تحديث الفاصل لإصدار الملف"},
{"eFM.Transaction.label","عملية"},
{"eFM.DateTime.label","تاريخ / وقت"},
{"eFM.FSLocation.label","موقع FS"},
{"eFM.Reason.label","السبب"},
{"eFM.ForWhom.label","لمن"},
{"eFM.MrdLocation.label","موقع MRD"},
{"eFM.MrdCode.label","كود MRD"},
{"eFM.MrdDescription.label","وصف MRD"},
{"eFM.TransferredDateTime.label","التاريخ / الوقت المحول"},
{"eFM.Day.label","يوم"},
{"eFM.Hour.label","ساعة"},
{"eFM.fromdischarge.label","من الخروج"}

	};
}
