/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eFM.resources;

import java.util.*;

public class  Labels  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
			{"eFM.AcceptFileTypeandVolumeNoforAutoRequest.label","Accept File Type and Volume No for Auto Request"},
			{"eFM.AccesstoallFSLocations.label","Access to all FS Locations"},
			{"eFM.AccountablePerson.label","Accountable Person"},
			{"eFM.AcrossFacility.label","Across Facility"},
			{"eFM.ActiveVolumeNo.label","Active Volume No"},
			{"eFM.AppointmentDatefield.label","Appointment Date field"},
			{"eFM.AppointmentDetail.label","Appointment Detail"},
			{"eFM.ApptCancelled.label","Appt. Cancelled"},
			{"eFM.ApptTransfered.label","Appt. Transfered"},
			{"eFM.Archeived.label","Archeived"},
			{"eFM.ArchiveDocumentstatus.label","Archive Document status"},
			{"eFM.ArchiveFilesStatus.label","Archive Files Status"},
			{"eFM.Assign.label","Assign"},
			{"eFM.AssignAllDocumentsTo.label","Assign All Documents To"},
			{"eFM.AssignAllFilesTo.label","Assign All Files To"},
			{"eFM.AssignFSLocation.label","Assign FS Location"},
			{"eFM.AutoReceiptRules.label","Auto Receipt Rules"},
			{"eFM.AutoReceive.label","Auto Receive"},
			{"eFM.AutoTrackouttoIPW.label","Auto Track out to IPW"},
			{"eFM.AutoTrackouttoOPD.label","Auto Track out to OPD"},
			{"eFM.BelongstoMRD.label","Belongs to MRD"},
			{"eFM.CancelledBooking.label","Cancelled Booking"},
			{"eFM.CancelRequestRemarks.label","Cancel Request Remarks"},
			{"eFM.CarriedBy.label","Carried By"},
			{"eFM.ChangeFileReturnDate.label","Change File Return Date"},
			{"eFM.ChangeFileReturnDateFilesNotAllowed.label","Change File Return Date - Files Not Allowed"},
			{"eFM.ChangeFileStatus.label","Change File Status"},
			{"eFM.ChangeFSLocation.label","Change FS Location"},
			{"eFM.ClinicType.label","Clinic Type"},
			{"eFM.ConfirmedFiles.label","Confirm File Receipt"},
			{"eFM.ConfirmFileReceipt.label","Confirmed Files"},
			{"eFM.ConfirmPullingListRemarks.label","Confirm Pulling List Remarks"},
			{"eFM.ConfirmReceipt.label","Confirm Receipt"},
			{"eFM.ConfirmReturn.label","Confirm Return"},
			{"eFM.ControlPullingListGenerationbyGender.label","Control Pulling List Generation by Gender"},
			{"eFM.CreateFileVolume.label","Create File Volume"},
			{"eFM.CurrentDocumentStatus.label","Current Document Status"},
			{"eFM.CurrentFS.label","Current FS"},
			{"eFM.CurrentFSLocation.label","Current FS Location"},
			{"eFM.CurrentFSLocationIdentity.label","Current FS Location Identity"},
			{"eFM.CurrentFSlocationoftheDocument.label","Current FS location of the Document"},
			{"eFM.CurrentFSlocationoftheFile.label","Current FS location of the File"},
			{"eFM.CurrentStatusoftheDocument.label","Current Status of the Document"},
			{"eFM.CurrentStatusoftheFile.label","Current Status of the File"},
			{"eFM.CurrrentVolumeNumber.label","Current Volume Number"},
			{"eFM.CurrrentVolumeStatus.label","Current Volume Status"},
			{"eFM.DateofIssue.label","Date of Issue"},
			{"eFM.DateReported.label","Date Reported"},
			{"eFM.DateResolvedCancelled.label","Date Resolved / Cancelled"},
			{"eFM.DateTimeReported.label","Date/Time Reported"},
			{"eFM.DateTimeResolvedCancelled.label","Date/Time Resolved / Cancelled"},
			{"eFM.DefaultSettings.label","Default Settings"},
			{"eFM.Deficiencies.label","Deficiencies"},
			{"eFM.Deficiency.label","Deficiency"},
			{"eFM.DeficiencyCode.label","Deficiency Code"},
			{"eFM.DeficiencyCriteria.label","Deficiency Criteria"},
			{"eFM.DeficiencyDescription.label","Deficiency Description"},
			{"eFM.DeficiencyStatus.label","Deficiency Status"},
			{"eFM.DeficiencyType.label","Deficiency Type"},
			{"eFM.De-Link.label","De-Link"},
			{"eFM.DestFSLocationIdentity.label","Dest FS Location Identity"},
			{"eFM.DocIssueDate.label","Doc Issue Date"},
			{"eFM.DocsSelectedforIssue.label","Docs Selected for Issue"},
			{"eFM.DocStorageLocation.label","Doc Storage Location"},
			{"eFM.DocumentCode.label","Document Code"},
			{"eFM.DocumentFolder.label","Document Folder"},
			{"eFM.DocumentFolderDetails.label","Document Folder Details"},
			{"eFM.DocumentFolderID.label","Document Folder ID"},
			{"eFM.DocumentFolderInFSLocn.label","Document Folder In FSLocn"},
			{"eFM.DocumentFolderName.label","Document Folder Name"},
			{"eFM.DocumentFolderType.label","Document Folder Type"},
			{"eFM.DocumentID.label","Document ID"},
			{"eFM.DocumentName.label","Document Name"},
			{"eFM.DocumentReturnDetails.label","Document Return Details"},
			{"eFM.Documentscannotberequested.label","Documents cannot be requested"},
			{"eFM.DocumentscannotbeReturned.label","Documents cannot be Returned"},
			{"eFM.DocumentsinTransit.label","Documents in Transit"},
			{"eFM.Documentspendingformorethan.label","Documents pending for more than"},
			{"eFM.DocumentsRequestedin.label","Documents Requested in"},
			{"eFM.DocumentStatus.label","Document Status"},
			{"eFM.DocumentstobeReturned.label","Documents to be Returned"},
			{"eFM.DocumentTypeCode.label","Document Type Code"},
			{"eFM.DocumentTypeinFolder.label","Document Type in Folder"},
			{"eFM.DocumentTypeName.label","Document Type Name"},
			{"eFM.DTParameter.label","DT Parameter"},
			{"eFM.Dueforreturn.label","Due for  return"},
			{"eFM.EncounterDeficiencyStatus.label","Encounter Deficiency Status "},
			{"eFM.FileCreationDate.label","File Creation Date"},
			{"eFM.FileinPermanentLoc.label","File in Permanent Loc"},
			{"eFM.FileInTransit.label","File In Transit"},
			{"eFM.FileisArchived.label","File is Archived"},
			{"eFM.FileisLost.label","File is Lost"},
			{"eFM.FileisOutside.label","File is Outside"},
			{"eFM.FileIssueDate.label","File Issue Date"},
			{"eFM.FileMovement.label","File Movement"},
			{"eFM.FileNoPatientDetails.label","File No / Patient Details"},
			{"eFM.FileOutsideMRD.label","File Outside MRD"},
			{"eFM.FileRequiredOn.label","File Required On"},
			{"eFM.FileReturnDetails.label","File Return Details"},
			{"eFM.FilesCannotbeIssued.label","Files Cannot be Issued"},
			{"eFM.Filescannotberequested.label","Files cannot be requested"},
			{"eFM.FilescannotbeReturned.label","Files cannot be Returned"},
			{"eFM.FilesinTransit.label","Files in Transit"},
			{"eFM.Filespendingformorethan.label","Files pending for more than"},
			{"eFM.FilesRequestedin.label","Files Requested in"},
			{"eFM.FilesSelectedforIssue.label","Files Selected for Issue"},
			{"eFM.FileStatus.label","File Status"},
			{"eFM.FilestobeReturned.label","Files to be Returned"},
			{"eFM.FileStorageLocationDesc.label","File Storage Location Desc"},
			{"eFM.FileTransportDetails.label","File Transport Details"},
			{"eFM.FileTransportModeDescription.label","File Transport Mode Description"},
			{"eFM.FileTypeforFSLocation.label","File Type for FS Location"},
			{"eFM.FileTypeVolumeNo.label","File Type / Volume No"},
			{"eFM.FileVolume.label","File Volume"},
			{"eFM.FMFileType.label","FM File Type"},
			{"eFM.FMParameter.label","FM Parameter"},
			{"eFM.FMUserAccess.label","FM User Access"},
			{"eFM.FolderName.label","Folder Name"},
			{"eFM.FollowingFilesReturnDatecannotbeChanged.label","Following Files Return Date cannot be Changed"},
			{"eFM.Found.label","Found"},
			{"eFM.FromLocationCode.label","From Location Code"},
			{"eFM.FromLoggedInFacility.label","From Logged In Facility"},
			{"eFM.FromOtherFacilities.label","From Other Facilities"},
			{"eFM.FromTO.label","From / To"},
			{"eFM.FSLocation.label","FS Location"},
			{"eFM.FSLocationCode.label","FS Location Code"},
			{"eFM.FSLocationDescription.label","FS Location Description"},
			{"eFM.FSLocationIdentity.label","FS Location Identity"},
			{"eFM.GeneratedBy.label","Generated By"},
			{"eFM.HolderName.label","Holder Name"},
			{"eFM.HolderPhoneNo..label","Holder Phone No."},
			{"eFM.InactiveFSLocation.label","Inactive FS Location"},
			{"eFM.InactiveIn.label","Inactive In"},
			{"eFM.InactivePeriod.label","Inactive Period"},
			{"eFM.InactiveVolumeNo.label","Inactive Volume No"},
			{"eFM.IncludeInpatients.label","Include Inpatients"},
			{"eFM.IncompleteFSLocation.label","Incomplete FS Location"},
			{"eFM.InOtherFacility.label","In Other Facility"},
			{"eFM.InpatientDetails.label","Inpatient Details"},
			{"eFM.InReqFSLocation.label","In Req FS Location"},
			{"eFM.InvalidFile.label","Invalid File"},
			{"eFM.IPConfirmedFileList.label","IP Confirmed File List"},
			{"eFM.IPPullingList.label","IP Pulling List"},
			{"eFM.IPTracerCard.label","IP Tracer Card"},
			{"eFM.IssueDateTime.label","Issue Date/Time"},
			{"eFM.IssuedDSLocation.label","Issued DS Location"},
			{"eFM.IssuedFSLocation.label","Issued FS Location"},
			{"eFM.Issuedon.label","Issued on"},
			{"eFM.IssueFile.label","Issue File"},
			{"eFM.IssueFileToOtherFacilities.label","Issue File To Other Facilities"},
			{"eFM.IssueFileWithinFacility.label","Issue File Within Facility"},
			{"eFM.IssueFSLocation.label","Issue FS Location"},
			{"eFM.IssueTracerCard.label","Issue Tracer Card"},
			{"eFM.IssuingFSLocation.label","Issuing FS Location"},
			{"eFM.LinkBetweenFileandEncounterRequired.label","Link Between File and Encounter Required"},
			{"eFM.LocationReason.label","Location/Reason"},
			{"eFM.LostDocumentstatus.label","Lost Document status"},
			{"eFM.LostFilesStatus.label","Lost Files Status"},
			{"eFM.LostFSLocation.label","Lost FS Location"},
			{"eFM.MandatoryStatutory.label","Mandatory/Statutory"},
			{"eFM.ManualEntry.label","Manual Entry"},
			{"eFM.ManualRequest.label","Manual Request"},
			{"eFM.ManualRequestYN.label","Manual Request Y/N"},
			{"eFM.MedicalRecordDept.label","Medical Record Dept"},
			{"eFM.MedicoLegalCase.label","Medico Legal Case"},
			{"eFM.MonitorDeficiency.label","Monitor Deficiency"},
			{"eFM.MonitorFileDeficiency.label","Monitor File Deficiency"},
			{"eFM.Narration.label","Narration"},
			{"eFM.NarrationCode.label","Narration Code"},
			{"eFM.NarrationDescription.label","Narration Description"},
			{"eFM.NarrationforAutoTrackouttoOPD.label","Narration for Auto Track out to OPD"},
			{"eFM.NarrForReturnFileToMRD.label","Narration for returning files to MRD"},
			{"eFM.NewFSLocation.label","New FS Location"},
			{"eFM.NewStatusoftheDocument.label","New Status of the Document"},
			{"eFM.NewStatusoftheFile.label","New Status of the File"},
			{"eFM.NewVolumeNumber.label","New Volume Number"},
			{"eFM.NIADueDate.label","NIA Due Date"},
			{"eFM.NonPermanentDepartment.label","Non-Permanent Department"},
			{"eFM.NoofDaystoReturn.label","No of Days to Return"},
			{"eFM.NoofDaysuptowhichtocheckforappointmentsinFileInquiry.label","No of Days up to which to check for appointments in File Inquiry"},
			{"eFM.NoofDaysuptowhichtocheckforbookingsinFileInquiry.label","No of Days up to which to check for bookings in File Inquiry"},
			{"eFM.NoofDocs.label","No of Docs"},
			{"eFM.NoofFiles.label","No of Files"},
			{"eFM.NoofHourstoReturn.label","No of Hours to Return"},
			{"eFM.OnlineReport.label","Online Report"},
			{"eFM.OPConfirmedFileList.label","OP Confirmed File List"},
			{"eFM.OPDAppointmentfor.label","OPD Appointment for"},
			{"eFM.OPPullingList.label","OP Pulling List"},
			{"eFM.OPTracerCard.label","OP Tracer Card"},
			{"eFM.OtherRules.label","Other Rules"},
			{"eFM.OutstandingFrom.label","Outstanding From"},
			{"eFM.OutstandingFSLocation.label","Outstanding FS Location"},
			{"eFM.OutstandingRequest.label","Outstanding Request"},
			{"eFM.OutstandingRequestSearchCriteria.label","Outstanding Request Search Criteria"},
			{"eFM.OverDueforreturn.label","Over Due for  return"},
			{"eFM.PeriodSpecific.label","Period Specific"},
			{"eFM.PermanentDepartment.label","Permanent Department"},
			{"eFM.PermanentFSLocation.label","Permanent FS Location"},
			{"eFM.PlannedAdmissionFSLocation.label","Planned Admission FS Location"},
			{"eFM.PractitionerResponsible.label","Practitioner Responsible"},
			{"eFM.PreferredTime.label","Preferred Time"},
			{"eFM.PreviousDocumentStatus.label","Previous Document Status"},
			{"eFM.PreviousFileStatus.label","Previous File Status"},
			{"eFM.PreviousFSLocation.label","Previous FS Location"},
			{"eFM.PrintBarCode.label","Print Bar Code"},
			{"eFM.PrintPullingList.label","Print Pulling List"},
			{"eFM.PrintTelNoinPullingList.label","Print Tel. No in Pulling List"},
			{"eFM.PrintTracerCard.label","Print Tracer Card"},
			{"eFM.PrintTracerCardonIssueof.label","Print Tracer Card on Issue of"},
			{"eFM.Pull.label","Pull"},
			{"eFM.PullingListType.label","Pulling List Type"},
			{"eFM.ReasonForBorrowing.label","Reason For Borrowing"},
			{"eFM.Receive.label","Receive"},
			{"eFM.ReceivedDetails.label","Received Details"},
			{"eFM.Receivedon.label","Received on"},
			{"eFM.ReceiveFile.label","Receive File"},
			{"eFM.ReceiveFileatMRD.label","Receive File at MRD"},
			{"eFM.ReceiverName.label","Receiver Name"},
			{"eFM.ReceivingFSLocation.label","Receiving FS Location"},
			{"eFM.ReceivingFSLocationIdentity.label","Receiving FS Location Identity"},
			{"eFM.ReceivingFSLocn.label","Receiving FS Locn"},
			{"eFM.RecordChangeDeficiencydetail.label","Record/Change Deficiency detail"},
			{"eFM.RegisterFileNotPulled.label","Register File Not Pulled"},
			{"eFM.ReportedDateFrom.label","Reported Date From"}, 
			{"eFM.ReportOptionBy.label","Report Option By"},
			{"eFM.RequestedDocumentDetails.label","Requested Document Details"},
			{"eFM.RequestedFileDetails.label","Requested File Details"},
			{"eFM.RequestedFiles.label","Requested Files"},
			{"eFM.RequestedDetails.label","Requested Details"},
			{"eFM.RequestedFrom.label","Requested From"},
			{"eFM.RequestedOnDate.label","Requested On Date"},
			{"eFM.RequesterDetails.label","Requester Details"},
			{"eFM.RequestFileFromOtherFacilities.label","Request File From Other Facilities"},
			{"eFM.RequestFileWithinFacility.label","Request File Within Facility"},
			{"eFM.RequestFrom.label","Request From"},
			{"eFM.Requesting.label","Requesting"},
			{"eFM.RequestModeDescription.label","Request Mode Description"},
			{"eFM.RequestofDocumentsFrom.label","Request of Document(s) From"},
			{"eFM.RequestRemarks.label","Request Remarks"},
			{"eFM.RequestTo.label","Request To"},
			{"eFM.ResponsiblePractitioner.label","Responsible Practitioner"},
			{"eFM.RestrictionacrossFSLocnIdentities.label","Restriction across FS Locn Identities"},
			{"eFM.ReturnDate.label","Return Date"},
			{"eFM.ReturnDueDate.label","Return Due Date"},
			{"eFM.ReturnDueDateTime.label","Return Due Date/Time"},
			{"eFM.ReturnFile.label","Return File"},
			{"eFM.ReturnFileatMRD.label","Return File at MRD"},
			{"eFM.ReturnFromArchived.label","Return From Archived"},
			{"eFM.Returning.label","Returning"},
			{"eFM.ReturningFSLocation.label","Returning FS Location"},
			{"eFM.ReturnRemarks.label","Return Remarks"},
			{"eFM.ScheduleCancelled.label","Schedule Cancelled"},
			{"eFM.SecurityAccesstobeenforced.label","Security Access to be enforced"},
			{"eFM.SecurityRules.label","Security Rules"},
			{"eFM.Specialitys.label","Specialities"},
			{"eFM.Statutory.label","Statutory"},
			{"eFM.Supplementary.label","Supplementary"},
			{"eFM.ThirdPartyName.label","Third Party Name"},
			{"eFM.ToFSLocation.label","To FS Location"},
			{"eFM.ToLocationCode.label","To Location Code"},
			{"eFM.ToOtherFacilities.label","To Other Facilities"},
			{"eFM.TotalNoofDocuments.label","Total No of Documents"},
			{"eFM.TotalNoofFiles.label","Total No of Files"},
			{"eFM.TracerCard.label","Tracer Card"},
			{"eFM.TrackedoutBy.label","Trackedout By"},
			{"eFM.TrackoutfilestoOPD.label","Trackout files to OPD"},
			{"eFM.TrackoutOuttoOPD.label","Trackout to OPD"},
			{"eFM.TransferFile.label","Transfer File"},
			{"eFM.TransferFileoutsideMRD.label","Transfer File outside MRD"},
			{"eFM.Transferof.label","Transfer of"},
			{"eFM.Transit.label","Transit"},
			{"eFM.TransportDetail.label","Transport Detail"},
			{"eFM.UpdatedBy.label","Updated By"},
			{"eFM.UpdatedDate.label","Updated Date"},
			{"eFM.VolumeNo.label","Volume No"},
			{"eFM.WithInFacility.label","With In Facility"},
			{"eFM.TrackOut.label","Track Out"},
			{"eFM.FileisInside.label","File is Inside"},
			{"eFM.ShowAllFiles.label","Show All Files"},
			{"eFM.Files.label","Files"},
			{"eFM.ClinicName.label","Clinic Name"}, 
			{"eFM.QIDno.label","QID No"}, 
			{"eFM.TotalNoOfBookings.label","Total Number of Bookings"},
			{"eFM.PrintPullingLable.label","Print Pulling Label"},
			{"eFM.PrintIdentificationLabel.label","Print Identification Label"},
			{"eFM.NeverTobeArchived.label","Never To be Archived"},
			{"eFM.AutoTrackOutUponCnPL.label","Auto Track Out Upon Confirm Pulling List"},
			{"eFM.AcceptOutsideTransitFiles.label","Accept Outside & In Transit Files Directly in Receive File at MRD"},
			{"eFM.EnableMonitorFileDefFSLocation.label","Enable Monitor File Deficiency when Incomplete FS Location not defined"},
			/*Below Line Added for this CRF[SKR-CRF-0012]*/
			{"eFM.AutoCheckPrintPatientFileRequestSlip.label","Auto Check Print Patient File Request Slip in Request File"},
			{"eFM.IncludePreviousDayRequest.label","Include Previous Day Request"},
			

            // Reports related Lables added on 20/1/2009

			{"eFM.not.label","Not"},
			{"eFM.Movement.label","Movement"},
			{"eFM.Defined.label","Defined"},
			{"eFM.Tracked.label","Tracked"},
			{"eFM.Nat.label","Nat"},
			{"eFM.forwhom.label","for whom"},
			{"eFM.pullinglist.label","pulling list"},
			{"eFM.FS.label","FS"},
			{"eFM.OPDFile.label","OPD File"},
			{"eFM.IPDFile.label","IPD File"},
			{"eFM.RequireonDate.label","Require on Date"},
			{"eFM.ConfirmPullingList.label","Confirm Pulling List"},
			{"eFM.TrackoutfilestoIPW.label","Trackout files to IPW"},
			{"eFM.PrintPatientFileRequestSlip.label","Print Patient File Request Slip"},
            // Reports related Lables added on 11/6/2009--AK006-CRF
			{"eFM.FileCreatedDate.label","File Created Date"},
			{"eFM.RequiredOnDate.label","Required On Date"},
            {"eFM.BookingReqSlip.label","Booking Request Slip"},
			{"eFM.AppointmentReqSlip.label","Appointment Request Slip"},
			{"eFM.RequestingPractitioner.label","Requesting Practitioner"},
			{"eFM.RequestedDate/Time.label","Requested Date/Time"},
			{"eFM.AdmitDateTime.label","Admit Date/Time"},
			{"eFM.RequiredonDate/Time.label","Required on Date/Time"},
			{"eFM.RefreshIntervalforIssuefile.label","Refresh Interval for Issue file "},
			//Added for HSA-CRF-0306
			{"eFM.Transaction.label","Transaction"},
			{"eFM.DateTime.label","Date Time"},
			{"eFM.FSLocation.label","FS Location"},
			{"eFM.Reason.label","Reason"},
			{"eFM.ForWhom.label","For Whom"},
			{"eFM.MrdLocation.label","MRD Location"},
			{"eFM.MrdCode.label","MRD Code"},
			{"eFM.MrdDescription.label","MRD Description"},
			{"eFM.TransferredDateTime.label","Transferred Date/Time "},
            {"eFM.Day.label","Day"},
            {"eFM.Hour.label","Hour"},
            {"eFM.fromdischarge.label","from discharge"} 			
	};
}
