/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMO.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eMO.Diseasedeath.label","疾病直接导致死亡"},
		{"eMO.OtherSignificantCond.label","其它�?�?�?�件"},
		{"eMO.AmputatedBodyPart.label","截肢部�?"},
		{"eMO.AntecedentCause.label","先行原因"},
		{"eMO.ApprovedDateFrom.label","核定日期"},
		{"eMO.ApprovedDateTo.label","核定日期"},
		{"eMO.AreaDesc.label","区域�??述"},
		{"eMO.AreaType.label","区域类型"},
		{"eMO.AssignedDate.label","指定日期"},
		{"eMO.AutopsyNoDetailsRequired.label","尸检一些细节需�?�??�?�"},
		{"eMO.AutopsyNoFormat.label","尸检数字格�?"},
		{"eMO.BodyConditionType.label","身体�?�件类型"},
		{"eMO.BayTableAvailChart.label","湾/表�?�用性图表"},
		{"eMO.BayTableNo.label","湾/表没有"},
		{"eMO.BayNo.label","湾�?��?？？"},
		{"eMO.Body.label","身体"},
		{"eMO.BodyCondition.label","身体状况"},
		{"eMO.BodyConditionCode.label","身体状况代�?"},
		{"eMO.BodyConditionDesc.label","身体状况�??述"},
//		{"eMO.BodyDisToMortuary.label","Body Dispatch To Mortuary"},
//		{"eMO.BodyFoundAt.label","Body Found At"},
//		{"eMO.BodyIdentifiedBy.label","Body Identified By"},
		{"eMO.BodyMovement.label","身体�?动"},
		{"eMO.BodyPartCode.label","人体部件代�?"},
		{"eMO.BodyPartDesc.label","人体部件�??述"},
		{"eMO.BodyPartReceiptDateTime.label","正文部分收到日期时间"},
		{"eMO.BodyPartType.label","正文部分类型"},
		{"eMO.BodyReceipt.label","机构收到的日期/时间"},
		{"eMO.BodyRelDateTimefromSource.label","人体释放的日期/时间从�?"},
		{"eMO.BroughtByPolice.label","警方�??请"},
		{"eMO.BurialPermit.label","埋葬许�?��?"},
		{"eMO.BurialPermitApprovalDate.label","埋葬许�?��?批准日期"},
		{"eMO.BurialPermitApprovedBy.label","埋葬许�?��?核准"},
		{"eMO.BurialPermitApprovedByName.label","埋葬许�?��?核准的�??称"},
		{"eMO.BurialPermitNumber.label","埋葬许�?��?编�?�"},
		{"eMO.BurialPermitIssueDateTime.label","埋葬许�?��?问题的日期/时间"},
		{"eMO.BurialPermitIssued.label","埋葬�?�出的许�?��?"},
		{"eMO.Capacity.label","能力"},
		{"eMO.Claimant.label","索赔"},
		{"eMO.ClaimantAccompany.label","陪�?�索赔"},
		{"eMO.ClaimantCode.label","索赔代�?"},
		{"eMO.ClaimantDesc.label","索赔说明"},
		{"eMO.ClaimantType.label","索赔类型"},
		{"eMO.ClaimantTypeRelat.label","索赔类型/关系"},
		{"eMO.Clinical.label","临床"},
		{"eMO.ClinicalPostmortem.label","临床死�?�"},
		{"eMO.CollectionTime.label","收集时间"},
		{"eMO.ConsentFormReceivDate.label","�?��?书收到日期/时间"},
		{"eMO.ConsentCode.label","�?��?代�?"},
		{"eMO.ConsentDesc.label","�?��?�??述"},
		{"eMO.ConsentFormReceivedBy.label","收到�?��?书"},
		{"eMO.ConsentFormType.label","�?��?书�?类"},
		{"eMO.ConsentGivenBy.label","�?��?的情况"},
		{"eMO.CutoffperiodPatientsfromMPI.label","�?�产期间寻找死者患者的MPI？？"},
		{"eMO.DateTimeOfClaiming.label","日期时间的�?求"},
		{"eMO.DeadFetus.label","死胎"},
		{"eMO.DeceasedMortuaryRegNoFormat.label","死者的殓房登记�?��?格�?"},
		{"eMO.DeceasedPatientDetls.label","死者病人细节"},
		{"eMO.DeceasedPatientID.label","死者病人编�?�"},
		{"eMO.DeceasedPatientName.label","死者病人的�??字"},
		{"eMO.DeceasedReg.label","死者登记"},
		{"eMO.DetlsofSpeciCollected.label","详细资料采集的标本"},
		{"eMO.DonorCardAvlbl.label","�??助�?��?�用"},
		{"eMO.DonorCardInfo.label","�??助�?�信�?�"},
		{"eMO.DonorCardNo.label","�??助�?��?�"},
		{"eMO.EmbassyCertificateNo.label","大使馆�?书�?�"},
		{"eMO.EmbassyCountry.label","大使馆的国家"},
		{"eMO.EndAutopsyNo.label","尸体解剖完人数"},
		{"eMO.EndPostmortem.label","死�?�"},
		{"eMO.ExportDeceasedBodyPart.label","尸体/器官�?出"},
		{"eMO.ExportationAddress.label","�?出地�?�"},
		{"eMO.ExportationRequired.label","�?出请求"},
		{"eMO.Finding.label","查找"},
		{"eMO.GenerateBurialPermit.label","生�?埋葬许�?��?"},
		{"eMO.GenerateBurialPermitNo.label","生�?埋葬许�?��?编�?�"},
		{"eMO.HealthOfficer.label","�?�生署"},
		{"eMO.HealthOfficerRemarks.label","�?�生官员言论"},
		{"eMO.HighRiskBodyPart.label","高风险身体器官"},
		{"eMO.IdentificationMarks.label","识别标记"},
		{"eMO.InternalReport.label","内部报告"},
		{"eMO.ListoforganforDonation.label","清�?�器官�??赠"},
		{"eMO.LocationAvailability.label","�?置状况"},
		{"eMO.LocationforArea.label","�?置区域"},
		{"eMO.LocationStatus.label","�?置状�?"},
		{"eMO.MannerofDeath.label","死亡方�?"},
		{"eMO.MannerOfDeathCode.label","死亡的方�?代�?"},
		{"eMO.MannerOfDeathDesc.label","死亡的方�?�??述"},
		{"eMO.MannerOfDeathType.label","死亡的方�?类型"},
		{"eMO.MedicoLegal.label","医学法律"},
		{"eMO.MedicolegalPostmortem.label","法医学尸体"},
		{"eMO.MobilePhoneNo.label","移动电�?�?��?"},
		{"eMO.Morethan.label","超过"},
		{"eMO.MortuaryNextRegNo.label","殓房下一登记�?��?"},
		{"eMO.MortuaryRegEndNo.label","殓房结�?�登记�?��?"},
		{"eMO.MortuaryRegNoRequired.label","殓房登记�?��?的细节需�?�??�?�"},
		{"eMO.MortuaryRegStartNo.label","殓房开始登记�?��?"},
		{"eMO.NextAutopsyNo.label","下一埋葬�?�"},
		{"eMO.NextBurialPermitNo.label","下一埋葬�?许�?�"},
		{"eMO.NotReleased.label","没有公布"},
		{"eMO.NotRequested.label","没有�?求"},
		{"eMO.NoOfDaysToPrsrvUnkwnBody.label","�?存尸体天数"},
		{"eMO.OrganDonation.label","器官�??赠"},
		{"eMO.OrganforDonation.label","器官�??赠"},
		{"eMO.OrgansForDonationCode.label","器官�??赠代�?"},
		{"eMO.OrgansForDonationDesc.label","器官�??赠�??述"},
		{"eMO.OrgansLstdForProcmnt.label","机关采购�??�?�"},
		{"eMO.PatientCheckedInAt.label","病人检查"},
		{"eMO.PatientDonorCardInfo.label","患者�??助者的�??助�?�资料"},
		{"eMO.PatientIDRegNoName.label","病人编�?�/ 登记�?�/�??称"},
		{"eMO.PerformedBy.label","由"},
//		{"eMO.PMCompletedAt.label","PM Completed At"},
//		{"eMO.PMRequestedBy.label","PM Requested By"},
//		{"eMO.PMStartedAt.label","PM Started At"},
//		{"eMO.PMYN.label","PM Y/N"},
//		{"eMO.Police61Recvd.label","Police 61 Received"},
//		{"eMO.Police61RecvdBy.label","Police 61 Received By"},
//		{"eMO.Police61RecvdDt.label","Police 61 Received Date"},
		{"eMO.PoliceDetails.label","警方详细"},
		{"eMO.PoliceID.label","警察编�?�"},
		{"eMO.PoliceOfficer.label","警务人员"},
		{"eMO.PoliceRank.label","警方排�??"},
		{"eMO.PoliceStation.label","警署"},
		{"eMO.PostMortem.label","验尸"},
		{"eMO.PostMortemStartAt.label","验尸开始"},
		{"eMO.PurposeForPrfmgPostMrtm.label","执行验尸目的"},
		{"eMO.PostMortemNo.label","验尸报告数�?"},
		{"eMO.PostmortemArea.label","死亡区域"},
		{"eMO.PostmortemCertifiedBy.label","死亡�?明"},
		{"eMO.PostmortemDtls.label","死亡详情"},
		{"eMO.PostmortemPrfmdBy.label","死�?��?作"},
		{"eMO.PostmortemStatus.label","死�?�状�?"},
		{"eMO.PostmortemType.label","死�?�类型"},
		{"eMO.PrefixSuffix.label","�?缀 �?�缀"},
		{"eMO.PresentDrngPostmrtm.label","死�?�"},
		{"eMO.ProcedureDuration.label","程�?期�?"},
		{"eMO.ProcurementTime.label","采购时间"},
		{"eMO.ReassignArea.label","调动区"},
		{"eMO.Receipt.label","收�?�"},
		{"eMO.ReceiptDateTime.label","收到日期/时间"},
		{"eMO.RecordPostmortem.label","记录死�?�"},
		{"eMO.RegNo.label","登记�?��?"},
		{"eMO.RegisteredCases.label","登记案件"},
		{"eMO.RegistrationDtls.label","登记详情"},
		{"eMO.RegnNo.label","？？�?��?"},
		{"eMO.RelnWithDeceased.label","与死者关系"},
		{"eMO.ReleaseArea.label","�?�布区"},
		{"eMO.ReleaseDateTime.label","�?�行日期/时间"},
		{"eMO.ReleaseDeceased.label","�?�布死亡"},
		{"eMO.ReleaseDeceasedBodyPart.label","�?�行死者/器官"},
		{"eMO.ReleaseLocation.label","�?�布�?置"},
		{"eMO.ReleaseStatus.label","�?�布状�?"},
		{"eMO.Released.label","�?�布"},
		{"eMO.ReleasedYN.label","�?�布（是/�?�）"},
		{"eMO.ReleasedBy.label","�?�布"},
		{"eMO.ReligiousOrgn.label","宗教组织"},
		{"eMO.SpecimenDescription.label","标本�??述"},
		{"eMO.SpecimenHandedDateTime.label","标本移交日期/时间"},
		{"eMO.SpecimenHandedOverTo.label","标本移交给"},
		{"eMO.StartPostmortem.label","死�?�开始"},
		{"eMO.StartingAutopsyNo.label","开始尸检�?�"},
		{"eMO.StorageArea.label","存储区域"},
		{"eMO.SmryOfFdgs.label","调查结果摘�?"},
		{"eMO.SpecimenHandedOverDate.label","标本移交日期"},
		{"eMO.TissueProcured.label","组织采购"},
		{"eMO.TissueProcurement.label","组织采购"},
		{"eMO.TissueProcuredPrfmdBy.label","组织采购由"},
		{"eMO.TissueProcuredPrfmdDt.label","组织采购执行日期"},
		{"eMO.TissueProcmntRegn.label","组织采购登记"},
		{"eMO.TypeOfPostmortem.label","死�?�类型"},
		{"eMO.UnclaimedBody.label","无人认领的尸体"},
		{"eMO.UnclaimedBodyPart.label","无人认领的尸体器官"},
		{"eMO.UnderTaker.label","根�?�接�?�者"},
		{"eMO.UnidentifiedBodyPart.label","�?明身份器官"},
		{"eMO.VehicleNumber.label","车辆数"},
		{"eMO.ViewMovementHistory.label","检视�?动�?�"},
		{"eMO.WaitTimeDuration.label","等待时间"},
		{"eMO.WelfareAssociations.label","�?利�??会"},
		{"eMO.ConsentTitle.label","�?��?标题"},
		{"eMO.ViewDeceasedDtls.label","查看死者的细节"},
		{"eMO.DeceasedPatients.label","死亡患者"},
		{"eMO.OrganCode.label","器官代�?"},
		{"eMO.OrganDescription.label","器官�??述"},
		{"eMO.BurialPermitNo.label","�?�?许埋葬"},
		{"eMO.Unregistered.label","未登记"},
		{"eMO.CopyDetails.label","�?制详情"},
//		{"eMO.ObtainedFrom.label","Obtained From"},
		{"eMO.ConsentOrgnDtn.label","�?��?器官�??赠"},
		{"eMO.ConsentClnicPstMrm.label","�?��?临床验尸"},
		{"eMO.ManageDeceasedPatients.label","死者病人管�?�"},
		{"eMO.PostmortemRequest.label","死�?�请求"},
//		{"eMO.StartPM.label","Start PM"},
//		{"eMO.EndPM.label","End PM"},
		{"eMO.ExportationDocument.label","出�?�文件"},
		{"eMO.UnAssignLocation.label","�?�消指定�?置"},
		{"eMO.NormalDeath.label","正常死亡"},
		{"eMO.PoliceCase.label","警方病例"},
		{"eMO.DeceasedName.label","死者姓�??"},
		{"eMO.BIDcase.label","B.I.D案例"},
		{"eMO.Biohazard.label","生化�?�机"},
		{"eMO.FreezerNo.label","冰冻�?�"},
		{"eMO.FreezerDesc.label","冰冻�??述"},
//newly added legends on 21/01/09
		{"eMO.BodyDisToMortuary.label","器官已被�?往太平间"},
		{"eMO.BodyFoundAt.label","器官�?置"},
		{"eMO.BodyIdentifiedBy.label","器官标签"},
		{"eMO.EndPM.label","验尸结�?�"},
		{"eMO.ObtainedFrom.label","获得"},
		{"eMO.PMCompletedAt.label","验尸结�?�时间"},
		{"eMO.PMRequestedBy.label","请求验尸者"},
		{"eMO.PMStartedAt.label","验尸开始时间"},
		{"eMO.PMYN.label","验尸 是/�?�"},
		{"eMO.Police61Recvd.label","收到者"},
		{"eMO.Police61RecvdBy.label","签署收到"},
		{"eMO.Police61RecvdDt.label","收到日期"},
		{"eMO.StartPM.label","开始验尸"},


	};
}
