/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMO.resources;

import java.util.*;

public class  Labels_th  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {

			{"eMO.Diseasedeath.label","th_Disease directly leading to death"},
			{"eMO.OtherSignificantCond.label","th_Other Significant Condition"},
			{"eMO.AmputatedBodyPart.label","th_Amputated Body Part"},
			{"eMO.AntecedentCause.label","th_Antecedent Cause"},
			{"eMO.ApprovedDateFrom.label","th_Approved Date From"},
			{"eMO.ApprovedDateTo.label","th_Approved Date To"},
			{"eMO.AreaDesc.label","th_Area Desc"},
			{"eMO.AreaType.label","th_Area Type"},
			{"eMO.AssignedDate.label","th_Assigned Date"},
			{"eMO.AutopsyNoDetailsRequired.label","th_Autopsy Number Associate Details Required"},
			{"eMO.AutopsyNoFormat.label","th_Autopsy Number Format"},
			{"eMO.BodyConditionType.label","th_Body Condition Type"},
			{"eMO.BayTableAvailChart.label","th_Bay/Table Availability Chart"},
			{"eMO.BayTableNo.label","th_Bay/Table No"},
			{"eMO.BayNo.label","th_Bay No"},
			{"eMO.Body.label","th_Body"},
			{"eMO.BodyCondition.label","th_Body Condition"},
			{"eMO.BodyConditionCode.label","th_Body Condition Code"},
			{"eMO.BodyConditionDesc.label","th_Body Condition Desc"},
			{"eMO.BodyDisToMortuary.label","th_Body Dispatch To Mortuary"},
			{"eMO.BodyFoundAt.label","th_Body Found At"},
			{"eMO.BodyIdentifiedBy.label","th_Body Identified By"},
			{"eMO.BodyMovement.label","th_Body Movement"},
			{"eMO.BodyPartCode.label","th_Body Part Code"},
			{"eMO.BodyPartDesc.label","th_Body Part Desc"},
			{"eMO.BodyPartReceiptDateTime.label","th_Body Part Receipt Date Time"},
			{"eMO.BodyPartType.label","th_Body Part Type"},
			{"eMO.BodyReceipt.label","th_Body Receipt Date/Time"},
			{"eMO.BodyRelDateTimefromSource.label","th_Body Release Date/Time from Source"},
			{"eMO.BroughtByPolice.label","th_Brought by Police"},
			{"eMO.BurialPermit.label","th_Burial Permit"},
			{"eMO.BurialPermitApprovalDate.label","th_Burial Permit Approval Date"},
			{"eMO.BurialPermitApprovedBy.label","th_Burial Permit Approved By"},
			{"eMO.BurialPermitApprovedByName.label","th_Burial Permit Approved By Name"},
			{"eMO.BurialPermitNumber.label","th_Burial Permit Number"},
			{"eMO.BurialPermitIssueDateTime.label","th_Burial Permit Issue Date/Time"},
			{"eMO.BurialPermitIssued.label","th_Burial Permit Issued"},
			{"eMO.Capacity.label","th_Capacity"},
			{"eMO.Claimant.label","th_Claimant"},			
			{"eMO.ClaimantAccompany.label","th_Claimant Accompanying"},
			{"eMO.ClaimantCode.label","th_Claimant Code"},
			{"eMO.ClaimantDesc.label","th_Claimant Description"},
			{"eMO.ClaimantType.label","th_Claimant Type"},
			{"eMO.ClaimantTypeRelat.label","th_Claimant Type/ Relationship"},
			{"eMO.Clinical.label","th_Clinical"},
			{"eMO.ClinicalPostmortem.label","th_Clinical Postmortem"},
			{"eMO.CollectionTime.label","th_Collection Time"},
			{"eMO.ConsentFormReceivDate.label","th_Consent  Form  Received Date/Time"},
			{"eMO.ConsentCode.label","th_Consent Code"},
			{"eMO.ConsentCode.label","th_Consent Code"},
			{"eMO.ConsentDesc.label","th_Consent Description"},
			{"eMO.ConsentFormReceivedBy.label","th_Consent Form Received by"},
			{"eMO.ConsentFormType.label","th_Consent Form Type"},
			{"eMO.ConsentGivenBy.label","th_Consent Given By"},
			{"eMO.CutoffperiodPatientsfromMPI.label","th_Cut-off period to look for deceased Patients from MPI"},
			{"eMO.DateTimeOfClaiming.label","th_Date Time Of Claiming"},
			{"eMO.DeadFetus.label","th_Dead Fetus"},
			{"eMO.DeceasedMortuaryRegNoFormat.label","th_Deceased Mortuary Registration Number Format"},
			{"eMO.DeceasedPatientDetls.label","th_Deceased Patient Details"},
			{"eMO.DeceasedPatientID.label","th_Deceased Patient ID"},
			{"eMO.DeceasedPatientName.label","th_Deceased Patient Name"},
			{"eMO.DeceasedReg.label","th_Deceased Registration"},
			{"eMO.DetlsofSpeciCollected.label","th_Details of Specimens Collected"},
			{"eMO.DonorCardAvlbl.label","th_Donor Card Available"},
			{"eMO.DonorCardInfo.label","th_Donor Card Info"},
			{"eMO.DonorCardNo.label","th_Donor Card No"},			
			{"eMO.EmbassyCertificateNo.label","th_Embassy Certificate No"},
			{"eMO.EmbassyCountry.label","th_Embassy of a Country"},
			{"eMO.EndAutopsyNo.label","th_End Autopsy Number"},
			{"eMO.EndPostmortem.label","th_End Postmortem"},
			{"eMO.ExportDeceasedBodyPart.label","th_Export Deceased/Body Part"},
			{"eMO.ExportationAddress.label","th_Exportation Address"},
			{"eMO.ExportationRequired.label","th_Exportation Required"},
			{"eMO.Finding.label","th_Finding"},
			{"eMO.GenerateBurialPermit.label","th_Generate Burial Permit"},
			{"eMO.GenerateBurialPermitNo.label","th_Generate Burial Permit Number"},
			{"eMO.HealthOfficer.label","th_Health Officer"},
			{"eMO.HealthOfficerRemarks.label","th_Health Officer Remarks"},
			{"eMO.HighRiskBodyPart.label","th_High Risk Body Part"},
			{"eMO.IdentificationMarks.label","th_Identification Marks"},
			{"eMO.InternalReport.label","th_Internal Report"},
			{"eMO.ListoforganforDonation.label","th_List of organ for Donation"},
			{"eMO.LocationAvailability.label","th_Location Availability"},
			{"eMO.LocationforArea.label","th_Location for Area"},
			{"eMO.LocationStatus.label","th_Location Status"},
			{"eMO.MannerofDeath.label","th_Manner of Death"},
			{"eMO.MannerOfDeathCode.label","th_Manner Of Death Code"},
			{"eMO.MannerOfDeathDesc.label","th_Manner Of Death Desc"},
			{"eMO.MannerOfDeathType.label","th_Manner Of Death Type"},
			{"eMO.MedicoLegal.label","th_Medico Legal"},			
			{"eMO.MedicolegalPostmortem.label","th_Medicolegal Postmortem"},
			{"eMO.MobilePhoneNo.label","th_Mobile Phone No"},
			{"eMO.Morethan.label","th_More than"},
			{"eMO.MortuaryNextRegNo.label","th_Mortuary Next Registration  Number"},
			{"eMO.MortuaryRegEndNo.label","th_Mortuary Registration End  Number"},
			{"eMO.MortuaryRegNoRequired.label","th_Mortuary Registration Number Associate Details Required"},
			{"eMO.MortuaryRegStartNo.label","th_Mortuary Registration Start Number"},
			{"eMO.NextAutopsyNo.label","th_Next Autopsy Number"},
			{"eMO.NextBurialPermitNo.label","th_Next Burial Permit No"},
			{"eMO.NotReleased.label","th_Not Released"},
			{"eMO.NotRequested.label","th_Not Requested"},
			{"eMO.NoOfDaysToPrsrvUnkwnBody.label","th_Number of days to preserve unknown body"},
			{"eMO.OrganDonation.label","th_Organ Donation"},
			{"eMO.OrganforDonation.label","th_Organ for Donation"},
			{"eMO.OrgansForDonationCode.label","th_Organs For Donation Code"},
			{"eMO.OrgansForDonationDesc.label","th_Organs For Donation Desc"},
			{"eMO.OrgansLstdForProcmnt.label","th_Organs Listed for Procurement"},
			{"eMO.PatientCheckedInAt.label","th_Patient Checked in At"},
			{"eMO.PatientDonarCardInfo.label","th_Patient Donar Card Information"},
			{"eMO.PatientIDRegNoName.label","th_Patient ID/Reg No/Name"},
			{"eMO.PerformedBy.label","th_Performed By"},
			{"eMO.PMCompletedAt.label","th_PM Completed At"},
			{"eMO.PMRequestedBy.label","th_PM Requested  By"},
			{"eMO.PMStartedAt.label","th_PM Started At"},
			{"eMO.PMYN.label","th_PM Y/N"},
			{"eMO.Police61Recvd.label","th_Police 61 Received"},
			{"eMO.Police61RecvdBy.label","th_Police 61 Received By"},
			{"eMO.Police61RecvdDt.label","th_Police 61 Received Date"},
			{"eMO.PoliceDetails.label","th_Police Details"},
			{"eMO.PoliceID.label","th_Police ID"},
			{"eMO.PoliceOfficer.label","th_Police Officer"},
			{"eMO.PoliceRank.label","th_Police Rank"},
			{"eMO.PoliceStation.label","th_Police Station"},
			{"eMO.PostMortem.label","th_Post Mortem"},
			{"eMO.PostMortemStartAt.label","th_Postmortem Start At"},
			{"eMO.PurposeForPrfmgPostMrtm.label","th_Purpose for performing Postmortem"},
			{"eMO.PostMortemNo.label","th_Post Mortem Number"},
			{"eMO.PostmortemArea.label","th_Postmortem Area"},
			{"eMO.PostmortemCertifiedBy.label","th_Postmortem Certified By"},
			{"eMO.PostmortemDtls.label","th_Postmortem Details"},
			{"eMO.PostmortemPrfmdBy.label","th_Postmortem Performed By"},
			{"eMO.PostmortemStatus.label","th_Postmortem Status"},
			{"eMO.PostmortemType.label","th_Postmortem Type"},
			{"eMO.PrefixSuffix.label","th_Prefix Suffix"},
			{"eMO.PresentDrngPostmrtm.label","th_Present During Postmortem"},
			{"eMO.ProcedureDuration.label","th_Procedure Duration"},
			{"eMO.ProcurementTime.label","th_Procurement Time"},
			{"eMO.ReassignArea.label","th_Reassign Area"},
			{"eMO.Receipt.label","th_Receipt"},
			{"eMO.ReceiptDateTime.label","th_Receipt Date/Time"},
			{"eMO.RecordPostmortem.label","th_Record Postmortem"},
			{"eMO.RegNo.label","th_Reg No"},
			{"eMO.RegisteredCases.label","th_Registered Cases"},
			{"eMO.RegistrationDtls.label","th_Registration Details"},
			{"eMO.RegnNo.label","th_Regn No"},
			{"eMO.RelnWithDeceased.label","th_Relationship with deceased"},
			{"eMO.ReleaseArea.label","th_Release Area"},
			{"eMO.ReleaseDateTime.label","th_Release Date/Time"},
			{"eMO.ReleaseDeceased.label","th_Release Deceased"},
			{"eMO.ReleaseDeceasedBodyPart.label","th_Release Deceased/Body Part"},
			{"eMO.ReleaseLocation.label","th_Release Location"},
			{"eMO.ReleaseStatus.label","th_Release Status"},
			{"eMO.Released.label","th_Released"},
			{"eMO.ReleasedBy.label","th_Released By"},
			{"eMO.ReleasedYN.label","th_Released(Y/N)"},
			{"eMO.ReligiousOrgn.label","th_Religious Organizations"},
			{"eMO.SpecimenDescription.label","th_Specimen Description"},
			{"eMO.SpecimenHandedDateTime.label","th_Specimen Handed Date/Time"},
			{"eMO.SpecimenHandedOverTo.label","th_Specimen Handed over to"},
			{"eMO.StartPostmortem.label","th_Start Postmortem"},
			{"eMO.StartingAutopsyNo.label","th_Starting Autopsy Number"},
			{"eMO.StorageArea.label","th_Storage Area"},
			{"eMO.SmryOfFdgs.label","th_Summary of Findings"},
			{"eMO.SpecimenHandedOverDate.label","th_Specimen Handed Over Date"},
			{"eMO.TissueProcured.label","th_Tissue Procured"},
			{"eMO.TissueProcurement.label","th_Tissue Procurement"},
			{"eMO.TissueProcuredPrfmdBy.label","th_Tissue procurement performed by"},
			{"eMO.TissueProcuredPrfmdDt.label","th_Tissue procurement performed date"},
			{"eMO.TissueProcmntRegn.label","th_Tissue Procurement Registration"},
			{"eMO.TypeOfPostmortem.label","th_Type of Postmortem"},
			{"eMO.UnclaimedBody.label","th_Unclaimed Body"},
			{"eMO.UnclaimedBodyPart.label","th_Unclaimed Body Part"},
			{"eMO.UnderTaker.label","th_Under Taker"},
			{"eMO.UnidentifiedBodyPart.label","th_Unidentified Body Part"},
			{"eMO.VehicleNumber.label","th_Vehicle Number"},
			{"eMO.ViewMovementHistory.label","th_View Movement History"},
			{"eMO.WaitTimeDuration.label","th_Wait Time Duration"},
			{"eMO.WelfareAssociations.label","th_Welfare Associations"},
			{"eMO.ConsentTitle.label","th_Consent Title"},
			{"eMO.ViewDeceasedDtls.label","th_View Deceased Details"}, 
			{"eMO.DeceasedPatients.label","th_Deceased Patients"}, 
			{"eMO.OrganCode.label","th_Organ Code"}, 
			{"eMO.OrganDescription.label","th_Organ Description"}, 
			{"eMO.BurialPermitNo.label","th_Burial Permit No"}, 
			{"eMO.Unregistered.label","th_Unregistered"},
			{"eMO.CopyDetails.label","th_Copy Details"},
			{"eMO.ObtainedFrom.label","th_Obtained From"},
			{"eMO.ConsentOrgnDtn.label","th_Consent For Organ Donation"},
			{"eMO.ConsentClnicPstMrm.label","th_Consent For Clinical Post Mortem"},
			{"eMO.ManageDeceasedPatients.label","th_Manage Deceased Patients"},
			{"eMO.PostmortemRequest.label","th_Postmortem Request"},
			{"eMO.StartPM.label","th_Start PM"},
			{"eMO.EndPM.label","th_End PM"},
			{"eMO.ExportationDocument.label","th_Exportation Document"},
			{"eMO.UnAssignLocation.label","th_UnAssign Location"},
			{"eMO.NormalDeath.label","th_Normal Death"},
			{"eMO.PoliceCase.label","th_Police Case"},
			{"eMO.DeceasedName.label","th_Deceased Name"},
			{"eMO.BIDcase.label","th_B.I.D Case"},
			{"eMO.Biohazard.label","th_Biohazard"},
			{"eMO.FreezerNo.label","th_Freezer No"},
			{"eMO.FreezerDesc.label","th_Freezer Desc"}

				
	};
}
