/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eST.resources;

import java.util.*;

public class Labels_th extends ListResourceBundle implements java.io.Serializable
{
	public Object[][] getContents() 
	{
         return contents;
    }

	static final Object[][] contents = 
	{
		{"eST.A.label","เอ"},
		{"eST.ABCAnalysis.label","วิเคราะห์เอบีซี"},
		{"eST.ABCAnalysisReport.label","รายงานวิเคราะห์เอบีซี"},
		{"eST.ABCCategory.label","�?ย�?ประเภทเอบีซี"},
		{"eST.ABCCriteria.label","เ�?ณฑ์เอบีซี"},
		{"eST.ABCCutoffRange.label","ตัดช่วงเอบีซี"},
		{"eST.ActualBalanceQty.label","ปริมาณสมดุลที่เป็นจริง"},
		{"eST.ActualQuantity.label","ปริมาณที่เป็นจริง"},
		{"eST.AddItems.label","เพิ่มราย�?าร"},
		{"eST.AdjDocDate.label","วันที่ปรับเอ�?สาร"},
		{"eST.AdjDocRef.label","อ้างอิงเอ�?สารที่ปรับ"},
		{"eST.AdjDocStartNo.label","เลขเริ่มของเอ�?สารที่ปรับ"},
		{"eST.AdjDocType.label","ชนิดของเอ�?สารที่ปรับ"},
		{"eST.AdjRemarks.label","หมายเหตุ�?ารปรับ"},
		{"eST.Adjustments.label","�?ารปรับ"},
		{"eST.AgeSlots.label","ช่องอายุ"},
		{"eST.AgeingSlots.label","ช่องอายุ"},
		{"eST.AlertPickSlipPrint.label","พิมพ์เตือนPickslip"},
		{"eST.AllItems.label","ราย�?ารทั้งหมด"},
		{"eST.AllStores.label","ห้องยาทั้งหมด"},
		{"eST.AllowMultiStoreIssue.label","อนุ�?าตให้ห้องยา หลายๆที่จ่าย"},
		{"eST.Analysis.label","�?ารวิเคราะห์"},
		{"eST.Annual.label","รายปี"},		
		{"eST.ApplicabletoPharmacy.label","ซึ่งเหมาะสม�?ับ�?ารใช้ �?ับPharmacy"},
		{"eST.AssociatedRTV.label","RTVที่เ�?ี่ยวข้อง�?ับ "},
		{"eST.AssociatedRTVsforReplacement.label","RTVที่เ�?ี่ยวข้อง�?ับ�?ารปลี่ยนคืน "},
		{"eST.AuditInformationfor.label","ตรวจสอบข้อมูลเพื่อ"},		
		{"eST.AuthorizeAtIssueStoreRemarks.label","อนุมัติที่"},
		{"eST.AuthatReqByStore.label","�?ารอนุมัติที่ร้องขอโดยห้องยา"},
		{"eST.AuthorizeQuantity.label","ปริมาณที่อนุมัติ"},
		{"eST.AuthorizeSpecialRequest.label","�?ารร้องขอพิเศษที่ต้องได้รับอนุมัติ"},
		{"eST.AuthorizedatIssueStore.label","ถู�?อนุมัติที่ห้องยาที่จ่าย"},
		{"eST.AuthorizedatRequestbyStore.label","ถู�?อนุมัติที่ร้องขอโดยห้องยา"},
		{"eST.AvailableQty.label","ปริมาณที่ใช้ได้"},
		{"eST.AvailableStock.label"," Stockที่ใช้ได้"},
		{"eST.Averagecostwillbechangedfrom.label","ราคาเฉลี่ยจะถู�?เปลี่ยนจา�?"},
		{"eST.AvlQtyatIssueStore.label","ปริมาณที่ใช้ได้ที่ห้องจ่ายยา"},
		{"eST.AvlQtyinIssStore.label","ปริมาณที่ใช้ได้ใน ห้องจ่ายยา"},
		{"eST.AvlQtyinReqStore.label","ปริมาณที่ใช้ได้ใน Req Store"},
		{"eST.B.label","บี"},		
		{"eST.BaseQuantity.label","ปริมาณพื้น�?าน"},		
		{"eST.BatchExpiresNext.label","Batchหมดอายุครั้งต่อไป"},
		{"eST.BatchSearch.label","ค้นหาBatch"},
		{"eST.BatchSelection.label","�?ารเลือ�?Batch"},
		{"eST.BatchSeries.label","ลำดับBatch"},
		{"eST.BatchStatusHistory.label","ประวัติสถานะBatch"},
		{"eST.BelowMinimumStockLevel.label","ระดับต่ำ�?ว่าMinimum Stock"},
		{"eST.BelowRe-OrderLevel.label","ระดับต่ำ�?ว่า�?ารสั่ง�?ารรั�?ษาซ้ำ"},
		{"eST.BillingConfirmationAlert.label","�?จ้งเตือนให้รับรองใบ�?จ้งหนี้"},
		{"eST.BinLocationRange.label","ชั้นช่องเ�?็บยา"},
		{"eST.Bonus.label","โบนัส"},
		{"eST.BonusQuantity.label","ปริมาณโบนัส"},
		{"eST.BufferPercentage.label","เปอร์เซ็นต์ปริมาณสำรอง"},
		{"eST.ByBinLocation.label","โดยช่องเ�?็บยา"},
		{"eST.ByDate.label","โดยวันที่"}, //extra
		{"eST.ByDocumentDate.label","โดยวันที่ของเอ�?สาร"},
		{"eST.ByFromStore.label","โดยจา�?ห้องยา"},
		{"eST.ByIssuingStore.label","โดยIssuing  Store"},
		{"eST.ByItem.label","โดยราย�?าร"},
		{"eST.ByItemCode.label","โดยรหัสราย�?าร"},
		{"eST.ByReceivingStore.label","โดยห้องยา ที่รับรอง"},
		{"eST.ByShortDescription.label","โดยคำอธิบายย่อๆ"},
		{"eST.ByStore.label","โดยห้องยา"},
		{"eST.BySupplier.label","โดยผู้ซื้อ"},
		{"eST.ByToStore.label","โดยห้องยา"},
		{"eST.C.label","ซี"},		
		{"eST.ChangeBin.label","เปลี่ยนBin"},		
		{"eST.ChildItem.label","ราย�?ารเล็�?ๆ"},
		{"eST.CloseUponIssue.label","ปิดขึ้นอยู่�?ับเรื่อง"},
		{"eST.Closed/Cancelled.label","ปิด/ย�?เลิ�?"},
		{"eST.ClosingBalance.label","�?ารปิดสมดุล"},
		{"eST.CommittedQty.label","ปริมาณที่ทำสั�?�?า"},		
		{"eST.Compositionfor.label","ส่วนประ�?อบสำหรับ"},
		{"eST.CompositionforQty.label","ส่วนประ�?อบสำหรับปริมาณ"},
		{"eST.ComputedDetails.label","รายละเอียด�?ารคำนวณ"},		
		{"eST.ConfirmPrinting.label","ยืนยัน�?ารพิมพ์"},
		{"eST.ConsiderIteminTargetStore.label","พิจารณาราย�?ารในTargetStore"},
		{"eST.ConsiderReprintasOriginal.label","พิจารณา�?ารพิมพ์ซ้ำ"},
		{"eST.ConsiderStockpositionforReorder.label","พิจารณาตำ�?หน่งstock สำหรับ"},
		{"eST.Consignment.label","�?ารส่งมอบ"},
		{"eST.ConsignmentItemsOnly.label","ราย�?าร�?ารส่งมอบเท่านั้น"},
		{"eST.Consumption.label","�?ารบริโภค"},
		{"eST.ConsumptionCost.label","ต้นทุน�?ารใช้"},
		{"eST.ConsumptionCriteria.label","เ�?ณฑ์�?ารใช้"},
		{"eST.ConsumptionPeriod.label","รอบ�?ารใช้"},
		{"eST.ConsumptionQty.label","ปริมาณที่ใช้ไป"},
		{"eST.Contract.label","สั�?�?า"},
		{"eST.ConvFactor.label","องค์ประ�?อบความสะดว�?"},		
		{"eST.Currency.label","ประจำวัน"},
		{"eST.CurrentInventory.label","คลังยาปัจจุบัน"},
		{"eST.CurrentPackSize.label","ขนาดบรรจุภัณฑ์ปัจจุบัน"},		
		{"eST.CurrentSpecificInventory.label","คลังยาเฉพาะปัจจุบัน"},		
		{"eST.DefaultStockParameter.label","พารามีเตอร์สต๊อ�?ป�?ติที่ตั้งมาจา�?โรงงาน"},		
		{"eST.DocDateFrom.label","เอ�?สารเริ่มวันที่"},		
		{"eST.DocSrlNo.label","เลขลำดับเอ�?สาร"},		
		{"eST.DocType/No.label","เลข/ชนิดเอ�?สาร"},		
		{"eST.DocumentsforAuthorize.label","เอ�?สารเพื่อ�?ารอนุมัติ"},		
		{"eST.Edit/View.label","�?�?้ไข/�?สดง"},		
		{"eST.ExcludeExternalStores.label","ไม่นับคลังยานอ�?"},
		{"eST.Excludeitemsreceivedwithin.label","ไม่นับราย�?ารรับภายใน"},
		{"eST.ExpectedBalanceQuantity.label","ปริมาณสมดุลที่คาดไว้"},
		{"eST.ExpectedQuantity.label","ปริมาณที่คาดไว้"},		
		{"eST.Expired&NotifiedBatch.label","ชุดที่�?จ้งไว้�?ละหมดอายุ"},
		{"eST.ExpiredBatch.label","ชุดที่หมดอายุ"},
		{"eST.Expired/Notified.label","หมดอายุ/�?จ้งไว้"},
		{"eST.Expired/Suspend.label","หมดอายุ/งดไว้"},
		{"eST.Expiringin.label","�?ำลังหมอายุใน"},
		{"eST.Expiring/expiredBatches.label","ชุดที่หมดอายุ/�?ำลังหมดอายุ"},		
		{"eST.ExpiryAnalysisReport.label","รายงานวิเคราะห์�?ารหมดอายุ"},
		{"eST.ExpiryCutoffDays.label","วันที่ตัดหมดอายุ"},
		{"eST.ExpiryFlag.label","สั�?�?าณว่าหมดอายุ"},
		{"eST.ExpiryItems.label","ราย�?ารที่หมดอายุ"},
		{"eST.ExpirySelection.label","�?ารเลือ�?หมดอายุ"},
		{"eST.ExpiryWarningDays.label","วันที่เตือนหมดอายุ"},
		{"eST.Expiry/ReceiptDate.label","วันที่ใบรับ/หมดอายุ"},
		{"eST.Extemporaneous.label","เฉพาะหน้า"},
		{"eST.ExternalItem.label","ราย�?ารภายนอ�?"},
		{"eST.ExternalStores.label","ห้องยานอ�?"},		
		{"eST.FacilityWiseYearlySummaryReport.label","รายงานสรุปรายปี�?ต่ละสถานบริ�?าร"},
		{"eST.Factor.label","ปัจจัย"},
		{"eST.Fast/Slow/NoMovementReport.label","รายงาน�?ารเคลื่อนไหวเร็ว/ช้า/ไม่เคลื่อน"},		
		{"eST.ForA.label","สำหรับเอ"},
		{"eST.ForB.label","สำหรับบี"},
		{"eST.ForC.label","สำหรับซี"},
		{"eST.FractionalUOM.label","หน่วยวัดย่อย"},		
		{"eST.FromBinLocation.label","จา�?ช่องเ�?็บยา"},
		{"eST.FromDocDate.label","จา�?วันที่ในเอ�?สาร"},
		{"eST.FromItem.label","จา�?ราย�?าร"},		
		{"eST.GenerateBatch.label","ชุดที่ผลิต"},
		{"eST.GoodsReceipt.label","ใบรับสินค้า"},
		{"eST.GoodsReceiptFinalize.label","สรุปใบรับสินค้า"},
		{"eST.GraceDaysforHomeCare.label","ระยะเวลาผ่อนผันสำหรับ�?ารดู�?ลที่บ้าน"},
		{"eST.GRN.label","ใบรับของ"},
		{"eST.GRNBatchSearch.label","สืบค้นชุดใบรับของ"},
		{"eST.GRNDetailsfor.label","รายละเอียดใบรับของสำหรับ"},
		{"eST.GRNDetailsForReplacement.label","รายละเอียดใบรับของสำหรับ�?ารทด�?ทน"},
		{"eST.GRNDocType.label","ชนิดเอ�?สารใบรับของ"},
		{"eST.GRNDocType/No.label","ชนิด/เลขเอ�?สารใบรับของ"},
		{"eST.GRNHistory.label","ประวัติใบรับของ"},
		{"eST.GRNHistoryRTVList.label","ราย�?าร  RTV ในประวัติใบรับของ"},
		{"eST.GRNPreviewDetails.label","รายละเอียด�?สดงใบรับของ"},
		{"eST.GRNQuantity.label","ปริมาณใบรับของ"},
		{"eST.GRNStatisticsReport.label","รายงานสถิติใบรับของ"},
		{"eST.GRNValue.label","ค่าใบรับของ"},
		{"eST.IncludeExpiredBatches.label","รวมชุดที่หมดอายุ"},
		{"eST.IncludeNotifiedBatches.label","รวมชุดที่�?จ้งไว้"},
		{"eST.IncludeStockIssues.label","รวมสต๊อ�?ที่ปล่อย"},
		{"eST.IncludeSuspendedBatches.label","รวมชุดที่งดไว้"},
		{"eST.IncludeZeroStockBatches.label","รวมชุดสต๊อ�?ที่หมด"},		
		{"eST.InsurancePolicyIsExpired Proceed.label","ออ�?นโยบาย�?ารดำเนิน�?ารหมดอายุ"},
		{"eST.InternalStores.label","ห้องยาใน"},		
		{"eST.IssueBatchSearch.label","�?ารสืบค้นชุดที่จ่ายออ�?"},
		{"eST.IssueIntegerQuantity.label","ปริมาณจำนวนเต็มที่จ่ายออ�?"},
		{"eST.IssuePreviewDetails.label","รายละเอียด�?สดง�?ารจ่ายออ�?"},		
		{"eST.IssueReturnFinalize.label","ท้ายสุด�?ารจ่ายคืน"},
		{"eST.IssueReturnPreviewDetails.label","รายละเอียด�?สดง�?ารจ่ายคืน"},
		{"eST.IssueReturns.label","จ่ายคืน"},
		{"eST.IssueSequence.label","ลำดับที่จ่ายออ�?"},		
		{"eST.IssueUOM.label","ชุดหน่วย�?ารวัด"},
		{"eST.IssueUOMQuantity.label","ชุดปริมาณหน่วย�?ารวัด"},
		{"eST.IssuesCost.label","ออ�?ค่าใช้จ่าย"},
		{"eST.IssuingStore.label","คลังจ่าย"},		
		{"eST.ItemDetails.label","รายละเอียดราย�?าร"},
		{"eST.ItemFrom.label","ราย�?ารจา�?"},		
		{"eST.ItemQuantity.label","ปริมาณราย�?าร"},
		{"eST.ItemSearch.label","สืบค้นราย�?าร"},
		{"eST.ItemSelection.label","เลือ�?ราย�?าร"},
		{"eST.ItemSpecifications.label","�?ารระบุราย�?าร"},
		{"eST.ItemSummaryReport.label","รายงานสรุปราย�?าร"},
		{"eST.ItemTo.label","ราย�?ารถึง"},
		{"eST.Itemtobeused.label","ราย�?ารที่ถู�?ใช้"},
		{"eST.ItemsMovementStatus.label","สถานะ�?ารเคลื่อนไหวราย�?าร"},
		{"eST.LabelRequired.label","ป้ายที่ต้อง�?าร"},		
		{"eST.LastDays.label","วันล่าสุด"},		
		{"eST.LeadDays.label","วัน�?่อนหน้า"},
		{"eST.lessthanminstock.label","น้อย�?ว่าสต๊อ�?ที่น้อยที่สุด"},
		{"eST.lessthanROL.label","น้อย�?ว่าระดับ�?ารสั่งใหม่"},
		{"eST.MachineCode.label","รหัสเครื่องจั�?ร"},		
		{"eST.ManufactureReceipts.label","ใบรับ�?ารผลิต"},		
		{"eST.ManufacturerItem.label","ราย�?ารผู้ผลิต"},
		{"eST.Manufacturing.label","�?ารผลิต"},
		{"eST.ManufacturingFormulary.label","สูตร�?ารผลิต"},
		{"eST.ManufacturingItem.label","ราย�?ารผลิต"},
		{"eST.ManufacturingItemLabel.label","ป้ายราย�?ารผลิต"},
		{"eST.ManufacturingItems.label","ราย�?ารผลิต"},
		{"eST.ManufacturingItemsFinalize.label","สรุปราย�?ารผลิต"},
		{"eST.ManufacturingReceipt.label","ใบรับ�?ารผลิต"},
		{"eST.ManufacturingRequestDetails.label","รายละเอียด�?ารขอ�?ารผลิต"},
		{"eST.MasterBinLocation.label","ช่องเ�?็บยาหลั�?"},
		{"eST.MaxAvailable.label","มา�?ที่สุดที่หาได้"},
		{"eST.MaxReturnableQuantity.label","ปริมาณที่สามารถคืนได้มา�?ที่สุด"},
		{"eST.MaxStock.label","สต๊อ�?มา�?ที่สุด"},
		{"eST.MaxStockLevel.label","ระดับสต๊อ�?มา�?ที่สุด"},
		{"eST.MaxStockQuantity.label","ปริมาณสต๊อ�?มา�?ที่สุด"},
		{"eST.MaximumLevel.label","ระดับที่มา�?ที่สุด"},		
		{"eST.MFG.label","วันที่ผลิต"},
		{"eST.MFGItem.label","ราย�?ารที่ผลิต"},
		{"eST.MFGReceipts.label","ใบรับ�?ารผลิต"},
		{"eST.MFGUOM.label","หน่วย�?ารผลิต"},
		{"eST.MFGWorkloadStatisticsReport.label","รายงานสถิติภาระ�?ารผลิต"},
		{"eST.MinSalesQuantity.label","ปริมาณ�?ารขายน้อยที่สุด"},
		{"eST.MinStock.label","สต๊อ�?ที่น้อยที่สุด"},
		{"eST.MinStockDays.label","สต๊อ�?ประจำวันที่น้อยที่สุด"},
		{"eST.MinStockLevel.label","ระดับสต๊อ�?ที่น้อยที่สุด"},		
		{"eST.MinimumLevel.label","ระดับที่น้อยที่สุด"},
		{"eST.ModelNo.label","เลขตัวอย่าง"},		
		{"eST.ModifyDocumentDetails.label","รายละเอียด�?าร�?�?้ไขเอ�?สาร"},		
		{"eST.MovedItemsOnly.label","ราย�?ารที่มี�?ารเคลื่อนย้ายเท่านั้น"},
		{"eST.MTDIssueQuantity.label","ปริมาณMTD ที่จ่ายออ�?"},
		{"eST.MTDReceiptsQuantity.label","ปริมาณใบรับ MTD"},
		{"eST.NoofCopies.label","จำนวนสำเนา"},
		{"eST.NoofLabels.label","จำนวนป้าย"},
		{"eST.NoofUnfinalised/GLUninterfacedTransactions.label","จำนวน�?ารดำเนิน�?ารที่ยังไม่สรุป/ไม่เชื่อมโยง GL"},
		{"eST.NonConsignment.label","ไม่ส่งมอบ"},
		{"eST.NonConsumption.label","ไม่บริโภค"},
		{"eST.NonInventoryGRN.label","ใบรับของที่ไม่ใช่คลังยา"},
		{"eST.NonManufacturing.label","ไม่ใช่�?ารผลิต"},
		{"eST.NonMedical.label","ไม่ใช่ทาง�?าร�?พทย์"},
		{"eST.NonMedicalItems.label","ราย�?ารที่ไม่ใช่ทาง�?าร�?พทย์"},
		{"eST.NonMovedItemsOnly.label","ราย�?ารที่ไม่มี�?ารเคลื่อนไหวเท่านั้น"},
		{"eST.NonPSItems.label","ราย�?ารที่ไม่ใช่ PS"},
		{"eST.NonReorderableStoresStock.label","สต๊อ�?ห้องยาที่ไม่สามารถสั่งใหม่"},
		{"eST.NonSoleSource.label","ไม่ใช่�?หล่งขาย"},
		{"eST.NonSterile.label","ไม่ปราศจา�?เชื้อ"},
		{"eST.NonStock.label","ไม่สต๊อ�?"},
		{"eST.NonStockIssues.label","ไม่ใช่ราย�?ารสต๊อ�?"},
		{"eST.NonStockReturns.label","ไม่คืนสต๊อ�?"},
		{"eST.NonContract.label","ไม่มีสั�?�?า"},
		{"eST.NonExpiryItems.label","ราย�?ารที่ไม่หมดอายุ"},
		{"eST.NonMedicalItem.label","ราย�?ารที่ไม่ใช่ทาง�?าร�?พทย์"},
		{"eST.NonStockStore.label","ห้องยาที่ไม่ใช่สต๊อ�?"},
		{"eST.NormalQty.label","ปริมาณป�?ติ"},
		{"eST.NormalRequest.label","ขอตามป�?ติ"},		
		{"eST.Notified.label","�?จ้งไว้"},
		{"eST.NotifiedBatch.label","ชุดที่�?จ้งไว้"},
		{"eST.ofMinStock.label","ของสต๊อ�?ที่น้อยที่สุด"},
		{"eST.OldDetails.label","รายละเอียดเ�?่า"},
		{"eST.OnlyA.label","เอเท่านั้น"},
		{"eST.OnlyB.label","บีเท่านั้น"},
		{"eST.OnlyC.label","ซีเท่านั้น"},		
		{"eST.OpeningStock.label","สต๊อ�?เปิด"},
		{"eST.OtherAttributes.label","ลั�?ษณะอื่น ๆ "},		
		{"eST.OtherStore.label","ห้องยาอื่น ๆ"},		
		{"eST.ParentStore.label","ห้องยาหลั�?"},
		{"eST.PartNumber.label","จำนวนบางส่วน"},		
		{"eST.PendingRequestQty.label","ปริมาณที่ขอจ่าย"},
		{"eST.PeriodFrom.label","รอบจา�?"},
		{"eST.PeriodFromDate.label","รอบจา�?วันที่"},
		{"eST.Perpetual.label","ตลอดไป"},
		{"eST.PharmacyStockItems.label","ราย�?ารสต๊อ�?เ�?ี่ยว�?ับยา"},
		{"eST.PhyCount.label","นับตามที่มีอยู่จริง"},
		{"eST.PhyCountPerYear.label","นับตามที่มีอยู่จริงต่อปี"},
		{"eST.PhyInvProcessMode.label","โหมด�?ระบวน�?ารคลังยาที่มีอยู่จริง"},
		{"eST.PhyInventory.label","คลังยาที่มีอยู่จริง"},
		{"eST.PhyInventoryID.label","เลขประจำคลังยาที่มีอยู่จริง"},
		{"eST.PhyInventoryType.label","ชนิดคลังยาที่มีอยู่จริง"},
		{"eST.PONo.label","หมายเลข PO "},
		{"eST.PrePacking.label","�?่อนบรรจุหีบห่อ"},
		{"eST.PreparationMode.label","โหมด�?ารเตรียม"},
		{"eST.PreparationType.label","ชนิด�?ารเตรียม"},
		{"eST.PresentCount.label","�?ารนับที่เป็นปัจจุบัน"},		
		{"eST.PrimaryStore.label","ห้องยาเดิม"},
		{"eST.Print/View.label","พิมพ์/�?สดง"},
		{"eST.PrintAlertRequired.label","พิมพ์ความต้อง�?ารที่เตือนไว้"},
		{"eST.PrintDocument.label","พิมพ์เอ�?สาร"},
		{"eST.PrintTechnicalSpecification.label","พิมพ์รายละเอียดทางเทคนิค"},		
		{"eST.ProcessExpiredBatch.label","ชุดดำเนิน�?ารที่หมดอายุ"},
		{"eST.ProcessLoss.label","สู�?เสีย�?ารดำเนิน�?าร"},
		{"eST.ProcessOption.label","ทางเลือ�?�?ระบวน�?าร"},
		{"eST.ProcessSuspendedBatch.label","Batch ที่ถู�?ระงับ�?ารจ่าย"},
		{"eST.ProductTransfer.label","โอนย้ายผลิตภัณฑ์"},
		{"eST.ProductTransferReqNo.label","เลขขอโอนย้ายผลิตภัณฑ์"},
		{"eST.ProductTransferRequestSearch.label","สืบค้น�?ารขอโอนย้ายผลิตภัณฑ์"},		
		{"eST.QuantityOnHand.label","ปริมาณที่มีอยู่"},
		{"eST.QuantityToTransfer.label","ปริมาณที่โอนย้าย"},		
		{"eST.QueryType.label","ชนิด�?ารถาม"},		
		{"eST.ReceivedQuantity.label","ปริมาณที่ได้รับ"},
		{"eST.Refundallowed.label","อนุ�?าตให้คืน"},
		{"eST.Reordarable.label","สั่งใหม่ได้"},
		{"eST.ReorderAttributes.label","ลั�?ษณะ�?ารสั่งใหม่"},
		{"eST.ReorderDays.label","�?ารสั่งใหม่ประจำวัน"},
		{"eST.ReorderFreqDays.label","ความถี่�?ารสั่งใหม่ประจำวัน"},
		{"eST.ReorderQuantity.label","ปริมาณ�?ารสั่งใหม่"},
		{"eST.Reorderable.label","สั่งใหม่ได้"},
		{"eST.ReorderableItems.label","ราย�?ารที่สั่งใหม่ได้"},
		{"eST.ReorderableStore.label","ห้องยาที่สามารถสั่งใหม่ได้"},
		{"eST.ReorderableStoresstock.label","ห้องยาที่สามารถสั่งใหม่ได้สต็อ�?"},
		{"eST.RepackGroup.label","�?ลุ่มที่บรรจุหีบห่อใหม่"},
		{"eST.RepackItem.label","ราย�?ารที่บรรจุหีบห่อใหม่"},
		{"eST.RepackSize.label","ขนาดของ�?ารบรรจุหีบห่อใหม่"},
		{"eST.RepackStore.label","ห้องยาบรรจุหีบห่อใหม่"},
		{"eST.RepackingLabel.label","ป้าย�?ารบรรจุหีบห่อใหม่"},
		{"eST.Replonexpiry.label","ทด�?ทน�?ารหมดอายุ"},
		{"eST.ReplRTVQuantity.label","ปริมาณ�?ารทด�?ทน RTV"},
		{"eST.ReplacementGRN.label","�?ารทด�?ทน GRN "},
		{"eST.ReplacementGRNBatchSearch.label","�?ารสืบค้นชุดของ GRN ที่ทด�?ทน"},
		{"eST.ReplacementGRNPreviewDetails.label","รายละเอียด�?สดง�?ารทด�?ทนของ GRN "},
		{"eST.ReplacementOnExpiry.label","ทด�?ทน�?ารหมดอายุ"},
		{"eST.ReplacementQty.label","ปริมาณที่ทด�?ทน"},
		{"eST.ReplacementRTV.label","ทด�?ทนRTV"},
		{"eST.ReplacementRTVDetailsForItem.label","รายละเอียดทด�?ทนRTVสำหรับราย�?าร"},		
		{"eST.ReplGRNQuantity.label","ปริมาณ�?ารทด�?ทน GRN"},
		{"eST.ReportExecutedBy.label","รายงานถู�?เขียนโดย"},
		{"eST.ReportMfgItemLabel.label","รายงานป้ายราย�?ารผลิต"},		
		{"eST.ReportRepackingLabel.label","รายงานป้าย�?ารบรรจุหีบห่อใหม่"},
		{"eST.ReportSuspendedReinstateBatches.label","รายงานชุด�?าร�?ลับคืนของที่งดไว้"},
		{"eST.ReqBy.label","ขอโดย"},		
		{"eST.ReqEntered.label","ลงชื่อเข้าขอ"},
		{"eST.ReqGenerationBase.label","�?าน�?ารผลิตที่ขอ"},
		{"eST.ReqIssue.label","ประเด็นที่ขอ"},
		{"eST.ReqItemDetailsfor.label","รายละเอียดราย�?ารขอสำหรับ"},
		{"eST.ReqNo.label","หมายเลขที่ขอ"},
		{"eST.ReqNoFrom.label","หมายเลขที่ขอเริ่มจา�?"},		
		{"eST.ReqQty.label","ปริมาณ�?ารขอ"},		
		{"eST.ReqStatisticsReport.label","รายงานสถิติ�?ารขอ"},
		{"eST.ReqStatus.label","สถานะ�?ารขอ"},
		{"eST.ReqStore.label","ห้องยาที่ขอ"},
		{"eST.ReqType.label","ชนิด�?ารขอ"},
		{"eST.ReqUOM.label","หน่วย�?ารเบิ�?"},
		{"eST.ReqUOMQty.label","ปริมาณหน่วย�?ารเบิ�?"},
		{"eST.RequestbyStore.label","ขอโดยห้องยา"},
		{"eST.RequestByStoreCode.label","ขอโดย�?ารใช้รหัสห้องยา"},
		{"eST.Requestsof.label","ขอเ�?ี่ยว�?ับ"},
		{"eST.RequiredItem.label","ราย�?ารที่ต้อง�?าร"},
		{"eST.RequiredQuantity.label","ปริมาณที่ต้อง�?าร"},
		{"eST.Requisition.label","�?ารเบิ�?"},
		{"eST.RequisitionAuthorize.label","อนุมัติ�?ารเบิ�?"},		
		{"eST.RequisitionIssues.label","จ่ายที่เบิ�?"},
		{"eST.RequisitionIssuesFinalize.label","สรุป�?ารจ่ายที่เบิ�?"},		
		{"eST.ResultCriteria.label","เ�?ณฑ์ผลลัพธ์"},
		{"eST.RetQty.label","ปริมาณ�?ารคืน"},		
		{"eST.ReturnPeriod.label","รอบ�?ารคืน"},		
		{"eST.ReturntoVendor.label","คืนให้�?ับผู้ขาย"},
		{"eST.ReturnVendor.label","ผู้ขายคืน"},
		{"eST.Returns.label","�?ารคืน"},
		{"eST.RevokeDate.label","วันที่เรีย�?�?ลับคืน"},
		{"eST.ROLevel.label","ระดับ�?ารสั่งใหม่"},
		{"eST.ROQuantity.label","ปริมาณ�?ารสั่งใหม่"},
		{"eST.RTVDetailsforReplacementGRN.label","รายละเอียด RTV สำหรับทด�?ทน GRN"},
		{"eST.RTVDocType/No.label","ชนิด/เลขเอ�?สาร  RTV"},
		{"eST.RTVforReplacement.label"," RTV เพื่อ�?ารทด�?ทน"},
		{"eST.RTVHistory.label","ประวัติ  RTV"},
		{"eST.RTVPreviewDetails.label","รายละเอียด�?สดง  RTV"},
		{"eST.RTVQuantity.label","ปริมาณ  RTV"},
		{"eST.RTVREF.label","อ้างอิง  RTV"},		
		{"eST.SaleTrnType.label","ชนิด Sale Trn "},
		{"eST.SaleUOM.label","หน่วยวัด�?ารขาย"},
		{"eST.Sales.label","ขาย"},
		{"eST.SalesAttributes.label","คุณสมบัติเ�?ี่ยว�?ับ�?ารขาย"},
		{"eST.SalesAuthorize.label","ลงนาม�?ารขาย"},
		{"eST.SalesBatchSearch.label","สืบค้นชุดเ�?ี่ยว�?ับ�?ารขาย"},
		{"eST.SalesHistory.label","ประวัติ�?ารขาย"},
		{"eST.SalesReturnFinalize.label","ข้อสรุป�?ารคืน�?ารขาย"},
		{"eST.SalesReturnPreviewDetails.label","รายละเอียด�?สดงคืน�?ารขาย"},
		{"eST.SalesReturns.label","คืน�?ารขาย"},
		{"eST.SalesType.label","ชนิด�?ารขาย"},
		{"eST.Sales/PatientIssue.label","ประเด็น�?ารขาย/ผู้ป่วย"},
		{"eST.Sales/PatientIssueCost.label","ต้นทุน�?ารขาย/ผู้ป่วย"},
		{"eST.Sales/PatientIssuesPreviewDetails.label","รายละเอียด�?สดงประเด็น�?ารขาย/ผู้ป่วย"},
		{"eST.Sample.label","ตัวอย่าง"},
		{"eST.SelectBatchFor.label","เลือ�?ชุดสำหรับ "},
		{"eST.SelectCriteria.label","เลือ�?เ�?ณฑ์"},		
		{"eST.ShowBatchInfo.label","�?สดงข้อมูลของชุด"},		
		{"eST.SpecialReqItem.label","ราย�?ารขอที่เฉพาะเจาะจง"},
		{"eST.SpecialRequest.label","�?ารขอที่เฉพาะเจาะจง"},
		{"eST.SplitBatch.label","ชุดที่�?ย�?ออ�?"},
		{"eST.SplitBatches.label","ชุดที่�?ย�?ออ�?"},
		{"eST.StandardFormulary.label","สูตรมาตร�?าน"},
		{"eST.Sterile.label","ปราศจา�?เชื้อ"},		
		{"eST.Sterilizable.label","ทำให้ปราศจา�?เชื้อได้"},		
		{"eST.StockAdjustment.label","�?ารปรับสต๊อ�?"},
		{"eST.StockAdjustmentFinalize.label","ข้อสรุป�?ารปรับสต๊อ�?"},
		{"eST.StockatPrimaryStore.label","สต๊อ�?ที่ห้องยา�?ร�?"},
		{"eST.StockAvailability.label","สต๊อ�?ที่สามารถหาได้"},
		{"eST.StockFast/SlowMovementReport.label","รายงาน�?ารเคลื่อนไหวเร็ว/ช้าของสต๊อ�?"},
		{"eST.StockHandledByMedicalStore.label","สต๊อ�?ที่ดู�?ลโดยห้องยา"},
		{"eST.StockHoldingAnalysisReport.label","รายงานวิเคราะห์สต๊อ�?ที่มีอยู่"},
		{"eST.StockItem.label","ราย�?ารสต๊อ�?เ�?ี่ยว�?ับยา"},
		{"eST.StockItemConsumption.label","�?ารใช้ราย�?ารที่สต๊อ�?"},
		{"eST.StockItemConsumptionPreviewDetails.label","รายละเอียด�?สดง�?ารใช้ราย�?ารที่สต๊อ�?"},
		{"eST.StockLevel.label","ระดับ�?ารสต๊อ�?"},
		{"eST.StockPositionof.label","ตำ�?หน่งสต๊อ�?ของ"},
		{"eST.StockReorderStore.label","ห้องยาสำหรับสั่งสต๊อ�?ใหม่"},
		{"eST.StockStatusByItem.label","สถานะสต๊อ�?ตามราย�?าร"},
		{"eST.StockStatusReportForTransactedItems.label","รายงานสถานะสต๊อ�?สำหรับราย�?ารที่ดำเนิน�?าร"},
		{"eST.StockTransfer.label","�?ารโย�?ย้ายสต๊อ�?"},
		{"eST.StockTransferFinalize.label","ข้อสรุป�?ารโย�?ย้ายสต๊อ�?"},		
		{"eST.StockValue.label","ค่าที่สต๊อ�?"},		
		{"eST.StoreFrom.label","ห้องยาจา�?"},
		{"eST.StoreTo.label","ห้องยาถึง"},		
		{"eST.StorewiseConsumption.label","�?ารบริโภคของ�?ต่ละห้องยา"},
		{"eST.StorewiseConsumptionforthePeriod.label","�?ารบริโภคของ�?ต่ละห้องยาในรอบนั้น ๆ"},
		{"eST.SubStore.label","ห้องยาย่อย"},
		{"eST.SuppressSummary.label","สรุป�?ารระงับ"},
		{"eST.SuspendDate.label","วันที่ถู�?ระงับ�?ารจ่าย"},		
		{"eST.Suspended&ExpiredBatch.label","Batch ที่ถู�?ระงับ�?ารจ่าย �?ละBatch ที่หมดอายุ"},
		{"eST.SuspendedBatch.label","Batch ที่ถู�?ระงับ�?ารจ่าย"},
		{"eST.SuspendedExpiredNotifiedBatch.label","ชุดที่�?จ้งไว้�?ละหมดอายุ, ระงับ�?ารจ่าย"},
		{"eST.TechnicalSpecification.label","รายละเอียดทางเทคนิค"},
		{"eST.TemporaryPhyInvID.label","เลขประจำคลังยาที่มีอยู่จริงชั่วคราว"},		
		{"eST.ToBinLocation.label","ถึงช่องเ�?็บยา"},
		{"eST.ToDocDate.label","ตามวันที่เอ�?สาร"},
		{"eST.ToItem.label","ตามราย�?าร"},		
		{"eST.ToStoreMasterBin.label","ถึงห้องเ�?็บยาหลั�?"},		
		{"eST.TotalItemValue.label","ต้นทุนราย�?ารทั้งหมด"},
		{"eST.TotalStock.label","สต๊อ�?ทั้งหมด"},		
		{"eST.TransAnalysisReport.label","รายงานวิเคราะห์�?ารดำเนินงาน"},
		{"eST.TransQty.label","ปริมาณ�?ารโอนย้าย"},		
		{"eST.Transactionacrossfacility.label","ดำเนิน�?ารข้ามสถานบริ�?าร"},
		{"eST.TransactionApplicable.label","ดำเนิน�?ารได้"},		
		{"eST.TransferExecutedby.label","โอนย้ายโดย"},		
		{"eST.TransferQty.label","ปริมาณ�?ารโอนย้าย"},		
		{"eST.UnfinalizedTransactionsReport.label","รายงาน�?ารประชุมที่หาข้อสรุปไม่ได้"},
		{"eST.UnitPrice.label","ราคาต่อหน่วย"}, // extra
		{"eST.UrgentIssue.label","ประเด็นเร่งด่วน"},
		{"eST.UrgentIssueFinalize.label","สรุปประเด็นเร่งด่วน"},
		{"eST.UseAfterExpiry.label","ใช้ภายหลัง�?ารหมดอายุ"},		
		{"eST.UserInfo.label","ข้มูลผู้ใช้"},
		{"eST.VendorReturn.label","คืนผู้ขาย"},
		{"eST.VendorReturnFinalize.label","สรุป�?ารคืนผู้ขาย"},
		{"eST.WithFormulary.label","ด้วย�?ารรวมสูตร"},
		{"eST.WithoutFormulary.label","ปราศจา�?�?ารรวมสูตร"},
		{"eST.WorkLoadStatisticReport.label","รายงานสถิติภาระงาน"},
		{"eST.YearlyStockTurnoverReport.label","รายงาน�?ารคืนคลังประจำปี"},
		{"eST.YTDConsQty.label","ปริมาณต่อเนื่องของ YTD"},
		{"eST.YTDIssQty.label","ปริมาณ�?ารออ�? YTD"}
		// new labels be added
		/*{"eST.Autoclavable.label","th-Autoclavable"},
		{"eST.CondemnID.label","th-Condemn ID"},
		{"eST.CounterChecked.label","th-Counter Checked"},
		{"eST.FromStore.label","th-From  Store"},
		{"eST.ItemAnalysisCodeshouldbeunique.label","th-Item Analysis Code should be unique"},
		{"eST.ModelNoFrom.label","th-Model No From"},
		{"eST.PRT.label","th-PRT"},
		{"eST.RET.label","th-RET"},
		{"eST.RFDays.label","th-RF Days"},
		{"eST.RTV.label","th-RTV"},
		{"eST.S.label","th-S"},
		{"eST.SAL.label","th-SAL"},
		{"eST.SRT.label","th-SRT"},
		{"eST.StockConvFactor.label","th-Stock Conv Factor"},
		{"eST.SuppressZero.label","th-Suppress Zero"},
		{"eST.SuppressZeroVariance.label","th-Suppress Zero Variance"},
		{"eST.TFR.label","th-TFR"},
		{"eST.URG.label","th-URG"},
		{"eST.WardSupplyManufacturingAndRepackingOutput.label","th-Ward Supply  Manufacturing And Repacking-Output"},  
		{"eST.ReportOnGRNStatisticsForDrugs.label","th-Report On GRN Statistics For Drugs"},  
		{"eST.QAP13AnnualTurnoverRateofStock.label","th-QAP-13   Annual Turn-over Rate of Stock"},  
		{"eST.QAP14Proportionofvalueofstockswrittenoff.label","th-QAP 14 - Proportion of value of stocks written off"},  
		{"eST.ReturnType.label","th-Return Type"},  
		{"eST.StockReturns.label","th-Stock Returns"},  
		{"eST.StockIssues.label","th-Stock Issues"},  
		{"eST.PresentCountStatus.label","th-Present Count Status"},  
		{"eST.PurchaseValueItems.label","th-Purchase Value Items"},  
		{"eST.RequestOnStoreCode.label","th-Request On Store Code"},  
		{"eST.Excludetheitemsreceivedwithin.label","th-Exclude the items received within"},  
		{"eST.IssueType.label","th-Issue Type"},  
		{"eST.ConsignmentItems.label","th-Consignment Items"},  
		{"eST.ABCCodeItemMaster.label","th-ABC Code {Item Master}"},  
		{"eST.RepackingGroupCode.label","th-RepackingGroup Code"},  
		{"eST.RepackingGroupDescription.label","th-RepackingGroup Description"},  
		{"eST.ZeroStockItems.label","th-Zero Stock Items"},  
		{"eST.ItemLessthanReorderLevel.label","th-Item Less than Reorder Level"},  
		{"eST.ItemLessthanMinimumLevel.label","th-Item Less than Minimum Level"},  
		{"eST.ItemwithStock.label","th-Item with Stock"},  
		{"eST.ItemGreaterthanMaximumLevel.label","th-Item Greater than Maximum Level"},  
		{"eST.ActiveBatches.label","th-Active Batches"},  
		{"eST.SuspendedBatches.label","th-Suspended Batches"},  
		{"eST.AllBatches.label","th-All Batches"},  
		{"eST.ItemConsolidated.label","th-Item Consolidated"},  
		{"eST.ByItemStore.label","th-By Item Store"},  
		{"eST.ByStoreBatch.label","th-By Store Batch"},  
		{"eST.ByStoreBinLocation.label","th-By Store Bin Location"},  
		{"eST.ByItemBatch.label","th-By Item Batch"},  
		{"eST.NonZeroStock.label","th-Non Zero Stock"},  
		{"eST.ItemClassConsolidated.label","th-Item Class Consolidated"},  
		{"eST.StoreItem.label","th-Store-Item"},  
		{"eST.StoreItemClass.label","th-Store-Item Class"},  
		{"eST.NonSpecialItem.label","th-Non Special Item"},  
		{"eST.ConsumptionDeviation.label","th-Consumption Deviation"},  
		{"eST.ConsumptionByATCClassification.label","th-Consumption By ATC Classification"},  
		{"eST.StoreLevel.label","th-Store Level"},  
		{"eST.ByGRN.label","th-By GRN"},  
		{"eST.ByQuantity.label","th-By Quantity"},  
		{"eST.ByValue.label","th-By Value"},  
		{"eST.ProductRecall.label","th-Product Recall"},  
		{"eST.LastAccessedOn.label","th-Last Accessed On"},  
		{"eST.RequestItemDetailsfor.label","th-Request Item Details for"},  
		{"eST.NoMovement.label","th-No Movement"},  
		{"eST.GoodsReceivedNote.label","th-Goods Received Note"},  
		{"eST.GoodsReturntoVendor.label","th-Goods Return to Vendor"},  
		{"eST.ItemnotmappedtoDrug.label","th-Item not mapped to Drug"},  
		{"eST.SameAsExpiryDate.label","th-Same As Expiry Date"},  
		{"eST.RequestStatisticsReport.label","th-Request Statistics Report"} , 
		{"eST.DrugDescIsDifferent.label","th-Drug Description is different from Item Description.. Do you want to overwrite the existing Drug Description..{Ok/Cancel}?"},  
		{"eST.ByCondemnedId.label","th-By Condemned Id"}, 
		{"eST.VarianceReportatBatchLevel.label","th-Variance Report at Batch Level"}, 
		{"eST.VarianceReportatItemLevel.label","th-Variance Report at Item Level"}, 
		{"eST.VarianceReportatStoreLevel.label","th-Variance Report at Store Level"}, 
		{"eST.SummaryReportatItemClassLevel.label","th-Summary Report at Item Class Level"}, 
		{"eST.OnlyNotifiedBatches.label","th-Only Notified Batches"}, 
		{"eST.BufferonMinStock.label","th-Buffer % {on Min Stock}"}, 
		{"eST.Notify.label","th-Notify"}, 
		{"eST.LastAccessedBy.label","th-Last Accessed By"},  
		{"eST.ByItemClass.label","th-By Item Class"}, 
		{"eST.ReorderableStoresOnly.label","th-Reorderable Stores Only"}, 
		{"eST.NonReorderableStoresOnly.label","th-Non Reorderable Stores Only"}, 
		{"eST.TopValue.label","th-Top Value"}, 
		{"eST.CostValue.label","th-Cost Value"}, 
		{"eST.InventoryAgeingSlot.label","th-Inventory Ageing Slot"} ,
		{"eST.InventoryIssues.label","th-Inventory Issues"} ,
		{"eST.InventoryReturns.label","th-Inventory Returns"} ,
		{"eST.ISS.label","th-ISS"},
		{"eST.ModifiableYN.label","th-Modifiable Y/N"} ,		
		{"eST.MoreDetails.label","th-More Details"},
		{"eST.MovementCutoffMonthsSlotRanges.label","th-Movement Cutoff Months {Slot Ranges}"},
		{"eST.Outflow.label","th-Outflow"} ,
		{"eST.Particular.label","th-Particular"} ,
		{"eST.PhysicalCountSheetHistory.label","th-Physical CountSheet History"},
		{"eST.PrepareInstruction.label","th-Prepare Instruction"},
		{"eST.ReportOfTransferredBatches.label","th-Report Of Transferred Batches"},
		{"eST.RTVValue.label","th-RTV Value"} ,
		{"eST.SampleQuantity.label","th-Sample Quantity"} ,
		{"eST.ShowItems.label","th-Show Items"},
		{"eST.SoleSourceYN.label","th-Sole Source YN"},
		{"eST.SpecialItemYN.label","th-Special Item YN"},
		{"eST.StockInflow.label","th-Stock Inflow"} ,
		{"eST.StockOnHand.label","th-Stock On Hand"},
		{"eST.StockOutflow.label","th-Stock Outflow"} , 
		{"eST.StoreLevelStatus.label","th-Store Level Status"},
		{"eST.TransactionAnalysisReport.label","th-Transaction Analysis Report"},
		{"eST.ValueOfProcurementMadeByMedicalStore.label","th-Value Of Procurement Made By Medical Store"}, 
		{"eST.ZeroStock.label","th-Zero Stock"},
		{"eST.AgeingSlotdays.label","th-Ageing Slot {days}"}, 
		{"eST.AssemblyItemCode.label","th-Assembly Item Code"} ,
		{"eST.AutoclavableYN.label","th-Autoclavable YN"},
		{"eST.BasesYN.label","th-Bases Y/N"} ,
		{"eST.BatchQuantity.label","th-Batch Quantity"},		
		{"eST.Inflow.label","th-Inflow"} ,
		{"eST.Reorder.label","th-Re-Order"},
		{"eST.BelowMinStockLevel.label","th-Below Min Stock Level"},
		{"eST.PendReqdQty.label","th-Pend Req Qty"},
		{"eST.forItemCode.label","th-for Item Code"},
		{"eST.exceedmaxStockLevel.label","th-exceed max Stock Level"},
		{"eST.LessThanROLinFromStore.label","th-Less Than R.O.L in From Store"},
		{"eST.ExceedsMaxStkinToStore.label","th-Exceeds Max. Stk. in To Store"},	
		{"eST.BelowMinStkinFromStore.label","th-Below Min Stk in From Store"},
		{"eST.IndividualItem.label","th-Individual Item"},		
		{"eST.RangeOfItems.label","th-Range Of Items"}	,	
		{"eST.BasedYN.label","th-Based Y/N"}	,	
		{"eST.ExpiryYN.label","th-Expiry Y/N"},
		{"eST.ADJ.label","th-ADJ"},
		{"eST.expiredBatches.label","th-ExpiredBatche{s}"},
		{"eST.ReOrder.label","th-Re Order"},
		{"eST.IssQty.label","th-Iss Qty"},
		{"eST.Ingredients.label","th-Ingredients"},
		{"eST.PrintOnlabel.label","th-Print On Label"},
		{"eST.GetData.label","th-Get Data"},
		{"eST.MfgInstructions.label","th-Mfg Instructions"},
		{"eST.ToStoreBin.label","th-To Store Bin"},
		{"eST.RepackFactor.label","th-Repack Factor"},
		{"eST.ReplacementGRNExists.label","th-Replacement GRN Exists"},
		{"eST.FinalizedandRTVExists.label","th-Finalized and RTV Exists"},
		{"eST.RequisitionRef.label","th-Requisition Ref"},
		{"eST.PuUOMFACTOR.label","th-PuUOM/FACTOR"},
		{"eST.RequestedUOM.label","th-Requested UOM"},
		{"eST.RequestqtyinReqUOM.label","th-Request qty in Req UOM"},
		{"eST.RTVDetails.label","th-RTV Details"},
		{"eST.ReplGRNQty.label","th-Repl GRN Qty"},
		{"eST.TotalNoOfItems.label","th-Total No Of Items"},
		{"eST.TotalTransferValue.label","th-Total Transfer Value"},
		{"eST.DuplicateCopy.label","th-Duplicate/Copy"},
		{"eST.SoldQuantity.label","th-Sold Quantity"},
		{"eST.SaleValue.label","th-Sale Value"},
		{"eST.AdjustQuantity.label","th-Adjust Quantity"},
		{"eST.AdjustCost.label","th-Adjust Cost"},		
		{"eST.BatchValue.label","th-Batch Value"},		
		{"eST.AdjustLineRemarks.label","th-Adjust Line Remarks"},		
		{"eST.FromItemCode.label","th-From Item Code"},		
		{"eST.FromExpiryDate.label","th-From Expiry Date"},		
		{"eST.FromItemQuantity.label","th-From Item Quantity"},		
		{"eST.NewBatch.label","th-New Batch"},		
		{"eST.Repackat.label","th-Repack at"},
		{"eST.ReqEnteredBy.label","th-Req Entered By"},
		{"eST.ReqAuthorisedBy.label","th-Req Authorised By"},
		{"eST.IssueAuthorisedBy.label","th-Issue Authorised By"},
		{"eST.issueref.label","th-Issue Ref"},
		{"eST.ReqDocDate.label","th-Req Doc Date"},
		{"eST.RequestQtyin.label","th-Request Qty In"},
		{"eST.issuom.label","th-Iss UOM"},
		{"eST.IssueQty{ISSUOM}.label","th-Issue Qty{ISSUOM}"},
		{"eST.IssueQtyStkUOM.label","th-Issue Qty Stk UOM"},
		{"eST.QuantityPrepared.label","th-Quantity Prepared"},
		{"eST.QtyUsed.label","th-Qty Used"},
		{"eST.QtyValue.label","th-Qty Value"},
		{"eST.BinDescription.label","th-Bin Description"},
		{"eST.IssueToStore.label","th-Issue To Store"},
		{"eST.IssueFromStore.label","th-Issue From Store"},
		{"eST.AdjQty.label","th-Adj Qty"},
		{"eST.Adjcost.label","th-Adj Cost"},
		{"eST.BatchQty.label","th-Batch Qty"},
		{"eST.ToItemCode.label","th-To Item Code"},
		{"eST.ToExpiryDate.label","th-To Expiry Date"},
		{"eST.Repackeddate.label","th-Repacked Date"},
		{"eST.StockItemYN.label","th-StockItem YN"},
		{"eST.IssueValue.label","th-Issue Value"},
		{"eST.AdjustQty.label","th-Adjust Qty"},
		{"eST.HomeCarepatients.label","th-Home Care patients"},
		{"eST.StoreSubTotal.label","th-Store Sub Total"},
		{"eST.PayabAmt.label","th-Payab Amt"},
		{"eST.chargeAmt.label","th-Charge Amt"},
		{"eST.FolioAtBatchPrice.label","th-Folio At Batch Price"},
		{"eST.InpatientSaleApplicable.label","th-Inpatient Sale Applicable"},
		{"eST.OutpatientSaleApplicable.label","th-Outpatient Sale Applicable"},
		{"eST.ReferralSaleApplicable.label","th-Referral Sale Applicable"},
		{"eST.ItemClassFrom.label","th-Item Class From"},
		{"eST.CutOffRangeforA.label","th-Cut Off Range for A"},
		{"eST.CutOffRangeforB.label","th-Cut Off Range for B"},
		{"eST.CutOffRangeforC.label","th-Cut Off Range for C"},
		{"eST.MinimumStock.label","th-Minimum Stock"},
		{"eST.NoOfItems.label","th-No Of Items"},		
		{"eST.NoOfTransactions.label","th-No. Of Transactions"},
		{"eST.ItemClassTotal.label","th-Item Class Total"},
		{"eST.ItemTotal.label","th-Item Total"},
		{"eST.UpTo.label","th-Up To"},
		{"eST.Above.label","th-Above"},
		{"eST.FortheFollowingIndicator.label","th-For the Following Indicator"},
		{"eST.AnnualTurnOverRateOfStocks.label","th-Annual Turn-Over Rate Of Stocks"},
		{"eST.AnnualValueOfStocksIssued.label","th-Annual Value Of Stocks Issued"},
		{"eST.ValueOfStocksHeldAnnually.label","th-Value Of Stocks Held Annually"},
		{"eST.AnnualTurnOverRateofStocks.label","th-Annual Turn Over Rate of Stocks"},
		{"eST.ValueOfStocksHeldon1stJanValueOfStocksHeldOn31stDecOfTheSameYear.label","th-{Value Of Stocks Held on 1stJan+Value Of Stocks Held On 31stDec Of The Same Year}/2"},
		{"eST.ThisformistobesenttostatePharmacyDivisioneveryYear.label","th-This form is to be sent to state Pharmacy Division every Year"},
		{"eST.JanDecby15thJan.label","th-Jan-Dec-by 15th Jan"},
		{"eST.JanDecby31stJan.label","th-Jan-Dec-by 31st Jan"},
		{"eST.ThisStatePharmacyDivisionwillsendthisformtostatePharmaceuticalServicesDivisioneveryYear.label","th-This State Pharmacy Division will send this form to state Pharmaceutical Services Division every Year"},
		{"eST.AssemblyItemCodeFrom.label","th-Assembly Item Code From"},
		{"eST.ChildItemCode.label","th-Child Item Code"},
		{"eST.ChildItemDescription.label","th-Child Item Description"},
		{"eST.ComponentQty.label","th-Component Qty"},
		{"eST.AssemblyItem.label","th-Assembly Item"},
		{"eST.ATCClassificationFrom.label","th-ATC Classification From"},
		{"eST.ConsumptionPeriodFrom.label","th-Consumption Period From"},
		{"eST.ComplaintBy.label","th-Complaint By"},
		{"eST.ClassTotal.label","th-Class Total"},
		{"eST.ClassCode.label","th-Class Code"},
		{"eST.ClassDescription.label","th-Class Description"},
		{"eST.AsonReportDateExpiredStock.label","th-As on Report Date Expired Stock"},
		{"eST.TotalStockValue.label","th-Total Stock Value"},
		{"eST.CutOfDateFrom.label","th-Cut Of Date From"},
		{"eST.ItemClassStockValue.label","th-Item Class Stock Value"},
		{"eST.EXPIRYINGBETWEEN.label","th-Expiring Between"},
		{"eST.MoveYearFrom.label","th-Move Year From"},
		{"eST.StockValueReceived.label","th-Stock Value Received"},
		{"eST.NumberofItemReceived.label","th-Number of Item Received"},
		{"eST.ValueofItemSupplied.label","th-Value of Item Supplied"},
		{"eST.StockValueAtDec31.label","th-Stock Value At Dec31"},
		{"eST.ValueDisposed.label","th-Value Disposed"},
		{"eST.NoofChecksbyStockVerificationBoard.label","th-No of Checks by Stock Verification Board"},
		{"eST.NumberofGRNs.label","th-Number of GRNs"},
		{"eST.IssuingStoreFrom.label","th-Issuing Store From"},
		{"eST.Add/ModifyItem.label","th-Add/Modify Item"},
		{"eST.KitTemplateCode.label","th-Kit Template Code"},
		{"eST.KitTemplateDescription.label","th-Kit Template Description"},
		{"eST.ViewCostDetails.label","th-View Cost Details"},
		{"eST.NoofrecordsperTransaction.label","th-No. of records per Transaction"},
		{"eST.MachineCodeFrom.label","th-Machine Code From"},
		{"eST.PartNoFrom.label","th-Part No From"},
		{"eST.NonInventory.label","th-Non Inventory"},
		{"eST.YtdRecp.label","th-Ytd Recp"},
		{"eST.YtdConsm.label","th-Ytd Consm"},
		{"eST.MachCode.label","th-Mach Code"},
		{"eST.PreviousQty.label","th-Previous Qty"},
		{"eST.ConsignmentYN.label","th-Consignment Y/N"},
		{"eST.InsuranceYN.label","th-Insurance Y/N"},
		{"eST.PhysicalInvType.label","th-Physical Inv Type"},
		{"eST.ManufacturedItems.label","th-Manufactured Items"},
		{"eST.UseafterexpiryYN.label","th-Use after expiry Y/N"},
		{"eST.NetStockPosition.label","th-Net Stock Position"},
		{"eST.UnitCostFrom.label","th-Unit Cost From"},
		{"eST.StockPosition.label","th-Stock Position"},
		{"eST.StockValueFrom.label","th-Stock Value From"},
		{"eST.NoofStores.label","th-No of Stores"},
		{"eST.NetQty.label","th-Net Qty"},
		{"eST.Part.label","th-Part"},
		{"eST.IndicatesSuspendedBatch.label","th-Indicates Suspended Batch"},
		{"eST.BatchStatus.label","th-Batch Status"},
		{"eST.ItemBelowMinimumLevel.label","th-Item Below Minimum Level"},
		{"eST.ItemsBelowReorderLevel.label","th-Items Below Reorder Level"},
		{"eST.ClearenceBalance.label","th-Clearence Balance"},
		{"eST.PresentStock.label","th-Present Stock"},
		{"eST.ReorderValue.label","th-Reorder Value"},
		{"eST.LastReceiptDate.label","th-Last Receipt Date"},
		{"eST.LastCost.label","th-Last Cost"},
		{"eST.NonSpecialItemOnly.label","th-Non Special Item Only"},
		{"eST.SpecialItemOnly.label","th-Special Item Only"},
		{"eST.IssuedItem.label", "Issued Item"},
		{"eST.TRN.label", "TRN"},
		{"eST.TrnQty.label", "Trn Qty"},
		{"eST.LastDate.label","th-Last Date"},
		{"eST.AlphaCodeFrom.label", "Alpha Code From"},
		{"eST.Issued.label", "Issued"},
		{"eST.AvgQty.label", "Avg Qty"},
		{"eST.DeviationPercentage.label","th-Deviation Percentage"},
		{"eST.Last12MonthsConsumption.label","th-Last 12 Months Consumption"},
		{"eST.PrevYear12MonthsConsumption.label","th-Prev Year 12 Months Consumption"},
		{"eST.SupressZero.label","th-Supress Zero"},
		{"eST.ExcludeExStore.label","th-Exclude Ex Store"},
		{"eST.VariancePostedBy.label","th-Variance Posted By"},
		{"eST.StartQty.label","th-Start Qty"},
		{"eST.PhyStock.label","th-Phy Stock"},
		{"eST.VarQtypve.label","th-Var Qty {+}ve"},
		{"eST.VarQtynve.label","th-Var Qty {-}ve"},
		{"eST.VarValuepve.label","th-Var Value {+}ve"},
		{"eST.VarValuenve.label","th-Var Value {-}ve"},
		{"eST.TrnQtyForPeriod.label","th-Trn Qty For Period"},
		{"eST.NoofItemsSupplied.label","th-No of Items Supplied"},
		{"eST.StockTurnOverRate.label","th-Stock Turn Over Rate"},
		{"eST.NoofItemDisposed.label","th-No of Item Disposed"},
		{"eST.MoveYear.label","th-Move Year"},
		{"eST.ClosingStock.label","th-Closing Stock"},
		{"eST.TurnoverRate.label","th-Turn over Rate"},
		{"eST.Last.label","th-Last"},
		{"eST.EarliestExpiryDate.label","th-Earliest Expiry Date"},
		{"eST.TotalCondemnID.label","th-Total Condemn ID"},
		{"eST.PercentageonExpiryStock.label","th-Percentage on Expiry Stock"},
		{"eST.NumberofFinalizedGRNs.label","th-Number of Finalized GRNs"},
		{"eST.NumberofUnfinalizedGRNs.label","th-Number of Unfinalized GRNs"},
		{"eST.MfgDate.label","th-Mfg Date"},
		{"eST.UserFrom.label","th-User From"},
		{"eST.CancelledPhysicalCountSheet.label","th-Cancelled Physical Count Sheet"},
		{"eST.CancelDate.label","th-Cancel Date"},
		{"eST.EmployeeName.label","th-Employee Name"},
		{"eST.Percent.label","th-Percent"},
		{"eST.SummaryfortheItemClass.label","th-Summary for the Item Class"},
		{"eST.NumberofItemsCounted.label","th-Number of Items Counted"},
		{"eST.ValueasperPhysicalInventory.label","th-Value as per Physical Inventory"},
		{"eST.NumberofItemswithpveVariance.label","th-Number of Items with (+}ve Variance"},
		{"eST.NumberofItemswithnveVariance.label","th-Number of Items with (-}ve Variance"},
		{"eST.TotalVarianceValue.label","th-Total Variance Value"},
		{"eST.SummaryofClasses.label","th-Summary of Classes"},
		{"eST.PhysicalIdTotal.label","th-Physical Id Total"},
		{"eST.TotalPhysicalInventoryID.label","th-Total Physical Inventory ID"},
		{"eST.PositiveVariance.label","th-Positive Variance"},
		{"eST.NegativeVariance.label","th-Negative Variance"},
		{"eST.NetVariance.label","th-Net Variance"},
		{"eST.ZeroVariance.label","th-Zero Variance"},
		{"eST.CountSheet.label","th-Count Sheet"},
		{"eST.Expirable.label","th-Expirable"},
		{"eST.PercentageOnPresentCount.label","th-Percentage On Present Count"},
		{"eST.AutoBatchGenerationYN.label","th-Auto Batch Generation Y/N"},
		{"eST.BatchIDSeries.label","th-Batch ID Series"},
		{"eST.NextBatchID.label","th-Next Batch ID"},
		{"eST.TotalnoofLocationCode.label","th-Total no of Location Code"},
		{"eST.Yield.label","th-Yield"},
		{"eST.ItemRequested.label","th-Item Requested"},
		{"eST.RepackingCode.label","th-Repacking Code"},
		{"eST.RequestedQtyinReqUOM.label","th-RequestedQty(inReqUOM}"},
		{"eST.RequestedQtyinStkUOM.label","th-RequestedQty(inStkUOM}"},
		{"eST.CommitedQty.label","th-Commited Qty"},
		{"eST.Receipts.label","th-Receipts"},
		{"eST.ReceiptQty.label","th-Receipt Qty"},
		{"eST.ReplacementCompleted.label","th-Replacement Completed"},
		{"eST.NoofReqStores.label","th-No.of ReqStores"},
		{"eST.NoofRequests.label","th-No.of Requests"},
		{"eST.NoofCompletedRequests.label","th-No.ofCompletedRequests"},
		{"eST.NoofPendingRequests.label","th-No.ofPendingRequests"},
		{"eST.NoofCancelRequests.label","th-No.ofCancelRequests"},
		{"eST.PercentageonCompletedRequests.label","th-Percentage on Completed Requests"},
		{"eST.NoofItemsRequested.label","th-No of Items Requested"},
		{"eST.NoofItemsCompletelyIssued.label","th-No.of ItemsCompletelyIssued"},
		{"eST.NoofItemsPartiallyIssued.label","th-No.of ItemsPartiallyIssued"},
		{"eST.PercentageonCompletelyIssued.label","th-Percentage on Completely Issued"},
		{"eST.ItemCost.label","th-Item Cost"},
		{"eST.GRNRef.label","th-GRN Ref"},
		{"eST.StockValueReceivedRM.label","th-StockValueReceived (RM}"},
		{"eST.ValueofItemSuppliedRM.label","th-ValueofItemSupplied(RM}"},
		{"eST.NumberofItemCondemnedRM.label","th-NumberofItemCondemned(RM}"}, 
		{"eST.ValueCondemned.label","th-Value Condemned"},
		{"eST.NumberOfQualityComplaints.label","th-Number Of Quality Complaints"},
		{"eST.CheckStockLevel.label","th-Check Stock Level"},
		{"eST.TransactionAllowed.label","th-Transaction Allowed"},
		{"eST.BinChange.label","th-Bin Change"},
		{"eST.AuthorizeAtIssueStore.label","th-Authorize At Issue Store"},
		{"eST.CondemnExpiryBatches.label","th-Condemn Expiry Batches"},
		{"eST.RequestIssues.label","th-Request Issues"},
		{"eST.PendingRequest.label","th-Pending Request"},
		{"eST.WardUnitSupply.label","th-Ward/Unit Supply"},
		{"eST.DrugManufacturing.label","th-Drug Manufacturing"},
		{"eST.PrepackedDrug.label","th-Prepacked Drug"},
		{"eST.SatellitePharmacy.label","th-Satellite Pharmacy"},
		{"eST.NoofPack.label","th-No of Pack"},
		{"eST.NoItem.label","th-No Item"},
		{"eST.NoPack.label","th-No Pack"},
		{"eST.Tablet.label","th-Tablet"},
		{"eST.NoofStaff.label","th-No of Staff"},
		{"eST.Atten.label","th-Atten"},
		{"eST.PharAsst.label","th-Phar Asst"},
		{"eST.NoofWardUnit.label","th-No. of Ward/Unit"},
		{"eST.UnitofUse.label","th-Unit of Use"},
		{"eST.Traditional.label","th-Traditional"},
		{"eST.MFGRequest.label","th-MFG Request"},
		{"eST.ItemTobeManufactured.label","th-Item To be Manufactured"},
		{"eST.ProcessLossPercent.label","th-Process Loss Percent"},
		{"eST.PrepareType.label","th-Prepare Type"},
		{"eST.ExpectedOutput.label","th-Expected Output"},
		{"eST. MFGStore.label","th-MFG Store"},
		{"eST.RequestedQty.label","th-Requested Qty"},
		{"eST.ActualOutput.label","th-Actual Output"},
		{"eST.Constituent.label","th-Constituent"},
		{"eST.TimeTakenForPreparation.label","th-Time Taken For Preparation"},
		{"eST.Repackedat.label","th-Repacked at"},
		{"eST.ItemToBePacked.label","th-Item To Be Packed"},
		{"eST.SourceBatch.label","th-Source Batch"},
		{"eST.ExpectedBalance.label","th-Expected Balance"},
		{"eST.ActualQty.label","th-Actual Qty"},
		{"eST.ActualBal.label","th-Actual Bal"},
		{"eST.ProductIdentification.label","th-Product Identification"},
		{"eST.TimeTakenforRepacking.label","th-Time Taken for Repacking"},
		{"eST.HighestValueofPurchaseForAPPLDrugs.label","th-Highest Value of Purchase For APPL Drugs"},
		{"eST.HighestValueofPurchaseForNONAPPLDrugs.label","th-HighestValueofPurchaseForNON-APPLDrugs"},
		{"eST.TotalPurchasedQuantity.label","th-Total Purchased Quantity"},
		{"eST.PriceUnitRM.label","th-Price/Unit(RM}"},
		{"eST.APPL.label","th-APPL"},
		{"eST.NONAPPL.label","th-NON-APPL"},
		{"eST.APPLNONAPPL.label","th-APPL & NON-APPL"},
		{"eST.PrintNilStockItems.label","th-Print Nil Stock Items"},
		{"eST.NonStockItem.label","th-Non-Stock Item"},
		{"eST.ROQty.label","th-RO Qty"},
		{"eST.DirectSales.label","th-Direct Sales"},
        {"eST.InternalReportsReprint.label","th-Internal Reports Reprint"},
        {"eST.ValueasperSystem.label","th-Value as per System"},
		{"eST.NumberofItemswithvarriance.label","th-Number of Items with variance"},
		{"eST.NilStockItems.label","th-Nil Stock Items"},
      	{"eST.TotalNoOfRepackingGroups.label","th-Total No Of Repacking Groups"},
        {"eST.IssuedItemQty.label","th-Issued Item Qty"},
        {"eST.MaximumStock.label","th-Maximum Stock"},
        {"eST.IssueReturn.label","th-Issue Return"},
        {"eST.SalesReturn.label","th-Sales Return"},
		{"eST.ItemsWithZeroAuthorizedQuantity.label","th-Items With Zero Authorized Quantity"},
		{"eST.Exp.label","th-Exp"},
		{"eST.Referrals.label","th-Referrals"}	,	
		{"eST.RepackedProduct.label","th-Repacked Product"},
		{"eST.ProductDescription","th-Product Description"},
		{"eST.CancelRequestBy.label","th-Cancel Request By"},
		{"eST.AuthorizedDate.label", "th-Authorized Date"},
		{"eST.RaisedBy.label","th-Raised By"},
		{"eST.ActionType.label","th-Action Type"},
		{"eST.Acknowledge.label","th-Acknowledge"},
		{"eST.Show.label","th-Show"},
		{"eST.CopyValues.label","th-Copy Values"},
		{"eST.BillDate.label","th-Bill Date"},
		{"eST.BillNo.label","th-Bill No."},
		{"eST.RegNo.label","th-Reg No."},
		{"eST.SalePriceApplicable.label","th-Sale Price Applicable"},
		{"eST.MRPGreaterThanUnitPrice.label","th-MRP Greater Than Unit Price"},
		{"eST.CategoryDrugNonDrug.label", "th-Category(Drug / Non Drug)"},
		{"eST.NameofItems.label","th-Name of Items"},
		{"eST.DateOfPurchaseReceive.label","th-Date Of Purchase/Receive"},
		{"eST.PeriodUsed.label","th-Period Used"},
		{"eST.PurchasingValue.label","th-Purchasing Value"},
		{"eST.CurrentValue.label","th-Current Value"},
		{"eST.RemarksCommentsbyInspectionBoard.label","th-Remarks/Comments by Inspection Board"},
		{"eST.RecommendationbyBoardofCondemn.label","th-Recommendation by Board of Condemn"},
		{"eST.AuthorizedDate.label", "th-Authorized Date"},
		{"eST.POCost.label", "th-PO Cost"},
		{"eST.PODiscount.label", "th-PO Discount"},
		{"eST.SalePrice.label", "th-Sale Price"},
		{"eST.RevisedSalePrice.label", "th-Revised Sale Price"},
		{"eST.SalePriceHistory.label", "th-Sale Price History"},
		{"eST.SalePriceStatusHistory.label", "th-Sale Price Status History"},
		{"eST.ModifiedDate.label", "th-Modified Date"},
		{"eST.Tax.label", "th-Tax"},
		{"eST.ConfirmAmmendedSalePrice.label", "th-Confirm Ammended Sale Price"},
		{"eST.SalePriceOnceAmmendedCanNotBeChanged.label", "th-Sale Price Once Ammended Can Not Be Changed"},
		{"eST.ReturnAllowed.label", "th-Return Allowed"},
		{"eST.nursingunit/clinic.label", "th-Nursing Unit/Clinic"},
		{"eST.InterfacetoexternalPO.label", "th-Interface to external PO"},
		{"eST.PurchaseOrderRequest.label", "th-Purchase Order Request"},
		{"eST.PORequest.label", "th-PO Request"},
		{"eST.PORequestFinalize.label", "th-PORequest Finalize"},
		{"eST.ToDepartment.label", "th-To Department"},
		{"eST.GeneratePORequestBy.label","th-Generate PO Request By"},
		{"eST.PendingForApproval.label","th-Pending For Approval"},
		{"eST.RequestRejectedbyPODept.label","th-Request Rejected by PO Dept"},
		{"eST.RequestReceivedPartially.label","th-Request Received Partially"},

		{"eST.RequestReceivedCompletely.label","th-Request Received Completely"},
		{"eST.RequestCancelled.label","th-Request Cancelled"},
		{"eST.RequestOnDepartment.label","th-Request On Department"},
		{"eST.NewBatchYN.label", "th-New Batch(Yes/No)"}*/

		// labels to be removed soon

		/*{"eST.Applicable.label","ซึ่งเหมาะสม�?ับ�?ารใช้"},
		{"eST.Authorize.label","อนุมัติ"},
		{"eST.Balance.label","สมดุล"},
		{"eST.BatchDetails.label","รายละเอียดBatch"},
		{"eST.CancellationRemarks.label","หมายเหตุ�?ารย�?เลิ�?"},
		{"eST.Cannotbeblank.label","เว้นว่างไม่ได้"},
		{"eST.Chargeable.label","เพิ่มได้"},
		{"eST.Charges.label","เพิ่ม"},
		{"eST.Component.label","ส่วนประ�?อบ"},
		{"eST.ConfirmAuthorize.label","อนุมัติยืนยัน"},
		{"eST.ConfirmCancel.label","ยืนยัน�?ารย�?เลิ�?"},
		{"eST.ConfirmDelete.label","ยืนยัน�?ารลบ"},
		{"eST.ConfirmFinalize.label","ยืนยันข้อสรุป"},
		{"eST.Cost.label","ต้นทุน"},
		{"eST.CountSheetDate.label","วันที่ใน�?ระดาษคำนวณ"},
		{"eST.CounterChecked.label","ตรวจสอบซ้ำ"},
		{"eST.CurrentProcessingMonth/Year.label","เดือน/ปีที่�?ำลังดำเนิน�?าร"},
		{"eST.CurrentYear.label","ปีปัจจุบัน"},
		{"eST.CutOffDate.label","วันที่ตัดออ�?"},
		{"eST.DefaultDocumentTypes.label","ชนิดของเอ�?สารป�?ติที่ตั้งมาจา�?โรงงาน"},
		{"eST.Detail.label","รายละเอียด"},
		{"eST.Discharge.label","จำหน่าย"},
		{"eST.DocDate.label","วันที่ตามเอ�?สาร"},
		{"eST.DocNo.label","เลขเอ�?สาร"},
		{"eST.DocRef.label","อ้างอิงตามเอ�?สาร"},
		{"eST.DocType.label","ชนิดเอ�?สาร"},
		{"eST.DocTypeCode.label","รหัสชนิดเอ�?สาร"},
		{"eST.DocTypeDescription.label","คำอธิบายชนิดเอ�?สาร"},
		{"eST.Document.label","เอ�?สาร"},
		{"eST.Drug.label","ยา"},
		{"eST.DrugCode.label","รหัสยา"},
		{"eST.EffectiveDate.label","วันที่มีผลใช้"},
		{"eST.EntryCompleted.label","�?ารลงทะเบียนสมบูรณ์"},
		{"eST.Expired.label","หมดอายุ"},
		{"eST.Expiry.label","�?ารหมดอายุ"},
		{"eST.FacilityName.label","ชื่อสถานบริ�?าร"},
		{"eST.Finalize.label","หาข้อสรุป"},
		{"eST.Finalized.label","ข้อสรุป"},
		{"eST.FromStore.label","จา�?ห้องยา"},
		{"eST.FullyIssued.label","ปล่อยออ�?เต็มที่"},
		{"eST.GeneralLedger.label","บั�?ชี�?ย�?ประเภททั่วไป"},
		{"eST.Insurance.label","�?ารประ�?ันภัย"},
		{"eST.Issue.label","จ่ายออ�?"},
		{"eST.IssueQuantity.label","ปริมาณที่จ่ายออ�?"},
		{"eST.IssueRemarks.label","หมายเหตุ�?ารจ่ายออ�?"},
		{"eST.IssueStore.label","ห้องจ่ายยา"},
		{"eST.ItemClassDescription.label","คำอธิบายประเภทราย�?าร"},
		{"eST.ItemName.label","ชื่อราย�?าร"},
		{"eST.LabelType.label","ชนิดของป้าย"},
		{"eST.LastIssueDate.label","วันที่ออ�?ล่าสุด"},
		{"eST.MachineName.label","ชื่อเครื่องจั�?ร"},
		{"eST.Mandatory.label","บังคับ"},
		{"eST.ManufacturerID.label","เลขประจำตัวผู้ผลิต"},
		{"eST.MedicalItem.label","ราย�?ารยา"},
		{"eST.Minimum.label","น้อยที่สุด"},
		{"eST.Modify.label","�?�?้ไข"},
		{"eST.Month/Year.label","เดือน/ปี"},
		{"eST.NotCompleted.label","ไม่สมบูรณ์"},
		{"eST.NotIssued.label","ไม่ถู�?จ่ายออ�?"},
		{"eST.OpeningBalance.label","สมดุลเปิด"},
		{"eST.OtherDefaults.label","สิ่งป�?ติอื่น ๆ ที่ตั้งมาจา�?โรงงาน"},
		{"eST.OutPatient.label","ผู้ป่วยนอ�?"},
		{"eST.PackSize.label","ขนาดบรรจุห่อ"},
		{"eST.PackedBy.label","บรรจุห่อโดย"},
		{"eST.PartiallyIssued.label","จ่ายออ�?บางส่วน"},
		{"eST.Pending.label","�?ารจ่าย"},
		{"eST.PendingQty.label","ปริมาณ�?ารจ่าย"},
		{"eST.PrepareLocation.label","สถานที่เตรียม"},
		{"eST.Preview.label","�?สดง�?่อน"},
		{"eST.printworksheet.label","พิมพ์�?ผ่นงาน"},
		{"eST.Profile.label","โครงร่าง"},
		{"eST.PurchaseUOM.label","หน่วยวัด�?ารซื้อ"},
		{"eST.QTY.label","ปริมาณ"},
		{"eST.Quantity.label","ปริมาณ"},
		{"eST.QueryCriteria.label","เ�?ณฑ์�?ารถาม"},
		{"eST.Range.label","ช่วง"},
		{"eST.ReceiptDate.label","วันที่รับ"},
		{"eST.ReplacementStatus.label","สถานะ�?ารทด�?ทน"},
		{"eST.ReportOption.label","รายงานทางเลือ�?"},
		{"eST.ReportOrder.label","รายงาน�?ารสั่ง"},
		{"eST.ReqByStore.label","ขอโดยห้องยา"},
		{"eST.ReqOnStore.label","ขอที่ห้องยา"},
		{"eST.ReqQuantity.label","ปริมาณ�?ารขอ"},
		{"eST.RequisitionbyStore.label","�?ารเบิ�?โดยห้องยา"},
		{"eST.RequisitiononStore.label","�?ารเบิ�?ที่ห้องยา"},
		{"eST.ReturnFromStore.label","คืนจา�?ห้องยา"},
		{"eST.ReturnQty.label","ปริมาณ�?ารคืน"},
		{"eST.SaleQuantity.label","ปริมาณ�?ารขาย"},
		{"eST.Selection.label","�?ารเลือ�?"},
		{"eST.Slot.label","ช่องเวลา"},
		{"eST.SoleSource.label","�?หล่งขาย"},
		{"eST.SpecialItem.label","ราย�?ารที่เฉพาะเจาะจง"},
		{"eST.SterileType.label","ชนิดของปราศจา�?เชื้อ"},
		{"eST.Stock.label","สต๊อ�?"},
		{"eST.StockUOM.label","หน่วย�?ารวัดสต๊อ�?"},
		{"eST.StoreDescription.label","คำอธิบายห้องยา"},
		{"eST.StoreType.label","ชนิดห้องยา"},
		{"eST.Suspended.label","ถู�?ระงับ�?ารจ่าย"},
		{"eST.TimeTaken.label","ใช้เวลา"},
		{"eST.ToStore.label","ไปห้องยา"},
		{"eST.Top.label","ยอด"},
		{"eST.Trade.label","�?ารค้า"},
		{"eST.Transaction.label","�?ารดำเนิน�?าร"},
		{"eST.TransactionDate.label","วันที่ดำเนินงาน"},
		{"eST.TransferFrom.label","โอนย้ายจา�?"},
		{"eST.TRNTypeDescription.label","คำอธิบายชนิดของ TRN"},
		{"eST.Unfinalized.label","หาข้อสรุปไม่ได้"},
		{"eST.UserAccessforStoreListing.label","ผู้ใช้เข้าถึงราย�?ารคงคลัง"},
		{"eST.Value.label","คุณค่า"},
		{"eST.Variance.label","ความ�?ปรเปลี่ยน"},
		{"eST.WorkStation.label","ที่ทำงาน"},*/
	};
}
