/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eOA.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eOA.AllResources.label","所有资�?"},
		{"eOA.AppointmentCriteria.label","预约规则"},
		{"eOA.AppointmentExists.label","预约存在"},
		{"eOA.AppointmentSlipRemarks.label","预约间"},
		{"eOA.ApptDateFrom.label","预约日期"},
		{"eOA.ApptDateTo.label","预约日期"},
		{"eOA.ApptEndTime.label","预约结�?�时间"},
		{"eOA.ApptGivenBy.label","给予预约"},
		{"eOA.ApptGivenOn.label","给予预约"},
		{"eOA.ApptStartTime.label","预约开始时间"},
		{"eOA.ArrivalDate.label","抵达日期"},
//		{"eOA.BlockDate.label","Block Date"},
//		{"eOA.BlockExists.label","Block Exists"},
//		{"eOA.BlockFromTime.label","Block From Time"},
//		{"eOA.BlockReason.label","Block Reason"},
//		{"eOA.BlockSlots.label","Block Slots"},
//		{"eOA.blocksums.label","Sum of BLOCK SLOTS and SLOTS TO BE BLOCKED must match"},
//		{"eOA.BlockTime.label","Block Time"},
//		{"eOA.BlockToTime.label","Block To Time"},
		{"eOA.BookAppointmentfor.label","预订预约"},
		{"eOA.Break.label","打断"},
		{"eOA.BreakTime.label","休�?�时间"},
		{"eOA.CancelAppointmentfor.label","�?�消预约"},
		{"eOA.CancelTransferAppointment.label","�?�消/转让任命"},
		{"eOA.Cannotgobeyondsystemdate.label","�?能超越系统日期"},
		{"eOA.ConfirmAppointment.label","确认预约"},
		{"eOA.ControlBy.label","控制"},
		{"eOA.CreateAppointmentWaitList.label","建立预约等待列表"},
//		{"eOA.CS.label","CS"},
		{"eOA.CurrentAppointmentDetails.label","当时预约明细"},
		{"eOA.CurrentDay.label","当日"},
		{"eOA.CurrentDayStatus.label","当日状�?"},
//		{"eOA.Cutoffelapsedwaitlist.label","Cutoff elapsed waitlist"},
//		{"eOA.CutoffperiodforClosingElapsedWaitlist.label","Cutoff period for Closing Elapsed Waitlist"},
//		{"eOA.DayCode.label","Day Code"},
//		{"eOA.DaysOldWillBeClosed.label","Days old will be closed"},
//		{"eOA.DayTimeDetails.label","Day/Time Details"},
//		{"eOA.dayto.label","To Day"},
//		{"eOA.DisplayEarliestSch.label","Display Earliest Schedule"},
//		{"eOA.ExactNoofVisits.label","Exact No of Visits"},
//		{"eOA.ExamDesc.label","Exam Desc"},
//		{"eOA.ExistingHoliday.label","Existing Holiday"},
//		{"eOA.FI.label","FI"},
		{"eOA.Followup.label","�?�续"},
		{"eOA.Forced.label","强制"},
		{"eOA.ForcedAppointment.label","强制预约"},
		{"eOA.ForcedBooking.label","强制预订"},
		{"eOA.ForcedinBookingsallowed.label","强制�?许预订"},
		{"eOA.FreeFormatDetails.label","自由格�?细节"},
//		{"eOA.FromDay.label","From Day"},
//		{"eOA.FU.label","FU"},
		{"eOA.Global.label","全�?�"},
//		{"eOA.Graceelapsedwaitlist.label","Grace elapsed waitlist"},
//		{"eOA.GraceperiodtoConfirmElapsedWaitlist.label","Grace period to Confirm Elapsed Waitlist"},
		{"eOA.GroupByLocation.label","集团的�?置"},
//		{"eOA.Highlightpatientsifnotinvitedwithin.label","Highlight patients if not invited within"},
		{"eOA.HolidayDay.label","�?�日"},
//		{"eOA.HolidayForNewLocation.label","Holiday For New Location"},
		{"eOA.Increased.label","增加"},
		{"eOA.InvitationApplicable.label","邀请适用"},
		{"eOA.InvitationDate.label","邀请日期"},
		{"eOA.InvitationStatus.label","邀请状�?"},
		{"eOA.invited.label","邀请"},
		{"eOA.InvitedDate.label","邀请日期"},
		{"eOA.Letter.label","信"},
		{"eOA.LiftBlock.label","电梯座"},
		{"eOA.ListofAppointmentsfor.label","预约�??�?�"},
//		{"eOA.LocationResourceDetails.label","Location / Resource Details"},
//		{"eOA.LocnLevel.label","Location Level"},
		{"eOA.maxfirstvisits.label","最大首次就诊�?�"},
		{"eOA.MaximumOverBookings.label","超过预订的最大数�?"},
		{"eOA.MaxNoofVisits.label","最大就诊�?�"},
		{"eOA.maxob.label","超过预订的最大就诊�?�"},
		{"eOA.MaxOtherVisits.label","其它就诊的最大�?�"},
		{"eOA.MaxPatients.label","最大病人数"},
		{"eOA.maxpatperday.label","�?天最大病人数"},
		{"eOA.maxpatperslab.label","�?个间隔最大病人数"},
//		{"eOA.MaxRecurringDays.label","Max Recurring Days"},
		{"eOA.maxslotsperday.label","�?天最多的间隔"},
		{"eOA.ModifiedOn.label","修改"},
		{"eOA.NoOfAppts.label","预约�?�"},
		{"eOA.nooffirstvisits.label","首次就诊�?�"},
		{"eOA.NoOfForcedAppointment.label","强制预约�?�"},
		{"eOA.NoofForcedinBookingday.label","�?天强制预约�?�"},
//		{"eOA.noofglobalbooking.label","No of Global booking for Referral / day"},
		{"eOA.noofothervisits.label","其它预约�?�"},
//		{"eOA.NoofSlots.label","No of Slots"},
		{"eOA.NormalTransfer.label","正常转�?�"},
		{"eOA.NoSchedule.label","时间表"},
//		{"eOA.OB.label","OB"},
		{"eOA.OtherAppointment.label","其它预约"},
		{"eOA.OtherAppointments.label","其它预约"},
		{"eOA.OtherNo.label","其它�?��?"},
		{"eOA.overbooking.label","超过"},
		{"eOA.OverbookingsAvailable.label","�?�?许超过预订"},
//		{"eOA.OverridingNoofSlots.label","Overriding No of Slots"},
//		{"eOA.PendingOrderSchedule.label","Pending Order Schedule"},
//		{"eOA.PrimaryResource.label","Primary Resource"},
		{"eOA.PrintConfirm.label","打�?�确认"},
		{"eOA.RadiologyBookings.label","预订放射"},
//		{"eOA.ReasonForBlock.label","Reason For Block"},
//		{"eOA.ReasonforForceClosing.label","Reason for Force Closing"},
		{"eOA.ReasonforModification.label","修改原因"},
		{"eOA.ReasonForModify.label","修改原因"},
//		{"eOA.RecurringDays.label","Recurring Days"},
//		{"eOA.RecurringDaysSchedule.label","Recurring Days Schedule"},
//		{"eOA.RecurringType.label","Recurring Type"},
//		{"eOA.ReportBody.label","Report Body"},
//		{"eOA.RescheduleAppointment.label","Reschedule Appointment"},
//		{"eOA.ResetBlockTime.label","Reset Block Time"},
//		{"eOA.ResourceDetail.label","Resource Detail"},
//		{"eOA.RestrictonlyoneWaitlistforaPatientagainstCategoryandSpecialty.label","Restrict only one Waitlist for a Patient against Category and Specialty"},
//		{"eOA.Roster.label","Roster"},
//		{"eOA.RosterDays.label","Roster Days"},
//		{"eOA.RosterRequired.label","Roster Required"},
		{"eOA.Salutation.label","称呼"},
//		{"eOA.ScheduleBreakExists.label","Schedule Break Exists"},
		{"eOA.ScheduleCriteria.label","附表标准"},
		{"eOA.SearchWith.label","�?�索"},
		{"eOA.SecondaryBookingForRecurring.label","二次�?�?预订"},
		{"eOA.SecondaryResources.label","�?生资�?"},
		{"eOA.SelectedLocation.label","选�?�的�?置"},
		{"eOA.SelectedResource.label","所选资�?"},
		{"eOA.SelectedTimeDuration.label","选定的时间"},
		{"eOA.SelectReport.label","选择报告"},
//		{"eOA.ShowSchAfter.label","Show Sch After"},
//		{"eOA.slab.label","Slab"},
//		{"eOA.SlabDetails.label","Slab Details"},
//		{"eOA.SlotDetails.label","Slot Details"},
//		{"eOA.SlotsBasedAppointmentsParameters.label","Slots Based Appointments Parameters"},
//		{"eOA.SlotsBlocked.label","Slots Blocked"},
//		{"eOA.Slotstobeblocked.label","Slots to be Blocked"},
		{"eOA.SpecialistMedicalOfficer.label","专家�?医务人员"},
//		{"eOA.SR.label","SR"},
//		{"eOA.StatisticsMonth.label","Statistics Month"},
//		{"eOA.Thanks.label","Thanks"},
		{"eOA.TimeDuration.label","�?续时间"},
		{"eOA.TimeperPatient.label","�?个病人所用时间"},
		{"eOA.timeperslab.label","间隔时间"},
		{"eOA.TimeperSlot.label","间隔时间"},
		{"eOA.TimeTableAvailableDays.label","工作日时间表"},
		{"eOA.TimeTableType.label","时间表型"},
		{"eOA.TotalBookedPatients.label","预约病人总计"},
		{"eOA.TotalInvited.label","就诊病人总计"},
		{"eOA.TotalInvitedForCurrentMonth.label","当月就诊病人总计"},
		{"eOA.TotalWaitListed.label","总的等候列表"},
		{"eOA.TransferAppointmentfor.label","转�?�预约"},
		{"eOA.TransferDay.label","转�?�天"},
		{"eOA.TransferingAppointmentDetails.label","转�?�预约明细"},
		{"eOA.visitallocationdtls.label","就诊�?许明细"},
		{"eOA.VisitLimitRule.label","就诊�?制规则"},
		{"eOA.VisitOverBookingDetails.label","就诊/超过预订明细"},
		{"eOA.WaitinglistThatAreLapsedAnd.label","等候时间已过"},
		{"eOA.WaitListApptDetails.label","等候预约列表明细"},
		{"eOA.WaitlistCategory.label","等候类型"},
		{"eOA.WaitlistCategoryApplicable.label","适用等候列表类型"},
		{"eOA.WaitlistCategoryCode.label","等候列表类型代�?"},
		{"eOA.WaitlistCategoryDescription.label","等候列表�??述"},
		{"eOA.WaitlistCategoryRequired.label","�?求等候的列表"},
		{"eOA.WaitListnumber.label","等候列表数�?"},
		{"eOA.WithoutPatientNumbers.label","无病人数目"},
		{"eOA.WithPatientNumbers.label","病人数目"},
		{"eOA.AcceptDate.label","接收日期"},
		{"eOA.Scheduleisnotdefined.label","未定义进度表"},
		{"eOA.Notidentified.label","未确定"},
		{"eOA.VisitRegistered.label","就诊注册"},
		{"eOA.PleaseComeInTime.label","请按时到"},
		{"eOA.Incaseofabnormalsignspatientcancomebeforeappointdate.label","预约日期�?指定异常病人"},
		{"eOA.DoctorAppointBy.label","预约医生"},
//		{"eOA.PleaseBringSlip.label","Please bring this slip"},
//		{"eOA.BulkTransfer.label","Bulk Transfer"},
		{"eOA.captfinancedetailsgapptbooking.label","预约期间�?�获财务明细"},
//		{"eOA.ReasonForCreateWaitlist.label","Reason For Create Waitlist"},
//		{"eOA.FV.label","FV"},
//		{"eOA.OV.label","OV"},
		{"eOA.ApptRefNo.label","预约�?�照�?�"},
		{"eOA.DateofRecordAppt.label","记录预约日期"},
//		{"eOA.ApptSection.label","Appt. Section"},
		{"eOA.SecondaryResourceName.label","二次资�?�??称"},
		{"eOA.ModifyAppointment.label","修改预约"},
		{"eOA.IncludePastAppts.label","包括过期预约"},
		{"eOA.Pendingreferral.label","待定推介"},
		{"eOA.Lastmodifiedon.label","最�?�修改日期"},
		{"eOA.BulkTransferDateTime.label","�?�转�?�日期。时间"},
		{"eOA.ReasonforBulkTransfer.label","�?�转�?�原因"},
		{"eOA.Minperiodforschnoshowappt.label","未显示排�?�表的最�?时间"},
		{"eOA.BySpecialty.label","科室"},
		{"eOA.Displayunidenpract.label","�?�显示未识别的医生"},
		{"eOA.Viewaudittrial.label","View Audit Trial"},
		{"eOA.captcontactdetailsgapptbooking.label","预约时�?求留下�?�系�?��?"},
		{"eOA.Numofnoshowappointments.label","显示�??示预约的�?��?"},
		{"eOA.Noshowapptcontrol.label","未显示预约控制"},
		{"eOA.Periodchklast.label","检查期间未出院预约�??示"},
		{"eOA.NoShowappt.label","未显示预约"},
		{"eOA.RecallReminderApplicable.label","记得/�??醒适用"},
		{"eOA.EmailApplicable.label","电�?邮件适用"},
		{"eOA.SendRemiForAppointment.label","预约�?�?��?�??示"},
		{"eOA.EmailAppliForAppointmentwithoutPatientid.label","邮件�??示无门诊编�?�的预约"},
//Newly Added Legends on 21/01/09
		{"eOA.ApptSection.label","预约科"},
{"eOA.BlockDate.label","�?定"},
{"eOA.BlockExists.label","已存在的�?定"},
{"eOA.BlockFromTime.label","�?定开始"},
{"eOA.BlockReason.label","预约�?定原因"},
{"eOA.BlockSlots.label","Block Slots"},
{"eOA.blocksums.label","Sum of BLOCK SLOTS and SLOTS TO BE BLOCKED must match"},
{"eOA.BlockTime.label","�?定时间"},
{"eOA.BlockToTime.label","�?定结�?�时间"},
{"eOA.BulkTransfer.label","转让批预约"},
{"eOA.CS.label","CS"},
{"eOA.Cutoffelapsedwaitlist.label","等候�??�?�截止时间"},
{"eOA.CutoffperiodforClosingElapsedWaitlist.label","关闭等待�??�?�截止时间"},
{"eOA.DayCode.label","日代�?"},
{"eOA.DaysOldWillBeClosed.label","Days old will be closed"},
{"eOA.DayTimeDetails.label","日期/时间表明细"},
{"eOA.dayto.label","最近的时间表"},
{"eOA.DisplayEarliestSch.label","显示最近预订表"},
{"eOA.ExactNoofVisits.label","正确的访问次数"},
{"eOA.ExamDesc.label","测试说明"},
{"eOA.ExistingHoliday.label","已存在的�?�期"},
{"eOA.FI.label","FI"},
{"eOA.FromDay.label","开始日期"},
{"eOA.FU.label","�?诊"},
{"eOA.FV.label","�?诊"},
{"eOA.Graceelapsedwaitlist.label","Grace elapsed waitlist"},
{"eOA.GraceperiodtoConfirmElapsedWaitlist.label","Grace period to Confirm Elapsed Waitlist"},
{"eOA.Highlightpatientsifnotinvitedwithin.label","病人在就诊列表中未列出,高亮显示病人"},
{"eOA.HolidayForNewLocation.label","新�?置�?�期列表"},
{"eOA.LocationResourceDetails.label","�?置/资�?明细"},
{"eOA.LocnLevel.label","水平�?置？"},
{"eOA.MaxRecurringDays.label","最大周期"},
{"eOA.noofglobalbooking.label","转诊预订�?�"},
{"eOA.NoofSlots.label","医生就诊间隔"},
{"eOA.OB.label","在预订"},
{"eOA.OV.label","其他就诊"},
{"eOA.OverridingNoofSlots.label","Overriding No of Slots"},
{"eOA.PendingOrderSchedule.label","待执行时间表"},
{"eOA.PleaseBringSlip.label","使滑动"},
{"eOA.PrimaryResource.label","首�?资�?"},
{"eOA.ReasonForBlock.label","阻止预约的原因"},
{"eOA.ReasonForCreateWaitlist.label","建立等待�??�?�的原因"},
{"eOA.ReasonforForceClosing.label","强行关闭预认的�?�由"},
{"eOA.RecurringDays.label","周期"},
{"eOA.RecurringDaysSchedule.label","周期表"},
{"eOA.RecurringType.label","周期类型"},
{"eOA.ReportBody.label","报告正文"},
{"eOA.RescheduleAppointment.label","�?新预约"},
{"eOA.ResetBlockTime.label","�?置�?�?时间"},
{"eOA.ResourceDetail.label","详细资�?"},
{"eOA.RestrictonlyoneWaitlistforaPatientagainstCategoryandSpecialty.label","�?制�?�用一个等待列表"},
{"eOA.Roster.label","�??�?�"},
{"eOA.RosterDays.label","排�?�表"},
{"eOA.RosterRequired.label","�??�?��?求"},
{"eOA.ScheduleBreakExists.label","Schedule Break Exists"},
{"eOA.ShowSchAfter.label","Show Sch After"},
{"eOA.slab.label","Slab"},
{"eOA.SlabDetails.label","Slab Details"},
{"eOA.SlotDetails.label","Slot Details"},
{"eOA.SlotsBasedAppointmentsParameters.label","Slots Based Appointments Parameters"},
{"eOA.SlotsBlocked.label","Slots Blocked"},
{"eOA.Slotstobeblocked.label","Slots to be Blocked"},
{"eOA.SR.label","SR"},
{"eOA.StatisticsMonth.label","月统计"},
{"eOA.Thanks.label","感谢"},
{"eOA.Viewaudittrial.label","查看历�?�事件"},



	};
}
