/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eOA.resources;

import java.util.*;

public class  Labels  extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }
	static final Object[][] contents = {
			{"eOA.AllResources.label","All Resources"},
			{"eOA.AppointmentCriteria.label","Appointment Criteria"},
			{"eOA.AppointmentExists.label","Appointment Exists"},
			{"eOA.AppointmentSlipRemarks.label","Appointment Slip Remarks"},
			{"eOA.ApptDateFrom.label","Appt Date From"},
			{"eOA.ApptDateTo.label","Appt Date To"},
			{"eOA.ApptEndTime.label","Appt End Time"},
			{"eOA.ApptGivenBy.label","Appt Given By"},
			{"eOA.ApptGivenOn.label","Appt Given On"},
			{"eOA.ApptStartTime.label","Appt Start Time"},
			{"eOA.ArrivalDate.label","Arrival Date"},
			{"eOA.BlockDate.label","Block Date"},
			{"eOA.BlockExists.label","Block Exists"},
			{"eOA.BlockFromTime.label","Block From Time"},
			{"eOA.BlockReason.label","Block Reason"},
			{"eOA.BlockSlots.label","Block Slots"},
			{"eOA.blocksums.label","Sum of BLOCK SLOTS and SLOTS TO BE BLOCKED must match"},
			{"eOA.BlockTime.label","Block Time"},
			{"eOA.BlockToTime.label","Block To Time"},
			{"eOA.BookAppointmentfor.label","Book Appointment for"},
			{"eOA.Break.label","Break"},
			{"eOA.BreakTime.label","Break Time"},
			{"eOA.CancelAppointmentfor.label","Cancel Appointment for"},
			{"eOA.CancelTransferAppointment.label","Cancel/Transfer Appointment"},
			{"eOA.Cannotgobeyondsystemdate.label","Cannot  go beyond system date"},
			{"eOA.ConfirmAppointment.label","Confirm Appointment"},
			{"eOA.ControlBy.label","Control By"},
			{"eOA.CreateAppointmentWaitList.label","Create Appointment Wait List"},
			{"eOA.CS.label","CS"},
			{"eOA.CurrentAppointmentDetails.label","Current Appointment Details"},
			{"eOA.CurrentDay.label","Current Day"},
			{"eOA.CurrentDayStatus.label","Current Day Status"},
			{"eOA.Cutoffelapsedwaitlist.label","Cutoff elapsed waitlist"},
			{"eOA.CutoffperiodforClosingElapsedWaitlist.label","Cutoff period for Closing Elapsed Waitlist"},
			{"eOA.DayCode.label","Day Code"},
			{"eOA.DaysOldWillBeClosed.label","Days old will be closed"},
			{"eOA.DayTimeDetails.label","Day/Time Details"},
			{"eOA.dayto.label","To Day"},
			{"eOA.DisplayEarliestSch.label","Display Earliest Schedule"},
			{"eOA.ExactNoofVisits.label","Exact No of Visits"},
			{"eOA.ExamDesc.label","Exam Desc"},
			{"eOA.ExistingHoliday.label","Existing Holiday"},
			{"eOA.FI.label","FI"},
			{"eOA.Followup.label","Follow up"},
			{"eOA.Forced.label","Forced"},
			{"eOA.ForcedAppointment.label","Forced Appointment"},
			{"eOA.ForcedBooking.label","Forced Booking"},
			{"eOA.ForcedinBookingsallowed.label","Forced in Bookings allowed"},
			{"eOA.FreeFormatDetails.label","Free Format Details"},
			{"eOA.FromDay.label","From Day"},
			{"eOA.FU.label","FU"},
			{"eOA.Global.label","Global"},
			{"eOA.Graceelapsedwaitlist.label","Grace elapsed waitlist"},
			{"eOA.GraceperiodtoConfirmElapsedWaitlist.label","Grace period to Confirm Elapsed Waitlist"},
			{"eOA.GroupByLocation.label","Group By Location"},
			{"eOA.Highlightpatientsifnotinvitedwithin.label","Highlight patients if not invited within"},
			{"eOA.HolidayDay.label","Holiday Day"},
			{"eOA.HolidayForNewLocation.label","Holiday For New Location"},
			{"eOA.Increased.label","Increased"},
			{"eOA.InvitationApplicable.label","Invitation Applicable"},
			{"eOA.InvitationDate.label","Invitation Date"},
			{"eOA.InvitationStatus.label","Invitation Status"},
			{"eOA.invited.label","Invited"},
			{"eOA.InvitedDate.label","Invited Date"},
			{"eOA.Letter.label","Letter"},
			{"eOA.LiftBlock.label","Lift Block"},
			{"eOA.ListofAppointmentsfor.label","List of Appointments for"},
			{"eOA.LocationResourceDetails.label","Location / Resource Details"},
			{"eOA.LocnLevel.label","Location Level"},
			{"eOA.maxfirstvisits.label","Max First Visits"},
			{"eOA.MaximumOverBookings.label","Maximum Over Bookings"},
			{"eOA.MaxNoofVisits.label","Max No of Visits"},
			{"eOA.maxob.label","Max Over Bookings"},
			{"eOA.MaxOtherVisits.label","Max Other Visits"},
			{"eOA.MaxPatients.label","Max Patients"},
			{"eOA.maxpatperday.label","Max Patients per Day"},
			{"eOA.maxpatperslab.label","Max Patients per Slab"},
			{"eOA.MaxRecurringDays.label","Max Recurring Days"},
			{"eOA.maxslotsperday.label","Max Slots per Day"},
			{"eOA.ModifiedOn.label","Modified On"},
			{"eOA.NoOfAppts.label","No of Appts"},
			{"eOA.nooffirstvisits.label","No of First Visits"},
			{"eOA.NoOfForcedAppointment.label","No of Forced Appointment"},
			{"eOA.NoofForcedinBookingday.label","No of Forced in Booking / day"},
			{"eOA.noofglobalbooking.label","No of Global booking for Referral / day"},
			{"eOA.noofothervisits.label","No of Other Visits"},
			{"eOA.NoofSlots.label","No of Slots"},
			{"eOA.NormalReschedule.label","Normal Reschedule"}, //Line modified ML-MMOH-CRF-0609 by Mano
			{"eOA.NoSchedule.label","No Schedule"},
			{"eOA.OB.label","OB"},
			{"eOA.OtherAppointment.label","Other Appointment"},
			{"eOA.OtherAppointments.label","Other Appointments"},
			{"eOA.OtherNo.label","Other Number"},
			{"eOA.overbooking.label","Overbooking"},
			{"eOA.OverbookingsAvailable.label","Overbookings Available"},
			{"eOA.OverridingNoofSlots.label","Overriding No of Slots"},
			{"eOA.PendingOrderSchedule.label","Pending Order Schedule"},
			{"eOA.PrimaryResource.label","Primary Resource"},
			{"eOA.PrintConfirm.label","Print Confirm"},
		    {"eOA.PrintAllSlip.label","Print All"},
			{"eOA.OverlapDetails.label","Overlap Details"},
			{"eOA.noofpatsappts.label","No. of Patients with Appt."},
			{"eOA.RadiologyBookings.label","Radiology Bookings"},
			{"eOA.ReasonForBlock.label","Reason For Block"},
			{"eOA.ReasonforForceClosing.label","Reason for Force Closing"},
			{"eOA.ReasonforModification.label","Reason for Modification"},
			{"eOA.ReasonForModify.label","Reason For Modify"},
			{"eOA.RecurringDays.label","Recurring Days"},
			{"eOA.RecurringDaysSchedule.label","Recurring Days Schedule"},
			{"eOA.RecurringType.label","Recurring Type"},
			{"eOA.ReportBody.label","Report Body"},
			{"eOA.RescheduleAppointment.label","Reschedule Appointment"},
			{"eOA.ResetBlockTime.label","Reset Block Time"},
			{"eOA.ResourceDetail.label","Resource Detail"},
			{"eOA.RestrictonlyoneWaitlistforaPatientagainstCategoryandSpecialty.label","Restrict only one Waitlist for a Patient against Category and Specialty"},
			{"eOA.Roster.label","Roster"},
			{"eOA.RosterDays.label","Roster Days"},
			{"eOA.RosterRequired.label","Roster Required"},
			{"eOA.Salutation.label","Salutation"},
			{"eOA.ScheduleBreakExists.label","Schedule Break Exists"},
			{"eOA.ScheduleCriteria.label","Schedule Criteria"},
			{"eOA.SearchWith.label","Search With"},
			{"eOA.SecondaryBookingForRecurring.label","Secondary Booking For Recurring "},
			{"eOA.SecondaryResources.label","Secondary Resources"},
			{"eOA.SelectedLocation.label","Selected Location"},
			{"eOA.SelectedResource.label","Selected Resource"},
			{"eOA.SelectedTimeDuration.label","Selected Time Duration"},
			{"eOA.SelectReport.label","Select Report"},
			{"eOA.ShowSchAfter.label","Show Sch After"},
			{"eOA.slab.label","Slab"},
			{"eOA.SlabDetails.label","Slab Details"},
			{"eOA.SlotDetails.label","Slot Details"},
			{"eOA.SlotsBasedAppointmentsParameters.label","Slots Based Appointments Parameters"},
			{"eOA.SlotsBlocked.label","Slots Blocked"},
			{"eOA.Slotstobeblocked.label","Slots to be Blocked"},
			{"eOA.SpecialistMedicalOfficer.label","Specialist/Medical Officer"},
			{"eOA.SR.label","SR"},
			{"eOA.StatisticsMonth.label","Statistics Month"},
			{"eOA.Thanks.label","Thanks"},
			{"eOA.TimeDuration.label","Time Duration"},
			{"eOA.TimeperPatient.label","Time per Patient"},
			{"eOA.timeperslab.label","Time per Slab"},
			{"eOA.TimeperSlot.label","Time per Slot"},
			{"eOA.TimeTableAvailableDays.label","Time Table Available Days"},
			{"eOA.TimeTableType.label","Time Table Type"},
			{"eOA.TotalBookedPatients.label","Total Booked Patients"},
			{"eOA.TotalInvited.label","Total Invited"},
			{"eOA.TotalInvitedForCurrentMonth.label","Total Invited for Current Month"},
			{"eOA.TotalWaitListed.label","Total WaitListed"},
			{"eOA.RescheduleAppointmentfor.label","Reschedule Appointment for"},
			{"eOA.TransferDay.label","Transfer Day"},
			{"eOA.TransferingAppointmentDetails.label","Transfering Appointment Details"},
			{"eOA.visitallocationdtls.label","Visit Allocation Details"},
			{"eOA.VisitLimitRule.label","Visit Limit Rule"},
			{"eOA.VisitOverBookingDetails.label","Visit / Over Booking Details"},
			{"eOA.WaitinglistThatAreLapsedAnd.label","Waiting lists that are elapsed and"},
			{"eOA.WaitListApptDetails.label","Wait List Appt Details"},
			{"eOA.WaitlistCategory.label","Waitlist Category"},
			{"eOA.WaitlistCategoryApplicable.label","Waitlist Category Applicable"},
			{"eOA.WaitlistCategoryCode.label","Waitlist Category Code"},
			{"eOA.WaitlistCategoryDescription.label","Waitlist Category Description"},
			{"eOA.WaitlistCategoryRequired.label","Waitlist Category Required"},
			{"eOA.WaitListnumber.label","WaitList number"},
			{"eOA.WithoutPatientNumbers.label","Without Patient Numbers"},
			{"eOA.WithPatientNumbers.label","With Patient Numbers"},
			{"eOA.AcceptDate.label","Accept Date"},
			{"eOA.Scheduleisnotdefined.label","Schedule is not defined"},
			{"eOA.Notidentified.label","Not Identified"},
     		{"eOA.VisitRegistered.label","Visit Registered"},
			{"eOA.PleaseComeInTime.label","Please Come In Time"},
     		{"eOA.Incaseofabnormalsignspatientcancomebeforeappointdate.label","Incase of abnormal signs Patient can come before Appoint Date"},
			{"eOA.DoctorAppointBy.label","Doctor Appoint by"} ,
			{"eOA.PleaseBringSlip.label","Please bring this slip"} ,
			{"eOA.BulkReschedule.label","Bulk Reschedule"},  //line modified ML-MMOH-CRF-0609
			{"eOA.captfinancedetailsgapptbooking.label","Capture Financial details during Appointment"},
			{"eOA.ReasonForCreateWaitlist.label","Reason For Create Waitlist"},
			{"eOA.FV.label","FV"},
			{"eOA.OV.label","OV"},
			{"eOA.ApptRefNo.label","Appt.Ref.No."},
			{"eOA.DateofRecordAppt.label","Date of Record Appt."},
			{"eOA.ApptSection.label","Appt. Section"},
			{"eOA.SecondaryResourceName.label","Secondary Resource Name"},
			{"eOA.ModifyAppointment.label","Modify Appointment"},
			{"eOA.IncludePastAppts.label","Include Past Appointments"},
			{"eOA.Pendingreferral.label","Pending Referral"},
			{"eOA.Lastmodifiedon.label","Last Modified On"},
			{"eOA.BulkRescheduleDateTime.label","Bulk Reschedule Date/Time"}, //line modified ML-MMOH-CRF-0609
			{"eOA.ReasonforBulkReschedule.label","Reason for Bulk Reschedule"},//line modified ML-MMOH-CRF-0609
			{"eOA.Minperiodforschnoshowappt.label","Minimum elapsed period for scheduling No show"},
			{"eOA.BySpecialty.label","By Speciality"},
			{"eOA.Displayunidenpract.label","Display only Not-identified Practitioner"},
			{"eOA.Viewaudittrial.label","View Audit Trial"},
			{"eOA.captcontactdetailsgapptbooking.label","Contact Number required during Appointment"},
			{"eOA.Numofnoshowappointments.label","Number of No show Appts For Alert"},
			{"eOA.Noshowapptcontrol.label","No show Appointment Control"},
			{"eOA.Periodchklast.label","Period Check For No Show Appts For Alert"},
			{"eOA.NoShowappt.label","No Show Appts"},
			{"eOA.RecallReminderApplicable.label","Recall/Reminder Applicable"},
			{"eOA.EmailApplicable.label","Email Applicable"},
			{"eOA.SendRemiForAppointment.label","Send reminder for appointment before"},
			{"eOA.EmailAppliForAppointmentwithoutPatientid.label","Email Applicable for Appointment with out patient ID"},
			{"eOA.timeperslotslab.label","Time per Slot/Slab"},
			{"eOA.AlocationCriteria.label","Allocation Criteria"},
			{"eOA.Allocation.label","Allocation"},
			// Reports related Lables added on 20/1/2009
			{"eOA.PID.label","PID"},
			{"eOA.Generated.label","Generated"},
			{"eOA.Affected.label","Affected"},
			{"eOA.Lift.label","Lift"},
			{"eOA.Effected.label","Effected"},
			{"eOA.waitliswebreqtno.label","Wait List/Web Request No"},
			{"eOA.CancelWaitListwebReq.label","Cancel Wait List/Web Request"},
			{"eOA.ForcedbookingsAvailable.label","Forcedbookings Available"},
			{"eOA.noofglobalbookingperday.label","No of Global booking per day"},
			{"eOA.ProcInstructions.label","Procedure Instructions"},
			{"eOA.EditInstructructions.label","Edit Instructions"},
			{"eOA.Pleaseregisteratthecliniccounterby.label","Please register at the clinic counter by"},
			{"eOA.TransactedDate.label","Transacted Date"},
			{"eOA.ClinicalInstructions.label","Clinical Instructions"},
			{"eOA.SpeacialitesSelected.label","Speacialites Selected"},
			{"eOA.RuleBasedScheduling.label","Rule Based Scheduling"},
			{"eOA.scheduleruleapplicable.label","Schedule Rule Applicable"},
			{"eOA.NumberofRescheduledAppointmentforalert.label","Number of Reschedule Appointments for Alert"},
			{"eOA.PeriodCheckforReschApptsAlert.label","Period Check for Rescheduled Appointments for Alert"},
			{"eOA.NumofCancelledApptsforalert.label","Number of Cancelled Appointments for Alert"},
			{"eOA.PeriodCheckforCancelledApptsAlert.label","Period Check for Cancelled Appointments for Alert"},
			{"eOA.NoofTranslators.label","No of Translators"},
			{"eOA.TranslatorsAvble.label","Translators Available"},
			{"eOA.NumOfFutApptsForAlert.label","Number of Future Appointments for Alert"},
			{"eOA.PerChkForFutApptsForAlert.label","Period Check for Future Appointments for Alert"},
			{"eOA.NoofPatperTranslator.label","No of Patients per Translator"},
			{"eOA.MobNumReqDuringAppt.label","Mobile Number Required During Appointment"},
			{"eOA.PatLangReqDuringAppt.label","Patient Language required during Appointment"},
			{"eOA.PractUnSpecified.label","Practitioner UnSpecified"},
			{"eOA.ReasonForOverride.label","Reason For Override"},
			{"eOA.PreferredDateTime.label","Preferred Date & Time"},
			{"eOA.NewPatConsltd.label","New Patients Consulted"},
			{"eOA.NewPatToBeConsltd.label","New Patients to be Consulted"},
			{"eOA.OldPatConsltd.label","Old Patients Consulted"},
			{"eOA.OldPatToBeConsltd.label","Old Patients to be Consulted"},
			{"eOA.RuleDescription.label","Rule Description"},
			{"eOA.NoofWeekstobeconsidrd.label","No of Weeks to be considered"},
			{"eOA.Consider.label","Consider"},
			{"eOA.MaxNewPat.label","Max New Patients"},
			{"eOA.MaxOldPat.label","Max Old Patients"},
			{"eOA.ViewWaitList.label","View WaitList"},
			{"eOA.IntegrateRadApptAppl.label","Integration of Radiology Appointments Applicable"},
			{"eOA.RadAppt.label","Radiology Appointments"},
			{"eOA.RadWaitList.label","Radiology WaitList"},
			{"eOA.ReasonForPatCancelledAppt.label","Patient Cancellation Reason for Alert"},
			{"eOA.MaxCancelledApptForPrompt.label","Max Patient Cancelled Appointments for Alert"},
			{"eOA.GroupId.label","Group ID"},
			{"eOA.AppointmentGroups.label","Appointment Group"},
			{"eOA.GroupAppointmentallowed.label","Allow Group Appointment"},
			{"eOA.AppointmentSlips.label","Appointment Slip"},
			{"eOA.Print.label","Print"},
			{"eOA.OverlapDetails.label","Overlap Details"},
			{"eOA.TotalPatientsLinkedInGroup.label","Total Patients in Group"},
			{"eOA.Grouppatient.label","Patients in Group is less than Minimum Patients defined for the Group."},
			{"eOA.SelectedPatientList.label","Selected Patient List"},
			{"eOA.blkschdlwithapptyn.label","Block Schedule even if Appointments exist"},	
			{"eOA.SynContactDtlsMP.label","Synchronise Contact Details to Master Patient "},//added for HSA-CRF-0226
			{"eOA.ActionOnHolidayForOpenSchedule.label","Action on holidays for open schedules"},//Added By Rameswar on 7th Apr 2015 Against HSA-CRF-0183 [IN:049543] 
			{"eOA.restrict.label","Restrict"},//Added By Rameswar on 7th Apr 2015 Against HSA-CRF-0183 [IN:049543] 
			{"eOA.MAxBookingPerPatientPerDay.label","Maximum Bookings per Patient per Day"},//Added By Dharma on Sep 11th 2015 against portal.
			{"eOA.AdvanceBookinglimits.label","Advance Booking limits"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.AppointmentBookingControls.label","Appointment Booking Controls"},//Added By Dharma on Sep 11th 2015 against portal.
			{"eOA.AlternateIDsToValidateForPatientMapping.label","Alternate IDs to validate for Patient Mapping"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.ScheduleDetail.label","Schedule detail"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.SlotsSlabsAllocated.label","Slots/Slabs allocated"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.DefaultReasons.label","Default Reason(s)"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.ReasonForBookingAppointment.label","Reason for Booking an Appointment"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.ReasonForReschedulingAppointment.label","Reason for Rescheduling an Appointment"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.ReasonForCancellingAppointment.label","Reason for Cancelling an Appointment"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.AllowPatientToChange.label","Allow patient to change"},//Added By Dharma on Sep 11th 2015 against Portal.
			{"eOA.AppointmentThrough.label","Appointment Through"},//Added By Dharma on Feb 8th 2016 against PMG2016-CRF-MMS-0001 [IN:059014].
			{"eOA.Online.label","Online"},//Added By Dharma on Feb 8th 2016 against PMG2016-CRF-MMS-0001 [IN:059014].
			{"eOA.MaxBookingPerPatient.label","Maximum Bookings per Patient"},//Added By Dharma on Mar 7th 2016 against Portal.
			{"eOA.ReScheduleDate/Time.label","Re-Schedule Date/Time"},//Added by Ashwini on 25-May-2017 for ML-MMOH-CRF-0610
			{"eOA.ExternalAppointmentsOnly.label","External Appointments Only"},
			{"eOA.AppointmentSource.label","Appointment Source"},
			{"eOA.Practo.label","Practo"},
			//Added by Ashwini on 21-Jul-2021 for NMC-JD-CRF-0112
			{"eOA.ScheduleExtend.label","Schedule Extend"},
			{"eOA.ExtendTillDayEnd.label","Extend till Day End"},
			//Added by Ashwini on 11-Aug-2021 for ML-BRU-CRF-0628.1
			{"eOA.AllSlots.label","All Slots"},
			{"eOA.BruHealthSlot.label","BruHealth Slot"},
			{"eOA.BruHealth.label","BruHealth"}

		};
}
