package eIP.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }
	static final Object[][] contents = {
{"eIP.AbortCancel.label","إيقاف إلغاء"},
{"eIP.AbortCancellation.label","إيقاف الإلغاء"},
{"eIP.AbortDischarge.label","إلغاء الخروج"},
{"eIP.AbortRevision.label","إيقاف مراجعة"},
{"eIP.AbortSwap.label","إيقاف المبادلة"},
{"eIP.Absconded.label","هرب"},
{"eIP.AbscondedDetails.label","تفاصيل هرب "},
{"eIP.AbscondedFrom.label","هرب من"},
{"eIP.AbscondedRemarks.label","ملاحظات الهرب"},
{"eIP.Absconding.label","الهروب"},
{"eIP.AbscondingDate.label","تاريخ الهروب"},
{"eIP.AbscondingDateTime.label","الهروب التاريخ / الوقت"},
{"eIP.AbscondingDetails.label","تفاصيل الهروب"},
{"eIP.Accident.label","حادثة"},
{"eIP.AccompanyingPerson.label","الشخص المرافق"},
{"eIP.AccompanyingPersonDetails.label","بيانات الشخص المرافق"},
{"eIP.AccompanyingPersonID.label","هوية الشخص المرافق"},
{"eIP.AccompanyingPersonName.label","اسم الشخص المرافق"},
{"eIP.AccompanyingPersons.label","المرافقون"},
{"eIP.AcctDeptService.label","قسم / خدمة الحساب"},
{"eIP.ActiononExceedingMaxLeave.label","إجراء تجاوز الحد الأقصى للإجازة"},
{"eIP.ActiveBooking.label","الحجز النشط"},
{"eIP.Activity.label","نشاط"},
{"eIP.ActivityReason.label","سبب النشاط"},
{"eIP.AdditionalDepositAmount.label","قيمة الإيداع الإضافي"},
{"eIP.AdditionalDepositRequired.label","مطلوب إيداع إضافي"},
{"eIP.AdditionalDischargeDetails.label","تفاصيل الخروج الإضافية"},
{"eIP.AdditionalServices.label","خدمات إضافية"},
{"eIP.AdmDateFrom.label","تاريخ التقديم من"},
{"eIP.DischargeReport.label","تقرير الخروج"},
{"eIP.AdmissionReport.label","تقرير الدخول"},
{"eIP.AdmDateTo.label","تاريخ الدخول حتى"},
{"eIP.AdmissionFor.label","الدخول ل"},
{"eIP.AdmissionHistory.label","تاريخ الدخول"},
{"eIP.Admissions.label","الدخول"},
{"eIP.AdmissionTypeCode.label","رمز نوع الدخول"},
{"eIP.AdmissionWithBed.label","الدخول بوجود السرير"},
{"eIP.AdmissionWithoutBed.label","الدخول بدون سرير"},
{"eIP.AdmissionWorkupChargeFee.label","رسوم الدخول"},
{"eIP.AdmissionYear.label","سنة الدخول"},
{"eIP.AdmittedDate.label","تاريخ الدخول"},
{"eIP.Admitting.label","إدخال"},
{"eIP.AdmittingPractitioner.label","طبيب الدخول"},
{"eIP.AdmMonthFrom.label","شهر الدخول من"},
{"eIP.AdviceGivenTo.label","تقديم المشورة ل"},
{"eIP.AdviceonContcare.label","المشورة بشأن الرعاية المستمرة المقدمة للوالد"},
{"eIP.AgeGender.label","العمر / الجنس"},
{"eIP.AgeGroupBedClass.label","الفئة العمرية- فئة السرير"},
{"eIP.AllowablePeriodforIssue.label","الفترة المسموح بها للإصدار"},
{"eIP.AllowBedSwap.label","السماح بتبديل السرير"},
{"eIP.AllowBookingforUnregisteredPatients.label","السماح بالحجز للمرضى غير المسجلين"},
{"eIP.AllowedAdmission.label","الدخول المسموح به"},
{"eIP.AllowedBooking.label","الحجز المسموح به"},
{"eIP.AllowLeaveCancellationWithin.label","السماح بإلغاء الإجازة"},
{"eIP.AllowNewbornRegn.label","السماح بتسجيل حديثي الولادة "},
{"eIP.AllowPatientCheckin.label","السماح بتسجيل وصول المريض"},
{"eIP.AllowPseudoBeds.label","السماح للأسرة المرافقة"},
{"eIP.AllowTransferWOReq.label","السماح بنقل بدون طلب"},
{"eIP.AllSPLTY.label","كل التخصصات"},
{"eIP.AmbulanceReqdDateTime.label","تاريخ / وقت طلب سيارة الإسعاف"},
{"eIP.AmendInpatientLeave.label","تعديل إجازة التنويم"},
{"eIP.AnalDilatation.label","توسع الشرج"},
{"eIP.ApplFixturesDocuments.label","التطبيقات / المستندات"},
{"eIP.assignbedmarkpatientarrival.label","تعيين السرير / تحديد وصول المريض"},
{"eIP.Assisting.label","المساعدة"},
{"eIP.Attendant.label","المصاحبة"},
{"eIP.AuthorizationDateTime.label","تاريخ / وقت التفويض"},
{"eIP.AuthorizedPractitioner.label","طبيب معتمد"},
{"eIP.AutoFileTransfer.label","النقل التلقائي للملفات"},
{"eIP.AvailNursUnit.label","وحدة التمريض المتاحة"},
{"eIP.BabiesBeds.label","سرير اطفال"},
{"eIP.BabyDetails.label","تفاصيل الطفل"},
{"eIP.BabyToMotherDetails.label","تفاصيل الطفل إلى الأم"},
{"eIP.BedAllocationDateTime.label","تاريخ / وقت تخصيص السرير"},
{"eIP.BedAvailabilityChart.label","مخطط توافر السرير"},
{"eIP.BedBlockDetails.label","تفاصيل حجب السرير"},
{"eIP.BedBlocking.label","حجب السرير"},
{"eIP.BedBlockingPeriod.label","فترة حجب السرير"},
{"eIP.BedBlockleduntil.label","سرير محظور حتى"},
{"eIP.BedBookingSerialControl.label","التحكم التسلسلي حجز السرير"},
{"eIP.BedCharge.label","شحن السرير"},
{"eIP.BedClassCode.label","كود فئة السرير"},
{"eIP.BedClassCodeFrom.label","رمز فئة السرير من"},
{"eIP.BedClassification.label","تصنيف السرير"},
{"eIP.BedDetails.label","تفاصيل السرير"},
{"eIP.BedLayoutForFloor.label","تخطيط السرير للأرضية / المقصورة"},
{"eIP.BedOccupancyByNursingUnit.label","إشغال السرير بواسطة وحدة التمريض"},
{"eIP.BedOccupancybySpecialty.label","إشغال السرير حسب التخصص"},
{"eIP.Beds.label","سرير"},
{"eIP.BedsBlocked.label","أسرة محظورة"},
{"eIP.Bedside.label","بجانب السرير"},
{"eIP.BedsideReferralSeenDate.label","تاريخ الإحالة إلى السرير"},
{"eIP.BedsOccupied.label","أسرة مشغولة"},
{"eIP.BedsVacant.label","أسرة شاغرة"},
{"eIP.BedTypeCode.label","رمز نوع السرير"},
{"eIP.BedLayout.label","تخطيط السرير"},
{"eIP.BelongingsReturned.label","عاد المقتنيات"},
{"eIP.BillingParameter.label","معايير الفواتير"},
{"eIP.BillType.label","نوع الفاتورة"},
{"eIP.BlackListed.label","مدرج في القائمة السوداء"},
{"eIP.BlockBed.label","سرير بلوك"},
{"eIP.BlockBedDetails.label","تفاصيل السرير"},
{"eIP.BlockBedonDischarge.label","حجب السرير عند الخروج"},
{"eIP.BlockedBedNo.label","سرير محظور لا"},
{"eIP.BlockedFrom.label","ممنوع من"},
{"eIP.BlockedFromDate.label","ممنوع من التاريخ"},
{"eIP.BlockedRemarks.label","الملاحظات المحظورة"},
{"eIP.BlockedThrough.label","حجبت بواسطة"},
{"eIP.BlockedType.label","النوع المحظور"},
{"eIP.BlockingDetail.label","تفاصيل الحجب"},
{"eIP.BlockingFunction.label","وظيفة الحجب"},
{"eIP.BlockingPeriod.label","فترة الحجب"},
{"eIP.BlockingRefNo.label","رقم مرجع الحجب "},
{"eIP.BlockingType.label","نوع الحجب"},
{"eIP.BlockingTypeCode.label","رمز نوع الحجب"},
{"eIP.BlockPeriod.label","فترة الحجب"},
{"eIP.BlockType.label","نوع الحجب"},
{"eIP.BloodandMedication.label","الدم والأدوية"},
{"eIP.BodyReleasedtoMortuary.label","صرف الجثة إلى مستودع الجثث"},
{"eIP.BodyReleasedtoMortuaryDate.label","أفرج عن الجثة حتى تاريخ الدفن"},
{"eIP.BookedBlocked.label","محجوز / محظور"},
{"eIP.BookedFrom.label","محجوزة من"},
{"eIP.BookedUntil.label","محجوزة حتى"},
{"eIP.BookingAdmissionDetails.label","تفاصيل قبول الحجز"},
{"eIP.BookingDateTime.label","تاريخ / وقت الحجز"},
{"eIP.BookingDetails.label","تفاصيل الحجز"},
{"eIP.BookingLimitByAgeGroupBedClass.label","حد الحجز حسب الفئة العمرية - فئة السرير"},
{"eIP.BookingLimitByNursingUnitBedClass.label","حد الحجز لوحدة التمريض - فئة السرير"},
{"eIP.BookingorReferral.label","الحجز أو الإحالة"},
{"eIP.BookingRef.label","مرجع الحجز"},
{"eIP.BookingReferenceLookup.label","بحث مرجع الحجز"},
{"eIP.BookingRelatedSetup.label","الحجز ذات الصلة الإعداد"},
{"eIP.Bookings.label","الحجوزات"},
{"eIP.BookingSerialDetails.label","تفاصيل مسلسل الحجز"},
{"eIP.BookingType.label","نوع الحجز"},
{"eIP.BreastFeeding.label","الرضاعة الطبيعية"},
{"eIP.BreastFeedingExpressedbreastmilk.label","الرضاعة / حليب الثدي المسحوب"},
{"eIP.ByNursingUnit.label","بواسطة وحدة التمريض"},
{"eIP.ByPractitioner.label","بواسطة ممارس طبي"},
{"eIP.CalculatedAmount.label","المبلغ المحسوب"},
{"eIP.CalculatePercentageOn.label","حساب النسبة المئوية على"},
{"eIP.CancelLeave.label","إلغاء الإجازة"},
{"eIP.CancelLeaveDetails.label","إلغاء تفاصيل الإجازة"},
{"eIP.CancelledAdmission.label","الدخول الملغي"},
{"eIP.CancelledByID.label","تم الإلغاء بواسطة الهوية"},
{"eIP.CancelledDate.label","تاريخ ملغى"},
{"eIP.CancelledDateTo.label","تاريخ الإلغاء إلى"},
{"eIP.CancelledReason.label","سبب ملغى"},
{"eIP.CancelledRequest.label","طلب ملغى"},
{"eIP.CancelledTransferOut.label","تم إلغاء التحويل للخارج"},
{"eIP.CancelReasonDescription.label","إلغاء وصف السبب"},
{"eIP.CancelRequestForTransfer.label","إلغاء طلب التحويل"},
{"eIP.CancelTransferPatientOut.label","إلغاء تحويل المريض للخارج"},
{"eIP.CareofCatheters.label","العناية بالقسطرة"},
{"eIP.CareofEye.label","العناية بالعين"},
{"eIP.CareofPOP.label","رعاية الملوثات العضوية الثابتة"},
{"eIP.CareOfPretermbaby.label","رعاية المبتسرين"},
{"eIP.CareofSkin.label","العناية بالبشرة"},
{"eIP.CareOfStoma.label","رعاية الفتحة المعوية"},
{"eIP.CareofTube.label","العناية بالأنبوب"},
{"eIP.CareofumbilicusStump.label","رعاية قطعة السرة"},
{"eIP.CensusDate.label","تاريخ التعداد"},
{"eIP.CensusMonth.label","شهر التعداد"},
{"eIP.CensusMonthYear.label","التعداد شهرعام"},
{"eIP.CertificateNumber.label","رقم شهادة"},
{"eIP.ChangeofNasogastricTube.label","تغيير الأنبوب الأنفي المعدي"},
{"eIP.ChangeofUrinaryCatheter.label","تغيير القسطرة البولية"},
{"eIP.ChargesIncurredonDischargeDay.label","الرسوم المدخلة في يوم الخروج"},
{"eIP.CheckBookingLimitBasedon.label","تحقق من حد الحجز على أساس"},
{"eIP.CheckforSameSexinRoom.label","تحقق من وجود نفس الجنس في الغرفة"},
{"eIP.CheckInAccompanyingPerson.label","تحقق في الشخص المرافق"},
{"eIP.CheckInDateFrom.label","تاريخ الوصول من"},
{"eIP.CheckInDateTime.label","تاريخ / وقت تسجيل الوصول"},
{"eIP.CheckInlodger.label","تسجيل دخول النزيل"},
{"eIP.checkoutaccomperson.label","تسجيل خروج الشخص المرافق"},
{"eIP.checkoutdatetime.label","تاريخ الخروج / الوقت"},
{"eIP.checkoutlodger.label","تسجيل خروج النزيل"},
{"eIP.ChkdInDt.label","تاريخ تسجيل الوصول"},
{"eIP.ClinicalDocFilm.label","فيلم / وثيقة سريرية"},
{"eIP.ColorSchemeTable.label","جدول نظام الألوان"},
{"eIP.ColourCodeScheme.label","نظام رمز اللون"},
{"eIP.ConfirmBedClassChange.label","تأكيد تغيير فئة السرير"},
{"eIP.ConfirmBookingDetails.label","تأكيد تفاصيل الحجز"},
{"eIP.ConfirmCancellation.label","تأكيد الالغاء"},
{"eIP.ConfirmCancelReviseBooking.label","تأكيد / إلغاء / مراجعة الحجز"},
{"eIP.ConfirmDetails.label","تأكيد التفاصيل"},
{"eIP.ConfirmDischarge.label","تأكيد الخروج"},
{"eIP.ConfirmRequestforTransfer.label","تأكيد طلب التحويل"},
{"eIP.ConfirmSwap.label","تأكيد المبادلة"},
{"eIP.ConfirmSwapBeds.label","تأكيد سرير المبادلة"},
{"eIP.ConsumableBillingService.label","خدمة فواتير المستهلكات"},
{"eIP.ConsumableFee.label","رسوم الاستهلاك"},
{"eIP.CostCenter.label","مركز تقييم التكلفة "},
{"eIP.CreatePseudoBed.label","إنشاء سرير مرافق"},
{"eIP.CurrentEncounterDetails.label","تفاصيل الزيارة الحالي"},
{"eIP.CurrentInpatientsOnly.label","المرضى المنومين الحاليين فقط"},
{"eIP.CurrentLodgers.label","نزلاء حاليين"},
{"eIP.CurrentOccupancy.label","الوظيفة الحالية"},
{"eIP.CurrentValidityDetails.label","تفاصيل الصلاحية الحالية"},
{"eIP.DailyAdmissions.label","الدخول اليومي"},
{"eIP.DailyBookingsByMedicalServiceGroup.label","الحجوزات اليومية من قبل مجموعة الخدمات الطبية"},
{"eIP.DailyBookingsByNursingUnit.label","الحجوزات اليومية لوحدة التمريض"},
{"eIP.DailyCharge.label","الرسم اليومي"},
{"eIP.DailyCharges.label","الرسوم اليومية"},
{"eIP.DailyMonthlyBookings.label","الحجوزات اليومية / الشهرية"},
{"eIP.DailyRate.label","تقدير يومي"},
{"eIP.DateTimeOfAuthTransfer.label","تاريخ / وقت التحويل المصرح به"},
{"eIP.DateTimeReturned.label","تاريخ / وقت العودة"},
{"eIP.DaycareUnitforNursingUnit.label","وحدة الرعاية النهارية لوحدة التمريض"},
{"eIP.DeactivatePseudoBed.label","قم بإلغاء تنشيط السرير المرافق"},
{"eIP.DeathTransactionTime.label","وقت معاملة الوفاة"},
{"eIP.DeceasedDateFrom.label","تاريخ الوفاة من"},
{"eIP.DeceasedDateTo.label","تاريخ الوفاة إلى"},
{"eIP.DefaultBedBlockingPeriodonTransferDischargeofInfectiousDiseasePatients.label","فترة حجب السرير الافتراضية عند نقل / خروج مرضى الأمراض المعدية"},
{"eIP.DefaultPeriodforNormal.label","الفترة الافتراضية للعادي"},
{"eIP.DepositAmount.label","قيمة الايداع"},
{"eIP.DepositApplicable.label","الإيداع مسموح"},
{"eIP.DesignationTitle.label","التحديد / العنوان"},
{"eIP.Diet.label","حمية غذائية"},
{"eIP.DischargeAdviceReport.label","تقرير إشعار الخروج"},
{"eIP.DischargeBookGiven.label","كتاب الخروج المعطى"},
{"eIP.DischargeCheckList.label","قائمة فحص الخروج"},
{"eIP.DischargeCheckListApplicable.label","قائمة التحقق من الخروج قابلة للتطبيق"},
{"eIP.DischargeChecklistExpiryPeriod.label","فترة انتهاء قائمة مراجعة الخروج"},
{"eIP.DischargeDateFrom.label","تاريخ الخروج من"},
{"eIP.DischargeDateTo.label","تاريخ الخروج إلى"},
{"eIP.DischargeDetails.label","تفاصيل الخروج"},
{"eIP.DischargedHome.label","خروج / المنزل"},
{"eIP.DischargeDiagnosis.label","تشخيص الخروج"},
{"eIP.DischargeFunction.label","وظيفة الخروج"},
{"eIP.DischargeRemarks.label","ملاحظات الخروج"},
{"eIP.DischargeSummarySigned.label","توقيع ملخص الخروج"},
{"eIP.DischargeTypeCode.label","رمز نوع الخروج"},
{"eIP.DischargeTypeIndicator.label","مؤشر نوع الخروج"},
{"eIP.DischargingPractitioner.label","طبيب الخروج"},
{"eIP.DiscSummaryPrepared.label","تم إعداد ملخص الخروج"},
{"eIP.DrainageCatheters.label","قسطرة الصرف"},
{"eIP.EmergencyDetail.label","تفاصيل الطوارئ"},
{"eIP.EmergencyTransfer.label","تحويل طارئ"},
{"eIP.EscortAmbulanceService.label","مرافقة / خدمة الاسعاف"},
{"eIP.ExistingMedication.label","الأدوية الموجودة"},
{"eIP.ExpdaysofStay.label","أيام الإقامة المتوقعة"},
{"eIP.ExpectedDischarge.label","الخروج المتوقع"},
{"eIP.ExpectedDischargeDateTime.label","تاريخ / وقت الخروج المتوقع"},
{"eIP.ExpectesDischargeDate.label","تاريخ الخروج المتوقع"},
{"eIP.ExpiryPeriodUnit.label","وحدة فترة انتهاء الصلاحية"},
{"eIP.ExpiryRequired.label","الصلاحية مطلوبة"},
{"eIP.FatherIDNo.label","رقم هوية الأب"},
{"eIP.Fever.label","حمى"},
{"eIP.FinancialClassification.label","التصنيف المالي"},
{"eIP.FitForDutyon.label","يصلح للخدمة في"},
{"eIP.FloorPlanLayout.label","شكل مخطط الطابق"},
{"eIP.FollowupAppointments.label","متابعة المواعيد"},
{"eIP.Formulamilk.label","حليب تركيبة"},
{"eIP.FromBedType.label","من نوع السرير"},
{"eIP.FromBedTypeAmount.label","من نوع السرير القيمة"},
{"eIP.FromBedTypeCode.label","من كود نوع السرير"},
{"eIP.FromDetails.label","من التفاصيل"},
{"eIP.FromYear.label","من سنة"},
{"eIP.Gastrotomyfeeding.label","تغذية المعدة"},
{"eIP.GenerateBookingNumber.label","إنشاء رقم الحجز"},
{"eIP.GraceperiodforAbscondPatient.label","فترة سماح للمريض الهارب"},
{"eIP.GraceperiodforNoShow.label","فترة سماح لعدم الحضور"},
{"eIP.GracePeriodforRevisionofBooking.label","فترة السماح لمراجعة الحجز"},
{"eIP.guardian.label","وصي"},
{"eIP.HandedovertoPatient.label","سلمت للمريض"},
{"eIP.HealthEducation.label","التثقيف الصحي"},
{"eIP.HospitalOccupancy.label","إشغال المستشفى"},
{"eIP.ImmunizationSchedule.label","جدول التطعيم"},
{"eIP.InclDiscPatients.label","بما في ذلك مرضى الخروج"},
{"eIP.IncludeBedtobereleasedin.label","قم بتضمين السرير ليتم تحريره فيه"},
{"eIP.IncludeforHospitalCalculation.label","تضمين لحساب المستشفى"},
{"eIP.IncludeforHospitalOccupancyCalculations.label","قم بتضمين حسابات إشغال المستشفى"},
{"eIP.Informed.label","أبلغ"},
{"eIP.InformedDetails.label","تفاصيل تم إبلاغها"},
{"eIP.InformedOthers.label","تم إبلاغ آخرين"},
{"eIP.InformedPatientRelatives.label","أقارب مريض تم إبلاغم"},
{"eIP.InformedTo.label","تم إبلاغه"},
{"eIP.InformedToName.label","إسم تم أبلاغه"},
{"eIP.InsuranceExpiryWarning.label","تحذير انتهاء التأمين"},
{"eIP.Interward.label","بين الأدوار"},
{"eIP.Intraward.label","داخل الدور"},
{"eIP.IPMiscsetup.label","إعدادات مريض داخلي متنوع"},
{"eIP.IssuingPractitioner.label","صرف بواسطة ممارس طبي"},
{"eIP.IVCatheters.label","القسطرة وريدية"},
{"eIP.Jaundice.label","الصفراء"},
{"eIP.LabourAndDelivery.label","الحمل والولادة"},
{"eIP.LastTransactionDateTime.label","تاريخ / وقت الخروج المتوقع"},
{"eIP.LeaveDatefrom.label","تاريخ الخروج من"},
{"eIP.leavedatetime.label","تاريخ / وقت الخروج"},
{"eIP.LeaveDetails.label","تفاصيل الخروج"},
{"eIP.LeaveExpiry.label","انتهاء صلاحية الخروج"},
{"eIP.LeaveRemarks.label","اترك الملاحظات"},
{"eIP.LeaveWardAccompaniedBy.label","مغادرة الجناح برفقة"},
{"eIP.LengthofStay.label","مدة الأقامة"},
{"eIP.LodgerAccompanyingPersonReference.label","مرجع الشخص المرافق"},
{"eIP.LodgerDetails.label","تفاصيل المرافق"},
{"eIP.LodgerId.label","هوية المرافق"},
{"eIP.LodgerName.label","اسم المرافق"},
{"eIP.LodgerPersonID.label","هوية شخص المرافق"},
{"eIP.LodgerReferenceMaxSrlNo.label"," مرجع الرقم التسلسلي الأقصى للمرافق"},
{"eIP.LodgerReferenceNextSrlNo.label"," مرجع الرقم التسلسلي القادم للمرافق"},
{"eIP.MainBedNo.label","رقم السرير الرئيسي"},
{"eIP.MaternalDeath.label","وفاة أثناء الولادة"},
{"eIP.MaxAllowableBackdatedAdmission.label","الحد الأقصى المسموح به لقبول دخول بأثر رجعي"},
{"eIP.MaxAllowableBackdatedDischarge.label","الحد الأقصى المسموح به لقبول خروج بأثر رجعي"},
{"eIP.MaxAllowableBedblockingPeriod.label","الحد الأقصى المسموح به لحجب السرير"},
{"eIP.MaxAllowableLeavePeriod.label","أقصى فترة إجازة مسموح بها"},
{"eIP.MaxAllowablePeriodforAdvanceBedBooking.label","الحد الأقصى للفترة المسموح بها لحجب السريرالمسبق"},
{"eIP.MaxAllowablePeriodforDischarge.label","أقصى فترة مسموح بها للخروج"},
{"eIP.MaxAllowablePeriodforNormal.label","أقصى فترة مسموح بها للعادي"},
{"eIP.MaxAllowablePeriodforTransferOut.label","الحد الأقصى للمدة المسموح بها للتحويل"},
{"eIP.MaxAllowedAccompanyingPersons.label","الحد الأقصى المسموح به للمرافقين"},
{"eIP.MaxAllowedPeriodofStayforLodgerAccompanyingPerson.label","الحد الأقصى لفترة الإقامة المسموح بها للنزيل / الشخص المرافق"},
{"eIP.MaxDailyBooking.label","أقصى عدد حجز اليومي"},
{"eIP.MaxDailyBookingLimit.label","الحد الأقصى للحجز اليومي"},
{"eIP.MaxFemaleDailyBookingLimit.label","الحد الأقصى للحجز اليومي للسيدات"},
{"eIP.MaximumParameterValue.label","الحد الأقصى لقيمة المعايير"},
{"eIP.MaxMaleDailyBookingLimit.label","الحد الأقصى للحجز اليومي للذكور"},
{"eIP.MaxMonthlyBooking.label","الحد الأقصى للحجز الشهري"},
{"eIP.MaxNo.label","اكبر عدد"},
{"eIP.MaxPeriodafterDischargeforCheckinLodger.label","أقصى فترة للخروج بعد تسجيل الوصول لمرافق"},
{"eIP.MaxUnknownDailyBookingLimit.label","الحد الأقصى للحجز اليومي غير المعروف"},
{"eIP.MedicalCertificate.label","شهادة طبية"},
{"eIP.MedicalDetails.label","التفاصيل الطبية"},
{"eIP.MedicalEquipment.label","معدات طبية"},
{"eIP.MedicalServiceGroup.label","مجموعة الخدمات الطبية"},
{"eIP.MonthlyAdmission.label","الدخول الشهري"},
{"eIP.MonthlyBookingsByMedicalServiceGroup.label","الحجوزات الشهرية من قبل مجموعة الخدمات الطبية"},
{"eIP.MonthlyBookingsByNursingUnit.label","الحجوزات الشهرية لوحدة التمريض"},
{"eIP.MotherIDNo.label","رقم هوية الأم"},
{"eIP.MRI.label","التصوير بالرنين المغناطيسي"},
{"eIP.MVRegnNo.label","MV رقم تعريف"},
{"eIP.NasogastricTube.label","أنبوب تغذية عبر الأنف"},
{"eIP.NewMedicine.label","الطب الجديد"},
{"eIP.NextNo.label","الرقم التالي"},
{"eIP.Nonoverrideable.label","غير قابل للتجاوز"},
{"eIP.NormalBeds.label","أسرة عادية"},
{"eIP.NormalDefaultBedBlockingPeriod.label","فترة حجب السرير الافتراضية العادية"},
{"eIP.NoShowsCancelledBooking.label","عدم الحضور / إلغاء الحجز"},
{"eIP.NoLayoutExit.label","لا يوجد مخطط تعريف"},
{"eIP.NoofRows.label","عدد الصفوف"},
{"eIP.NoofCols.label","عدد الأعمدة"},
{"eIP.NursingTypeCode.label","رمز نوع التمريض"},
{"eIP.NursingUnitBedClass.label","وحدة التمريض - فئة السرير"},
{"eIP.NursingUnitDescription.label","وصف وحدة التمريض"},
{"eIP.NursingUnitFrom.label","وحدة تمريض من"},
{"eIP.NursingUnitSetup.label"," إعدادات وحدة التمريض"},
{"eIP.NursingUnitType.label","نوع وحدة التمريض"},
{"eIP.NursingUnitTypeforMedicalServiceGroup.label","نوع وحدة التمريض لمجموعة الخدمات الطبية"},
{"eIP.Nutrition.label","تغذية"},
{"eIP.OcccupiedDeparted.label","مشغولة - خالية"},
{"eIP.OccupancyDetails.label","تفاصيل الإشغال"},
{"eIP.OccupyingPatientID.label","هوية المريض المقيم"},
{"eIP.OtherAppliancesFixtures.label","أجهزة / تركيبات أخرى"},
{"eIP.OtherDocuments.label","مستندات أخرى"},
{"eIP.OthersSpecify.label","أخرى برجاء التحديد"},
{"eIP.OutpatientLocation.label","موقع العيادة الخارجية"},
{"eIP.OutstandingAmountexceeds.label","عندما يتجاوز المبلغ المستحق الحد المسموح مطلوب موافقة"},
{"eIP.OutstandingamountLimit.label","حد المبلغ المستحق"},
{"eIP.Overrideable.label","يمكن إلغاءه / تجاوزه"},
{"eIP.OverstayDays.label","أيام تجاوز مدة الإقامة"},
{"eIP.OverStayPatients.label","مرضى تجاوزوا مدة الإقامة"},
{"eIP.PaediatricDetails.label","تفاصيل طب الأطفال"},
{"eIP.Pamphlets.label","كتيبات"},
{"eIP.PastOpenBookings.label","الحجوزات المفتوحة السابقة"},
{"eIP.PatientBelongings.label","متعلقات المريض"},
{"eIP.PatientFamilyDetails.label","تفاصيل عائلة المريض"},
{"eIP.PatientReferral.label","إحالة المريض"},
{"eIP.PatientsNotReturnedfromleave.label","المرضى الذين لم يعودوا من الإجازة"},
{"eIP.PatientsReAdmittedonthesameday.label","إعادة دخول المرضى في نفس اليوم"},
{"eIP.PatientTransfer.label","نقل المريض"},
{"eIP.PercentageonDepositAmount.label","النسبة المئوية لمبلغ الإيداع"},
{"eIP.PercentAmount.label","النسبة المئوية / القيمة"},
{"eIP.PercentAmountIndicator.label","مؤشر النسبة المئوية / القيمة"},
{"eIP.PersonalHygiene.label","النظافة الشخصية"},
{"eIP.PersonID.label","هوية الشخص"},
{"eIP.PhysicalLocationforNursingUnit.label","المكان الفعلي لوحدة التمريض"},
{"eIP.Physio.label","علاج طبيعي"},
{"eIP.POP.label","POP"},
{"eIP.PopCare.label","العناية POP"},
{"eIP.PorterageDetails.label","تفاصيل الحمولة"},
{"eIP.PorterageReceived.label","استلام الحمولة"},
{"eIP.PorterageRemarks.label","ملاحظات الحمولة"},
{"eIP.PostMortemReqd.label","مطلوب بعد الوفاة"},
{"eIP.PostMortemRequested.label","طلب بعد الوفاة"},
{"eIP.PractitionerDesignation.label","تحديد ممارس طبي"},
{"eIP.PractitionerforNursingUnit.label","ممارس طبي لوحدة التمريض"},
{"eIP.Preview.label","معاينة"},
{"eIP.PrefAdmDateTime.label","تاريخ / وقت الدخول المفضل"},
{"eIP.PreferredAdmissionDate.label","تاريخ الدخول المفضل"},
{"eIP.PreferredDateTime.label","التاريخ / الوقت المفضل"},
{"eIP.PreferredDateTo.label","التاريخ المفضل إلى"},
{"eIP.PreferredMonthFrom.label","الشهر المفضل من"},
{"eIP.PreferredMonthTo.label","الشهر المفضل"},
{"eIP.PrepareDischargeAdvice.label","تحضير أمر الخروج"},
{"eIP.PreviousBedDetails.label","تفاصيل السرير السابقة"},
{"eIP.PreviousIPStay.label","الدخول السابق"},
{"eIP.PreviousOccupancy.label","الإشغال السابق"},
{"eIP.PrintCertificate.label","طباعة الشهادة"},
{"eIP.PrintOn.label","الطباعة على"},
{"eIP.PrintTransferDetails.label","طباعة تفاصيل التحويل"},
{"eIP.ProcedureSurgeryDateTime.label","الإجراء / تاريخ الجراحة / الوقت"},
{"eIP.Properties.label","ملكيات"},
{"eIP.Pseudo.label","مرافق / مستعار"},
{"eIP.PseudoBabyBeds.label","أسرة مرافقة / أطفال"},
{"eIP.PseudoBed.label","سرير مرافق"},
{"eIP.RangeinDays.label","المدى في أيام"},
{"eIP.ReasonforAdmissionBooking.label","سبب الدخول / الحجز"},
{"eIP.ReasonforBlocking.label","سبب الحجب"},
{"eIP.ReasonforCancel.label","سبب الإلغاء"},
{"eIP.ReasonforLodgerStay.label","سبب إقامة المرافق"},
{"eIP.ReasonForLodgerStayCode.label","سبب رمز إقامة المرافق"},
{"eIP.ReasonforStay.label","سبب البقاء"},
{"eIP.ReasonForSwap.label","سبب المبادلة"},
{"eIP.ReasonforTransfer.label","سبب النقل"},
{"eIP.ReasonforTurnDownAdmission.label","سبب رفض الدخول"},
{"eIP.ReceivedinFull.label","تم استلامها بالكامل"},
{"eIP.ReceivedPartially.label","تم الاستلام جزئيًا"},
{"eIP.ReceivedPartiallyFully.label","تم الاستلام جزئيًا / كليًا"},
{"eIP.RecordNoShow.label","تسجيل عدم حضور"},
{"eIP.RecordNoShowDateTime.label","سجل عدم إظهار التاريخ / الوقت"},
{"eIP.RecordNoShowDetails.label","سجل لا إظهار التفاصيل"},
{"eIP.RecordProcedureSurgeryDate.label","إجراء التسجيل / تاريخ الجراحة"},
{"eIP.RecordReturn.label","تسجيل العودة"},
{"eIP.RecordReturnDetails.label","سجل تفاصيل الإرجاع"},
{"eIP.RecordsDocuments.label","السجلات والوثائق"},
{"eIP.ReferralLetter.label","خطاب الإحالة"},
{"eIP.ReferredDetails.label","التفاصيل المشار إليها"},
{"eIP.ReferredType.label","النوع المشار إليه"},
{"eIP.RegisterNewBornForIP.label","تسجيل حديثي الولادة للمرضى الداخليين"},
{"eIP.ReleaseBedonLeave.label","حرر السرير عند الإجازة"},
{"eIP.RemovalOf.label","إزالة"},
{"eIP.RejectedBy.label","مرفوض من طرف"},
{"eIP.RejectedDate.label","تاريخ مرفوض"},
{"eIP.RemovedBy.label","تمت إزالته بواسطة"},
{"eIP.RenewalOfGatePass.label","تجديد تصريح الدخول"},
{"eIP.RenewalValidityDetails.label","تفاصيل صلاحية التجديد"},
{"eIP.renewgatepass.label","تجديد تصريح الدخول"},
{"eIP.ReplyLetter.label","رسالة للرد"},
{"eIP.ReportedTo.label","أبلغ إلى"},
{"eIP.RequestBedClassChange.label","طلب تغيير فئة السرير"},
{"eIP.RequestforBedClassChange.label","طلب تغيير فئة السرير"},
{"eIP.RequestInpatientConfirmed.label","طلب / مريض داخلي"},
{"eIP.RequestPlaced.label","تم تقديم الطلب"},
{"eIP.RequestTransfer.label","طلب تحويل"},
{"eIP.ReturnedRemarks.label","ملاحظات الإرجاع"},
{"eIP.Resolution.label","قرار"},
{"eIP.ReviseBookingDetails.label","مراجعة تفاصيل الحجز"},
{"eIP.ReviseLeave.label","مراجعة الإجازة"},
{"eIP.ReviseLeaveDetails.label","مراجعة تفاصيل الإجازة"},
{"eIP.reviseperiodfrom.label","مراجعة الفترة من"},
{"eIP.reviseperiodto.label","مراجعة الفترة إلى"},
{"eIP.RoleEndDate.label","تاريخ انتهاء الدور"},
{"eIP.RoleStartDate.label","تاريخ بدء الدور"},
{"eIP.RoomCubicleDescription.label","وصف الغرفة / المقصورة"},
{"eIP.RoomCubicleforNursingUnit.label","غرفة / حجرة لوحدة التمريض"},
{"eIP.RoundingBillingService.label","خدمة فواتير التقريب"},
{"eIP.RoundingFee.label","رسوم التقريب"},
{"eIP.Scan.label","مسح"},
{"eIP.Seizure.label","حجز"},
{"eIP.ServicesforNursingUnit.label","خدمات وحدة التمريض"},
{"eIP.ServiceTeam.label","فريق خدمة"},
{"eIP.SetupBillingDtls.label","تفاصيل إعدادات الفواتير"},
{"eIP.SexSpecInd.label"," مواصفات الجنس النوعية"},
{"eIP.SpecialBedType.label","نوع السرير الخاص"},
{"eIP.SpecialtyforNursingUnit.label","تخصص لوحدة التمريض"},
{"eIP.StayPeriod.label","فترة البقاء"},
{"eIP.STO.label","STO"},
{"eIP.StockMedicine.label","الطب المخزون"},
{"eIP.StomaCare.label","العناية بالفتحة المعوية"},
{"eIP.StoolColour.label","لون البراز"},
{"eIP.StoolFrequency.label","تردد البراز"},
{"eIP.SupportiveCare.label","الرعاية الداعمة في المنزل"},
{"eIP.SwapBeds.label","مقايضة الأسرة"},
{"eIP.SwapPatientBeds.label","استبدل سرير بين مريضين"},
{"eIP.TakeHomeMedicine.label","دواء خروج المريض للمنزل"},
{"eIP.TakeHomeNewMedicine.label","دواء جديد لخروج المريض للمنزل"},
{"eIP.Takencareby.label","عناية"},
{"eIP.TeachingLocation.label","مكان التدريس"},
{"eIP.TemporaryLocation.label","موقع مؤقت"},
{"eIP.ToBedType.label","نوع السرير"},
{"eIP.ToBedTypeAmount.label","قيمة نوع السرير"},
{"eIP.ToBedTypeCode.label","رمز نوع السرير"},
{"eIP.ToDateTime.label","إلى التاريخ / الوقت"},
{"eIP.ToDetails.label","إلى التفاصيل"},
{"eIP.ToptoToe.label","من أعلى إلى اسفل"},
{"eIP.TotalAdmission.label"," مجموع حالات الدخول"},
{"eIP.TotalBeds.label","عدد الأسرة"},
{"eIP.ToYear.label","إلى سنة"},
{"eIP.TransactionDateFrom.label","تاريخ المعاملة من"},
{"eIP.TransactionDateTime.label","تاريخ / وقت المعاملة"},
{"eIP.TransactionMonthYear.label","معاملات شهر / سنة"},
{"eIP.TransferBookingDate.label","تاريخ حجز النقل"},
{"eIP.TransferCharge.label","رسوم التحويل"},
{"eIP.TransferChargeable.label","رسوم التحويل"},
{"eIP.TransferChargeDetails.label","تفاصيل رسوم التحويل"},
{"eIP.TransferConfirmation.label","تأكيد التحويل"},
{"eIP.TransferedOut.label","المحولة إلى الخارج"},
{"eIP.TransferFunction.label","وظيفة النقل"},
{"eIP.TransferInStatus.label","نقل في الحالة"},
{"eIP.TransferPatientIn.label","نقل المريض"},
{"eIP.TransferPatientOut.label","نقل المريض للخارج"},
{"eIP.TransferPriority.label","أولوية التحويل"},
{"eIP.TransferredIn.label","تم التحويل في"},
{"eIP.TransferRequest.label","طلب التحويل"},
{"eIP.TransferringPractitioner.label","نقل بواسطة ممارس طبي"},
{"eIP.TransferServiceCharge.label","رسوم خدمة التحويل"},
{"eIP.TransferType.label","نوع التحويل"},
{"eIP.TransferTypeCode.label","رمز نوع التحويل"},
{"eIP.Transport.label","ينقل"},
{"eIP.TransportArranged.label","ترتيب النقل"},
{"eIP.Tubefeeding.label","أنبوب التغذية"},
{"eIP.Tubes.label","أنابيب"},
{"eIP.TurnDown.label","رفض"},
{"eIP.UntilDateTime.label","حتى التاريخ / الوقت"},
{"eIP.UrinaryCatheter.label","القسطرة البولية"},
{"eIP.ValuablesReturned.label","تم إرجاع الأشياء الثمينة"},
{"eIP.WorkupBillingService.label"," فحوصات خدمة الفواتير"},
{"eIP.WoundCare.label","العناية بالجروح"},
{"eIP.Xray.label","الأشعة السينية"},
{"eIP.RejoinedFromLeave.label","عاد من الإجازة"},
{"eIP.Transferred.label","نقل"},
{"eIP.RecordInpatientLeaveAbscond.label","سجل إجازة / هروب المرضى الداخليين"},
{"eIP.EncounterLocation.label","موقع الزيارة"},
{"eIP.ServiceSubService.label","الخدمة / الخدمة الفرعية"},
{"eIP.LastAdmissionDateTime.label","تاريخ / وقت آخر دخول"},
{"eIP.LastDischargeDateTime.label","تاريخ / وقت آخر خروج"},
{"eIP.RequestedForRecordDocument.label","مطلوب لسجل الوثيقة"},
{"eIP.RequestingNursingUnit.label","طلب وحدة تمريض"},
{"eIP.AdmittedPatientIntoBuilding.label","تم قبول المريض في المبنى"},
{"eIP.BedAlloter.label","تخصيص السرير"},
{"eIP.FirstPortionForDoctor.label","الحصة الأولى للطبيب"},
{"eIP.InvestigationHappenedBeforeAdmission.label","حدث التحقيق قبل الدخول"},
{"eIP.PatientRelativeContactPlace.label","مكان اتصال المريض / القريب"},
{"eIP.SecondPortionForAdmissionCenterStaff.label","الحصة الثانية لمركز الدخول / الموظفين"},
{"eIP.SpecialRequirement.label","متطلبات خاصة"},
{"eIP.ThirdPortionForPatient.label","الحصة الثالثة للمريض"},
{"eIP.NotSpecified.label","غير محدد"},
{"eIP.MaximumAllowed.label","الحد الأقصى المسموح به"},
{"eIP.AdmitableDate.label","تاريخ مبدئي للدخول"},
{"eIP.CurrentlyPatientIsAt.label","المريض حاليا في"},
{"eIP.Faculty.label","هيئة التدريس"},
{"eIP.SpecialMulBedRoom.label","غرفة نوم متعددة خاصة"},
{"eIP.SpecialPvtRoom.label","غرفة خاصة خاصة"},
{"eIP.HealthDistrict.label","منطقة الصحة"},
{"eIP.InfoRequestor.label","معلومات / متلقي الطلب"},
{"eIP.OtherIdentificationNo.label","رقم تعريف آخر"},
{"eIP.FamilyHealthOfficer.label","مسؤول صحة الأسرة"},
{"eIP.GravidaParity.label","عدد مرات الحمل / عدد الولادات"},
{"eIP.MatDeathInvOfficer.label","ضابط تحقيق وفيات الولادة"},
{"eIP.NationalRegnNo.label","رقم التسجيل الوطني"},
{"eIP.StateHealthDepartment.label","وزارة الصحة بالولاية"},
{"eIP.AbscondFromDateTime.label","الهروب من التاريخ / الوقت"},
{"eIP.ClinicalInformation.label","المعلومات الطبيه"},
{"eIP.RequestedFor.label","مطلوب ل"},
{"eIP.ActiveProblemsDiagnosis.label","المشاكل النشطة / التشخيص"},
{"eIP.ClinicalSummary.label","الملخص السريري"},
{"eIP.LastAdmissionDate.label","تاريخ آخر موعد للدخول"},
{"eIP.LastAdmissionLocation.label","آخر مكان تم الدخول فيه"},
{"eIP.NewProblemsDiagnosis.label","مشاكل / تشخيص جديد"},
{"eIP.Stamp.label","ختم"},
{"eIP.GatePassValidity","صلاحية المنفذ"},
{"eIP.AdmittedForTreatment.label","دخل لأخذ علاج"},
{"eIP.ScheduledOperationDate.label","تاريخ العملية المجدولة"},
{"eIP.ScheduledSpecialCheckupDate.label","موعد الفحص الخاص المقرر"},
{"eIP.ContactPlaceOfDoctor.label","مكان الاتصال بالطبيب"},
{"eIP.SocialSecurity.label","ضمان اجتماعي"},
{"eIP.LifeInsurance.label","التأمين على الحياة"},
{"eIP.SelfPayment.label","دفع ذاتي"},
{"eIP.DateAssignedForOperation.label","التاريخ المعين للعملية"},
{"eIP.HospitalAdmissionCenter.label","مركز الدخول بالمستشفى"},
{"eIP.IncaseOfQuestionOrChangeRequest.label","في حالة السؤال أو طلب التغيير"},
{"eIP.UnConfirmed.label","غير مؤكد"},
{"eIP.EstimateCost.label","تقدير التكلفة"},
{"eIP.OverReimbursable.label","زيادة عن التكلفة القابلة للسداد"},
{"eIP.LeavePass.label","رحيل لمكان"},
{"eIP.ValuableBelongTo.label","مقتنيات تنتمي إلى"},
{"eIP.Pieces.label.label","قطع"},
{"eIP.LastUpdateFileLocation.label","موقع ملف التحديث الأخير"},
{"eIP.LocationPriorToLastUpdate.label","الموقع قبل آخر تحديث"},
{"eIP.PatientGender.label","جنس المريض"},
{"eIP.GenderType.label","نوع الجنس"},
{"eIP.BedGender.label","جنس السرير"},
{"eIP.BedAvailablibilityDate.label","تاريخ توفر السرير"},
{"eIP.ReserveBedDetails.label","تفاصيل السرير الاحتياطي"},
{"eIP.ReserveBed.label","سرير احتياطي"},
{"eIP.ReasonforReserveBed.label","سبب حجز السرير"},
{"eIP.ReservedBeds.label","أسرة محجوزة"},
{"eIP.ReserveBedWhileTransfer.label","حجز السرير أثناء النقل"},
{"eIP.MultipleBookingforPatients.label","الحجز المتعدد للمرضى"},
{"eIP.ViewOpenBookings.label","عرض الحجوزات المفتوحة"},
{"eIP.MotherBedNo.label","رقم سرير الام"},
{"eIP.IncludeReservedBeds.label","تضمين الأسرة المحجوزة"},
{"eIP.AssignPractitionerBedsideReferral.label","تعيين ممارس طبي للإحالة إلى السرير"},
{"eIP.StatisticsBy.label","إحصائيات بواسطة"},
{"eIP.ChangeInpatientService.label","تغيير خدمة المرضى الداخليين"},
{"eIP.BookedOverrideableConfirmed.label","تم تأكيد حجز مبالغ فيه"},
{"eIP.BookedOverrideableUnConfirmed.label","تم تجاوز الحجز بدون تأكيد"},
{"eIP.BookedNonOverrideableConfirmed.label","تم تأكيد الحجز غير القابل للإلغاء"},
{"eIP.BookedNonOverrideableUnConfirmed.label","حجز غير قابل للتبديل غير مؤكد"},
{"eIP.PreOpPreparationDays.label","أيام التحضير قبل العملية"},
{"eIP.BlockBedBasedon.label","حجب السرير على أساس"},
{"eIP.CancelDischargeApplicable.label","ينطبق إلغاء الخروج"},
{"eIP.CancelDischargePatient.label","إلغاء خروج مريض"},
{"eIP.AbortCancelDischarge.label","إيقاف إلغاء الخروج"},
{"eIP.BookingRemarks.label","ملاحظات الحجز"},
{"eIP.InvokeAdmFromNewBornReg.label","طلب الدخول من تسجيل حديثي الولادة"},
{"eIP.DischargeStatus.label","حالة الخروج"},
{"eIP.CompleteRecovery.label","تعاف كلي"},
{"eIP.PartialRecovery.label","الانتعاش الجزئي"},
{"eIP.StatusQuo.label","الوضع الراهن"},
{"eIP.ConditionWorse.label","الشرط أسوأ"},
{"eIP.DischargeStatusIndicator.label","مؤشر حالة الخروج"},
{"eIP.Deceasedperiod.label","فترة الوفاة"},
{"eIP.CensusDateRange.label","نطاق تاريخ التعداد"},
{"eIP.PercentageofOccupancy.label","نسبة الإشغال"},
{"eIP.AllowMultipleBedsForReserving.label","السماح لعدة أسرّة بالحجز"},
{"eIP.AllowBookingoccupiedbedswithoutEDD.label","السماح بالحجز للأسرة المشغولة حاليًا بدون موعد محدد"},
{"eIP.AllowBookingoccupiedbedswithEDD.label","السماح بالحجز للأسرة المشغولة حاليًا بموعد محدد"},
{"eIP.TypeOfBooking.label","نوع الحجز"},
{"eIP.IndicateFutureBooking.label","حدد الحجز المستقبلي"},
{"eIP.NumberofdaysBefore.label","عدد الأيام قبل"},
{"eIP.ConsiderEDDBeforeStop.label","ضع في اعتبارك  موعد محدد قبل التوقف"},
{"eIP.ActiononBookingadmission.label","اتخاذ إجراء بشأن الحجز / الدخول"},
{"eIP.ConfirmedOverridable.label","مؤكد و قابل للإلغاء"},
{"eIP.UnConfirmedOverridable.label","غير مؤكد و قابل للإلغاء"},
{"eIP.ConfirmedNonOverridable.label","مؤكد و غير قابل للإلغاء"},
{"eIP.UnConfirmedNonOverridable.label","غير مؤكد و غير قابل للإلغاء"},
{"eIP.GrcprdforAsgnBed.label","فترة سماح لتعيين السرير / تحديد الوصول"},
{"eIP.ReasonforChangeAdmission.label","سبب تغيير الدخول"},
{"eIP.CurrentAdmissionDetails.label","تفاصيل الدخول الحالية"},
{"eIP.ChangeAdmissionDetails.label","تغيير تفاصيل الدخول"},
{"eIP.AdmissionAuditDetails.label","تفاصيل تدقيق الدخول"},
{"eIP.modifieddatefrom.label","تاريخ التعديل من"},
{"eIP.modifieddateto.label","تاريخ التعديل إلى"},
{"eIP.ReasonForModification.label","سبب التعديل"},
{"eIP.BookingRefList.label","قائمة مرجعية الحجز"},
{"eIP.InvokeDthReginDisAdv.label","السماح باستدعاء الاحتفاظ بسجل الوفيات في إعداد نصيحة الخروج"},
{"eIP.RevisonReason.label","سبب المراجعة"},
{"eIP.DisplayNoShowstatusinConfirmBookingAfter.label","عرض حالة عدم العرض في تأكيد الحجز بعد"},
{"eIP.Complement.label","إطراء"},
{"eIP.OccupancyRate.label","معدل الإشغال"},
{"eIP.Pref.label","تم"},
{"eIP.Proc.label","سوف يتم"},
{"eIP.Occupancy.label","شغل"},
{"eIP.Stay.label","إقامة"},
{"eIP.Turnover.label","تناوب"},
{"eIP.OneDayStays.label","يبقى يوم واحد"},
{"eIP.DischIncldeaths.label","حالات الخروج (بما في ذلك الوفيات)"},
{"eIP.BedComp.label","مكون السرير"},
{"eIP.Adm.label","دخول"},
{"eIP.TfrIn.label","تحويل للداخل"},
{"eIP.TfrOut.label","تحويل للخارج"},
{"eIP.TotOneDayStay.label","ضريبة الإشغال المؤقتة لإقامة يوم واحد"},
{"eIP.NoOfAdmissions.label","عدد حالات الدخول"},
{"eIP.BkgLstRefNo.label"," المرجع رقم"},
{"eIP.TotPatientDays.label","ضريبة الإشغال المؤقتة لأيام مرضى"},
{"eIP.PercentAvgOccup.label","النسبة المئوية لمتوسط ​​الاحتلال."},
{"eIP.Labour.label","ولادة"},
{"eIP.Full.label","ممتلىء"},
{"eIP.Jan.label","يناير"},
{"eIP.Feb.label","فبراير"},
{"eIP.Mar.label","مارس"},
{"eIP.Apr.label","أبريل"},
{"eIP.Jun.label","يونيو"},
{"eIP.Jul.label","يوليو"},
{"eIP.Aug.label","أغسطس"},
{"eIP.Sep.label","سبتمبر"},
{"eIP.Oct.label","أكتوبر"},
{"eIP.Nov.label","نوفمبر"},
{"eIP.May.label","مايو"},
{"eIP.Dec.label","ديسمبر"},
{"eIP.DaysOverstayed.label","أيام تجاوز مدة الإقامة"},
{"eIP.RefType.label","نوع المرجع"},
{"eIP.RefLocn.label","موقع المرجع "},
{"eIP.RefSplty.label","مرجع التخصص"},
{"eIP.RefPract.label","مرجع الممارس طبي"},
{"eIP.Occup.label","اشغل"},
{"eIP.morbidity&mortality.label","وفيات بسبب المرض"},
{"eIP.mortality.label","معدل الوفيات"},
{"eIP.deathsbynationality.label","الوفاة حسب الجنسية"},
{"eIP.externalcauseofdeath.label","سبب الوفاة الخارجي"},
{"eIP.agerange.label","الفئة العمرية"},
{"eIP.Reasonforbooking.label","سبب الحجز"},
{"eIP.Reasonforrevision.label","سبب المراجعة"},
{"eIP.IntraHospitalBooking.label","حجز داخل المستشفى"},
{"eIP.ExternalHospitalBooking.label","حجز المستشفى الخارجي"},
{"eIP.AdmnMonth.label","حالات الدخول بالشهر"},
{"eIP.AverageInPatientsPerDay.label","متوسط ​​عدد المرضى المنومين في اليوم"},
{"eIP.BedCapacity.label","عدد الأسرة"},
{"eIP.BedComplement.label","مكمل للسرير"},
{"eIP.BedOccupancyRate.label","معدل إشغال السرير"},
{"eIP.Deaths.label","حالات الوفاة"},
{"eIP.DischargeMonth.label","حالات الخروج بالشهر"},
{"eIP.Discharges.label","حالات الخروج"},
{"eIP.Diseases.label","الأمراض"},
{"eIP.ExcludingDeaths.label","باستثناء الوفيات"},
{"eIP.HospitalAdmissions.label","الإقامة في المستشفى"},
{"eIP.HospitalDischarges.label","الخروج من المستشفى"},
{"eIP.HospitalStatistics.label","إحصائيات المستشفى"},
{"eIP.IncludingDeaths.label","بما في ذلك الوفيات"},
{"eIP.IPBDTNAT_REPORT_TEXT1.label","حالات الخروج (متضمن الوفيات) (متضمن الولادات و حديثي الولادة) حسب العمر والجنس"},
{"eIP.MeanLengthofStay.label","متوسط ​​مدة الإقامة"},
{"eIP.OfficialBedStrength.label","تحمل السرير الرسمي"},
{"eIP.TotalBedCountDays.label","إجمالي عدد أيام السرير"},
{"eIP.TotalInPatientServiceDays.label","إجمالي أيام خدمة المرضى المنومين"},
{"eIP.TotalLengthofStay.label","إجمالي مدة الإقامة"},
{"eIP.RequestingClinic.label","العيادة مقدمة الطلب"},
{"eIP.RequestingName.label","اسم مقدم الطلب"},
{"eIP.Blue.label","أزرق"},
{"eIP.White.label","أبيض"},
{"eIP.Red.label","أحمر"},
{"eIP.PatientWristBandLabel.label","ملصق المعصم للمريض"},
{"eIP.ExcludeNonPDA.label","مرضى لهم امر خروج"},
{"eIP.DsplyDisPatLst.label","عرض قائمة مرضى الخروج"},
{"eIP.AllPatients.label","كل المرضى"},
{"eIP.OnlyPatPDA.label","فقط للمريض مع نصيحة الخروج"},
{"eIP.DischargebillPrepared.label","إعداد فاتورة الخروج"},
{"eIP.CheckForPendingOrdersBerforeDischargeAdvice.label","تحقق من الأوامر المعلقة قبل إشعار الخروج"},
{"eIP.IfOrdersArePending.label","إذا كانت الطلبات معلقة"},
{"eIP.DonotallowdischargeAdvice.label","لا تسمح بنصيحة الخروج من الخدمة"},
{"eIP.AllowDischargeAdvice.label","السماح بأمر الخروج"},
{"eIP.SlNo.label","الرقم التسلسلي"},
{"eIP.ReportName.label","اسم التقرير"},
{"eIP.Count.label","عدد"},
{"eIP.TotNoInPat.label","إجمالي عدد المرضى المنومين"},
{"eIP.TotNoForPat.label","العدد الإجمالي للمرضى الأجانب"},
{"eIP.TotNoDisAdvPat.label","العدد الإجمالي لأوامر الخروج التي تم إعدادها"},
{"eIP.TotNoCorPat.label","إجمالي عدد مرضى المؤسسات"},
{"eIP.TotNoInsPat.label","إجمالي عدد مرضى التأمين"},
{"eIP.TotNoFrePat.label","العدد الإجمالي لمرضى الحالات المجانية"},
{"eIP.TotNoCasPat.label","إجمالي عدد مرضى الدفع النقدي"},
{"eIP.ConsentText.label","نص الموافقة"},
{"eIP.FutureAppointments.label","عرض الحجوزات / المواعيد المستقبلية"},
{"eIP.inpatientbookings.label","حجوزات المرضى الداخليين"},
{"eIP.CheckForPendingOrdersBerforeDischarge.label","تحقق من الأوامر المعلقة قبل الخروج"},
{"eIP.Donotallowdischarge.label","لا تسمح بالخروج"},
{"eIP.AllowDischarge.label","السماح بالخروج"},
{"eIP.AllowReasonForLateDischarge.label","السماح بإدخال اسباب خروج متأخر"},
{"eIP.ReasonForLateDischarge.label","سبب الخروج المتأخر"},
{"eIP.Mandatory.label","إلزامي"},
{"eIP.NotMandatory.label","غير إلزامي"},
{"eIP.otherReason.label","سبب آخر"},
{"eIP.CancelledDateTime.label","تم إلغاءه التاريخ / الوقت"},
{"eIP.AlertReadmitPatient.label","تنبيه إعادة إدخال للمريض خلال"},
{"eIP.ConfigureFloor.label","تكوين الطابق"},
{"eIP.ConfigureRooms.label","تعريف الغرف"},
{"eIP.ConfigureBeds.label","تعريف الأسرة"},
{"eIP.ConfigureColors.label","تعريف أبعاد السرير"},
{"eIP.SurgeryOrder.label","ترتيب الجراحة"},
{"eIP.SurgeryDate.label","تاريخ الجراحة"},
{"eIP.InpatientDetails.label","تفاصيل المرضى الداخليين"},
{"eIP.GeneralDetails.label","تفاصيل عامة"},
{"eIP.DefaultReferringPractitioner.label","ممارس الإحالة الافتراضي عند الإحالة من موقع المريض"},
{"eIP.LoginPractitioner.label","ممارس طبي تسجيل الدخول"},
{"eIP.TransferWODelink.label","السماح بالنقل بدون فك ارتباط الطفل"},
{"eIP.PreDischargeApplicable.label","تمكين بدء الخروج "},
{"eIP.PreDischargeInitiated.label","تم بدأ الخروج"},
{"eIP.ArrivedDateTime.label","تاريخ / وقت الوصول"},
{"eIP.ReasonForAdmMandatory.label","سبب الدخول إلزامي"},
{"eIP.Readmissionwithin.label","إعادة الدخول خلال"},
{"eIP.Daysofdischarge.label","أيام الخروج"},
{"eIP.AllowMultipleBedsideReview.label","السماح بمراجعة الإحالة المتعددة بجانب المريض"},
{"eIP.SeenandTobeReviewedAgain.label","تمت مشاهدتها وستتم مراجعتها مرة أخرى"},
{"eIP.SeenandClosed.label","تم رؤيته وأغلق"},
{"eIP.WeightOnAdmission.label","الوزن عند الدخول"},
{"eIP.History.label","تاريخ"},
{"eIP.PerformedBy.label","تم تأديتها بواسطة"},
{"eIP.Performed.label","وقت و تاريخ التنفيذ"},
{"eIP.NotSeenandClosed.label","لم يتم رؤيته وأغلق"},
{"eIP.RestrictReserveBedinIntraWardTrnsfr.label","تقييد الحجز للتحويلات الداخلية"},
{"eIP.EnableRecordingofReferralLetterNotewithReferralRequest.label","تمكين تسجيل ملاحظة خطاب الإحالة مع طلب الإحالة"},
{"eIP.CheckInDate.label","تاريخ تسجيل الدخول"},
{"eIP.ReleaseBookedBedForAdmission.label","حرر السرير المحجوز إذا تم إدخاله في سرير آخر"},
{"eIP.RestrictDischargeAdviceForPendingReturns.label","منع أمر الخروج إذا كان إرجاع الدواء مازال معلقًا"},
{"eIP.RemovedDoneby.label","تمت إزالته / تم بواسطة"},
{"eIP.PlannedAdmission.label","دخول مخطط له"},
{"eIP.DateOfPlannedAdmission.label","تاريخ الدخول المخطط له"},
{"eIP.InformedDtlsMand.label","اجعل التفاصيل المستنيرة إلزامية"},
{"eIP.AutoCnrmTfrReq.label","طلب تأكيد تلقائي للنقل"},
{"eIP.InformedName.label","اسم المعرف"},
{"eIP.CensusBed.label","سرير التعداد"},
{"eIP.DispBedClsChangeRec.label","عرض تفاصيل تفويض تغيير فئة السرير في تفاصيل الزيارة الحالي وسجل الدخول"},
{"eIP.BlockedBy.label","حجب من قبل"},
{"eIP.PsychiatryForm.label","PF"},
{"eIP.AllowUserToModifyDischargeTypeStatus.label","تعديل نوع / حالة الخروج"},
{"eIP.Keep.label","احتفظ"},
{"eIP.RestrictDischargePatientIfBTOrdersPending.label","تقييد مريض الخروج إذا كانت أوامر فاتورة معلقة"},
{"eIP.RestrictTransferForUnfinalizedNewbornRecords.label","تقييد تحويل المواليد في حال عدم الإنتهاء من تسجيله"},
{"eIP.AssistedBy.label","بمساعدة"},
{"eIP.WitnessedBy1.label","شاهد 1"},
{"eIP.WitnessedBy2.label","شاهد 2"},
{"eIP.ItemOnLoan.label","عناصر على قرض"},
{"eIP.MedicalCertificateNumber.label","رقم الشهادة الطبية (MC)"},
{"eIP.ValidateNatIDDurIPAdmsn.label","التحقق من وجود الهوية الوطنية قبل قبول دخول"},
{"eIP.RestrictDischargeAdviceIfSaleReturnPending.label","تقييد أمر الخروج إذا كان هناك صرف أو إرتجاع غير مكتمل"},
{"eIP.RestrictIfOTRecordsPending.label","تقييد"},
{"eIP.Allowgatepassinpredisadvice.label","السماح بإدخال تصريح مرور في إعداد أمر الخروج"},
{"eIP.EnableDischargeDiagInPrepareDischargeAdvice.label","تمكين إدخال التشخيص في إعداد أمر الخروج"},
{"eIP.HeightOnAdmission.label","الارتفاع عند الدخول"},
{"eIP.EnableHeightandBmiforPatienClass.label","تمكين الارتفاع عند الدخول ومؤشر كتلة الجسم لفئة المريض"},
{"eIP.DaycareandInpatient.label","المرضى الداخليين ورعاية اليوم الواحد"},
{"eIP.OtherHospital.label"," مستشفى أخرى"},
{"eIP.DischargeTo.label"," الخروج إلى "},
{"eIP.VacantNormalBeds.label","آسرة طبيعية شاغرة"}, 
{"eIP.OccupiedNormalBeds.label","آسرة طبيعية مشغولة"}, 
{"eIP.VacantPseudoBabyBeds.label","آسرة وهمية/ آسرة أطفال  شاغرة"}, 
{"eIP.OccupiedPseudoBabyBeds.label","آسرة وهمية/ آسرة أطفال مشغولة"},
{"eIP.Readmission.label","إعادة الدخول"},
{"eIP.AdmissionApprovalDtls.label","تفاصيل موافقه الدخول"}, //Added by Suji Keerthi for MMS-DM-CRF-0191 ON DEC 2021 
{"eIP.CoderClearance.label","تخليص المبرمج"},  
{"eIP.DischargeBill.label","فاتورة التفريغ"}, 
// Added by lakshmanan for ML-MMOH-CRF-1972 US007 on 07/07/2023 start 
{"eIP.ReasonForCancellation.label","سبب الالغاء"}, 
{"eIP.CancelledBy.label","ألغى بواسطة"}, 
{"eIP.CancelForAdmission.label","إلغاء للقبول"},  
// Added by lakshmanan for ML-MMOH-CRF-1972 US007 on 07/07/2023 end 
{"eIP.DischargeClearance.label","تصريح التفريغ"} ,
{"eIP.DischargeAdvicePending.label","إشعار التسريح معلق"},  
{"eIP.DischargeAdvicePrepared.label","تم إعداد نصيحة الخروج"}

	};
}
