/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eRS.resources;

import java.util.*;

public class Labels extends ListResourceBundle
{
	public Object[][] getContents() 
	{
         return contents;
    }

	static final Object[][] contents = 
	{
		{"eRS.GradeLevel.label","Grade Level"},
		{"eRS.FTWorkHours.label","FT Work Hours"},
		{"eRS.GradeDescription.label","Grade Description"},
		{"eRS.GradeCode.label","Grade Code"},
		{"eRS.ConsiderForScheduling.label","Consider For Scheduling"},
		{"eRS.Level.label","Level"},
		{"eRS.ConsiderforScheduling.label","Consider for Scheduling"},
		{"eRS.FindGrade.label","Find Grade"},
		{"eRS.TrainingCode.label","Training Code"},
		{"eRS.FTHours.label","FTHours"},
		{"eRS.TrainingDescription.label","Training Description"},
		{"eRS.SkillCode.label","Skill Code"},
		{"eRS.SkillDescription.label","Skill Description"},
		{"eRS.Skill.label","Skill"},
		{"eRS.LicenseCode.label","License Code"},
		{"eRS.LicenseDescription.label","License Description"},
		{"eRS.StaffReviewOption.label","Staff Review Option"},
		{"eRS.WorkplaceCode.label","Workplace Code"},
		{"eRS.WorkplaceDescription.label","Workplace Description"},
		{"eRS.OperatingHours.label","Operating Hours"},
		{"eRS.From(hh:mi).label","From (hh:mi)"},
		{"eRS.To(hh:mi).label","To (hh:mi)"},
		{"eRS.WorkingDays.label","Working Days"},
		{"eRS.Non-WorkingDays.label","Non-Working Days"},
		{"eRS.Holidays.label","Holidays"},
		{"eRS.StaffUtilizationReviewOption.label","Staff Utilization Review Option"},
		{"eRS.DependencyBasedFTE.label","Dependency Based FTE"},
		{"eRS.FTE.label","FTE"},
		{"eRS.StafftoBedRatio.label","Staff to Bed Ratio"},
		{"eRS.StafftoPatientRatio.label","Staff to Patient Ratio"},
		{"eRS.OperatingDaysApplicabilityfortheWorkCycle.label","Operating Days Applicability for the Work Cycle"},
		{"eRS.WDay.label","WDay"},
		{"eRS.NWDay.label","NWDay"},
		{"eRS.HDay.label","HDay"},
		{"eRS.ByPosition.label","By Position"},
		{"eRS.BySkill.label","By Skill"},
		{"eRS.PositionCode.label","Position Code"},
		{"eRS.PositionDescription.label","Position Description"},
		{"eRS.StaffType.label","Staff Type"},
		{"eRS.Staff.label","Staff"},
		{"eRS.SkillForPosition.label","Skill For Position"},
		{"eRS.StaffId.label","Staff Id"},
		{"eRS.ProficiencyLevel.label","Proficiency Level"},
		{"eRS.FromDate.label","From-Date"},
		{"eRS.To-Date.label","To-Date"},
		{"eRS.TrainingProgram.label","Training Program"},
		{"eRS.Organisation.label","Organisation"},
		{"eRS.IssueDate.label","Issue Date"},
		{"eRS.Grade.label","Grade"},
		{"eRS.LicenseType.label","License Type"},
		{"eRS.In-house.label","In-house"},
		{"eRS.Local.label","Local"},
		{"eRS.Overseas.label","Overseas"},
		{"eRS.TrainingType.label","Training Type"},
		{"eRS.Certified.label","Certified"},
		{"eRS.FacilityType.label","Facility Type"},
		{"eRS.StaffProfile.label","Staff Profile"},
		{"eRS.Skills.label","Skills"},
		{"eRS.Experience.label","Experience"},
		{"eRS.Training.label","Training"},
		{"eRS.PrimarySpecialty.label","Primary Specialty"},
		{"eRS.StaffID.label","StaffID"},
		{"eRS.StaffName.label","Staff Name"},
		{"eRS.License.label","License"},
		{"eRS.Visitor.label","Visitor"},
		{"eRS.PartTime.label","Part Time"},
		{"eRS.FullTime.label","Full Time"},
		{"eRS.EmplStatus.label","Empl Status"},
		{"eRS.ExperienceDetails.label","Experience Details"},
		{"eRS.StaffDetails.label","Staff Details"},
		{"eRS.Licensure.label","Licensure"},
		{"eRS.ValidUntill.label","Valid Untill"},
		{"eRS.Organization.label","Organization"},
		{"eRS.StaffOtherDetails.label","Staff Other Details"},
		{"eRS.LicensureDetails.label","Licensure Details"},
		{"eRS.Issue.label","Issue"},
		{"eRS.Specialty.label","Specialty"},
		{"eRS.Tel.label","Tel"},
		{"eRS.Mobile.label","Mobile"},
		{"eRS.PractitionerDetails.label","Practitioner Details"},
		{"eRS.OtherStaffDetails.label","Other Staff Details"},
		{"eRS.Positions.label","Positions"},
		{"eRS.ByWorkplace.label","By Workplace"},
		{"eRS.ByStaff.label","By Staff"},
		{"eRS.StaffProfileSetup.label","StaffProfileSetup"},
		{"eRS.WorkplaceType.label","Workplace Type"},
		{"eRS.Proficiency.label","Proficiency"},
		{"eRS.SkillDetails.label","Skill Details"},
		{"eRS.Program.label","Program"},
		{"eRS.StaffForWorkplace.label","Staff For Workplace"},
		{"eRS.ShiftPattern.label","Shift Pattern"},
		{"eRS.ShiftPatternForWorkplace.label","Shift Pattern For Workplace"},
		{"eRS.ByShiftPattern.label","By Shift Pattern"},
		{"eRS.ShiftPatternID.label","Shift Pattern ID"},
		{"eRS.ShiftPatternDescription.label","Shift Pattern Description"},
		{"eRS.FindShiftPatternForWorkplace.label","Find Shift Pattern For Workplace"},
		{"eRS.WorkCycle.label","Work Cycle"},
		{"eRS.Pattern.label","Pattern"},
		{"eRS.Operating.label","Operating"},
		{"eRS.FindSkillForPosition.label","Find Skill For Position"},
		{"eRS.WorkCycleBasis.label","Work Cycle Basis"},
		{"eRS.Shifts.label","Shifts"},
		{"eRS.Key.label","Key"},
		{"eRS.FindShiftPattern.label","Find ShiftPattern"},
		{"eRS.WorkPlaceAllocation.label","WorkPlaceAllocation"},
		{"eRS.ViewOptions.label","View Options"},
		{"eRS.TotalByWorkPlace.label","Total By WorkPlace"},
		{"eRS.TotalByShift.label","Total By Shift"},
		{"eRS.TotalByPosition.label","Total By Position"},
		{"eRS.WorkplaceAllocationDetails.label","WorkplaceAllocation Details"},
		{"eRS.WorkPlaceRequirement.label","WorkPlaceRequirement"},
		{"eRS.requirement.label","requirement"},
		{"eRS.AllRequirement.label","All Requirement"},
		{"eRS.FeatureRequirement.label","Feature Requirement"},
		{"eRS.FindRequirement.label","Find Requirement"},
		{"eRS.WorkPlaceRequirementQryResult.label","WorkPlaceRequirementQryResult"},
		{"eRS.ByRatio.label","By Ratio"},
		{"eRS.ByFTE.label","By FTE"},
		{"eRS.Opt.label","Opt"},
		{"eRS.WDay.label","W Day"},
		{"eRS.NWDay.label","NW Day"},
		{"eRS.RequirementPeriod.label","Requirement Period"},
		{"eRS.FindWorkplace.label","Find Workplace"},
		{"eRS.RequirementDescription.label","Requirement Description"},
		{"eRS.AllowOverlapofShiftsinaWorkplace.label","Allow Overlap of Shifts in a Workplace"},
		{"eRS.PeriodaheadforWorkSchedulecreation.label","Period ahead for Work Schedule creation"},
		{"eRS.Maximumcontinuousdurationstaffcanwork.label","Maximum continuous duration staff can work"},
		{"eRS.StaffSubstitutionBasis.label","Staff Substitution Basis"},
		{"eRS.WithinsameGrade.label","Within same Grade"},
		{"eRS.LowtoHighGrade.label","Low to High Grade"},
		{"eRS.HightoLowGrade.label","High to Low Grade"},
		{"eRS.AttendanceFeatureRequired.label","Attendance Feature Required"},
		{"eRS.Maxdurationfromstartofshifttomarkattendance.label","Max duration from start of shift to mark attendance"},
		{"eRS.ValidatestaffaccessrightsbyAttendance.label","Validate staff access rights by Attendance"},
		{"eRS.ValidatestaffaccessrightsbyWorkSchedule.label","Validate staff access rights by Work Schedule"},
		{"eRS.Activitiesallowedonactiveshift.label","Activities allowed on active shift"},
		{"eRS.Durationfromstartofshift.label","Duration from start of shift"},
		{"eRS.Allocate.label","Allocate"},
		{"eRS.Swap.label","Swap"},
		{"eRS.Overtime.label","Overtime"},
		{"eRS.MaximumContinuousDurationStaffcanworkHours.label","Maximum Continuous Duration Staff can work Hours"},
		{"eRS.MaximumContinuousDurationStaffcanworkMinutes.label","Maximum Continuous Duration Staff can work Minutes"},
		{"eRS.Re-allocate.label","Re-allocate"},
		{"eRS.CancelSch.label","Cancel Sch"},
		{"eRS.SetUpReq.label","SetUp Req"},
		{"eRS.ShiftIndicator.label","Shift Indicator"},
		{"eRS.ProductiveFlag.label","Productive Flag"},
		{"eRS.ShiftCode.label","Shift Code"},
		{"eRS.ShiftDescription.label","Shift Description"},
		{"eRS.Productivity.label","Productivity"},
		{"eRS.ShiftsforLocation.label","Shifts for Location"},
		{"eRS.ExpiringWithin.label","Expiring Within"},
		{"eRS.ShiftTiming.label","Shift Timing"},
		{"eRS.ShiftPatternDetails.label","Shift Pattern Details"},
		{"eRS.ShiftForWorkplace.label","Shift For Workplace"},
		{"eRS.ByShift.label","By Shift"},
		{"eRS.RosterDetails.label","Roster Details"},
		{"eRS.OncallTimings.label","Oncall Timings"},
		{"eRS.ManageWorkSchedule.label","Manage Work Schedule"},
		{"eRS.WorkplaceID.label","Workplace ID"},
		{"eRS.DurationFrom.label","Duration From"},
		{"eRS.StaffType.label","Staff Type"},
		{"eRS.LicenseID.label","License ID"},
		{"eRS.BelowOptimal.label","Below Optimal"},
		{"eRS.Optimal.label","Optimal"},
		{"eRS.AboveOptimal.label","Above Optimal"},
		{"eRS.ExternelWorkplace(s).label","Externel Workplace(s)"},
		{"eRS.Unavailability.label","Unavailability"},
		{"eRS.AllocateNewShift.label","Allocate New Shift"},
		{"eRS.ViewSchedule.label","View Schedule"},
		{"eRS.End.label","End"},
		{"eRS.ScheduleDate.label","Schedule Date"},
		{"eRS.AlreadyAllocatedShifts.label","Already Allocated Shifts"},
		{"eRS.ChangeShift.label","Change Shift"},
		{"eRS.AllocatedShifts.label","Allocated Shifts"},
		{"eRS.NewShift.label","New Shift"},
		{"eRS.SwapShifts.label","Swap Shifts"},
		{"eRS.TransferShift.label","Transfer Shift"},
		{"eRS.TransferFrom.label","Transfer From"},
		{"eRS.TransferTo.label","Transfer To"},
		{"eRS.RecordOverTime.label","Record OverTime"},
		{"eRS.StaffUnavailability.label","Staff Unavailability"},
		{"eRS.LeavePeriod.label","Leave Period"},
		{"eRS.CancelShifts.label","Cancel Shifts"},
		{"eRS.MasterSchedule.label","Master Schedule"},
		{"eRS.AllStaff.label","All Staff"},
		{"eRS.AllocatedStaff.label","Allocated Staff"},	
		{"eRS.UnproductiveShift.label","Unproductive Shift"},
		{"eRS.Unproductive.label","Unproductive"},
		{"eRS.WorkingShifts.label","Working Shifts"},
		{"eRS.WorkingShift.label","Working Shift"},
		{"eRS.OncallShifts.label","Oncall Shifts"},
		{"eRS.OncallShift.label","Oncall Shift"},
		{"eRS.Oncall.label","Oncall"},
		{"eRS.Over.label","Over"},			
	   	{"eRS.WorkPlace.label","Work Place"},
		{"eRS.MasterScheduleByWorkplaceResultWeeklyFrames.label","Master Schedule By Workplace Result Weekly Frames"},
		{"eRS.DateTo.label","Date To"},
		{"eRS.GenerateWorkSchedule.label","GenerateWorkSchedule"},
		{"eRS.GenerateSchedule.label","Generate Schedule"},
		{"eRS.Working.label","Working"},
		{"eRS.OverTimeDuration.label","OverTime Duration"},
		{"eRS.ReasonforCancellation.label","Reason for Cancellation"},
		{"eRS.CancelSchedule.label","Cancel Schedule"},
		{"eRS.CancelWorkSchedule.label","CancelWorkSchedule"},
		{"eRS.Timings.label","Timings"},
		{"eRS.StepIn.label","Step In"},
		{"eRS.Fixed.label","Fixed"},
		{"eRS.StepOut.label","Step Out"},
		{"eRS.Workplace.label","Workplace"},
		{"eRS.Requirement.label","Requirement"},
		{"eRS.StaffID.label","Staff ID"},
		{"eRS.ShowWorkplaces.label","Show Workplaces"},
		{"eRS.ShowDetails.label","Show Details"},
		{"eRS.GenerateWorkSchedule.label","Generate Work Schedule"},
		{"eRS.SwapWith.label","Swap With"},
		{"eRS.AllWeeks.label","All Weeks"},
		{"eRS.ShowStaff.label","Show Staff"},
		{"eRS.ShowShifts.label","Show Shifts"},
		{"eRS.UnproductiveShifts.label","Unproductive Shifts"},
		{"eRS.ShowShiftPattern.label","Show ShiftPattern"},
		{"eRS.ShowSkills.label","Show Skills"},
		{"eRS.ShowPositions.label","Show Positions"},
		{"eRS.Show Workplace.label","Show Workplace"},
		{"eRS.ShowProfile.label","Show Profile"},
		{"eRS.SetupRequirement.label","Setup Requirement"},
		{"eRS.ManageWorkScheduleCancelLeave","Cancel Leave"},
		{"eRS.ReasonForCancelLeave.label","Reason For Cancel Leave"},
		{"eRS.NoofShifts.label","No. of Shifts"},
		{"eRS.ShiftName.label","Shift Name"}


		};
}

