/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eBL.resources;
import java.util.*;


public class Labels_th extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
		{"eBL.ACCOUNT_CODE.label","รหัสบัญชี"},
		{"eBL.ACTUAL_AMT.label","จำนวนเงิน"},
		{"eBL.ADDITIONAL_FACTOR.label","ส่วนประกอบเพิ่มเติม"},
		{"eBL.AMT_SETTLED.label","จำนวนเงินที่ชำระ"},
		{"eBL.ANNUAL_INCOME.label","รายได้ต่อปี"},
		{"eBL.APPROVAL_CODE.label","รหัสการอนุมัติ"},
		{"eBL.APPROVED_AMT.label","จำนวนเงินที่อนุมัติ"},
		{"eBL.APPROVED_DAY.label","จำนวนวันที่อนุมัติ"},
		{"eBL.AUTH_SCREEN.label","หน้าจอการอนุมัติ"},
		{"eBL.AVAILABLE_PACKAGE.label","ชุดการให้บริการที่สามารถใช้ได้"},
		{"eBL.AVAILED.label","สิทธิประโยชน์"},
		{"eBL.AVAILED_PRICE.label","ราคาที่ได้รับ"},
		{"eBL.BANK_NAME.label","ชื่อธนาคาร"},
		{"eBL.BASE_CHARGE_AMT.label","ราคาขั้นต้น"},
		{"eBL.BASE_QTY.label","จำนวนขั้นต้น"},
		{"eBL.BASE_RATE.label","อัตราขั้นต้น"},
		{"eBL.BASIC_BILLING_GROUP.label","สิทธิค่ารักษาบริการขั้นพื้นฐาน"},
		{"eBL.BILL_DATE.label","วันที่แจ้งหนี้"},
		{"eBL.BILL_DOC_NO.label","หมายเลขใบแจ้งหนี้"},
		{"eBL.BILL_DOC_TYPE.label","ประเภทใบแจ้งหนี้"},
		{"eBL.BILL_NO.label","เลขที่ใบแจ้งหนี้"},
		{"eBL.BILL_SLMT_DTL.label","รายละเอียดการชำระในใบแจ้งหนี้"},
		{"eBL.BILLED_AMT.label","จำนวนเงินแจ้งหนี้"},
		{"eBL.BILLING_GROUP_EXPLANATORY_NOTE.label","การชี้แจงสิทธิ์"},
		{"eBL.BILLING_GROUP_REMARK.label","หมายเหตุสิทธิ์"},
		{"eBL.BILLING_SERVICE_PANEL.label","รายการค่าบริการ/ ชุดการให้บริการ"},
		{"eBL.BRANCH_NAME.label","ชื่อสาขา"},
		{"eBL.CANCEL_AMT.label","จำนวนเงินที่ยกเลิก"},
		{"eBL.CASH_CLOSING_BALANCE.label","สรุปยอดเงินรับสุทธิ"},
		{"eBL.CASH_COUNTER.label","จุดรับชำระเงิน"},
		{"eBL.CASH_COUNTER_LOGOUT.label","ออกจากการใช้ระบบรับชำระเงิน"},
		{"eBL.CASH_INSTR_DATE.label","วันที่ในเช็คเงินสด"},
		{"eBL.CASH_INSTR_REF.label","เลขที่เช็คเงินสด"},
		{"eBL.CASH_INSTR_REMARKS.label","ข้อความในเช็คเงินสด"},
		{"eBL.CASH_OPENING_BALANCE.label","ยอดเงินตั้งต้น"},
		{"eBL.CASH_SLMT_TYPE.label","ประเภทการชำระเงิน"},
		{"eBL.CASHIER_JOURNAL.label","รายงานการรับชำระเงิน"},
		{"eBL.CLOSED_YN.label","ปิด (ใช่/ไม่ใช่)"},
		{"eBL.CLOSING_DATE_TIME.label","วัน และเวลาปิดรอบการรับชำระเงิน"},
		{"eBL.CONFIRMATION_OF_BILLING_GROUP.label","ยืนยันการใช้สิทธิ์"},
		{"eBL.COPAY_INDICATOR.label","เครื่องหมายบ่งชี้ว่าเป็นค่าใช้จ่ายเพิ่มเติมของผู้รับบริการ"},
		{"eBL.COPAY_VALUE.label","ค่าใช้จ่ายเพิ่มเติมโดยผู้รับบริการ"},
		{"eBL.CREDIT_AUTH_DATE.label","วันที่อนุมัติการผ่อนชำระ"},
		{"eBL.CREDIT_AUTH_REF.label","ข้อมูลอ้างอิงการอนุมัติการผ่อนชำระ"},
		{"eBL.CREDIT_AUTH.label","การอนุมัติการผ่อนชำระ"},
		{"eBL.CREDIT_CARD_CO.label","บริษัทบัตรเครดิต"},
		{"eBL.CREDIT_DOC_DATE.label","วันที่เอกสารการผ่อนชำระ"},
		{"eBL.CREDIT_DOC_DESC.label","คำอธิบายเอกสารการผ่อนชำระ"},
		{"eBL.CREDIT_DOC_REF.label","ข้อมูลอ้างอิงเอกสารการผ่อนชำระ"},
		{"eBL.CUSTOMER_DTL.label","รายละเอียดต้นสังกัด"},
		{"eBL.CUSTOMER_GROUP.label","ประเภทต้นสังกัด"},
		{"eBL.CUSTOMER_PAYABLE_AMT.label","จำนวนเงินค้างชำระของต้นสังกัด"},
		{"eBL.DAY_TYPE_CODE.label","รหัสประเภทวัน"},
		{"eBL.DISCOUNT_PERC.label","ส่วนลด (%)"},
		{"eBL.DISC_PERC_ON_CURR_PRICE.label","ส่วนลด (%) จากราคาปัจจุบัน"},
		{"eBL.DISC_PERC_ON_PROP_PRICE.label","ส่วนลด (%) ตามสัดส่วนของราคา"},
		{"eBL.DISCOUNT_AMT.label","ส่วนลด (บาท)"},
		{"eBL.DISCREPANCY_AMT.label","ผลต่าง (บาท)"},
		{"eBL.DOC_AMT.label","จำนวนเงิน"},
		{"eBL.DOC_END_DATE.label","วันที่สิ้นสุดของเอกสาร"},
		{"eBL.DOC_REF.label","ข้อมูลอ้างอิง"},
		{"eBL.DOC_START_DATE.label","วันที่เริ่มต้นของเอกสาร"},
		{"eBL.ELIG_LEVEL.label","ระดับของสิทธิ์"},
		{"eBL.EMPLOYER_NAME.label","ชื่อนายจ้าง"},
		{"eBL.EXCLUSION_SERVICE.label","รายการที่ไม่รวม"},
		{"eBL.EXT_ALLOWED.label","ผู้ป่วยจากโรงพยาบาลอื่น"},
		{"eBL.FAMILY_ASSET.label","ทรัพย์สินสุทธิของครอบครัว"},
		{"eBL.GL_HOLDER_NAME_NRIC.label","GL Holder Name/NRIC"},
		{"eBL.GOVT_REFERRAL.label","ข้อมูลอ้างอิงทางราชการ"},
		{"eBL.GROSS_AMT.label","จำนวนเงินขั้นต้น"},
		{"eBL.GROSS_CHARGE.label","จำนวนเงินที่ต้องชำระ"},
		{"eBL.GROSS_CHARGE_AMT.label","จำนวนเงินที่ต้องชำระ"},
		{"eBL.HOSPITAL_REQUEST.label","คำร้องของโรงพยาบาล"},
		{"eBL.ILLNESS_DEDUCTIBLE.label","Illness Deductible"},
		{"eBL.INCLUSION_SERVICE.label","รายการที่รวม"},
		{"eBL.IP_ALLOWED.label","ผู้ป่วยใน"},
		{"eBL.INSTR_DATE.label","วันที่ในเช็คเงินสด"},
		{"eBL.INSTR_REF.label","เลขที่เช็คเงินสด"},
		{"eBL.INSTR_REMARK.label","ข้อความในเช็คเงินสด"},
		{"eBL.INS_DTL.label","รายละเอียดการประกัน"},
		{"eBL.INS_DTL_DOC_REF.label","รายละเอียดการประกัน/ เอกสารอ้างอิง"},
		{"eBL.LOGGED_IN_USER.label","ผู้ใช้ระบบ"},
		{"eBL.LOGIN_DATE_TIME.label","วัน และเวลาเข้าใช้ระบบ"},
		{"eBL.LOGOUT_DATE_TIME.label","วัน และเวลาออกจากระบบ"},
		{"eBL.NET_CHARGE.label","ค่าบริการสุทธิ"},
		{"eBL.NO_OF_DEPENDANTS.label","จำนวนผู้อยู่ในความปกครอง"},
		{"eBL.NON_INS_BILLING_GROUP.label","	Non Insurance Billing Group"},
		{"eBL.NON_INS_CUSTOMER_CODE.label","Non Insurance Customer Code"},
		{"eBL.NON_INS_FRAME_TITLE.label","Non-Insurance Settlement Details / Document References"},
		{"eBL.ONLINE_APPROVAL.label","อนุมัติผ่านระบบ"},
		{"eBL.OP_EMG_ALLOWED.label","ผู้ป่วยนอก/ ฉุกเฉิน"},
		{"eBL.OPERATOR_ID.label","หมายเลขผู้ปฏิบัติงาน"},
		{"eBL.OTHER_SERVICE_AMT.label","ค่าบริการอื่น"},
		{"eBL.PACKAGE_BILL.label","ใบแจ้งหนี้ของชุดการให้บริการ"},
		{"eBL.PKG_BILL_NUM_DATE.label","เลขที่ และวันที่ใบแจ้งหนี้ของชุดการให้บริการ"},
		{"eBL.PACKAGE_BILL_REF.label","ข้อมูลอ้างอิงชุดการให้บริการ"},
		{"eBL.PKG_BILL_TYPE.label","ประเภทใบแจ้งหนี้ของขุดการให้บริการ"},
		{"eBL.PACKAGE_DTL.label","รายละเอียดชุดการให้บริการ"},
		{"eBL.PKG_PRICE.label","ราคาของชุดการให้บริการ"},
		{"eBL.PAID_AMT.label","รับชำระทั้งสิ้น"},
		{"eBL.PATIENT_HCARD_NOT_AVAILABLE_EXPIRED.label","บัตรหมดอายุ"},
		{"eBL.PATIENT_REMARK.label","ข้อคิดเห็น"},
		{"eBL.PATIENT_REQUEST.label","คำร้องของผู้ป่วย"},
		{"eBL.PAYABLE_AMT.label","จำนวนเงินค้างชำระ"},
		{"eBL.PAYER_NAME.label","ชื่อต้นสังกัด"},
		{"eBL.PAYER_REF_ID.label","เลขที่อ้างอิงต้นสังกัด"},
		{"eBL.POLICY.label","กรมธรรม์"},
		{"eBL.POLICY_DTL.label","รายละเอียดของกรมธรรม์"},
		{"eBL.POLICY_EXPIRY_DATE.label","วันหมดอายุของกรมธรรม์"},
		{"eBL.POLICY_NO.label","เลขที่กรมธรรม์"},
		{"eBL.POLICY_TYPE.label","ประเภทกรมธรรม์"},
		{"eBL.POLICY_TYPE_CODE.label","รหัสประเภทกรมธรรม์"},
		{"eBL.PRE_APP_YN.label","อนุมัติ?"},
		{"eBL.PRICE_CLASS_CUST_SPECIFIC.label","Price Class/Customer Specific"},
		{"eBL.PVT_REFERRAL.label","ข้อมูลอ้างอิงทางเอกชน"},
		{"eBL.RECEIPT_AMT.label","จำนวนเงินในใบเสร็จ"},
		{"eBL.RECEIPT_TIME.label","เวลาในใบเสร็จ"},
		{"eBL.RECEIPT_TYPE.label","ประเภทใบเสร็จ"},
		{"eBL.REFUND.label","คืนเงิน"},
		{"eBL.RELATIONSHIP_WITH_GL_HOLDER.label","Relationship with GL Holder"},
		{"eBL.HIGHER_CLASS_CHARGE_BASIS_TITLE.label","Request for Higher Class and Associated Charging Basis"},
		{"eBL.RESPONSIBLE_FOR_PAYMENT.label","ความรับผิดชอบในการชำระหนี้"},
		{"eBL.SALE_DRAFT_NO.label","เลขที่ตั๋วเงินขาย"},
		{"eBL.SELF_PAY_BILL_AMT.label","จำนวนเงินที่ผู้ป่วยต้องชำระ"},
		{"eBL.SLMT.label","การชำระเงิน"},
		{"eBL.SLMT_CLOSING_DTL.label","รายละเอียดสุดท้ายของการรับชำระ"},
		{"eBL.SLMT_DTL_DOC_REF.label","รายละเอียด/ เอกสารการรับชำระ"},
		{"eBL.SLMT_INDICATOR.label","ข้อบ่งชี้ในการรับชำระ"},
		{"eBL.SHIFT_STARTED_BY.label","เวลาเริ่มต้นรอบการปฏิบัติงาน"},
		{"eBL.TIME_TYPE_CODE.label","รหัสประเภทเวลา"},
		{"eBL.TOTAL_SLMT.label","ยอดรับชำระทั้งหมด"},
		{"eBL.UNBILLED_AMT.label","จำนวนเงินที่ยังไม่ได้แจ้งหนี้"},//TBMC-SCF-0101 & 162 & 164 added on 06-Mar-20
		{"eBL.UPDATE_PATIENT_FIN_DTL.label","แก้ไขรายละเอียดการชำระของผู้ป่วย"},
		{"eBL.VALID_DAYS.label","ระยะเวลาคุ้มครอง"},
		{"eBL.VALUE_QTY.label","มูลค่า/จำนวน"},
		{"eBL.VISIT_CHARGE_DTL.label","รายละเอียดค่าบริการ"},
		{"eBL.VISIT_DEDUCTIBLE.label","Visit Deductible"},
		{"eBL.ADD_SERV_PRICE.label","Additional Service Price"},
		{"eBL.ADD_SERV_QTY.label","Additional Service Qty"},
		{"eBL.BLNG_SERV_CODE.label","Billing Service Code"},
		{"eBL.SERV_PRICE.label","Service Price"},
		{"eBL.PKG_VAL_QTY.label","Package Value/Qty"},
		{"eBL.APPLY_REFUND.label","Apply Refund"},
		{"eBL.EXPLANATORY_NOTE.label","Explanatory Note"},
		{"eBL.VALID_DOCUMENTS.label","Valid Documents"},
		{"eBL.VALID_FROM.label","Valid From"},
		{"eBL.VALID_TO.label","Valid To"},
		{"eBL.RELATIONSHIP_CODE.label","relationship_code"},
		{"eBL.LONG_DESCRIPTION.label","long_desc"},
		{"eBL.RELATIONSHIPS.label","Relationships"},
		{"eBL.CASH_SETTLEMENT.label","Cash Settlement"},
		{"eBL.USER_SEARCH.label","User Search"},
		{"eBL.RECEIPT_TYPES.label","Receipt Types"},
		{"eBL.ACCOUNT_CODES.label","Account Codes"},
		{"eBL.ACCOUNTING_DEPT.label","Accounting Departments"},
		{"eBL.CREDIT_CARD_COMP_NAMES.label","Credit Card Company Names"},
		{"eBL.SUBMIT_REPORT.label","Submit Report"},
		{"eBL.VIEW_CASHIER_JOURNAL.label","View Cashier journal"},
		{"eBL.CLOSE_CASH_COUNTER.label","Close Cash Counter"},
		{"eBL.CASHIER_SETTLEMENTS.label","Cashier Settlements"},
		{"eBL.BED_TYPE_FOR_CHARGING_BASIS","Bed Type for Charging Basis"},
		{"eBL.CASH_COUNTER_USER.label","Cash Counter User"},
		{"eBL.CASH_COUNTER_SEARCH.label","Cash Counter Search"},
		{"eBL.CASH_COUNTER_CODE.label","Cash Counter Code"},
		{"eBL.CASH_COUNTER_USER_SEARCH.label","Cash Counter User Search"},
		{"eBL.LOGIN_TIME.label","Login Time"},
		{"eBL.LOGOUT_TIME.label","Logout Time"},
		{"eBL.CASH_COUNTER_IS_FILTERED_FOR.label","Cash Counter is Filtered for"},
		{"eBL.CASH_COUNTER_IN_USAGE_LIST.label","Cash Counter in Usage List"},
		{"eBL.CASH_COUNTER_LOGIN.label","Cash Counter Login"},
		{"eBL.LOGGEDIN_USER_COUNTER_DTLS.label","Logged In User/Counter Details"},
		{"eBL.SHIFT_STARTED_AT.label","Shift Started At"},
		{"eBL.CONFIRM_LOGIN.label","Confirm Login"},
		{"eBL.PRIMARY_BILLING_GROUP.label","Primary Billing Group"},
		{"eBL.FAMILY_ANNUAL_INCOME.label","Family Annual Income"},
		{"eBL.PATIENT_RELN_WITH_RESP_PERSON.label","Patient Reln with Responsible Person"},
		{"eBL.GL_HOLDER_NAME.label","GL Holder Name"},
		{"eBL.PATIENT_RELN_WITH_GL_HOLDER.label","Patient Reln with GL Holder"},
		{"eBL.PAYER_POLICY_DTLS.label","Payers/Policy Details"},
		{"eBL.IN_USE_BY.label","In Use By"},
		{"eBL.CANCELLED_COUNT.label","Cancelled Count"},
		{"eBL.BOUNCED_COUNT.label","Bounced Count"},
		{"eBL.NOS.label","Nos"},
		{"eBL.ADD_MORE_PAYERS.label","Add More Payers"},
		{"eBL.SETTLEMENT_WISE_COLLECTION.label","Settlement-wise Collection"},
		{"eBL.PAYER_GROUP_DESC.label","Payer Group Description"},
		{"eBL.ADJUSTMENT_RULE_INDICATOR.label","Adjustment Rule Indicator"},
		{"eBL.PERC_AMOUNT_INDICATOR.label","%/Amount Indicator"},
		{"eBL.ADJUSTMENT_VALUE.label","Adjustment Value"},
		{"eBL.ADJUSTMENT_INTERFACE_CODE.label","Adjustment Interface Code"},
		{"eBL.DRG_ADJUSTMENET_INTERFACE_CODE.label","DRG Adjustmenet Interface Code"},
		{"eBL.SPL_SERVICE_ADJUSTMENT_INTERFACE_CODE.label","Spl Service Adjustment Interface Code"},
		{"eBL.FIN_DTLS_QRY.label","Financial Details Query"},
		{"eBL.PAT_ENCOUNTER_FIN_DTLS.label","Patient/Encounter Financial Details"},
		{"eBL.PATIENT_FIN_DTLS.label","Patient Financial Details"},
		{"eBL.ENCOUNTER_FIN_DTLS.label","Encounter Financial Details"},
		{"eBL.FINANCIAL_REMARKS.label","Financial Remarks"},	
		{"eBL.SERVICE_DISC_AMT.label","Service Discount Amt"},
		{"eBL.OTHER_DISC_AMT.label","Other Discount Amt"},
		{"eBL.DEPOSIT_AMT.label","Deposit Amt"},
		{"eBL.SURGERY_DEPOSIT_AMT.label","Surgery Deposit Amt"},
		{"eBL.REFUNDABLE_DEPOSIT_AMT.label","Refundable Deposit Amt"},
		{"eBL.PACKAGE_DEPOSIT_AMT.label","Package Deposit Amt"},
		{"eBL.PREPAYMENT_AMT.label","Prepayment Amt"},
		{"eBL.UNADJUSTED_DEPOSIT_PREPAYMENT.label","Unadjusted Deposit/Pre-Payment"},
		{"eBL.EDIT_ENTER_CHARGE_DETAILS.label","Edit/Enter Charge Details"},
		{"eBL.RATE.label","Rate"},
		{"eBL.TOTAL_QTY.label","Total Quantity"},
		{"eBL.REVISE_QTY.label","Revise Quantity"},
		{"eBL.TOTAL_PAYABLE.label","Total Payable"},
		{"eBL.ADD_PAYER.label","Add Payer"},
		{"eBL.MODIFY_PAYER.label","Modify Payer"},
		{"eBL.REMOVE_PAYER.label","Remove Payer"},
		{"eBL.INCLUDED_EXCLUDED.label","Included/Excluded"},
		{"eBL.INCLUDED_EXCLUDED_ACTION.label","Included/Excluded Action"},
		{"eBL.ORIG_QTY_PER_PANEL.label","Original Quantity per Panel"},
		{"eBL.REVISED_QTY_PER_PANEL.label","Revised Quantity per Panel"},
		{"eBL.RATE_CHARGE.label","Rate/Charge"},
		{"eBL.PRACT_STAFF_TYPE.label","Practitioner/Staff Type"},
		{"eBL.PRACTITIONER_STAFF.label","Practitioner/Staff"},
		{"eBL.PREAPPR_REQD.label","Preapproved Reqd"},
		{"eBL.POLICY_START_DATE.label","Policy Start Date"},
		{"eBL.POLICY_EFFECTIVE_FROM.label","Policy Effective From"},
		{"eBL.POLICY_EFFECTIVE_TO.label","Policy Effective To"},
		{"eBL.ADD_MORE_SECONDARY_BILLING_GROUPS.label","Add More Secondary Billing Groups"},
		{"eBL.VISIT_CHRG_EXEMPT_UPTO.label","Visit charge exempted upto"},
		{"eBL.VISIT_CHRG.label","Visit charge"},
		{"eBL.PLS_NOTE_DOWN_THE_BILL.label","Please note down the bill"},
		{"eBL.FOR_THE_VISIT_CHRG.label","for the visit charge"},
		{"eBL.HOSP_CHRG.label","Hospital Charge"},
		{"eBL.PROF_CHRG.label","Professional Charge"},
		{"eBL.PAYER_CODE.label","Payer Code"},
		{"eBL.PAYER_DESC.label","Payer Description"},
		{"eBL.PAYER_GROUP_CODE.label","Payer Group Code"},
		{"eBL.CASH_GIVEN.label","Cash Given"},
		{"eBL.CASH_RETURNED.label","Cash Returned"},
		{"eBL.RECD_THRU_MAIL.label","Received through mail"},
		{"eBL.ADD_CHARGE_DETAILS.label","Add Charge Details"},
		{"eBL.EDIT_CHARGE_DETAILS.label","Edit Charge Details"},
		{"eBL.REMOVE_CHARGE_DETAILS.label","Remove Charge Details"},
		{"eBL.ADD_BILL_SLMT_DTL.label","Add Bill Settlements Details"},
		{"eBL.MODI_BILL_SLMT_DTL.label","Modify Bill Settlements Details"},
		{"eBL.REMOVE_BILL_SLMT_DTL.label","Remove Bill Settlements Details"},
		{"eBL.SLMT_AMT.label","Settlement Amount"},
		{"eBL.AMT_COLL.label","Amount Collected"},
		{"eBL.REM_SLMT_AMT.label","Remaining Settlement Amount"},
		{"eBL.ADJUST_DEPOSIT.label","Adjust Deposit"},
		{"eBL.ADJUSTED_DEPOSIT.label","Adjusted Deposit"},
		{"eBL.PAYABLE_AMT_EXCEED.label","Payable Amount Exceeding"},
		{"eBL.INTERIM_BILL_GEN_FREQ_EVERY.label","Interim Bill Generation Frequency Every"},
		{"eBL.CURR_IPS.label","Current Inpatients"},
		{"eBL.PAYABLE_TYPE.label","Payable Type"},
		{"eBL.ANY.label","Any"},
		{"eBL.PENDING_SETTLEMENT.label","Pending Settlement"},
		{"eBL.CURRENT_SETTLEMENT.label","Current Settlement"},
		{"eBL.SETTLED_AMOUNT.label","Settled Amount"},
		{"eBL.SETTLEMENT_BY_SERVICES.label","Settlement By Services"},
		{"eBL.LOGIN_TIME_SEARCH.label","Login Time Search"},
		{"eBL.POLICY_COVERAGE_BASIS_IND.label","Policy Coverage Basis Indicator"},
		{"eBL.PATIENT_BASED.label","Patient Based"},
		{"eBL.PAYER_BASED.label","Payer Based"},
		{"eBL.ADJUST_PREPAY.label","Adjust Prepay"},
		{"eBL.BILL_GENERATED.label","Bill Generated"},
		{"eBL.NOT_GENERATED_FOR_DAYS.label","Not Generated For Days"},
		{"eBL.EXEMPT_AMOUNT.label","Exempt Amount"},
		{"eBL.EXEMPTION_AMOUNT.label","Exemption Amount"},
		{"eBL.ADJUST_AMT.label","Adjust Amount"},
		{"eBL.ADJUSTMENT_AMT.label","Adjustment Amount"},
		{"eBL.WRITOFF_ROUND.label","Write-off Amt Rounded"},
		{"eBL.SERVICE_DATE.label","Service Date"},
		{"eBL.BILL_CHARGE_DET.label","Bill Charge Details"},
		{"eBL.UNBILLED_CHARGE_DET.label","UnBilled Charge Details"},
		{"eBL.CASHIER.label","Cashier"},
		{"eBL.RECEIVED_BACK_ON.label","Received Back On"},
		{"eBL.REMAINDER.label","Remainder"},
		{"eBL.PRIMARY_PRIVILEGE.label","Primary Privilege"},
		{"eBL.PRIMARY_PAYER.label","Primary Payer"},
		{"eBL.ADJUSTMENT_DETAILS.label","Adjustment Details"},
		{"eBL.EXEMPTION_DETAILS.label","Exemption Details"},
		{"eBL.REMAINDER_DETAILS.label","Remainder Details"},
		{"eBL.WRITE_OFF_DETAILS.label","Write-off Details"},
		{"eBL.PAT_ENCOUNTER_DETAILS.label","Patient Encounter Details"},
		{"eBL.PRV_ENCOUNTER_FIN_DETAILS.label","Previous Encounters Financial Details"},
		{"eBL.CAPTURE_REF_SOURCE_DTL.label","Capture Referral Source"},
		{"eBL.PMY_REF_SRC.label","Primary Referral Source"},
		{"eBL.SEC_REF_SRC.label","Secondary Referral Source"},
		{"eBL.SEL_FRM_PREV_ENC.label","Select From Previous Encounters"},
		{"eBL.REFERRAL_LINK.label","Referral Link"},
		{"eBL.CASH.label","Cash"},
		{"eBL.CREDIT.label","Credit"},
		{"eBL.SPONSOR.label","Sponsor"},
		{"eBL.UPD_PAT_FIN_DTLS_VALIDATE.label","Update Patient Financial Details - CheckList"},
		{"eBL.PREREQ_UPD_PAT_FIN_DTLS.label","Prerequisite - For Updating Patient Level Financial Details"},
		{"eBL.NON_INS_CUSTOMER.label","Non Insurance Customer"},
		{"eBL.SEC_INS_BLNG_GRP.label","Secondary Insurance Billing Group(s)"},
		{"eBL.PRIO_1_INS_PYR.label","Priority 1 Insurance Payer"},
		{"eBL.OTH_INS_PYR.label","Other Insurance Payer(s)"},
		{"eBL.CASH_REFUNDED.label","Cash Refunded"},
		{"eBL.GET_CC_INFO.label","Get CC Info"},
		{"eBL.FROM_ADM_NO.label","From Admission No"},
		{"eBL.TO_ADM_NO.label","To Admission No"},
		{"eBL.LAST_BED_CHARGE_DATE.label","Last Bed Charge Date"},
		{"eBL.UNADJUST_AMT.label","Unadjust Amount"},
		{"eBL.SUBMIT_BED_CHARGE_PROCESS.label","Submit Bed Charge Process"},
		{"eBL.PRMY_REF_SRC_MAND.label","Primary Referral Source Mandatory"},
		{"eBL.SEC_REF_SRC_MAND.label","Secondary Referral Source Mandatory"},
		{"eBL.OUTSTANDING_BILLED_AMT.label","Outstanding Billed Amount"},
		{"eBL.CUST_GROUP_CODE.label","Customer Group Code"},
		{"eBL.CHQ_CARD_BANK_NO.label","Cheque / Card / Bank A/C No."},
		{"eBL.PAYER_DEP_REF_NO.label","Payer Ref Id / Deposit Ref No."},
		{"eBL.SERVICE_GROUP.label","Service Group"},
		{"eBL.PANEL_CATEGORY.label","Panel Category"},
		{"eBL.SERVICE_CLASSIFICATION.label","Service Classification"},
		{"eBL.APPRL.label","Apprl"},
		{"eBL.EXIST_SERV_PANEL.label","Existing Service/Panel"},
		{"eBL.ENT_SERV_PANEL_REQ.label","Enter Service/Panel Request"},
		{"eBL.ADDL_SERV_PANEL.label","Additional Service/Panel"},
		{"eBL.PLACE_SERV_PANEL_REQ.label","Place Service/Panel Request"},
		{"eBL.R_C.label","R/C"},
		{"eBL.VIEW_EDIT.label","View/Edit"},
		{"eBL.PLS_NOTE_TRX_REF_NO.label","Please note the Transaction Reference No. :- "},
		{"eBL.PAYER_GROUP.label","Payer Group"},
		{"eBL.ADM_DEP.label","Admission Deposit"},
		{"eBL.REC_NATURE.label","Receipt Nature"},
		{"eBL.RECEIPT_REFUND.label","Receipt/Refund"},
		{"eBL.DEPOSIT_TYPE.label","Deposit Type"},
		{"eBL.THRU_MAIL.label","Thru Mail"},
		{"eBL.TRN_DEP.label","Transfer Deposit"},
		{"eBL.OTH_DEP.label","Other Deposit"},
		{"eBL.ADDL_CHARGE.label","Additional Charge"},
		{"eBL.CURR_CODE.label","Currency Code"},
		{"eBL.CURR_DESC.label","Currency Description"},
		{"eBL.PAT_PAY_SIM_MES_1.label","Patient Payable Amt simulated above is calculated based on the Availed Approved Amt by the payers for the current visit details."},
		{"eBL.PAT_PAY_SIM_MES_2.label","On record of Revise Visit Details, Patient Payable amount will be adjusted accordingly if any discrepancy exist."},
		{"eBL.DOC_GEN.label","Please note down the Document Number(s):"},
		{"eBL.REC_ADHOC_DISC.label","Record Adhoc Discount"},
		{"eBL.ADHOC_DISC_AMT.label","Adhoc Discount Amount"},
		{"eBL.ADHOC_DISC_PERC.label","Adhoc Discount %age"},
		{"eBL.ADHOC_DISC_REASON.label","Adhoc Discount Reason"},
		{"eBL.ACT_GROSS_AMT.label","Actual Gross Amount"},
		{"eBL.USE_PREV_REASON.label","Use Previous Reason"},
		{"eBL.USE_DEFAULT_REASON.label","Use Default Reason"},//Added by Karthik for AMS-SCF-0170 
		{"eBL.DISC_FOR_ENC_CHARGE_DTLS.label","Discount for Encounter Charge Details"},
		{"eBL.DISC_SLMT_FOR_ENC_CHARGE_DTLS.label","Discount/Settlement for Encounter Charge Details"},
		{"eBL.ADDL_SERV_CHAGE_DTLS.label","Additional Service Charge Details"},
		{"eBL.DEPENDENT_SERVICE.label","Dependent Service"},
		{"eBL.DISC_AMT.label","Disc Amt"},
		{"eBL.VIEW_ADDL_CHARGE_DTL.label","View Additional Charge Details"},
		{"eBL.VISIT_BILL_GEN_AFTER_DISC.label","Pls note down the Visit Bill No. Generated after Discount(s):"},
		{"eBL.RECORD_ADDL_SUR_CHARGES.label","Record Additional Surgery Charges"},
		{"eBL.VW_SUBS_OPEN_PACKAGE_DTL.label","View Subscribed Open Package Details"},
		{"eBL.SUBS_OPEN_PACKAGE_DTL.label","Subscribed Open Package Dtls"},
		{"eBL.PKG_DESC.label","Package Description"},			
		{"eBL.PKG_AMT.label","Package Amount"},			
		{"eBL.AVAILD_AMT.label","Availed Amount"},			
		{"eBL.PKG_COMPONENT.label","Package Components"},			
		{"eBL.QTY_LMT.label","Quantity Limit"},			
		{"eBL.AVAILD_QTY.label","Availed Quantity"},			
		{"eBL.AMT_LMT.label","Amount Limit"},
		{"eBL.AVAILD_PACK_DTLS.label","Availed Package Details"},
		{"eBL.CHARGE_FOR_MAIN_SERV.label","Charge for Main Service"},
		{"eBL.CHARGE_FOR_ADDL_SERV.label","Charge For Additional Service"},
		{"eBL.INVALID_ADDL_SERV.label","Invalid Additional Service"},
		{"eBL.IS_SPL_CLINIC_ENC_YN.label","Special Clinic Related Encounter"},
		{"eBL.MAX_NO_OF_ENC_ALLOW_FOR_CREDIT_DOC.label","Maximum No.of Encounters allowed for the Credit Doc Reference"},
		{"eBL.CLASS_TYPE.label","Classification Type"},
		{"eBL.CLASS_CODE.label","Classification Code"},
		{"eBL.CASH_PAY_PAT.label","Cash Paying Patient"},
		{"eBL.INCOME_ASSET.label","Income/Asset"},
		{"eBL.INCOME_ASSET_BASED.label","Income/Asset Based"},
		{"eBL.EXEMPTED.label","Exempted"},
		{"eBL.SOCIAL_GRANT.label","Social Grant"},
		{"eBL.INCOME_ASSET_BASED.label","Income/Asset Based"},
		{"eBL.SPECIAL_CASE.label","Special Case"},
		{"eBL.SPONSORED.label","Sponsored"},
		{"eBL.INCOME.label","Income"},
		{"eBL.ASSET.label","Asset"},
		{"eBL.INDVL_INC_FREQ.label","Individual Income Frequency"},
		{"eBL.SPOUSE_INC_FREQ.label","Spouse Income Frequency"},
		{"eBL.DEP_INC_FREQ.label","Dependents Income Frequency"},
		{"eBL.FIN_CLASS.label","Financial Classification"},
		{"eBL.SOCIAL_PENSIONER_ID.label","Social Pensioner Id"},
		{"eBL.WRITOFF_AMT.label","Write-off Amount"},
		{"eBL.INSTLMT_DUE_AMT.label","Installment Due Amount"},
		{"eBL.CHRG_NON_CHRG_PAT_DUR_ENC.label","Charge Non-Chargeable Patient during Encounter"},
		{"eBL.PAT_REG_CHARGE_BILL_GEN.label","Please note down the bill # for the Patient Registration Charge % Patient Payable &"},
		{"eBL.PAT_REG_CHRG.label","Patient Registration Charge"},
		{"eBL.SERV_PANEL_CODE.label","Service/Panel Code"},
		{"eBL.SERV_PANEL_DESC.label","Service/Panel Description"},
		{"eBL.BLNG_GRP_DESC.label","Billing Group Description"},
		{"eBL.INV_AMT.label","Invoiced Amount"},
		{"eBL.AUTOMATIC.label","Automatic"},
		{"eBL.CURR_IP.label","Current Inpatients"},
		{"eBL.TOD_EXP_DISCHRG.label","Expected Discharges for the Day"},
		{"eBL.TOD_DISCHRGD_PAT.label","Discharged Patients for the Day"},
		{"eBL.BILL_PYMT_DTLS.label","Bill/Payment Details"},
		{"eBL.FIN_SUMM_BY_BG.label","Fin. Summary by Billing Group"},
		{"eBL.FIN_SUMM_BY_PYR.label","Fin. Summary by Payer"},
		{"eBL.NO_OF_DAYS_OCCU_FORECAST.label","No. of Days Occupancy Forecast is Required"},
		{"eBL.EXPECTED_IP.label","Expected Inpatients"},
		{"eBL.OUTST_PAT_BILLS.label","Outstanding Patient Bill(s)"},
		{"eBL.CREDIT_CARD_NO.label","Credit Card No."},
		{"eBL.ROUND_OFF.label","Round-Off"},
		{"eBL.CHARGE_DTL.label","Charge Details"},
		{"eBL.FOR_THE_CHRG.label","for the charges"} ,
		{"eBL.CASH_IN_HAND.label","Cash in Hand"},
		{"eBL.CHQ_IN_HAND.label","Cheque in Hand"},
		{"eBL.CASH_HANDED_OVER.label","Cash Handed Over"},
		{"eBL.DENO.label","Denominations"},
		{"eBL.NUM.label","Number"},
		{"eBL.CHEQ_NUM.label","Cheq No"},
		{"eBL.CHEQ_DATE.label","Cheq Date"},
		{"eBL.CASH_COLLECTION.label","Cash Collection"},
		{"eBL.CHEQ_COLLECTION.label","Cheque Collection"},
		{"eBL.HAND_OVER_REQ_AMT.label","Hand Over Request Amount"},
		{"eBL.NOS.label","Nos."},
		{"eBL.CHEQUE.label","Cheque"},
		{"eBL.REQ_DATE_TIME.label","Requested Date Time"},
		{"eBL.TRANS_DTLS.label","Transcation Details"},
		{"eBL.CASH_CHEQ_COLL_DTLS.label","Cash/Cheque Collection Details"},
		{"eBL.CASH_DTLS.label","Cash Details"},
		{"eBL.CHEQ_DTLS.label","Cheque Details"},
		{"eBL.OP_OVERRIDE_REIM_DTLS.label","Modify OP/EXT Bill Reimbursable Amt"},
		{"eBL.IP_OVERRIDE_REIM_DTLS.label","Modify IP Bill Reimbursable Amt"},
		{"eBL.OP_OVERRIDE_UNBLD_REIM_DTLS.label","Modify OP/EXT Unbilled Reimbursable Amt"},
		{"eBL.IP_OVERRIDE_UNBLD_REIM_DTLS.label","Modify IP Unbilled Reimbursable Amt"},
		{"eBL.LIST_OF_SERV.label","List of Services"},
		{"eBL.DFND_REIMB.label","Defined Reimbursable"},
		{"eBL.DFN_REIMB_TYPE.label","Defined Reimbursable Type"},
		{"eBL.DFN_REIMB_AMT.label","Defined Reimbursable Amount"},
		{"eBL.CURR_REIMB.label","Current Reimbursable"},
		{"eBL.CURR_REIMB_TYPE.label","Current Reimbursable Type"},
		{"eBL.REVISED_AMT.label","Revised Amount"},
		{"eBL.FULL.label","Full"},
		{"eBL.PART.label","Part"},
		{"eBL.NA.label","N/A"},
		{"eBL.AUDIT_DTLS.label","Audit Details"},
		{"eBL.AUDIT_NO.label","Audit No"},
		{"eBL.OLD_REIMB.label","Old Reimbursable"},
		{"eBL.OLD_REIMB_TYPE.label","Old Reimbursable Type"},
		{"eBL.OLD_REIMB_AMT.label","Old Reimbursable Amount"},
		{"eBL.NEW_REIMB.label","New Reimbursable"},
		{"eBL.NEW_REIMB_TYPE.label","New Reimbursable Type"},
		{"eBL.NEW_REIMB_AMT.label","New Reimbursable Amount"},
		{"eBL.OVERRIDING_REASON.label","Overriding Reason"},
		{"eBL.HO_AMOUNT.label","HO Aamount"},
		{"eBL.REG_BILL_GEN_AFTER_DISC.label","Pls note down the Registration Bill No. Generated after Discounts:"},
		{"eBL.CHRG_DUR_ENC.label","Chargeable at Encounter"},
		{"eBL.DISC_FOR_REG_CHARGE_DTLS.label","Discount for Registration Charge Details"},
		{"eBL.CHAR_AT_REG.label","Chargeable at Registration"},
		{"eBL.LAST_MOD_DATE_TIME.label","Last Modified Date/Time"},
		{"eBL.EX.label","EX"},
		{"eBL.RateBased.label","Rate Based"},
		{"eBL.AmountIndicator.label","Amount Indicator"},
		{"eBL.FactorRate.label","Factor/Rate"},
		{"eBL.NoLimit.label","No Limit"},
		{"eBL.Dtls.label","Dtls"},
		{"eBL.PERCENT.label","%"},
		{"eBL.addRow.label","Click to add row"},
		{"eBL.serviceLimit.label","Service Limit"},
		{"eBL.PercentageLimit.label","% Limit"},
		{"eBL.del.label","Del"},
		{"eBL.replaceableService.label","Replaceable Service"},
		{"eBL.replaceableCatalog.label","Replaceable Catalog"},
		{"eBL.orderAssociated.label","Order Associated"},
		{"eBL.AsPerRule.label","As per Rule"},
		{"eBL.Pack_Subs.label","Package Subscription"},
		{"eBL.Subs_pack.label","Subscribe Package"},
		{"eBL.Bill_CLASS_CODE.label","Billing Class Code"} ,
		{"eBL.FACTOR_APPL_SER.label","Factor Applicable For Service"},
		{"eBL.FACTOR.label","Factor"},
		{"eBL.ApplyFactorForServiceLimit.label","Factor applicable for service limit"},
		{"eBL.AcrossEncounters.label","Across Encounters"},
		{"eBL.CashCredit.label","Cash & Credit"},
		{"eBL.Customers.label","Customers"},
		{"eBL.PRICE_FACT.label","Price/Factor"},
		{"eBL.CopyFrom.label","Copy From"},
		{"eBL.CopyTo.label","Copy To"},
		{"eBL.CopyPackage.label","Copy Package"},
		{"eBL.PayerDtls.label","Payer Details"},
		{"eBL.CUSTOMERS_SPECIFIC.label","Customers Specific Price & Coverage"},
		{"eBL.PACKAGE_PRICE_CLASS.label","Package Price Class"},
		{"eBL.OUTSIDE_PACKAGE_PRICE_CLASS.label","Outside Package Price Class"},
		{"eBL.AssociateSubscribedPackage.label","Associate Subscribed Package"},
		{"eBL.APPROVED_DATE.label","Approved Date"},
		{"eBL.UNLIMITED.label","Unlimited"},
		{"eBL.PERC_AMOUNT.label","%/Amount"},
		{"eBL.PRICE_CLASS.label","Price Class"},
		{"eBL.packageApprovalAmt.label","Package Approval Amt"},
		{"eBL.additionalApprovals.label","Additional Approvals"},
		{"eBL.additionalApproval.label","Additional Approval"},
		{"eBL.packageApprovals.label","Package Approvals"},
		{"eBL.packageApproval.label","Package Approval"},
		{"eBL.userGroup.label","User Group"},
		{"eBL.userGroupId.label","User Group Id"},
		{"eBL.userGroupName.label","User Group Name"},
		{"eBL.PackageCreation.label","Package Creation"},
		{"eBL.PackageTransfer.label","Package Transfer"},
		{"eBL.PackageDiscount.label","Package Discount"},
		{"eBL.PackageRefund.label","Package Refund"},
		{"eBL.PackageCancel.label","Package Cancel"},
		{"eBL.InitialCreditAuthorization.label","Initial Credit Authorization"},
		{"eBL.InitialCreditAuthorizationDate.label","Initial Credit Auth Date"},
		{"eBL.ROUND_TO.label","Round-To"},
		{"eBL.ROUND_INDICATOR.label","Round Indicator"},
		{"eBL.DOWN.label","Down"},
		{"eBL.AUTO_REFUND.label","Auto Refund"},
		{"eBL.DEPOSIT.label","Deposit"},
		{"eBL.PARTIAL_DEPOSIT.label","Partial Deposit"},
		{"eBL.MIN_DEPOSIT_AMOUNT.label","Minimum Deposit Amount"},
		{"eBL.PackageCode-Desc-Seqno.label","Package Code-Desc-Seq No"},
		{"eBL.CLOSE_PACKAGE.label","Close Package"},
		{"eBL.packageSeqNo.label","Package Seq No"},
		{"eBL.UtilizedAmt.label","Utilized Amt"},
		{"eBL.BillingClassCode.label","Billing Class Code"},
		{"eBL.BillingClassDesc.label","Billing Class Desc"},		
		{"eBL.RateIndicator.label","Rate Indicator"},	
		{"eBL.RefundRate.label","Refund Rate"},
		{"eBL.UtilizedServiceQty.label","Utilized Service Qty"},
		{"eBL.UtilizedServiceAmt.label","Utilized Service Amt"},
		{"eBL.Excl.label","Excl."},
		{"eBL.RefundAmt.label","Refund Amt"},
		{"eBL.PackageServiceCode.label","Package Service Code"},
		{"eBL.PackageApplicable.label","Package Applicable"},
		{"eBL.PackageEffBackDated.label","Package Efective From Back dated"},
		{"eBL.GLPostingBySmmry.label","GL Posting by Summary"},
		{"eBL.ValidDysPkgSerOrds.label","Validity for Availing Package Service Orders"},
		{"eBL.unavailedSrvCode.label","Unavailed Service Code"},
		{"eBL.AutoRefundApplicable.label","Auto Refund Applicable"},
		{"eBL.ValidDysForPkgRefund.label","Validity for Package Service Refund"},
		{"eBL.fromDateOfBlGen.label","(from the date of bill generation)"},
		{"eBL.AccountingCode.label","Accounting Code"},
		{"eBL.DISC_ACC_CODE.label","Discount Accounting Code"},
		{"eBL.CustomerBasePrice.label","Customer Base Price"},
		{"eBL.CustomerRateBasedServices.label","Customer Rate Based Services"},
		{"eBL.CustomerChargeBasedServices.label","Customer Charge Based Services"},
		{"eBL.PackageRateBaseHdr.label","Package Services(Rate Based)"},
		{"eBL.PackageChargeBaseHdr.label","Package Services(Charge Based)"},
		{"eBL.UtilizedQty.label","Utilized Qty"},
		{"eBL.Refunded.label","Refunded"},
		{"eBL.DEPOSITCOLECTD.label","Deposit Collected"},
		{"eBL.ELIGIBLE.label","Eligible"},
		{"eBL.PLACED.label","Placed"},
		{"eBL.REGISTERED.label","Registered"},
		{"eBL.DISCOUNT_AS_PER_SETUP.label","Discount As per Setup"},
		{"eBL.discountType.label","Discount Type"},
		{"eBL.Discount.label","Discount"},
		{"eBL.Transactionreference.label","Transaction Reference"},
		{"eBL.EXEMPTINPKG.label","Exempt in Package"},
		{"eBL.PAYERCOVERAGE.label","Payer Coverage"},
		{"eBL.PKG_DEP.label","Package Deposit"},
		{"eBL.BLNG_CLASS_ELIG_PKG.label","Billing Class Eligibility for Package"},
		{"eBL.PackageAdhocRefund.label","Package Adhoc Refund"},
		{"eBL.VarianceSrvCode.label","Variance Service Code"},
		{"eBL.RefundRatePer.label","Refund Rate %"},
		{"eBL.CUST_GROUP_DESC.label","Customer Group Desc"},
		{"eBL.CUST_NAME.label","Customer  Name"},
		{"eBL.AvailableServiceAmt.label","Available Service Amt"},
		{"eBL.PatientDepositForPackage.label","Patient Deposit for Package"},
		{"eBL.DISC_APPL.label","Discount Applicable"}
	};
}
