/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eCommon.resources; 

import java.util.*;

public class  Labels_ar  extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    } 

	static final Object[][] contents = {		
{"Common.Abnormalonly.label","غير الطبيعى فقط"},
{"Common.Abort.label","إيقاف"},
{"Common.aboutProduct.label","عن المنتج"},
{"Common.Abscond.label","خروج"},
{"Common.AccessRights.label","صلاحيات الدخول"},
{"Common.AccountingEntity.label","الجهة المحاسبية"},
{"Common.acctdept.label","القسم المحاسبى"},
{"Common.action.label","إجراء"},
{"Common.ActionDateTime.label","تاريخ/وقت الإجراء"},
{"Common.active.label","نشط"},
{"Common.Add.label","إضافة"},
{"Common.AddAssociateCodesfor.label","إضافة أكواد ملحقة ب"},
{"Common.Additional.label","إضافى"},
{"Common.additionaldetails.label","تفاصيل إضافية"},
{"Common.Address.label","العنوان"},
{"Common.AddressDetails.label","تفاصيل العنوان"},
{"Common.adhoc.label","عشوائى"},
{"Common.admission.label","الدخول"},
{"Common.admissiondate.label","تاريخ الدخول"},
{"Common.AdmissionDateTime.label","تاريخ/وقت الدخول"},
{"Common.AdmissionDetails.label","تفاصيل الدخول"},
{"Common.admissiontype.label","نوع الدخول"},
{"Common.admit.label","حجز"},
{"Common.AdmitPatient.label","حجز مريض"},
{"Common.Adult.label","راشد"},
{"Common.After.label","بعد"},
{"Common.age.label","العمر"},
{"Common.agegroup.label","المجموعة العمرية"},
{"Common.agegroupcode.label","كود المجموعة العمرية"},
{"Common.agegroupdesc.label","وصف المجموعة العمرية"},
{"Common.AgeRange.label","المدى العمرى"},
{"Common.all.label","الكل"},
{"Common.AllAccessFacilities.label","صلاحية دخول لكل المنشآت"},
{"Common.AllEncounters.label","كل الزيارات"},
{"Common.Allergies.label","الحساسية"},
{"Common.AllergyDetails.label","تفاصيل الحساسية"},
{"Common.AllergyType.label","نوع الحساسية"},
{"Common.AllFacilities.label","كل المنشآت"},
{"Common.AlphaInfo.label","معلومات"},
{"Common.AlternateID.label","بطاقة هوية بديلة"},
{"Common.Ambulatory.label","متنقل"},
{"Common.ambulatorystatus.label","الوضع الإسعافي/ التنقل"},
{"Common.amount.label","الكمية"},
{"Common.Anaesthesia.label","التخدير"},
{"Common.AnaesthesiaCode.label","كود التخدير"},
{"Common.AnaesthesiaCode.label","كود التخدير"},
{"Common.AnaesthesiaDetails.label","تفاصيل التخدير"},
{"Common.AnaesthesiaDetails.label","تفاصيل التخدير"},
{"Common.Anaesthetist.label","طبيب التخدير"},
{"Common.Anaesthetist.label","طبيب التخدير"},
{"Common.AnatomicalSite.label","المنطقة التشريحية"},
{"Common.and.label","بالإضافة إلى"},
{"Common.Applicability.label","الإتاحة"},
{"Common.Applicable.label","متاح"},
{"Common.ApplicableTo.label","متاح ل"},
{"Common.appluserid.label","بطاقة هوية مستخدم التطبيق"},
{"Common.applusername.label","اسم مستخدم التطبيق"},
{"Common.apply.label","تطبيق"},
{"Common.AppointmentDetails.label","تفاصيل الحجز"},
{"Common.Appointments.label","الحجوزات"},
{"Common.apptdate.label","تاريخ الحجز"},
{"Common.apptno.label","رقم الحجز"},
{"Common.appttime.label","وقت الحجز"},
{"Common.area.label","المنطقة"},
{"Common.AreaCode.label","كود المنطقة"},
{"Common.arrival.label","الوصول"},
{"Common.ArrivalDateTime.label","تاريخ/وقت الوصول"},
{"Common.ascending.label","صاعد"},
{"Common.Ason.label","كما هو"},
{"Common.Assessment.label","تقييم"},
{"Common.assigndatetime.label","تعيين التاريخ / الوقت"},
{"Common.AssignTreatingPractitioner.label","تعيين الطبيب المعالج"},
{"Common.Associate.label","ربط"},
{"Common.AssociateCodesFor.label","أكواد مرتبطة"},
{"Common.AtOwnRisk.label","على مسؤوليتك الخاصة"},
{"Common.AttachedtoPatient.label","ملحق بالمريض"},
{"Common.AttendingPractitioner.label","الطبيب المقيم"},
{"Common.ATTGiven.label","اللقاحات المعطاة"},
{"Common.ATTImmunizationDetails.label","تفاصيل اللقاحات / التطعيم"},
{"Common.Authorize.label","تصريح"},
{"Common.Authorized.label","مصرّح "},
{"Common.authorizedby.label","مصرح له من"},
{"Common.AuthorizingPractitioner.label","ممارس معتمد"},
{"Common.AutoFileRequest.label","طلب ملف تلقائي"},
{"Common.available.label","متاح"},
{"Common.OnlyFirstVisitAvailable.label","الزيارة الأولى فقط"},
{"Common.OnlyOtherVisitAvailable.label","زيارة أخرى فقط"},
{"Common.FirstandOtherVisitAvailable.label","الزيارة الأولى والأخرى"},
{"Common.AvailableFunctions.label","الوظائف المتاحة"},
{"Common.AvailableImages.label","الصور المتاحة"},
{"Common.Back.label","عودة"},
{"Common.Barcode.label","الباركود /الشريط التعريفى"},
{"Common.Scanning.label","مسح"},
{"Common.Bed.label","السرير"},
{"Common.BedClass.label","فئة السرير"},
{"Common.bedno.label","رقم السرير"},
{"Common.BedSideReferral.label","الإحالة من جانب السرير"},
{"Common.bedstatus.label","حالة السرير"},
{"Common.bedtype.label","نوع السرير"},
{"Common.birthDate.label","تاريخ الولادة"},
{"Common.birthPlace.label","مكان الولادة"},
{"Common.block.label","غلق"},
{"Common.blocked.label","مغلق"},
{"Common.blockeduntil.label","محظور حتى"},
{"Common.bloodgroup.label","فصيلة الدم"},
{"Common.BodyReleaseDateTime.label","تاريخ / وقت الإطلاق"},
{"Common.bookappointment.label","حجز موعد"},
{"Common.booked.label","محجوز"},
{"Common.booking.label","حجز"},
{"Common.BookingDate.label","تاريخ الحجز"},
{"Common.Both.label","الكل"},
{"Common.broughtdead.label","متوفى"},
{"Common.broughtindead.label","متوفى"},
{"Common.building.label","مبنى"},
{"Common.BuildingCode.label","كود المبنى"},
{"Common.by.label","بواسطة"},
{"Common.ByFacility.label","حسب المنشأة"},
{"Common.ByUser.label","حسب المستخدم"},
{"Common.Calendar.label","التقويم"},
{"Common.All.label","الكل"},
{"Common.CalendarSelectDate.label","التقويم: حدد التاريخ"},
{"Common.cancel.label","إلغاء"},
{"Common.CancelAdmission.label","إلغاء الدخول"},
{"Common.CancelAppointment.label","إلغاء الموعد"},
{"Common.CancelBooking.label","إلغاء الحجز"},
{"Common.CancelDischargeAdvice.label","إلغاء إشعار الخروج"},
{"Common.Cancellation.label","إلغاء"},
{"Common.cancelled.label","تم الإلغاء بواسطة"},
{"Common.cancelledby.label","ألغى بواسطة"},
{"Common.CancelRequest.label","إلغاء الطلب"},
{"Common.CancelTransfer.label","إلغاء التحويل"},
{"Common.CancelWaitList.label","إلغاء قائمة الانتظار"},
{"Common.CaseofTrauma.label","حالة الإصابة"},
{"Common.catalog.label","فهرس"},
{"Common.category.label","فئة المريض"},
{"Common.category1.label","الفئة"},
{"Common.CategoryCode.label","كود الفئة"},
{"Common.CategoryDescription.label","وصف التصنيف"},
{"Common.CauseIndicator.label","مؤشر السبب"},
{"Common.CensusYear.label","سنة التعداد"},
{"Common.Central.label","وسط"},
{"Common.certificate.label","شهادة"},
{"Common.certificateissued.label","شهادة صادرة"},
{"Common.certificatetype.label","نوع الشهادة"},
{"Common.change.label","تغيير"},
{"Common.changepassword.label","غير كلمة السر"},
{"Common.changePasswordFor.label","تغيير كلمة المرور لـ"},
{"Common.Characteristics.label","مميزات"},
{"Common.CHARTING.label","الرسوم البيانية/ السجلات"},
{"Common.Check.label","فحص"},
{"Common.CheckOut.label","الدفع/ الخروج"},
{"Common.Chief.label","رئيس"},
{"Common.chiefconsultant.label","استشارى رئيسي"},
{"Common.Circumference.label","محيط"},
{"Common.CircumstanceofInjury.label","ظرف الإصابة"},
{"Common.CircumstanceofInjuryCode.label","كود ظرف الإصابة"},
{"Common.citizen.label","مواطن"},
{"Common.Citizenship.label","الجنسية"},
{"Common.Class.label","فئة"},
{"Common.ClassicBlue.label","Classic Blue"},
{"Common.clear.label","محو"},
{"Common.clinic.label","عيادة"},
{"Common.ClinicalComments.label","الملاحظات السريرية"},
{"Common.ClinicalEvent.label","حدث سريري"},
{"Common.ClinicCode.label","كود العيادة"},
{"Common.ClinicDescription.label","وصف العيادة"},
{"Common.close.label","إغلاق"},
{"Common.closeAll.label","إغلاق الكل"},
{"Common.closed.label","مغلق"},
{"Common.cm.label","سم"},
{"Common.code.label","كود"},
{"Common.CodeIndicator.label","مؤشر الكود"},
{"Common.CodeLevel.label","مستوى الكود"},
{"Common.Collapse.label","غلق"},
{"Common.Color.label","اللون"},
{"Common.colortheme.label","اختر نسق اللون"},
{"Common.ColumnHeader.label","رأس العمود"},
{"Common.ColumnPosition.label","موضع العمود"},
{"Common.ColumnSpan.label","مدى العمود"},
{"Common.Comments.label","تعليقات"},
{"Common.Complaint.label","شكوى"},
{"Common.complete.label","اكتمال"},
{"Common.completed.label","مكتمل"},
{"Common.Component.label","مكون"},
{"Common.ComponentDefinition.label","تعريف المكون"},
{"Common.ComponentID.label","كود المكون"},
{"Common.ComponentLookup.label","بحث المكون"},
{"Common.ComponentPrompt.label","موجه المكون"},
{"Common.ComponentType.label","نوع المكون"},
{"Common.CompType.label","نوع الشركة"},
{"Common.CompanyGroup.label","مجموعة شركة"},
{"Common.ConductedBy.label","تم إجرائها بواسطة"},
{"Common.Confidential.label","سري"},
{"Common.confirm.label","تأكيد"},
{"Common.ConfirmBooking.label","تأكيد الحجز"},
{"Common.confirmed.label","تم تأكيد"},
{"Common.ConfirmRevision.label","تأكيد المراجعة"},
{"Common.Consult.label","استشارة"},
{"Common.consultant.label","استشاري"},
{"Common.ConsultingPatient.label","المريض طالب الاستشارة"},
{"Common.contact.label","الاتصال"},
{"Common.ContactDetails.label","بيانات الاتصال"},
{"Common.contactmode.label","وضع الاتصال"},
{"Common.ContactName.label","اسم جهة الاتصال"},
{"Common.contactNo.label","رقم الاتصال."},
{"Common.ContactNoAddr.label","رقم جهة الاتصال"},
{"Common.ContactReason.label","سبب الاتصال"},
{"Common.contains.label","يحتوي على"},
{"Common.Continuous.label","مستمر"},
{"Common.ConversionFactor.label","عامل التحويل"},
{"Common.CoolViolet.label","Cool Violet"},
{"Common.copies.label","نسخ"},
{"Common.count.label","العد"},
{"Common.country.label","الدولة"},
{"Common.CPT4.label","CPT 4"},
{"Common.create.label","إنشاء"},
{"Common.CreateBooking.label","إنشاء الحجز"},
{"Common.Createdby.label","انشأ من قبل"},
{"Common.createddate.label","تاريخ الإنشاء"},
{"Common.CreateWaitList.label","إنشاء قائمة انتظار"},
{"Common.Credential.label","بيانات الهوية"},
{"Common.criteria.label","المعايير"},
{"Common.Critical.label","حرج"},
{"Common.CriticalHighValue.label","قيمة عالية حرجة"},
{"Common.CriticalLowValue.label","قيمة منخفضة حرجة"},
{"Common.current.label","حالى"},
{"Common.currentvalue.label","القيمة الحالية"},
{"Common.CurrentDate.label","التاريخ الحالي"},
{"Common.CurrentDateTime.label","التاريخ / الوقت الحالي"},
{"Common.CurrentEncounter.label","الزيارة الحالية"},
{"Common.CurrentFileStatus.label","حالة الملف الحالي"},
{"Common.CurrentLanguage.label","اللغة الحالية"},
{"Common.currentlocation.label","الموقع الحالي"},
{"Common.CustomerCode.label","كود العميل"},
{"Common.daily.label","يومي"},
{"Common.date.label","تاريخ"},
{"Common.DateFrom.label","التاريخ من"},
{"Common.DateofBirth.label","تاريخ الولادة"},
{"Common.DateRange.label","نطاق التاريخ"},
{"Common.datetime.label","التاريخ / الوقت"},
{"Common.day.label","يوم"},
{"Common.DayAfterDischarge.label","بعد يوم من الخروج"},
{"Common.daycare.label","رعاية نهارية"},
{"Common.DaycareUnit.label","وحدة الرعاية النهارية"},
{"Common.daycareunitcode.label","رمز وحدة الرعاية النهارية"},
{"Common.daycareunitdesc.label","وصف وحدة العناية النهارية"},
{"Common.dayofweek.label","يوم من الأسبوع"},
{"Common.days.label","أيام"},
{"Common.DC.label","DC"},
{"Common.deathdatetime.label","تاريخ / وقت الوفاة"},
{"Common.deceased.label","متوفى"},
{"Common.DeceasedDate.label","تاريخ الوفاة"},
{"Common.deceaseddatetime.label","تاريخ / وقت الوفاة"},
{"Common.deceaseddetails.label","تفاصيل المتوفى"},
{"Common.DecimalNumeric.label","عدد عشري"},
{"Common.Default.label","إفتراضي"},
{"Common.DefaultFileType.label","نوع الملف الافتراضي"},
{"Common.defaultSelect.label","تحديد"},
{"Common.DefaultValue.label","القيمة الافتراضية"},
{"Common.Degree.label","الدرجة"},
{"Common.delete.label","حذف"},
{"Common.Demographics.label","البيانات السكانية"},
{"Common.department.label","قسم"},
{"Common.Departmental.label","إداري"},
{"Common.descending.label","تنازلي"},
{"Common.description.label","وصف"},
{"Common.designation.label","تعيين"},
{"Common.Destination.label","جهة"},
{"Common.Detail.label","التفاصيل"},
{"Common.details.label","تفاصيل"},
{"Common.DetailsofTraining.label","تفاصيل التدريب"},
{"Common.detailsunknown.label","التفاصيل غير معروفة"},
{"Common.diagnosis.label","التشخيص"},
{"Common.DiagnosisCode.label","كود التشخيص"},
{"Common.DiagnosisDescription.label","وصف التشخيص"},
{"Common.DiagnosisDetails.label","تفاصيل التشخيص"},
{"Common.Differential.label","محتمل"},
{"Common.Disabled.label","غير نشط"},
{"Common.Disaster.label","كارثة"},
{"Common.Discharge.label","مغادرة"},
{"Common.DischargeAdvice.label","إشعار الخروج"},
{"Common.discharged.label","خرج"},
{"Common.dischargedate.label","تاريخ الخروج"},
{"Common.dischargedatetime.label","تاريخ / وقت الخروج"},
{"Common.DischargePatient.label","خروج المريض"},
{"Common.dischargetype.label","نوع الخروج"},
{"Common.DiscreteMeasure.label","قياس منفصل"},
{"Common.DiscreteMeasureCode.label","كود قياس منفصل"},
{"Common.DiscreteMeasureDescription.label","وصف قياس منفصل"},
{"Common.Dispensing.label","الصرف"},
{"Common.display.label","عرض"},
{"Common.DisplayDateTime.label","عرض التاريخ / الوقت"},
{"Common.DisplayOnly.label","عرض فقط"},
{"Common.DisplayOrder.label","ترتيب العرض"},
{"Common.DisplayType.label","نوع العرض"},
{"Common.Disposition.label","تغير"},
{"Common.DispType.label","نوع الترتيب"},
{"Common.DocType.label","نوع المستند"},
{"Common.Document.label","مستند"},
{"Common.DocumentDate.label","تاريخ المستند"},
{"Common.documentdetails.label","تفاصيل المستند"},
{"Common.documentno.label","رقم المستند"},
{"Common.DocumentNumber.label","رقم المستند"},
{"Common.documents.label","مستندات"},
{"Common.documenttype.label","نوع المستند"},
{"Common.Dressing.label","ضمادة"},
{"Common.Drug.label","دواء"},
{"Common.duration.label","المدة الزمنية"},
{"Common.DurationType.label","نوع المدة"},
{"Common.Earliest.label","فى أبكر وقت"},
{"Common.ecg.label","رسم القلب"},
{"Common.EDD.label","EDD"},
{"Common.EffectiveDate.label","تاريخ النفاذ"},
{"Common.EffectiveFrom.label","ساري المفعول من"},
{"Common.EffectiveTo.label","ساري المفعول حتى"},
{"Common.EffStatus.label","حالة الفعالية"},
{"Common.Elapsed.label","انقضى"},
{"Common.elective.label","اختياري"},
{"Common.email.label","البريد الإلكتروني"},
{"Common.EmbeddedComponent.label","مكون مضمن"},
{"Common.emergency.label","طوارئ"},
{"Common.EmergencyUnits.label","وحدات الطوارئ"},
{"Common.emergent.label","طارئ"},
{"Common.employeedetails.label","تفاصيل الموظف"},
{"Common.EmployeeNo.label","رقم الموظف"},
{"Common.employer.label","صاحب العمل"},
{"Common.employerdetails.label","تفاصيل صاحب العمل"},
{"Common.employmentdetails.label","تفاصيل العمل"},
{"Common.employmentid.label","معرف العمل"},
{"Common.EmplStatus.label","الحالة الوظيفية"},
{"Common.Enable.label","إتاحة"},
{"Common.enabled.label","متاح"},
{"Common.ShiftOne.label","الفترة الأولى"},
{"Common.ShiftTwo.label","الفترة الثانية"},
{"Common.ShiftThree.label","الفترة الثالثة"},
{"Common.ShiftSummaryRequired.label","ملخص الفترة مطلوب"},
{"Common.NumberOfShifts.label","عدد الورديات"},
{"Common.ShiftDuration.label","مدة الوردية"},
{"Common.encounter.label","زيارة"},
{"Common.encounterdate.label","موعد الزيارة"},
{"Common.encounterdatetime.label","تاريخ / وقت الزيارة"},
{"Common.encounterdetails.label","تفاصيل الزيارة"},
{"Common.encounterid.label","كود الزيارة"},
{"Common.encountertype.label","نوع الزيارة"},
{"Common.enddate.label","تاريخ الانتهاء"},
{"Common.enddatetime.label","تاريخ / وقت الانتهاء"},
{"Common.endsWith.label","ينتهي بـ"},
{"Common.EndTime.label","وقت النهاية"},
{"Common.entereddatetime.label","تم إدخال التاريخ / الوقت"},
{"Common.enterprise.label","المنظمة"},
{"Common.enterprisefacility.label","منشأة المنظمة"},
{"Common.episodeid.label","كود الزيارة"},
{"Common.equipment.label","معدات"},
{"Common.Ethnic.label","عرقي"},
{"Common.Event.label","حدث"},
{"Common.EventClass.label","فئة الحدث"},
{"Common.EventDescription.label","وصف الحدث"},
{"Common.EventType.label","نوع الحدث"},
{"Common.Execute.label","تنفيذ"},
{"Common.ExecuteQuery.label","تنفيذ الاستعلام"},
{"Common.ExpiryBased.label","على أساس انتهاء الصلاحية"},
{"Common.expiryDate.label","تاريخ الانتهاء"},
{"Common.ExpiryPeriod.label","فترة انتهاء الصلاحية"},
{"Common.ExpiryRule.label","قاعدة انتهاء الصلاحية"},
{"Common.ExplanatoryText.label","نص توضيحي"},
{"Common.Ext.label","تمديد"},
{"Common.external.label","خارجي"},
{"Common.externalfacility.label","منشأة خارجية"},
{"Common.ExternalPractitioner.label","ممارس خارجي"},
{"Common.facility.label","منشأة"},
{"Common.FacilityID.label","كود المنشأة"},
{"Common.FacilityName.label","إسم المنشأة"},
{"Common.fax.label","فاكس"},
{"Common.female.label","أنثى"},
{"Common.filecreated.label","تم إنشاء الملف"},
{"Common.FileCreatedDateTime.label","تاريخ / وقت إنشاء الملف"},
{"Common.FileDetails.label","تفاصيل ملف"},
{"Common.fileno.label","رقم الملف."},
{"Common.FileStorageLocation.label","موقع تخزين الملفات"},
{"Common.FileTransportMode.label","وضع نقل الملفات"},
{"Common.filetype.label","نوع الملف"},
{"Common.final.label","نهائي"},
{"Common.financialdetails.label","التفاصيل المالية"},
{"Common.first.label","أول"},
{"Common.firsttonotify.label","أول من يخطر"},
{"Common.firstvisit.label","الزيارة الأولى"},
{"Common.floor.label","الدور"},
{"Common.followup.label","متابعة"},
{"Common.followupdate.label","تاريخ المتابعة"},
{"Common.Food.label","طعام"},
{"Common.for.label","إلى"},
{"Common.Format.label","صيغة"},
{"Common.Formula.label","معادلة"},
{"Common.Frequency.label","تكرار"},
{"Common.FrequencyCode.label","كود التكرار"},
{"Common.FrequencyDescription.label","وصف التكرار"},
{"Common.frequentlyAccessedFunctions.label","الوظائف التي يتم الوصول إليها بشكل متكرر"},
{"Common.fri.label","يوم الجمعة"},
{"Common.from.label","من"},
{"Common.fromdate.label","من تاريخ"},
{"Common.fromdatetime.label","من تاريخ / وقت"},
{"Common.FromNursingUnit.label","من وحدة التمريض"},
{"Common.fromresource.label","من مورد"},
{"Common.fromtime.label","من وقت"},
{"Common.FullName.label","الاسم بالكامل"},
{"Common.Function.label","وظيفة"},
{"Common.FunctionName.label","اسم الوظيفة"},
{"Common.Future.label","مستقبل"},
{"Common.FutureOrders.label","الطلبات المستقبلية"},
{"Common.g6pd.label","G6PD"},
{"Common.gender.label","جنس"},
{"Common.GenderGroup.label","مجموعة الجنس"},
{"Common.GenderSpecificInd.label","خاصة بالجنس"},
{"Common.general.label","عام"},
{"Common.generalRemarks.label","تصريحات او ملاحظات عامه"},
{"Common.generic.label","عام"},
{"Common.givenby.label","معطى بواسطة"},
{"Common.Go.label","تنفيذ"},
{"Common.Government.label","حكومة"},
{"Common.GridComponent.label","مكون الشبكة"},
{"Common.GridComponentDefinition.label","تعريف مكونات الشبكة"},
{"Common.Group.label","مجموعة"},
{"Common.groupby.label","مجموعة من"},
{"Common.GroupDetails.label","تفاصيل المجموعة"},
{"Common.GroupName.label","أسم المجموعة"},
{"Common.Header.label","رأس"},
{"Common.HealthcareSettingType.label","نوع إعداد الرعاية الصحية"},
{"Common.height.label","ارتفاع"},
{"Common.hideMenu.label","إخفاء القائمة"},
{"Common.High.label","عالي"},
{"Common.HighRisk.label","عالى الخطورة"},
{"Common.highriskbody.label","عالى الخطورة"},
{"Common.HighRiskConditions.label","حالات عالية الخطورة"},
{"Common.HighValue.label","قيمة عالية"},
{"Common.HistoryType.label","نوع التاريخ"},
{"Common.Holiday.label","يوم الاجازة"},
{"Common.HolidayDate.label","تاريخ الإجازة"},
{"Common.home.label","الصفحة الرئيسية"},
{"Common.homephoneno.label","رقم هاتف المنزل"},
{"Common.hours.label","ساعات"},
{"Common.ICD.label","التصنيف الدولي للأمراض"},
{"Common.icd10pcs.label","التصنيف الدولي للأمراض 10PCS"},
{"Common.ICD9CM.label","التصنيف الدولي للأمراض 9CM"},
{"Common.identification.label","هوية شخصية"},
{"Common.Identity.label","هوية"},
{"Common.illegal.label","غير شرعي"},
{"Common.IllegalResident.label","مقيم غير شرعي"},
{"Common.ImageDescription.label","وصف الصورة"},
{"Common.Immunizationuptodate.label","تطعيمات محدثة"},
{"Common.in.label","في"},
{"Common.Include.label","تضمين"},
{"Common.IncludeforAnalysis.label","تضمين للتحليل"},
{"Common.incomplete.label","غير مكتمل"},
{"Common.INDICATOR.label","مؤشر"},
{"Common.Individual.label","فردى"},
{"Common.InError.label","عن طريق الخطأ"},
{"Common.InfectiousDisease.label","الأمراض المعدية"},
{"Common.Inhalant.label","المستنشق"},
{"Common.inpatient.label","مريض داخلي"},
{"Common.inpatientbooking.label","حجز المرضى الداخليين"},
{"Common.Inpatients.label","القسم الداخلى"},
{"Common.InProgress.label","في تقدم"},
{"Common.Instructions.label","تعليمات"},
{"Common.IntegerNumeric.label","عدد صحيح"},
{"Common.InterfacetoBillingModule.label","واجهة نظام الفواتير"},
{"Common.Intermediate.label","متوسط"},
{"Common.intern.label","المتدرب"},
{"Common.Internal.label","داخلي"},
{"Common.internalreport.label","التقارير الداخلية"},
{"Common.invalid.label","غير صالحة"},
{"Common.invitationlist.label","قائمة المدعوين"},
{"Common.invitationno.label","رقم الدعوة"},
{"Common.IPOP.label","العيادات الخارجية للمرضى الداخليين"},
{"Common.Isolation.label","عزل"},
{"Common.issuedby.label","صادر عن"},
{"Common.issueddate.label","تاريخ الإصدار"},
{"Common.issueddatetime.label","تاريخ / وقت الإصدار"},
{"Common.item.label","صنف"},
{"Common.ItemCode.label","كود الصنف"},
{"Common.ItemDescription.label","وصف الصنف"},
{"Common.Items.label","الأصناف"},
{"Common.Itemtype.label","نوع الصنف"},
{"Common.JobTitle.label","المسمى الوظيفي"},
{"Common.kg.label","كجم"},
{"Common.Kgs.label","كجم"},
{"Common.Lab.label","مختبر"},
{"Common.Label.label","تسمية"},
{"Common.LabelPosition.label","موضع التسمية"},
{"Common.Laboratory.label","مختبر"},
{"Common.LastRefreshTime.label","وقت التحديث الأخير"},
{"Common.lb.label","رطل"},
{"Common.Lbs.label","رطل"},
{"Common.Leave.label","مغادرة"},
{"Common.LeaveFrom.label","مغادرة من"},
{"Common.LeaveTo.label","مغادرة إلى"},
{"Common.Left.label","اليسار"},
{"Common.legal.label","قانوني"},
{"Common.LegalResident.label","مقيم شرعي"},
{"Common.length.label","الطول"},
{"Common.lesscriteria.label","معايير أقل"},
{"Common.Level.label","مستوى"},
{"Common.LevelDesc.label","وصف المستوى"},
{"Common.levelofcare.label","مستوى الرعاية"},
{"Common.LinkBabyToMother.label","ربط الطفل بالأم"},
{"Common.List.label","قائمة"},
{"Common.ListItem.label","قائمة الاغراض"},
{"Common.ListofGridComponents.label","قائمة مكونات الشبكة"},
{"Common.Location.label","الموقع"},
{"Common.locationcode.label","كود الموقع"},
{"Common.LocationDesc.label","وصف الموقع"},
{"Common.LocationDescription.label","وصف الموقع"},
{"Common.LocationName.label","اسم الموقع"},
{"Common.locationtype.label","نوع الموقع"},
{"Common.Lodger.label","مستأجر"},
{"Common.loggedinfacility.label","منشأة المستخدم"},
{"Common.LoggedUser.label","مستخدم مسجل"},
{"Common.login.label","تسجيل الدخول"},
{"Common.loginfacility.label","منشأة تسجيل الدخول"},
{"Common.logout.label","تسجيل خروج"},
{"Common.longdescription.label","وصف طويل"},
{"Common.longname.label","اسم طويل"},
{"Common.LongText.label","نص طويل"},
{"Common.Low.label","منخفض"},
{"Common.Lower.label","أقل"},
{"Common.LowValue.label","قيمة منخفضة"},
{"Common.mail.label","بريد"},
{"Common.MailingAddress.label","العنوان البريدي"},
{"Common.main.label","الأساسي"},
{"Common.male.label","ذكر"},
{"Common.ManagePatQ.label","إدارة قائمة انتظار المريض"},
{"Common.Mandatory.label","إلزامي"},
{"Common.Manufacturer.label","الشركة المصنعة"},
{"Common.ManufacturerID.label","كود الشركة المصنعة"},
{"Common.ManufacturerName.label","اسم المصنع"},
{"Common.MatrixAttributes.label","سمات المصفوفة"},
{"Common.MatrixColumns.label","أعمدة المصفوفة"},
{"Common.MatrixColumnSpan.label","امتداد عمود المصفوفة"},
{"Common.MatrixComponent.label","مكون المصفوفة"},
{"Common.MatrixDefinition.label","تعريف المصفوفة"},
{"Common.MatrixRows.label","صفوف المصفوفة"},
{"Common.Max.label","أقصي"},
{"Common.MaxAge.label","أقصى عمر"},
{"Common.MaxDischargePeriodforDayCare.label","فترة الخروج القصوى للرعاية النهارية"},
{"Common.maximum.label","أقصى"},
{"Common.maxserialno.label","الرقم التسلسلي الأقصى"},
{"Common.MaxValue.label","القيمة القصوي"},
{"Common.MCNo.label","رقم MC"},
{"Common.MechanismofInjury.label","طريقة الإصابة"},
{"Common.medical.label","طبي"},
{"Common.MedicalEventType.label","نوع الحدث الطبي"},
{"Common.MedicalService.label","الخدمة الطبية"},
{"Common.medicalteam.label","الفريق الطبي"},
{"Common.Member.label","عضو"},
{"Common.Menarche.label","الدورة"},
{"Common.MenstrualHistory.label","تاريخ الدورة"},
{"Common.menu.label","قائمة "},
{"Common.MenuID.label","كود القائمة"},
{"Common.Message.label","رسالة"},
{"Common.midwife.label","قابلة"},
{"Common.MIN.label","دقيقة"},
{"Common.MinAge.label","الحد الأدنى للعمر"},
{"Common.Minimum.label","الحد الأدنى"},
{"Common.Minute.label","دقيقة"},
{"Common.MistyGreen.label","أخضر"},
{"Common.ml.label","مل"},
{"Common.mlc.label","MLC"},
{"Common.mlcdetails.label","تفاصيل MLC"},
{"Common.MobileNo.label","رقم المحمول."},
{"Common.mode.label","طريقة"},
{"Common.ModeofArrival.label","طريقة الوصول"},
{"Common.ModeOfTransport.label","وسيلة النقل"},
{"Common.modifiedby.label","تم التعديل بواسطة"},
{"Common.modifieddatetime.label","تاريخ / وقت التعديل"},
{"Common.Modify.label","تعديل"},
{"Common.ModifyWaitList.label","تعديل قائمة الانتظار"},
{"Common.Module.label","نظام"},
{"Common.ModuleId.label","كود النظلم"},
{"Common.ModuleName.label","اسم النظام"},
{"Common.mon.label","الإثنين"},
{"Common.Monitoring.label","الملاحظة"},
{"Common.month.label","شهر"},
{"Common.monthly.label","شهري"},
{"Common.months.label","الشهور"},
{"Common.morecriteria.label","المزيد من المعايير"},
{"Common.MRSection.label","قسم الملف الطبى"},
{"Common.MRSectionCode.label","رمز قسم الملف الطبى"},
{"Common.MRSectionDesc.label","وصف قسم الملف الطبى"},
{"Common.MRSectionType.label","نوع قسم الملف الطبى"},
{"Common.multiple.label","مضاعف"},
{"Common.name.label","اسم"},
{"Common.NamePrefix.label","لقب"},
{"Common.NameSuffix.label","لاحقة الاسم"},
{"Common.nationality.label","الجنسية"},
{"Common.NationalityCode.label","كود الجنسية"},
{"Common.Nature.label","طبيعة"},
{"Common.New.label","جديد"},
{"Common.newPassword.label","كلمة مرور جديدة"},
{"Common.NewProcedure.label","إجراء جديد"},
{"Common.NewValue.label","قيمة جديدة"},
{"Common.next.label","التالى"},
{"Common.nextofkin.label","التالي من الأقارب"},
{"Common.nextsrlno.label","الرقم المسلسل التالي"},
{"Common.no.label","لا"},
{"Common.noncitizen.label","غير مواطن"},
{"Common.none.label","لا شيء"},
{"Common.nonurgent.label","غير عاجل"},
{"Common.noofbeds.label","لعدد الأسرة"},
{"Common.noofdays.label","عدد الأيام"},
{"Common.Normal.label","طبيعى"},
{"Common.noshow.label","عدم الحضور"},
{"Common.notapplicable.label","لا ينطبق"},
{"Common.notavailable.label","غير متاح"},
{"Common.NotConfirmed.label","غير مؤكد"},
{"Common.note.label","ملاحظة"},
{"Common.notes.label","ملاحظات"},
{"Common.NoteType.label","نوع الملاحظة"},
{"Common.Notifiable.label","قابل للإبلاغ"},
{"Common.notrequired.label","غير مطلوب"},
{"Common.NumericPrefixRequired.label","مطلوب بادئة رقمية"},
{"Common.nurse.label","ممرضة"},
{"Common.Nursing.label","التمريض"},
{"Common.nursingUnit.label","القسم الداخلى"},
{"Common.NursingUnitCode.label","كود القسم الداخلى"},
{"Common.Occupied.label","مشغول"},
{"Common.of.label","من"},
{"Common.office.label","مكتب"},
{"Common.officephoneno.label","رقم هاتف المكتب."},
{"Common.ok.label","موافقة"},
{"Common.oldPassword.label","كلمة سر قديمة"},
{"Common.on.label","على"},
{"Common.onsetdate.label","تاريخ البدء"},
{"Common.OP.label","العمليات"},
{"Common.open.label","افتح"},
{"Common.openAll.label","افتح الكل"},
{"Common.operation.label","عملية"},
{"Common.Operator.label","التشغيل"},
{"Common.operatorstation.label","محطة التشغيل"},
{"Common.Optional.label","اختياري"},
{"Common.Order.label","طلب"},
{"Common.orderBy.label","طلب حسب"},
{"Common.ordercatalog.label","كتالوج الطلب"},
{"Common.OrdercatalogCode.label","كود كتالوج الطلب"},
{"Common.OrderCatalogDesc.label","وصف كتالوج الطلب"},
{"Common.OrderCategory.label","فئة الطلب"},
{"Common.OrderDate.label","تاريخ الطلب"},
{"Common.OrderingPract.label","ترتيب "},
{"Common.Orders.label","الأوامر"},
{"Common.OrderSrlNo.label","الرقم المسلسل للطلب"},
{"Common.OrderStatus.label","حالة الطلب"},
{"Common.OrderType.label","نوع الطلب"},
{"Common.orgName.label","اسم المنظمة"},
{"Common.oscc.label","OSCC"},
{"Common.other.label","آخر"},
{"Common.otheraltid.label","كود بديل آخر"},
{"Common.OtherAltType.label","نوع بديل آخر"},
{"Common.otherDetails.label","تفاصيل أخرى"},
{"Common.OtherRes.label","رقم السكن الآخر"},
{"Common.others.label","أخرى"},
{"Common.OtherStaff.label","موظفين آخرين"},
{"Common.OtherStaffName.label","اسم الموظف"},
{"Common.OtherStaffType.label","نوع الموظف"},
{"Common.othertelno.label","رقم هاتف الموظف"},
{"Common.othervisit.label","زيارة أخرى"},
{"Common.outcome.label","النتيجة"},
{"Common.Outpatient.label","العيادات الخارجية"},
{"Common.Outpatients.label","العيادات الخارجية"},
{"Common.Outstanding.label","غير مدفوعة"},
{"Common.outstandingamount.label","كمية غير مدفوعة"},
{"Common.Overdue.label","متأخر"},
{"Common.override.label","تجاوز"},
{"Common.page.label","الصفحة"},
{"Common.PagerNo.label","رقم النداء"},
{"Common.PanelID.label","كود الباقة"},
{"Common.ParagraphDefinition.label","تعريف الفقرة"},
{"Common.password.label","كلمه السر"},
{"Common.patient.label","مريض"},
{"Common.PatientCare.label","رعاية المرضى"},
{"Common.patientchart.label","مخططات المريض"},
{"Common.patientclass.label","فئة المريض"},
{"Common.PatientClassDescription.label","وصف فئة المريض"},
{"Common.PatientCondition.label","حالة المريض"},
{"Common.PatientDetails.label","تفاصيل المريض"},
{"Common.PatientFileNo.label","رقم ملف المريض."},
{"Common.PatientHistory.label","تاريخ المريض"},
{"Common.patientId.label","رقم المريض"},
{"Common.PatientName.label","اسم المريض"},
{"Common.PatientSeriesGroup.label","مجموعة المريض"},
{"Common.patienttype.label","نوع المريض"},
{"Common.PatientValuables.label","مقتنيات المريض"},
{"Common.Pending.label","قيد الانتظار"},
{"Common.Period.label","فترة"},
{"Common.periodfrom.label","الفترة من"},
{"Common.periodto.label","الفترة إلى"},
{"Common.personalize.label","تخصيص"},
{"Common.personalizeoptions.label","تخصيص الخيارات"},
{"Common.pharmacy.label","صيدلية"},
{"Common.PIN.label","رمز تحقق"},
{"Common.PMRequired.label","مطلوب تشريح الجثة"},
{"Common.police.label","الشرطة"},
{"Common.PoliceReportNo.label","تقرير الشرطة رقم."},
{"Common.Position.label","موضع"},
{"Common.practitioner.label","طبيب"},
{"Common.practitionerid.label","كود الممارس الطبى"},
{"Common.practitionername.label","اسم الممارس الطبى"},
{"Common.PractitionerTransfer.label","نقل ممارس طبى"},
{"Common.practitionertype.label","نوع الممارس الطبى"},
{"Common.PreferredDate.label","موعد مفضل"},
{"Common.PreferredOn.label","يفضل في"},
{"Common.preferredperiod.label","الفترة المفضلة"},
{"Common.PrefMode.label","الوضع المفضل"},
{"Common.PregnantatPresent.label","حامل في الوقت الحاضر"},
{"Common.previous.label","السابق"},
{"Common.PreviousDayVisitsOnly.label","زيارات اليوم السابق فقط"},
{"Common.PreviousEncounters.label","زيارات سابقة"},
{"Common.primary.label","ابتدائي"},
{"Common.primaryspeciality.label","التخصص الأساسي"},
{"Common.print.label","طباعة"},
{"Common.PrintApplicability.label","إمكانية تطبيق الطباعة"},
{"Common.PrintDateTime.label","تاريخ / وقت الطباعة"},
{"Common.priority.label","أفضلية"},
{"Common.Private.label","خاص"},
{"Common.PrivateRoom.label","غرفة خاصة"},
{"Common.Procedure.label","إجراء"},
{"Common.ProcedureCode.label","كود الإجراء"},
{"Common.ProcedureDescription.label","وصف الإجراء"},
{"Common.ProcedureUnit.label","وحدة الإجراءات"},
{"Common.Process.label","معالجة"},
{"Common.processing.label","جارى المعالجة..برجاء الانتظار"},
{"Common.Prompt.label","تنفيذ"},
{"Common.Provisional.label","مبدئي"},
{"Common.QualificationDetails.label","تفاصيل التأهيل"},
{"Common.QualificationTraining.label","التأهيل / التدريب"},
{"Common.Quantity.label","كمية"},
{"Common.query.label","استعلام"},
{"Common.QueryCriteria.label","معايير الاستعلام"},
{"Common.QueueManagement.label","إدارة قائمة الانتظار"},
{"Common.QueueNo.label","رقم الطابور"},
{"Common.QueueStatus.label","حالة قائمة الانتظار"},
{"Common.race.label","العرق"},
{"Common.Radiology.label","الأشعة"},
{"Common.RadiologyWing.label","جناح الأشعة"},
{"Common.Range.label","نطاق"},
{"Common.Reaction.label","رد فعل"},
{"Common.reason.label","السبب"},
{"Common.ReasonCode.label","كود السبب"},
{"Common.ReasonDescription.label","وصف السبب"},
{"Common.ReasonforAdmission.label","سبب القبول"},
{"Common.ReasonforCancellation.label","سبب الالغاء"},
{"Common.ReasonForContact.label","سبب الاتصال"},
{"Common.ReasonForHoliday.label","سبب الإجازة"},
{"Common.ReasonforReferral.label","سبب التحويل"},
{"Common.ReasonforRejection.label","سبب الرفض"},
{"Common.ReasonforRevision.label","سبب المراجعة"},
{"Common.ReasonforVisit.label","سبب الزيارة"},
{"Common.ReassignPract.label","تعيين / إعادة تعيين ممارس"},
{"Common.receiptdate.label","تاريخ الايصال"},
{"Common.receiptno.label","رقم الإيصال."},
{"Common.received.label","تم الاستلام"},
{"Common.ReceivedDate.label","تاريخ الاستلام"},
{"Common.ReceivingDateTime.label","تاريخ / وقت الاستلام"},
{"Common.record.label","تسجيل"},
{"Common.RecordedBy.label","مسجل بواسطة"},
{"Common.recordeddate.label","تاريخ التسجيل"},
{"Common.recordeddatetime.label","تاريخ/ وقت التسجيل"},
{"Common.RecordedOn.label","مسجل في"},
{"Common.Red.label","أحمر"},
{"Common.reEnterNewPassword.label","أعد إدخال كلمة مرور جديدة"},
{"Common.referenceno.label","رقم المرجع."},
{"Common.referral.label","الإحالة"},
{"Common.referraldetails.label","تفاصيل الإحالة"},
{"Common.referralid.label","كود الإحالة"},
{"Common.referralsource.label","مصدر الإحالة"},
{"Common.referraltype.label","نوع الإحالة"},
{"Common.Referred.label","محوّل"},
{"Common.referredby.label","محول من قبل"},
{"Common.referredfor.label","محول إلى"},
{"Common.ReferredOn.label","تم تحويله فى"},
{"Common.ReferredSource.label","مصدر التحويل"},
{"Common.ReferredTo.label","محول إلى"},
{"Common.Refresh.label","تحديث"},
{"Common.RefreshInterval.label","الفاصل الزمني للتحديث"},
{"Common.Register.label","تسجيل"},
{"Common.RegisterAttendance.label","تسجيل الحضور"},
{"Common.RegisterVisit.label","تسجيل الزيارة"},
{"Common.registrar.label","المسجل"},
{"Common.Registration.label","التسجيل"},
{"Common.RegistrationDate.label","تاريخ التسجيل"},
{"Common.registrationno.label","رقم التسجيل."},
{"Common.regndatetime.label","تاريخ / وقت التسجيل"},
{"Common.Regular.label","منتظم"},
{"Common.Rejected.label","مرفوض"},
{"Common.relationship.label","صلة"},
{"Common.Release.label","تحرير"},
{"Common.ReleaseBed.label","تحرير سرير"},
{"Common.religion.label","دين"},
{"Common.ReligionCode.label","كود الدين"},
{"Common.remarks.label","ملاحظات"},
{"Common.Remove.label","إزالة"},
{"Common.RepFacility.label","منشأة الإبلاغ"},
{"Common.report.label","تقرير"},
{"Common.ReportBy.label","تقرير بواسطة"},
{"Common.reportcritera.label","معايير التقرير"},
{"Common.ReportDesc.label","وصف تقرير"},
{"Common.ReportID.label","كود التقرير"},
{"Common.reportname.label","اسم التقرير"},
{"Common.reporttype.label","نوع التقرير"},
{"Common.ReprintAll.label","طبع الكل"},
{"Common.Request.label","طلب"},
{"Common.RequestDate.label","تاريخ الطلب"},
{"Common.Requested.label","تم الطلب"},
{"Common.RequestedBy.label","طلب بواسطة"},
{"Common.requesteddate.label","تاريخ الطلب"},
{"Common.RequestforTransfer.label","طلب نقل"},
{"Common.RequestStatus.label","حالة الطلب"},
{"Common.required.label","مطلوب"},
{"Common.reset.label","إعادة تعيين"},
{"Common.residence.label","إقامة"},
{"Common.residency.label","الإقامة"},
{"Common.resitelno.label","رقم هاتف السكن"},
{"Common.resource.label","الموارد"},
{"Common.resourceclass.label","فئة المورد"},
{"Common.ResourceCode.label","كود المورد"},
{"Common.resourceid.label","معرف المورد"},
{"Common.resourcename.label","اسم المورد"},
{"Common.resourcetype.label","نوع المورد"},
{"Common.responsibility.label","الصلاحية"},
{"Common.ResponsibilityID.label","معرف الصلاحية ID"},
{"Common.ResponsibilityName.label","اسم الصلاحية"},
{"Common.ResTelNo.label","رقم الهاتف"},
{"Common.RestrictTo.label","حصر على"},
{"Common.Result.label","نتيجة"},
{"Common.ResultPage.label","صفحة النتائج"},
{"Common.ResultReporting.label","تقرير النتائج"},
{"Common.ResultTemplate.label","نموذج النتيجة"},
{"Common.ResultType.label","نوع النتيجة"},
{"Common.ResumeActivity.label","استئناف النشاط"},
{"Common.returndatetime.label","تاريخ / وقت العودة"},
{"Common.returned.label","مرتجع"},
{"Common.returnedby.label","تم إرجاعه بواسطة"},
{"Common.revise.label","مراجعة"},
{"Common.revisebooking.label","مراجعة الحجز"},
{"Common.revisedby.label","تمت مراجعته من"},
{"Common.ReviseVisit.label","مراجعة الزيارة"},
{"Common.Revoked.label","إلغاء "},
{"Common.RhFactor.label","عامل RH"},
{"Common.RichGold.label","ذهبى"},
{"Common.Role.label","وظيفة"},
{"Common.RoleType.label","نوع الوظيفة"},
{"Common.room.label","غرفة"},
{"Common.RoomCubicle.label","غرفة "},
{"Common.roomcubicleno.label","رقم الغرفة "},
{"Common.RoomCubicleStatus.label","حالة الغرفة "},
{"Common.roomno.label","رقم الغرفة"},
{"Common.RootMenu.label","قائمة رئيسية"},
{"Common.routine.label","نمط"},
{"Common.rule.label","قاعدة"},
{"Common.run.label","تنفيذ"},
{"Common.sat.label","السبت"},
{"Common.Schedule.label","جدولة"},
{"Common.scheme.label","مخطط"},
{"Common.Score.label","نتيجة"},
{"Common.search.label","بحث"},
{"Common.searchby.label","البحث عن طريق"},
{"Common.SearchCriteria.label","معايير البحث"},
{"Common.searchIn.label","بحث في"},
{"Common.SearchPatient.label","بحث المرضي"},
{"Common.searchtext.label","نص البحث"},
{"Common.SearchUser.label","مستخدم البحث"},
{"Common.SearchVisit.label","البحث عن زيارة"},
{"Common.secondary.label","ثانوي"},
{"Common.Section.label","القسم"},
{"Common.SectionCode.label","كود القسم"},
{"Common.SectionDescription.label","وصف القسم"},
{"Common.selectall.label","اختر الكل"},
{"Common.SelectLanguage.label","اختار اللغة"},
{"Common.self.label","الذات"},
{"Common.SemiCritical.label","شبه حرج"},
{"Common.semiemergency.label","شبه طارىء"},
{"Common.SemiPrivateRoom.label","غرفة شبه خاصة"},
{"Common.semiurgent.label","شبه عاجل"},
{"Common.seniorconsultant.label","استشارى"},
{"Common.seniorspecialist.label","أخصائى"},
{"Common.Sensitive.label","حساس"},
{"Common.SensitiveDiagnosis.label","التشخيص الحساس"},
{"Common.SequenceNo.label","رقم التسلسل"},
{"Common.SerialNo.label","الرقم التسلسلي."},
{"Common.Series.label","سلسلة"},
{"Common.service.label","الخدمات"},
{"Common.ServiceCode.label","كود الخدمة"},
{"Common.ServiceDescription.label","وصف الخدمة"},
{"Common.setup.label","إعداد"},
{"Common.setupfreqaccesslist.label","إعداد قائمة المستخدم"},
{"Common.SHIFT.label","نوبتجية"},
{"Common.shortdescription.label","وصف قصير"},
{"Common.shortname.label","اسم قصير"},
{"Common.ShortText.label","نص قصير"},
{"Common.sicc.label","SICC"},
{"Common.Signature.label","التوقيع"},
{"Common.Stamp.label","طابع"},    //
{"Common.significant.label","مهم"},
{"Common.since.label","منذ"},
{"Common.single.label","غير مرتبط"},
{"Common.Site.label","موقع"},
{"Common.Smoking.label","تدخين"},
{"Common.SortOrder.label","امر ترتيب"},
{"Common.soundex.label","Soundex"},
{"Common.source.label","مصدر"},
{"Common.specialist.label","متخصص"},
{"Common.SpecialistClinic.label","العيادة التخصصية"},
{"Common.speciality.label","تخصص"},
{"Common.SpecialityCode.label","كود التخصص"},
{"Common.specific.label","محدد"},
{"Common.Start.label","ابدأ"},
{"Common.StartConsult.label","بدء الاستشارة"},
{"Common.StartDate.label","تاريخ البدء"},
{"Common.startdatetime.label","تاريخ / وقت البدء"},
{"Common.startsWith.label","يبدأ بـ"},
{"Common.StartTime.label","وقت البدء"},
{"Common.station.label","محطة"},
{"Common.statistics.label","إحصائيات"},
{"Common.StatisticsGroup.label","مجموعة الاحصائيات"},
{"Common.status.label","الحالة"},
{"Common.staydetails.label","تفاصيل الإقامة"},
{"Common.Stock.label","مخزون"},
{"Common.Stop.label","إيقاف"},
{"Common.Store.label","مخزن"},
{"Common.Strength.label","قوة"},
{"Common.SubMenu.label","القائمة الفرعية"},
{"Common.subservice.label","الخدمة الفرعية"},
{"Common.Summary.label","ملخص"},
{"Common.sun.label","الأحد"},
{"Common.Surgical.label","جراحي"},
{"Common.switchlanguage.label","تغيير اللغة"},
{"Common.switchResponsibility.label","تغيير الصلاحية"},
{"Common.SystemDate.label","تاريخ النظام"},
{"Common.SystemDateTime.label","تاريخ / وقت النظام"},
{"Common.SystemDescription.label","وصف النظام"},
{"Common.telephone.label","هاتف"},
{"Common.telno.label","رقم الهاتف"},
{"Common.TemplateID.label","معرف النموذج"},
{"Common.TemplateName.label","اسم النموذج"},
{"Common.TermCodeDescription.label","وصف رمز المصطلح"},
{"Common.TerminalDigit.label","رقم"},
{"Common.TermSet.label","مجموعة المدة"},
{"Common.TermSetDescription.label","وصف مجموعة المصطلحات"},
{"Common.TermSetID.label","معرف المجموعة"},
{"Common.tertiary.label","ثالث"},
{"Common.Test.label","اختبار"},
{"Common.Testing.label","اختبارات"},
{"Common.Text.label","نص"},
{"Common.TextRows.label","صفوف النص"},
{"Common.Theatre.label","مسرح العملية"},
{"Common.thu.label","الخميس"},
{"Common.till.label","حتى"},
{"Common.time.label","زمن"},
{"Common.TITLE.label","عنوان"},
{"Common.to.label","إلى"},
{"Common.todate.label","حتى تاريخ"},
{"Common.ToDateTime.label","حتى تاريخ /وقت"},
{"Common.today.label","اليوم"},
{"Common.ToNursingUnit.label","إلى وحدة التمريض"},
{"Common.Topical.label","موضعي"},
{"Common.toresource.label","إلى الموارد"},
{"Common.total.label","مجموع"},
{"Common.totime.label","الى وقت"},
{"Common.Town.label","مدينة"},
{"Common.TownCode.label","كود المدينة"},
{"Common.TradeID.label","كود الصنف التجارى"},
{"Common.TradeName.label","اسم تجاري"},
{"Common.trainee.label","المتدرب"},
{"Common.TrainingDetails.label","تفاصيل التدريب"},
{"Common.transactiontype.label","نوع المعاملة"},
{"Common.Transfer.label","نقل"},
{"Common.TransferAppointment.label","موعد النقل"},
{"Common.transferdate.label","تاريخ النقل"},
{"Common.TransferOut.label","نقل خارج الوحدة"},
{"Common.TransferPatient.label","نقل المريض"},
{"Common.TransferSchedule.label","جدول النقل"},
{"Common.TransferTo.label","نقل المريض إلى"},
{"Common.TransfertoBed.label","نقل إلى السرير"},
{"Common.TransfertoNursingUnit.label","التحويل إلى وحدة تمريض"},
{"Common.TransfertoOtherHospital.label","نقل إلى مستشفى أخرى"},
{"Common.TransfertoRoomCubicleNo.label","التحويل إلى الغرفة رقم."},
{"Common.TransportMode.label","طريقة النقل"},
{"Common.treatmentarea.label","منطقة العلاج"},
{"Common.tue.label","الثلاثاء"},
{"Common.type.label","نوع"},
{"Common.Unassigned.label","غير معين"},
{"Common.Unit.label","وحدة"},
{"Common.Units.label","الوحدات"},
{"Common.University.label","جامعة"},
{"Common.unknown.label","مجهول"},
{"Common.until.label","حتى"},
{"Common.unused.label","غير مستعمل"},
{"Common.uom.label","وحدة القياس"},
{"Common.Upper.label","العلوي"},
{"Common.urgent.label","عاجل"},
{"Common.URL.label","عنوان Url"},
{"Common.used.label","مستخدم"},
{"Common.user.label","المستخدم"},
{"Common.UserAccessRights.label","حقوق وصول المستخدم"},
{"Common.UserDefined.label","المستخدم معرف"},
{"Common.userid.label","معرف المستخدم"},
{"Common.username.label","اسم المستخدم"},
{"Common.Vacant.label","شاغر"},
{"Common.valid.label","صالح"},
{"Common.view.label","عرض"},
{"Common.Visit.label","زيارة"},
{"Common.VisitControls.label","إعدادات الزيارة"},
{"Common.VisitDate.label","تاريخ الزيارة"},
{"Common.VisitDateFrom.label","تاريخ الزيارة من"},
{"Common.VisitDateTime.label","موعد الزيارة"},
{"Common.VisitDateTo.label","تاريخ الزيارة إلى"},
{"Common.VisitDetail.label","تفاصيل الزيارة"},
{"Common.VisitStatus.label","حالة الزيارة"},
{"Common.visittype.label","نوع الزيارة"},
{"Common.VisitTypeCode.label","كود نوع الزيارة"},
{"Common.VisitTypeDescription.label","وصف نوع الزيارة"},
{"Common.VitalSignsBattery.label","محطة قياس العلامات الحيوية"},
{"Common.volume.label","الحجم"},
{"Common.WaitList.label","قائمة الانتظار"},
{"Common.waitlistno.label","رقم قائمة الانتظار"},
{"Common.WaitTime.label","وقت الانتظار"},
{"Common.Ward.label","عنبر"},
{"Common.wed.label","الأربعاء"},
{"Common.Week.label","أسبوع"},
{"Common.WeekAppl.label","الأسبوع المطبق"},
{"Common.weekly.label","أسبوعي"},
{"Common.weeks.label","أسابيع"},
{"Common.weight.label","وزن"},
{"Common.whodoneit.label","من قام بها"},
{"Common.within.label","في غضون"},
{"Common.Witness.label","الشاهد"},
{"Common.WorkingDays.label","أيام العمل"},
{"Common.workstation.label","محطة العمل"},
{"Common.year.label","عام"},
{"Common.Yearly.label","سنوي"},
{"Common.Yearofpassing.label","السنة"},
{"Common.Years.label","سنوات"},
{"Common.Yellow.label","الأصفر"},
{"Common.yes.label","نعم"},
{"Common.YesNo.label","نعم / لا"},
{"Common.Archived.label","مؤرشف"},
{"Common.Lost.label","مفقود"},
{"Common.Outside.label","في الخارج"},
{"Common.Severity.label","الشدة"},
{"Common.ConfirmBedsideReferral.label","تأكيد الإحالة الداخلية على سرير"},
{"Common.RegisterInpatientReferral.label","تسجيل الإحالة للمرضى الداخليين"},
{"Common.FileFormat.label","تنسيق الملف"},
{"Common.FileName.label","اسم الملف"},
{"Common.ReportOption.label","خيار التقرير"},
{"Common.ReportOptions.label","خيارات التقرير"},
{"Common.ChiefComplaint.label","الشكوى الرئيسية"},
{"Common.History.label","التاريخ"},
{"Common.PhysicalExamination.label","الفحص البدني"},
{"Common.ProblemList.label","قائمة التشخيصات"},
{"Common.Examination.label","الفحص"},
{"Common.January.label","يناير"},
{"Common.February.label","فبراير"},
{"Common.March.label","مارس"},
{"Common.April.label","أبريل"},
{"Common.May.label","مايو"},
{"Common.June.label","يونيو"},
{"Common.July.label","يوليو"},
{"Common.August.label","أغسطس"},
{"Common.September.label","سبتمبر"},
{"Common.October.label","اكتوبر"},
{"Common.November.label","نوفمبر"},
{"Common.December.label","ديسمبر"},
{"Common.Monday.label","الإثنين"},
{"Common.Tuesday.label","الثلاثاء"},
{"Common.Wednesday.label","الأربعاء"},
{"Common.Thursday.label","خميس"},
{"Common.Friday.label","الجمعة"},
{"Common.Saturday.label","السبت"},
{"Common.Sunday.label","الأحد"},
{"Common.PhysicalLocation.label","الموقع الفعلي"},
{"Common.CreateModifyWaitlist.label","إنشاء / تعديل قائمة الانتظار"},
{"Common.BC.label","B.C. 25"},
{"Common.Highest.label","الأعلى"},
{"Common.Lowest.label","أدنى"},
{"Common.A.label","أ."},
{"Common.ATCClassification.label","تصنيف ATC"},
{"Common.ATC.label","ATC"},
{"Common.Abnormal.label","غير طبيعي"},
{"Common.Absence.label","غياب"},
{"Common.Absolute.label","مطلق"},
{"Common.Accept.label","قبول"},
{"Common.AcceptOption.label","خيارات القبول"},
{"Common.Accepted.label","مقبول"},
{"Common.Accuracy.label","الدقة"},
{"Common.AcknowledgementDate.label","تاريخ الإقرار"},
{"Common.ActionDescription.label","وصف الإجراء"},
{"Common.ActionRemarks.label","ملاحظات الإجراء"},
{"Common.ActionType.label","نوع الإجراء"},
{"Common.ActionedBy.label","عمل"},
{"Common.ActiveBookings.label","الحجوزات النشطة"},
{"Common.ActiveProblems.label","مشاكل نشطة"},
{"Common.Actual.label","فعلي"},
{"Common.Add/New.label","اضف جديد"},
{"Common.AdditionalCriteria.label","معايير إضافية"},
{"Common.AdditionalInformation.label","معلومة اضافية"},
{"Common.Administer.label","إدارة"},
{"Common.AdministeredBy.label","تدار من قبل"},
{"Common.AdmissionNo.label","رقم القبول"},
{"Common.Admitted.label","اعترف"},
{"Common.AdverseReaction.label","رد فعل سلبي"},
{"Common.AgeUnit.label","وحدة العمر"},
{"Common.Alert.label","إنذار"},
{"Common.AllCases.label","جميع الحالات"},
{"Common.AllDays.label","كل الأيام"},
{"Common.AllLocations.label","جميع المواقع"},
{"Common.AllOperations.label","جميع العمليات"},
{"Common.AllOrders.label","جميع الطلبات"},
{"Common.AllWeeks.label","كل الأسابيع"},
{"Common.AllergicDescription.label","وصف الحساسية"},
{"Common.Allergy.label","حساسية"},
{"Common.AllergyAlertby.label","تنبيه الحساسية بواسطة"},
{"Common.AllergyClass.label","فئة الحساسية"},
{"Common.AllergyOverrideReason.label","سبب تجاوز الحساسية"},
{"Common.Allocate.label","تخصيص"},
{"Common.Allocated.label","مخصصة"},
{"Common.AlphaCode.label","كود ألفا"},
{"Common.Amend.label","عدّل"},
{"Common.ApgarScore.label","نقاط أبغار"},
{"Common.ApplicableAgeGroup.label","الفئة العمرية القابلة للتطبيق"},
{"Common.ApplicablePatientClass.label","فئة المريض المطبقة"},
{"Common.ApplicablePatientClasses.label","فئات المرضى المعمول بها"},
{"Common.Application.label","تطبيق"},
{"Common.Appointment.label","موعد"},
{"Common.AppointmentDate.label","تاريخ الموعد"},
{"Common.Approve.label","يوافق"},
{"Common.Approved.label","وافق"},
{"Common.ApprovedBy.label","تمت الموافقة عليه من قبل"},
{"Common.ApptDate/Time.label","تاريخ / وقت التطبيق"},
{"Common.Appt.RefNo.label","أبت. مصدر رقم"},
{"Common.AssignBed.label","تعيين السرير"},
{"Common.Assigned.label","تعيين"},
{"Common.Associated.label","مرتبطة"},
{"Common.Association.label","جمعية"},
{"Common.At.label","في"},
{"Common.Attributes.label","السمات"},
{"Common.AuditLog.label","سجل التدقيق"},
{"Common.AuditTrail.label","سجل تدقيق"},
{"Common.Authorization.label","تفويض"},
{"Common.AuthorizationLevel.label","مستوى التفويض"},
{"Common.AuthorizationReqd..label","مطلوب إذن."},
{"Common.AuthorizedSignatory.label","المفوض بالتوقيع"},
{"Common.Autoclave.label","فرن الضغط"},
{"Common.Average.label","معدل"},
{"Common.B.label","ب"},
{"Common.BMI.label","مؤشر كتلة الجسم"},
{"Common.BSA.label","BSA"},
{"Common.Balance.label","توازن"},
{"Common.Basedon.label","مرتكز على"},
{"Common.Batch.label","دفعة"},
{"Common.BatchDetails.label","تفاصيل الدفعة"},
{"Common.BatchID.label","معرف الدفعة"},
{"Common.BatchNo.label","رقم الحزمة"},
{"Common.Before.label","قبل"},
{"Common.Between.label","ما بين"},
{"Common.BillDetails.label","تفاصيل الفاتورة"},
{"Common.Billing.label","الفواتير"},
{"Common.BillingClass.label","فئة الفواتير"},
{"Common.BillingDetails.label","تفاصيل الفاتورة"},
{"Common.BillingGroup.label","مجموعة الفواتير"},
{"Common.BillingService.label","خدمة الفواتير"},
{"Common.BinLocation.label","بن الموقع"},
{"Common.BodyPart.label","جزء من الجسم"},
{"Common.BodyParts.label","أجزاء الجسم"},
{"Common.BookingRefNo.label","رقم الحجز"},
{"Common.BookingStatus.label","وضع الحجز"},
{"Common.BookingTime.label","وقت الحجز"},
{"Common.ByDate.label","حسب التاريخ"},
{"Common.ByPosition.label","حسب الوظيفة"},
{"Common.ByShift.label","بواسطة Shift"},
{"Common.C.label","ج"},
{"Common.CancelDischarge.label","إلغاء الخروج"},
{"Common.CancelRemarks.label","إلغاء الملاحظات"},
{"Common.CancelSchedule.label","إلغاء الجدول"},
{"Common.CancellationDate.label","تاريخ الإلغاء"},
{"Common.CancellationDetails.label","تفاصيل الإلغاء"},
{"Common.CancellationRemarks.label","ملاحظات الإلغاء"},
{"Common.CancelledDateFrom.label","تاريخ الإلغاء من"},
{"Common.CancelledDate/Time.label","التاريخ / الوقت الملغي"},
{"Common.CancelledDetail.label","التفاصيل الملغاة"},
{"Common.Cannotbeblank.label","لا يمكن أن يكون فارغا"},
{"Common.CaptureFinancialDetails.label","الحصول على التفاصيل المالية"},
{"Common.CatalogCrossReference.label","كتالوج مرجعى"},
{"Common.CauseofDeath.label","سبب الوفاة"},
{"Common.Center.label","مركز"},
{"Common.Certain.label","المؤكد"},
{"Common.ChangeDescription.label","قم بتغيير الوصف"},
{"Common.Changedby.label","تغيير من قبل"},
{"Common.Charge.label","الشحنة"},
{"Common.ChargeAmount.label","مستوى الشحن"},
{"Common.ChargeDetails.label","تفاصيل الشحن"},
{"Common.Chargeable.label","تحميل"},
{"Common.Charges.label","خدمات  للدفع"},
{"Common.Chart.label","مخطط"},
{"Common.Charts.label","الرسوم البيانية"},
{"Common.ChartID.label","معرف الرسم البياني"},
{"Common.ChartSummaryCurrentMedications.label","رسم بياني"},
{"Common.CheckBox.label","خانة اختيار"},
{"Common.CheckedBy.label","فحص بواسطة"},
{"Common.CheckedIn.label","تم تسجيل الوصول"},
{"Common.CheckedOut.label","تم تسجيل الخروج"},
{"Common.Classification.label","تصنيف"},
{"Common.ClinicalNote.label","ملاحظة سريرية"},
{"Common.ClinicalNotes.label","ملاحظات سريرية"},
{"Common.Clinician.label","طبيب"},
{"Common.Cms.label","سم"},
{"Common.CollectedBy.label","جمع بواسطة"},
{"Common.Complications.label","المضاعفات"},
{"Common.Components.label","مكونات"},
{"Common.Composition.label","تكوين"},
{"Common.Compute.label","إحصاء - عد"},
{"Common.Condition.label","شرط"},
{"Common.ConfirmAuthorize.label","تأكيد التفويض"},
{"Common.ConfirmCancel.label","تأكيد إلغاء"},
{"Common.ConfirmDelete.label","تأكيد الحذف"},
{"Common.ConfirmFinalize.label","تأكيد الإنهاء"},
{"Common.ConfirmPassword.label","تأكيد كلمة المرور"},
{"Common.Consent.label","موافقة"},
{"Common.ConsentDetails.label","تفاصيل الموافقة"},
{"Common.ConsentForm.label","نموذج الموافقة"},
{"Common.ConsentNote.label","مذكرة الموافقة"},
{"Common.ConsentRequired.label","الموافقة مطلوبة"},
{"Common.ConsentStage.label","مرحلة الموافقة"},
{"Common.ConsentType.label","نوع الموافقة"},
{"Common.ConsiderforScheduling.label","فكر في الجدولة"},
{"Common.ConstituentName.label","اسم المكون"},
{"Common.Consumable.label","مستهلك"},
{"Common.Continue.label","استمر"},
{"Common.Copy.label","نسخ"},
{"Common.Cosign.label","امضاء مؤكد"},
{"Common.CosignReqd.label","تأكيد الامضاء مطلوب"},
{"Common.Cosigned.label","تم تأكيد  الإمضاء"},
{"Common.Cost.label","تكلفة"},
{"Common.CountSheetDate.label","تاريخ ورقة العد"},
{"Common.CounterCheckedBy.label","فحص العداد بواسطة"},
{"Common.CreatedOn.label","تم إنشاؤها على"},
{"Common.CriticallyAbnormal.label","حرج للغاية"},
{"Common.CurrentProcessMonth/Year.label","العملية الحالية شهر / سنة"},
{"Common.CurrentProcessingMonth.label","شهر المعالجة الحالي"},
{"Common.CurrentProcessingMonth/Year.label","شهر / سنة المعالجة الحالية"},
{"Common.CurrentProcessingYear.label","سنة المعالجة الحالية"},
{"Common.CurrentYear.label","السنة الحالية"},
{"Common.CustomList.label","قائمة مخصصة"},
{"Common.Customer.label","الزبون"},
{"Common.CutOffDate.label","تعدى التاريخ"},
{"Common.CycleDays.label","أيام الدورة"},
{"Common.DISPENSED.label","وزع"},
{"Common.DOB.label","DOB"},
{"Common.DataEntryStatus.label","حالة إدخال البيانات"},
{"Common.DateTo.label","التاريخ ل"},
{"Common.DateofReporting.label","تاريخ التقرير"},
{"Common.Date/Time.label","التاريخ / الوقت"},
{"Common.Day(s).label","أيام"},
{"Common.Decreased.label","انخفض"},
{"Common.DefaultDocumentTypes.label","أنواع المستندات الافتراضية"},
{"Common.DefaultSite.label","الموقع الافتراضي"},
{"Common.Define.label","حدد"},
{"Common.DefinitionType.label","نوع التعريف"},
{"Common.Definitive.label","نهائي"},
{"Common.DeleteAllItems.label","حذف كافة العناصر"},
{"Common.DepartmentCode.label","كود قسم"},
{"Common.Dependency.label","الاعتماد"},
{"Common.DependencyLevel.label","مستوى التبعية"},
{"Common.DestinationType.label","نوع الوجهة"},
{"Common.DiagnosisCodingScheme.label","مخطط ترميز التشخيص"},
{"Common.DiagnosisDate.label","تاريخ التشخيص"},
{"Common.DiagnosisType.label","نوع التشخيص"},
{"Common.Differentials.label","التفاضل"},
{"Common.Direct.label","مباشرة"},
{"Common.DischargeMedication.label","دواء الخروج"},
{"Common.Discontinue.label","توقف"},
{"Common.DiscontinueReason.label","توقف السبب"},
{"Common.Discontinued.label","توقف"},
{"Common.DiscreteMeasurePanel.label","لوحة قياس منفصلة"},
{"Common.DispatchedBy.label","مرسل بواسطة"},
{"Common.Dispensed.label","وزع"},
{"Common.DisplayResult.label","عرض النتيجة"},
{"Common.DocDate.label","تاريخ الوثيقة"},
{"Common.DocNo.label","رقم الوثيقة"},
{"Common.DocRef.label","مرجع الوثيقة"},
{"Common.DocTypeCode.label","كود نوع الوثيقة"},
{"Common.DocTypeDescription.label","وصف نوع المستند"},
{"Common.DoneBy.label","تم بواسطة"},
{"Common.Dosage.label","الجرعة"},
{"Common.DosageBy.label","الجرعة بواسطة"},
{"Common.DosageRegimen.label","نظام الجرعات"},
{"Common.Dose.label","جرعة"},
{"Common.DoseNo.label","جرعة لا"},
{"Common.DrugCode.label","كود الدواء"},
{"Common.DrugInteraction.label","تفاعل الدواء"},
{"Common.DrugName.label","اسم الدواء"},
{"Common.DrugProfile.label","الملف الشخصي المخدرات"},
{"Common.Drug/TradeImage.label","صورة المخدرات / التجارة"},
{"Common.Due.label","بسبب"},
{"Common.Element.label","جزء"},
{"Common.EmplStatus.label","حالة الموظف"},
{"Common.EmployeeID.label","هوية الموظف"},
{"Common.End.label","النهاية"},
{"Common.EndDateTime.label","وقت تاريخ الانتهاء"},
{"Common.EndofResults.label","نهاية النتائج"},
{"Common.English.label","الإنجليزية"},
{"Common.EnterRemarks.label","أدخل الملاحظات"},
{"Common.Enter/Edit.label","أدخل / تحرير"},
{"Common.Entered.label","دخلت"},
{"Common.EnteredBy.label","أدخل بواسطة"},
{"Common.EntryCompleted.label","اكتمل الدخول"},
{"Common.EpisodeType.label","نوع الحلقة"},
{"Common.EquivalentUOM.label","وحدة قياس مكافئة"},
{"Common.Error.label","خطأ"},
{"Common.ErrorMessage.label","رسالة خطأ"},
{"Common.ErrorRemarks.label","ملاحظات الخطأ"},
{"Common.EthnicGroup.label","المجموعة العرقية"},
{"Common.EventDetails.label","تفاصيل الحدث"},
{"Common.EventEndDate.label","تاريخ انتهاء الفعالية"},
{"Common.EventStartDate.label","تاريخ بدء الحدث"},
{"Common.EventStatus.label","حالة الحدث"},
{"Common.Events.label","الأحداث"},
{"Common.Every.label","كل"},
{"Common.Exclude.label","استبعاد"},
{"Common.Expired.label","منتهية الصلاحية"},
{"Common.Expiry.label","انقضاء"},
{"Common.ExternalInterfaceRequired.label","الواجهة الخارجية مطلوبة"},
{"Common.ExternalInterfaceforPrivilege.label","واجهة خارجية للصلاحية"},
{"Common.ExternalPrescriptions.label","الوصفات الخارجية"},
{"Common.FacilityBased.label","مقرها منشأة"},
{"Common.Failed.label","فشل"},
{"Common.Failure.label","بالفشل"},
{"Common.FamilyName.label","اسم العائلة"},
{"Common.FaxNo.label","فاكس رقم"},
{"Common.Field.label","حقل"},
{"Common.FileTypeDescription.label","وصف نوع الملف"},
{"Common.FillProcID.label","قم بتعبئة معرف الاجراء"},
{"Common.Finalize.label","وضع اللمسات الأخيرة"},
{"Common.Finalized.label","انتهى"},
{"Common.FindPractitionerTypeForAssessmentNote.label","ابحث عن نوع الممارس لملاحظة التقييم"},
{"Common.Findings.label","الموجودات"},
{"Common.FirstName.label","الاسم الاول"},
{"Common.Fixed.label","ثابت"},
{"Common.FloorCode.label","كود الطابق"},
{"Common.FluidName.label","اسم السائل"},
{"Common.Form.label","شكل"},
{"Common.FormatItem.label","تنسيق العنصر"},
{"Common.Formatted.label","منسق"},
{"Common.Forward.label","إلى الأمام"},
{"Common.ForwardtoPractitioner.label","إلى الممارس"},
{"Common.FreeFormat.label","تنسيق مجاني"},
{"Common.FromMonth.label","من شهر"},
{"Common.FromStore.label","من المخزن"},
{"Common.FromTreatment.label","من العلاج"},
{"Common.FullTime.label","وقت كامل"},
{"Common.FullyBooked.label","محجوز بالكامل"},
{"Common.FullyImmunized.label","محصن بالكامل"},
{"Common.FullyIssued.label","تم إصداره بالكامل"},
{"Common.GeneralLedger.label","دفتر الأستاذ العام"},
{"Common.Generate.label","انشاء"},
{"Common.GenericName.label","اسم عام"},
{"Common.GenericNameLookup.label","بحث عام عن الاسم"},
{"Common.GrandTotal.label","المجموع الكلي"},
{"Common.Green.label","أخضر"},
{"Common.GroupCode.label","كود المجموعة"},
{"Common.GroupType.label","نوع المجموعة"},
{"Common.Growth/DevelMilestoneAge.label","النمو / تطور العمر ميلستون"},
{"Common.HDay.label","HDay"},
{"Common.HeadCircumference.label","محيط الرأس"},
{"Common.Hold.label","معلق"},
{"Common.HoldReason.label","سبب الاحتفاظ"},
{"Common.Holidays.label","العطل"},
{"Common.Hospital.label","مستشفى"},
{"Common.HourAfterDischarge.label","ساعة بعد الخروج"},
{"Common.Hour(s).label","ساعة (ساعات)"},
{"Common.Hr.label","ساعة"},
{"Common.Hrs.label","ساعات"},
{"Common.ICDCode.label","كود التصنيف الدولي للأمراض"},
{"Common.IP.label","الداخلى"},
{"Common.AE.label","AE"},
{"Common.IPfillprocessScheduleStarttime.label","عملية تعبئة الداخلى جدولة وقت البدء"},
{"Common.IVAdmixture.label","رابعا الاختلاط"},
{"Common.IVwithAdditives.label","الرابع مع الإضافات"},
{"Common.Image.label","صورة"},
{"Common.ImageFilename.label","اسم ملف الصورة"},
{"Common.ImageURL.label","رابط الصورة"},
{"Common.ImmunizationStatus.label","حالة التحصين"},
{"Common.Implant.label","زرع"},
{"Common.InPerson.label","شخصيا"},
{"Common.InProcess.label","تحت المعالجة"},
{"Common.Inactive.label","غير نشط"},
{"Common.Inch.label","بوصة"},
{"Common.IncludeinCurrentEncounter.label","تضمين في اللقاء الحالي"},
{"Common.Included.label","متضمن"},
{"Common.IndexType.label","نوع الفهرس"},
{"Common.InformedDate/Time.label","التاريخ / الوقت المستنير"},
{"Common.Insert.label","إدراج"},
{"Common.Instrument.label","أداة"},
{"Common.Insurance.label","تأمين"},
{"Common.Interface.label","واجهه المستخدم"},
{"Common.Interval(min).label","الفاصل الزمني (دقيقة)"},
{"Common.Intervention.label","تدخل قضائي"},
{"Common.InterventionType.label","نوع التدخل"},
{"Common.Intravenous.label","وريدي"},
{"Common.Inventory.label","المخزون"},
{"Common.Issue.label","القضية"},
{"Common.IssueDate.label","تاريخ الإصدار"},
{"Common.IssueQuantity.label","كمية الإصدار"},
{"Common.IssueRemarks.label","ملاحظات إصدار"},
{"Common.IssueStore.label","مخزن الإصدار"},
{"Common.Issued.label","نشر"},
{"Common.IssuedQuantity.label","الكمية المصدرة"},
{"Common.ItemAnalysis.label","تحليل العنصر"},
{"Common.ItemClass.label","فئة البند"},
{"Common.ItemClassCode.label","رمز فئة العنصر"},
{"Common.ItemClassDescription.label","وصف فئة العنصر"},
{"Common.ItemCodeFrom.label","رمز العنصر من"},
{"Common.ItemLevel.label","مستوى العنصر"},
{"Common.ItemName.label","اسم العنصر"},
{"Common.ItemQty.label","البند الكمية"},
{"Common.ItemValue.label","قيمة البند"},
{"Common.Key.label","مفتاح"},
{"Common.labelText.label","نص التسمية"},
{"Common.labelType.label","نوع التسمية"},
{"Common.Language.label","لغة"},
{"Common.Last.label","الاخير"},
{"Common.LastExecution.label","آخر تنفيذ"},
{"Common.LastIssueDate.label","تاريخ آخر اصدار"},
{"Common.LastModifiedBy.label","التعديل الأخير من قبل"},
{"Common.LastProcessedDate.label","تاريخ آخر معالجة"},
{"Common.LastVisitDetails.label","تفاصيل الزيارة الأخيرة"},
{"Common.LeavePeriod.label","فترة الإجازة"},
{"Common.LessThan.label","أقل من"},
{"Common.Limit.label","حد"},
{"Common.Line.label","خط"},
{"Common.Link.label","رابط"},
{"Common.LinkCatalog.label","كتالوج الرابط"},
{"Common.Lipid.label","دهون"},
{"Common.ListID.label","معرف القائمة"},
{"Common.Local.label","محلي"},
{"Common.LocalLanguage.label","لغة محلية"},
{"Common.LocalLanguageDescription.label","وصف اللغة المحلية"},
{"Common.LocationDetails.label","تفاصيل الموقع"},
{"Common.LocationFrom.label","الموقع من"},
{"Common.LoggedinFacility.label","مرفق تسجيل الدخول"},
{"Common.LongDesc.label","تنازلي طويل"},
{"Common.MachineName.label","إسم الألة"},
{"Common.ManageQueue.label","إدارة قائمة الانتظار"},
{"Common.MarkError.label","وضع علامة على خطأ"},
{"Common.MarkedBy.label","علمت بواسطة"},
{"Common.MarkedDate.label","التاريخ المحدد"},
{"Common.Med/AncService.label","حدمات  طبية / مساعدة"},
{"Common.MedicalItem.label","الصنف الطبي"},
{"Common.MedicalReportRequest.label","طلب تقرير طبي"},
{"Common.Medication.label","دواء"},
{"Common.MedicationAdministration.label","إدارة الدواء"},
{"Common.MessageDate.label","تاريخ الرسالة"},
{"Common.MessageDate/Time.label","تاريخ / وقت الرسالة"},
{"Common.MessageText.label","رسالة نصية"},
{"Common.MessageType.label","نوع الرسالة"},
{"Common.Mild.label","خفيف"},
{"Common.MinimumAge.label","الحد الإدنى للعمر"},
{"Common.Minute(s).label","الدقائق)"},
{"Common.Minutes.label","الدقائق"},
{"Common.Miscellaneous.label","متنوع"},
{"Common.Mobile.label","التليفون المحمول"},
{"Common.Moderate.label","معتدل"},
{"Common.Modified.label","تم التعديل"},
{"Common.Month/Year.label","شهر سنة"},
{"Common.Mother.label","أم"},
{"Common.NWDay.label","NWDay"},
{"Common.Negative.label","سلبي"},
{"Common.NetAmount.label","كمية الشبكة"},
{"Common.NewDocument.label","مستند جديد"},
{"Common.NewOrders.label","طلبات جديدة"},
{"Common.NextExecution.label","التنفيذ القادم"},
{"Common.NoShows.label","الحالات  لم تاتى"},
{"Common.NoofBirths.label","عدد المواليد"},
{"Common.Non-WorkingDays.label","أيام العطلات"},
{"Common.NotAdministered.label","غير مُدار"},
{"Common.NotCompleted.label","غير مكتمل"},
{"Common.NotDelivered.label","لم يتم تسليمها"},
{"Common.NotIssued.label","لم يصدر"},
{"Common.NotKnown.label","غير معروف"},
{"Common.NotPerformed.label","لم تتم"},
{"Common.NoteDescription.label","وصف الملاحظة"},
{"Common.Numeric.label","رقمي"},
{"Common.NursingUnitDetails.label","تفاصيل وحدة التمريض"},
{"Common.NursingUnitSearch.label","البحث عن وحدة التمريض"},
{"Common.Observation.label","الملاحظة"},
{"Common.Old.label","قديم"},
{"Common.OldValue.label","القيمة القديمة"},
{"Common.OnsetDateTime.label","تاريخ  ووقت البداية"},
{"Common.OpeningBalance.label","الرصيد الافتتاحي"},
{"Common.OperatingRoom.label","غرفة العمليات"},
{"Common.Option.label","اختيار"},
{"Common.Options.label","خيارات"},
{"Common.OrderCatalogDescription.label","وصف كتالوج الطلب"},
{"Common.OrderDateFrom.label","تاريخ الطلب من"},
{"Common.OrderDateTime.label","تاريخ الطلب الوقت"},
{"Common.OrderDetails.label","تفاصيل الطلب"},
{"Common.OrderEntryTabs.label","ترتيب الدخول"},
{"Common.OrderID.label","رقم التعريف الخاص بالطلب"},
{"Common.OrderLocation.label","موقع الطلب"},
{"Common.OrderNo.label","رقم الطلب"},
{"Common.OrderQty.label","كمية الطلب"},
{"Common.OrderTypeCode.label","كود نوع الطلب"},
{"Common.OrderTypeCodeFrom.label","كود نوع الطلب من"},
{"Common.Orderable.label","قابل لطلب"},
{"Common.Ordered.label","أمر"},
{"Common.OrderedBy.label","مرتبة حسب"},
{"Common.Ordering.label","ترتيب"},
{"Common.OrderingDoctor.label","طلب طبيب"},
{"Common.OrderingFacility.label","طلب مرفق"},
{"Common.OrderingFacilityID.label","طلب معرف المنشأة"},
{"Common.OrderingFacilityName.label","طلب اسم مرفق"},
{"Common.OrderingLocation.label","ترتيب الموقع"},
{"Common.OrderingPractitioner.label","طلب ممارس"},
{"Common.OrganisationType.label","نوع المنظمة"},
{"Common.Organization.label","منظمة"},
{"Common.OrganizationType.label","نوع المنظمة"},
{"Common.OtherDefaults.label","افتراضات أخرى"},
{"Common.OtherFacility.label","مرفق آخر"},
{"Common.OtherStaffDetails.label","تفاصيل الموظفين الأخرى"},
{"Common.OutpatientAppointments.label","مواعيد العيادات الخارجية"},
{"Common.PFReports.label","تقارير PF"},
{"Common.POA.label","POA"},
{"Common.PRN.label","وقت اللزوم"},
{"Common.PackSize.label","حجم العبوة"},
{"Common.Package.label","صفقة"},
{"Common.PackageCode.label","كود الصفقة"},
{"Common.PackedBy.label","معبأة من قبل"},
{"Common.Paid.label","دفع"},
{"Common.Panel.label","لوجة"},
{"Common.PanelDescription.label","وصف اللوحة"},
{"Common.Parameters.label","المعلمات"},
{"Common.PartTime.label","دوام جزئى"},
{"Common.PartiallyCompleted.label","أنجزت جزئيا"},
{"Common.PartiallyImmunized.label","محصن جزئياً"},
{"Common.PartiallyIssued.label","صادرة جزئيا"},
{"Common.PatientAdministration.label","إدارة المريض"},
{"Common.PatientClassCode.label","كود فئة المريض"},
{"Common.PatientInstruction.label","تعليمات المريض"},
{"Common.PatientInstructions.label","تعليمات المريض"},
{"Common.PatientLabel.label","تسمية المريض"},
{"Common.PatientPaid.label","يدفع المريض"},
{"Common.PatientPayable.label","يدفع المريض"},
{"Common.PatientPosition.label","موقف المريض"},
{"Common.PatientSpecific.label","خاص بالمريض"},
{"Common.PatientStatus.label","حالة المريض"},
{"Common.Patients.label","المرضى"},
{"Common.Payer.label","ممول"},
{"Common.PaymentDetails.label","بيانات الدفع"},
{"Common.PediatricDetail.label","تفاصيل طب الأطفال"},
{"Common.PendingAuthorization.label","تصريح معلق"},
{"Common.PendingConsent.label","في انتظار الموافقة"},
{"Common.PendingCosign.label","في انتظار  تاكيد الامضاء"},
{"Common.PendingOrders.label","الأوامر المعلقة"},
{"Common.PendingQty.label","الكمية المعلقة"},
{"Common.PendingforReviews.label","في انتظار التعليقات"},
{"Common.Percent.label","نسبه مئويه"},
{"Common.Performed.label","أديت"},
{"Common.PerformedDate.label","تاريخ التنفيذ"},
{"Common.PerformedOn.label","تجرى على"},
{"Common.PerformingFacility.label","مرفق الأداء"},
{"Common.PerformingFacilityID.label","أداء معرف المنشأة"},
{"Common.PerformingFacilityName.label"," اسم المنشأة المؤدية"},
{"Common.PerformingLocation.label","الموقع"},
{"Common.Permanent.label","دائم"},
{"Common.Personal.label","شخصي"},
{"Common.PhysicalStock.label","المخزون المادي"},
{"Common.PickOnlyBookingsDoneAfter.label","اختر الحجوزات التي تمت بعد ذلك فقط"},
{"Common.PlaceOrder.label","طلب  اوامر"},
{"Common.PlaceofDeath.label","مكان الموت"},
{"Common.PoliceStationDetails.label","تفاصيل مركز الشرطة"},
{"Common.PositionCode.label","رمز الوظيفة"},
{"Common.PositionDescription.label","وصف الوظيفة"},
{"Common.PositionDuringIncident.label","الموقف أثناء الحادث"},
{"Common.Positive.label","إيجابي"},
{"Common.Potential.label","محتمل"},
{"Common.PractitionerDetails.label","تفاصيل الممارس"},
{"Common.PractitionerFrom.label","ممارس من"},
{"Common.PractitionerTypeDescription.label","وصف نوع الممارس"},
{"Common.PreferredDateFrom.label","التاريخ المفضل من"},
{"Common.PreferredMonth.label","الشهر المفضل"},
{"Common.Pregnant.label","حامل"},
{"Common.PreparationStrength/Quantity.label","قوة التحضير / الكمية"},
{"Common.PrepareDate.label","تحضير التاريخ"},
{"Common.PrepareLocation.label","تحضير الموقع"},
{"Common.PreparedAt.label","أعد في"},
{"Common.PreparedBy.label","أعدت بواسطة"},
{"Common.PrescribedBy.label","المنصوص عليها"},
{"Common.Prescription.label","وصفة طبية"},
{"Common.Presentation.label","عرض"},
{"Common.Preview.label","معاينة"},
{"Common.Price.label","السعر"},
{"Common.PrintAt.label","طباعة في"},
{"Common.PrintPreview.label","معاينة قبل الطباعة"},
{"Common.PrintWorksheet.label","طباعة ورقة العمل"},
{"Common.Printing.label","طباعة"},
{"Common.PriorityApplicable.label","الأولوية المطبقة"},
{"Common.PriorityCode.label","كود الأولوية"},
{"Common.PriorityZone.label","منطقة الأولوية"},
{"Common.Probable.label","محتمل"},
{"Common.Problem.label","مشكلة"},
{"Common.ProblemAssessment.label","تقييم المشكلة"},
{"Common.Problems.label","مشاكل"},
{"Common.Procedures.label","الإجراءات"},
{"Common.Proceed.label","تقدم"},
{"Common.ProcessDetails.label","تفاصيل العملية"},
{"Common.ProcessID.label","معرف العمليه"},
{"Common.ProcessName.label","اسم العملية"},
{"Common.ProcessType.label","نوع العملية"},
{"Common.ProductName.label","اسم المنتج"},
{"Common.ProductiveFlag.label","علم الإنتاج"},
{"Common.Profile.label","الملف الشخصي"},
{"Common.Program.label","برنامج"},
{"Common.ProtectiveDeviceUsed.label","جهاز الحماية المستخدم"},
{"Common.Purchase.label","شراء"},
{"Common.PurchaseUOM.label","وحدة شراء"},
{"Common.QAPReport.label","تقرير QAP"},
{"Common.Qty.label","الكمية"},
{"Common.QtyUnit.label","وحدة الكمية"},
{"Common.QueueDate.label","تاريخ قائمة الانتظار"},
{"Common.R/N.label","رقم تسلسل"},
{"Common.RT.label","يمين"},
{"Common.ReactionCode.label","كود التفاعل"},
{"Common.ReactionDate.label","تاريخ التفاعل"},
{"Common.ReceivedBy.label","استلمت من قبل"},
{"Common.ReceivedValue.label","القيمة المستلمة"},
{"Common.ReceivingStore.label","مخزن الاستلام"},
{"Common.ReferralDiagnosis.label","تشخيص الإحالة"},
{"Common.ReferralFacility.label","منشأة الإحالة"},
{"Common.ReferredDate.label","التاريخ المشار إليه"},
{"Common.ReferredFrom.label","المشار إليه من"},
{"Common.ReferredPractitioner.label","ممارس مُحال"},
{"Common.RegisterOrder.label","طلب تسجيل"},
{"Common.Registered.label","مسجل"},
{"Common.RegisteredBy.label","مسجل بواسطة"},
{"Common.RegnDate.label","تاريخ التسجيل"},
{"Common.RegnDate/Time.label","تاريخ / وقت التسجيل"},
{"Common.Reimburse.label","تعويض"},
{"Common.Reinstate.label","إعادة"},
{"Common.Reinstated.label","تم الاعادة"},
{"Common.Reject.label","رفض"},
{"Common.RelationshipType.label","نوع العلاقة"},
{"Common.RepackDate.label","أعد حزم التاريخ"},
{"Common.RepackingGroup.label","مجموعة إعادة التعبئة"},
{"Common.Repl?.label","رد؟"},
{"Common.Replace.label","يستبدل"},
{"Common.ReplacementStatus.label","حالة الاستبدال"},
{"Common.ReportOrder.label","طلب تقرير"},
{"Common.ReportedBy.label","تم عمل تقرير بواسطة"},
{"Common.ReportedDate.label","تاريخ الإبلاغ"},
{"Common.Reprint.label","اعادة طبع"},
{"Common.ReqByStore.label","طلب من المخزن"},
{"Common.ReqOnStore.label","مطلوب في المخزن"},
{"Common.ReqQuantity.label","الكمية المطلوبة"},
{"Common.RequestDateFrom.label","تاريخ الطلب من"},
{"Common.RequestDetails.label","طلب تفاصيل"},
{"Common.RequestMode.label","وضع الطلب"},
{"Common.RequestNo.label","رقم الطلب"},
{"Common.RequestType.label","نوع الطلب"},
{"Common.RequestedOn.label","طلبت في"},
{"Common.RequestedOnStore.label","مطلوب في المخزن"},
{"Common.Requestor.label","الطالب"},
{"Common.Requirement.label","المتطلبات"},
{"Common.RequisitionbyStore.label","طلب من المخزن"},
{"Common.RequisitiononStore.label","طلب في المخزن"},
{"Common.Reschedule.label","إعادة الجدولة"},
{"Common.RescheduledReason.label","سبب اعادة جدولة"},
{"Common.Reserved.label","محجوز"},
{"Common.ReservedNotRequested.label","محجوز غير مطلوب"},
{"Common.Resolved.label","تم الحل"},
{"Common.Response.label","استجابة"},
{"Common.RestrictbyService.label","تقييد حسب الخدمة"},
{"Common.Return.label","إرجاع"},
{"Common.ReturnFrom.label","العودة من"},
{"Common.ReturnFromStore.label","العودة من المخزن"},
{"Common.ReturnQty.label","عودة الكمية"},
{"Common.ReturnToStore.label","العودة إلى المخزن"},
{"Common.Returnable.label","قابل للإرجاع"},
{"Common.ReturnedQty.label","تم إرجاع الكمية"},
{"Common.ReturnedValue.label","القيمة المعادة"},
{"Common.ReturningStore.label","المخزن المرتجع"},
{"Common.Review.label","مراجعة"},
{"Common.Reviewed.label","تمت المراجعة"},
{"Common.Route.label","طريق"},
{"Common.RouteofExposure.label","طريق التعرض"},
{"Common.RowPosition.label","موقف الصف"},
{"Common.S.label","س"},
{"Common.Sale.label","بيع"},
{"Common.SaleQuantity.label","كمية البيع"},
{"Common.Same.label","نفسه"},
{"Common.Save.label","حفظ"},
{"Common.ScheduleDate.label","تاريخ الجدول الزمني"},
{"Common.ScheduledDate.label","التاريخ المقرر"},
{"Common.Scope.label","نطاق"},
{"Common.ScrubNurse.label","ممرضة تدليك"},
{"Common.SecondName.label","الاسم الثاني"},
{"Common.Selected.label","المحدد"},
{"Common.Selection.label","اختيار"},
{"Common.SelfRelated.label","ذات الصلة"},
{"Common.Separate.label","منفصل"},
{"Common.Set.label","جلس"},
{"Common.SettlementType.label","نوع التسوية"},
{"Common.Severe.label","شديدة"},
{"Common.Sex.label","الجنس"},
{"Common.ShiftIndicator.label","مؤشر نوبات العمل"},
{"Common.ShortDesc.label","ترتيب تنازلي"},
{"Common.ShowPositions.label","عرض المناصب"},
{"Common.ShowShifts.label","إظهار نوبات العمل"},
{"Common.Sign.label","إشارة"},
{"Common.SiteName.label","اسم الموقع"},
{"Common.SkipAge.label","تخطي العمر"},
{"Common.SlidingScale.label","مقياس متدرج"},
{"Common.Slot.label","مكان"},
{"Common.SoftStop.label","توقف ناعم"},
{"Common.SoleSource.label","المصدر الوحيد"},
{"Common.SourceType.label","نوع المصدر"},
{"Common.SpecialApproval.label","الموافقة الخاصة"},
{"Common.SpecialApprovalReqd.label","مطلوب موافقة خاصة"},
{"Common.SpecialApprovalRequired.label","مطلوب موافقة خاصة"},
{"Common.SpecialItem.label","بند خاص"},
{"Common.SpecialityforPractitioner.label","تخصص للممارس"},
{"Common.Specialty.label","تخصص"},
{"Common.SpecialtyCode.label","كود التخصص"},
{"Common.SpecialtyDescription.label","وصف التخصص"},
{"Common.SpecificOperation.label","عملية محددة"},
{"Common.SpecificSpecialty.label","تخصص معين"},
{"Common.Specify.label","حدد"},
{"Common.Specimen.label","عينة"},
{"Common.SpecimenCollection.label","جمع العينات"},
{"Common.SpecimenDetails.label","تفاصيل العينة"},
{"Common.SpecimenType.label","نوع العينة"},
{"Common.SrlNo.label","رقم تسلسل"},
{"Common.Staff.label","العاملين"},
{"Common.StaffID.label","معرف الموظفين"},
{"Common.StaffType.label","نوع الموظفين"},
{"Common.Stage.label","المسرح"},
{"Common.StageCode.label","كود المرحلة"},
{"Common.Standard.label","اساسي"},
{"Common.StartSerialNo.label","بدء الرقم التسلسلي"},
{"Common.Stat.label","ستات"},
{"Common.State.label","حالة"},
{"Common.SterileLife.label","حياة معقمة"},
{"Common.SterileType.label","نوع معقم"},
{"Common.Sterilize.label","عقم"},
{"Common.StockUOM.label","وحدة قياس المخزن"},
{"Common.StorageLocation.label","مكان التخزين"},
{"Common.StoreCode.label","كود المخزن"},
{"Common.StoreCodeFrom.label","رمز المخزن من"},
{"Common.StoreDescription.label","وصف المخزن"},
{"Common.StoreTotal.label","إجمالي المخزن"},
{"Common.StoreType.label","نوع المخزن"},
{"Common.SubClass.label","فئة فرعية"},
{"Common.SubTotal.label","المجموع الفرعي"},
{"Common.Submit.label","إرسال"},
{"Common.SubmittedBy.label","مقدم من"},
{"Common.Success.label","نجاح"},
{"Common.Supplier.label","المورد"},
{"Common.SupplierCode.label","كود المورد"},
{"Common.SupportingDiagnosis.label","دعم التشخيص"},
{"Common.Surgeon.label","دكتور جراح"},
{"Common.Surgery.label","جراحة"},
{"Common.SurgeryType.label","نوع الجراحة"},
{"Common.Suspend.label","تعليق"},
{"Common.Suspended.label","معلق"},
{"Common.Swap.label","مبادلة"},
{"Common.System.label","النظام"},
{"Common.SystemDefined.label","معرّف من قبل النظام"},
{"Common.SystemStock.label","مخزون النظام"},
{"Common.TDMDetails.label","تفاصيل مراقبة الادوية العلاجية"},
{"Common.TRNType.label","نوع الحركة"},
{"Common.TRNTypeDescription.label","وصف نوع الحركة"},
{"Common.TRNdoctype.label","نوع وثيقة الحركة"},
{"Common.Table.label","الطاولة"},
{"Common.Taper.label","تفتق"},
{"Common.Task.label","مهمة"},
{"Common.Tasks.label","مهام"},
{"Common.TeamID.label","معرف الفريق"},
{"Common.TelexNo.label","رقم التلكس"},
{"Common.TermCode.label","كود المصطلح"},
{"Common.TermCodeforDrug.label","كود المصطلح للدواء"},
{"Common.TerminologyCode.label","قانون المصطلحات"},
{"Common.TerminologyCodeDescription.label","وصف كود المصطلحات"},
{"Common.TerminologySet.label","مجموعة المصطلحات"},
{"Common.TextBlock.label","كتلة النص"},
{"Common.TimeTaken.label","الوقت المستغرق"},
{"Common.TitleText.label","نص العنوان"},
{"Common.ToMonth.label","الى شهر"},
{"Common.ToStore.label","للتخزين"},
{"Common.ToTreatment.label","للعلاج"},
{"Common.Top.label","أعلى"},
{"Common.TotalCount.label","العدد الإجمالي"},
{"Common.TotalNOOfOperationsRoomwise.label","العدد الإجمالي لغرفة العمليات"},
{"Common.TotalValue.label","القيمة الإجمالية"},
{"Common.Trade.label","التجارة"},
{"Common.Training.label","تدريب"},
{"Common.Transaction.label","حركة"},
{"Common.TransactionDate.label","تاريخ الحركة"},
{"Common.TransactionRemarks.label","ملاحظات الحركة"},
{"Common.Transcribed.label","نسخت"},
{"Common.TransferFrom.label","تحويل من"},
{"Common.TransferredBy.label","تم التحويل بواسطة"},
{"Common.TransfusionHistory.label","تاريخ نقل الدم"},
{"Common.Trauma.label","الصدمة"},
{"Common.Tray.label","صينية"},
{"Common.TrayNo.label","رقم صينية "},
{"Common.Treat/Invest.label","تعامل / استثمار"},
{"Common.Treatment.label","علاج او معاملة"},
{"Common.TreatmentCategory.label","فئة العلاج"},
{"Common.TriageDetails.label","تفاصيل الفرز"},
{"Common.UOMCode.label","كود وحدة القياس"},
{"Common.Ultrasound.label","الموجات فوق الصوتية"},
{"Common.UnFinalized.label","غير مكتمل"},
{"Common.Unauthorized.label","غير مصرح"},
{"Common.Uncertain.label","غير مؤكد"},
{"Common.UnitCost.label","تكلفة الوحدة"},
{"Common.UnitDose.label","جرعة الوحدة"},
{"Common.UnitPrice.label","سعر الوحدة"},
{"Common.UnitType.label","نوع الوحدة"},
{"Common.UnitofMeasure.label","وحدة القياس"},
{"Common.Unproductive.label","غير منتج"},
{"Common.Up.label","فوق"},
{"Common.Update.label","تحديث"},
{"Common.Usage.label","إستعمال"},
{"Common.UseWithin.label","استخدم في خلال"},
{"Common.UserAccessforStore.label","وصول المستخدم إلى المخزن"},
{"Common.UserAccessforStoreListing.label","وصول المستخدم لقائمة المخزن"},
{"Common.UserDescription.label","وصف المستخدم"},
{"Common.UserEnterable.label","المستخدم قابل للدخول"},
{"Common.Vaccine.label","لقاح"},
{"Common.Value.label","القيمة"},
{"Common.Values.label","القيم"},
{"Common.Variable.label","متغير"},
{"Common.Variance.label","فرق"},
{"Common.VehiclesInvolved.label","المركبات ذات الصلة"},
{"Common.VerificationStatus.label","حالة التحقق"},
{"Common.VerifiedBy.label","أكد عن طريق"},
{"Common.ViewBy.label","مشاهدة بواسطة"},
{"Common.ViewDetails.label","عرض التفاصيل"},
{"Common.VisitAdmDate.label","قم بزيارة تاريخ القبول"},
{"Common.VisitID.label","معرف الزيارة"},
{"Common.Visitor.label","زائر"},
{"Common.VitalSigns.label","علامات حيوية"},
{"Common.WDay.label","WDay"},
{"Common.WarmingUp.label","الاحماء"},
{"Common.Warn.label","حذر"},
{"Common.Warning.label","تحذير"},
{"Common.Web.label","الويب"},
{"Common.Wellness.label","العافية"},
{"Common.WhenScheduled.label","عند الجدولة"},
{"Common.WorkStation.label","محطة عمل"},
{"Common.Working.label","العمل"},
{"Common.Workplace.label","مكان العمل"},
{"Common.WriteLog.label","اكتب السجل"},
{"Common.assignarea.label","منطقة التخصيص"},
{"Common.BurialPermitApprovedDate.label","تاريخ اعتماد اذن الدفن"},
{"Common.notetypedescription.label","نوع الملاحظة الوصف"},
{"Common.searchresult.label","نتيجة البحث"},
{"Common.Right.label","يمين"},
{"Common.CancelCheckout.label","إلغاء الخروج"},
{"Common.CancelAECheckout.label","إلغاء الخروج AE"},
{"Common.CancelOPCheckout.label","إلغاء الخروج OP"},
{"Common.CheckoutDate.label","موعد انتهاء الأقامة"},
{"Common.DisplayOrder.label","ترتيب العرض"},
{"Common.VIP.label","كبار الشخصيات"},
{"Common.SimpleSearch.label","بحث بسيط"},
{"Common.UploadFile.label","رفع ملف"},
{"Common.Cam.label","كاميرا"},
{"Common.KnownAllergy.label","الحساسية المعروفة"},
{"Common.RecordAllergy.label","سجل الحساسية"},
{"Common.basic.label","الأساسي"},
{"Common.advanced.label","المتقدمة"},
{"Common.CancelReservBeds.label","إلغاء حجز الأسرة"},
{"Common.UM_patient.label","جهات مانحة"},
{"Common.Yrs.label","سنوات"},
{"Common.PresentingProblem.label","عرض المشكلة"},
{"Common.GradeCode.label","كود الصف"},
{"Common.Grade.label","درجة"},
{"Common.GradeDescription.label","وصف الصف"},
{"Common.PatientName_fs.label","اسم المريض"},
{"Common.patienttype_fs.label","نوع المريض"},
{"Common.birthDate_fs.label","تاريخ الميلاد"},
{"Common.MailingAddress_fs.label","العنوان البريدي"},
{"Common.relationship_fs.label","صلة"},
{"Common.officephoneno_fs.label","رقم هاتف المكتب"},
{"Common.Address_fs.label","عنوان"},
{"Common.AllergyHistory_fs.label","تاريخ الحساسية"},
{"Common.ReportDateAndTime_fs.label","تاريخ التقرير والوقت"},
{"Common.Signature_fs.label","التوقيع"},
{"Common.Stamp_fs.label","اطابع"},
{"Common.year_fs.label","عام"},
{"Common.SlNo.label","رقم تسلسل"},
{"Common.PatientSearch.label","بحث المريض"},
{"Common.Switch.label","مفتاح كهربائي"},
{"Common.CloseChart.label","إغلاق المخطط"},
{"Common.MainCauseofDeath.label","السبب الرئيسي للوفاة"},
{"Common.MRNo.label","رقم طبي"},
{"Common.FromAppointDate.label","من تاريخ الموعد"},
{"Common.TOAppointDate.label","حتى تاريخ الموعد"},
{"Common.PrefAdmissionDate.label","تاريخ القبول المفضل"},
{"Common.FRPrefAdmissionDate.label","من تاريخ القبول المفضل"},
{"Common.ToPrefAdmissionDate.label","لتاريخ القبول المفضل"},
{"Common.Global.label","عالمي"},
{"Common.PrintedBy.label","طبع بواسطة"},
{"Common.DateAndTimePrinting.label","تاريخ ووقت الطباعة"},
{"Common.NumberOfCopies.label","عدد النسخ"},
{"Common.WorkstationNo.label","رقم محطة العمل "},
{"Common.InitialPrintYN.label","الطباعة الأولية نعم/لا"},
{"Common.TypeofDocument.label","نوع المستند"},
{"Common.ViewPatChartSummary.label","عرض ملخص مخطط المريض"},
{"Common.MDH.label","سبب الوفاة شهور / أيام / ساعات"},
{"Common.InitialPrint.label","طباعة أولية"},
{"Common.InitialPrintDt.label","تاريخ ووقت الطباعة الأولي"},
{"Common.ViewPatChartSummary.label","عرض ملخص مخطط المريض"},
{"Common.LoginDateTime.label","وقت تاريخ تسجيل الدخول"},
{"Common.Select.label","تحديد"},
{"Common.MonthFrom.label","شهر من"},
{"Common.MonthTo.label","شهر ل"},
{"Common.PatFileReqSlipForWalkin.label","قسيمة طلب ملف المريض للمعاينة"},
{"Common.Original.label","أصلي"},
{"Common.NationalItem.label","صنف قومي"},
{"Common.National.label","قومي"},
{"Common.NonNational.label","غير مواطن"},
{"Common.EDClassification.label","تصنيف ED"},
{"Common.Profit.label","الربح"},
{"Common.AnatomicalClass.label","فئة تشريحية"},
{"Common.TherapeuticMainClass.label","التصنيف العلاجي الرئيسي"},
{"Common.TherapeuticSubClass.label","التصنيف العلاجي الفرعي"},
{"Common.ChemicalMainClass.label","الفئة الكيميائية الرئيسية"},
{"Common.ChemicalSubClass.label","فئة فرعية كيميائية"},
{"Common.DetailLevel.label","مستوى التفاصيل"},
{"Common.OPPatientFileRequestSlip.label","قسيمة طلب ملف المريض الخارجي"},
{"Common.IPPatientFileRequestSlip.label","قسيمة طلب ملف المريض الداخلى"},
{"Common.Unoccupied.label","غير مشغول"},
{"Common.SuggestedDiagnosis.label","التشخيص المقترح"},
{"Common.TotalforSpecialty.label","المجموع للتخصص"},
{"Common.Past.label","السابق"},
{"Common.UplodDoc.label","تحميل المستند"},
{"Common.MobileNo.label","رقم الهاتف المحمول"},
{"Common.isinpatient.label","هل داخلى/خروج"},
{"Common.OldFileNo.label","رقم الملف القديم "},
{"Common.ActiveVolumeNumber.label","رقم المجلد النشط"},
{"Common.FileCurrentLocation.label","موقع الملف الحالي"},
{"Common.FileCreatedAt.label","تم إنشاء الملف في"},
{"Common.FileCreatedBy.label","ملف تم إنشاؤه بواسطة"},
{"Common.CancelledDateTime.label","التاريخ / الوقت الملغي"},
{"Common.ApplicableToRadiology.label","ينطبق على الأشعة"},
{"Common.Cause.label","سبب"},
{"Common.Condition.label","شرط"},
{"Common.ICDCode.label","كود التصنيف الدولي للأمراض"},
{"Common.PhysicalStatus.label","الوضع المادي"},
{"Common.TransOverrideReason.label","سبب تجاوز المترجم"},
{"Common.CriteriaNotMet.label","لم تتحقق المعايير"},
{"Common.CriteriaMet.label","تم استيفاء المعايير"},
{"Common.Compliance.label","الامتثال"},
{"Common.Completion.label","إكمال"},
{"Common.GroupSubGroup.label","المجموعة / المجموعة الفرعية"},
{"Common.GroupSubFlag.label","علامة المجموعة / المجموعة الفرعية"},
{"Common.SubGroup.label","المجموعة الفرعية"},
{"Common.SubGroupType.label","نوع المجموعة الفرعية"},
{"Common.ComponentFlag.label","علامة المجموعة الفرعية / المكون"},
{"Common.XAxisLabel.label","تسمية المحور س"},
{"Common.YAxisLabel.label","تسمية المحور ص"},
{"Common.XAxisLabelDataType.label","نوع بيانات المحور س"},
{"Common.YAxisLabelDataType.label","نوع بيانات المحور ص"},
{"Common.PrintSummary.label","ملخص الطباعة"},
{"Common.ProvisionalDiagnosis.label","التشخيص المؤقت"},
{"Common.TotalNumberofDischarges.label","إجمالي عدد حالات الخروج"},
{"Common.MovementLocation.label","موقع الحركة"},
{"Common.Dischargedatecheck.label","يجب أن يكون الخروج حتى التاريخ أكبر من أو يساوي الخروج من التاريخ"},
{"Common.Reportperiodtype.label","نوع فترة التقرير"},
{"Common.Cash.label","السيولة النقدية"},
{"Common.Credit.label","ائتمان"},
{"Common.MedicalLegalCase.label","قضية طبية قانونية"},
{"Common.Armco.label","ارمكو"},
{"Common.DisplayCancelledPreviousEncounters.label","عرض اللقاءات السابقة الملغاة"},
{"Common.CashPatient.label","المريض النقدي"},
{"Common.CashGroup.label","المجموعة النقدية"},
{"Common.documentchecklist.label","وثيقة مرجعية"},
{"Common.CustomerGroup.label","مجموعة العملاء"},
{"Common.Billed.label","فاتورة"},
{"Common.opd.label","العيادات الخارجية"},
{"Common.id_passport_assylum.label","الهوية / جواز السفر / اللجوء / اللاجئ"},
{"Common.FromWeek","من أسبوع"},
{"Common.ToWeek","إلى الأسبوع"},
{"Common.bid.label","مرتين باليوم"},
{"Common.Absconded.label","هرب"},
{"Common.EligibilityCheck.label","التحقق من الأهلية"},
{"Common.Registeredby.label","مسجل بواسطة"},
{"Common.Registrationdatetime.label","تاريخ / وقت التسجيل"},
{"Common.Referralfrom.label","إحالة من"},
{"Common.GoodsandServicesTax.label","ضريبة السلع والخدمات"},
{"Common.GoodsandServicesTaxID.label","رقم ضريبة السلع والخدمات"},
{"Common.ReasonforCancel.label","سبب الالغاء"},
{"Common.Auto.label","تلقاءي"},
{"Common.NOTDONE.label","لم تفعل"},
{"Common.InfectiousDeceasedBody.label","الجثة المعدية المتوفى"},
{"Common.MedicoLegalCase.label","حالة طبية القانونية"},
{"Common.InfectiousDeceasedBodyPart.label","جزء من جسم المتوفى المعدي"},
{"Common.InvestigationOfficer.label","ضابط تحقيق"},
{"Common.DateTime.label","تاريخ الوقت"},
{"Common.ApplicationMode.label","وضع التطبيق"},
{"Common.CollectionMode.label","وضع المجموعة"},
{"Common.NotificationMode.label","وضع الإشعار"},
{"Common.Configuration.label","تهيئة"},
{"Common.BackDateConsultation.label","استشارة بتاريخ سابق"},
{"Common.LocationReschedule.label","إعادة جدولة الموقع"},
{"Common.RescheduleAppointment.label","اعادة جدولة الموعد"},
{"Common.did.label","DID"},
{"Common.CallNotAround.label","غير متاح بالجوار"},
{"Common.MedicalRecords.label","سجلات طبية"},
{"Common.DeathInDepartment.label","الوفاة في القسم"},
{"Common.CernerId.label","معرف ممارس الهجرة"},
{"Common.EmId.label","معرف ممارس طوارئ"},
{"Common.Attendant.label","المصاحبة"},
{"Common.Spouse.label","الزوج"},
{"Common.LegendNameConfig.label","تكوين اسم وسيلة الإيضاح"},
{"Common.Compression.label","ضغط"},
{"Common.AadharCard.label","بطاقة اAdhar"},
{"Common.DeliveryCertificate.label","شهادة التسليم (سورات أكوان برسالين)"},
{"Common.fromTo.label","من / إلى التاريخ"},
{"Common.CDRNoData.label","بيانات المرافق الأخرى CDR غير متوفرة"},
{"Common.FullPayngPatient.label","المريض يدفع الثمن الكامل"},
{"Common.FPP.label","FPP"},
{"Common.Acknowledgement.label","إعتراف"},
{"Common.preadmission.label","موافقة مبدئية"},
{"Common.ApplicationCategory.label","فئة التطبيق"},
{"Common.CancelledOn.label","تم الإلغاء في"},
{"Common.ValidateAlphanumeric.label","تحقق من صحة الأبجدية الرقمية"},
{"Common.statusincomplete.label","الحالة غير مكتملة"},
{"Common.AcceptedRequest.label","طلب مقبول"},
{"Common.Rejectedreport.label","تقرير مرفوض"},
{"Common.RejectedRequest.label","طلب مرفوض"},
{"Common.popup.label","يظهر فجأة"},
{"Common.Therapist.label","المعالج"},
{"Common.PayerNetPayable.label","صافي المدفوعات المستحقة الدفع"},
{"Common.PatientNetPayable.label","صافي مدفوعات المريض"},
{"Common.DiscreteComponent.label","مكون منفصل"},
{"Common.ComponentDescription.label","وصف القطع"},
{"Common.Postmortem.label","بعد الوفاة"},
{"Common.EM.label","طوارئ"},
{"Common.PAC.label","باك"},
{"Common.NRICAltID.label","NRIC / معرف بديل"},
{"Common.AcceptDateTime.label","قبول التاريخ / الوقت"},
{"Common.RejectDateTime.label","تاريخ الرفض / الوقت"},
{"Common.GRNFromDate.label","فترة GRN من"},
{"Common.GRNToDate.label","إلى"},
{"Common.UploadInsDoc.label","تحميل وثيقة التأمين"},
{"Common.PaymentTypeIsCash.label","نوع الدفع المواجه هذا هو النقد."},
{"Common.StaffID.label","معرف الموظفين"},
{"Common.StaffName.label","اسم الموظفين"},
{"Common.Army.label","جيش"},
{"Common.FamilyArmy.label","أسر المحاربين"},
{"Common.VeteranArmy.label","قدامى الجيش"},
{"Common.Public.label","عامة"},
{"Common.Service/Subservice.label","الخدمة/الخدمة الفرعية"},
{"Common.ClinicLocation.label","موقع العيادة"},
{"Common.Download.label","تنزيل"},
{"Common.AllergyHistoryArb.label","تاريخ الحساسية"},
{"Common.HomePhoneNoArb.label","رقم هاتف المنزل"},
{"Common.TrueAndValid.label","صحيحة"},
{"Common.CertifiedAllInformation.label","جميع المعلومات معتمدة"},
{"Common.UplodDoc.label","تحميل المستند"},
{"Common.Without.label","بدون"},
{"Common.Workload.label","عبء العمل"},
{"Common.WithAppt.label","موعد حجز"},
//Below added for PMG2021-MOHE-CRF-0002
{"Common.NRIC.label","الرقم القومي"},
{"Common.Tfrfm.label","الإنتقال من"},
{"Common.Tfrto.label","الإنتقال إلى"},
{"Common.Appt.label","موعد"},
{"Common.ForThePeriod.label","للفترة"},
{"Common.Sno.label","الرقم المسلسل"},
{"Common.IdentificationBadgeRel.label","التعريف / الشارة / العلاقة"},
{"Common.ProcedureTest.label","الإجراء/ الاختبار"},
{"Common.SickDays.label","أيام المرض"},
{"Common.CompanyMR.label","الرقم الطبي للشركة"},
{"Common.TOTALFUP.label","إجمالي زيارات المتابعة"},
{"Common.GRANDNEW.label","إجمالي الزيارات الجديدة"},
{"Common.GRANDFUP.label","الإجمالي الكلي لزيارات المتابعة"},
{"Common.CustomerName.label","اسم الزبون"},
{"Common.CustomerGroupCode.label","كود مجموعة العملاء"}, 
{"Common.CustomerGroupSummary.label","ملخص مجموعة العملاء"},
{"Common.TransactionEffectedByID.label","المعاملة تتأثر بالمعرف"}, 
{"Common.ListofTransactionRecords.label","قائمة سجلات المعاملات"},
{"Common.Num.label","رقم"}, 
{"Common.U.label","غير معروف"},
{"Common.T.label","إجمالي"},
{"Common.Withtotal.label","مع الإجمالي"}, 
{"Common.CompanyName.label","اسم الشركة"},
{"Common.BadgeNo.label","رقم الشارة"},
{"Common.currentpatientonly.label","المريض الحالي فقط"},
{"Common.Rangeindays.label","المدى بالأيام"},
{"Common.Jan.label","يناير"},
{"Common.Feb.label","فبراير"},
{"Common.Mar.label","مارس"},
{"Common.Apr.label","ابريل"},
{"Common.May.label","مايو"},
{"Common.Jun.label","يونيو"},
{"Common.Jul.label","يوليو"},
{"Common.Aug.label","أغسطس"},
{"Common.Sep.label","سبتمبر"},
{"Common.Oct.label","أكتوبر"},
{"Common.Nov.label","نوفمبر"},
{"Common.Dec.label","ديسمبر"},
{"Common.Totalfortheyear.label","الإجمالي للسنة"},
{"Common.Totalforthefacility.label","الإجمالي للمنشأة الصحية"},
{"Common.NRICOthID.label","الرقم القومي/ معرف آخر بديل"},
{"Common.AdmittedBy.label","تم تسجيل الدخول بواسطة"},
{"Common.LenOfStay.label","عدد أيام الإقامة"},
{"Common.CurrEncDiagDesc.label","وصف تشخيص الزيارة الحالية"},
{"Common.OpenActiveDiagDesc.label","وصف التشخيص النشط"},
{"Common.TotalCase.label","إجمالي الحالة"},
{"Common.AllGovernorates.label","كل المحافظات"},//Added by Arthi for MOHE-CRF-0134 and MOHE-CRF-0136
{"Common.ClinicCategory.label","فئة العيادة"},//added manju
{"Common.ClinicCategoryman.label","فئة العيادة إلزامية"},
{"Common.CurrentStatus.label","الحالة الحالية"},
{"Common.virtualConsultation.label","استشارة افتراضية"}, //added by Himanshu Saxena for ML-MMOH-CRF-1930(U1)
{"Common.CancelForAdmission.label","إلغاء للقبول"},
{"Common.MlcDeath.label", "الموت MLC"},
{"Common.OutMlcNoDtls.label", "خارج MLC رقم / تفاصيل"},
{"Common.DateOfMlcCapture.label", "تاريخ التقاط MLC"},
{"Common.DeathRegForm.label", "نموذج تسجيل الوفاة"},
{"Common.SuccessfulAuthentication.label","المصادقة الناجحة"},
{"Common.UnsuccessfulAuthentication.label","مصادقة غير ناجحة"},
{"Common.RestrictReinstate.label", " تقييد/إعادة"}

	};
}
