
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from eCP.AssessBasedDepClassification.AssessBasedDepClassificationManager
package eCP.AssessBasedDepClassification;

/**
 * Local-Home interface for AssessBasedDepClassification
 */
public interface AssessBasedDepClassificationLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/AssessBasedDepClassificationLocal";
    public static final String JNDI_NAME = "AssessBasedDepClassificationLocal";

    eCP.AssessBasedDepClassification.AssessBasedDepClassificationLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
