/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package ePO.resources;

import java.util.*;

public class Labels extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
			
			{"ePO.AccNoDesc.label","Acct Description"},
			{"ePO.AccountNumber.label","Account No"},
			{"ePO.SuppAccountNumber.label","Supplier Account No"},
			{"ePO.AccountNumberDescription.label","Account No Description"},
			{"ePO.Acct/DeptID/OperUnit.label","Acct/DeptID/OperUnit"},
			{"ePO.AcctNumber.label","Account No"},
			{"ePO.Add.label","Add"},
			{"ePO.AdditionalBudget.label","Additional Budget"},
			{"ePO.AdditionalDetails.label","Additional Details"},
			{"ePO.AddressLine1.label","Address Line 1"},
			{"ePO.AddressLine2.label","Address Line 2"},
			{"ePO.AddressLine3.label","Address Line 3"},
			{"ePO.AllocatedBudget.label","Allocated Budget"},
			{"ePO.AllowUnfinalizedGRNThroughInterface.label","Allow Unfinalized GRN Through Interface"},
			{"ePO.Approval.label","Approval"},
			{"ePO.ApprovalReference.label","Approval Reference"},
			{"ePO.AuthorisedSignature.label","Authorised Signature"},
			{"ePO.AutoGenerate.label","Auto Generate"},
			{"ePO.BackOrderQty.label","Back Order Qty"},
			{"ePO.BalanceBudget.label","Balance Budget"},
			{"ePO.BillTo.label","Bill To"},
			{"ePO.BillToAddress.label","Bill To Address"},
			{"ePO.BinnLocation.label","Bin Location"},			
			{"ePO.BlanketPurchase.label","Blanket Purchase"} ,
			{"ePO.BlockedBudget.label","Blocked Budget"},
			{"ePO.Buyer.label","Buyer"},
			{"ePO.Cancel.label","Cancel"},
			{"ePO.CommitmentCode.label","Commitment Code"},
			{"ePO.CommitmentCodeAdditionalDetails.label","Commitment Code Additional Details"},
			{"ePO.ConvFactorRule.label","Conv Factor/Rule"},
			{"ePO.Create.label","Create"},
			{"ePO.DefaultInterfaceGRNValues.label","Default InterfaceGRN Values"},
			{"ePO.DefaultStore.label","Default Store"},
			{"ePO.DelDueDate.label","Delivery Due Date"},
			{"ePO.Delete.label","Delete"},
			{"ePO.DeliverTo.label","Deliver To"},
			{"ePO.DeliverToAddress.label","Deliver To Address"},
			{"ePO.DeliveryMode.label","Delivery Mode"},
			{"ePO.DeliveryScheduleDetails.label","Delivery Schedule Details"},
			{"ePO.Department.label","Department"},
			{"ePO.DeptId.label","Department Id"},
			{"ePO.Discount.label","Discount"},
			{"ePO.DiscountType.label","Discount Type"},
			{"ePO.DocDateFrom.label","Doc Date From"},
			{"ePO.DocGenMethod.label","Doc Gen. Method"},
			{"ePO.EffectiveFrom.label","Effective From"},
			{"ePO.EffectiveTo.label","Effective To"},
			{"ePO.EnterItemDetails.label","Enter Item Details"},
			{"ePO.EnteredDate.label","Entered Date"},
			{"ePO.Error.label","Error"},
			{"ePO.ExchangeRate.label","Exchange Rate"},
			{"ePO.ExpDelDate.label","Expected Delivery Date"},
			{"ePO.Facility.label","Facility"},
			{"ePO.GlobalUnit.label","Global Unit"}, 	
			{"ePO.GrossAmount.label","Gross Amount"},
			{"ePO.HeaderRemarks1.label","Header Remarks - 1"},
			{"ePO.HeaderRemarks2.label","Header Remarks - 2"},
			{"ePO.InterfacePOApplicable.label","Purchase Order Applicable"},
			{"ePO.Item.label","Item"}, 
			{"ePO.ItemRemarks.label","Item Remarks"},
			{"ePO.LabelwithBarcode.label","Label with Barcode"},
			{"ePO.LocalCurrency.label","Local Currency"},
			{"ePO.Manual.label","Manual"},			
			{"ePO.MasterCode.label","Master Code"}, 
			{"ePO.MasterCodeDesc.label","Master Code Description"} ,
			{"ePO.MasterType.label","Master Type"}, 
			{"ePO.Modify.label","Modify"},
			{"ePO.NetAmount.label","Net Amount"},
			{"ePO.NextDocNo.label","Next Doc. No."},
			{"ePO.NotApplicable.label","Not Applicable"},
			{"ePO.OldPurchaseNo.label","Old Purchase No."},
			{"ePO.OldPurchaseOrderNo.label","Old Purchase Order No"},
			{"ePO.OrderDate.label","Order Date"},
			{"ePO.OrderQty.label","Order Qty"},
			{"ePO.OrderRemarks.label","Order Remarks"},
			{"ePO.OrderUOM.label","Order UOM"},
			{"ePO.PODate.label","PO Date"},
			{"ePO.POItemDetails.label","PO Item Details"},
			{"ePO.POMode.label","PO Mode"},
			{"ePO.PONo.label","PO No"},
			{"ePO.PONumber.label","PO Number"},
			{"ePO.POQty.label","PO Quantity"},
			{"ePO.PORaisedBy.label","Purchase Unit"},
			{"ePO.PORef.label","PO Ref"},
			{"ePO.PaymentTerms.label","Payment Terms"},
			{"ePO.PeriodFromDate.label","Period From Date"},
			{"ePO.PoDate.label","PO Date"},
			{"ePO.PoDateFrom.label","PO Date From"},
			{"ePO.PrefixFacility.label","Prefix Facility"},
			{"ePO.PrefixPurchaseUnit.label","Prefix Purchase Unit"},
			{"ePO.PrefixYear.label","Prefix Year"},
			{"ePO.PurchaseMode.label","Purchase Mode"}, 
			{"ePO.PurchaseNo.label","Purchase No"},
			{"ePO.PurRequePONo.label","Pur RequePO No"},
			{"ePO.PurchaseOrder.label","Purchase Order"},
			{"ePO.PurchaseOrderAmend.label","Purchase Order Amend"},
			{"ePO.PurchaseOrderCancel.label","Purchase Order Cancel"},
			{"ePO.PurchaseOrderCreate.label","Purchase Order Create"},
			{"ePO.PurchaseOrderDetails.label","Purchase Order Details"},
			{"ePO.PurchaseOrderFinalize.label","Purchase Order Finalize"},
			{"ePO.PurchasePrice.label","Purchase Price"},
			{"ePO.PurchaseRequePO.label","Purchase RequePO"},
			{"ePO.PurchaseRequePODetails.label","Purchase RequePO Details"},
			{"ePO.PurchaseRequestCancel.label","Purchase Request Cancel"},
			{"ePO.PurchaseRequestCreate.label","Purchase Request Create"},
			{"ePO.PurchaseRequestFinalize.label","Purchase Request Finalize"},
			{"ePO.PurchaseType.label","Purchase Type"},
			{"ePO.PurchaseUnit.label","Purchase Unit"},
			{"ePO.PurchaseUnitCode.label","Purchase Unit Code"}, 
			{"ePO.PurchaseUnitDesc.label","Purchase Unit Description"}, 
			{"ePO.PurchaseUnitDescription.label","Purchase Unit Description"},
			{"ePO.Quantity/UOM.label","Quantity/UOM"},
			{"ePO.QuotationNo.label","Total Quotation No."},
			{"ePO.QuotationNoTenderRef.label","Quotation No/Tender Ref."},
			{"ePO.QuotationNumber.label","Quotation No."},
			{"ePO.Remarks.label","Remarks"},
			{"ePO.RepackingLabelWithBarcode.label","Repacking Label With Barcode"},
			{"ePO.RepackingLabelWithoutBarcode.label","Repacking Label Without Barcode"},
			{"ePO.ReqQty.label","Req Qty"},
			{"ePO.ReqUOM.label","Req UOM"},
			{"ePO.ReqUOMQty.label","Req UOM Qty"},
			{"ePO.RequePOType.label","RequePO Type"},
			{"ePO.RequestDateFrom.label","Request Date From"},
			{"ePO.RequestNo.label","Request No"},
			{"ePO.RequestOnDepartment.label","Request On Department"},
			{"ePO.RequestType.label","Request Type"},
			{"ePO.RequestbyStore.label","Request by Store"},
			{"ePO.RequiredByDate.label","Required By Date"},
			{"ePO.Revision.label","Revision"},
			{"ePO.S.label","#"},
			{"ePO.SNo.label","S.No"},
			{"ePO.StartDocNo.label","Starting Doc. No."},
			{"ePO.Supplier.label","Supplier"},
			{"ePO.SupplierAddress.label","Supplier Address"},
			{"ePO.SupplierAddressLine1.label","Supplier Address Line 1"},
			{"ePO.TermsAndCondCode.label","Terms and Conditions Code"},
			{"ePO.TermsAndCondDesc.label","Description"},
			{"ePO.TermsAndConditions.label","Terms & Conditions"},
			{"ePO.ToPurUnit.label","To Purchase Unit"},
			{"ePO.TotalPOAmount.label","Total PO Amount"},
			{"ePO.TradeName.label","Trade Name"},
			{"ePO.TransactionApplicable.label","Transaction Applicable"},
			{"ePO.TransactionCurrency.label","Transaction Currency"},
			{"ePO.TransactionType.label","Transaction Type"},
			{"ePO.UnitPrice.label","Unit Price"}, 
			{"ePO.UserStoreAccessApplicable.label","User Store Access Applicable"},
			{"ePO.ValidUpto.label","Valid Upto"},
			{"ePO.Warning.label","Warning"},
			{"ePO.Year.label","Year"},
			{"ePO.cancel.label","Cancel"},
			{"ePO.defaultSelect.label","Select"},
			{"ePO.uom.label","UOM"},
			{"ePO.ItmLvlOrdApReq.label","Item Label Order Approval Required"}, 
    		{"ePO.AlowOvOrDelDt.label","Allow Override Of Order Delivery Date"}, 
			{"ePO.AlowOvOrQtRe.label","Allow Override Of Order Quantity During Receiving"}, 
			{"ePO.AlowOvOrPrRe.label","Allow Override Of Order Price During Receiving"},
			{"ePO.PurchaseRequest.label","Purchase Request"},
			{"ePO.RequestDate.label","Request Date From"},
			{"ePO.Request Date.label","Request Date"},
			{"ePO.Approval.label","Approved"},
			{"ePO.DeliverToBillToDetails.label","Deliver To & Bill To Details"}, 
			{"ePO.DeliverTo.label","Deliver To"}, 
			{"ePO.BillTo.label","Bill To"},
			{"ePO.ListPrice.label","List Price"},
			{"ePO.ItemDetails.label","Item Details"},		
			{"ePO.requestStatus.label","Request Status"},
			{"ePO.requestItem.label","Item"},
			{"ePO.docDateFrm.label","Doc Date From"},
			{"ePO.documentDate.label","Doc Date"},
			{"ePO.docDateTo.label","To"},
			{"ePO.reqStore.label","Req Store"},
			{"ePO.purchaseItem.label","Item"},
			{"ePO.docNo.label","Doc No"},
			{"ePO.documentNo.label","Document Number"},
			{"ePO.orderStatus.label","Order Status"},
			{"ePO.description.label","Description"},
			{"ePO.requiredQty.label","Req Qty"},
			{"ePO.poQty.label","PO Qty"},
			{"ePO.pendingGRNQty.label","Pending GRN Qty"},
			{"ePO.approvalRefNo.label","Approval Ref. No"},
			{"ePO.enteredBy.label","Entered By"},
			{"ePO.enteredOn.label","Entered On"},
			{"ePO.pendingORDQty.label","PendingOrderQty"},
			{"ePO.OverrideBudgetControl.label","Override Budget Control"},
			{"ePO.OverrideWarning.label","Override Budget Warning"},
			{"ePO.OverrideError.label","Override Budget Error"},
			{"ePO.RequestRemarks.label","Request Remarks"},
			{"ePO.StoreDetails.label","Store Details"},
			{"ePO.RequestNumber.label","Request Number"},
			{"ePO.StoreCode.label","Store Code"},
			{"ePO.StoreName.label","Store Name"},
			{"ePO.FacilityCode.label","Facility Code"},
			{"ePO.FacilityName.label","Facility Name"},
			{"ePO.lastAccssBy.label", "Approved By"}, 
			{"ePO.lastAccssOn.label", "Approved Date"},
			{"ePO.POMasterType.label","PO Master Type/Code"},
			{"ePO.SupplierDescription.label","Supplier Description"},
			{"ePO.Currency.label","Currency"},
			{"ePO.PurchaseOrderNumber.label","Purchase Order No"},
			{"ePO.Date.label","Date"},
			{"ePO.DateFrom.label","Date From"},
			{"ePO.Status.label","Status"},
			{"ePO.Mode.label","Mode"},
			{"ePO.ItemDescription.label","Item Description"},
			{"ePO.RequestQty.label","Request Qty"},
			{"ePO.RequestUOM.label","Request UOM"},
			{"ePO.OrderQty.label","Order Qty"},
			{"ePO.OrderUOM.label","Order UOM"},
			{"ePO.ItemUnitCost.label","Item Unit Cost"},
			{"ePO.CostValue.label","Cost Value"},
			{"ePO.GRNNo.label","GRN No"},
			{"ePO.ReceivedQty.label","Received Qty"},
			{"ePO.ReceivedUOM.label","Received UOM"},
			{"ePO.ReceivedValue.label","Received Value"},
			{"ePO.PendingQty.label","Pending Qty"},
			{"ePO.ItemTotal.label","Item Total"},
			{"ePO.OrderQtyBreakup.label","Order Qty Breakup"},
			{"ePO.PlannedDevlDt.label","Planned Devl Dt."},
			{"ePO.ReceivedDate.label","Received Date"},
			{"ePO.POItemRemarks.label","PO Item Remarks"},
			{"ePO.POApprovalRemarks.label","PO Approval Remarks"},	
			{"ePO.DeliveryStatus.label","Delivery Status"},	
			{"ePO.RequestDetails.label","Request Details"},
			{"ePO.POStatus.label"," PO Status"},
			
			{"ePO.DOType.label","Delivery Order Type"},
			{"ePO.DONo.label","DO No"},
			{"ePO.DODate.label","DO Date"},
			{"ePO.DORef.label","DO Ref"},
			{"ePO.itemCode.label","Item Code"},
			{"ePO.itemDesc.label","Item Desc"},
			{"ePO.POUOM.label","PO UOM"},
			{"ePO.TradeId.label","Trade Id"},
			{"ePO.ExpiryDate.label","Expiry Date"},
			{"ePO.BatchId.label","Batch Id"},
			{"ePO.DeliveryUOM.label","Delivery UOM"},
			{"ePO.FreeQty.label","Free Qty"},
			{"ePO.SampleQty.label","Sample Qty"},
			{"ePO.DeliveryQty.label","Delivery Qty"},
			{"ePO.Store.label","Store"},
			{"ePO.DORemarks.label","DO Remarks"},
			{"ePO.RejectedQty.label","Rejected Qty"},
			{"ePO.RejectionRmks.label","Rejection Rmks"},
			{"ePO.ItemRmks.label","Item Rmks"},
			{"ePO.ScheduledDate.label","Scheduled Date"},
			{"ePO.DeliveryOrderDetails.label","Delivery Order Details"},
			{"ePO.InvoiceNo.label","Invoice No"},
			{"ePO.InvoiceDate.label","Invoice Date"},
			{"ePO.InvoiceReceivedBy.label","Invoice Received By"},
			{"ePO.DeliveryRemarks.label","Delivery Remarks"},
			{"ePO.MoreDtls.label","More Dtls"},
			{"ePO.QtyDistribution.label","Qty Distribution"},
			{"ePO.Price.label","Price"},
			{"ePO.DeliveryQtyDistribution.label","Delivery Qty Distribution"},
			{"ePO.DeliveryOrder.label","Delivery Order"},
			{"ePO.pendingPoQty.label","Pending Qty"},
			{"ePO.UnitCost.label","Unit Cost"},
			{"ePO.MultiBatchDetails.label","Batch Details"},
			{"ePO.pendingOrder.label","Pending Order"},
			{"ePO.Delivery.label","Delivery"},
			{"ePO.Qty.label","Quantity"},
			//Added By Sakti Sankar against Inc#30079
			{"ePO.OrderNo.label", "Order No"},
			{"ePO.ScheduleNo.label", "Schedule No"},
			{"ePO.ScheduleDate.label", "Schedule Date"},
			{"ePO.DeliveredQty.label", "Delivered Qty"},
			{"ePO.DeliveryNo.label", "Delivery No"},
			{"ePO.DeliveryStatus.label", "Delivery Status"},
			{"ePO.PoMendatForDevorder.label", "Purchase Order Mandatory for Delivery Order"},
			{"ePO.AllowChangePurPrice.label", "Allow Change to Purchase Price During Delivery"},
			{"ePO.DoQty.label","DO Qty"},
			{"ePO.DoUOM.label","DO UOM"},
			{"ePO.DODateFrom.label","DO Date From"},
			{"ePO.DOItemDetails.label","DO Item Details"},
			{"ePO.DeliveryOrderCancel.label","Delivery Order Cancel"},
			{"ePO.DeliveryOrderCreate.label","Delivery Order Create"},
			{"ePO.DeliveryOrderDelete.label","Delivery Order Delete"},
			{"ePO.DeliveryOrderFinalize.label","Delivery Order Finalize"},
			{"ePO.GrossDOAmount.label","Gross DO Amount"},
			{"ePO.NetDOAmount.label","Net DO Amount"},
			{"ePO.AdditionalDiscount.label","Additional Discount"},
				// Quotation
			{"ePO.Quotation.label","Quotation"},
			{"ePO.QuotationCreate.label","Quotation Create"},
			{"ePO.QuotationFinalize.label","Quotation Finalize"},
			{"ePO.QuotationCancel.label","Quotation Cancel"},
			{"ePO.QuotationDelete.label","Quotation Delete"},
			{"ePO.QuotNo.label","Quotation No"},
			{"ePO.QuotDate.label","Quotation Date"},
			{"ePO.QuotRef.label","Quotation Ref"},
			{"ePO.QuotType.label","Quotation Type"},
			{"ePO.ContactPerson.label","Contact Person"},
			{"ePO.DateOfAdvt.label","Submit for Advt Date"},
			{"ePO.ApprovedDate.label","Approved Date"},
			{"ePO.OpenDate.label","Open Date"},
			{"ePO.ClosedDate.label","Closed Date"},
			{"ePO.DrugPurchasingRecordDate.label","Drug Purchasing Record Date"},
			{"ePO.ClerkRecordDate.label","Clerk Record Date"},
			{"ePO.InitialEvaluationDate.label","Initial Evaluation Date"},
			{"ePO.QCResultDate.label","QC Result Date"},
			{"ePO.CheckedDate.label","Checked Date"},
			{"ePO.MeetingDate.label","Meeting Date"},
			{"ePO.RecordAfterMeetingDate.label","Record After Meeting Date"},
			{"ePO.SubmittedDate.label","Submitted Date"},
			{"ePO.QuotationRemarks.label","Quotation Remarks"},
			{"ePO.QuotationQty.label","Quotation Qty"},
			{"ePO.QuotationUOM.label","Quotation UOM"},
			{"ePO.Replacable.label","Replacable"},
			{"ePO.SampleProvided.label","Sample Provided"},
			{"ePO.Manufacturer.label","Manufacturer"},
			{"ePO.TradeId.label","TradeId"},
			{"ePO.MoreDetails.label","More Details"},
			{"ePO.ItemStatus.label","Item Status"},
			{"ePO.EvaluationFactor.label","Evaluation Factor"},
			{"ePO.SelectionCriteria.label","Selection Criteria"},
			{"ePO.QuotnQty.label","Quotn Qty"},
			{"ePO.QuotnUOM.label","Quotn UOM"},
			{"ePO.QuotationDetails.label","Quotation Details"},
			{"ePO.GrossQuotAmount.label","Gross Quot Amount"},
			{"ePO.NetQuotAmount.label","Net Quot Amount"},
			{"ePO.DelvFreqType.label","Delivery Frequency Type"},
			{"ePO.NoOfDelv.label","No Of Deliveries"},
			{"ePO.FirstDelvDate.label","First Delivery Date"},
			{"ePO.EqShipment.label","Equal Shipment"},
			{"ePO.CatalogueNo.label","Catalogue No"},
			{"ePO.CountryOfOrigin.label","Country Of Origin"},
			{"ePO.ItemSpecification.label","Item Specification"},
			{"ePO.QuotationSelectionCriteria.label","Quotation Selection Criteria"},
			{"ePO.SelectionCriteria.label","Selection Criteria"},
			{"ePO.Status.label","Status"},
			{"ePO.Weightage.label","Weightage"},
			{"ePO.Ranking.label","Ranking"},
			{"ePO.EvalRemarks.label","Evaluation Remarks"},
			{"ePO.Recommendation.label","Recommendation"},
			{"ePO.RecommendedRemarks.label","Remarks"},
			{"ePO.EvaluationFactor.label","Evaluation Factor"},
			{"ePO.QuotationEvaluationFactor.label","Quotation Evaluation Factor"},
			{"ePO.QuotPaymentTerms.label","Payment Terms :"},
			{"ePO.QuotDeliveryMode.label","Delivery Mode :"},
			{"ePO.QuotTermsAndConditions.label","Terms & Conditions :"},
			{"ePO.SubmissiontoAdvt.label","Submission to Advt :"},
			{"ePO.QuotOpenDate.label","Quot.Open Date :"}, 
			{"ePO.QuotClosedDate.label","Quot.Closed Date :"},
			{"ePO.DrugPurchasingRecordDoc.label","Drug Purchasing Record Doc :"},
			{"ePO.QuotClerkRecord.label","Clerk Record :"},
			{"ePO.QuotInitialEvaluation.label","Initial Evaluation :"},
			{"ePO.QCResult.label","QC Result :"},
			{"ePO.QuotCheckedDate.label","Checked Date :"},
		    {"ePO.QuotMeetingDate.label","Meeting Date :"},
			{"ePO.QuotRecordAfterMeeting.label","Record After Meeting :"},
			{"ePO.SubmittedforApproval.label","Submitted for Approval:"}, 
			{"ePO.QuotApprovedDate.label","Approved Date :"},
			{"ePO.QuotContactPerson.label","Contact Person :"},
			{"ePO.QuotationRemarksQuot.label","Quotation Remarks :"},
			{"ePO.DelvFreq.label","Delivery Frequency"},
			{"ePO.Recommended.label","Recommended ?"},
			{"ePO.StockUOM.label","Stock UOM"},
			{"ePO.DeptId/Acc.label","Dept/Acc. Start Dt "},
			{"ePO.POCancel.label","PO Cancel "},
			{"ePO.POClose.label","PO Close "}, 
			{"ePO.PendDeliveredQty.label", "Pending Delivery Qty"},
				//Tender
			{"ePO.TndrType.label", "Tender Type"},
			{"ePO.TndrRef.label", "Tender Ref"},
			{"ePO.TndrNo.label", "Tender No"},
			{"ePO.TndrDate.label", "Tender Date"},
			{"ePO.TndrExpiryDate.label", "Tender Expiry Date"}, 
			{"ePO.TndrApprovalDate.label", "Tender Approval Date"},
			{"ePO.ContractSignDate.label", "Contract Sign Date"},
			{"ePO.TenderRemarks.label", "Tender Remarks"},
			{"ePO.TndrQty.label", "Tender Qty"},
			{"ePO.TndrUOM.label", "Tender UOM"},
			{"ePO.TenderDetails.label", "Tender Details"},
			{"ePO.SupplierDetails.label", "Supplier Details"},
			{"ePO.SupplierListForTender.label", "Supplier List For Tender"},
			{"ePO.ContactNumber.label", "Contact Number"},
			{"ePO.EmailId.label", "Email Id"},
			{"ePO.Tender.label", "Tender"} ,//Added by Rabbani #inc no:30078(Bru-HIMS-CRF-119) on 30-MAY-2013
			{"ePO.TenderCreate.label", "Tender Create"},  
			{"ePO.TenderFinalize.label", "Tender Finalize"},  
			{"ePO.TenderCancel.label", "Tender Cancel"}  ,
			{"ePO.Brand.label", "Brand"}

			
	};
}
 
