/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eOT.resources;

import java.util.*;

public class  Labels  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

// Comments with //Duplicate  are moved to eCommon resource Bundle. Commented and patch sent on 15th May 2008 by bshankar against SCR-3870
	static final Object[][] contents = {
		{"eOT.2ndCount.Label"," 2nd Count"},
		{"eOT.AcceptRemarks.Label"," Accept Remarks"},
		{"eOT.AccessionNum.Label"," Accession Num"},
		{"eOT.AcrossSpecialities.Label"," Across Specialties"},
		{"eOT.ActionDate.Label"," Action Date "},
		{"eOT.ActionIfNotDone.Label"," Action If Not Done"},
		{"eOT.ActionTypesForReason.Label"," Action Type for Reason"},
		{"eOT.AddaSet.Label"," Add a Set"},
		{"eOT.Addaswabcount.Label"," Add a swab count"},
		{"eOT.AdditionsafterClcavityCompl.Label"," Additions after Cl. cavity Completed?"},
		{"eOT.AdditionsduringOP.Label"," Additions during OP"},
		{"eOT.AdditionsDuringOPCompleted.Label"," Additions During OP Completed?"},
		{"eOT.AdditionsduringOperation.Label"," Additions during Operation"},
		{"eOT.Addns.Label"," Addns.."},
		{"eOT.AddnsafterCC.Label"," Additions (after CC.)"},
		{"eOT.AdmittingSpeciality.Label"," Admitting Specialty"},
		{"eOT.AllBookings.Label"," All Bookings"},
		{"eOT.AllCategories.Label"," All Categories"},
		{"eOT.AllElective.Label"," All Elective"},
		{"eOT.AllEmergency.Label"," All Emergency"},
		{"eOT.Allow.Label"," Allow"},
		{"eOT.AllowBarcode.Label"," Allow Barcode"},
		{"eOT.AllowEmergPatwhilefinalizing.Label"," Allow Emergency Patients while finalizing"},
		{"eOT.AllowOutpatientswhilefinalizing.Label"," Allow Outpatients while finalizing"},
		{"eOT.AllTheatres.Label","ALL THEATRES"},
		{"eOT.AllUsers.Label"," All Users"},
		{"eOT.AnaesSerialNo.Label"," Anes.Serial No"},
		{"eOT.AnaesDocCmplTime.Label"," Anesthetist Documentation Completed Time"},
		{"eOT.AnaesthesiaEndTime.Label"," Anesthesia End Time"},
		{"eOT.AnaesthesiaHistory.Label"," Anesthesia History"},
		{"eOT.AnaesthesiaNotes.Label"," Anesthesia Notes"},
		{"eOT.AnaesthesiaNumbering.Label"," Anesthesia Numbering"},
		{"eOT.AnaesthesiaOrderedDate.Label"," Anesthesia Ordered Date"},
		{"eOT.AnaesthesiaOrderedDateFrom.Label"," Anesthesia Ordered Date From"},//AAKH CRF-0069
		{"eOT.AnaesthesiaOrderedDateTo.Label"," Anesthesia Ordered Date To"},//AAKH CRF-0069
		{"eOT.AnaesthesiaParticulars.Label"," Anesthesia Particulars"},
		{"eOT.AnaesthesiaProcedure.Label"," Anesthesia Procedure"},
		{"eOT.AnaesthesiaProcedureEndTime.Label"," Anesthesia Procedure End Time"},
		{"eOT.AnaesthesiaProcedureStartTime.Label"," Anesthesia Procedure Start Time"},
		{"eOT.AnaesthesiaReviewRequired.Label"," Anesthesia Review Required"},
		{"eOT.AnaesthesiaStartTime.Label"," Anesthesia Start Time"},
		{"eOT.AnaesthesiaType.Label"," Anesthesia Type"},
		{"eOT.AnaesthetistWiseTotal.Label","Anesthetist Wise Total"},
		{"eOT.AnyDiscrepanciesinFirstCount.Label"," Any Discrepancies in First Count"},
		{"eOT.AnyDiscrepanciesinFirstCount.Label"," Any Discrepancies within In Count"},//Added against PMG2015-MOD-CRF-0001
		{"eOT.ApplicableForOTSlate.Label"," Applicable For OT Slate"},
		{"eOT.ApplicablePosition.Label"," Applicable Position"},
		{"eOT.AssignAnaesthetist.Label"," Assign Anesthetist"},
		{"eOT.AssignedTheatre.Label"," Assigned Theatre"},
		{"eOT.AssignedTime.Label"," Assigned Time"},
		{"eOT.AssignTheatre.Label"," Assign Theatre"},
		{"eOT.AssociatedAnaesthestist.Label"," Associated Anaesthestist"},
		{"eOT.AsstSurgeon.Label"," Assistant Surgeon"},
		{"eOT.AutoPopulated.Label"," Auto Populated"},
		{"eOT.Amount.Label"," Amount (Baht)"},//Added by lakshmi for CRF-0601
		{"eOT.BackGroundColor.Label"," BackGround Color"},
		{"eOT.BasicSet.Label"," Basic Set"},
		{"eOT.BasicSetSuppltemVerifySwabCnt.Label"," Basic Set / Supplementary Item / Verify Swab Count"},
		{"eOT.Bilateral.Label"," Bilateral"},
		{"eOT.Black.Label"," Black"},
		{"eOT.BlockSlotsByAgeGroup.Label"," Block Slots By Age Group"},			
		{"eOT.BlockSlotsBySpeciality.Label"," Block Slots By Specialty"},			
		{"eOT.BlockSlotsForTheOperatingRoom.Label"," Block Slots for the OperatingRoom"},
		{"eOT.BlockTheatreSlots.Label"," Block Theatre Slots"},			
		{"eOT.Blue.Label"," Blue"},
		{"eOT.BMIDetails.Label"," BMI Details"},
		{"eOT.Book.Label"," Book"},
		{"eOT.BookedCases.Label"," Booked Cases"},
		{"eOT.BookedDate.Label"," Booked Date"},
		{"eOT.BookingFinalizationStages.Label"," Booking Finalization Stages"},
		{"eOT.BookingHeader.Label"," Booking Header"},
		{"eOT.BookingNextNumber.Label"," Booking Next Number"},
		{"eOT.BookingMaxNumber.Label"," Booking Max Number"},
		{"eOT.BookingNO.Label"," Booking NO"},
		{"eOT.BookingNumbering.Label"," Booking Numbering"},
		{"eOT.BookingPriority.Label"," Booking Priority"},
		{"eOT.BookingRemarks.Label"," Booking Remarks"},
		{"eOT.BookingRights.Label"," Booking Rights"},
		{"eOT.BookingScreenSlip.Label"," Booking Screen Slip"},
		{"eOT.BookingStartTime.Label"," Booking Start Time"},
		{"eOT.BookingVerification.Label"," Booking Verification"},
		{"eOT.BookingWaitList.Label"," Booking/WaitList"},
		{"eOT.BookingWindow.Label"," Booking Window"},
		{"eOT.Brown.Label"," Brown"},
		{"eOT.ByPatient.Label"," By Patient"},
		{"eOT.BySpeciality.Label"," By Specialty"},
		{"eOT.BySurgeon.Label"," By Surgeon"},
		{"eOT.ByTimeSeq.Label"," By Time/Seq"},
		{"eOT.BuildAnaesthesiaIntoCR.Label"," Build Anesthesia Into CR"},			
		{"eOT.CancelCheckedInCases.Label"," Cancel Checked-In Cases"},
		{"eOT.CancelledCases.Label"," Cancelled Cases"},
		{"eOT.CancelOrder.Label"," Cancel Order"},
		{"eOT.CancelViewDetails.Label"," Cancel View Details"},
		{"eOT.CancelWaitlist.Label"," Cancel Waitlist"},
		{"eOT.CaseCalledTime.Label"," Case Called Time"},
		{"eOT.ChangeHoldingBay.Label"," Change Holding Bay"},
		{"eOT.ChangeSequence.Label"," Re-Seq"},
		{"eOT.ChangeStage.Label"," Change Stage"},
		{"eOT.ChangeStatusto.Label"," Change Status to"},
		{"eOT.ChangeType.Label"," Change Type"},
		{"eOT.CheckedInDateTime.Label"," Checked-In Date/Time"},
		{"eOT.CheckForChecklistCompleted.Label"," Check For Checklist Completed"},
		{"eOT.CheckIn.Label"," Check-In"},
		{"eOT.CheckInTime.Label"," Check In Time"},
		{"eOT.CheckInToOperatingRoom.Label"," Check-In To Operating Room"},
		{"eOT.CheckIntoOR.Label"," Check-In to OR"},
		{"eOT.CheckIntoORTime.Label"," Check In to OR Time"},
		{"eOT.CheckInToRecoveryRoom.Label"," Check-In To Recovery Room"},
		{"eOT.CheckIntoRecoveryTime.Label"," Check In to Recovery Time"},
		{"eOT.Checklist.Label"," Checklist"},
		{"eOT.Checklists.Label"," Checklists "},
		{"eOT.CheckListCompleted.Label"," CheckList Completed"},
		{"eOT.ChecklistItem.Label"," Checklist Item"},
		{"eOT.ChecklistItemCode.Label"," Checklist Item Code"},
		{"eOT.ChecklistType.Label"," Checklist Type"},
		{"eOT.CheckOut.Label"," Check-Out "},
		{"eOT.CheckOutFromRecoveryRoom.Label"," Check-Out From Recovery Room"},
		{"eOT.CheckOutFromWard.Label"," Check-Out From Ward"},
		{"eOT.Check-OutPatient.Label"," Check-Out Patient"},
		{"eOT.CheckOutTime.Label"," Check-Out Time"},
		{"eOT.CodingScheme.Label"," Coding Scheme"},
		{"eOT.ConsentDateTime.Label"," Consent Date/Time"},
		{"eOT.ConsentTakenBy.Label"," Consent Taken By"},
		{"eOT.ConsentTakenFrom.Label"," Consent Taken From"},
		{"eOT.ConsignmentItem.Label"," Consignment Item"},
		{"eOT.ConsumableItemTooltip.Label"," This is a Consumable Item. It cannot be returned "},
		{"eOT.ConsumablePacks.Label"," Consumable Packs"},
		{"eOT.Consumables.Label"," Consumables"},
		{"eOT.CrossReferenceItem.Label"," Cross Reference Item"},
		{"eOT.CrossReferenceItemCode.Label"," Cross Reference Item Code"},
		{"eOT.CrossRefMMItem.Label"," Cross-Ref MM Item"},
		{"eOT.CrossRefSSGroup.Label"," Cross-Ref SS Group"},
		{"eOT.CSSDQty.Label"," CSSD Qty"},
		{"eOT.CSSDStoreCode.Label"," CSSD Store Code"},
		{"eOT.Cumulative.Label"," Cumulative"},
		{"eOT.CurrentMedicationAlert.Label"," Current Medication Alert"},
		{"eOT.CurrentSequence.Label"," Seq"},
		{"eOT.CurrentStage.Label"," Current Stage"},
		{"eOT.Cyan.Label"," Cyan"},
		{"eOT.priority1Case.label","Priority-1 Case"},
		{"eOT.priority1.label","Priority-1"},
		{"eOT.priority2.label","Priority-2"},
		{"eOT.priority3.label","Priority-3"},
		{"eOT.DarkBlue.Label"," Dark Blue"},
		{"eOT.DarkCyan.Label"," Dark Cyan"},
		{"eOT.DarkGreen.Label"," Dark Green"},
		{"eOT.DarkRed.Label"," Dark Red"},
		{"eOT.DateofSurgery.Label"," Date of Surgery"},
		{"eOT.DaySchedule.Label"," Day Schedule"},
		{"eOT.DaySpecific.Label"," Day Specific"},
		{"eOT.DayRefCode.Label","Day RefCode"},
		{"eOT.DefaultStoreCode.Label"," Default Store Code"},
		{"eOT.DepositRequired.Label"," Deposit Required?"},
		{"eOT.DiaryGeneratedupto.Label"," Diary Generated upto"},
		{"eOT.DiaryScheduleforSurgeon.Label"," Diary Schedule for Surgeon"},
		{"eOT.DiaryScheduleforTheatre.Label"," Diary Schedule for Theatre"},
		{"eOT.Disposal.Label"," Disposal"},
		{"eOT.DisposalCode.Label"," Disposal Code"},
		{"eOT.DisposalDescription.Label"," Disposal Description"},
		{"eOT.DisposalDetails.Label"," Disposal Details"},
		{"eOT.DisposedItem.Label"," Disposed Item"},
		{"eOT.DocumentationCompleted.Label"," Documentation Completed"},
		{"eOT.DocumentationCompletionStatusCheck.Label"," Documentation Completion Status Check"},
		{"eOT.DocumentationLevel.Label"," Documentation Level"},
		{"eOT.ConsumablesUsed.Label"," Consumables Used"},
		{"eOT.DrugsForNotification.Label"," Drugs for Notification"},
		{"eOT.EmailPrintReminderLetter.Label"," Email/Print Reminder Letter"},
		{"eOT.EmergencyCases.Label"," Emergency Cases"},
		{"eOT.EncounterLookup.Label"," Encounter Lookup"},
		{"eOT.EnterPIN.Label"," Enter PIN"},
		{"eOT.Episode.Label"," Episode"},
		{"eOT.EpisodeDetails.Label"," Episode Details"},
		{"eOT.EpisodeTypeID.Label"," Episode Type / ID"},
		{"eOT.EquipmentCode.Label"," Equipment Code"},
		{"eOT.EquipmentID.Label"," Equipment ID"},
		{"eOT.Equipments.Label"," Equipments"},
		{"eOT.EquipmentsDetails.Label"," Equipments Details"},
		{"eOT.Exam.Label"," Exam"},
		{"eOT.ExamsCheckList.Label"," Exams CheckList"},
		{"eOT.Extubated.Label"," Extubated"},
		{"eOT.FacilityIDFrom.Label"," Facility ID From"},
		{"eOT.FacilityIDTo.Label"," Facility ID To"},
		{"eOT.FifthWeek.Label"," Fifth Week"},
		{"eOT.FinalCount.Label"," Final Count"},
		{"eOT.FinalCountCompleted.Label"," Final Count Completed?"},
		{"eOT.Finalise.Label"," Finalize"},
		{"eOT.FinalisedBookings.Label"," Finalized Bookings"},
		{"eOT.FinalStatus.Label"," Final Status"},
		{"eOT.FinalStatusRemarks.Label"," Final Status Remarks "},
		{"eOT.FinalStatusCompleted.Label"," Final Status Completed? "},
		{"eOT.FinishDate.Label"," Finish Date"},
		{"eOT.FinishTime.Label"," Finish Time"},
		{"eOT.FinishDateTime.Label"," Finish Date/Time"},
		{"eOT.FirstAvailableDate.Label"," First Available Date"},
		{"eOT.FirstCount.Label"," First Count"},
		{"eOT.InCount.Label"," In Count"},//Added against PMG2015-MOD-CRF-0001
		{"eOT.FirstCountCompleted.Label"," First Count Completed?"},
		{"eOT.InCountCompleted.Label"," In Count Completed?"},//Added against PMG2015-MOD-CRF-0001
		{"eOT.FirstWeek.Label"," First Week"},
		{"eOT.FourthWeek.Label"," Four Week"},
		{"eOT.FromAdmissionDate.Label"," From Admission Date"},
		{"eOT.FromAnaesthesia.Label"," From Anesthesia"},
		{"eOT.FromAnaesthetist.Label"," From Anesthetist"},
		{"eOT.FromBookingDate.Label"," From Booking Date"},
		{"eOT.FromOperationDate.Label"," From Operation Date"},
		{"eOT.FromOperationRoom.Label"," From Operation Room"},
		{"eOT.FromOperationNO.Label"," From Operation NO"},
		{"eOT.FromOperationType.Label"," From Operation Type"},
		{"eOT.FromPosition.Label"," From Position"},
		{"eOT.FromProcedure.Label"," From Procedure "},
		{"eOT.FromProcedureDate.Label"," From Procedure Date "},
		{"eOT.FromRegistrationDate.Label"," From Registration Date"},
		{"eOT.FromSpeciality.Label"," From Specialty "},
		{"eOT.FromSurgeon.Label"," From Surgeon"},			
		{"eOT.FromSurgeryDate.Label"," From Surgery Date"},
		{"eOT.FunctionDescription.Label"," Function Description"},
		{"eOT.FunctionsForRole.Label"," Functions for Role"},
		{"eOT.FunctionsForUser.Label"," Functions for User"},
		{"eOT.FunctionsForStatus.Label"," Functions for Status"},
		{"eOT.FunctionID.Label"," Function ID"},
		{"eOT.Gray.Label"," Grey"},
		{"eOT.HoldingArea.Label"," Holding Area"},
		{"eOT.HoldingAreaDetails.Label"," Holding Area Details"},
		{"eOT.HoldingAreaNotes.Label"," Holding Area Notes"},
		{"eOT.HoldingAreaTime.Label"," Holding Area Time"},
		{"eOT.HoldingBay.Label"," Holding Bay"},
		{"eOT.HolidayEndTime.Label"," Holiday End Time"},
		{"eOT.HolidayStartTime.Label"," Holiday Start Time"},
		{"eOT.HospitalPersonnel.Label"," Hospital Personnel"},
		{"eOT.Implants.Label"," Implants"},
		{"eOT.ImplantType.Label"," Implant Type"},
		{"eOT.ImplantUsed.Label"," Implant Used"},
		{"eOT.ImplantVendor.Label"," Implant Vendor"},
		{"eOT.Indigo.Label"," Indigo"},
		{"eOT.InformedWard.Label"," Informed Ward"},
		{"eOT.Interfaces.Label"," Interfaces"},
		{"eOT.InterfacetoCSSD.Label"," Interface to CSSD"},
		{"eOT.InterfacetoInventory.Label"," Interface to Inventory"},
		{"eOT.InterfacetoRevenuemanag.Label"," Interface to Patient Billing"},
		{"eOT.Initial.Label"," Initial"},
		{"eOT.InitialCount.Label"," Initial Count"},
		{"eOT.InitialStatus.Label"," Initial Status"},
		{"eOT.InitialStatusRemarks.Label"," Initial Status Remarks "},
		{"eOT.InitialStatusCompleted.Label"," Initial Status Completed?"},
		{"eOT.InitiateIPBooking.Label"," Initiate IP Booking"},
		{"eOT.InstructionTextInLocal.Label"," Instruction Text in Local"},
		{"eOT.InstructionText.Label"," Instruction Text"},
		{"eOT.InstrumentCode.Label"," Instrument Code"},
		{"eOT.InstrumentCount.Label"," Instrument Count"},
		{"eOT.InstrumentsCSSDPacks.Label"," Instruments/CSSD Packs"},
		{"eOT.IntialCount.Label"," Initial Count"},
		{"eOT.IntraAnaesthesia.Label"," Intra Anesthesia"},
		{"eOT.IntraAnaesthesiaDetails.Label"," Intra Anesthesia Details"},
		{"eOT.IntraAnaesthesiaDoc.Label"," Intra Anesthesia Doc"},
		{"eOT.IntraAnaesthesiaChartID.Label"," Intra-Anesthesia Chart ID"},
		{"eOT.IntraAnaesthesiaCompleted.Label"," Intra-Anesthesia Completed"},
		{"eOT.IntraAnaesthesiaNotes.Label"," Intra Anesthesia Notes"},
		{"eOT.IntraAnaesthesiaNoteType.Label"," Intra-Anesthesia Note Type"},
		{"eOT.IntraOperativeDetailsRecord.Label"," Intra Operative Details Record"},
		{"eOT.Intubated.Label"," Intubated"},
		{"eOT.InventoryDocumentType.Label"," Inventory Document Type"},
		{"eOT.IPOperNextNumber.Label"," IP Oper Next Number"},
		{"eOT.IPOperMaxNumber.Label"," IP Oper Max Number"},
		{"eOT.LeftSide.Label"," Left Side"},
		{"eOT.LightBlue.Label"," Light Blue"},
		{"eOT.LightGreen.Label"," Light Green"},
		{"eOT.LinkedStatus.Label"," Linked Status"},
		{"eOT.LinkPreOperativeOrders.Label"," Link Pre-Operative Orders"},
		{"eOT.LinkToCurrentEpisode.Label"," Link To Current Episode"},
		{"eOT.ListOption.Label"," List Option"},
		{"eOT.Magenta.Label"," Magenta"},
		{"eOT.MarkforReschedule.Label"," Mark for Reschedule"},
		{"eOT.MissingItemFound.Label"," Missing Item Found"},
		{"eOT.Mortuary.Label"," Mortuary"},
		{"eOT.MultiSpeciality.Label"," Multi Specialty"},
		{"eOT.NatureCode.Label"," Nature Code"},
		{"eOT.NatureType.Label"," Nature Type"},
		{"eOT.NextNo.Label"," Next No."},
		{"eOT.NonFinalisedBookings.Label"," Non Finalized Bookings"},
		{"eOT.NoOfDaysWaitlisted.Label"," No Of Days Waitlisted"},
		{"eOT.NoOfPersons.Label"," No Of Persons"},
		{"eOT.NoofSwabCountsReqdMandatory.Label"," No. of Swab Counts reqd (Mandatory)"},
		{"eOT.NoofTimesRescheduled.Label"," No. of Times Rescheduled"},
		{"eOT.NoofUnits.Label"," No of Units"}, // New
		{"eOT.NoOfUnitsPersons.Label"," No Of Units/Persons"},
		{"eOT.NoOfVerifications.Label"," No. Of Verifications"},
		{"eOT.NotAdmitted.Label"," Not Admitted"},
		{"eOT.NoteTypesForSpecialities.Label"," Note Types for Specialties"},
		{"eOT.NoticeDate.Label"," Notice Date"},
		{"eOT.NotifyAtPreAnaesthesia.Label"," Notify At Pre-Anesthesia"},
		{"eOT.NursingDoc.Label"," Nursing Doc"},
		{"eOT.NursingDocCmplTime.Label"," Nursing Documentation Completed Time"},
		{"eOT.NursingNotes.Label"," Nursing Notes"},
		{"eOT.OrderRef.Label"," Order Ref"},
		{"eOT.OPOperNextNumber.Label","OP Oper Next Number"},
		{"eOT.OPOperMaxNumber.Label","OP Oper Max Number"},
		{"eOT.OpenQty.Label"," Open Qty"},
		{"eOT.OperationRoom.Label"," Operation Room"},
		{"eOT.Operations.Label"," Operations"},
		{"eOT.OperatingSpeciality.Label"," Operating Specialty"},
		{"eOT.OperCannotbeperfin.Label"," Operation cannot be performed in"},
		{"eOT.OperationCategory.Label"," Operation Category"},
		{"eOT.OperationCode.Label"," Operation Code"},
		{"eOT.OperationCodeScheme.Label"," Operation Code Scheme"},
		{"eOT.OperationDate.Label"," Operation Date"},
		{"eOT.OperationDescription.Label"," Operation Description"},
		{"eOT.OperationDetails.Label"," Operation Details"},
		{"eOT.OperationNo.Label"," Operation No"},
		{"eOT.OperationNumberingIPDC.Label"," Operation Numbering IP/DC"},
		{"eOT.OperationNumberingOPEM.Label"," Operation Numbering OP/EM"},
		{"eOT.OperationsProcedures.Label"," Operations/Procedures"},
		{"eOT.OperationProcedure.Label"," Operation/Procedure"},
		{"eOT.OperationStatus.Label"," Operation Status"},
		{"eOT.OperationSubCategory.Label"," Operation Sub Category"},
		{"eOT.OperationTimings.Label"," Operation Timings"},
		{"eOT.OperationType.Label"," Operation Type"},
		{"eOT.OperationTypeForRanges.Label"," Operation type for Ranges"},
		{"eOT.OperativeRecords.Label"," Operative Records"},
		{"eOT.OperativeRecordsNoteType.Label"," Operative Records Note Type"},
		{"eOT.Orange.Label"," Orange"},
		{"eOT.OrderTypeForSepcialities.Label"," Order Type for Specialties"},
		{"eOT.OrganDisposal.Label"," Organ Disposal"},
		{"eOT.OtherActions.Label"," Other Actions"},
		{"eOT.OverBookingAllowedYN.Label"," Over Booking Allowed Y/N"},
		{"eOT.OverrideSpecialtyRestriction.Label"," Override Specialty Restriction"},
		{"eOT.OTNotificationWithinADay.Label"," OT Notification (Within A Day)"},
		{"eOT.OTStatusDescriptions.Label"," OT Status Descriptions "},
		{"eOT.OtherPayableAmount.Label"," Other Payable Amount (Baht)"},//Added by lakshmi for CRF-0601
		{"eOT.PACReviewOrderable.Label"," PAC Review Orderable"},
		{"eOT.PacksInstrsEquipsImplants.Label"," Consumables Packs/Instruments/Equipments/Implants"},
		{"eOT.PatientConsentDetails.Label"," Patient Consent Details"},
		{"eOT.PatientDemographics.Label"," Patient Demographics"},
		{"eOT.PatientSurgeryHistory.Label"," Patient Surgery History"},
		{"eOT.Personnel.Label"," Personnel"},
		{"eOT.PersonnelDetails.Label"," Personnel Details"},
		{"eOT.PersonnelInvolved.Label"," Personnel Involved"},
		{"eOT.PersonnelRequired.Label"," Personnel Required"},
		{"eOT.Pink.Label"," Pink"},
		{"eOT.PostAnaesthesia.Label"," Post Anesthesia"},
		{"eOT.PostAnaesthesiaDetails.Label"," Post Anesthesia Details"},
		{"eOT.PostAnaesthesiaChartID.Label"," Post-Anesthesia Chart ID"},
		{"eOT.PostAnaesthesiaCompleted.Label"," Post Anesthesia Completed"},
		{"eOT.PostAnaesthesiaNotes.Label"," Post Anesthesia Notes"},
		{"eOT.PostAnaesthesiaNoteType.Label"," Post-Anesthesia Note Type"},
		{"eOT.PostOperativeCheckList.Label"," Post Operative CheckList"},
		{"eOT.PostOperativeDetailsRecord.Label"," Post Operative Details Record"},
		{"eOT.PostOperativeDiagnosis.Label"," Post Operative Diagnosis"},
		{"eOT.PostOperativeNoOfVerifications.Label"," Post Operative No Of Verifications"},
		{"eOT.PostStageDescription.Label"," Post Stage Description"},
		{"eOT.PractitionerTypesForRoleTypes.Label","Practitioner Types for Role Types"},			
		{"eOT.PreAnaesthesiaCompleted.Label"," Pre Anesthesia Completed"},
		{"eOT.PreAnaesthesiaDetails.Label"," Pre Anesthesia Details"},
		{"eOT.PreAnaesthesiaEval.Label"," Pre-Anesthesia Evaluation"},
		{"eOT.PreAnaesthesiaEvalStage.Label"," Pre-Anesthesia Evaluation Stage"},
		{"eOT.PreAnaesthesiaForm.Label"," Pre Anesthesia Form"},
		{"eOT.PreAnaesthesiaNotes.Label"," Pre Anesthesia Notes"},
		{"eOT.PreAnaesthesiaNoteType.Label"," Pre-Anesthesia Note Type"},
		{"eOT.PreAnaesthesiaStage.Label"," Pre-Anesthesia Stage"},
		{"eOT.PreferredSurgeryDate.Label"," Preferred Surgery Date"},
		{"eOT.PrefixDateOperationNumber.Label"," Prefix Date-Operation Number"},
		{"eOT.PreMorbidCode.Label"," Pre Morbid Code"},
		{"eOT.PremorbidDetails.Label"," Pre-morbid Details"},
		{"eOT.PreMorbidStatus.Label"," Pre-Morbid Status"},
		{"eOT.PreOperativeAssessmentNum.Label"," Pre-Operative Assessment Numbering"},
		{"eOT.PreOperativeCheckList.Label"," Pre Operative CheckList"},
		{"eOT.PreOperativeDetailsRecord.Label"," Pre Operative Details Record"},
		{"eOT.PreOperativeDiagnosisNew.Label"," Pre-Operative Diagnosis"},//Added By MuthuN against CRF-011
		{"eOT.PreOperativeDiagnosis.Label"," Pre-operative clinical comments"},
		{"eOT.PreOperativeComments.Label"," Pre-operative comments"},
		{"eOT.PreOperativeIndicator.Label"," Pre Operative Indicator"},
		{"eOT.PreOperativeNoOfVerifications.Label"," Pre Operative No Of Verifications"},
		{"eOT.PreparationTime.Label"," Preparation Time"},
		{"eOT.PrepTimeinMins.Label"," Preparation Time (in Mins)"},
		{"eOT.PreStageDescription.Label"," Pre Stage Description"},
		{"eOT.PreviousRemarks.Label"," Previous Remarks"},
		{"eOT.PreviousReschedule.Label"," Previous Reschedule"},
		{"eOT.PrintBookingSlipOnConfirmation.Label"," Print Booking Slip On Confirmation"},
		{"eOT.PrintOption.Label"," Print Option"},
		{"eOT.ProcedureCoding.Label"," Procedure Coding"},
		{"eOT.Procedure(s).Label"," Procedure(s)"},
		{"eOT.ProcedureEndTime.Label"," Procedure End Time"},
		{"eOT.ProcedureRemarksData.Label"," Procedure Remarks Data"},
		{"eOT.ProcedureStartTime.Label"," Procedure Start Time"},
		{"eOT.Prosthesis.Label"," Prosthesis"},
		{"eOT.ProsthesisCategory.Label"," Prosthesis Category"},
		{"eOT.ProsthesisCode.Label"," Prosthesis Code"},
		{"eOT.ProsthesisImplantsCategories.Label"," Prosthesis/Implants Categories"},
		{"eOT.ProsthesisImplants.Label"," Prosthesis/Implants"},
		{"eOT.ProsthesisImplantsDetails.Label"," Prosthesis/Implants Details"},
		{"eOT.ProsthesisImplantsTypes.Label"," Prosthesis/Implants Types"},			
		{"eOT.ProsthesisType.Label"," Prosthesis Type"},
		{"eOT.Purple.Label"," Purple"},
		{"eOT.PayableAmount.Label"," Payable Amount (Baht)"},//Added by lakshmi for CRF-0601
		{"eOT.ProsthesisImplantsUsedForTreatment.Label"," Prosthesis/Implants Used for Treatment"},//Added by lakshmi for CRF-0601
		{"eOT.PrintReports.Label"," Print Reports"},//Added by lakshmi for CRF-0601
		{"eOT.RearrangeSequence.Label"," Rearrange Sequence"},
		{"eOT.ReassignTheatre.Label"," Reassign Theatre"},
		{"eOT.RecordChart.Label"," Record Chart"},
		{"eOT.RecordIntraAnaesthesiaDetails.Label"," Record Intra Anesthesia Details"},
		{"eOT.RecordNursingNotes.Label"," Record Nursing Notes"},
		{"eOT.RecordPostAnaesthesiaDetails.Label"," Record Post Anesthesia Details"},
		{"eOT.RecordSurgeonNotes.Label"," Record Surgeon Notes"},
		{"eOT.RecordVitals.Label"," Record Vitals"},
		{"eOT.RecoveryDetails.Label"," Recovery Details"},
		{"eOT.RecoveryCheckInTime.Label"," Recovery Check-In Time"},
		{"eOT.RecoveryEndDate.Label"," Recovery End Date"},
		{"eOT.RecoveryEndTime.Label"," Recovery End Time"},
		{"eOT.RecoveryEndTransferDate.Label"," Recovery End Transfer Date"},
		{"eOT.RecoveryNotes.Label"," Recovery Notes"},
		{"eOT.RecoveryParticulars.Label"," Recovery Particulars"},
		{"eOT.RecoveryStartDate.Label"," Recovery Start Date"},
		{"eOT.RecoveryStartTime.Label"," Recovery Start Time"},
		{"eOT.ReEvaluation.Label"," Re-Evaluation"},
		{"eOT.Registeredforoperation.Label"," Registered for operation"},
		{"eOT.ReleaseTheatreSlots.Label"," Release Theatre Slots"},
		{"eOT.ReportEmailReminderLetter.Label"," Report/Email Reminder Letter"},
		{"eOT.ReportinExcelFormat.Label"," Report in Excel Format"},
		{"eOT.Reqd.Label"," Reqd"},
		{"eOT.Resequencing.Label"," Resequencing"}, // new
		{"eOT.ResequencingDate.Label"," Resequencing Date"}, // new
		{"eOT.ReScheduled.Label"," ReScheduled"},			
		{"eOT.ReScheduleCases.Label"," Reschedule cases"},//047067 Bharati
		{"eOT.RescheduleCount.Label"," Reschedule Count"},
		{"eOT.RescheduleForm.Label"," Reschedule Form"},
		{"eOT.RescheduledBy.Label"," Rescheduled By"},
		{"eOT.RestrictBySpecialityYN.Label"," Restrict By Specialty Y/N"},
		{"eOT.RestrictTheatreBooking.Label"," Restrict Theatre Booking"},			
		{"eOT.Reversal.Label"," Reversal"},
		{"eOT.RightSide.Label"," Right Side"},
		{"eOT.RoleDescription.Label"," Role Description"},
		{"eOT.RoleID.Label"," Role ID"},
		{"eOT.RoleTypeDescription.Label"," Role Type Description"},
		{"eOT.RoomWiseTotal.Label","Room Wise Total"},
		{"eOT.ScanPatient.Label"," Scan Patient"},
		{"eOT.ScheduledCases.Label"," Scheduled Cases"},
		{"eOT.ScheduleStatus.Label"," Schedule Status"},
		{"eOT.ScheduleType.Label"," Schedule Type"},
		{"eOT.SecondCount.Label"," Second Count"},
		{"eOT.SecondCountCompleted.Label"," Second Count Completed?"},
		{"eOT.SecondWeek.Label"," Second Week"},
		{"eOT.Section1.Label"," Section 1"},
		{"eOT.Section2.Label"," Section 2"},
		{"eOT.Section3.Label"," Section 3"},
		{"eOT.Section1NoticeFromTime.Label"," Section 1 Notice From Time "},
		{"eOT.Section1NoticeToTime.Label"," Section 1 Notice To Time "},
		{"eOT.Section2NoticeFromTime.Label"," Section 2 Notice From Time "},
		{"eOT.Section2NoticeToTime.Label"," Section 2 Notice To Time "},
		{"eOT.Section3NoticeFromTime.Label"," Section 3 Notice From Time "},
		{"eOT.Section3NoticeToTime.Label"," Section 3 Notice To Time "},
		{"eOT.SelectDeselectAll.Label"," Select/Deselect All"}, // New
		{"eOT.SelectNoteType.Label"," Select Note Type"},
		{"eOT.Sequence.Label"," Sequence"},
		{"eOT.SetComponents.Label"," Set Components"},
		{"eOT.SetUpOperTimeRangesForRept.Label"," Set Up Operation Time  Ranges For Reporting"},
		{"eOT.SetupParameter.Label"," Setup Parameter"},
		{"eOT.SetupParametersForFacility.Label"," Setup Parameters for Facility"},
		{"eOT.ShowLastAntibioticAdminTime.Label"," Show Last Antibiotic Admin Time"},			
		{"eOT.SideApplicable.Label"," Side Applicable"},
		{"eOT.SignatureAndSeal.Label"," Signature & Seal"},
		{"eOT.Slate.Label"," Slate"},
		{"eOT.SlotTime.Label"," Slot time"},
		{"eOT.SourceId.Label"," Source Id"},
		{"eOT.SpecificIndicator.Label"," Specific Indicator"},
		{"eOT.SpecificOperationCategoryWithinSpeciality.Label"," Specific Operation Category (within the specialty)"},
		{"eOT.SpecificOperationSubCategoryWithinSpeciality.Label"," Specific Operation Sub-Category (within the specialty)"},
		{"eOT.SpecificUsers.Label"," Specific Users"},
		{"eOT.SpecificWeeks.Label"," Specific Weeks"},
		{"eOT.SpecimenNoDtl.Label"," Specimen No/Dtl"},
		{"eOT.Stages.Label"," Stages"},
		{"eOT.StandardDuration.Label"," Standard Duration"},
		{"eOT.StandardInstructions.Label"," Standard Instructions"},
		{"eOT.StandInstrnsinLocalLang.Label"," Standard Instructions in Local Language"},
		{"eOT.StatusCode.Label"," Status Code"},
		{"eOT.StatusDescription.Label"," Status Description"},
		{"eOT.StatusDetails.Label"," Status Details"},
		{"eOT.StdQty.Label"," Std Qty"},
		{"eOT.SubCategory.Label"," Sub Category"},
		{"eOT.SupplementaryItem.Label"," Supplementary Item"},
		{"eOT.SurgDocCmplTime.Label"," Surgeon Documentation Completed Time"},
		{"eOT.SurgeonAvgTime.Label"," Surgeon Avg. Time"},
		{"eOT.SurgeonsDiarySchedule.Label"," Surgeon Diary - Generate Schedule"},
		{"eOT.SurgeonsDiaryMaintainSchedule.Label"," Surgeon Diary - Maintain Schedule"},
		{"eOT.SurgeonDoc.Label"," Surgeon Doc"},
		{"eOT.SurgeonNotes.Label"," Surgeon Notes"},
		{"eOT.SurgeonPreferences.Label"," Surgeon Preferences"},
		{"eOT.SurgeryBookings.Label"," Surgery Bookings"},
		{"eOT.SurgeryDate.Label"," Surgery Date"},
		{"eOT.SurgeryDateFrom.Label"," Surgery Date From"},//AAKH CRF-0069
		{"eOT.SurgeryDateTo.Label"," Surgery Date To"},//AAKH CRF-0069
		{"eOT.SurgeryHistory.Label"," Surgery History"},
		{"eOT.SurgeryStartTime.Label"," Surgery Start Time"},
		{"eOT.SurgicalAccessories.Label"," Surgical Accessories"},
		{"eOT.SwabandInstrumentCount.Label"," Swab and Instrument Count"},
		{"eOT.SwabCount.Label"," Swab Count"},
		{"eOT.SwabSerialNumbers.Label"," Swab Serial Number(s)"},
		{"eOT.SystemDefinedDescription.Label"," System Defined Description"},
		{"eOT.SummaryOfMedicalTreatmentInOT.Label"," Summary of Medical Treatment in OT"},//Added by lakshmi for CRF-0601
		{"eOT.TemplateItems.Label"," Template Items"},
		{"eOT.TextColor.Label"," Text Color"},
		{"eOT.TheatretypeTheatre.Label"," Theatre type/Theatre"},
		{"eOT.TheatreDate.Label"," Theatre Date"},
		{"eOT.Theatrefrom.Label"," Theatre from"},
		{"eOT.TheatreSequenceNo.Label"," Theatre Sequence No."},
		{"eOT.TheatreType.Label"," Theatre Type"},
		{"eOT.TheatreValue.Label"," Theatre Value"}, // New
		{"eOT.ThirdWeek.Label"," Third Week"},
		{"eOT.TimeandDetails.Label"," Time and Details"},
		{"eOT.TimeRange.Label"," Time Range"},
		{"eOT.TimeRangeCode.Label"," Time Range Code"},
		{"eOT.TimeSlot.Label"," Time Slot"},
		{"eOT.TimeSlots.Label"," Time Slots"},
		{"eOT.ToAdmissionDate.Label"," To Admission Date"},
		{"eOT.ToAnaesthesiaCode.Label"," To Anesthesia Code"},
		{"eOT.ToAnaesthetist.Label"," To Anesthetist"},
		{"eOT.ToBeRescheduleCases.Label"," To Be Reschedule Cases"},
		{"eOT.ToBookingDate.Label"," To Booking Date"},
		{"eOT.ToDiagnosis.Label"," To Diagnosis"},
		{"eOT.ToImplantType.Label"," To Implant Type"},
		{"eOT.ToOperationDate.Label"," To Operation Date"},
		{"eOT.ToOperationNo..Label"," To Operation No."},
		{"eOT.ToOperationRoom.Label"," To Operation Room"},
		{"eOT.ToOperationType.Label"," To Operation Type"},
		{"eOT.ToPosition.Label"," To Position"},
		{"eOT.ToProcedure.Label"," To Procedure"},
		{"eOT.ToProcedureDate.Label"," To Procedure Date"},
		{"eOT.ToRegistrationDate.Label"," To Registration Date"},
		{"eOT.ToSpeciality.Label"," To Specialty"},
		{"eOT.ToSurgeon.Label"," To Surgeon"},
		{"eOT.ToSurgeryDate.Label"," To Surgery Date"},
		{"eOT.TotalDuration.Label"," Total Duration"},
		{"eOT.TotalNoOfPatientsWaitlisted.Label"," Total NO Of Patients Waitlisted"},
		{"eOT.TotalNoOfPatientsWaitlistedSpecialitywise.Label"," Total NO Of Patients Waitlisted (Specialty wise)"},
		{"eOT.TotalNoOfPatientsWaitlistedSurgeonwise.Label"," Total NO Of Patients Waitlisted (Surgeon wise)"},			
		{"eOT.TotalSurgeonwiseBookings.Label"," Total Surgeon wise Bookings"},			
		{"eOT.TotalTheatrewiseBookings.Label"," Total Theatre wise Bookings"},			
		{"eOT.ToTheatre.Label"," To Theatre"},
		{"eOT.ToWard.Label"," To Ward"},
		{"eOT.TransferDetails.Label"," Transfer Details"},
		{"eOT.TransferSelectedPatients.Label"," Transfer Selected Patients"},
		{"eOT.TransferTime.Label"," Transfer Time"},
		{"eOT.TransfertoOTfromRecoveryRoom.Label"," Transfer to OT from Recovery Room"},
		{"eOT.UnitTimeforBooking.Label"," Unit Time for Booking (hh24:mi)"},
		{"eOT.UnSchedule.Label"," UnSchedule"},
		{"eOT.UnScheduledCases.Label"," UnScheduled Cases"},
		{"eOT.UntowardEvent.Label"," Untoward Event"},
		{"eOT.UntowardEvents.Label"," Untoward Events"},
		{"eOT.UnusualOccurenceCode.Label"," Unusual Occurrence Code"},
		{"eOT.UnusualOccurrence.Label"," Unusual Occurrence"},
		{"eOT.UnusualOccurrence.label"," Unusual Occurrence"},
		{"eOT.UserRole.Label"," User Role"},
		{"eOT.VerificationAllowed.Label"," Verification Allowed"},
		{"eOT.VerificationApplicable.Label"," Verification Applicable"},
		{"eOT.VerifyCheckList.Label"," Verify CheckList"},
		{"eOT.VerifyCheckOutChecklist.Label"," Verify Check-Out CheckList"},
		{"eOT.VerifySwabCount.Label"," Verify Swab Count"},
		{"eOT.ViewBookingDetails.Label"," View Booking Details"},
		{"eOT.ViewCheckList.Label"," View CheckList"},
		{"eOT.ViewPreAnaesthesiaEvaluationDetails.Label"," View Pre-Anesthesia Evaluation Details"},
		{"eOT.ViewRemarks.Label"," View Remarks for "},
		{"eOT.VisitingPersonnel.Label"," Visiting Personnel"},
		{"eOT.Violet.Label"," Violet"},
		{"eOT.WaitingTimeBy.Label"," Waiting Time By"},
		{"eOT.WaitlistCases.Label"," Waitlist Cases"},
		{"eOT.WaitlistDate.Label"," Waitlist Date"},
		{"eOT.WaitlistDays.Label"," Waitlist Days"},
		{"eOT.WaitListDetails.Label"," WaitList Details "},
		{"eOT.WaitListNextNumber.Label"," WaitList Next Number "},
		{"eOT.WaitListMaxNumber.Label"," WaitList Max Number "},
		{"eOT.WaitListNO.Label"," WaitList NO"},
		{"eOT.WaitListNumbering.Label"," WaitList Numbering"},
		{"eOT.WaitlistSelectedPatients.Label"," Waitlist Selected Patients"},
		{"eOT.WaitlistWarning.Label"," Waitlist Warning "},
		{"eOT.WaitlistWarningLimitDays.Label"," Waitlist Warning Limit Days"},
		{"eOT.WaitListWindow.Label"," WaitList Window"},
		{"eOT.WardCheckoutTime.Label"," Ward Checkout Time"},
		{"eOT.WarnForUnscheduledCasesOnly.Label"," Warn For Unscheduled Cases"},
		{"eOT.White.Label"," White"},
		{"eOT.WorkingDay.Label"," Working Day"},
		{"eOT.WorkingDayEndTime.Label"," Working Day End Time"},
		{"eOT.WorkingDayStartTime.Label"," Working Day Start Time"},
		{"eOT.WoundDetails.Label"," Wound Details"},
		{"eOT.WoundType.Label"," Wound Type"},
		{"eOT.WoundTypeCode.Label"," Wound Type Code"},
		{"eOT.X-rayPerformed.Label"," X-ray Performed"},
		{"eOT.SwabCountTemplate.Label"," Swab Count Template"},
		{"eOT.TimeCalled.Label"," Time Called"},
		{"eOT.NameOfOTStaff.Label","Name Of OT Staff"},
		{"eOT.NameOfPorter.Label","Name Of Porter"},
		{"eOT.TimePorterLeavesOT.Label","Time Porter Leaves OT"},
		{"eOT.ApplicableToOTSlate.Label"," Applicable To OT-Slate "},
		{"eOT.AvgTime.Label"," Avg. Time "},			
		{"eOT.BookingSequenceNo.Label"," Booking Sequence NO "},
		{"eOT.DateReceived.Label"," Date Received "},
		{"eOT.DateSent.Label"," Date Sent "},
		{"eOT.DepartmentwiseTotalNoOfPatients.Label"," Department wise Total NO of Patients "},
		{"eOT.DisposedTo.Label"," Disposed To "},
		{"eOT.EndOfReport.Label"," End Of Report "},
		{"eOT.FinalizedBy.Label"," Finalized By "},
		{"eOT.FromCode.Label"," From Code "},
		{"eOT.HrsMins.Label"," (Hrs:Mins) "},
		{"eOT.ListCheckedBy.Label"," List Checked By"},
		{"eOT.MaxTime.Label"," Max. Time "},
		{"eOT.MinTime.Label"," Min. Time "},
		{"eOT.MonthwiseTotal.Label"," MonthWise Total "},
		{"eOT.MthYr.Label"," Mth/Yr "},
		{"eOT.NameOfBodyPart.Label"," Name Of Body Part "},
		{"eOT.NameofMedicalOfficerI/C.Label"," Name Of Medical Officer I/C "},
		{"eOT.NameOfOrNurse.Label"," Name Of OR Nurse "},
		{"eOT.NameOfTest.Label"," Name Of Test "},
		{"eOT.NatureOfSurgery.Label"," Nature Of Surgery "},
		{"eOT.NonSpecimenOrForeignBody.Label"," Non-Specimen or Foreign Body "},
		{"eOT.NoOfCasesPerformed.Label"," No Of Cases Performed "},
		{"eOT.NoOfOperatingRoomsForThisFacility.Label"," No Of Operating Rooms For This Facility "},
		{"eOT.NoOfOperations.Label"," No Of Operations "},
		{"eOT.OperatingFacility.Label"," Operating Facility "},
		{"eOT.OperationsPerformed.Label"," Operations Performed "},
		{"eOT.PlannedOperation.Label"," Planned Operation "},
		{"eOT.PatientInformationFileID.Label"," Patient Information File ID "},
		{"eOT.PersonDespatchingSpecimen.Label"," Person Despatching Specimen "},
		{"eOT.Persons.Label"," Persons "},
		{"eOT.RecordingNurse.Label"," Recording Nurse "},
		{"eOT.SSGroup.Label"," SS Group "},
		{"eOT.SurgicalDepartment.Label"," Surgical Department "},
		{"eOT.SwabandInstrumentTemplate.Label"," Swab and Instrument Count Template "},
		{"eOT.TimeReceived.Label"," Time Received"},
		{"eOT.TimeSent.Label"," Time Sent"},
		{"eOT.TotalNoOfBookingFinalisationStageCodes.Label"," Total NO Of Booking Finalization Stage Codes "},
		{"eOT.TotalNoOfBookingPriorityCodes.Label"," Total NO Of Booking Priority Codes "},
		{"eOT.TotalNoOfChecklistCodes.Label"," Total NO Of Checklist Codes "},
		{"eOT.TotalNoOfConsumablePacks.Label"," Total NO Of Consumable Packs "},
		{"eOT.TotalNoOfEquipments.Label"," Total NO Of Equipments "},
		{"eOT.TotalNoOfFunctionIDs.Label"," Total NO Of Function IDs "},
		{"eOT.TotalNoOfHoldingAreaCodes.Label"," Total NO Of Holding Area Codes "},
		{"eOT.TotalNoOfInstruments.Label"," Total NO Of Instruments "},
		{"eOT.TotalNoOfOperations.Label"," Total NO Of Operations "},
		{"eOT.TotalNoOfOperationTypes.Label"," Total NO Of Operation Types "},
		{"eOT.TotalNoOfOrganDisposal.Label"," Total NO Of Organ Disposal "},
		{"eOT.TotalNoOfPositions.Label"," Total NO Of Positions "},
		{"eOT.TotalNoOfProthesisCategory.Label"," Total NO Of Prosthesis Category "},
		{"eOT.TotalNoOfProthesisImplants.Label"," Total No Of Prosthesis / Implants "},
		{"eOT.TotalNoOfProthesisType.Label"," Total NO Of Prosthesis Types "},
		{"eOT.TotalNoOfReasons.Label"," Total NO Of Reasons "},
		{"eOT.TotalNoOfRecordsForChecklistItems.Label"," Total NO Of Records For Checklist Items "},
		{"eOT.TotalNoOfRoles.Label"," Total NO Of Roles "},
		{"eOT.TotalNoOfRoleTypes.Label"," Total NO Of Role Types "},
		{"eOT.TotalNoOfSpecialities.Label"," Total NO Of Specialties "},
		{"eOT.TotalNoOfStatus.Label"," Total NO Of Statuses "},
		{"eOT.TotalNoOfSurgeryTypes.Label"," Total NO Of Surgery Types "},
		{"eOT.TotalNoOfSwabTemplate.Label"," Total NO Of Swab Count Templates "},
		{"eOT.TotalNoOfSwabTemplateItems.Label"," Total NO Of Swab Count Template Items "},
		{"eOT.TotalNoOfUsers.Label"," Total NO Of Users "},
		{"eOT.TotalNoOfUsualOccurences.Label"," Total NO Of Usual Occurrences "},
		{"eOT.TotalNoOfOperWithoutPostOperDtls.Label"," Total NO Of Operations Without Post Operations Details "},
		{"eOT.TotalNoOfWoundTypes.Label"," Total NO Of Wound Types "},
		{"eOT.WaitingTimeInDays.Label"," Waiting Time In Days "},
		{"eOT.WoundText.Label","Wound Text"},
		{"eOT.OrderDateVsApptDate.Label","Order Date Vs Appt Date"},
		{"eOT.FirstScheduleDateVsReScheduledDate.Label","First Schedule Date Vs Re-Scheduled Date"},
		{"eOT.TotalNoOfOperationsForTheAnaesthetist.Label","Total No of Operations for the Anesthetist"},
		{"eOT.TotalNoOfOperationsForTheSurgeon.Label","Total NO of Operations for the Surgeon"},
		{"eOT.SpecialitywiseTotal.Label","Specialty wise Total"},
		{"eOT.DatewiseTotal.Label","Date wise Total"},
		{"eOT.OperationTypewiseTotal.Label","Operation Type wise Total"},
		{"eOT.OperationDurationwiseTotal.Label","Operation duration wise Total"},
		{"eOT.SurgeonwiseTotal.Label","Surgeon wise Total"},
		{"eOT.TotalNoOfOperationsForTheDate.Label","Total NO of Operations for the Date"},
		{"eOT.TimeDetails.Label","Time Details"},
		{"eOT.BillingSubServices.Label","Billing Sub Services"},
		{"eOT.Payable.label","Payable"},
		{"eOT.Payable.Label","Payable"},
		{"eOT.ReportPeriodicity.Label","Report Periodicity"},
		{"eOT.Quarterly.Label","Quarterly"},
		{"eOT.Annually.Label","Annually"},
		{"eOT.BiAnnually.Label","Bi Annually"},
		{"eOT.FirstHalf.Label","First Half"},
		{"eOT.SecondHalf.Label","Second Half"},
		{"eOT.Quarter1.Label","Quarter1"},
		{"eOT.Quarter2.Label","Quarter2"},
		{"eOT.Quarter3.Label","Quarter3"},
		{"eOT.Quarter4.Label","Quarter4"},
		{"eOT.PatientSignature.Label","Patient Signature"},
		{"eOT.PreOperatingDiagnosis.Label","Pre-Operating Diagnosis"},
		{"eOT.BookingNumber.Label","Booking Number"},
		{"eOT.BookingBy.Label","Booking By"},
		{"eOT.GenerateBy.Label"," Generate By"},
		{"eOT.TheatreAndSurgeon.Label"," Theatre and Surgeon"},
		{"eOT.SurgeryDepartment.Label","Surgery Department"},
		{"eOT.DiarySchduleForSurgeonReqd.Label","Create Diary Schedule By ?"},
		{"eOT.AssignSurgeon.Label"," Assign Surgeon"},
		{"eOT.AllowedForOverBooking.Label"," Fully Booked (Over Booking Allowed)"},
		{"eOT.WardCheckOutSearchCheckBox.Label","Consider Patient Current Nursing Unit for Search"},
		{"eOT.SlateLoginRequired.Label","Slate Login Required?"},
		{"eOT.Citizenid.Label","Citizen ID"},
		{"eOT.Orderresultstatus/additionalinformation-forpatientid.Label","Order Result Status / Additional Information - for Patient ID:"},
		{"eOT.Lastmealtime.Label","Last Meal Time"},
		{"eOT.Totalfor.Label","Total For"},
		{"eOT.CheckOutFromOR.Label","Check-Out From OR"},
		{"eOT.BookingCut-offTimeforElectiveCases.Label","Booking Cut-off Time for Elective Cases"},
		{"eOT.ReviewedBy.Label","Reviewed By"},
		{"eOT.OperationNumber.Label","Operation Number"},
		{"eOT.NationalID.Label","National ID"},
		{"eOT.PrePackSet.Label","Pre-Pack Set"},
		{"eOT.Supplementary.Label","Supplementary"},
		{"eOT.CountItems.Label","Count Items"},
		{"eOT.AdditionsDuringCC.Label","Additions During CC"},
		{"eOT.CompletionDetails.Label","Completion Details"},
		{"eOT.CountStage.Label","Count Stage"},
		{"eOT.CompletedBy.Label","Completed By"},
		{"eOT.CompleteDate/Time.Label","Complete date/Time"},
		{"eOT.ReviewedDate.Label","Reviewed Date"},
		{"eOT.BioHazard.Label","Bio Hazard"},
		{"eOT.DetailToIndicateCorrectFinalCheckOfOtherInstruments.Label","DETAIL TO INDICATE CORRECT FINAL CHECK OF OTHER INSTRUMENTS"},
		{"eOT.ForDiscrepenciesInCount.Label","FOR DISCREPENCIES IN COUNT :"},
		{"eOT.X-RayOrdered.Label","X-RAY ORDERED :"},
		{"eOT.Taken.Label","TAKEN :"},
		{"eOT.Result.Label","RESULT :"},
		{"eOT.ParticularsOfGauzeTubesandCathetersLeftInSitu.Label","PARTICULARS OF GAUZE, TUBES AND CATHETERS LEFT IN SITU :"},
		{"eOT.UnderWaterDrainage.Label","UNDER WATER DRAINAGE :"},
		{"eOT.PacingWire.Label","PACING WIRE :"},
		{"eOT.MonitoringLine.Label","MONITORING LINE :"},
		{"eOT.Specimens.Label","SPECIMENS :"},
		{"eOT.SurgeonInformedThatAboveCountsAreCorrect.Label","SURGEON INFORMED THAT ABOVE COUNTS ARE CORRECT :"},
		{"eOT.SurgeonsSignature.Label","SURGEON'S SIGNATURE"},
		{"eOT.ScrubNursesSignature.Label","SCRUB NURSE'S SIGNATURE"},
		{"eOT.Allanaesthesia.Label","All Anesthesia"},
		{"eOT.CirculatingNursesSignature.Label","CIRCULATING NURSE'S SIGNATURE"},
		{"eOT.operationss.Label","Operation(s)"},
		{"eOT.TotalNoOfOperationsForTheAnaesthesia.Label","Total No of Operations for the Anesthesia"},
		{"eOT.ReasonForReArrangeSequenceMandatory.Label","Reason For Re Arrange Sequence(Mandatory)?"},
		{"eOT.SubCategorywiseTotal.Label","Sub Categorywise Total"},
		{"eOT.CategorywiseTotal.Label","Categorywise Total"},
		{"eOT.BySurgeonsPrimarySpeciality.Label","By Surgeon's Primary Specialty"},
		{"eOT.FromRegistrationMonth.Label","From Registration Month"},
		{"eOT.ToRegistrationMonth.Label","To Registration Month"},
		{"eOT.CurrentMonth.Label","Currnet Month/year.."},
		{"eOT.ID.Label","ID"},
		{"eOT.BloodGrouping.Label","Blood Grouping"},
		{"eOT.AdminDate.Label","Admin Date"},
		{"eOT.NoticeDate.Label"," Notice Date"},
		{"eOT.OTRoom.Label","OT Room"},
		{"eOT.RecoveryRoom.Label","Recovery Room"},
		{"eOT.AverageOperatingTime.Label","Average Operating Time"},
		{"eOT.NotFinalized.Label","( Not Finalized )"},
		{"eOT.ViewAdditionalCharges.Label"," View Additional Charges"},
		{"eOT.Currentlocation/RoomNo/BedNo.Label","Current Location"},
		{"eOT.IncludeCasesforPast.Label","Include Cases for Past"},
		{"eOT.TheatrePeriod.Label"," Theatre Period"},	
		{"eOT.ElectiveEmergency.Label"," Elective/Emergency"},	
		{"eOT.DocumentationStatus.Label"," Documentation Status"},
		{"eOT.DateTimeSlot.Label"," Date/Time Slot"},
		{"eOT.ApptRefnum.Label"," Appt. Ref Num"},
		{"eOT.OperNum.Label"," Oper Num"},
		{"eOT.BillingSetup.Label"," Billing Setup"},
		{"eOT.OperationServices.Label"," Operation Services"},
		{"eOT.AdminFunctionforCharging.Label"," Admin Function for Charging"},
		{"eOT.RoomServiceUsage.Label"," Room Service Usage"},
		{"eOT.BillHoldingAreaUsage?.Label"," Bill Holding Area Usage?"},
		{"eOT.BillOperatingRoomUsage?.Label"," Bill Operating Room Usage?"},
		{"eOT.BillRecoveryRoomUsage?.Label"," Bill Recovery Room Usage?"},
		{"eOT.BillFinalizationStages.Label"," Bill Finalization Stages"},
		{"eOT.DuringChecking-OutIndividualRooms.Label"," During Checking-Out Individual Rooms"},
		{"eOT.BeforeCheck-out/DocumentationCompletition.Label"," Before Check-out/Documentation Completition"},
		{"eOT.AccessoryType.Label"," Accessory Type"},
		{"eOT.FinalizationStages.Label"," Finalization Stages"},
		{"eOT.Admin.Label"," Admin"},
		{"eOT.AdminFunction.Label"," Admin Function"},
		{"eOT.RoombedStatus.Label"," Room & Bed Status"},
		{"eOT.CancelledRemarks.Label"," Cancelled Remarks"},
		{"eOT.CheckedOutDateTime.Label"," Checked-Out Date/Time"},
		{"eOT.CurrentLoc.Label"," Current Loc."},
		{"eOT.RequestingStore.Label"," Requesting Store"},
		{"eOT.PackageandImplants.Label"," Package and Implants"},
		{"eOT.InstrumentsandEquipments.Label"," Instruments and Equipments"},
		{"eOT.PersonalDetails.Label"," Personal Details"},
		{"eOT.ChargableBay.Label"," Chargeable Bay?"},
		{"eOT.ChargableRoom.Label"," Chargeable Room?"},
		{"eOT.Chargable.Label"," Chargeable ?"},
		{"eOT.DefaultRecoveryRoom.Label"," Default Recovery Room?"},
		{"eOT.QOHofReqStore.Label"," QOH of Req Store"},
		{"eOT.ReserveQty.Label"," Reserve Qty"},
		{"eOT.RequestQty.Label"," Request Qty"},
		{"eOT.ChargableUnits.Label"," Chargeable Units"},
		{"eOT.IssuingStore.Label"," Issuing Store"},
		{"eOT.CheckinToORDateTime.Label"," Check-in to OR Date/Time"},
		{"eOT.CheckOutFromORDateTime.Label"," Check-Out from OR Date/Time"},
		{"eOT.TheatreRequestingConsumptionStore.Label"," Theatre Requesting/Consumption Store"},
		{"eOT.TheatreIssuingStore.Label"," Theatre Issuing Store"},
		{"eOT.DefaultStore.Label"," Default Store"},
		{"eOT.SurgicalAccesCompleted.Label"," Surgical Accessories Completed"},
		{"eOT.ConsumptionStore.Label"," Consumption Store"},
		{"eOT.StockAvailable.Label"," Stock Available"},
		{"eOT.ReservedPicklistUnits.Label"," Reserved Picklist Units"},
		{"eOT.RequestedPicklistUnits.Label"," Requested Picklist Units"},
		{"eOT.ActualUnits.Label"," Actual Units"},
		{"eOT.SaleDoctype.Label"," Sale Doc type"},
		{"eOT.RequestDocType.Label"," Request Doc Type"},
		{"eOT.CheckedOutDate.Label"," Checked Out Date"},
		{"eOT.CheckedOutTime.Label"," Checked Out Time"},
		{"eOT.ProsthesisImplantscompleted.Label"," Prosthesis Implants"},
		{"eOT.ConsumablePacksCompleted.Label"," Consumable Packs"},
		{"eOT.EquipmentsCompleted.Label"," Equipments"},
		{"eOT.InstrumentsCSSDPacksCompleted.Label"," Instruments/CSSD Packs"},
		{"eOT.Prothesis/ImplantsCompleted.Label"," Prosthesis/Implants Completed"},
		{"eOT.ConsumablesCompleted.Label"," Consumables Completed"},
		{"eOT.EquipmentsCompleted.Label"," Equipments Completed"},
		{"eOT.Instruments/CSSDCompleted.Label"," Instruments/CSSD Completed"},
		{"eOT.CompletionStatus.Label"," Completion Status"},
		{"eOT.HoldingAreaUsage.Label"," Holding Area Usage"},
		{"eOT.OperatingRoomUsage.Label"," Operating Room Usage"},
		{"eOT.RecoveryRoomUsage.Label"," Recovery Room Usage"},
		{"eOT.DirectConsumption.Label"," Direct Consumption"},
		{"eOT.AdditionalSurgeryCharges.Label"," Additional Surgery Charges"},
		{"eOT.ChangeHoldingArea.Label"," Change Holding Area"},
		{"eOT.ProcedureCodingScheme.Label"," Procedure Coding Scheme"},
		{"eOT.FromDiagnosis.Label"," From Diagnosis"},
		{"eOT.ToAnaesthesiaCode.Label"," To Anesthesia Code"},
		{"eOT.FromDiagnosis.Label"," From Diagnosis"},
		{"eOT.ToDiagnosis.Label"," To Diagnosis"},
		{"eOT.icd10.Label"," ICD-10"},
		{"eOT.Unscheduled.Label"," UnScheduled"},
		{"eOT.ViewConsumablesUsed.Label"," View Consumables Used"},
		{"eOT.CheckInBackdateLimit.Label"," Check-In Backdate Limit"},
		{"eOT.RecoveryStartdateTime.Label"," Recovery Start Date Time"},
		{"eOT.ApptScheduled.Label"," Appt. Scheduled"},
		{"eOT.ApprovalRequired.Label"," Approval reqd?"},
		{"eOT.Included.Label"," Included?"},
		{"eOT.Includeone.Label"," Included"},
		{"eOT.Include.Label"," Include?"},
		{"eOT.IncludeExclude.Label","Include/Exclude"},
		{"eOT.Exclude.Label","Exclude"},
		{"eOT.IncludeExcludecharges.Label","Include/Exclude charges"},
		{"eOT.SummaryofOperationbyNurse.Label","Summary of Operation by Nurse"},
		{"eOT.UnscheduledOperations.Label","Unscheduled Operations"},
		{"eOT.UnusualOccurrence.Label","Unusual Occurrence"},
		{"eOT.WaitingTimebyAdmit.Label","Waiting Time by Admit"},
		{"eOT.WaitingTimeinOR.Label","Waiting Time in OR"},
		{"eOT.interfacetooralhealth.Label"," Interface to Oral Health"},
		{"eOT.invokeDentalChart.Label"," Invoke Dental Chart"},
		{"eOT.OralHealthOTprocedure.Label"," Oral Health OT Procedure"},
		{"eOT.InvokeRestorativeChart.Label"," Invoke Restorative Chart"},
		{"eOT.WaitingTimeinMinutes.label"," Waiting Time in Minutes"},
		{"eOT.FromCheckinORDateTime.label"," From Check in OR Date/Time"},
		{"eOT.ToCheckinORDateTime.label"," To Check in OR Date/Time"},
		{"eOT.AllSurgeons.label"," All Surgeons"},
		{"eOT.AnaesthetistDocComTime.Label","Anaesthetist Documentation Completed Time"},
		{"eOT.CancelledReason.Label","Cancelled Reason"},
		{"eOT.DisplayonlyloggedinUserBookings.Label","Display only logged in User Bookings?"},
		{"eOT.Hrs.Label","Hrs."},
		{"eOT.BookingByRep.Label","Booking By"},
		{"eOT.PreOperatingDiagnosisRep.Label","Pre-Operating Diagnosis"},
		{"eOT.PatientInstructionsRep.Label","Patient Instructions"},
		{"eOT.SurgeonRep.Label","Surgeon"},
		{"eOT.YRep.Label","Y"},
		{"eOT.MRep.Label","M"},
		{"eOT.DRep.Label","D"},
		{"eOT.BookingNumberRep.Label","Booking Number"},
		{"eOT.Sourcerep.Label","Source"},
		{"eOT.BookingDaterep.Label","Booking Date"},
		{"eOT.BookingTimerep.Label","Booking Time"},
		{"eOT.DOBrep.Label","Date of Birth"},
		{"eOT.OperationDetailsrep.Label"," Operation"},
		{"eOT.SameBatchLegend.Label","Charge details included in above batch"},
		/*Added by lakshmi for crf-0601*/
		{"eOT.TotalPrice.Label","Total Price"},
		{"eOT.Reimbursable.Label","Reimbursable"},
		{"eOT.NonReimbursable.Label","Non Reimbursable"},
		{"eOT.PrevilegeByPriority.Label","Privilege by Priority"},
		{"eOT.CompleteDocumentDateTime.Label","Complete Document Date/Time"},
		{"eOT.CheckInOperatingRoomStartTime.Label","Check-in Operating Room Start Time"},
		{"eOT.ApcNo.Label","APC NO"},
		{"eOT.MappingCode.Label","Mapping Code"},
		//Added by Rajesh 5-9-2012	
		{"eOT.InstrCSSDImg.Label","Instrument/CSSD Path"},
		{"eOT.InstrCSSDImgLoc.Label","Instrument/CSSD Image Location"},		
		//Added by Rajesh 5-9-2012
		//Modified for displaying Boking report - Rajesh V 12/10/2012
		{"eOT.PrintAppointmentSlip.Label","Print Appointment Slip"},
		{"eOT.PreferredLanguage.Label","Preferred language"},
		//Modified for displaying Boking report - Rajesh V 12/10/2012
		//CRF-004 Authorize Slots for Booking - Rajesh V
		{"eOT.AuthorizeUsers.Label","Authorized Users"},
		{"eOT.AssignUser.Label","Assign User"},
		{"eOT.TotalSlots.Label","Total slots available"},
		{"eOT.PermissibleSlots.Label","Booking allowed for"},
		{"eOT.UserToOverride.Label","User to override booking restriction"},
		{"eOT.SelectUser.Label","Select User"},
		{"eOT.AuthorizeSlotBooking.Label","Authorize - Slot booking"},
		//CRF-004 Authorize Slots for Booking - Rajesh V
		//CRF-268 Setup Parameter - Rajesh V
		{"eOT.RestrictBookingYN.Label","Restrict Booking y/n"},
		{"eOT.CSSDInterface.Label","CSSD Interface"},
		{"eOT.ReqDocType.Label","Request Document type"},
		{"eOT.RetDocType.Label","Return Document Type"},
		{"eOT.ReqStore.Label","Request Store"},
		{"eOT.IssueStore.Label","Issue Store"},
		{"eOT.FromStatus.Label","Start OT status"},
		{"eOT.ToStatus.Label","End OT status"},
		//CRF-004 Setup Parameter - Rajesh V
		//added by Sanjay for Over Booking Cases against MO-CRF-0058 on 16-Oct-12
		{"eOT.TotalOverBookedCases.Label","Total No. of Over Booked Cases :"},
		{"eOT.ContinueBooking.Label","Do you want to continue with overbooking?"},
		{"eOT.OverBookedCases.Label","Booking List"}, 
		{"eOT.OverBookedCasesInTheRoom.Label","Booking List"},
		{"eOT.ScheduleTime.Label","Schedule Time:"},
		{"eOT.TotalProcTime.Label","Total Proc. Time"},
		{"eOT.OverBookingWindowRestriction.Label","Overbooking Window & Rights Restriction"},
		//Added by MuthuN against 31719 on 07-Nov-12
		{"eOT.OverBookingAvailability.Label","Overbooking availability :"},		
		/* Added by MuthuN against 29704 - Report CRF */
		{"eOT.TurnAroundTime.Label","Turn around time"},
		/* Added by MuthuN against 29704 - Report CRF */
		/* Added by MuthuN against BRU-CRF-268 */
		{"eOT.QuantityOnHands.Label","Quantity On Hand"},
		{"eOT.PickListStatus.Label","Pick List Generation Status"},
		{"eOT.AllocatedQuantity.Label","Allocated Quantity"},
		{"eOT.RequiredQuantity.Label","Required quantity"},
		//Added for CRF Bru - 298
		{"eOT.MultiFacility.Label","Enable Multi Facility OT Booking"},
		{"eOT.PerformingLocation.Label","Performing Location"},
		{"eOT.ExternalFacilityBooking.Label","Alternate Facility Selection"},
		{"eOT.Facility.Label","Facility"},
		{"eOT.ExternalFacility.Label","Alternate Facility"},

		/*eDSN related lable changes  */
		{"eOT.DietType.Label","Diet Type"},
		{"eOT.LongDescription.Label","Long Description"},
		{"eOT.ShortDescription.Label","Short Description"},
		{"eOT.AgeGroup.Label","Age Group"},
		{"eOT.DefaultDietType.Label","Default Diet Type"},
		{"eOT.DefaultFeedType.Label","Default Feed Type"},
		{"eOT.DietCycleType.Label","Diet Cycle Type"},
		{"eOT.OrderCatalogcode.Label","Order Catalog code"},
		{"eOT.DietCategory.Label","Diet Category"},
		{"eOT.Enabled.Label","Enabled"},
		{"eOT.select.Label","-----select-----"},
		{"eOT.MealClass.Label","Meal Class"},
		{"eOT.MealType.Label","Meal Type"},
		{"eOT.ItemType.Label","Item Type"},
		{"eOT.ItemQty.Label","Item Qty"},
		{"eOT.Item.Label","Item"},
		{"eOT.ItemSrl.Label","Item Srl"},
		{"eOT.ItemsForMenu.Label","Items For Menu"},
		{"eOT.Order.Label","Order"},
		{"eOT.CommercialFormula.Label","Commercial Formula"},
		{"eOT.ApplDietCategory.Label","Applicable Diet Category"},
		{"eOT.FeedType.Label","Feed Type"},
		{"eOT.InstructionCode.Label","Instruction Code"},
		{"eOT.Description.Label","Description"},
		{"eOT.ComplaintCode.Label","Complaint Code"},
		{"eOT.DietCategoryCode.Label","Diet Category Code"},
		{"eOT.OrderType.Label","Order Type"},
		{"eOT.Attendents.Label","Attendents"},
		{"eOT.MealCategory.Label","Meal Category"},
		{"eOT.NursingUnit.Label","Nursing Unit"},
		{"eOT.PatientOrder.Label","Patient Order"},
		{"eOT.NoOfAttendent.Label","No of Attendent"},
		{"eOT.NutrientCode.Label","Nutrient Code"},
		{"eOT.Uom.Label","UOM"},
		{"eOT.EnergyConversion.Label","Energy Conversion"},
		{"eOT.KiloCalories.Label","Kilo Calories"},
		{"eOT.IngredientCode.Label","Ingredient Code"},
		{"eOT.Ingredients.Label","Ingredients"},
		{"eOT.ItemCode.Label","Item Code"},
		{"eOT.StockUOM.Label","Stock UOM"},
		{"eOT.FoodItemCode.Label","Food Item Code"},
		{"eOT.ServingUOM.Label","Serving UOM"},
		{"eOT.servingTime.Label","Serving Time"},
		{"eOT.PreparationFactor.Label","Preparation Factor"},
		{"eOT.CalorieContentUOM.Label","Calorie Content / UOM"},
		{"eOT.PreparationUOM.Label","Preparation UOM"},
		{"eOT.PrepUOM.Label","Prep UOM"},
		{"eOT.PreparationBaseQty.Label","Preparation Base Qty"},
		{"eOT.PreparatoryFactor.Label","Preparatory Factor"},
		{"eOT.BaseQty.Label","Base Qty"},
		{"eOT.Qty.Label","Qty"},
		{"eOT.CommercialFormula.Label","Commercial Formula"},
		{"eOT.CrossReferenceItem.Label","Cross Reference Item"},
		{"eOT.Kitchen.Label","Kitchen"},
		{"eOT.KitchenArea.Label","Kitchen Area"},
		{"eOT.KitchenCode.Label","Kitchen Code"},
		{"eOT.KitchenAreaCode.Label","Kitchen Area Code"},
		{"eOT.Nutrient.Label","Nutrient"},
		{"eOT.ContentValue.Label","Content Value"},
		{"eOT.FoodItem.Label","Food Item"},
		{"eOT.UOMCode.Label","UOM Code"},
		{"eOT.NutrientsCommercialFormula.Label","Nutrients for Commercial Formula"},
		{"eOT.NutrientsFoodItem.Label","Nutrients for Food Item"},
		{"eOT.DayNo.Label","Day No"},
		{"eOT.Menu.Label","Menu"},
		{"eOT.MenuSchedCycle.Label","Menu Schedule Cycle"},
		{"eOT.MealPlanDate.Label","Meal Plan Date"},
		{"eOT.RefDayNo.Label","Reference Day No"},
		{"eOT.WardCode.Label","Ward Code"},
		{"eOT.EffectiveFromDate.Label","Effective From Date"},
		{"eOT.EffectiveToDate.Label","Effective To Date"},
		{"eOT.EffectiveToDate.Label","Effective To Date"},
		{"eOT.GenerateMealPlan.Label","Generate MealPlan"},
		{"eOT.PrintMealDietList.Label","Print MealDiet list"},
		{"eOT.DischargedPatients.Label","Discharged Patients"},
		{"eOT.MealPrepared.Label","Meal Prepared"},
		{"eOT.MealReceived.Label","Meal Received"},
		{"eOT.MealServed.Label","Meal Served"},
		{"eOT.MealReject.Label","Meal Rejected"},
		{"eOT.MealTypeTab.Label","Meal Type"},
		{"eOT.SpclFoodItems.Label","Special Food Items"},
		{"eOT.FreqBased.Label","Frequency Based"},
		{"eOT.NonFreqBased.Label","Non Frequency Based"},
		{"eOT.statusDateTimeforAllPatients.Label","Set Status / Date Time for all Patients"},
		{"eOT.Complaints.Label","Complaints"},
		{"eOT.Rejected.Label","Rejected ?"},
		{"eOT.MealOrderFrom.Label","Order Date From"},
		{"eOT.MealOrderTo.Label","Order Date To"},
		{"eOT.NoOfOrders.Label","No. Of Orders"},
		{"eOT.mealOrderForStaff.displayMessage","Do you want to create a new record?"},
		{"eOT.MealOrder.Label","Meal Order"},
		{"eOT.DocMealServed.Label","Document Meal Served"},
		{"eOT.NoOfMeals.Label","No. Of Meals"},
		{"eOT.TotalNoOfMealsServed.Label","Total No. of meals served"},
		{"eOT.NoOfMealsServed.Label","No. of meals served"},
		{"eOT.ServingDate.Label","Serving Date"},
		{"eOT.Kitchen.Label","Kitchen"},
		{"eOT.DietType.Label","Diet Type"},
		{"eOT.MealType.Label","Meal Type"},
		{"eOT.ItemDtls.Label","Item Details"},
		{"eOT.DontServe.Label","Don't Serve"},
		{"eOT.ServingQty.Label","Serving Qty"},
		{"eOT.Freq.Label","Freq."},
		{"eOT.RegnerateMealplan.Label","Regenerate Mealplan"},
		{"eOT.MealplanSeqno.Label","Meal Plan Sequence No"},
		{"eOT.GenerateMealPlanAttendant.Label","Generate MealPlan For Attendants"},//MMS-DM-CRF-0044
		{"eOT.MealTicketfor.Label","Meal Ticket for"},
		//Subhani place diet order

		{"eOT.deliveryInstruction.Label","Delivery Instruction"},
		{"eOT.feedingInstruction.Label","Feeding Instruction"},
		{"eOT.preparatoryInstruction.Label","Preparatory Instruction"},
		{"eOT.patientAttendantTitle.Label","Diet Order For Attendant"},
		{"eOT.assign.Label","Assign Diet Type If Different"},
		{"eOT.nilBYMounth.Label","Nil By Mouth"},
		{"eOT.dietOrders.Label","Diet Orders"},
		{"eOT.activeOrders.Label","Active Orders"},
		{"eOT.closedOrders.Label","Closed Orders"},
		{"eOT.futureOrders.Label","Future Orders"},
		{"eOT.aaaAttendent.Label","ADD ATTENDANT"},
		{"eOT.dietCycles.Label","Diet Cycle"},
		{"eOT.meals.Label","Meals"},
		{"eOT.nutriEntSupp.Label","Nutrient Supplement"},
		{"eOT.activeProblems.Label","Active Problems"},
		{"eOT.allergies.Label","Allergies"},
		{"eOT.fooditems.Label","Spl. Food items"},
		{"eOT.foodDislikes.Label","Food Dislikes"},
		{"eOT.menuForDate.Label","Menu For Date"},
		{"eOT.orDietCycle.Label","Or Diet Cycle"},
		{"eOT.serve.Label","Serve"},
		{"eOT.periodBetween.Label","Period Between"},
		{"eOT.foodType.Label","Food Item"},
		{"eOT.nutrientSupplient.Label","Nutrient Supplient"},
		{"eOT.addItem.Label","ADD ITEM"},
		{"eOT.CalorieGrandTotal.Label","Calorie Grand Total"},
		{"eOT.AddItemto.Label","Add Item To"},
		{"eOT.SelectItem.Label","Select Item"},
		{"eOT.qty.Label","Qty"},
		{"eOT.messageFrame.Label","MessageFrame"},
		{"eOT.placeDietOrder.Label","Place Diet Order"},
		{"eOT.patientOptionTitle.Label","Diet Order For Patient"},
		{"eOT.attendant.Label","Attendant"},
		{"eOT.show.Label","Show"},
		{"eOT.date.Label","Select Date"},
		{"eOT.edit.Label","Edit"},
		{"eOT.practitioner.Label","Practitioner"},
		{"eOT.admDate.Label","Admission Date"},
		{"eOT.frequency.Label","Frequency"},
		{"eOT.ReferredToDietician.Label","Refer to Dietician"},
		{"eOT.OrderPlacedForCurrentDate.Label","Order Placed For Current Date"},
		{"eOT.OrderPendingForPatient.Label","Order Pending For Patient"},
		{"eOT.OrderReferredToTheDietician.Label","Order Referred to the Dietician"},
		{"eOT.OrderModified.Label","Order Modified"},
		{"eOT.OrderPlaced.Label","Order Placed"},
		{"eOT.OrderPending.Label","Order Pending For Patient"},
		{"eOT.DieticianReferral.label","Refer to Dietician"},
		{"eOT.AttendantInstr.Label","Attendant Instruction"},
		{"eOT.gracePeriod.Label","Grace Period"},
		{"eOT.GracePeriodApplicable.Label","Applicability for Grace Period"},
		{"eOT.Remarks.Label","Remarks"},
		{"eOT.Ok.label","OK"},
		{"eOT.Cancel.label","Cancel"},
		{"eOT.DietOrderSheet.Label","Diet Order Sheet"},
		{"eOT.dsparameteracrossfacility.energy","Energy UOM"},
		{"eOT.dsparameteracrossfacility.deptcode","Dept Code"},
		{"eOT.DefaultDietForPatientsWoOrders.Label","General Default Diet For patients without orders"},
		{"eOT.Labelmessage.Label","LabelMessage"},
		{"eOT.MultiKitchen.Label","Multi Kitchen"},
		{"eOT.KitchenCode.Label","Kitchen Code"},
		{"eOT.MaxMealPlanAllowed.Label","Max Meal Plan Allowed Days"},
		{"eOT.NextMealPlanNo.Label","Next Meal Plan No."},
		{"eOT.AcceptDietTypeForMealType.Label","Accept diet type for each meal type"},
		{"eOT.InterfacePatBilling.Label","Interfaced to Patient Billing"},
		{"eOT.AttendantOrdersAppl.Label","Attendant Orders Applicable"},
		{"eOT.CutOffTimeToAckFreq.Label","Cut-off time to Acknowledge Frequency Based Items"},
		{"eOT.Hours.Label","Hours"},
		{"eOT.Ward.Label","Ward"},
		{"eOT.fromDate.Label","From Date"},
		{"eOT.toDate.Label","To Date"},
		{"eOT.reasonComplaints.Label","Reason Complaints"},
		{"eOT.WardWiseSummary.Label","Ward Wise Summary"},
		{"eOT.KitchenWiseSummary.Label","Kitchen Wise Summary"},
		{"eOT.MasterCodes.Label","Master Codes"},
		{"eOT.MenuCycle.Label","Menu Cycle"},
		{"eOT.MenuTimeTable.Label","Menu Time Table"},
		{"eOT.WardsForKitchen.Label","Wards For Kitchen"},
		{"eOT.AsaScore.Label","ASA Score"},
		{"eOT.IntraOperative.Label","Intra-Operative"},
		{"eOT.IntraOperativeApplicable.Label","Applicable for Intra Operative"},
		{"eOT.BookingAuthorizationRequired.Label","Booking Authorization Required"},//Added by MuthuN against CRF-4.1
		{"eOT.IntraOperativeCheckList.Label"," Intra Operative CheckList"},
		{"eOT.FromOperationDate.Label","From Operation Date"},
		{"eOT.ToOperationDate.Label","To Operation Date"},
		{"eOT.count.Label","Count"},
		//Add for KDAH-257-CRF
		{"eOT.BookingDateTime.Label"," Booked Date/Time"},
		//Added for MMS-QH-CRF-0076.1
		{"eOT.yes.Label","Yes"},
		{"eOT.no.Label","No"},
		{"eOT.MultiFacilityOP.Label","Enable Multi Facility Meal Order for Outpatients/Emergency Patients"},
		{"eOT.PlaceOPMealOrder.Label","Place Outpatient Meal Order"},
		{"eOT.OPMealOrder.Label","Outpatient Meal Order"},
		//Added for BRU 006
		{"eOT.SADate.Label","Date"},
		{"eOT.CreateStaffAssignment.Label","Create Staff Assignment"},
		{"eOT.SARoom.Label","Room"},
		{"eOT.StaffDetails.Label","Staff Details"},
		{"eOT.SARole.Label","Role"},
		{"eOT.SAName.Label","Name"},
		{"eOT.ShowInWidget.Label","Show in widget"},
		{"eOT.FromTime.Label","From Time"},
		{"eOT.ToTime.Label","To Time"},
		{"eOT.SAAction.Label","Action"},
		{"eOT.ModifyStaffAssignment.Label","Modify Staff Assignment"},
		{"eOT.AuditHistory.Label","Audit History"},
		{"eOT.SAOld.Label","Old"},
		{"eOT.SANew.Label","New"},
		{"eOT.ActionDateTime.Label","Action Date Time"},
		{"eOT.SAUser.Label","User"},
		{"eOT.ExternalLink.Label","External Link"},
		{"eOT.AuditTrail.Label","Audit Trail"},
		{"eOT.DisplayMapping.Label","Display Mapping"},
		{"eOT.DisplayStatus.Label","Display Status"},
		{"eOT.OTSlateStatus.Label","OT Slate Status"},
		//Add for KDAH-257-CRF
		{"eOT.BookingDateTime.Label","Booked Date/Time"},
		{"eOT.WidgetSelection.Label","Widget Selection"},
		{"eOT.StaffAssignment.Label","Staff Assignment"},
		{"eOT.ExtendDispConfig.Label","Extended Display Configuration"},
		{"eOT.AutoRefreshTime.Label","Auto refresh"},
		{"eOT.Widgetselectfordispare.Label","Widget selected for display are"},
		{"eOT.seconds.Label","seconds"},
		{"eOT.minutes.Label","minutes"},
		{"eOT.OnlyMaxThreeItemDisplay.Label","Only maximum of 3 items can be selected for a display."},
		{"eOT.Create.Label","Create"},
		{"eOT.DisplayMapping.Label","Display Mapping"},
		{"eOT.Createdisplaymap.Label","Create display mapping"},
		{"eOT.OTslatestatus.Label","OT slate status"},
		{"eOT.Bookings.Label","Bookings"},
		{"eOT.icareHospital.Label","iCARE Hospital"},
		{"eOT.CloseDashboard.Label","Close DashBoard"},
		{"eOT.DisplayDashboard.Label","Display DashBoard"},
		{"eOT.DisplayHospitalPersonnel.Label","Display Hospital Personnel Assigned During Booking/Check-In"},
		//Above line is Added by MuthuN against CHL-CRF-0020.1 on 11/6/2013
		{"eOT.OperSiteIdentify.Label","Operating Site Identification"},
		//Added for CRF-0092 Start
		{"eOT.OperSiteIdentify.Label","Operating Site Identification"},
		{"eOT.ItemRequestDetails.Label","Item Request Details"},
		{"eOT.ManageItemRequest.Label","Manage Item Request"},
		{"eOT.OrderID.Label","OT Order ID"},
		{"eOT.BookingDTTM.Label","Booking Date Time"},	
		{"eOT.OperationType.label","Operation Type"},
		{"eOT.BookingDTTM.Label","Booking Date Time"},
		{"eOT.Status.Label","Status"},
		{"eOT.Theatre.label","Theatre"},	
		{"eOT.Anesthetist.label","Anesthetist"},
		{"eOT.Add.label","Add"},
		{"eOT.Print.label","Print"},
		{"eOT.ItemDesc.label","Item Description"},
		{"eOT.RequestedDate.label","Requested Date"},
		{"eOT.ItemSpecRem.label","Item Spec Remarks"},
		{"eOT.Items.label","Items"},
		{"eOT.ChargesApplCheckinDateTime.label","Charges Applicable from Check-In Date Time"},
		//Added for CRF-0092 End.
		//PMG-CRF-003
		{"eOT.Reasons.label","Reasons"},
		{"eOT.DefaultUserRole.Label","Default User Role"},
		{"eOT.Roles.Label","Role"},
		{"eOT.RoleType.Label","Role Type"},
		{"eOT.Applicability.Label","Applicability"},
		{"eOT.IsDefault.Label","Is Default"},//PMG-CRF-003
		{"eOT.DateTime.label","Date & Time"},//047546
		{"eOT.BookingPriorityPendingOrders.label","Booking Priority for Pending Orders"}, //  start KDAH-CRF-0283 [IN:050553]
		{"eOT.PreoperativeClinicalComments.label","Pre-operative clinical comments"},
		{"eOT.OrderingSurgeon.label","Ordering Surgeon"}, //  end KDAH-CRF-0283 [IN:050553]
		{"eOT.LinkOperationAndNotesinRecordSurgeonNotes.Label","Link Operation And Notes in Record Surgeon Notes"},//PMG-MOD-0005

		 //IN054191 start
		{"eOT.NoOfSwabsRequired.Label","No. of Swab Counts reqd (Including Initial and Final Count)"},
		{"eOT.SecondCountComp.Label","Second Count Completed?"},
		{"eOT.AddtSecondCountComp.Label","Additions after Second Count Completed?"},
		{"eOT.ThirdCountComp.Label","Third Count Completed?"},
		{"eOT.AddtThirdCountComp.Label","Additions after Third Count Completed?"},
		{"eOT.FourthCountComp.Label","Fourth Count Completed?"},
		{"eOT.AddtFourthCountComp.Label","Additions after Fourth Count Completed?"},
		{"eOT.FifthCountComp.Label","Fifth Count Completed?"},
		{"eOT.AddtFifthCountComp.Label","Additions after Fifth Count Completed?"},
		{"eOT.AddtSecondCount.Label","Additions(after Second Count)"},
		{"eOT.ThirdCount.Label"," Third Count"},
		{"eOT.AddtThirdCount.Label","Additions(after Third Count)"},
		{"eOT.FourthCount.Label"," Fourth Count"},
		{"eOT.AddtFourthCount.Label","Additions(after Fourth Count)"},
		{"eOT.FifthCount.Label"," Fifth Count"},
		{"eOT.AddtFifthCount.Label","Additions(after Fifth Count)"},
		 //IN054191 end
		//AAKH-71 Start
		{"eOT.Or.Label","OR"},
		{"eOT.EstimatedTime.Label","Estimated Time"},
		{"eOT.TotalBookingsbyOR.Label","Total Bookings by OR"},
		{"eOT.TotalBookingsbySurgeon.Label","Total Bookings by Surgeon"},
		//AAKH-71 end
		
		//MMS-QH-CRF-0186
		{"eOT.FutureAppointmentExists.Label","Future Appointment Exists"},
		{"eOT.AnaesthesiaRequired.Label","Anaesthesia Required"},
		{"eOT.ConsentRecorded.Label","Consent Recorded"},
		{"eOT.ConsentRequiredandNotRecorded.Label","Consent Required and Not Recorded"},
		{"eOT.FutureAppointment.Label","Future Appointment"},
		{"eOT.Consent.Label","Consent"},
		{"eOT.TimelimitForExistingBookingShouldBeminimumAndMaximum.Label","Timelimit for existing booking selection (In days) should be minimum 1 and maximum 365"},
		{"eOT.AllowMergeOfPendingOrdersIntoExistingBooking.Label","Allow merge of pending orders into existing booking"},
		{"eOT.TimelimitForExistingBookingSelection.Label","Timelimit for existing booking selection (In days)"},
		{"eOT.IncludeBlockedSlotinAvailableSlotCount.Label","Include Blocked Slot in Available Slot Count"},//ML-MMOH-CRF-0337
		{"eOT.FullyBlocked.Label","Fully Blocked"},
		{"eOT.PartiallyBlocked.Label","Partially Blocked"},//ML-MMOH-CRF-0337

		//MMS-QH-CRF-0215
		{"eOT.OTbyCategorization.Label","OT by Categorization"},
		{"eOT.OTbySpecialist.Label","OT by Specialist"},
		{"eOT.OTStatisticalReport.Label","OT Statistical Report"},
		{"eOT.FromOperationMonth.Label","From Operation Month"},
		{"eOT.ToOperationMonth.Label","To Operation Month"},
		{"eOT.ARAMCO.Label","ARAMCO"},
		//MMS-QH-CRF-0215
		//GDOH-CRF-0083 starts
		{"eOT.ServingFromDate.Label","Serving From Date"},
		{"eOT.ServingToDate.Label","Serving To Date"},
		//GDOH-CRF-0083 ends
		{"eOT.MultiCheckInAllowed.Label","Multiple Check In Allowed"},//KDAH PMG CRF-0001
		{"eOT.CategoryType.Label","Category Type"},//Added against MO-CRF-20086	
		//Added against ML-MMOH-CRF-1208
		{"eOT.OperDate.Label","Oper Date"},
		{"eOT.Ot.Label","OT"},
		{"eOT.InsuranceStatus.label","Insurance Status"},//Added against TH-KW-CRF-0126
        {"eOT.PatientPayement.label","Patient Payement"},//Added against TH-KW-CRF-0126
        {"eOT.DisclaimerForBillStatus.label","*Patient paid status is subject to change during the final bill/settlement"}, //Added against TH-KW-CRF-0126
		//Added Against ML-MMOH-CRF-1939
		{"eOT.IncludeFpp.Label","Include FPP"},
		{"eOT.FppCategory.Label","FPP Category"},
		{"eOT.Simple.Label","Simple"},
		{"eOT.Moderate.Label","Moderate"},
		{"eOT.Complex.Label","Complex"},
		{"eOT.NonFPP.Label","Non FPP"},//Added against ML-MMOH-CRF-1939
		{"eOT.MandatoryField.Label","Mandatory Field"}, //Added against ML-MMOH-CRF-1936
		{"eOT.StartandEndTime.Label","Start & End Time"}, //Added against ML-MMOH-CRF-1936
		{"eOT.Preparation.Label","Preparation"}, //Added against ML-MMOH-CRF-1936
		{"eOT.Recorded.Label","Recorded"}, //Added against ML-MMOH-CRF-1936
		{"eOT.NotyetRecorded.Label","Not yet Recorded"}, //Added against ML-MMOH-CRF-1936
		{"eOT.DateTimeScheduled.Label","Date/Time Scheduled"}, //Added against ML-MMOH-CRF-1791-US04
		{"eOT.DateTimeRescheduled.Label","Date/Time New Scheduled"}, //Added against ML-MMOH-CRF-1791-US04
		{"eOT.PerformedBy.Label","Performed By"}, //Added against ML-MMOH-CRF-1791-US04
		{"eOT.Reschdl.Label","Rescheduled"}, //Added against ML-MMOH-CRF-1696
		{"eOT.AutoSchdlToNxtDay.Label","Auto Schedule to Next Day for case finalized"}, //Added against ML-MMOH-CRF-1791-US001
		{"eOT.AllowToUpdateNotes.Label","Allow to Update Notes in Record Surgeon Notes if Documentation Completed in Record Surgeon Notes"}, //Added by Gaurav Hardia against PMG2023-MMS-CRF-0002
		{"eOT.UpdatingNotesDoc.Label","Updating Notes After Documentaion Completed"}, //Added against PMG2023-MMS-CRF-0002
		{"eOT.UpdateNotes.Label","Update Notes"} //Added against PMG2023-MMS-CRF-0002
		};
}