package eAE.resources;

import java.util.*;

public class  Labels  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
		{"eAE.Abdomen.label","Abdomen"},
		{"eAE.Absent.label","Absent"},
		{"eAE.AccidentCase.label","Accident Case"},
		{"eAE.AccidentType.label","Accident Type"},
		{"eAE.AccompaniedBy.label","Accompanied By"},
		{"eAE.AddedBy.label","Added By"},
		{"eAE.AddedDateTime.label","Added Date Time"},
		{"eAE.AddrofEscortAmbulanceService.label","Address of Escort/Ambulance Service"},
		{"eAE.AEDetails.label","A E Details"},
		{"eAE.AffectedSite.label","Affected Site"},
		{"eAE.AgeLimits.label","Age Limits"},
		{"eAE.AirEntryRight.label","Air Entry Right"},
		{"eAE.Airway.label","Airway"},
		{"eAE.AllowbackdatingofVisitDateTime.label","Allow backdating of Visit Date/Time"},
		{"eAE.AmbulanceDetails.label","Ambulance Details"},
		{"eAE.AssessmentDateTime.label","Assessment Date/Time"},
		{"eAE.AssignBedBaysForTreatmentArea.label","Assign Bed/Bays For Treatment Area"},
		{"eAE.AssignedDateTime.label","Assigned Date/Time"},
		{"eAE.AssignedPractitioner.label","Assigned Practitioner"},
		{"eAE.AssignTreatArea.label","Assign Treatment Area"},
		{"eAE.AssignTreatmentArea.label","Assigned Treatment Area"},
		{"eAE.AttendanceDate.label","Attendance Date"},
		{"eAE.AttendanceDateTo.label","Attendance Date To"},
		{"eAE.AttendDateFrom.label","Attendance Date From"},
		{"eAE.Autoclosed.label","Autoclosed"}, 
		{"eAE.BedBay.label","Bed / Bay"},
		{"eAE.BedBayAvailabilityChart.label","Bed/Bay Availability Chart"},
		{"eAE.BedBayNo.label","Bed/Bay No"},
		{"eAE.BedBayStatus.label","Bed/Bay Status"},
		{"eAE.BedBayType.label","Bed/Bay Type"},
		{"eAE.BedBayTypeCode.label","Bed/Bay Type Code"},
		{"eAE.BedBayTypeDesc.label","Bed/Bay Type Desc"},
		{"eAE.BillingInterface.label","Billing Interface"},
		{"eAE.BillingInterfaced.label","Billing Interfaced"},
		{"eAE.Blood.label","Blood"},
		{"eAE.BloodAtMeatus.label","Blood at Meatus"},
		{"eAE.Blunt.label","Blunt"},
		{"eAE.BonyCrepitus.label","Bony Crepitus"},
		{"eAE.BonyCrepitusPos.label","Bony Crepitus Position"},
		{"eAE.Brachial.label","Brachial"},
		{"eAE.BreathDensity.label","Breathing Density"},
		{"eAE.Breathing.label","Breathing"},
		{"eAE.BreathSound.label","Breath Sound"},
		{"eAE.BreathType.label","Breathing Type"},
		{"eAE.Brisk.label","Brisk"},
		{"eAE.BulbocavemousReflex.label","Bulbocavemous Reflex"},
		{"eAE.Burn.label","Burn"},
		{"eAE.CapacityRefill.label","Capacity Refill"},
		{"eAE.CapBloodSugar.label","Cap Blood Sugar"},
		{"eAE.CapillaryBloodSugar.label","Capillary Blood Sugar"},
		{"eAE.CaseDetails.label","Case Details"},
		{"eAE.CaseofMLC.label","Case of MLC"},
		{"eAE.Catheterin.label","Catheter in"},
		{"eAE.CauseofAccident.label","Cause of Accident"},
		{"eAE.CervicalCollar.label","Cervical Collar"},
		{"eAE.Chest.label","Chest"},
		{"eAE.ChestTubeinSitu.label","Chest Tube in Situ"},
		{"eAE.ChestTubeinSituVolLeft.label","Chest Tube in Situ. Volume Left"},
		{"eAE.ChestTubeinSituVolRight.label","Chest Tube in Situ. Volume Right"},
		{"eAE.Circulation.label","Circulation"},
		{"eAE.Cold.label","Cold"},
		{"eAE.ConditionCase.label","Condition / Case"},
		{"eAE.ContactTelNo.label","Contact Tel No."},
		{"eAE.Convulsion.label","Convulsion"},
		{"eAE.CreateAttendanceDetails.label","Create Attendance Details"},
		{"eAE.CSpineFracture.label","C-Spine Fracture"},
		{"eAE.CSpineTenderness.label","C-Spine Tenderness"},
		{"eAE.Cutoffperiodforincluding.label","Cut off period for including previous days visits"},
		{"eAE.Cyanotic.label","Cyanotic"},
		{"eAE.DateTimeIn.label","Date/Time In"},
		{"eAE.Deep.label","Deep"},
		{"eAE.DegreeofBurn.label","Degree of Burn"},
		{"eAE.Density.label","Density"},
		{"eAE.DetailsOfTheCaseMLCCase.label","Details Of The Case / MLC Case"},
		{"eAE.Diffuse.label","Diffuse"},
		{"eAE.Diminished.label","Diminished"},
		{"eAE.DisabilityCNS.label","Disability CNS"},
		{"eAE.DisasterArea.label","Disaster Area"},
		{"eAE.DisasterPatientRegistration.label","Disaster Patient Registration"},
		{"eAE.DisasterType.label","Disaster Type"},
		{"eAE.DisasterTypeCode.label","Disaster Type Code"},
		{"eAE.DisasterTypeDesc.label","Disaster Type Desc"},
		{"eAE.DispositionCodeFrom.label","Disposition Code From"},
		{"eAE.DispositionCodeTo.label","Disposition Code To"},
		{"eAE.DispositionDate.label","Disposition Date"},
		{"eAE.DispositionDateFrom.label","Disposition Date From"},
		{"eAE.DispositionDateTo.label","Disposition Date To"},
		{"eAE.DispositionTypeCode.label","Disposition Type Code"},
		{"eAE.Distended.label","Distended"},
		{"eAE.Doneduring.label","Done During"},
		{"eAE.Dry.label","Dry"},
		{"eAE.Easy.label","Easy"},
		{"eAE.ECGMonitorBP.label","ECG Monitor BP"},
		{"eAE.EID.label","EID"},
		{"eAE.Emergencyclinic.label","Emergency Clinic"},
		{"eAE.Equal.label","Equal"},
		{"eAE.EscAmbulanceContNo.label","Escort/Ambulance Contact No"},
		{"eAE.Escort.label","Escort"},
		{"eAE.EscortDetail.label","Escort Detail"},
		{"eAE.EscortName.label","Escort Name"},
		{"eAE.ExamDateTime.label","Exam Date/Time"},
		{"eAE.ExaminedBy.label","Examined By"},
		{"eAE.ExistingDetails.label","Existing Details"},
		{"eAE.ExistingPatientID.label","Existing Patient ID"},
		{"eAE.ExpLengthOfStay.label","Exp Length Of Stay"},
		{"eAE.Extremities.label","Extremities"},
		{"eAE.EyeResponse.label","Eye Response"},
		{"eAE.EyeResponseGCSDescription.label","Eye Response GCS Description"},
		{"eAE.FacialFracture.label","Facial Fracture"},
		{"eAE.FB.label","FB"},
		{"eAE.FBC.label","FBC"},
		{"eAE.Femoral.label","Femoral"},
		{"eAE.FlailSegment.label","Flail Segment"},
		{"eAE.FlailSegPos.label","Flail Segment Position"},
		{"eAE.Fracture.label","Fracture"},
		{"eAE.FractureDislocation.label","Fracture Dislocation"},
		{"eAE.FracturesList.label","Fractures List"},
		{"eAE.GCS.label","GCS"},
		{"eAE.GCSCategory.label","GCS Category"},
		{"eAE.GCSCode.label","GCS Code"},
		{"eAE.GCSCodes.label","GCS Codes"},
		{"eAE.GCSDesc.label","GCS Desc"},
		{"eAE.GCSDescription.label","GCS Description"},
		{"eAE.GCSforResponse.label","GCS for Response"},
		{"eAE.GCSforResponseCode.label","GCS for Response Code"},
		{"eAE.GCSResponseCode.label","GCS Response Code"},
		{"eAE.GCSResponseDesc.label","GCS Response Desc"},
		{"eAE.GCSScore.label","GCS Score"},
		{"eAE.GenitoUrinary.label","Genito urinary"},
		{"eAE.Good.label","Good"},
		{"eAE.GrowthDevelMileStoneforAge.label","Growth/Developmental Mile Stone for Age"},
		{"eAE.GTubeNasal.label","G-Tube Nasal"},
		{"eAE.GTubeOral.label","G-Tube Oral"},
		{"eAE.GynaecDetail.label","Gynaec Detail"},
		{"eAE.GynaecDetails.label","Gynaec Details"},
		{"eAE.Haematura.label","Haematura"},
		{"eAE.HeadNeck.label","Head & Neck"},
		{"eAE.Hyper.label","Hyper"},
		{"eAE.Immobilization.label","Immobilization"},
		{"eAE.ImmobilizationCode.label","Immobilization Code"},
		{"eAE.ImmobilizationDesc.label","Immobilization Desc"},
		{"eAE.ImmunizationuptoDate.label","Immunization up to Date"},
		{"eAE.Impaired.label","Impaired"},
		{"eAE.IncludeCheckOutPat.label","Include Checked Out Patient"},
		{"eAE.Infant.label","Infant"},
		{"eAE.InitialManagement.label","Initial Management"},
		{"eAE.InjuryCategory.label","Injury Category"},
		{"eAE.InjuryCategoryCode.label","Injury Category Code"},
		{"eAE.InjuryCategoryDesc.label","Injury Category Desc"},
		{"eAE.InjurySubcategory.label","Injury Subcategory"},
		{"eAE.InjurySubcategoryCode.label","Injury Subcategory Code"},
		{"eAE.InjurySubcategoryDesc.label","Injury Subcategory Desc"},
		{"eAE.InjuryType.label","Injury Type"},
		{"eAE.InvokeVitalSignsfromQueue.label","Invoke Vital Signs from Queue"},
		{"eAE.Irregular.label","Irregular"},
		{"eAE.JVP.label","JVP"},
		{"eAE.Laboured.label","Laboured"},
		{"eAE.LastVisitWithin24Hrs.label","Last Visit Within 24 Hrs. Details"},
		{"eAE.LimbColour.label","Limb Colour"},
		{"eAE.LLQ.label","LLQ"},
		{"eAE.LMPDate.label","LMP Date"},
		{"eAE.LocationofAccident.label","Location of Accident"},
		{"eAE.LUQ.label","LUQ"},
		{"eAE.MaxAgeofcapturingpediatric.label","Max Age of the patient for capturing pediatric details"},
		{"eAE.MaxNoofdayallowedforrevattenddetls.label","Max No of days allowed for revising attendance details"},
		{"eAE.MaxNoofdaysallowedforRevising.label","Max No of days allowed for Revising Attendance"},
		{"eAE.MechaofSubInjury.label","Mechanism of Sub-Injury"},
		{"eAE.MinAgeofcapturingpediatric.label","Min Age of the patient for capturing pregnancy  details"},
		{"eAE.Motor Response GCS Description.label","Motor Response GCS Description"},
		{"eAE.MotorResponse.label","Motor Response"},
		{"eAE.MovementHistory.label","Movement History"},
		{"eAE.NameofEscortService.label","Name of Escort/Ambulance Service"},
		{"eAE.NasalAirway.label","Nasal airway"},
		{"eAE.NewDetails.label","New Details"},
		{"eAE.NewPatientID.label","New Patient ID"},
		{"eAE.NoControl.label","No Control"},
		{"eAE.NoControlOn.label","No Control On"},
		{"eAE.NonCritical.label","Non-Critical"},
		{"eAE.NonResp.label","Non Resp"},
		{"eAE.NoofPatients.label","No. of Patients"},
		{"eAE.NormalBedBay.label","Normal Bed/Bay"},
		{"eAE.NursingDetails.label","Nursing Details"},
		{"eAE.Obstructed.label","Obstructed"},
		{"eAE.ObstructedBy.label","Obstructed By"},
		{"eAE.OneBed.label","Atleast one Bed should be selected"},
		{"eAE.OpenPneumothroax.label","Open Pneumothroax"},
		{"eAE.OpenPneumothroaxPos.label","Open Pneumothroax Position"},
		{"eAE.OpentoAllPracLocation.label","Open to All Practitioners of Location"},
		{"eAE.OpenWound.label","Open Wound"},
		{"eAE.OpenWoundPos.label","Open Wound Position"},
		{"eAE.OpenWounds.label","Open Wounds"},
		{"eAE.OralAirway.label","Oral airway"},
		{"eAE.OrderByPriority.label","Order By Priority"},
		{"eAE.OTDateTime.label","OT Date/Time"},
		{"eAE.Pale.label","Pale"},
		{"eAE.PatientManagement.label","Patient Management"},
		{"eAE.PatientPositionCode.label","Patient Position Code"},
		{"eAE.PatientPositionduringIncident.label","Patient Position during Incident"},
		{"eAE.PatientPriority.label","Patient Priority"},
		{"eAE.PatientPriorityCode.label","Patient Priority Code"},
		{"eAE.PatientsSeenDate.label","Patients Seen Date/Time"},
		{"eAE.PatientsSeenDateFrom.label","Patients Seen Date/Time From"},
		{"eAE.PatientsSeenDateTo.label","Patients Seen Date/Time To"},
		{"eAE.PatientTypeFrom.label","Patient Type From"},
		{"eAE.PatientTypeTo.label","Patient Type To"},
		{"eAE.PatPositionDesc.label","Patient Position Desc"},
		{"eAE.PatSecondaryTriageHistory.label","Patient Secondary Triage History"},
		{"eAE.Pedal.label","Pedal"},
		{"eAE.PediatricDetails.label","Pediatric Details"},
		{"eAE.Pelvis.label","Pelvis"},
		{"eAE.Penetrating.label","Penetrating"},
		{"eAE.Physician.label","Physician"},
		{"eAE.Popliteal.label","Popliteal"},
		{"eAE.PositionDesc.label","Position Desc"},
		{"eAE.PostalCodeNo.label","Postal Code No"},
		{"eAE.Practitionerfor.label","Practitioner for"},
		{"eAE.PractitionerIDFrom.label","Practitioner ID From"},
		{"eAE.PractitionerIDTo.label","Practitioner ID To"},
		{"eAE.PreviousSurgery.label","Previous Surgery"},
		{"eAE.PrimaryAssessment.label","Primary Assessment"},
		{"eAE.PrimaryTriageDetails.label","Primary Triage Details"},
		{"eAE.PriorityDesc.label","Priority Desc"},
		{"eAE.PriorityZoneDesc.label","Priority Zone Desc"},
		{"eAE.PriorityZoneCode.label","Priority Zone"},
		{"eAE.PriorityZoneColorDesc.label","Priority Zone Desc"},
		{"eAE.PriorityZoneTabDesc.label","Priority Zone Tab Desc"},
		{"eAE.Prostrate.label","Prostrate"},
		{"eAE.ProtectiveDevice.label","Protective Device"},
		{"eAE.ProtectiveDeviceCode.label","Protective Device Code"},
		{"eAE.ProtectiveDeviceDesc.label","Protective Device Desc"},
		{"eAE.PseudoBedBay.label","Pseudo Bed/Bay"},
		{"eAE.PseudoBedBays.label","Pseudo Bed/Bays"},
		{"eAE.PseudoBeds.label","Pseudo Beds"},
		{"eAE.PulsesRight.label","Pulses Right"},
		{"eAE.PupilReaction.label","Pupil Reaction"},
		{"eAE.PupilSize.label","Pupil Size"},
		{"eAE.PupilSizeLeft.label","Pupil Size Left"},
		{"eAE.Radial.label","Radial"},
		{"eAE.Reasons.label","Reasons"},
		{"eAE.ReassignTreatArea.label","Reassign Treatment Area"},
		{"eAE.RecordedDetails.label","Recorded Details"},
		{"eAE.Rectal.label","Rectal"},
		{"eAE.RectalInjury.label","Rectal Injury"},
		{"eAE.Reduced.label","Reduced"},
		{"eAE.RegistrationType.label","Registration Type"},
		{"eAE.Relation.label","Relation"},
		{"eAE.ReservedBedBay.label","Reserved Bed/Bay"},
		{"eAE.ReservedUntil.label","Reserved Until"},
		{"eAE.ReserveUntil.label","Reserve Until"},
		{"eAE.ResidenceAreaCodeFrom.label","Residence Area Code From"},
		{"eAE.ResidenceAreaCodeTo.label","Residence Area Code To"},
		{"eAE.Respiratory.label","Respiratory"},
		{"eAE.RespiratoryRate.label","Respiratory Rate"},
		{"eAE.ResponseToPain.label","Response to pain"},
		{"eAE.ResponseToVerbal.label","Response to Verbal"},
		{"eAE.Responsiveness.label","Responsiveness"},
		{"eAE.Resuscitation.label","Resuscitation"},
		{"eAE.RibFracture.label","Rib Fracture"},
		{"eAE.RibFracturePos.label","Rib Fracture Position"},
		{"eAE.Right.label","Right"},
		{"eAE.Rigidity.label","Rigidity"},
		{"eAE.RLQ.label","RLQ"},
		{"eAE.RTA.label","RTA"},
		{"eAE.RUQ.label","RUQ"},
		{"eAE.ScoreType.label","Score Type"},
		{"eAE.SecondaryTriage.label","Secondary Triage"},
		{"eAE.Shallow.label","Shallow"},
		{"eAE.SkinCondition.label","Skin Condition"},
		{"eAE.Sluggish.label","Sluggish"},
		{"eAE.SpareBedBay.label","Spare Bed/Bay"},
		{"eAE.Spine.label","Spine"},
		{"eAE.SpO2.label","Sp02"},
		{"eAE.Spontaneous.label","Spontaneous"},
		{"eAE.Stable.label","Stable"},
		{"eAE.SubCategoryCode.label","Sub Category Code"},
		{"eAE.SubEmphysema.label","Sub. Emphysema"},
		{"eAE.Suprapubic.label","Suprapubic"},
		{"eAE.Symptom.label","Symptom"},
		{"eAE.SystolicBP.label","Systolic BP"},
		{"eAE.Tenderness.label","Tenderness"},
		{"eAE.Tense.label","Tense"},
		{"eAE.TetanusVaccination.label","Tetanus Vaccination"},
		{"eAE.Tone.label","Tone"},
		{"eAE.Trachea.label","Trachea"},
		{"eAE.TracheaMidlineShifted.label","Trachea Midline Shifted"},
		{"eAE.TracheaMidlineShiftTo.label","Trachea Midline Shifted To"},
		{"eAE.TraumaAssessment.label","Trauma Assessment"},
		{"eAE.TraumaDetails.label","Trauma Details"},
		{"eAE.TraumaScore.label","Trauma Score"},
		{"eAE.TreatmentAreaCode.label","Treatment Area Code"},
		{"eAE.TreatmentAreaDesc.label","Treatment Area Desc"},
		{"eAE.TreatmentAreaforLocation.label","Treatment Area for Location"},
		{"eAE.Triage.label","Triage"},
		{"eAE.UnassignedList.label","Unassigned List"},
		{"eAE.Unstable.label","Unstable"},
		{"eAE.Vaccinated.label","Vaccinated"},
		{"eAE.ValuableDetails.label","Valuable Details"},
		{"eAE.Vascular.label","Vascular"},
		{"eAE.VehicleRegNo.label","Motor Vehicle Registration No"},
		{"eAE.VerbalResponse.label","Verbal Response"},
		{"eAE.VerbalResponseGCSDescription.label","Verbal Response GCS Description"},
		{"eAE.VisitWithin24Hrs.label","Visit Within 24 Hrs"},
		{"eAE.VolumeLeft.label","Volume Left"},
		{"eAE.VolumeRight.label","Volume Right"},
		{"eAE.Vomits.label","Vomits"},
		{"eAE.Warm.label","Warm"},
		{"eAE.Consulted.label","Consulted"},
		{"eAE.AwaitingTreatment.label","Awaiting Treatment"},
		{"eAE.AssignedtoTreatmentArea.label","Assigned to Treatment Area"},
		{"eAE.UndergoingTreatment.label","Undergoing Treatment"},
		{"eAE.ConsultationStarted.label","Consultation Started"},
		{"eAE.TriageDateTime.label","Triage Date Time"},
		{"eAE.Screening.label","Screening"},
		{"eAE.MainComplaintAndKeyFindings.label","Main complaint and key findings"},
		{"eAE.NewProblems.label","New Problems"},
		{"eAE.TickApplicableCategory.label","Tick Applicable Category"},
		{"eAE.SpecialInvestigations.label","Special Investigations"},
		{"eAE.ReferToOtherFacility.label","Refer to other facility"},
		{"eAE.HealthcareProfessional.label","Health Care Professional"},
		{"eAE.PleaseSpecify.label","Please Specify"},
		{"eAE.Noproblemexists.label","No Problem Exists"}, 
		{"eAE.DateTimeOfAccident.label","Date/Time of Accident"}, 
		{"eAE.PlaceOfAccident.label","Place of Accident"},
		{"eAE.MotorVehicleAccident.label","Motor Vehicle Accident"},
		{"eAE.LocationOfLastVisit.label","Location of last visit"},
		{"eAE.ScreeningData.label","Screening Data"},
		{"eAE.TriageLevel.label","Triage Level"},
		{"eAE.TriageNurse.label","Triage Nurse"},
		{"eAE.NursingQuickLook.label","Nursing Quick Look"},
		{"eAE.NonAppointment.label","Non appointment"},
		{"eAE.OPD.label","OPD"},
		{"eAE.FastTrack.label","Fast track"},
		{"eAE.TriageTime.label","Triage Time"},
		{"eAE.NursingTriage.label","Nursing Triage"},
		{"eAE.BW.label","BW"},
		{"eAE.GmKg.label","gm/Kg"},
		{"eAE.Ht.label","Ht"},
		{"eAE.T.label","T"},
		{"eAE.P.label","P"},
		{"eAE.RR.label","RR"},
		{"eAE.BP.label","BP"},
		{"eAE.mmHg.label","mmHg"},
		{"eAE.02Sat.label","O2 Sat"},
		{"eAE.O.label","O"},
		{"eAE.I.label","I"},
		{"eAE.ExaminationTime.label","Examination time"},
		{"eAE.PrimarySurvey.label","Primary Survey"},
		{"eAE.SecondarySurvey.label","Secondary Survey"},
		{"eAE.PatientAllergies.label","Patient allergies"},
		{"eAE.NursingTreatment.label","Nursing treatment"},
		{"eAE.AllowRegAttendInpat.label","Allow Register Attendance for Inpatient"},
		{"eAE.Consultation.label","Consultation"},
		{"eAE.EnableAccess.label","Enable Access Rights for Emergency Queue Management"},
		{"eAE.MinAgeofcapturingLMP.label","Min Age of the patient for capturing LMP details"},
		{"eAE.DisRegnReference.label","Dis. Regn. Reference"},
		{"eAE.DisRegnReference1.label","Dis.Regn.Reference"},
		{"eAE.Cases.label","Cases"},
		{"eAE.The.label","The"},
		{"eAE.Recall.label","Recall"},
		{"eAE.EstdAge.label","Estd Age"},
		{"eAE.DisasterManag.label","Disaster Management"},
		{"eAE.ObservationWardType.label","Observation Ward Type"},
		{"eAE.NonEmergency.label","Non-Emergency"},
		{"eAE.antipyretic.label", "Antipyretic"},
		{"eAE.tepid.label", "Tepid"},
		{"eAE.sponge.label", "Sponge"},
		{"eAE.DefUnknownAdultAge.label", "Default Unknown Adult Age"},
		{"eAE.NonAppt.label","Non Appt"},
		{"eAE.AllowAEchkoutWithBillSettle.label","Allow AE checkout with bill settlement"},
		{"eAE.OutstandingBillsSettlement.label","Outstanding Bills Settlement"},
		{"eAE.ObservationWard.label","Observation Ward"},
		{"eAE.IncludeTreatAreaPat.label","Include Treatment Area Assigned Patients"},		
		{"eAE.PromptMsgReAttnd.label","Alert Re-attendance of the Patient in Register Attendance Within"},
		{"eAE.LevelsOfTriageApplicable.label","Levels of Triage Applicable"}, //this line added by senthil
		{"eAE.DeadOnArrival.label","Dead on Arrival"},//Added For AAKH-CRF-0010 [IN:038535] By Dharma on Mar 4th 2014
		{"eAE.ColorIndicator.label","Color Indicator"},//Added For AAKH-CRF-0010 [IN:038535] By Dharma on Mar 4th 2014
		{"eAE.EndNumber.label","End Number"},
		{"eAE.IncidentRegister.label","Incident Register"},
		{"eAE.AmbulanceOdometer.label","Ambulance Odometer"},
		{"eAE.RequestQueuePeriod.label","Request Queue Period"},
		{"eAE.IncidentNumberingBy.label","Incident Numbering By"},
		{"eAE.Displaypastrequestsfor.label","Display past requests for "},
		{"eAE.Displayfuturerequestsfor.label","Display future requests for"},
		{"eAE.OdometerUnits.label","Odometer Units"},
		{"eAE.PrintCompletedTripSheet.label","Print Completed Trip Sheet"},
		{"eAE.AmbulanceType.label","Ambulance Type"},
		{"eAE.Make.label","Make"},
		{"eAE.AvailableStaff.label","Available Staff"},
		{"eAE.StaffStartsWith.label","Staff Starts With"},
		{"eAE.DisplayContact.label","Display Contact"},
		{"eAE.AttachedEquipments.label","Attached Equipments"},
		{"eAE.AvailableEquipments.label","Available Equipments"},
		{"eAE.EquipmentsStartsWith.label","Equipments Starts With"},
		{"eAE.AssociatedStaff.label","Associated Staff"},
		{"eAE.AmbulanceManagementDashboard.label","Ambulance Management Dashboard"},
		{"eAE.RequestedQueue.label","Requested Queue"},
		{"eAE.AmbulanceChart.label","Ambulance Chart"},
		{"eAE.maintenance.label","Maintenance"},
		{"eAE.find.label","Find"},
		{"eAE.NatureOfCall.label","Nature Of Call"},
		{"eAE.GoogleMap.label","Google Map"},
		{"eAE.Dispatched.label","Dispatched"},
		{"eAE.RequesterName.label","Requester Name"},
		{"eAE.AttendedBy.label","Attended By"},
		{"eAE.PickupLocation.label","Pickup Location"},
		{"eAE.PickupTime.label","Pickup Time"},
		{"eAE.Immediate.label","Immediate"},
		{"eAE.DroppingLocation.label","Dropping Location"},
		{"eAE.AmbulanceServiceType.label","Ambulance Service Type"},
		{"eAE.OdometerStart.label","Odometer Start"},
		{"eAE.ExpectedDistance.label","Expected Distance"},
		{"eAE.StartDateTime.label","Start Date Time"},
		{"eAE.DispatchRemarks.label","Dispatch Remarks"},
		{"eAE.OdometerEnd.label","Odometer End"},
		{"eAE.DistanceCovered.label","Distance Covered"},
		{"eAE.UnderRepair.label","Under Repair"},
		{"eAE.RecordUnderMaintenanceDetails.label","Record Under Maintenance Details"},
		{"eAE.RevokeUnderMaintenanceDetails.label","Revoke Under Maintenance Details"},
		{"eAE.RevokeMaintenance.label","Revoke Maintenance"},
		{"eAE.UpdateAmbulanceStatus.label","Update Ambulance Status"},
		{"eAE.StartingMeter.label","Starting Meter"},
		{"eAE.Endmeter.label","End meter"},
		{"eAE.CustomizedPositionforGridtable.label","Customized Position for Grid table"},
		{"eAE.Choosewhichcolumnsyouwouldliketosee.label","Choose which columns you would like to see"},
		{"eAE.NoOfPatientIDsToBePrinted.label","No of Patient IDs to be printed"},
		{"eAE.RecordDiagnosisNotMandatory.label","Record Diagnosis not Mandatory"}, //Added by Ashwini on 10-Jan-2017 for ML-MMOH-CRF-624
		{"eAE.PickupPlace.label","Pickup Place"}, //Added by Ashwini on 18-Jan-2017 for GDOH-CRF-0131
		{"eAE.DisasterReference.label","Disaster Reference"}, //Added by Mano on 20-Apr-2017 for ML-MMOH-CRF-0644 
		{"eAE.Reattendance.label","Re-Attendance"}, //Added for this CRF ML-MMOH-CRF-0637
		{"eAE.SeenbyDoctorImmediately.label","Seen by Doctor Immediately?"}, //Added for this CRF ML-MMOH-CRF-0629
		{"eAE.Messagefrom.label","Message from"}, //Added for this CRF ML-MMOH-CRF-0629 
		{"eAE.Zone.label","Zone"}, //Added by Sangeetha for ML-MMOH-CRF-0636 on 26/apr/17
		{"eAE.DisplayAEattendanceregisteredwithinHrs.label","Display AE Patients with attendance registered within"}, //Added for this CRF ML-MMOH-CRF-0639
		// added for ML-MMOH-CRF-0647 by Mujafar start
		{"eAE.PlaceOfOccurrenceCode.label","Place of Occurrence Code"},
		{"eAE.PlaceOfOccurrence.label","Place of Occurrence"},
		{"eAE.DateTimeOfOccurrence.label","Date/Time of Occurrence"},
		{"eAE.PlaceOfOccurrenceDesc.label","Place of Occurrence Description"},
		// added for for ML-MMOH-CRF-0647 by Mujafar end
		{"eAE.RegisterNewBornForAE.label","Register Newborn for AE"},//Added by Dharma on July 25th against ML-MMOH-CRF-0631 [IN:062148]
		{"eAE.InvokeRegisterNewBorn.label","Invoke Register Newborn for AE"},//Added by Dharma on July 25th against ML-MMOH-CRF-0631 [IN:062148]
		{"eAE.AllowbackdatingConsDateTime.label","Allow back Date/Time of Start Consultation"},//Added by Thamizh selvi on 13th Oct 2017 for ML-MMOH-CRF-0623
		{"eAE.InvokeRecallForAE.label","Invoke Recall option for AE"},//Added by Ashwini on 18-Dec-2017 for ML-MMOH-CRF-0657
		{"eAE.ToComeAgain.label","TCA"},//Added by Ashwini on 18-Dec-2017 for ML-MMOH-CRF-0657
		{"eAE.LinkDelink.label","Link/Delink"},//Added by Ashwini on 18-Dec-2017 for ML-MMOH-CRF-0657
		{"eAE.GroupbyTreatmentarea.label","Group by Treatment Area"}, //Added by Mano against ML-MMOH-CRF-0822
		{"eAE.OandG.label","O&G"}, //Added by Thamizh selvi on 8th Mar 2018 against ML-MMOH-CRF-0645
		{"eAE.MechOfMainInj.label","Mechanism of Main Injury"}, //Added by Thamizh selvi on 29th Mar 2018 against ML-MMOH-CRF-0649
		{"eAE.WaitingTimeExceeds.label","Waiting Time Exceeds"},
		{"eAE.WaitingTimeColorIndicator.label","Waiting Time Color Indicator"},
		{"eAE.CBD.label","CBD"},//Added by Thamizh selvi on 11th Apr 2018 against ML-MMOH-CRF-0651
		/*Added By Dharma on 1st Oct 2018 against GHL-CRF-0517 [IN:067155] Start*/
		{"eAE.ChkForPendingOrdersBeforeAECheckout.label","Check for Pending Orders before AE Checkout"},
		{"eAE.DonotallowAECheckout.label","Do not allow AE Checkout"},
		// Added by Lakshmanan For ML-MMOH-CRF-1973 on 01-07-2023 start
		{"eAE.AppearAsTab.label","Appear As Tab"},
		{"eAE.TabColour.label","Tab Colour"},		
		{"eAE.Purple.label","Purple"}, 
		{"eAE.Brown.label","Brown"}, 
		{"eAE.Blue.label","Blue"}, 
		{"eAE.Darkblue.label","Dark blue"}, 
		{"eAE.Magenta.label","Magenta"}, 
		{"eAE.Pink.label","Pink"}, 
		{"eAE.Cyan.label","Cyan"}, 
		{"eAE.Grey.label","Grey"},  
		// Added by Lakshmanan For ML-MMOH-CRF-1973 on 01-07-2023 end
		{"eAE.AllowAECheckout.label","Allow AE Checkout"},
		/*Added By Dharma on 1st Oct 2018 against GHL-CRF-0517 [IN:067155] End*/
		{"eAE.ValidateNatIDRegAttn.label","Validate existence of National ID during Register Attendance"},//Added by Ashwini on 06-Mar-2019 for MO-CRF-20148
		{"eAE.AERegistrationTypeAutoUpdate.label","AE Registration Type Auto Update"}, // Added by mujafar for KDAH-CRF-0526
		{"eAE.ReconfirmCOT.label","Reconfirm Case of Trauma"},//Added by Ashwini on 18-Jan-2021 for ML-MMOH-CRF-1409
		{"eAE.EnableEmiratesID.label","Enable Emirates ID"},//Added by Ashwin K for AAKH-CRF-0150
		{"eAE.Visit.label","Visit"},//Added by Arthi on 18-Nov-2022 against ML-MMOH-CRF-1978
		{"eAE.ForAdmission.label","For Admission"},//<!--Added by Himanshu Saxena on 14-Jun-2023 for ML-MMOH-CRF-1972 Starts-->
		{"eAE.EnableForAdmission.label","Enable for Admission Tab"},//<!--Added by Himanshu Saxena on 14-Jun-2023 for ML-MMOH-CRF-1972 Starts-->
		{"eAE.ModifyReferral.label","Modify Referral"},//<!--Added by Himanshu Saxena on 14-Jun-2023 for ML-MMOH-CRF-1972 Starts-->
		{"eAE.WaitingForAdmission.label","Waiting for Admission"},//<!--Added by Himanshu Saxena on 14-Jun-2023 for ML-MMOH-CRF-1972 Starts-->
		{"eAE.CaseType.label","Case Type"},//Added by Ajay Hatwate on 02-Jan-2024 for ML-MMOH-CRF-1653
		{"eAE.AutoTickMlc.label","Auto Tick MLC"},//Added by Ajay Hatwate on 17-Jan-2024 for ML-MMOH-CRF-2103
		{"eAE.DoNotAutoTickMlc.label","Do Not Auto Tick MLC"},//Added by Ajay Hatwate on 17-Jan-2024 for ML-MMOH-CRF-2103
		{"eAE.IfOsccIsTicked.label","If OSCC Case Is Ticked"},//Added by Ajay Hatwate on 17-Jan-2024 for ML-MMOH-CRF-2103
		{"eAE.QueueNumInSecTriage.label","Queue Number in Secondary Triage"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.EnterQueueNumInSecTriage.label","Enter Queue Number in Secondary Triage"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.DispQueueNumInCEPatient.label","Display Queue Number in Current Emergency Patients"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.AppPriorityZone.label","Applicable Priority Zone"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.DispQueueNumInAECheckOut.label","Display Queue Number in AE Check Out"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.QueueNumInMandatory.label","Queue Number Mandatory"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.MaxNumOfDigitsAllowedQueueNum.label","Maximum Number of Digits allowed for Queue Number"},//Added by Santhosh for ML-MMOH-CRF-2069
		{"eAE.UnbilledChargesIPEncoExistsAEChkOut.label","Unbilled Charges & IP Encounter Exists during AE Check Out"},//GHL-CRF-0517.4  added by Krishna Pranay
		{"eAE.TransferUnbilledCharges.label","Transfer Unbilled Charges"},//Added by Gunasekar on 19-Aug-2024 for GHL-CRF-0517.4
{"eAE.ViewMenstrualHistoryDetails.label","View Menstrual History Details"}//68508
	}; 
	 
}
