/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eSM.MenuHeader.MenuHeaderManager
package eSM.MenuHeader;

/**
 * Remote interface for MenuHeader
 */
public interface MenuHeaderRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap insertMenuHeader(java.util.HashMap argMap) throws java.rmi.RemoteException;
    java.util.HashMap updateMenuHeader(java.util.HashMap argMap) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
