/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eFM.FMLostFoundFile.LostFoundFileManager
package eFM.FMLostFoundFile;

/**
 * Remote interface for FMLostFoundFile
 */
public interface LostFoundFileRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap insertLostFoundFile(java.util.Properties p, java.util.Properties prop, java.util.HashMap htRecord) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
