/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eAM.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
{"eAM.AccountingDepartmentCostCenter.label","قسم المحاسبة / مركز التكلفة"},
{"eAM.AcctDeptforRoom.label","قسم المحاسبة للغرفة"},
{"eAM.AddModifyRange.label","إضافة / تعديل النطاق"},
{"eAM.AdminFacilityID.label","معرف منشأة الإدارة"},
{"eAM.AdmitPatientwithBed.label","أدخل المريض مع السرير"},
{"eAM.AllowChangingNursingUnitinAssignBed.label","السماح بتغيير وحدة التمريض في السرير المخصص"},
{"eAM.AllowDirectordersfor.label","السماح بالأوامر المباشرة لـ"},
{"eAM.AllowForcedinAppointment.label","السماح بالتعيين الإجباري"},
{"eAM.AllowGlobalBooking.label","السماح للحجز العالمي"},
{"eAM.AnatomicalSiteCode.label","كود الموقع التشريحي"},
{"eAM.Ancillary.label","المساعد الإضافي"},
{"eAM.AncillaryMedicalService.label","الخدمة الطبية المساعدة"},
{"eAM.APCNo.label","رقم APC"},
{"eAM.ApplicableCategoriesAll.label","الفئات القابلة للتطبيق جميع"},
{"eAM.ApplicableForInpatients.label","ينطبق على المرضى الداخليين"},
{"eAM.ApplicableForOutpatients.label","ينطبق على العيادات الخارجية"},
{"eAM.ApplicableForOutpatientsInpatients.label","ينطبق على العيادات الخارجية / المرضى الداخليين"},
{"eAM.ApplicablePeriodFrom.label","الفترة المطبقة من"},
{"eAM.ApplicabletoISS.label","ينطبق على ISS"},
{"eAM.ApplUserID.label","معرف مستخدم الجهاز"},
{"eAM.AppointmentScheduling.label","جدولة المواعيد"},
{"eAM.ArrivalCode.label","كود الوصول"},
{"eAM.AssignUnassigned.label","تعيين غير معين"},
{"eAM.AssignUnassignedPatient.label","تعيين المريض غير المعين"},
{"eAM.AssociatedEnterpriseFacilityforReferral.label","مرفق المؤسسة المرتبطة للإحالة"},
{"eAM.AssociatedPanelElements.label","عناصر اللوحة المرتبطة"},
{"eAM.AssociateScore.label","نقاط المنتسب"},
{"eAM.AvailableClasses.label","الفئات المتوفرة"},
{"eAM.AvailableEquipment.label","المعدات المتاحة"},
{"eAM.BackdatedAdmission.label","القبول بأثر رجعي"},
{"eAM.BatteryID.label","معرف البطارية"},
{"eAM.BedClasschange.label","تغيير فئة السرير"},
{"eAM.BedMaintenance.label","صيانة السرير"},
{"eAM.BlockSchedule.label","جدول الحظر"},
{"eAM.BookAppointmentwithoutPatientID.label","حجز موعد بدون هوية المريض"},
{"eAM.BuildinginFacility.label","بناء في منشأة"},
{"eAM.ByLocationType.label","حسب نوع الموقع"},
{"eAM.ByPerson.label","من قبل شخص"},
{"eAM.CancelTransferOut.label","إلغاء التحويل للخارج"},
{"eAM.CancelVisit.label","إلغاء الزيارة"},
{"eAM.CareLocationCode.label","رمز موقع الرعاية"},
{"eAM.CareLocationType.label","نوع موقع الرعاية"},
{"eAM.ChartSection.label","قسم الرسم البياني"},
{"eAM.CheckInCheckOutLodger.label","تحقق في / تحقق من لودجر"},
{"eAM.CheckoutPatient.label","تحقق من المريض"},
{"eAM.ClickonanyotherColumnnumbertoreposition.label","انقر فوق أي رقم عمود آخر لتغيير موضعه"},
{"eAM.Closest.label","الأقرب"},
{"eAM.ComplaintCode.label","كود الشكوى"},
{"eAM.ConditionalCode.label","كود شرطي"},
{"eAM.ConfirmonCreatebooking.label","قم بالتأكيد عند إنشاء الحجز"},
{"eAM.ConfirmRequest.label","تأكيد الطلب"},
{"eAM.ContactPersonDetails.label","تفاصيل جهة الاتصال"},
{"eAM.ContactReasonCode.label","رمز سبب الاتصال"},
{"eAM.CriticalCare.label","عناية حرجة"},
{"eAM.CurrentlySelectedComponentismarkforrepositioning.label","المكون المحدد حاليًا هو علامة لإعادة تحديد الموضع."},
{"eAM.CurrentTime.label","الوقت الحالي"},
{"eAM.Dec.label","ديسمبر"},
{"eAM.DeceasedIndicator.label","مؤشر المتوفى"},
{"eAM.DefineGrid.label","تعريف الشبكة"},
{"eAM.DefineMatrix.label","تحديد المصفوفة"},
{"eAM.Definition.label","تعريف"},
{"eAM.DemoCall.label","دعوة تجريبية"},
{"eAM.Dischargechecklist.label","قائمة مراجعة التفريغ"},
{"eAM.Discrete.label","منفصلة"},
{"eAM.DiscreteID.label","معرف منفصل"},
{"eAM.DiscretePanel.label","لوحة منفصلة"},
{"eAM.DocumentTypeDetails.label","تفاصيل نوع المستند"},
{"eAM.DonorPrefixforidentifyingSource.label","بادئة المانح لتحديد المصدر"},
{"eAM.ElectroCardiogram.label","تخطيط القلب الكهربي"},
{"eAM.ElectroEncephelogram.label","الرسم الكهربائي"},
{"eAM.EmployerStatus.label","حالة صاحب العمل"},
{"eAM.EncounterNumberingControl.label","مواجهة التحكم في الترقيم"},
{"eAM.EquipmentOtherResource.label","معدات الموارد الأخرى"},
{"eAM.EquipmentOtherResourceTypes.label","المعدات أنواع الموارد الأخرى"},
{"eAM.EquivalentUnitofMeasure.label","وحدة القياس المكافئة"},
{"eAM.EscortType.label","نوع المرافقة"},
{"eAM.EveryFrequencyType.label","كل نوع تردد"},
{"eAM.ExamProcedureUnit.label","وحدة الاختبارات / الإجراءات"},
{"eAM.ExistingRange.label","النطاق الحالي"},
{"eAM.ExternalPractitionerforReferralSource.label","ممارس خارجي لمصدر الإحالة"},
{"eAM.ExternalReferral.label","الإحالة الخارجية"},
{"eAM.ExternalReferralSource.label","مصدر خارجي / إحالة"},
{"eAM.FacilityforAcctDept.label","مرفق لقسم الحساب"},
{"eAM.FileRelated.label","ملف ذات صلة"},
{"eAM.FloorDescription.label","وصف الطابق"},
{"eAM.FloorinFacility.label","الطابق في مرفق"},
{"eAM.FollowupofReferral.label","متابعة الإحالة"},
{"eAM.formatBlock.label","تنسيق الكتلة"},
{"eAM.ForText.label","للنص"},
{"eAM.FreeDocumentation.label","التوثيق المجاني"},
{"eAM.FreeText.label","نص مجاني"},
{"eAM.FreeTextTemplate.label","قالب نص مجاني"},
{"eAM.FrequencySchedule.label","جدول التردد"},
{"eAM.FromHealthCareSettingType.label","من نوع إعداد الرعاية الصحية"},
{"eAM.FromHlthcare.label","من الرعاية الصحية"},
{"eAM.FromHours.label","من ساعات"},
{"eAM.FromMins.label","من دقيقة"},
{"eAM.GovernmentEmployees.label","موظفين حكوميين"},
{"eAM.HD.label","عالية الدقة"},
{"eAM.HealthCareSettingTypeRestrictions.label","قيود نوع إعداد الرعاية الصحية"},
{"eAM.HistoryTypeDirectRecording.label","نوع التاريخ (تسجيل مباشر)"},
{"eAM.Hour.label","ساعة"},
{"eAM.InfusionPump.label","مضخة التصريف"},
{"eAM.InLocalLanguage.label","في اللغة المحلية"},
{"eAM.InpatientManagement.label","إدارة المرضى الداخليين"},
{"eAM.InpatientReferral.label","الإحالة للمرضى الداخليين"},
{"eAM.InstructionID.label","معرف التعليمات"},
{"eAM.IntensiveCare.label","عناية مركزة"},
{"eAM.Interval.label","فترة"},
{"eAM.IntervalDura.label","مدة الفاصل"},
{"eAM.IntervalDuraType.label","نوع مدة الفاصل الزمني"},
{"eAM.IntervalFrequencyValue.label","قيمة التردد الفاصل"},
{"eAM.IPReferral.label","الإحالة للمرضى الداخليين"},
{"eAM.IVPump.label","مضخة IV"},
{"eAM.LiftBlockonSchedule.label","رفع كتلة في الجدول الزمني"},
{"eAM.LinkStandardValue.label","ربط القيمة القياسية"},
{"eAM.LocationforOperatorStation.label","موقع محطة المشغل"},
{"eAM.ManufacturerStatus.label","حالة الشركة المصنعة"},
{"eAM.MaximumAge.label","الحد الأقصى للسن"},
{"eAM.MeasureID.label","معرّف القياس"},
{"eAM.MinValue.label","قيمة الحد الأدنى"},
{"eAM.MnemonicforShiftID.label","ذاكري لمعرف التحول"},
{"eAM.MnemonicKey.label","مفتاح ذاكري"},
{"eAM.MotorVehicleAccidentFund.label","صندوق حوادث السيارات"},
{"eAM.NationalIDNo.label","رقم الهوية الوطني"},
{"eAM.NextNumber.label","الرقم التالي"},
{"eAM.NextReferralNumber.label","رقم الإحالة التالي"},
{"eAM.NoofBeds.label","عدد الأسرة"},
{"eAM.NoofRanges.label","عدد النطاقات"},
{"eAM.NotesTemplate.label","قالب الملاحظات"},
{"eAM.NumericDetails.label","تفاصيل رقمية"},
{"eAM.NumericMapDigits.label","أرقام الخريطة الرقمية"},
{"eAM.NumericValue.label","قيمة عددية"},
{"eAM.NWD.label","NWD"},
{"eAM.OnCall.label","في مكالمة"},
{"eAM.OneTime.label","مره واحده"},
{"eAM.OperationTheatreAll.label","مسرح العمليات (الكل)"},
{"eAM.OperationTheatrespec.label","مسرح العمليات (المواصفات)"},
{"eAM.OperatorStationDescription.label","وصف محطة المشغل"},
{"eAM.OperatorStationID.label","معرف محطة المشغل"},
{"eAM.OperatorStationRestriction.label","قيود محطة المشغل"},
{"eAM.OperatorStationType.label","نوع محطة المشغل"},
{"eAM.OPReferral.label","الإحالة إلى العيادات الخارجية"},
{"eAM.OtherStaffForFacility.label","موظفين آخرين للمنشأة"},
{"eAM.OtherStaffID.label","معرف الموظف الآخر"},
{"eAM.OutpatientManagement.label","إدارة العيادات الخارجية"},
{"eAM.OutpatientReferral.label","الإحالة إلى العيادات الخارجية"},
{"eAM.OverbookAppointment.label","حجز موعد إضافي"},
{"eAM.OverrideAllocationRuleforBookAppointment.label","تجاوز قاعدة التخصيص لموعد الكتاب"},
{"eAM.OverrideAllocationRuleforTransferAppointment.label","تجاوز قاعدة التخصيص لتعيين النقل"},
{"eAM.Oxygen.label","الأكسجين"},
{"eAM.Pager.label","بيجر"},
{"eAM.PatientCarePanel.label","لوحة رعاية المريض"},
{"eAM.PatientClassDesc.label","وصف فئة المريض"},
{"eAM.PatientMovementTracking.label","تتبع حركة المريض"},
{"eAM.PatientPrefixforidentifyingSource.label","بادئة المريض لتحديد المصدر"},
{"eAM.PatientRelated.label","ذات صلة بالمريض"},
{"eAM.PatientTypeClass.label","فئة نوع المريض"},
{"eAM.PersonName.label","اسم الشخص"},
{"eAM.PractitionerforFacility.label","ممارس للمنشأة"},
{"eAM.PractitionerforTeam.label","ممارس للفريق"},
{"eAM.PractitionrerName.label","اسم الممارس"},
{"eAM.Precision.label","دقة"},
{"eAM.PrefMode.label","الوضع المفضل"},
{"eAM.PrivacyLevel.label","مستوى الخصوصية"},
{"eAM.Productive.label","إنتاجي"},
{"eAM.ProfessionalQualification.label","المؤهلات المهنية"},
{"eAM.ProgramID.label","معرف البرنامج"},
{"eAM.ProgramName.label","إسم البرنامج"},
{"eAM.ProgramType.label","نوع البرنامج"},
{"eAM.QuarterHour.label","ربع ساعة"},
{"eAM.RangeID.label","معرف النطاق"},
{"eAM.Ranges.label","نطاقات"},
{"eAM.RangeType.label","نوع النطاق"},
{"eAM.ReasonforDepart.label","سبب المغادرة"},
{"eAM.ReasonforRecall.label","سبب الاستدعاء"},
{"eAM.RecordAmendLeave.label","تسجيل / تعديل الإجازة"},
{"eAM.RecordingChart.label","مخطط التسجيل"},
{"eAM.RecordingVital.label","تسجيل أمر حيوي"},
{"eAM.ReferenceRanges.label","النطاقات المرجعية"},
{"eAM.ReferenceRangesNumericDetails.label","النطاقات المرجعية - تفاصيل رقمية"},
{"eAM.ReferralIDNumbering.label","ترقيم معرف الإحالة"},
{"eAM.ReferralManagement.label","إدارة الإحالة"},
{"eAM.RegisterNewbornforIP.label","تسجيل حديثي الولادة للمريض الداخلي"},
{"eAM.RegisterPatientFromAdmitPatient.label","تسجيل المريض من دخول المريض"},
{"eAM.RegisterPatientfromRegisterVisit.label","تسجيل المريض من تسجيل الزيارة"},
{"eAM.RegisterReferral.label","سجل الإحالة"},
{"eAM.RegisterWalkIn.label","تسجيل دخول مباشر"},
{"eAM.ReimbursementType.label","نوع السداد"},
{"eAM.RejectionofReferral.label","رفض الإحالة"},
{"eAM.ReleaseBedBay.label","حرر السرير / الخليج"},
{"eAM.RepeatFrequencyType.label","كرر نوع التردد"},
{"eAM.RepeatFrequencyValue.label","كرر قيمة التردد"},
{"eAM.RepeatsPer.label","كرر (ق) لكل"},
{"eAM.RepFacility.label","مرفق مندوب"},
{"eAM.RepFacilityID.label","معرف منشأة مندوب"},
{"eAM.ReportFacility.label","مرفق التقرير"},
{"eAM.ReserveBedBay.label","سرير احتياطي / خليج"},
{"eAM.ResidentStay.label","إقامة المقيم"},
{"eAM.ResourceDescription.label","وصف المورد"},
{"eAM.ResourceNarration.label","سرد الموارد"},
{"eAM.ResourceTypecode.label","رمز نوع المورد"},
{"eAM.ResourceTypeDescription.label","وصف نوع المورد"},
{"eAM.ResultTemplateID.label","معرف قالب النتيجة"},
{"eAM.RoundTo.label","جولة إلى"},
{"eAM.Scheduled.label","المقرر"},
{"eAM.Seconds.label","ثواني"},
{"eAM.SectioninFacility.label","قسم في المنشأة"},
{"eAM.SelectedClasses.label","فئات مختارة"},
{"eAM.SeriesforDonorNumbering.label","سلسلة ترقيم المانحين"},
{"eAM.SeriesforExtPatNumbering.label","سلسلة ترقيم المرضى الخارجيين"},
{"eAM.ServiceinFacility.label","الخدمة في المنشأة"},
{"eAM.SetgCode.label","رمز الإعداد"},
{"eAM.ShiftforLocationType.label","التحول لنوع الموقع"},
{"eAM.ShiftforPosition.label","التحول للوظيفة"},
{"eAM.ShiftID.label","معرف التحول"},
{"eAM.ShiftMnemonic.label","التحول ذاكري"},
{"eAM.ShiftTimings.label","توقيت التحول"},
{"eAM.ShowFacilities.label","عرض المرافق"},
{"eAM.SpecialtyforCatalog.label","التخصص في الكتالوج"},
{"eAM.SpecialtyforExternalReferralSource.label","تخصص لمصدر الإحالة الخارجية"},
{"eAM.SpecimenRelated.label","العينة ذات الصلة"},
{"eAM.StandardComp.label","التركيب القياسي"},
{"eAM.StandardValueRef.label","المرجع القيمة القياسية"},
{"eAM.StandardValueReference.label","مرجع القيمة القياسية"},
{"eAM.StartTimeAssignment.label","تعيين وقت البدء"},
{"eAM.StatID.label","معرف الحالة"},
{"eAM.StatisticsGroupDetail.label","تفاصيل مجموعة الإحصائيات"},
{"eAM.StatisticsGroupforProgram.label","مجموعة الإحصاء للبرنامج"},
{"eAM.StatisticsGroupID.label","معرف مجموعة الإحصائيات"},
{"eAM.StudyLocation.label","موقع الدراسة"},
{"eAM.SubServiceCode.label","كود الخدمة الفرعية"},
{"eAM.SubServiceinFacility.label","الخدمة الفرعية في المنشأة"},
{"eAM.Suction.label","مص"},
{"eAM.SwapBed.label","سرير مبادلة"},
{"eAM.Team.label","فريق"},
{"eAM.TelephoneNumber.label","رقم هاتف"},
{"eAM.Temporary.label","مؤقت"},
{"eAM.TestObservID.label","اختبار معرف مراقبة"},
{"eAM.TimeRoundedto.label","تقريب الوقت إلى"},
{"eAM.TissueCollection.label","جمع الأنسجة"},
{"eAM.ToHealthCareSettingType.label","إلى نوع إعداد الرعاية الصحية"},
{"eAM.ToHlthcare.label","للرعاية الصحية"},
{"eAM.ToHours.label","إلى ساعات"},
{"eAM.ToMins.label","إلى دقيقة"},
{"eAM.TransferIn.label","نقل في"},
{"eAM.UsablebyRadiationImplantPatients.label","يمكن استخدامها من قبل مرضى الزرع الإشعاعي"},
{"eAM.UseasExternalReferralDestinationat.label","استخدم كوجهة خارجية / إحالة في"},
{"eAM.UseasExternalReferralSourceat.label","استخدم كمصدر خارجي / إحالة في"},
{"eAM.UseasExternalReferralSourcefordirectordering.label","استخدم كمصدر خارجي / مرجعي للطلب المباشر"},
{"eAM.UseasExternalReferralSourceforTissueCollection.label","استخدم كمصدر خارجي / مرجعي لجمع الأنسجة"},
{"eAM.UseasReferralDestinationat.label","استخدم كوجهة إحالة في"},
{"eAM.UseasReferralSourceat.label","استخدم كمصدر للإحالة في"},
{"eAM.UseatDischarge.label","استخدم في التفريغ"},
{"eAM.UseatVisitConclusion.label","استخدم في زيارة الخاتمة"},
{"eAM.UseforMaternalDeath.label","استخدام لوفاة الأمهات"},
{"eAM.UserforOperatorStation.label","مستخدم لمحطة المشغل"},
{"eAM.Ventilator.label","التنفس الصناعي"},
{"eAM.VisitAnalysisCode.label","زيارة كود التحليل"},
{"eAM.VisitConclusion.label","زيارة الخاتمة"},
{"eAM.VisitingSpecialist.label","أخصائي زائر"},
{"eAM.VistingSpecialist.label","اخصائي زيارة الموقع"},
{"eAM.WD.label","WD"},
{"eAM.WebSite.label","موقع الكتروني"},
{"eAM.WorkmenCompensationFund.label","صندوق تعويض العمال"},
{"eAM.WorkStationNo.label","رقم محطة العمل"},
{"eAM.10thminute.label","الدقيقة العاشرة"},
{"eAM.5thminute.label","الدقيقة الخامسة"},
{"eAM.Hourly.label","ساعيا"},
{"eAM.NumberofBedsAllowed.label","عدد الأسرة المسموح بها"},
{"eAM.AddNewPanelElement.label","إضافة عنصر لوحة جديد"},
{"eAM.ModifyExisitingPanelElement.label","تعديل الخروج من عنصر اللوحة"},
{"eAM.Unscheduled.label","غير مجدول"},
{"eAM.SpecialtyForModule.label","تخصص للوحدة"},
{"eAM.SpecialityModule.Label","وحدة التخصص"},
{"eAM.AssociatedSpecialities.Label","تخصص مشارك"},
{"eAM.SequenceNumber.label","رقم التسلسل"},
{"eAM.ChangeAdmDtls.label","تغيير تفاصيل القبول"},
{"eAM.RowColumnHeader.label","رأس الصف / العمود"},
{"eAM.InstructionDescript.label","وصف التعليمات"},
{"eAM.PatInstructions.label","تعليمات المريض"},
{"eAM.Repeat.label","يكرر"},
{"eAM.DiscreteTypeIndicator.label","مؤشر نوع منفصل"},
{"eAM.EveryFrequencyValue.label","كل قيمة تردد"},
{"eAM.EveryIntervalValue.label","كل قيمة فترة"},
{"eAM.EveryIntervalType.label","كل نوع فترة"},
{"eAM.LateDischarge.label","التفريغ المتأخر"},
{"eAM.Multispeciality.label","متعدد التخصصات"},
{"eAM.AbscondedIndicator.label","مؤشر غائب"},
{"eAM.CancelTransferIn.label","إلغاء التحويل"},
{"eAM.Transfer.label","تحويل"},
{"eAM.TfrPatientOut.label","نقل المريض إلى الخارج"},
{"eAM.Cycle.label","دورة"},
{"eAM.MaxCycle.label","العدد الأقصى للدورة"},
{"eAM.ApplicableForMedicalReport.label","ينطبق على التقرير الطبي"},
{"eAM.CallNotAroundIndicator.label","مؤشر ليس حول المكالمة"},
{"eAM.MMCNO.label","رقم MMC"},
{"eAM.EnableCDRIcon.label","تفعيل رمز CDR"},
{"eAM.FacilityAccess.label","مع إمكانية الوصول إلى جميع المرافق"},
{"eAM.WithRepFacility.label","مع مرفق التقارير"},
{"eAM.EmployeeServiceNumber.label","رقم خدمة الموظف"},  // Added by lakshmanan For MO-CRF-20183.2 US001
{"eAM.MasterPatientIndex.label","بطاقة فهرسة المريض"}, // Added by lakshmanan for ML-MMOH-CRF-1955
{"eAM.ReasontoMarkMLC.label","سبب تحديد MLC"}, // Added by lakshmanan for ML-MMOH-CRF-1955
{"eAM.ReasontoMarkNonMLC.label","سبب وضع علامة على عدم وجود MLC"},  // Added by lakshmanan for ML-MMOH-CRF-1955
{"eAM.EmployeeServiceNumber.label","رقم خدمة الموظف"},
{"eAM.Supervisor.label","المشرف"},
{"eAM.ReasonForBiometricRejection.label","سبب الرفض البيومتري"} //<!--Added by Himanshu Saxena on 30-Jun-2023 for AAKH-CRF-0175-->

			}; 
}
