/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eCP.resources;

import java.util.*;

public class Labels extends ListResourceBundle
{
	public Object[][] getContents() 
	{
         return contents;
    }

	static final Object[][] contents = 
	{
		
		{"eCP.AssociatedMeasures.label","Associated Measures"},
		{"eCP.Associate.label","Associate"},
		{"eCP.Associated.label","Associated"},
		{"eCP.Alt.label","Alt"},
		{"eCP.AssociateTermCode.label","Associate Term Code"},
		{"eCP.AssessmentCategoryCode.label","Assessment Category Code"},
		{"eCP.AssessmentCriteria.label","Assessment Criteria"},
		{"eCP.AssessmentCategory.label","Assessment Category"},
		{"eCP.AssessmentCategoryDescription.label","Assessment Category Description"},
		{"eCP.AssessmentNoteDescription.label","Assessment Note Description"},
		{"eCP.AssessmentNote.label","Assessment Note"},
		{"eCP.AssessmentNoteId.label","Assessment Note Id"},
		{"eCP.AssessmentCriteriaScoresQueryResult.label","AssessmentCriteriaScoresQueryResult"},
		{"eCP.Abnormal25.label","Abnormal 2-5"},
		{"eCP.AssessBasedDepClassification.label","AssessBasedDepClassification"},
		{"eCP.AccuracyforCarePlan.label","Accuracy for Care Plan"},
		{"eCP.Atleast1InterventionOutcomeexist.label","Atleast 1 Intervention/Outcome must exist in a Group"},
		{"eCP.Atleast1InterventionOutcomeassociated.label","Atleast 1 Intervention/Outcome Group must be associated"},
		{"eCP.Atleast1Goalassociated.label","Atleast 1 Goal must be associated"},
		{"eCP.Atleast1Terminologyassociated.label","Atleast 1 Terminology code must be associated"},
		{"eCP.AssessmentBasedDependencyClassification.label","Assessment Based Dependency Classification"},
		{"eCP.AssessmentBasedTerminologyCode.label","Assessment Based Terminology Code"},
		{"eCP.AssessmentCriteriaScore.label","Assessment Criteria Score"},
		{"eCP.AssessmentCategoryforAssessmentNote.label","Assessment Category for Assessment Note"},
		{"eCP.AgeGroupforAssessmentNote.label","Age Group for Assessment Note"},
		{"eCP.BuildLibrary.label","Build Library"},
		{"eCP.CaseTypeNature.label","Case Type Nature"},
		{"eCP.CaseTypeCode.label","Case Type Code"},
		{"eCP.CaseTypeDescription.label","Case Type Description"},
		{"eCP.CaseType.label","Case Type"},
		{"eCP.CutOffScore.label","Cut Off Score"},
		{"eCP.CategoryCode.label","Catg. Code"},
		{"eCP.CategoryDescription.label","Catg. Description"},
		{"eCP.CriticallyAbnormal69.label","Critically Abnormal 6-9"},
		{"eCP.CriteriaDescription.label","CriteriaDescription"},
		{"eCP.ClassificationLevel.label","Classification Level"},
		{"eCP.CarePlanScope.label","Care Plan Scope"},
		{"eCP.CarePlanAdminSetup.label","Care Plan Admin Setup"},
		{"eCP.CriteriaforAssessmentCategory.label","Criteria for Assessment Category"},		
		{"eCP.CarePlanSetup.label","Care Plan Setup"},
		{"eCP.Draft.label","Draft"},	
		{"eCP.Dep.label","Dep"},			
		{"eCP.DependencyCode.label","Dependency Code"},
		{"eCP.DependencyDescription.label","Dependency Description"},	
		{"eCP.DiscreteMeasureforDependency.label","Discrete Measure for Dependency"},
		{"eCP.DiscreteMeasures.label","Discrete Measures"},			
		{"eCP.ExpectedOutcome.label","Expected Outcome"},
		{"eCP.FindStage.label","Find Stage"},
		{"eCP.FindTerminologySetForFacility.label","Find Terminology Set For Facility"},
		{"eCP.FindCaseType.label","Find Case Type"},
		{"eCP.FindAssessmentCategory.label","Find Assessment Category"},		
		{"eCP.FindAgeGroupForAssessNote.label","Find Practitioner Type For Assessment Note"},
		{"eCP.FindService.label","Find Service"},
		{"eCP.FindReason.label","Find Reason"},
		{"eCP.FindLevelofCareForDependency.label","Find Level of Care For Dependency"},
		{"eCP.FindSpecialtyForAssessmentNote.label","Find Specialty For Assessment Note"},
		{"eCP.FindDependency.label","Find Dependency"},
		{"eCP.Guideline.label","Guideline"},
		{"eCP.Guidelines.label","Guidelines"},
		{"eCP.Goal.label","Goal"},		
		{"eCP.GoalDescription.label","Goal Description"},
		{"eCP.GoalDefinitionLevel.label","Goal Definition Level"},		
		{"eCP.InterventionsOutcomes.label","Interventions/Outcomes"},
		{"eCP.Interventions.label","Interventions"},
		{"eCP.Intervention.label","Intervention"},
		{"eCP.InterventionDescription.label","Intervention Description"},
		{"eCP.lllness.label","lllness"},
		{"eCP.LibraryBasis.label","Library Basis"},
		{"eCP.LibraryDetails.label","Library Details"},
		{"eCP.LibraryID.label","Library ID"},
		{"eCP.LibraryDescription.label","Library Description"},
		{"eCP.Library.label","Library"},
		{"eCP.LOOKUP.label","LOOKUP"},
		{"eCP.LibrarySearch.label","Library Search"},
		{"eCP.LibraryforCaseType.label","Library for Case Type"},		
		{"eCP.Months.label","Month(s)"},
		{"eCP.MinScore.label","Min Score"},
		{"eCP.MaxScore.label","Max Score"},
		{"eCP.MedicationAdministrationTasks.label","Medication Administration Tasks"},
		{"eCP.NoteID.label","Note ID"},		
		{"eCP.NotApplicable0.label","Not Applicable 0"},
		{"eCP.Normal1.label","Normal 1"},		
		{"eCP.OutcomeDescription.label","Outcome Description"},
		{"eCP.Outcomes.label","Outcomes"},
		{"eCP.OutcomeIndicator.label","Outcome Indicator"},
		{"eCP.OutcomeCode.label","Outcome Code"},
		{"eCP.OutcomeEvaluationMeasures.label","Outcome Evaluation Measures"},		
		{"eCP.PreAdmit.label","Pre-Admit"},
		{"eCP.PostAdmit.label","Post-Admit"},
		{"eCP.PostDischarge.label","Post-Discharge"},
		{"eCP.PatientClassApplicable.label","Patient Class Applicable"},						
		{"eCP.PractTypeforAssessmentNote.label","Pract Type for Assessment Note"},				
		{"eCP.PatientClassforStage.label","Patient Class for Stage"},
		{"eCP.RelativeStart.label","Relative Start"},	
		{"eCP.ReassessmentInterval.label","Reassessment Interval"},
		{"eCP.ReassessmentUnit.label","Reassessment Unit"},		
		{"eCP.StageDescription.label","Stage Description"},
		{"eCP.StageIndicator.label","Stage Indicator"},
		{"eCP.SexSpecific.label","Sex Specific"},
		{"eCP.SubSection.label","Sub-Section"},		
		{"eCP.SpecialtyForAssessmentNote.label","Specialty For Assessment Note"},				
		{"eCP.TargetPeriod.label","Target Period"},
		{"eCP.TaskforMedicationAdministration.label","Task for Medication Administration"},
		{"eCP.TerminologySetType.label","Terminology Set Type"},
		{"eCP.TerminologyCodeSearch.label","Terminology Code Search"},
		{"eCP.TerminologyCodeEvaluationMeasures.label","Terminology Code Evaluation Measures"},
		{"eCP.TerminologyCodeforCaseType.label","Terminology Code for Case Type"},			
		{"eCP.VersionDetails.label","Version Details"},
		{"eCP.VersionRemarks.label","Version Remarks"},
		{"eCP.VersionNo.label","Version No."},
		{"eCP.VarianceCauseCode.label","Variance Cause Code"},
		{"eCP.VarianceCause.label","Variance Cause"},
		{"eCP.VarianceCauseDescription.label","Variance Cause Description"},
		{"eCP.VarianceCode.label","Variance Code"},
		{"eCP.VarianceDescription.label","Variance Description"},
		{"eCP.VarianceReasonCode.label","Variance Reason Code"},
		{"eCP.VarianceReasonDescription.label","Variance Reason Description"},
		{"eCP.Version.label","Version"},
		{"eCP.VarianceReason.label","Variance Reason"},
		{"eCP.Weeks.label","Week(s)"},								
		{"eCP.AssignNewCarePlanManager.label","Assign New Care Plan Manager"},
		{"eCP.Achieved.label","Achieved"},
		{"eCP.ActionPlan.label","Action Plan"},
		{"eCP.AdhocIntervention.label","Ad hoc Intervention"},		
		{"eCP.ActivePlans.label","Active Plans"},
		{"eCP.AllPlans.label","All Plans"},
		{"eCP.AssessmentDetailat.label","Assessment Detail at "},
		{"eCP.AddNew.label","Add New"},
		{"eCP.AddInterventions.label","Add Interventions"},
		{"eCP.AsEvidencedByFactors.label","As Evidenced By: Factors:"},
		{"eCP.BackdatingLimit.label","Backdating limit"},
		{"eCP.BackdateLimitForResultingOfTasks.label","Backdate limit for resulting of tasks"},
		{"eCP.CareManager.label","Care Manager"},		
		{"eCP.CarePlanStartDate.label","CarePlan Start Date"},		
		{"eCP.CarePlanTargetDate.label","CarePlan Target Date"},		
		{"eCP.CarePlanManager.label","CarePlan Manager"},		
		{"eCP.CarePlanStage.label","Care Plan Stage"},
		{"eCP.Cause.label","Cause"},
		{"eCP.CutOff.label","Cut Off"},	
		{"eCP.CareManagerName.label","Care Manager Name"},
		{"eCP.CarePlanManager.label","Care Plan Manager"},
		{"eCP.CarePlanManagerId.label","Care Plan Manager Id"},
		{"eCP.CarePlanId.label","Care Plan Id"},
		{"eCP.CarePlans.label","CarePlans"},
		{"eCP.DurationUnit.label","Duration Unit"},
		{"eCP.DurationBeforeStartTimeWhenTaskBecomesDue.label","Duration before start time when task becomes due"},
		{"eCP.DurationAfterStartTimeWhenTaskBecomesOverDue.label","Duration after start time when task becomes overdue"},
		{"eCP.DurationToPerformIntervention.label","Duration to perform Intervention"},
		{"eCP.DurationAfterEndTimeForMarkingTasksAsExpired.label","Duration after end time for marking tasks as expired"},
		{"eCP.DoYouWantAssociateOutcomeEvaluationMeasures.label","Do you want to associate outcome evaluation measures?"},
		{"eCP.DurationBeforeStartTime.label","Duration before start time"},
		{"eCP.DurationAfterStartTime.label","Duration after start time"},
		{"eCP.DurationAfterEndTime.label","Duration after end time"},
		{"eCP.d.label","(D)"},
		{"eCP.DepLvl.label","Dep Lvl"},		
		{"eCP.DefinePlanScope.label","Define Plan Scope"},
		{"eCP.DiagnosisCaseType.label","Diagnosis/Case Type"},
		{"eCP.DefiningCharacteristics.label","Defining Characteristics:"},		
		{"eCP.EndOn.label","End On"},
		{"eCP.EvaluationErrors.label","Evaluation Errors"},
		{"eCP.EvaluationErrorDate.label","Evaluation Error Date"},
		{"eCP.EvaluationRemarks.label","Evaluation Remarks"},
		{"eCP.E.label","#E"},
		{"eCP.EvaluationScore.label","Evaluation Score"},
		{"eCP.EvaluatedBy.label","Evaluated By"},
		{"eCP.EvaluatePlan.label","Evaluate Plan"},
		{"eCP.EvaluationDate.label","Evaluation Date"},
		{"eCP.EvaluationHistory.label","Evaluation History"},		
		{"eCP.EligibleDiagnosisforCarePlan.label","Eligible Diagnosis for Care Plan"},				
		{"eCP.EligibleCaseTypeforCarePlan.label","Eligible Case Type for Care Plan"},					
		{"eCP.FindInterventionType.label","Find InterventionType"},		
		{"eCP.FrequencyForIntervention.label","FrequencyForIntervention"},		
		{"eCP.GoalStatement.label","Goal Statement"},
		{"eCP.Graphical.label","Graphical"},
		{"eCP.GuidelinesToPerformIntervention.label","Guidelines to perform Intervention"},
		{"eCP.GeneratePlanPreview.label","Generate Plan - Preview"},
		{"eCP.GeneratePlanDetail.label","Generate Plan - Detail"},
		{"eCP.IntermediateStatusDependency.label","IntermediateStatusDependency"},		
		{"eCP.InterventionCode.label","Intervention Code"},
		{"eCP.InterventionTypeDescription.label","Intervention Type Description"},		
		{"eCP.LastRevision.label","Last Revision"},
		{"eCP.LastEvaluation.label","Last Evaluation"},		
		{"eCP.ListofVariances.label","List of Variances"},		
		{"eCP.MarkEvaluationError.label","Mark Evaluation Error"},		
		{"eCP.Nex.label","Next >>"},		
		{"eCP.NoStandardCarePlanAvailable.label","No Standard Care Plan Available ....."},
		{"eCP.NewAssessment.label","New Assessment"},	
		{"eCP.NoofRevns.label","No of Revns"},	
		{"eCP.NoOfEvals.label","No. of Evals"},			
		{"eCP.NotAchieved.label","Not Achieved"},	
		{"eCP.OutcomeTargetDate.label","Outcome Target Date"},	
		{"eCP.PlanDetail.label","Plan Detail"},		
		{"eCP.PlannedIntervention.label","Planned Intervention"},
		{"eCP.Prev.label","<< Prev"},	
		{"eCP.PeriodUpto.label","Period Upto"},	
		{"eCP.PlanNo.label","Plan No"},			
		{"eCP.PartiallyAchieved.label","Partially Achieved"},	
		{"eCP.PlanSummary.label","Plan Summary"},		
		{"eCP.PatientAssessmentError.label","PatientAssessmentError"},	
		{"eCP.PatientAssessmentResult.label","Patient Assessment Result"},
		{"eCP.PatientAssessment.label","Patient Assessment"},	
		{"eCP.PatientAssessmentDiagnosis.label","PatientAssessmentDiagnosis"},	
		{"eCP.PatientAssessmentAddModify.label","PatientAssessmentAddModify"},			
		{"eCP.PositionNote.label","Position Note"},		
		{"eCP.PositionForIntervention.label","PositionForIntervention"},
		{"eCP.PlanID.label","Plan ID"},
		{"eCP.RecordButton.label","RecordButton"},	
		{"eCP.ReviseCareplan.label","Revise Careplan"},	
		{"eCP.RecordPlan.label","Record Plan"},		
		{"eCP.ReasonForVariance.label","Reason For Variance"},
		{"eCP.RecordVariance.label","Record Variance"},
		{"eCP.ResultMeasure.label","Result Measure"},		
		{"eCP.RecClinicalNotesPrintPreviewView.label","RecClinicalNotesPrintPreviewView"},
		{"eCP.R.label","#R"},		
		{"eCP.StartOn.label","Start On"},		
		{"eCP.StandardCarePlans.label","Standard Care Plans"},
		{"eCP.StandardCarePlan.label","Standard Care Plan"},
		{"eCP.SystemSuggested.label","System Suggested"},	
		{"eCP.SelectDiagnosistoGenerateCareplan.label","Select Diagnosis to Generate Care plan"},		
		{"eCP.TargetDate.label","Target Date"},	
		{"eCP.Textual.label","Textual"},			
		{"eCP.UserDefinedDiagnoses.label","User Defined Diagnoses"},		
		{"eCP.UnitsFor.label","Units for "},
		{"eCP.UseAsAdHocIntervention.label","Use as Ad Hoc Intervention"},
		{"eCP.VarianceDate.label","Variance Date"},		
		{"eCP.DurationBeforeStartTimeWhenTaskConsideredDue.label","Duration before start time when task is considered due"},
		{"eCP.DurationAfterStartTimeWhenTaskConsideredOverdue.label","Duration after start time when task is considered overdue"},
		{"eCP.DurationAfterEndTimeWhenTaskExpired.label","Duration after end time when task gets expired"},
		{"eCP.BackdatingLimitForTaskResulting.label","Backdating limit for task resulting"}, 
		{"eCP.PatientInstructionsIntervention.label","Patient Instructions for Intervention"} //IN030473
			// following labels will be removed soon due to duplication.
		/*{"eCP.AgeGroupCode.label","Age Group Code"},
		{"eCP.AgeGroupDescription.label","Age Group Description"},
		{"eCP.ApplicableTo.label","Applicable To"},
		{"eCP.Actual.label","Actual"},
		{"eCP.Classification.label","Classification"},
		{"eCP.Certain.label","Certain"},
		{"eCP.CheckBox.label","Check Box"},
		{"eCP.DependencyLevel.label","Dependency Level"},
		{"eCP.Days.label","Day(s)"},
		{"eCP.DependencyLevel.label","Dependency Level"},
		{"eCP.Dependency.label","Dependency"},
		{"eCP.FindPractitionerTypeForAssessmentNote.label","Find Practitioner Type For Assessment Note"},
		{"eCP.Hours.label","Hour(s)"},
		{"eCP.Inactive.label","Inactive"},
		{"eCP.Minutes.label","Minute(s)"},
		{"eCP.Note.label","Note"},
		{"eCP.NoteDescription.label","Note Description"},
		{"eCP.Nature.label","Nature"},
		{"eCP.Numeric.label","Numeric"},
		{"eCP.Potential.label","Potential"},
		{"eCP.PractitionerType.label","Practitioner Type"},
		{"eCP.PractitionerTypeDescription.label","Practitioner Type Description"},
		{"eCP.PatientClassCode.label","Patient Class Code"},
		{"eCP.Preview.label","Preview"},
		{"eCP.Parameters.label","Parameters"},			
		{"eCP.Response.label","Response"},
		{"eCP.ReasonCode.label","Reason Code"},
		{"eCP.ReasonDescription.label","Reason Description"},
		{"eCP.Reason.label","Reason"},
		{"eCP.Specialty.label","Specialty"},
		{"eCP.SpecialtyCode.label","Specialty Code"},
		{"eCP.SpecialtyDescription.label","Specialty Description"},
		{"eCP.StageCode.label","Stage Code"},
		{"eCP.Stage.label","Stage"},
		{"eCP.save.label","Save"},
		{"eCP.TerminologySet.label","Terminology Set"},
		{"eCP.TerminologyCodeDescription.label","Terminology Code Description"},
		{"eCP.TerminologyCode.label","Terminology Code"},
		{"eCP.Uncertain.label","Uncertain"},
		{"eCP.Accuracy.label","Accuracy"},
		{"eCP.Attributes.label","Attributes"},
		{"eCP.Amend.label","Amend"},
		{"eCP.Differentials.label","Differentials"},
		{"eCP.Discontinued.label","Discontinued"},
		{"eCP.ErrorRemarks.label","Error Remarks"},
		{"eCP.Finalize.label","Finalize"},		
		{"eCP.InterventionType.label","Intervention Type"},
		{"eCP.LastModifiedBy.label","Last Modified By"},
		{"eCP.LevelOfCare.label","Level Of Care"},
		{"eCP.MedAncService.label","Med/Anc Service"},
		{"eCP.MarkError.label","Mark Error"},
		{"eCP.NotPerformed.label","Not Performed"},	
		{"eCP.Performed.label","Performed"},
		{"eCP.PartiallyCompleted.label","Partially Completed"},	
		{"eCP.PrintPreview.label","Print Preview"},	
		{"eCP.PatientClass.label","Patient Class"},
		{"eCP.PatientClassDescription.label","Patient Class Description"},
		{"eCP.PositionCode.label","Position Code"},
		{"eCP.PositionDescription.label","Position Description"},
		{"eCP.Resolved.label","Resolved"},
		{"eCP.ResultType.label","Result Type"},
		{"eCP.StaffType.label","Staff Type"},
		{"eCP.Sex.label","Sex"},		
		{"eCP.ScheduleDate.label","Schedule Date"},		
		{"eCP.TermCode.label","Term Code"},	
		{"eCP.Workplace.label","Workplace"},
		{"eCP.Modified.label","Modified"},
		{"eCP.Unauthorized.label","Unauthorized"},
		{"eCP.Transcribed.label","Transcribed"},
		{"eCP.Abnormal.label","Abnormal"},
		{"eCP.Wellness.label","Wellness"}*/
		};
}

