/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.  
 ******************************************************************************/
/*  
-------------------------------------------------------------------------------------------------------------------------------------------
Date		            Edit History	        Name		       Rev.Date		     Rev.Name			     Description
-------------------------------------------------------------------------------------------------------------------------------------------
27/02/2014				42063			        Suresh R           27/02/2014        Suresh R     AMS-CRF-0054(Added Item Based IssueReturn)
26/04/2016				56060				Badmavathi B					 					  PMG2015-CRF-INT-ST-0001(Use 'Authorize at Issue Store' privilege to Authorize)		
???
20/04/2017				63281				B.Badmavathi									  To display Available Quantity at Request Store 
24/05/2017				63603				Badmavathi B										  GHL-CRF-0456
09/01/2018				66199					Shazana Hasan										GHL-CRF- 0499 - Added Challan_No in Batch Search
12/12/2017									Chithra M										  	GHL-CRF-0496
1/2/2018				66368					Shazana												GHL-CRF-0503 - Added Zero Stock Batches in Split Batch
21/01/2019		        IN067798			    B Haribabu						                             AMRI-CRF-0382 - New filter Authorized date
10/10/2019              IN:071343              B Haribabu                                         GHL-CRF-0608	
10/10/2019              IN:071344              B Haribabu          31/10/2019        Manickam     GHL-CRF-0609
27/11/2019              IN:071539               B Haribabu         28/11/2019         Manickam                NMC-JD-CRF-0029
30/01/2020      		IN071972            	Haribabu                               						AAKH-CRF-0117.2 
08/06/2020              IN:072963               Haribabu            08/06/2020        Manickam       ML-MMOH-CRF-1389.1        
31/12/2020				TFS-8224      		     Prabha           31/12/2020		  Manickam	     MMS-DM-CRF-0177
13/5/2021		TFS:14012			Shazana											MO-CRF-20165   
7/6/2021				TFS-19787				Shazana													MOHE-CRF-0084.1 
13/10/2021				TFS-24348			Shazana		13/10/2021		Manickam		MO-CRF-20172
20/10/2021				TFS-24350			Shazana		20/10/2021		Manickam		MO-CRF-20173
17/1/2022	  			TFS-27751	   			Shazana     										MO-CRF-20175
--------------------------------------------------------------------------------------------------------------------------------------------
*/
package eST.resources;

import java.util.*;
public class Labels extends ListResourceBundle
{
	public Object[][] getContents()
	{
         return contents;
    }

	static final Object[][] contents = 
	{
		{"eST.A.label","A"},
		{"eST.ABCAnalysis.label","ABC Analysis"},
		{"eST.ABCAnalysisReport.label","ABC Analysis Report"},
		{"eST.ABCCategory.label","ABC Category"},
		{"eST.ABCCriteria.label","ABC Criteria"},
		{"eST.ABCCutoffRange.label","ABC Cutoff Range"},
		{"eST.ActualBalanceQty.label","Actual Balance Qty"},
		{"eST.ActualQuantity.label","Actual Quantity"},
		{"eST.AddedBy.label","Added By"},
		{"eST.AddedDate.label","Added Date"},
		{"eST.AddItems.label","Add Items"},
		{"eST.AdjDocDate.label","Adj Doc Date"},
		{"eST.AdjDocRef.label","Adj Doc Ref"},
		{"eST.AdjDocStartNo.label","Adj Doc Start No"},
		{"eST.AdjDocType.label","Adj Doc Type"},
		{"eST.AdjRemarks.label","Adj Remarks"},
		{"eST.Adjustments.label","Adjustments"},
		{"eST.AgeSlots.label","Age Slots"},
		{"eST.AgeingSlots.label","Ageing Slots"},
		{"eST.AlertPickSlipPrint.label","Alert Pickslip Print"},
		{"eST.AllItems.label","All Items"},
		{"eST.AllStores.label","All Stores"},
		{"eST.AllowMultiStoreIssue.label","Allow Multi Store Issue"},
		{"eST.Analysis.label","Analysis"},
		{"eST.Annual.label","Annual"},
		{"eST.ApplicabletoPharmacy.label","Applicable to Pharmacy"},
		{"eST.ApplicableforConsumption.label","Applicable for Consumption"},
		{"eST.AssociatedRTV.label","Associated RTV"},
		{"eST.AssociatedRTVsforReplacement.label","Associated RTVs for Replacement"},
		{"eST.AuditInformationfor.label","Audit Information for"},
		{"eST.AuthorizeAtIssueStoreRemarks.label","Authorize At Issue Store Remarks"},
		{"eST.AuthatReqByStore.label","Authorize at Request By Store"},
		{"eST.AuthorizeQuantity.label","Authorize Quantity"},
		{"eST.AuthorizeSpecialRequest.label","Authorize Special Request"},
		{"eST.AuthorizedatIssueStore.label","Authorized at Issue Store"},
		{"eST.AuthorizedatRequestbyStore.label","Authorized at Request by Store"},
		{"eST.Autoclavable.label","Autoclavable"},
		{"eST.AvailableQty.label","Available Qty"},
		{"eST.AvailableStock.label","Available Stock"},
		{"eST.Averagecostwillbechangedfrom.label","Average cost will be changed from"},
		{"eST.AvlQtyatIssueStore.label","Avl Qty at Issue Store"},
		{"eST.AvlQtyinIssStore.label","Avl Qty in Iss Store"},
		{"eST.AvlQtyinReqStore.label","Avl Qty in Req Store"},
		{"eST.B.label","B"},
		{"eST.BaseQuantity.label","Base Quantity"},
		{"eST.BatchExpiresNext.label","Batch Expires Next"},
		{"eST.BatchSearch.label","Batch Search"},
		{"eST.BatchSelection.label","Batch Selection"},
		{"eST.BatchSeries.label","Batch Series"},
		{"eST.BatchStatusHistory.label","Batch Status History"},
		{"eST.BelowMinimumStockLevel.label","Below Minimum Stock Level"},
		{"eST.BelowRe-OrderLevel.label","Below Re-Order Level"},
		{"eST.BillingConfirmationAlert.label","Billing Confirmation Alert"},
		{"eST.BinLocationRange.label","Bin Location Range"},
		{"eST.Bonus.label","Bonus"},
		{"eST.BonusQuantity.label","Bonus Quantity"},
		{"eST.BufferPercentage.label","Buffer Percentage"},
		{"eST.ByBinLocation.label","By Bin Location"},
		{"eST.ByDocumentDate.label","By Document Date"},
		{"eST.ByFromStore.label","By From Store"},
		{"eST.ByIssuingStore.label","By Issuing  Store"},
		{"eST.ByItem.label","By Item"},
		{"eST.ByItemCode.label","By Item Code"},
		{"eST.ByReceivingStore.label","By Receiving Store"},
		{"eST.ByShortDescription.label","By Short Description"},
		{"eST.ByStore.label","By Store"},
		{"eST.BySupplier.label","By Supplier"},
		{"eST.ByToStore.label","By To Store"},
		{"eST.C.label","C"},
		{"eST.ChangeBin.label","Change Bin"},
		{"eST.ChildItem.label","Child Item"},
		{"eST.CloseUponIssue.label","Close Upon Issue"},
		{"eST.Closed/Cancelled.label","Closed/Cancelled"},
		{"eST.ClosingBalance.label","Closing Balance"},
		{"eST.CommittedQty.label","Committed Qty"},
		{"eST.Compositionfor.label","Composition for"},
		{"eST.CompositionforQty.label","Composition for Qty"},
		{"eST.ComputedDetails.label","Computed Details"},
		{"eST.CondemnID.label","Condemn ID"},
		{"eST.ConfirmPrinting.label","Confirm Printing"},
		{"eST.ConsiderIteminTargetStore.label","Consider Item in TargetStore"},
		{"eST.ConsiderReprintasOriginal.label","Consider Reprint as Original"},
		{"eST.ConsiderStockpositionforReorder.label","Consider Stock positionfor Reorder"},
		{"eST.Consignment.label","Consignment"},
		{"eST.ConsignmentItemsOnly.label","Consignment Items Only"},
		{"eST.Consumption.label","Consumption"},
		{"eST.ConsumptionCost.label","Consumption Cost"},
		{"eST.ConsumptionCriteria.label","Consumption Criteria"},
		{"eST.ConsumptionPeriod.label","Consumption Period"},
		{"eST.ConsumptionQty.label","Consumption Qty"},
		{"eST.Contract.label","Contract"},
		{"eST.ConvFactor.label","Conv Factor"},
		{"eST.CounterChecked.label","Counter Checked"},
		{"eST.Currency.label","Currency"},
		{"eST.CurrentInventory.label","Current Inventory"},
		{"eST.CurrentPackSize.label","Current Pack Size"},
		{"eST.CurrentSpecificInventory.label","Current Specific Inventory"},
		{"eST.DefaultStockParameter.label","Default Stock Parameter"},
		{"eST.DeptWiseConsumption.label","Dept Wise Consumption"},
		{"eST.DocDateFrom.label","Doc Date From"},
		{"eST.DocSrlNo.label","Doc Srl No"},
		{"eST.DocType/No.label","Doc Type/ No"},
		
		{"eST.DocumentsforAuthorize.label","Documents for Authorize"},
		{"eST.DurnforStartDate.label","Duration for Start Date"},
		{"eST.Edit/View.label","Edit/View"},
		{"eST.ExcludeExternalStores.label","Exclude External Stores"},
		{"eST.Excludeitemsreceivedwithin.label","Exclude items receivedwithin"},
		{"eST.ExpectedBalanceQuantity.label","Expected Balance Quantity"},
		{"eST.ExpectedQuantity.label","Expected Quantity"},
		{"eST.Expired&NotifiedBatch.label","Expired & Notified Batch"},
		{"eST.ExpiredBatch.label","Expired Batch"},
		{"eST.Expired/Notified.label","Expired/Notified"},
		{"eST.Expired/Suspend.label","Expired/Suspend"},
		{"eST.Expiringin.label","Expiring in"},
		{"eST.Expiring/expiredBatches.label","Expiring/expired Batches"},
		{"eST.ExpiryAnalysisReport.label","Expiry Analysis Report"},
		{"eST.ExpiryCutoffDays.label","Expiry Cutoff Days"},
		{"eST.ExpiryFlag.label","Expiry Flag"},
		{"eST.ExpiryItems.label","Expiry Items"},
		{"eST.ExpirySelection.label","Expiry Selection"},
		{"eST.ExpiryWarningDays.label","Expiry Warning Days"},
		{"eST.Expiry/ReceiptDate.label","Expiry/Receipt Date"},
		{"eST.Extemporaneous.label","Extemporaneous"},
		{"eST.ExternalItem.label","External Item"},
		{"eST.ExternalStores.label","External Stores"},
		{"eST.FacilityWiseYearlySummaryReport.label","Facility Wise Yearly Summary Report"},
		{"eST.Factor.label","Factor"},
		{"eST.Fast/Slow/NoMovementReport.label","Fast/Slow/No Movement Report"},
		{"eST.ForA.label","For A"},
		{"eST.ForB.label","For B"},
		{"eST.ForC.label","For C"},
		{"eST.FractionalUOM.label","Fractional UOM"},
		{"eST.FromStore.label","From  Store"},
		{"eST.FromBinLocation.label","From Bin Location"},
		{"eST.FromDocDate.label","From Doc Date"},
		{"eST.FromItem.label","From Item"},
		{"eST.GenerateBatch.label","Generate Batch"},
		{"eST.GoodsReceipt.label","Goods Receipt"},
		{"eST.GoodsReceiptFinalize.label","Goods Receipt Finalize"},
		{"eST.GraceDaysforHomeCare.label","Grace Days for Home Care"},
		{"eST.GRN.label","GRN"},
		{"eST.GRNBatchSearch.label","GRN Batch Search"},
		{"eST.GRNDetailsfor.label","GRN Details for"},
		{"eST.GRNDetailsForReplacement.label","GRN Details For Replacement"},
		{"eST.GRNDocType.label","GRN Doc Type"},
		{"eST.GRNDocType/No.label","GRN Doc Type/No"},
		{"eST.GRNHistory.label","GRN History"},
		{"eST.GRNHistoryRTVList.label","GRN History RTV List"},
		{"eST.GRNPreviewDetails.label","GRN Preview Details"},
		{"eST.GRNQuantity.label","GRN Quantity"},
		{"eST.GRNStatisticsReport.label","GRN Statistics Report"},
		{"eST.GRNValue.label","GRN Value"},
		{"eST.IncludeExpiredBatches.label","Include Expired Batches"},
		{"eST.IncludeNotifiedBatches.label","Include Notified Batches"},
		{"eST.IncludeStockIssues.label","Include Stock Issues"},
		{"eST.IncludeSuspendedBatches.label","Include Suspended Batches"},
		{"eST.IncludeZeroStockBatches.label","Include Zero Stock Batches"},
		{"eST.IndentIssuebyDept.label","Indent Issue by Dept"},
		{"eST.InsurancePolicyIsExpired Proceed.label","Insurance Policy Is Expired Proceed"},
		{"eST.InternalStores.label","Internal Stores"},
		{"eST.InterfaceAttributes.label","Interface Attributes"},
		{"eST.IssueBatchSearch.label","Issue Batch Search"},
		{"eST.IssueIntegerQuantity.label","Issue Integer Quantity"},
		{"eST.IssuePreviewDetails.label","Issue Preview Details"},
		{"eST.IssueReturnFinalize.label","Issue Return Finalize"},
		{"eST.IssueReturnPreviewDetails.label","Issue Return Preview Details"},
		{"eST.IssueReturns.label","Issue Returns"},
		{"eST.IssueSequence.label","Issue Sequence"},
    	{"eST.IssuebySeqPrint.label","Print by Issue Sequence"}, //ganga
		{"eST.IssueUOM.label","Issue UOM"},
		{"eST.IssueUOMQuantity.label","Issue UOM Quantity"},
		{"eST.IssuesCost.label","Issues Cost"},
		{"eST.IssuingStore.label","Issuing Store"},
		{"eST.ItemAnalysisCodeshouldbeunique.label","Item Analysis Code should be unique"},
		{"eST.ItemDetails.label","Item Details"},
		{"eST.ItemFrom.label","Item From"},
		{"eST.ItemMasterPriceSummary.label","Item Master Price Summary"},
		{"eST.ItemQuantity.label","Item Quantity"},
		{"eST.ItemSearch.label","Item Search"},
		{"eST.ItemSelection.label","Item Selection"},
		{"eST.ItemSpecifications.label","Item Specifications"},
		{"eST.ItemSummaryReport.label","Item Summary Report"},
		{"eST.ItemTo.label","Item To"},
		{"eST.Itemtobeused.label","Item to be used"},
		{"eST.ItemsMovementStatus.label","Items Movement Status"},
		{"eST.LabelRequired.label","Label Required"},
		{"eST.LastDays.label","Last Days"},
		{"eST.LeadDays.label","Lead Days"},
		{"eST.lessthanminstock.label","Less Than Min Stock"},
		{"eST.lessthanROL.label","Less Than ROL"},
	    {"eST.ListofItemsCrossingROL.label","List of Items Crossing ROL"},
		{"eST.MachineCode.label","Machine Code"},
		{"eST.ManufactureReceipts.label","Manufacture Receipts"},
		{"eST.ManufacturerItem.label","Manufacturer Item"},
		{"eST.Manufacturing.label","Manufacturing"},
		{"eST.ManufacturingFormulary.label","Manufacturing Formulary"},
		{"eST.ManufacturingItem.label","Manufacturing Item"},
		{"eST.ManufacturingItemLabel.label","Manufacturing Item Label"},
		{"eST.ManufacturingItems.label","Manufacturing Items"},
		{"eST.ManufacturingItemsFinalize.label","Manufacturing Items Finalize"},
		{"eST.ManufacturingReceipt.label","Manufacturing Receipt"},
		{"eST.ManufacturingRequestDetails.label","Manufacturing Request Details"},
		{"eST.MasterBinLocation.label","Master Bin Location"},
		{"eST.MaxAvailable.label","Max Available"},
		{"eST.MaxReturnableQuantity.label","Max Returnable Quantity"},
		{"eST.MaxStock.label","Max Stock"},
		{"eST.MaxStockLevel.label","Max Stock Level"},
		{"eST.MaxStockQuantity.label","Max Stock Quantity"},
		{"eST.MaximumLevel.label","Maximum Level"},
		{"eST.MFG.label","MFG"},
		{"eST.MFGItem.label","MFG Item"},
		{"eST.MFGReceipts.label","MFG Receipts"},
		{"eST.MFGUOM.label","MFG UOM"},
		{"eST.MFGWorkloadStatisticsReport.label","MFG Workload StatisticsReport"},
		{"eST.MinSalesQuantity.label","Min Sales Quantity"},
		{"eST.MinStock.label","Min Stock"},
		{"eST.MinStockDays.label","Min Stock Days"},
		{"eST.MinStockLevel.label","Min Stock Level"},
		{"eST.MinimumLevel.label","Minimum Level"},
		{"eST.ModelNo.label","Model No"},
		{"eST.ModifyDocumentDetails.label","Modify Document Details"},
		{"eST.MovedItemsOnly.label","Moved Items Only"},
		{"eST.MTDIssueQuantity.label","MTD Issue Quantity"},
		{"eST.MTDReceiptsQuantity.label","MTD Receipts Quantity"},
		{"eST.ModelNoFrom.label","Model No From"},
		{"eST.NoofCopies.label","No of Copies"},
		{"eST.NoofLabels.label","No of Labels"},
		{"eST.NoofUnfinalised/GLUninterfacedTransactions.label","No of Unfinalised/GL Uninterfaced Transactions"},
		{"eST.NonConsignment.label","Non Consignment"},
		{"eST.NonConsumption.label","Non Consumption"},
		{"eST.NonInventoryGRN.label","Non Inventory GRN"},
		{"eST.NonManufacturing.label","Non Manufacturing"},
		{"eST.NonMedical.label","Non Medical"},
		{"eST.NonMedicalItems.label","Non Medical Items"},
		{"eST.NonMovedItemsOnly.label","Non Moved Items Only"},
		{"eST.NonPSItems.label","Non PS Items"},
		{"eST.NonSoleSource.label","Non Sole Source"},
		{"eST.NonSterile.label","Non Sterile"},
		{"eST.NonStock.label","Non Stock"},
		{"eST.NonStockIssues.label","Non Stock Issues"},
		{"eST.StockIssues.label","Stock Issues"},//Added by Sakti on 13/12/2013 to display in Item movement query function
		{"eST.NonStockReturns.label","Non Stock Returns"},
		{"eST.NonContract.label","Non-Contract"},
		{"eST.NonExpiryItems.label","Non-Expiry Items"},
		{"eST.NonMedicalItem.label","Non-Medical Item"},
		{"eST.NonStockStore.label","Non-Stock Store"},
		{"eST.NormalQty.label","Normal Qty"},
		{"eST.NormalRequest.label","Normal Request"},
		{"eST.Notified.label","Notified"},
		{"eST.NotifiedBatch.label","Notified Batch"},
		{"eST.ofMinStock.label","of Min Stock"},
		{"eST.OldDetails.label","Old Details"},
		{"eST.OnlyA.label","Only A"},
		{"eST.OnlyB.label","Only B"},
		{"eST.OnlyC.label","Only C"},
		{"eST.OpeningStock.label","Opening Stock"},
		{"eST.OtherAttributes.label","Other Attributes"},
		{"eST.OtherStore.label","Other Store"},
		{"eST.ParentStore.label","Parent Store"},
		{"eST.PendingIndentList.label","Pending Indent List"},
       	{"eST.PendingRequestQty.label","Pending Request Qty"},
		{"eST.PeriodFrom.label","Period  From"},
		{"eST.PeriodFromDate.label","Period From Date"},
		{"eST.Perpetual.label","Perpetual"},
		{"eST.PharmacyStockItems.label","Pharmacy Stock Items"},
		{"eST.PhyCount.label","Phy Count"},
		{"eST.PhyCountPerYear.label","Phy Count Per Year"},
		{"eST.PhyInvProcessMode.label","Phy Inv Process Mode"},
		{"eST.PhyInventory.label","Phy Inventory"},
		{"eST.PhyInventoryID.label","Phy Inventory ID"},
		{"eST.PhyInventoryType.label","Phy Inventory Type"},
		{"eST.PONo.label","PO No"},
		{"eST.PrePacking.label","Pre Packing"},
		{"eST.PreparationMode.label","Preparation Mode"},
		{"eST.PreparationType.label","Preparation Type"},
		{"eST.PresentCount.label","Present Count"},
		{"eST.PrimaryStore.label","Primary Store"},
		{"eST.Print/View.label","Print / View"},
		{"eST.PrintAlertRequired.label","Print Alert Required"},
		{"eST.PrintDocument.label","Print Document"},
		{"eST.PrintTechnicalSpecification.label","Print Technical Specification"},
		{"eST.ProcessExpiredBatch.label","Process Expired Batch"},
		{"eST.ProcessLoss.label","Process Loss"},
		{"eST.ProcessOption.label","Process Option"},
		{"eST.ProcessSuspendedBatch.label","Process Suspended Batch"},
		{"eST.ProductTransfer.label","Product Transfer"},
		{"eST.ProductTransferReqNo.label","Product Transfer Req No"},
		{"eST.ProductTransferRequestSearch.label","Product Transfer Request Search"},
		{"eST.PRT.label","PRT"},
		{"eST.PurchaseSummaryReport.label","Purchase Summary Report"},
		{"eST.QuantityOnHand.label","Quantity On Hand"},
		{"eST.QuantityToTransfer.label","Quantity To Transfer"},
		{"eST.QueryType.label","Query Type"},
		{"eST.ReceivedQuantity.label","Received Quantity"},
		{"eST.Refundallowed.label","Refund allowed"},
		{"eST.Reordarable.label","Reordarable"},
		{"eST.ReorderAttributes.label","Reorder Attributes"},
		{"eST.ReorderDays.label","Reorder Days"},
		{"eST.ReorderFreqDays.label","Reorder Freq Days"},
		{"eST.ReorderQuantity.label","Reorder Quantity"},
		{"eST.Reorderable.label","Reorderable"},
		{"eST.ReorderableItems.label","Reorderable Items"},
		{"eST.ReorderableStore.label","Reorderable Store"},
		{"eST.ReorderableStoresstock.label","Reorderable Stores stock"},
		{"eST.RepackGroup.label","Repack Group"},
		{"eST.RepackItem.label","Repack Item"},
		{"eST.RepackSize.label","Repack Size"},
		{"eST.RepackStore.label","Repack Store"},
		{"eST.RepackingLabel.label","Repacking Label"},
		{"eST.Replonexpiry.label","Repl on expiry"},
		{"eST.ReplRTVQuantity.label","Repl RTV Quantity"},
		{"eST.ReplacementGRN.label","Replacement GRN"},
		{"eST.ReplacementGRNBatchSearch.label","Replacement GRN Batch Search"},
		{"eST.ReplacementOnExpiry.label","Replacement On Expiry"},
		{"eST.ReplacementQty.label","Replacement Qty"},
		{"eST.ReplacementRTV.label","Replacement RTV"},
		{"eST.ReplacementRTVDetailsForItem.label","Replacement RTV DetailsFor Item"},
		{"eST.ReplGRNQuantity.label","ReplGRN Quantity"},
		{"eST.Reports.label","Reports"},
		{"eST.ReportExecutedBy.label","Report Executed By"},
		{"eST.ReportMfgItemLabel.label","Report Mfg Item Label"},
		{"eST.ReportRepackingLabel.label","Report Repacking Label"},
		{"eST.ReportSuspendedReinstateBatches.label","Report Suspended Reinstate Batches"},
		{"eST.ReqBy.label","Req By"},
		{"eST.ReqEntered.label","Req Entered"},
		{"eST.ReqGenerationBase.label","Req Generation Base"},
		{"eST.ReqIssue.label","Req Issue"},
		{"eST.ReqItemDetailsfor.label","Req Item Details for"},
		{"eST.ReqNo.label","Req No"},
		{"eST.ReqNoFrom.label","Req No From"},
		{"eST.ReqQty.label","Req Qty"},
		{"eST.ReqStatisticsReport.label","Req Statistics Report"},
		{"eST.ReqStatus.label","Req Status"},
		{"eST.ReqStore.label","Req Store"},
		{"eST.ReqType.label","Req Type"},
		{"eST.ReqUOM.label","Req UOM"},
		{"eST.ReqUOMQty.label","Req UOM Qty"},
		{"eST.RequestbyStore.label","Request by Store"},
		{"eST.RequestByStoreCode.label","Request By Store Code"},
		{"eST.Requestsof.label","Requests of"},
		{"eST.RequiredItem.label","Required Item"},
		{"eST.RequiredQuantity.label","Required Quantity"},
		{"eST.Requisition.label","Requisition"},
		{"eST.RequisitionAuthorize.label","Requisition Authorize"},
		{"eST.RequisitionIssues.label","Requisition Issues"},
		{"eST.RequisitionIssuesFinalize.label","Requisition Issues Finalize"},
		{"eST.ResultCriteria.label","Result Criteria"},
		{"eST.RET.label","RET"},
		{"eST.RetailMasterStockQuantityandValueReport.label","Retail Master Stock Quantity and Value Report"},
		{"eST.RetQty.label","Ret Qty"},
		{"eST.ReturnPeriod.label","Return Period"},
		{"eST.ReturntoVendor.label","Return to Vendor"},
		{"eST.ReturnVendor.label","Return Vendor"},
		{"eST.Returns.label","Returns"},
		{"eST.RevokeDate.label","Revoke Date"},
		{"eST.RFDays.label","RF Days"},
		{"eST.ROLevel.label","RO Level"},
		{"eST.ROQuantity.label","RO Quantity"},
		{"eST.RTV.label","RTV"},
		{"eST.RTVDetailsforReplacementGRN.label","RTV Details for Replacement GRN"},
		{"eST.RTVDocType/No.label","RTV Doc Type/No"},
		{"eST.RTVforReplacement.label","RTV for Replacement"},
		{"eST.RTVHistory.label","RTV History"},
		{"eST.RTVPreviewDetails.label","RTV Preview Details"},
		{"eST.RTVQuantity.label","RTV Quantity"},
		{"eST.RTVREF.label","RTV Ref"},
		{"eST.S.label","S"},
		{"eST.SAL.label","SAL"},
		{"eST.SaleTrnType.label","Sale Trn Type"},
		{"eST.SaleUOM.label","Sale UOM"},
		{"eST.Sales.label","Sales"},
		{"eST.SalesAttributes.label","Sales Attributes"},
		{"eST.SalesAuthorize.label","Sales Authorize"},
		{"eST.SalesBatchSearch.label","Sales Batch Search"},
		{"eST.SalesHistory.label","Sales History"},
		{"eST.SalesReturnFinalize.label","Sales Return Finalize"},
		{"eST.SalesReturnPreviewDetails.label","Sales Return Preview Details"},
		{"eST.SalesReturns.label","Sales Returns"},
		{"eST.SalesType.label","Sales Type"},
		{"eST.ModifyFin.Details.label","Modify Fin. Details"},// Added By Narasimhulu for KDAH-CRF-0432.1
		{"eST.Sales/PatientIssue.label","Sales/Patient Issue"},
		{"eST.Sales/PatientIssueCost.label","Sales/Patient Issue Cost"},
		{"eST.Sales/PatientIssuesPreviewDetails.label","Sales/Patient Issues Preview Details"},
		{"eST.Sample.label","Sample"},
		{"eST.SelectBatchFor.label","Select Batch For"},
		{"eST.SelectCriteria.label","Select Criteria"},
		{"eST.ShowBatchInfo.label","Show Batch Info"},
		{"eST.SpecialReqItem.label","Special Req Item"},
		{"eST.SpecialRequest.label","Special Request"},
		{"eST.SplitBatch.label","Split Batch"},
		{"eST.SplitBatches.label","Split Batches"},
		{"eST.SRT.label","SRT"},
		{"eST.StandardFormulary.label","Standard Formulary"},
		{"eST.Sterile.label","Sterile"},
		{"eST.Sterilizable.label","Sterilizable"},
		{"eST.StockAdjustment.label","Stock Adjustment"},
		{"eST.StockAdjustmentFinalize.label","Stock Adjustment Finalize"},
		{"eST.StockatPrimaryStore.label","Stock at Primary Store"},
		{"eST.StockAvailability.label","Stock Availability"},
		{"eST.StockConvFactor.label","Stock Conv Factor"},
		{"eST.StockFast/SlowMovementReport.label","Stock Fast/Slow Movement Report"},
		{"eST.StockHandledByMedicalStore.label","Stock Handled By Medical Store"},
		{"eST.StockHoldingAnalysisReport.label","Stock Holding AnalysisReport"},
		{"eST.StockItem.label","Stock Item"},
		{"eST.StockItemConsumption.label","Stock Item Consumption"},
		{"eST.StockItemConsumptionPreviewDetails.label","Stock Item ConsumptionPreview Details"},
		{"eST.StockLevel.label","Stock Level"},
		{"eST.StockPositionof.label","Stock Position of"},
		{"eST.StockQuantityStationWise.label","Stock Quantity Station Wise"},
		{"eST.StockReorderStore.label","Stock Reorder Store"},
		{"eST.StockStatusByItem.label","Stock Status By Item"},
		{"eST.StockStatusReportForTransactedItems.label","Stock Status Report ForTransacted Items"},
		{"eST.StockTransfer.label","Stock Transfer"},
		{"eST.StockTransferFinalize.label","Stock Transfer Finalize"},
		{"eST.StockValue.label","Stock Value"},
		{"eST.StockValueStationWise.label","Stock Value Station Wise"},
	    {"eST.StoreFrom.label","Store From"},
		{"eST.StoreTo.label","Store To"},
		{"eST.StorewiseConsumption.label","Storewise Consumption"},
		{"eST.StorewiseConsumptionforthePeriod.label","Storewise Consumption for the Period"},
		{"eST.SubStore.label","Sub Store"},
		{"eST.SuppressSummary.label","Suppress Summary"},
		{"eST.SuppressZero.label","Suppress Zero"},
		{"eST.SuppressZeroVariance.label","Suppress Zero Variance"},
		{"eST.SuspendDate.label","Suspend Date"},
		{"eST.Suspended&ExpiredBatch.label","Suspended & Expired Batch"},
		{"eST.SuspendedBatch.label","Suspended Batch"},
		{"eST.SuspendedExpiredNotifiedBatch.label","Suspended, Expired & Notified Batch"},
		{"eST.TechnicalSpecification.label","Technical Specification"},
		{"eST.TemporaryPhyInvID.label","Temporary Phy Inv ID"},
		{"eST.TFR.label","TFR"},
		{"eST.ToBinLocation.label","To Bin Location"},
		{"eST.ToDocDate.label","To Doc Date"},
		{"eST.ToItem.label","To Item"},
		{"eST.ToStoreMasterBin.label","To Store Master Bin"},
		{"eST.TotalItemValue.label","Total Item Value"},
		{"eST.TotalStock.label","Total Stock"},
		{"eST.TransAnalysisReport.label","Trans Analysis Report"},
		{"eST.TransQty.label","Trans Qty"},
		{"eST.Transactionacrossfacility.label","Transaction across facility"},
		{"eST.TransactionApplicable.label","Transaction Applicable"},
		{"eST.TransferExecutedby.label","Transfer Executed By"},
		{"eST.TransferQty.label","Transfer Qty"},
		{"eST.UnfinalizedTransactionsReport.label","Unfinalized Transactions Report"},
		{"eST.URG.label","URG"},
		{"eST.UrgentIssue.label","Urgent Issue"},
		{"eST.UrgentIssueFinalize.label","Urgent Issue Finalize"},
		{"eST.UseAfterExpiry.label","Use After Expiry"},
		{"eST.UserInfo.label","User Info"},
		{"eST.VendorReturn.label","Vendor Return"},
		{"eST.VendorReturnFinalize.label","Vendor Return Finalize"},
		{"eST.WithFormulary.label","With Formulary"},
		{"eST.WithoutFormulary.label","Without Formulary"},
		{"eST.WorkLoadStatisticReport.label","Work Load Statistic Report"},
		{"eST.YearlyStockTurnoverReport.label","Yearly Stock Turnover Report"},
		{"eST.YTDConsQty.label","YTD Cons Qty"},
		{"eST.YTDIssQty.label","YTD Iss Qty"},
		{"eST.WardSupplyManufacturingAndRepackingOutput.label","Ward Supply  Manufacturing And Repacking-Output"},  
		{"eST.ReportOnGRNStatisticsForDrugs.label","Report On GRN Statistics For Drugs"},  
		{"eST.QAP13AnnualTurnoverRateofStock.label","QAP-13   Annual Turn-over Rate of Stock"},  
		{"eST.QAP14Proportionofvalueofstockswrittenoff.label","QAP 14 - Proportion of value of stocks written off"},  
		{"eST.ReturnType.label","Return Type"},  
		{"eST.StockReturns.label","Stock Returns"},  
		{"eST.StockIssues.label","Stock Issues"},  
		{"eST.PresentCountStatus.label","Present Count Status"},  
		{"eST.PurchaseValueItems.label","Purchase Value Items"},  
		{"eST.RequestOnStoreCode.label","Request On Store Code"},  
		{"eST.Excludetheitemsreceivedwithin.label","Exclude the items received within"},  
		{"eST.IssueType.label","Issue Type"},  
		{"eST.ConsignmentItems.label","Consignment Items"},  
		{"eST.ABCCodeItemMaster.label","ABC Code {Item Master}"},  
		{"eST.RepackingGroupCode.label","RepackingGroup Code"},  
		{"eST.RepackingGroupDescription.label","RepackingGroup Description"},  
		{"eST.ZeroStockItems.label","Zero Stock Items"},  
		{"eST.ItemLessthanReorderLevel.label","Item Less than Reorder Level"},  
		{"eST.ItemLessthanMinimumLevel.label","Item Less than Minimum Level"},  
		{"eST.ItemwithStock.label","Item with Stock"},  
		{"eST.ItemGreaterthanMaximumLevel.label","Item Greater than Maximum Level"},  
		{"eST.ActiveBatches.label","Active Batches"},  
		{"eST.SuspendedBatches.label","Suspended Batches"},  
		{"eST.AllBatches.label","All Batches"},  
		{"eST.ItemConsolidated.label","Item Consolidated"},  
		{"eST.ByItemStore.label","By Item Store"},  
		{"eST.ByStoreBatch.label","By Store Batch"},  
		{"eST.ByStoreBinLocation.label","By Store Bin Location"},  
		{"eST.ByItemBatch.label","By Item Batch"},  
		{"eST.NonZeroStock.label","Non Zero Stock"},  
		{"eST.ItemClassConsolidated.label","Item Class Consolidated"},  
		{"eST.StoreItem.label","Store-Item"},  
		{"eST.StoreItemClass.label","Store-Item Class"},  
		{"eST.NonSpecialItem.label","Non Special Item"},  
		{"eST.ConsumptionDeviation.label","Consumption Deviation"},  
		{"eST.ConsumptionByATCClassification.label","Consumption By ATC Classification"},  
		{"eST.StoreLevel.label","Store Level"},  
		{"eST.ByGRN.label","By GRN"},  
		{"eST.ByQuantity.label","By Quantity"},  
		{"eST.ByValue.label","By Value"},  
		{"eST.ProductRecall.label","Product Recall"},  
		{"eST.LastAccessedOn.label","Last Accessed On"},  
		{"eST.RequestItemDetailsfor.label","Request Item Details for"},  
		{"eST.NoMovement.label","No Movement"},  
		{"eST.GoodsReceivedNote.label","Goods Received Note"},  
		{"eST.GoodsReturntoVendor.label","Goods Return to Vendor"},  
		{"eST.ItemnotmappedtoDrug.label","Item not mapped to Drug"},  
		{"eST.SameAsExpiryDate.label","Same As Expiry Date"},  
		{"eST.RequestStatisticsReport.label","Request Statistics Report"} , 
		{"eST.DrugDescIsDifferent.label","Drug Description is different from Item Description.. Do you want to overwrite the existing Drug Description..{Ok/Cancel}?"},  
		{"eST.ByCondemnedId.label","By Condemned Id"}, 
		{"eST.VarianceReportatBatchLevel.label","Variance Report at Batch Level"}, 
		{"eST.VarianceReportatItemLevel.label","Variance Report at Item Level"}, 
		{"eST.VarianceReportatStoreLevel.label","Variance Report at Store Level"}, 
		{"eST.SummaryReportatItemClassLevel.label","Summary Report at Item Class Level"}, 
		{"eST.OnlyNotifiedBatches.label","Only Notified Batches"}, 
		{"eST.BufferonMinStock.label","Buffer % {on Min Stock}"}, 
		{"eST.Notify.label","Notify"}, 
		{"eST.LastAccessedBy.label","Last Accessed By"},  
		{"eST.ByItemClass.label","By Item Class"}, 
		{"eST.ReorderableStoresOnly.label","Reorderable Stores Only"}, 
		{"eST.NonReorderableStoresOnly.label","Non Reorderable Stores Only"}, 
		{"eST.TopValue.label","Top Value"}, 
		{"eST.CostValue.label","Cost Value"}, 
		{"eST.InventoryAgeingSlot.label","Inventory Ageing Slot"} ,
		{"eST.InventoryIssues.label","Inventory Issues"} ,
		{"eST.InventoryReturns.label","Inventory Returns"} ,
		{"eST.ISS.label","ISS"},
		{"eST.ModifiableYN.label","Modifiable Y/N"} ,		
		{"eST.MoreDetails.label","More Details"},
		{"eST.MovementCutoffMonthsSlotRanges.label","Movement Cutoff Months {Slot Ranges}"},
		{"eST.Outflow.label","Outflow"} ,
		{"eST.Particular.label","Particular"} ,
		{"eST.PhysicalCountSheetHistory.label","Physical CountSheet History"},
		{"eST.PrepareInstruction.label","Prepare Instruction"},
		{"eST.ReportOfTransferredBatches.label","Report Of Transferred Batches"},
		{"eST.RTVValue.label","RTV Value"} ,
		{"eST.SampleQuantity.label","Sample Quantity"} ,
		{"eST.ShowItems.label","Show Items"},
		{"eST.SoleSourceYN.label","Sole Source YN"},
		{"eST.SpecialItemYN.label","Special Item YN"},
		{"eST.StockInflow.label","Stock Inflow"} ,
		{"eST.StockOnHand.label","Stock On Hand"},
		{"eST.StockOutflow.label","Stock Outflow"} , 
		{"eST.StoreLevelStatus.label","Store Level Status"},
		{"eST.TransactionAnalysisReport.label","Transaction Analysis Report"},
		{"eST.ValueOfProcurementMadeByMedicalStore.label","Value Of Procurement Made By Medical Store"}, 
		{"eST.ZeroStock.label","Zero Stock"},
		{"eST.AgeingSlotdays.label","Ageing Slot {days}"}, 
		{"eST.AssemblyItemCode.label","Assembly Item Code"} ,
		{"eST.AutoclavableYN.label","Autoclavable YN"},
		{"eST.BasesYN.label","Bases Y/N"} ,
		{"eST.BatchQuantity.label","Batch Quantity"},		
		{"eST.Inflow.label","Inflow"} ,
		{"eST.Reorder.label","Re-Order"},
		{"eST.BelowMinStockLevel.label","Below Min Stock Level"},
		{"eST.PendReqdQty.label","Pend Req Qty"},
		{"eST.forItemCode.label","for Item Code"},
		{"eST.exceedmaxStockLevel.label","exceed max Stock Level"},
		{"eST.LessThanROLinFromStore.label","Less Than R.O.L in From Store"},
		{"eST.ExceedsMaxStkinToStore.label","Exceeds Max. Stk. in To Store"},	
		{"eST.BelowMinStkinFromStore.label","Below Min Stk in From Store"},
		{"eST.IndividualItem.label","Individual Item"},		
		{"eST.RangeOfItems.label","Range Of Items"}	,	
		{"eST.BasedYN.label","Based Y/N"}	,	
		{"eST.ExpiryYN.label","Expiry Y/N"},
		{"eST.ADJ.label","ADJ"},
		{"eST.IMPR.label","IMPR"},
		{"eST.PIL.label","PIL"},
		{"eST.expiredBatches.label","ExpiredBatche{s}"},
		{"eST.ReOrder.label","Re Order"},
		{"eST.IssQty.label","Iss Qty"},
		{"eST.Ingredients.label","Ingredients"},
		{"eST.PrintOnlabel.label","Print On Label"},
		{"eST.GetData.label","Get Data"},
		{"eST.MfgInstructions.label","Mfg Instructions"},
		{"eST.ToStoreBin.label","To Store Bin"},
		{"eST.RepackFactor.label","Repack Factor"},
		{"eST.ReplacementGRNExists.label","Replacement GRN Exists"},
		{"eST.FinalizedandRTVExists.label","Finalized and RTV Exists"},
		{"eST.ReplacementGRNPreviewDetails.label","Replacement GRN Preview Details"},
		{"eST.RequisitionRef.label","Requisition Ref"},
		{"eST.PuUOMFACTOR.label","PuUOM/FACTOR"},
		{"eST.RequestedUOM.label","Requested UOM"},
		{"eST.RequestqtyinReqUOM.label","Request qty in Req UOM"},
		{"eST.RTVDetails.label","RTV Details"},
		{"eST.ReplGRNQty.label","Repl GRN Qty"},
		{"eST.TotalNoOfItems.label","Total No Of Items"},
		{"eST.TotalTransferValue.label","Total Transfer Value"},
		{"eST.DuplicateCopy.label","Duplicate/Copy"},
		{"eST.SoldQuantity.label","Sold Quantity"},
		{"eST.SaleValue.label","Sale Value"},
		{"eST.AdjustQuantity.label","Adjust Quantity"},
		{"eST.AdjustCost.label","Adjust Cost"},		
		{"eST.BatchValue.label","Batch Value"},		
		{"eST.AdjustLineRemarks.label","Adjust Line Remarks"},		
		{"eST.FromItemCode.label","From Item Code"},		
		{"eST.FromExpiryDate.label","From Expiry Date"},		
		{"eST.FromItemQuantity.label","From Item Quantity"},		
		{"eST.NewBatch.label","New Batch"},		
		{"eST.Repackat.label","Repack at"},
		{"eST.ReqEnteredBy.label","Req Entered By"},
		{"eST.ReqAuthorisedBy.label","Req Authorised By"},
		{"eST.IssueAuthorisedBy.label","Issue Authorised By"},
		{"eST.issueref.label","Issue Ref"},
		{"eST.ReqDocDate.label","Req Doc Date"},
		{"eST.RequestQtyin.label","Request Qty In"},
		{"eST.issuom.label","Iss UOM"},
		{"eST.IssueQty{ISSUOM}.label","Issue Qty{ISSUOM}"},
		{"eST.IssueQtyStkUOM.label","Issue Qty Stk UOM"},
		{"eST.QuantityPrepared.label","Quantity Prepared"},
		{"eST.QtyUsed.label","Qty Used"},
		{"eST.QtyValue.label","Qty Value"},
		{"eST.BinDescription.label","Bin Description"},
		{"eST.IssueToStore.label","Issue To Store"},
		{"eST.IssueFromStore.label","Issue From Store"},
		{"eST.AdjQty.label","Adj Qty"},
		{"eST.Adjcost.label","Adj Cost"},
		{"eST.BatchQty.label","Batch Qty"},
		{"eST.ToItemCode.label","To Item Code"},
		{"eST.ToExpiryDate.label","To Expiry Date"},
		{"eST.Repackeddate.label","Repacked Date"},
		{"eST.StockItemYN.label","StockItem YN"},
		{"eST.IssueValue.label","Issue Value"},
		{"eST.AdjustQty.label","Adjust Qty"},
		{"eST.HomeCarepatients.label","Home Care patients"},
		{"eST.StoreSubTotal.label","Store Sub Total"},
		{"eST.PayabAmt.label","Payab Amt"},
		{"eST.chargeAmt.label","Charge Amt"},
		{"eST.FolioAtBatchPrice.label","Folio At Batch Price"},
		{"eST.InpatientSaleApplicable.label","Inpatient Sale Applicable"},
		{"eST.OutpatientSaleApplicable.label","Outpatient Sale Applicable"},
		{"eST.ReferralSaleApplicable.label","Referral Sale Applicable"},
		{"eST.ItemClassFrom.label","Item Class From"},
		{"eST.CutOffRangeforA.label","Cut Off Range for A"},
		{"eST.CutOffRangeforB.label","Cut Off Range for B"},
		{"eST.CutOffRangeforC.label","Cut Off Range for C"},
		{"eST.MinimumStock.label","Minimum Stock"},
		{"eST.NoOfItems.label","No Of Items"},		
		{"eST.NoOfTransactions.label","No. Of Transactions"},
		{"eST.ItemClassTotal.label","Item Class Total"},
		{"eST.ItemTotal.label","Item Total"},
		{"eST.UpTo.label","Up To"},
		{"eST.Above.label","Above"},
		{"eST.FortheFollowingIndicator.label","For the Following Indicator"},
		{"eST.AnnualTurnOverRateOfStocks.label","Annual Turn-Over Rate Of Stocks"},
		{"eST.AnnualValueOfStocksIssued.label","Annual Value Of Stocks Issued"},
		{"eST.ValueOfStocksHeldAnnually.label","Value Of Stocks Held Annually"},
		{"eST.AnnualTurnOverRateofStocks.label","Annual Turn Over Rate of Stocks"},
		{"eST.ValueOfStocksHeldon1stJanValueOfStocksHeldOn31stDecOfTheSameYear.label","{Value Of Stocks Held on 1stJan+Value Of Stocks Held On 31stDec Of The Same Year}/2"},
		{"eST.ThisformistobesenttostatePharmacyDivisioneveryYear.label","This form is to be sent to state Pharmacy Division every Year"},
		{"eST.JanDecby15thJan.label","Jan-Dec-by 15th Jan"},
		{"eST.JanDecby31stJan.label","Jan-Dec-by 31st Jan"},
		{"eST.ThisStatePharmacyDivisionwillsendthisformtostatePharmaceuticalServicesDivisioneveryYear.label","This State Pharmacy Division will send this form to state Pharmaceutical Services Division every Year"},
		{"eST.AssemblyItemCodeFrom.label","Assembly Item Code From"},
		{"eST.ChildItemCode.label","Child Item Code"},
		{"eST.ChildItemDescription.label","Child Item Description"},
		{"eST.ComponentQty.label","Component Qty"},
		{"eST.AssemblyItem.label","Assembly Item"},
		{"eST.ATCClassificationFrom.label","ATC Classification From"},
		{"eST.ConsumptionPeriodFrom.label","Consumption Period From"},
		{"eST.ComplaintBy.label","Complaint By"},
		{"eST.ClassTotal.label","Class Total"},
		{"eST.ClassCode.label","Class Code"},
		{"eST.ClassDescription.label","Class Description"},
		{"eST.AsonReportDateExpiredStock.label","As on Report Date Expired Stock"},
		{"eST.TotalStockValue.label","Total Stock Value"},
		{"eST.CutOfDateFrom.label","Cut Of Date From"},
		{"eST.ItemClassStockValue.label","Item Class Stock Value"},
		{"eST.EXPIRYINGBETWEEN.label","Expiring Between"},
		{"eST.MoveYearFrom.label","Move Year From"},
		{"eST.StockValueReceived.label","Stock Value Received"},
		{"eST.NumberofItemReceived.label","Number of Item Received"},
		{"eST.ValueofItemSupplied.label","Value of Item Supplied"},
		{"eST.StockValueAtDec31.label","Stock Value At Dec31"},
		{"eST.ValueDisposed.label","Value Disposed"},
		{"eST.NoofChecksbyStockVerificationBoard.label","No of Checks by Stock Verification Board"},
		{"eST.NumberofGRNs.label","Number of GRNs"},
		{"eST.IssuingStoreFrom.label","Issuing Store From"},
		{"eST.Add/ModifyItem.label","Add/Modify Item"},
		{"eST.KitTemplateCode.label","Kit Template Code"},
		{"eST.KitTemplateDescription.label","Kit Template Description"},
		{"eST.ViewCostDetails.label","View Cost Details"},
		{"eST.ViewSalePriceDetails.label","View SalePrice Details"},
		{"eST.NoofrecordsperTransaction.label","No. of records per Transaction"},
		{"eST.MachineCodeFrom.label","Machine Code From"},
		{"eST.PartNoFrom.label","Part No From"},
		{"eST.NonInventory.label","Non Inventory"},
		{"eST.YtdRecp.label","Ytd Recp"},
		{"eST.YtdConsm.label","Ytd Consm"},
		{"eST.MachCode.label","Mach Code"},
		{"eST.PreviousQty.label","Previous Qty"},
		{"eST.ConsignmentYN.label","Consignment Y/N"},
		{"eST.InsuranceYN.label","Insurance Y/N"},
		{"eST.PhysicalInvType.label","Physical Inv Type"},
		{"eST.ManufacturedItems.label","Manufactured Items"},
		{"eST.UseafterexpiryYN.label","Use after expiry Y/N"},
		{"eST.NetStockPosition.label","Net Stock Position"},
		{"eST.UnitCostFrom.label","Unit Cost From"},
		{"eST.StockPosition.label","Stock Position"},
		{"eST.StockValueFrom.label","Stock Value From"},
		{"eST.NoofStores.label","No of Stores"},
		{"eST.NetQty.label","Net Qty"},
		{"eST.Part.label","Part"},
		{"eST.IndicatesSuspendedBatch.label","Indicates Suspended Batch"},
		{"eST.BatchStatus.label","Batch Status"},
		{"eST.NonReorderableStoresStock.label","Non Reorderable Stores Stock"},
		{"eST.ItemBelowMinimumLevel.label","Item Below Minimum Level"},
		{"eST.ItemsBelowReorderLevel.label","Items Below Reorder Level"},
		{"eST.ClearenceBalance.label","Clearence Balance"},
		{"eST.PresentStock.label","Present Stock"},
		{"eST.ReorderValue.label","Reorder Value"},
		{"eST.LastReceiptDate.label","Last Receipt Date"},
		{"eST.LastCost.label","Last Cost"},
		{"eST.NonSpecialItemOnly.label","Non Special Item Only"},
		{"eST.SpecialItemOnly.label","Special Item Only"},
		{"eST.IssuedItem.label", "Issued Item"},
		{"eST.TRN.label", "TRN"},
		{"eST.TrnQty.label", "TRN Qty"},
		{"eST.LastDate.label","Last Date"},
		{"eST.AlphaCodeFrom.label", "Alpha Code From"},
		{"eST.Issued.label", "Issued"},
		{"eST.AvgQty.label", "Avg Qty"},
		{"eST.DeviationPercentage.label","Deviation Percentage"},
		{"eST.Last12MonthsConsumption.label","Last 12 Months Consumption"},
		{"eST.PrevYear12MonthsConsumption.label","Prev Year 12 Months Consumption"},
		{"eST.SupressZero.label","Supress Zero"},
		{"eST.ExcludeExStore.label","Exclude Ex Store"},
		{"eST.VariancePostedBy.label","Variance Posted By"},
		{"eST.StartQty.label","Start Qty"},
		{"eST.PhyStock.label","Phy Stock"},
		{"eST.VarQtypve.label","Var Qty {+}ve"},
		{"eST.VarQtynve.label","Var Qty {-}ve"},
		{"eST.VarValuepve.label","Var Value {+}ve"},
		{"eST.VarValuenve.label","Var Value {-}ve"},
		{"eST.TrnQtyForPeriod.label","Trn Qty For Period"},
		{"eST.NoofItemsSupplied.label","No of Items Supplied"},
		{"eST.StockTurnOverRate.label","Stock Turn Over Rate"},
		{"eST.NoofItemDisposed.label","No of Item Disposed"},
		{"eST.MoveYear.label","Move Year"},
		{"eST.ClosingStock.label","Closing Stock"},
		{"eST.TurnoverRate.label","Turn over Rate"},
		{"eST.Last.label","Last"},
		{"eST.EarliestExpiryDate.label","Earliest Expiry Date"},
		{"eST.TotalCondemnID.label","Total Condemn ID"},
		{"eST.PercentageonExpiryStock.label","Percentage on Expiry Stock"},
		{"eST.NumberofFinalizedGRNs.label","Number of Finalized GRNs"},
		{"eST.NumberofUnfinalizedGRNs.label","Number of Unfinalized GRNs"},
		{"eST.MfgDate.label","Mfg Date"},
		{"eST.UserFrom.label","User From"},
		{"eST.CancelledPhysicalCountSheet.label","Cancelled Physical Count Sheet"},
		{"eST.CancelDate.label","Cancel Date"},
		{"eST.EmployeeName.label","Employee Name"},
		{"eST.Percent.label","Percent"},
		{"eST.SummaryfortheItemClass.label","Summary for the Item Class"},
		{"eST.NumberofItemsCounted.label","Number of Items Counted"},
		{"eST.ValueasperPhysicalInventory.label","Value as per Physical Inventory"},
		{"eST.NumberofItemswithpveVariance.label","Number of Items with (+)ve Variance"},
		{"eST.NumberofItemswithnveVariance.label","Number of Items with (-)ve Variance"},
		{"eST.TotalVarianceValue.label","Total Variance Value"},
		{"eST.SummaryofClasses.label","Summary of Classes"},
		{"eST.PhysicalIdTotal.label","Physical Id Total"},
		{"eST.TotalPhysicalInventoryID.label","Total Physical Inventory ID"},
		{"eST.PositiveVariance.label","Positive Variance"},
		{"eST.NegativeVariance.label","Negative Variance"},
		{"eST.NetVariance.label","Net Variance"},
		{"eST.ZeroVariance.label","Zero Variance"},
		{"eST.CountSheet.label","Count Sheet"},
		{"eST.Expirable.label","Expirable"},
		{"eST.PercentageOnPresentCount.label","Percentage On Present Count"},
		{"eST.AutoBatchGenerationYN.label","Auto Batch Generation Y/N"},
		{"eST.BatchIDSeries.label","Batch ID Series"},
		{"eST.NextBatchID.label","Next Batch ID"},
		{"eST.TotalnoofLocationCode.label","Total no of Location Code"},
		{"eST.Yield.label","Yield"},
		{"eST.ItemRequested.label","Item Requested"},
		{"eST.RepackingCode.label","Repacking Code"},
		{"eST.RequestedQtyinReqUOM.label","RequestedQty(inReqUOM}"},
		{"eST.RequestedQtyinStkUOM.label","RequestedQty(inStkUOM}"},
		{"eST.CommitedQty.label","Commited Qty"},
		{"eST.Receipts.label","Receipts"},
		{"eST.ReceiptQty.label","Receipt Qty"},
		{"eST.ReplacementCompleted.label","Replacement Completed"},
		{"eST.NoofReqStores.label","No.of ReqStores"},
		{"eST.NoofRequests.label","No.of Requests"},
		{"eST.NoofCompletedRequests.label","No.ofCompletedRequests"},
		{"eST.NoofPendingRequests.label","No.ofPendingRequests"},
		{"eST.NoofCancelRequests.label","No.ofCancelRequests"},
		{"eST.PercentageonCompletedRequests.label","Percentage on Completed Requests"},
		{"eST.NoofItemsRequested.label","No of Items Requested"},
		{"eST.NoofItemsCompletelyIssued.label","No.of ItemsCompletelyIssued"},
		{"eST.NoofItemsPartiallyIssued.label","No.of ItemsPartiallyIssued"},
		{"eST.PercentageonCompletelyIssued.label","Percentage on Completely Issued"},
		{"eST.ItemCost.label","Item Cost"},
		{"eST.GRNRef.label","GRN Ref"},
		{"eST.StockValueReceivedRM.label","StockValueReceived (RM}"},
		{"eST.ValueofItemSuppliedRM.label","ValueofItemSupplied(RM}"},
		{"eST.NumberofItemCondemnedRM.label","NumberofItemCondemned(RM}"}, 
		{"eST.ValueCondemned.label","Value Condemned"},
		{"eST.NumberOfQualityComplaints.label","Number Of Quality Complaints"},
		{"eST.CheckStockLevel.label","Check Stock Level"},
		{"eST.TransactionAllowed.label","Transaction Allowed"},
		{"eST.BinChange.label","Bin Change"},
		{"eST.AuthorizeAtIssueStore.label","Authorize At Issue Store"},
		{"eST.CondemnExpiryBatches.label","Condemn Expiry Batches"},
		{"eST.RequestIssues.label","Request Issues"},
		{"eST.PendingRequest.label","Pending Request"},
		{"eST.WardUnitSupply.label","Ward/Unit Supply"},
		{"eST.DrugManufacturing.label","Drug Manufacturing"},
		{"eST.PrepackedDrug.label","Prepacked Drug"},
		{"eST.SatellitePharmacy.label","Satellite Pharmacy"},
		{"eST.NoofPack.label","No of Pack"},
		{"eST.NoItem.label","No Item"},
		{"eST.NoPack.label","No Pack"},
		{"eST.Tablet.label","Tablet"},
		{"eST.NoofStaff.label","No of Staff"},
		{"eST.Atten.label","Atten"},
		{"eST.PharAsst.label","Phar Asst"},
		{"eST.NoofWardUnit.label","No. of Ward/Unit"},
		{"eST.UnitofUse.label","Unit of Use"},
		{"eST.Traditional.label","Traditional"},
		{"eST.MFGRequest.label","MFG Request"},
		{"eST.ItemTobeManufactured.label","Item To be Manufactured"},
		{"eST.ProcessLossPercent.label","Process Loss Percent"},
		{"eST.PrepareType.label","Prepare Type"},
		{"eST.ExpectedOutput.label","Expected Output"},
		{"eST. MFGStore.label","MFG Store"},
		{"eST.RequestedQty.label","Requested Qty"},
		{"eST.ActualOutput.label","Actual Output"},
		{"eST.Constituent.label","Constituent"},
		{"eST.TimeTakenForPreparation.label","Time Taken For Preparation"},
		{"eST.Repackedat.label","Repacked at"},
		{"eST.ItemToBePacked.label","Item To Be Packed"},
		{"eST.SourceBatch.label","Source Batch"},
		{"eST.ExpectedBalance.label","Expected Balance"},
		{"eST.ActualQty.label","Actual Qty"},
		{"eST.ActualBal.label","Actual Bal"},
		{"eST.ProductIdentification.label","Product Identification"},
		{"eST.TimeTakenforRepacking.label","Time Taken for Repacking"},
		{"eST.HighestValueofPurchaseForAPPLDrugs.label","Highest Value of Purchase For APPL Drugs"},
		{"eST.HighestValueofPurchaseForNONAPPLDrugs.label","HighestValueofPurchaseForNON-APPLDrugs"},
		{"eST.TotalPurchasedQuantity.label","Total Purchased Quantity"},
		{"eST.PriceUnitRM.label","Price/Unit(RM}"},
		{"eST.APPL.label","APPL"},
		{"eST.NONAPPL.label","NON-APPL"},
		{"eST.APPLNONAPPL.label","APPL & NON-APPL"},
		{"eST.PrintNilStockItems.label","Print Nil Stock Items"},
		{"eST.NonStockItem.label","Non-Stock Item"},
		{"eST.ROQty.label","RO Qty"},
		{"eST.DirectSales.label","Direct Sales"},
        {"eST.InternalReportsReprint.label","Internal Reports Reprint"},
        {"eST.ValueasperSystem.label","Value as per System"},
		{"eST.NumberofItemswithvarriance.label","Number of Items with variance"},
		{"eST.NilStockItems.label","Nil Stock Items"},
      	{"eST.TotalNoOfRepackingGroups.label","Total No Of Repacking Groups"},
        {"eST.IssuedItemQty.label","Issued Item Qty"},
        {"eST.MaximumStock.label","Maximum Stock"},
        {"eST.IssueReturn.label","Issue Return"},
        {"eST.SalesReturn.label","Sales Return"},
		{"eST.ItemsWithZeroAuthorizedQuantity.label","Items With Zero Authorized Quantity"},
		{"eST.Exp.label","Exp"},
		{"eST.Referrals.label","Referrals"}	,	
		{"eST.PartNumber.label","Part Number"},
		{"eST.RepackedProduct.label","Repacked Product"},
		{"eST.ProductDescription.label","Product Description"},
		{"eST.PayableAmount.label","Payable Amount"},
		{"eST.Patient.label","Patient"},
		{"eST.CancelRequestBy.label","Cancel Request By"},
		{"eST.RaisedBy.label","Raised By"},
		{"eST.ActionType.label","Action Type"},
		{"eST.Acknowledge.label","Acknowledge"},
		{"eST.Show.label","Show"},
		{"eST.CopyValues.label","Copy Values"},
		{"eST.BillDate.label","Bill Date"},
		{"eST.BillNo.label","Bill No"},
		{"eST.RegNo.label","Reg No"},
		{"eST.SalePriceApplicable.label","Sale Price Applicable"},
		{"eST.MRPGreaterThanUnitPrice.label","MRP Greater Than Unit Price"},
        {"eST.CategoryDrugNonDrug.label", "Category(Drug / Non Drug)"},
		{"eST.NameofItems.label","Name of Items"},
		{"eST.DateOfPurchaseReceive.label","Date Of Purchase/Receive"},
		{"eST.PeriodUsed.label","Period Used"},
		{"eST.PurchasingValue.label","Purchasing Value"},
		{"eST.CurrentValue.label","Current Value"},
		{"eST.RemarksCommentsbyInspectionBoard.label","Remarks/Comments by Inspection Board"},
		{"eST.RecommendationbyBoardofCondemn.label","Recommendation by Board of Condemn"},
		{"eST.AuthorizedDate.label", "Authorized Date"},
		{"eST.POCost.label", "PO Cost"},
		{"eST.PODiscount.label", "PO Discount"},
		{"eST.SalePrice.label", "Sale Price"},
		{"eST.RevisedSalePrice.label", "Revised Sale Price"},
		{"eST.SalePriceHistory.label", "Sale Price History"},
		{"eST.SalePriceStatusHistory.label", "Sale Price Status History"},
		{"eST.ModifiedDate.label", "Modified Date"},
		{"eST.Tax.label", "Tax"},
		{"eST.ConfirmAmmendedSalePrice.label", "Confirm Ammended Sale Price"},
		{"eST.SalePriceOnceAmmendedCanNotBeChanged.label", "Sale Price Once Ammended Can Not Be Changed"},
		{"eST.ReturnAllowed.label", "Return Allowed"},
		{"eST.nursingunit/clinic.label", "Nursing Unit/Clinic"},
		{"eST.InterfacetoexternalPO.label", "Interface to external PO"},
		{"eST.PurchaseOrderRequest.label", "Purchase Order Request"},
		{"eST.PORequest.label", "PO Request"},
		{"eST.PORequestFinalize.label", "PORequest Finalize"},
		{"eST.ToDepartment.label", "To Department"},
		{"eST.GeneratePORequestBy.label","Generate PO Request By"},
		{"eST.PendingForApproval.label","Pending For Approval"},
		{"eST.RequestRejectedbyPODept.label","Request Rejected by PO Dept"},
		{"eST.RequestReceivedPartially.label","Request Received Partially"},
		{"eST.RequestReceivedCompletely.label","Request Received Completely"},
		{"eST.RequestCancelled.label","Request Cancelled"},
		{"eST.RequestOnDepartment.label","Request On Department"},
		{"eST.NewBatchYN.label", "New Batch(Yes/No)"},
		{"eST.ScheduleCode.label", "Schedule Code"},
		{"eST.StartingFrom.label", "Starting From"},
		{"eST.AutoAuthorised.label", "Auto Authorised ?"},
		{"eST.SchduleDescription.label", "Schedule Description"},
		{"eST.SchduleCreatedBy.label", "Schedule Created By"},
		{"eST.AutoRequest.label", "Auto Request"},
		{"eST.ByCost.label", "By Cost"},
		{"eST.Avgconslast2months.label", "Average Cons. Last 2 Months"},
		{"eST.MRP.label", "MRP"},
		{"eST.Nonreorderstock.label", "Non Reorder Stock"},
		{"eST.reference.label", "Reference"},
		{"eST.beyondusedate.label", "Beyond Use Date"},
		{"eST.PhysicalCountforBatchQty.label", "Physical Count for Batch Qty"},
		{"eST.StockItemValue.label", "Stock Item Value"},
		{"eST.ZeroQuantity.label", "Zero Quantity"},
		{"eST.NonZeroquantity.label", "Quantity > 0"},
		{"eST.DisplayItemQuantity.label", "Display Item Quantity"},
		{"eST.NormalIssues.label", "Normal Issues"},
		{"eST.ToStoreBin.label","To Store Bin"},
		{"eST.UrgentIssues.label", "Urgent Issues"},
		{"eST.DeletionDateTime.label", "Deletion Date Time"},
		{"eST.DeletedBy.label", "Deleted By"},
		{"eST.Confirm.label", "Confirm"},
		{"eST.VendorReturnDelete.label" ,"Vendor Return Delete"},
		{"eST.RequisitionIssuesDelete.label","Requisition Issues Delete"},
		{"eST.IssueReturnsDelete.label","Issue Returns Delete"},
		{"eST.StockAdjustmentDelete.label","Stock Adjustment Delete"},
		{"eST.ProductTransferDelete.label","Product Transfer Delete"},
		{"eST.SalesDelete.label","Sales delete"},
		{"eST.GoodsReceiptDelete.label","Goods Receipt delete"},
		{"eST.StockTransferDelete.label","Stock Transfer delete"},
		{"eST.RequisitionDelete.label","Requisition Delete"},
		{"eST.UrgentIssueDelete.label","Urgent Issue Delete"},
		{"eST.ManufacturingDelete.label","Manufacturing Delete"},
		{"eST.SalesReturnDelete.label","Sales Return Delete"},
		{"eST.PORequestdelete.label", "PO Request Delete"},
		{"eST.PositiveAdjustment.label", "Positive Adjustment"},
		{"eST.AcknowledgementFor.label","Acknowledgement For"},
		{"eST.GRNBatchesOnly.label","GRN Batches Only"},
		{"eST.ApplicableBatchesInPhysicalInventoryEntry.label","Applicable Batches In Physical Inventory Entry"},
		{"eST.DisplayBatchlookupinPhysicalInventoryEntryEntry.label","Display Batch lookup in Physical Inventory Entry"},
		{"eST.IssueReqUrg.label","Issue(Req/Urg)"},
		{"eST.CondemnDate.label","Condemn Date"},
		{"eST.CurrentPendingRequests.label","Current Pending Requests"},
		{"eST.DocumentNo.label","Document No"},
		{"eST.Discard.label","Discard"},
		{"eST.EDClass.label","ED Class"},
		{"eST.Goods.label", "Goods"},
		{"eST.StoreGroup.label", "Store Group"},
		{"eST.DrugNonDrug.label", "Drug/Non Drug"},
		{"eST.Cost.label", "Cost"},
		{"eST.BatchNumber.label", "Batch Number"},
		{"eST.StoreSupplier.label", "Store/Supplier"},
		{"eST.QtyIssued.label", "Qty Issued"},
		{"eST.BaseUnit.label", "Base Unit"},
		{"eST.ReservedQty.label", "Reserved Qty"},
		{"eST.ProductComplaintFormForPharmaceuticalProductsRegisteredWithDrugControlAuthority.label","Product Complaint Form For Pharmaceutical Products Registered With Drug Control Authority"},
		{"eST.NameOfProduct.label","Name Of Product"},
		{"eST.RegistrationNumber.label","Registration Number"},
		{"eST.NameandAddressofSupplier.label","Name and Address of Supplier"},
		{"eST.StorageConditionsOfTheAffectedRegisteredProducts.label","Storage Condition(s) Of The Affected Registered Product(s)"},
		{"eST.FullDescriptionOfComplaintShouldmorespaceneededattachseparatenotes.label","Full Description Of Complaint (Should more space needed, attach separate notes)"},
		{"eST.PleaseSendTheAffectedRegisteredProductTogetherWithThisComplaintForm.label","Please Send The Affected Registered Product Together With This Complaint Form"},
		{"eST.ParticularsOfReporter.label","Particulars Of Reporter"},
		{"eST.PlaceOfWork.label","Place Of Work"},
		{"eST.Pleasesendto.label","Please send to"},
		{"eST.Occupation.label","Occupation"},
		{"eST.ShowBatches.label","Show Batches"},
		{"eST.CondemnExpiredBatches.label","Condemn Expired Batches"},
		{"eST.ChangeBinLocation.label","Change Bin Location"},
		{"eST.CondemnQty.label","Condemn Qty"},
		{"eST.FullyAuthorizedIssuedatIssueStore.label","Fully Authorized/Issued at Issue Store"},
		{"eST.PartiallyAuthorisedIssuedAtIssueStore.label","Partially Authorised/Issued At Issue Store"},
		{"eST.PartiallyAuthorisedatIssueStore.label","Partially Authorised at Issue Store"},
		{"eST.FullyAuthorisedPartiallyIssuedAtIssueStore.label","Fully Authorised/Partially Issued At Issue Store"},
		{"eST.FullyAuthorizedatIssueStore.label","Fully Authorized at Issue Store"},
		{"eST.IssueClosed.label","Issue Closed"},
		{"eST.RequestEnteredAtRequestStore.label","Request Entered At Request Store"},
		{"eST.AuthorisedAtRequestingStore.label","Authorised At Requesting Store"},
		{"eST.SalesDocNo.label","Sales Doc.No"},
		{"eST.MTDConsQty.label","MTD Cons Qty"},
		{"eST.SterilizableYN.label","Sterilizable YN"},
		{"eST.ItemClassTo.label","Item Class To"},
		{"eST.NonDrug.label","Non Drug"},
		{"eST.YTDIssueQty.label","YTD Issue Qty"},
		{"eST.AcknowledgeDateFrom.label","Acknowledge Date From"},
		{"eST.AcknowledgeDateTo.label","Acknowledge Date To"},
		{"eST.Zero.label","Zero"},
		{"eST.RejectQty.label","Reject Qty"},
		{"eST.NonZero.label","Non Zero"},
		{"eST.MFGReceive.label" ,  "MFG Receive"},
		{"eST.AckDate.label" ,  "Ack.Date"},
		{"eST.IssuedQty.label" ,  "Issued Qty"},
		{"eST.PendingAckQty.label" ,  "Pending Ack.Qty"},
		{"eST.ReceivedQty.label" ,  "Received Qty"},
		{"eST.RejectedQty.label" ,  "Rejected Qty"},
		{"eST.PendingConf.label" ,  "Pending Conf"},
		{"eST.Remarks/BatchDetails.label" ,  "Remarks/Batch Details"},
		{"eST.MultipleBatchesExist.label" ,  "Multiple Batches Exist"},
		{"eST.PromptAlertforPreferredItem.label" ,  "Prompt Alert for Preferred Item"},
		{"eST.KitTemplateUOM.label" ,  "Kit Template UOM"},
		{"eST.MTDIssueQty.label","MTD Issue Qty"},
		{"eST.MTDReceiptsQty.label","MTD Receipts Qty"},
		{"eST.DrugMedicalSupply.label","Drug/Medical Supply"},
		{"eST.MedicalSupply.label","Medical Supply"},
		{"eST.UserAccessStores.label","User Access to Stores"},
		{"eST.RestrictViewingStockStatus.label","Restrict Viewing Stock Status"},
		{"eST.MovementCalculateBy.label","Movement Calculate By"},
		{"eST.IssuetononStockitem.label","Issue to non Stock item"},
		{"eST.IssueStockNonstock.label","Issue ( Stock + Non stock)"},
		{"eST.IssuetoNonStockItem.label","Issue to Non Stock Item"},
		{"eST.MovementCutoffDaysSlotRange.label","Movement Cutoff Days {Slot Range}"},
		{"eST.ReceiveType.label","Receive Type"},
		{"eST.RejectQuantity.label", "Reject Quantity"},
		{"eST.AverageUsageCalculateBy.label","Average Usage Calculate By"},
		{"eST.SaleIssue.label","Sale + Issue"},
		{"eST.RequestOnStore.label","Request On Store"},
		{"eST.ItemNature.label","Item Nature"},
		{"eST.ItemClassSelection.label","Item Class Selection"},
		{"eST.AssemblyInstruction.label","Assembly Instruction"},
		{"eST.SuppliedBy.label","Supplied By"},
		{"eST.ReturnDate.label","Return Date"},
		{"eST.ReturnStore.label","Return Store"},
		{"eST.ReturnDateFrom.label","Return Date From"},
		{"eST.ReturnDateTo.label","Return Date To"},
		{"eST.SeqNo.label","Seq.No"},
		{"eST.ItemClassWise.label","Item Class Wise"},
		{"eST.PendingAck.label" ,  "Pending Ack."},
		{"eST.GrandTotalForReorderValue.label","Grand Total For Reorder Value"},
		{"eST.Last2MonthAVGCon.label","Last 2 Month AVG Con."},
		{"eST.NonReorderableStore.label","Non Reorderable Store"},
		{"eST.PackageItem.label", "Package Item"},
		{"eST.BaseUOM.label", "Base UOM"},
		{"eST.ConvFactorRule.label","Conv Factor/Rule"},
		{"eST.GRNDocNo.label","GRN Doc No"},
		{"eST.BaseUOMQuantity.label","Base UOM Quantity"},
		{"eST.BaseUOMCode.label","Base UOM Code"},
		{"eST.EquivalentUOMQuantity.label","Equivalent UOM Quantity"},
		{"eST.EquivalentUOMCode.label","Equivalent UOM Code"},
		{"eST.BillingNature.label","Billing Nature"},
		{"eST.Cash.label","Cash"},
		{"eST.Credit.label","Credit"},
		{"eST.Sponsor.label","Sponsor"},
		{"eST.ByOtherStore.label","By Other Store"},
		{"eST.SalesDocTpe.label","Sales Doc.Type"},
		{"eST.noofdrugsmedicalsold.label","No. of Drugs/Medical Sold"},
		{"eST.BillNature.label","Bill Nature"},
		{"eST.totalnoofsale.label","Total No. of Sales"},
		{"eST.totalcostprice.label","Total Cost Price"},
		{"eST.costprice.label","Cost Price"},
		{"eST.saleprice.label","Sale Price"},
		{"eST.customername.label","Customer Name"},
		{"eST.Priority.label","Priority"},
		{"eST.Req.SaleQuantity.label","Req. Sale Quantity"},
		{"eST.PendingSaleQuantity.label","Pending Sale Quantity"},
		{"eST.TRNtype.label","TRN Type"},
		{"eST.TotalClosingBalanceItemClass.label","Closing Balance By Item Class"},
		{"eST.NoofTransactionGrandTotal.label","No Of Transactions - Grand Total"},
		{"eST.TotalClosingBalanceItem.label", "Closing Balance By Item"},
		{"eST.SaleIssueValueBaht.label", "Sale Issue Value (Baht)"},
		{"eST.SaleReturnValueBaht.label", "Sale Return Value (Baht)"},
		{"eST.FullyIssued.label","Fully Issued"},
		{"eST.PartiallyIssued.label","Partially Issued"},
		{"eST.NotIssued.label","Not Issued"},
		{"eST.PatientPayableAmount.label","Patient Payable Amount"},
		{"eST.RefundAmount.label","Refund Amount"},
		{"eST.AllStores.label", "All Stores"},
		{"eST.ReorderableStoresStock.label","Reorderable Stores stock"},
		{"eST.NonReorderableStoresStock.label","Non Reorderable Stores Stock"},
		{"eST.ItemDesc.label","Item Desc"},
		{"eST.OnHandValue.label","On Hand Value"},
		{"eST.AccountingPeriodStart.label","Accounting Period (Start)"},
		{"eST.AccountingPeriod.label","Accounting Period"},
		{"eST.Accounting.label","Accounting "},
		{"eST.Supplier wise Sales and Consumption Report.label","Supplier wise Sales and Consumption Report"},
		{"eST.Supplier Wise Stock Report.label","Supplier Wise Stock Report"},
		{"eST.Product/Batch Wise Report.label","Product/Batch Wise Report"},
		{"eST.Transaction Register For The Period.label","Transaction Register For The Period"},
		{"eST.SalesReturnDetails.label","Sales Return Details "},
		{"eST.TransactionDetails.label","Transaction Details "},
		{"eST.Both.label","Both "},
		{"eST.VAT.label","VAT"},
		{"eST.PickSlip.label","Pick Slip "},
		{"eST.DefaultItemSearchBy.label","Default Item Search By "},
		{"eST.DefaultItemSearch.label","Default Item Search "},
		{"eST.SaleRefNo.label","SaleRefNo."},
		{"eST.ReturnQuantity.label","Return Quantity"},
		{"eST.ReturnValue.label","Return Value"},
		{"eST.RefNo.label","Ref. No."},
		{"eST.Quantity.label","Quantity"},
		{"eST.Sales/Return Value.label","Sales/Return Value"},
		{"eST.BarCodeId.label","BarCode ID"},
		{"eST.ByItemDatewiseDetail.label","By Item-DateWise(Detail)"},
		{"eST.ByItemDatewiseSummary.label","By Item-DateWise(Summary)"},
		{"eST.ExtRefNo.label","Ext Ref No"},
		{"eST.InterfaceToThirdParty.label","Interface To ThirdParty"},
		{"eST.ExpiryDate.label","Expiry Date"},
		{"eST.DefaultSaleType.label","Default Sale Type"},  // Added by Padmapriya
		{"eST.ItemAlphaCode.label","Item Alpha Code"},   // Added by Padmapriya
		{"eST.DosageForm.label","Dosage Form"},			// Added by Padmapriya
		{"eST.ByItemAlphaCode.label","By Item Alpha Code"},
		{"eST.ByGenericName.label","By Generic Name"},
		{"eST.ByDosageForm.label","By Dosage Form"},
		{"eST.SortOrderBy.label","Sort Order By"},
		{"eST.Date.label","Date"}, 
		{"eST.Margin.label","Margin"}, 
		{"eST.Ascending.label","Ascending"}, 
		{"eST.Descending.label","Descending"}, 
		{"eST.UnitValue.label","Unit Value"}, 
		{"eST.QOH.label","QOH"},
		{"eST.SourceItemBatchId.label","Source Item Batch ID"},
		{"eST.SortOptionForUOM.label","Sort Option For UOM"},
		
		
		//Added By sakti Sankar on 03/05/2012 against inc#29972
		{"eST.GenerateBarCode.label","Generate Barcode"},	
		{"eST.Manually.label","Manually"},
		{"eST.SystemGenerated.label","System Generated"},
		{"eST.PredefinedRules.label","Predefined Rules"},
		{"eST.AllElements.label","All Elements"},
		{"eST.BarCodeElements.label","Barcode Elements"},
		{"eST.FacilityId.label","FACILITY ID"},
		{"eST.TradeId.label","TRADE ID"},
		{"eST.ManufacturerId.label","MANUFACTURER ID"},	
		{"eST.SupplierId.label","SUPPLIER ID"},
		{"eST.StoreCode.label","STORE CODE"},
		{"eST.BinLocation.label","BIN LOCATION"},
		{"eST.MRP.label","MRP"},
		{"eST.ItemCode.label","ITEM CODE"},
		{"eST.BatchId.label","BATCH ID"},
		{"eST.ExpiryDate.label","EXPIRY DATE"},
		{"eST.SequenceSelection.label","Sequence Selection For Predefined Rules"},

		
		
		// For Purchase Order Module
		
		{"eST.TermsAndCondDesc.label","Terms And Conditions Description"}, 
		{"eST.TermsAndCondCode.label","Terms And Conditions Code"}, 
		
		{"eST.MasterType.label","Master Type"}, 
		{"eST.MasterCode.label","Master Code"}, 
		{"eST.MasterCodeDesc.label","Master Code Description"}, 
		
		{"eST.DefDocNoGenerationRule.label","Default Document Number Generation Rule"}, 
		{"eST.AutogenerateDocNo.label","Autogenerate Document Number"}, 
		{"eST.ManualEntry.label","Manual Entry"}, 
		
		{"eST.DefPurReqStr.label","Default Purchase Request Store"}, 
		{"eST.DefPurDept.label","Default Purchase Department"}, 
		
			
		{"eST.ItmLvlOrdApReq.label","Item Label Order Approval Required"}, 
		{"eST.AlowOvOrDelDt.label","Allow Override Of Order Delivery Date"}, 
		{"eST.AlowOvOrQtRe.label","Allow Override Of Order Quantity During Receiving"}, 
		{"eST.AlowOvOrPrRe.label","Allow Override Of Order Price During Receiving"}, 
		
		{"eST.PurchaseRequest.label","Purchase Request"}, 
		{"eST.PurchaseOrder.label","Purchase Order"}, 
		{"eST.PurchaseUnit.label","Purchase Unit"}, 
		{"eST.PurchaseUnitCode.label","Purchase Unit Code"}, 
		{"eST.PurchaseUnitDesc.label","Purchase Unit Description"}, 
			
		{"eST.GlobalUnit.label","Global Unit"}, 	
		{"eST.DeptNo.label","Department Number"}, 
		{"eST.AccNo.label","Account Number"}, 
		{"eST.FromDate.label","From Date"}, 
		{"eST.ToDate.label","To Date"}, 
		
		{"eST.PORaisedBy.label","Purchase Unit"}, 
		{"eST.POMode.label","PO Mode"}, 
		{"eST.PurchaseReqNo.label","Request No."}, 
		{"eST.BlanketPurchase.label","Blanket Purchase"} ,
		
		{"eST.OrderQty.label","Order Qty"}, 
		{"eST.UOM.label","UOM"}, 
		{"eST.UnitPrice.label","Unit Price"}, 
		{"eST.Value.label","Value"}, 
		{"eST.RequestQty.label","Request Quantity"}, 
		{"eST.DelDueDate.label","Delivery Due Date"}, 
		{"eST.DeptNo.label","Department No"}, 
		
		{"eST.Item.label","Item"}, 
		{"eST.ReqNo.label","Req No"},
		{"eST.ReqStore.label","Req Store"}, 
		{"eST.ReqFacility.label","Req Facility"}, 
		{"eST.ReqByStore.label","Req By Store"}, 
		{"eST.POQty.label","PO Quantity"}, 
		{"eST.Amount.label","Amount"}, 
		{"eST.DueDate.label","Due Date"}, 
		{"eST.Approval.label","Approval"}, 
		
		{"eST.ItemApproval.label","Item Approval"},
		
		{"eST.ApprovedBy.label","Approved By"}, 
		{"eST.ApprovalDate.label","Approval Date"}, 
		{"eST.ApprovalRefNo.label","Approval Ref No"}, 
		{"eST.Facility.label","Facility"},
		{"eST.PurchaseType.label","Purchase Type"}, 
		
		{"eST.BlanketPurchase.label","Blanket Purchase"} ,
		{"eST.TransactionCurrency.label","Transaction Currency"},
		{"eST.ExchangeRate.label","Exchange Rate"},
		{"eST.LocalCurrency.label","Local Currency"},
		{"eST.ValidUpto.label","Valid Upto"},
		{"eST.OrderRemarks.label","Order Remarks"},
		{"eST.ItemRemarks.label","Item Remarks"},
		{"eST.POCurrency.label","PO Currency"},
		{"eST.DeliveryScheduleDetails.label","Delivery Schedule Details"},
		{"eST.EnterItemDetails.label","Enter Item Details"},
		{"eST.OrderUOM.label","Order UOM"},
		{"eST.PurchasePrice.label","Purchase Price"},
		{"eST.GrossAmount.label","Gross Amount"},
		{"eST.DiscountType.label","Discount Type"},
		{"eST.Discount.label","Discount"},
		{"eST.NetAmount.label","Net Amount"},
		{"eST.DeptId.label","Department Id"},
		{"eST.CommitmentCode.label","Commitment Code"},
		{"eST.AcctNumber.label","Account No"},
		{"eST.AccNoDesc.label","Acct Description"},
		{"eST.ApprovalReference.label","Approval Reference"},
	
		{"eST.OldPurchaseOrderNo.label","Old Purchase Order No"},
		{"eST.PurchaseOrderDetails.label","Purchase Order Details"},
		{"eST.AdditionalDetails.label","Additional Details"},
		{"eST.AccountNumber.label","Supplier Account No"},

		//Added By sakti sankar for requirement in PO module
		{"eST.Create.label","Create"},
		{"eST.Cancel.label","Cancel"},
		{"eST.PurchaseRequest.label","Purchase Request"},
		{"eST.PurchaseOrder.label","Purchase Order"},
		{"eST.PurchaseUnit.label","Purchase Unit"},
		{"eST.PurchaseUnitDescription.label","Purchase Unit Description"},
		{"eST.PurchaseRequestCreate.label","Purchase Request Create"},
		{"eST.PurchaseRequestFinalize.label","Purchase Request Finalize"},
		{"eST.PurchaseRequestCancel.label","Purchase Request Cancel"},
		{"eST.PurchaseOrderCreate.label","Purchase Order Create"},
		{"eST.PurchaseOrderFinalize.label","Purchase Order Finalize"},
		{"eST.PurchaseOrderAmend.label","Purchase Order Amend"},
		{"eST.PurchaseOrderCancel.label","Purchase Order Cancel"},

		{"eST.AllowUnfinalizedGRNThroughInterface.label","Allow Unfinalized GRN Through Interface"},
		{"eST.DefaultInterfaceGRNValues.label","Default InterfaceGRN Values"},
		{"eST.Supplier.label","Supplier"},
		{"eST.TradeName.label","Trade Name"},
		{"eST.BinnLocation.label","Bin Location"},
		
		{"eST.TransactionType.label","Transaction Type"},
		{"eST.PrefixYear.label","Prefix Year"},
		{"eST.PrefixFacility.label","Prefix Facility"},
		{"eST.PrefixPurchaseUnit.label","Prefix Purchase Unit"},
		{"eST.DocGenMethod.label","Doc Gen. Method"},
		{"eST.Year.label","Year"},
		{"eST.StartDocNo.label","Starting Doc. No."},
		{"eST.NextDocNo.label","Next Doc. No."},
		{"eST.AutoGenerate.label","Auto Generate"},
		{"eST.Manual.label","Manual"},
		
		{"eST.QuotationNoTenderRef.label","Quotation No/Tender Ref."},
		{"eST.QuotationNumber.label","Quotation No."},
		{"eST.DeliveryMode.label","Delivery Mode"},
		{"eST.OldPurchaseNo.label","Old Purchase No."},
		{"eST.TermsAndConditions.label","Terms & Conditions"},
		{"eST.SupplierAddress.label","Supplier Address"},
		{"eST.Remarks.label","Remarks"},
		{"eST.AddressLine1.label","Address Line 1"},
		{"eST.SupplierAddressLine1.label","Supplier Address Line 1"},
		{"eST.AddressLine2.label","Address Line 2"},
		{"eST.AddressLine3.label","Address Line 3"},
		{"eST.DeliverTo.label","Deliver To"},
		{"eST.BillTo.label","Bill To"},
		{"eST.PONumber.label","PO Number"},
		{"eST.PODate.label","PO Date"},
		{"eST.EnteredDate.label","Entered Date"},
		{"eST.Revision.label","Revision"},
		{"eST.Buyer.label","Buyer"},
		{"eST.SNo.label","S.No"},
		{"eST.Acct/DeptID/OperUnit.label","Acct/DeptID/OperUnit"},
		{"eST.Quantity/UOM.label","Quantity/UOM"},
		{"eST.TotalPOAmount.label","Total PO Amount"},
		{"eST.AuthorisedSignature.label","Authorised Signature"},
		{"eST.QuotationNo.label","Total Quotation No."},
		{"eST.ToPurUnit.label","To Purchase Unit"},
		{"eST.POItemDetails.label","PO Item Details"},
		{"eST.PurRequestNo.label","Pur Request No"},
		{"eST.NotApplicable.label","Not Applicable"},
		{"eST.Error.label","Error"},
		{"eST.Warning.label","Warning"},
		{"eST.UserStoreAccessApplicable.label","User Store Access Applicable"},
		{"eST.DefaultStore.label","Default Store"},
		{"eST.CommitmentCodeAdditionalDetails.label","Commitment Code Additional Details"},
		{"eST.Department.label","Department"},
		{"eST.AccountNumber.label","Account No"},
		{"eST.AccountNumberDescription.label","Account No Description"},
		{"eST.AllocatedBudget.label","Allocated Budget"},
		{"eST.AdditionalBudget.label","Additional Budget"},
		{"eST.BalanceBudget.label","Balance Budget"},
		{"eST.EffectiveFrom.label","Effective From"},
		{"eST.EffectiveTo.label","Effective To"},
		{"eST.RequiredByDate.label","Required By Date"},
		{"eST.RequestType.label","Request Type"},
		{"eST.ItemRemarks.label","Item Remarks"},
		{"eST.RepackingLabelWithBarcode.label","Repacking Label With Barcode"},
		{"eST.RepackingLabelWithoutBarcode.label","Repacking Label Without Barcode"},
		{"eST.LabelwithBarcode.label","Label with Barcode"},
		{"eST.HeaderRemarks1.label","Header Remarks - 1"},
		{"eST.HeaderRemarks2.label","Header Remarks - 2"},
		{"eST.PurchaseRequestDetails.label","Purchase Request Details"},
		{"eST.PurchaseOrderDetails.label","Purchase Order Details"},
		{"eST.InterfacePOApplicable.label","Purchase Module Installed"},
		{"eST.ExpDelDate.label","Expected Delivery Date"},
		{"eST.PaymentTerms.label","Payment Terms"},
		{"eST.DeliverToAddress.label","Deliver To Address"},
		{"eST.BillToAddress.label","Bill To Address"},
		{"eST.BackOrderQty.label","Back Order Qty"},
		{"eST.DelDateForPendQty.label","Delievery Date For Pending Qty"},//Modified for IN:071539
		{"eST.UsageType.label","Usage Type"}, //27/07/12
		{"eST.Required.label","Required"},
		{"eST.Optional/Required.label","Optional Required"},
		{"eST.Optional/PreSelected.label","Optional Pre-Selected"},
		{"eST.Optional/DeSelected.label","Optional De-Selected"},
		{"eST.AuthQty.label","Authorized Qty"},
		{"eST.ViewBatchDetails.label","View Batch Details"},
		{"eST.ChangeBatch.label","Change Batch"},
		{"eST.AllowChangeBatchDuringAuthorize.label","Allow Change of Batch During Authorize at Issue Stage"},
		{"eST.AllowPartialQtyWORemarksDuringAuthorize.label","Allow Authorize of Partial Quantity Without Remarks"},
		{"eST.ItemImageCatalogue.label","Item Image/Catalogue Path"},
		{"eST.DateofReceipt.label","Date of Receipt"},
		{"eST.ItemImageCatalogue.label","Item Image/Catalogue "},
		{"eST.ItemImageCataloguePath.label","Item Image/Catalogue Path"},
		{"eST.ItemImageCatalogueFileName.label","Item Image/Catalogue File Name"},
		{"eST.SlowMoving.label","Slow Moving"},
		{"eST.FastMoving.label","Fast Moving"},
		{"eST.DoNo.label","DO No"},//added for Bru-HIMS-CRF-113 by Ganga
		{"eST.InvoiceNo.label","Invoice No"},
		{"eST.InvoiceReceivedBy.label","Invoice Received By"},
		{"eST.DOQty.label","DO Qty"},
		{"eST.DelieveryOrderDetails.label","Delievery Order Details"},
		{"eST.ScheduleDate.label","Schedule Date"},//added ended for Bru-HIMS-CRF-113 by Ganga
		//Added by Rabbani INC NO:34758(RUT-CRF-0082) on 07/02/2013 Starts
		{"eST.RequestRemarks.label","Request Remarks"}, 
		{"eST.HeaderLevelRemarksRequired.label","Header Level Remarks Required"},  
		//ends
		
		//Added By Sakti against CRF# - RUT-CRF-0081 inc#34757
		{"eST.CutoffDays.label","Cutoff Receipt Days for consideration of Batches for Physical Inventory"},
		{"eST.DefaultCutoffDays.label","Default Receipt Cutoff Days for consideration of Batches for Physical Inventory"},
		{"eST.DisplayLookup.label","Display Look up in Physical Inventory Entry"},
		{"eST.DisplayAndAllowNewBatch.label","Display And Allow additon of new batches"},
		{"eST.AllowBatchLookup.label","Allow addition only through batch lookup"},
		{"eST.ManualBatchEntry.label","Allow addition of new batch but do not display batch look up"},
		//Added ends
		//Added By Sakti Sankar on 11/02/2013 against SCF#ML-BRU-SCF-0640 inc#36859
		{"eST.IncludeAcknowledgement.label","Include Acknowledgement"} ,
		
		//Added by Rabbani #Inc no:29950(Bru-HIMS-CRF-084) on 18-FEB-2013
		{"eST.DefaultManufacturingMode.label","Default Manufacturing Mode"},
		{"eST.BasedonRequest.label","Based on Request"},
		{"eST.DirectManufacturing.label","Direct Manufacturing"},
		{"eST.ByRequest.label","By Request"},
		{"eST.ManufacturingReceiptsDetails.label","Manufacturing Receipts Details"},
		//ends
		//Added by Rabbani #Inc no:29954(Bru-HIMS-CRF-088) on 04-MAR-2013 Starts
		{"eST.DefaultDurationforExpiryDateforDisposableDrugswithoutExpiryDate.label","Default Duration for Expiry Date for Disposable Drugs without Expiry Date"} ,
		{"eST.Disposable.label","Disposable"},  
		//ends
		{"eST.StockStatusforFacility.label","Stock Status for Facility"}, //Added by Rabbani #Inc no:39203 on 18-APR-2013 
		{"eST.IncludeSuspendedBatchesinAvailableQuantity.label","Include Suspended Batches in Available Quantity"}, //Added by Rabbani #30069(BRU-HIMS-CRF-110) on 23-APR-2013
		//Added by Rabbani #30075(BRU-HIMS-CRF-116) on 10-MAY-2013
		{"eST.GRNNo.label","GRN No"},
		//Added by Sakti against BRU-HIMS-CRF-187
		{"eST.PendingAckRejZero.label","Pending Ack./Reject Zero"},
		{"eST.PendingAckRejNonZero.label","Pending Ack./Reject Non-Zero"},
		{"eST.RejectNonZero.label","Reject Non-Zero"},
		{"eST.AcknowledgementDate.label","Acknowledgement Date"},
		{"eST.AcknowledgementStatus.label","Acknowledgement Status"},
		{"eST.PromptForFinalize.label","Prompt For Finalize"},
		{"eST.CurrentRecord.label","Current Record"},
		{"eST.ScannedRecord.label","Scanned Record"},
		{"eST.PendingForScanning.label","Pending For Scanning"},
		{"eST.PendingAcknowledgement.label","Pending Acknowledgement"},
		//Added by Sakti sankar against AMRI-CRF-100024 and AMS-CRF-0028
		{"eST.QtyOnHand.label","Qty. On Hand"},
		{"eST.DispCurrEncFinDtl.label","Display Current Encounter Financial Details"},//Added by suresh.r 12-11-2013 against JD-CRF-156
		//Added by Sakti sankar against Bru-Hims-CRF-408
		{"eST.DefaultsForPhysicalInventory.label","Defaults for Physical Inventory"},
		{"eST.UseDeviceForPhysicalCount.label","Use Device for Physical Count"},
		//Added by suresh.r on 28-01-2014 against AMS-CRF-054 beg
		{"eST.IssueDocNo.label","Issue Doc No"},
		{"eST.IssueRetBaseOn.label","Default Issue Return Mode"},
		{"eST.DocLevel.label","Issue Document based"},
		{"eST.ItemLevel.label","Item based"},
		//Added by suresh.r on 28-01-2014 against AMS-CRF-054 end
		//Added by Rabbani #Inc no:43682(AMS-SCF-0275) on 22-MAY-2014
		{"eST.HeaderRemarksModeforStockItemConsumption.label","Header Remarks Mode for Stock Item Consumption"},
		{"eST.Predefined.label","Pre defined"},
		//Added by suresh.r on 27-02-2015 against MMS-QH-CRF-0205 Inc 52253 beg
		{"eST.AllowEqualUOMforPhyInvEntry.label","Allow Equivalent UOMs for Physical Inventory Entry"},
		{"eST.BaseUOMQty.label","Base UOM Qty"},
		//Added by suresh.r on 27-02-2015 against MMS-QH-CRF-0205 Inc 52253 end
		{"eST.BinLocationCode.label","Bin Location Code"}, //Added by B.Badmavathi on 02-04-2015 against HSA-CRF-0220
		{"eST.CondemnBatches.label","Condemn Batches"},//Added by B.Badmavathi on 12-04-2016 against ML-MMOH-CRF-0375
		{"eST.AuthorizeatIssueStore.label","Authorize at Issue Store"},//Added by B.Badmavathi on 21/04/2016 against PMG2015-CRF-INT-ST-0001
		{"eST.AllowAuthorizeAtIssueStore.label","Use 'Authorize at Issue Store' privilege to Authorize"},//Added by B.Badmavathi on 21/04/2016 against PMG2015-CRF-INT-ST-0001
		{"eST.BarcodeId.label","Barcode ID"}, // GHL-CRF-413.4
		{"eST.AllowGRNBatchDuringSplit.label","Restrict Split/Reassign destination batches to GRN batches"},//Added against GHL-CRF-0446 
		{"eST.AvlQtyatReqStore.label","Avl Qty at Req Store"},//Added against MMS-DM-CRF-0097
		{"eST.Sales/PatientIssues.label","Sales/Patient Issues"},//Added against GHL-CRF-0456
		{"eST.InternalConsumption.label","Internal Consumption"},//Added against GHL-CRF-0456
		{"eST.DocNo.label","Doc.No"},//Added by Shazana against CRF-99.2
		{"eST.SelectAllItemsByDefaultWhenSaleDocumentIsPicked.label","Sales Return: Select all items by default when Sale Document is picked"}, //Added by sharanraj against GHL-CRF-0483
		{"eST.MaxReturnQty.label","Max Returnable<br>Qty for GRN"},//Added GHL-CRF-496 
		{"eST.TotalAvailableQuantity.label","Total Available Quantity"},//Added GHL-CRF-496 
		{"eST.ChallanNo.label","Challan No."},//Added Against GHL-CRF- 0499 
		{"eST.AllowZeroStockBatchDuringSplit.label","Include Zero QOH destination Batches in Split/Reassign Batch"},//Added against GH-CRF-0503 Split Batch
		{"eST.FromAuthorizeDate.label","From Authorize Date"},//Added Against AMRI-CRF-0382
		{"eST.ToAuthorizeDate.label","To Authorize Date"},//Added Against AMRI-CRF-0382 
		{"eST.AuthorizeDate.label","Authorize Date"},//Added Against AMRI-CRF-0382 	
		{"eST.RstrictRequesastionExdMaxstock.label","Restrict Requisition of Stock if exceeding Max Quantity"},//Added for IN:071343
		{"eST.ConsiderForAutoROLCalculation.label","Autocalculate ROL, ROQ, Min & Max Stock Levels"},//Added for IN:071344
		{"eST.CunsumptionPeriod.label","Consumption Period (in days)"},//Added for IN:071344
		{"eST.SortByItemDesc.label","Sort By Item Description"},//Added for IN:071539
		{"eST.SortByItemCode.label","Sort By Item Code"},//Added for IN:071539
		{"eST.ItemCode.label","Item Code"},//Added for IN:071539
		{"eST.ExpiryReceiptDate.label","Expiry/Receipt Date"},//Added for IN:071539
		{"eST.PODocType.label","PO Doc Type"},//Added for IN:071539
		{"eST.ApprovalNumber.label","Approval Number"},//Added for IN:071972
		{"eST.AutomaticallyAssociateNewInterfaceItemsToStore.label","Automatically associate new interface Items to Store"},//Added for IN:072963
		{"eST.PatientPaid.label","Patient Paid"}, 
		{"eST.OverrideInclExcl.label","Override Incl/Excl"},
		{"eST.Select.label","Select"}, //Added for MMS-DM-CRF-0177
		{"eST.PreAllocationDrugs.label","Pre Allocation of Drugs Based on"}, //Added for MMS-DM-CRF-0177
		{"eST.NearExpiry.label","Near Expiry"}, //Added for MMS-DM-CRF-0177
		{"eST.StockLevel.label","Stock Level"}, //Added for MMS-DM-CRF-0177
		{"eST.BarcodeForAck.label","Barcoding for Acknowledgement"},//Added for TFS id:6938
		{"eST.NormalQty.label","Normal Qty"},//added for MO-CRF-20165 START
		{"eST.BonusQty.label","Bonus Qty"},
		{"eST.SampleQty.label","Sample Qty"},
		{"eST.ManufacturedDate.label","Manufactured Date"},
		{"eST.Catalogue.label","Catalogue"},//END  
		{"eST.DurationForIssueHistory.label","Issue History Days (Max 365 Days)"},//Added for MO-CRF-20166
		{"eST.RestrictStoresToUserAccessibleStoresInReports.label","Restrict Stores to User Accessible Stores in Reports/Queries"},//Added for TFS:19787
		{"eST.TotalQuantity.label","Total Quantity"}, //Added for MOHE-CRF-0040.1
		{"eST.NoofDays.label","Prevent New Request if the Item is received in the past "},//added for MO-CRF-20172		
		{"eST.CloseItem.label","Close"},//added for MO-CRF-20173
		{"eST.NoOfDaysFromPrevReq.label","Block Repeat Request Days"}, 
		{"eST.Days.label","Days"},
		{"eST.PurchaseUOMQOH.label","Purchase UOM QOH"}, //MO-CRF-20175 
		{"eST.PurchaseUOMAvlQty.label","Purchase UOM Avl Qty"},
		{"eST.CancelAuthorizeatIssueStore.label","Cancel Authorization at Issue Store"},   //TFS ID - 23934 - MO-CRF-20177
		{"eST.RejectRequestatIssueStore.label","Reject Request at Issue Store"},   //TFS ID - 23934 - MO-CRF-20174
		{"eST.ForRejectOrCancel.label","For Reject or Cancel"}, //MO-CRF-20174	
		{"eST.Reject.label","Reject"},
		{"eST.RejectionRemarks.label","Rejection Remarks"},
		{"eST.RejectRequestBy.label","Reject Request By"},//MO-CRF-20174 END 
		{"eST.ItemStoreCombination.label","Item Store Combination"}, //added for  NMC-JD-CRF-0142
		{"eST.ItemInstruction.label","Item Instruction"}, //added for  TH-KW-CRF-0039
		{"eST.IntegrateWithCSSDModule.label","Integrate With CSSD Module"},//added for ML-MMOH-CRF-1968
		{"eST.UploadFile.label","UploadFile"}, //added for  TH-KW-CRF-0083
		{"eST.BrowseAndView.label","Browse"},//added for  TH-KW-CRF-0083
		{"eST.ItemName.label","Item Name"},//added for  TH-KW-CRF-0083
		{"eST.BatchID.label","Batch ID"},//added for  TH-KW-CRF-0083
		{"eST.BinLocationS.label","Bin Location"},//added for  TH-KW-CRF-0083
		{"eST.ExpiryDateS.label","Expiry Date"},//added for  TH-KW-CRF-0083
		{"eST.IntegrateWithCSSDModule.label","Integrate With CSSD Module"},//added for ML-MMOH-CRF-1968
		{"eST.CSSDCleaningStore.label","CSSD Cleaning Store"},//added for ML-MMOH-CRF-1968
		{"eST.ShelfLife.label","Shelf Life"},//Added for ML-MMOH-CRF-1909
		{"eST.Day(s).label","Day(s)"},//Added for ML-MMOH-CRF-1909
		{"eST.Week(s).label","Week(s)"},//Added for ML-MMOH-CRF-1909
		{"eST.Month(s).label","Month(s)"},//Added for ML-MMOH-CRF-1909
		{"eST.Year(s).label","Year(s)"},//Added for ML-MMOH-CRF-1909
		{"eST.UomForPharmacyInterface.label","UOM for Pharmacy interface"},//Added for MMS-DM-CRF-0230 US002
		{"eST.HighestUOM.label","Highest UOM"},//Added for MMS-DM-CRF-0230 US002
		{"eST.LeastUOM.label","Least UOM"},//Added for MMS-DM-CRF-0230 US002
		{"eST.WeightedAverageCostUnitCostPrice.label","Weighted Average Cost for Unit cost price"}//Added for PMG2023-COMN-CRF-0039 US002
	}; 
}
