/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eST.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
//		{"eST.A.label","A"},
//		{"eST.ABCAnalysis.label","ABC Analysis"},
//		{"eST.ABCAnalysisReport.label","ABC Analysis Report"},
//		{"eST.ABCCategory.label","ABC Category"},
//		{"eST.ABCCriteria.label","ABC Criteria"},
//		{"eST.ABCCutoffRange.label","ABC Cutoff Range"},
		{"eST.ActualBalanceQty.label","实际余�?数�?"},
		{"eST.ActualQuantity.label","实际数�?"},
		{"eST.AddItems.label","新增项目"},
		{"eST.AdjDocDate.label","调整档的日期"},
		{"eST.AdjDocRef.label","调整档�?�照�?�"},
		{"eST.AdjDocStartNo.label","调整档�?�"},
		{"eST.AdjDocType.label","调整档类型"},
		{"eST.AdjRemarks.label","高速备注"},
		{"eST.Adjustments.label","调整"},
		{"eST.AgeSlots.label","年龄阶段"},
		{"eST.AgeingSlots.label","�?龄阶段"},
//		{"eST.AlertPickSlipPrint.label","Alert Pickslip Print"},
		{"eST.AllItems.label","所有物�?"},
		{"eST.AllStores.label","所有库房"},
		{"eST.AllowMultiStoreIssue.label","�?许多库房�?�出"},
		{"eST.Analysis.label","分�?"},
		{"eST.Annual.label","年度"},
		{"eST.ApplicabletoPharmacy.label","适用于�?�剂"},
//		{"eST.AssociatedRTV.label","Associated RTV"},
//		{"eST.AssociatedRTVsforReplacement.label","Associated RTVs for Replacement"},
//		{"eST.AuditInformationfor.label","Audit Information for"},
//		{"eST.AuthorizeAtIssueStoreRemarks.label","Authorize At Issue Store Remarks"},
//		{"eST.AuthatReqByStore.label","Authorize at Request By Store"},
		{"eST.AuthorizeQuantity.label","授�?�数�?"},
//		{"eST.AuthorizeSpecialRequest.label","Authorize Special Request"},
//		{"eST.AuthorizedatIssueStore.label","Authorized at Issue Store"},
//		{"eST.AuthorizedatRequestbyStore.label","Authorized at Request by Store"},
		{"eST.Autoclavable.label","高压清洗"},
		{"eST.AvailableQty.label","�?许数�?"},
		{"eST.AvailableStock.label","�?许库存"},
		{"eST.Averagecostwillbechangedfrom.label","平�?��?本将改�?�"},
		{"eST.AvlQtyatIssueStore.label","库房�?�出平�?�数�?"},
		{"eST.AvlQtyinIssStore.label","库房�?�出平�?�数�?"},
		{"eST.AvlQtyinReqStore.label","库房请求平�?�数�?"},
//		{"eST.B.label","B"},
		{"eST.BaseQuantity.label","基于数�?"},
		{"eST.BatchExpiresNext.label","批�?到次"},
		{"eST.BatchSearch.label","批�?查找"},
		{"eST.BatchSelection.label","批�?选择"},
		{"eST.BatchSeries.label","批�?系列"},
		{"eST.BatchStatusHistory.label","批历�?�状�?"},
		{"eST.BelowMinimumStockLevel.label","低于历�?�库库水平"},
		{"eST.BelowRe-OrderLevel.label","低于�?订购水平"},
//		{"eST.BillingConfirmationAlert.label","Billing Confirmation Alert"},
//		{"eST.BinLocationRange.label","Bin Location Range"},
//		{"eST.Bonus.label","Bonus"},
//		{"eST.BonusQuantity.label","Bonus Quantity"},
//		{"eST.BufferPercentage.label","Buffer Percentage"},
//		{"eST.ByBinLocation.label","By Bin Location"},
//		{"eST.ByDocumentDate.label","By Document Date"},
//		{"eST.ByFromStore.label","By From Store"},
//		{"eST.ByIssuingStore.label","By Issuing Store"},
//		{"eST.ByItem.label","By Item"},
//		{"eST.ByItemCode.label","By Item Code"},
//		{"eST.ByReceivingStore.label","By Receiving Store"},
//		{"eST.ByShortDescription.label","By Short Description"},
//		{"eST.ByStore.label","By Store"},
/*		{"eST.BySupplier.label","By Supplier"},
		{"eST.ByToStore.label","By To Store"},
		{"eST.C.label","C"},
		{"eST.ChangeBin.label","Change Bin"},
		{"eST.ChildItem.label","Child Item"},
		{"eST.CloseUponIssue.label","Close Upon Issue"},
		{"eST.Closed/Cancelled.label","Closed/Cancelled"},
		{"eST.ClosingBalance.label","Closing Balance"},
		{"eST.CommittedQty.label","Committed Qty"},*/
		{"eST.Compositionfor.label","�?分"},
		{"eST.CompositionforQty.label","�?分数�?"},
		{"eST.ComputedDetails.label","计算明细"},
		{"eST.CondemnID.label","Condemn ID"},
		{"eST.ConfirmPrinting.label","确认打�?�"},
//		{"eST.ConsiderIteminTargetStore.label","Consider Item in TargetStore"},
		{"eST.ConsiderReprintasOriginal.label","试想作为原始转载"},
//		{"eST.ConsiderStockpositionforReorder.label","Consider Stock positionfor Reorder"},
		{"eST.Consignment.label","寄售"},
		{"eST.ConsignmentItemsOnly.label","寄售物�?"},
		{"eST.Consumption.label","消费"},
		{"eST.ConsumptionCost.label","消费�?本"},
		{"eST.ConsumptionCriteria.label","消费标准"},
		{"eST.ConsumptionPeriod.label","消费时代"},
		{"eST.ConsumptionQty.label","消费数�?"},
		{"eST.Contract.label","�?��?�"},
		{"eST.ConvFactor.label","转�?�因�?"},
		{"eST.CounterChecked.label","�??检查"},
		{"eST.Currency.label","货�?"},
		{"eST.CurrentInventory.label","现有库存"},
		{"eST.CurrentPackSize.label","目�?包大�?"},
		{"eST.CurrentSpecificInventory.label","目�?具体的清�?�"},
		{"eST.DefaultStockParameter.label","缺�?库存�?�数"},
		{"eST.DocDateFrom.label","文檔日期"},
		{"eST.DocSrlNo.label","文档�?列�?�"},
		{"eST.DocType/No.label","文档类型"},
		{"eST.DocumentsforAuthorize.label","授�?�文档"},
		{"eST.Edit/View.label","编辑/查看"},
//		{"eST.ExcludeExternalStores.label","Exclude External Stores"},
//		{"eST.Excludeitemsreceivedwithin.label","Exclude items receivedwithin"},
		{"eST.ExpectedBalanceQuantity.label","预计余�?数�?"},
		{"eST.ExpectedQuantity.label","预计数�?"},
		{"eST.Expired&NotifiedBatch.label","过期�?�通知批次"},
		{"eST.ExpiredBatch.label","过期批次"},
		{"eST.Expired/Notified.label","过期/通知"},
		{"eST.Expired/Suspend.label","过期/暂�?�"},
		{"eST.Expiringin.label","到期的"},
		{"eST.Expiring/expiredBatches.label","到期/过期批"},
		{"eST.ExpiryAnalysisReport.label","期满分�?报告"},
//		{"eST.ExpiryCutoffDays.label","Expiry Cutoff Days"},
		{"eST.ExpiryFlag.label","过期标志"},
		{"eST.ExpiryItems.label","过期项目"},
		{"eST.ExpirySelection.label","过期选择"},
		{"eST.ExpiryWarningDays.label","期满预警天"},
		{"eST.Expiry/ReceiptDate.label","期满/收到日期"},
//		{"eST.Extemporaneous.label","Extemporaneous"},
		{"eST.ExternalItem.label","外部专案"},
		{"eST.ExternalStores.label","外挂"},
//		{"eST.FacilityWiseYearlySummaryReport.label","Facility Wise Yearly Summary Report"},
		{"eST.Factor.label","因�?"},
//		{"eST.Fast/Slow/NoMovementReport.label","快/慢/无移动的报告"},
//		{"eST.ForA.label","For A"},
//		{"eST.ForB.label","For B"},
//		{"eST.ForC.label","For C"},
//		{"eST.FractionalUOM.label","Fractional UOM"},
//		{"eST.FromStore.label","From Store"},
//		{"eST.FromBinLocation.label","From Bin Location"},
		{"eST.FromDocDate.label","檔的日期"},
		{"eST.FromItem.label","项目"},
		{"eST.GenerateBatch.label","生�?批处�?�"},
		{"eST.GoodsReceipt.label","货物收�?�"},
		{"eST.GoodsReceiptFinalize.label","完�?货物收�?�"},
//		{"eST.GraceDaysforHomeCare.label","Grace Days for Home Care"},
//		{"eST.GRN.label","GRN"},
//		{"eST.GRNBatchSearch.label","GRN Batch Search"},
//		{"eST.GRNDetailsfor.label","GRN Details for"},
//		{"eST.GRNDetailsForReplacement.label","GRN Details For Replacement"},
//		{"eST.GRNDocType.label","GRN Doc Type"},
//		{"eST.GRNDocType/No.label","GRN Doc Type/No"},
//		{"eST.GRNHistory.label","GRN History"},
//		{"eST.GRNHistoryRTVList.label","GRN History RTV List"},
//		{"eST.GRNPreviewDetails.label","GRN Preview Details"},
//		{"eST.GRNQuantity.label","GRN Quantity"},
//		{"eST.GRNStatisticsReport.label","GRN Statistics Report"},
//		{"eST.GRNValue.label","GRN Value"},
//		{"eST.IncludeExpiredBatches.label","Include Expired Batches"},
//		{"eST.IncludeNotifiedBatches.label","Include Notified Batches"},
//		{"eST.IncludeStockIssues.label","Include Stock Issues"},
/*		{"eST.IncludeSuspendedBatches.label","Include Suspended Batches"},
		{"eST.IncludeZeroStockBatches.label","Include Zero Stock Batches"},
		{"eST.InsurancePolicyIsExpired Proceed.label","Insurance Policy Is Expired Proceed"},
		{"eST.InternalStores.label","Internal Stores"},
		{"eST.IssueBatchSearch.label","Issue Batch Search"},
		{"eST.IssueIntegerQuantity.label","Issue Integer Quantity"},
		{"eST.IssuePreviewDetails.label","Issue Preview Details"},
		{"eST.IssueReturnFinalize.label","Issue Return Finalize"},
		{"eST.IssueReturnPreviewDetails.label","Issue Return Preview Details"},
		{"eST.IssueReturns.label","Issue Returns"},
		{"eST.IssueSequence.label","Issue Sequence"},
		{"eST.IssueUOM.label","Issue UOM"},
		{"eST.IssueUOMQuantity.label","Issue UOM Quantity"},
		{"eST.IssuesCost.label","Issues Cost"},
		{"eST.IssuingStore.label","Issuing Store"},
		{"eST.ItemAnalysisCodeshouldbeunique.label","Item Analysis Code should be unique"},
		{"eST.ItemDetails.label","Item Details"},
		{"eST.ItemFrom.label","Item From"},*/
		{"eST.ItemQuantity.label","项目数�?"},
		{"eST.ItemSearch.label","项目查找"},
		{"eST.ItemSelection.label","项目选择"},
		{"eST.ItemSpecifications.label","项目规格"},
		{"eST.ItemSummaryReport.label","项目总结报告"},
		{"eST.ItemTo.label","项目"},
		{"eST.Itemtobeused.label","项目将使用"},
		{"eST.ItemsMovementStatus.label","项目移动状�?"},
		{"eST.LabelRequired.label","标签�?求"},
		{"eST.LastDays.label","最�?�的日�?"},
//		{"eST.LeadDays.label","Lead Days"},
		{"eST.lessthanminstock.label","�?于最�?库存"},
		{"eST.lessthanROL.label","�?于ROL"},
		{"eST.MachineCode.label","机器代�?"},
		{"eST.ManufactureReceipts.label","厂商�?�票"},
		{"eST.ManufacturerItem.label","厂商项目"},
		{"eST.Manufacturing.label","制造"},
		{"eST.ManufacturingFormulary.label","制造处方"},
		{"eST.ManufacturingItem.label","制造项目"},
		{"eST.ManufacturingItemLabel.label","�?�标制造项目"},
		{"eST.ManufacturingItems.label","制造项目"},
		{"eST.ManufacturingItemsFinalize.label","制造业项目完�?"},
		{"eST.ManufacturingReceipt.label","制造收�?�"},
		{"eST.ManufacturingRequestDetails.label","制造�?求的细节"},
//		{"eST.MasterBinLocation.label","Master Bin Location"},
		{"eST.MaxAvailable.label","�?许最大值"},
		{"eST.MaxReturnableQuantity.label","最大�?�退回数�?"},
		{"eST.MaxStock.label","最大库存"},
		{"eST.MaxStockLevel.label","最大库存水平"},
		{"eST.MaxStockQuantity.label","最大库存�?"},
		{"eST.MaximumLevel.label","最大库存水平"},
//		{"eST.MFG.label","MFG"},
//		{"eST.MFGItem.label","MFG Item"},
//		{"eST.MFGReceipts.label","MFG Receipts"},
//		{"eST.MFGUOM.label","MFG UOM"},
//		{"eST.MFGWorkloadStatisticsReport.label","MFG Workload StatisticsReport"},
		{"eST.MinSalesQuantity.label","最低售出数�?"},
		{"eST.MinStock.label","最低库存"},
		{"eST.MinStockDays.label","最低库存天数"},
		{"eST.MinStockLevel.label","最低库存水平"},
		{"eST.MinimumLevel.label","最低水平"},
		{"eST.ModelNo.label","模�?��?�"},
		{"eST.ModifyDocumentDetails.label","修改文档细节"},
		{"eST.MovedItemsOnly.label","移动项目"},
//		{"eST.MTDIssueQuantity.label","MTD Issue Quantity"},
//		{"eST.MTDReceiptsQuantity.label","MTD Receipts Quantity"},
		{"eST.ModelNoFrom.label","模�?�编�?�"},
		{"eST.NoofCopies.label","�?制�?�"},
		{"eST.NoofLabels.label","标签�?�"},
//		{"eST.NoofUnfinalised/GLUninterfacedTransactions.label","No of Unfinalised/GL Uninterfaced Transactions"},
		{"eST.NonConsignment.label","�?�寄售"},
		{"eST.NonConsumption.label","�?�消费"},
		{"eST.NonInventoryGRN.label","�?�库存GRN"},
		{"eST.NonManufacturing.label","�?�制造业"},
		{"eST.NonMedical.label","�?�医学"},
		{"eST.NonMedicalItems.label","�?�医疗用�?"},
		{"eST.NonMovedItemsOnly.label","�?�?�是移动项目"},
//		{"eST.NonPSItems.label","Non PS Items"},
		{"eST.NonSoleSource.label","�?�唯一�?��?"},
		{"eST.NonSterile.label","�?�无�?�"},
		{"eST.NonStock.label","�?�库存"},
		{"eST.NonStockIssues.label","�?�库存问题"},
		{"eST.NonStockReturns.label","�?�库存退回"},
		{"eST.NonContract.label","�?��?��?�"},
		{"eST.NonExpiryItems.label","�?�过期项止"},
		{"eST.NonMedicalItem.label","�?�医疗项目"},
		{"eST.NonStockStore.label","�?�库存商店"},
		{"eST.NormalQty.label","正常数�?"},
		{"eST.NormalRequest.label","正常申请"},
		{"eST.Notified.label","通知"},
		{"eST.NotifiedBatch.label","通知批次"},
		{"eST.ofMinStock.label","最�?库存"},
		{"eST.OldDetails.label","旧的明细"},
		{"eST.OnlyA.label","�?�有A"},
		{"eST.OnlyB.label","�?�有B"},
		{"eST.OnlyC.label","�?�有C"},
//		{"eST.OpeningStock.label","Opening Stock"},
		{"eST.OtherAttributes.label","其它属性"},
		{"eST.OtherStore.label","其它库房"},
		{"eST.ParentStore.label","总库房"},
		{"eST.PendingRequestQty.label","待�?求数�?"},
		{"eST.PeriodFrom.label","期间"},
		{"eST.PeriodFromDate.label","期间"},
		{"eST.Perpetual.label","永久"},
		{"eST.PharmacyStockItems.label","�?�房库存物�?"},
		{"eST.PhyCount.label","物�?�计数"},
		{"eST.PhyCountPerYear.label","�?年物�?�计数"},
		{"eST.PhyInvProcessMode.label","物�?�库存模�?"},
		{"eST.PhyInventory.label","物�?�库存"},
		{"eST.PhyInventoryID.label","物�?�库存编�?�"},
		{"eST.PhyInventoryType.label","物�?�库存类型"},
		{"eST.PONo.label","采购�?� �?�"},
		{"eST.PrePacking.label","预包装"},
//		{"eST.PreparationMode.label","Preparation Mode"},
//		{"eST.PreparationType.label","Preparation Type"},
		{"eST.PresentCount.label","当�?计算"},
		{"eST.PrimaryStore.label","主库房"},
		{"eST.Print/View.label","打�?��?查看"},
		{"eST.PrintAlertRequired.label","打�?��??醒信�?�"},
		{"eST.PrintDocument.label","打�?�文本"},
		{"eST.PrintTechnicalSpecification.label","打�?�技术规范"},
//		{"eST.ProcessExpiredBatch.label","Process Expired Batch"},
//		{"eST.ProcessLoss.label","Process Loss"},
//		{"eST.ProcessOption.label","Process Option"},
//		{"eST.ProcessSuspendedBatch.label","Process Suspended Batch"},
		{"eST.ProductTransfer.label","产�?转让"},
		{"eST.ProductTransferReqNo.label","产�?转让请求�?�"},
		{"eST.ProductTransferRequestSearch.label","产�?转让查询请求"},
//		{"eST.PRT.label","PRT"},
		{"eST.QuantityOnHand.label","目�?数�?"},
		{"eST.QuantityToTransfer.label","转移数�?"},
		{"eST.QueryType.label","查询类型"},
		{"eST.ReceivedQuantity.label","收到数�?"},
		{"eST.Refundallowed.label","�?许退回"},
//		{"eST.Reordarable.label","Reordarable"},
//		{"eST.ReorderAttributes.label","Reorder Attributes"},
//		{"eST.ReorderDays.label","Reorder Days"},
//		{"eST.ReorderFreqDays.label","Reorder Freq Days"},
//		{"eST.ReorderQuantity.label","Reorder Quantity"},
//		{"eST.Reorderable.label","Reorderable"},
//		{"eST.ReorderableItems.label","Reorderable Items"},
//		{"eST.ReorderableStore.label","Reorderable Store"},
//		{"eST.ReorderableStoresstock.label","Reorderable Stores stock"},
		{"eST.RepackGroup.label","改装组"},
		{"eST.RepackItem.label","改装项目"},
		{"eST.RepackSize.label","改装大�?"},
		{"eST.RepackStore.label","改装库房"},
		{"eST.RepackingLabel.label","改装标签"},
//		{"eST.Replonexpiry.label","Repl on expiry"},
//		{"eST.ReplRTVQuantity.label","Repl RTV Quantity"},
//		{"eST.ReplacementGRN.label","Replacement GRN"},
//		{"eST.ReplacementGRNBatchSearch.label","Replacement GRN Batch Search"},
//		{"eST.ReplacementOnExpiry.label","Replacement On Expiry"},
		{"eST.ReplacementQty.label","替�?�数�?"},
//		{"eST.ReplacementRTV.label","Replacement RTV"},
//		{"eST.ReplacementRTVDetailsForItem.label","Replacement RTV DetailsFor Item"},
//		{"eST.ReplGRNQuantity.label","ReplGRN Quantity"},
//		{"eST.ReportExecutedBy.label","Report Executed By"},
//		{"eST.ReportMfgItemLabel.label","Report Mfg Item Label"},
/*		{"eST.ReportRepackingLabel.label","Report Repacking Label"},
		{"eST.ReportSuspendedReinstateBatches.label","Report Suspended Reinstate Batches"},
		{"eST.ReqBy.label","Req By"},
		{"eST.ReqEntered.label","Req Entered"},
		{"eST.ReqGenerationBase.label","Req Generation Base"},
		{"eST.ReqIssue.label","Req Issue"},
		{"eST.ReqItemDetailsfor.label","Req Item Details for"},
		{"eST.ReqNo.label","Req No"},
		{"eST.ReqNoFrom.label","Req No From"},
		{"eST.ReqQty.label","Req Qty"},
		{"eST.ReqStatisticsReport.label","Req Statistics Report"},
		{"eST.ReqStatus.label","Req Status"},
		{"eST.ReqStore.label","Req Store"},
		{"eST.ReqType.label","Req Type"},*/
		{"eST.ReqUOM.label","请求UOM"},
		{"eST.ReqUOMQty.label","请求UOM数�?"},
		{"eST.RequestbyStore.label","�?求店铺"},
		{"eST.RequestByStoreCode.label","�?求商店代�?"},
		{"eST.Requestsof.label","�?求"},
		{"eST.RequiredItem.label","必填项目"},
		{"eST.RequiredQuantity.label","所需数�?"},
		{"eST.Requisition.label","�?用"},
		{"eST.RequisitionAuthorize.label","�?用授�?�"},
		{"eST.RequisitionIssues.label","�?用问题"},
		{"eST.RequisitionIssuesFinalize.label","完�?�?地问题"},
		{"eST.ResultCriteria.label","结果标准"},
		{"eST.RET.label","回波"},
		{"eST.RetQty.label","织红细胞数�?"},
		{"eST.ReturnPeriod.label","�?现期"},
		{"eST.ReturntoVendor.label","返回到供货商"},
		{"eST.ReturnVendor.label","返回供货商"},
		{"eST.Returns.label","返回"},
		{"eST.RevokeDate.label","撤销日期"},
		{"eST.RFDays.label","射频天"},
		{"eST.ROLevel.label","�??渗�?水平"},
/*		{"eST.ROQuantity.label","RO Quantity"},
		{"eST.RTV.label","RTV"},
		{"eST.RTVDetailsforReplacementGRN.label","RTV Details for Replacement GRN"},
		{"eST.RTVDocType/No.label","RTV Doc Type/No"},
		{"eST.RTVforReplacement.label","RTV for Replacement"},
		{"eST.RTVHistory.label","RTV History"},
		{"eST.RTVPreviewDetails.label","RTV Preview Details"},
		{"eST.RTVQuantity.label","RTV Quantity"},
		{"eST.RTVREF.label","RTV Ref"},
		{"eST.S.label","S"},
		{"eST.SAL.label","SAL"},
		{"eST.SaleTrnType.label","Sale Trn Type"},
		{"eST.SaleUOM.label","Sale UOM"},*/
		{"eST.Sales.label","销售"},
		{"eST.SalesAttributes.label","销售属性"},
		{"eST.SalesAuthorize.label","销售授�?�"},
	//	{"eST.SalesBatchSearch.label","Sales Batch Search"},
		{"eST.SalesHistory.label","销售历�?�"},
		{"eST.SalesReturnFinalize.label","完�?销售返回"},
		{"eST.SalesReturnPreviewDetails.label","返回销售细节预览"},
		{"eST.SalesReturns.label","销售退货"},
		{"eST.SalesType.label","销售型"},
		{"eST.Sales/PatientIssue.label","销售/病人�?��?�"},
		{"eST.Sales/PatientIssueCost.label","销售/病人�?��?��?本"},
		{"eST.Sales/PatientIssuesPreviewDetails.label","销售/病人�?��?�预览明细"},
		{"eST.Sample.label","样�?"},
		{"eST.SelectBatchFor.label","选择一批对"},
		{"eST.SelectCriteria.label","选择标准"},
		{"eST.ShowBatchInfo.label","显示批信�?�"},
		{"eST.SpecialReqItem.label","特别请求项目"},
		{"eST.SpecialRequest.label","特殊�?求"},
		{"eST.SplitBatch.label","分批次"},
		{"eST.SplitBatches.label","分批"},
//		{"eST.SRT.label","SRT"},
		{"eST.StandardFormulary.label","标准处方"},
		{"eST.Sterile.label","无�?�"},
		{"eST.Sterilizable.label","消毒"},
		{"eST.StockAdjustment.label","库存调整"},
		{"eST.StockAdjustmentFinalize.label","库存调整结�?�"},
		{"eST.StockatPrimaryStore.label","主库存的"},
		{"eST.StockAvailability.label","库存状况"},
		{"eST.StockConvFactor.label","库存转�?�因�?"},
/*		{"eST.StockFast/SlowMovementReport.label","Stock Fast/Slow Movement Report"},
		{"eST.StockHandledByMedicalStore.label","Stock Handled By Medical Store"},
		{"eST.StockHoldingAnalysisReport.label","Stock Holding AnalysisReport"},
		{"eST.StockItem.label","库存项目"},
		{"eST.StockItemConsumption.label","Stock Item Consumption"},
		{"eST.StockItemConsumptionPreviewDetails.label","Stock Item ConsumptionPreview Details"},
		{"eST.StockLevel.label","Stock Level"},
		{"eST.StockPositionof.label","Stock Position of"},
		{"eST.StockReorderStore.label","Stock Reorder Store"},
		{"eST.StockStatusByItem.label","Stock Status By Item"},
		{"eST.StockStatusReportForTransactedItems.label","Stock Status Report ForTransacted Items"},*/
		{"eST.StockTransfer.label","库存转移"},
		{"eST.StockTransferFinalize.label","库存转移完�?"},
		{"eST.StockValue.label","库存金�?"},
//		{"eST.StoreFrom.label","Store From"},
//		{"eST.StoreTo.label","Store To"},
//		{"eST.StorewiseConsumption.label","Storewise Consumption"},
//		{"eST.StorewiseConsumptionforthePeriod.label","Storewise Consumption for the Period"},
		{"eST.SubStore.label","�?库房"},
//		{"eST.SuppressSummary.label","Suppress Summary"},
		{"eST.SuppressZero.label","�?止零差异"},
//		{"eST.SuppressZeroVariance.label","Suppress Zero Variance"},
		{"eST.SuspendDate.label","暂�?�日期"},
		{"eST.Suspended&ExpiredBatch.label","暂�?��?�一批过期"},
		{"eST.SuspendedBatch.label","暂�?�批"},
		{"eST.SuspendedExpiredNotifiedBatch.label","暂�?�过期�?�通知批次"},
		{"eST.TechnicalSpecification.label","技术规范"},
		{"eST.TemporaryPhyInvID.label","临时造影�?�票编�?�"},
		{"eST.TFR.label","总生育率"},
		{"eST.ToBinLocation.label","为了本�?置"},
		{"eST.ToDocDate.label","为了文件的日期"},
		{"eST.ToItem.label","项目"},
//		{"eST.ToStoreMasterBin.label","To Store Master Bin"},
		{"eST.TotalItemValue.label","项目总价值"},
		{"eST.TotalStock.label","总库存"},
		{"eST.TransAnalysisReport.label","横贯分�?报告"},
		{"eST.TransQty.label","横贯数�?"},
		{"eST.Transactionacrossfacility.label","整个交易设施"},
		{"eST.TransactionApplicable.label","交易适用"},
		{"eST.TransferExecutedby.label","转让处决"},
		{"eST.TransferQty.label","转让数�?"},
		{"eST.UnfinalizedTransactionsReport.label","未完�?交易报告"},
//		{"eST.URG.label","URG"},
		{"eST.UrgentIssue.label","紧急�?�出"},
		{"eST.UrgentIssueFinalize.label","紧急�?�出确认"},
		{"eST.UseAfterExpiry.label","失效�?�使用"},
		{"eST.UserInfo.label","用户信�?�"},
		{"eST.VendorReturn.label","供货商退回"},
		{"eST.VendorReturnFinalize.label","供就商退回确定"},
		{"eST.WithFormulary.label","有处方的"},
		{"eST.WithoutFormulary.label","无处方"},
		{"eST.WorkLoadStatisticReport.label","工作�?统计报告"},
		{"eST.YearlyStockTurnoverReport.label","�?年的库存周转报告"},
		{"eST.YTDConsQty.label","本年迄今�?守数�?"},
		{"eST.YTDIssQty.label","本年迄今�?�出数�?"},
//		{"eST.WardSupplyManufacturingAndRepackingOutput.label","Ward Supply Manufacturing And Repacking-Output"},
//		{"eST.ReportOnGRNStatisticsForDrugs.label","Report On GRN Statistics For Drugs"},
//		{"eST.QAP13AnnualTurnoverRateofStock.label","QAP-13 Annual Turn-over Rate of Stock"},
//		{"eST.QAP14Proportionofvalueofstockswrittenoff.label","QAP 14 - Proportion of value of stocks written off"},
		{"eST.ReturnType.label","退回类型"},
		{"eST.StockReturns.label","存货退回"},
		{"eST.StockIssues.label","存货�?�出"},
//		{"eST.PresentCountStatus.label","Present Count Status"},
//		{"eST.PurchaseValueItems.label","Purchase Value Items"},
//		{"eST.RequestOnStoreCode.label","Request On Store Code"},
//		{"eST.Excludetheitemsreceivedwithin.label","Exclude the items received within"},
		{"eST.IssueType.label","�?�出类型"},
//		{"eST.ConsignmentItems.label","Consignment Items"},
//		{"eST.ABCCodeItemMaster.label","ABC Code {Item Master}"},
		{"eST.RepackingGroupCode.label","包装组代�?"},
		{"eST.RepackingGroupDescription.label","包装组�??述"},
		{"eST.ZeroStockItems.label","零库存项目"},
/*		{"eST.ItemLessthanReorderLevel.label","Item Less than Reorder Level"},
		{"eST.ItemLessthanMinimumLevel.label","Item Less than Minimum Level"},
		{"eST.ItemwithStock.label","Item with Stock"},
		{"eST.ItemGreaterthanMaximumLevel.label","Item Greater than Maximum Level"},
		{"eST.ActiveBatches.label","Active Batches"},
		{"eST.SuspendedBatches.label","Suspended Batches"},
		{"eST.AllBatches.label","All Batches"},
		{"eST.ItemConsolidated.label","Item Consolidated"},
		{"eST.ByItemStore.label","By Item Store"},
		{"eST.ByStoreBatch.label","By Store Batch"},
		{"eST.ByStoreBinLocation.label","By Store Bin Location"},
		{"eST.ByItemBatch.label","By Item Batch"},
		{"eST.NonZeroStock.label","Non Zero Stock"},
		{"eST.ItemClassConsolidated.label","Item Class Consolidated"},
		{"eST.StoreItem.label","Store-Item"},
		{"eST.StoreItemClass.label","Store-Item Class"},
		{"eST.NonSpecialItem.label","Non Special Item"},
		{"eST.ConsumptionDeviation.label","Consumption Deviation"},
		{"eST.ConsumptionByATCClassification.label","Consumption By ATC Classification"},
		{"eST.StoreLevel.label","Store Level"},
		{"eST.ByGRN.label","By GRN"},
		{"eST.ByQuantity.label","By Quantity"},
		{"eST.ByValue.label","By Value"},
		{"eST.ProductRecall.label","Product Recall"},
		{"eST.LastAccessedOn.label","Last Accessed On"},
		{"eST.RequestItemDetailsfor.label","Request Item Details for"},
		{"eST.NoMovement.label","No Movement"},
		{"eST.GoodsReceivedNote.label","Goods Received Note"},
		{"eST.GoodsReturntoVendor.label","Goods Return to Vendor"},
		{"eST.ItemnotmappedtoDrug.label","Item not mapped to Drug"},
		{"eST.SameAsExpiryDate.label","Same As Expiry Date"},
		{"eST.RequestStatisticsReport.label","Request Statistics Report"},
		{"eST.DrugDescIsDifferent.label","Drug Description is different from Item Description.. Do you want to overwrite the existing Drug Description..{Ok/Cancel}?"},
		{"eST.ByCondemnedId.label","By Condemned Id"},
		{"eST.VarianceReportatBatchLevel.label","Variance Report at Batch Level"},
		{"eST.VarianceReportatItemLevel.label","Variance Report at Item Level"},
		{"eST.VarianceReportatStoreLevel.label","Variance Report at Store Level"},
		{"eST.SummaryReportatItemClassLevel.label","Summary Report at Item Class Level"},
		{"eST.OnlyNotifiedBatches.label","Only Notified Batches"},
		{"eST.BufferonMinStock.label","Buffer % {on Min Stock}"},
		{"eST.Notify.label","Notify"},
		{"eST.LastAccessedBy.label","Last Accessed By"},
		{"eST.ByItemClass.label","By Item Class"},
		{"eST.ReorderableStoresOnly.label","Reorderable Stores Only"},
		{"eST.NonReorderableStoresOnly.label","Non Reorderable Stores Only"},*/
		{"eST.TopValue.label","最高值"},
		{"eST.CostValue.label","�?本值"},
//		{"eST.InventoryAgeingSlot.label","Inventory Ageing Slot"},
		{"eST.InventoryIssues.label","�?�出库存"},
		{"eST.InventoryReturns.label","退回存库"},
		{"eST.ISS.label","�?�出"},
		{"eST.ModifiableYN.label","修改　Y/N"},
		{"eST.MoreDetails.label","更多细节"},
//		{"eST.MovementCutoffMonthsSlotRanges.label","Movement Cutoff Months {Slot Ranges}"},
		{"eST.Outflow.label","�?出"},
		{"eST.Particular.label","特别"},
//		{"eST.PhysicalCountSheetHistory.label","Physical CountSheet History"},
//		{"eST.PrepareInstruction.label","Prepare Instruction"},
		{"eST.ReportOfTransferredBatches.label","报告转批"},
//		{"eST.RTVValue.label","RTV Value"},
		{"eST.SampleQuantity.label","样本�?"},
		{"eST.ShowItems.label","显示物�?"},
//		{"eST.SoleSourceYN.label","Sole Source YN"},
//		{"eST.SpecialItemYN.label","Special Item YN"},
		{"eST.StockInflow.label","库存入库"},
		{"eST.StockOnHand.label","目�?库存"},
		{"eST.StockOutflow.label","库存�?出"},
		{"eST.StoreLevelStatus.label","库房状�?"},
		{"eST.TransactionAnalysisReport.label","交易分�?报告"},
		{"eST.ValueOfProcurementMadeByMedicalStore.label","�?�店采购的数�?"},
		{"eST.ZeroStock.label","零库存"},
//		{"eST.AgeingSlotdays.label","Ageing Slot {days}"},
//		{"eST.AssemblyItemCode.label","Assembly Item Code"},
//		{"eST.AutoclavableYN.label","Autoclavable YN"},
//		{"eST.BasesYN.label","Bases Y/N"},
		{"eST.BatchQuantity.label","批数�?"},
		{"eST.Inflow.label","�?入"},
		{"eST.Reorder.label","�?订购"},
		{"eST.BelowMinStockLevel.label","低于最低存货"},
		{"eST.PendReqdQty.label","等待请求数�?"},
		{"eST.forItemCode.label","项目代�?"},
		{"eST.exceedmaxStockLevel.label","越过最大存货水平"},
		{"eST.LessThanROLinFromStore.label","�?于"},
		{"eST.ExceedsMaxStkinToStore.label","超高最大存库"},
		{"eST.BelowMinStkinFromStore.label","低于最低存货"},
		{"eST.IndividualItem.label","个别项目"},
		{"eST.RangeOfItems.label","项目范围"},
		{"eST.BasedYN.label","基于是/�?�"},
		{"eST.ExpiryYN.label","过期是/�?�"},
		{"eST.ADJ.label","调节"},
		{"eST.expiredBatches.label","过期批"},
		{"eST.ReOrder.label","�?订购"},
		{"eST.IssQty.label","�?�出数�?"},
		{"eST.Ingredients.label","�?分"},
		{"eST.PrintOnlabel.label","标签打�?�"},
		{"eST.GetData.label","得到数�?�"},
		{"eST.MfgInstructions.label","�?牌说明"},
//		{"eST.ToStoreBin.label","To Store Bin"},
		{"eST.RepackFactor.label","包装因�?"},
		{"eST.ReplacementGRNExists.label","更�?�GRN存在"},
//		{"eST.FinalizedandRTVExists.label","Finalized and RTV Exists"},
		{"eST.ReplacementGRNPreviewDetails.label","更�?�GRN细节预览"},
//		{"eST.RequisitionRef.label","Requisition Ref"},
//		{"eST.PuUOMFACTOR.label","PuUOM/FACTOR"},
//		{"eST.RequestedUOM.label","Requested UOM"},
//		{"eST.RequestqtyinReqUOM.label","Request qty in Req UOM"},
//		{"eST.RTVDetails.label","RTV Details"},
		{"eST.ReplGRNQty.label","替代GRN数�?"},
		{"eST.TotalNoOfItems.label","总计项目�?�"},
		{"eST.TotalTransferValue.label","共计转让价值"},
		{"eST.DuplicateCopy.label","备份/�?制"},
		{"eST.SoldQuantity.label","销售数�?"},
		{"eST.SaleValue.label","销售价值"},
		{"eST.AdjustQuantity.label","调整数�?"},
		{"eST.AdjustCost.label","调整�?本"},
//		{"eST.BatchValue.label","Batch Value"},
//		{"eST.AdjustLineRemarks.label","Adjust Line Remarks"},
		{"eST.FromItemCode.label","从项目代�?"},
		{"eST.FromExpiryDate.label","从失效日期"},
		{"eST.FromItemQuantity.label","从项目数�?"},
		{"eST.NewBatch.label","新批�?�"},
		{"eST.Repackat.label","改装"},
		{"eST.ReqEnteredBy.label","输入请求"},
		{"eST.ReqAuthorisedBy.label","批准请求"},
		{"eST.IssueAuthorisedBy.label","批准�?�出"},
		{"eST.issueref.label","�?�出�?�考"},
		{"eST.ReqDocDate.label","请求数�?"},
		{"eST.RequestQtyin.label","请求数�?"},
		{"eST.issuom.label","�?�出数�?"},
		{"eST.IssueQty{ISSUOM}.label","�?�出数�?"},
		{"eST.IssueQtyStkUOM.label","�?�出数�?"},
		{"eST.QuantityPrepared.label","备用数�?"},
		{"eST.QtyUsed.label","已用数�?"},
		{"eST.QtyValue.label","数�?值"},
//		{"eST.BinDescription.label","Bin Description"},
		{"eST.IssueToStore.label","�?�货到库房"},
		{"eST.IssueFromStore.label","从库房�?�货"},
		{"eST.AdjQty.label","调整数�?"},
		{"eST.Adjcost.label","调整�?本"},
		{"eST.BatchQty.label","批数�?"},
		{"eST.ToItemCode.label","到 项目代�?"},
		{"eST.ToExpiryDate.label","失效日期"},
		{"eST.Repackeddate.label","包装日期"},
		{"eST.StockItemYN.label","StockItem YN"},
		{"eST.IssueValue.label","�?�出数值"},
		{"eST.AdjustQty.label","调整数�?"},
//		{"eST.HomeCarepatients.label","Home Care patients"},
//		{"eST.StoreSubTotal.label","Store Sub Total"},
//		{"eST.PayabAmt.label","Payab Amt"},
//		{"eST.chargeAmt.label","Charge Amt"},
//		{"eST.FolioAtBatchPrice.label","Folio At Batch Price"},
		{"eST.InpatientSaleApplicable.label","�?院病人销售适用"},
		{"eST.OutpatientSaleApplicable.label","门诊病人销售适用"},
		{"eST.ReferralSaleApplicable.label","�?�考销售适用"},
//		{"eST.ItemClassFrom.label","Item Class From"},
//		{"eST.CutOffRangeforA.label","Cut Off Range for A"},
//		{"eST.CutOffRangeforB.label","Cut Off Range for B"},
//		{"eST.CutOffRangeforC.label","Cut Off Range for C"},
		{"eST.MinimumStock.label","最�?库存"},
		{"eST.NoOfItems.label","项目编�?�"},
		{"eST.NoOfTransactions.label","交易�?�"},
		{"eST.ItemClassTotal.label","专案分类汇总"},
		{"eST.ItemTotal.label","项目总数"},
		{"eST.UpTo.label","Up To"},
		{"eST.Above.label","以上"},
/*		{"eST.FortheFollowingIndicator.label","For the Following Indicator"},
		{"eST.AnnualTurnOverRateOfStocks.label","Annual Turn-Over Rate Of Stocks"},
		{"eST.AnnualValueOfStocksIssued.label","Annual Value Of Stocks Issued"},
		{"eST.ValueOfStocksHeldAnnually.label","Value Of Stocks Held Annually"},
		{"eST.AnnualTurnOverRateofStocks.label","Annual Turn Over Rate of Stocks"},
		{"eST.ValueOfStocksHeldon1stJanValueOfStocksHeldOn31stDecOfTheSameYear.label","{Value Of Stocks Held on 1stJan+Value Of Stocks Held On 31stDec Of The Same Year}/2"},
		{"eST.ThisformistobesenttostatePharmacyDivisioneveryYear.label","This form is to be sent to state Pharmacy Division every Year"},
		{"eST.JanDecby15thJan.label","Jan-Dec-by 15th Jan"},
		{"eST.JanDecby31stJan.label","Jan-Dec-by 31st Jan"},
		{"eST.ThisStatePharmacyDivisionwillsendthisformtostatePharmaceuticalServicesDivisioneveryYear.label","This State Pharmacy Division will send this form to state Pharmaceutical Services Division every Year"},
		{"eST.AssemblyItemCodeFrom.label","Assembly Item Code From"},*/
		{"eST.ChildItemCode.label","儿童用�?代�?"},
		{"eST.ChildItemDescription.label","儿童用�?�??述"},
//		{"eST.ComponentQty.label","Component Qty"},
//		{"eST.AssemblyItem.label","Assembly Item"},
//		{"eST.ATCClassificationFrom.label","ATC Classification From"},
//		{"eST.ConsumptionPeriodFrom.label","Consumption Period From"},
		{"eST.ComplaintBy.label","投诉"},
		{"eST.ClassTotal.label","总的分类"},
		{"eST.ClassCode.label","分类代�?"},
		{"eST.ClassDescription.label","分类�??述"},
		{"eST.AsonReportDateExpiredStock.label","过期库存报告"},
		{"eST.TotalStockValue.label","总的库存值"},
		{"eST.CutOfDateFrom.label","�?�消日期"},
//		{"eST.ItemClassStockValue.label","Item Class Stock Value"},
		{"eST.EXPIRYINGBETWEEN.label","有效期"},
//		{"eST.MoveYearFrom.label","Move Year From"},
		{"eST.StockValueReceived.label","收到库存值"},
		{"eST.NumberofItemReceived.label","收到项目数�?"},
		{"eST.ValueofItemSupplied.label","�??供项目数"},
		{"eST.StockValueAtDec31.label","年底库存值"},
		{"eST.ValueDisposed.label","处置价值"},
//		{"eST.NoofChecksbyStockVerificationBoard.label","No of Checks by Stock Verification Board"},
//		{"eST.NumberofGRNs.label","Number of GRNs"},
		{"eST.IssuingStoreFrom.label","�?�出库存"},
		{"eST.Add/ModifyItem.label","增加�?修改项目"},
//		{"eST.KitTemplateCode.label","Kit Template Code"},
//		{"eST.KitTemplateDescription.label","Kit Template Description"},
//		{"eST.ViewCostDetails.label","View Cost Details"},
//		{"eST.NoofrecordsperTransaction.label","No. of records per Transaction"},
		{"eST.MachineCodeFrom.label","机器代�? 从"},
//		{"eST.PartNoFrom.label","Part No From"},
		{"eST.NonInventory.label","�?�存货"},
//		{"eST.YtdRecp.label","Ytd Recp"},
//		{"eST.YtdConsm.label","Ytd Consm"},
//		{"eST.MachCode.label","Mach Code"},
//		{"eST.PreviousQty.label","Previous Qty"},
//		{"eST.ConsignmentYN.label","Consignment Y/N"},
//		{"eST.InsuranceYN.label","Insurance Y/N"},
		{"eST.PhysicalInvType.label","物�?�库存类型"},
//		{"eST.ManufacturedItems.label","Manufactured Items"},
		{"eST.UseafterexpiryYN.label","过期使用　Ｙ�?Ｎ"},
//		{"eST.NetStockPosition.label","Net Stock Position"},
		{"eST.UnitCostFrom.label","�?��?�?本"},
		{"eST.StockPosition.label","库存�?置"},
		{"eST.StockValueFrom.label","库存值"},
		{"eST.NoofStores.label","库存�?�"},
		{"eST.NetQty.label","净数�?"},
		{"eST.Part.label","部分"},
//		{"eST.IndicatesSuspendedBatch.label","Indicates Suspended Batch"},
		{"eST.BatchStatus.label","批状�?"},
//		{"eST.NonReorderableStoresStock.label","Non Reorderable Stores Stock"},
		{"eST.ItemBelowMinimumLevel.label","项目低于最低水平"},
//		{"eST.ItemsBelowReorderLevel.label","Items Below Reorder Level"},
//		{"eST.ClearenceBalance.label","Clearence Balance"},
		{"eST.PresentStock.label","当�?库存"},
		{"eST.ReorderValue.label","�?排�?数�?"},
		{"eST.LastReceiptDate.label","最�?��?�票日期"},
		{"eST.LastCost.label","最�?��?本"},
		{"eST.NonSpecialItemOnly.label","�?�特殊项目"},
		{"eST.SpecialItemOnly.label","特殊项目"},
//		{"eST.IssuedItem.label","Issued Item"},
//		{"eST.TRN.label","TRN"},
//		{"eST.TrnQty.label","Trn Qty"},
		{"eST.LastDate.label","最�?�日期"},
//		{"eST.AlphaCodeFrom.label","Alpha Code From"},
//		{"eST.Issued.label","Issued"},
//		{"eST.AvgQty.label","Avg Qty"},
		{"eST.DeviationPercentage.label","�??差百分比"},
		{"eST.Last12MonthsConsumption.label","过去12个月消费"},
//		{"eST.PrevYear12MonthsConsumption.label","Prev Year 12 Months Consumption"},
//		{"eST.SupressZero.label","Supress Zero"},
		{"eST.ExcludeExStore.label","排除�?外库存"},
//		{"eST.VariancePostedBy.label","Variance Posted By"},
		{"eST.StartQty.label","起始数�?"},
		{"eST.PhyStock.label","物�?�库存"},
//		{"eST.VarQtypve.label","Var Qty {+}ve"},
//		{"eST.VarQtynve.label","Var Qty {-}ve"},
//		{"eST.VarValuepve.label","Var Value {+}ve"},
//		{"eST.VarValuenve.label","Var Value {-}ve"},
//		{"eST.TrnQtyForPeriod.label","Trn Qty For Period"},
		{"eST.NoofItemsSupplied.label","无供应专案"},
//		{"eST.StockTurnOverRate.label","Stock Turn Over Rate"},
		{"eST.NoofItemDisposed.label","�?处�?�的项"},
//		{"eST.MoveYear.label","Move Year"},
//		{"eST.ClosingStock.label","Closing Stock"},
//		{"eST.TurnoverRate.label","Turn over Rate"},
		{"eST.Last.label","最�?�"},
		{"eST.EarliestExpiryDate.label","最早失效日期"},
//		{"eST.TotalCondemnID.label","Total Condemn ID"},
		{"eST.PercentageonExpiryStock.label","失效库存的百分比"},
		{"eST.NumberofFinalizedGRNs.label","完�?GRN的数�?"},
		{"eST.NumberofUnfinalizedGRNs.label","未完�?的GRN数�?"},
		{"eST.MfgDate.label","制造 日期"},
		{"eST.UserFrom.label","用户"},
//		{"eST.CancelledPhysicalCountSheet.label","Cancelled Physical Count Sheet"},
		{"eST.CancelDate.label","�?�消日期"},
		{"eST.EmployeeName.label","雇员姓�??"},
		{"eST.Percent.label","百分比"},
//		{"eST.SummaryfortheItemClass.label","Summary for the Item Class"},
//		{"eST.NumberofItemsCounted.label","Number of Items Counted"},
		{"eST.ValueasperPhysicalInventory.label","�?�房库存数"},
//		{"eST.NumberofItemswithpveVariance.label","Number of Items with (+}ve Variance"},
//		{"eST.NumberofItemswithnveVariance.label","Number of Items with (-}ve Variance"},
//		{"eST.TotalVarianceValue.label","Total Variance Value"},
//		{"eST.SummaryofClasses.label","Summary of Classes"},
//		{"eST.PhysicalIdTotal.label","Physical Id Total"},
//		{"eST.TotalPhysicalInventoryID.label","Total Physical Inventory ID"},
		{"eST.PositiveVariance.label","正差异"},
		{"eST.NegativeVariance.label","负差异"},
		{"eST.NetVariance.label","净差�?"},
		{"eST.ZeroVariance.label","零差�?"},
//		{"eST.CountSheet.label","Count Sheet"},
//		{"eST.Expirable.label","Expirable"},
//		{"eST.PercentageOnPresentCount.label","Percentage On Present Count"},
//		{"eST.AutoBatchGenerationYN.label","Auto Batch Generation Y/N"},
		{"eST.BatchIDSeries.label","批�?�系列"},
		{"eST.NextBatchID.label","下一批�?�"},
//		{"eST.TotalnoofLocationCode.label","Total no of Location Code"},
//		{"eST.Yield.label","Yield"},
//		{"eST.ItemRequested.label","Item Requested"},
//		{"eST.RepackingCode.label","Repacking Code"},
//		{"eST.RequestedQtyinReqUOM.label","RequestedQty(inReqUOM}"},
//		{"eST.RequestedQtyinStkUOM.label","RequestedQty(inStkUOM}"},
//		{"eST.CommitedQty.label","Commited Qty"},
		{"eST.Receipts.label","收�?�"},
		{"eST.ReceiptQty.label","收到数�?"},
		{"eST.ReplacementCompleted.label","更�?�完�?"},
		{"eST.NoofReqStores.label","请求库�?编�?�"},
		{"eST.NoofRequests.label","请求�?�"},
		{"eST.NoofCompletedRequests.label","完�?请求编�?�"},
		{"eST.NoofPendingRequests.label","等待请求编�?�"},
		{"eST.NoofCancelRequests.label","�?�消请求编�?�"},
		{"eST.PercentageonCompletedRequests.label","已完�?的百分比�?求"},
		{"eST.NoofItemsRequested.label","无项目请求"},
		{"eST.NoofItemsCompletelyIssued.label","完全�?�出的编�?�"},
		{"eST.NoofItemsPartiallyIssued.label","部分�?�出的编�?�"},
		{"eST.PercentageonCompletelyIssued.label","完�?�?�出的百分比"},
		{"eST.ItemCost.label","项目�?本"},
		{"eST.GRNRef.label","ＧＲＮ�?�考�?�"},
		{"eST.StockValueReceivedRM.label","接收库存值"},
		{"eST.ValueofItemSuppliedRM.label","供应专案数"},
//		{"eST.NumberofItemCondemnedRM.label","NumberofItemCondemned(RM}"},
//		{"eST.ValueCondemned.label","Value Condemned"},
		{"eST.NumberOfQualityComplaints.label","�?质投数数目"},
		{"eST.CheckStockLevel.label","检查存货水平"},
		{"eST.TransactionAllowed.label","�?许交易"},
//		{"eST.BinChange.label","Bin Change"},
		{"eST.AuthorizeAtIssueStore.label","被授�?�的库房"},
//		{"eST.CondemnExpiryBatches.label","Condemn Expiry Batches"},
		{"eST.RequestIssues.label","请求�?�出"},
		{"eST.PendingRequest.label","等待的请求"},
		{"eST.WardUnitSupply.label","病区�?�?��?供应"},
		{"eST.DrugManufacturing.label","�?��?生产"},
		{"eST.PrepackedDrug.label","预�?�?�物"},
		{"eST.SatellitePharmacy.label","�?�星�?�房"},
		{"eST.NoofPack.label","未包装"},
		{"eST.NoItem.label","没有项目"},
		{"eST.NoPack.label","�?包"},
		{"eST.Tablet.label","片"},
		{"eST.NoofStaff.label","无工作人员"},
//		{"eST.Atten.label","Atten"},
		{"eST.PharAsst.label","�?�房助�?�"},
		{"eST.NoofWardUnit.label","病区�?��?�?��?"},
		{"eST.UnitofUse.label","使用�?��?"},
		{"eST.Traditional.label","传统"},
		{"eST.MFGRequest.label","制造商请求"},
		{"eST.ItemTobeManufactured.label","项目生产"},
//		{"eST.ProcessLossPercent.label","Process Loss Percent"},
		{"eST.PrepareType.label","准备类型"},
		{"eST.ExpectedOutput.label","预期产出"},
//		{"eST. MFGStore.label","？"},
		{"eST.RequestedQty.label","�?求数�?"},
		{"eST.ActualOutput.label","实际产�?"},
//		{"eST.Constituent.label","Constituent"},
		{"eST.TimeTakenForPreparation.label","准备时间"},
		{"eST.Repackedat.label","�?新包装"},
		{"eST.ItemToBePacked.label","项目包装"},
		{"eST.SourceBatch.label","�?��?批次"},
		{"eST.ExpectedBalance.label","预计平衡"},
		{"eST.ActualQty.label","实际数�?"},
		{"eST.ActualBal.label","实际平衡"},
		{"eST.ProductIdentification.label","产�?标识"},
		{"eST.TimeTakenforRepacking.label","花费时间�?包装"},
//		{"eST.HighestValueofPurchaseForAPPLDrugs.label","Highest Value of Purchase For APPL Drugs"},
//		{"eST.HighestValueofPurchaseForNONAPPLDrugs.label","HighestValueofPurchaseForNON-APPLDrugs"},
		{"eST.TotalPurchasedQuantity.label","共计购买数�?"},
		{"eST.PriceUnitRM.label","价格/�?��?（？）"},
//		{"eST.APPL.label","APPL"},
//		{"eST.NONAPPL.label","NON-APPL"},
//		{"eST.APPLNONAPPL.label","APPL & NON-APPL"},
		{"eST.PrintNilStockItems.label","打�?�无库存物�?"},
		{"eST.NonStockItem.label","�?�库存项目"},
		{"eST.ROQty.label","退回订购数�?"},
		{"eST.DirectSales.label","直销"},
		{"eST.InternalReportsReprint.label","内部报告�?�?�"},
		{"eST.ValueasperSystem.label","�?介系统值"},
		{"eST.NumberofItemswithvarriance.label","一些项目的差�?"},
		{"eST.NilStockItems.label","无库存物�?"},
		{"eST.TotalNoOfRepackingGroups.label","总的包装组�?�"},
		{"eST.IssuedItemQty.label","项目�?�出数�?"},
		{"eST.MaximumStock.label","最大库存"},
		{"eST.IssueReturn.label","�?��?�退回"},
		{"eST.SalesReturn.label","进货退回"},
		{"eST.ItemsWithZeroAuthorizedQuantity.label","�?��?�数�?为�?的项目"},
		{"eST.Exp.label","进出�?�"},
		{"eST.Referrals.label","推介"},
		{"eST.PartNumber.label","编�?�"},
		{"eST.RepackedProduct.label","产�?包装"},
		{"eST.ProductDescription","产�?�??述"},
		{"eST.PayableAmount.label","应付金�?"},
		{"eST.Patient.label","病人"},
		{"eST.CancelRequestBy.label","�?�消请求"},
		{"eST.RaisedBy.label","�??高"},
		{"eST.ActionType.label","�?作类型"},
//		{"eST.Acknowledge.label","Acknowledge"},
		{"eST.Show.label","显示"},
		{"eST.CopyValues.label","�?制值"},
		{"eST.BillDate.label","账�?�日期"},
		{"eST.BillNo.label","账�?��?�"},
		{"eST.RegNo.label","登记�?�"},
		{"eST.SalePriceApplicable.label","适用零售价"},
		{"eST.MRPGreaterThanUnitPrice.label","需求计划大于�?��?价格？"},
//		{"eST.CategoryDrugNonDrug.label","Category(Drug / Non Drug)"},
		{"eST.NameofItems.label","项目�??称"},
		{"eST.DateOfPurchaseReceive.label","购买�?收到日期"},
		{"eST.PeriodUsed.label","使用期间"},
		{"eST.PurchasingValue.label","采购价值"},
		{"eST.CurrentValue.label","现值"},
		{"eST.RemarksCommentsbyInspectionBoard.label","被检查局备注�?评论"},
//		{"eST.RecommendationbyBoardofCondemn.label","Recommendation by Board of Condemn"},
//		{"eST.AuthorizedDate.label","Authorized Date"},
//		{"eST.POCost.label","PO Cost"},
//		{"eST.PODiscount.label","PO Discount"},
//		{"eST.SalePrice.label","Sale Price"},
//		{"eST.RevisedSalePrice.label","Revised Sale Price"},
//		{"eST.SalePriceHistory.label","Sale Price History"},
//		{"eST.SalePriceStatusHistory.label","Sale Price Status History"},
/*		{"eST.ModifiedDate.label","Modified Date"},
		{"eST.Tax.label","Tax"},
		{"eST.ConfirmAmmendedSalePrice.label","Confirm Ammended Sale Price"},
		{"eST.SalePriceOnceAmmendedCanNotBeChanged.label","Sale Price Once Ammended Can Not Be Changed"},
		{"eST.ReturnAllowed.label","Return Allowed"},
		{"eST.nursingunit/clinic.label","Nursing Unit/Clinic"},
		{"eST.InterfacetoexternalPO.label","Interface to external PO"},
		{"eST.PurchaseOrderRequest.label","Purchase Order Request"},
		{"eST.PORequest.label","PO Request"},
		{"eST.PORequestFinalize.label","PORequest Finalize"},
		{"eST.ToDepartment.label","To Department"},*/
		{"eST.GeneratePORequestBy.label","生�?订购�?求"},
		{"eST.PendingForApproval.label","待审批"},
		{"eST.RequestRejectedbyPODept.label","订购部门拒�?请求"},
		{"eST.RequestReceivedPartially.label","收到部分请求"},
		{"eST.RequestReceivedCompletely.label","收到完全请求"},
		{"eST.RequestCancelled.label","�?�消请求"},
		{"eST.RequestOnDepartment.label","按部门请求"},
//		{"eST.NewBatchYN.label","New Batch(Yes/No)"}
//Newly Added legends on 21/01/09
{"eST. MFGStore.label","制造店铺"},
{"eST.A.label","A"},
{"eST.ABCAnalysis.label","ABC分�?"},
{"eST.ABCAnalysisReport.label","ABC分�?报告"},
{"eST.ABCCategory.label","ABC�?类"},
{"eST.ABCCodeItemMaster.label","ABC代�?"},
{"eST.ABCCriteria.label","ABC标准"},
{"eST.ABCCutoffRange.label","ABC截止范围"},
{"eST.Acknowledge.label","承认"},
{"eST.ActiveBatches.label","在用批�?�"},
{"eST.AdjustLineRemarks.label","备注"},
{"eST.AgeingSlotdays.label","年龄组"},
{"eST.AlertPickSlipPrint.label","Alert Pickslip Print"},
{"eST.AllBatches.label","所有批�?�"},
{"eST.AlphaCodeFrom.labelAlpha Code From","Alpha 代�?"},
{"eST.AnnualTurnOverRateOfStocks.label","Annual Turn-Over Rate Of Stocks"},
{"eST.AnnualTurnOverRateofStocks.label","Annual Turn Over Rate of Stocks"},
{"eST.AnnualValueOfStocksIssued.label","Annual Value Of Stocks Issued"},
{"eST.APPL.label","适用的"},
{"eST.APPLNONAPPL.label","适用的和�?适用的"},
{"eST.AssemblyItem.label","Assembly Item"},
{"eST.AssemblyItemCode.label","Assembly Item Code"},
{"eST.AssemblyItemCodeFrom.label","Assembly Item Code From"},
{"eST.AssociatedRTV.label","Associated RTV"},
{"eST.AssociatedRTVsforReplacement.label","Associated RTVs for Replacement"},
{"eST.ATCClassificationFrom.label","ATC Classification From"},
{"eST.Atten.label","Atten"},
{"eST.AuditInformationfor.label","Audit Information for"},
{"eST.AuthatReqByStore.label","Authorize at Request By Store"},
{"eST.AuthorizeAtIssueStoreRemarks.label","Authorize At Issue Store Remarks"},
{"eST.AuthorizedatIssueStore.label","Authorized at Issue Store"},
{"eST.AuthorizedatRequestbyStore.label","Authorized at Request by Store"},
{"eST.AuthorizedDate.labelAuthorized Date","授�?�日期"},
{"eST.AuthorizeSpecialRequest.label","Authorize Special Request"},
{"eST.AutoBatchGenerationYN.label","Auto Batch Generation Y/N"},
{"eST.AutoclavableYN.label","高压�?��?� Y/N"},
{"eST.AvgQty.labelAvg Qty","平�?�数�?"},
{"eST.B.label","B"},
{"eST.BasesYN.label","Bases Y/N"},
{"eST.BatchValue.label","Batch Value"},
{"eST.BillingConfirmationAlert.label","Billing Confirmation Alert"},
{"eST.BinChange.label","改�?�存储"},
{"eST.BinDescription.label","存储�?置�??述"},
{"eST.BinLocationRange.label","存储范围"},
{"eST.Bonus.label","奖励"},
{"eST.BonusQuantity.label","奖励数�?"},
{"eST.BufferonMinStock.label","�?存库存的最�?期�?"},
{"eST.BufferPercentage.label","截止期的最�?期�?"},
{"eST.ByBinLocation.label","通过存储�?置"},
{"eST.ByCondemnedId.label","By Condemned Id"},
{"eST.ByDocumentDate.label","通过文档日期"},
{"eST.ByFromStore.label","能过库房"},
{"eST.ByGRN.label","通过GRN"},
{"eST.ByIssuingStore.label","通过�?�放库房"},
{"eST.ByItem.label","通过项目"},
{"eST.ByItemBatch.label","通过项目批�?�"},
{"eST.ByItemClass.label","通过项目分类"},
{"eST.ByItemCode.label","通过项目代�?"},
{"eST.ByItemStore.label","通过项目库房"},
{"eST.ByQuantity.label","通过数�?"},
{"eST.ByReceivingStore.label","通过接收库房"},
{"eST.ByShortDescription.label","能过简短�??述"},
{"eST.ByStore.label","通过库房"},
{"eST.ByStoreBatch.label","通过库房批�?�"},
{"eST.ByStoreBinLocation.label","通过库存�?置"},
{"eST.BySupplier.label","通过供应商"},
{"eST.ByToStore.label","能过到达库房"},
{"eST.ByValue.label","通过值"},
{"eST.C.label","C"},
{"eST.CancelledPhysicalCountSheet.label","�?�消清点表"},
{"eST.CategoryDrugNonDrug.labelCategory(Drug / Non Drug)","类别(�?�物/�?��?�物)"},
{"eST.ChangeBin.label","更改库存�?置"},
{"eST.chargeAmt.label","收费金�?"},
{"eST.ChildItem.label","儿科项目"},
{"eST.ClearenceBalance.label","清除余�?"},
{"eST.Closed/Cancelled.label","关闭/�?�消"},
{"eST.CloseUponIssue.label","关闭�?�现的项目"},
{"eST.ClosingBalance.label","期末余�?"},
{"eST.ClosingStock.label","期末库存"},
{"eST.CommitedQty.label","�??交数�?"},
{"eST.CommittedQty.label","�??交数�?"},
{"eST.ComponentQty.label","元件数�?"},
{"eST.CondemnExpiryBatches.label","批次已�?过期"},
{"eST.CondemnID.label","Condemn ID"},
{"eST.ConfirmAmmendedSalePrice.labelConfirm Ammended Sale Price","确认修改零售价"},
{"eST.ConsiderIteminTargetStore.label","考虑目标存储项目"},
{"eST.ConsiderStockpositionforReorder.label","考虑记录的库存数�?"},
{"eST.ConsignmentItems.label","委托物�?"},
{"eST.ConsignmentYN.label","委托?"},
{"eST.Constituent.label","组�?"},
{"eST.ConsumptionByATCClassification.label","根�?�ATC分类消费"},
{"eST.ConsumptionDeviation.label","消费�??差"},
{"eST.ConsumptionPeriodFrom.label","消费期间"},
{"eST.CountSheet.label","计数表"},
{"eST.CutOffRangeforA.label","A的截止范围"},
{"eST.CutOffRangeforB.label","B的截止范围"},
{"eST.CutOffRangeforC.label","C的截止范围"},
{"eST.DrugDescIsDifferent.label","�?��?说明�?等�?�于项目说明..你想覆盖现存的�?��?说明�?�,确认/�?�消?"},
{"eST.ExcludeExternalStores.label","排除外部库房"},
{"eST.Excludeitemsreceivedwithin.label","排除项目接收范围"},
{"eST.Excludetheitemsreceivedwithin.label","排除项目接收范围"},
{"eST.Expirable.label","易过期"},
{"eST.ExpiryCutoffDays.label","过期范围"},
{"eST.Extemporaneous.label","临时的"},
{"eST.FacilityWiseYearlySummaryReport.label","部门年度总结报告"},
{"eST.FinalizedandRTVExists.label","结�?�和RTV存在"},
{"eST.FolioAtBatchPrice.label","批�?价格"},
{"eST.ForA.label","A类"},
{"eST.ForB.label","B类"},
{"eST.ForC.label","C类"},
{"eST.FortheFollowingIndicator.label","对于指标"},
{"eST.FractionalUOM.label","UOM片"},
{"eST.FromBinLocation.label","存储�?置"},
{"eST.FromStore.label","存储�?置"},
{"eST.GoodsReceivedNote.label","接收货物"},
{"eST.GoodsReturntoVendor.label","退回货物"},
{"eST.GraceDaysforHomeCare.label","家庭护�?�有效期"},
{"eST.GRN.label","GRN"},
{"eST.GRNBatchSearch.label","分�?货物批次"},
{"eST.GRNDetailsfor.label","GRN明细"},
{"eST.GRNDetailsForReplacement.label","替代GRN明细"},
{"eST.GRNDocType.label","GRN文档类型"},
{"eST.GRNDocType/No.label","GRN文档类型�?�"},
{"eST.GRNHistory.label","GRN历�?�"},
{"eST.GRNHistoryRTVList.label","GRN历�?�退回列表"},
{"eST.GRNPreviewDetails.label","GRN预览详情"},
{"eST.GRNQuantity.label","GRN数�?"},
{"eST.GRNStatisticsReport.label","GRN统计报告"},
{"eST.GRNValue.label","GRN值"},
{"eST.HighestValueofPurchaseForAPPLDrugs.label","应用�?��?购买的最高值"},
{"eST.HighestValueofPurchaseForNONAPPLDrugs.label","�?�应用�?��?购买的最高值"},
{"eST.HomeCarepatients.label","家庭护�?�病人"},
{"eST.IncludeExpiredBatches.label","包括过期批次"},
{"eST.IncludeNotifiedBatches.label","包括分批通知"},
{"eST.IncludeStockIssues.label","包括�?�出库存"},
{"eST.IncludeSuspendedBatches.label","包括暂�?�批次"},
{"eST.IncludeZeroStockBatches.label","包括零库存批次"},
{"eST.IndicatesSuspendedBatch.label","包括暂�?�批次"},
{"eST.InsurancePolicyIsExpired Proceed.label","�?�?�已过期"},
{"eST.InsuranceYN.label","是�?�存在�?险 是/�?�?"},
{"eST.InterfacetoexternalPO.labelInterface to external PO","外部定�?�接�?�"},
{"eST.InternalStores.label","外部库房"},
{"eST.InventoryAgeingSlot.label","存货时间过长"},
{"eST.IssueBatchSearch.label","查找�?�出批次"},
{"eST.Issued.labelIssued","已�?�?�出"},
{"eST.IssuedItem.labelIssued Item","�?�出项目"},
{"eST.IssueIntegerQuantity.label","�?�出整数数�?"},
{"eST.IssuePreviewDetails.label","�?�出明细"},
{"eST.IssueReturnFinalize.label","�?�出退还完�?"},
{"eST.IssueReturnPreviewDetails.label","�?�出退还预览明细"},
{"eST.IssueReturns.label","�?�出退回"},
{"eST.IssuesCost.label","�?�放�?本"},
{"eST.IssueSequence.label","�?�放�?列"},
{"eST.IssueUOM.label","�?�放�?��?"},
{"eST.IssueUOMQuantity.label","�?�放�?��?数�?"},
{"eST.IssuingStore.label","�?�出库房"},
{"eST.ItemAnalysisCodeshouldbeunique.label","项目分�?代�?应该唯一"},
{"eST.ItemClassConsolidated.label","综�?�类项目"},
{"eST.ItemClassFrom.label","开始项目分类"},
{"eST.ItemClassStockValue.label","项目分�?代�?应该唯一"},
{"eST.ItemConsolidated.label","项目�?�并"},
{"eST.ItemDetails.label","项目明细"},
{"eST.ItemFrom.label","项目开始"},
{"eST.ItemGreaterthanMaximumLevel.label","数�?高于最大库存数�?"},
{"eST.ItemLessthanMinimumLevel.label","数�?低于最低库存数�?"},
{"eST.ItemLessthanReorderLevel.label","数�?低于历�?�记录"},
{"eST.ItemnotmappedtoDrug.label","�?��?�物项目"},
{"eST.ItemRequested.label","项目�?求"},
{"eST.ItemsBelowReorderLevel.label","项目低于历�?�记录"},
{"eST.ItemwithStock.label","存在库存项目"},
{"eST.JanDecby15thJan.label","从1月15日到12月"},
{"eST.JanDecby31stJan.label","从1月31日到12月"},
{"eST.KitTemplateCode.label","试剂盒模版代�?"},
{"eST.KitTemplateDescription.label","试剂盒模版�??述"},
{"eST.LastAccessedBy.label","上次访问日期"},
{"eST.LastAccessedOn.label","上次访问日期"},
{"eST.LeadDays.label","领先天数"},
{"eST.MachCode.label","机器代�?"},
{"eST.ManufacturedItems.label","�?�?"},
{"eST.MasterBinLocation.label","主存储�?置"},
{"eST.MFG.label","制造"},
{"eST.MFGItem.label","�?�?"},
{"eST.MFGReceipts.label","制造�?�票"},
{"eST.MFGUOM.label","制造�?��?"},
{"eST.MFGWorkloadStatisticsReport.label","制造工作�?统计报告"},
{"eST.ModifiedDate.labelModified Date","更改日期"},
{"eST.MovementCutoffMonthsSlotRanges.label","项目移动截止"},
{"eST.MoveYear.label","�?动???"},
{"eST.MoveYearFrom.label","开始日期"},
{"eST.MTDIssueQuantity.label","�?月�?�放数�?"},
{"eST.MTDReceiptsQuantity.label","�?月收�?�数�?"},
{"eST.NetStockPosition.label","净库存"},
{"eST.NewBatchYN.labelNew Batch(Yes/No)","建新批(Y/N)"},
{"eST.NoMovement.label","�?�移动库存"},
{"eST.NONAPPL.label","�?�适用"},
{"eST.NonPSItems.label","�?��?�房库存"},
{"eST.NonReorderableStoresOnly.label","�?记录项目的库房"},
{"eST.NonReorderableStoresStock.label","�?被记录的库存"},
{"eST.NonSpecialItem.label","�?�特殊项目"},
{"eST.NonZeroStock.label","�?�零库存"},
{"eST.NoofChecksbyStockVerificationBoard.label","核查库存数�?"},
{"eST.NoofrecordsperTransaction.label","�?次交易的记录数"},
{"eST.NoofUnfinalised/GLUninterfacedTransactions.label","未确定的交易数目"},
{"eST.Notify.label","指出"},
{"eST.NumberofGRNs.label","GRN数�?"},
{"eST.NumberofItemCondemnedRM.label","被拒�?项目的数�?"},
{"eST.NumberofItemsCounted.label","项目计数"},
{"eST.NumberofItemswithnveVariance.label","项目数�?差异"},
{"eST.NumberofItemswithpveVariance.label","项目数�?差异"},
{"eST.nursingunit/clinic.labelNursing Unit/Clinic","护�?�科室/�?��?"},
{"eST.OnlyNotifiedBatches.label","�?�有分批通知"},
{"eST.OpeningStock.label","�?始库存"},
{"eST.PartNoFrom.label","部分�?��?"},
{"eST.PayabAmt.label","付款�?"},
{"eST.PercentageOnPresentCount.label","百分比"},
{"eST.PhysicalCountSheetHistory.label","历�?�实物清点表"},
{"eST.PhysicalIdTotal.label","总的物�?�编�?�"},
{"eST.POCost.labelPO Cost","采购�?本"},
{"eST.PODiscount.labelPO Discount","采购折扣"},
{"eST.PORequest.labelPO Request","采购�?求"},
{"eST.PORequestFinalize.labelPORequest Finalize","订�?��?求被完�?"},
{"eST.PreparationMode.label","准备模�?"},
{"eST.PreparationType.label","准备类型"},
{"eST.PrepareInstruction.label","准备建议"},
{"eST.PresentCountStatus.label","�?始数�?"},
{"eST.PreviousQty.label","之�?数�?"},
{"eST.PrevYear12MonthsConsumption.label","全年消费"},
{"eST.ProcessExpiredBatch.label","处�?�过期批次"},
{"eST.ProcessLoss.label","过程报�?�"},
{"eST.ProcessLossPercent.label","报�?�百分批"},
{"eST.ProcessOption.label","过程�?作"},
{"eST.ProcessSuspendedBatch.label","批处�?�过程暂�?�"},
{"eST.ProductRecall.label","撤销产�?"},
{"eST.PRT.label","产�?转让"},
{"eST.PurchaseOrderRequest.labelPurchase Order Request","订购�?�请求"},
{"eST.PurchaseValueItems.label","购买项目值"},
{"eST.PuUOMFACTOR.label","购买�?��?/因素"},
{"eST.QAP13AnnualTurnoverRateofStock.label","�?年的库存效率??"},
{"eST.QAP14Proportionofvalueofstockswrittenoff.label","库存被注销"},
{"eST.RecommendationbyBoardofCondemn.label","Recommendation by Board of Condemn"},
{"eST.Reordarable.label","�?新排�?"},
{"eST.Reorderable.label","�?新排�?"},
{"eST.ReorderableItems.label","�?新排�?"},
{"eST.ReorderableStore.label","�?新排�?库房"},
{"eST.ReorderableStoresOnly.label","�?��?�以�?新排�?的库房"},
{"eST.ReorderableStoresstock.label","�?新排�?库存"},
{"eST.ReorderAttributes.label","�?新排�?属性"},
{"eST.ReorderDays.label","天数�?新排�?"},
{"eST.ReorderFreqDays.label","�?排天数频率"},
{"eST.ReorderQuantity.label","�?排数�?"},
{"eST.RepackingCode.label","包装代�?"},
{"eST.ReplacementGRN.label","替�?�GRN"},
{"eST.ReplacementGRNBatchSearch.label","查询更�?�GRN批次"},
{"eST.ReplacementOnExpiry.label","替代过期项目"},
{"eST.ReplacementRTV.label","替�?�RTV"},
{"eST.ReplacementRTVDetailsForItem.label","替�?�RTV项目明细"},
{"eST.ReplGRNQuantity.label","替�?�GRN数�?"},
{"eST.Replonexpiry.label","有效期替代"},
{"eST.ReplRTVQuantity.label","替代RTV数�?"},
{"eST.ReportExecutedBy.label","报告用户"},
{"eST.ReportMfgItemLabel.label","制造项目标签报告"},
{"eST.ReportOnGRNStatisticsForDrugs.label","�?�物GRN统计报告"},
{"eST.ReportRepackingLabel.label","�?新包装标签报告"},
{"eST.ReportSuspendedReinstateBatches.label","暂�?�/�?��?批次报告"},
{"eST.ReqBy.label","请求人"},
{"eST.ReqEntered.label","输入请求"},
{"eST.ReqGenerationBase.label","Req Generation Base"},
{"eST.ReqIssue.label","请求�?�放"},
{"eST.ReqItemDetailsfor.label","�?求项目的详细资料"},
{"eST.ReqNo.label","请求�?�"},
{"eST.ReqNoFrom.label","开始请求�?�"},
{"eST.ReqQty.label","请求数�?"},
{"eST.ReqStatisticsReport.label","请求统计报告"},
{"eST.ReqStatus.label","请求状�?"},
{"eST.ReqStore.label","请求库房"},
{"eST.ReqType.label","请求类型"},
{"eST.RequestedQtyinReqUOM.label","请求数�?"},
{"eST.RequestedQtyinStkUOM.label","请求数�?"},
{"eST.RequestedUOM.label","请求�?��?"},
{"eST.RequestItemDetailsfor.label","请求项目详细资料"},
{"eST.RequestOnStoreCode.label","基于库房的请求"},
{"eST.RequestqtyinReqUOM.label","请求的数�?�?��?"},
{"eST.RequestStatisticsReport.label","�?求统计报告"},
{"eST.RequisitionRef.label","所�?求项目的�?�考"},
{"eST.ReturnAllowed.labelReturn Allowed","�?许退还标志"},
{"eST.RevisedSalePrice.labelRevised Sale Price","修改/更新零售价"},
{"eST.ROQuantity.label","�?订购数�?"},
{"eST.RTV.label","TRV(退还贷应商,退的数�?)"},
{"eST.RTVDetails.label","RTV详细资料"},
{"eST.RTVDetailsforReplacementGRN.label","替代GRN的RTV详细资料"},
{"eST.RTVDocType/No.label","RTV文档类型/编�?�"},
{"eST.RTVforReplacement.label","替代RTV"},
{"eST.RTVHistory.label","RTV历�?�"},
{"eST.RTVPreviewDetails.label","RTV预览明细"},
{"eST.RTVQuantity.label","RTV�?�考文档"},
{"eST.RTVREF.label","RTV�?�考文档"},
{"eST.RTVValue.label","RTV值"},
{"eST.S.label","S"},
{"eST.SAL.label","SAL(零售)"},
{"eST.SalePrice.labelSale Price","零售价"},
{"eST.SalePriceHistory.labelSale Price History","零售价历�?�"},
{"eST.SalePriceOnceAmmendedCanNotBeChanged.labelSale Price Once Ammended Can Not Be Changed","零售价一旦更新,�?能修改"},
{"eST.SalePriceStatusHistory.labelSale Price Status History","以往零售价"},
{"eST.SalesBatchSearch.label","查询基准价"},
{"eST.SaleTrnType.label","零售交易类型"},
{"eST.SaleUOM.label","零售�?��?"},
{"eST.SameAsExpiryDate.label","失效期�?�上"},
{"eST.SoleSourceYN.label","�?�一�?��??Y/N"},
{"eST.SpecialItemYN.label","指定项目?Y/N"},
{"eST.SRT.label","销售退货交易"},
{"eST.StockFast/SlowMovementReport.label","快速/低速库存报告"},
{"eST.StockHandledByMedicalStore.label","医疗库房的库存处�?�"},
{"eST.StockHoldingAnalysisReport.label","库存处�?�分�?报告"},
{"eST.StockItemConsumption.label","库存消耗"},
{"eST.StockItemConsumptionPreviewDetails.label","库存项目消耗明细"},
{"eST.StockItemYN.label","库存项目?Y/N"},
{"eST.StockLevel.label","库存水平"},
{"eST.StockPositionof.label","库存�?置"},
{"eST.StockReorderStore.label","库房存货�?排�?"},
{"eST.StockStatusByItem.label","项目库存状�?"},
{"eST.StockStatusReportForTransactedItems.label","交易项目的库存状�?报告"},
{"eST.StockTurnOverRate.label","库存周转率"},
{"eST.StoreFrom.label","开始库房"},
{"eST.StoreItem.label","库房项目"},
{"eST.StoreItemClass.label","库房项目分类"},
{"eST.StoreLevel.label","库房级别"},
{"eST.StoreSubTotal.label","库房项组�?组汇总"},
{"eST.StoreTo.label","库房"},
{"eST.StorewiseConsumption.label","库房消耗"},
{"eST.StorewiseConsumptionforthePeriod.label","期间消耗分�?"},
{"eST.SummaryfortheItemClass.label","项目分类汇总"},
{"eST.SummaryofClasses.label","汇总分类"},
{"eST.SummaryReportatItemClassLevel.label","项目级别的总结报告"},
{"eST.SuppressSummary.label","�?止总结"},
{"eST.SuppressZeroVariance.label","�?考虑零差�?"},
{"eST.SupressZero.label","�?考虑0"},
{"eST.SuspendedBatches.label","暂�?�批次"},
{"eST.Tax.label","税"},
{"eST.ThisformistobesenttostatePharmacyDivisioneveryYear.label","此报告必须�?年�??交国家�?�房"},
{"eST.ThisStatePharmacyDivisionwillsendthisformtostatePharmaceuticalServicesDivisioneveryYear.label","�?年国家�?�房将把此报告�?��?到�?��?�?务部门"},
{"eST.ToDepartment.label","到达部门"},
{"eST.ToStoreBin.label","到过存储�?置"},
{"eST.ToStoreMasterBin.label","存储主�?置"},
{"eST.TotalCondemnID.label","Total Condemn ID"},
{"eST.TotalnoofLocationCode.label","�?置编�?汇总"},
{"eST.TotalPhysicalInventoryID.label","总的物�?�盘点�?�"},
{"eST.TotalVarianceValue.label","总的差异金�?"},
{"eST.TRN.label","交易"},
{"eST.TrnQty.label","交易数�?"},
{"eST.TrnQtyForPeriod.label","期间交易数�?"},
{"eST.TurnoverRate.label","移交比率"},
{"eST.UpTo.label","直到"},
{"eST.ValueCondemned.label","�?�失价值"},
{"eST.ValueOfStocksHeldAnnually.label","�?年处�?�库存值"},
{"eST.ValueOfStocksHeldon1stJanValueOfStocksHeldOn31stDecOfTheSameYear.label","(1月处�?�的值+12月处�?�值)/2"},
{"eST.VariancePostedBy.label","差异�?�布者"},
{"eST.VarianceReportatBatchLevel.label","批级别的分�?报告"},
{"eST.VarianceReportatItemLevel.label","项目分�?报告"},
{"eST.VarianceReportatStoreLevel.label","存储分�?报告"},
{"eST.VarQtynve.label","负的差�?数�?"},
{"eST.VarQtypve.label","正的差�?数�?"},
{"eST.VarValuenve.label","负的差�?值"},
{"eST.VarValuepve.label","正的差�?值"},
{"eST.ViewCostDetails.label","回顾�?本明细"},
{"eST.WardSupplyManufacturingAndRepackingOutput.label","病区供应商以�?��?包装输出"},
{"eST.Yield.label","生产"},
{"eST.YtdConsm.label","截止日期消耗"},
{"eST.YtdRecp.label","迄今为止的项目收�?�"},



};
}
