
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eFM.FMHoliday.FMHolidayManager
package eFM.FMHoliday;

/**
 * Remote interface for FMHoliday
 */
public interface FMHolidayManagerRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap insertFMHoliday(java.util.Properties p, java.util.HashMap passObjects) throws java.rmi.RemoteException;  
    java.util.HashMap updateFMHoliday(java.util.Properties p, java.util.HashMap passObjects) throws java.rmi.RemoteException;
    java.util.HashMap deleteFMHoliday(java.util.Properties p, java.util.HashMap passObjects) throws java.rmi.RemoteException;
	java.util.HashMap deleteMultipleFMHolidays(java.util.Properties p, java.util.HashMap passObjects) throws java.rmi.RemoteException; 
   
   
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
