/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMP.resources;

import java.util.*;

public class Labels_zh extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
		{"eMP.AcceptAlphanumeric.label","接�?�字�?"},
		{"eMP.AcceptApptRefNoReferralIDinRegisterPatient.label","接�?�预约�?�照�?�/登记病人�?�照�?�"},
		{"eMP.AcceptExpiryDate.label","接�?�失效日期"},
		{"eMP.AcceptforOtherPatientSeries.label","接�?�一系列其它病人"},
		{"eMP.AcceptOtherAltID.label","接�?�其它替代编�?�"},
		{"eMP.AcceptPatientNameasMultiparts.label","接�?�病人的姓�??作为？？？"},
		{"eMP.AcceptPatientNameinLocalLanguage.label","用当地语言接�?�病人姓�??"},
		{"eMP.AccessRightsforViewPatientPhoto.label","查看病人照片的�?��?"},
		{"eMP.ActivateInactivatePatient.label","�?�动/�?�活病人"},
		{"eMP.ActivateInactivateReason.label","�?�动�?�活原因"},
		{"eMP.activationremarks.label","�?�动备注"},
		{"eMP.ActiveStatus.label","主动地�?"},
		{"eMP.AddedDetails.label","增加细节"},
		{"eMP.AdditionalFields.label","其它字段"},
		{"eMP.AgeLimitofMother.label","�?亲的年龄特�?�?制"},
		{"eMP.AlertinAdv.label","在腺病毒警报。"},
		{"eMP.AliasName.label","别�??"},
		{"eMP.AllowRegistrationWithin.label","�?许注册"},
		{"eMP.AllowseparateMRN.label","�?许分离病历�?�"},
		{"eMP.Allseries.label","所有系列"},
		{"eMP.Alone.label","�?�独的"},
		{"eMP.AlphabetsandSpecialCharecters.label","字�?和特殊字符"},
		{"eMP.AlternateIDChecks.label","检查替代编�?�"},
		{"eMP.AlternateIDSeries.label","替代编�?�系列"},
		{"eMP.AlternateIDType.label","替代编�?�类型"},
		{"eMP.AlternateIDTypeforMembershipID.label","替�?�会员编�?�的编�?�类型"},
		{"eMP.Ambulance.label","救护车"},
		{"eMP.AnteNatalCare.label","产�?产�?�护�?�"},
		{"eMP.AntenatalCareDetails.label","产�?护�?�细节"},
//		{"eMP.ApplyEligibilityRulesbyPatientCategory.label","Apply Eligibility Rules by Patient Category"},
		{"eMP.apptreferraldtls.label","任命/推�??细节"},
		{"eMP.ApptSch.label","任命附表"},
		{"eMP.AreaDesc.label","区域说明"},
		{"eMP.Arrangement.label","安排"},
		{"eMP.AttendingMidwife.label","�?�与助产士"},
		{"eMP.AttendingNurse.label","�?�与护士"},
		{"eMP.Atthelevelof.label","在水平上"},
		{"eMP.AuditTrailParameterSettings.label","审计线索�?�数设置"},
		{"eMP.Baby.label","婴儿"},
		{"eMP.BabyName.label","婴儿姓�??"},
		{"eMP.BabySex.label","婴儿性别"},
		{"eMP.BabySuffix.label","婴儿�?�缀"},
		{"eMP.BCG.label","介苗"},
		{"eMP.BeforeArrival.label","抵达�?"},
		{"eMP.BirthAttendant.label","接生"},
		{"eMP.BirthCertificateNo.label","出生�?明编�?�"},
		{"eMP.BirthDateFrom.label","出生日期"},
		{"eMP.BirthOrder.label","出生顺�?"},
		{"eMP.BirthPlaceCode.label","�?贯代�?"},
		{"eMP.BirthPlaceDesc.label","出生地说明"},
		{"eMP.BirthWeight.label","出生体�?"},
		{"eMP.Bornat.label","出生于"},
		{"eMP.BornBeforeArrival.label","入�?之�?出生"},
		{"eMP.BornWhere.label","出生在哪里"},
		{"eMP.Bottle.label","瓶"},
		{"eMP.Breast.label","胸部"},
		{"eMP.ByName.label","姓�??"},
		{"eMP.CapturePatientPhoto.label","采集患者照片"},
		{"eMP.CareGiven.label","鉴于护�?�"},
		{"eMP.categoryexpirydate.label","病人类别的终止日期"},
		{"eMP.Changeallowedforseries.label","系列�?许�?�化"},
		{"eMP.ChangeDemographics.label","人�?��?�化"},
		{"eMP.ChartMaintenance.label","图表维修"},
		{"eMP.CheckDigit.label","校验�?"},
		{"eMP.CheckDigitScheme.label","检查�?数计划"},
		{"eMP.CheckDigitSchemeID.label","检查�?数计划编�?�"},
		{"eMP.CheckDigitSchemeName.label","检查�?数计划�??称"},
		{"eMP.CheckExp.label","检查试验"},
		{"eMP.CheckUnique.label","检查唯一性"},
		{"eMP.ChestCircum.label","胸围"},
		{"eMP.ChestCirumference.label","胸围"},
		{"eMP.ChgPatDtl.title.label","病人的细节�?�化"},
		{"eMP.child.label","孩�?"},
		{"eMP.ChildBirthDateFrom.label","儿童出生日期"},
		{"eMP.ChildBirthDateTo.label","儿童出生日期"},
		{"eMP.clinicaldetails.label","临床详情"},
		{"eMP.Combination.label","组�?�"},
		{"eMP.ComplicationsOfDeliveryCode.label","分娩并�?�症的代�?"},
		{"eMP.ComplicationsOfDeliveryDesc.label","分娩并�?�症的�??述"},
		{"eMP.CompofDelivery.label","分娩并�?�症"},
		{"eMP.CongenitalAnomalies.label","先天性畸形"},
		{"eMP.CongenitalAnomaliesCode.label","先天性畸形代�?"},
		{"eMP.CongenitalAnomaliesDesc.label","先天性畸性�??述"},
		{"eMP.ContactAddresses.label","�?�系地�?�"},
		{"eMP.ContactModes.label","�?�系方�?"},
		{"eMP.ContactPersonName.label","�?�系人姓�??"},
		{"eMP.CopyFirsttoNotify.label","�?制第一通知"},
		{"eMP.CopyHeadofFamily.label","�?制户主"},
		{"eMP.CopyNextofKin.label","�?制近亲"},
		{"eMP.CopyPatient.label","�?制病人"},
		{"eMP.CopyPatientAddress.label","�?制病人地�?�"},
		{"eMP.CopyResidenceAddress.label","�?制居�?地�?�"},
		{"eMP.CountryCode.label","国家代�?"},
		{"eMP.CountryName.label","国家�??字"},
		{"eMP.CreateFile.label","创建文件"},
		{"eMP.CreateFileduring.label","在创建文件"},
		{"eMP.CreatePatientFile.label","建立病人档案"},
		{"eMP.CutOffPeriod.label","切断期"},
		{"eMP.Deceasedonly.label","死者"},
		{"eMP.deceasedremarks.label","死者备注"},
		{"eMP.DefaultAltID1ValueinEmp.ID.label","雇员编�?�中默认�?�选的�?件�?�"},
//		{"eMP.DefaultSoundexType.label","Default Soundex Type"},
		{"eMP.DeliveryIndication.label","�?�?指示"},
		{"eMP.DeliveryIndicationCode.label","�?�?说明代�?"},
		{"eMP.DeliveryIndicationDesc.label","�?�?说明说明"},
		{"eMP.DeliverySurgicalClassification.label","手术分类"},
		{"eMP.DeliverySurgicalClassificationCode.label","手术分类代�?"},
		{"eMP.DeliverySurgicalClassificationDesc.label","手术分类说明"},
		{"eMP.DeliveryType.label","投放类型"},
		{"eMP.DeliveryTypeDesc.label","投放类型的说明"},
		{"eMP.demographicdetails.label","人�?�信�?�"},
//		{"eMP.DesignatedRoyalties.label","Designated Royalties"},
		{"eMP.District.label","区域"},
		{"eMP.DistrictCode.label","区域代�?"},
		{"eMP.DistrictCodeFrom.label","区域代�?"},
//		{"eMP.DocDesc.label","Doc Desc"},
		{"eMP.Doyouwanttochangethevalues.label","想更改数值？"},
		{"eMP.DuplicateMaster.label","多学�?？"},
		{"eMP.EducationLevel.label","教育水平"},
		{"eMP.EM.label","急诊"},
		{"eMP.EmergencySeries.label","急诊系列"},
		{"eMP.emerpatregn.label","急诊病人登记"},
		{"eMP.EmerRegn.label","紧急注册"},
		{"eMP.EnterPatientID.label","输入病人编�?�"},
		{"eMP.EntitlementApplicability.label","居留�?�的适用性"},
		{"eMP.EntitlementBy.label","居留�?�"},
		{"eMP.EntitlementPlan.label","居留�?�计划"},
		{"eMP.EstateWorkers.label","地产工人"},
		{"eMP.EthnicGroupCode.label","民�?组代�?"},
		{"eMP.EthnicGroupDescription.label","�?群�??述"},
		{"eMP.ethnicity.label","�?�?"},
		{"eMP.EthnicityCode.label","民�?�?"},
		{"eMP.EthnicityDesc.label","�?�?说明"},
		{"eMP.EthnicSubGroup.label","少数民�?�?组"},
		{"eMP.EthnicSubGroupCode.label","少数民�?�?组代�?"},
		{"eMP.EthnicSubGroupDesc.label","少数民�?组说明"},
		{"eMP.examclinicalfindings.label","测试与临床结果"},
		{"eMP.expiration.label","到期"},
		{"eMP.ExpiryApplicable.label","适用过期"},
		{"eMP.externalhospital.label","外部医院"},
		{"eMP.ExternalPatientDonorSeries.label","对外病人/�??助者系列"},
		{"eMP.ExternalReferralSource.label","对外推介�?��?"},
		{"eMP.ExternalSourceSeries.label","外部�?��?系列"},
//		{"eMP.FaceSheetDeclaration.label","Face Sheet Declaration"},
		{"eMP.family.label","家庭"},
		{"eMP.FamilyLink.label","家庭�?�系"},
		{"eMP.FamilyNameinOtherLanguage.label","外文�??"},
		{"eMP.FamilyNo.label","家庭编�?�"},
		{"eMP.fatherdetails.label","父亲详细情况"},
		{"eMP.fathername.label","父亲姓�??"},
		{"eMP.fatherremarks.label","父亲备注"},
		{"eMP.Feeding.label","喂养"},
		{"eMP.FieldName.label","字段�??"},
		{"eMP.FieldSize.label","字段长度"},
		{"eMP.FieldTitle.label","字段标题"},
		{"eMP.File.label","文件"},
		{"eMP.FileMaintenance.label","档案维护"},
		{"eMP.FileStorageLocn.label","文件存储�?置"},
		{"eMP.FileTypeCode.label","档类型代�?"},
		{"eMP.ForBaby.label","婴儿"},
		{"eMP.Foreigner.label","外国人"},
		{"eMP.ForEnglish.label","英语"},
		{"eMP.ForLocLang.label","本地语言"},
		{"eMP.Fresh.label","新鲜的？"},
		{"eMP.FullTimeEmployed.label","全�?�就业"},
		{"eMP.FullTimeStudent.label","全日制学生"},
		{"eMP.GeneralSeries.label","一般系列"},
		{"eMP.GeneratedFileNo.label","生�?文件编�?�"},
		{"eMP.GeneratePatientID.label","生�?病人编�?�"},
		{"eMP.GenerateSl.No.forUnknownPatients.label","生�?未知病人编�?�"},
		{"eMP.Gestation.label","妊娠"},
		{"eMP.given.label","鉴于"},
		{"eMP.GovtEmployee.label","政府雇员"},
//		{"eMP.GraceDays.label","Grace Days"},
		{"eMP.Gravida.label","孕妇"},
		{"eMP.GroupCount.label","组计数"},
		{"eMP.headfamilydetails.label","户主详细"},
		{"eMP.HeadofFamilyPatientID.label","户主病人编�?�"},
		{"eMP.headpatientdetails.label","负责病人的细节"},
//		{"eMP.HeadPatientID.label","Head Patient ID"},
		{"eMP.HepatitisB.label","B型�?炎"},
		{"eMP.holder.label","�?有人"},
		{"eMP.identitydetails.label","身份详情"},
		{"eMP.in10Min.label","10分钟内"},
		{"eMP.in1Min.label","1分钟内"},
		{"eMP.in5Min.label","5分钟内"},
		{"eMP.inactivationremarks.label","�?活动标识"},
		{"eMP.Inactiveonly.label","�?�是活动"},
		{"eMP.IndicatorMark.label","指示标志"},
//		{"eMP.InFacility.label","In Facility"},
		{"eMP.Informant.label","线人"},
		{"eMP.InformantRemarks.label","线人备注"},
		{"eMP.inhospital.label","在院"},
		{"eMP.InternalRequestReport.label","内部请求报告"},
		{"eMP.InternalRequestReportDesc.label","内部请求报告说明"},
		{"eMP.InternalRequestReportId.label","内部请求报告编�?�"},
//		{"eMP.InvokeChangePatientDetailsinNewbornRegn.label","Invoke Change Patient Details in Newborn Regn"},
		{"eMP.InvokeRoutine.label","调用常规"},
		{"eMP.IPAdmission.label","�?院病人登记"},
		{"eMP.IpBooking.label","�?院病人登记"},
		{"eMP.KeepFileNumbersameasPatientID.label","使病人编�?�和文件编�?�相�?�"},
		{"eMP.KeepMRNsameasPatientID.label","使病历�?�和病人编�?�相�?�"},
		{"eMP.lastcontact.label","最�?��?�系"},
		{"eMP.LastName.label","姓�?"},
		{"eMP.LastNameinOtherLanguage.label","外文姓�?"},
		{"eMP.LastPurgedDate.label","最�?�整肃日期"},
		{"eMP.latestmodifieddetails.label","最新修改的细节"},
		{"eMP.LegalName.label","法律�??称"},
		{"eMP.LegalNames.label","法律�??称"},
		{"eMP.Legend.label","传奇"},
//		{"eMP.LegendforLocLang.label","Legend for Loc Lang"},
		{"eMP.LengthofBaby.label","婴儿的长度"},
		{"eMP.Live.label","活的"},
		{"eMP.Livingarrangement.label","生活安排"},
		{"eMP.Macerated.label","浸�?"},
		{"eMP.mailing.label","邮寄"},
		{"eMP.MaintainFamilyLink.label","�?�?家庭�?�系"},
		{"eMP.MaintainOrganizationMembership.label","�?�?？？�?员"},
		{"eMP.manual.label","手册"},
		{"eMP.maritalstatus.label","婚姻状况"},
		{"eMP.MaritalStatusCode.label","婚姻状况代�?"},
		{"eMP.MaritalStatusDesc.label","婚姻状况�??述"},
		{"eMP.MaxPatientAge.label","病人最大年龄"},
		{"eMP.mcno.label","医疗�?编�?�"},
		{"eMP.Meconium.label","胎粪"},
		{"eMP.MedicalEntitlement.label","医疗居留�?�"},
		{"eMP.MedicalRecordAdministration.label","病案管�?�"},
		{"eMP.MedicalRecordNumber.label","病历�?��?"},
		{"eMP.MedicalRecordsAdministration.label","病案管�?�"},
		{"eMP.MedicalSupervisionReqd.label","所需的医疗监�?�"},
		{"eMP.membership.label","会员"},
		{"eMP.MembershipDetails.label","会员详细信�?�"},
		{"eMP.MinCutOff.label","最低�?度�?�消？"},
		{"eMP.MinimumAgeofFather.label","父亲的最�?年龄"},
		{"eMP.MotherBabyLink.label","婴儿的�?亲链接"},
		{"eMP.motherdetails.label","�?亲详细情况"},
		{"eMP.mothername.label","新生儿�?亲姓�??"},
		{"eMP.mothernameinothlang.label","�?亲其它�??字"},
		{"eMP.motherpatientid.label","产妇编�?�"},
		{"eMP.MotherPatientName.label","产妇姓�??"},
//		{"eMP.motherpmino.label","Mother's PMI No"},
		{"eMP.motherremarks.label","产妇备注"},
		{"eMP.mothers.label","产妇的"},
/*		{"eMP.MPAuditTrailParameter.label","MP Audit Trail Parameter"},
		{"eMP.MPInternalRequestReportRule.label","MP Internal Request Report Rule"},
		{"eMP.MPParameter.label","MP Parameter"},
		{"eMP.MPParameterforFacility.label","MP Parameter for Facility"},
		{"eMP.MPTerminalDigit.label","MP Terminal Digit"},
		{"eMP.MRAdministrationBy.label","MR Administration By"},
		{"eMP.MRSectionNotDefinedForthisSeries.label","MR Section Not Defined For this Series"},
		{"eMP.MultipleBirth.label","Multiple Birth"},
		{"eMP.NameDerivationLogic.label","Name Derivation Logic"},*/
		{"eMP.NamePrefixinOtherLanguage.label","其它语言的�??称�?缀"},
		{"eMP.names.label","�??称"},
		{"eMP.namesearchby.label","�??称查询"},
		{"eMP.NameSuffixinOtherLanguage.label","其它语言的�??称�?�缀"},
//		{"eMP.NationalID.label","National ID"},
//		{"eMP.NationalIDChecks.label","National ID Checks"},
//		{"eMP.NationalIDHolder.label","National ID Holder"},
//		{"eMP.NationalIDSeries.label","National ID Series"},
		{"eMP.natureofdelivery.label","自然分娩"},
		{"eMP.NewBorn.label","新生儿"},
		{"eMP.newborndetails.label","新生儿详细情况"},
		{"eMP.NewBornSeries.label","新生儿系列"},
		{"eMP.newvalues.label","新的数值"},
		{"eMP.NODType.label","糖尿病类型"},
		{"eMP.NODTypeCode.label","糖尿病类型代�?"},
		{"eMP.NODTypeDesc.label","糖尿病类型�??称"},
		{"eMP.nonorganizationmember.label","�?�组织�?员"},
		{"eMP.NoofGroups.label","群�?�"},
		{"eMP.noofmultiplebirths.label","多胞胎"},
		{"eMP.NoofPositions.label","排�??�?�"},
		{"eMP.NoofTerminalDigits.label","终端数�?�?�"},
//		{"eMP.NotPatent.label","Not Patent"},
		{"eMP.NumberingControl.label","编�?控制"},
		{"eMP.occupation.label","�?�业"},
		{"eMP.OccupationClass.label","�?�业 级别"},
		{"eMP.OccupationClassCode.label","�?�业级别代�?"},
		{"eMP.OccupationClassDesc.label","�?�业级别�??述"},
		{"eMP.OccupationCode.label","�?�业代�?"},
		{"eMP.OccupationDesc.label","�?�业�??述"},
		{"eMP.OccupationEmployer.label","雇主"},
		{"eMP.OccupationofthePerson.label","�?�业人"},
		{"eMP.OldFileNo.label","旧文件�?�"},
		{"eMP.OldReferrals.label","旧的�?�考"},
		{"eMP.oldvalues.label","旧值"},
		{"eMP.OPVisitRegistration.label","门诊病人登记"},
		{"eMP.OrderableProcedure.label","订购/程�?"},
		{"eMP.Ordernumber.label","订�?��?��?"},
		{"eMP.OrganizationID.label","组织编�?�"},
		{"eMP.organizationmember.label","组织会员"},
		{"eMP.OrganizationMembership.label","组织�?员"},
		{"eMP.OrganizationSubUnit.label","分�?��?组织"},
		{"eMP.OtherAltNo.label","其它替代�?�"},
		{"eMP.OtherDocAttached.label","其它文件所附"},
		{"eMP.othermodes.label","其它方�?"},
		{"eMP.OtherModesofTpt.label","其它�?输方�?的"},
		{"eMP.OtherName.label","其它�??称"},
		{"eMP.OtherNamOtherLang.label","其它语言诉其它�??称"},
		{"eMP.parentdetails.label","家长明细"},
		{"eMP.Parity.label","平价"},
		{"eMP.PartTimeEmployed.label","兼�?�"},
		{"eMP.PartTimeStudent.label","部分时间制学生"},
//		{"eMP.PatCatbyOrg.Membership.label","Pat Cat by Org. Membership"},
		{"eMP.PatencyofAnus.label","肛门通畅"},
		{"eMP.Patent.label","专利"},
		{"eMP.PatientCardTitle.label","病人�?�片标题"},
		{"eMP.PatientCategoryCode.label","病人类别代�?"},
		{"eMP.PatientCategoryDesc.label","病人类别的说明"},
		{"eMP.PatientCategoryType.label","病人类别类型"},
		{"eMP.PatientDateofBirth.label","患者的出生日期"},
		{"eMP.PatientIDFrom.label","病人编�?�"},
		{"eMP.PatientIDLength.label","病人编�?�长度"},
		{"eMP.PatientMaster.label","患者？"},
//		{"eMP.PatientNameDerivationLogic.label","Patient Name Derivation Logic"},
//		{"eMP.PatientNameinLocLang.Required.label","Patient Name in Loc Lang. Required"},
		{"eMP.PatientNumbering.label","病人编�?�"},
		{"eMP.PatientRegistrationTitle.label","病人登记"},
		{"eMP.PatientSearchResultFormat.label","病人�?�索结果格�?"},
		{"eMP.PatientSerieDesc.label","病人的一系列�??述"},
		{"eMP.PatientSeries.label","病人系列"},
		{"eMP.PatientSeriesCode.label","病人一系列代�?"},
		{"eMP.PatientSeriesSameAsMotherSeries.label","病人和�?亲�?�样系列？"},
		{"eMP.PatientSex.label","患者性别"},
		{"eMP.PatientSuspension.label","患者？？？"},
		{"eMP.Pensioner.label","�?�雇者"},
		{"eMP.Periodbetweentwodeliveries.label","两年间交付"},
		{"eMP.personaldetails.label","个人资料"},
		{"eMP.PersonUnderPoliceCustody.label","根�?�警方拘留人"},
		{"eMP.photo.label","图片"},
		{"eMP.PlaceOfIssue.label","�?�行地点"},
		{"eMP.PopulateFrom.label","从填充"},
		{"eMP.Postal.label","邮政"},
		{"eMP.postalcode.label","邮政编�?"},
		{"eMP.PostalDesc.label","邮政说明"},
		{"eMP.PrefFacility.label","所选诊室或医院"},
		{"eMP.prefix.label","�?缀"},
		{"eMP.PrefixRequired.label","�?缀必填"},
		{"eMP.PrefixSex.label","�?缀性别"},
		{"eMP.primaryresidenceno.label","主�?�?所�?�"},
		{"eMP.Prisoners.label","囚犯"},
		{"eMP.ProcedureClassification.label","程�?分类"},
		{"eMP.ProcedureClassificationCode.label","分类代�?程�?"},
		{"eMP.ProcedureClassificationDesc.label","程�?分类�??述"},
//		{"eMP.PromptforoldMRN.label","Prompt for old MRN"},
//		{"eMP.PurgeAudit.label","Purge Audit"},
//		{"eMP.PurgeChangesupto.label","Purge Changes upto"},
//		{"eMP.PurgeDate.label","Purge Date"},
//		{"eMP.PurgedDateFrom.label","Purged Date From"},
//		{"eMP.PurgedDateTo.label","Purged Date To"},
//		{"eMP.PurgedUntil.label","Purged Until"},
		{"eMP.RaceCode.label","比赛守则"},
		{"eMP.RaceCodes.label","比赛守则"},
		{"eMP.RaceDesc.label","竞赛说明"},
		{"eMP.RaceGroup.label","竞赛组"},
		{"eMP.RangeValues.label","范围值"},
		{"eMP.rapidregn.label","快速注册"},
//		{"eMP.RdAppts.label","RD Appointments"},
//		{"eMP.ReasonforActive.label","Reason for Active"},
//		{"eMP.ReasonforActiveInactive.label","Reason for Active/Inactive"},
//		{"eMP.ReasonforSuspension.label","Reason for Suspension"},
		{"eMP.RecordPatientDeath.label","记录患者死亡"},
		{"eMP.RecordRevokePatientDeath.label","记录/撤销病人死亡"},
		{"eMP.Reference.label","�?�考"},
		{"eMP.ReferralLetterNo.label","�?�考信编�?�"},
		{"eMP.ReferralNotes.label","推介笔记"},
		{"eMP.ReferredForIP.label","�?院病人�??�?�"},
		{"eMP.region.label","地区"},
		{"eMP.Regioncode.label","地区代�?"},
		{"eMP.RegionDesc.label","地区�??述"},
		{"eMP.RegisteredDisabled.label","残疾人登记"},
		{"eMP.RegisterPatient.label","病人登记册"},
		{"eMP.RegisterPatientReferral.label","转诊病人登记册"},
		{"eMP.RegisterReferraldetails.label","登记册推介细节"},
		{"eMP.RegistrationOutput.label","注册输出"},
		{"eMP.RegistrationSource.label","登记�?��?"},
		{"eMP.RegnDateFrom.label","注册日期"},
		{"eMP.RegnDateTo.label","注册日期"},
		{"eMP.RegNewBorn.label","新出生登记"},
//		{"eMP.regnfacility.label","Registration Facility"},
		{"eMP.RegnMonthFrom.label","登记月"},
		{"eMP.RegnMonthTo.label","登记月"},
		{"eMP.RegnType.label","登记类型"},
		{"eMP.regntypeno.label","注册类型/�?�"},
		{"eMP.RegnYearFrom.label","登记年"},
		{"eMP.RegnYearTo.label","登记年"},
		{"eMP.reinstatementremarks.label","�?��?谈�?"},
		{"eMP.relatedcontacts.label","相关�?�系人"},
		{"eMP.relatedmemberfamily.label","家庭相关�?员"},
		{"eMP.relatedmembernonfamily.label","�?�家庭相关�?员"},
		{"eMP.RelationshipCode.label","关系�?"},
		{"eMP.RelationshipDesc.label","关系�??述"},
//		{"eMP.RelationshipforOrganizationMember.label","Relationship for Orgn Member"},
		{"eMP.RelationshiptoHeadofFamily.label","户主关系家庭"},
		{"eMP.relationshipwithpatient.label","与患者的关系"},
		{"eMP.relative.label","关系"},
		{"eMP.ReligionDesc.label","宗教�??述"},
		{"eMP.remarksonrevoking.label","撤销备注"},
//		{"eMP.repository.label","Repository"},
		{"eMP.RequiredforAllSeries.label","�?求所有系列"},
		{"eMP.residenceaddress.label","居�?地�?�"},
		{"eMP.ResidenceArea.label","�?宅�?区"},
		{"eMP.ResidenceTown.label","居�?城市"},
		{"eMP.Resident.label","驻地"},
		{"eMP.ResidentialArea.label","�?宅�?区"},
		{"eMP.ResidentialTown.label","城市�?宅"},
		{"eMP.ReviewMotherbabylinkbeforeRegn.label","登记�?修改�?婴链接"},
		{"eMP.RevokePatientDeath.label","撤销病人死亡"},
		{"eMP.RoutineName.label","路由�??称"},
		{"eMP.searchfamilyname.label","�?�索姓�?"},
		{"eMP.searchothername.label","�?�寻其它�??称"},
		{"eMP.Second.label","二"},
		{"eMP.SectionType.label","科类"},
		{"eMP.SelectSeries.label","选择系列"},
		{"eMP.SelfEmployed.label","自雇人士"},
		{"eMP.Semigovernment.label","�?�政府"},
		{"eMP.SerialNumberNext.label","下一�?�?�"},
		{"eMP.SerialNumberStart.label","开始�?�?�"},
		{"eMP.SeriesType.label","系列类型"},
		{"eMP.SiteFacility.label","网站/基金"},
		{"eMP.SiteFacilityID.label","网站/设施编�?�"},
		{"eMP.SiteFacilityName.label","网站/设施�??称"},
		{"eMP.SmallChildren.label","�?孩�?"},
		{"eMP.SpecialCharacters.label","特殊字符"},
		{"eMP.SpecialityDesc.label","科室�??述"},
		{"eMP.SpouseDependent.label","�?赖�?�?�"},
		{"eMP.spouseonly.label","�?�有�?�?�"},
		{"eMP.Sr.Resident.label","高级驻地"},
		{"eMP.StandardFamilyName.label","标准姓�?"},
		{"eMP.StandardOtherName.label","其它标准�??称"},
		{"eMP.StateCode.label","国家代�?"},
		{"eMP.StateCodeFrom.label","国家代�?"},
		{"eMP.StillBorn.option.label","�?然生于？"},
		{"eMP.Stools.label","大便"},
		{"eMP.Student.label","学生"},
		{"eMP.Stump.label","残端"},
		{"eMP.Stumps.label","树桩"},
		{"eMP.suborgn.label","�?组组织"},
//		{"eMP.SubsequentRegnofMultipleBirthWithin.label","Subsequent Regn of Multiple Birth Within"},
		{"eMP.SubUnit.label","�?组�?��?"},
		{"eMP.SubUnitDetails.label","�?组�?��?细节"},
		{"eMP.SubUnitID.label","�?组�?��?编�?�"},
		{"eMP.Suffix.label","�?�缀"},
		{"eMP.SummarizationRange.label","综述幅度"},
		{"eMP.Suspendedonly.label","暂�?�"},
		{"eMP.SuspendingofService.label","暂�?��?务"},
		{"eMP.SuspendingServicetoPatient.label","暂�?��?务的病人"},
		{"eMP.SuspendReinstatePatient.label","暂�?�/�?��?病人"},
		{"eMP.suspensionremarks.label","暂�?�备注？？"},
		{"eMP.suspstatusremarks.label","暂�?�状�?/备注"},
		{"eMP.telephoneres.label","�?宅电�?"},
		{"eMP.TerminalDigitBy.label","数�?终端"},
		{"eMP.TerminalDigitCount.label","终端�?数计数"},
		{"eMP.TerminalDigitDerivationLogic.label","终端数字逻辑的推导"},
		{"eMP.TerminalDigitLevel.label","终端数字水平"},
		{"eMP.TerminalDigitsPosition.label","终端数字�?置"},
		{"eMP.Third.label","第三"},
		{"eMP.ThirdName.label","第三�??称"},
		{"eMP.TotalSelection.label","共计选择"},
		{"eMP.TownCodeFrom.label","城市代�?"},
		{"eMP.TownDesc.label","城市�??述"},
		{"eMP.UmbCordCutBy.label","�?带血�?少？？"},
		{"eMP.UmbilicalCord.label","�?血"},
		{"eMP.Unemployed.label","未就业"},
		{"eMP.UnmarriedIndicator.label","未婚指标"},
		{"eMP.UnrestrictedSeries.label","无�?制系列"},
		{"eMP.UsedStatus.label","使用现状"},
		{"eMP.vaccinationdetails.label","疫苗接�?详细信�?�"},
		{"eMP.VaccSite.label","接�?网站"},
		{"eMP.VaginalDeliveryType.label","阴�?�分娩类型"},
		{"eMP.VaginalDeliveryTypeCode.label","阴�?�分娩类型代�?"},
		{"eMP.VaginalDeliveryTypeDesc.label","阴�?�分娩类型�??述"},
		{"eMP.ValidforHeadPatientID.label","病人编�?�有效"},
		{"eMP.viewbirthregdtls.label","查看出生登记明细"},
		{"eMP.ViewMotherBabyLink.label","检视�?婴链接"},
		{"eMP.ViewPatientDetails.label","查看病人的细节"},
		{"eMP.ViewPatientPhoto.label","查看病人的照片"},
		{"eMP.VitaminK.label","维生素K"},
		{"eMP.WalkUp.label","步行"},
		{"eMP.WeightRange.label","�?�?范围"},
		{"eMP.WelcometoeHIS.label","欢迎使用EHIS"},
		{"eMP.WithAlternateID.label","�?�替�?�编�?�"},
//		{"eMP.WithNationalID.label","With National ID"},
//		{"eMP.YellowSoft.label","Yellow Soft"},
		{"eMP.LinkRelatedFamilyMembers.label","链接相关的家庭�?员"},
		{"eMP.RegistrationMode.label","注册模�?"},
		{"eMP.Rapid.label","快速"},
		{"eMP.DefaultPatientNameInEnglish.label","默认病人英文�??称"},
		{"eMP.DoctorAdministratorSignature.label","医生/署长签�??"},
//		{"eMP.SearchNameWithLocalLang.label","Search Name With Local Lang"},
//		{"eMP.PatientNameInLocalLang.label","Patient Name In Local Lang"},
		{"eMP.PersonProvideTreatmentBeforeDeath.label","死亡�?�??供治疗"},
		{"eMP.StartDurationOfDiseaseUntilDeath.label","开始病程，直至死亡"},
		{"eMP.PleaseWriteTheReasonOfDeath.label","请写的原因死亡"},
		{"eMP.InCaseDeathPersonIsFemale.label","死亡的人是女性"},
		{"eMP.NotPregnant.label","没有怀孕"},
		{"eMP.PregnantNotMoreThan6Weeks.label","怀孕�?超过6个星期"},
		{"eMP.DurationInStayingAtDeath.label","在居�?中死亡"},
		{"eMP.ParentOfDeathPerson.label","死亡人的父�?"},
//		{"eMP.SupportPersonOfDeath.label","？？"},
		{"eMP.HealthDepartmentPersonal.label","�?�生署个人"},
		{"eMP.LocationOfBirth.label","出生地点"},
		{"eMP.ChildDetails.label","儿童详情"},
		{"eMP.TotalNoOfChildren.label","儿童总人数"},
		{"eMP.DeathAtBirth.label","出生死亡"},
		{"eMP.DeathDuringPregnant.label","怀孕期间死亡"},
		{"eMP.PersonDelivered.label","人传递"},
//		{"eMP.SingleBirth.label","？？"},
		{"eMP.DurationOfPregnancy.label","怀孕期"},
		{"eMP.InjureFromPregnancy.label","从怀孕�?�伤"},
		{"eMP.DeformSinceBirth.label","�?�形自出生"},
		{"eMP.SicknessFromPregnancy.label","怀孕带�?�的疾病"},
		{"eMP.SicknessFromDelivery.label","疾病从交付？？？"},
		{"eMP.SicknessOutOfDelivery.label","疾病的交付？？？"},
		{"eMP.SpecialDelivery.label","特殊投递"},
		{"eMP.Province.label","�?"},
		{"eMP.ControlNo.label","控制�?�"},
		{"eMP.CertificateIssue.label","�?书�?�行"},
		{"eMP.ReportInBehalfOfParent.label","代表父�?的报告"},
		{"eMP.HouseOwnerReportInBehalfOfParent.label","代表父�?的屋主报告"},
		{"eMP.AlternateIDDesc.label","人物编�?�说明"},
		{"eMP.Activated.label","活动的"},
		{"eMP.InActivated.label","�?活动的"},
		{"eMP.ChangedAt.label","改�?�"},
		{"eMP.TransactionName.label","交易�??称"},
		{"eMP.ChangedOn.label","改�?�"},
		{"eMP.PatientNameLocal.label","病人本地�??字"},
//		{"eMP.Dlainterfacesearch.label","DLA Interface Search"},
//		{"eMP.surname.label","Sur Name"},
//		{"eMP.usercredentials.label","User Credentials"},
//		{"eMP.searchresult.label","Search Result"},
//		{"eMP.getimage.label","GetImage"},
		{"eMP.CurrentAddress.label","当�?地�?�"},
		{"eMP.PermanentAddress.label","永久地�?�"},
		{"eMP.NOKAddress.label","？？？地�?�"},
		{"eMP.SpouseName.label","�?�?�姓�??"},
		{"eMP.NearByPlace.label","近的地方"},
		{"eMP.CongenitalDisease.label","先天性疾病"},
		{"eMP.DrugAndOtherDisease.label","�?�物�?�疾病"},
		{"eMP.HospitalInformation.label","医院信�?�"},
		{"eMP.ToBeFilledByHospitalStaff.label","需�?医院人员填补"},
		{"eMP.SocialWelfareInformation.label","社会�?利信�?�"},
		{"eMP.ChangeAllowed.label","�?许改�?�"},
		{"eMP.EstimatedBirthDate.label","预产期"},
		{"eMP.EnterPassword.label","输入密�?"},
		{"eMP.AcceptPasswordinChangePatientDtls.label","修改�?�病信�?�时输入密�?"},
		{"eMP.ContactPerson.label","�?�系人"},
		{"eMP.FatherMotherName.label","父亲/�?亲姓�??"},
		{"eMP.CurrentPatientClass.label","当�?病人级别"},
		{"eMP.InvokePatientSearchinRegisterPatient.label","登记病人时�?�消病人查询"},
//		{"eMP.GeneratePatientIDusingAlternateID1Rule.label","Use Alternate ID1 Rule"},
		{"eMP.RelationshipLevel.label","关系水平"},
		{"eMP.RelationshipLevelCode.label","关系级别代�?"},
		{"eMP.RelationshipLevelDesc.label","关系级别�??述"},
		{"eMP.LinkedRelnshpLevel.label","相连的关系水平"},
		{"eMP.LinkedRelnshp.label","连结关系"},
		{"eMP.RelationShipLevInd.label","关系指票"},
		{"eMP.HeadofFamilyPatientName.label","户主姓�??患者"},
		{"eMP.PatientNumberingForRelation.label","病人关系"},
		{"eMP.SeparatorValue.label","分离价值"},
		{"eMP.SeparatorPosition.label","分离�?置"},
		{"eMP.PatientIDGenerationRule.label","病人编�?�生�?规则"},
//		{"eMP.ReqdforOrgnMember.label","Reqd for Orgn Member"},
//		{"eMP.AltID1RuleAppl.label","Alternate ID1 Rule Applicable"},
		{"eMP.Ambigious.label","歧义"},
		{"eMP.RelLevelLength.label","关系级别长度"},
//		{"eMP.AltID1RuleforPatNo.label","Alt ID1 Rule for Patient Numbering"},
		{"eMP.PatNumberingUsing.label","病人的编�?�使用"},
		{"eMP.SystemGenerated.label","系统生�?"},
//		{"eMP.GestationPeriod.label","Gestation Period"},
		{"eMP.Dusk.label","黄�?"},
		{"eMP.Waning.label","消退"},
		{"eMP.Compnotreltopreg.label","�?�孕期并�?�症"},
		{"eMP.Mothersillness.label","妇科病"},
		{"eMP.Certificateofficer.label","�?书干事"},
		{"eMP.Birth.label","出生"},
		{"eMP.Host.label","主人"},
		{"eMP.Representative.label","代表"},
		{"eMP.Rep.label","代表"},
//		{"eMP.RaceReqdDuringRegn.label","Race Required During Registration"},
		{"eMP.BannerType.label","横幅型"},
		{"eMP.PatientContextBanner.label","Patient Context Banner"},
		{"eMP.EncounterContextBanner.label","Encounter Context Banner"},
		{"eMP.ViewDefaultBanner.label","View Default Banner"},
		{"eMP.PreviewBanner.label","预览横幅"},
		{"eMP.ActualLength.label","实际长度"},
		{"eMP.DisplayLenght.label","显示长度"},
		{"eMP.SpaceBeforeText.label","文檔之�?的空格"},
		{"eMP.DisplayText.label","显示文字"},
		{"eMP.ToolTipText.label","�??示文字"},
		{"eMP.PatEncBanner.label","Patient / Encounter Context Banner"},
		{"eMP.MPAccessRights.label","MP访问�?��?"},
		{"eMP.NewbornID.label","新生儿编�?�"},
		{"eMP.PatientInformation.label","患者信�?�"},
		{"eMP.Tumbon.label","Tumbon"},
		{"eMP.ViewPatFinlDtls.label","查看病人的财务细节"},
		{"eMP.EmailNotification.label","适用预约时，邮件通知"},
		{"eMP.Father.label","父亲"},
		{"eMP.CitizenId.label","公民身份�?"},
		{"eMP.ICertfiedAllInfo.label","本人认�?的所有资料和照片"},
		{"eMP.TrueAndValid.label","是真正的和有效的"},
	//newly added lege21/01/09
		{"eMP.AltID1RuleAppl.label","替代ID1规则"},
{"eMP.AltID1RuleforPatNo.label","病人数目替代ID1规则"},
{"eMP.ApplyEligibilityRulesbyPatientCategory.label","分类规则"},
{"eMP.DefaultSoundexType.label","缺�?探测法类型"},
{"eMP.DesignatedRoyalties.label","指定费用"},
{"eMP.Dlainterfacesearch.label","DLA接�?�查询"},
{"eMP.DocDesc.label","文档�??述"},
{"eMP.EncounterContextBanner.label","病例背景"},
{"eMP.FaceSheetDeclaration.label","�?��?�定义"},
{"eMP.GeneratePatientIDusingAlternateID1Rule.label","用替�?�言之ID1规则"},
{"eMP.GestionalPeriod.label","妊娠期"},
{"eMP.getimage.label","获�?�图�?"},
{"eMP.GraceDays.label","宽�?期"},
{"eMP.HeadPatientID.label","Head Patient ID"},
{"eMP.InFacility.label","在院"},
{"eMP.InvokeChangePatientDetailsinNewbornRegn.label","新生儿登记时调用病人明细"},
{"eMP.LegendforLocLang.label","当地语言传说"},
{"eMP.motherpmino.label","�?亲的个人医疗索引代�?�?�"},
{"eMP.MPAuditTrailParameter.label","MP审计�?�数"},
{"eMP.MPInternalRequestReportRule.label","MP内部审计�?�数"},
{"eMP.MPParameter.label","MP�?�数"},
{"eMP.MPParameterforFacility.label","医院MP�?�数"},
{"eMP.MPTerminalDigit.label","MP数字终端"},
{"eMP.MRAdministrationBy.label","病历管�?�人"},
{"eMP.MRSectionNotDefinedForthisSeries.label","此系列未定义病历科"},
{"eMP.MultipleBirth.label","多胎"},
{"eMP.NameDerivationLogic.label","姓�??推导逻辑"},
{"eMP.NationalID.label","身份�?�?�"},
{"eMP.NationalIDChecks.label","身份�?�?�验�?"},
{"eMP.NationalIDHolder.label","身份�?�?有人"},
{"eMP.NationalIDSeries.label","身份�?系列"},
{"eMP.NotPatent.label","Not Patent"},
{"eMP.PatCatbyOrg.Membership.label","组织�?员分类"},
{"eMP.PatEncBanner.label","Patient / Encounter Context Banner"},
{"eMP.PatientContextBanner.label","Patient Context Banner"},
{"eMP.PatientNameDerivationLogic.label","病人姓�??推导逻辑"},
{"eMP.PatientNameInLocalLang.label","病人的�?语�??"},
{"eMP.PatientNameinLocLang.Required.label","�?求病人的�?语�??"},
{"eMP.PrefFacility.label","首选医院"},
{"eMP.PromptforoldMRN.label","�??醒旧的病历�?�"},
{"eMP.PurgeAudit.label","删除痕迹"},
{"eMP.PurgeChangesupto.label","登录记录删除期"},
{"eMP.PurgeDate.label","删除日期"},
{"eMP.PurgedDateFrom.label","开始删除日期"},
{"eMP.PurgedDateTo.label","结�?�删除日期"},
{"eMP.PurgedUntil.label","删除直到"},
{"eMP.RaceReqdDuringRegn.label","登记时�?求国�?"},
{"eMP.RdAppts.label","放射预约"},
{"eMP.ReasonforActive.label","有效原因"},
{"eMP.ReasonforActiveInactive.label","有效/无效原因"},
{"eMP.ReasonforSuspension.label","暂�?�原因"},
{"eMP.regnfacility.label","注册医院"},
{"eMP.RelationshipforOrganizationMember.label","登记�?员"},
{"eMP.repository.label","数�?�存储"},
{"eMP.ReqdforOrgnMember.label","�?求的�?员"},
{"eMP.SearchNameWithLocalLang.label","本地语言查询姓�??"},
{"eMP.searchresult.label","查询结果"},
{"eMP.SingleBirth.label","�?�胎"},
{"eMP.SubsequentRegnofMultipleBirthWithin.label","�?�续多胎登记"},
{"eMP.SupportPersonOfDeath.label","支�?人死亡"},
{"eMP.surname.label","最�?�姓�??"},
{"eMP.Tumbon.label","Tumbon"},
{"eMP.usercredentials.label","用户凭�?�"},
{"eMP.ViewDefaultBanner.label","查看缺�?"},
{"eMP.WithNationalID.label","身份�?�?�"},
{"eMP.YellowSoft.label","软黄色"},

	};
}
