package eMP.resources;

import java.util.*;

public class Labels_ar extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
{"eMP.AcceptAlphanumeric.label","قبول الأبجدية الرقمية"},
{"eMP.AcceptApptRefNoReferralIDinRegisterPatient.label","قبول الرقم المرجعي للموعد / معرّف الإحالة في تسجيل المريض"},
{"eMP.AcceptExpiryDate.label","قبول تاريخ انتهاء الصلاحية"},
{"eMP.AcceptforOtherPatientSeries.label","قبول لسلسلة المرضى الآخرين"},
{"eMP.AcceptOtherAltID.label","قبول معرف بديل آخر"},
{"eMP.AcceptPatientNameasMultiparts.label","قبول اسم المريض كأجزاء متعددة"},
{"eMP.AcceptPatientNameinLocalLanguage.label","قبول اسم المريض باللغة المحلية"},
{"eMP.AccessRightsforViewPatientPhoto.label","حقوق الوصول لعرض صورة المريض"},
{"eMP.ActivateInactivatePatient.label","تنشيط / تعطيل المريض"},
{"eMP.ActivateInactivateReason.label","سبب التنشيط/ التعطيل"},
{"eMP.activationremarks.label","ملاحظات التنشيط"},
{"eMP.ActiveStatus.label","الحالة النشطة"},
{"eMP.AddedDetails.label","التفاصيل المضافة"},
{"eMP.AdditionalFields.label","حقول إضافية"},
{"eMP.AgeLimitofMother.label","حد عمر الأم"},
{"eMP.AlertinAdv.label","تنبيه مقدما."},
{"eMP.AliasName.label","الاسم المستعار"},
{"eMP.AllowRegistrationWithin.label","السماح بالتسجيل ضمن"},
{"eMP.AllowseparateMRN.label","السماح ب MRN منفصل"},
{"eMP.Allseries.label","كل السلاسل"},
{"eMP.Alone.label","وحيد"},
{"eMP.AlphabetsandSpecialCharecters.label","الحروف الهجائية والرموز الخاصة"},
{"eMP.AlternateIDChecks.label","التحقق من الهوية البديلة"},
{"eMP.AlternateIDSeries.label","سلسلة المعرف البديل"},
{"eMP.AlternateIDType.label","نوع المعرف البديل"},
{"eMP.AlternateIDTypeforMembershipID.label","نوع معرف البديل لمعرف العضوية"},
{"eMP.Ambulance.label","سياره اسعاف"},
{"eMP.AnteNatalCare.label","رعاية ما قبل الولادة"},
{"eMP.AntenatalCareDetails.label","تفاصيل رعاية ما قبل الولادة"},
{"eMP.ApplyEligibilityRulesbyPatientCategory.label","تطبيق قواعد الأهلية حسب فئة المريض"},
{"eMP.apptreferraldtls.label","تفاصيل التعيين / الإحالة"},
{"eMP.ApptSch.label","جدول المواعيد"},
{"eMP.AreaDesc.label","وصف المنطقة"},
{"eMP.Arrangement.label","ترتيب"},
{"eMP.AttendingMidwife.label","القابلة"},
{"eMP.AttendingNurse.label","ممرضة حاضرة"},
{"eMP.Atthelevelof.label","في مستوي ال"},
{"eMP.AuditTrailParameterSettings.label","تدوين إعدادات معلمة المسار"},
{"eMP.Baby.label","طفل"},
{"eMP.BabyName.label","اسم الطفل"},
{"eMP.BabySex.label","جنس الطفل"},
{"eMP.BabySuffix.label","طفل لاحقة"},
{"eMP.BCG.label","BCG"},
{"eMP.BeforeArrival.label","قبل الوصول"},
{"eMP.BirthAttendant.label","قابلة"},
{"eMP.BirthCertificateNo.label","رقم شهادة الميلاد"},
{"eMP.BirthDateFrom.label","تاريخ الميلاد من"},
{"eMP.BirthOrder.label","ترتيب الولادة"},
{"eMP.BirthPlaceCode.label","رمز مكان الميلاد"},
{"eMP.BirthPlaceDesc.label","وصف مكان الميلاد"},
{"eMP.BirthWeight.label","الوزن عند الولادة"},
{"eMP.Bornat.label","ولد في"},
{"eMP.BornBeforeArrival.label","ولد قبل الوصول"},
{"eMP.BornWhere.label","أين ولد"},
{"eMP.Bottle.label","زجاجة"},
{"eMP.Breast.label","صدر"},
{"eMP.ByName.label","بالاسم"},
{"eMP.CapturePatientPhoto.label","التقاط صورة المريض"},
{"eMP.CareGiven.label","الرعاية المقدمة"},
{"eMP.categoryexpirydate.label","تاريخ انتهاء فئة المريض"},
{"eMP.Changeallowedforseries.label","التغيير المسموح به للمسلسل"},
{"eMP.ChangeDemographics.label","تغيير الديموغرافيات"},
{"eMP.ChartMaintenance.label","صيانة الرسم البياني"},
{"eMP.CheckDigit.label","تحقق من الرقم"},
{"eMP.CheckDigitScheme.label","تحقق من مخطط الأرقام"},
{"eMP.CheckDigitSchemeID.label","تحقق من معرف مخطط الأرقام"},
{"eMP.CheckDigitSchemeName.label","تحقق من اسم مخطط الأرقام"},
{"eMP.CheckExp.label","تحقق من الصلاحية"},
{"eMP.CheckUnique.label","تحقق من التفرد"},
{"eMP.ChestCircum.label","محيط الصدر"},
{"eMP.ChestCirumference.label","محيط الصدر"},
{"eMP.ChgPatDtl.title.label","تغيير بيانات المريض"},
{"eMP.child.label","طفل"},
{"eMP.ChildBirthDateFrom.label","تاريخ ميلاد الطفل من"},
{"eMP.ChildBirthDateTo.label","تاريخ ميلاد الطفل إلى"},
{"eMP.clinicaldetails.label","التفاصيل السريرية"},
{"eMP.Combination.label","مزيج"},
{"eMP.ComplicationsOfDeliveryCode.label","كود مضاعفات الولادة"},
{"eMP.ComplicationsOfDeliveryDesc.label","وصف مضاعفات الولادة"},
{"eMP.CompofDelivery.label","مضاعفات الولادة"},
{"eMP.FetusCompofDelivery.label","مضاعفات الولادة للجنين"},
{"eMP.CongenitalAnomalies.label","التشوهات الخلقية"},
{"eMP.CongenitalAnomaliesCode.label","كود التشوهات الخلقية"},
{"eMP.CongenitalAnomaliesDesc.label","وصف التشوهات الخلقية"},
{"eMP.ContactAddresses.label","عناوين الاتصال"},
{"eMP.ContactModes.label","طرق الاتصال"},
{"eMP.ContactPersonName.label","اسم شخص الاتصال"},
{"eMP.CopyFirsttoNotify.label","نسخ أولا للإعلام"},
{"eMP.CopyHeadofFamily.label","نسخة رب الأسرة"},
{"eMP.CopyNextofKin.label","نسخ التالي من الأقارب"},
{"eMP.CopyPatient.label","نسخ المريض"},
{"eMP.CopyPatientAddress.label","نسخ عنوان المريض"},
{"eMP.CopyResidenceAddress.label","نسخ عنوان السكن"},
{"eMP.CountryCode.label","كود الدولة"},
{"eMP.CountryDesc.label","وصف الدولة"},
{"eMP.CountryName.label","اسم الدولة"},
{"eMP.CreateFile.label","إنشاء ملف"},
{"eMP.CreateFileduring.label","إنشاء ملف أثناء"},
{"eMP.CreatePatientFile.label","إنشاء ملف المريض"},
{"eMP.CutOffPeriod.label","فترة الانقطاع"},
{"eMP.Deceasedonly.label","المتوفى فقط"},
{"eMP.deceasedremarks.label","ملاحظات المتوفى"},
{"eMP.DefaultAltID1ValueinEmp.ID.label","المعرف البديل الافتراضي 1 القيمة في معرف الموظف"},
{"eMP.DefaultSoundexType.label","نوع الصوت الافتراضي"},
{"eMP.DeliveryIndication.label","مؤشر الولادة"},
{"eMP.DeliveryIndicationCode.label","كود مؤشر الولادة"},
{"eMP.DeliveryIndicationDesc.label","وصف مؤشر الولادة"},
{"eMP.DeliverySurgicalClassification.label","التصنيف الجراحي للولادة"},
{"eMP.DeliverySurgicalClassificationCode.label","كود تصنيف الولادة الجراحية"},
{"eMP.DeliverySurgicalClassificationDesc.label","وصف تصنيف الولادة الجراحية"},
{"eMP.DeliveryTypeBirthReg.label","نوع التسليم: تسجيل الولادة"},
{"eMP.DeliveryType.label","نوع الولادة"},
{"eMP.DeliveryTypeDesc.label","وصف نوع الولادة"},
{"eMP.demographicdetails.label","التفاصيل الديموغرافية"},
{"eMP.DesignatedRoyalties.label","الإتاوات المعينة"},
{"eMP.District.label","المنطقة"},
{"eMP.DistrictCode.label","كود المنطقة"},
{"eMP.DistrictCodeFrom.label","رمز المنطقة من"},
{"eMP.DocDesc.label","وصف الوثيقة"},
{"eMP.Doyouwanttochangethevalues.label","هل تريد تغيير القيم"},
{"eMP.DuplicateMaster.label","ملف التكرار"},
{"eMP.EducationLevel.label","مستوى التعليم"},
{"eMP.EM.label","طارئ"},
{"eMP.EmergencySeries.label","تسلسل الطوارئ"},
{"eMP.emerpatregn.label","تسجيل مرضى الطوارئ"},
{"eMP.EmerRegn.label","التسجيل في حالات الطوارئ"},
{"eMP.EnterPatientID.label","أدخل هوية المريض"},
{"eMP.EntitlementApplicability.label","تطبيق الاستحقاق"},
{"eMP.EntitlementBy.label","الاستحقاق بواسطة"},
{"eMP.EntitlementPlan.label","خطة الاستحقاق"},
{"eMP.EstateWorkers.label","عمال العقارات"},
{"eMP.EthnicGroupCode.label","كود المجموعة العرقية"},
{"eMP.EthnicGroupDescription.label","وصف المجموعة العرقية"},
{"eMP.ethnicity.label","الأصل العرقي"},
{"eMP.EthnicityCode.label","قانون العرق"},
{"eMP.EthnicityDesc.label","وصف العرق"},
{"eMP.EthnicSubGroup.label","المجموعة العرقية الفرعية"},
{"eMP.EthnicSubGroupCode.label","كود المجموعة الفرعية العرقية"},
{"eMP.EthnicSubGroupDesc.label","وصف المجموعة العرقية الفرعية"},
{"eMP.examclinicalfindings.label","نتائج الفحص والنتائج السريرية"},
{"eMP.expiration.label","انتهاء الصلاحية"},
{"eMP.ExpiryApplicable.label","تاريخ انتهاء الصلاحية"},
{"eMP.externalhospital.label","مستشفى خارجي"},
{"eMP.ExternalPatientDonorSeries.label","تسلسل المريض الخارجي / المتبرع"},
{"eMP.ExternalReferralSource.label","مصدر الإحالة الخارجي"},
{"eMP.ExternalSourceSeries.label","تسلسل المصدر الخارجي"},
{"eMP.FaceSheetDeclaration.label","إعلان اول ورقة "},
{"eMP.family.label","عائلة"},
{"eMP.FamilyLink.label","رابط العائلة"},
{"eMP.FamilyNameinOtherLanguage.label","اسم العائلة بلغة أخرى"},
{"eMP.FamilyNo.label","رقم الأسرة"},
{"eMP.fatherdetails.label","تفاصيل الأب"},
{"eMP.fathername.label","اسم الأب"},
{"eMP.fatherremarks.label","ملاحظات الأب"},
{"eMP.Feeding.label","تغذية"},
{"eMP.FieldName.label","اسم الحقل"},
{"eMP.FieldSize.label","حجم الحقل"},
{"eMP.FieldTitle.label","عنوان الحقل"},
{"eMP.File.label","ملف"},
{"eMP.FileMaintenance.label","صيانة الملف"},
{"eMP.FileStorageLocn.label","موقع تخزين الملفات"},
{"eMP.FileTypeCode.label","رمز نوع الملف"},
{"eMP.ForBaby.label","للطفل"},
{"eMP.Foreigner.label","أجنبي"},
{"eMP.ForEnglish.label","للغة الإنجليزية"},
{"eMP.ForLocLang.label","للغة المحلية"},
{"eMP.Fresh.label","طازج"},
{"eMP.FullTimeEmployed.label","يعمل بدوام كامل"},
{"eMP.FullTimeStudent.label","طالب بدوام كامل"},
{"eMP.GeneralSeries.label","التسلسل العام"},
{"eMP.GeneratedFileNo.label","رقم الملف الذي تم إنشاؤه"},
{"eMP.GeneratePatientID.label","إنشاء هوية المريض"},
{"eMP.GenerateSl.No.forUnknownPatients.label","إنشاء الرقم التسلسلي للمرضى غير المعروفين"},
{"eMP.Gestation.label","الحمل"},
{"eMP.given.label","معطى"},
{"eMP.GovtEmployee.label","موظف حكومي"},
{"eMP.GraceDays.label","أيام السماح"},
{"eMP.Gravida.label","عدد مرات الحمل"},
{"eMP.GroupCount.label","عدد المجموعة"},
{"eMP.headfamilydetails.label","تفاصيل الأسرة الرئيسية"},
{"eMP.HeadofFamilyPatientID.label","هوية مريض رئيس العائلة"},
{"eMP.headpatientdetails.label","تفاصيل رئيس المريض"},
{"eMP.HeadPatientID.label","معرف المريض الرئيسي"},
{"eMP.HepatitisB.label","التهاب الكبد ب"},
{"eMP.holder.label","مالك"},
{"eMP.identitydetails.label","تفاصيل الهوية"},
{"eMP.in10Min.label","في 10 دقائق"},
{"eMP.in1Min.label","في 1 دقيقة"},
{"eMP.in5Min.label","في 5 دقائق"},
{"eMP.inactivationremarks.label","ملاحظات التعطيل"},
{"eMP.Inactiveonly.label","غير نشط فقط"},
{"eMP.IndicatorMark.label","علامة المؤشر"},
{"eMP.InFacility.label","في المنشأة الصحية"},
{"eMP.Informant.label","المخبر"},
{"eMP.InformantRemarks.label","ملاحظات المخبر"},
{"eMP.inhospital.label","في المستشفى"},
{"eMP.InternalRequestReport.label","تقرير الطلب الداخلي"},
{"eMP.InternalRequestReportDesc.label","وصف تقرير الطلب الداخلي"},
{"eMP.InternalRequestReportId.label","معرف تقرير الطلب الداخلي"},
{"eMP.InvokeChangePatientDetailsinNewbornRegn.label","استدعاء تغيير تفاصيل المريض في تسجيل حديثي الولادة"},
{"eMP.InvokeRoutine.label","استدعاء الروتين"},
{"eMP.IPAdmission.label","دخول المرضى الداخليين"},
{"eMP.IpBooking.label","حجز المرضى الداخليين"},
{"eMP.KeepFileNumbersameasPatientID.label","الاحتفاظ برقم الملف مثل معرف المريض"},
{"eMP.KeepMRNsameasPatientID.label","احتفظ بالسجل الطبي بنفس رقم المريض"},
{"eMP.lastcontact.label","آخر جهة اتصال"},
{"eMP.LastName.label","الكنية"},
{"eMP.LastNameinOtherLanguage.label","اسم العائلة بلغة أخرى"},
{"eMP.LastPurgedDate.label","تاريخ آخر مسح"},
{"eMP.latestmodifieddetails.label","أحدث التفاصيل المعدلة"},
{"eMP.LegalName.label","الاسم القانوني"},
{"eMP.LegalNames.label","الأسماء القانونية"},
{"eMP.Legend.label","عنوان تفسيري"},
{"eMP.LegendforLocLang.label","العنوان التفسيري للغة المحلية"},
{"eMP.LengthofBaby.label","طول المولود"},
{"eMP.Live.label","حي"},
{"eMP.Livingarrangement.label","ترتيب المعيشة"},
{"eMP.Macerated.label","منقوع"},
{"eMP.mailing.label","المراسلات"},
{"eMP.MaintainFamilyLink.label","حافظ على ربطة العائلة"},
{"eMP.MaintainOrganizationMembership.label","الاحتفاظ بعضوية المنظمة"},
{"eMP.manual.label","يدوي"},
{"eMP.maritalstatus.label","الحالة الإجتماعية"},
{"eMP.MaritalStatusCode.label","كود الحالة الاجتماعية"},
{"eMP.MaritalStatusDesc.label","وصف الحالة الاجتماعية"},
{"eMP.MaxPatientAge.label","أقصى عمر للمريض"},
{"eMP.mcno.label","رقم الشهادة الطبية"},
{"eMP.Meconium.label","Meconium"},
{"eMP.MedicalEntitlement.label","الاستحقاق الطبي"},
{"eMP.MedicalRecordAdministration.label","إدارة السجلات الطبية"},
{"eMP.MedicalRecordNumber.label","رقم السجل الطبي"},
{"eMP.MedicalRecordsAdministration.label","إدارة السجلات الطبية"},
{"eMP.MedicalSupervisionReqd.label","مطلوب إشراف طبي"},
{"eMP.membership.label","عضوية"},
{"eMP.MembershipDetails.label","تفاصيل العضوية"},
{"eMP.MinCutOff.label","الحد الأدنى للقطع"},
{"eMP.MinimumAgeofFather.label","الحد الأدنى لسن الأب"},
{"eMP.MotherBabyLink.label","رابط الأم بيبي"},
{"eMP.motherdetails.label","تفاصيل الأم"},
{"eMP.mothername.label","اسم والدة المولود"},
{"eMP.mothernameinothlang.label","اسم الأم في لغة أخرى"},
{"eMP.motherpatientid.label","رقم والدة المريض"},
{"eMP.MotherPatientName.label","اسم والدة المريض"},
{"eMP.motherpmino.label","رقم فهرس والدة المريض"},
{"eMP.motherremarks.label","ملاحظات الأم"},
{"eMP.mothers.label","الأم"},
{"eMP.MPAuditTrailParameter.label","إعدادات مسار التدقيق MP"},
{"eMP.MPInternalRequestReportRule.label","قاعدة تقرير الطلب الداخلي لـ MP"},
{"eMP.MPParameter.label","MP إعدادات"},
{"eMP.MPParameterforFacility.label","MP إعدادات للمنشأة"},
{"eMP.MPTerminalDigit.label","رقم طرفية MP"},
{"eMP.MRAdministrationBy.label","إدارة السجلات الطبية"},
{"eMP.MRSectionNotDefinedForthisSeries.label","قسم السجلات الطبية غير محدد لهذه السلسلة"},
{"eMP.MultipleBirth.label","تعدد المواليد"},
{"eMP.NameDerivationLogic.label","منطق اشتقاق الاسم"},
{"eMP.NamePrefixinOtherLanguage.label","بادئة الاسم بلغة أخرى"},
{"eMP.names.label","الأسماء"},
{"eMP.namesearchby.label","البحث عن الاسم عن طريق"},
{"eMP.NameSuffixinOtherLanguage.label","لاحقة الاسم بلغة أخرى"},
{"eMP.NationalID.label","الرقم القومي"},
{"eMP.NationalIDChecks.label","التحقق من الرقم القومي"},
{"eMP.NationalIDHolder.label","حامل الرقم القومي"},
{"eMP.NationalIDSeries.label","تسلسل الرقم القومي"},
{"eMP.natureofdelivery.label","طبيعة الولادة"},
{"eMP.NewBorn.label","مولود جديد"},
{"eMP.newborndetails.label","تفاصيل حديثي الولادة"},
{"eMP.NewBornSeries.label","تسلسل المولود الجديد"},
{"eMP.newvalues.label","قيم جديدة"},
{"eMP.NODType.label","طبيعة نوع الولادة"},
{"eMP.NODTypeCode.label","كود طبيعة نوع الولادة"},
{"eMP.NODTypeDesc.label","وصف طبيعة نوع الولادة"},
{"eMP.nonorganizationmember.label","عضو غير منظم"},
{"eMP.NoofGroups.label","عدد المجموعات"},
{"eMP.noofmultiplebirths.label","عدد الولادات المتعددة"},
{"eMP.NoofPositions.label","عدد المناصب"},
{"eMP.NoofTerminalDigits.label","عدد الأرقام الطرفية"},
{"eMP.NotPatent.label","ليس واضح"},
{"eMP.NumberingControl.label","التحكم في الترقيم"},
{"eMP.occupation.label","الوظيفة"},
{"eMP.OccupationClass.label","فئة الوظيفة"},
{"eMP.OccupationClassCode.label","كود فئة الوظيفة"},
{"eMP.OccupationClassDesc.label","وصف فئة الوظيفة"},
{"eMP.OccupationCode.label","كود الوظيفة"},
{"eMP.OccupationDesc.label","وصف الوظيفة"},
{"eMP.OccupationEmployer.label","صاحب العمل"},
{"eMP.OccupationofthePerson.label","وظيفة الشخص"},
{"eMP.OldFileNo.label","رقم الملف القديم"},
{"eMP.OldReferrals.label","الإحالات القديمة"},
{"eMP.oldvalues.label","القيم القديمة"},
{"eMP.OPVisitRegistration.label","تسجيل الزيارة الخارجية"},
{"eMP.OrderableProcedure.label","أمر / إجراء"},
{"eMP.Ordernumber.label","رقم الأمر"},
{"eMP.OrganizationID.label","معرف المنظمة"},
{"eMP.organizationmember.label","عضو منظمة"},
{"eMP.OrganizationMembership.label","عضوية المنظمة"},
{"eMP.OrganizationSubUnit.label","الوحدة الفرعية للمنظمة"},
{"eMP.OtherAltNo.label","رقم بديل آخر"},
{"eMP.OtherDocAttached.label","وثيقة أخرى مرفقة"},
{"eMP.othermodes.label","أوضاع أخرى"},
{"eMP.OtherModesofTpt.label","وسائط النقل الأخرى"},
{"eMP.OtherName.label","اسم آخر"},
{"eMP.OtherNamOtherLang.label","اسم آخر بلغة أخرى"},
{"eMP.parentdetails.label","تفاصيل الوالدين"},
{"eMP.Parity.label","التكافؤ"},
{"eMP.PartTimeEmployed.label","توظيف بدوام جزئي"},
{"eMP.PartTimeStudent.label","طالب بدوام جزئي"},
{"eMP.PatCatbyOrg.Membership.label","فئة المريض حسب عضوية المنظمة"},
{"eMP.PatencyofAnus.label","Patency of Anus"},
{"eMP.Patent.label","Patent"},
{"eMP.PatientCardTitle.label","عنوان بطاقة المريض"},
{"eMP.PatientCategoryCode.label","رمز فئة المريض"},
{"eMP.PatientCategoryDesc.label","وصف فئة المريض"},
{"eMP.PatientCategoryType.label","نوع فئة المريض"},
{"eMP.PatientDateofBirth.label","تاريخ ميلاد المريض"},
{"eMP.PatientIDFrom.label","رقم المريض من"},
{"eMP.PatientIDLength.label","طول رقم المريض"},
{"eMP.PatientMaster.label","فهرس المرضى"},
{"eMP.PatientNameDerivationLogic.label","منطق اشتقاق اسم المريض"},
{"eMP.PatientNameinLocLang.Required.label","مطلوب اسم المريض باللغة المحلية"},
{"eMP.PatientNumbering.label","ترقيم المريض"},
{"eMP.PatientRegistrationTitle.label","تسجيل المريض"},
{"eMP.PatientSearchResultFormat.label","تنسيق نتيجة بحث المريض"},
{"eMP.PatientSerieDesc.label","وصف تسلسل المريض"},
{"eMP.PatientSeries.label","تسلسل المريض"},
{"eMP.PatientSeriesCode.label","كود تسلسل المريض"},
{"eMP.PatientSeriesSameAsMotherSeries.label","تسلسل المرضى نفس تسلسل الأم"},
{"eMP.PatientSex.label","نوع المريض"},
{"eMP.PatientSuspension.label","تعليق المريض"},
{"eMP.Pensioner.label","المتقاعد"},
{"eMP.Periodbetweentwodeliveries.label","الفترة بين الولادتين"},
{"eMP.personaldetails.label","تفاصيل شخصية"},
{"eMP.PersonUnderPoliceCustody.label","محبوس لدى الشرطة"},
{"eMP.photo.label","صورة فوتوغرافية"},
{"eMP.PlaceOfIssue.label","مكان الإصدار"},
{"eMP.PopulateFrom.label","يسكن من"},
{"eMP.Postal.label","بريدي"},
{"eMP.postalcode.label","رمز بريدي"},
{"eMP.PostalDesc.label","الوصف البريدي"},
{"eMP.PrefFacility.label","المنشأة الصحية المفضلة"},
{"eMP.prefix.label","بادئة"},
{"eMP.PrefixRequired.label","البادئة مطلوبة"},
{"eMP.PrefixSex.label","جنس البادئة"},
{"eMP.primaryresidenceno.label","رقم السكن الأساسي"},
{"eMP.Prisoners.label","سجناء"},
{"eMP.ProcedureClassification.label","تصنيف الإجراء"},
{"eMP.ProcedureClassificationCode.label","كود تصنيف الإجراءات"},
{"eMP.ProcedureClassificationDesc.label","وصف تصنيف الإجراء"},
{"eMP.PromptforoldMRN.label","موجه للحصول على رقم السجل الطبي القديم"},
{"eMP.PurgeAudit.label","تدقيق الإزالة"},
{"eMP.PurgeChangesupto.label","إزالة التغييرات حتى"},
{"eMP.PurgeDate.label","تاريخ الإزالة"},
{"eMP.PurgedDateFrom.label","تاريخ إزالة من"},
{"eMP.PurgedDateTo.label","تمت إزالة التاريخ إلى"},
{"eMP.PurgedUntil.label","إزالة حتى"},
{"eMP.RaceCode.label","كود السلالة"},
{"eMP.RaceCodes.label","كود السلالة"},
{"eMP.RaceDesc.label","وصف السلالة"},
{"eMP.RaceGroup.label","مجموعة السلالة"},
{"eMP.RangeValues.label","قيم النطاق"},
{"eMP.rapidregn.label","التسجيل السريع"},
{"eMP.RdAppts.label","مواعيد RD"},
{"eMP.ReasonforActive.label","سبب نشط"},
{"eMP.ReasonforActiveInactive.label","سبب نشط / غير نشط"},
{"eMP.ReasonforSuspension.label","سبب الإيقاف"},
{"eMP.RecordPatientDeath.label","سجل وفاة المريض"},
{"eMP.RecordRevokePatientDeath.label","تسجيل / إلغاء وفاة المريض"},
{"eMP.Reference.label","المرجعي"},
{"eMP.ReferralLetterNo.label","خطاب الإحالة رقم"},
{"eMP.ReferralNotes.label","ملاحظات الإحالة"},
{"eMP.ReferredForIP.label","تمت الإحالة للمرضى الداخليين"},
{"eMP.region.label","منطقة"},
{"eMP.Regioncode.label","رمز المنطقة"},
{"eMP.RegionDesc.label","وصف المنطقة"},
{"eMP.RegisteredDisabled.label","Registered Disabled"},
{"eMP.RegisterPatient.label","تسجيل المريض"},
{"eMP.RegisterPatientReferral.label","تسجيل إحالة المريض"},
{"eMP.RegisterReferraldetails.label","تسجيل تفاصيل الإحالة"},
{"eMP.RegistrationOutput.label","مخرجات التسجيل"},
{"eMP.RegistrationSource.label","مصدر التسجيل"},
{"eMP.RegnDateFrom.label","تاريخ التسجيل من"},
{"eMP.RegnDateTo.label","تاريخ التسجيل ل"},
{"eMP.RegNewBorn.label","تسجيل مولود جديد"},
{"eMP.regnfacility.label","منشأة التسجيل"},
{"eMP.RegnMonthFrom.label","شهر التسجيل من"},
{"eMP.RegnMonthTo.label","شهر التسجيل ل"},
{"eMP.RegnType.label","نوع التسجيل"},
{"eMP.regntypeno.label","نوع / رقم التسجيل"},
{"eMP.RegnYearFrom.label","سنة التسجيل من"},
{"eMP.RegnYearTo.label","سنة التسجيل ل"},
{"eMP.reinstatementremarks.label","ملاحظات العودة"},
{"eMP.relatedcontacts.label","جهات الاتصال ذات الصلة"},
{"eMP.relatedmemberfamily.label","عضو ذو صلة - عائلة"},
{"eMP.relatedmembernonfamily.label","عضو ذو صلة - غير عائلي"},
{"eMP.RelationshipCode.label","كود العلاقة"},
{"eMP.RelationshipDesc.label","وصف العلاقة"},
{"eMP.RelationshipforOrganizationMember.label","العلاقة لعضو المنظمة"},
{"eMP.RelationshiptoHeadofFamily.label","العلاقة برب الأسرة"},
{"eMP.relationshipwithpatient.label","العلاقة مع المريض"},
{"eMP.relative.label","نسبي"},
{"eMP.ReligionDesc.label","وصف الديانة"},
{"eMP.remarksonrevoking.label","ملاحظات على الإلغاء"},
{"eMP.repository.label","مخزن"},
{"eMP.RequiredforAllSeries.label","مطلوب لجميع التسلسل"},
{"eMP.residenceaddress.label","عنوان السكن"},
{"eMP.ResidenceArea.label","منطقة الإقامة"},
{"eMP.ResidenceTown.label","مدينة الإقامة"},
{"eMP.Resident.label","مقيم"},
{"eMP.ResidentialArea.label","منطقة سكنية"},
{"eMP.ResidentialTown.label","مدينة سكنية"},
{"eMP.ReviewMotherbabylinkbeforeRegn.label","مراجعة رابط الأم والطفل قبل التسجيل"},
{"eMP.RevokePatientDeath.label","إبطال وفاة المريض"},
{"eMP.RoutineName.label","الاسم الروتيني"},
{"eMP.searchfamilyname.label","ابحث عن اسم العائلة"},
{"eMP.searchothername.label","ابحث عن اسم آخر"},
{"eMP.Second.label","ثانية"},
{"eMP.SectionType.label","نوع القسم"},
{"eMP.SelectSeries.label","حدد التسلسل"},
{"eMP.SelfEmployed.label","العاملون لحسابهم الخاص"},
{"eMP.Semigovernment.label","شبه حكومية"},
{"eMP.SerialNumberNext.label","الرقم التسلسلي التالي"},
{"eMP.SerialNumberStart.label","بدء الرقم التسلسلي"},
{"eMP.SeriesType.label","نوع التسلسل"},
{"eMP.SiteFacility.label","الموقع / المنشأة"},
{"eMP.SiteFacilityID.label","معرف الموقع / المنشأة"},
{"eMP.SiteFacilityName.label","اسم الموقع / المرفق"},
{"eMP.SmallChildren.label","أطفال صغار"},
{"eMP.SpecialCharacters.label","الرموز الخاصة"},
{"eMP.SpecialityDesc.label","وصف التخصص"},
{"eMP.SpouseDependent.label","الزوج العائل"},
{"eMP.spouseonly.label","الزوج فقط"},
{"eMP.Sr.Resident.label","مقيم أول"},
{"eMP.StandardFamilyName.label","اسم العائلة القياسي"},
{"eMP.StandardOtherName.label","الاسم القياسي الآخر"},
{"eMP.StateCode.label","رمز الولاية"},
{"eMP.StateCodeFrom.label","رمز الولاية من"},
{"eMP.StillBorn.option.label","لا يزال مولودًا"},
{"eMP.Stools.label","تغوط"},
{"eMP.Student.label","طالب علم"},
{"eMP.Stump.label","Stump"},
{"eMP.Stumps.label","Stumps"},
{"eMP.suborgn.label","منظمة فرعية"},
{"eMP.SubsequentRegnofMultipleBirthWithin.label","تسجيل الولادة المتعددة خلال"},
{"eMP.SubUnit.label","الوحدة الفرعية"},
{"eMP.SubUnitDetails.label","تفاصيل الوحدة الفرعية"},
{"eMP.SubUnitID.label","معرف الوحدة الفرعية"},
{"eMP.Suffix.label","لاحقة"},
{"eMP.SummarizationRange.label","نطاق التلخيص"},
{"eMP.Suspendedonly.label","معلق فقط"},
{"eMP.SuspendingofService.label","تعليق الخدمة"},
{"eMP.SuspendingServicetoPatient.label","تعليق الخدمة للمريض"},
{"eMP.SuspendReinstatePatient.label","تعليق / إعادة المريض"},
{"eMP.suspensionremarks.label","ملاحظات التعليق"},
{"eMP.suspstatusremarks.label","حالة التعليق / الملاحظات"},
{"eMP.telephoneres.label","الإقامة الهاتفية"},
{"eMP.telephoneoff.label","مكتب الهاتف"},
{"eMP.TerminalDigitBy.label","رقم نهائي بواسطة"},
{"eMP.TerminalDigitCount.label","عدد الأرقام النهائية"},
{"eMP.TerminalDigitDerivationLogic.label","منطق اشتقاق الرقم الطرفي"},
{"eMP.TerminalDigitLevel.label","مستوى الرقم النهائي"},
{"eMP.TerminalDigitsPosition.label","موقف الأرقام النهائية"},
{"eMP.Third.label","ثالث"},
{"eMP.ThirdName.label","الاسم الثالث"},
{"eMP.TotalSelection.label","إجمالي التحديد"},
{"eMP.TownCodeFrom.label","كود المدينة من"},
{"eMP.TownDesc.label","وصف المدينة"},
{"eMP.UmbCordCutBy.label","قطع الحبل السري"},
{"eMP.UmbilicalCord.label","حبل سري"},
{"eMP.Unemployed.label","عاطلين عن العمل"},
{"eMP.UnmarriedIndicator.label","مؤشر غير المتزوجين"},
{"eMP.UnrestrictedSeries.label","تسلسل غير مقيد"},
{"eMP.UsedStatus.label","الحالة المستخدمة"},
{"eMP.vaccinationdetails.label","تفاصيل التطعيم"},
{"eMP.VaccSite.label","موقع التطعيم"},
{"eMP.VaginalDeliveryType.label","نوع الولادة الطبيعية"},
{"eMP.VaginalDeliveryTypeCode.label","كود نوع الولادة الطبيعية"},
{"eMP.VaginalDeliveryTypeDesc.label","وصف نوع الولادة الطبيعية"},
{"eMP.ValidforHeadPatientID.label","صالح لمعرف رئيس المريض"},
{"eMP.viewbirthregdtls.label","عرض تفاصيل سجل الميلاد"},
{"eMP.ViewMotherBabyLink.label","عرض رابط الطفل/ الأم"},
{"eMP.ViewPatientDetails.label","عرض تفاصيل المريض"},
{"eMP.ViewPatientPhoto.label","عرض صورة المريض"},
{"eMP.VitaminK.label","فيتامين ك"},
{"eMP.WalkUp.label","السير نحو"},
{"eMP.WeightRange.label","نطاق الوزن"},
{"eMP.WelcometoeHIS.label","مرحبًا بك في eHIS"},
{"eMP.WithAlternateID.label","مع معرف بديل"},
{"eMP.WithNationalID.label","مع الرقم القومي"},
{"eMP.YellowSoft.label","صفراء"},
{"eMP.LinkRelatedFamilyMembers.label","ربط أفراد العائلة ذوي الصلة"},
{"eMP.RegistrationMode.label","وضع التسجيل"},
{"eMP.Rapid.label","سريعون"},
{"eMP.DefaultPatientNameInEnglish.label","اسم المريض الافتراضي باللغة الإنجليزية"},
{"eMP.DoctorAdministratorSignature.label","توقيع الطبيب / المسؤول"},
{"eMP.SearchNameWithLocalLang.label","البحث عن الاسم مع اللغة المحلية"},
{"eMP.PatientNameInLocalLang.label","اسم المريض باللغة المحلية"},
{"eMP.PersonProvideTreatmentBeforeDeath.label","يقدم الشخص العلاج قبل الموت"},
{"eMP.StartDurationOfDiseaseUntilDeath.label","تبدأ مدة المرض حتى الموت"},
{"eMP.PleaseWriteTheReasonOfDeath.label","الرجاء كتابة سبب الوفاة"},
{"eMP.InCaseDeathPersonIsFemale.label","في حالة وفاة أنثى"},
{"eMP.NotPregnant.label","ليست حاملا"},
{"eMP.PregnantNotMoreThan6Weeks.label","حامل ليس أكثر من 6 أسابيع"},
{"eMP.DurationInStayingAtDeath.label","المدة في البقاء عند الموت"},
{"eMP.ParentOfDeathPerson.label","والد الشخص المتوفى"},
{"eMP.SupportPersonOfDeath.label","دعم شخص الموت"},
{"eMP.HealthDepartmentPersonal.label","قسم الصحة الشخصية"},
{"eMP.LocationOfBirth.label","مكان الميلاد"},
{"eMP.ChildDetails.label","تفاصيل الطفل"},
{"eMP.TotalNoOfChildren.label","إجمالي عدد الأطفال"},
{"eMP.DeathAtBirth.label","الموت عند الولادة"},
{"eMP.DeathDuringPregnant.label","الموت أثناء الحمل"},
{"eMP.PersonDelivered.label","ولادة الطفل"},
{"eMP.SingleBirth.label","ولادة واحدة"},
{"eMP.DurationOfPregnancy.label","مدة الحمل"},
{"eMP.InjureFromPregnancy.label","إصابة من الحمل"},
{"eMP.DeformSinceBirth.label","تشوه منذ الولادة"},
{"eMP.SicknessFromPregnancy.label","المرض من الحمل"},
{"eMP.SicknessFromDelivery.label","المرض من الولادة"},
{"eMP.SicknessOutOfDelivery.label","المرض خارج الولادة"},
{"eMP.SpecialDelivery.label","ولادة خاصة"},
{"eMP.Province.label","مقاطعة"},
{"eMP.ControlNo.label","رقم التحكم"},
{"eMP.CertificateIssue.label","إصدار الشهادة"},
{"eMP.ReportInBehalfOfParent.label","تقرير بالنيابة عن الوالدين"},
{"eMP.HouseOwnerReportInBehalfOfParent.label","تقرير صاحب المنزل بالنيابة عن الوالدين"},
{"eMP.AlternateIDDesc.label","وصف المعرف البديل"},
{"eMP.Activated.label","مفعل"},
{"eMP.InActivated.label","معطل"},
{"eMP.ChangedAt.label","تم التغيير في"},
{"eMP.TransactionName.label","اسم المعاملة"},
{"eMP.ChangedOn.label","تم التغيير"},
{"eMP.PatientNameLocal.label","اسم المريض اللغة المحلية"},
{"eMP.Dlainterfacesearch.label","بحث واجهة DLA"},
{"eMP.surname.label","لقب"},
{"eMP.usercredentials.label","صلاحيات المستخدم"},
{"eMP.searchresult.label","نتيجة البحث"},
{"eMP.getimage.label","احصل على الصورة"},
{"eMP.CurrentAddress.label","العنوان الحالي"},
{"eMP.PermanentAddress.label","العنوان الدائم"},
{"eMP.NOKAddress.label","عنوان NOK"},
{"eMP.SpouseName.label","اسم الزوج"},
{"eMP.NearByPlace.label","المكان القريب"},
{"eMP.CongenitalDisease.label","مرض خلقي"},
{"eMP.DrugAndOtherDisease.label","المخدرات والأمراض الأخرى"},
{"eMP.HospitalInformation.label","معلومات المستشفى"},
{"eMP.ToBeFilledByHospitalStaff.label","يتم ملؤها من قبل طاقم المستشفى"},
{"eMP.SocialWelfareInformation.label","معلومات الرعاية الاجتماعية"},
{"eMP.ChangeAllowed.label","تغيير مسموح به"},
{"eMP.EstimatedBirthDate.label","تاريخ الميلاد المقدر"},
{"eMP.EnterPassword.label","أدخل كلمة المرور"},
{"eMP.AcceptPasswordinChangePatientDtls.label","قبول كلمة المرور عند تغيير تفاصيل المريض"},
{"eMP.ContactPerson.label","الشخص الذي يمكن الاتصال به"},
{"eMP.FatherMotherName.label","اسم الأب / الأم"},
{"eMP.CurrentPatientClass.label","فئة المريض الحالية"},
{"eMP.InvokePatientSearchinRegisterPatient.label","قم باستدعاء بحث المريض في تسجيل المريض"},
{"eMP.GeneratePatientIDusingAlternateID1Rule.label","استخدم قاعدة المعرف البديل 1"},
{"eMP.RelationshipLevel.label","مستوى العلاقة"},
{"eMP.RelationshipLevelCode.label","رمز مستوى العلاقة"},
{"eMP.RelationshipLevelDesc.label","وصف مستوى العلاقة"},
{"eMP.LinkedRelnshpLevel.label","مستوى العلاقة المرتبطة"},
{"eMP.LinkedRelnshp.label","علاقة مرتبطة"},
{"eMP.RelationShipLevInd.label","مؤشر مستوى العلاقة"},
{"eMP.HeadofFamilyPatientName.label","اسم المريض رب الأسرة"},
{"eMP.PatientNumberingForRelation.label","ترقيم المريض للعلاقة"},
{"eMP.SeparatorValue.label","قيمة الفاصل"},
{"eMP.SeparatorPosition.label","موقع الفاصل"},
{"eMP.PatientIDGenerationRule.label","قاعدة إنشاء معرف المريض"},
{"eMP.ReqdforOrgnMember.label","مطلوب لعضو منظمة"},
{"eMP.AltID1RuleAppl.label","تنطبق قاعدة المعرف 1 البديل"},
{"eMP.Ambigious.label","غامض"},
{"eMP.RelLevelLength.label","طول مستوى العلاقة"},
{"eMP.AltID1RuleforPatNo.label","قاعدة المعرف 1 البديلة لترقيم المريض"},
{"eMP.PatNumberingUsing.label","ترقيم المريض باستخدام"},
{"eMP.SystemGenerated.label","انشاء من النظام"},
{"eMP.GestationPeriod.label","فترة الحمل"},
{"eMP.Dusk.label","الغسق"},
{"eMP.Waning.label","يتضاءل"},
{"eMP.Compnotreltopreg.label","مضاعفات غير متعلقة بالحمل"},
{"eMP.Mothersillness.label","مرض الأم"},
{"eMP.Certificateofficer.label","ضابط الشهادات"},
{"eMP.Birth.label","ولادة"},
{"eMP.Host.label","مضيف"},
{"eMP.Representative.label","وكيل"},
{"eMP.Rep.label","اعادة / عد"},
{"eMP.RaceReqdDuringRegn.label","السلالة مطلوب أثناء التسجيل"},
{"eMP.BannerType.label","نوع الشعار"},
{"eMP.PatientContextBanner.label","شعار سياق المريض"},
{"eMP.EncounterContextBanner.label","شعار زيارة المريض"},
{"eMP.ViewDefaultBanner.label","عرض الشعار الافتراضي"},
{"eMP.PreviewBanner.label","معاينة الشعار"},
{"eMP.ActualLength.label","الطول الفعلي"},
{"eMP.DisplayLenght.label","طول العرض"},
{"eMP.SpaceBeforeText.label","عدد المسافات قبل النص"},
{"eMP.DisplayText.label","عرض النص"},
{"eMP.ToolTipText.label","نص تلميح الأداة"},
{"eMP.PatEncBanner.label","شعار سياق المريض / اللقاء"},
{"eMP.MPAccessRights.label","حقوق الوصول MP"},
{"eMP.NewbornID.label","هوية الوليد"},
{"eMP.PatientInformation.label","معلومات المريض"},
{"eMP.Tumbon.label","Tumbon"},
{"eMP.ViewPatFinlDtls.label","عرض التفاصيل المالية للمريض"},
{"eMP.EmailNotification.label","إشعار البريد الإلكتروني لحجز العيادات مطبق"},
{"eMP.Father.label","أب"},
{"eMP.CitizenId.label","هوية المواطن"},
{"eMP.ICertfiedAllInfo.label","لقد صدقت على جميع المعلومات وصور"},
{"eMP.TrueAndValid.label","صحيحة وصالحة"},
{"eMP.DLAUserID.label","معرف مستخدم DLA"},
{"eMP.PrematureCutOffPeriod.label","الفترة الفاصلة للولادات قبل النضج"},
{"eMP.UM_PatientSeries.label","تسلسل المتبرعين"},
{"eMP.UM_PatientNumbering.label","ترقيم المتبرعين"},
{"eMP.UM_PatientIDGenerationRule.label","قاعدة إنشاء معرف المتبرعين"},
{"eMP.UM_GeneratePatientID.label","إنشاء هوية المتبرع"},
{"eMP.UM_AltID1RuleforPatNo.label","قاعدة المعرف 1 البديلة لترقيم المتبرعين"},
{"eMP.UM_PatNumberingUsing.label","ترقيم المتبرعين باستخدام"},
{"eMP.UM_ValidforHeadPatientID.label","صالح لمعرف المتبرع الرئيسي"},
{"eMP.UM_PatientNameinLocLang.Required.label","مطلوب اسم المتبرع في اللغة المحلية"},
{"eMP.UM_PatientSeriesCode.label","كود سلسلة المتبرعين"},
{"eMP.UM_PatientSerieDesc.label","وصف سلسلة المتبرعين"},
{"eMP.UM_PatientIDLength.label","طول هوية المتبرع"},
{"eMP.UM_PatientRegistrationTitle.label","تسجيل المتبرعين"},
{"eMP.UM_AcceptPatientNameinLocalLanguage.label","قبول اسم المتبرع باللغة المحلية"},
{"eMP.UM_AcceptPatientNameasMultiparts.label","قبول اسم المتبرع كأجزاء متعددة"},
{"eMP.UM_DefaultPatientNameInEnglish.label","اسم المتبرع الافتراضي باللغة الإنجليزية"},
{"eMP.UM_AcceptforOtherPatientSeries.label","قبول لسلسلة المتبرعين الأخرى"},
{"eMP.UM_PatientSeriesSameAsMotherSeries.label","سلسلة المانحين نفس سلسلة الأم"},
{"eMP.UM_MaxPatientAge.label","الحد الأقصى لعمر المتبرعين"},
{"eMP.UM_ApplyEligibilityRulesbyPatientCategory.label","تطبيق قواعد الأهلية حسب فئة المتبرع"},
{"eMP.UM_AcceptApptRefNoReferralIDinRegisterPatient.label","قبول الرقم المرجعي للموعد / معرف الإحالة في سجل المتبرع"},
{"eMP.UM_InvokePatientSearchinRegisterPatient.label","استدعاء البحث عن المانحين في تسجيل المتبرع"},
{"eMP.UM_SuspendingServicetoPatient.label","تعليق الخدمة للجهة المانحة"},
{"eMP.UM_AcceptPasswordinChangePatientDtls.label","قبول كلمة المرور في تغيير تفاصيل المتبرع"},
{"eMP.UM_GenerateSl.No.forUnknownPatients.label","إنشاء الرقم التسلسلي للمتبرعين غير المعروفين"},
{"eMP.UM_MPParameter.label","معلمة المتبرع"},
{"eMP.AssociatedNoSeries.label","سلسلة الترقيم المرتبطة"},
{"eMP.SinglePatientNoAppl.label","ينطبق ترقيم مريض واحد"},
{"eMP.SelfDeputy.label","ذاتي / نائب"},
{"eMP.DispNBAgeInHrIfAgeLT.label","عرض عمر حديثي الولادة بالساعات عندما يكون العمر أقل من أو يساوي"},
{"eMP.ReqStatDesc.label","وصف حالة الطلب:"},
{"eMP.KinTelNo.label","رقم هاتف القريب"},
{"eMP.UpdatedFacility.label","منشأة محدثة"},
{"eMP.PersonInactivated.label","تم تعطيل الشخص"},
{"eMP.DateOfInactivation.label","تاريخ التعطيل"},
{"eMP.ReasonForInactivation.label","سبب التعطيل"},
{"eMP.DeceasedStatus.label","حالة المتوفى"},
{"eMP.maritalstatus_fs.label","الحالة الإجتماعية"},
{"eMP.residenceaddress_fs.label","عنوان السكن"},
{"eMP.NonNationality.label","عدم الجنسية"},
{"eMP.Registrationcard.label","بطاقة التسجيل"},
{"eMP.Persontonotifyincaseofemergency.label","شخص للتواصل في الحالات الطارئة"},
{"eMP.knownallergyIfany.label","الحساسية المعروفة"},
{"eMP.AddressofCorrespondence.label","عنوان المراسلات"},
{"eMP.Preferredmodeofcomm.label","طريقة الاتصال المفضلة"},
{"eMP.ModeofPayment.label","طريقة الدفع"},
{"eMP.Relationshipifany.label","علاقة"},
{"eMP.BloodGroupRh.label","فصيلة الدم / العامل الريصي"},
{"eMP.Pincode.label","الرقم السري"},
{"eMP.Patientbroughtby.label","جلب المريض من قبل"},
{"eMP.PhoneNo.label","رقم الهاتف"},
{"eMP.PassportNo.label","رقم جواز السفر"},
{"eMP.SonDaughterWifeof.label","ابن / ابنة / زوجة"},
{"eMP.MiddleName.label","الاسم الأوسط"},
{"eMP.ForIndividuals.label","للأفراد من أصل أجنبي "},
{"eMP.Tobefilled.label","يتم ملؤها بالأحرف الكبيرة"},
{"eMP.mpbfrnst.label","أقر بموجبه أن المعلومات المقدمة دقيقة على حد علمي"},
{"eMP.mpbfrnstams.label","أوافق على الخضوع لفحص التشخيص الطبي"},
{"eMP.mpbfrnstamsreport.label","أمنح بهذا موافقتي على العلاج إلى معهد أرتميس الصحي وأوافق وأتعهد بتسوية الفواتير بالكامل ونهائيًا مع معهد أرتميس الصحي قبل الخروج من المستشفى."},
{"eMP.mpbfrnstamsreporttext4.label","أفوض بموجب هذا معهد أرتميس الصحي بالاحتفاظ بالنماذج الموقعة رقمياً / قسائم التفريغ / التقارير / السجلات الطبية وما إلى ذلك الصادرة عن معهد أرتميس الصحي في نسخة إلكترونية للرجوع إليها والتسجيل في المستقبل."},
{"eMP.mpbfrnstamsreporttext5.label","لقد قرأت الشروط والأحكام المذكورة أعلاه وأتفهم وأوافق على قبول المسؤولية كما هو موضح هنا."},
{"eMP.ExternalSourceDetails.label","تفاصيل المصدر الخارجي"},
{"eMP.PatientListforAltIdNo1.label","قائمة المرضى لـ $"},
{"eMP.Complicationsin1stStage.label","المضاعفات في المرحلة الأولى من الولادة"},
{"eMP.Complicationsin2ndStage.label","المضاعفات في المرحلة الثانية من الولادة"},
{"eMP.Complicationsin3rdStage.label","المضاعفات في المرحلة الثالثة من الولادة"},
{"eMP.DeliveryIndicator.label","مؤشر الولادة"},
{"eMP.CSection.label","ولاده قيصريه"},
{"eMP.RelatedtoPregnancy.label","المتعلقة بالحمل"},
{"eMP.ComplicationsofPregnancy.label","مضاعفات الحمل"},
{"eMP.ComplicationsofPregnancyCode.label","كود مضاعفات الحمل"},
{"eMP.ComplicationsofPregnancyDesc.label","وصف مضاعفات الحمل"},
{"eMP.SingleStageNewBornRegnAppl.label","يمكن تسجيل المواليد الجدد بمرحلة واحدة"},
{"eMP.FirstStageRegistrationRecords.label","سجلات تسجيل المرحلة الأولى"},
{"eMP.FinalizedRecords.label","السجلات المكتملة"},
{"eMP.FamilyStatus.label","الوضع العائلي"},
{"eMP.BirthCertificateOfficer.label","ضابط شهادة الميلاد"},
{"eMP.ComplicationsnotrelatedtoPregnancy.label","المضاعفات غير المتعلقة بالحمل"},
{"eMP.Mothersillness.label","مرض الأم"},
{"eMP.BirthInjury.label","إصابة الولادة"},
{"eMP.Waxing.label","أزالة الشعر الزائد"},
{"eMP.Moon.label","القمر"},
{"eMP.PlaceofIssuingCertificate.label","مكان اصدار الشهادة"},
{"eMP.HospitalName.label","اسم المستشفى"},
{"eMP.BirthLevel.label","مستوى الولادة"},
{"eMP.Day_bc.label","يوم"},
{"eMP.Address_bc.label","عنوان"},
{"eMP.PractitionerType_bc.label","نوع الممارس"},
{"eMP.Practitioner_bc.label","ممارس المهنة"},
{"eMP.Year_bc.label","سنة"},
{"eMP.Name_bc.label","اسم"},
{"eMP.Child_bc.label","طفل"},
{"eMP.Address1_bc.label","عنوان"},
{"eMP.CongenitalAnomalies_bc.label","التشوهات الخلقية"},
{"eMP.BirthWeight_bc.label","الوزن عند الولادة____"},
{"eMP.Gestation_bc.label","الحمل"},
{"eMP.BirthOrder_bc.label","ترتيب الولادة"},
{"eMP.MultipleBirth_bc.label","تعدد المواليد"},
{"eMP.NewBorn_bc.label","مولود جديد"},
{"eMP.No_bc.label","رقم"},
{"eMP.ComplicationsofDelivery.label","مضاعفات الولادة"},
{"eMP.PlaceofBirth_th.label","مكان الميلاد"},
{"eMP.Estimated.label","(EBD)"},
{"eMP.ComplicationsRelatedPregnancy.label","المضاعفات المتعلقة بالحمل"},
{"eMP.ComplicationsNotRelatedPregnancy.label","المضاعفات التي لا تتعلق بالحمل"},
{"eMP.NewBornFatherNameMandatory.label","اسم الأب إلزامي للطفل المولود حديثًا "},
{"eMP.ChngofDataAlwdAfrFinalization.label","يسمح بتغيير البيانات بعد الصياغة النهائية"},
{"eMP.DfltRaceNationalitySetupofNB.label","الإعداد الافتراضي للعرق والجنسية لحديثي الولادة حسب"},
{"eMP.AcceptNamesforLiveBirth.label","مكونات الاسم الافتراضي للولادة "},
{"eMP.NameoftheCertperson.label","الاسم الكامل للشخص المعتمد"},
{"eMP.LicenseNo.label","رقم الرخصة"},
{"eMP.AttendantAtBirth.label","حاضرة عند الولادة"},
{"eMP.MaternalcondAffectFetus.label","حالة الأم تؤثر على الجنين"},
{"eMP.DurationofDisease.label","مدة المرض"},
{"eMP.Preexistent.label","موجود مسبقا"},
{"eMP.OthRelatMaternalCondiAffectFetus.label","حالة الأمومة الأخرى ذات الصلة التي تؤثر على الجنين"},
{"eMP.RelatedcauseofDeath.label","سبب متعلق بالوفاة"},
{"eMP.CondiCausDeathinFetus.label","حالة تسبب الموت في الجنين"},
{"eMP.RelCondiCausDeathinFetus.label","حالة ذات صلة تسبب الموت في الجنين"},
{"eMP.AutopsyRequried.label","مطلوب تشريح الجثة"},
{"eMP.Accoucheuse.label","اتهام"},
{"eMP.TraditionalMedicine.label","الطب التقليدي"},
{"eMP.MidwifeAssistance.label","مساعدة قابلة"},
{"eMP.Physician.label","الطبيب المعالج"},
{"eMP.TypeofComplication.label","نوع المضاعفات"},
{"eMP.Foetus.label","الجنين"},
{"eMP.NameOfHospitalIssuedTheDeathCertification.label","اسم المستشفى الصادر شهادة الوفاة."},
{"eMP.Tambon.label","Tambon"},
{"eMP.Amphur.label","Amphur"},
{"eMP.TreatedPhysicianBeforeDecease.label","الطبيب المعالج قبل الوفاة"},
{"eMP.DiagnosisCauseOfDeath.label","تشخيص سبب الوفاة"},
{"eMP.CapitalLetters.label","الحروف الكبيرة"},
{"eMP.TheDurationFromTheIllnessStartToDecease.label","المدة من بداية المرض إلى الوفاة"},
{"eMP.OtherDiseaseOrComplicationsThatSupportTheCauseOfDeath.label","مرض أو مضاعفات أخرى تدعم سبب الوفاة."},
{"eMP.IfTheDiseasedPersonIsFemale.label","إذا كان المريض أنثى."},
{"eMP.DeceasedLocation.label","موقع المتوفى"},
{"eMP.NameOfDeceaseLocation.label","اسم مكان الوفاة"},
{"eMP.ParentOfDeceasePerson.label","والد المتوفى"},
{"eMP.PersonCertifiedTheDecease.label","شخص مصدق على الوفاة"},
{"eMP.Profession.label","مهنة"},
{"eMP.MPDTHCER_REPORT_TEXT1.label","تم تصنيف سبب الوفاة في هذه الوثيقة حسب تصنيف المرض الدولي. والغرض من ذلك هو جمع بيانات DLC وإحصاءات وفيات المقاطعات وتخطيط الوقاية من الصحة العامة فقط. لذلك قد يكون سبب الوفاة المحدد في هذا المستند مختلفًا عن مستند قانوني آخر مثل تقرير التشريح."},
{"eMP.MPDTHCER_REPORT_TEXT2.label","أنا بموجب هذا أقر بأن المستند أعلاه صحيح"},
{"eMP.CertifiedPerson.label","شخص معتمد"},
{"eMP.PublicHealthWorker.label","عامل صحة عامة"},
{"eMP.DeceasedPersonDetail.label","تفاصيل الشخص المتوفى"},
{"eMP.DocumentRunningNumber.label","رقم تشغيل المستند"},
{"eMP.SurnameOfCertifiedPerson.label","لقب الشخص المعتمد"},
{"eMP.ThaiTraditionalMedicine.label","الطب التايلاندي التقليدي"},
{"eMP.DeceasedPatient.label","مريض متوفى"},
{"eMP.DateOfDeceased.label","تاريخ الوفاة"},
{"eMP.PlaceOfDeceased.label","مكان الوفاة"},
{"eMP.NameOfMother.label","اسم الام"},
{"eMP.SurnameOfMother.label","لقب الأم"},
{"eMP.PregnancyPeriod.label","فترة الحمل"},
{"eMP.MainCauseOfDeath.label","السبب الرئيسي للوفاة"},
{"eMP.OtherCauseOfDeath.label","سبب آخر للوفاة"},
{"eMP.OldCauseOfDeath.label","سبب قديم للوفاة"},
{"eMP.AssociatedCauseOfDeath.label","سبب الوفاة المرتبط"},
{"eMP.BodyHasToBeAutopsy.label","يجب أن يتم تشريح الجثة"},
{"eMP.AutopsyNotRequired.label","التشريح غير مطلوب"},
{"eMP.SurnameOfFather.label","لقب الأب"},
{"eMP.Heartrate.label","معدل ضربات القلب"},
{"eMP.Breathing.label","عمليه التنفس"},
{"eMP.Grimace.label","الوجه"},
{"eMP.Activity.label","نشاط"},
{"eMP.Appearance.label","مظهر"},
{"eMP.Absent.label","غائب"},
{"eMP.Below100bpm.label","أقل من 100 نبضة في الدقيقة"},
{"eMP.Above100bpm.label","فوق 100 نبضة في الدقيقة"},
{"eMP.Slowirregular.label","بطيء"},
{"eMP.GoodCrying.label","حسن"},
{"eMP.NoResponse.label","لا يوجد رد"},
{"eMP.Facialgrimace.label","كشر الوجه"},
{"eMP.Sneezecoughpullsaway.label","عطس"},
{"eMP.Armslegsextended.label","امتداد الذراعين والساقين"},
{"eMP.Activemovementwithflexedarmslegs.label","حركة نشطة مع ثني الذراعين والساقين"},
{"eMP.Blue-graypaleallover.label","ازرق - رمادي"},
{"eMP.Pinkbodyandblueextremities.label","الجسم الوردي والأزرق في الأطراف"},
{"eMP.Normaloverentirebody-completelypink.label","طبيعي على كامل الجسم - وردي بالكامل"},
{"eMP.RecStillBirthDtls.label","تسجيل تفاصيل الولادة"},
{"eMP.StillBirthDtls.label","تفاصيل الولادة"},
{"eMP.RelCondCausingDeathInFetus.label","حالة تسبب الموت في الجنين"},
{"eMP.HeartRateAtMin.label","معدل ضربات القلب عند # دقيقة"},
{"eMP.BreathingAtMin.label","التنفس في دقيقة واحدة"},
{"eMP.GrimaceAtMin.label","الوجه في # دقيقة"},
{"eMP.ActivityAtMin.label","النشاط في # دقيقة"},
{"eMP.AppearanceAtMin.label","ظهور عند # دقيقة"},
{"eMP.CauseOfDeath.label","سبب الوفاة"},
{"eMP.PregnancyPeriod1.label","فترة الحمل"},
{"eMP.Specialty.label","تخصص"},
{"eMP.FullNameofCertifiedPractitioner.label","الاسم الكامل للممارس المعتمد"},
{"eMP.Omani.label","عماني"},
{"eMP.NonOmani.label","غير عماني"},
{"eMP.N_Entitled.label","غير متاح"},
{"eMP.PlaceBabyWasBorn.label","مكان ولادة الطفل"},
{"eMP.BirthMonth.label","شهر الميلاد"},
{"eMP.BabiesBorn.label","الاطفال المولودين"},
{"eMP.LiveBirths.label","ولادة حية"},
{"eMP.StillFresh.label","ما زال طازج"},
{"eMP.StillMacer.label","لا يزال Macer"},
{"eMP.TotalStillBirth.label","إجمالي المواليد الجدد"},
{"eMP.BabiesBornAlive.label","أطفال يولدون أحياء"},
{"eMP.AgeofMothers.label","عمر الأمهات"},
{"eMP.InYears.label","في سنوات"},
{"eMP.NoofMothers.label","عدد الأمهات"},
{"eMP.ModeofDelivery.label","طريقة الولادة"},
{"eMP.WebCam.label","كاميرا ويب"},
{"eMP.ChangePatientPhoto.label","تغيير صورة المريض"},
{"eMP.PatientPhoto.label","صورة المريض"},
{"eMP.StillBirth.label","لولادة"},
{"eMP.SexNeonatalSingletonPregnancy.label","جنس حديثي الولادة للحمل المفرد"},
{"eMP.BirthWeightForSingletonPregnancy.label","الوزن عند الولادة للحمل المفرد"},
{"eMP.SexOfNeonatalForMultiFoetalPregnancy.label","جنس حديثي الولادة للحمل متعدد الأجنة"},
{"eMP.BirthWeightForMultiFoetalPregnancy.label","الوزن عند الولادة لحمل متعدد الأجنة"},
{"eMP.GestationalAgeForTwinPregnancy.label","عمر الحمل لحمل التوأم"},
{"eMP.TypeofDeliveryfortwinpregnancy.label","نوع الولادة لحمل توأم"},
{"eMP.SexOfBirthForTwinPregnancy.label","جنس الولادة للحمل التوأم"},
{"eMP.BirthWeightForTwinPregnancy.label","الوزن عند الولادة لحمل التوأم"},
{"eMP.StatusofBirthfortwinpregnancy.label","حالة الولادة لحمل التوأم"},
{"eMP.DeliveryAndFoetalOutcomeForTripletPregnancy.label","نتائج الولادة والجنين للحمل الثلاثي"},
{"eMP.Respiration.label","التنفس"},
{"eMP.Pulse.label","نبض"},
{"eMP.ConjoinedTwins.label","توأمان ملتصقان"},
{"eMP.PresentationForTwinPregnancy.label","عرض لتوأم الحمل"},
{"eMP.GestationTripletPregnancy.label","الحمل والعرض التقديمي للحمل الثلاثي"},
{"eMP.Dfltrelnshipnewborn.label","العلاقة الافتراضية لحديثي الولادة"},
{"eMP.StillBornPrefix.label","StillBorn Prefix"},
{"eMP.AlertForPatientPhotoRenewalAfter.label","تنبيه لتجديد صورة المريض بعد"},
{"eMP.AdminDateTime.label","تاريخ / وقت الدخول"},
{"eMP.RoundoffDOBEstdAge.label","تقريب تاريخ الميلاد بالنسبة للعمر المقدر"},
{"eMP.Dfltlangforonlinereport.label","اللغة الافتراضية للتقرير عبر الإنترنت"},
{"eMP.OneEye.label","المريض لديه عين واحدة"},
{"eMP.OneRightEye.label","العين اليمنى"},
{"eMP.OneLeftEye.label","العين اليسرى"},
{"eMP.AutomaticPrefixUpdateforPatientSeries.label","تحديث البادئة التلقائي لسلسلة المرضى"},
{"eMP.PatientLongNameDerivationLogic.label","منطق اشتقاق الاسم الطويل للمريض"},
{"eMP.ReportDateAndTime.label","تاريخ  و وقت التقرير"},
{"eMP.AllergyHistory.label","تاريخ الحساسية"},
{"eMP.DeceasedPatsReleasedMO.label","خذ بعين الاعتبار المرضى المتوفين الذين تم الإفراج عنهم فقط من خلال ثلاجة الموتى"},
{"eMP.NoOfDaysBeforeDeceased.label","خذ بعين الاعتبار المرضى المتوفين من قبل"},
{"eMP.AutoCancelFutDtls.label","الإلغاء التلقائي للمواعيد المستقبلية / قائمة الانتظار / الحجوزات / إحالات المرضى المتوفين"},
{"eMP.RecentNotes.label","ملاحظات حديثة"},
{"eMP.NewNote.label","ملاحظة جديدة"},
{"eMP.PurgedOn.label","إزالة على"},
{"eMP.PurgedBy.label","إزالة بواسطة"},
{"eMP.PurgedUpto.label","إزالة حتى"},
{"eMP.PurgedAtFacilityId.label","تمت الإزالة في المنشأة"},
{"eMP.PatientSearchTab.label","علامة التبويب بحث المريض"},
{"eMP.LogReferenceId.label","معرف مرجع السجل"},
{"eMP.PatDoc.label","وثيقة المريض"},
{"eMP.CapturePatientDoc.label","التقاط وثيقة المريض"},
{"eMP.QuickAdmission.label","دخول سريع"},
{"eMP.ReferraltoPractioner.label","الطبيب المحول"},
{"eMP.ReqdDuringRegn.label","الحقول الإلزامية أثناء التسجيل"},
{"eMP.Hijri.label","هجري"},
{"eMP.PatSerAccessByUser.label","وصول المستخدم إلى تسلسل المريض"},
{"eMP.OtherAlternateNo.label","رقم بديل آخر"},
{"eMP.SynContactDtlsApt.label","مزامنة تفاصيل الاتصال مع الموعد"},
{"eMP.DeliveryDate.label","تاريخ الولادة"},
{"eMP.ModifyMotherdetailsinMultipleBirth.label","تعديل تفاصيل الأم في ولادات متعددة"},
{"eMP.GravidaOnAdmission.label","الحمل عند الدخول"},
{"eMP.ParityOnAdmission.label","Parity on Admission"},
{"eMP.Alive.label","على قيد الحياة"},
{"eMP.ExactSearch.label","بحث دقيق"},
{"eMP.PatencyofAnusCheckedBy.label","تم فحص سالكية فتحة الشرج بواسطة"},
{"eMP.FormNo60.label","نموذج رقم 60"},
{"eMP.RecordReferralLetterNote.label","تسجيل مذكرة إحالة "},
{"eMP.UpdatePatientDetailsToReferrals.label","تحديث بيانات المريض للإحالات"},
{"eMP.NeonatalResuscitation.label","إنعاش حديثي الولادة"},
{"eMP.ConsentforMyHIX.label","الموافقة على MyHIX"},
{"eMP.MyHIXGlobalID.label","معرّف MyHIX العمومي"},
{"eMP.ConsentforNDHM.label","الموافقة على NDHM"},// added by lakshmanan GHL CRF 0657.1
{"eMP.ABHANumber.label","رقم ABHA"},// added by lakshmanan GHL CRF 0657.1
{"eMP.MyHIX.label","MyHIX"},
{"eMP.Resuscitated.label","إنعاش"},
{"eMP.OnAdmission.label","عند الدخول"},
{"eMP.AltFileNo.label","رقم الملف البديل"},
{"eMP.form60.label","نموذج رقم 60"},
{"eMP.Surname.label","اسم العائلة"},
{"eMP.DobInsOfDec.label","تاريخ الميلاد / التأسيس للمقر"},
{"eMP.FlatRoomNo.label","رقم الشقة / الغرفة"},
{"eMP.FloorNo.label","رقم الطابق"},
{"eMP.NameOfPremises.label","اسم المبنى"},
{"eMP.BlockNameNo.label","رقم/ اسم البلوك"},
{"eMP.RoadStreetLane.label","طريق / شارع"},
{"eMP.AreaLocality.label","المنطقة "},
{"eMP.TownCity.label","بلدة / مدينة"},
{"eMP.AmountOfTransaction.label","مبلغ المعاملة "},
{"eMP.DateOfTransaction.label","تاريخ المعاملة"},
{"eMP.NumberOfPersonInvolved.label","في حالة المعاملة بأسماء مشتركة"},
{"eMP.ModeOfTransaction.label","طريقة المعاملة"},
{"eMP.AdharNoIssuedByUIDAI.label","رقم Aadhar الصادر عن UIDAI (إن وجد)"},
{"eMP.AppliedForPAN.label","تقدم بطلب للحصول على PAN"},
{"eMP.PANAcknowledgement.label","تقدير PAN"},
{"eMP.PANDateOfApplication.label","تاريخ تطبيق PAN"},
{"eMP.EstimatedAgriculturalIncome.label","الدخل الزراعي المقدر"},
{"eMP.EstimatedNonAgriculturalIncome.label","الدخل غير الزراعي المقدر"},
{"eMP.SupportIdentifyProof.label","تفاصيل المستند الذي يتم إنتاجه لدعم إثبات الهوية"},
{"eMP.SupportOfAddress.label","تفاصيل الوثيقة التي يتم إنتاجها لدعم العنوان"},
{"eMP.DocumentIdentificationNumber.label","رقم تعريف الوثيقة"},
{"eMP.NameAndAddressOfAuthority.label","اسم وعنوان الجهة التي أصدرت الوثيقة"},
{"eMP.Cheque.label","شيك"},
{"eMP.Card.label","بطاقة"},
{"eMP.DraftORBankersCheque.label","حوالة / شيك مصرفي"},
{"eMP.OnlineTransfer.label","التحويل عبر الإنترنت"},
{"eMP.Finalize.label","اكمال"},
{"eMP.SuppDocType.label","نوع الوثيقة الداعمة"},
{"eMP.SuppDocDesc.label","وصف الوثيقة الداعمة"},
{"eMP.AddrProof.label","إثبات العنوان"},
{"eMP.IDProof.label","إثبات الهوية"},
{"eMP.MobileNo.label","رقم الهاتف المحمول"},
{"eMP.pancardrelation.label","علاقة بطاقة PAN"},
{"eMP.DeclarantDetails.label","تفاصيل المصرح"},
{"eMP.DeclarantAddDetails.label","تفاصيل عنوان المصرح"},
{"eMP.DeclarantTrasactionDetails.label","تفاصيل معاملة المصرح"},
{"eMP.ValidatePAN.label","تحقق من صحة PAN"},
{"eMP.Alternate.label","البديل"},
{"eMP.AlternateAddress.label","العنوان البديل"},
{"eMP.CopyAlternateAddress.label","نسخ العنوان البديل"},
{"eMP.OtherAltNoDetails.label","تفاصيل رقم بديل أخر"},
{"eMP.OtherAltIdDetails.label","تفاصيل معرف بديل أخرى"},
{"eMP.NewbornAssessmentNote.label","مذكرة تقييم حديثي الولادة"},
{"eMP.NOK.label","NOK"},
{"eMP.BloodDonor.label","متبرع بالدم"},
{"eMP.OperativeComplications.label","المضاعفات الجراحية"},
{"eMP.IndicationsForOperativeDelivery.label","مؤشرات الولادة"},
{"eMP.DeliverySurgClass.label","التصنيف الجراحي للولادة"},
{"eMP.UHIDValidFor.label","UHID صالح لـ"},
{"eMP.VisaType.label","نوع الفيزا"},
{"eMP.Work.label","العمل"},
{"eMP.ResidentWork.label","المقيم / العمل"},
{"eMP.AgeWiseNotConsidrNatID.label","لا يتم النظر في تعريف العمر للحصول على بطاقة الرقم القومي"},
{"eMP.RenewDate.label","تاريخ التجديد"},
{"eMP.AgeDefNotConsideredNatIDAltId.label","لا يتم اعتبار تعريف العمر بالنسبة للرقم القومي / رقم الهوية / جواز السفر"},
{"eMP.AgeDefNotConsideredNatIDIqmaID.label","لا يتم النظر في تعريف العمر بالنسبة للرقم القومي/ معرف الإقامة"},
{"eMP.AgeDefNotConsideredEmrIDMOHId.label","العمر الحكيم Def.not يجب مراعاته للهوية الإماراتية / بطاقة جواز السفر / هوية وزارة الصحة الموحدة"},
{"eMP.GenerateOTP.label","تخليق OTP"},
{"eMP.EnterOTP.label","أدخل OTP"},
{"eMP.TransferCase.label","نقل الحالة؟"},
{"eMP.HouseholdMonthlyIncome.label","الدخل الشهري للأسرة "},
{"eMP.NewbornNameDervLogic.label","منطق اشتقاق اسم المولود المتعدد"},
{"eMP.SynPatientDtlsApt.label","مزامنة تفاصيل المريض مع الموعد"},
{"eMP.NewbornNameDervLogicSB.label","منطق اشتقاق اسم المولود المفرد"},
{"eMP.BloodDonor.label","المتبرع بالدم"},
{"eMP.OtherAlternateNo.label","رقم بديل"},
{"eMP.DefaultCardReader.label","افتراضي لقارئ البطاقات"},
{"eMP.GCC.label","مجلس التعاون الخليجي"},
{"eMP.DftNationalID.label","قيمة الهوية الوطنية الافتراضية"},
{"eMP.MLC.label","MLC"}, // added by lakshmanan for ML-MMOH-CRF-1955
{"eMP.NonMLC.label","غير MLC"}, // added by lakshmanan for ML-MMOH-CRF-1955
{"eMP.telephonecode.label","رمز الهاتف"}, ////added by Himanshu Saxena for ML-MMOH-CRF-1930(U3)
{"eMP.BiometricAuthentication.label","المصادقة البيومترية"}, //added by Himanshu Saxena for AAKH-CRF-0175(U1)
{"eMP.ReasonBiometricAuthenticationfail.label","السماح بمتابعة المعاملات مع الأسباب في حالة فشل المصادقة البيومترية"},  //added by Himanshu Saxena for AAKH-CRF-0175(U1)
{"eMP.Scan.label","مسح"}, 
{"eMP.Reason.label","سبب"},
{"eMP.EnableDeathRegFormDuringCheckout.label", "تفعيل نموذج تسجيل الوفاة للمتوفى أثناء الخروج (AE/IP/OP/DY)"},
{"eMP.ScanABHA.label","مسح أبها"},
{"eMP.Unlink.label","إلغاء الارتباط"},
{"eMP.FingerAuth.label","التحقق من بصمة الإصبع"},
{"eMP.Restricted.label", " مقيد"},
{"eMP.Restrict.label", "يقيد"},
{"eMP.Reinstate.label", "إعادة"},
{"eMP.RestrictionRemark.label", "ملاحظة التقييد"},
{"eMP.ReinstatementRemark.label", "ملاحظة الإعادة"},
{"eMP.ReasonForRestriction.label", "سبب التقييد"}
};

	
}