
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from eCP.AssessmentCategoryForAssessmentNote.AssessmentCategoryForAssessmentNoteManager
package eCP.AssessmentCategoryForAssessmentNote;

/**
 * Local-Home interface for AssessmentCategoryForAssessmentNote
 */
public interface AssessmentCategoryForAssessmentNoteLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/AssessmentCategoryForAssessmentNoteLocal";
    public static final String JNDI_NAME = "AssessmentCategoryForAssessmentNoteLocal";

    eCP.AssessmentCategoryForAssessmentNote.AssessmentCategoryForAssessmentNoteLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
