
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteHomeInterfacePlugin from eCP.AgeGroupForIntervention.AgeGroupForInterventionManager
package eCP.AgeGroupForIntervention;

/**
 * Home interface for AgeGroupForIntervention
 */
public interface AgeGroupForInterventionHome
extends javax.ejb.EJBHome {
    public static final String COMP_NAME = "java:comp/env/ejb/AgeGroupForInterventionRemote";
    public static final String JNDI_NAME = "AgeGroupForInterventionRemote";

    eCP.AgeGroupForIntervention.AgeGroupForInterventionRemote create() throws javax.ejb.CreateException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
