/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eMP.PatSearch.PatSearchManager
package eMP.PatSearch;

/**
 * Local interface for PatSearch
 */
public interface PatSearchLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap getSearchTable(java.lang.String func_act, java.lang.String logged_facility, java.lang.String query, int current, int totalpercent, java.lang.String function_id, java.lang.String search_in, java.lang.String act_yn, java.lang.String[] photo, java.lang.String alignment, java.lang.String othlang, java.util.Properties props, int searchThreshold) ;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
