/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMM.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eMM.Adjustment.label","调整"},
		{"eMM.AllowBonusEntry.label","�?许奖金输入"},
		{"eMM.AllowSampleEntry.label","�?许输入实例"},
//		{"eMM.AssemblyDetails/MFGFormulary.label","Assembly Details/MFG Formulary"},
//		{"eMM.AssemblyInstructions.label","Assembly Instructions"},
//		{"eMM.BillableItem.label","Billable Item"},
//		{"eMM.BinLocationCode.label","Bin Location Code"},
		{"eMM.CategoryType.label","目录类型"},
//		{"eMM.ContactReference.label","Contact Reference"},
//		{"eMM.DecentralizedInventory.label","Decentralized Inventory"},
		{"eMM.DefaultBatchIDifBatchIDisNotApplicable.label","如果批�?��?适用，用缺�?批�?�"},
//		{"eMM.DefaultTradeIDifTradeIDisNotApplicable.label","Default Trade ID if Trade ID is Not Applicable"},
//		{"eMM.FacilityLevel.label","Facility Level"},
//		{"eMM.InchargeName.label","Incharge Name"},
//		{"eMM.InchargeTitle.label","Incharge Title"},
		{"eMM.InventoryManagement.label","库存管�?�"},
//		{"eMM.ItemAlphaCode.label","Item Alpha Code"},
//		{"eMM.ItemAnalysisCode.label","Item Analysis Code"},
//		{"eMM.ItemClassforStore.label","Item Class for Store"},
//		{"eMM.ItemforStore.label","Item for Store"},
//		{"eMM.ItemMaster.label","Item Master"},
//		{"eMM.ItemRemarks.label","Item Remarks"},
//		{"eMM.ItemSpecification.label","Item Specification"},
//		{"eMM.ItemStoreBinLocation.label","Item Store Bin Location"},
//		{"eMM.LastPurchaseAdviceDate.label","Last Purchase Advice Date"},
		{"eMM.Machine.label","机器"},
		{"eMM.MaterialCode.label","�??料代�?"},
		{"eMM.MaterialGroup.label","�??料分组"},
		{"eMM.MaterialGroupCode.label","�??料分组代�?"},
		{"eMM.ModuleApplicability.label","模�?�的适用性"},
		{"eMM.Non-Inventory.label","�?�库存"},
		{"eMM.PeriodEndScope.label","结�?�范围期"},
		{"eMM.PharmacyStockItem.label","�?�房库存项目"},
		{"eMM.PurchaseControl.label","采购控制"},
		{"eMM.QuantityOnOrder.label","订购数�?"},
		{"eMM.SearchString.label","�?�寻字符串"},
//		{"eMM.SterileStock.label","Sterile Stock"},
//		{"eMM.StoreInchargeDetails.label","Store Incharge Details"},
		{"eMM.TradeNameforItem.label","贸易项目�??称"},
		{"eMM.TransactionRemarksCode.label","交易代�?"},
		{"eMM.ItemAnalysisDesc.label","项目分�?说明"},
		{"eMM.BinDesciption.label","本�?置�??述"},
		{"eMM.SupplierDescription.label","供货商说明"},
		{"eMM.TRNRemarksDescription.label","交易备注说明"},
		{"eMM.CSSDComponent.label","消毒组件"},
		{"eMM.ShowSimilarItems.label","查看类似物�?"},
		{"eMM.DefaultBatchIDforNonExpiryItems.label","默认批次编�?�为�?�到期项目"},
		{"eMM.Materials.label","�??料"},
		{"eMM.ItemUOMDefinition.label","项目UOM定义"},
		{"eMM.OccupationStatus.label","�?�业现状"},
		{"eMM.ApplModules.label","应用模�?�"},
		{"eMM.ItemClassCodeFrom.label","项目类别代�?"},
		{"eMM.MaterialCodeFrom.label","�??料代�?"},
		{"eMM.DepartmentCodeFrom.label","部门代�? 从"},
		{"eMM.StoreLocation.label","存放�?置"},
		{"eMM.TotalNoofDepartments.label","总计部门�?�"},
		{"eMM.TotalNoofStore.label","商店�?�"},
		{"eMM.SupplierCodeFrom.label","供货商代�?"},
		{"eMM.SupplierAlphaCode.label","阿尔法供货商代�?"},
		{"eMM.TradeIdFrom.label","贸易标识"},
		{"eMM.EffectiveStatus.label","有效状�?"},
		{"eMM.TRNCode.label","TRN�?"},
		{"eMM.ItemAnalysisCodeFrom.label","项目分�?代�?"},
		{"eMM.ReturnPeriodFrom.label","回归期间"},
		{"eMM.ReceivedQty.label","收到数�?"},
		{"eMM.SupplierTotal.label","供货商共计"},
//		{"eMM.DirectSalesPatient.label","？？"},
		{"eMM.KitTemplate.label","试剂盒范本"},
		{"eMM.ParentStoreforStore.label","总店"},
//		{"eMM.MaterialsGroupDesc.label","Materials Group Desc"},
//		{"eMM.DirectSalesAllowed.label","Direct Sales Allowed"},
		{"eMM.ImportedItem.label","进�?�项目"},
		{"eMM.EssentialItem.label","基本专案"},
		{"eMM.ReimburseType.label","�?�还类型"},
		{"eMM.NonReimbursable.label","�?�?��?�还"},
		{"eMM.PartialReimbursable.label","部分�?�还"},
		{"eMM.FullyReimbursable.label","完全�?�以�?�还"},
		{"eMM.UOMDescription.label","UOM说明"},
		{"eMM.EquivalentUOMCode.label","等效UOM代�?"},
		{"eMM.EquivalentUOMDescription.label","等效UOM说明"},
		{"eMM.TRNRemarksFrom.label","TRN备注"},
		{"eMM.UserAccessForMaterialGroup.label","用户�?�访问设备组"},
//		{"eMM.PODepartment.label","PO Department"}
//Newly added legends on 21/01/09
		{"eMM.AssemblyDetails/MFGFormulary.label","�?件明细/制造商处方"},
		{"eMM.AssemblyInstructions.label","�?件"},
		{"eMM.BillableItem.label","收费项目"},
		{"eMM.BinLocationCode.label","存储�?置代�?"},
		{"eMM.ContactReference.label","�?�系�?�考"},
		{"eMM.DecentralizedInventory.label","分散库存"},
		{"eMM.DefaultTradeIDifTradeIDisNotApplicable.label","如果商�?编�?��?适用,使用缺�?值"},
		{"eMM.DirectSalesAllowed.labelDirect Sales Allowed","�?许直接销售项目"},
		{"eMM.DirectSalesPatient.label","�?许直接销售给病人"},
		{"eMM.FacilityLevel.label","�?业级别"},
		{"eMM.InchargeName.label","入院�??称"},
		{"eMM.InchargeTitle.label","入院标题"},
		{"eMM.ItemAlphaCode.label","项目Alpha 编�?"},
		{"eMM.ItemAnalysisCode.label","项目分�?编�?"},
		{"eMM.ItemClassforStore.label","库存项目分类"},
		{"eMM.ItemforStore.label","库存项目"},
		{"eMM.ItemMaster.label","项目分类"},
		{"eMM.ItemRemarks.label","项目备注"},
		{"eMM.ItemSpecification.label","项目规格"},
		{"eMM.ItemStoreBinLocation.label","项目存储�?置"},
		{"eMM.LastPurchaseAdviceDate.label","上次建议采购日期"},
		{"eMM.MaterialsGroupDesc.labelMaterials Group Desc","�??料组�??述"},
		{"eMM.PODepartment.labelPO Department","订购部门"},
		{"eMM.SterileStock.label","无�?�库存"},
		{"eMM.StoreInchargeDetails.label","库房负责人明细"},


	};
}
