package eMR.resources;

import java.util.*; 


public class Labels_ar extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }
	static final Object[][] contents = {
{"eMR.AccuracyCode.label","كود الدقة"},
{"eMR.AccuracyDescription.label","وصف الدقة"},
{"eMR.AccuracyForPatientClass.label","الدقة لفئة المريض"},
{"eMR.AckDateTime.label","وقت و تاريخ إشعار الاستلام"},
{"eMR.ActiveVolumeNumber.label","رقم المجلد النشط"},
{"eMR.Acute.label","حاد"},
{"eMR.AdditionalAmount.label","مبلغ إضافي"},
{"eMR.AdditionalCharges.label","رسوم إضافية"},
{"eMR.AdditionalReceiptDate.label","تاريخ الاستلام الإضافي"},
{"eMR.AdditionalReceiptNo.label","رقم الإيصال الإضافي"},
{"eMR.AddtoProblemList.label","أضف إلى قائمة المشاكل"},
{"eMR.AdmVisitDate.label","تاريخ الدخول / الزيارة"},
{"eMR.AdverseEventType.label","نوع الحدث العكسى"},
{"eMR.AdverseSetup.label","الاعداد العكسى"},
{"eMR.AgeGroupDetails.label","تفاصيل الفئة العمرية"},
{"eMR.AgeGroupforTerminologyCode.label","الفئة العمرية لرمز المصطلحات"},
{"eMR.AgeSpecific.label","العمر المحدد"},
{"eMR.AgeSpecificIndicator.label","مؤشر خاص بالعمر"},
{"eMR.AllergyClassCode.label","كود فئة الحساسية"},
{"eMR.AllergyCode.label","كود الحساسية"},
{"eMR.AllergyTypeClass.label","فئة نوع الحساسية"},
{"eMR.AllergyTypeCode.label","كود نوع الحساسية"},
{"eMR.AntenatalService.label","خدمة ما قبل الولادة"},
{"eMR.ApplicantAddress.label","عنوان مقدم الطلب"},
{"eMR.ApplicantInformation.label","معلومات مقدم الطلب"},
{"eMR.ApplicantName.label","اسم مقدم الطلب"},
{"eMR.ApplicationCompletionDates.label","تاريخ إتمام الطلب"},
{"eMR.ApplicationDate.label","تاريخ الطب"},
{"eMR.ApplicationDateTime.label","تاريخ / وقت الطلب"},
{"eMR.ApplicationforMedicalBoard.label","طلب مجلس طبي"},
{"eMR.ApplicationNo.label","رقم الطلب"},
{"eMR.ApplicationStatus.label","حالة الطلب"},
{"eMR.ApplicationType.label","نوع الطلب"},
{"eMR.ApplnSubDate.label","تاريخ الطلب الفرعى"},
{"eMR.ApplTypeCode.label","كود نوع الطلب"},
{"eMR.AppointmentforMedicalBoardRequest.label","طلب التعيين على اللجنة الطبية"},
{"eMR.AppointmentGiven.label","موعد معين"},
{"eMR.AppointmentIntimated.label","موعد محدد"},
{"eMR.ApptDetails.label","تفاصيل الموعد"},
{"eMR.AsEvidencedBy.label","يتضح من"},
{"eMR.Asterisk.label","النجمة"},
{"eMR.AsteriskCode.label","رمز النجمة"},
{"eMR.AsteriskCodeforDaggerCode.label","كود رمز النجمه"},
{"eMR.AsteriskDescription.label","وصف النجمة"},
{"eMR.Asthma.label","الربو"},
{"eMR.AttendingCommunityNurse.label","حضور مؤتمر الممرضات"},
{"eMR.Attentionto.label","الانتباه إلى"},
{"eMR.AverageNumberofDrugs.label","متوسط ​​عدد الأدوية"},
{"eMR.BloodGroupCode.label","كود فصيلة الدم"},
{"eMR.BornWithintheHospital.label","ولد داخل المستشفى"},
{"eMR.BuildEpisodeofCare.label","بناء زيارة رعاية"},
{"eMR.BuildStatistics.label","الاحصائيات"},
{"eMR.CancerNotificationRegistryForm.label","نموذج التسجيل / الإخطار بالسرطان"},
{"eMR.CausativeAgentForAdverseEvent.label","العامل المسبب لحدث ضار"},
{"eMR.CauseOfDeathDetails.label","تفاصيل سبب الوفاة"},
{"eMR.Ceasarean.label","قيصرية"},
{"eMR.ChargesApplicable.label","الرسوم المطبقة"},
{"eMR.ChargesDetails.label","تفاصيل الرسوم"},
{"eMR.CheckoutEndVisit.label","تسجيل الخروج - إنهاء الزيارة"},
{"eMR.Chronic.label","مزمن"},
{"eMR.ClassificationLevelDetails.label","تفاصيل مستوى التصنيف"},
{"eMR.ClassificationLevels.label","مستويات التصنيف"},
{"eMR.ClosedBy.label","أغلقت"},
{"eMR.ClosedDate.label","تاريخ الغلق"},
{"eMR.CodeCategory.label","فئة الكود"},
{"eMR.CodeForDiagnosisProcedureGroup.label","كود للتشخيص / مجموعة الإجراءات"},
{"eMR.CodeLength.label","طول الكود"},
{"eMR.CodeScheme.label","مخطط التعليمات البرمجية"},
{"eMR.CodeType.label","نوع الكود"},
{"eMR.CollectDate.label","تاريخ التجميع"},
{"eMR.Common.label","مشترك"},
{"eMR.CommunicationDateTime.label","تاريخ / وقت الاتصال"},
{"eMR.CommunicationDetails.label","تفاصيل الاتصال"},
{"eMR.CommunicationName.label","اسم الاتصال"},
{"eMR.ComorbCheck.label","فحص الاعتلال المشترك"},
{"eMR.ComplicnComorb.label","المضاعفات / الاعتلال المشترك"},
{"eMR.ConfirmTransmitNotifiableReport.label","تأكيد إرسال تقرير الإخطار"},
{"eMR.ConsentLetter.label","خطاب الموافقة"},
{"eMR.Consequence.label","نتيجة"},
{"eMR.ContactNumber.label","رقم الاتصال"},
{"eMR.Correspondence.label","المراسلات"},
{"eMR.CostofInvestigationsandTreatments.label","تكلفة التحقيقات والعلاجات"},
{"eMR.CostofStay.label","تكلفة الإقامة"},
{"eMR.CPTCode.label","كود التشخيص"},
{"eMR.CurrentDiagnosisProfile.label","ملف التشخيص الحالي"},
{"eMR.CurrentMonth.label","الشهر الحالي"},
{"eMR.CustomDiagnosisGroup.label","مجموعة التشخيص المخصصة"},
{"eMR.CustomDiagnosisGroupDetails.label","تفاصيل مجموعة التشخيص المخصصة"},
{"eMR.CutOffUnit.label","وحدة القطع"},
{"eMR.Dagger.label","Dagger"},
{"eMR.DaggerCode.label","Dagger Code"},
{"eMR.DaggerDescription.label","Dagger Description"},
{"eMR.DateDetails.label","تفاصيل التاريخ"},
{"eMR.DatePosted.label","تاريخ الإعلان"},
{"eMR.DaystoComplete.label","أيام حتى الاكتمال"},
{"eMR.Death.label","الموت"},
{"eMR.DeathDate.label","تاريخ الوفاة"},
{"eMR.DeathDetails.label","تفاصيل الوفاة"},
{"eMR.DeathRegistration.label","تسجيل الوفاة"},
{"eMR.DeathRegistrationDetails.label","تفاصيل تسجيل الوفاة"},
{"eMR.DeceasedPeriod.label","فترة الوفاة"},
{"eMR.DefiningCharacteristics.label","تحديد الخصائص"},
{"eMR.DelayinPreparation.label","التأخير في التحضير"},
{"eMR.DelayOverdueofMedicalReport.label","تأخيرالتقرير الطبي"},
{"eMR.DeliverDispatchMode.label","تسليم / وضع الإرسال"},
{"eMR.Delivered.label","التوصيل"},
{"eMR.DeliveredDate.label","تاريخ التوصيل"},
{"eMR.DeliverMedicalBoard.label","تسليم الملف الطبى"},
{"eMR.DeliverMedicalReport.label","تسليم التقرير الطبى"},
{"eMR.DeliverMode.label","وضع التسليم"},
{"eMR.DeliveryDate.label","تاريخ التسليم"},
{"eMR.DengueFever.label","حمى الضنك"},
{"eMR.DepartmentSpecialty.label","القسم / التخصص"},
{"eMR.DiagCodeScheme.label","كود التشخيص"},
{"eMR.DiagDetails.label","تفاصل التشخيص"},
{"eMR.DiagGroup.label","مجموعة التشخيص"},
{"eMR.DiagGrpCode.label","كود مجموعة التشخيص"},
{"eMR.DiagGrpDesc.label","مسمى مجموعة التشخيص"},
{"eMR.DiagnosisCodeRange.label","نطاق كود التشخيص"},
{"eMR.DiagnosisCodeScheme.label","مخطط كود التشخيص"},
{"eMR.DiagnosisCodingRange.label","نطاق كود التشخيص"},
{"eMR.DiagnosisFactors.label","عوامل التشخيص"},
{"eMR.DiagnosisGroup.label","مجموعة التشخيص"},
{"eMR.DiagnosisGroupCode.label","كود مجموعة التشخيص"},
{"eMR.DiagnosisNature.label","طبيعة التشخيص"},
{"eMR.DiagnosisProblemCode.label","التشخيص / كود المشكلة"},
{"eMR.DiagnosisProcedureGroup.label","مجموعة التشخيص / الإجراءات"},
{"eMR.DiagnosisRecoding.label","إعادة تكويد التشخيص"},
{"eMR.DiagnosisRecodingDetails.label","تفاصيل إعادة التشخيص"},
{"eMR.DiagnosisSet.label","مجموعة التشخيص"},
{"eMR.DiagnosisSpecific.label","تشخيص محدد"},
{"eMR.DiagnosisStage.label","مرحلة التشخيص"},
{"eMR.DiagnosisTabs.label","علامات تبويب التشخيص"},
{"eMR.DiagStage.label","مرحلة التشخيص"},
{"eMR.DifferentialDiagnosis.label","تشخيص متباين"},
{"eMR.DifferentialGroup.label","المجموعة المختلفة"},
{"eMR.DischPeriod.label","فترة الخروج"},
{"eMR.Discipline.label","القواعد"},
{"eMR.DisciplineCode.label","كود القواعد"},
{"eMR.DisciplineforWard.label","قواعد الانضباط لادوار"},
{"eMR.DiscreteMeasureforGeneticMarkers.label","مقياس منفصل للعلامات الجينية"},
{"eMR.Disease.label","مرض"},
{"eMR.DisplayActiveOnly.label","عرض نشط فقط"},
{"eMR.EmergencyClinicCode.label","كود عيادة الطوارئ"},
{"eMR.EmergencyDepartment.label","قسم الطوارئ"},
{"eMR.EncPeriod.label","فترة الزيارة"},
{"eMR.EnterEditSensitiveDiagnosis.label","ادخال / تعديل التشخيص"},
{"eMR.EpisodeNo.label","رقم الزيارة"},
{"eMR.EpisodeOfCare.label","الزيارة"},
{"eMR.EventTypeCode.label","رمز نوع الحدث"},
{"eMR.ExistingDifferentialDiagnosis.label","التشخيص الحالى"},
{"eMR.ExistingEpisodeofCare.label","الزيارة الحالية"},
{"eMR.ExternalCause.label","سبب خارجي"},
{"eMR.ExternalFile.label","ملف خارجي"},
{"eMR.ExternalFileStorageLocation.label","موقع تخزين الملفات الخارجية"},
{"eMR.ExternalMasterCode.label","الكود الرئيسى الخارجى"},
{"eMR.Extreme.label","شديد"},
{"eMR.FactorCode.label","كود العامل"},
{"eMR.FactorDescription.label","وصف العامل"},
{"eMR.Factors.label","العوامل"},
{"eMR.FactorsforTerminologyCode.label","عوامل رمز المصطلحات"},
{"eMR.FactorTypes.label","أنواع العامل"},
{"eMR.FileCreatedBy.label"," تم إنشاؤه بواسطة"},
{"eMR.FilePath.label","مسار الملف"},
{"eMR.Forceps.label","ملقط"},
{"eMR.FormationofMedicalBoard.label","تشكيل مجلس طبي"},
{"eMR.FormationStatus.label","حالة التشكيل"},
{"eMR.ForwardedDate.label","تاريخ إعادة التوجيه"},
{"eMR.ForwardedHOD.label","رئيس القسم / المنسق المرسل"},
{"eMR.ForwardedHODDate.label","تاريخ المحال من رئيس القسم / المنسق"},
{"eMR.InformToHOD.label","إبلاغ رئيس القسم / المنسق"},
{"eMR.ForwardedPractitioner.label","الممارس المحول"},
{"eMR.ForwardedtoPractitioner.label","الممارس المحول اليه"},
{"eMR.ForwardedtoHOD.label","يُحال إلى رئيس القسم / المنسق"},
{"eMR.ForwardMedicalBoardRequest.label","طلب إحالة المجلس الطبي"},
{"eMR.ForwardMedicalReportRequest.label","طلب تقرير طبي آجل"},
{"eMR.FromProcedureUnit.label","من وحدة الإجراءات"},
{"eMR.FromReferralDtls.label","من تفاصيل الاحالة"},
{"eMR.GenderSpecific.label","خاص بالنوع"},
{"eMR.GeneticMarkers.label","العلامات الجينية"},
{"eMR.GovernmentBodies.label","الهيئات الحكومية"},
{"eMR.GroupCategory.label","فئة المجموعة"},
{"eMR.GroupDesc.label","وصف المجموعة"},
{"eMR.HighRiskCode.label","كود عالي الخطورة"},
{"eMR.HighRiskCondition.label","حالة عالية الخطورة"},
{"eMR.HomeState.label","المنزل"},
{"eMR.HospitalCode.label","كود المستشفى"},
{"eMR.ICD10.label","ICD10"},
{"eMR.ICDCodeForTabulationList.label","رمز ICD لقائمة الجدولة"},
{"eMR.ICDCodeSearch.label","البحث عن رمز ICD"},
{"eMR.ICDCodeType.label","نوع رمز ICD"},
{"eMR.ICDDesc.label","وصف التصنيف الدولي للأمراض"},
{"eMR.ICDSetup.label","إعداد التصنيف الدولي للأمراض"},
{"eMR.InpatientCensus.label","تعداد المرضى الداخليين"},
{"eMR.Inside.label","في داخل"},
{"eMR.InsuranceCompanies.label","شركات التأمين"},
{"eMR.InterfaceMode.label","وضع الواجهة"},
{"eMR.InternalMedicine.label","الباطنة"},
{"eMR.IntimateAppointmentforMedicalBoardRequest.label","طلب موعد للهيئة الطبية"},
{"eMR.IntimatedTo.label","اشار الى"},
{"eMR.IntimationMode.label","وضع التنبيه"},
{"eMR.IssuedInTransit.label","صدر - قيد النقل"},
{"eMR.Lawyers.label","محامون"},
{"eMR.LetterDateTime.label","تاريخ / وقتا الخطاب"},
{"eMR.ListDesc.label","قائمة المسميات"},
{"eMR.ListGroup.label","قائمة المجموعات"},
{"eMR.LongTitle.label","عنوان طويل"},
{"eMR.MainGroup.label","المجموعة الرئيسية"},
{"eMR.MajorDiagCat.label","فئة التشخيصات الاساسية"},
{"eMR.Manifestation.label","مظهر"},
{"eMR.MarkedStatus.label","وضع ملحوظ"},
{"eMR.MarkingofMLCOSCC.label","Marking of MLC/OSCC"},
{"eMR.Master.label","رئيسى"},
{"eMR.MasterDescription.label","الوصف الرئيسي"},
{"eMR.Maternity.label","التوليد"},
{"eMR.MaternityWard.label","جناح الولادة"},
{"eMR.MedBoardCode.label","كود المجلس الطبي"},
{"eMR.MedBoardTypeCode.label","كود نوع المجلس الطبي"},
{"eMR.MedicalBoard.label","المجلس الطبي"},
{"eMR.MedicalBoardCompleted.label","المجلس الطبي مكتمل"},
{"eMR.MedicalBoardFormed.label","تشكيل المجلس الطبي"},
{"eMR.MedicalBoardMembers.label","أعضاء المجلس الطبي"},
{"eMR.MedicalBoardMembersFormation.label","تشكيل أعضاء الهيئة الطبية"},
{"eMR.MedicalBoardStatus.label","حالة اللجنة الطبي"},
{"eMR.MedicalBoardType.label","نوع اللجنة الطبية"},
{"eMR.MedicalEventTypeCode.label","كود نوع الحدث الطبى"},
{"eMR.MedicalReport.label","التقرير الطبى"},
{"eMR.MedicalReportBoardSetup.label","التقرير الطبي / إعداد اللجنة"},
{"eMR.MedicalReportCompleted.label","التقرير الطبي مكتمل"},
{"eMR.MedicalReportPaymentInterface.label","واجهة دفع التقرير الطبي"},
{"eMR.MedicalReportStatus.label","حالة التقرير الطبي"},
{"eMR.MemberType.label","نوع العضو"},
{"eMR.MemberTypeUser.label","نوع العضو المستخدم"},
{"eMR.MonthFrom.label","من شهر"},
{"eMR.MonthlyMaternityCensus.label","التعداد الشهري للمواليد"},
{"eMR.MRParameter.label","إعدادات السجل الطبى"},
{"eMR.NeonatalDeathsoccuredwithin.label","وفيات حديثي الولادة"},
{"eMR.NewDiagDescription.label","وصف التشخيص الجديدة"},
{"eMR.NewDiagnosisCode.label","كود التشخيص الجديد"},
{"eMR.NewDiagRemarks.label","ملاحظات التشخيص الجديد"},
{"eMR.NewDiagStage.label","مرحلة التشخيص الجديد"},
{"eMR.NewDiagType.label","نوع التشخيص الجديد"},
{"eMR.NewGroup.label","مجموعة جديدة"},
{"eMR.NonNotifiable.label","غير قابل للإخطار"},
{"eMR.NonNotifiableonly.label","غير قابل للإبلاغ فقط"},
{"eMR.NonSensitive.label","غير حساسة"},
{"eMR.NonSensitiveonly.label","غير حساسة فقط"},
{"eMR.NoofLevels.label","عدد المستويات"},
{"eMR.NoteforTerminologyCode.label","ملاحظان لكود المصطلح"},
{"eMR.NotesSectionHeading.label","عنوان قسم الملاحظات"},
{"eMR.NotifiableForm.label","نموذج الإخطار"},
{"eMR.NotifiableIndicator.label","مؤشرالإخطار"},
{"eMR.Notifiableonly.label","للإبلاغ عنه فقط"},
{"eMR.Notification.label","تنبيه"},
{"eMR.NotificationDate.label","تاريخ الإنذار"},
{"eMR.NotificationForm.label","نموذج الإخطار"},
{"eMR.OldDiagDescription.label","وصف التشخيص القديم"},
{"eMR.OldDiagnosisCode.label","كود التشخيص القديم"},
{"eMR.OldDiagRemarks.label","ملاحظات التشخيص القديم"},
{"eMR.OldDiagStage.label","التشخيص القديم"},
{"eMR.OldDiagType.label","نوع التشخيص القديم"},
{"eMR.OnsetDateFrom.label","من تاريخ"},
{"eMR.OnsetDateTo.label","الى تاريخ"},
{"eMR.OnsetLocation.label","موقع البداية"},
{"eMR.OnsetPractitioner.label","الممارس"},
{"eMR.OnsetType.label","النوع"},
{"eMR.OprtgRoomProc.label","إجراءات غرفة العمليات"},
{"eMR.OrderCatalogforSSReports.label","كتالوج الطلب لتقارير SS"},
{"eMR.OrderSerialNo.label","الرقم التسلسلي للطلب"},
{"eMR.OrigDiagCode.label","كود التشخيص الاصلى"},
{"eMR.OriginalDiagDescription.label","وصف التشخيص الاصلى"},
{"eMR.OriginalDiagnosisCode.label","كود التشخيص الاصلى"},
{"eMR.OriginalDiagRemarks.label","ملاحظات التشخيص الاصلى"},
{"eMR.OriginalDiagStage.label","مرحلة التشخيص الاصلى"},
{"eMR.OriginalDiagType.label","نوع التشخيص الاصلى"},
{"eMR.OtherPatient.label","مريض اخر"},
{"eMR.PatientIdName.label","رقم المريض / الاسم"},
{"eMR.PatientRecordSent.label","تم إرسال سجل المريض"},
{"eMR.Pediatric.label","اخصائي اطفال"},
{"eMR.PlaceofDelivery.label","مكان التوصيل"},
{"eMR.PleaseSelectGroupforthenewDiagnois.label","برجاء اختيار مجموعة التشخيص الجديد"},
{"eMR.Postmortemrequested.label","تم طلب تشريح الجثة"},
{"eMR.PostnatalService.label","خدمة ما بعد الولادة"},
{"eMR.PrefMonth.label","الشهر السابق"},
{"eMR.PreparedbyPractitioner.label","تم الاعداد بواسطة الممارس"},
{"eMR.PrepareMedicalReport.label","تجهيز التقرير طبي"},
{"eMR.PrepareMedicalReportbyBoard.label","إعداد التقرير الطبي من قبل اللجنة"},
{"eMR.ProcedureClass.label","فئة الإجراء"},
{"eMR.ProcedureCodeScheme.label","مخطط كود الإجراءات"},
{"eMR.ProcedureDate.label","تاريخ الإجراء"},
{"eMR.ProcedureSpecific.label","مواصفات الاجراء"},
{"eMR.ReceivedbyMedicalBoard.label","تم الاستلام من خلال اللجنة الطبي"},
{"eMR.ReceivedbyMedicalRecord.label","تم الاستلام من خلال السجلات الطبية"},
{"eMR.ReceiveMedicalReport.label","استلام تقرير طبي"},
{"eMR.Recode.label","إعادة تكويد"},
{"eMR.RecodedBy.label","إعادة طلب بواسطة"},
{"eMR.RecodedCode.label","إعادة تكويد الكود"},
{"eMR.RecodedDate.label","تاريخ إعادة التكويد"},
{"eMR.RecodedDiagnosis.label","إعادة تكويد التشخيص"},
{"eMR.RecordDiagnosis.label","تسجيل التشخيص"},
{"eMR.RecordPatientBloodGroup.label","سجل فصيلة دم المريض"},
{"eMR.RecordSequence.label","تسلسل التسجيل"},
{"eMR.RegnStartCons.label","التسجيل - ابدأ الاستشارة"},
{"eMR.Related.label","ذات صلة"},
{"eMR.RelatedandRiskFactor.label","عامل المخاطرة وذات الصلة"},
{"eMR.RelatedFactor.label","عامل ذو صلة"},
{"eMR.ReportComplete.label","التقرير مكتمل"},
{"eMR.ReportDelivered.label","تم تسليم التقرير"},
{"eMR.ReportFor.label","تقرير لـ"},
{"eMR.ReportOn.label","تقرير عن"},
{"eMR.ReportPreparedDate.label","تاريخ إعداد التقرير"},
{"eMR.ReportTakenBy.label","تقرير مأخوذ بواسطة"},
{"eMR.RequestedPractitioner.label","الممارس الطالب"},
{"eMR.RequestforMedicalBoard.label","مطلوب للجنة الطبية"},
{"eMR.RequestID.label","رقم الطلب"},
{"eMR.RequestorCode.label","كود الطالب"},
{"eMR.RequestorDetails.label","تفاصيل الطالب"},
{"eMR.RequestorType.label","نوع الطالب"},
{"eMR.RequestPractitioner.label","طلب ممارس"},
{"eMR.RequiredDocuments.label","ملفات مطلوبة"},
{"eMR.ReturnedInTransit.label","إعادة الحركة"},
{"eMR.RevisedCollectDate.label","مراجعة تاريخ التحصيل"},
{"eMR.RevisedDate.label","تاريخ المراجعة"},
{"eMR.ReviseMedicalBoard.label","مراجعة اللجنة الطبية"},
{"eMR.ReviseMedicalReport.label","مراجعة التقرير الطبي"},
{"eMR.RHDFactor.label","عامل RH (D)"},
{"eMR.RhesusFactor.label","عامل ريسوس"},
{"eMR.RhesusFactorCode.label","كود عامل الريسوس"},
{"eMR.Risk.label","المخاطرة"},
{"eMR.RiskFactor.label","عامل الخطر"},
{"eMR.SearchDesc.label","بحث بالوصف"},
{"eMR.SectionFileNo.label","قسم / رقم الملف"},
{"eMR.Selectable.label","اختيار"},
{"eMR.SelectDiagnosisProblem.label","اختيار التشخيص / المشكلة"},
{"eMR.SelectedClassificationLevels.label","مستويات التصنيف المختارة"},
{"eMR.SensitiveIndicator.label","مؤشرالحساسية"},
{"eMR.Sensitiveonly.label","حساسة فقط"},
{"eMR.Sensitivity.label","حساسية"},
{"eMR.SocialSecurityOrganization.label","منظمة الضمان الاجتماعي"},
{"eMR.SpclstClinicEmerDept.label","عيادة تخصص قسم الطوارئ"},
{"eMR.SpecialEditFlag.label","علامة التحرير الخاصة"},
{"eMR.SpecialistClinicandEmergencyDepartment.label","العيادة التخصصية وقسم الطوارئ"},
{"eMR.StartConsCheckout.label","إبداء الزيارة/ خروج"},
{"eMR.StatusCompleted.label","الحالة اكتملت"},
{"eMR.StatusofMedicalBoardRequest.label","حالة طلب اللجنة الطبية"},
{"eMR.StatusofMedicalReportRequest.label","حالة طلب التقرير طبي"},
{"eMR.Subdivided.label","مقسمة"},
{"eMR.SubGroup.label","المجموعة الفرعية"},
{"eMR.SupportingDiagnosisCode.label","كود التشخيص"},
{"eMR.TabListCode.label","رمز قائمة الجدولة"},
{"eMR.TabListDescription.label","مسمى قائمة الجدولة"},
{"eMR.TabulationList.label","قائمة الجدولة"},
{"eMR.TabulationListCode.label","كود قائمة الجدولة"},
{"eMR.TabulationListNumber.label","رقم قائمة الجدولة"},
{"eMR.TabulationListType.label","نوع قائمة الجدولة"},
{"eMR.TermDescription.label","وصف المصطلح"},
{"eMR.TerminologyCodeAssociated.label","كود المصطلحات المرتبطة"},
{"eMR.TerminologyDescription.label","وصف المصطلحات"},
{"eMR.TerminologyGroup.label","مجموعة المصطلحات"},
{"eMR.TerminologyID.label","كود المصطلحات"},
{"eMR.TerminologySetDescription.label","وصف مجموعة المصطلحات"},
{"eMR.TerminologySetforFacility.label","مجموعة المصطلحات للمنشأة"},
{"eMR.TerminologySetforPractitioner.label","مجموعة المصطلحات للممارس"},
{"eMR.TerminologySetforPractType.label","مجموعة المصطلحات لنوع الممارسة"},
{"eMR.TerminologySetforSpecialty.label","مجموعة المصطلحات الخاصة بالتخصص"},
{"eMR.TerminologySetId.label","كود مجموعة المصطلحات"},
{"eMR.TerminologySetup.label","إعداد المصطلحات"},
{"eMR.TermologySet.label","مجموعة المصطلحات"},
{"eMR.ToProcedureUnit.label","إلى وحدة الإجراءات"},
{"eMR.ToReferralDtls.label","الى تفاصيل الاحالة"},
{"eMR.TotalNoOfPatients.label","العدد الإجمالي للمرضى"},
{"eMR.TransmissionDateTime.label","تاريخ / وقت الإرسال"},
{"eMR.TransmissionDetails.label","تفاصيل الإرسال"},
{"eMR.TransmissionName.label","اسم الإرسال"},
{"eMR.TransmitNotifialbeDiseaseReport.label","إرسال تقرير المرض الواجب الإبلاغ عنه"},
{"eMR.Treated.label","يعالج"},
{"eMR.TypeDO.label","نوع D / O"},
{"eMR.TypeofDelivery.label","نوع التسليم"},
{"eMR.TypeofMedicalBoard.label","نوع اللجنة الطبية"},
{"eMR.UnauthorisedUser.label","مستخدم غير مصرح به"},
{"eMR.UngroupDiagnosis.label","التشخيصات الغيرمجمعة"},
{"eMR.UpdateDiagnosisProfile.label","تحديث ملف التشخيص"},
{"eMR.Vacuum.label","فراغ"},
{"eMR.ViewEncounterDetails.label","عرض تفاصيل الزيارة"},
{"eMR.ViewMedicalReport.label","مشاهدة التقرير الطبي"},
{"eMR.Visited.label","تمت زيارتها"},
{"eMR.WardCode.label","كود الجناح"},
{"eMR.YearFrom.label","من سنة"},
{"eMR.InterfaceFromBilling.label","واجهة من الفواتير (إيصال النظام)"},
{"eMR.NoInterface.label","لا توجد تكامل (إيصال يدوي)"},
{"eMR.ReceiptDateTime.label","وقت تاريخ الاستلام"},
{"eMR.Unclassified.label","غير مصنف"},
{"eMR.Indeterminate.label","غير محدد"},
{"eMR.RecordNotes.label","سجل الملاحظات"},
{"eMR.SignatureOfPatient.label","توقيع المريض"},
{"eMR.SignatureOfParentGuardian.label","توقيع ولي الأمر / الوصي"},
{"eMR.SignatureOfWitness.label","توقيع الشاهد"},
{"eMR.PrintedDate.label","التاريخ المطبوع"},
{"eMR.MaintainDeathRegister.label","الاحتفاظ بسجل الوفيات"},
{"eMR.EquivalentTermSet.label","مجموعة الشروط المكافئة"},
{"eMR.EquivalentTermSetCode.label","كود مجموعة الشروط المكافئة"},
{"eMR.EquivalentTermSetDesc.label","وصف مجموعة الشروط المكافئة"},
{"eMR.EncounterStage.label","مراحل الزيارة"},
{"eMR.RecordNotifiableForm.label","سجل نموذج الإخطار"},
{"eMR.Expand.label","مدد"},
{"eMR.CurrentAssessment.label","التقييم الحالي"},
{"eMR.Allergen.label","مسببات الحساسية"},
{"eMR.Certanity.label","تاكيد"},
{"eMR.EventTypeId.label","كود نوع الحدث"},
{"eMR.Hypersensitivity.label","فرط الحساسية"},
{"eMR.TypeII.label","نوع  II"},
{"eMR.TypeIII.label","نوع III"},
{"eMR.TypeIV.label","نوع  IV"},
{"eMR.Recurrence.label","تكرار"},
{"eMR.CausativeSubstance.label","المادة المسببة"},
{"eMR.Ingestion.label","ابتلاع"},
{"eMR.Inhalation.label","استنشاق"},
{"eMR.Injection.label","حقنة"},
{"eMR.Tropical.label","الاستوائية"},
{"eMR.ReactionCaused.label","شبب رد الفعل"},
{"eMR.OtherReactions.label","ردود أفعال أخرى"},
{"eMR.SiteOfReaction.label","موقع التفاعل"},
{"eMR.SourceOfInfo.label","مصدر المعلومة"},
{"eMR.TreatAdviceActionTaken.label","علاج النصيحة / الإجراء المتخذ"},
{"eMR.PatientObservation.label","ملاحظة المريض"},
{"eMR.AllergyTestResult.label","نتيجة اختبار الحساسية"},
{"eMR.StaffObservation.label","ملاحظة الموظفين"},
{"eMR.reactiondesc.label","وصف رد الفعل"},
{"eMR.AdeverseEventsAllgSens.label","الأحداث الضائرة (الحساسية / الحساسيات)"},
{"eMR.ApplicableAdverseEventTypeInd.label","تنطبق مؤشرات نوع الحدث الضار"},
{"eMR.AdverseEventTypeIndicator.label","مؤشر نوع الحدث الضار"},
{"eMR.AdverseEventTypeDesc.label","وصف نوع الحدث الضار"},
{"eMR.AdverseEventTypeCode.label","كود نوع الحدث الضار"},
{"eMR.AllergenAgent.label","عامل مسببات الحساسية"},
{"eMR.AdverseReaction Code.label","كود رد الفعل العكسي"},
{"eMR.AdverseReaction Desc.label","وصف رد الفعل العكسي"},
{"eMR.AllergenCode.label","كود مسببات الحساسية"},
{"eMR.Allergendesc.label","وصف مسببات الحساسية"},
{"eMR.ReactionType.label","نوع رد الفعل"},
{"eMR.ReactionAgentCode.label","وصف رد الفعل"},
{"eMR.ReactionAgentDesc.label","وصف عامل التفاعل"},
{"eMR.NoDataFound.label","لا توجد بيانات"},
{"eMR.PrevDelMedReport.label","تقرير طبي سابق تم تسليمه"},
{"eMR.addreaction.label","اضافة  رد فعل"},
{"eMR.DrugLookup.label","بحث الادوية"},
{"eMR.StatusDateTime.label","تاريخ / وقت الحالة"},
{"eMR.OnsetDateTime.label","تاريخ / وقت البدء"},
{"eMR.ReactionDateTime.label","تاريخ / وقت رد الفعل"},
{"eMR.AdverseEventIndindicator.label","مؤشر الحدث الضار"},
{"eMR.StatusDate.label","تاريخ الحالة"},
{"eMR.ReactionSearch.label","بحث عن رد فعل"},
{"eMR.HideDetails.label","أخفاء التفاصيل"},
{"eMR.CausativeAgent.label","العامل المسبب"},
{"eMR.Indexed.label","مفهرسة"},
{"eMR.TerminologyGroupforCustomList.label","مجموعة المصطلحات للقائمة المخصصة"},
{"eMR.AdmittingDiagnosis.label","تشخيص الدخول"},
{"eMR.SuppDiagMandatoryForConsequence.label","التشخيص إجبارى للنتيجة"},
{"eMR.SuppDiagMandatoryForDagger.label","التشخيص إجبارى"},
{"eMR.AuthorisedPractitioner.label","ممارس معتمد"},
{"eMR.NationalGroupReq.label","مجموعة الجنسية إجبارى"},
{"eMR.FileCreatedAt.label","تم إنشاء الملف في"},
{"eMR.MDSforPatClass.label","MDS لفئة المرضى"},
{"eMR.MDS.label","الحد الأدنى لمجموعة البيانات"},
{"eMR.AcceptOption.label"," قبول الاختيار"},
{"eMR.ApplicableSide.label","الجانب القابل للتطبيق"},
{"eMR.OralCavity.label","تجويف الفم"},
{"eMR.TermCodeControl.label","ضوابط كود المصطلح"},
{"eMR.DiagnosisClassification.label","تصنيف التشخيص"},
{"eMR.DefaultTermSet.label","المصطلح الافتراضي"},
{"eMR.DiagnosisClassificationApplicable.label","تصنيف التشخيص"},
{"eMR.CrossReferenceRule.label","القاعدة المرجعية"},
{"eMR.CrossReferenceType.label","نوع القاعدة المرجعية"},
{"eMR.EstimatedDuration.label","المدة المقدرة"},
{"eMR.ListValue.label","قائمة القيم"},
{"eMR.AppForRecoders.label","قابل للتسجيل"},
{"eMR.DiagnosisProcedureRecode.label","تسجيل التشخيص / الإجراءات"},
{"eMR.DiagnosisProcedureCode.label","تكويد التشخيص / الإجراءات"},
{"eMR.RecodeSetup.label","إعادة تكويد الإعداد"},
{"eMR.CutOffPeriodForRecoding.label","فترة القطع لإعادة التكويد"},
{"eMR.DaysFromVisitCompletion.label","عدد الايام من انتهاء الزيارة"},
{"eMR.AllowAuthorization.label","السماح بالترخيص"},
{"eMR.ActionIfNotDone.label","الإجراء إذا لم يتم"},
{"eMR.AllowRecoding.label","السماح بالتسجيل"},
{"eMR.AllowProcedureRecoding.label","السماح بإعادة تسجيل الإجراء"},
{"eMR.OT.label","OT"},
{"eMR.NonOT.label","غير OT"},
{"eMR.GracePeriod.label","فترة السماح"},
{"eMR.RecodingAllowBeyondCutOff.label","إعادة التكويد مسموح به بعد فترة قطع المستوى القصوى"},
{"eMR.daysfromdischarge.label","عدد الايام بعد الخروج"},
{"eMR.ApplicableRecodingComponent.label","التسجيل القابل للتطبيق"},
{"eMR.PendingReview.label","في انتظار المراجعة"},
{"eMR.MyLevel.label","مستواي"},
{"eMR.Select.label","اختيار"},
{"eMR.DRGCalculationApplicable.label","تطبيق حساب DRG"},
{"eMR.show.label","عرض"},
{"eMR.CausedDeath.label","تسبب وفاه"},
{"eMR.CodedBy.label","مشفر بواسطة"},
{"eMR.StageWhichAuthorizationApplicable.label","المرحلة التي يكون فيها التفويض قابلاً للتطبيق"},
{"eMR.Laterality.label","لاحقة"},
{"eMR.NewCode.label","كود جديد"},
{"eMR.Sequence.label","تسلسل"},
{"eMR.AdverseEvents.label","الأحداث السلبية"},
{"eMR.CodedDateandTime.label","تاريخ ووقت التكويد"},
{"eMR.ApplicablePatientClassForRecoding.label","فئة المريض المطبقة لإعادة التكويد"},
{"eMR.EM.label","EM"},
{"eMR.DRGCalculation.label","حساب DRG"},
{"eMR.MDC.label","MDC"},
{"eMR.DRG.label","DRG"},
{"eMR.WTLOS.label","WTLOS"},
{"eMR.RW.label","RW"},
{"eMR.OT.label","OT"},
{"eMR.AdjRW.label","Adj RW"},
{"eMR.WARN.label","WARN"},
{"eMR.PatientInformation.label","بيانات المريض"},
{"eMR.FieldSeperator.label","فاصل "},
{"eMR.CallOS.label","استدعاء OS"},
{"eMR.CalculateDRG.label","حساب DRG"},
{"eMR.DRGResults.label","نتيجة DRG"},
{"eMR.OriginalCode.label","الكود الأصلي"},
{"eMR.OriginalTermSet.label","المصطلح الاصلى"},
{"eMR.RejectDRG.label","رفض DRG"},
{"eMR.NewDiagnosis.label","تشخيص جديد"},
{"eMR.NewProcedure.label","إجراء جديد"},
{"eMR.RejectDiagnosis.label","رفض التشخيص"},
{"eMR.RejectProcedure.label","رفض الإجراء"},
{"eMR.EquivalentCode.label","كود مكافئ"},
{"eMR.FreeTextApplicable.label","تطبيق النص"},
{"eMR.ViewClinicalHistory.label","عرض التاريخ المرضى"},
{"eMR.FromSpeciality.label","من تخصص"},
{"eMR.ToSpeciality.label","الى تخصص"},
{"eMR.MaxPrimaryDiagnosisCauseOfDeath.label","أقصى تشخيص أولي لتحديد سبب الوفاة"},
{"eMR.MaxOtherDiseaseCauseOfDeath.label","أقصى تشخيص اخر لتحديد سبب الوفاة"},
{"eMR.SingleStageDeathRegistrationAppl.label","تسجيل الوفاة بمرحلة واحدة"},
{"eMR.ErrorCode.label","كود الخطاء"},
{"eMR.PreviousCode.label","الكود السابق"},
{"eMR.NextCode.label","الكود التالى"},
{"eMR.DiagnosisErrorHistory.label"," أخطاء التشخيص"},
{"eMR.ProcedureErrorHistory.label"," أخطاء الاجراءات"},
{"eMR.completed.label","مكتمل"},
{"eMR.confirmed.label","مؤكد"},
{"eMR.authorized.label","مفوض"},
{"eMR.review.label","مراجعه"},
{"eMR.recoded.label","إعادة تكويد"},
{"eMR.newcode.label","كود جديد"},
{"eMR.supporting.label","دعم"},
{"eMR.principal.label","رئيسي"},
{"eMR.comorbidity.label","الاعتلال المشترك"},
{"eMR.externalcauses.label","أسباب خارجية"},
{"eMR.complication.label","تعقيد"},
{"eMR.others.label","آخرون"},
{"eMR.ViewErrorHistory.label","عرض الاخطاء"},
{"eMR.Recorded.label","مسجل"},
{"eMR.ErrorHistory.label","سجل الاخطاء"},
{"eMR.Recodedby .label","تم التسجيل بواسطة"},
{"eMR.IncludeFreeTextDiagnosis.label","كتابة التشخيص يدويا"},
{"eMR.FreeText.label","نصى"},
{"eMR.PeriodRange.label","مدى الفترة"},
{"eMR.CauseDeathEnteredDLC.label","تم إدخال سبب الوفاة بواسطة ضابط DLC"},
{"eMR.PregnancyDetails.label","تفاصيل الحمل"},
{"eMR.MovedFromGeneralToCauseOfDeath.label","انتقل من القائمة العامة إلى سبب الوفاة"},
{"eMR.MovedFromGeneralListToOther.label","انتقل من قائمة عامة إلى مضاعفات أخرى"},
{"eMR.MovedFromCauseOfDeathToOther.label","انتقل من سبب الوفاة إلى مضاعفات أخرى"},
{"eMR.MovedFromOtherToCauseOfDeath.label","انتقل من مضاعفات أخرى إلى سبب الوفاة"},
{"eMR.MovedFromCauseOfDeathToGeneral.label","انتقل من سبب الوفاة إلى القائمة العامة"},
{"eMR.MovedFromOtherToGeneral.label","انتقل من المضاعفات الأخرى إلى القائمة العامة"},
{"eMR.Modifications.label","التعديلات"},
{"eMR.Modification.label","تعديل"},
{"eMR.Initial.label","مبدئي"},
{"eMR.CreatedUser.label","المستخدم الذى انشاءه"},
{"eMR.SeqNo.label","الرقم التسلسلى"},
{"eMR.ceritifiedpractitioner.label","ممارس معتمد"},
{"eMR.lengthofstay.label","مدة الأقامة"},
{"eMR.otherdiseasecomplication.label","أمراض / مضاعفات أخرى تسببت في الوفاة"},
{"eMR.generaldiaglist.label","قائمة التشخيص العام"},
{"eMR.addnewdiagnosis.label","اضافة تشخيص جديد"},
{"eMR.durationofillness.label","مدة المرض"},
{"eMR.moveto.label","الانتقال إلى"},
{"eMR.notpregnant.label","ليست حاملا"},
{"eMR.deliveredlessthan6weeks.label","سلمت أقل من 6 أسابيع"},
{"eMR.gestationalage.label","عمر الحمل"},
{"eMR.femalepatientstatus.label","حالة المريضة"},
{"eMR.Y.label","Y"},
{"eMR.M.label","M"},
{"eMR.D.label","D"},
{"eMR.headersection.label","قسم"},
{"eMR.viewdeathregister.label","مشاهدة سجل الوفيات"},
{"eMR.dischargeYN.label","خروج (نعم / لا)"},
{"eMR.createddatetime.label","تاريخ ووقت الإنشاء"},
{"eMR.initialprintYN.label","طباعة اولية (نعم / لا)"},
{"eMR.Residential.label","سكني"},
{"eMR.explanatorynotesoverleaf.label","ملاحظات توضيحية على الصفحة"},
{"eMR.NewICNo.label","رقم I / C الجديد:"},
{"eMR.OldICNo.label","رقم I / C القديم:"},
{"eMR.CaseNo.label","رقم الحالة :"},
{"eMR.UsualResidentialAddress.label","عنوان السكن الحالى"},
{"eMR.TUMOUR.label","ورم"},
{"eMR.DiagnosisTopographyanatomicalsite.label","التشخيص: الطبوغرافيا - الموقع التشريحي"},
{"eMR.Morphologyhistologicaldiagnosis.label","مورفولوجيا - التشخيص النسيجي"},
{"eMR.Specifyprimarypossible.label","حدد العضو الأساسي / الموقع الدقيق / الجانب الجانبي إن أمكن"},
{"eMR.TNMClassification.label","تصنيف TNM"},
{"eMR.N.label","N"},
{"eMR.Otherstagingsystemstage.label","نظام التدريج الآخر: المرحلة"},
{"eMR.Stagingsystem.label","نظام التدريج:"},
{"eMR.pleasespecifystagingsystem.label","يرجى تحديد نظام التدريج"},
{"eMR.Basisofdiagnosis.label","أساس التشخيص"},
{"eMR.Clinical.label","مرضي"},
{"eMR.BiochemImmunology.label","الكيمياء الحيوية / علم المناعة"},
{"eMR.Histologyofprimary.label","لأنسجة الابتدائية"},
{"eMR.ClinicalinvestigationUltrasound.label","الفحص السريري / الموجات فوق الصوتية"},
{"eMR.CytologyHaematology.label","علم الخلايا / أمراض الدم"},
{"eMR.Autopsywithhistory.label","تشريح الجثة"},
{"eMR.Exploratorysurgery.label","الجراحة الاستكشافية"},
{"eMR.Histologyofmetastases.label","علم الأنسجة"},
{"eMR.SOURCEOFINFORMATION.label","مصدر المعلومات (الإخطار)"},
{"eMR.Chemotherapy.label","العلاج الكيميائي"},
{"eMR.Hospital.label","مستشفى "},
{"eMR.Hormonetherapy.label","العلاج بالهرمونات"},
{"eMR.Exploratorysurgery.label","الجراحة الاستكشافية"},
{"eMR.PRESENTSTATUS.label","الوضع الحالي"},
{"eMR.ifdeaddateofdeath.label","إذا مات"},
{"eMR.Notifiedby.label","أخطر من"},
{"eMR.Cancer.label","سرطان"},
{"eMR.NameandDesignationofReporting.label","اسم وتعيين مسؤول التقارير"},
{"eMR.THANKYOUFORYOURCOOPERATION.label","شكرا لتعاونكم"},
{"eMR.Totalnoofvisitson.label","إجمالي عدد الزيارات في"},
{"eMR.TotalnoofEncountersin.label","إجمالي عدد اللقاءات في"},
{"eMR.TotalnoofEncounters.label","إجمالي عدد اللقاءات للمريض:"},
{"eMR.SNO.label","SNO."},
{"eMR.ConfirmationDetails.label","تفاصيل التأكيد"},
{"eMR.DischargeswoDeaths.label","<------ الخروج مع الوفيات ------->"},
{"eMR.NumberofDeaths.label","<--------- عدد الوفيات ---------->"},
{"eMR.Peadiatic.label","اخصائي اطفال"},
{"eMR.Metanity.label","التوليد"},
{"eMR.Spec.label","التخصص"},
{"eMR.Ind.label","مؤشر"},
{"eMR.Desc.label","وصف"},
{"eMR.Diag.label","تشخيص"},
{"eMR.PrefMonth.label","الشهر السابق"},
{"eMR.CTZ.label","CTZ"},
{"eMR.NCTZ.label","NCTZ"},
{"eMR.TurnArndTime.label","الفترة الزمنية"},
{"eMR.PERPD101.label","PER-PD 101"},
{"eMR.Number.label","عدد"},
{"eMR.OTHID.label","OTH رقم"},
{"eMR.Malayesian.label","ماليزي"},
{"eMR.Detailed.label","مفصلة"},
{"eMR.NoofAdmissions.label","عدد حالات الدخول"},
{"eMR.NoofDeaths.label","عدد الوفيات"},
{"eMR.NoofDischarges.label","عدد حالات الخروج"},
{"eMR.ofDeathRate.label","نسبة الوفيات"},
{"eMR.Pind12003.label","[Pind. 1/2003]"},
{"eMR.TabListNo.label","رقم قائمة علامات التبويب"},
{"eMR.CircumHead.label","رئيس المحيط"},
{"eMR.CircumChest.label","محيط الصدر"},
{"eMR.DurnDays.label","المدة بالأيام"},
{"eMR.Radiotherapy.label","العلاج الإشعاعي"},
{"eMR.TotalBirths.label","مجموع المواليد"},
{"eMR.Dead.label","متوفى"},
{"eMR.NonMalaysian.label","غير ماليزي"},
{"eMR.Malaysian.label","ماليزى"},
{"eMR.MR.label","السيد"},
{"eMR.FEMALE_PATIENT_DETAILS.label","تفاصيل المريضة"},
{"eMR.MEDICAL_LEGAL_CASE.label","MLC"},
{"eMR.AUTH_PRACTITIONER.label","ممارس معتمد"},
{"eMR.ATTENDING_PRACTITIONER.label","الممارس المنواب"},
{"eMR.POL_REP_NO.label","تقرير الشرطة رقم"},
{"eMR.POL_STN_ID.label","محطة"},
{"eMR.POL_ID.label","Pol ID"},
{"eMR.BROUGHT_IN_DEAD.label","تم إحضاره متوفيا"},
{"eMR.CAUSE_OF_DEATH_REMARKS.label","ملاحظات"},
{"eMR.ADD_DIAGNOSIS.label","أضف التشخيص"},
{"eMR.MOVED_FROM_GEN_TO_COD.label","تم نقله من القائمة العامة إلى سبب الوفاة"},
{"eMR.MOVED_FROM_GEN_TO_OTH.label","تم النقل من القائمة العامة إلى قائمة أخرى"},
{"eMR.MOVED_FROM_COD_TO_OTH.label","sانتقل من سبب الموت إلى الآخرين"},
{"eMR.MOVED_FROM_OTH_TO_COD.label","انتقل من الآخرين إلى سبب الموت"},
{"eMR.MOVED_FROM_COD_TO_GEN.label","انتقل من قائمة سبب الوفاة إلى قائمة عامة"},
{"eMR.MOVED_FROM_OTH_TO_GEN.label","تم النقل من الآخرين إلى القائمة العامة"},
{"eMR.SEQ_NO.label","تسلسل "},
{"eMR.ONSET_DATE.label","تاريخ البدء"},
{"eMR.PREGNANT.label","حامل"},
{"eMR.NOT_PREGNANT.label","غير حامل"},
{"eMR.DETAILS_UNKNOWN.label","تفاصيل غير معروفة"},
{"eMR.DELIVERED_LESS_THAN_6_WEEKS.label","سلمت أقل من 6 أسابيع"},
{"eMR.GESTATIONAL_PERIOD.label","فترة الحمل"},
{"eMR.MOVED_TO_COD.label","انتقل إلى سبب الوفاة"},
{"eMR.MOVED_TO_OTH.label","انتقل إلى الآخرين"},
{"eMR.MOVED_TO_GEN.label","انتقل إلى القائمة العامة"},
{"eMR.atthetimeofdeath.label","في وقت الوفاة"},
{"eMR.printgroupname.label","طباعة اسم المجموعة في التقرير"},
{"eMR.noofbeds.label","عدد الأسرة"},
{"eMR.level1group.label","مجموعة المستوى 1"},
{"eMR.level2group.label","مجموعة المستوى 2"},
{"eMR.level3group.label","مجموعة المستوى 3"},
{"eMR.tabcode.label","رمز علامة التبويب"},
{"eMR.new_proc_for_recode.label","السماح بإضافة كود الإجراء الجديد في شاشة الإجراء كـ"},
{"eMR.checkindatetime.label","تاريخ / وقت التسجيل"},
{"eMR.checkoutdatetime.label","تاريخ / وقت المغادرة"},
{"eMR.related.label","متعلق ب"},
{"eMR.notrelated.label","غير مرتبط"},
{"eMR.excludeorignalcodes.label","استثناء الرموز الأصلية من اعادة التكويد"},
{"eMR.independent.label","مستقل"},
{"eMR.linked.label","مرتبط"},
{"eMR.unlinked.label","غير مرتبط"},
{"eMR.Excludecodes.label","استبعاد الكود "},
{"eMR.viewexcludedcodes.label","عرض الاكواد المستبعدة"},
{"eMR.Excluded.label","مستبعد"},
{"eMR.showerrorcodesbypractitioner.label","إظهار رموز خطأ علامة الممارس"},
{"eMR.errorcodemarkedbypractitioner.label","رموز الخطأ التي تم وضع علامة عليها من قبل الممارس"},
{"eMR.PHGeneric.label","عام PH"},
{"eMR.NotifyDiseases.label","الأمراض الواجب الإبلاغ عنها"},
{"eMR.NotifyDiseasesCode.label","قانون الأمراض الواجب الإبلاغ عنها"},
{"eMR.NotifyDiseasesDesc.label","وصف الأمراض الواجب التبليغ عنها"},
{"eMR.TEST_CODE.label","كود الاختبار"},
{"eMR.TEST_DES.label","وصف الاختبار"},
{"eMR.DateReang.label","مدى التاريخ"},
{"eMR.MaxDateforNotifyDis.label","الحد الأقصى للنطاق الزمني لتقرير اختبار مختبر الأمراض الواجب الإبلاغ عنها"},
{"eMR.NotifyDisLabTestReportDateRange.label","نطاق تاريخ تقرير اختبار الأمراض الواجب الإبلاغ عنها"},
{"eMR.ASAScorecode.label","رمز نقاط Asa"},
{"eMR.PreOpreative.label","قبل الجراحة"},
{"eMR.PreOpreativedesc.label","قبل الجراحة"},
{"eMR.DiagnosisSelectionSearch.label","علامة التبويب الافتراضية في تحديد التشخيص"},
{"eMR.CustomList.label","قائمة مخصصة"},
{"eMR.DiagnosisClassificationMandatory.label","تصنيف التشخيص إلزامي"},
{"eMR.PrincipleDiagnosisnotrecorded.label","لم يتم تسجيل مبدأ التشخيص"},
{"eMR.DiagnosisEncounterLevel.label","التشخيص على مستوى الزيارة"},
{"eMR.DefaultPrincipalDiagClassification.label","تصنيف التشخيص الرئيسي الافتراضي"},
{"eMR.AllergyConfirmation.label","تأكيد الحساسية"},
{"eMR.PatientDrugAllergy.label","هل يعاني المريض من حساسية جديدة؟"},
{"eMR.AllergyConfirmationRequired.label","مطلوب تأكيد الحساسية"},
{"eMR.Notifiable.label","قابل للإبلاغ"},
{"eMR.Injury.label","إصابة"},
{"eMR.UpdateInjDtls.label","تحديث تفاصيل الإصابة"},
{"eMR.PasswordValidationforWitness.label","التحقق من صحة كلمة المرور للشاهد في تسجيل الأشياء الثمينة للمريض"},
{"eMR.DiagnosisSearchByLongDescription.label","تشخيص البحث بالوصف الطويل"},
{"eMR.WorkRelatedFormMandatory.label","نموذج متعلق بالعمل إلزامي"},
{"eMR.WorkRelatedFormNotRecorded.label","لم يتم تسجيل النموذج المرتبط بالعمل"},
{"eMR.NotifyReport.label","أبلغ عن التقرير"},
{"eMR.WorkRelatedReport.label","تقرير متعلق بالعمل"},
{"eMR.IncludeBBA.label","تضمين حالات BBA"},
{"eMR.WorkRelated.label","العمل ذات الصلة"},
{"eMR.CheckList.label","قائمة تدقيق"},
{"eMR.CheckListDetails.label","تحقق من تفاصيل القائمة"},
{"eMR.ConsentFromPatientNextofKin.label","موافقة المريض / أقرب الأقارب"},
{"eMR.CopyofIdentificationDocumentofRequestor.label","نسخة من وثيقة الهوية لمقدم الطلب"},
{"eMR.MaritalCertificateofSpouse.label","شهادة الزواج للزوج"},
{"eMR.StatutoryDeclaration.label","تصريح قانوني"},
{"eMR.ConsentFromEmbassy.label","موافقة من السفارة"},
{"eMR.PaymentAutolinkFromBilling.label","الدفع (الربط التلقائي من الفواتير)"},
{"eMR.AcknowledgedByHODCoordinator.label","تم الإقرار بها من قبل رئيس القسم / المنسق"},
{"eMR.InformToPractitioner.label","إبلاغ الممارس"},
{"eMR.ForwardToPractitioner.label","إلى الممارس"},
{"eMR.Delayed.Label","تأخير"},
{"eMR.NotKnown.label","غير معروف"},
{"eMR.noofficalbeds.label","رقم السرير الرسمي."},
{"eMR.noofopertnalbeds.label","رقم السرير التشغيلي"},
{"eMR.MaxDaysForReportCompletion.label","الحد الأقصى لعدد الأيام لإكمال التقرير"},
{"eMR.PMBCode.label","كود PMB"},
{"eMR.PMBCodeDescription.label","وصف PMB"},
{"eMR.TreatmentDesc.label","وصف العلاج"},
{"eMR.SupportingCode.label","كود الدعم"},
{"eMR.Top10PMBICDCodes.label","أعلى 10 رموز PMB ICD"},
{"eMR.PMBCodes.label","كود PMB"},
{"eMR.IncompleteICDCodes.label","رموز ICD غير مكتملة"},
{"eMR.IncorrectICDCodes.label","رموز ICD غير صحيحة"},
{"eMR.ThisisPMB.label","هذا الكود هو PMB"},
{"eMR.ThisisnotPMB.label","هذا الرمز ليس PMB"},
{"eMR.ICD10CODE.label","كود ICD10"},
{"eMR.AdmVisitMonth.label","شهر الدخول / الزيارة"},
{"eMR.Chapter.label","الفصل"},
{"eMR.TopMorbidity.label","أعلى رموز المرض"},
{"eMR.TopMortality.label","أعلى رموز الوفيات"},
{"eMR.ReportCategory.label","فئة التقرير"},
{"eMR.MedicalReqAuth.label","تصريح طلب طبي ساري المفعول حتى"},
{"eMR.TypesofNotificationFormMandatory.label","أنواع نموذج الإخطار إلزامي"},
{"eMR.TypesofNotificationReport.label","أنواع تقرير الإخطار"},
{"eMR.TypesofNotification.label","أنواع الإخطار"},
{"eMR.TypesofNotificationFormNotRecorded.label","أنواع نموذج الإخطار غير المسجلة"},
{"eMR.IncompleteReqCancellation.label","الحد الأقصى لعدد الأيام لإلغاء الطلبات غير المكتملة"},
{"eMR.AutoCancelIncompReq.label","الإلغاء التلقائي للطلبات غير المكتملة"},
{"eMR.TotalIncompReqForAutoCancel.label","إجمالي الطلبات غير المكتملة للإلغاء التلقائي"},
{"eMR.MRBatchProcess.label","عملية دفع MR"},
{"eMR.PendingAssgnPract.label","في انتظار التخصيص للممارس"},
{"eMR.CancelRequestbymrd.label","طلب ملغى"},
{"eMR.AutoCancelRequest.label","طلب تم إلغاؤه تلقائيًا"},
{"eMR.RejectedBy.label","مرفوض من طرف"},
{"eMR.RejectedOn.label","رفض في"},
{"eMR.SignForMedReport.label","التوقيع على التقرير الطبي"},
{"eMR.HeaderForMedReport.label","العنوان للتقرير الطبي"},
{"eMR.ReceivedAtMRD.label","تم الاستلام في MRD"},
{"eMR.SelfPrepare.label","الاستعداد الذاتي"},
{"eMR.SelectAcceptReject.label","لا يمكن المتابعة مع مستخدم تسجيل الدخول"},
{"eMR.OverduebyPractitioner.label","تأخرت من قبل الممارس"},
{"eMR.LessThanOrEqual.label","<="},
{"eMR.DueDays.label","أيام الاستحقاق"},
{"eMR.CheckLists.label","قائمة تدقيق"},
{"eMR.CheckListName.label","اسم قائمة التحقق"},
{"eMR.DeliveryDispatchAdd.label","التسليم / الإرسال إضافة"},
{"eMR.DiagnosisRemarks.label","ملاحظات التشخيص"},
{"eMR.Coded.label","مشفرة"},
{"eMR.Disposal.label","تصرف"},
{"eMR.Archival.label","أرشيف"},
{"eMR.DisposalApproval.label","الموافقة على التصرف"},
{"eMR.DisposedDate.label","تاريخ التخلص"},
{"eMR.InactiveDate.label","تاريخ غير نشط"},
{"eMR.AllowMultiDesc.label","السماح بالوصف المتعدد"},
{"eMR.DoctorDesc.label","وصف الطبيب"},
{"eMR.ForwardedtoHOD_Coordinator.label","يتم إرسالها إلى HOD / منسق / ممارس طلب"},
{"eMR.MedicalRecordTask.label","مهمة السجل الطبي"},
{"eMR.HODCoordinatorTask.label","مهمة HOD / منسق"},
{"eMR.MRDRemarks.label","ملاحظات MRD"},
{"eMR.AcceptedbyHOD.label","تم قبول الطلب من قبل رئيس القسم / المنسق"},
{"eMR.RejectedbyHOD.label","طلب مرفوض من قبل رئيس القسم / المنسق"},
{"eMR.AssignReAssignPractitioner.label","تعيين / إعادة تعيين ممارس"},
{"eMR.PractitionerAssignedDate.label","التاريخ / الوقت المعين للممارس"},
{"eMR.HODCoordinatorRemarks.label","ملاحظات رئيس القسم / المنسق"},
{"eMR.AcceptedbyPractitioner.label","مقبول من قبل الممارس"},
{"eMR.RejectedbyPractitionertoMRD.label","رفض الممارس لـ MRD"},
{"eMR.RejectedbyPractitionertoHOD.label","عاد إلى HOD / المنسق بواسطة الممارس"},
{"eMR.DeliveryMode.label","وضع التوصيل"},
{"eMR.PostageNo.label","رقم البريد"},
{"eMR.DeliveryPostageAddress.label","عنوان بريد التسليم"},
{"eMR.SubmitMedicalReport.label","إرسال تقرير طبي"},
{"eMR.SaveAsDraft.label","حفظ كمسودة"},
{"eMR.Returnedbypractitioner.label","عاد من قبل ممارس"},
{"eMR.Rejectedbypractitioner.label","رفضه الممارس"},
{"eMR.ReasonforReturn.label","سبب الإرجاع"},
{"eMR.AutoCancelApplication.label","تطبيق مُلغى تلقائيًا"},
{"eMR.KlinikKhas.label","عيادة خاصة (كلينيك خاص)"},
{"eMR.PAC.label","مركز تقويم الحمل"},
{"eMR.OurReferenceNo.label","المرجع"},
{"eMR.ApplicableForMR.label","ينطبق على التقرير الطبي"},
{"eMR.CompletedApplication.label","التطبيق المكتمل"},
{"eMR.RequestOrReportStatus.label","حالة الطلب / التقرير"},
{"eMR.CancelledOrRejectedStatus.label","التفاصيل الملغاة / المرفوضة"},
{"eMR.CancelledApplication.label","التطبيق الملغى"},
{"eMR.PractitionerTask.label","مهمة ممارس"},
{"eMR.ModificationRequired.label","التعديل مطلوب"},
{"eMR.PractitionerRemarks.label","ملاحظات الممارس"},
{"eMR.MedicalReportCancelled.label","تم إلغاء التقرير الطبي"},
{"eMR.MedicalReportAutoCancelled.label","تم إلغاء التقرير الطبي تلقائيًا"},
{"eMR.ExtGenLinkLookup.label","حث عن ارتباط عام خارجي"},
{"eMR.ReportDeliveredByMR.label","تقرير تسليم بواسطة السجل الطبي"},
{"eMR.Counter.label","يعداد"},
{"eMR.Post.label","بريد"},
{"eMR.DeliveryDetails.label","تفاصيل التسليم"},
{"eMR.DeliveryRemarks.label","ملاحظات التسليم"},
{"eMR.ApprovalDisposalNo.label","الموافقة على التصرف لا"},
{"eMR.ApprovalDate.label","تاريخ الموافقة"},
{"eMR.ReportCompletionDate.label","تاريخ اكتمال التقرير"},
{"eMR.RH101PatientCategory.label","فئة RH-101-المريض"},
{"eMR.POA.label","POA"},
{"eMR.POAIndicator.label","مؤشر POA"},
{"eMR.ToBeReported.label","سيتم الابلاغ عنها"},
{"eMR.MRN.label","MRN"},
{"eMR.TreatingPractitioner.label","ممارس علاج"},
{"eMR.LicenseNo.label","رقم الرخصة"},
{"eMR.SpecialClinic.label","عيادة خاصة"},
{"eMR.DelAttndBy.label","حضر الولادة"},
{"eMR.JanToJune.label","يناير حتى يونيو"},
{"eMR.JulyToDesc.label","يوليو حتى ديسمبر"},
{"eMR.DiagnosisCategory.label","فئة التشخيص"},
{"eMR.ChronicDiagnosis.label","التشخيص المزمن"}, //added by Himanshu Saxena for MOHE-CRF-0135 on 13-04-2023 
{"eMR.Governate.label","محافظة"} ,                //added by Himanshu Saxena for MOHE-CRF-0135 on 13-04-2023
{"eMR.MaxNofdaysforBHTSubmission.label","الحد الأقصى لعدد الأيام لتقديم BHT"},
/*Added By Santhosh against ML-MMOH-CRF-1959 Start*/
{"eMR.DischargePeriodFrom.label","فترة التفريغ من"},
{"eMR.DischargePeriodTo.label","فترة التفريغ ل"},
{"eMR.BHTStatus.label","حالة BHT"},
{"eMR.PENDING.label","قيد الانتظار"},
{"eMR.OVERDUE.label","متأخر"},
{"eMR.DELIVERED.label","تم التوصيل"},
{"eMR.RECEIVED.label","تلقى"},
{"eMR.RETURNED.label","عاد"},
{"eMR.EnterRemarks.label","أدخل الملاحظات"},
{"eMR.DiagnosisDetails.label","تفاصيل التشخيص"}
/*END*/ 
	};
}