/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eXH.resources;

import java.util.*;

public class  Labels_th  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    } 

	static final Object[][] contents = {
{"eXH.AbouttoSplit.Label","About to Split"},
{"eXH.AbouttoStop.Label","About to Stop"},
{"eXH.Abouttoprocess.Label","About to process"},
{"eXH.AccessionNumber.Label","Accession Number"},
{"eXH.Acknowledged.Label","Acknowledged"},
{"eXH.AckDir.Label","Acknowlege Directory"},
{"eXH.AcknowlegementType.Label","Acknowlegement Type"},  
{"eXH.AddedDate.Label","Added Date"},
{"eXH.AddedID.Label","Added ID"},
{"eXH.AddedWSNo.Label","Added WS No"},
{"eXH.Always.Label","Always"},
{"eXH.APIBased.Label","API Based"},
{"eXH.APICode.Label","API Code"},
{"eXH.APIType.Label","API Type"},
{"eXH.ApplicationCrossReference.Label","Application Cross Reference"},
{"eXH.ApplicationMessage.Label","Application Message"},
{"eXH.ApplicationKey.Label","Application Key"},
{"eXH.ApplicationID.Label","Application ID"},
{"eXH.ApplicationName.Label","Application Name"},
{"eXH.CtrlElementId.Label","Control Element ID"},
{"eXH.ExpectedValue.Label","Expected Value"},
{"eXH.ExpectedValue1.Label","Expected Value 1"},
{"eXH.ExpectedValue2.Label","Expected Value 2"},
{"eXH.ApplicationwiseSegments.Label","Application wise Segments"},
{"eXH.ArgSerialNo.Label","Argument Serial Number"},
{"eXH.ArgID.Label","Argument ID"},
{"eXH.ArgName.Label","Argument Name"},
{"eXH.ASCIIFile.Label","ASCII File"},
{"eXH.AutomaticRestartType.Label","Automatic Restart Type"},
{"eXH.AutomaticRestartTime.Label","Automatic Restart Time[hh:mm]"},
{"eXH.Audit.Label","Audit"},
{"eXH.ByLocation.Label","By Location"},
{"eXH.BYPatientType.Label","By PatientType"},
{"eXH.BYCategory.Label","By Category"},
{"eXH.BySubLocation.Label","By SubLocation"},
{"eXH.ByType.Label","By Type"},
{"eXH.Client.Label","Client"},
{"eXH.ClientId.Label","Client Id"},
{"eXH.CommunicationClient.Label","Communication Client"},
{"eXH.CommunicationErrors.Label","Communication Exceptions"},
{"eXH.CommunicationProcesSettings.Label","Communication Process Settings"},
{"eXH.CommunicationSettings.Label","Communication Settings"},
{"eXH.CommunicationMode.Label","Communication Mode"},
{"eXH.CommDataIOAPI.Label","Comm Data I/O API"},
{"eXH.CommStatisticsAPI.Label","Comm Statistics API"},
{"eXH.CommType.Label","Comm Type"},
{"eXH.CommunicationType.Label","Communication Type"},
{"eXH.CondForInsertUpdt.Label","Condition For Insert Update"},
{"eXH.CondExpr.Label","Condition/Expression"},
{"eXH.ConfigType.Label","Config Type"},
{"eXH.ConfigName.Label","Config Name"},
{"eXH.ControlStructure.Label","Control Structure"},
{"eXH.CrossReference.Label","Cross Reference"},
{"eXH.CrossReferenceCode.Label","Cross Reference Code"},
{"eXH.CrossReferenceDesc.Label","Cross Reference Desc"},
{"eXH.Data.Label","Data"},
{"eXH.ProcessDate.Label","Process Date"},
{"eXH.IF.Label","IF"},
{"eXH.IF.Label","IF"},
{"eXH.AE.Label","AE"},
{"eXH.LTRIM.Label","LTRIM"},
{"eXH.RTRIM.Label","RTRIM"},
{"eXH.TRIM.Label","TRIM"},
{"eXH.SUBSTR.Label","SUBSTR"},
{"eXH.REPLACE.Label","REPLACE"},
{"eXH.Between.Label","Between"},
{"eXH.NotBetween.Label","Not Between"},
{"eXH.IN.Label","IN"},
{"eXH.NotIN.Label","Not In"},
{"eXH.Like.Label","Like"},
{"eXH.NotLike.Label","Not Like"},
{"eXH.Prefix.Label","Prefix"},
{"eXH.Suffix.Label","Suffix"},
{"eXH.PreSuffix.Label","PreSuffix"},
{"eXH.UserDefinedFormat.Label","User Defined Format"},
{"eXH.<>.Label","<>"},
{"eXH.=.Label","="},
{"eXH.<.Label","<"},
{"eXH.>.Label",">"},
{"eXH.<=.Label","<="},
{"eXH.>=.Label",">="},
{"eXH.ISNULL.Label","IS NULL"},
{"eXH.ISNOTNULL.Label","IS NOT NULL"},
{"eXH.Position.Label","Position"},
{"eXH.DataInterval.Label","Data Creation Interval[hh:mm]"},
{"eXH.DataSourceType.Label","Data Source Type"},
{"eXH.DateNumber.Label","Date Number"},
{"eXH.DBConnectString.Label","Database Details"},
{"eXH.DBConnectString1.Label","Database PortNumber"},
{"eXH.DBConnectString2.Label","Database TnsName"},
{"eXH.DBCONNSTRING.Label","Database Connection String"},
{"eXH.DBDRIVER.Label","Database Driver"},
{"eXH.Debug.Label","Debug"},
{"eXH.Debugging.Label","Debugging"},
{"eXH.DebugLog.Label","Debug Log"},
{"eXH.DefaultVal.Label","Default Value"},
{"eXH.Defered.Label","Defered"},
{"eXH.DerivationType.Label","Derivation Type"},
{"eXH.Edit.Label","Edit"},
{"eXH.EnableInterface.Label","Enable Interface"},
{"eXH.EnableEventFiltering.Label","Enable Event Filtering"},
{"eXH.Elements.Label","Elements"},
{"eXH.ElementCode.Label","Element Code"},
{"eXH.ElementDesc.Label","Element Description"},
{"eXH.ElementPos.Label","Element Position"},
{"eXH.ElementSEQ.Label","Element Sequence"},
{"eXH.ElementType.Label","Element Type"},
{"eXH.ElementVal.Label","Element Value"},
{"eXH.ErrorReject.Label","Error/Reject"},
{"eXH.EventwiseSegments.Label","Event wise Segments"},
{"eXH.EventID.Label","Event ID"},
{"eXH.EventName.Label","Event Name"},
{"eXH.ExecOrder.Label","Execution Order"},
{"eXH.ExecId.Label","Segment Id"},
{"eXH.ExecNature.Label","Execution Nature"},
{"eXH.ExpectedValue.Label","Expected Value"},
{"eXH.ExternalAccessionNumber.Label","Ext.Accession Number"},
{"eXH.FailedProcedure.Label","Failed Procedure"},
{"eXH.Fax.Label","Fax"},
{"eXH.FaxSettings.Label","Fax Settings"},
{"eXH.FieldSeparator.Label","Field Separator"},
{"eXH.File.Label","File"},
{"eXH.FileDirectory.Label","File Directory"},
{"eXH.FileFormat.Label","File Format"},
{"eXH.FileInterval.Label","File Creation Interval[hh:mm]"},
{"eXH.FileNamingAPI.Label","File Naming API"},
{"eXH.FileNamingConvention.Label","FileNamingConvention"},
{"eXH.FileSettings.Label","File Settings"},
{"eXH.FileType.Label","File Type"},
{"eXH.Filtering.Label","Filtering"},
{"eXH.FilterRules.Label","Filter Rules"},
{"eXH.FilterRuleType.Label","Filter Rule Type"},
{"eXH.FilterType.Label","Filter Type"},
{"eXH.FilterSubType.Label","Filter Sub Type"},
{"eXH.FilterSub1Type.Label","Filter Sub1 Type"},
{"eXH.FilterSub2Type.Label","Filter Sub2 Type"},
{"eXH.FormatType.Label","Format Type"},
{"eXH.FromSleepTime.Label","From Sleep Time "},
{"eXH.GeneralOrderMessaging.Label","General Order Messaging"},
{"eXH.HL7.Label","HL7"},
{"eXH.HL7Version.Label","HL7 Version"},
{"eXH.HL7Interface.Label","HL7 Interface"},
{"eXH.IBAeHis.Label","eHIS"},
{"eXH.IdleTime.Label","Idle Time[min]"},
{"eXH.Immediate.Label","Immediate"},
{"eXH.InsertingStatement.Label","Inserting Statement"},
{"eXH.Interfaced.Label","Interfaced"},
{"eXH.InterfacedApplications.Label","Interfaced Applications"},
{"eXH.Inbound.Label","Inbound"},
{"eXH.InboundAPI.Label","Inbound API"},
{"eXH.InboundSettings.Label","Inbound Settings"},
{"eXH.InboundDirectory.Label","Inbound Directory Name"},
{"eXH.InputAPI.Label","Input API"},
{"eXH.InsertQuery.Label","Insert Query"},
{"eXH.InUse.Label","In Use"},
{"eXH.IPAddress.Label","IPAddress"},
{"eXH.JobQueue.Label","Job-Queue"},
{"eXH.LastCommnTime.Label","Last Commn Time"},
{"eXH.LastOutboundRetries.Label","Last Outbound Retries"},
{"eXH.LastMessageID.Label","Last Message ID"},
{"eXH.Log.Label","Log"},
{"eXH.Loaded.Label","Loaded"},
{"eXH.LoginName.Label","Login Name"},
{"eXH.MailSettings.Label","Mail Settings"},
{"eXH.MasterFileNotification.Label","Master File Notification"},
{"eXH.MaximumRetries.Label","Maximum Re-tries"},
{"eXH.ibaehisCode.Label","eHIS Code"},
{"eXH.MEDICOMDesc.Label","IBAEHIS Desc"},
{"eXH.MergedPatientID.Label","Merged PatID"},
{"eXH.MessageAmended.Label","Message Amended"},
{"eXH.MessageReplayed.Label","Message Replayed"},
{"eXH.MessageHeaderSegmentSettings.Label","Message Header Segment Settings"},
{"eXH.MessageID.Label","Message ID"},
{"eXH.MessageNumber.Label","Message Number"},
{"eXH.MessageStatus.Label","Message Status"},
{"eXH.MessageTriggerEvent.Label","Message Trigger Event"},
{"eXH.MessageTriggerTime.Label","Message Trigger"},
{"eXH.MessageTypes.Label","Messages"},
{"eXH.ModifiedID.Label","Modified ID"},
{"eXH.ModifiedDate.Label","Modified Date"},
{"eXH.ModifiedWSNo.Label","Modified WS No"},
{"eXH.ModuleId.Label","Module Id"},
{"eXH.Module.Label","Module"},
{"eXH.Move.Label","Move"},
{"eXH.NextProcessDateTime.Label","Next Process Date"},
{"eXH.Never.Label","Never"},
{"eXH.NoAction.Label","No Action"},
{"eXH.NoteRequiredReason.Label","Not Req.Reason"},
{"eXH.NonTableValues.Label","Non Table Values"},
{"eXH.ObservationReporting.Label","Observation Reporting"},
{"eXH.ODBC.Label","ODBC"},
{"eXH.ODBCSettings.Label","ODBCSettings"},
{"eXH.OracleTable.Label","OracleTable"},
{"eXH.OracleTableQuery.Label","Oracle Table Query"},
{"eXH.OracleTableInsertQuery.Label","OracleTableInsertQuery"},
{"eXH.OracleTableSettings.Label","OracleTableSettings"},
{"eXH.OnOrder.Label","On Order"},
{"eXH.OnPatientArrival.Label","On Order Registration"},
{"eXH.OperatedBy.Label","Operated By"},
{"eXH.OperatedDate.Label","Operated Date"},
{"eXH.OtherInterface.Label","Other Interface"},
{"eXH.Outbound.Label","Outbound"},
{"eXH.OutboundSettings.Label","Outbound Settings"},
{"eXH.OutboundDirectoryName.Label","Outbound Directory Name"},
{"eXH.PatientAllergy.Label","Patient Allergy Information Segment"},
{"eXH.Permanentpurgeinterval.Label","Permanent Purge Interval [days]"},
{"eXH.Port.Label","Port#(Typical 1025-5000)"},
{"eXH.PortNumber.Label","Port Number"},
{"eXH.Prev.Label","Prev"},
{"eXH.ProcedureParameters.Label","Procedure Parameters"},
{"eXH.Processed.Label","Processed"},
{"eXH.ProcessingID.Label","Processing ID"},
{"eXH.ProcessBy.Label","Processed By"},
{"eXH.ProcessEndTime.Label","Process End Time"},
{"eXH.ProcessStartTime.Label","Process Start Time"},
{"eXH.ProcedureName.Label","Procedure Name"},
{"eXH.Production.Label","Production"},
{"eXH.ProtocolLinkId.Label","Protocol Link Id"},
{"eXH.ProtocolLinkName.Label","Protocol Link Name"},
{"eXH.ProtocolType.Label","Type"},
{"eXH.QueryBased.Label","Query Based"},
{"eXH.QueryDate.Label","Query Date"},
{"eXH.QueryID.Label","Query ID"},
{"eXH.QueryStatus.Label","Query Status"},
{"eXH.QueryText.Label","Query Text"},
{"eXH.Referal.Label","Referal"},
{"eXH.Rebuild.Label","Rebuild"},
{"eXH.Recently.Label","Recently Enabled Elements"},
{"eXH.Replay.Label","Replay"},
{"eXH.Restricted.Label","Restricted"},
{"eXH.Retries.Label","Retries"},
{"eXH.RetryInterval.Label","Re-try Interval(sec)"},
{"eXH.Row.Label","Row"},
{"eXH.Scheduling.Label","Scheduling"},
{"eXH.Segments.Label","Segments"},
{"eXH.SegmentID.Label","Segment ID"},
{"eXH.SegmentName.Label","Segment Name"},
{"eXH.SegmentType.Label","Segment Type"},
{"eXH.SetupMasterCodeMapping.Label","Setup Master Code Mapping"},
{"eXH.ServerError.Label","Server Exceptions"},
{"eXH.Standardcode.Label","Standard Code"},
{"eXH.StandardType.Label","Standard Type"},
{"eXH.Statement.Label","Statement"},
{"eXH.SysDefStr.Label","System Defined Structure"},
{"eXH.MsgStart.Label","Message Start"},
{"eXH.MsgEnd.Label","Message End"},
{"eXH.PABX.Label","PABX"},
{"eXH.SegStart.Label","Segment Start"},
{"eXH.SegEnd.Label","Segment End"},
{"eXH.FldSeparator.Label","Field Separator"},
{"eXH.ElmntSeparator.Label","Element Separator"},
{"eXH.StartedbyID.Label","Started by ID"},
{"eXH.StopAtCondFailure.Label","Stop At Condition Failure"},
{"eXH.StopDateTime.Label","Stop Date"},
{"eXH.StoppedbyID.Label","Stopped by ID"},
{"eXH.StatusText.Label","Status Remarks"},
{"eXH.String.Label","String"},
{"eXH.SubElement.Label","Sub Element"},
{"eXH.SubElementType.Label","Sub Element Type"},
{"eXH.Sub1Element.Label","Sub1 Element"},
{"eXH.Sub1ElementType.Label","Sub1 Element Type"},
{"eXH.Sub2Element.Label","Sub2 Element"},
{"eXH.Sub2ElementType.Label","Sub2 Element Type"},
{"eXH.Sucessfull.Label","Successful"},
{"eXH.TableValues.Label","Table Values"},
{"eXH.TCPIP.Label","TCP/IP"},
{"eXH.TCPIPSettings.Label","TCP/IP Settings"},
{"eXH.TCPIPAddress.Label", "TCP/IP Address"},
{"eXH.Temporarypurgeinterval.Label","Temporary Purge Interval [days]"},
{"eXH.Timed.Label","Timed"},
{"eXH.ToSleepTime.Label","To Sleep Time"},
{"eXH.TotalMessages.Label","Total Messages"},
{"eXH.TransferFailed.Label","Transfer Failed"},
{"eXH.TransferSuccessful.Label","Transfer Successful"},
{"eXH.Triggers.Label","Triggers"},
{"eXH.TriggeringCondition.Label","Triggering Condition"},
{"eXH.TriggerEvent.Label","Trigger Event"},
{"eXH.TriggerName.Label","Trigger Name"},
{"eXH.TriggerType.Label","Trigger Type"},
{"eXH.TriggeringTable.Label","Triggering Table"},
{"eXH.Unprocessed.Label","Unprocessed"},
{"eXH.Unrestricted.Label","Un-restricted"},
{"eXH.UpdateQuery.Label","Update Query"},
{"eXH.ViewEvents.Label","View Events"},
{"eXH.ViewPurgeEvents.Label","View Purge Events"},
{"eXH.ViewEpabxEvents.Label","View EPABX Events"},
{"eXH.ViewMessage.Label","View Message"},
{"eXH.ViewDebugLogInformation.Label","View Debug Log Information"},
{"eXH.ViewCommunicationProcessErrors.Label","View Communication Process Errors"},
{"eXH.ViewMessagesAuditLog.Label","View Messages Audit Log"},
{"eXH.ViewServerProcessErrors.Label","View Server Process Errors"},
{"eXH.SolicitedYN.Label","SolicitedYN"},
{"eXH.ProtocolLink.Label","Protocol Link"},
{"eXH.AccessionNumber.Label","Accession Number"},
{"eXH.CommMode.Label","Communication Mode"},
{"eXH.SubDomain.Label","Sub Domain"},
{"eXH.ExtAccNo.Label","External Acc No"},
{"eXH.PurgeStatus.Label","Purge Status"},
{"eXH.ModifiedFacilityID.Label","Modified Facility"},
{"eXH.AddedFacility.Label","Added Facility ID"},
{"eXH.ModifiedBy.Label","Modified By"},
{"eXH.AddedBy.Label","Added By"},
{"eXH.SuccessfullyProcessed.Label","Successfully Processed"},
{"eXH.TransmissionComplete.Label","Transmission Complete"},
{"eXH.SuccessfullyLoaded.Label","Successfully Loaded"},
{"eXH.MessageDesc.Label","Message Desc"},
{"eXH.ADD.Label","ADD"},
{"eXH.Profile.Label","Profile"},
{"eXH.Short Description.Label","Short Description"},
{"eXH.Long Description.Label","Long Description"},
{"eXH.Version Specific.Label","Version Specific"},
{"eXH.Geography specific.Label","Geography specific"},
{"eXH.Site specific.Label","Site specific"},
{"eXH.Application specific.Label","Application specific"},
{"eXH.TransactionLayer.Label","Transaction Layer"},
{"eXH.Profile.Label","Profile"},
{"eXH.ProfileId.Label","ProfileID"},
{"eXH.Short Description.Label","Short Description"},
{"eXH.Long Description.Label","Long Description"},
{"eXH.Version Specific.Label","Version Specific"},
{"eXH.Geography specific.Label","Geography specific"},
{"eXH.Site specific.Label","Site specific"},
{"eXH.Application specific.Label","Application specific"},
{"eXH.LevelNumber.Label","Level Number"},
{"eXH.FilterTypedesc.Label","Filter Type Desc"} ,
{"eXH.FilterTypeQuery.Label","Filter Type Query" },
{"eXH.FilterSubDesc.Label","Filter Sub Desc"},
{"eXH.FiltersubTypeQuery.Label","Filtersub Type Query"},
{"eXH.ElementQuery.Label","Element Query"},
{"eXH.GroupwiseFilterLevel.label","Group wise Filter Level"},
{"eXH.Group.label","Group"},
{"eXH.FilterType.Label","Filter Type"},
{"eXH.FilterSubType.Label","Filter Sub Type"},
{"eXH.TRANS.Label","Trans"},
{"eXH.FL.Label","FL"},
{"eXH.GL.Label","GL"},
{"eXH.InterfaceDomain.Label","Interface Domain"},
{"eXH.Solicited.Label","Solicited"},
{"eXH.Repetition_Appl.Label","Repetition Applicable"},
{"eXH.MessageControl.Label","Message Control"},
{"eXH.FileCtrlType.Label","File Control Type"},
{"eXH.FileHeader.Label","File Header"},
{"eXH.FileFooter.Label","File Footer"},
{"eXH.TableBased.Label","Table Based"},
{"eXH.API.Label","API"},
{"eXH.SubAPI.Label","Sub API"},
{"eXH.OutboundLog.Label","Outbound Log"},
{"eXH.InboundLog.Label","Inbound Log"},
{"eXH.Protocol.Label","Gateway"},
{"eXH.DataGroup.Label","Data Group"},
{"eXH.AddDetails.Label","Add Details"},
{"eXH.NewFacility.Label","New Facility"},
{"eXH.SelectFromSM_PARAM.Label","Select From SM_PARAM"},
{"eXH.Segment.Label","Segment"},
{"eXH.RS232.Label","RS232"},
{"eXH.SMS.Label","SMS"},
{"eXH.FoxPro.Label","FoxPro Dbf"},
{"eXH.XML.Label","XML"},
{"eXH.MDB.Label","MDB"},
{"eXH.Communicated.Label","Communicated"},
{"eXH.NonCommunicated.Label","Non-Communicated"},
{"eXH.AddIntDataCriteria.Label","Add Interface Data Criteria"},
{"eXH.QueryOption.Label","Query Option"},
{"eXH.QueryProcessed.Label","Query Processed"},
{"eXH.QueryInitiated.Label","Query Initiated"},
{"eXH.TransmissionError.Label","Transmission Error"},
{"eXH.Validate.Label","Validate"},
{"eXH.TotalLevels.Label","Total Levels"},
{"eXH.DerivationLayer.Label","Derivation Layer"},
{"eXH.EncodingLayer.Label","Encoding Layer"},
{"eXH.RearrangementLayer.Label","Rearrangement Layer"},
{"eXH.StandardLayer.Label","Standard Layer"},
{"eXH.EncodDecodeAlg.Label","ENCOD_DECOD_ALGORITH"},
{"eXH.UserDefStr.Label","User Defined Structure"},
{"eXH.SMPARAM.Label","Select From SM_PARAM"},
{"eXH.Domain.Label","Domain"},
{"eXH.Entity.Label","Entity"},
{"eXH.DataSourceMapping.Label","Data Source Mapping"},
{"eXH.Input.Label","Input"},
{"eXH.QueryError.Label","Query Error"},	
{"eXH.AddField.Label","Add Field"},	
{"eXH.AddWhrClause.Label","Add Where Clause"},
{"eXH.FacilityBased.Label","Facility Based"},
{"eXH.SelectedCols.Label","Selected Columns"},
{"eXH.AllCols.Label","All Columns"},
{"eXH.MasterName.Label","Master Name"},
{"eXH.EncodingAlgorithem.Label","Encoding Algorithm"},
{"eXH.AddProtocolLink.Label","Add Gateway"},
{"eXH.GlobalReferences.Label","Global References"},
{"eXH.DataFieldRef.Label","Data Field Reference"},
{"eXH.Message/QryID.Label","Message / Query Identifier"},
{"eXH.OutboundTrig.Label","Outbound Triggers"},
{"eXH.EventCtrlMapping.Label","Event Control Mapping"},
{"eXH.OutboundEvents.label","Outbound Events"},
{"eXH.InboundEvents.label","Inbound Events"},
{"eXH.SuccessfulCommunication.Label","Successful Communication"},
{"eXH.ResponseAcknowledged.Label","Response Acknowledged"},
{"eXH.ResponseRejected.Label","Response Rejected"},
{"eXH.ProcessingError.Label","Processing Error"},
{"eXH.TransmissionPending.Label","Transmission Pending"},
{"eXH.ProcessingPending.Label","Processing Pending"},
{"eXH.LoadingSuccessful.Label","Processing Pending"},
{"eXH.TransmissionSuccessful.Label","Transmission Successful"},
{"eXH.TransmissionError.Label","Transmission Error"},
{"eXH.ItemClass.Label","Item Class"},
{"eXH.ItemType.Label","Item Type"},
{"eXH.DefaultAttributes.Label","Default Attributes"},
{"eXH.eHISVal.Label","eHIS Value"},
{"eXH.TranslatedVal.Label","Translated Value"},
{"eXH.RepeatSeg.Label","Repeat Segment"},
{"eXH.APISignature.Label","API Signature"},
{"eXH.Interactive.Label","InterActive"},
{"eXH.AckMessageid.Label","ACKMessageid"},
{"eXH.InterActiveInterface.Label","InterActive Interface Events"},
{"eXH.trx_no.Label","Trx_no"},
{"eXH.encounterid.Label","EncounterID"},
{"eXH.Sessionid.Label","Session id"},
{"eXH.Translateentity.Label","Translate Entity"},
{"eXH.ehisentity.Label","eHIS Entity"},
{"eXH.Attributes1.Label","Attributes1"},
{"eXH.Attributes2.Label","Attributes2"},
{"eXH.Translationqry.Label","Translation Query"},
{"eXH.Reload.Label","Reload"},
{"eXH.ValidationLayer.Label","Validation Layer"},
{"eXH.ValidationType.Label","Validation Type"},
{"eXH.dataType.Label","Data Type"},
{"eXH.EncodingAlgorithm.Label","ENCODE/DECODE ALGORITHM"},
{"eXH.entHealthRec.Label","enterprise Health Record"},
{"eXH.cenpatientrec.Label","Centralised Patient  Record "},
{"eXH.SQLSererTab.Label","SQL Serer Table"},
{"eXH.OracleTab.Label","Oracle Table "},
{"eXH.Parent.Label","Parent Field "},
{"eXH.Componentlevel.Label","Component level "},
{"eXH.Ctrl.Label","Control"},
{"eXH.LogDir.Label","Log Directory"},
{"eXH.OfflinePurgeYN.Label","Archive Communicated Messages"},
{"eXH.Precision.Label","Precision"},
{"eXH.LastProcessedDate.Label","Last ProcDate"},
{"eXH.EditQuery.Label","Edit Query"},
{"eXH.Purge.Label","Purge"},
{"eXH.Offline.Label","Offline"},
{"eXH.PGMID.Label","PGM ID"},
{"eXH.Gateway.Label","Gateway"},
{"eXH.MessageViewer.Label","Message Viewer"},
{"eXH.WriteToXls.Label","Write to Excel"},
{"eXH.QueueType.Label","Queue Type"},
{"eXH.OutputType.Label","Output Type"},
{"eXH.*ALL.Label","*All"},
{"eXH.Exceptions.Label","Exceptions"},
{"eXH.PostAPI.Label","PostAPI"},
{"eXH.PostAPISignature.Label","PostAPISignature"},
{"eXH.DesgTmSign.Label","Design Time Signature"},
{"eXH.RunTmSign.Label","Run Time Signature"},
{"eXH.ProcessGroup.Label","Process Group"},
{"eXH.V5-1.Label","5.1"},
{"eXH.replication.Label","Replication"},
{"eXH.ErrorDir.Label","Error Directory"},
{"eXH.ODBCSID.Label","SID"},
{"eXH.DBLink.Label","DB Link"},
{"eXH.replSettings.Label","Replication Settings"},
{"eXH.StatusText.Label","Status Text"},
{"eXH.Online.Label","Online"},
{"eXH.LoadedSuccessfully.Label","Loaded Successfully"},
{"eXH.ErrorInLoading.Label","Error In loading"},
{"eXH.MessageReview.Label","Message Review"},
{"eXH.MsgIDSno.Label","MessageID/Sno"},
{"eXH.EnabledGateway.Label","Enabled Gateway's Log directory"},
{"eXH.NoofPurgeRecords.Label","No.of records to purge/Iteration"},
{"eXH.ActionBy.Label","Action By"},
{"eXH.OldMessageStatus.Label","Old Message Status"},
{"eXH.OldCommDateTime.Label","Old Comm Date/Time"},
// Labels added on Jun 26
{"eXH.Communication.Label","Communication"},
{"eXH.Qrydiplay.Label","Query Display"},
{"eXH.ReviewDisplay.Label","Review Display"},
{"eXH.CommSuccessfully.Label","Communicated Successfully"}, 
{"eXH.ErrorComm.Label","Errors in Communication"},
{"eXH.PendingComm.Label","Pending for Communication"},
{"eXH.FilterGroup.Label","Filter Group"},
{"eXH.UsrdefGroupCode.Label","User Defined Group Code"},
{"eXH.SysdefGroupCode.Label","System Defined Group Code"},
{"eXH.ResCommStatus.Label","Response Comm Status"},
{"eXH.AddmsgRoutingCriteria.Label","Add Message Routing Criteria"},
{"eXH.SysdefGroup.Label","System Defined Filter Group"},
{"eXH.Acknowlegment.Label","Acknowlegment"}, 
{"eXH.Processing.Label","Processing"},
{"eXH.ExtCode.Label","External Code"},	
{"eXH.Repeatable.Label","Repeatable"},
// Added for Dev Config
{"eXH.Translation.Label","Translation"},
{"eXH.Validation.Label","Validation"},
{"eXH.Derivation.Label","Derivation"},
{"eXH.ConstrCond.Label","Constraint Condition"},
{"eXH.RefKey.Label","Reference Key"},
{"eXH.NullYN.Label","Null_YN"},
{"eXH.OtherDomain.Label","Other Domain"},
{"eXH.Configuration.Label","Configuration"},
{"eXH.EventViewer.Label","Event Viewer"},
{"eXH.SegmentViewer.Label","Segment Viewer"},
{"eXH.InboundDataMapping.Label","Inbound Data Mapping"},
{"eXH.DownloadAPI.Label","Download API Source"},
{"eXH.AddFileCtrlStr.Label","Add File Control Structure "},
{"eXH.CtrlYN.Label","Control"},	
{"eXH.ShowDesc.Label","Show Description"},
{"eXH.TranslationSetting.Label","Translation Settings"},
{"eXH.FilterConfig.Label","Filter Configuration"},
{"eXH.Synchronize.Label","Synchronize"},
{"eXH.ConfigureTrans.Label","Configure Translation"},
{"eXH.TransTableType.Label","Trans Table Type"},
{"eXH.Skey.Label","SKEY"},
{"eXH.Dkey.Label","DKEY"},
{"eXH.MasterTableId.Label","Master Table Id"},
{"eXH.TransTableId.Label","Trans Table Id"},
{"eXH.ColumnId.Label","Column Id"},
{"eXH.ColumnLength.Label","Column Length"} ,
{"eXH.PK_YN.Label","PK_YN"},
{"eXH.TransColumnId.Label","Trans Column Id"},
{"eXH.TableOrForm.Label","Table Or Form"},
{"eXH.ConfigureTrans.Label","Configure Translation"},
{"eXH.exportdata.Label","Export Data"},
{"eXH.AddPredefindValidation.Label","Add Predefined Validation"},
{"eXH.Intitators.Label","Intitators"},
{"eXH.ChooseXLSFile.Label","Choose Excel File"},
{"eXH.TableName.Label","Table Name"},
// XB Param Labels
{"eXH.DrgDetails.Label","DRG Details"},
{"eXH.DbfTableName.Label","DBF Table Name"}, 
{"eXH.DbfSourceDir.Label","DBF Source Directory"}, 
{"eXH.DbfDestDir.Label","DBF Dest Directory"}, 
{"eXH.ExternalExeName.Label","External Exe Name"}, 
{"eXH.SecDiagCount.Label","Secondary Diagnosis Count"}, 
{"eXH.PrcDiagCount.Label","Procedure Diagnosis Count"},
{"eXH.DbfTableCreateStmt.Label","DBF Table Create Stmt"},  
{"eXH.DbfColumnHdng.Label","DBF Column Hdng"}, 
{"eXH.DRGQry.Label","DRG Query"}, 
{"eXH.DbfTraceY/N.Label","DBF Trace Y/N"}, 
{"eXH.CCDetails.Label","CC Details"}, 
{"eXH.CCTraceY/N.Label","CC Trace Y/N"},
{"eXH.MsgRouting.Label","Message Routing(Data Group)"},
{"eXH.ConnSetting.Label","Connectivity  Settings"},
{"eXH.TrigSource.Label","Trigger Source"},
// XF Labels
{"eXH.Interfacet0ExlGL.Label","Interface to External GL"},
{"eXH.Payment.Label","Payment"},
{"eXH.Cash_bill_ctrl_main_ac1.Label","Cash Bill Control Main Ac1"},
{"eXH.Cash_bill_ctrl_main_ac2.Label","Cash Bill Control Main Ac2"},
{"eXH.ExtGLApplication.Label","External GL Application"},
{"eXH.Job.Label","Job"},
{"eXH.Webserivce.Label","Webservice"},
{"eXH.Settings.Label","Settings"},
{"eXH.SAPFunctions.Label","SAP Functions"},
{"eXH.ErrorCode.Label","Error Code"},
{"eXH.SSMonDPErr.Label","SS Monthly Data Process Errors"},
{"eXH.PolicyTypeCode.Label","Policy type code"},
{"eXH.PolicyNo.Label","Policy no"},
{"eXH.CustomerGroup.Label","Customer Group"},
{"eXH.ProcForDate.Label","Process for date"},
{"eXH.ClearErrors.Label","Clear Errors"},
{"eXH.AUTH_USER_ID.Label","Authorized UserID"},
{"eXH.LAST_UPLOAD_DATE.Label","Last Upload Date"},
{"eXH.DATA_UPLOAD.Label","Data Upload"},
{"eXH.PROC_SOC_SEC_DATA.Label","Process Social Security Data"},
{"eXH.CNF_ARC_SOC_SEC_DATA_PROC.Label","Confirm and Archive Social Security Data Process"},
{"eXH.RP_OPEN_ENC_PRIV_UPDATE.Label","Report Open Encounters During Privilege Update"},
{"eXH.RP_UNREG_SS_PAT_PRIV_UPDATE.Label","Report Unregistered SS Patients During Privilege Update"},
{"eXH.OPD_SOC_SEC_PRIV_USAGE_MDB.Label","OPD Social Security Privilege Usage Output(MDB file)"},
{"eXH.RP_IPD_SOC_SEC_PRIV_USAGE.Label","Report IPD Social Security Privilege Usage Output"},
{"eXH.OP_Mon_Year.Label","Output Month/Year"},
{"eXH.LAST_CFM_DATE.Label","Last Confirmed Date"},
{"eXH.PAYER_CODE.Label","Payer Code"},
{"eXH.NO_OF_PAT_PRIV.Label","NO OF PATIENTS PRIVILEGE"},
{"eXH.EXTENDED.Label","Extended"},
{"eXH.REMOVED.Label","Removed"},
{"eXH.ADDED.Label","Added"},
{"eXH.DATA_BYPASSED.Label","Data Bypassed"},
{"eXH.PAYER_GROUP.Label","Payer Group"},
{"eXH.POL_NUM_IND.Label","Policy Number Indicator"},
{"eXH.REF_SUB_HOSP.Label","Ref-SubHospital"},
{"eXH.SMAS_NAT_ID_NO.Label","Same as National ID Number"},
{"eXH.SMAS_PAT_ID.Label","Same as Patient ID"},
{"eXH.FIX_STR.Label","Fixed String"},
{"eXH.UPLOAD.Label","Upload"},
{"eXH.CONFIRMATION.Label","Confirmation"},
{"eXH.DAILY_INVOICE.Label","Daily Invoice"},
{"eXH.GEN_ACCPAC_INV_CSV_FILE.Label","Generate ACCPAC Invoice as CSV file"},
{"eXH.CONSOLIDATE.Label","Consolidate"},
{"eXH.REPLY_FILE_ID.Label","Reply File ID"},
{"eXH.REPLY_DATE.Label","Reply Date"},
{"eXH.DOC_REF_NO.Label","Document Ref No"},
{"eXH.STUDY_LOCATION.Label","Study Location"},
{"eXH.COUNTER_NAME.Label","Counter Name"},
{"eXH.QMS_SERVICE_ID.Label","QMS Service ID"},
{"eXH.REPLY_FILE_NAME.Label","Reply Filename"},
{"eXH.PAYMENT_FILE_EVENT_TYPE.Label","Payment File Eventtype"},
{"eXH.PAYMENT_FILE_ID.Label","Payment File ID"},
{"eXH.PAYMENT_FILE_DATE.Label","Payment File Date"},
{"eXH.PAYMENT_FILE_NAME.Label","Payment Filename"},
{"eXH.NOTIFICATION.Label","Notification"},
{"eXH.REVIEW_PENDING.Label","Review Pending"},
{"eXH.VISIT_ADMIT_DATE.Label","Visit/Admission Date"}

};
}

		

