/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMO.resources;

import java.util.*;

public class  Labels  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {

			{"eMO.Diseasedeath.label","Disease directly leading to death"},
			{"eMO.OtherSignificantCond.label","Other Significant Condition"},
			{"eMO.AmputatedBodyPart.label","Amputated Body Part"},
			{"eMO.AntecedentCause.label","Antecedent Cause"},
			{"eMO.ApprovedDateFrom.label","Approved Date From"},
			{"eMO.ApprovedDateTo.label","Approved Date To"},
			{"eMO.AreaDesc.label","Area Desc"},
			{"eMO.AreaType.label","Area Type"},
			{"eMO.AssignedDate.label","Assigned Date"},
			{"eMO.AutopsyNoDetailsRequired.label","Autopsy Number Associate Details Required"},
			{"eMO.AutopsyNoFormat.label","Autopsy Number Format"},
			{"eMO.BodyConditionType.label","Body Condition Type"},
			{"eMO.BayTableAvailChart.label","Bay/Table Availability Chart"},
			{"eMO.BayTableNo.label","Bay/Table No"},
			{"eMO.BayNo.label","Bay No"},
			{"eMO.Body.label","Body"},
			{"eMO.BodyCondition.label","Body Condition"},
			{"eMO.BodyConditionCode.label","Body Condition Code"},
			{"eMO.BodyConditionDesc.label","Body Condition Desc"},
			{"eMO.BodyDisToMortuary.label","Body Dispatch To Mortuary"},
			{"eMO.BodyFoundAt.label","Body Found At"},
			{"eMO.BodyIdentifiedBy.label","Body Identified By"},
			{"eMO.BodyMovement.label","Body Movement"},
			{"eMO.BodyPartCode.label","Body Part Code"},
			{"eMO.BodyPartDesc.label","Body Part Desc"},
			{"eMO.BodyPartReceiptDateTime.label","Body Part Receipt Date Time"},
			{"eMO.BodyPartType.label","Body Part Type"},
			{"eMO.BodyReceipt.label","Body Receipt Date/Time"},
			{"eMO.BodyRelDateTimefromSource.label","Body Release Date/Time from Source"},
			{"eMO.BroughtByPolice.label","Brought by Police"},
			{"eMO.BurialPermit.label","Burial Permit"},
			{"eMO.BurialPermitApprovalDate.label","Burial Permit Approval Date"},
			{"eMO.BurialPermitApprovedBy.label","Burial Permit Approved By"},
			{"eMO.BurialPermitApprovedByName.label","Burial Permit Approved By Name"},
			{"eMO.BurialPermitNumber.label","Burial Permit Number"},
			{"eMO.BurialPermitIssueDateTime.label","Burial Permit Issue Date/Time"},
			{"eMO.BurialPermitIssued.label","Burial Permit Issued"},
			{"eMO.Capacity.label","Capacity"},
			{"eMO.Claimant.label","Claimant"},			
			{"eMO.ClaimantAccompany.label","Claimant Accompanying"},
			{"eMO.ClaimantCode.label","Claimant Code"},
			{"eMO.ClaimantDesc.label","Claimant Description"},
			{"eMO.ClaimantType.label","Claimant Type"},
			{"eMO.ClaimantTypeRelat.label","Claimant Type/Relationship"},
			{"eMO.Clinical.label","Clinical"},
			{"eMO.ClinicalPostmortem.label","Clinical Postmortem"},
			{"eMO.CollectionTime.label","Collection Time"},
			{"eMO.ConsentFormReceivDate.label","Consent  Form  Received Date/Time"},
			{"eMO.ConsentCode.label","Consent Code"},
			{"eMO.ConsentDesc.label","Consent Description"},
			{"eMO.ConsentFormReceivedBy.label","Consent Form Received by"},
			{"eMO.ConsentFormType.label","Consent Form Type"},
			{"eMO.ConsentGivenBy.label","Consent Given By"},
			{"eMO.CutoffperiodPatientsfromMPI.label","Cut-off period to look for deceased Patients from MPI"},
			{"eMO.DateTimeOfClaiming.label","Date Time Of Claiming"},
			{"eMO.DeadFetus.label","Dead Fetus"},
			{"eMO.DeceasedMortuaryRegNoFormat.label","Deceased Mortuary Registration Number Format"},
			{"eMO.DeceasedPatientDetls.label","Deceased Patient Details"},
			{"eMO.DeceasedPatientID.label","Deceased Patient ID"},
			{"eMO.DeceasedPatientName.label","Deceased Patient Name"},
			{"eMO.DeceasedReg.label","Deceased Registration"},
			{"eMO.DetlsofSpeciCollected.label","Details of Specimens Collected"},
			{"eMO.DonorCardAvlbl.label","Donor Card Available"},
			{"eMO.DonorCardInfo.label","Donor Card Info"},
			{"eMO.DonorCardNo.label","Donor Card No"},			
			{"eMO.EmbassyCertificateNo.label","Embassy Certificate No"},
			{"eMO.EmbassyCountry.label","Embassy of a Country"},
			{"eMO.EndAutopsyNo.label","End Autopsy Number"},
			{"eMO.EndPostmortem.label","End Postmortem"},
			{"eMO.ExportDeceasedBodyPart.label","Export Deceased/Body Part"},
			{"eMO.ExportationAddress.label","Exportation Address"},
			{"eMO.ExportationRequired.label","Exportation Required"},
			{"eMO.Finding.label","Finding"},
			{"eMO.GenerateBurialPermit.label","Generate Burial Permit"},
			{"eMO.GenerateBurialPermitNo.label","Generate Burial Permit Number"},
			{"eMO.HealthOfficer.label","Health Officer"},
			{"eMO.HealthOfficerRemarks.label","Health Officer Remarks"},
			{"eMO.HighRiskBodyPart.label","High Risk Body Part"},
			{"eMO.IdentificationMarks.label","Identification Marks"},
			{"eMO.InternalReport.label","Internal Report"},
			{"eMO.ListoforganforDonation.label","List of organ for Donation"},
			{"eMO.LocationAvailability.label","Location Availability"},
			{"eMO.LocationforArea.label","Location for Area"},
			{"eMO.LocationStatus.label","Location Status"},
			{"eMO.MannerofDeath.label","Manner of Death"},
			{"eMO.MannerOfDeathCode.label","Manner Of Death Code"},
			{"eMO.MannerOfDeathDesc.label","Manner Of Death Desc"},
			{"eMO.MannerOfDeathType.label","Manner Of Death Type"},
			{"eMO.MedicoLegal.label","Medico Legal"},			
			{"eMO.MedicolegalPostmortem.label","Medicolegal Postmortem"},
			{"eMO.MobilePhoneNo.label","Mobile Phone No"},
			{"eMO.Morethan.label","More than"},
			{"eMO.MortuaryNextRegNo.label","Mortuary Next Registration  Number"},
			{"eMO.MortuaryRegEndNo.label","Mortuary Registration End  Number"},
			{"eMO.MortuaryRegNoRequired.label","Mortuary Registration Number Associate Details Required"},
			{"eMO.MortuaryRegStartNo.label","Mortuary Registration Start Number"},
			{"eMO.NextAutopsyNo.label","Next Autopsy Number"},
			{"eMO.NextBurialPermitNo.label","Next Burial Permit No"},
			{"eMO.NotReleased.label","Not Released"},
			{"eMO.NotRequested.label","Not Requested"},
			{"eMO.NoOfDaysToPrsrvUnkwnBody.label","Number of days to preserve unknown body"},
			{"eMO.OrganDonation.label","Organ Donation"},
			{"eMO.OrganforDonation.label","Organ for Donation"},
			{"eMO.OrgansForDonationCode.label","Organs For Donation Code"},
			{"eMO.OrgansForDonationDesc.label","Organs For Donation Desc"},
			{"eMO.OrgansLstdForProcmnt.label","Organs Listed for Procurement"},
			{"eMO.PatientCheckedInAt.label","Patient Checked in At"},
			{"eMO.PatientDonorCardInfo.label","Patient Donor Card Information"},
			{"eMO.PatientIDRegNoName.label","Patient ID/Reg No/Name"},
			{"eMO.PerformedBy.label","Performed By"},
			{"eMO.PMCompletedAt.label","PM Completed At"},
			{"eMO.PMRequestedBy.label","PM Requested  By"},
			{"eMO.PMStartedAt.label","PM Started At"},
			{"eMO.PMYN.label","PM Y/N"},
			{"eMO.Police61Recvd.label","Police Form Received"},
			{"eMO.Police61RecvdBy.label","Police Form Received By"},
			{"eMO.Police61RecvdDt.label","Police Form Received Date"},
			{"eMO.PoliceDetails.label","Police Details"},
			{"eMO.PoliceID.label","Police ID"},
			{"eMO.PoliceOfficer.label","Police Officer"},
			{"eMO.PoliceRank.label","Police Rank"},
			{"eMO.PoliceStation.label","Police Station"},
			{"eMO.PostMortem.label","Post Mortem"},
			{"eMO.PostMortemStartAt.label","Postmortem Start At"},
			{"eMO.PurposeForPrfmgPostMrtm.label","Purpose for performing Postmortem"},
			{"eMO.PostMortemNo.label","Post Mortem Number"},
			{"eMO.PostmortemArea.label","Postmortem Area"},
			{"eMO.PostmortemCertifiedBy.label","Postmortem Certified By"},
			{"eMO.PostmortemDtls.label","Postmortem Details"},
			{"eMO.PostmortemPrfmdBy.label","Postmortem Performed By"},
			{"eMO.PostmortemStatus.label","Postmortem Status"},
			{"eMO.PostmortemType.label","Postmortem Type"},
			{"eMO.PrefixSuffix.label","Prefix    Suffix"},
			{"eMO.PresentDrngPostmrtm.label","Present During Postmortem"},
			{"eMO.ProcedureDuration.label","Procedure Duration"},
			{"eMO.ProcurementTime.label","Procurement Time"},
			{"eMO.ReassignArea.label","Reassign Area"},
			{"eMO.Receipt.label","Receipt"},
			{"eMO.ReceiptDateTime.label","Receipt Date/Time"},
			{"eMO.RecordPostmortem.label","Record Postmortem"},
			{"eMO.RegNo.label","Reg No"},
			{"eMO.RegisteredCases.label","Registered Cases"},
			{"eMO.RegistrationDtls.label","Registration Details"},
			{"eMO.RegnNo.label","Regn No"},
			{"eMO.RelnWithDeceased.label","Relationship with deceased"},
			{"eMO.ReleaseArea.label","Release Area"},
			{"eMO.ReleaseDateTime.label","Release Date/Time"},
			{"eMO.ReleaseDeceased.label","Release Deceased"},
			{"eMO.ReleaseDeceasedBodyPart.label","Release Deceased/Body Part"},
			{"eMO.ReleaseLocation.label","Release Location"},
			{"eMO.ReleaseStatus.label","Release Status"},
			{"eMO.Released.label","Released"},
			{"eMO.ReleasedYN.label","Released(Y/N)"},
			{"eMO.ReleasedBy.label","Released By"},
			{"eMO.ReligiousOrgn.label","Religious Organizations"},
			{"eMO.SpecimenDescription.label","Specimen Description"},
			{"eMO.SpecimenHandedDateTime.label","Specimen Handed Date/Time"},
			{"eMO.SpecimenHandedOverTo.label","Specimen Handed over to"},
			{"eMO.StartPostmortem.label","Start Postmortem"},
			{"eMO.StartingAutopsyNo.label","Starting Autopsy Number"},
			{"eMO.StorageArea.label","Storage Area"},
			{"eMO.SmryOfFdgs.label","Summary of Findings"},
			{"eMO.SpecimenHandedOverDate.label","Specimen Handed Over Date"},
			{"eMO.TissueProcured.label","Tissue Procured"},
			{"eMO.TissueProcurement.label","Tissue Procurement"},
			{"eMO.TissueProcuredPrfmdBy.label","Tissue procurement performed by"},
			{"eMO.TissueProcuredPrfmdDt.label","Tissue procurement performed date"},
			{"eMO.TissueProcmntRegn.label","Tissue Procurement Registration"},
			{"eMO.TypeOfPostmortem.label","Type of Postmortem"},
			{"eMO.UnclaimedBody.label","Unclaimed Body"},
			{"eMO.UnclaimedBodyPart.label","Unclaimed Body Part"},
			{"eMO.UnderTaker.label","Under Taker"},
			{"eMO.UnidentifiedBodyPart.label","Unidentified Body Part"},
			{"eMO.VehicleNumber.label","Vehicle Number"},
			{"eMO.ViewMovementHistory.label","View Movement History"},
			{"eMO.WaitTimeDuration.label","Wait Time Duration"},
			{"eMO.WelfareAssociations.label","Welfare Associations"},
			{"eMO.ConsentTitle.label","Consent Title"},
			{"eMO.ViewDeceasedDtls.label","View Deceased Details"}, 
			{"eMO.DeceasedPatients.label","Deceased Patients"}, 
			{"eMO.OrganCode.label","Organ Code"}, 
			{"eMO.OrganDescription.label","Organ Description"}, 
			{"eMO.BurialPermitNo.label","Burial Permit No"}, 
			{"eMO.Unregistered.label","Unregistered"},
			{"eMO.CopyDetails.label","Copy Details"},
			{"eMO.ObtainedFrom.label","Obtained From"},
			{"eMO.ConsentOrgnDtn.label","Consent For Organ Donation"},
			{"eMO.ConsentClnicPstMrm.label","Consent For Clinical Post Mortem"},
			{"eMO.ManageDeceasedPatients.label","Manage Deceased Patients"},
			{"eMO.PostmortemRequest.label","Postmortem Request"},
			{"eMO.StartPM.label","Start PM"},
			{"eMO.EndPM.label","End PM"},
			{"eMO.ExportationDocument.label","Exportation Document"},
			{"eMO.UnAssignLocation.label","UnAssign Location"},
			{"eMO.NormalDeath.label","Normal Death"},
			{"eMO.PoliceCase.label","Police Case"},
			{"eMO.DeceasedName.label","Deceased Name"},
			{"eMO.BIDcase.label","B.I.D Case"},
			{"eMO.Biohazard.label","Biohazard"},
			{"eMO.FreezerNo.label","Freezer No"},
			{"eMO.FreezerDesc.label","Freezer Desc"},
			{"eMO.card.label","Card"},
			{"eMO.organ.label","organ"},

			// Reports related Lables added on 20/1/09

			{"eMO.where.label","where"},
			{"eMO.Registry.label","Registry"},
			{"eMO.made.label","made"},
			{"eMO.IssuingOfficer.label","Issuing Officer"},
			{"eMO.CATEGORY.label","CATEGORY"},
			{"eMO.ApprovingOfficer.label","Approving Officer"},
			{"eMO.HANDOVEROFBODY.label","HANDOVER OF BODY"},
			{"eMO.VehicleNo.label","Vehicle No"},
			{"eMO.Organdonated.label","Organ donated"},
			{"eMO.HP.label","HP"},
			{"eMO.ASSISTANT.label","ASSISTANT"},
			{"eMO.Case.label","Case"},
			{"eMO.handling.label","handling"},
			{"eMO.Doctor.label","Doctor"},
			{"eMO.Act.label","Act"},
			{"eMO.hereby.label","hereby"},
			{"eMO.that.label","that"},
			{"eMO.haveconductedan.label","have conducted an"},
			{"eMO.This.label","This"},
			{"eMO.is.label","is"},
			{"eMO.medicalofficer.label","medical officer"},
			{"eMO.use.label","use"},
			{"eMO.certify.label","certify"},
			{"eMO.whileconducting.label","while conducting"},
			{"eMO.must.label","must"},
			{"eMO.be.label","be"},
			{"eMO.whohasreported.label","who has reported"},
			{"eMO.are.label","are"},
			{"eMO.OfficialStamp.label","Official Stamp"},
			{"eMO.person.label","person"},
			{"eMO.Freezer.label","Freezer"},
			{"eMO.2aCoronersdeathbodyorderburial.label","2a.Coroners will see the death body and order burial."},
			{"eMO.2bCorwillnotdoctorproceedreleasing.label","2b.Coroners will not see the death body and the doctor will proceed or will releasing"},
			{"eMO.bodytoclaimatafterpostmortem.label","body to claimat after post mortem."},
			{"eMO.Rank.label","Rank"},
			{"eMO.Accompaniesby.label","Accompanies by"},
			{"eMO.OFFICER.label","OFFICER"},
			{"eMO.hereby.label","hereby"},
			{"eMO.carry.label","carry"},
			{"eMO.understand.label","understand"},
			{"eMO.that.label","that"},
			{"eMO.will.label","will"},
			{"eMO.Whole.label","Whole"},
			{"eMO.Iunderstandpartbodyfurinveststandby.label","I also understand that some part of the body will be taken for the purpose of further investigation / standby."},
			{"eMO.AUTHORITY.label","AUTHORITY"},
			{"eMO.naturepurposeautopsyexplained.label","The nature and purpose of the autopsy have been explained by"},
			{"eMO.Pleasepostmortemdeceasedstatecausedeath.label","1. Please do the postmortem on the deceased and state the cause of death :"},
			{"eMO.Exporting.label","Exporting"},
			{"eMO.Endorse.label","Endorse"},
			{"eMO.Claimant.label","Claimant"},
			{"eMO.investigating.label","investigating"},
			{"eMO.HP.label","HP"},
			{"eMO.Approximate.label","Approximate"},
			{"eMO.Qualification.label","Qualification"},		
			{"eMO.DurationinMortuary.label","Duration in Mortuary"},		
			{"eMO.BurialPermitRequiredYesNo.label","Burial Permit Mandatory"}	,	
			{"eMO.RervertReleased.label","Revert Released"},		
			{"eMO.RevertReleasedBodyPart.label","Revert Released/Body Part"},
			{"eMO.RFIDTag.label","RFID Tag No"},
			{"eMO.RFIDTagDetails.label","RFID Tag Details"},
			{"eMO.MortuaryManagement.label","Mortuary Management"},
			{"eMO.ExternalDeath.label","External Deaths"},
			{"eMO.ReleasedToOtherFacility.label","Released to other facility"},
		    {"eMO.MannerofDeathuponReceipt.label","Manner of Death upon Receipt"},
			{"eMO.MannerofDeathafterPostmortem.label","Manner of Death after Postmortem"},
			{"eMO.EmbalmService.label","Embalm Service"},
			{"eMO.RequireEmbalmService.label","Require Embalm Service"},
			{"eMO.RecordEmbalm.label","Record Embalm"},
            {"eMO.PatientisHIV.label","Patient is HIV+"},
			{"eMO.PatientisHEP.label","Patient is HEP+"},
			{"eMO.EmbalmAthome.label","Embalm to be performed at home"},
			{"eMO.EmbalmFromDetails.label","Embalm Form Details"},
			{"eMO.Payable.label","Payable"},
			{"eMO.ApplicantID.label","Applicant ID"},
			{"eMO.DateofApplication.label","Date of Application"},
			{"eMO.ContactNoofApplicant.label","Contact No.of Applicant"},
			{"eMO.Identitycard/passportofApplicant.label","Identity card/passport No. of Applicant"},
			{"eMO.Identitycard/passportNo.label","Identity card/passport No."},
			{"eMO.AddressofApplicant.label","Address of Applicant"},
			{"eMO.DetailsofdeceasedtobeEmbalmed.label","Details of deceased to be Embalmed"},
			{"eMO.Identitycard/passpotNo.label","Identity card/passpot No."},
			{"eMO.AddressofEmblamingProcedurediffere.label","Address of Emblaming Procedure(uncheck if different from above)"},
			{"eMO.DetailstobeFilledbyMortuaryStaff.label","Details to be Filled by Mortuary Staff"},
			{"eMO.DateofEmbalmingProcedure.label","Date of Embalming Procedure"},
			{"eMO.TimeofEmbalmingProcedure.label","Time of Embalming Procedure"},
			{"eMO.AmountofEmbalmingluidused.label","Amount of Embalming fluid used"},
			{"eMO.EmbalmCompleted.label","Embalm Completed"},
			{"eMO.ReleaseEmbalmedBody.label","Release Embalmed Body"},
			{"eMO.CancelEmbalm.label","Cancel Embalm"},
		 	{"eMO.ReasonforCancellation.label","Reason for Cancellation"},
		 	{"eMO.CancelEmbalm/ReleaseEmbalm.label","Embalm Completion/Cancel Embalm"},
		 	{"eMO.EmbalmRequeiredatHome.label"," Embalm at Home"},
		 	{"eMO.EmbalmRequeiredatHospital.label","Embalm at Hospital"},
			{"eMO.ApplicantAddress.label","Applicant Address"},
			{"eMO.EmbalmAddress.label","Embalm Address"},
			{"eMO.EmbalmStatus.label","Embalm Status"},
			{"eMO.Canceled.label","Cancelled"},
			{"eMO.liter.label","Liter(s)"},
			{"eMO.EmbalmRequestDetails.label","Embalm Request Details"},
			{"eMO.DefaultPreviousClaimantDetails.label","Default Previous Claimant Details"},//Added For Bru-HIMS-CRF-0368 By Dharma on 3rd Dec 2013 
			{"eMO.ViewClaimantHistory.label","View Claimant History"},//Added For Bru-HIMS-CRF-0368 By Dharma on 3rd Dec 2013
			{"eMO.StartingEmbalmNo.label","Starting Embalm Number"},
			{"eMO.NextEmbalmNo.label","Next Embalm Number"},
			{"eMO.EndEmbalmNo.label","End Embalm Number"},	
			{"eMO.EmbalmNoDetailsRequired.label","Embalm Number Associate Details Required"},
			{"eMO.EmbalmNoFormat.label","Embalm Number Format"},
			{"eMO.CopyApplicantAddress.label","Copy Applicant Address"},
			{"eMO.PrintEmbalmForm.label","Print Embalm Application Form"},
			{"eMO.MyKad.label","My Kad"}, //Added by Ashwini on 24-Jul-2017 for ML-MMOH-CRF-0743
			{"eMO.OtherId.label","Other Identification"}, //Added by Ashwini on 24-Jul-2017 for ML-MMOH-CRF-0743
			{"eMO.InternalExamination.label","Internal"}, //Added by Mano on 25-sep-2017 for ML-MMOH-CRF-0791
			{"eMO.ExternalExamination.label","External"}, //Added by Mano on 25-sep-2017 for ML-MMOH-CRF-0791
			{"eMO.ExaminationType.label","Examination Type"}, //Added by Mano on 25-sep-2017 for ML-MMOH-CRF-0791
			{"eMO.ReleaseLetterFromEmbassy.label","Release Letter from Embassy"}, //Added by Mano 16-oct-2017 for ML-MMOH-CRF-0738
			{"eMO.AllowUserRecordPMFindingDetails.label","Allow user to record PM Finding details"}, // added by mujafar for ML-MMOH-CRF-0880
	        {"eMO.DateTimeOfDeath.label","Date Time Of Death"}, //Added by Shanmukh on 25-JUNE-2018 for ML-MMOH-CRF-1183
			{"eMO.AutopsyNo.label","Autopsy No"},//Added by Shanmukh on 26-JUNE-2018 for ML-MMOH-CRF-1034
			//Added by Shanmukh on 19th-JULY-2018 for ML-MMOH-CRF-1096
			{"eMO.murder.label","Murder"},
			{"eMO.suicide.label","Suicide"},
			{"eMO.natural.label","Natural"},
			{"eMO.undetermined.label","Undetermined"},
			{"eMO.unclassified.label","Unclassified"},
			{"eMO.pending.label","Pending lx"},
			//END
			{"eMO.DateTimeOfClaimingMandatory.label","Date Time of claiming mandatory"},//Added by Santhosh on 26-Oct-2022 for ML-MMOH-CRF-1948
			//Added by Santhosh on 26-Oct-2022 for ML-MMOH-CRF-1947
			{"eMO.MaxNumCharAllowedInBurialPermitNumber.label","Maximum number & characters allowed in Burial Permit Number"},
			{"eMO.MaxNumAndCharAllowedInBurialPermitNumber.label","Maximum number and characters allowed in Burial Permit Number"}
			//END
	};
}
