/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMO.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
{"eMO.Diseasedeath.label","مرض يؤدي مباشرة إلى الوفاة"},
{"eMO.OtherSignificantCond.label","حالة أخرى مهمة"},
{"eMO.AmputatedBodyPart.label","جزء من الجسم مبتور"},
{"eMO.AntecedentCause.label","سبب سابق"},
{"eMO.ApprovedDateFrom.label","تاريخ الموافقة من"},
{"eMO.ApprovedDateTo.label","التاريخ الموافقة ل"},
{"eMO.AreaDesc.label","وصف المنطقة"},
{"eMO.AreaType.label","نوع المنطقة"},
{"eMO.AssignedDate.label","التاريخ المحدد"},
{"eMO.AutopsyNoDetailsRequired.label","مطلوب التفاصيل المساعدة لرقم التشريح"},
{"eMO.AutopsyNoFormat.label","تنسيق رقم التشريح"},
{"eMO.BodyConditionType.label","نوع حالة الجسم"},
{"eMO.BayTableAvailChart.label","Bay/Table Availability Chart"},
{"eMO.BayTableNo.label","Bay/Table No"},
{"eMO.BayNo.label","Bay No"},
{"eMO.Body.label","الجسم"},
{"eMO.BodyCondition.label","حالة الجسم"},
{"eMO.BodyConditionCode.label","كود حالة الجسم"},
{"eMO.BodyConditionDesc.label","وصف حالة الجسم"},
{"eMO.BodyDisToMortuary.label","إرسال الجثمان إلى ثلاجة الموتى"},
{"eMO.BodyFoundAt.label","تم العثور على الجثمان في"},
{"eMO.BodyIdentifiedBy.label","تم التعرف على الجثمان بواسطة"},
{"eMO.BodyMovement.label","حركة الجسد"},
{"eMO.BodyPartCode.label","كود جزء الجسم"},
{"eMO.BodyPartDesc.label","وصف جزء الجسم"},
{"eMO.BodyPartReceiptDateTime.label","وقت و تاريخ استلام الجزء من الجسم"},
{"eMO.BodyPartType.label","نوع جزء الجسم"},
{"eMO.BodyReceipt.label","تاريخ / وقت استلام الجثمان"},
{"eMO.BodyRelDateTimefromSource.label","تاريخ / وقت إصدار الجثمان من المصدر"},
{"eMO.BroughtByPolice.label","جلبتها الشرطة"},
{"eMO.BurialPermit.label","تصريح الدفن"},
{"eMO.BurialPermitApprovalDate.label","تاريخ الموافقة على تصريح الدفن"},
{"eMO.BurialPermitApprovedBy.label","تصريح الدفن معتمد من"},
{"eMO.BurialPermitApprovedByName.label","تصريح الدفن مصدق عليه بالاسم"},
{"eMO.BurialPermitNumber.label","رقم تصريح الدفن"},
{"eMO.BurialPermitIssueDateTime.label","تاريخ / وقت إصدار تصريح الدفن"},
{"eMO.BurialPermitIssued.label","إصدار تصريح الدفن"},
{"eMO.Capacity.label","سعة"},
{"eMO.Claimant.label","المدعي"},
{"eMO.ClaimantAccompany.label","المدعي المرافق"},
{"eMO.ClaimantCode.label","كود المدعي"},
{"eMO.ClaimantDesc.label","وصف المدعي"},
{"eMO.ClaimantType.label","نوع المدعي"},
{"eMO.ClaimantTypeRelat.label","نوع المدعي / العلاقة"},
{"eMO.Clinical.label","مرضي"},
{"eMO.ClinicalPostmortem.label","تشريح الجثة السريرية"},
{"eMO.CollectionTime.label","وقت التجميع"},
{"eMO.ConsentFormReceivDate.label","تاريخ / وقت استلام نموذج الإقرار"},
{"eMO.ConsentCode.label","كود الإقرار"},
{"eMO.ConsentDesc.label","وصف الإقرار"},
{"eMO.ConsentFormReceivedBy.label","تم استلام نموذج الإقرار بواسطة"},
{"eMO.ConsentFormType.label","نوع نموذج الإقرار"},
{"eMO.ConsentGivenBy.label","الإقرار مقدم من"},
{"eMO.CutoffperiodPatientsfromMPI.label","فترة التوقف للبحث عن مرضى متوفين من فهرس المرضى"},
{"eMO.DateTimeOfClaiming.label","تاريخ و وقت المطالبة"},
{"eMO.DeadFetus.label","الجنين المتوفى"},
{"eMO.DeceasedMortuaryRegNoFormat.label","تنسيق رقم تسجيل جثمان المتوفى"},
{"eMO.DeceasedPatientDetls.label","بيانات المريض المتوفى"},
{"eMO.DeceasedPatientID.label","هوية المريض المتوفى"},
{"eMO.DeceasedPatientName.label","اسم المريض المتوفى"},
{"eMO.DeceasedReg.label","تسجيل المتوفى"},
{"eMO.DetlsofSpeciCollected.label","تفاصيل العينات المجمعة"},
{"eMO.DonorCardAvlbl.label","بطاقة المتبرع متوفرة"},
{"eMO.DonorCardInfo.label","معلومات بطاقة المتبرع"},
{"eMO.DonorCardNo.label","رقم بطاقة المتبرع"},
{"eMO.EmbassyCertificateNo.label","رقم شهادة السفارة"},
{"eMO.EmbassyCountry.label","سفارة دولة"},
{"eMO.EndAutopsyNo.label","رقم نهاية التشريح "},
{"eMO.EndPostmortem.label","نهاية تشريح الجثمان"},
{"eMO.ExportDeceasedBodyPart.label","تصدير المتوفى / جزء من الجسم"},
{"eMO.ExportationAddress.label","عنوان التصدير"},
{"eMO.ExportationRequired.label","التصدير مطلوب"},
{"eMO.Finding.label","العثور على"},
{"eMO.GenerateBurialPermit.label","استخراج تصريح الدفن"},
{"eMO.GenerateBurialPermitNo.label","إصدار رقم تصريح الدفن"},
{"eMO.HealthOfficer.label","مسئول الصحة"},
{"eMO.HealthOfficerRemarks.label","ملاحظات مسئول الصحة"},
{"eMO.HighRiskBodyPart.label","جزء الجسم عالي الخطورة"},
{"eMO.IdentificationMarks.label","علامات تعريف"},
{"eMO.InternalReport.label","تقرير داخلي"},
{"eMO.ListoforganforDonation.label","قائمة الأعضاء للتبرع"},
{"eMO.LocationAvailability.label","توافر الموقع"},
{"eMO.LocationforArea.label","موقع للمنطقة"},
{"eMO.LocationStatus.label","حالة الموقع"},
{"eMO.MannerofDeath.label","طريقة الوفاة"},
{"eMO.MannerOfDeathCode.label","كود طريقة الوفاة"},
{"eMO.MannerOfDeathDesc.label","وصف طريقة الوفاة"},
{"eMO.MannerOfDeathType.label","نوع طريقة الوفاة"},
{"eMO.MedicoLegal.label","الطب الشرعي"},
{"eMO.MedicolegalPostmortem.label","تشريح الجثمان"},
{"eMO.MobilePhoneNo.label","رقم الهاتف المحمول"},
{"eMO.Morethan.label","أكثر من"},
{"eMO.MortuaryNextRegNo.label","رقم القيد التالي للمشرحة"},
{"eMO.MortuaryRegEndNo.label","الرقم النهائي لتسجيل الجثامين"},
{"eMO.MortuaryRegNoRequired.label","مطلوب تفاصيل رقم قيد الجثامين"},
{"eMO.MortuaryRegStartNo.label","رقم بدء تسجيل المشرحة"},
{"eMO.NextAutopsyNo.label","رقم التشريح التالي"},
{"eMO.NextBurialPermitNo.label","تصريح الدفن التالي رقم"},
{"eMO.NotReleased.label","لم يفرج عنه"},
{"eMO.NotRequested.label","غير مطلوب"},
{"eMO.NoOfDaysToPrsrvUnkwnBody.label","عدد أيام الاحتفاظ بالجثمان المجهول"},
{"eMO.OrganDonation.label","التبرع بالأعضاء"},
{"eMO.OrganforDonation.label","العضو للتبرع"},
{"eMO.OrgansForDonationCode.label","كود العضو للتبرع"},
{"eMO.OrgansForDonationDesc.label","وصف العضو للتبرع"},
{"eMO.OrgansLstdForProcmnt.label","الأعضاء المدرجة في قائمة المشتريات"},
{"eMO.PatientCheckedInAt.label","تم تسجيل وصول المريض في"},
{"eMO.PatientDonorCardInfo.label","معلومات بطاقة المريض المتبرع "},
{"eMO.PatientIDRegNoName.label","معرف المريض / رقم التسجيل / الاسم"},
{"eMO.PerformedBy.label","تم تأديتها بواسطة"},
{"eMO.PMCompletedAt.label","اكتمل تشريح الجثمان في"},
{"eMO.PMRequestedBy.label","تم طلب تشريح الجثمان بواسطة"},
{"eMO.PMStartedAt.label","بدأ تشريح الجثمان في"},
{"eMO.PMYN.label","تشريح الجثمان بعد الوفاة نعم / لا"},
{"eMO.Police61Recvd.label","تم استلام استمارة الشرطة"},
{"eMO.Police61RecvdBy.label","تم استلام استمارة الشرطة من قبل"},
{"eMO.Police61RecvdDt.label","تاريخ استلام استمارة الشرطة"},
{"eMO.PoliceDetails.label","تفاصيل الشرطة"},
{"eMO.PoliceID.label","رقم تعريف الشرطي"},
{"eMO.PoliceOfficer.label","ضابط شرطة"},
{"eMO.PoliceRank.label","رتبة الشرطي"},
{"eMO.PoliceStation.label","قسم الامن"},
{"eMO.PostMortem.label","تشريح الجثمان"},
{"eMO.PostMortemStartAt.label","تشريح الجثمان يبدأ في"},
{"eMO.PurposeForPrfmgPostMrtm.label","الغرض من إجراء تشريح الجثمان"},
{"eMO.PostMortemNo.label","رقم التشريح"},
{"eMO.PostmortemArea.label","منطقة تشريح الجثمان"},
{"eMO.PostmortemCertifiedBy.label","تم التصديق على تشريح الجثمان بواسطة"},
{"eMO.PostmortemDtls.label","تفاصيل تشريح الجثمان"},
{"eMO.PostmortemPrfmdBy.label","تم إجراء تشريح الجثمان بواسطة"},
{"eMO.PostmortemStatus.label","حالة تشريح الجثمان"},
{"eMO.PostmortemType.label","نوع تشريح الجثمان"},
{"eMO.PrefixSuffix.label","البادئة / اللاحقة"},
{"eMO.PresentDrngPostmrtm.label","حاضر أثناء تشريح الجثمان"},
{"eMO.ProcedureDuration.label","مدة الإجراء"},
{"eMO.ProcurementTime.label","وقت الشراء"},
{"eMO.ReassignArea.label","إعادة تعيين المنطقة"},
{"eMO.Receipt.label","الاستلام"},
{"eMO.ReceiptDateTime.label","تاريخ / وقت الاستلام"},
{"eMO.RecordPostmortem.label","تسجيل تشريح الجثمان"},
{"eMO.RegNo.label","رقم التسجيل"},
{"eMO.RegisteredCases.label","الحالات المسجلة"},
{"eMO.RegistrationDtls.label","تفاصيل التسجيل"},
{"eMO.RegnNo.label","رقم التسجيل"},
{"eMO.RelnWithDeceased.label","العلاقة مع المتوفى"},
{"eMO.ReleaseArea.label","منطقة الإصدار"},
{"eMO.ReleaseDateTime.label","تاريخ / وقت الإصدار"},
{"eMO.ReleaseDeceased.label","خروج المتوفين"},
{"eMO.ReleaseDeceasedBodyPart.label","خروج المتوفى / جزء من الجسم"},
{"eMO.ReleaseLocation.label","موقع الخروج"},
{"eMO.ReleaseStatus.label","حالة الخروج"},
{"eMO.Released.label","تم الخروج"},
{"eMO.ReleasedYN.label","تم الخروج (نعم / لا)"},
{"eMO.ReleasedBy.label","خروج من قبل"},
{"eMO.ReligiousOrgn.label","المنظمات الدينية"},
{"eMO.SpecimenDescription.label","وصف العينة"},
{"eMO.SpecimenHandedDateTime.label","تاريخ/ وقت تسليم العينة "},
{"eMO.SpecimenHandedOverTo.label","تم تسليم العينة إلى"},
{"eMO.StartPostmortem.label","بدء تشريح الجثمان"},
{"eMO.StartingAutopsyNo.label","بدء رقم التشريح"},
{"eMO.StorageArea.label","منطقة تخزين"},
{"eMO.SmryOfFdgs.label","ملخص النتائج"},
{"eMO.SpecimenHandedOverDate.label","تاريخ تسليم العينة"},
{"eMO.TissueProcured.label","الأنسجة المشتراة"},
{"eMO.TissueProcurement.label","شراء الأنسجة"},
{"eMO.TissueProcuredPrfmdBy.label","شراء الأنسجة بواسطة"},
{"eMO.TissueProcuredPrfmdDt.label","تاريخ إجراء شراء الأنسجة"},
{"eMO.TissueProcmntRegn.label","تسجيل مشتريات الأنسجة"},
{"eMO.TypeOfPostmortem.label","نوع تشريح الجثمان"},
{"eMO.UnclaimedBody.label","الجثمان غير المطالب به"},
{"eMO.UnclaimedBodyPart.label","جزء الجسم غير المطالب به"},
{"eMO.UnderTaker.label","متعهد الدفن"},
{"eMO.UnidentifiedBodyPart.label","جزء من الجسم مجهول الهوية"},
{"eMO.VehicleNumber.label","رقم المركبة"},
{"eMO.ViewMovementHistory.label","عرض تاريخ الحركة"},
{"eMO.WaitTimeDuration.label","مدة الانتظار"},
{"eMO.WelfareAssociations.label","جمعيات الرفاه"},
{"eMO.ConsentTitle.label","عنوان الموافقة"},
{"eMO.ViewDeceasedDtls.label","عرض تفاصيل المتوفى"},
{"eMO.DeceasedPatients.label","المرضى المتوفون"},
{"eMO.OrganCode.label","كود العضو"},
{"eMO.OrganDescription.label","وصف العضو"},
{"eMO.BurialPermitNo.label","تصريح الدفن رقم"},
{"eMO.Unregistered.label","غير مسجل"},
{"eMO.CopyDetails.label","نسخ التفاصيل"},
{"eMO.ObtainedFrom.label","تم الحصول عليها من"},
{"eMO.ConsentOrgnDtn.label","الموافقة على التبرع بالأعضاء"},
{"eMO.ConsentClnicPstMrm.label","الموافقة على تشريح الجثمان"},
{"eMO.ManageDeceasedPatients.label","إدارة المرضى المتوفين"},
{"eMO.PostmortemRequest.label","طلب تشريح الجثمان"},
{"eMO.StartPM.label","بداية التشريح"},
{"eMO.EndPM.label","نهاية التشريح"},
{"eMO.ExportationDocument.label","وثيقة التصدير"},
{"eMO.UnAssignLocation.label","موقع غير مخصص"},
{"eMO.NormalDeath.label","الموت الطبيعي"},
{"eMO.PoliceCase.label","قضية الشرطة"},
{"eMO.DeceasedName.label","اسم المتوفى"},
{"eMO.BIDcase.label","حالة B.I.D"},
{"eMO.Biohazard.label","خطر حيوي"},
{"eMO.FreezerNo.label","رقم حجرة التجميد"},
{"eMO.FreezerDesc.label","وصف حجرة التجميد"},
{"eMO.card.label","بطاقة"},
{"eMO.organ.label","عضو"},
{"eMO.where.label","أين"},
{"eMO.Registry.label","التسجيل"},
{"eMO.made.label","مصنوع"},
{"eMO.IssuingOfficer.label","ضابط إصدار"},
{"eMO.CATEGORY.label","الفئة"},
{"eMO.ApprovingOfficer.label","موظف اعتماد"},
{"eMO.HANDOVEROFBODY.label","تسليم الجثمان"},
{"eMO.VehicleNo.label","رقم المركبة"},
{"eMO.Organdonated.label","تم التبرع بالأعضاء"},
{"eMO.HP.label","HP"},
{"eMO.ASSISTANT.label","مساعد"},
{"eMO.Case.label","قضية"},
{"eMO.handling.label","تسليم"},
{"eMO.Doctor.label","طبيب"},
{"eMO.Act.label","فعل"},
{"eMO.hereby.label","أنشر"},
{"eMO.that.label","ذلك"},
{"eMO.haveconductedan.label","أجرى"},
{"eMO.This.label","هذه"},
{"eMO.is.label","يكون"},
{"eMO.medicalofficer.label","طبيب"},
{"eMO.use.label","استعمال"},
{"eMO.certify.label","يشهد"},
{"eMO.whileconducting.label","أثناء إجراء"},
{"eMO.must.label","يجب"},
{"eMO.be.label","يكون"},
{"eMO.whohasreported.label","الذي أبلغ"},
{"eMO.are.label","تكون"},
{"eMO.OfficialStamp.label","ختم رسمي"},
{"eMO.person.label","شخص"},
{"eMO.Freezer.label","حجرة التجميد"},
{"eMO.2aCoronersdeathbodyorderburial.label","2 أ- سوف يرى الطبيب الشرعي الجثمان ويأمر بدفنه."},
{"eMO.2bCorwillnotdoctorproceedreleasing.label","2 ب - لن يرى الطبيب الشرعي الجثمان والطبيب سيستكمل أو سيقوم بعمل خروج له"},
{"eMO.bodytoclaimatafterpostmortem.label","الجثمان للمطالبة بعد التشريح."},
{"eMO.Rank.label","مرتبة"},
{"eMO.Accompaniesby.label","يرافق"},
{"eMO.OFFICER.label","ضابط"},
{"eMO.hereby.label","بموجب هذا"},
{"eMO.carry.label","احمل"},
{"eMO.understand.label","تفهم"},
{"eMO.that.label","ذلك"},
{"eMO.will.label","وصية"},
{"eMO.Whole.label","كل"},
{"eMO.Iunderstandpartbodyfurinveststandby.label","أفهم أيضًا أنه سيتم أخذ جزء من الجسم لغرض مزيد من التحقيق / الاستعداد."},
{"eMO.AUTHORITY.label","السلطة"},
{"eMO.naturepurposeautopsyexplained.label","تم شرح طبيعة والغرض من تشريح الجثمان من قبل"},
{"eMO.Pleasepostmortemdeceasedstatecausedeath.label","1. يرجى إجراء تشريح الجثة على المتوفى وذكر سبب الوفاة:"},
{"eMO.Exporting.label","تصدير"},
{"eMO.Endorse.label","صدّق"},
{"eMO.Claimant.label","المدعي"},
{"eMO.investigating.label","التحقيق"},
{"eMO.HP.label","HP"},
{"eMO.Approximate.label","تقريبي"},
{"eMO.Qualification.label","المؤهل"},
{"eMO.DurationinMortuary.label","المدة في الثلاجة الموتى"},
{"eMO.BurialPermitRequiredYesNo.label","تصريح الدفن إلزامي"},
{"eMO.RervertReleased.label","تم تحرير الإسترداد"},
{"eMO.RevertReleasedBodyPart.label","تم تحرير الإسترداد / جزء من الجسم"},
{"eMO.RFIDTag.label","رقم بطاقة RFID "},
{"eMO.RFIDTagDetails.label","تفاصيل بطاقة RFID"},
{"eMO.MortuaryManagement.label","إدارة ثلاجة الموتى"},
{"eMO.ExternalDeath.label","الوفيات الخارجية"},
{"eMO.ReleasedToOtherFacility.label","خروج إلى منشأة أخرى"},
{"eMO.MannerofDeathuponReceipt.label","طريقة الموت عند الاستلام"},
{"eMO.MannerofDeathafterPostmortem.label","طريقة الموت بعد التشريح"},
{"eMO.EmbalmService.label","خدمة غسل الجثمان"},
{"eMO.RequireEmbalmService.label","طلب خدمة غسل الجثمان"},
{"eMO.RecordEmbalm.label","سجل غسل الجثامين"},
{"eMO.PatientisHIV.label","المريض هو HIV +"},
{"eMO.PatientisHEP.label","المريض هو HEP +"},
{"eMO.EmbalmAthome.label","يتم إجراء الغسل في المنزل"},
{"eMO.EmbalmFromDetails.label","تفاصيل نموذج الغسل"},
{"eMO.Payable.label","مستحق الدفع"},
{"eMO.ApplicantID.label","معرف مقدم الطلب"},
{"eMO.DateofApplication.label","تاريخ التطبيق"},
{"eMO.ContactNoofApplicant.label","رقم الاتصال لمقدم الطلب"},
{"eMO.Identitycard/passportofApplicant.label","بطاقة الهوية / رقم جواز السفر لمقدم الطلب"},
{"eMO.Identitycard/passportNo.label","رقم بطاقة الهوية / جواز السفر"},
{"eMO.AddressofApplicant.label","عنوان مقدم الطلب"},
{"eMO.DetailsofdeceasedtobeEmbalmed.label","تفاصيل المتوفى المراد غسله"},
{"eMO.Identitycard/passpotNo.label","بطاقة الهوية / رقم جواز السفر"},
{"eMO.AddressofEmblamingProcedurediffere.label","عنوان إجراء الغسل (قم بإلغاء التحديد إذا كان مختلفًا عن العنوان أعلاه)"},
{"eMO.DetailstobeFilledbyMortuaryStaff.label","التفاصيل التي يجب ملؤها من قبل طاقم ثلاجة الموتى"},
{"eMO.DateofEmbalmingProcedure.label","تاريخ إجراء الغسل"},
{"eMO.TimeofEmbalmingProcedure.label","وقت إجراء الغسل"},
{"eMO.AmountofEmbalmingluidused.label","كمية سائل الغسل المستخدم"},
{"eMO.EmbalmCompleted.label","اكتمل الغسل"},
{"eMO.ReleaseEmbalmedBody.label","خروج الجثمان المغسل"},
{"eMO.CancelEmbalm.label","إلغاء الغسل"},
{"eMO.ReasonforCancellation.label","سبب إلغاء الغسل"},
{"eMO.CancelEmbalm/ReleaseEmbalm.label","إكمال الغسل / إلغاء الغسل"},
{"eMO.EmbalmRequeiredatHome.label","الغسل في المنزل"},
{"eMO.EmbalmRequeiredatHospital.label","الغسل في المستشفى"},
{"eMO.ApplicantAddress.label","عنوان مقدم الطلب"},
{"eMO.EmbalmAddress.label","عنوان الغسل"},
{"eMO.EmbalmStatus.label","حالة الغسل"},
{"eMO.Canceled.label","ألغيت"},
{"eMO.liter.label","لتر"},
{"eMO.EmbalmRequestDetails.label","تفاصيل طلب الغسل"},
{"eMO.DefaultPreviousClaimantDetails.label","التفاصيل الافتراضية لصاحب المطالبة السابق"},
{"eMO.ViewClaimantHistory.label","عرض سجل المدعي"},
{"eMO.StartingEmbalmNo.label","بدء رقم الغسل"},
{"eMO.NextEmbalmNo.label","رقم الغسل التالي"},
{"eMO.EndEmbalmNo.label","رقم الغسل النهائي"},
{"eMO.EmbalmNoDetailsRequired.label","مطلوب تفاصيل رقم الغسل"},
{"eMO.EmbalmNoFormat.label","تنسيق رقم الغسل"},
{"eMO.CopyApplicantAddress.label","نسخ عنوان مقدم الطلب"},
{"eMO.PrintEmbalmForm.label","طباعة نموذج طلب الغسل"},
{"eMO.MyKad.label","My Kad"},
{"eMO.OtherId.label","تعريف آخر"},
{"eMO.InternalExamination.label","داخلي"},
{"eMO.ExternalExamination.label","خارجي"},
{"eMO.ExaminationType.label","نوع الفحص"},
{"eMO.ReleaseLetterFromEmbassy.label","خطاب إخلاء طرف من السفارة"},
{"eMO.AllowUserRecordPMFindingDetails.label","السماح للمستخدم بتسجيل تفاصيل ملاحظات التشريح"},
{"eMO.DateTimeOfDeath.label","تاريخ و وقت الوفاة"},
{"eMO.AutopsyNo.label","رقم التشريح"},
{"eMO.murder.label","قتل"},
{"eMO.suicide.label","انتحار"},
{"eMO.natural.label","طبيعي"},
{"eMO.undetermined.label","غير محدد"},
{"eMO.unclassified.label","غير مصنف"},
{"eMO.pending.label","قيد الانتظار lx"}

			}; 
}
