/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eCA.resources; 

import java.util.*;

public class  Labels_ar  extends ListResourceBundle implements java.io.Serializable{
public Object[][] getContents() {
         return contents;
    }
 
static final Object[][] contents = {
{"eCA.AbnormalValue.label","نتيجة غير طبيعية"},
{"eCA.AccessedAt.label","متاح عند"},
{"eCA.AccidentEmergency.label","الحوادث والطوارئ"},
{"eCA.ActionBy.label","تم بواسطة"},
{"eCA.AddComplaint.label","اضافة شكوى"},
{"eCA.AddEncounterparameter.label","اضافة بيانات للزيارة"},
{"eCA.AddNewPanel.label","اضافة لوحة جديدة"},
{"eCA.AddNewRow.label","اضافة سطر جديد"},
{"eCA.AdhocIntervention.label","تدخل خاص"},
{"eCA.AdmNo.label","رقم الدخول "},
{"eCA.AdmittedNewborn.label","طفل حديثى الولادة"},
{"eCA.AdmittedNewborns.label","اطفال حديثى الولادة"},
{"eCA.AdmittedPeriod.label","مدة الاقامة"},
{"eCA.AgeCommon.label","العمر المشترك"},
{"eCA.Alive.label","حي"},
{"eCA.AllClinics.label","كل العيادات"},
{"eCA.AllNursingUnits.label","كل  ادوار التمريض"},
{"eCA.AllergicTo.label","حساس لـ"},
{"eCA.AllergyAssessment.label","تقييم الحساسية"},
{"eCA.AllergyList.label","قائمة الحساسية"},
{"eCA.AllowDirect.label","سماح مباشر"},
{"eCA.Allowed.label","مسموح"},
{"eCA.AllowedDocTypes.label","انواع الملفات المسموحة"},
{"eCA.AmendOriginalSection.label","تعديل القسم الاصلي "},
{"eCA.AmendError.label","تعديل/ خطـأ"},
{"eCA.AmendmentType.label","نوع التعديل"},
{"eCA.Anaesthetists.label","اطباء التخدير"},
{"eCA.ApplicableOnlyforTableFormat.label","متاح فقط في صورة اقراص"},
{"eCA.ApplicableTask.label","مهمة قابلة للتنفيذ"},
{"eCA.ApplicabletoProcedures.label","متاح للاجراءات"},
{"eCA.ApplicationDetail.label","تفاصيل التطبيق"},
{"eCA.ApplicationParameter.label","متغير التطبيق"},
{"eCA.ApplicationSetup.label","اعداد التطبيق"},
{"eCA.Arial.label","نوع الخط Arial"},
{"eCA.ArialBlack.label","نوع الخط  Arial Black"},
{"eCA.ArialNarrow.label","نوع الخط Arial Narrow"},
{"eCA.ArrivedatNS.label","وصل إلى وحدة التمريض"},
{"eCA.AssignCAMenu.label","تعيين قائمة شاشة الطبيب"},
{"eCA.AssignChartSummary.label","تعيين ملخص بيانى"},
{"eCA.AssignPatientRelationship.label","تعيين علاقة المريض"},
{"eCA.AssignRelationship.label","تحديد العلاقة"},
{"eCA.AssociateLinking.label","ربط المنتسب"},
{"eCA.AttachedSections.label","الاقسام المرفقة"},
{"eCA.AttachedSectionsForType.label","الاقسام المرفقة لنوع الملاحظة"},
{"eCA.AttendingRelationship.label","العلاقة القائمة"},
{"eCA.Author.label","مفوض"},
{"eCA.AuthorbutwithoutAuthorizationFacility.label","مفوض بدون صلاحية على منشأة"},
{"eCA.AuthorwithAuthorizationFacility.label","مفوض بصلاحية على منشأة"},
{"eCA.AvailableSections.label","الاقسام المتاحة"},
{"eCA.AwaitingReview.label","المراجعة المنتظرة"},
{"eCA.AwaitingSign.label","في إنتظار الإستكمال"},
{"eCA.Babiesof.label","اطفال"},
{"eCA.Backdate.label","يرجع الى تاريخ"},
{"eCA.BackwardDischarge.label","خروج متأخر"},
{"eCA.BackwardVisits.label","الزيارات المتخلفة"},
{"eCA.BaseURL.label","Base URL"},
{"eCA.BlockID.label","رقم البلوك"},
{"eCA.BMICalculator.label","حاسبة مؤشر كتلة الجسم"},
{"eCA.BuildClinicalRepository.label","بناء المستودع السريري"},
{"eCA.BuildClinicalRepositoryForDirectRegn.label","بناء المستودع السريري لمنطقة مباشرة"},
{"eCA.ByPractitionerRights.label","بواسطة حقوق الممارس"},
{"eCA.CAMenu.label","قائمة شاشة الطبيب"},
{"eCA.CanAssign.label","امكانية تعيين"},
{"eCA.CanHold.label","امكانية ايقاف مؤقت"},
{"eCA.CanTerminate.label","امكانية انهاء"},
{"eCA.CannedText.label","نص معلب"},
{"eCA.CannedTextDescription.label","وصف النص المعلب"},
{"eCA.CardiacIndex.label","مؤشر القلب"},
{"eCA.Centigrade.label","مئوية"},
{"eCA.CentigradetoFahrenheit.label","مئوية لفهرنهايت"},
{"eCA.Cerebralperfusionpressure.label","ضغط التروية الدماغي"},
{"eCA.ChangeFileReference.label","تغيير مرجع الملف"},
{"eCA.ChartApplicability.label","قابلية تطبيق الرسم البياني"},
{"eCA.ChartCode.label","كود المخطط"},
{"eCA.ChartComponentAddPanel.label","لوحة إضافة مكون التخطيط"},
{"eCA.ChartComponentHeader.label","رأس مكون التخطيط"},
{"eCA.ChartComponentList.label","قائمة مكونات التخطيط"},
{"eCA.ChartComponents.label","مكونات الرسم البياني"},
{"eCA.ChartEvents.label","أحداث الرسم البياني"},
{"eCA.ChartQueryResult.label","نتيجة استعلام المخطط"},
{"eCA.ChartRecordingControls.label","ضوابط تسجيل الرسم البياني"},
{"eCA.ChartRecordingErrorList.label","قائمة أخطاء تسجيل التخطيط"},
{"eCA.ChartRecordingViewErrorResults.label","نتائج خطأ عرض تسجيل المخطط البياني"},
{"eCA.ChartRecordingViewErrorsToolBar.label","شريط أدوات أخطاء عرض تسجيل المخطط البياني"},
{"eCA.ChartSetup.label","إعداد المخطط"},
{"eCA.ChartSetUpIntermediate.label","إعداد الرسم البياني المتوسط"},
{"eCA.ChartSetUpIntermediateUpdateComponentTable.label","جدول تحديث المكون لانشاء المخطط"},
{"eCA.ChartSummaryContent.label","محتوى ملخص الرسم البياني"},
{"eCA.ChartSummaryTemplate.label","قالب ملخص الرسم البياني"},
{"eCA.ChartSummaryTemplatePreviewof.label","معاينة قالب ملخص الرسم البياني لـ"},
{"eCA.ChartTemplateCreate.label","إنشاء قالب الرسم البياني"},
{"eCA.ChartAddmodify.label","تعديل الرسم البياني"},
{"eCA.ChartComponentAddNew.label","مكون التخطيط إضافة جديد"},
{"eCA.ChartMain.label","الرسم البياني الرئيسي"},
{"eCA.ChartSummaryCareFlowsheet.label","ملخص مخطط جدول قراءات الرعاية المركزة"},
{"eCA.ChatPage.label","صفحة الدردشة"},
{"eCA.Checked.label","تم التحقق"},
{"eCA.ChiefComplaintSearch.label","بحث الشكوى الرئيسية"},
{"eCA.ChiefComplaintSection.label","قسم الشكوى الرئيسية"},
{"eCA.ChiefComplaints.label","الشكوى الرئسية"},
{"eCA.ChiefComplaintMaster.label","ملف الشكوى الرئيسية"},
{"eCA.Clickheretocollapsethecolumn.label","انقر هنا لطي العمود"},
{"eCA.Clickheretoview.label","انقر هنا لعرض"},
{"eCA.ClickheretoviewSecondaryResources.label","انقر هنا لعرض المصادر الثانوية."},
{"eCA.ClicktoAuthorize.label","انقر للتفويض"},
{"eCA.ClicktoNormalize.label","انقر للتطبيع"},
{"eCA.ClinicCommon.label","عيادة مشتركة"},
{"eCA.ClinicEventParam.label","متغير الحدث للعيادة"},
{"eCA.ClinicalCalculator.label","الحاسبة السريرية"},
{"eCA.ClinicalEventGroup.label","مجموعة الأحداث السريرية"},
{"eCA.ClinicalEventMaster.label","ماستر الحدث السريري"},
{"eCA.ClinicalEventParameter.label","متغير الحدث السريري"},
{"eCA.ClinicalEvents.label","الأحداث السريرية"},
{"eCA.ClinicalNoteDetails.label","تفاصيل الملاحظة السريرية"},
{"eCA.ClinicalNoteStatusDetails.label","تفاصيل حالة الملاحظة السريرية"},
{"eCA.ClinicianAccessRichTextEditor.label","شاشة الطبيب - محرر نص منسق"},
{"eCA.ClinicianDesktop.label","الطبيب المكتبي"},
{"eCA.Clinics.label","عيادات"},
{"eCA.CloseDate.label","تاريخ قريب"},
{"eCA.CloseDetails.label","إغلاق التفاصيل"},
{"eCA.Column.label","عمود"},
{"eCA.ComicSansMS.label","نوع الخط Comic Sans MS"},
{"eCA.ComplaintDescription.label","وصف الشكوى"},
{"eCA.ComplaintDetails.label","تفاصيل الشكوى"},
{"eCA.ComplaintDetailsfor.label","تفاصيل الشكوى لـ"},
{"eCA.ComplaintID.label","رقم الشكوى"},
{"eCA.ComplaintText.label","نص الشكوى"},
{"eCA.ComponentDescription.label","وصف القطع"},
{"eCA.ConsEndDate.label","تاريخ انتهاء الاستشارة"},
{"eCA.ConsInProgress.label","الاستشارة قيد النتفيذ"},
{"eCA.ConstantValue.label","قيمة ثابتة"},
{"eCA.ConstructCAMenu.label","إنشاء قائمة شاشة الطبيب"},
{"eCA.ContentDescription.label","وصف المحتوى"},
{"eCA.ContrSystem.label","Contr System"},
{"eCA.CourierNew.label","حامل جديد"},
{"eCA.CreateNewAddendum.label","إنشاء ملحق جديد"},
{"eCA.Creatinineclearance.label","تحليل إفراز الكرياتنين"},
{"eCA.CriticalValue.label","قيمة حرجة"},
{"eCA.CurrentChiefComplaint.label","الشكوى الرئيسة الحالي"},
{"eCA.DataSet.label","مجموعة البيانات"},
{"eCA.DayAfterAdmit.label","بعد يوم من الدخول"},
{"eCA.DayAfterEffect.label","بعد يوم من التأثير"},
{"eCA.DayAfterTransfer.label","بعد يوم من التحويل"},
{"eCA.DaySummaryPeriodFrom.label","فترة ملخص اليوم من"},
{"eCA.DefaultFromHistory.label","افتراضي من التاريخ المرضي"},
{"eCA.DefineChartScope.label","تحديد نطاق المخطط"},
{"eCA.DefineChiefComplaint.label","تحديد رئيس شكوى"},
{"eCA.DefineMenu.label","تحديد القائمة"},
{"eCA.DefinePersonalizedHomePage.label","تحديد الصفحة الرئيسية المخصصة"},
{"eCA.DeltaValue.label","قيمة دلتا"},
{"eCA.Desktop.label","سطح المكتب"},
{"eCA.DetailsofErrorRemarks.label","تفاصيل ملاحظات الخطأ"},
{"eCA.DiagID.label","معرف التشخيص"},
{"eCA.DiagType.label","نوع التشخيص"},
{"eCA.Diagnosisfor.label","التشخيص"},
{"eCA.DiagnosisforChiefComplaint.label","تشخيص الشكوى الرئيسية"},
{"eCA.DiagnosisForCurrentChiefComplaint.label","التشخيص لشكوى الرئيس الحالي"},
{"eCA.DiastolicBloodPressure.label","ضغط الدم الانبساطي"},
{"eCA.DictationWindow.label","نافذة الإملاء"},
{"eCA.DirectIndirectSettings.label","إعدادات مباشرة / غير مباشرة"},
{"eCA.Disable.label","تعطيل"},
{"eCA.Disclaimer.label","اخلاء المسؤولية"},
{"eCA.DisclaimerText.label","نص إخلاء المسؤولية"},
{"eCA.DiscreteMeasureSearch.label","بحث قياس محدد"},
{"eCA.DisplayOrderSequence.label","عرض تسلسل الطلب"},
{"eCA.DisplayRecords.label","سجلات العرض"},
{"eCA.DocumentLinkedNote.label","ملاحظة مرتبطة بالمستند"},
{"eCA.DosageDetails.label","تفاصيل الجرعة"},
{"eCA.DrugDuration.label","مدة الدواء"},
{"eCA.EncounterParameter.label","معطيات الزيارة"},
{"eCA.EncounterRadioButtons.label","اختيارات الزيارة"},
{"eCA.EncounterSummary.label","ملخص الزيارة"},
{"eCA.Encounters.label","زيارات"},
{"eCA.EndingTime.label","نهاية الوقت"},
{"eCA.ErrorMarkedBy.label","تم وضع علامة بواسطة خطأ"},
{"eCA.EstablishRelationship.label","إقامة علاقة"},
{"eCA.EventCaptions.label","تعليق الأحداث"},
{"eCA.EventCode.label","كود الحدث"},
{"eCA.EventDate.label","تاريخ الحدث"},
{"eCA.EventGroup.label","مجموعة الحدث"},
{"eCA.EventItem.label","عنصر الحدث"},
{"eCA.EventSetup.label","إعداد الحدث"},
{"eCA.EventTypeParameter.label","معلمة نوع الحدث"},
{"eCA.EventsFlowSheet.label","جدول متابعة  الأحداث"},
{"eCA.ExtAppParamPanel.label","لوحة تحكم التطبيق الخارجي"},
{"eCA.ExternalApplicationDetail.label","تفاصيل التطبيق الخارجي"},
{"eCA.ExternalID.label","معرف خارجي"},
{"eCA.ExternalName.label","الاسم الخارجي"},
{"eCA.ExtremeObesity.label","السمنة المفرطة 40 إلى 50"},
{"eCA.Fahrenheit.label","فهرنهايت"},
{"eCA.FahrenheittoCentigrade.label","فهرنهايت إلى مئوية"},
{"eCA.FileReference.label","مصدر المعلومات"},
{"eCA.FileSizeLimit.label","حد حجم الملف"},
{"eCA.FirstOperand.label","المعامل الأول"},
{"eCA.FlowSheet.label","شيت الرعاية"},
{"eCA.FlowSheetApplicability.label","إمكانية تطبيق شيت الرعاية"},
{"eCA.FlowSheetComponent.label","مكون شيت الرعاية"},
{"eCA.FlowSheetID.label","معرف شيت الرعاية"},
{"eCA.FlowSheets.label","شيتات الرعاية"},
{"eCA.FomulaConstructionForSummary.label","بناء التركيبةا للملخص"},
{"eCA.Font.label","الخط"},
{"eCA.FormulaConstruction.label","بناء التركيبة"},
{"eCA.FormulaDefinition.label","تعريف التركيبة "},
{"eCA.FormulaDefinitionForChartComponents.label","تعريف التركيبة لمكونات الرسم البياني"},
{"eCA.ForwardTo.label","ارسال الي"},
{"eCA.FromSection.label","من القسم"},
{"eCA.FunctionOptions.label","خيارات الوظيفة"},
{"eCA.FutureFuture.label","المستقبل - المستقبل"},
{"eCA.FutureAppointments.label","المواعيد المستقبلية"},
{"eCA.FutureReferrals.label","الإحالات المستقبلية"},
{"eCA.Garamond.label","نوع الخط Garamond"},
{"eCA.GlomerularFiltrationRate.label","معدل الترشيح الكبيبي"},
{"eCA.Graph.label","رسم بياني"},
{"eCA.GroupButtons.label","أزرار المجموعة"},
{"eCA.GroupNames.label","أسماء المجموعات"},
{"eCA.Groups.label","مجموعات"},
{"eCA.GuideLines.label","القواعد الارشادية"},
{"eCA.Heading.label","عنوان"},
{"eCA.HintMessage.label","رسالة تلميح"},
{"eCA.HistoryRecordType.label","نوع سجل التاريخ"},
{"eCA.HistoryRecordTypes.label","أنواع سجلات المحفوظات"},
{"eCA.HourAfterAdmit.label","ساعة بعد الدخول"},
{"eCA.HourAfterEffect.label","ساعة بعد التأثير"},
{"eCA.HourAfterTransfer.label","ساعة بعد التحويل"},
{"eCA.HPI.label","تاريخ المرض الحالي"},
{"eCA.ImageForSection.label","صورة للقسم"},
{"eCA.ImageLinked.label","الصورة مرتبطة"},
{"eCA.ImageReference.label","مرجع الصورة"},
{"eCA.ImageReferenceID.label","معرف مرجع الصورة"},
{"eCA.ImmunizationDetails.label","تفاصيل التحصين"},
{"eCA.Impression.label","الانطباع"},
{"eCA.IncludeonlythefilledComponents.label","قم بتضمين المكونات المعبأة فقط"},
{"eCA.IncludesDate.label","يشمل التاريخ"},
{"eCA.Indication.label","إشارة"},
{"eCA.InsertLeft.label","أدخل اليسار"},
{"eCA.InsertRight.label","أدخل اليمين"},
{"eCA.InterventionDetails.label","تفاصيل التدخل"},
{"eCA.Intracranialpressure.label","الضغط داخل الجمجمة"},
{"eCA.IPAdmit.label","دخول المرضى الداخلى"},
{"eCA.IPEnc.label","زيارات المرضي الداخلى"},
{"eCA.Kilogram.label","كيلوغرام"},
{"eCA.KilogramtoPounds.label","كيلوغرام إلى رطل"},
{"eCA.LifeTime.label","وقت الحياة"},
{"eCA.LimitPractitionerListtoAccessLocation.label","تحديد قائمة الممارسين للوصول إلى الموقع"},
{"eCA.LimittoCurrentEncounter.label","الحد من اللقاء الحالي"},
{"eCA.LinkHistoryElementsFor.label","ربط عناصر التاريخ ل"},
{"eCA.LinkResultDocuments.label","وثائق نتيجة الارتباط"},
{"eCA.LinkingImagesForSection.label","ربط الصور للقسم"},
{"eCA.LinkingListItems.label","ربط عناصر القائمة"},
{"eCA.ListText.label","نص القائمة"},
{"eCA.LMP.label","اخر دورة طمث"},
{"eCA.LocationforPractitioner.label","موقع الممارس"},
{"eCA.LocationTypeFrom.label","نوع الموقع من"},
{"eCA.Long.label","طويل"},
{"eCA.LookUpfor.label","ابحث عن"},
{"eCA.LOS.label","مدة  الاقامة"},
{"eCA.MainFrame.label","الاطار الرئيسي"},
{"eCA.MainSection.label","القسم الرئيسي"},
{"eCA.MainSectionCode.label","كود القسم الرئيسي"},
{"eCA.MainSectionDesc.label","وصف القسم الرئيسي"},
{"eCA.MarkallasError.label","علم على الكل خطأ"},
{"eCA.MarkedasErrorList.label","مؤشر عليه كخطأ في القائمة"},
{"eCA.MarkedforError.label","مؤشر عليه كخطأ "},
{"eCA.Meanarterialbloodpressure.label","متوسط ​​ضغط الدم الشرياني"},
{"eCA.MeanBloodPressure.label","متوسط ضغط الدم"},
{"eCA.MedicalEvents.label","الأحداث الطبية"},
{"eCA.MenuOptions.label","خيارات القائمة"},
{"eCA.MenuStructure.label","هيكل القائمة"},
{"eCA.Minus.label","ناقص"},
{"eCA.MothersBed.label","سرير الأم #"},
{"eCA.MothersID.label","معرف الأم"},
{"eCA.MotherLinkExists.label","رابط الام موجود"},
{"eCA.Motherof.label","أم لـ"},
{"eCA.NewBornList.label","قائمة المواليد الجدد"},
{"eCA.NewBornEncounterID.label","معرف زيارة المولود الجديد"},
{"eCA.NewBornID.label","معرفالمولود الجديد"},
{"eCA.NewBornLocation.label","موقع المولود الجديد"},
{"eCA.NewBornName.label","اسم المولود الجديد"},
{"eCA.NewFileReference.label","مرجع ملف جديد"},
{"eCA.NoofRows.label","عدد الصفوف"},
{"eCA.NonCritical.label","غير حرج"},
{"eCA.Normal185to24.label","عادي 18.5 إلى 24"},
{"eCA.Normal25to36LminM2.label","عادي 2.5 إلى 3.6 لتر / دقيقة / م 2"},
{"eCA.NormalInd.label","مؤشر طبيعى"},
{"eCA.NormalmeanBPis93.3mmHg.label","متوسط ​​ضغط الدم الطبيعي هو 93.3 مم زئبق"},
{"eCA.NormalRange.label","المعدل الطبيعي"},
{"eCA.NormalcyStatus.label","الحالة الطبيعية"},
{"eCA.NotAllowed.label","غير مسموح"},
{"eCA.NoteDisclaimer.label","ملاحظة إخلاء المسؤولية"},
{"eCA.NoteGroup.label","مجموعة الملاحظات"},
{"eCA.NoteImageList.label","قائمة صور الملاحظة"},
{"eCA.Noteparameter.label","ملاحظة المعلمة"},
{"eCA.NoteTitle.label","عنوان الملاحظة"},
{"eCA.NoteTypebyService.label","نوع الملاحظة حسب الخدمة"},
{"eCA.NoteTypeForResponosibilityDetails.label","نوع الملاحظة للحصول على تفاصيل المسؤولية"},
{"eCA.NoteTypeForResponosibilityHeader.label","نوع الملاحظة لمقدمة المسؤولية"},
{"eCA.NoteTypeForResponosibilityResults.label","نوع الملاحظة لنتائج المسؤولية"},
{"eCA.NoteTypeforResponsibility.label","نوع الملاحظة للمسؤولية"},
{"eCA.NoteTypeFrom.label","نوع الملاحظة من"},
{"eCA.NoteTypeSection.label","قسم نوع الملاحظة"},
{"eCA.NoteTypes.label","أنواع الملاحظات"},
{"eCA.NOTESHEADERINFORMATION.label","بيانات مقدمة الملاحظات"},
{"eCA.Notescontent.label","محتوى الملاحظات"},
{"eCA.NotesPrintPreviewView.label"," عرض معاينة طباعة الملاحظات"},
{"eCA.NumofNotePerEncounter.label","عدد الملاحظات في كل زيارة"},
{"eCA.NurseRelation.label","علاقة الممرضة"},
{"eCA.NursingUnits.label","وحدات التمريض"},
{"eCA.Onset.label","بداية"},
{"eCA.OnsetDetails.label","تفاصيل البداية"},
{"eCA.OPVisit.label","زيارة مريض خارجي"},
{"eCA.OrderSequenceNumber.label","رقم تسلسل الطلب "},
{"eCA.OSCCMLCCase.label","حالة قانونية طبية / OSCC"},
{"eCA.Overweight25to29.label","زيادة الوزن من 25 إلى 29"},
{"eCA.Paragraph.label","فقرة"},
{"eCA.ParsingSectionTemplate.label","قالب قسم الترجمة"},
{"eCA.PastVisits.label","الزيارات السابقة"},
{"eCA.PatientChartSummaryTemplatePreview.label","معاينة قالب ملخص مخطط المريض"},
{"eCA.PatientProfile.label","الملف الشخصي للمريض"},
{"eCA.PatientProfileContent.label","محتوى الملف الشخصي للمريض"},
{"eCA.PatientRelatedTreatments.label","العلاجات المتعلقة بالمريض"},
{"eCA.Percentage.label","النسبة المئوية"},
{"eCA.PerformedDetails.label","التفاصيل المنفذة"},
{"eCA.PeriodRange.label","نطاق الفترة"},
{"eCA.PersonalizedHomePage.label","الصفحة الرئيسية المخصصة"},
{"eCA.PlasmaCreatinine.label","كرياتينين البلازما"},
{"eCA.Plus.label","زائد"},
{"eCA.PostProcedureStdOrders.label","اوردرات ما بعد العملية"},
{"eCA.Pounds.label","جنيه أو رطل للوزن"},
{"eCA.PoundstoKilogram.label","جنيه إلى كيلوغرام"},
{"eCA.PractitionerHomePage.label","الصفحة الرئيسية للممارس الطبي"},
{"eCA.PreImage.label","الصورة المسبقة"},
{"eCA.PreconditionforRecording.label","شرط مسبق للتسجيل"},
{"eCA.PreserveTemplateFormat.label","الحفاظ على تنسيق القالب"},
{"eCA.PreviewNotes.label","معاينة الملاحظات"},
{"eCA.PrintDischargeSummaryHeader.label","طباعة مقدمة ملخص الخروج"},
{"eCA.ProblemDetails.label","تفاصيل المشكلة"},
{"eCA.ProcedureApplicable.label","الإجراء المطبق"},
{"eCA.ProcedureSet.label","مجموعة الإجراءات"},
{"eCA.ProcedureSummary.label","ملخص الإجراء"},
{"eCA.ProceduresIntermediate.label","متوسط ​​الإجراءات"},
{"eCA.ProfileContent.label","محتوى الملف الشخصي"},
{"eCA.PromptText.label","نص موجه"},
{"eCA.PublishLevel.label","مستوى النشر"},
{"eCA.QuickText.label","نص سريع"},
{"eCA.Relink.label","إعادة الارتباط"},
{"eCA.RebuildSectionTemplate.label","نموذج اعادة القسم"},
{"eCA.RecDate.label","تاريخ التسجيل"},
{"eCA.ReceiveMessage.label","تلقي رسالة"},
{"eCA.RecordClinicalNotesToolbar.label"," شريط أدوات سجل الملاحظات السريرية"},
{"eCA.RecordedClosedBy.label","مسجل / مغلق بواسطة"},
{"eCA.RecordingClinicalNotes.label","تسجيل الملاحظات السريرية"},
{"eCA.RedCellVolumeinAdultsbasedonBodySurfaceArea.label","حجم الخلايا الحمراء عند البالغين بناءً على مساحة سطح الجسم"},
{"eCA.RedefineCAOption.label","أعد تعريف خيار  شاشة الطبيب"},
{"eCA.RefDate.label","تاريخ المرجع"},
{"eCA.ReferenceRange.label","مدى القيم الطبيعية"},
{"eCA.ReferralRelation.label","علاقة الإحالة"},
{"eCA.ReferralReln.label","علاقة الإحالة"},
{"eCA.ReferralsMadeTo.label","الإحالات المقدمة إلى"},
{"eCA.RelatedPatientHistoryCriteria.label","معايير تاريخ المريض ذات الصلة"},
{"eCA.RelationshipforResponsibility.label","علاقة  المسؤولية"},
{"eCA.RelationshipID.label","معرف العلاقة"},
{"eCA.RelationshipName.label","اسم العلاقة"},
{"eCA.RelationshipPeriod.label","فترة العلاقة"},
{"eCA.ReplaceRemarks.label","استبدال الملاحظات"},
{"eCA.ReportHeader.label","مقدمةالتقرير"},
{"eCA.RequestedAt.label","مطلوب في"},
{"eCA.ResearchCategory.label","فئة البحث"},
{"eCA.ResearchCategoryDescription.label","وصف فئة البحث"},
{"eCA.ResearchCategoryID.label","معرف فئة البحث"},
{"eCA.ResearchDescription.label","وصف البحث"},
{"eCA.ResearchInfo.label","معلومات البحث"},
{"eCA.ResearchPatient.label","مريض البحث"},
{"eCA.ResearchPatientCategory.label","فئة مريض البحث"},
{"eCA.ResearchRemarks.label","ملاحظات البحث"},
{"eCA.ResultCategory.label","فئة النتيجة"},
{"eCA.Resultlinked.label","النتيجة مرتبطة"},
{"eCA.ReturnfromInvest.label","العائد من الاستثمار"},
{"eCA.ReviewNotes.label","ملاحظات المراجعة"},
{"eCA.ReviewResults.label","مراجعة النتائج"},
{"eCA.ReviewedBy.label","تمت مراجعته من قبل"},
{"eCA.ReviewerPrivilegeforVerifyingandAuthorization.label","امتياز المراجع للتحقق والتفويض"},
{"eCA.RichTextEditorandMEDIPainter.label","محرر نص منسق و الرسام"},
{"eCA.RichTextEditorforSectionTemplateLongText.label","محرر نص منسق لقالب القسم نص طويل"},
{"eCA.Row.label","صف"},
{"eCA.SansSerif.label","Sans Serifخط"},
{"eCA.SecondOperand.label","المعامل الثاني"},
{"eCA.SectionforNoteType.label","قسم لنوع الملاحظة"},
{"eCA.SectionHeading.label","عنوان القسم"},
{"eCA.SectionScope.label","نطاق القسم"},
{"eCA.SectionStartsWith.label","يبدأ القسم بـ"},
{"eCA.SectionTemplate.label","قالب القسم"},
{"eCA.SectionTemplateToolbar.label","شريط أدوات قالب القسم"},
{"eCA.SectionsForChart.label","أقسام للرسم البياني"},
{"eCA.Serumcreatinine.label","الكرياتينين في الدم"},
{"eCA.ServiceName.label","اسم الخدمة"},
{"eCA.ServiceFacilitySpecific.label","خدمة / مرفق محدد"},
{"eCA.Services.label","خدمات"},
{"eCA.ShiftRows.label","تحول الصفوف"},
{"eCA.ShiftthisRowby.label","تحويل هذا الصف بمقدار"},
{"eCA.Short.label","قصيرة"},
{"eCA.ShowNotes.label","اظهار الملاحظات"},
{"eCA.SignNotes.label","توقيع الملاحظات"},
{"eCA.Size.label","حجم"},
{"eCA.SpecialityDesc.label","وصف التخصص"},
{"eCA.SpecialtySpecificIndirectRelationship.label","علاقة تخصص غير مباشرة محددة"},
{"eCA.SpecimenSent.label","العينة المرسلة"},
{"eCA.StartingTime.label","وقت البدء"},
{"eCA.Statuschattingwith.label","الحالة: الدردشة مع"},
{"eCA.SubSectionCode.label","رمز القسم الفرعي"},
{"eCA.SubSectionDescription.label","وصف القسم الفرعي"},
{"eCA.SubSectionMain.label","القسم الفرعي الرئيسي"},
{"eCA.Subject.label","موضوع"},
{"eCA.SubSectionforMainSection.label","قسم فرعي للقسم الرئيسي"},
{"eCA.SubSectionsfor.label","أقسام فرعية لـ"},
{"eCA.SUM.label","ملخص"},
{"eCA.SummaryBy.label","ملخص بواسطة"},
{"eCA.SummaryColumn.label","عمود الملخص"},
{"eCA.SummaryDesc.label","ملخص تنازلي"},
{"eCA.SummaryID.label","معرف الملخص"},
{"eCA.SummaryLegend.label","علامة المخلص"},
{"eCA.SummaryRequired.label","الملخص مطلوب"},
{"eCA.SummaryType.label","نوع الملخص"},
{"eCA.SupportingDiagCode.label","دعم كود التشخيص"},
{"eCA.SwitchOptions.label","تبديل الخيارات"},
{"eCA.SystolicBloodPressure.label","ضغط دم انقباضي"},
{"eCA.Tableforchat.label","طاولة للدردشة"},
{"eCA.TaskDesc.label","وصف المهمة"},
{"eCA.TaskforRespMainFrame.label","مهمة Resp Main Frame"},
{"eCA.TaskForResponosibilityRelationshipDetails.label","مهمة للمسؤولية / تفاصيل العلاقة"},
{"eCA.TaskForResponosibilityRelationshipHeader.label","مهمة للمسؤولية /مقدمة العلاقة"},
{"eCA.TaskForResponsibilityRelationship.label","مهمة للمسؤولية / العلاقة"},
{"eCA.TaskID.label","معرف المهمة"},
{"eCA.TaskType.label","نوع المهمة"},
{"eCA.TasksSearch.label","البحث عن المهام"},
{"eCA.TemplateBased.label","نموذج قائم"},
{"eCA.TerminateRelation.label","إنهاء العلاقة"},
{"eCA.TextBlockID.label","معرف الفقرة"},
{"eCA.ThisEncounterisnotaReferral.label","هذه الزيارة ليست إحالة"},
{"eCA.TimesNewRoman.label","Times New Romanخط"},
{"eCA.TitleValue.label","قيمة العنوان"},
{"eCA.ToSection.label","إلى القسم"},
{"eCA.Tools.label","أدوات"},
{"eCA.Transcriber.label","الناسخ"},
{"eCA.TraumaCaseDetail.label","تفاصيل حالة التصادم"},
{"eCA.TriageDetail.label","تفاصيل الفرز"},
{"eCA.Unchecked.label","لم يتم التحقق منه"},
{"eCA.UserDefinedDescription.label","وصف محدد من قبل المستخدم"},
{"eCA.UserTree.label","شجرة المستخدم"},
{"eCA.Verdana.label","Verdanaخط "},
{"eCA.ViewErrorDocuments.label","عرض مستندات الخطأ"},
{"eCA.ViewList.label","عرض القائمة"},
{"eCA.ViewonlyPrivilege.label","عرض الامتياز فقط"},
{"eCA.ViewPatientListbyLocation.label","عرض قائمة المرضى حسب الموقع"},
{"eCA.ViewPatientListbyMedicalService.label","عرض قائمة المرضى حسب الخدمة الطبية"},
{"eCA.ViewPatientListbyProviderService.label","عرض قائمة المرضى حسب مقدم الخدمة"},
{"eCA.ViewReferralDetails.label","عرض تفاصيل الإحالة"},
{"eCA.ViewClinicalNote.label","عرض الملاحظات السريرية"},
{"eCA.VisitAdmCloseDate.label","تاريخ اغلاق الزيارة"},
{"eCA.VisitAdmEndDate.label","تاريخ انتهاء الزيارة"},
{"eCA.VisitCloseDate.label","تاريخ اغلاق الزيارة"},
{"eCA.VSRecorded.label","مسجل VS"},
{"eCA.Wingdings.label","أجنحة"},
{"eCA.XSLfolder.label","مجلد XSL"},
{"eCA.Constant.label","ثابت"},
{"eCA.FlowSheetView.label","عرض شيت الرعاية"},
{"eCA.NormalCPP.label","ضغط التروية الدماغي طبيعي"},
{"eCA.TypeYourMessagehere.label","اكتب رسالتك هنا"},
{"eCA.BuildingNotes.label","ملاحظات البناء"},
{"eCA.AddendumToNote.label","ملحق للملاحظة"},
{"eCA.NewbornExists.label","المولود موجود"},
{"eCA.NoPPRelationship.label","لا علاقة PP"},
{"eCA.SelectedEncounter.label","الزيارة المحددة"},
{"eCA.ActiveOnly.label","نشط فقط"},
{"eCA.AddNewComments.label","أضف تعليقات جديدة"},
{"eCA.AddYourAddendumBelow.label","أضف الملحق الخاص بك أدناه"},
{"eCA.AllNotes.label","كل الملاحظات"},
{"eCA.ApplicationTask.label","مهمة التطبيق"},
{"eCA.AssociatedContributingEvents.label","الأحداث المساهمة المصاحبة"},
{"eCA.AssociatedEventGroups.label","مجموعات الأحداث المصاحبة"},
{"eCA.BMIValue.label","قيمة مؤشر كتلة الجسم"},
{"eCA.CHARTSUMMARY.label","ملخص الرسم البياني"},
{"eCA.CheckBox.label","خانة الاختيار"},
{"eCA.Comment.label","تعليق"},
{"eCA.CommonRemarks.label","ملاحظات مشتركة"},
{"eCA.Constants.label","الثوابت"},
{"eCA.CurrentlySelectedComponentismarkedforrepositioning.label","المكون المحدد حاليًا تم تمييزه لإعادة تحديد موضعه."},
{"eCA.DefineRedifineFormulaSection.label","تعريف / إعادة تعريف قسم الصيغة:"},
{"eCA.Detailsason.label","التفاصيل في"},
{"eCA.ErrorDetails.label","تفاصيل الخطأ"},
{"eCA.ErrorMarkedDate.label","تاريخ وضع علامة خطأ "},
{"eCA.ExistingComments.label","التعليقات الموجودة"},
{"eCA.EXTERNALAPPLICATION.label","تطبيق خارجي"},
{"eCA.FinalSelection.label","الاختيار النهائي"},
{"eCA.FrequencywithDurationvalue.label","التردد مع قيمة المدة"},
{"eCA.HOMEPAGE.label","الصفحة الرئيسية"},
{"eCA.IBAHealth.label","IBA Health"},
{"eCA.Immunization.label","تطعيم"},
{"eCA.Impressions.label","الانطباعات"},
{"eCA.LastRecordedDateTime.label","آخر وقت تم تسجيله:"},
{"eCA.LinkedParameters.label","المتغيرات المرتبطة"},
{"eCA.LOCATIONACCESS.label","الوصول إلى الموقع"},
{"eCA.Men.label","رجال"},
{"eCA.MySchedules.label","جداولى"},
{"eCA.MyTaskList.label","قائمة المهام الخاصة بي"},
{"eCA.NormalcyIndication.label","مؤشر Normalcy"},
{"eCA.NoteTypeDesc.label","نوع الملاحظة تنازليا"},
{"eCA.NotesView.label","طريقة عرض الملاحظات"},
{"eCA.Obesity.label","بدانة"},
{"eCA.OPBookings.label","حجوزات الخارجي"},
{"eCA.Operators.label","العاملين"},
{"eCA.OTBookings.label","حجوزات الخارجي"},
{"eCA.PARAMETER.label","معامل/مدخل"},
{"eCA.PerfomedBy.label","معطر بقلم"},
{"eCA.PlacingOption.label","وضع الخيار"},
{"eCA.PostProcStdOrders.label","اوردرات ما بعد العملية"},
{"eCA.ProcNarration.label","رواية العملية"},
{"eCA.RecordingClinicalNotesTabs.label","تسجيل الملاحظات السريرية - علامات التبويب"},
{"eCA.RedCellVolume.label","حجم الخلية الحمراء"},
{"eCA.ReferralPatients.label","مرضى الإحالة"},
{"eCA.ReplaceValue.label","استبدل القيمة"},
{"eCA.ResultsforReview.label","نتائج للمراجعة"},
{"eCA.RichTextEditor.label","معالج النصوص"},
{"eCA.SelectSection.label","حدد القسم"},
{"eCA.SelectDependentComponents.label","حدد المكونات التابعة"},
{"eCA.SelectSubSection.label","حدد القسم الفرعي"},
{"eCA.SelectedForErrorAmend.label","تم التحديد للخطأ / التعديل"},
{"eCA.SelectedItems.label","عناصر مختارة"},
{"eCA.Span.label","امتداد"},
{"eCA.Nohistorydata.label","لا توجد بيانات محفوظات موجودة لآخر 24 ساعة"},
{"eCA.NoPatientcaredata.label","لم يتم العثور على بيانات رعاية المرضى لآخر زيارتين"},
{"eCA.NoResultdata.label","لم يتم العثور على بيانات نتيجة لآخر زيارتين"},
{"eCA.ViewAll.label","مشاهدة الكل"},
{"eCA.ViewPatientAllergyCriteriaJSP.label","عرض معايير حساسية المريض"},
{"eCA.ViewPatientListbyLocationResultMain.label","عرض قائمة المرضى حسب نتيجة الموقع"},
{"eCA.ViewPatientListbyMedServiceResultMain.label","عرض قائمة المرضى عن طريق MedService Result Main"},
{"eCA.Women.label","نساء"},
{"eCA.NumberofUsers.label","عدد المستخدمين"},
{"eCA.Restrict.label","بقييد"},
{"eCA.PrevNotes.label","ملاحظات سابقة"},
{"eCA.LinkDoc.label","رابط الوثيقة"},
{"eCA.HideHeader.label","إخفاء الرأس"},
{"eCA.ViewPatientListbyPPRelationResult.label","عرض قائمة المرضى حسب نتيجة PPRelation"},
{"eCA.HealthNewBorns.label","المواليد الجدد الأصحاء"},
{"eCA.HealthNewBorn.label","مولود بصحة جيدة"},
{"eCA.MothersName.label","اسم الأم"},
{"eCA.DuetoExpireExpired.label","على وشك الانتهاء / منتهية الصلاحية"},
{"eCA.PendingSignature.label","التوقيع المعلق"},
{"eCA.PendingReview.label","في انتظار المراجعة"},
{"eCA.ViewPatientProviderRelation.label","عرض العلاقة بين جهة التامين والمريض"},
{"eCA.CarePendSch.label","جدول الرعاية المعلقة"},
{"eCA.BirthRegister.label","سجل الميلاد"},
{"eCA.MoreDtlRef.label","مزيد من التفاصيل"},
{"eCA.Viewgraph.label","مشاهدة الرسم البياني"},
{"eCA.ModifyScope.label","تعديل النطاق"},
{"eCA.SelectedSubSections.label","أقسام فرعية مختارة"},
{"eCA.NoofColumns.label","عدد الأعمدة"},
{"eCA.Configuration.label","تهيئة"},
{"eCA.Showdetail.label","أظهر تفاصيل"},
{"eCA.PreviewTemplate.label","معاينة القالب"},
{"eCA.CollapseAll.label","اغلاق الجميع"},
{"eCA.DefaultMenu.label","القائمة الافتراضية"},
{"eCA.Validate.label","تحقق"},
{"eCA.LinkHistory.label","تاريخ الارتباط"},
{"eCA.Upload.label","رفع"},
{"eCA.Backward.label","الى الوراء"},
{"eCA.ShowHeader.label","إظهار المقدمة"},
{"eCA.ShowImage.label","إظهار الصورة"},
{"eCA.ShowBoth.label","عرض كلاهما"},
{"eCA.ShowEditor.label","عرض محرر"},
{"eCA.AcrossEncounter.label","عبر الزيارة"},
{"eCA.MotherDetail.label","تفاصيل الأم"},
{"eCA.GestationalPeriod.label","فترة الحمل"},
{"eCA.Calculate.label","احسب"},
{"eCA.CardiacOutput.label","Cardiac Output"},
{"eCA.Zoom.label","تكبير"},
{"eCA.ViewErrorList.label","عرض قائمة الأخطاء"},
{"eCA.Send.label","إرسال"},
{"eCA.Better.label","أفضل"},
{"eCA.Worse.label","أسوأ"},
{"eCA.Medications.label","الأدوية"},
{"eCA.PatientMarkers.label","علامات المريض"},
{"eCA.Show.label","تبين"},
{"eCA.SignOut.label","خروج"},
{"eCA.NoDataForEventInGraph.label","بالنسبة لهذا الحدث ، لا توجد قيمة لعرضها في الرسم البياني"},
{"eCA.IncudeOthersUnsignedNotes.label","قم بتضمين ملاحظات الآخرين غير الموقعة"},
{"eCA.ComplaintBased.label","تمت الشكوى"},
{"eCA.DAPrepared.label","تم إعداد نصيحة الخروج"},
{"eCA.DiagnosisRec.label","تم تسجيل التشخيص"},
{"eCA.BedAssigned.label","سرير مخصص"},
{"eCA.QNo.label","رقم السؤال"},
{"eCA.QPr.label","Q/Pr"},
{"eCA.Signed.label","تم التوقيع"},
{"eCA.MarkedasError.label","تم وضع علامة خطأ"},
{"eCA.ShowSelectedItem.label","إظهار العنصر المحدد"},
{"eCA.DaySummary.label","ملخص اليوم"},
{"eCA.DaySum.label","اليوم / المجموع"},
{"eCA.EventGroupCode.label","رمز مجموعة الحدث"},
{"eCA.FileUpload.label","تحميل الملف"},
{"eCA.ContributingSystem.label","Contra System"},
{"eCA.MarkasError.label","وضع علامة كخطأ"},
{"eCA.RemarksforModify.label","ملاحظات للتعديل"},
{"eCA.ForwardNotesTo.label","ملاحظات إلى الأمام"},
{"eCA.AddendumCreatedBy.label","المحق تم بواسطة "},
{"eCA.AVG.label","AVG"},
{"eCA.CorkCroft.label","CockCroft"},
{"eCA.Axis.label","محور"},
{"eCA.KeyValue.label","القيمة الرئيسية"},
{"eCA.Static.label","ثابتة"},
{"eCA.IntervalBased.label","الفاصل الزمني"},
{"eCA.Median.label","متوسط"},
{"eCA.Trans.label","عبر"},
{"eCA.AddRows.label","أضف صفوفًا"},
{"eCA.PastRecords.label","السجلات السابقة"},
{"eCA.PastRecordsScope.label","نطاق السجلات السابقة"},
{"eCA.StandardView.label","طريقة العرض الرئيسية"},
{"eCA.Graphs.label","الرسوم البيانية"},
{"eCA.RegularGraph.label","رسم بياني منتظم"},
{"eCA.SpecialGraph.label","رسم بياني خاص"},
{"eCA.SpecialChartLinks.label","ارتباطات التخطيط الخاصة"},
{"eCA.SpecificView.label","عرض محدد"},
{"eCA.CustomView.label","عرض مخصصة"},
{"eCA.GroupingEvents.label","أحداث التجميع"},
{"eCA.SpecialChartKey.label","مفتاح الرسم البياني الخاص"},
{"eCA.SpecialChartGraph.label","رسم بياني خاص"},
{"eCA.SpecialChartRef.label","مرجع الرسم البياني الخاص"},
{"eCA.GrowthChart.label","الرسم البياني للنمو"},
{"eCA.PRDetails.label","تفاصيل سجل المريض"},
{"eCA.CurrentQueue.label","قائمة الانتظار الحالية"},
{"eCA.SpecialityEvent.label","حدث التخصص"},
{"eCA.ComparisionView.label","عرض المقارنة"},
{"eCA.ComparisionGraph.label","الرسم البياني للمقارنة"},
{"eCA.GeneralGraph.label","الرسم البياني العام"},
{"eCA.OrderSequence.label","ترتيب الطلب"},
{"eCA.AutoClosePeriod.label","فترة الإغلاق التلقائي"},
{"eCA.AutoCloseType.label","نوع الإغلاق التلقائي"},
{"eCA.ForceClose.label","اغلاق اجباري"},
{"eCA.SpecialityTasksForEvents.label","مهام التخصص للأحداث"},
{"eCA.ClinicianAccessTasks.label","مهام بوابة  الطبيب"},
{"eCA.SpecialityEpisodeCycle.label","دورة حلقة التخصص"},
{"eCA.EpisodeDescription.label","وصف الحلقة"},
{"eCA.EventTitleDescription.label","وصف عنوان الحدث"},
{"eCA.NoOfTransactionsAllowed.label","عدد المعاملات المسموح بها"},
{"eCA.AvailableTasks.label","المهام المتاحة"},
{"eCA.SpecialtyTaskStartsWith.label","تبدأ مهمة التخصص"},
{"eCA.SpecialtyTaskDescription.label","وصف مهمة التخصص"},
{"eCA.SpecialtyTaskHeaderCode.label","كود مقدمة مهمة التخصص"},
{"eCA.SpecialtyEventOutcome.label","نتيجة الحدث التخصصي"},
{"eCA.AvailableOutcomes.label","النتائج المتاحة"},
{"eCA.AttachedOutcomes.label","النتائج المرفقة"},
{"eCA.CloseEpisode.label","إغلاق الحلقة"},
{"eCA.AttachedTasks.label","المهام المرفقة"},
{"eCA.Icon.label","أيقونة"},
{"eCA.CurrentSelection.label","الإختيار الحالي"},
{"eCA.ViewSpecialtyEventHistory.label","عرض تاريخ الأحداث التخصصية"},
{"eCA.SpecialityMasterCode.label","كود التخصص الرئيسي"},
{"eCA.MasterCategory.label","الفئة الرئيسية "},
{"eCA.SpecialityAssesmentTask.label","مهمة تقييم التخصص"},
{"eCA.Foetus.label","الجنين"},
{"eCA.SpecialityEventDesc.label","وصف الحدث التخصصي"},
{"eCA.Cycle.label","دورة"},
{"eCA.tilldate.label","حتى تاريخ"},
{"eCA.SelectCycle.label","حدد دورة "},
{"eCA.ScrolltoCycle.label","مرر إلى دورة "},
{"eCA.RecMaternityconsPrinting.label","استشارة زيارة الام للطباعة"},
{"eCA.RecMaternityconsView.label","استشارة زيارة الام للعرض"},
{"eCA.NonSpecific.label","غير محدد"},
{"eCA.RecMaternityConsMain.label","استشارة زيارة الام الرئيسية"},
{"eCA.ClickHereToCreateaNewEvent.label","انقر هنا لإنشاء حدث جديد"},
{"eCA.MaternityHomePage.label","الصفحة الرئيسية للأمومة"},
{"eCA.ClickHereToViewTheGraph.label","انقر هنا لعرض الرسم البياني"},
{"eCA.PrintHeaderLogo.label","تسمية رأس الطباعة"},
{"eCA.PrintHeaderImageList.label","طباعة قائمة صورة الرأس"},
{"eCA.ChangeIfPatIdGiven.label","يمكن أن يتغير فقط إذا تم إعطاء معرف المريض أو إذا كان ضمن النطاق"},
{"eCA.NonEncSpecific.label","غير محدد الزيارة"},
{"eCA.Inchs.label","بوصة"},
{"eCA.SiteForVaccine.label","موقع للقاح"},
{"eCA.VaccineCategory.label","فئة اللقاح"},
{"eCA.CanBeUsedAsAdhoc.label","هل يمكن استخدامها كمخصص؟"},
{"eCA.DuplicateCheckRecquired.label","مطلوب تحقق مكرر؟"},
{"eCA.DuplicateCheckDays.label","أيام فحص مكرر"},
{"eCA.DuplicateCheckAction.label","إجراء تحقق مكرر"},
{"eCA.VaccinesForCategory.label","لقاحات للفئة"},
{"eCA.CategoryId.label","معرف الفئة"},
{"eCA.VaccineDescription.label","وصف اللقاح"},
{"eCA.SelectVaccine.label","اختر لقاح"},
{"eCA.VaccineNoDoses.label","عدد الجرعات"},
{"eCA.VaccinePrevAdministered.label","تحقق من االتناول السابق"},
{"eCA.VaccinePrevDays.label","تحقق من الأيام السابقة"},
{"eCA.VaccinePreAction.label","تحقق من الإجراء السابق"},
{"eCA.AllowMultiple.label","السماح المتعدد"},
{"eCA.VaccinationSchedule.label","الجدول الزمني للتطعيم"},
{"eCA.SelectedSites.label","مواقع مختارة"},
{"eCA.SelectSite.label","حدد الموقع"},
{"eCA.PendingReferrals.label","الإحالات المعلقة"},
{"eCA.ViewReferralPatientList.label","عرض قائمة المرضى المحالين"},
{"eCA.ActualDate.label","التاريخ الفعلي"},
{"eCA.AdministerDate.label","تاريخ الإدارة"},
{"eCA.BatchNumber.label","رقم الدفعة"},
{"eCA.AdministerDetails.label","إدارة التفاصيل"},
{"eCA.ExternalAdminister.label","اعطاء خارجي"},
{"eCA.CreatingUser.label","إنشاء المستخدم"},
{"eCA.ExistingSchedules.label","الجداول الحالية"},
{"eCA.ReferralStatus.label","حالة الإحالة"},
{"eCA.ForAMonth.label","لمدة شهر"},
{"eCA.ForAPeriodRange.label","لنطاق الفترة"},
{"eCA.Consults.label","قائمة الاستشارة"},
{"eCA.StillbornDeceased.label","ميت / متوفى"},
{"eCA.AllPatients.label","كل المرضى"},
{"eCA.Future.label","مستقبلى"},
{"eCA.TimeInterval.label","الفاصل الزمني"},
{"eCA.MyFilter.label","فلتر"},
{"eCA.ShowTimeInterval.label","إظهار الفاصل الزمني"},
{"eCA.Ongoing.label","مستمر"},
{"eCA.MedAdmin.label","مشرف متوسط"},
{"eCA.PatientCare.label","رعاية المرضى"},
{"eCA.CustomizeIcons.label","تخصيص الرموز"},
{"eCA.CurrentPrivilege.label","الامتياز الحالي"},
{"eCA.NoteHeader.label","رأس الملاحظة"},
{"eCA.HeaderType.label","نوع الرأس"},
{"eCA.DefineHeader.label","تحديد الرأس"},
{"eCA.TemplateType.label","نوع النموذج"},
{"eCA.NoteFooter.label","ملاحظة التذييل"},
{"eCA.NoteBody.label","جسد الملاحظة"},
{"eCA.DocRefFormat.label","تنسيق المرجع المستند"},
{"eCA.DateAndTime.label","التاريخ و الوقت"},
{"eCA.AccessionNum.label","رقم الاتصال"},
{"eCA.RefNumLogic.label","منطق الرقم المرجعي"},
{"eCA.RefNo.label","رقم المصدر"},
{"eCA.ImageExists?.label","الصورة موجودة؟"},
{"eCA.SectionTemplateOutputForm.label","نموذج مخرج  قالب القسم"},
{"eCA.Editor.label","محرر"},
{"eCA.Right.label","صحيح"},
{"eCA.Laterality.label","لاحقة"},
{"eCA.Recorded.label","مسجل"},
{"eCA.PrintLogoHeader.label","طباعة الشعار"},
{"eCA.DefineQuickLink.label","تحديد رابط سريع"},
{"eCA.QuickLinkForResponsibility.label","رابط سريع للمسؤولية"},
{"eCA.CustomiseLinks.label","تخصيص الروابط"},
{"eCA.CustomiseFilter.label","تخصيص عامل التصفية"},
{"eCA.relative.label","نسبيا"},
{"eCA.QuickLinkType.label","نوع الرابط السريع"},
{"eCA.QueryFilter.label","فلتر الاستعلام"},
{"eCA.ActualFunction.label","الوظيفة الفعلية"},
{"eCA.ExternalApplication.label","التطبيق الخارجي"},
{"eCA.ExternalURL.label","URL خارجي"},
{"eCA.FunctionSpecific.label","وظيفة محددة"},
{"eCA.QuickLinks.label","روابط سريعة"},
{"eCA.QuickLinkDescription.label","وصف الرابط السريع"},
{"eCA.Global.label","عالمي"},
{"eCA.LinkType.label","نوع الرابط"},
{"eCA.Filter.label","فلتر "},
{"eCA.QuickLink.label","رابط سريع"},
{"eCA.Approx.label","تقريبي"},
{"eCA.tree.label","شجرة"},
{"eCA.ViewResults.label","عرض النتائج"},
{"eCA.LinkedEncounters.label","لقاءات مرتبطة"},
{"eCA.LinkedDate.label","تاريخ مرتبط"},
{"eCA.Results.label","النتائج"},
{"eCA.ReserveAndRequest.label","مطلوب حجز"},
{"eCA.ReserveNotRequest.label","محجوز غير مطلوب"},
{"eCA.Issued.label","نشر"},
{"eCA.Transfused.label","منقول(دم او مشتقاته)"},
{"eCA.PartialTransfusion.label","نقل الدم الجزئي"},
{"eCA.UnitNo.label","رقم الوحدة"},
{"eCA.TransfusionDtls.label","تفاصيل نقل الدم"},
{"eCA.Antibody.label","جسم مضاد"},
{"eCA.PatientAntibody.label","الأجسام المضادة للمريض"},
{"eCA.CheckbyPractitioner.label","فحص من قبل الممارس"},
{"eCA.TransfusionRemarks.label","ملاحظات نقل الدم"},
{"eCA.TransfusebyPractitioner.label","نقلها ممارس"},
{"eCA.RecordConsumption.label","سجل الاستهلاك"},
{"eCA.LastReportedDate.label","تاريخ آخر تقرير"},
{"eCA.ProductDetails.label","تفاصيل المنتج"},
{"eCA.ViewOrderDetail.label","عرض تفاصيل الطلب"},
{"eCA.TransfusionHistory.label","تاريخ نقل الدم"},
{"eCA.PendingTranscription.label","في انتظار النسخ"},
{"eCA.BirthDateTime.label","تاريخ / وقت الميلاد"},
{"eCA.Abnormal.label","غير طبيعي"},
{"eCA.AcceptOption.label","قبول الخيار"},
{"eCA.ActionDescription.label","وصف الإجراء"},
{"eCA.ActionRemarks.label","ملاحظات العمل"},
{"eCA.ActionType.label","نوع الإجراء"},
{"eCA.ActiveProblems.label","مشاكل نشطة"},
{"eCA.AddAssociateCodesfor.label","أضف رموز الارتباط لـ"},
{"eCA.addNew.label","اضف جديد"},
{"eCA.Address.label","عنوان"},
{"eCA.AdministeredBy.label","تباشر من قبل"},
{"eCA.AgeRange.label","الفئة العمرية"},
{"eCA.Alert.label","إنذار"},
{"eCA.AllLocations.label","جميع المواقع"},
{"eCA.AllergicDesc.label","وصف الحساسية"},
{"eCA.Allergy.label","حساسية"},
{"eCA.AllergyClass.label","فئة الحساسية"},
{"eCA.AllergyType.label","نوع الحساسية"},
{"eCA.AlphaInfo.label","معلومات ألفا"},
{"eCA.Anaesthesia.label","تخدير"},
{"eCA.AnaesthesiaCode.label","كود التخدير"},
{"eCA.Apgarscore.label","نقاط أبجار"},
{"eCA.ApplicableAgeGroup.label","الفئة العمرية القابلة للتطبيق"},
{"eCA.Application.label","تطبيق"},
{"eCA.Assessment.label","تقييم"},
{"eCA.Assigned.label","تعيين"},
{"eCA.AssociateCodesFor.label","رموز الارتباط لـ"},
{"eCA.Average.label","متوسط"},
{"eCA.Batch.label","دفعة"},
{"eCA.BedCommon.label","السرير"},
{"eCA.Before.label","قبل"},
{"eCA.BSA.label","مساحة سطح الجسم"},
{"eCA.Category.label","الفئة"},
{"eCA.Center.label","مركز"},
{"eCA.ChangeDescription.label","تغيير الوصف"},
{"eCA.Characteristics.label","مواصفات"},
{"eCA.Chart.label","مخطط"},
{"eCA.ChartSummaryCurrentMedications.label","مخطط مجمع للأدوية الحالة"},
{"eCA.CheckedIn.label","تم تسجيل الوصول"},
{"eCA.CheckedOut.label","تم تسجيل الخروج"},
{"eCA.ChiefComplaint.label","الشكوى الرئيسية"},
{"eCA.CLINICALNOTE.label","ملاحظة سريرية"},
{"eCA.ClinicalNotes.label","ملاحظات سريرية"},
{"eCA.Clinician.label","طبيب"},
{"eCA.Cms.label","Cms"},
{"eCA.cms.label","cms"},
{"eCA.CodeIndicator.label","مؤشر الكود"},
{"eCA.ColumnHeader.label","رأس العمود"},
{"eCA.CompType.label","نوع المكون"},
{"eCA.ComponentDefinition.label","تعريف المكون"},
{"eCA.ComponentID.label","الرمز التعريفي للمكون"},
{"eCA.ComponentLookup.label","بحث المكون"},
{"eCA.ComponentPrompt.label","موجه المكون"},
{"eCA.ComponentType.label","نوع المكون"},
{"eCA.Confidential.label","سري"},
{"eCA.ConsultingPatient.label","استشارة المريض"},
{"eCA.Continue.label","استمر"},
{"eCA.CriticallyAbnormal.label","حرج "},
{"eCA.CustomList.label","قائمة معدلة"},
{"eCA.CycleDays.label","أيام الدورة"},
{"eCA.CycleDays.label","أيام الدورة"},
{"eCA.VaccineSiteID.label","كود مكان التطعيم"},
{"eCA.Define.label","حدد"},
{"eCA.DefinitionType.label","نوع التعريف"},
{"eCA.Demographics.label","بيانات"},
{"eCA.Dependency.label","الاعتماد"},
{"eCA.DiagnosisType.label","نوع التشخيص"},
{"eCA.DispalyOnly.label","عرض فقط"},
{"eCA.DisplayOrder.label","عرض الأوامر"},
{"eCA.DisplayResult.label","عرض النتيجة"},
{"eCA.VaccineDoseNo.label","رقم الجرعة"},
{"eCA.Drug.label","دواء"},
{"eCA.DrugName.label","اسم الدواء"},
{"eCA.Due.label","مستحق"},
{"eCA.EffStatus.label","حالة الفعالية"},
{"eCA.EffectiveTo.label","فعالة ل"},
{"eCA.Element.label","عنصر"},
{"eCA.EmbeddedComponent.label","مكون مضمن"},
{"eCA.Enable.label","تنشيط"},
{"eCA.EnterEdit.label","أدخل / تحرير"},
{"eCA.Error.label","خطأ"},
{"eCA.ErrorRemarks.label","ملاحظات الخطأ"},
{"eCA.EventDetails.label","تفاصيل الحدث"},
{"eCA.EventEndDate.label","تاريخ انتهاء الحدث"},
{"eCA.EventStartDate.label","تاريخ بدء الحدث"},
{"eCA.Events.label","الأحداث"},
{"eCA.Expired.label","منتهية الصلاحية"},
{"eCA.ExplanatoryText.label","نص توضيحي"},
{"eCA.filename.label","اسم الملف"},
{"eCA.Findings.label","الموجودات"},
{"eCA.Fixed.label","ثابت"},
{"eCA.Food.label","طعام"},
{"eCA.Formatted.label","منسق"},
{"eCA.FormattedPRE.label","منسق"},
{"eCA.Formula.label","معادلة"},
{"eCA.Forward.label","إلى الأمام"},
{"eCA.Freeformat.label","صيغة حرة"},
{"eCA.VaccineFrequency.label","جرعات التطعيم"},
{"eCA.FullyImmunized.label","محصن بالكامل"},
{"eCA.GenericName.label","اسم بالمادة الفعالة"},
{"eCA.GridComponent.label","مكون الشبكة"},
{"eCA.GridComponentDefinition.label","تعريف مكونات الشبكة"},
{"eCA.GrowthDevelMilestoneAge.label","مقياس النمو / تطور العمر"},
{"eCA.HighRisk.label","عالى الخطورة"},
{"eCA.History.label","التاريخ"},
{"eCA.HourAfterDischarge.label","ساعة بعد الخروج"},
{"eCA.ICD.label","التصنيف الدولي للأمراض"},
{"eCA.id.label","هوية شخصية"},
{"eCA.IllegalResident.label","مقيم غير شرعي"},
{"eCA.ImageFileName.label","اسم ملف الصورة"},
{"eCA.ImageURL.label","رابط الصورة"},
{"eCA.ImmunizationStatus.label","حالة التحصين"},
{"eCA.InError.label","في خطأ"},
{"eCA.Inch.label","بوصة"},
{"eCA.IncludeforAnalysis.label","تضمين للتحليل"},
{"eCA.IncludeinCurrentEncounter.label","تضمين في الزيارة الحالية"},
{"eCA.Indicator.label","مؤشر"},
{"eCA.Inhalant.label","المستنشق"},
{"eCA.Insert.label","إدراج"},
{"eCA.Intermediate.label","متوسط"},
{"eCA.Intervention.label","تدخل "},
{"eCA.InterventionType.label","نوع التدخل"},
{"eCA.Last.label","الاخير"},
{"eCA.LastModifiedBy.label","التعديل الأخير من قبل"},
{"eCA.LegalResident.label","مقيم شرعي"},
{"eCA.Limit.label","حد"},
{"eCA.ListId.label","معرف القائمة"},
{"eCA.ListItem.label","قائمة الاغراض"},
{"eCA.ListofGridComponents.label","قائمة مكونات الشبكة"},
{"eCA.LoggedUser.label","مستخدم مسجل"},
{"eCA.LongDescription.label","وصف طويل"},
{"eCA.LongText.label","نص طويل"},
{"eCA.Low.label","منخفض"},
{"eCA.VaccineMandatory.label"," إلزامي"},
{"eCA.MarkError.label","وضع علامة على خطأ"},
{"eCA.MarkedBy.label","علمت بواسطة"},
{"eCA.MarkedDate.label","التاريخ المحدد"},
{"eCA.MatrixAttributes.label","سمات المصفوفة"},
{"eCA.MatrixColumnSpan.label","امتداد عمود المصفوفة"},
{"eCA.MatrixColumns.label","أعمدة المصفوفة"},
{"eCA.MatrixComponent.label","مكون المصفوفة"},
{"eCA.MatrixDefinition.label","تعريف المصفوفة"},
{"eCA.MatrixRows.label","صفوف المصفوفة"},
{"eCA.MaxValue.label","قيمة الحد الأقصى"},
{"eCA.MedAncService.label","خدمات عيادات طبية"},
{"eCA.MedicalEventType.label","نوع الحدث الطبي"},
{"eCA.MedicalReportRequest.label","طلب تقرير طبي"},
{"eCA.MedicalService.label","الخدمة الطبية"},
{"eCA.MenuID.label","معرف القائمة"},
{"eCA.MIN.label","حد أدنى"},
{"eCA.Minimum.label","الحد الأدنى"},
{"eCA.Minutes.label","الدقائق"},
{"eCA.Modified.label","تم التعديل"},
{"eCA.Monitoring.label","المراقبة"},
{"eCA.Mother.label","أم"},
{"eCA.Multiple.label","مضاعف"},
{"eCA.NewDocument.label","مستند جديد"},
{"eCA.NoofBirths.label","عدد المواليد"},
{"eCA.NotAdministered.label","لم يتم إعطاؤه"},
{"eCA.NotPerformed.label","لم تتم"},
{"eCA.NoteDescription.label","وصف الملاحظة"},
{"eCA.Notifiable.label","قابل للإبلاغ"},
{"eCA.Numeric.label","رقمي"},
{"eCA.NumericPrefixRequired.label","مطلوب بادئة رقمية"},
{"eCA.Observation.label","الملاحظة"},
{"eCA.OldValue.label","القيمة القديمة"},
{"eCA.OnsetDatetime.label","بداية التاريخ والوقت"},
{"eCA.ordered.label","أمر"},
{"eCA.OrderedBy.label","طلب بواسطة"},
{"eCA.OrganizationType.label","نوع المنظمة"},
{"eCA.OutCome.label","النتيجة"},
{"eCA.Outpatient.label","العيادات الخارجية"},
{"eCA.PanelDescription.label","وصف المجموعة"},
{"eCA.PanelID.label","معرف المجموعة"},
{"eCA.ParagraphDefinition.label","تعريف الفقرة"},
{"eCA.PartiallyImmunized.label","محصن جزئياً"},
{"eCA.Patients.label","المرضى"},
{"eCA.PediatricDetail.label","تفاصيل طب الأطفال"},
{"eCA.PendingAuthorization.label","تصريح معلق"},
{"eCA.PendingConsent.label","في انتظار الموافقة"},
{"eCA.PendingCosign.label","في انتظار الإمضاء المشتركة"},
{"eCA.Performed.label","تم الإجراء"},
{"eCA.PerformedOn.label","تم إجراءها على"},
{"eCA.POA.label","POA"},
{"eCA.PoliceStationDetails.label","تفاصيل مركز الشرطة"},
{"eCA.PositionDuringIncident.label","الموقف أثناء الحادث"},
{"eCA.PractitionerDetails.label","تفاصيل الممارس"},
{"eCA.PractitionerFrom.label","ممارس من"},
{"eCA.PrescribedBy.label","موصوفة بواسطة"},
{"eCA.Presentation.label","عرض"},
{"eCA.Preview.label","معاينة"},
{"eCA.PrintDateTime.label","تاريخ / وقت الطباعة"},
{"eCA.Printpreview.label","معاينة قبل الطباعة"},
{"eCA.Printing.label","طباعة"},
{"eCA.PriorityZone.label","منطقة الأولوية"},
{"eCA.Problem.label","مشكلة"},
{"eCA.ProblemAssessment.label","تقييم المشكلة"},
{"eCA.ProblemList.label","قائمة المشاكل"},
{"eCA.Problems.label","مشاكل"},
{"eCA.ProcedureCode.label","كود الإجراء"},
{"eCA.Procedures.label","الإجراءات"},
{"eCA.Profile.label","الملف الشخصي"},
{"eCA.Prompt.label","مستعجل"},
{"eCA.ProtectiveDeviceUsed.label","جهاز الحماية المستخدم"},
{"eCA.Range.label","نطاق"},
{"eCA.Reaction.label","رد الفعل"},
{"eCA.ReactionCode.label"," رد الفعل"},
{"eCA.ReactionDate.label","تاريخ رد الفعل"},
{"eCA.ReferralDiagnosis.label","تشخيص الإحالة"},
{"eCA.RegisterOrder.label","طلب تسجيل"},
{"eCA.Registered.label","مسجل"},
{"eCA.RelationshipType.label","نوع العلاقة"},
{"eCA.Replace.label","يحل محل"},
{"eCA.Response.label","استجابة"},
{"eCA.ResponsibilityID.label","معرف المسؤولية"},
{"eCA.ResponsibilityName.label","اسم المسؤولية"},
{"eCA.RestrictTo.label","تقييد ل"},
{"eCA.Result.label","نتيجة"},
{"eCA.ResultType.label","نوع النتيجة"},
{"eCA.Reviewed.label","تمت المراجعة"},
{"eCA.Reviewed.label","تمت المراجعة"},
{"eCA.RootMenu.label","قائمة الجذر"},
{"eCA.RowPosition.label","موقف الصف"},
{"eCA.Same.label","نفسه"},
{"eCA.ScheduleDate.label","تاريخ الجدول الزمني"},
{"eCA.Scope.label","نطاق"},
{"eCA.ScrubNurse.label","ممرضة "},
{"eCA.SearchResult.label","نتيجة البحث"},
{"eCA.SearchUser.label","بحث عن المستخدم"},
{"eCA.Section.label","الجزء"},
{"eCA.SectionCode.label","كود القسم"},
{"eCA.Selected.label","المحدد"},
{"eCA.Selection.label","اختيار"},
{"eCA.SelfRelated.label","ذات الصلة"},
{"eCA.Sensitive.label","حساس"},
{"eCA.ServiceCode.label","رمز الخدمة"},
{"eCA.Sex.label","الجنس"},
{"eCA.ShortDescription.label","وصف قصير"},
{"eCA.ShortText.label","نص قصير"},
{"eCA.Sign.label","إشارة"},
{"eCA.Signature.label","التوقيع"},
{"eCA.Single.label","غير مرتبطة"},
{"eCA.SiteName.label","اسم الموقع"},
{"eCA.Specify.label","حدد"},
{"eCA.Specimen.label","عينة"},
{"eCA.SpecimenCollection.label","جمع العينات"},
{"eCA.Stage.label","المرحلة"},
{"eCA.SupportingDiagnosis.label","دعم التشخيص"},
{"eCA.System.label","النظام"},
{"eCA.SystemDefined.label","معرّف من قبل النظام"},
{"eCA.SystemDescription.label","وصف النظام"},
{"eCA.Table.label","الطاولة"},
{"eCA.Task.label","مهمة"},
{"eCA.Tasks.label","مهام"},
{"eCA.Testing.label","اختبارات"},
{"eCA.Text.label","نص"},
{"eCA.TextBlock.label","كتلة النص"},
{"eCA.TextRows.label","صفوف النص"},
{"eCA.Title.label","عنوان"},
{"eCA.TitleText.label","نص العنوان"},
{"eCA.Top.label","أعلى"},
{"eCA.Topical.label","موضعي"},
{"eCA.Transcribed.label","نسخت"},
{"eCA.TreatInvest.label","علاج / استثمار"},
{"eCA.Treatment.label","علاج او معاملة"},
{"eCA.TriageDetails.label","تفاصيل الفرز"},
{"eCA.UnAssigned.label","غير معين"},
{"eCA.Unauthorized.label","غير مصرح"},
{"eCA.Unit.label","وحدة"},
{"eCA.Units.label","الوحدات"},
{"eCA.Update.label","تحديث"},
{"eCA.URL.label","الرابط"},
{"eCA.UserDefined.label","تعريف المستخدم"},
{"eCA.Vaccine.label","لقاح"},
{"eCA.VaccineId.label","لقاح"},
{"eCA.Value.label","القيمة"},
{"eCA.Values.label","القيم"},
{"eCA.Variable.label","متغير"},
{"eCA.VehiclesInvolved.label","المركبات ذات الصلة"},
{"eCA.ViewBy.label","مشاهدة بواسطة"},
{"eCA.VisitAdmDate.label","قم بزيارة تاريخ القبول"},
{"eCA.VitalSigns.label","علامات حيوية"},
{"eCA.Warn.label","تحذير"},
{"eCA.YesNo.label","نعم / لا"},
{"eCA.PatEncBanner.label","إشعار المريض / الزيارة"},
{"eCA.BannerType.label","نوع الإشعار"},
{"eCA.ShowPatPhoto.label","إظهار صورة المريض"},
{"eCA.LinkPatName.label","ربط اسم المريض"},
{"eCA.LineSelector.label","محدد الخط"},
{"eCA.FieldName.label","اسم الحقل"},
{"eCA.DisplayLenght.label","طول العرض"},
{"eCA.ActualLength.label","الطول الفعلي"},
{"eCA.Config.label","الإعدادات"},
{"eCA.DisplayText.label","عرض النص"},
{"eCA.ToolTipText.label","شرح الأداة"},
{"eCA.Legend.label","عنوان تفسيري"},
{"eCA.SpaceBeforeText.label","عدد المسافات قبل النص"},
{"eCA.ViewDefaultBanner.label","عرض الشعار الافتراضي"},
{"eCA.PreviewBanner.label","معاينة لافتة"},
{"eCA.PatientContextBanner.label","شعار سياق المريض"},
{"eCA.EncounterContextBanner.label","إشعار الزيارة"},
{"eCA.Interval.label","فترة"},
{"eCA.PatMediReport.label","تقرير طبي للمريض"},
{"eCA.UserPrevilegeForPrintEMail.label","امتياز المستخدم للطباعة والبريد الإلكتروني"},
{"eCA.PrivilegeFor.label","امتياز لـ"},
{"eCA.PatientMedicalReport.label","تقرير طبي للمريض"},
{"eCA.EMail.label","البريد الإلكتروني"},
{"eCA.PastDays.label","الأيام الماضية"},
{"eCA.EmailingSetup.label","إعداد البريد الإلكتروني"},
{"eCA.EmailReportControlSetup.label","إعداد التحكم في تقرير البريد الإلكتروني"},
{"eCA.EmailReportBodyText.label","نص تقرير البريد الإلكتروني"},
{"eCA.ReportBodyTextID.label","معرّف نص التقرير"},
{"eCA.ReportBodyTextDesc.label","وصف نص نص التقرير"},
{"eCA.RegisteredEmailRecipient.label","مستلم البريد الإلكتروني المسجل"},
{"eCA.ManagePassword.label","إدارة كلمة المرور"},
{"eCA.UserPrivToVerifyEmail.label","امتياز المستخدم للتحقق من البريد الإلكتروني"},
{"eCA.EmailIdControl.label","التحكم في معرف البريد الإلكتروني"},
{"eCA.VerificationRequired.label","التحقق مطلوب"},
{"eCA.ApplicabletoPatient.label","ينطبق على المريض"},
{"eCA.ApplicableToRegisteredUsers.label","ينطبق على المستخدمين المسجلين"},
{"eCA.ApplicableToAdhocEmailID.label","ينطبق على معرف البريد الإلكتروني المخصص"},
{"eCA.VerificationRequiredForConfidentialResult.label","مطلوب التحقق للحصول على نتيجة سرية"},
{"eCA.Manage.label","إدارة"},
{"eCA.Email.label","البريد الإلكتروني"},
{"eCA.RegisteredRecipientID.label","معرف المستلم"},
{"eCA.RegisteredRecipientName.label","اسم المستلم"},
{"eCA.EmailId.label","عنوان الايميل"},
{"eCA.ApplicableToReport.label","ينطبق على التقرير"},
{"eCA.BodyText.label","نص أساسي"},
{"eCA.CC.label","نسخة مطابقة"},
{"eCA.NoteTypeAccessRights.label","نوع الملاحظة حقوق الاطلاع"},
{"eCA.AccessRightsfor.label","حقوق الاطلاع لـ"},
{"eCA.ManageSelectedEvents.label","إدارة الأحداث المختارة"},
{"eCA.ConfigureOutput.label","تكوين المخرجات"},
{"eCA.ByCategory.label","بالتصنيف"},
{"eCA.DeSelect.label","إلغاء"},
{"eCA.PastEncounters.label","زيارات سابقة"},
{"eCA.TermDescription.label","وصف المصطلح"},
{"eCA.ToPatient.label","للمريض"},
{"eCA.ToAdhocUser.label","إلى المستخدم المخصص"},
{"eCA.ToRegdRecepient.label","إلى المستلم المسجل"},
{"eCA.EncounterDetailForPMR.label","تفاصيل لقاء ل للملف الطبى للمريض"},
{"eCA.SpecialityForPMR.label","تخصص ل الملف الطبى للمريض"},
{"eCA.PractitionerForPMR.label","ممارس ل الملف الطبى للمريض"},
{"eCA.PrintMailPrivilegeForPMR.label","امتياز الطباعة / البريد لـ الملف الطبى للمريض"},
{"eCA.VerifySignReports.label","التحقق من التقارير وتوقيعها"},
{"eCA.MailedUser.label","مستخدم بالبريد"},
{"eCA.MailDetails.label","تفاصيل البريد"},
{"eCA.Mail.label","بريد"},
{"eCA.MailBody.label","نص البريد"},
{"eCA.MailText.label","نص البريد"},
{"eCA.ClearMailId.label","مسح معرف البريد"},
{"eCA.ClickOnValueCell.label","انقر فوق خلية القيمة لإلغاء التحديد / التحديد وتنفيذ ==>"},
{"eCA.FilterBy.label","مصنف بواسطة"},
{"eCA.NonSpeciality.label","غير تخصص"},
{"eCA.ConsultationSetup.label","إعداد الاستشارة"},
{"eCA.SpltyForConsultOrderable.label","تخصص للاستشارة "},
{"eCA.PractForConsultOrderable.label","ممارس للاستشارة "},
{"eCA.ConsultationParam.label","إعداد معايير الاستشارة"},
{"eCA.MaxConsultationPractitioner.label","الحد الأقصى لاستشارة الممارس "},
{"eCA.BackDateConsultationList.label","رجوع تاريخ قائمة الاستشارة"},
{"eCA.MaxConsultationSpeciality.label","الحد الأقصى للاستشارة حسب التخصص"},
{"eCA.AmendConsultationList.label","تعديل قائمة الاستشارة"},
{"eCA.MinDurationRecquired.label","الحد الأدنى للمدة المطلوبة بين الاستشارة"},
{"eCA.Mins.label","دقيقة"},
{"eCA.Diagnosis.label","التشخيص"},
{"eCA.ConsultationListBy.label","قائمة الاستشارة"},
{"eCA.OnBehalfOf.label","نيابة عن"},
{"eCA.ConsultDate.label","تاريخ الاستشارة"},
{"eCA.NewList.label","قائمة جديدة"},
{"eCA.ExistingList.label","القائمة الموجودة"},
{"eCA.GenerateList.label","إنشاء قائمة"},
{"eCA.ChargeConsultation.label","دفع الاستشارة"},
{"eCA.EHRView.label","عرض الملف الطبى الإلكترونى"},
{"eCA.ClinicalEventsCentralRepFor.label","الأحداث السريرية من المستودع المركزي لـ"},
{"eCA.ChargeApplicable.label","تطبيق الدفع"},
{"eCA.ApprovalRequired.label","الموافقة مطلوبة"},
{"eCA.DisplayFields.label","عرض الحقول"},
{"eCA.FutureEvents.label","أحداث مستقبلية"},
{"eCA.FutureEventType.label","نوع الحدث المستقبلي"},
{"eCA.ConfigureDisplayFields.label","تكوين حقول العرض"},
{"eCA.ConsultationListDesc.label","وصف قائمة الاستشارة"},
{"eCA.ConsultationList.label","قائمة الاستشارة"},
{"eCA.ExceedMaxConsSpeciality.label","تجاوز الحد الأقصى للاستشارات بنفس التخصص"},
{"eCA.ExceedMaxConsPractitioner.label","تجاوز الحد الأقصى لعدد الاستشارات للطبيب"},
{"eCA.CancelCharge.label","إالغاء الدفع"},
{"eCA.ListReference.label","مرجع القائمة"},
{"eCA.TocancelPostedCons.label","لإلغاء رسوم الاستشارة المنشورة - ابحث مع قيمة قائمة الحالة على أنها مكتملة."},
{"eCA.PrintNotesOnSign.label","طباعة الملاحظات عند التوقيع"},
{"eCA.PrintOnConfirm.label","الطباعة عند التأكيد"},
{"eCA.PrintDirectly.label","اطبع مباشرة"},
{"eCA.RouteOfAdmin.label","توجيه للإدارة"},
{"eCA.ViewMARChart.label","عرض الرسم البياني لسجل إعطاء الأدوية"},
{"eCA.ConfigDispCrit.label","تكوين معايير العرض"},
{"eCA.RecordedDateAndTime.label","التاريخ والوقت المسجل"},
{"eCA.IconsSelected.label","الرموز المحددة"},
{"eCA.FormulaAdopted.label","الصيغة المعتمدة"},
{"eCA.Centemeter.label","سنتيمتر"},
{"eCA.IsEqualTo.label","مساوي ل"},
{"eCA.IBW.label","وزن الجسم المثالي"},
{"eCA.Kilograms.label","كيلوغرام"},
{"eCA.CanConvertLbsToKg.label","يمكن تحويل رطل إلى كجم"},
{"eCA.Or.label","أو"},
{"eCA.yrs.label","سنوات"},
{"eCA.Child.label","طفل"},
{"eCA.ClinicalCalculations.label","الحسابات السريرية"},
{"eCA.FormulaeToBeUsed.label","الصيغ المراد استخدامها"},
{"eCA.NoPrivilege.label","لا امتياز"},
{"eCA.SymbolicLegends.label","رموز"},
{"eCA.NormalcyIndicator.label","مؤشر طبيعى"},
{"eCA.Symboliclegends.label","رموز"},
{"eCA.Colourlegends.label","رموز ملونة"},
{"eCA.DisplayEvents.label","عرض الأحداث"},
{"eCA.IncludeInErrRecs.label","تضمين في سجلات الأخطاء"},
{"eCA.MarkedInErrorBy.label","تم وضع علامة خطأ بواسطة"},
{"eCA.MarkedErrorDate.label","تاريخ خطأ ملحوظ"},
{"eCA.ByDiagnosis.label","بالتشخيص"},
{"eCA.ByDocument.label","حسب المستند"},
{"eCA.HideMenu.label","إخفاء القائمة"},
{"eCA.PatientwithoutEncounter.label","مريض بدون زيارة"},
{"eCA.DocumentName.label","اسم الملف"},
{"eCA.SearchWord.label","كلمة البحث"},
{"eCA.Sectionsp.label","الأقسام"},
{"eCA.ClickForRecAndSign.label","انقر للتسجيل والتوقيع"},
{"eCA.ProcessingPlsWait.label","جارى المعالجة .. انتظر من فضلك"},
{"eCA.ShowMenu.label","إظهار القائمة"},
{"eCA.PractAlert.label","تنبيه للممارس الطبي"},
{"eCA.AlertCode.label","رمز التنبيه"},
{"eCA.AlertDesc.label","وصف التنبيه"},
{"eCA.Onetime.label","مره واحده"},
{"eCA.AlertEvent.label","حدث التنبيه"},
{"eCA.ActionDateAndTime.label","تاريخ ووقت العمل"},
{"eCA.AlertCategoryCode.label","رمز فئة التنبيه"},
{"eCA.AlertCategoryDescription.label","وصف فئة التنبيه"},
{"eCA.AlertEventCode.label","رمز حدث التنبيه"},
{"eCA.AlertEventDescription.label","وصف حدث التنبيه"},
{"eCA.AlertCategory.label","فئة التنبيه"},
{"eCA.AlertDescription.label","وصف التنبيه"},
{"eCA.ActionEvent.label","حدث العمل"},
{"eCA.ActionFrequency.label","تكرار الحدث"},
{"eCA.ActionPeriod.label","فترة الحدث"},
{"eCA.inEvery.label","في كل"},
{"eCA.TriggeringTime.label","وقت التفعيل"},
{"eCA.TranscriptionApplicable.label","تطبيق النسخ"},
{"eCA.CutoffPeriodToAllowTrans.label","فترة السماح بالنسخ"},
{"eCA.DaysFromVisitRegDisc.label","أيام من تسجيل الزيارة "},
{"eCA.DefaultAgeGrp.label","الفئة العمرية الافتراضية"},
{"eCA.SpltySpcific.label","تخصص محدد"},
{"eCA.DfltTranscriptionNotes.label","ملاحظات النسخ الافتراضية"},
{"eCA.forwardedForAuth.label","تمت إعادة التوجيه للحصول على إذن"},
{"eCA.respSentTo.label","تم إرسال الرد إلى"},
{"eCA.AdaptiveMenu.label","القائمة التكيفية"},
{"eCA.New.label","جديد"},
{"eCA.BloodUnitCons.label","استهلاك وحدة الدم"},
{"eCA.AdaptiveFuncTo.label","وظيفة تكيفية ل"},
{"eCA.FunctionRef.label","مرجع الوظيفة"},
{"eCA.LinkNewFunc.label","ربط وظيفة جديدة"},
{"eCA.LinkedFunc.label","الوظائف المرتبطة"},
{"eCA.ModifyLinkedFunc.label","تعديل الوظيفة المرتبطة"},
{"eCA.TranscribeNotes.label","نسخ الملاحظات"},
{"eCA.ReqTranscription.label","طلب النسخ"},
{"eCA.MyPatients.label","المرضى الخاصة بي"},
{"eCA.MyRelatedPatients.label","المرضى المرتبطين بي"},
{"eCA.Unclassified.label","غير مصنف"},
{"eCA.RequestDetails.label","طلب تفاصيل"},
{"eCA.UncheckToRemove.label","قم بإلغاء التحديد للإزالة"},
{"eCA.RequestDateTime.label","طلب التاريخ والوقت"},
{"eCA.RequestedBy.label","بتوصية من"},
{"eCA.AlrgyResRecDate.label","التاريخ المسجل للحساسية"},
{"eCA.ResultRemarks.label","النتيجة / الملاحظات"},
{"eCA.AccessedBy.label","الوصول إليها"},
{"eCA.AuditTrailBy.label","مراجعة الحسابات بواسطة"},
{"eCA.PendingRxForMAR.label","روشتات معلقة"},
{"eCA.PatientDetailsGroup.label","مجموعة تفاصيل المريض"},
{"eCA.EncounterDetailsGroup.label","مجموعة تفاصيل الزيارة"},
{"eCA.ClinicalEventHistory.label","تاريخ الحدث السريري"},
{"eCA.DeliveryType.label","نوع التوصيل"},
{"eCA.AttendingNurse.label","الممرضة الملازمة"},
{"eCA.ProcedureClassification.label","تصنيف الإجراء"},
{"eCA.DeliverySurgicalClassification.label","التصنيف الجراحي للولادة"},
{"eCA.VaginalDeliveryType.label","نوع الولادة الطبيعية"},
{"eCA.NoofBirth.label","رقم الميلاد"},
{"eCA.ComplicationinStage1ofDelivery.label","المضاعفات في المرحلة الأولى من الولادة"},
{"eCA.ComplicationinStage2ofDelivery.label","المضاعفات في المرحلة الثانية من الولادة"},
{"eCA.ComplicationinStage3ofDelivery.label","المضاعفات فى المرحلة الثالة من الولادة"},
{"eCA.ComplicationofDelivery.label","مضاعفات الولادة"},
{"eCA.FoetusComplicationofDelivery.label","مضاعفات الجنين أثناء الولادة"},
{"eCA.AdministeredRxVaccines.label","التطعيمات المعطاة"},
{"eCA.DeliveryRecord.label","سجل الولادة"},
{"eCA.RestrictModifyLMP.label","تقييد تعديل تاريخ آخر دورة"},
{"eCA.WhichEverIsLess.label","ايهما اقل"},
{"eCA.CorrctdEDDNotExtendBeyond.label","لا يجب أن يمتد تاريخ الولادة المتوقع إلى أبعد من ذلك أو قبله"},
{"eCA.DaysFromthecalculatedEDD.label","أيام من تاريخ الولادة المحسوب"},
{"eCA.NewBornDetails.label","تفاصيل مولود جديد"},
{"eCA.NewBorn.label","مولود جديد"},
{"eCA.NumberofOccurrences.label","عدد مرات الحدوث"},
{"eCA.RegisterBaby.label","تسجيل طفل"},
{"eCA.QueryID.label","معرف الاستعلام"},
{"eCA.QueryDesc.label","وصف الاستعلام"},
{"eCA.DoseNumber.label","رقم الجرعة"},
{"eCA.OptLnkVaccineSchedule.label","خيار ربط اللقاح بالجدول الزمني"},
{"eCA.NoDaysVaccinesSchedule.label","عدد الأيام التي يمكن فيها ربط اللقاحات بالجدول الزمني"},
{"eCA.AutoLnk.label","ارتباط تلقائي"},
{"eCA.ManualLnk.label","رابط يدوي"},
{"eCA.VaccineCatagoryForRXVaccines.label","فئة اللقاح المخصص لـ سجل إعطاء الأدوية"},
{"eCA.ScheduledAge.label","العمر المقرر"},
{"eCA.ActualAge.label","العمر الفعلي"},
{"eCA.ValidateURL.label","التحقق من الرابط"},
{"eCA.ShowTextResult.label","إظهار نتيجة النص"},
{"eCA.Collapsed.label","مغلق"},
{"eCA.Expanded.label","مفتوح"},
{"eCA.View.label","عرض"},
{"eCA.RecordedPractType.label","نوع الممارس الطبي المسجل"},
{"eCA.RecordedPract.label","ممارس طبي مسجل"},
{"eCA.IncludeNoOfPreviousNotes.label","لا تتضمن أي من الملاحظات السابقة"},
{"eCA.ViewClinicalDocuments.label","عرض الوثائق السريرية"},
{"eCA.ViewPreviousNotes.label","عرض الملاحظات السابقة"},
{"eCA.VaccineCategoryType.label","نوع فئة اللقاح"},
{"eCA.LnkVaccSchedule.label","ربط جدول اللقاح"},
{"eCA.MoreValues.label","المزيد من القيم "},
{"eCA.RecordingForDateTime.label","تسجيل التاريخ والوقت"},
{"eCA.HighRiskResRecDate.label","التاريخ المسجل المخاطر العالية"},
{"eCA.RecordedDischargeSummary.label","ملخص الخروج المسجل"},
{"eCA.ReferralLetter.label","خطاب الإحالة"},
{"eCA.RecordedClinicalNotes.label","الملاحظات السريرية المسجلة"},
{"eCA.ErrMrkDlt.label","تعليم كخطأ للحذف"},
{"eCA.CurrentLength.label","الطول الحالي"},
{"eCA.MaxLengthAllowed.label","أقصى طول مسموح به"},
{"eCA.MaxNoImgAllowed.label","الحد الأقصى للصور المسموح بها لكل ملاحظة"},
{"eCA.Progression.label","التقدم"},
{"eCA.ShowActive.label","عرض نشط"},
{"eCA.ShowClosed.label","عرض مغلق"},
{"eCA.AddNewP.label","اضف جديد"},
{"eCA.RecordOutcome.label","تسجيل النتيجة"},
{"eCA.ProgressNotes.label","ملاحظات التقدم"},
{"eCA.MedAdmindetails.label","تفاصيل إعطاء الأدوية"},
{"eCA.SuggestedDiagnosis.label","التشخيص المقترح"},
{"eCA.SuggestedDiagnosisForCurrentChiefComplaint.label","التشخيص المقترح للشكوى الرئيسية الحالية"},
{"eCA.MaxIPConsChargable.label","الحد الأقصى من رسوم الاستشارة للزيارة الداخلية"},
{"eCA.PerDay.label","في اليوم"},
{"eCA.RegularCons.label","استشارة منتظمة"},
{"eCA.ReferralCons.label","استشارة الإحالة"},
{"eCA.Target.label","هدف"},
{"eCA.SourceEncounterClinicalEvents.label","مصدر الأحداث السريرية فى الزيارة"},
{"eCA.ParameterDetails.label","تفاصيل المعايير"},
{"eCA.ConstructedParameterList.label","قائمة المعايير المنشأة"},
{"eCA.ParamName.label","اسم المعيار"},
{"eCA.AccessRestriction.label","تقييد الوصول"},
{"eCA.SelfOrder.label","الطلبات الذاتية"},
{"eCA.SelfSpltyOrders.label","الأوامر الذاتية للتخصص"},
{"eCA.ParamValue.label","قيم المعيار"},
{"eCA.NotRecorded.label","غير مسجل"},
{"eCA.NotExist.label","لا يوجد"},
{"eCA.NotIdentified.label","غير معروف"},
{"eCA.SpecimenCollectedAt.label","العينة التي تم جمعها في"},
{"eCA.AnalyticalGroupCode.label","كود المجموعة التحليلية"},
{"eCA.AnalyticalGroupName.label","اسم المجموعة التحليلية"},
{"eCA.AvailableComponentList.label","قائمة المكونات المتاحة"},
{"eCA.GroupSection.label","مجموعة (قسم)"},
{"eCA.CompDetails.label","تفاصيل المكون"},
{"eCA.CompType.label","نوع المكون"},
{"eCA.SelectedComponentList.label","قائمة المكونات المحددة"},
{"eCA.CustomComponentTitle.label","عنوان المكون المخصص"},
{"eCA.ComponentDetails.label","تفاصيل المكون"},
{"eCA.SeqNo.label","رقم التسلسل"},
{"eCA.DefineAnalyticalGroup.label","تحديد مجموعة تحليلية"},
{"eCA.BedNo.label","رقم السرير"},
{"eCA.ConsultingPractitioner.label","طبيب استشاري"},
{"eCA.PrintEventHeaderinClinicalEventHistory.label","طباعة عنوان الحدث في تاريخ الأحداث السريرية"},
{"eCA.PendingConsent.label","في انتظار الموافقة"},
{"eCA.NoteHeaderMargin.label","هامش المقدمة للملاحظة"},
{"eCA.NoteFooterMargin.label","هامش التذييل للملاحظة"},
{"eCA.HeaderFooterMargin.label","هامش مقدمة وتذييل الصفحة"},
{"eCA.ViewChartSetup.label","عرض إعداد المخطط"},
{"eCA.LogoHeaderForAllPages.label"," طباعة  الشعار في كافة الصفحات"},
{"eCA.ReportHeaderForAllPages.label","طباعة مقدمة التقرير في كافة الصفحات"},
{"eCA.StartConsultation.label","هل تريد بدء الاستشارة؟"},
{"eCA.PatWithEnc.label","مريض له زيارة"},
{"eCA.PrintTextLogoHeader.label","مرفق الطباعة / مقدمة الموقع"},
{"eCA.PatWithOutEnc.label","مريض بدون زيارة"},
{"eCA.EditorText.label","نص المحرر"},
{"eCA.TextType.label","نوع النص"},
{"eCA.AddendumRecordedBy.label","ملحق مسجل بواسطة"},
{"eCA.SpellChecker.label","المدقق الإملائي مطلوب"},
{"eCA.DefaultSpellChecker.label","المدقق الإملائي الافتراضي"},
{"eCA.SpellCheckerPopUp.label","نافذة منبثقة للمدقق الإملائي"},
{"eCA.SpellCheckerInLine.label"," مدقق إملائي مضمّن"},
{"eCA.LegendForSummary.label","قائمة الملخص الأصلية"},
{"eCA.LegendForNavigation.label","قائمة التنقل الرئيسية"},
{"eCA.ResearchCategoryFactor.label","عامل فئة البحث"},
{"eCA.ResearchCategoryRiskFactor.label","فئة البحث عامل الخطورة"},
{"eCA.ResearchCategoryFactorCode.label","كود عامل فئة البحث"},
{"eCA.ResearchCategoryFactorDescription.label","وصف عامل فئة البحث"},
{"eCA.PractitionerTo.label","ممارس طبي ل"},
{"eCA.researchStudy.label","دراسة بحثية"},
{"eCA.NODATAFOUND.label","لا توجد بيانات تم العثور عليها."},
{"eCA.RiskFactorId.label","معرف عامل الخطر"},
{"eCA.RiskFactorDescription.label","وصف عامل الخطر"},
{"eCA.RiskFactorType.label","نوع عامل الخطر"},
{"eCA.AgeGrp.label","الفئة العمرية"},
{"eCA.RiskFactorIndicator.label","مؤشر عامل الخطر"},
{"eCA.Remarks.label","ملاحظات"},
{"eCA.AdverseEventType.label","نوع الحدث الضار"},
{"eCA.Allergen.label","مسببات الحساسية"},
{"eCA.Status.label","الحالة"},
{"eCA.Weight.label","وزن"},
{"eCA.Height.label","ارتفاع"},
{"eCA.DiscreteMeasure.label","قياس منفصل"},
{"eCA.LabResults.label","نتائج المختبر"},
{"eCA.OrderCatalog.label","كتالوج الطلب"},
{"eCA.DrugName.label","اسم الدواء"},
{"eCA.Radiology.label","الأشعة"},
{"eCA.TermSet.label","إعداد المصطلحات"},
{"eCA.RuleforRiskFactor.label","عامل الخطر"},
{"eCA.Start.label","بداية"},
{"eCA.End.label","النهاية"},
{"eCA.AllAges.label","كل الأعمار"},
{"eCA.Age.label","عمر"},
{"eCA.Operator.label","المشغل أو العامل"},
{"eCA.High.label","عالي"},
{"eCA.Average.label","متوسط"},
{"eCA.Low.label","منخفض"},
{"eCA.labtestresult.label","نتيجة الاختبار المعملي"},
{"eCA.defaultcriteria.label","المعايير الافتراضية"},
{"eCA.currentencounter.label","اللقاء الحالي"},
{"eCA.pastencounter.label","اللقاء السابق"},
{"eCA.scopefordata.label","نطاق البيانات "},
{"eCA.SignAddendumOthers.label","إضافة توقيع الملحق للآخرين"},
{"eCA.groupid.label","معرف مجموعة"},
{"eCA.groupdesc.label","وصف المجموعة"},
{"eCA.riskfactor.label","عامل الخطر"},
{"eCA.symbolid.label","معرف الرمز"},
{"eCA.symbol.label","رمز"},
{"eCA.symbolgroups.label","مجموعة الرموز"},
{"eCA.symbolgrpid.label","معرف مجموعة الرموز"},
{"eCA.symbolgrpdesc.label","وصف مجموعة الرموز"},
{"eCA.noteindicator.label","مؤشر الملاحظة"},
{"eCA.ntegrpntetypemand.label","ملاحظة نوع المجموعة / الملاحظة لمجموعة الرموز"},
{"eCA.ResultLinkSensitiveDia.label","نتيجة ارتباط التشخيص الحساس"},
{"eCA.MaxDaysViewPreviousNotes.label","أقصى فترة مسموح بها لعرض الملاحظات السابقة"},
{"eCA.GenogramOfOtherFamilyMemberExists.label","فحص جينى لأفراد الأسرة الآخرين موجود"},
{"eCA.NonPatientID.label","هوية غير المريض"},
{"eCA.FamilyMembers.label","أفراد الأسرة"},
{"eCA.FamilyMember.label","فرد من العائلة"},
{"eCA.PatientID.label","رقم المريض"},
{"eCA.PatientName.label","اسم المريض"},
{"eCA.Age.label","عمر"},
{"eCA.Gender.label","جنس"},
{"eCA.DeceasedDateTime.label","تاريخ / وقت الوفاة"},
{"eCA.Relation.label","علاقة"},
{"eCA.RelationWith.label","علاقة مع"},
{"eCA.FamilyMemberDetails.label","تفاصيل أفراد العائلة"},
{"eCA.FamilyRelationship.label","العلاقة الأسرية"},
{"eCA.RelationshipType.label","نوع العلاقة"},
{"eCA.NoOfChildren.label","عدد الاطفال"},
{"eCA.FamilyDemographics.label","ديموغرافيات الأسرة"},
{"eCA.RelationStartDate.label","تاريخ بدء العلاقة"},
{"eCA.Name.label","اسم"},
{"eCA.DateofBirth.label","تاريخ الولادة"},
{"eCA.DeceasedRemarks.label","ملاحظات المتوفى"},
{"eCA.FatherDetails.label","تفاصيل الأب"},
{"eCA.MotherDetails.label","تفاصيل الأم"},
{"eCA.RelationbetweenFatherAndMother.label","العلاقة بين الأب والأم"},
{"eCA.RelationStartDate.label","تاريخ بدء العلاقة"},
{"eCA.SiblingPosition.label","موقف الأخوة"},
{"eCA.RelationID.label","معرف العلاقة"},
{"eCA.Facility.label","منشأة"},
{"eCA.filterbasedon.label","عامل التصفية على أساس"},
{"eCA.basedon.label","مرتكز على"},
{"eCA.viewlist.label","عرض القائمة"},
{"eCA.authorizedorordered.label","مطلوبة / مصرحة بواسطة"},
{"eCA.secondaryspeciality.label","التخصص الثانوي"},
{"eCA.DispSeqNo.label","عرض رقم التسلسل"},
{"eCA.ComponentStartsWith.label","تبدأ المكونات بـ"},
{"eCA.AttachedComponents.label","المكونات المرفقة"},
{"eCA.ColumnNumbers.label","عدد الأعمدة"},
{"eCA.AddSubGroup.label","إضافة مجموعة فرعية"},
{"eCA.AddComponent.label","إضافة مكون"},
{"eCA.AddedComponents.label","المكونات المضافة"},
{"eCA.ComponentSubGroupCode.label","رمز المكون / المجموعة الفرعية"},
{"eCA.ModifyComponents.label","تعديل المكونات"},
{"eCA.ComponentCode.label","كود المكون"},
{"eCA.ColumnDetails.label","تفاصيل العمود"},
{"eCA.LineChartdetails.label","تفاصيل المخطط الخطي"},
{"eCA.GroupsStartsWith.label","تبدأ المجموعات بـ"},
{"eCA.SelectGroups.label","اختيار المجموعات"},
{"eCA.SelectedGroups.label","مجموعات مختارة"},
{"eCA.SummaryCode.label","كود الملخص"},
{"eCA.SummaryDescription.label","وصف الملخص"},
{"eCA.SummaryList.label","قائمة الملخص "},
{"eCA.SelectSummaryList.label","حدد قائمة الملخص"},
{"eCA.NOKNOWNALLERGY.label","لم يتم تسجيل أي حساسية معروفة"},
{"eCA.PatientClassification.label","تصنيف المريض"},
{"eCA.DisplayResultLinkInHTML.label","عرض رابط النتيجة في HTML"},
{"eCA.EncGrpCurrSpeclty.label","تجميع الزيارات حسب التخصص الحالي"},
{"eCA.NewVital.label","علامة حيوية جديدة"},
{"eCA.NOOPDAEENCOUNTER.label","لم يتم العثور على بيانات لـلزيارة"},
{"eCA.LOCATIONORPRACT.label","الموقع / الممارس"},
{"eCA.APPOINTMENTDATE.label","تاريخ الحجز"},
{"eCA.ACCESSSEDBY.label","مسموح الوصول إليها بواسطة"},
{"eCA.ACCESSEDDATETIME.label","تاريخ / وقت الاطلاع"},
{"eCA.mdscriteriamet.label","استيفاء معايير "},
{"eCA.mdscriterianotmet.label","معايير غير مستوفاة"},
{"eCA.referredLocationDtls.label","تفاصيل الموقع المشار إليها"},
{"eCA.reportgenerated.label","تم إنشاء التقرير"},
{"eCA.assignandconfirm.label","تعيين وتأكيد"},
{"eCA.assignandconfirmdiag.label","تعيين وتأكيد التشخيص"},
{"eCA.assigndiag.label","تعيين "},
{"eCA.VisitPatientClassEncounterSpecilityDtls.label","تفاصيل فئة المريض والزيارة والتخصص"},
{"eCA.CopyFromPreviousNote.label","نسخ من الملاحظة السابقة"},
{"eCA.pinvalidreq.label","مطلوب رقم التعريف الشخصي السري للطباعة"},
{"eCA.CopyText.label","نسخ النص"},
{"eCA.AuditLink.label","رابط التدقيق"},
{"eCA.Antibody.label","جسم مضاد"},
{"eCA.dispbyevent.label","عرض حسب الحدث"},
{"eCA.ShiftOne.label","نوبتجية أولى"},
{"eCA.ShiftTwo.label","نوبتجية ثانية"},
{"eCA.ShiftThree.label","نوبتجية ثالثة"},
{"eCA.ShiftSummaryRequired.label","مطلوب ملخص المناوبة"},
{"eCA.NumberOfShifts.label","عدد المناوبات"},
{"eCA.ShiftDuration.label","مدة المناوبة"},
{"eCA.recordsign.label","توقيع السجل"},
{"eCA.DisplayDisPrintText.label","اعرض نص إخلاء المسؤولية في طباعة تاريخ الأحداث السريرية"},
{"eCA.notifyalert.label","تنبيه الإخطار"},
{"eCA.rejectedtest.label","اختبار مرفوض"},
{"eCA.testcode.label","كود الاختبار"},
{"eCA.rejectreason.label","سبب الرفض"},
{"eCA.rejectedtime.label","وقت الرفض"},
{"eCA.rejectedtl.label","التفاصيل المرفوضة"},
{"eCA.antibodycode.label","كود الجسم المضاد"},
{"eCA.antibodydescription.label","وصف الجسم المضاد"},
{"eCA.resultdatetime.label","تاريخ النتائج والوقت"},
{"eCA.antibodydetails.label","تفاصيل الجسم المضاد"},
{"eCA.TextFormatDflt.label","حدد تنسيق النص افتراضيًا للأقسام المرتبطة"},
{"eCA.textAlignment.label","محاذاة النص"},
{"eCA.watermark.label","تمكين العلامة المائية في ملاحظة سريرية"},
{"eCA.RestrictUnsettledPatient.label","وضع قيود على المريض عند وجود فواتير غير مسددة لهذه الزيارة"},
{"eCA.amendResultNote.label","تعديل ملاحظة النتيجة السريرية"},
{"eCA.AutoRefTime.label","وقت التحديث التلقائي لقائمة الملخص"},
{"eCA.disprefrange.label","تعطيل النطاق المرجعي في نتائج الارتباط"},
{"eCA.dispspectype.label","تعطيل نوع العينة في نتائج الارتباط"},
{"eCA.AutoFillActiveDiagnosis.label"," التعبئة التلقائية للتشخيص النشط"},
{"eCA.datetimeformat.label","تعطيل التاريخ / الوقت المتكرر في نتائج الارتباط"},
{"eCA.noofenccopyprevnotes.label","عدد الزيارات لنسخ الملاحظات السابقة"},
{"eCA.PendDischSummGracePeriod.label","فترة سماح ملخص الخروج"},
{"eCA.Xaxiselement.label","عنصر المحور س"},
{"eCA.Yaxiselement.label","عنصر المحور ص"},
{"eCA.centimeters.label","سم"},
{"eCA.PersonalisePatList.label","قائمة المرضى المخصصة"},
{"eCA.PatEncDetails.label","عرض تفاصيل لقاء المريض"},
{"eCA.kgm2.label","كجم \\ م 2"},
{"eCA.AddedAt.label","تمت الإضافة في"},
{"eCA.splchtgrpid.label","معرف مجموعة التخطيط الخاص"},
{"eCA.splchtgrpdesc.label","وصف مجموعة الرسم البياني الخاص"},
{"eCA.Effectivestat.label","الوضع الفعال"},
{"eCA.MyReferrals.label","الإحالات الخاصة بي"},
{"eCA.AEConsultation.label","استشارة"},
{"eCA.PromptStartConsultAEPatQueue.label","موجه لبدء التشاور في مرضى الطوارئ الحاليين"},
{"eCA.PromptStartConsultAEPatQueueInCA.label","موجه لبدء استشارة في وصول الأطباء"},
{"eCA.OpenPatChrtwithEnc.label","فتح مخطط المريض مع الزيارة"},
{"eCA.OpenPatChrtWithoutEnc.label","افتح مخطط المريض بدون زيارة"},
{"eCA.PromptChartTypeForPatChart.label","نوع مخطط المريض"},
{"eCA.PromptStartConsultAEPatQueueInCA.label","بدء استشارة لتسلسل المرضي"},
{"eCA.PreDischargeAdvice.label","توصيات ما قبل الخروج من المستشفى"},
{"eCA.Prepared.label","أعدت"},
{"eCA.NotPrepared.label","غير جاهز"},
{"eCA.FinacialDetailsPopup.label","الشاشة المنبثقة لعرض التفاصيل المالية للمريض"},
{"eCA.CopyFromPreviousSection.label","نسخ من القسم السابق"},
{"eCA.TimeFrameDurtn.label","مدة الإطار الزمني التي يجب مراعاتها لإحالاتي"},
{"eCA.Hr24Formt.label","تنسيق الوقت 24 ساعة"},
{"eCA.noofenccopyprevnotessec.label","عدد الزيارات لنسخ الملاحظات / القسم السابق"},
{"eCA.DefaultView.label","طريقة العرض الافتراضية"},
{"eCA.SelfNoteRefTime.label","وقت التحديث التلقائي للملاحظات الذاتية في قائمة الملخص"},
{"eCA.GenitalDevelopment.label","تطور الأعضاء التناسلية"},
{"eCA.BreastDevelopment.label","نمو الثدي"},
{"eCA.PubicHair.label","شعر عانة"},
{"eCA.ReportCriteria.label","معايير التقرير"},
{"eCA.NursingDiagnosis.label","التشخيص التمريضي"},
{"eCA.GoalStmt.label","بيان الهدف"},
{"eCA.Interventions.label","التدخلات"},
{"eCA.AccessRightsApplicabilityForInError.label","تنطبق حقوق الوصول على الخطأ"},
{"eCA.AccessRightsApplicabilityForUnsignedNotes.label","حقوق الوصول المطبقة على الملاحظات غير الموقعة"},
{"eCA.RecordClinicalNotes.label","سجل الملاحظات السريرية"},
{"eCA.centralsed_default_days.label","يجب مراعاة الفترة الافتراضية أثناء إحضار تفاصيل لقاء المريض في سجل الإنماء والإعمار"},
{"eCA.MarkasReject.label","وضع علامة رفض"},
{"eCA.RemarksforUpdate.label","ملاحظات للتحديث"},
{"eCA.Updated.label","محدث"},
{"eCA.LogoHeadersizeDimensions.label","أبعاد حجم الشعار"},
{"eCA.Height.label","ارتفاع"},
{"eCA.Width.label","عرض"},
{"eCA.Px.label","Px"},
{"eCA.PrimaryInsurance.label","تأمين ابتدائي"},
{"eCA.SecondaryInsurance.label","التأمين الثانوي"},
{"eCA.InsuranceAuthorizationForm.label","نموذج تفويض التأمين"},
{"eCA.notInsurencePatient.label","مريض غير مؤمن عليه"},
{"eCA.BillingGroupPriorityWise.label","مجموعة الفواتير الأساسية - من حيث الأولوية"},
{"eCA.EventFilter.label","فلتر الأحداث"},
{"eCA.AMShift.label","مناوبة الصباح"},
{"eCA.PMShift.label","مناوبة المساء"},
{"eCA.ONShift.label","على المناوبة"},
{"eCA.SelectCategory.label","اختر الفئة"},
{"eCA.DefineChartCategory.label","تحديد فئة المخطط الطبي"},
{"eCA.Therapist.label","المعالج"},
{"eCA.mappingExistingChartId.label","معرّف التخطيط الحالي المطبق "},
{"eCA.ThirdPartyVitalsAck.label","البيانات الحيوية للجهات الخارجية المطلوبة للإقرار"},
{"eCA.InterVitalSignData.label","بيانات العلامات الحيوية المدخلة"},
{"eCA.LogoforClinicalNotes.label","شعار الملاحظات السريرية"},
{"eCA.Site.label","موقع"},
{"eCA.LoginFacility.label","المنشأة الصحية المسجل الدخول عليها"},
{"eCA.ControlToViewAndPrint.label","التحكم لعرض وطباعة تقرير نتائج المعمل"},
{"eCA.SpecimenWise.label","العينة"},
{"eCA.SpecimenIndividualPanelWise.label","مجموعة العينات الفردية"},
{"eCA.ViewDocuments.label","عرض المستندات"},
{"eCA.RestrictingCEHData.label","تقييد بيانات تاريخ الأحداث السريرية"},
{"eCA.EventClassType.label","نوع فئة الحدث"},
{"eCA.ToBeRestrict.label","للتقييد"},
{"eCA.RestrictionApplicableTo.label","القيود المطبقة على"},
{"eCA.PrintCommentsManage.label","طباعة / تعليقات / إدارة"},
{"eCA.historyType.label","نوع التاريخ"},
{"eCA.ViewDocuments.label","عرض المستندات"},
{"eCA.ApprovalNumber.label","رقم الموافقة"},
{"eCA.InsuranceName.label","اسم التأمين"},
{"eCA.ThirdPartyVitalsDataRep.label","تمثيل البيانات الحيوية للطرف الثالث"},
{"eCA.GraphView.label","عرض الرسم البياني"},
{"eCA.TableView.label","عرض جدول"},
{"eCA.AllowAutoSaveInNotes.label","السماح بالحفظ التلقائي في الملاحظات"},
{"eCA.AllowAutoSaveForEvery.label","السماح بالحفظ التلقائي للجميع"},
{"eCA.DifferenceofTimePeriod.label","الفارق الزمني الافتراضي في بيانات العلامات الحيوية المتداخلة"},
{"eCA.minutes.label","الدقائق"},
{"eCA.SerumCreatinine.label","الكرياتينين في الدم"},
{"eCA.CreatinineclearanceForChildren.label","تصفية الكرياتينين للأطفال"},
{"eCA.EstimatedGfrValue.label","قيمة GFR المقدرة"},
{"eCA.CreatinineclearanceForAdult.label","تصفية الكرياتينين للبالغين"},
{"eCA.applicableInterfacedData.label","ينطبق على بيانات الإشارات الحيوية المتداخلة"},
{"eCA.DoctorQuery.label","استعلام الطبيب"},
{"eCA.SupervisorQuery.label","استعلام المشرف"},
{"eCA.CodingStatus.label","حالة الترميز"},
{"eCA.CompleteStatus.label","حالة إكمال"},
{"eCA.DoctorName.label","اسم الطبيب"},
{"eCA.RecordCompletion.label","إتمام التسجيل"},
{"eCA.Sno.label","الرقم المتسلسل"},
{"eCA.Coder.label","المبرمج"},
{"eCA.Export.label","تصدير إلى Excel"},
{"eCA.ClinicalNoteAuditTrial.label","تقرير مسار مراجعة الملاحظات السريرية"},//IN073108
{"eCA.DisplayNoteDescription.label","لعرض عنوان اكتب الملاحظة في وقت عرض الملاحظات وطباعة الملاحظات"},//Exception-PMG2020-COMN-CRF-0085 7605
{"eCA.NoteContentCompressionRequired.label","ملاحظة: ضغط المحتوى مطلوب"},//6484
//27709
{"eCA.Browser.label","المستعرض"},
{"eCA.InternetExplorer.label","متصفح الانترنت"},
{"eCA.GoogleChrome.label","جوجل كروم"},
{"eCA.MozillaFirefox.label","موزيلا فايرفوكس"}
//27709
};
}