/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMM.resources;

import java.util.*;

public class Labels_th extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
		{"eMM.Adjustment.label","จัดให้เรียบร้อย"},
		{"eMM.AllowBonusEntry.label","อนุ�?าตให้ลงบั�?ชีโบนัส"},
		{"eMM.AllowSampleEntry.label","อนุ�?าตให้ลงบั�?ชีตัวอย่าง"},
		{"eMM.BillableItem.label","ราย�?ารที่ออ�?ใบ�?จ้งหนี้ได้"},
		{"eMM.BinLocationCode.label","รหัสBin Location"},
		{"eMM.CategoryType.label","ประเภทชนิด"},
		{"eMM.ContactReference.label","อ้างอิง�?ารติดต่อ"},
		{"eMM.DecentralizedInventory.label","�?ย�?สินค้าคงคลัง"},
		{"eMM.DefaultBatchIDifBatchIDisNotApplicable.label","ยุติ Batch ID ถ้าหา�?ใช้ไม่ได้"},
		{"eMM.DefaultTradeIDifTradeIDisNotApplicable.label","ยุติTrade ID ถ้าหา�?ใช้ไม่ได้"},
		{"eMM.FacilityLevel.label","ระดับสถานพยาบาล"},
		{"eMM.InchargeName.label","ชื่อผู้รับผิดชอบ /ชื่อหัวหน้าเวร"},
		{"eMM.InchargeTitle.label","ตำ�?หน่งผู้รับผิดชอบ"},
		{"eMM.InventoryManagement.label","�?ารบริหารจัด�?ารสินค้าคงคลัง"},
		{"eMM.ItemAlphaCode.label","ราย�?ารAlpha Code"},
		{"eMM.ItemAnalysisCode.label","ราย�?ารรหัส�?ารวิเคราะห์"},
		{"eMM.ItemClassforStore.label","ประเภทราย�?ารสำหรับเ�?็บไว้"},
		{"eMM.ItemforStore.label","ราย�?ารสำหรับเ�?็บไว้"},
		{"eMM.ItemMaster.label","ราย�?ารหลั�?"},
		{"eMM.ItemRemarks.label","หมายเหตุราย�?าร"},
		{"eMM.ItemSpecification.label","�?ารระบุราย�?าร"},
		{"eMM.ItemStoreBinLocation.label","ราย�?ารคลังBin Location"},
		{"eMM.LastPurchaseAdviceDate.label","วันที่�?นะนำ�?ารชำระเงินครั้งสุดท้าย"},
		{"eMM.Machine.label","เครื่องจั�?ร"},
		{"eMM.MaterialCode.label","รหัสวัตถุ"},
		{"eMM.MaterialGroup.label","�?ลุ่มวัตถุ"},
		{"eMM.MaterialGroupCode.label","รหัส�?ลุ่มวัตถุ"},
		{"eMM.ModuleApplicability.label","ระบบที่ใช้ได้"},
		{"eMM.Non-Inventory.label","ไม่ใช่สินค้าคงคลัง"},
		{"eMM.PeriodEndScope.label","�?รอบเวลาสิ้นสุด"},
		{"eMM.PharmacyStockItem.label","สถานที่เตรียม"},
		{"eMM.PurchaseControl.label","�?ารควบคุมราคา"},
		{"eMM.QuantityOnOrder.label","ปริมาณตามตำสั่ง�?ารรั�?ษา"},
		{"eMM.StoreInchargeDetails.label","รายละเอียดผู้รับผิดชอบStoreยา"},
		{"eMM.TradeNameforItem.label","ชื่อ�?ารค้าสำหรับ Item"},
		{"eMM.TransactionRemarksCode.label","รหัสหมายเหตุ�?ารดำเนิน�?าร"}		
		// new addition, don't have thai script
		/*{"eMM.SearchString.label","Search String"},
		{"eMM.SterileStock.label","Sterile Stock"},
		{"eMM.AssemblyDetails/MFGFormulary.label","Assembly Details/MFG Formulary"},
		{"eMM.AssemblyInstructions.label","Assembly Instructions"},
		{"eMM.ItemAnalysisDesc.label","th-Item Analysis Description"},									
		{"eMM.BinDesciption.label","th-Bin Location Description"},							
		{"eMM.SupplierDescription.label","th-Supplier Description"},			
		{"eMM.TRNRemarksDescription.label","th-Transaction Remarks Description"},  
		{"eMM.CSSDComponent.label","th-CSSD Component"},				
		{"eMM.ShowSimilarItems.label","th-Show Similar Items"},																				
		{"eMM.DefaultBatchIDforNonExpiryItems.label","th-Default Batch ID for Non Expiry Items"},							
		{"eMM.Materials.label","th-Materials"}, 
		{"eMM.ItemUOMDefinition.label","th-Item UOM Definition"}, 
		{"eMM.OccupationStatus.label","th-Occupation Status"},
		{"eMM.ApplModules.label","th-Appl Modules"},
		{"eMM.ItemClassCodeFrom.label","th-Item Class Code From"},
		{"eMM.MaterialCodeFrom.label","th-Material Code From"},
		{"eMM.DepartmentCodeFrom.label","th-Department Code From"},
		{"eMM.StoreLocation.label","th-Store Location"},
		{"eMM.TotalNoofDepartments.label","th-Total No of Departments"},
		{"eMM.TotalNoofStore.label","th-Total No of Store"},
		{"eMM.SupplierCodeFrom.label","th-Supplier Code From"},
		{"eMM.SupplierAlphaCode.label","th-Supplier Alpha Code"},
		{"eMM.TradeIdFrom.label","th-Trade Id From"},
		{"eMM.EffectiveStatus.label","th-Effective Status"},
		{"eMM.TRNCode.label","th-TRN Code"},
		{"eMM.ItemAnalysisCodeFrom.label","th-Item Analysis Code From"},
		{"eMM.ReturnPeriodFrom.label","th-Return Period From"},
		{"eMM.ReceivedQty.label","th-Received Qty"},
		{"eMM.SupplierTotal.label","th-Supplier Total"},
		{"eMM.DirectSalesPatient.label","th-Direct Sales Patient"},
		{"eMM.KitTemplate.label","th-Kit Template"},
		{"eMM.ParentStoreforStore.label","th-Parent Store For Store"}, 
   	    {"eMM.MaterialsGroupDesc.label", "Materials Group Desc"},
		{"eMM.DirectSalesAllowed.label", "Direct Sales Allowed"},
		{"eMM.ImportedItem.label","th-Imported Item"},
		{"eMM.EssentialItem.label","th-Essential Item"},
		{"eMM.ReimburseType.label","th-Reimburse Type"},
		{"eMM.NonReimbursable.label","th-Non Reimbursable"},
		{"eMM.PartialReimbursable.label","th-PartialReimbursable"},
		{"eMM.FullyReimbursable.label","th-Fully Reimbursable"},
		{"eMM.UOMDescription.label","th-UOM Description"},
		{"eMM.EquivalentUOMCode.label","th-Equivalent UOM Code"},
		{"eMM.EquivalentUOMDescription.label","th-Equivalent UOM Description"},
		{"eMM.TRNRemarksFrom.label","th-TRN Remarks From"},
		{"eMM.UserAccessForMaterialGroup.label","th-User Access For Material Group"}*/
		// labels to be removed
		/*{"eMM.ConversionFactor.label","ปัจจัย�?ารเปลี่ยน�?ปลง"},
		{"eMM.Customer.label","ลู�?ค้า"},
		{"eMM.DepartmentCode.label","รหัสภาควิชา"},
		{"eMM.Inventory.label","สินค้าคงคลัง"},
		{"eMM.ItemAnalysis.label","ราย�?าร�?ารวิเคราะห์"},
		{"eMM.ItemClass.label","ประเภทราย�?าร"},
		{"eMM.ItemClassCode.label","รหัสประเภทราย�?าร"},
		{"eMM.Manufacturer.label","ผู้ผลิต"},
		{"eMM.ManufacturerName.label","ชื่อผู้ผลิต"},
		{"eMM.Module.label","ระบบ"},
		{"eMM.ModuleID.label","หมายเลขประจำระบบ"},
		{"eMM.Nature.label","ธรรมดา"},
		{"eMM.PrepareLocation.label","ราย�?ารคลังยา"},
		{"eMM.PurchaseUOM.label","หน่วย�?ารวัดของราคา"},
		{"eMM.RepackingGroup.label","�?ลุ่มที่บรรจุใหม่"},
		{"eMM.SpecialItem.label","ราย�?ารพิเศษ"},
		{"eMM.Store.label","Storeยา"},
		{"eMM.StoreCode.label","รหัสStoreยา"},
		{"eMM.Supplier.label","ผู้จำหน่าย"},
		{"eMM.SupplierCode.label","รหัสผู้จำหน่าย"},
		{"eMM.TradeName.label","ชื่อทาง�?ารค้า"},
		{"eMM.TransactionRemarks.label","หมายเหตุ�?ารดำเนิน�?าร"},
		{"eMM.UnitCost.label","หน่วยราคา"},*/
	};
}
