
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eCP.SpecialtyForAssessmentNote.SpecialtyForAssessmentNoteManager
package eCP.SpecialtyForAssessmentNote;

/**
 * Local interface for SpecialtyForAssessmentNote
 */
public interface SpecialtyForAssessmentNoteLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap SpecialityAddModify(java.util.Properties properties, java.util.HashMap hashtable);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
