/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eFM.FMFileDeficiencyMonitoring.FMFileDeficiencyMonitoringManager
package eFM.FMFileDeficiencyMonitoring;

/**
 * Local interface for FMFileDeficiencyMonitoring
 */
public interface FMFileDeficiencyMonitoringLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap createDeficiency(java.util.Properties p, java.util.HashMap htDeficiency, webbeans.eFM.FileDeficiencyMonitoring recordSetDeficiency);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
