/*
*Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
* 
*Warning: This computer program is protected by copyright law and international treaties.
*Unauthorized reproduction or distribution of this program, or any portion of it, 
*may result in severe civil and criminal penalties, and will be prosecuted to 
*the maximum extent possible under the law.
*/
var SQLArray = new Array();

SQLArray['DENTIST']= "SELECT PRACTITIONER_ID CODE, PRACTITIONER_NAME DESCRIPTION FROM AM_PRACTITIONER_LANG WHERE LANGUAGE_ID = '##' AND UPPER(PRACTITIONER_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 2";

SQLArray['TRMT_CATEGORY']= "SELECT A.TRMT_CATEGORY_CODE CODE, A.TRMT_CATEGORY_DESC DESCRIPTION FROM OH_TREATMENT_CATEGORY_LANG A WHERE LANGUAGE_ID='##' AND UPPER(A.TRMT_CATEGORY_DESC) LIKE UPPER(?) AND UPPER(A.TRMT_CATEGORY_CODE) LIKE UPPER(?) ORDER BY A.TRMT_CATEGORY_DESC";

SQLArray['TRMT']= "SELECT A.TRMT_CODE CODE, A.TRMT_DESC DESCRIPTION FROM OH_TREATMENT_LANG A WHERE LANGUAGE_ID='##' AND UPPER(A.TRMT_DESC) LIKE UPPER(?) AND UPPER(A.TRMT_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['CLINICAL_GROUP'] = "SELECT CLINICAL_GROUP_CODE CODE,CLINICAL_GROUP_DESC DESCRIPTION FROM OH_CLINICAL_GROUP_LANG WHERE LANGUAGE_ID='##' AND UPPER(CLINICAL_GROUP_DESC) LIKE UPPER(?) AND UPPER(CLINICAL_GROUP_CODE) LIKE UPPER(?) ORDER BY 2";

//This query has to be modified for the PERFORMING_DEPTLOC_TYPE column based on the category.

SQLArray['EXT_PERF_LOCN'] = "SELECT PERFORMING_DEPTLOC_CODE CODE,PERFORMING_DEPTLOC_SHORT_DESC DESCRIPTION FROM OR_PERFORMING_DEPTLOC_LANG WHERE LANGUAGE_ID='##' AND UPPER(PERFORMING_DEPTLOC_SHORT_DESC) LIKE UPPER(?) AND UPPER(PERFORMING_DEPTLOC_CODE) LIKE UPPER(?) ORDER BY 2";

//Created By Rajesh On 21/02

SQLArray['TRMT_CAT_TYPE']= "SELECT TRMT_CATEGORY_TYPE CODE,TRMT_CATEGORY_TYPE_DESC DESCRIPTION FROM OH_TRTMT_CATEGORY_TYPE_LANG_VW WHERE LANGUAGE_ID='##' AND UPPER(TRMT_CATEGORY_TYPE_DESC) LIKE UPPER(?) AND UPPER(TRMT_CATEGORY_TYPE) LIKE UPPER(?) ORDER BY TRMT_CATEGORY_TYPE";

SQLArray['TRMT_CATEGORY']= "SELECT TRMT_CATEGORY_CODE CODE,TRMT_CATEGORY_DESC DESCRIPTION FROM OH_TREATMENT_CATEGORY_LANG_VW WHERE LANGUAGE_ID='##' AND UPPER(TRMT_CATEGORY_DESC) LIKE UPPER(?) AND UPPER(TRMT_CATEGORY_CODE) LIKE UPPER(?) ORDER BY TRMT_CATEGORY_CODE";

SQLArray['TREATMENT']= "SELECT TRMT_CODE CODE,TRMT_DESC DESCRIPTION FROM OH_TREATMENT_LANG_VW WHERE LANGUAGE_ID='##' AND UPPER(TRMT_DESC) LIKE UPPER(?) AND UPPER(TRMT_CODE) LIKE UPPER(?) ORDER BY TRMT_CODE";

SQLArray['TASKS']= "SELECT TASK_CODE CODE,TASK_DESC DESCRIPTION FROM OH_TASKS_LANG_VW WHERE LANGUAGE_ID='##' AND UPPER(TASK_DESC) LIKE UPPER(?) AND UPPER(TASK_CODE) LIKE UPPER(?) ORDER BY TASK_CODE";

SQLArray['PERIO_CHART_CODE']= "SELECT CHART_CODE CODE,CHART_DESC DESCRIPTION FROM OH_PERIODONTAL_CHART_DEF_HDR WHERE UPPER(CHART_DESC) LIKE UPPER(?) AND UPPER(CHART_CODE) LIKE UPPER(?) ORDER BY CHART_CODE";

SQLArray['PERIO_DON_CHART_COMP']= "SELECT COMPONENT_CODE CODE,  COMPONENT_DESC_USER_DEF DESCRIPTION FROM OH_PERDONTAL_CHRT_COMP_LANG_VW WHERE LANGUAGE_ID = '##' AND UPPER(COMPONENT_DESC_USER_DEF) LIKE UPPER(?) AND UPPER(COMPONENT_CODE) LIKE UPPER(?) ORDER BY COMPONENT_CODE";

function getSqlString(key){
	return replacePlaceHolder(SQLArray[key]);
}


function replacePlaceHolder(str){
//	var facility_id = document.forms[0].facility_id.value;
	var locale = document.forms[0].locale.value;
//	return str.replace("##",locale).replace("@@",facility_id);
	return str.replace("##",locale);
}


