/*
*Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
* 
*Warning: This computer program is protected by copyright law and international treaties.
*Unauthorized reproduction or distribution of this program, or any portion of it, 
*may result in severe civil and criminal penalties, and will be prosecuted to 
*the maximum extent possible under the law.
*/
var SQLArray = new Array();


SQLArray['SURGEON']= "SELECT PRACTITIONER_ID CODE, SHORT_NAME DESCRIPTION FROM AM_PRACTITIONER_LANG_VW WHERE LANGUAGE_ID = '##' AND PRACT_TYPE IN ('MD', 'SG') AND UPPER(SHORT_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 2";

// Qry altered by rajesh for adding role_type on 09/07/08

//SQLArray['SURGEON']= "SELECT PRACTITIONER_ID CODE, PRACTITIONER_NAME DESCRIPTION FROM AM_PRACTITIONER_LANG_VW A WHERE A.LANGUAGE_ID = '##' AND A.EFF_STATUS='E' AND PRACT_TYPE IN (SELECT PRACT_TYPE FROM OT_PRACT_TYPES_FOR_ROLE_TYPE WHERE ROLE_TYPE ='OS') AND UPPER(PRACTITIONER_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 1";//CRF-215 vikash 

//Newly added by rajesh on 25/08

//SQLArray['ASST_SURGEON']= "SELECT SHORT_NAME DESCRIPTION,PRACTITIONER_ID CODE FROM AM_PRACTITIONER_LANG_VW WHERE LANGUAGE_ID = '##' AND PRACT_TYPE IN ('MD','SG') AND NVL(EFF_STATUS,'X') <> 'S'  AND UPPER(SHORT_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 2";
// Qry altered by rajesh for adding role_type on 09/07/08
SQLArray['ASST_SURGEON']= "SELECT PRACTITIONER_ID CODE, PRACTITIONER_NAME DESCRIPTION FROM AM_PRACTITIONER_LANG_VW A WHERE A.LANGUAGE_ID = '##' AND   PRACT_TYPE IN (SELECT PRACT_TYPE FROM OT_PRACT_TYPES_FOR_ROLE_TYPE WHERE ROLE_TYPE ='AS') AND UPPER(PRACTITIONER_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 1";

/*SQLArray['SURGEON_1']="SELECT PHYSICIAN_ID CODE, SHORT_NAME DESCRIPTION FROM SY_PHYSICIAN_MAST WHERE FACILITY_ID = '@@' AND PRACT_TYPE IN ('MD', 'SG') AND UPPER(SHORT_NAME) LIKE UPPER(?) AND UPPER(PHYSICIAN_ID) LIKE UPPER(?) ORDER BY 2";*/

/*SQLArray['ANAESTHETIST'] = "SELECT PHYSICIAN_ID CODE, SHORT_NAME DESCRIPTION FROM SY_PHYSICIAN_MAST WHERE FACILITY_ID = '@@' AND PRACT_TYPE IN ('AN') AND UPPER(SHORT_NAME) LIKE UPPER(?) AND UPPER(PHYSICIAN_ID) LIKE UPPER(?) ORDER BY 2";*/

//SQLArray['ANAESTHETIST'] = "SELECT SHORT_NAME DESCRIPTION,PRACTITIONER_ID CODE FROM AM_PRACTITIONER_LANG_VW WHERE LANGUAGE_ID = '##' AND  PRACT_TYPE IN ('AN') AND  NVL(EFF_STATUS,'X') <> 'S' AND UPPER(SHORT_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 2";

SQLArray['ANAESTHETIST'] = "SELECT PRACTITIONER_ID CODE, PRACTITIONER_NAME DESCRIPTION FROM AM_PRACTITIONER_LANG_VW A WHERE A.LANGUAGE_ID = '##' AND   PRACT_TYPE IN (SELECT PRACT_TYPE FROM OT_PRACT_TYPES_FOR_ROLE_TYPE WHERE ROLE_TYPE ='MA') AND UPPER(PRACTITIONER_NAME) LIKE UPPER(?) AND UPPER(PRACTITIONER_ID) LIKE UPPER(?) ORDER BY 1";


SQLArray['SPECIALITY']= "SELECT A.SPECIALITY_CODE CODE, B.SHORT_DESC DESCRIPTION FROM OT_SPECIALITIES A,  AM_SPECIALITY_LANG_VW B WHERE B.LANGUAGE_ID='##' AND A.SPECIALITY_CODE =  B.SPECIALITY_CODE AND UPPER(B.SHORT_DESC) LIKE UPPER(?) AND UPPER(A.SPECIALITY_CODE) LIKE UPPER(?) ORDER BY 2";//CRF-215

//SQLArray['SPECIALITY']= "SELECT A.SPECIALITY_CODE CODE, B.SHORT_DESC DESCRIPTION FROM OT_SPECIALITIES A,  AM_SPECIALITY_LANG_VW B WHERE B.LANGUAGE_ID='##' AND B.EFF_STATUS='E' AND A.STATUS = 'E' AND A.SPECIALITY_CODE =  B.SPECIALITY_CODE AND UPPER(B.SHORT_DESC) LIKE UPPER(?) AND UPPER(A.SPECIALITY_CODE) LIKE UPPER(?) ORDER BY 2";//CRF-215  vikash

//Added by lakshmi against the emergency reports crf
//SQLArray['SPECIALITY_ER']= "SELECT '*ALL' CODE,'All Speciality' DESCRIPTION FROM DUAL UNION SELECT A.SPECIALITY_CODE CODE, B.SHORT_DESC DESCRIPTION FROM OT_SPECIALITIES A,  AM_SPECIALITY_LANG_VW B WHERE B.LANGUAGE_ID='##' AND A.SPECIALITY_CODE =  B.SPECIALITY_CODE AND UPPER(B.SHORT_DESC) LIKE UPPER(?) AND UPPER(A.SPECIALITY_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['SPECIALITY_ER']= "SELECT CODE,DESCRIPTION  FROM (SELECT '*ALL' CODE,'All Speciality' DESCRIPTION  FROM DUAL UNION SELECT A.SPECIALITY_CODE CODE, B.SHORT_DESC DESCRIPTION FROM OT_SPECIALITIES A,  AM_SPECIALITY_LANG_VW B WHERE B.LANGUAGE_ID='##' AND A.SPECIALITY_CODE =  B.SPECIALITY_CODE ) where  UPPER(DESCRIPTION) LIKE UPPER(?) AND UPPER(CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['WARD']= "SELECT A.NURSING_UNIT_CODE CODE, A.LONG_DESC DESCRIPTION FROM IP_NURSING_UNIT_LANG_VW A WHERE A.LANGUAGE_ID='##' AND FACILITY_ID = '@@' AND UPPER(A.LONG_DESC) LIKE UPPER(?) AND UPPER(A.NURSING_UNIT_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['SURGERY_TYPE']= "SELECT NATURE_CODE CODE, SHORT_DESC DESCRIPTION FROM OT_NATURE_OF_SURGERY_LANG_VW WHERE LANGUAGE_ID='##'AND UPPER(SHORT_DESC) LIKE UPPER(?) AND UPPER(NATURE_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['OPER_ROOM']= "SELECT A.OPER_ROOM_CODE CODE, A.SHORT_DESC DESCRIPTION FROM OT_OPER_ROOM_LANG_VW A WHERE LANGUAGE_ID='##' AND OPERATING_FACILITY_ID = '@@' AND UPPER(A.SHORT_DESC) LIKE UPPER(?) AND UPPER(A.OPER_ROOM_CODE) LIKE UPPER(?) ORDER BY 2";

//Added by lakshmi against the emergency reports crf
//SQLArray['OPER_ROOM_ER']= "SELECT '*ALL' CODE,'*All' DESCRIPTION  FROM DUAL UNION SELECT A.OPER_ROOM_CODE CODE, A.SHORT_DESC DESCRIPTION FROM OT_OPER_ROOM_LANG_VW A WHERE LANGUAGE_ID='##' AND OPERATING_FACILITY_ID = '@@' AND UPPER(A.SHORT_DESC) LIKE UPPER(?) AND UPPER(A.OPER_ROOM_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['OPER_ROOM_ER']= "SELECT CODE,DESCRIPTION FROm (SELECT '*ALL' CODE,'All' DESCRIPTION  FROM DUAL UNION SELECT A.OPER_ROOM_CODE CODE, A.SHORT_DESC DESCRIPTION FROM OT_OPER_ROOM_LANG_VW A WHERE LANGUAGE_ID='##' AND OPERATING_FACILITY_ID = '@@' ) where  UPPER(DESCRIPTION) LIKE UPPER(?) AND UPPER(CODE) LIKE UPPER(?) ORDER BY 2";


SQLArray['PROCEDURE'] = "SELECT OPER_CODE CODE, LONG_DESC DESCRIPTION FROM OT_OPER_MAST_LANG_VW WHERE LANGUAGE_ID='##' AND  UPPER(LONG_DESC) LIKE UPPER(?) AND UPPER(OPER_CODE) LIKE UPPER(?) ORDER BY 2";//CRF-215 & //MMS-QH-CRF-0199

//SQLArray['PROCEDURE'] = "SELECT OPER_CODE CODE, SHORT_DESC DESCRIPTION FROM OT_OPER_MAST_LANG_VW WHERE LANGUAGE_ID='##' AND STATUS='E' AND  UPPER(SHORT_DESC) LIKE UPPER(?) AND UPPER(OPER_CODE) LIKE UPPER(?) ORDER BY 2";//CRF-215

SQLArray['OPER_TYPE'] = "SELECT OPER_TYPE CODE, SHORT_DESC DESCRIPTION FROM OT_OPER_TYPE_LANG_VW WHERE  LANGUAGE_ID='##' AND STATUS = 'E' AND  UPPER(SHORT_DESC) LIKE UPPER(?) AND UPPER(OPER_TYPE) LIKE UPPER(?) ORDER BY 2";//CRF-215

//lang id is missing will not show thai description
SQLArray['DIAGNOSIS'] = "SELECT TERM_CODE CODE, SHORT_DESC DESCRIPTION FROM MR_TERM_CODE WHERE UPPER(SHORT_DESC) LIKE UPPER(?) AND UPPER(TERM_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['POSITION'] = "SELECT A.POSITION_CODE CODE, A.POSITION_DESC DESCRIPTION FROM AM_POSITION_LANG_VW A  WHERE A.LANGUAGE_ID='##' AND UPPER(A.POSITION_DESC) LIKE UPPER(?) AND UPPER(A.POSITION_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['ANAESTHESIA'] = "SELECT ANAESTHESIA_CODE CODE, SHORT_DESC DESCRIPTION FROM AM_ANAESTHESIA_LANG_VW  WHERE LANGUAGE_ID='##' AND UPPER(SHORT_DESC) LIKE UPPER(?) AND UPPER(ANAESTHESIA_CODE) LIKE UPPER(?) ORDER BY 2";

SQLArray['ANAESTHESIA_ALL'] = "SELECT '$$' DESCRIPTION,'ALL' CODE FROM DUAL  UNION  SELECT  INITCAP(SHORT_DESC) ESCRIPTION,ANAESTHESIA_CODE CODE FROM AM_ANAESTHESIA_LANG_VW WHERE LANGUAGE_ID='##' AND UPPER(SHORT_DESC) LIKE UPPER(?) AND UPPER(ANAESTHESIA_CODE) LIKE UPPER(?) ORDER BY 2";



SQLArray['ORGAN'] = "SELECT DISPOSAL_CODE CODE, DISPOSAL_DESC DESCRIPTION FROM OT_ORGAN_DISPOSAL_LANG_VW WHERE  LANGUAGE_ID ='##' AND UPPER(DISPOSAL_DESC) LIKE UPPER(?) AND UPPER(DISPOSAL_CODE) LIKE UPPER(?)  ORDER BY 2";

SQLArray['IMPLANTTYPE'] = "SELECT A.PROSTHESIS_CODE CODE, A.SHORT_DESC DESCRIPTION FROM OT_PROSTHESIS_LANG_VW A  WHERE UPPER(A.SHORT_DESC) LIKE UPPER(?) AND UPPER(A.PROSTHESIS_CODE) LIKE UPPER(?) AND A.LANGUAGE_ID='##'  ORDER BY 2";

SQLArray['NURSE'] = "SELECT A.practitioner_name DESCRIPTION, A.practitioner_id CODE FROM am_practitioner_lang_vw A  WHERE LANGUAGE_ID   ='##' and pract_type in(select B.PRACT_TYPE from OT_PRACT_TYPES_FOR_ROLE_TYPE B where role_type ='NS') AND UPPER(A.practitioner_name) LIKE UPPER(?) AND UPPER(A.practitioner_id) LIKE UPPER(?)";


 
function getSqlString(key){
	return replacePlaceHolder(SQLArray[key]);
}


function replacePlaceHolder(str){
	var facility_id = document.forms[0].facility_id.value;
	var locale = document.forms[0].locale.value;
	return str.replace("##",locale).replace("@@",facility_id);
}


