
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eCP.AssessmentCriteriaScores.AssessmentCriteriaScoresManager
package eCP.AssessmentCriteriaScores;

/**
 * Local interface for AssessmentCriteriaScores
 */
public interface AssessmentCriteriaScoresLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap AddModify(java.util.Properties properties, java.util.ArrayList assess_main);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
