package eBL.resources;
import java.util.*;
public class BLSqlQueries extends ListResourceBundle implements java.io.Serializable {
	public Object[][] getContents() {
        return contents;
   }
	
	static final Object[][] contents = {
			{"BLINTERNALREP_0","SELECT z.code code,z.description description FROM (SELECT 'All Users' description, '**' code FROM DUAL UNION SELECT appl_user_name description, bl_user_id code FROM sm_appl_user, bl_user WHERE bl_user_id = appl_user_id) z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_1","SELECT z.code code,z.description description FROM (SELECT 'All Groups' description, '**' code FROM DUAL UNION SELECT long_desc description, user_group_id code FROM bl_user_group) z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_2","SELECT z.code code,z.description description FROM (SELECT 'All Responsibilities' description, '**' code FROM DUAL UNION SELECT resp_name description, resp_id code FROM sm_resp) z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_3","SELECT z.code code,z.description description FROM (SELECT 'All Users' description, '**' code FROM DUAL UNION SELECT appl_user_name description, bl_user_id code FROM sm_appl_user, bl_user WHERE bl_user_id = appl_user_id) z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_4","SELECT z.code code,z.description description FROM (SELECT 'All Specialities' description, '**' code FROM DUAL UNION SELECT a.short_desc description, a.speciality_code code FROM am_speciality_lang_vw a JOIN op_clinic_lang_vw b ON (a.speciality_code = b.SPECIALITY_CODE AND b.clinic_code = '#' AND b.facility_id = '#' AND NVL (b.eff_status, 'D') = 'E' ) WHERE UPPER(a.language_id) = UPPER('#') ) z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_5","SELECT z.code code,z.description description FROM (SELECT 'All Specialities' description, '**' code FROM DUAL UNION SELECT a.short_desc description, a.speciality_code code FROM am_speciality_lang_vw a JOIN IP_NURS_UNIT_FOR_SPECIALTY b ON (a.speciality_code = b.SPECIALTY_CODE AND b.NURSING_UNIT_CODE = '#' AND b.facility_id = '#') WHERE UPPER(a.language_id) = UPPER('#')) z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_6","SELECT z.code code,z.description description FROM (SELECT 'All Specialities' description, '**' code FROM DUAL UNION SELECT short_desc description, speciality_code code FROM am_speciality_lang_vw WHERE language_id = '#') z WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_7","SELECT description,code FROM (SELECT Short_Desc DESCRIPTION,Blng_Class_Code CODE FROM BL_BLNG_CLASS_lang_vw WHERE LANGUAGE_ID='#' UNION SELECT 'All Billing Class','**' FROM DUAL) WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_8","SELECT description,code FROM (SELECT Short_Desc DESCRIPTION,Blng_Class_Code CODE FROM BL_BLNG_CLASS_lang_vw WHERE LANGUAGE_ID='#' UNION SELECT 'All Billing Class','A' FROM DUAL) WHERE UPPER(description) LIKE UPPER(?) AND UPPER(code) LIKE UPPER(?)#"},
			{"BLINTERNALREP_9","SELECT ACTION_REASON_CODE CODE,ACTION_REASON_DESC DESCRIPTION FROM BL_ACTION_REASON_LANG WHERE action_Reason_code IN (SELECT ACTION_REASON_CODE FROM BL_ACTION_REASON_BY_TYPE WHERE ACTION_TYPE='RA' AND ACTIVE_YN = 'Y') AND UPPER(ACTION_REASON_CODE) LIKE UPPER(?) AND UPPER(ACTION_REASON_DESC) LIKE UPPER(?) AND NVL(status,'E') = 'E' AND LANGUAGE_ID ='#'"},
			//{"BLINTERNALREP_10","SELECT NAME bank_name,NVL(branch_name, ' ') branch_name,code bank_code FROM bl_bank_credit_company_lang_vw WHERE language_id = '#' AND (('#' = 'A' AND NVL(bank_credit_company_ind, '~') = 'C') OR ('#' IN ('B') AND NVL (bank_credit_company_ind, '~') IN ('B') AND ((EXISTS (SELECT b.bank_code FROM bl_slmt_type a,bl_bank_name b WHERE a.cheque_type = b.cheque_type AND slmt_type_code = '#' AND b.bank_code = code) AND '#' > 0 ) OR '#' = 0 ) ) OR ('#' IN ('B') AND NVL (bank_credit_company_ind, '~') IN ('B') AND ((EXISTS ( SELECT b.bank_code FROM bl_slmt_type a, bl_bank_name b WHERE a.cheque_type = b.cheque_type AND a.slmt_type_code = '#' AND a.cheque_type IS NULL AND b.bank_code = code) AND '#' > 0 ) OR '#' = 0 )) OR ('#' IN ('C', 'D', 'Y') AND NVL (bank_credit_company_ind, '~') = 'B' )) AND NVL (status, '~') <> 'S'"},
			{"BLINTERNALREP_10","SELECT NAME bank_name,NVL(branch_name, ' ') branch_name,code bank_code FROM bl_bank_credit_company_lang_vw WHERE language_id = ? AND ((? = 'A' AND NVL(bank_credit_company_ind, '~') = 'C') OR (? IN ('B') AND NVL (bank_credit_company_ind, '~') IN ('B') AND ((EXISTS (SELECT b.bank_code FROM bl_slmt_type a,bl_bank_name b WHERE a.cheque_type = b.cheque_type AND slmt_type_code = ? AND b.bank_code = code) AND ? > 0 ) OR ? = 0 ) ) OR (? IN ('B') AND NVL (bank_credit_company_ind, '~') IN ('B') AND ((EXISTS ( SELECT b.bank_code FROM bl_slmt_type a, bl_bank_name b WHERE a.cheque_type = b.cheque_type AND a.slmt_type_code = ? AND a.cheque_type IS NULL AND b.bank_code = code) AND ? > 0 ) OR ? = 0 )) OR (? IN ('C', 'D', 'Y') AND NVL (bank_credit_company_ind, '~') = 'B' )) AND NVL (status, '~') <> 'S'"},
			{"BLINTERNALREP_11","SELECT EPISODE_ID DESCRIPTION, ENCOUNTER_ID CODE FROM BL_VISIT_FIN_DTLS WHERE upper(EPISODE_ID) like upper(?) and upper(ENCOUNTER_ID) like upper(?) AND OPERATING_FACILITY_ID = '#' #"},
			{"BLINTERNALREP_12","SELECT EPISODE_ID DESCRIPTION, ENCOUNTER_ID CODE FROM bl_episode_fin_dtls WHERE upper(EPISODE_ID) like upper(?) and upper(ENCOUNTER_ID) like upper(?) AND OPERATING_FACILITY_ID = '#' #"}
	};
}
