/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
 /* 
Sr No        Version        Incident/TFS         SCF/CRF             Developer Name
-------------------------------------------------------------------------------------
1            V210120          12493         MOHE-CRF-0038.4          Gomathi Sivakumar
2            V210226           14520        MOHE-CRF-0075.1           Shikha Seth
3		 V210727/210730        21718		MOHE-SCF-0125-TF		Mohana Priya K
--------------------------------------------------------------------------------------
 */
package eBL.resources;
import java.util.*;

public class Labels_ar extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
{"eBL.ACCOUNT_CODE.label","كود الحساب"},
		{"eBL.ACTUAL_AMT.label","القيمه الٿعليه"},
		{"eBL.ADDITIONAL_FACTOR.label","عامل اضافي"},
		{"eBL.AMT_SETTLED.label","القيمه المسويه"},
		{"eBL.ANNUAL_INCOME.label","الدخل السنوي"},
		{"eBL.APPROVAL_CODE.label","رمز التصديق"}, 
		{"eBL.APPROVED_AMT.label","المبلغ المعتمد"},
		{"eBL.APPROVED_DAY.label","الأيام المعتمدة"},
		{"eBL.AUTH_SCREEN.label","شاشة التفويض"},
		{"eBL.AVAILABLE_PACKAGE.label","الباقات المتوفرة"},
		{"eBL.AVAILED.label","المتاح"},
		{"eBL.AVAILED_PRICE.label","السعر المتاح"},
		{"eBL.BANK_NAME.label","اسم المصرٿ"},
		{"eBL.BASE_CHARGE_AMT.label","مبلغ الرسوم الأساسي"},
		{"eBL.BASE_QTY.label","الكمية الأساسية"},
		{"eBL.BASE_RATE.label","السعر الأساسي"},
		{"eBL.BASIC_BILLING_GROUP.label","مجموعة الفواتير الأساسية"},
		{"eBL.BILL_DATE.label","تاريخ الفاتورة"},
		{"eBL.BILL_DOC_NO.label","رقم الفاتورة"},
		{"eBL.BILL_DOC_TYPE.label","نوع مستند الفاتورة"},
		{"eBL.BILL_NO.label","رقم الٿاتورة"},
		{"eBL.BILL_SLMT_DTL.label","تٿاصيل تسوية الٿاتورة"},
		{"eBL.BILLED_AMT.label","مبلغ الفاتورة"},
		{"eBL.BILLING_GROUP_EXPLANATORY_NOTE.label","ملاحظة توضيحية لمجموعة الفواتير"},
		{"eBL.BILLING_GROUP_REMARK.label","ملاحظات مجموعة الفواتير"},
		{"eBL.BILLING_SERVICE_PANEL.label","خدمة / لوحة الفواتير"},
		{"eBL.BRANCH_NAME.label","اسم الٿرع"},
		{"eBL.CANCEL_AMT.label","إلغاء القيمه"},
		{"eBL.CASH_CLOSING_BALANCE.label","الرصيد النقدي عند الاغلاق"},
		{"eBL.CASH_COUNTER.label","الخزينة"},
		{"eBL.CASH_COUNTER_LOGOUT.label","تسجيل خروج الخزينه"},
		{"eBL.CASH_INSTR_DATE.label","تاريخ الأداة النقدية"},
		{"eBL.CASH_INSTR_REF.label","مرجع الاداة النقدي"},
		{"eBL.CASH_INSTR_REMARKS.label","ملاحظات الصك النقدي"},
		{"eBL.CASH_OPENING_BALANCE.label","الرصيد النقدي عند الاٿتتاح"},
		{"eBL.CASH_SLMT_TYPE.label","نوع التسوية النقدية"},
		{"eBL.CASHIER_JOURNAL.label","دفتر النقدية اليومي"},
		{"eBL.CLOSED_YN.label","مغلق {نعم / لا}"},
		{"eBL.CLOSING_DATE_TIME.label","وقت و تاريخ الاغلاق"},
		{"eBL.CONFIRMATION_OF_BILLING_GROUP.label","تأكيد مجموعة الفواتير"},
		{"eBL.COPAY_INDICATOR.label","مؤشر نسبه التحمل"},
		{"eBL.COPAY_VALUE.label","قيمة نسبه التحمل"},
		{"eBL.CREDIT_AUTH_DATE.label","تاريخ تخويل الائتمان"},
		{"eBL.CREDIT_AUTH_REF.label","مرجع مصادقة الائتمان"},
		{"eBL.CREDIT_AUTH.label","تخويل الائتمان"},
		{"eBL.CREDIT_CARD_CO.label","شركة بطاقات الائتمان"},
		{"eBL.CREDIT_DOC_DATE.label","تاريخ مستند الائتمان"},
		{"eBL.CREDIT_DOC_DESC.label","وصف مستند الائتمان"},
		{"eBL.CREDIT_DOC_REF.label","مرجع مستند الائتمان"},
		{"eBL.CUSTOMER_DTL.label","تفاصيل العميل"},
		{"eBL.CUSTOMER_GROUP.label","مجموعة العملاء"},
		{"eBL.CUSTOMER_PAYABLE_AMT.label","قيمة المبلغ المستحق الدٿع من الزبون"},
		{"eBL.DAY_TYPE_CODE.label","كود نوع اليوم"},
		{"eBL.DISCOUNT_PERC.label","خصم %"},
		{"eBL.DISC_PERC_ON_CURR_PRICE.label","خصم٪ على السعر الحالي"},
		{"eBL.DISC_PERC_ON_PROP_PRICE.label","خصم٪ على السعر المتناسب"},
		{"eBL.DISCOUNT_AMT.label","قيمة الخصم"},
		{"eBL.DISCREPANCY_AMT.label","قيمة الٿروقات"},
		{"eBL.DOC_AMT.label","قيمة المستند"},
		{"eBL.DOC_END_DATE.label","تاريخ انتهاء المستند"},
		{"eBL.DOC_REF.label","مرجع المستند"},
		{"eBL.DOC_START_DATE.label","تاريخ بدء المستند"},
		{"eBL.ELIG_LEVEL.label","مستوى الأهلية"},
		{"eBL.EMPLOYER_NAME.label","اسم الموظف"},
		{"eBL.EXCLUSION_SERVICE.label","خدمات الاستبعاد"},
		{"eBL.EXT_ALLOWED.label","مسموح خارجيا "},
		{"eBL.FAMILY_ASSET.label","دخل الاسره"},
		{"eBL.GL_HOLDER_NAME_NRIC.label","اسم حامل GL / NRIC"},
		{"eBL.GOVT_REFERRAL.label","الاحالة الحكومية"},
		{"eBL.GROSS_AMT.label","المبلغ الإجمالي"},
		{"eBL.GROSS_CHARGE.label","التكلفة الإجمالية"},
		{"eBL.GROSS_CHARGE_AMT.label","مبلغ الرسوم الإجمالي"},
		{"eBL.HOSPITAL_REQUEST.label","طلب المستشفى"},
		{"eBL.ILLNESS_DEDUCTIBLE.label","خصم المريض"},
		{"eBL.INCLUSION_SERVICE.label","خدمات الدمج"},
		{"eBL.IP_ALLOWED.label","مسموح للمرضى النزلاء"},
		{"eBL.INSTR_DATE.label","تاريخ الصك"},
		{"eBL.INSTR_REF.label","مرجع الصك"},
		{"eBL.INSTR_REMARK.label","ملاحظات الصك"},
		{"eBL.INS_DTL.label","تفاصيل التأمين"},
		{"eBL.INS_DTL_DOC_REF.label","تفاصيل التأمين / مراجع الوثيقة"},
		{"eBL.LOGGED_IN_USER.label","تسجيل دخول المستخدم "},
		{"eBL.LOGIN_DATE_TIME.label","وقت /تاريخ تسجيل الدخول"},
		{"eBL.LOGOUT_DATE_TIME.label","وقت تاريخ الخروج"},
		{"eBL.NET_CHARGE.label","صافي التكلفة"},
		{"eBL.NO_OF_DEPENDANTS.label","عدد اٿراد الاسره"},
		{"eBL.NON_INS_BILLING_GROUP.label","مجموعة ٿوتره غير مؤمنه"},
		{"eBL.NON_INS_CUSTOMER_CODE.label","رمز العملاء غير المؤمنين"},
		{"eBL.NON_INS_FRAME_TITLE.label","تفاصيل التسوية غير التأمينية / مراجع المستندات"},
		{"eBL.ONLINE_APPROVAL.label","تصديق الكترونى"},
		{"eBL.OP_EMG_ALLOWED.label","مسموح لمرضى العيادات الخارجية / الطوارئ"},
		{"eBL.OPERATOR_ID.label","معرف المشغل"},
		{"eBL.OTHER_SERVICE_AMT.label","مبلغ الخدمة الأخرى"},
		{"eBL.PACKAGE_BILL.label","فاتورة الصفقة"},
		{"eBL.PKG_BILL_NUM_DATE.label","رقم فاتورة الصفقة / التاريخ"},
		{"eBL.PACKAGE_BILL_REF.label","مرجع فاتورة الصفقة"},
		{"eBL.PKG_BILL_TYPE.label","نوع فاتورة الصفقة"},
		{"eBL.PACKAGE_DTL.label","حزمة من التفاصيل"},
		{"eBL.PKG_PRICE.label","سعر الصفقة"},
		{"eBL.PAID_AMT.label","المبلغ المدفوع"},
		{"eBL.PATIENT_HCARD_NOT_AVAILABLE_EXPIRED.label","بطاقة المريض الصحية غير متوفرة / منتهية الصلاحية"},
		{"eBL.PATIENT_REMARK.label","ملاحظات المريض"},
		{"eBL.PATIENT_REQUEST.label","طلب المريض"},
		{"eBL.PAYABLE_AMT.label","القيمه المتوجب دٿعها"},
		{"eBL.PAYER_NAME.label","اسم المسدد"},
		{"eBL.PAYER_REF_ID.label","معرف مرجع الدافع"},
		{"eBL.POLICY.label","بوليصة"},
		{"eBL.POLICY_DTL.label","تفاصيل البوليصه"},
		{"eBL.POLICY_EXPIRY_DATE.label","تاريخ انتهاء البوليصه"},
		{"eBL.POLICY_NO.label","رقم البوليصه"},
		{"eBL.POLICY_TYPE.label","نوع البوليصه"},
		{"eBL.POLICY_TYPE_CODE.label","كود نوع البوليصه"},
		{"eBL.PRE_APP_YN.label","الموافقة المسبقة؟"},
		{"eBL.PRICE_CLASS_CUST_SPECIFIC.label","فئة السعر / العميل المحدد"},
		{"eBL.PVT_REFERRAL.label","الإحالة الخاصة"},
		{"eBL.RECEIPT_AMT.label","استلام القيمه"},
		{"eBL.RECEIPT_TIME.label","وقت الاستلام"},
		{"eBL.RECEIPT_TYPE.label","نوع الإيصال"},
		{"eBL.REFUND.label","إعادة مال"},
		{"eBL.RELATIONSHIP_WITH_GL_HOLDER.label","العلاقة مع GL Holder"},
		{"eBL.HIGHER_CLASS_CHARGE_BASIS_TITLE.label","طلب فئه اعلي و التكلفه المرتبطه بها"},
		{"eBL.RESPONSIBLE_FOR_PAYMENT.label","المسئول عن الدٿع"},
		{"eBL.SALE_DRAFT_NO.label","رقم مسودة البيع"},
		{"eBL.SELF_PAY_BILL_AMT.label","قيمة ٿاتورة الدٿع الداتى"},
		{"eBL.SLMT.label","تسويه"},
		{"eBL.SLMT_CLOSING_DTL.label","تٿاصيل إقٿال التسوية"},
		{"eBL.SLMT_DTL_DOC_REF.label","تفاصيل التسوية / مراجع المستندات"},
		{"eBL.SLMT_INDICATOR.label","مؤشر التسوية"},
		{"eBL.SHIFT_STARTED_BY.label","تبدا المناوبه ب"},
		{"eBL.TIME_TYPE_CODE.label","كود نوع الوقت"},
		{"eBL.TOTAL_SLMT.label","مجموع التسوية"},
		{"eBL.UNBILLED_AMT.label","	مبلغ غير مفوتر"},
		{"eBL.UPDATE_PATIENT_FIN_DTL.label","تحديث البيانات المالية للمريض"},
		{"eBL.VALID_DAYS.label","الايام الصالحه"},
		{"eBL.VALUE_QTY.label","القيمة / الكمية"},
		{"eBL.VISIT_CHARGE_DTL.label","قم بزيارة تفاصيل الرسوم"},
		{"eBL.VISIT_DEDUCTIBLE.label","زيارة المخصوم"},
		{"eBL.ADD_SERV_PRICE.label","سعر الخدمة الإضافية"},
		{"eBL.ADD_SERV_QTY.label","كمية الخدمة الإضافية"},
		{"eBL.BLNG_SERV_CODE.label","كود خدمة الفواتير"},
		{"eBL.SERV_PRICE.label","سعر الخدمة"},
		{"eBL.PKG_VAL_QTY.label","قيمة الحزمة / الكمية"},
		{"eBL.APPLY_REFUND.label","تطبيق استرداد"},
		{"eBL.EXPLANATORY_NOTE.label","ملاحظة توضيحية"},
		{"eBL.VALID_DOCUMENTS.label","مستندات صالحة"},
		{"eBL.VALID_FROM.label","صالح من تاريخ"},
		{"eBL.VALID_TO.label","صالحة ل"},
		{"eBL.RELATIONSHIP_CODE.label","كود العلاقة"},
		{"eBL.LONG_DESCRIPTION.label","الوصف طويل"},
		{"eBL.RELATIONSHIPS.label","العلاقات"},
		{"eBL.CASH_SETTLEMENT.label","التسوية النقدية"},
		{"eBL.USER_SEARCH.label","بحث المستخدم"},
		{"eBL.RECEIPT_TYPES.label","أنواع الإيصالات"},
		{"eBL.ACCOUNT_CODES.label","رموز الحساب"},
		{"eBL.ACCOUNTING_DEPT.label","أقسام المحاسبة"},
		{"eBL.CREDIT_CARD_COMP_NAMES.label","أسماء شركات بطاقات الائتمان"},
		{"eBL.SUBMIT_REPORT.label","تاكيد التقرير"},
		{"eBL.VIEW_CASHIER_JOURNAL.label","عرض حركة الصندوق اليومية"},
		{"eBL.CLOSE_CASH_COUNTER.label","اغلاق الخزينه"},
		{"eBL.CASHIER_SETTLEMENTS.label","تسويات أمين الصندوق"},
		{"eBL.BED_TYPE_FOR_CHARGING_BASIS.label","نوع السرير لاساس التكلفه"},
		{"eBL.CASH_COUNTER_USER.label","مستخدم عداد النقد"},
		{"eBL.CASH_COUNTER_SEARCH.label","البحث عن عداد النقد"},
		{"eBL.CASH_COUNTER_CODE.label","الخزينة"},
		{"eBL.CASH_COUNTER_USER_SEARCH.label","بحث مستخدم عداد النقد"},
		{"eBL.LOGIN_TIME.label","وقت تسجيل الدخول"},
		{"eBL.LOGOUT_TIME.label","وقت الخروج"},
		{"eBL.CASH_COUNTER_IS_FILTERED_FOR.label","عداد النقد مصفى لـ"},
		{"eBL.CASH_COUNTER_IN_USAGE_LIST.label"," قائمة الاستخدام عداد النقد "},
		{"eBL.CASH_COUNTER_LOGIN.label","تسجيل دخول الخزينه"},
		{"eBL.LOGGEDIN_USER_COUNTER_DTLS.label","تسجيل دخول المستخدم /تٿاصيل المكتب"},
		{"eBL.SHIFT_STARTED_AT.label","تبدا المناوبه عند"},
		{"eBL.CONFIRM_LOGIN.label","تأكيد تسجيل الدخول"},
		{"eBL.PRIMARY_BILLING_GROUP.label","مجموعة الٿوتره الاوليه"},
		{"eBL.FAMILY_ANNUAL_INCOME.label","الدخل السنوى للاسرة"},
		{"eBL.PATIENT_RELN_WITH_RESP_PERSON.label","علاقة المريض بالشخص المسئول"},
		{"eBL.GL_HOLDER_NAME.label","اسم حامل GL"},
		{"eBL.PATIENT_RELN_WITH_GL_HOLDER.label","ربط المريض مع حامل GL"},
		{"eBL.PAYER_POLICY_DTLS.label","تٿاصيل بوليصة المسدد"},
		{"eBL.IN_USE_BY.label","مستخدم ل"},
		{"eBL.CANCELLED_COUNT.label","الغاء العد"},
		{"eBL.BOUNCED_COUNT.label","ارتداد العد"},
		{"eBL.NOS.label","ارقام"},
		{"eBL.ADD_MORE_PAYERS.label","اضاٿة اكثر من داٿع"},
		{"eBL.SETTLEMENT_WISE_COLLECTION.label","جمع التسوية"},
		{"eBL.PAYER_GROUP_DESC.label","وصف مجموعة الدافع"},
		{"eBL.ADJUSTMENT_RULE_INDICATOR.label","مؤشر قاعدة التعديل"},
		{"eBL.PERC_AMOUNT_INDICATOR.label","% مؤشر القيمه "},
		{"eBL.ADJUSTMENT_VALUE.label","القيمة المعدله"},
		{"eBL.ADJUSTMENT_INTERFACE_CODE.label","كود واجهة التعديل"},
		{"eBL.DRG_ADJUSTMENET_INTERFACE_CODE.label","رمز واجهة ضبط الدواء"},
		{"eBL.SPL_SERVICE_ADJUSTMENT_INTERFACE_CODE.label","رمز واجهة ضبط خدمة"},
		{"eBL.FIN_DTLS_QRY.label","استعلام التفاصيل المالية"},
		{"eBL.PAT_ENCOUNTER_FIN_DTLS.label","البيانات المالية للمريض / المقابلة"},
		{"eBL.FINANCIAL_REMARKS.label","ملاحظات مالية"},	
		{"eBL.SERVICE_DISC_AMT.label","مبلغ خصم علي الخدمة"},
		{"eBL.OTHER_DISC_AMT.label","مبالغ الخصم الأخرى"},
		{"eBL.DEPOSIT_AMT.label","مبلغ الإيداع"},
		{"eBL.SURGERY_DEPOSIT_AMT.label","مبلغ إيداع الجراحة"},
		{"eBL.REFUNDABLE_DEPOSIT_AMT.label","مبلغ الإيداع قابل للاسترداد"},
		{"eBL.PACKAGE_DEPOSIT_AMT.label","مبلغ إيداع الحزمة"},
		{"eBL.PREPAYMENT_AMT.label","مبلغ الدفع المسبق"},
		{"eBL.UNADJUSTED_DEPOSIT_PREPAYMENT.label","الإيداع غير المعدل / الدفع المسبق"},
		{"eBL.EDIT_ENTER_CHARGE_DETAILS.label","تحرير / إدخال تفاصيل الرسوم"},
		{"eBL.RATE.label","معدل"},
		{"eBL.TOTAL_QTY.label","الكمية الإجمالية"},
		{"eBL.REVISE_QTY.label","مراجعة الكمية"},
		{"eBL.TOTAL_PAYABLE.label","إجمالي المدفوعات"},
		{"eBL.ADD_PAYER.label","إضافة الدافع"},
		{"eBL.MODIFY_PAYER.label","تعديل معلومات الداٿع"},
		{"eBL.REMOVE_PAYER.label","ازالة معلومات الداٿع"},
		{"eBL.INCLUDED_EXCLUDED.label","متضمن / مستبعد"},
		{"eBL.INCLUDED_EXCLUDED_ACTION.label","اجراء متضمن / مستبعد"},
		{"eBL.ORIG_QTY_PER_PANEL.label","الكمية الأصلية لكل لوحة"},
		{"eBL.REVISED_QTY_PER_PANEL.label","الكمية التي تم مراجعتها لكل لوحة"},
		{"eBL.RATE_CHARGE.label","معدل / تهمة"},
		{"eBL.PRACT_STAFF_TYPE.label","نوع الممارس / الموظفين"},
		{"eBL.PRACTITIONER_STAFF.label","ممارس / طاقم"},
		{"eBL.PREAPPR_REQD.label","تمت الموافقة عليه مسبقا"},
		{"eBL.POLICY_START_DATE.label","تاريخ ابتدا البوليصه"},
		{"eBL.POLICY_EFFECTIVE_FROM.label","البوليصه صالحه من تاريخ"},
		{"eBL.POLICY_EFFECTIVE_TO.label","البوليصه صالحه حتى تاريخ"},
		{"eBL.ADD_MORE_SECONDARY_BILLING_GROUPS.label","اضاٿة اكثر من مجموعة ٿوتره ثانويه"},
		{"eBL.VISIT_CHRG_EXEMPT_UPTO.label","زيارة معفاة من الرسوم تصل"},
		{"eBL.VISIT_CHRG.label","رسوم زيارة"},
		{"eBL.PLS_NOTE_DOWN_THE_BILL.label","يرجى تدوين الفاتورة"},
		{"eBL.FOR_THE_VISIT_CHRG.label","مقابل رسوم الزيارة"},
		{"eBL.HOSP_CHRG.label","رسوم المستشفى"},
		{"eBL.PROF_CHRG.label","رسوم مهنيه"},
		{"eBL.PAYER_CODE.label","كود الدافع"},
		{"eBL.PAYER_DESC.label","وصف الدافع"},
		{"eBL.PAYER_GROUP_CODE.label","كود مجموعة الدافع"},
		{"eBL.CASH_GIVEN.label","المبلغ المدٿوع"},
		{"eBL.CASH_RETURNED.label","المبلغ المرجع"},
		{"eBL.RECD_THRU_MAIL.label","استلام عن طريق البريد الالكترونى"},
		{"eBL.ADD_CHARGE_DETAILS.label","أضف تفاصيل الرسوم"},
		{"eBL.EDIT_CHARGE_DETAILS.label","تحرير تفاصيل الرسوم"},
		{"eBL.REMOVE_CHARGE_DETAILS.label","إزالة تفاصيل الرسوم"},
		{"eBL.ADD_BILL_SLMT_DTL.label","أضف تفاصيل تسويات الفاتورة"},
		{"eBL.MODI_BILL_SLMT_DTL.label","تعديل تفاصيل تسويات الفاتورة"},
		{"eBL.REMOVE_BILL_SLMT_DTL.label","إزالة تفاصيل تسويات الفاتورة"},
		{"eBL.SLMT_AMT.label","قيمة التسويه"},
		{"eBL.AMT_COLL.label","القيمه المحصله"},
		{"eBL.REM_SLMT_AMT.label","قيمة التسويه المتبقيه"},
		{"eBL.ADJUST_DEPOSIT.label","ضبط الإيداع"},
		{"eBL.ADJUSTED_DEPOSIT.label","الإيداع المعدل"},
		{"eBL.PAYABLE_AMT_EXCEED.label","تجاوز المبلغ المستحق"},
		{"eBL.INTERIM_BILL_GEN_FREQ_EVERY.label","تكرار إصدار الفاتورة المؤقت كل"},
		{"eBL.CURR_IPS.label","المرضى الداخلي الحاليين"},
		{"eBL.PAYABLE_TYPE.label","نوع الدفع"},
		{"eBL.ANY.label","أي"},
		{"eBL.PENDING_SETTLEMENT.label","التسويه المعلقه"},
		{"eBL.CURRENT_SETTLEMENT.label","التسويه الحاليه"},
		{"eBL.SETTLED_AMOUNT.label","القيمه المسويه"},
		{"eBL.SETTLEMENT_BY_SERVICES.label","تسوية بواسطة الخدمات"},
		{"eBL.LOGIN_TIME_SEARCH.label","البحث عن وقت تسجيل الدخول"},
		{"eBL.POLICY_COVERAGE_BASIS_IND.label","مؤشر أساس تغطية البوليصه"},
		{"eBL.PATIENT_BASED.label","على أساس المريض"},
		{"eBL.PAYER_BASED.label","على أساس الدافع"},
		{"eBL.PREPAY_ADJUST_YN.label","ضبط الدفع المسبق"},
		{"eBL.BILL_GENERATED.label","الفاتوره تم انشائها"},
		{"eBL.NOT_GENERATED_FOR_DAYS.label","لم يتم إنشاؤها لأيام"},		
		{"eBL.EXEMPT_AMOUNT.label","المبلغ المعفى"},
		{"eBL.EXEMPTION_AMOUNT.label","مبلغ الإعفاء"},
		{"eBL.ADJUST_AMT.label","ضبط المبلغ"},
		{"eBL.ADJUSTMENT_AMT.label","مبلغ التعديل"},
		{"eBL.WRITOFF_ROUND.label","القيمه المشطوبه مقربه"},
		{"eBL.SERVICE_DATE.label","تاريخ الخدمة"},
		{"eBL.BILL_CHARGE_DET.label","تفاصيل رسوم الفاتورة"},
		{"eBL.UNBILLED_CHARGE_DET.label","تفاصيل الرسوم الغير مفوتره"},
		{"eBL.CASHIER.label","أمين الصندوق"},
		{"eBL.RECEIVED_BACK_ON.label","تلقى مرة أخرى"},
		{"eBL.REMAINDER.label","بقية"},
		{"eBL.PRIMARY_PRIVILEGE.label","الامتياز الأساسي"},
		{"eBL.PRIMARY_PAYER.label","الدافع الأساسي"},
		{"eBL.ADJUSTMENT_DETAILS.label","تفاصيل التعديل"},
		{"eBL.EXEMPTION_DETAILS.label","تفاصيل الإعفاء"},
		{"eBL.REMAINDER_DETAILS.label","تفاصيل الباقي"},
		{"eBL.WRITE_OFF_DETAILS.label","تفاصيل الشطب"},
		{"eBL.PAT_ENCOUNTER_DETAILS.label","تفاصيل لقاء المريض"},
		{"eBL.PRV_ENCOUNTER_FIN_DETAILS.label","التفاصيل المالية للقاءات السابقة"},
		{"eBL.CAPTURE_REF_SOURCE_DTL.label","التقاط مصدر الإحالة"},
		{"eBL.PMY_REF_SRC.label","مرجع رئيسي"},
		{"eBL.SEC_REF_SRC.label","مصدر الإحالة الثانوي"},
		{"eBL.SEL_FRM_PREV_ENC.label","حدد من المواجهات السابقة"},
		{"eBL.REFERRAL_LINK.label","رابط الإحالة"},
		{"eBL.CASH.label","السيولة النقدية"},
		{"eBL.CREDIT.label","ائتمان"},
		{"eBL.SPONSOR.label","كفيل"},
		{"eBL.UPD_PAT_FIN_DTLS_VALIDATE.label","تحديث البيانات المالية للمريض - قائمة المراجعة"},
		{"eBL.PREREQ_UPD_PAT_FIN_DTLS.label","المتطلبات المسبقة - لتحديث التفاصيل المالية لمستوى المريض"},
		{"eBL.NON_INS_CUSTOMER.label","عميل غير تأميني"},
		{"eBL.SEC_INS_BLNG_GRP.label","مجموعة (مجموعات) فواتير التأمين الثانوية"},
		{"eBL.PRIO_1_INS_PYR.label","الأولوية 1 دافع التأمين"},
		{"eBL.OTH_INS_PYR.label","دافع (دافعو) التأمين الآخرون"},
		{"eBL.CASH_REFUNDED.label","السداد النقدي"},
		{"eBL.GET_CC_INFO.label","احصل على CC Info"},
		{"eBL.FROM_ADM_NO.label","رقم الدخول من"},
		{"eBL.TO_ADM_NO.label","رقم الدخول الي"},
		{"eBL.LAST_BED_CHARGE_DATE.label","تاريخ رسوم آخر سرير"},
		{"eBL.UNADJUST_AMT.label","قيمه غير معدله"},
		{"eBL.SUBMIT_BED_CHARGE_PROCESS.label","عملية ارسال رسوم  السرير"},
		{"eBL.PRMY_REF_SRC_MAND.label","مصدر الإحالة الأساسي إلزامي"},
		{"eBL.SEC_REF_SRC_MAND.label","مصدر الإحالة الثانوي إلزامي"},
		{"eBL.OUTSTANDING_BILLED_AMT.label","المبلغ المستحق في الفاتورة"},
		{"eBL.CUST_GROUP_CODE.label","كود مجموعة العملاء"},
		{"eBL.CHQ_CARD_BANK_NO.label","صك/بطاقة ائتمان/رقم الحساب الجارى"},
		{"eBL.PAYER_DEP_REF_NO.label","اسم المسدد/ البطاقة الشخصية "},
		{"eBL.SERVICE_GROUP.label","مجموعة الخدمة"},
		{"eBL.PANEL_CATEGORY.label","فئة اللوحة"},
		{"eBL.SERVICE_CLASSIFICATION.label","تصنيف الخدمة"},
		{"eBL.APPRL.label","أببل"},
		{"eBL.EXIST_SERV_PANEL.label","الخدمة / اللوحة الحالية"},
		{"eBL.ENT_SERV_PANEL_REQ.label","أدخل طلب الخدمة / اللوحة"},
		{"eBL.ADDL_SERV_PANEL.label","خدمة / لوحة إضافية"},
		{"eBL.PLACE_SERV_PANEL_REQ.label","مكان الخدمة / طلب لوحة"},
		{"eBL.R_C.label","ص / ج"},
		{"eBL.VIEW_EDIT.label","معاينة / تعديل"},
		{"eBL.PLS_NOTE_TRX_REF_NO.label","يرجى ملاحظة رقم مرجع المعاملة: -"},
		{"eBL.PAYER_GROUP.label","مجموعة المسدد"},
		{"eBL.ADM_DEP.label","إيداع القبول"},
		{"eBL.REC_NATURE.label","طبيعة الاستلام"},
		{"eBL.RECEIPT_REFUND.label","الاستلام / الاسترداد"},
		{"eBL.DEPOSIT_TYPE.label","نوع الإيداع"},
		{"eBL.THRU_MAIL.label","من خلال البريد"},
		{"eBL.TRN_DEP.label","إيداع التحويل"},
		{"eBL.OTH_DEP.label","الودائع الأخرى"},
		{"eBL.ADDL_CHARGE.label","رسوم اضافية"},
		{"eBL.CURR_CODE.label","رمز العملة"},
		{"eBL.CURR_DESC.label","وصف العملة"},
		{"eBL.PAT_PAY_SIM_MES_1.label","محاكاة مبالغ مستحقة الدفع للمريض"},
		{"eBL.PAT_PAY_SIM_MES_2.label","في سجل مراجعة تفاصيل الزيارة ، سيتم تعديل المبلغ المستحق للمريض وفقًا لذلك في حالة وجود أي تناقض."},
		{"eBL.DOC_GEN.label","يرجى تدوين رقم (أرقام) المستند:"},
		{"eBL.REC_ADHOC_DISC.label","تسجيل الخصم المخصص"},
		{"eBL.ADHOC_DISC_AMT.label","مبلغ الخصم المخصص"},
		{"eBL.ADHOC_DISC_PERC.label","خصم Adhoc٪ العمر"},
		{"eBL.ADHOC_DISC_REASON.label","سبب الخصم المخصص"},
		{"eBL.ACT_GROSS_AMT.label","المبلغ الإجمالي الفعلي"},
		{"eBL.USE_PREV_DISC_REASON.label","استخدم سبب الخصم السابق"},
		{"eBL.USE_DEFAULT_REASON.label","استخدم السبب الافتراضي"},
		{"eBL.DISC_FOR_ENC_CHARGE_DTLS.label","خصم على تفاصيل رسوم اللقاء"},
		{"eBL.DISC_SLMT_FOR_ENC_CHARGE_DTLS.label","الخصم / التسوية لتفاصيل رسوم اللقاء"},
		{"eBL.ADDL_SERV_CHAGE_DTLS.label","تفاصيل رسوم الخدمة الإضافية"},
		{"eBL.DEPENDENT_SERVICE.label","خدمة المعالين"},
		{"eBL.DISC_AMT.label","قيمه الخصم"},
		{"eBL.VIEW_ADDL_CHARGE_DTL.label","عرض تفاصيل الرسوم الإضافية"},
		{"eBL.VISIT_BILL_GEN_AFTER_DISC.label","يرجى ملاحظة رقم فاتورة الزيارة التي تم إنشاؤها بعد الخصومات:"},		
		{"eBL.RECORD_ADDL_SUR_CHARGES.label","تسجيل رسوم الجراحة الإضافية"},
		{"eBL.VW_SUBS_OPEN_PACKAGE_DTL.label","عرض تفاصيل باقة الاشتراك المفتوحة"},
		{"eBL.SUBS_OPEN_PACKAGE_DTL.label","تفاصيل باقة الاشتراك المفتوحة"},
		{"eBL.PKG_DESC.label","حزمة الوصف"},			
		{"eBL.PKG_AMT.label","مبلغ العبوة"},			
		{"eBL.AVAILD_AMT.label","المبلغ المتاح"},			
		{"eBL.PKG_COMPONENT.label","مكونات الحزمه"},			
		{"eBL.QTY_LMT.label","حد الكمية"},			
		{"eBL.AVAILD_QTY.label","الكمية المتاحة"},			
		{"eBL.AMT_LMT.label","حد المبلغ"},
		{"eBL.AVAILD_PACK_DTLS.label","تفاصيل الحزمة المتوفرة"},
		{"eBL.CHARGE_FOR_MAIN_SERV.label","رسوم عن الخدمة الرئيسية"},
		{"eBL.CHARGE_FOR_ADDL_SERV.label","رسوم الخدمة الإضافية"},
		{"eBL.INVALID_ADDL_SERV.label","خدمة إضافية غير صالحة"},
		{"eBL.IS_SPL_CLINIC_ENC_YN.label","لقاء مرتبط بعياده خاصه"},
		{"eBL.MAX_NO_OF_ENC_ALLOW_FOR_CREDIT_DOC.label","الحد الأقصى المسموح به لعدد اللقاءات أو مرجع مستند الاعتماد"},
		{"eBL.CLASS_TYPE.label","نوع التصنيف"},
		{"eBL.CLASS_CODE.label","رمز التصنيف"},
		{"eBL.CASH_PAY_PAT.label","مريض الدفع النقدي"},
		{"eBL.INCOME_ASSET.label","الدخل / الأصول"},
		{"eBL.INCOME_ASSET_BASED.label","على أساس الدخل / الأصول"},
		{"eBL.EXEMPTED.label","معفى"},
		{"eBL.SOCIAL_GRANT.label","المنحة الاجتماعية"},
		{"eBL.INCOME_ASSET_BASED.label","على أساس الدخل / الأصول"},
		{"eBL.SPECIAL_CASE.label","حالة خاصة"},
		{"eBL.SPONSORED.label","برعاية"},
		{"eBL.INCOME.label","الإيرادات"},
		{"eBL.ASSET.label","الأصل"},
		{"eBL.INDVL_INC_FREQ.label","تردد الدخل الفردي"},
		{"eBL.SPOUSE_INC_FREQ.label","تردد دخل الزوج"},
		{"eBL.DEP_INC_FREQ.label","تردد دخل المعالين"},
		{"eBL.FIN_CLASS.label","التصنيف المالي"},
		{"eBL.SOCIAL_PENSIONER_ID.label","رقم المعاش الاجتماعي"},
		{"eBL.WRITOFF_AMT.label","مبلغ الشطب"},
		{"eBL.INSTLMT_DUE_AMT.label","مبلغ القسط المستحق"},
		{"eBL.CHRG_NON_CHRG_PAT_DUR_ENC.label","فرض رسوم على مريض غير متحمل رسوم أثناء المقابلة"},
		{"eBL.PAT_REG_CHARGE_BILL_GEN.label","يرجى تدوين الفاتورة # لرسوم تسجيل المريض٪ المريض مستحق الدفع و"},
		{"eBL.PAT_REG_CHRG.label","رسوم تسجيل المريض"},
		{"eBL.SERV_PANEL_CODE.label","رمز الخدمة / اللوحة"},
		{"eBL.SERV_PANEL_DESC.label","وصف الخدمة / اللوحة"},
		{"eBL.BLNG_GRP_DESC.label","وصف مجموعة الفواتير"},
		{"eBL.INV_AMT.label","المبلغ المفوتر"},
		{"eBL.AUTOMATIC.label","تلقائي"},
		{"eBL.CURR_IP.label","المرضى الداخلي الحاليين"},
		{"eBL.TOD_EXP_DISCHRG.label","حالات الخروج المتوقعة لهذا اليوم"},
		{"eBL.TOD_DISCHRGD_PAT.label","حالات خروج اليوم"},
		{"eBL.BILL_PYMT_DTLS.label","تفاصيل الفاتورة / الدفع"},
		{"eBL.FIN_SUMM_BY_BG.label","زعنفة. ملخص بواسطة مجموعة الفواتير"},
		{"eBL.FIN_SUMM_BY_PYR.label","زعنفة. ملخص بواسطة الدافع"},
		{"eBL.NO_OF_DAYS_OCCU_FORECAST.label","عدد الأيام المتوقع اشغالها مطلوب"},
		{"eBL.EXPECTED_IP.label","المرضى الداخليون المتوقعون"},
		{"eBL.OUTST_PAT_BILLS.label","فاتورة (فواتير) المريض المعلقة"},
		{"eBL.CREDIT_CARD_NO.label","رقم بطاقة الائتمان"},
		{"eBL.ROUND_OFF.label","التقريب"},
		{"eBL.CHARGE_DTL.label","تفاصيل الرسوم"},
		{"eBL.FOR_THE_CHRG.label","للرسوم"},
		{"eBL.CASH_IN_HAND.label","النقدية في اليد"},
		{"eBL.CHQ_IN_HAND.label","الشيك في اليد"},
		{"eBL.CASH_HANDED_OVER.label","تسليم النقدية"},
		{"eBL.DENO.label","فئة"},
		{"eBL.NUM.label","رقم"},
		{"eBL.CHEQ_NUM.label"," رقم الشيك"},
		{"eBL.CHEQ_DATE.label","تاريخ الشيك"},
		{"eBL.CASH_COLLECTION.label","استلام النقود"},
		{"eBL.CHEQ_COLLECTION.label","تحقق من المجموعة"},
		{"eBL.HAND_OVER_REQ_AMT.label","مبلغ طلب التسليم"},
		{"eBL.NOS.label","رقم"},
		{"eBL.CHEQUE.label","الشيك"},
		{"eBL.REQ_DATE_TIME.label","وقت التاريخ المطلوب"},
		{"eBL.TRANS_DTLS.label","تفاصيل الحركة"},
		{"eBL.HANDOVER_REQ_DTLS.label","تفاصيل طلب التسليم"},
		{"eBL.CASH_CHEQ_COLL_DTLS.label","تفاصيل تحصيل النقد / الشيكات"},
		{"eBL.CASH_DTLS.label","تفاصيل النقدية"},
		{"eBL.CHEQ_DTLS.label","تفاصيل الشيك"},
		{"eBL.OP_OVERRIDE_REIM_DTLS.label","تعديل مبلغ الفاتورة القابلة للاسترداد / OP / EXT"},
		{"eBL.IP_OVERRIDE_REIM_DTLS.label","تعديل المبلغ القابل لسداد فاتورة IP"},
		{"eBL.OP_OVERRIDE_UNBLD_REIM_DTLS.label","تعديل OP / EXT المبلغ غير القابل للدفع غير المفوتر"},
		{"eBL.IP_OVERRIDE_UNBLD_REIM_DTLS.label","تعديل مبلغ IP غير المفوتر قابل للسداد"},
		{"eBL.LIST_OF_SERV.label","قائمة الخدمات"},
		{"eBL.DFND_REIMB.label","السداد المحدد"},
		{"eBL.DFN_REIMB_TYPE.label","نوع قابل للسداد محدد"},
		{"eBL.DFN_REIMB_AMT.label","المبلغ المحدد قابل للسداد"},
		{"eBL.CURR_REIMB.label","السداد الحالية"},
		{"eBL.CURR_REIMB_TYPE.label","النوع الحالي القابل للسداد"},
		{"eBL.REVISED_AMT.label","المبلغ المنقح"},
		{"eBL.FULL.label","ممتلئ"},
		{"eBL.PART.label","جزء"},
		{"eBL.NA.label","غير متاح"},
		{"eBL.AUDIT_DTLS.label","تفاصيل المراجعة"},
		{"eBL.AUDIT_NO.label","رقم المراجعة"},
		{"eBL.OLD_REIMB.label","قديم قابل للسداد"},
		{"eBL.OLD_REIMB_TYPE.label","نوع قديم قابل للسداد"},
		{"eBL.OLD_REIMB_AMT.label","المبلغ القديم القابل للسداد"},
		{"eBL.NEW_REIMB.label","جديد قابل للسداد"},
		{"eBL.NEW_REIMB_TYPE.label","نوع جديد قابل للسداد"},
		{"eBL.NEW_REIMB_AMT.label","المبلغ الجديد القابل للسداد"},
		{"eBL.OVERRIDING_REASON.label","تجاوز السبب"},
		{"eBL.HO_AMOUNT.label","HO كمية"},
		{"eBL.REG_BILL_GEN_AFTER_DISC.label","يرجى ملاحظة رقم فاتورة التسجيل الذي تم إنشاؤه بعد الخصومات:"},
		{"eBL.CHRG_DUR_ENC.label","تحميل في الحساب"},
		{"eBL.DISC_FOR_REG_CHARGE_DTLS.label","الخصم لتفاصيل رسوم التسجيل"},
		{"eBL.CHAR_AT_REG.label","يتم تحميلها عند التسجيل"},
		{"eBL.LAST_MOD_DATE_TIME.label","تاريخ / وقت آخر تعديل"},
		{"eBL.EX.label","EX"},
		{"eBL.RateBased.label","معدل على أساس"},
		{"eBL.AmountIndicator.label","مؤشر المبلغ"},
		{"eBL.FactorRate.label","العامل / المعدل"},
		{"eBL.NoLimit.label","لا حدود"},
		{"eBL.Dtls.label","تفاصيل"},
		{"eBL.PERCENT.label","٪"},
		{"eBL.addRow.label","انقر لإضافة صف"},
		{"eBL.serviceLimit.label","حد الخدمة"},
		{"eBL.PercentageLimit.label","٪ حد"},
		{"eBL.del.label","ديل"},
		{"eBL.replaceableService.label","خدمة قابلة للاستبدال"},
		{"eBL.replaceableCatalog.label","كتالوج قابل للاستبدال"},
		{"eBL.orderAssociated.label","ترتيب المرتبطة"},
		{"eBL.AsPerRule.label","حسب القاعدة"},
		{"eBL.Pack_Subs.label","اشتراك الباقة"},
		{"eBL.Subs_pack.label","باقة الاشتراك"},
		{"eBL.Bill_CLASS_CODE.label","رمز فئة الفواتير"},
		{"eBL.FACTOR_APPL_SER.label","عامل ينطبق على الخدمة"},
		{"eBL.FACTOR.label","عامل"},
		{"eBL.ApplyFactorForServiceLimit.label","العامل المطبق على حد الخدمة"},
		{"eBL.AcrossEncounters.label","عبر لقاءات"},
		{"eBL.CashCredit.label","الائتمان النقدية"},
		{"eBL.Customers.label","العملاء"},
		{"eBL.PRICE_FACT.label","السعر / العامل"},
		{"eBL.CopyFrom.label","نسخة من"},
		{"eBL.CopyTo.label","نسخ الى"},
		{"eBL.CopyPackage.label","نسخ الحزمة"},
		{"eBL.PayerDtls.label","تفاصيل الدافع"},
		{"eBL.CUSTOMERS_SPECIFIC.label","السعر المحدد للعملاء والتغطية"},
		{"eBL.PACKAGE_PRICE_CLASS.label","فئة سعر الحزمة"},
		{"eBL.OUTSIDE_PACKAGE_PRICE_CLASS.label","فئة سعر الباقة الخارجية"},
		{"eBL.AssociateSubscribedPackage.label","حزمة الاشتراك المنتسب"},
		{"eBL.APPROVED_DATE.label","تاريخ الموافقة"},
		{"eBL.UNLIMITED.label","غير محدود"},
		{"eBL.PERC_AMOUNT.label","٪القيمة"},
		{"eBL.PRICE_CLASS.label","فئة السعر"},
		{"eBL.packageApprovalAmt.label","مبلغ الموافقة على الحزمة"},
		{"eBL.additionalApprovals.label","الموافقات الإضافية"},
		{"eBL.additionalApproval.label","موافقة إضافية"},
		{"eBL.packageApprovals.label","موافقات الحزمة"},
		{"eBL.packageApproval.label","الموافقة على الحزمة"},
		{"eBL.userGroup.label","مجموعة المستخدمين"},
		{"eBL.userGroupId.label","معرف مجموعة المستخدم"},
		{"eBL.userGroupName.label","اسم مجموعة المستخدم"},
		{"eBL.PackageCreation.label","إنشاء الحزمة"},
		{"eBL.PackageTransfer.label","نقل الطرود"},
		{"eBL.PackageDiscount.label","خصم الحزمة"},
		{"eBL.PackageRefund.label","استرداد الطرد"},
		{"eBL.PackageCancel.label","إلغاء الحزمة"},
		{"eBL.InitialCreditAuthorization.label","تفويض ائتماني مبدئي"},
		{"eBL.InitialCreditAuthorizationDate.label","التاريخ المبدئي للمصادقة الائتمانية"},
		{"eBL.ROUND_TO.label","جولة إلى"},
		{"eBL.ROUND_INDICATOR.label","مؤشر دائري"},
		{"eBL.DOWN.label","أسفل"},
		{"eBL.AUTO_REFUND.label","استرداد تلقائي"},
		{"eBL.DEPOSIT.label","الوديعة"},
		{"eBL.PARTIAL_DEPOSIT.label","الإيداع الجزئي"},
		{"eBL.MIN_DEPOSIT_AMOUNT.label","الحد الأدنى لمبلغ الإيداع"},
		{"eBL.PackageCode-Desc-Seqno.label","حزمة كود تنازلي رقم التسلسل"},
		{"eBL.CLOSE_PACKAGE.label","إغلاق الحزمة"},
		{"eBL.packageSeqNo.label","رقم تسلسل الحزمة "},
		{"eBL.UtilizedAmt.label","تستخدم Amt"},
		{"eBL.BillingClassCode.label","رمز فئة الفواتير"},
		{"eBL.BillingClassDesc.label","وصف فئة الفوترة"},
		{"eBL.RateIndicator.label","مؤشر السعر"},
		{"eBL.RefundRate.label","معدل الاسترداد"},
		{"eBL.UtilizedServiceQty.label","خدمة Qty"},
		{"eBL.UtilizedServiceAmt.label","استخدام الخدمة Amt"},
		{"eBL.Excl.label","غير شامل."},
		{"eBL.RefundAmt.label","المبلغ المسترد"},
		{"eBL.PackageServiceCode.label","كود خدمة الحزمة"},
		{"eBL.PackageApplicable.label","حزمة قابلة للتطبيق"},
		{"eBL.PackageEffBackDated.label","العبوة فعالة من تاريخها القديم"},
		{"eBL.GLPostingBySmmry.label","نشر GL عن طريق الملخص"},
		{"eBL.ValidDysPkgSerOrds.label","صلاحية الحصول على طلبات خدمة الحزمة"},
		{"eBL.unavailedSrvCode.label","رمز الخدمة غير متوفر"},
		{"eBL.AutoRefundApplicable.label","ينطبق استرداد تلقائي"},
		{"eBL.ValidDysForPkgRefund.label","صلاحية استرداد خدمة الحزمة"},
		{"eBL.fromDateOfBlGen.label","(من تاريخ إصدار الفاتورة)"},
		{"eBL.AccountingCode.label","كود المحاسبة"},
		{"eBL.DISC_ACC_CODE.label","كود محاسبة الخصم"},
		{"eBL.CustomerBasePrice.label","السعر الأساسي للعميل"},
		{"eBL.CustomerRateBasedServices.label","الخدمات القائمة على أسعار العملاء"},
		{"eBL.CustomerChargeBasedServices.label","خدمات العملاء القائمة على الرسوم"},
		{"eBL.PackageRateBaseHdr.label","خدمات الباقات (حسب السعر)"},
		{"eBL.PackageChargeBaseHdr.label","خدمات الحزمة (على أساس الرسوم)"},
		{"eBL.UtilizedQty.label","الكمية المستخدمة"},
		{"eBL.Refunded.label","معاد"},
		{"eBL.DEPOSITCOLECTD.label","تم جمع الإيداع"},
		{"eBL.ELIGIBLE.label","مؤهل"},
		{"eBL.PLACED.label","تم وضعها"},
		{"eBL.REGISTERED.label","مسجل"},
		{"eBL.DISCOUNT_AS_PER_SETUP.label","الخصم حسب الإعداد"},
		{"eBL.discountType.label","نوع الخصم"},
		{"eBL.Discount.label","خصم"},
		{"eBL.Transactionreference.label","رمز العملية"},
		{"eBL.EXEMPTINPKG.label","معفى في الحزمة"},
		{"eBL.PAYERCOVERAGE.label","تغطية الدافع"},
		{"eBL.PKG_DEP.label","إيداع الحزمة"},
		{"eBL.BLNG_CLASS_ELIG_PKG.label","أهلية فئة الفواتير للحزمة"},
		{"eBL.PackageAdhocRefund.label","استرداد حزمة Adhoc"},
		{"eBL.VarianceSrvCode.label","كود خدمة التباين"},
		{"eBL.RefundRatePer.label","معدل استرداد٪"},
		{"eBL.CUST_GROUP_DESC.label","وصف مجموعة العملاء"},
		{"eBL.CUST_NAME.label","اسم الزبون"},
		{"eBL.AvailableServiceAmt.label","كمية الخدمة المتاحة"},
		{"eBL.PatientDepositForPackage.label","وديعة المريض للحزمة"},
		{"eBL.FactorForServiceRate.Label","عامل معدل الخدمة"},
		{"eBL.PackageGrouping.label","مجموعة العبوات"},
		{"eBL.CopyBaseDef.label","نسخ Base Def"},
		{"eBL.ReplaceWithBaseDef.label","استبدل بـ Base Def"},
		{"eBL.SalesCategory.label","فئة المبيعات"},
		{"eBL.DrugPenalty.label","عقوبة المخدرات"},
		{"eBL.DISC_APPL.label","يطبق الخصم"},
		{"eBL.RegistrationFee.Label","رسوم التسجيل"},
		{"eBL.ConsultationFee.Label","رسوم الاستشارة"},
		{"eBL.PackageCode.Label","كود الحزمة"},
		{"eBL.PackageDesc.Label","وصف الحزمة"},
		{"eBL.EffectiveFrom.Label","ساري المفعول من"},
		{"eBL.BillingClass.Label","فئة الفواتير"},
		{"eBL.Price.Label","السعر"},
		{"eBL.BillingService.Label","خدمة الفواتير"},
		{"eBL.BillingServCode.Label","كود خدمة الفواتير"},
		{"eBL.AmountInd.Label","المبلغ إند"},
		{"eBL.QtyLimit.Label","حد الكمية"},
		{"eBL.Cost.Label","كلفة"},
		{"eBL.PackageCost.Label","تكلفة الحزمة"},
		{"eBL.Customer.label","الزبون"},
		{"eBL.Currency.label","عملة"},
		{"eBL.ConversionRate.label","معدل التحويل"},
		{"eBL.OutstandingAmount.label","كمية رهيبة"},
		{"eBL.ModeOfPayment.label","طريقة الدفع"},
		{"eBL.PaymentMode.label","طريقة الدفع"},
		{"eBL.CashDetails.label","التفاصيل النقدية"},
		{"eBL.CashOutstandingAmount.label","كمية رهيبة"},
		{"eBL.CashPaid.label","النقدية المدفوعة"},
		{"eBL.RefundAmount.label","المبلغ المسترد"},
		{"eBL.CardDetails.label","معلومات البطاقة"},
		{"eBL.CardOutstandingAmount.label","كمية رهيبة"},
		{"eBL.CardType.label","نوع البطاقة"},
		{"eBL.CardNumber.label","رقم البطاقة"},
		{"eBL.IssuingAuthority.label","سلطة الإصدار"},
		{"eBL.IssuingBranchName.label","اصدار اسم الفرع"},
		{"eBL.CardHoldersName.label","اسم حامل البطاقة"},
		{"eBL.AuthCode.label","APPR / كود المصادقة"},
		{"eBL.BatchNo.label","رقم الحزمة"},
		{"eBL.CardAmount.label","مبلغ البطاقة"},
		{"eBL.CounterShift.label","عداد النقد / التحول"},
		{"eBL.DocumentNo.label","رقم الوثيقة"},
		{"eBL.Date.label","تاريخ"},
		{"eBL.TransactionType.label","نوع المعاملة"},
		{"eBL.Nature.label","طبيعة"},
		{"eBL.Amount.label","كمية"},
		{"eBL.BlockedforOP.label","محظور بسبب OP"},
		{"eBL.BlockedforIP.label","محظور بسبب IP"},
		{"eBL.BlockedForDC.label","ممنوع من أجل DC"},
		{"eBL.FromDate.label","من التاريخ"},
		{"eBL.ToDate.label","ان يذهب في موعد"},
		{"eBL.ServiceLimit.label","حد الخدمة"},
		{"eBL.Remarks.label","ملاحظات"},
		{"eBL.BannerFormat.label","تنسيق البانر"},
		{"eBL.BannerAssociation.label","جمعية بانر"},
		{"eBL.StaticInformation.label","معلومات ثابتة"},
		{"eBL.Format.label","شكل"},
		{"eBL.BannerCode.label","كود البانر"},
		{"eBL.BannerDescription.label","وصف البانر"},
		{"eBL.FormatSelection.label","تحديد التنسيق"},
		{"eBL.SeqNo.label","تسلسل رقم"},
		{"eBL.Column1.label","العمود 1"},
		{"eBL.Column2.label","العمود 2"},
		{"eBL.Column3.label","العمود 3"},
		{"eBL.StaticLegend.label","أسطورة ثابتة"},
		{"eBL.Static Value.label","قيمة ثابتة"},
		{"eBL.AssociateBillingGroup.label","مجموعة الفواتير المنتسبة"},
		{"eBL.FunctionId.label","معرف الوظيفة"},
		{"eBL.FunctionDesc.label","وصف الوظيفة"},
		{"eBL.RightsType.label","نوع الحقوق"},
		{"eBL.RightsCode.label","كود الحقوق"},
		{"eBL.BillingGroupId.label","مجموعة الفواتير"},
		{"eBL.BillingGroupDesc.label","مجموعة الفواتير تنازليًا"},
		{"eBL.EpisodeType.label","نوع الحلقة"},
		{"eBL.EffFrom.label","من تاريخ"},
		{"eBL.EffTo Value.label","تاريخ التنفيذ"},
		{"eBL.encounterperiod.label","فترة اللقاء"},
		{"eBL.DOCTOR_NAME.label","اسم الطبيب"},
		{"eBL.EPISODE_STATUS.label","حالة الحلقة"},
		{"eBL.EPISODE_TYPE.label","نوع الحلقة"},
		{"eBL.OneWeek.label","أسبوع 1"},
		{"eBL.OneMonth.label","1 شهر"},
		{"eBL.CURRENT_INPATIENT.label","IP الحالي / DC"},
		{"eBL.CURRENT_EMERGENCY.label","حالة الطوارئ الحالية"},
		{"eBL.CURRENT_OUTPATIENT.label","OP / EM الحالي"},
		{"eBL.EXISTING_ORDERS.label","الأوامر الموجودة"},
		{"eBL.NEW_ORDERS.label","طلبات جديدة"},
		{"eBL.CLASSIFICATION.label","تصنيف"},
		{"eBL.BILLING_SERVICE_CODE.label","رمز الخدمة"},
		{"eBL.BILLING_SERVICE_DISC.label","قرص الخدمة"},
		{"eBL.ORDER_CATEGORY.label","فئة الطلب"},
		{"eBL.ORDER_TYPE.label","نوع الطلب"},
		{"eBL.ORDER_CATALOG_CODE.label","اطلب كود الكتالوج"},
		{"eBL.ORDER_CATALOG_DISC.label","طلب قرص كتالوج"},
		{"eBL.CONTAINS.label","يحتوي على"},
		{"eBL.PANEL_CODE.label","كود اللوحة"},
		{"eBL.BILLING_SERVICE_PANEL.label","الخدمة / اللوحة"},
		{"eBL.POLICY_IN_EX.label","السياسة في / على سبيل المثال"},
		{"eBL.ACTION_REASON.label","سبب العمل"},
		{"eBL.PRE_APP_REQ.label","الموافقة المسبقة مطلوبة"},
		{"eBL.Revenue_Stage.label","مرحلة الإيرادات"},
		{"eBL.ORDER_TYPE_DESC.label","نوع الطلب تنازلي"},
		{"eBL.StaticInformation.label","معلومات ثابتة"},
		{"eBL.LegendCode.label","رمز الأسطورة"},
		{"eBL.Description.label","وصف"},
		{"eBL.ReceiptNatureCode.Label","رمز طبيعة الاستلام"},
		{"eBL.ReceiptDescription.Label","وصف الإيصال"},
		{"eBL.ApplicableFor.Label","تنطبق على"},
		{"eBL.DefaultRemarks.Label","الملاحظات الافتراضية"},
		{"eBL.ReceiptType.Label","نوع الإيصال"},
		{"eBL.ServiceRestriction.Label","قيود الخدمة"},
		{"eBL.Refundable.Label","مستردة"},
		{"eBL.AdjDuringBillGeneration.Label","ضبط أثناء إنشاء الفاتورة"},
		{"eBL.AdjustFully.Label","ضبط بالكامل"},
		{"eBL.AcrossEncounter.Label","عبر المواجهة"},
		{"eBL.ApplicableEpisode.Label","الحلقة القابلة للتطبيق"},
		{"eBL.GenReceiptForAdj.Label","إنشاء إيصال للتعديل"},
		{"eBL.CancelandGenIntdocForPartial.Label","إلغاء وإنشاء مستند داخلي للتسوية الجزئية"},
		{"eBL.AlwaysAdjFullDurBillGen.Label","اضبط دائمًا أثناء إنشاء الفاتورة"},
		{"eBL.AllowPartAdjDurBillGen.Label","السماح بالتعديل الجزئي أثناء إنشاء الفاتورة"},
		{"eBL.AdjustDurSettle.Label","ضبط أثناء التسوية"},
		{"eBL.AlwaysAdjFullDurSettle.Label","قم دائمًا بضبط الوضع بالكامل أثناء التسوية"},
		{"eBL.AllowPartAdjDurSettle.Label","السماح بالتعديل الجزئي أثناء التسوية"},
		{"eBL.PatientDeposit.Label","إيداع المريض"},
		{"eBL.CustomerDeposit.Label","إيداع العميل"},
		{"eBL.AllowAdjwithCustBills.Label","السماح بالتعديل مع فواتير العملاء"},
		{"eBL.AllowAdjwithPatBills.Label","السماح بالتعديل مع فواتير المرضى"},
		{"eBL.AllowAdjForMultPat.Label","السماح بالتعديل لعدة مرضى"},
		{"eBL.ReceiptNatureShortDesc.Label","وصف قصير"},
		{"eBL.ReceiptNatureLongDesc.Label","وصف طويل"},
		{"eBL.EffectiveTo.Label","فعالة ل"},
		{"eBL.RIGHTS_TYPE.label","نوع الحقوق"},
		{"eBL.RIGHTS_CODE.label","كود الحقوق"},
		{"eBL.EPISODE_TYPE.label","نوع الحلقة"},
		{"eBL.EFFECTIVE_FROM_TO.label","فعال (من إلى)"},
		{"eBL.ALL.label","الكل"},
		{"eBL.IP.label","IP"},
		{"eBL.OP.label","OP"},
		{"eBL.DC.label","DC"},
		{"eBL.EM.label","EM"},
		{"eBL.EX.label","EX"},
		{"eBL.ADDED_BY.label","أضيفت من قبل"},
		{"eBL.ADDED_DATE.label","تم إضافة التاريخ"},
		{"eBL.MODIFIED_BY.label","تم التعديل بواسطة"},
		{"eBL.MODIFIED_DATE.label","التاريخ عدل"},
		{"eBL.CHUNK_VALUE.label","قيمة القطعة"},
		{"eBL.RECORDS_PER_PAGE.label","تسجيلات لكل صفحة"},
		{"eBL.BankCode.label","رمز بنكي"},
		{"eBL.BankName.label","اسم البنك"},
		{"eBL.BranchName.label","اسم الفرع"},
		{"eBL.UseForDep.label","استخدام للإيداع في البنك"},
		{"eBL.CreditCardProvided.label","بطاقة الائتمان M / c المقدمة"},
		{"eBL.SurchargeOnRefund.label","٪ رسوم إضافية على استرداد"},
		{"eBL.CreditCardTitle.label","آلات بطاقات الائتمان التي يزودها البنك"},
		{"eBL.OperatingFacilityId.label","معرف مرفق التشغيل"},
		{"eBL.CreditCardMachineId.label","معرف آلة بطاقة الائتمان"},
		{"eBL.Status.label","ممكن"},
		{"eBL.CreditCardCompany.label","شركات بطاقات الائتمان"},
		{"eBL.CompanyCode.label","كود الشركة"},
		{"eBL.CompanyName.label","اسم الشركة"},
		{"eBL.CALENDAR_YEAR.label","تقويم سنوي"},
		{"eBL.HOLIDAY_DATE.label","تاريخ العيد"},
		{"eBL.DAY_TYPE.label","نوع اليوم"},
		{"eBL.CREATE_CALENDAR.label","إنشاء التقويم"},
		{"eBL.MAINTAIN_CALENDAR.label","الحفاظ على التقويم"},
		{"eBL.DayTypes.Label","أنواع اليوم"},
		{"eBL.TimeTypes.Label","أنواع الوقت"},
		{"eBL.TimeSlabs.Label","ألواح الوقت"},
		{"eBL.DayType.Label","نوع اليوم"},
		{"eBL.WorkingDay.Label","يوم عمل"},
		{"eBL.LongDesc.Label","وصف طويل"},
		{"eBL.ShortDesc.Label","وصف قصير"},
		{"eBL.FacilityId.label","معرف المنشأة"},
		{"eBL.ServiceInd.label","مؤشر الخدمة"},
		{"eBL.MappingCode.label","رمز التعيين"},
		{"eBL.ShortDesc.label","وصف قصير"},
		{"eBL.LongDesc.label","وصف طويل"},
		{"eBL.LevelAppCov.label","المستوى المطبق للتغطية"},
		{"eBL.PhyDiagAppCov.label","الطبيب و Disgnostics المطبقة للتغطية"},
		{"eBL.ServItemTitle.label","الخدمة / العناصر الخاصة برمز التعيين"},
		{"eBL.ItemCode.label","الشفرة"},
		{"eBL.BillingService.label","خدمة الفواتير"},
		{"eBL.MaterialItem.label","البند المادي"},
		{"eBL.PayerGroupHeading.label","الدافع عن طريق مجموعة الدافع"},
		{"eBL.PayerGroup.label","مجموعة الدافع"},
		{"eBL.PayerCode.label","كود الدافع"},
		{"eBL.PayerName.label","اسم الدافع"},
		{"eBL.PayerPaymentHeading.label","أساس الدفع من قبل الدافع / مستشفى الإحالة"},
		{"eBL.RefHospital.label","مستشفى الإحالة"},
		{"eBL.PatientClass.label","فئة المريض"},
		{"eBL.PaymentBasisInd.label","مؤشر أساس الدفع"},
		{"eBL.AmtRw.label","مبلغ ل rw"},
		{"eBL.LessPaymentPer.label","توقع دفع أقل٪ ج"},
		{"eBL.SpPayerGrpRelm.label","مجموعة دافع محددة Relm"},
		{"eBL.NEW_SERVICE_GROUP_CON.label","يجب 'حفظ' مجموعات الخدمة الجديدة قبل متابعة تصنيفات الخدمة"},
		{"eBL.EnterpriseServiceGroup.Label","مجموعة خدمات المؤسسة"},
		{"eBL.ConsiderIncomeReporting.Label","النظر في تقرير الدخل"},
		{"eBL.PrintLine.Label","خط الطباعة"},
		{"eBL.PrintingPractionerName.Label","بما في ذلك / باستثناء الأساس لطباعة اسم ممارس"},
		{"eBL.DocumentPrintSecquence.Label","تأمين طباعة المستندات"},
		{"eBL.PayServGrpHdrTabTitle.label","رأس مجموعة خدمة الدافع"},
		{"eBL.PayServGrpLineTabTitle.label","خط مجموعة خدمة الدفع"},
		{"eBL.ServicesByPayerTitle.label","الخدمات من خلال مجموعة / خطوط خدمة الدافع"},
		{"eBL.ServiceGroup.label","مجموعة الخدمة"},
		{"eBL.ServiceGroupLine.label","خط مجموعة الخدمة"},
		{"eBL.LongDesc.label","وصف طويل"},
		{"eBL.ShortDesc.label","وصف قصير"},
		{"eBL.PrintSeqNo.label"," رقم طباعة تسلسل "},
		{"eBL.MarkUpDown.label","وضع علامة لأعلى / لأسفل"},
		{"eBL.PaymentBasisInd.label","مؤشر أساس الدفع"},
		{"eBL.HomeMed.label","الأدوية المنزلية"},
		{"eBL.ICUBedCharge.label","وحدة العناية المركزة / شحن السرير"},
		{"eBL.ServiceGrpLine.label","خط مجموعة الخدمة"},
		{"eBL.DocPrintSeq.label","تسلسل طباعة الوثيقة"},
		{"eBL.NonDrgRel.label","غير ذات صلة DRG"},
		{"eBL.BillingServices.label","خدمات الفواتير"},
		{"eBL.BillingClassTitle.label","فئات الفواتير"},
		{"eBL.BillingClass.label","فئة الفواتير"},
		{"eBL.ServiceLevel.label","مستوى الخدمة"},
		{"eBL.ServRulAppInd.label","عامل الوقت المطبق"},
		{"eBL.PackageGroupCode.Label","حزمة رمز المجموعة"},
		{"eBL.INDICATOR.label","مؤشر"},
		{"eBL.ServiceCode.label","رمز الخدمة"},
		{"eBL.ServiceDescription.label","وصف الخدمة"},
		{"eBL.MaintainTimeTabTitle.label","الحفاظ على العوامل المستندة إلى الوقت"},
		{"eBL.CreateTimeTabTitle.label","إنشاء عوامل الوقت"},
		{"eBL.CreateTimeSlabs.label","إنشاء ألواح زمنية"},
		{"eBL.BillingClass.label","فئة الفواتير"},
		{"eBL.DayType.label","نوع اليوم"},
		{"eBL.TimeType.label","نوع الوقت"},
		{"eBL.From.label","من عند"},
		{"eBL.To.label","إلى"},
		{"eBL.Hrs.label","ساعات"},
		{"eBL.BillingService.label","خدمة الفواتير"},
		{"eBL.Description.label","وصف"},
		{"eBL.AddlFactor.label","عامل إضافي"},
		{"eBL.To.label","إلى"},
		{"eBL.Option.label","اختيار"},
		{"eBL.AddlFactor.label","عامل إضافي"},
		{"eBL.TimeSlabs.label","ألواح الوقت"},
		{"eBL.CustGrpTabTitle.label","مجموع نقاط العملاء"},
		{"eBL.CashGrpTabTitle.label","الفواتير النقدية Grp"},
		{"eBL.PolicyCode.label","كود السياسة"},
		{"eBL.AppyForPayers.label","التقدم بطلب للحصول على دافعين آخرين Y / N"},
		{"eBL.CARD_TYPE.label","نوع البطاقة"},
		{"eBL.MEMBER_SHIP_FEES.label","رسوم سفينة الأعضاء"},
		{"eBL.PRIVILIEGE_CARD_MEMBER.label","عضو بطاقة الامتياز"},
		{"eBL.ActiveHealthCard.label","البطاقة الصحية النشطة"},
		{"eBL.BillingGroupCategoryCode.Label","كود مجموعة الفواتير"},
		{"eBL.BillingGroupCategory.Label","فئة مجموعة الفواتير"},
		{"eBL.DetailDescription.label","وصف التفاصيل"},
		{"eBL.BLClinic.label","عيادة"},
		{"eBL.BLVisitType.label","نوع الزيارة"},
		{"eBL.BLNoOfVisit.label","# من الزيارة"},
		{"eBL.BLAvailed.label","نفع"},
		{"eBL.BLOpVisitUtilazationStatus.label","OP زيارة حالة الاستخدام"},
		{"eBL.BLNoOfOPAllotment.label","رقم تخصيص OP"},
		{"eBL.BLTillDateAvailed.label","حتى تاريخ متوفر"},
		{"eBL.BLDetails.label","تفاصيل"},
		{"eBL.CARD_TYPE.label","نوع البطاقة"},
		{"eBL.MEMBER_SHIP_FEES.label","رسوم العضوية"},
		{"eBL.PRIVILIEGE_CARD_MEMBER.label","عضو بطاقة الامتياز"},
		{"eBL.PrimaryPatientID.label","معرف المريض الأساسي"},
		{"eBL.HCMasterValidity.label","صلاحية البطاقة (أيام)"},
		{"eBL.HCMasterApplicability.label","إمكانية تطبيق البطاقة (من إلى)"},
		{"eBL.HCMasterEnabled.label","ممكن"},
		{"eBL.HCMasterAgeGroup.label","الفئة العمرية"},
		{"eBL.HCMasterPriceClass.label","فئة السعر"},
		{"eBL.HCMasterOPAllotment.label","تخصيص OP"},
		{"eBL.HCMasterBGDetails.label","تفاصيل مجموعة الفواتير المطبقة"},
		{"eBL.HCMasterBGCode.label","كود مجموعة الفواتير"},
		{"eBL.HCMasterNoOfPat.label","عدد المرضى المسموح لهم"},
		{"eBL.PolicyApplicability.label","قابلية تطبيق السياسة"},
		{"eBL.DefPolicyStartDate.label","تاريخ بدء النهج الافتراضي"},
		{"eBL.PolicySettlementApplicability.label","قابلية تطبيق تسوية السياسة"},
		{"eBL.PolicyEndDate.label","تاريخ انتهاء الوثيقة"},
		{"eBL.PolicycoverageBasis.label","أساس تغطية السياسة"},
		{"eBL.PolicycoverageRules.label","قواعد تغطية السياسة"},
		{"eBL.CoveragePercent.label","تغطية ٪"},
		{"eBL.PolicyExpDays.label","أيام انتهاء السياسة الافتراضية"},
		{"eBL.PolicyInclExclCoverage.label","تشمل السياسة / باستثناء تفاصيل التغطية"},
		{"eBL.PreApprovalDetails.label","تفاصيل الموافقة المسبقة"},
		{"eBL.PAYER.label","دافع"},
		{"eBL.PolicyInclExclDetails.label","سياسة تضمين / استبعاد التفاصيل"},
		{"eBL.CoverageDetails.label","تفاصيل التغطية"},
		{"eBL.DefaultInclExclCriteria.label","استبعاد / تضمين معايير افتراضيًا"},
		{"eBL.ServiceInclExclCriteria.label","استثناء الخدمة / تضمين المعايير"},
		{"eBL.ServiceCoverageLimit.label","معايير حدود تغطية الخدمة"},
		{"eBL.OverrideInclExcl.label","تجاوز التضمين / الاستبعاد لخدمات غير محددة"},
		{"eBL.CoverageOtherPayer.label","تشمل التغطية دافعين آخرين"},
		{"eBL.LastPayer.label","آخر دافع"},
		{"eBL.OutpatientEmergency.label","العيادات الخارجية / الطوارئ"},
		{"eBL.InpatientDayCare.label","المرضى المنومين / داي كير"},
		{"eBL.CreditAuthReq.label","المصادقة الائتمانية مطلوبة"},
		{"eBL.CreditAuthMand.label","إدخال المصادقة الائتمانية إلزامي"},
		{"eBL.CreditAuthrefNo.label","مرجع مصادقة الائتمان الافتراضي باعتباره رقم السياسة"},
		{"eBL.Covered.label","مغطى"},
		{"eBL.LimitAmt.label","حد القيمة"},
		{"eBL.CoverageType.label","نوع حد التغطية"},
		{"eBL.MandChkBillGen.label","التحقق الإلزامي من انشاء الفاتورة"},
		{"eBL.MandChkInvoiceGen.label","التحقق الإلزامي من الفاتورة Gen"},
		{"eBL.ServicePolicyCoverage.label","تغطية السياسة"},
		{"eBL.MaterialPolicyCoverage.label","تغطية سياسة المواد المادية"},
		{"eBL.DefaultInclExclItem.label","العنصر الافتراضي استبعاد / تضمين المعايير"},
		{"eBL.MaterialInclExclItem.label","استبعاد عنصر مادي / تضمين معايير"},
		{"eBL.MaterialItemLimit.label","معايير حد تغطية المواد المادية"},
		{"eBL.OPCoverageLimit.label","نوع حد تغطية العيادات الخارجية"},
		{"eBL.OPCoverageAmt.label","مبلغ حد تغطية العيادات الخارجية"},
		{"eBL.IPCoverageLimit.label","نوع حد تغطية المرضى الداخليين"},
		{"eBL.IPCoverageAmt.label","مبلغ حد تغطية المرضى الداخليين"},
		{"eBL.EpisodeEncounter.label","حلقة / لقاء"},
		{"eBL.ClinicNu.label","العيادة / وحدة التمريض"},
		{"eBL.ClinicNuDetails.label","تفاصيل العيادة / وحدة التمريض"},
		{"eBL.SpecDetails.label","تفاصيل التخصص"},
		{"eBL.BGServiceDetails.label","تفاصيل خدمات الفواتير"},
		{"eBL.IncExcCriteria.label"," معايير التضمين / الاستبعاد"},
		{"eBL.IncExcInd.label","إدراج/ إستبعاد المؤشر"},
		{"eBL.InclusionBasis.label","أساس الشمول"},
		{"eBL.ServItemQty.label","سيرف / صنف الكمية"},
		{"eBL.AmtVisit.label","حد المبلغ"},
		{"eBL.AmtAdmission.label","المبلغ لكل قبول"},
		{"eBL.AmtIPDay.label","حد المبلغ في اليوم"},
		{"eBL.EffFromDate.label","من تاريخ"},
		{"eBL.EffToDate.label","تاريخ التنفيذ"},
		{"eBL.PreAppAmtCap.label","الموافقة المسبقة على تغطية المبالغ"},
		{"eBL.PreAppQtyCap.label","تغطية كمية الموافقة المسبقة"},
		{"eBL.EffToDate.label","تاريخ التنفيذ"},
		{"eBL.SoleCoverage.label","التغطية الوحيدة من قبل الدافع"},
		{"eBL.SharedCoverage.label","تغطية مشتركة مع دافع آخر"},
		{"eBL.AllIncluded.label","جميع الخدمات مشمولة"},
		{"eBL.AllExcluded.label","جميع الخدمات مستبعدة"},
		{"eBL.ServGrpClass.label","مجموعة الخدمة / التصنيف"},
		{"eBL.EntGrpLine.label","مجموعة المؤسسة / الخط"},
		{"eBL.PayerServiceGrp.label","مجموعة خدمة الدفع"},
		{"eBL.ByEntGrpLine.label","حسب مجموعة / خط خدمة المؤسسة"},
		{"eBL.EntServGrpLine.label","مجموعة / خط خدمة المؤسسة"},
		{"eBL.ByPayerServiceGrp.label","بواسطة مجموعة خدمة Payer"},
		{"eBL.Restricted.label","محدد"},
		{"eBL.UnRestricted.label","غير مقيد"},
		{"eBL.DiagnosisMR.label","التشخيص بواسطة MR"},
		{"eBL.DiagnosisPractioner.label","التشخيص من قبل الممارس"},
		{"eBL.Percentage.label","النسبة المئوية"},
		{"eBL.AllItemsIncluded.label","تم تضمين كافة العناصر"},
		{"eBL.AllItemsExcluded.label","جميع العناصر مستبعدة"},
		{"eBL.PayerMatGroup.label","مجموعة مواد الدفع"},
		{"eBL.EnterpriseMatGroup.label","مجموعة مواد المؤسسة"},
		{"eBL.SaleCategory.label","فئة البيع"},
		{"eBL.servicedtls.label","مستوى الخدمة مطلوب"},
		{"eBL.Episode.label","حلقة"},
		{"eBL.Encounter.label","يواجه .. ينجز"},
		{"eBL.OrthoClinic.label","عيادة اورثو"},
		{"eBL.NuroClinic.label","عيادة نورو"},
		{"eBL.GeneralWard.label","جناح العام"},
		{"eBL.SingleBed.label","سرير مفرد"},
		{"eBL.DoubleBed.label","سرير مزدوج"},
		{"eBL.Rad.label","راد"},
		{"eBL.Cardio.label","القلب"},
		{"eBL.Nuro.label","نورو"},
		{"eBL.Ortho.label","أورثو"},
		{"eBL.PrintGroup.label","مجموعة الطباعة"},
		{"eBL.PrintGroupLine.label","مجموعة / خط الطباعة"},
		{"eBL.Gross.label","إجمالي"},
		{"eBL.Net.label","شبكة"},
		{"eBL.ScreeningPolicy.label","سياسة الفرز"},
		{"eBL.PatCopay.label","Copay المريض"},
		{"eBL.PatAmtLimit.label","بات أمت الحد"},
		{"eBL.RecalculationCharges.label","رسوم إعادة الحساب"},
		{"eBL.SplitReqd.label","سبليت مطلوب"},
		{"eBL.DefGrpIdSameEpisode.label","معرف Grp الافتراضي لنفس الحلقة"},
		{"eBL.TimeLimitDefaultGrp.label","المهلة الزمنية للمجموعة الافتراضية"},
		{"eBL.BillFormatTabHeading.label","تنسيق الفاتورة"},
		{"eBL.FmtDetailsTabHeading.label","تفاصيل التنسيق"},
		{"eBL.CustBgGrpBillFmtTabHeading.label","تنسيق فاتورة العميل / مجموعة الفواتير"},
		{"eBL.SummByBlgServTabHeading.label","ملخص حسب خدمة الفواتير"},
		{"eBL.BillPrintFmtServTabHeading.label","خدمة تنسيق طباعة الفاتورة"},
		{"eBL.BillFmtCustTabHeading.label","تنسيق الفاتورة للعميل"},
		{"eBL.BillFmtBgTabHeading.label","تنسيق الفاتورة لمجموعة الفواتير"},
		{"eBL.StaticInfoTabHeading.label","معلومات ثابتة"},
		{"eBL.BillFormatTabHeading.label","تنسيق الفاتورة"},
		{"eBL.FmtDetailsTabHeading.label","تفاصيل التنسيق"},
		{"eBL.CustBgGrpBillFmtTabHeading.label","تنسيق فاتورة العميل / مجموعة الفواتير"},
		{"eBL.SummByBlgServTabHeading.label","ملخص حسب خدمة الفواتير"},
		{"eBL.BillPrintFmtServTabHeading.label","خدمة تنسيق طباعة الفاتورة"},
		{"eBL.BillFmtCustTabHeading.label","تنسيق الفاتورة للعميل"},
		{"eBL.BillFmtBgTabHeading.label","تنسيق الفاتورة لمجموعة الفواتير"},
		{"eBL.StaticInfoTabHeading.label","معلومات ثابتة"},
		{"eBL.FormatCode.label","كود التنسيق"},
		{"eBL.FormatDesc.label","وصف التنسيق"},
		{"eBL.toolBarFuncName.label","اسم وظيفة شريط الأدوات"},
		{"eBL.LinkingURL.label","ربط URL"},
		{"eBL.ToolBarFormat.label","تنسيق شريط الأدوات"},
		{"eBL.ToolBarAssociation.label","رابطة ToolBar"},
		{"eBL.IconDetail.label","تفاصيل الرمز"},
		{"eBL.FirstTimePrintInd.label","مؤشر طباعة لأول مرة"},
		{"eBL.RePrintInd.label","مؤشر إعادة الطباعة"},
		{"eBL.ApplicableTo.label","تنطبق على"},
		{"eBL.IP.label","المرضي الداخلى"},
		{"eBL.DC.label","DC"},
		{"eBL.OP.label","المرضي الخارجى"},
		{"eBL.EM.label","الطوارئ"},
		{"eBL.EX.label","EX"},
		{"eBL.ALL.label","الكل"},
		{"eBL.SummaryByPrintGroup.label","ملخص بواسطة مجموعة الطباعة"},
		{"eBL.PrintDoctor.label","طبيب الطباعة"},
		{"eBL.PrintDoctorInsteadOfDescription.label","اطبع دكتور بدلا من الوصف"},
		{"eBL.DetailByPrintGroupLine.label","التفاصيل بواسطة خط مجموعة الطباعة"},
		{"eBL.PrintDoctorSpeciality.label","تخصص طبيب الطباعة"},
		{"eBL.PrintServiceDescforItem.label","وصف خدمة الطباعة للعنصر"},
		{"eBL.DetailByService.label","التفاصيل حسب الخدمة"},
		{"eBL.PrintRemarksforMiscServiceinsteadofDescription.label","طباعة ملاحظات لخدمة متنوعة بدلاً من الوصف"},
		{"eBL.SummaryByBillingService.label","ملخص حسب خدمة الفواتير"},
		{"eBL.Subtotal.label","المجموع الفرعي"},
		{"eBL.SupressZeroGross.label","سوبريس صفر الإجمالي"},
		{"eBL.PrintDischargeSepLine.label","Print Disch Med في سطر منفصل"},
		{"eBL.BillTitleHeading.label","عنوان الفاتورة"},
		{"eBL.BillHeaderHeading.label","رأس الفاتورة"},
		{"eBL.ServiceHeading.label","الخدمات"},
		{"eBL.TotalHeading.label","مجموع"},
		{"eBL.EndOfBillHeading.label","اخر الفاتورة"},
		{"eBL.SeqNo.label","رقم التسلسل "},
		{"eBL.Column1.label","العمود 1"},
		{"eBL.Column2.label","العمود 2"},
		{"eBL.Column3.label","العمود 3"},
		{"eBL.Column4.label","العمود 4"},
		{"eBL.Column5.label","العمود 5"},
		{"eBL.Column6.label","العمود 6"},
		{"eBL.StaticValue.label","قيمة ثابتة"},
		{"eBL.StaticLegend.label","أسطورة ثابتة"},
		{"eBL.DetailOnly.label","التفاصيل فقط"},
		{"eBL.DetailRequired.label","التفاصيل مطلوبة"},
		{"eBL.SupressZero.label","سوبريس صفر"},
		{"eBL.Justification.label","التبرير"},
		{"eBL.CustomerHeading.label","الزبون"},
		{"eBL.BillingGroupHeading.label","مجموعة الفواتير النقدية"},
		{"eBL.CustomerGroupCode.label","كود مجموعة العملاء"},
		{"eBL.CustomerCode.label","كود العميل"},
		{"eBL.CustomerName.label","اسم الزبون"},
		{"eBL.BillingGroup.label","مجموعة الفواتير"},
		{"eBL.BillType.label","نوع الفاتورة"},
		{"eBL.PrintReprint.label","طباعة / إعادة طبع"},
		{"eBL.SummHeading.label","ستتم طباعة خدمات الفواتير لمجموعة الطباعة المحددة بإيجاز"},
		{"eBL.PrintGroupHdrCode.label","طباعة رمز مجموعة الرئيسي  "},
		{"eBL.ServiceDescription.label","وصف الخدمة"},
		{"eBL.PrintGrpLineServInd.label","طباعة مجموعة مؤشر خدمة خط "},
		{"eBL.PrintGroupServiceCode.label","طباعة مجموعة كود خدمة "},
		{"eBL.PrintGroupLineCode.label","طباعة مجموعة رمز خط "},
		{"eBL.PrintGroupDescription.label","طباعة وصف المجموعة"},
		{"eBL.ServiceLongDescription.label","وصف طويل للخدمة"},
		{"eBL.CUSTOMER_SPECIFIC.label","خاص بالعميل"},
		{"eBL.CASH_BILNG_GRP_SPECIF.label","مجموعة الفواتير النقدية محددة"},
		{"eBL.CUSTOMER_DETAILS.label","تفاصيل العميل"},
		{"eBL.CUST_SPEC_LONG_DESC.label","مواصفات الزبون تنازلي طويل"},
		{"eBL.CUST_SPEC_SHORT_DESC.label","مواصفات الزبون الوصف المختصر"},
		{"eBL.CUST_SPEC_BLNG_SERV_CODE.label","كود خدمة Blng لمواصفات العميل"},
		{"eBL.BLNG_GRP_ID.label","كود مجموعة الفواتير"},
		{"eBL.BLNG_GRP_SPEC_LONG_DESC.label","مجموعة الفواتير  وصف طويل"},
		{"eBL.BLNG_GRP_SPEC_SHORT_DESC.label","مجموعة الفواتير  وصف مختصر"},
		{"eBL.BLNG_GRP_BLNG_SERV_CODE.label","رمز خدمة الفوترة الخاص بمجموعة الفواتير"},
		{"eBL.AGELIMIT.label","حد السن"},
		{"eBL.AGELIMITFROM.label","الحد العمري (من)"},
		{"eBL.AGELIMITTO.label","الحد العمري (إلى)"},
		{"eBL.INSIMAGEUPLOAD.label","تحميل الصور"},
		{"eBL.INSIMAGEUPLOADDOC.label","وثيقة التأمين المرفوعة"},
		{"eBL.PanelDetails.label","تفاصيل اللوحة"},
		{"eBL.PanelConstituents.label","مكونات اللوحة"},
		{"eBL.PanelCategories.label","فئات اللوحة"},
		{"eBL.InterCompanySetup.label","إعداد InterCompany"},
		{"eBL.QtyModifiable.label","الكمية قابلة للتعديل"},
		{"eBL.FromFacility.label","من منشأة"},
		{"eBL.InterCompanyToFacility.label","InterCompany إلى منشأة"},
		{"eBL.BillingServiceDesc.label","وصف خدمة الفواتير"},
		{"eBL.ApprovalNumber.label","عدد الموافقة"},
		{"eBL.ServiceAmount.label","مبلغ الخدمة"},
		{"eBL.ApprovalRequiredDate.label","تاريخ طلب الموافقة"},
		{"eBL.ApprovalGivenDate.label","تاريخ منح الموافقة"},
		{"eBL.ServiceQuantity.label","سيرف الكمية"},
		{"eBL.APPROVED_QTY.label","الكمية المعتمدة"},
		{"eBL.DrName.label","اسم الدكتور"},
		{"eBL.PercSymbol.label","(٪)"},
		{"eBL.BilledUnBilled.label","مفوتر / غير مفوتر"},
		{"eBL.Billed.label","فاتورة"},
		{"eBL.UnBilled.label","غير مفوتر"},
		{"eBL.Directchgs.label","رسوم مباشرة"},
		{"eBL.Indirectchgs.label","في الرسوم المباشرة"},
		{"eBL.Direct/Indirectchgs.label","رسوم مباشرة / مباشرة"},
		{"eBL.EntGrpCode.label","Ent Grp Code"},
		{"eBL.EntLineCode.label","رمز خط الإدخال"},
		{"eBL.BillingServiceDtls.label","تفاصيل خدمة الفواتير"},
		{"eBL.AdhocDisc.label","خصم Adhoc"},
		{"eBL.FromBillNumber.label","رقم الفاتورة من"},
		{"eBL.BillNumber.label","رقم الفاتوره"},
		{"eBL.ToBillNumber.label","رقم الفاتورة الى"},
		{"eBL.FromBillNo.label","من رقم الفاتورة"},
		{"eBL.ToBillNo.label","إلى رقم الفاتورة"},
		{"eBL.FromPolicy.label","من السياسة"},
		{"eBL.ToPolicy.label","للسياسة"},
		{"eBL.FromPatientID.label","من معرف المريض"},
		{"eBL.PatientID.label","رقم المريض"},
		{"eBL.ToPatientID.label","إلى هوية المريض"},
		{"eBL.FromCustomer.label","من العميل"},
		{"eBL.ToCustomer.label","للعميل"},
		{"eBL.CutOffDate.label","تعدى التاريخ"},
		{"eBL.FromBillDate.label","تاريخ الفاتورة من"},
		{"eBL.ToBillDate.label","تاريخ الفاتورة إلى"},
		{"eBL.DetailedBillPrint.label","طباعة فاتورة مفصلة"},
		{"eBL.QTY.label","الكمية"},
		{"eBL.BL_RATE_CHARGE_TYPE.label","معدل / تهمة"},
		{"eBL.ServiceLocation.label","موقع الخدمة"},
		{"eBL.InterCoEncounters.label","لقاءات InterCo"},
		{"eBL.NRIC.label","NRIC"},
		{"eBL.UnBilledOrExists.label","غير مفوتر موجود"},
		{"eBL.PendCancelVisit.label","فاتورة معلقة للزيارة الملغاة"},
		{"eBL.PendZeroAmt.label","فاتورة معلقة مقابل مبلغ بقيمة صفر"},
		{"eBL.PendPayment.label","في انتظار الدفع"},
		{"eBL.PendVisit.label","فاتورة الزيارة المعلقة"},
		{"eBL.PayerOne.label","الدافع 1"},
		{"eBL.PayerTwo.label","الدافع 2"},
		{"eBL.PayerThree.label","الدافع 3"},
		{"eBL.PayerFour.label","الدافع 4"},
		{"eBL.PayerFive.label","الدافع 5"},
		{"eBL.ServiceDiscount.label","خصم الخدمة"},
		{"eBL.AdminRemarks.label","ملاحظات المسؤول"},
		{"eBL.LessDeposit.label","أقل إيداع"},
		{"eBL.Payment.label","دفع"},
		{"eBL.Card.label","بطاقة"},
		{"eBL.DD.label","DD"},
		{"eBL.ForeignCurrency.label","عملة أجنبية"},
		{"eBL.Debit.label","مدين"},
		{"eBL.IssuingBranch.label","فرع الإصدار"},
		{"eBL.ApprAuthCode.label","الموافقة / كود التفويض"},
		{"eBL.ValidFromMMYY.label","صالح من (MM / YY)"},
		{"eBL.ValidToMMYY.label","صالح حتى (شهر / سنة)"},
		{"eBL.DDNo.label","DD رقم"},
		{"eBL.DDAmount.label","مبلغ DD"},
		{"eBL.DDDate.label","تاريخ DD"},
		{"eBL.ChequeNo.label","رقم الشيك"},
		{"eBL.ChequeAmount.label","تحقق من المبلغ"},
		{"eBL.ChequeDate.label","تحقق من التاريخ"},
		{"eBL.BillGeneration.label","جيل بيل"},
		{"eBL.OutstandAmount.label","كمية رهيبة"},
		{"eBL.SetDefaultValue.label","تعيين القيمة الافتراضية"},
		{"eBL.OutstandingOnly.label","المعلقة فقط"},
		{"eBL.PriceCode.label","كود السعر"},
		{"eBL.PriceDescription.label","وصف السعر"},
		{"eBL.ValidFrom.label","صالح من تاريخ"},
		{"eBL.ValidTo.label","صالحة ل"},
		{"eBL.ChargeType.label","نوع التهمة"},
		{"eBL.DiscExists.label","القرص موجود"},
		{"eBL.PriceDetails.label","تفاصيل السعر"},
		{"eBL.ChkCostAvl.label","تحقق من التكلفة Avl"},
		{"eBL.CostIndicator.label","مؤشر التكلفة"},
		{"eBL.CostAmt.label","مبلغ التكلفة"},
		{"eBL.Applicability.label","القابلية للتطبيق"},
		{"eBL.ApplyDiscount.label","تطبيق الخصم"},
		{"eBL.EffectiveFromTo.label","فعال (من إلى)"},
		{"eBL.DiscountDetails.label","تفاصيل الخصم"},
		{"eBL.DiscountPercentage.label","نسبة الخصم"},
		{"eBL.ApplyDiscount.label","تطبيق الخصم"},
		{"eBL.DiscountIndicator.label","مؤشر الخصم"},
		{"eBL.DiscFromTo.label","صلاحية القرص (من إلى)"},
		{"eBL.BillingGroup.label","مجموعة الفواتير"},
		{"eBL.BillingServiceGroup.label","مجموعة خدمات الفواتير"},
		{"eBL.ServiceIndDesc.label","وصف الخدمة Ind-Desc"},
		{"eBL.PriceInd.label","مؤشر السعر"},
		{"eBL.PriceIndCode.label","رمز Ind السعر"},
		{"eBL.PriceIndDescription.label","وصف Ind Price"},
		{"eBL.ValidFrom.label","صالح من تاريخ"},
		{"eBL.ValidTo.label","صالحة ل"},
		{"eBL.ChargeType.label","نوع التهمة"},
		{"eBL.DiscExists.label","القرص موجود"},
		{"eBL.DiscApplicability.label","قابلية تطبيق القرص"},
		{"eBL.PolicyDesc.label","وصف السياسة"},
		{"eBL.CustGroupCode.label","كود مجموعة العميل"},
		{"eBL.CustGroupDesc.label","مجموعة الزبون Desc"},
		{"eBL.IP_RATE.label","معدل IP"},
		{"eBL.OP_RATE.label","معدل OP"},
		{"eBL.EMG_RATE.label","معدل Emg"},
		{"eBL.EXT_RATE.label","معدل التحويلة"},
		{"eBL.DC_RATE.label","معدل DC"},
		{"eBL.MIN_CHARGE.label","دقيقة تهمة"},
		{"eBL.MAX_CHARGE.label","ماكس المسؤول"},
		{"eBL.DISC_APPLICABILITY.label","القابلية للتطبيق"},
		{"eBL.DISC_APPLY.label","تطبيق القرص"},
		{"eBL.GenerateBill.label","توليد بيل"},
		{"eBL.SettleBill.label","تسوية بيل"},
		{"eBL.PrintOption.label","خيار الطباعة"},
		{"eBL.GenerateZeroBill.label","إنشاء فاتورة صفرية"},
		{"eBL.PrintZeroBill.label","طباعة فاتورة صفرية"},
		{"eBL.USER_TYPE.label","نوع المستخدم"},
		{"eBL.USER_CODE.label","الرقم السري للمستخدم"},
		{"eBL.PRIVILEGE.label","بريفليج"},
		{"eBL.DEFLT_PRIVILEGE.label","افتراضي بريديليج"},
		{"eBL.ALLOWED_YN.label","مسموح نعم / لا"},
		{"eBL.SETTLEMENT_WISE_DISC.label","خصم التسوية"},
		{"eBL.PRIORITY_SEQUENCE.label","تسلسل الأولوية"},
		{"eBL.DISC_APPLICABILITY.label","قابلية تطبيق الخصم"},
		{"eBL.DISCOUNT_AMT/%.label","مبلغ الخصم /٪"},
		{"eBL.AeCheckoutReceiptPrint.label","خيار طباعة إيصال الدفع A / E"},
		{"eBL.AeCheckoutPrintZeroBill.label","طباعة فاتورة صفرية لسداد A / E"},
		{"eBL.eBL.ALLOWED_YN","مسموح نعم / لا"},
		{"eBL.EncounterSequenceNo.label"," رقم تسلسل المواجهة "},
		{"eBL.PartialDepositType.label","نوع الإيداع الجزئي"},
		{"eBL.PartialDeposit.label","الإيداع الجزئي"},
		{"eBL.PartialDepositMandatory.label","الإيداع الجزئي إلزامي"},
		{"eBL.ReportTitle.label","عنوان التقرير"},
		{"eBL.ReportHeader.label","رأس التقرير"},
		{"eBL.AllUser.label","جميع المستخدمين"},
		{"eBL.UserGroup.label","مجموعة المستخدمين"},
		{"eBL.Information.label","معلومات"},
		{"eBL.Alignment.label","انتقام"},
		{"eBL.StaticLegend.label","أسطورة ثابتة"},
		{"eBL.Middle.label","الأوسط"},
		{"eBL.Left.label","اليسار"},
		{"eBL.Right.label","حق"},
		{"eBL.ReportHeader.label","رأس التقرير"},
		{"eBL.ReportDetails.label","تفاصيل التقرير"},
		{"eBL.DataGroup.label","مجموعة البيانات"},
		{"eBL.ReportPreview.label","معاينة التقرير"},
		{"eBL.DataGroupInformation.label","معلومات مجموعة البيانات"},
		{"eBL.TotalRequired.label","الإجمالي المطلوب"},
		{"eBL.ReportCriteria.label","معايير التقرير"},
		{"eBL.SeqNo.label","تسلسل رقم"},
		{"eBL.CriteriaSeqNo.label","معايير تسلسل رقم"},
		{"eBL.OrderBy.label","ترتيب حسب"},
		{"eBL.Type.label","نوع"},
		{"eBL.DefaultValue.label","القيمة الافتراضية"},
		{"eBL.Mandatory.label","إلزامي"},
		{"eBL.DropDown.label","اسقاط"},
		{"eBL.Selection.label","اختيار"},
		{"eBL.CalendarSelection.label","اختيار التقويم"},
		{"eBL.ViewReportCriteria.label","عرض معايير التقرير"},
		{"eBL.SelectCriteria.label","حدد المعايير"},
		{"eBL.ProvideAccessRights.label","توفير حقوق الوصول"},
		{"eBL.UserAccessRights.label","حقوق وصول المستخدم"},
		{"eBL.ExistingUsersList.label","قائمة المستخدمين الحاليين"},
		{"eBL.ReportData.label","بيانات التقرير"},
		{"eBL.ViewDownloadFile.label","انقر لعرض / تنزيل الملف"},
		{"eBL.ClaimCode.label","كود المطالبة"},
		{"eBL.CreditAuthorisationBy.label","تفويض الائتمان بواسطة"},
		{"eBL.TimeLimitGrpOP.label","مجموعة افتراضية محددة الوقت "},
		{"eBL.TimeLimitGrpIP.label","مجموعة افتراضية محددة الوقت - مريض داخلي"},
		{"eBL.CurrentPrice.label","السعر الحالي"},
		{"eBL.RevisedPrice.label","السعر المنقح"},
		{"eBL.StdCustPrice.label","الاساسى / سعر العميل"},
		{"eBL.CustomerPrice.label","سعر العميل"},
		{"eBL.StandardPrice.label","سعر قياسي"},
		{"eBL.BulkUpdPkgPrice.label","التحديث المجمع / الحزمة الفردية"},
		{"eBL.BulkUpdate.label","تحديث بالجملة"},
		{"eBL.PkgPriceType.label","نوع سعر الباقة"},
		{"eBL.PercentageOrAmt.label","النسبة المئوية / الكمية"},
		{"eBL.MarkUpOrDown.label","وضع علامة لأعلى / لأسفل"},
		{"eBL.RoundOff.label","نهاية الجولة"},
		{"eBL.RoundUpOrDown.label","تقريب لأعلى / لأسفل"},
		{"eBL.PackageRate.label","سعر الحزمة"},
		{"eBL.IndPkg.label","حزمة فردية"},
		{"eBL.JobId.label","معرف الوظيفة"},
		{"eBL.ProcessDate.label","تاريخ العملية"},
		{"eBL.JobStatus.label","حالة الوظيفة"},
		{"eBL.JobList.label","قائمة الوظائف"},
		{"eBL.BulkPkgPrice.label","سعر السائبة / الباكدج"},
		{"eBL.PackagePriceType.label","نوع سعر الباقة"},
		{"eBL.ErrorDesc.label","وصف الخطأ"},
		{"eBL.RevisedDiscountValue.label","قيمة الخصم المنقحة"},
		{"eBL.RevisedDiscountType.label","نوع الخصم المنقح"},
		{"eBL.CurrentPriceFactor.label","السعر الحالي / العامل"},
		{"eBL.ScreeningServiceApplicable.label","تنطبق خدمة الفرز"},
		{"eBL.ScreeningServiceApplicabilityStatus.label","حالة تطبيق خدمة الفحص"},
		{"eBL.ApplicableQuantity.label","الكمية المطبقة"},
		{"eBL.ApplicableAmount.label","المبلغ المطبق"},
		{"eBL.BillPaidAmt.label","قيمة فاتورة مدفوعة "},
		{"eBL.BillOutStdAmt.label","بيل أوت Std. أمت"},
		{"eBL.InterimBill.label","مشروع قانون مؤقت"},
		{"eBL.DischargeBill.label","فاتورة التفريغ"},
		{"eBL.UnderchargeAdvice.label","نصيحة الشحن"},
		{"eBL.ExternalBill.label","فاتورة خارجية"},
		{"eBL.VisitBill.label","قم بزيارة الفاتورة"},
		{"eBL.CosmeticRuleHeader.label","قانون الضرائب القاعدة"},
		{"eBL.RuleCode.label","قانون القاعدة"},
		{"eBL.CriteriaForTax.label","معايير الضرائب"},
		{"eBL.InclusionExclusion.label","التضمين / الاستبعاد"},
		{"eBL.AllPatClass.label","كل فئة المريض"},
		{"eBL.BillApprovedInv.label","الفاتورة المعتمدة / الفاتورة"},
		{"eBL.IDENTIFY_TYPE.label","نوع المعرف"},
		{"eBL.NID.label","NID"},
		{"eBL.CANCELREASON.label","سبب الإلغاء"},
		{"eBL.Service.label","خدمات"},
		{"eBL.Print.label","طباعة"},
		{"eBL.Cancel.label","إلغاء"},
		{"eBL.consolidatedBillSettlement.label","تسوية الفاتورة الموحدة"},
		{"eBL.Fromreceiptnumber.label","من نوع / رقم المستند"},
		{"eBL.downtimereceiptno.label","مستند التوقف"},
		{"eBL.documentnumber.label","رقم المستند"},
		{"eBL.FromreceiptDate.label","من التاريخ"},
		{"eBL.ToreceiptNumber.label","إلى نوع المستند / الرقم"},
		{"eBL.ToreceiptDate.label","ان يذهب في موعد"},
		{"eBL.Receipt_Detail.label","تفاصيل التسوية"},
		{"eBL.Slash.label","/"},
		{"eBL.HealthcareApplnnumber.label","Hcare Appln رقم"},
		{"eBL.Options.label","خيارات الطباعة"},
		{"eBL.RECEIPT.label","إيصال"},
		{"eBL.ACKNOWLEDGEMENT.label","خطاب  تأكيد"},
		{"eBL.BOTH.label","كلاهما"},
		{"eBL.VOIDNUMBER.label","رقم شاغر"},
		{"eBL.REASONFORCANCEL.label","سبب الإلغاء"},
		{"eBL.CURRENT_DAYCARE.label","الرعاية النهارية الحالية"},
		{"eBL.episodeid.label","كود الزياة"},
		{"eBL.episodeId.label","كود الزياة"},
		{"eBL.doc_srno.label","تسلسل المستند"},
		{"eBL.doc_amt.label","مبلغ المستند"},
		{"eBL.slmt_type_code.label","رمز نوع التسوية"},
		{"eBL.cash_amt_given.label","المبلغ النقدي المقدم"},
		{"eBL.cash_amt_returned.label","تم إرجاع المبلغ النقدي"},
		{"eBL.slmt_doc_ref_desc.label"," وصف مرجع مستند التسوية "},
		{"eBL.bank_code.label","رمز بنكي"},
		{"eBL.slmt_doc_remarks.label","ملاحظات وثيقة التسوية"},
		{"eBL.bank_branch.label","فرع بنك"},
		{"eBL.cc_batch_no.label","رقم نسخة الدفعة"},
		{"eBL.approval_ref_no.label","رقم المرجع الموافقة"},
		{"eBL.cc_swapped_yn.label","Cc مبادلة Y / N"},
		{"eBL.cc_sale_draft_no.label","مشروع بيع نسخة رقم"},
		{"eBL.payer_name.label","اسم الدافع"},
		{"eBL.nominee_name.label","اسم المرشح"},
		{"eBL.post_month.label","بعد شهر"},
		{"eBL.post_year.label","سنة ما بعد"},
		{"eBL.consolidated_receipt_yn.label","إيصال موحد Y / N"},
		{"eBL.DocAmt.label","مبلغ المستند"},
		{"eBL.Removeall.label","حذف الكل"},
		{"eBL.ReceiptNatureCode.label","طبيعة الايصال"},
		{"eBL.ReceiptTypeCode.label","نوع الإيصال"},
		{"eBL.receiptno.label","رقم الوثيقة"},
		{"eBL.PAT_DEP_PKG.label","إيداع المريض مقابل الحزمة"},
		{"eBL.DEP_SRGY.label","الإيداع مقابل الجراحة"},
		{"eBL.IRBSelect.label","اختيار"},
		{"eBL.IRBDocumentType.label","نوع الوثيقة"},
		{"eBL.IRBDocumentNumber.label","رقم المستند"},
		{"eBL.IRBDocumentSrNo.label","رقم الوثيقة "},
		{"eBL.IRBSettlementType.label","نوع التسوية"},
		{"eBL.IRBAmount.label","قيمة"},
		{"eBL.IRBAdjustedAmount.label","المبلغ المعدل"},
		{"eBL.IRBAmountPayable.label","المبلغ المستحق"},
		{"eBL.IRBBillNo.label"," رقم القاتورة "},
		{"eBL.IRBServiceDate.label","تاريخ الخدمة"},
		{"eBL.IRBDocRef.label","مرجع الوثيقة"},
		{"eBL.IRBDocLineNo.label","خط الوثيقة"},
		{"eBL.IRBDocSeqNo.label","رقم تسلسل الوثيقة"},
		{"eBL.IRBBlngServiceCode.label","رمز خدمة الفواتير"},
		{"eBL.IRBApplicableAmount.label","المبلغ المطبق"},
		{"eBL.IRBAdjAmt.label"," القيمة المعدلة"},
		{"eBL.IRBServiceAmt.label","قيمة الخدمة"},
		{"eBL.IRBIncludeExclude.label","وتشمل استبعاد"},
		{"eBL.IRBDelete.label","حذف"},
		{"eBL.Document_Number.label","رقم المستند"},
		{"eBL.DepositReason.label","السبب"},
		{"eBL.DepositDate.label","تاريخ"},
		{"eBL.DownTimeEntry.label","دخول وقت التوقف"},
		{"eBL.DocNoslash.label","/"},
		{"eBL.EpisodeNo.label","رقم الحلقة"},
		{"eBL.OriginalDocNo.label","رقم المستند الأصلي"},
		{"eBL.BookingReference.label","مرجع الحجز"},
		{"eBL.EstimateForDeposit.label","تقدير للإيداع"},
		{"eBL.PostMthYr.label","بعد شهر / سنة"},
		{"eBL.EnterServiceItem.label","أدخل عنصر الخدمة"},
		{"eBL.ServiceIndicator.label","مؤشر الخدمة"},
		{"eBL.ServiceDate/Time.label","تاريخ / وقت الخدمة"},
		{"eBL.TotalBillAmount.label","إجمالي مبلغ الفاتورة"},
		{"eBL.BillPaidAmount.label","مبلغ الفاتورة المدفوعة"},
		{"eBL.Emergency.label","حالة طوارئ"},
		{"eBL.External.label","خارجي"},
		{"eBL.Depositdetails.label","تفاصيل الإيداع"},
		{"eBL.Utilizedamount.label","المبلغ المستخدم"},
		{"eBL.Depositamount.label","قيمة الايداع"},
		{"eBL.requestid.label","طلب معرف"},
		{"eBL.serviceCode.label","كود الخدمة"},
		{"eBL.EnterBillingServiceDetails.label","أدخل تفاصيل خدمة الفواتير"},
		{"eBL.DepositAgainstSurgery.label","الإيداع مقابل الجراحة"},
		{"eBL.DepositReceipt.label","إيصال / استرداد الإيداع"},
		{"eBL.Alternative id.label","نوع الكود البديل"},
		{"eBL.Id.label","كود"},
		{"eBL.Patient Name.label","اسم المريض"},
		{"eBL.records.label","السجلات"},
		{"eBL.modules.label","الوحدات"},
		{"eBL.prmodule.label","وحدة رئيسية"},
		{"eBL.prkeymain.label","مفتاح رئيسي"},
		{"eBL.patientno.label","رقم المريض"},
		{"eBL.servicelocation.label","موقع الخدمة"},
		{"eBL.chargedate.label","تاريخ الحساب"},
		{"eBL.PhysicianId.label","كود الطبيب"},
		{"eBL.PrimaryKey.label","المفتاح الأساسي"},
		{"eBL.SecondaryKey.label","المفتاح الثانوي"},
		{"eBL.ServiceItemcode.label","كود صنف الخدمة"},
		{"eBL.InterfacedDate.label","تاريخ الواجهة"},
		{"eBL.Charged.label","محاسب"},
		{"eBL.ChargingState.label","حالة الحساب"},
		{"eBL.notCharged.label","غير محاسب"},
		{"eBL.FutureOrder.label","اوامر مستقبلية"},
		{"eBL.Excluded.label","مستبعد"},
		{"eBL.DepositAmount.label","قيمة الايداع"},
		{"eBL.UtilizedAmount.label","المبلغ المستخدم"},
		{"eBL.DepositDetails.label","تفاصيل الإيداع"},
		{"eBL.POLICY_NAME.label","اسم السياسة"},
		{"eBL.BILL_DOC_NUMBER.label","رقم الفاتورة / كود"},
		{"eBL.SelectBillingService.label","اختيار خدمة الفاتورة"},
		{"eBL.BASE_PRICE.label","السعر الأساسي"},
		{"eBL.PRINT_GROUP.label","طباعة المجموعة"},
		{"eBL.PRINT_LINE.label","طباعة الخط"},
		{"eBL.DIR_ENTRY.label","دخول "},
		{"eBL.DR_FEE.label","اتعاب الطبيب"},
		{"eBL.MISC_SERV.label","خدمات متفرقة"},
		{"eBL.MINIMUM_AMOUNT.label","الحد الأدنى للمبلغ"},
		{"eBL.NET_CHARGE.label","صافي القيمة"},
		{"eBL.voidNumber.label","رقم شاغر"},
		{"eBL.DocNum.label","رقم المستند"},
		{"eBL.SRNO.label","رقم التسلسل"},
		{"eBL.RN.label","RN"},
		{"eBL.SE.label","SE"},
		{"eBL.docamt.label","قيمة المستند"},
		{"eBL.oustamt.label","المبلغ المستحق"},
		{"eBL.chargedate.label","من تاريخ الخدمة"},
		{"eBL.tochargedate.label","لتاريخ الخدمة"},
		{"eBL.Exempt Type.label","نوع الإعفاء"},
		{"eBL.Assign To.label","يسند إلى"},
		{"eBL.PKG_SUBS_MSG.label","حزمة اللقاءات المتعددة التي تم الاشتراك بها للمريض الفعال"},
		{"eBL.ApprovalStatus.label","حالة القبول"},
		{"eBL.PatientWise.label","عن طريق المريض"},
		{"eBL.PayerWise.label","عن طريق الدافع"},
		{"eBL.VisitAdmissionDate.label","تسجيل الوصول / وقت الدخول"},
		{"eBL.CheckOutDischargeDate.label","تاريخ ووقت تسجيل المغادرة / الخروج"},
		{"eBL.MembershipNo.label","رقم العضوية"},
		{"eBL.DependantNo.label","رقم المعال"},
		{"eBL.DependantRelatiosnhip.label","علاقة المعالين"},
		{"eBL.WCANo.label","رقم WCA"},
		{"eBL.ResponseCode.label","رمز الاستجابة"},
		{"eBL.ValidityPeriod.label","فترة الصلاحية"},
		{"eBL.EligibilityCode.label","قانون الأهلية"},
		{"eBL.StatusDescription.label","وصف الحالة"},
		{"eBL.PAYTM_USER_CODE.label","رمز مستخدم PayTM"},
		{"eBL.PAYTM_PROMO_CODE.label","كود ترويجي"},
		{"eBL.PAYTM_PAY.label","PayTM"},
		{"eBL.PAYTM_CHECK_STATUS.label","تحقق من حالة"},
		{"eBL.PAYTM_TXN_NO.label","رقم المعاملة"},
		{"eBL.ADDL_CHARGE.label","رسوم اضافية"},
		{"eBL.VAT_APPLICABLE.label","تطبق ضريبة القيمة المضافة"},
		{"eBL.VAT_PERCENTAGE.label","قاعدة ضريبة القيمة المضافة"},
		{"eBL.RULE_COVERAGE.label","تغطية القاعدة"},
		{"eBL.AS_PER_POLICY.label","حسب السياسة"},
		{"eBL.PAYER_COVERAGE.label","تغطية الدافع"},
		{"eBL.PATIENT_COVERAGE.label","تغطية المريض"},
		{"eBL.PAYTM_ORDER_NO.label","كود طلب التاجر"},
		{"eBL.Patient_Id_From.label","كود المريض (من)"},
		{"eBL.Patient_Id_To.label","كود المريض (إلى)"},
		{"eBL.PAYTM_PAYBY_OPTION.label","الدفع عن طريق الخيار"},
		{"eBL.PAYTM_PAYBY_BARCODE.label","الباركود"},
		{"eBL.PAYTM_PAYBY_TOTP.label","الهاتف + OTP"},
		{"eBL.PAYTM_PHONE_NO.label","رقم الهاتف"},
		{"eBL.PAYTM_OTP.label","OTP"},
		{"eBL.UNBILLED_NEW.label","غير مفوتر"},
		{"eBL.CHQ_CARD_BANK_NO_OTH.label","شيك / بطاقة / بنك A / ج / أخرى رقم."},
		{"eBL.Public.label","عامة"},
		{"eBL.AVERAGE_COST.label","متوسط ​​السعر"},
		{"eBL.COMPUTED_VALUE.label","القيمة المحسوبة"},
		{"eBL.Basis.label","أساس"},
		{"eBL.billfromdate.label","فاتورة من تاريخ"},
		{"eBL.billtodate.label","فاتورة الى تاريخه"},
		{"eBL.ClaimedAmount.label","المبلغ المطالب به"},
		{"eBL.SchemeAuthNumber.label","رقم ترخيص البرنامج"},
		{"eBL.Membersuname.label","عضوية اللقب"},
		{"eBL.MemberInitial.label","أول العضوية"},
		{"eBL.PreAppDurCap.label","تحديد مدة الموافقة المسبقة"},
		{"eBL.ReprintDateFrom.label","إعادة الطباعة من تاريخ"},
		{"eBL.ReprintDateTo.label","إعادة الطباعة الى التاريخ "},
		{"eBL.DocTypeFrom.label","نوع المستند / رقم من"},
		{"eBL.DocTypeTo.label","نوع المستند / رقم الى"},
		{"eBL.CoverReferencePrice.label","مرجع السعر المغطى"},
		{"eBL.CoverRefPrice.label","مرجع السعر المغطى"},
		{"eBL.InclLabRadiologyStatus.label","تشمل حالة المختبر / الأشعة في"},
		{"eBL.Resulted.label","نتيجة"},
		{"eBL.JobSubmittedUser.label","المستخدم المقدم لوظيفة"},
		{"eBL.JobSubmittedDate.label","تاريخ تقديم الوظيفة"},
		{"eBL.JobSubmittedDateTime.label","تاريخ / وقت تقديم الوظيفة"},
		{"eBL.EMPLOYER.label","اسم صاحب العمل"},
		{"eBL.CHRG_DUR_REW.label","يتم تحميله عند التجديد"},
		{"eBL.UHID_RENEW_CHARGE_DTLS.label","تفاصيل رسوم خدمة تجديد UHID"},
		{"eBL.PractoRcptDateFrom.label","تاريخ الاستلام العملي من"},
		{"eBL.PractoRcptDateTo.label","تاريخ الاستلام العملي إلى"},
		{"eBL.ReceiptsStatus.label","حالة الإيصالات"},
		{"eBL.Generated.label","انشأت"},
		{"eBL.InError.label","في خطأ"},
		{"eBL.VendorType.label","نوع المورد"},
		{"eBL.PRACTO.label","Practo"},
		{"eBL.MASPACK.label","الحزمة الرئيسية"},
		{"eBL.Preacrossenc.label","عبر لقاءات"},
		{"eBL.DailyLimit.label","الحد اليومي"},
		{"eBL.DailyLimitPerDay.label","الحد اليومي في اليوم"},
		{"eBL.RenewalDescription.label","وصف تجديد الخدمة"},
		{"eBL.REN_SERV_PANEL_CODE.label","تجديد الخدمة / رمز المجموعة"},
		{"eBL.REN_SERV_PANEL_DESC.label","خدمة التجديد / وصف المجموعة"},
		{"eBL.CREDIT_PATIENT.label","مريض الائتمان"},
		{"eBL.SPONSORED_PATIENT.label","مريض مكفول"},
		{"eBL.MULTIPKGDISC.label","خصم الباقات المتعددة"},
		{"eBL.ALLOW.label","السماح"},
		{"eBL.PKGORCUSTDISC.label","حزمة / خصم العملاء"},
		{"eBL.PKGADHOCDISC.label","حزمة الخصم المخصص"},
		{"eBL.HIGHCOSTPKG.label","حزمة التكلفة العالية فقط"},
		{"eBL.LOWCOSTPKG.label","حزمة منخفضة التكلفة فقط"},
		{"eBL.ALLEXCHIGHCOST.label","جميع الحزم باستثناء التكلفة العالية"},
		{"eBL.UNAPPROVED.label","غير موافق عليه"},
		{"eBL.PkgServiceLimitBy.label","خدمة الحزمة محدودة بـ"},
		{"eBL.DailyPkgLimit.label","حد الحزمة اليومية"},
		{"eBL.PIPDLimit.label","حد PIPD (لكل عنصر في اليوم)"},
		{"eBL.PkgServicesDailyLmt.label","الحد اليومي لخدمات الحزمة"},
		{"eBL.PIPD.label","PIPD"},
		{"eBL.ClaimsAgrmtExts.label","اتفاقية المطالبات موجودة"},
		{"eBL.PATIENT_BED_CATEGORY.label","فئة سرير المريض"},
		{"eBL.Vat_Charges.label","رسوم ضريبة القيمة المضافة"},
		{"eBL.VIEW_VAT_CHARGE_DTL.label","عرض تفاصيل رسوم ضريبة القيمة المضافة"},
		{"eBL.VAT_SERV_CHAGE_DTLS.label","تفاصيل رسوم خدمة ضريبة القيمة المضافة"},
		{"eBL.GET_CC_STATUS.label","احصل على حالة الدفع"},
		{"eBL.UploadDocuments.label","تحميل المستندات"},
		{"eBL.AuthorizationLetter.label","خطاب تفويض"},
		{"eBL.PanCard.label","بطاقة الطعام"},
		{"eBL.Passport.label","جواز سفر"},
		{"eBL.CreditAuthNoDate.label","رقم المصادقة الائتمانية / التاريخ"},
		{"eBL.CreditAuthNo.label","رقم مصادقة الائتمان"},
		{"eBL.ViewDocument.label","عرض المستند"},
		{"eBL.ErrorDecs.label","حدد نوع المستند"},
		{"eBL.UploadImages.label","تحميل الصور"},
		{"eBL.ViewDocuments.label","عرض المستندات"},
		{"eBL.Show_Image.label","إظهار الصورة"},
		{"eBL.View_Image.label","عرض الصورة"},
		{"eBL.Show_Documents.label","إظهار المستندات"},
		{"eBL.docTypeManditory.label","نوع الوثيقة إلزامي"},
		{"eBL.imageOrPdf.label","الصورة / pdf إلزامي"},
		{"eBL.ModifiedDateRange.label","النطاق الزمني المعدل"},
		{"eBL.BillingGroupBasePrice.label","السعر الأساسي لمجموعة الفواتير"},
		{"eBL.BillingGroupRateBasedServices.label","الخدمات القائمة على سعر مجموعة الفواتير"},
		{"eBL.BillingGroupChargeBasedServices.label","الخدمات القائمة على الرسوم لمجموعة الفواتير"},
		{"eBL.ApplyCustPkgDiscNew.label","تطبيق خصم حزمة العملاء - باقات جديدة"},
		{"eBL.ApplyCustDistPolicy.label","تطبيق خصم العملاء حسب السياسة"},
		{"eBL.Query_Criteria.label","معايير الاستعلام"},
		{"eBL.ActivePackDiscount.label","خصم الحزمة النشط"},
		{"eBL.grouppolicy.label","سياسة مشتري المجموعة"},
		{"eBL.PkgLmtInd.label","مؤشر حدود الحزمة"},
		{"eBL.GroupService.label","المجموعة / الخدمة"},
		{"eBL.PkgLmtIndLevel.label","مستوى المجموعة / الخدمة"},
		{"eBL.Record_Approval.label","الموافقة على السجل"},
		{"eBL.Request_Status.label","حالة الطلب"},
		{"eBL.Time_Limit.label","المهلة الزمنية"},
		{"eBL.Color_Indicaotr.label","مؤشر اللون"},
		{"eBL.HH_MM.label","HH: MM"},
		{"eBL.DISC_PERC.label","خصم٪ العمر"},
		{"eBL.GosiPolicy.label","سياسة Gosi"},
		{"eBL.Facility.label","منشأة"}, //V210226
		{"eBL.Invoices_month_yr.label","الفواتير شهر / سنة"},
		{"eBL.frmbilldate.label","من تاريخ الفاتورة"},
		{"eBL.tobilldate.label","إلى تاريخ الفاتورة"},
		{"eBL.user.label","المستخدم"},
		{"eBL.OperaterID.label","كود التشغيل"},
		{"eBL.UserIds.label","اكواد المستخدم"},
		{"eBL.CASH_COUNTER_LOGIN_DATE_TIME.label","التاريخ والوقت لدخول مستخدم الخزينة "},
		{"eBL.BillingType.label","نوع الفاتورة"},
		{"eBL.PostedBillsOnly.label","ترحيل فواتير فقط"},
		{"eBL.DAYCARE.label","رعاية نهارية"},
		{"eBL.PharmacyMedical.label","صيدلية / مواد طبية"},
		{"eBL.AutoDistPkgVarServOP.label","توزيع تلقائى لحزمة خدمات المرضى الخارجى"},
		{"eBL.AutoDistPkgVarServIP.label","توزيع تلقائى لحزمة خدمات المرضى الداخلى"},
		{"eBL.FrmBillingGrp.label","من مجموعة الفواتير"},
		{"eBL.ToBillingGrp.label","إلى مجموعة الفواتير"},
		{"eBL.FrmPatno.label","من رقم المريض"},
		{"eBL.ToPatno.label","الى رقم المريض"},
		{"eBL.FrmCustCode.label","من كود العميل"},
		{"eBL.ToCustCode.label","إلى كود العميل"},
		{"eBL.inc_cur_IP/DC_Pat.label","تضمين المرضى المنومين / مرضى الرعاية النهارية الحاليين"},
		{"eBL.Inc_Zero_Rcrds.label","السجلات تشمل الصفر"},
		{"eBL.CancelledDocsOnly.label","المستندات الملغاة فقط"},
		{"eBL.ReceiptsRefundsBoth.label","الإيصالات / المبالغ المعادة / كلاهما"},
		{"eBL.frmReportdate.label","من تاريخ التقارير"},
		{"eBL.toReportdate.label","الى تاريخ  التقارير"},
		{"eBL.Zero_bill_Also.label"," أيضا الفاتورة صفر"},
		{"eBL.frmBillingClass.label","من فئة الفواتير"},
		{"eBL.toBillingClass.label","إلى فئة الفواتير"},
		{"eBL.frmBillingServ.label","من خدمة الفواتير"},
		{"eBL.toBillingServ.label","لخدمة الفواتير"},
		{"eBL.frmEffDate.label","من تاريخ السريان"},
		{"eBL.toEffDate.label","حتى تاريخ السريان"},
		{"eBL.frmCreateAmendBy.label","من إنشاء / عدل بواسطة"},
		{"eBL.toCreateAmendBy.label","تم إنشاؤه / تعديله بواسطة"},
		{"eBL.frmCreateAmendDate.label","من تاريخ الإنشاء / المعدل"},
		{"eBL.toCreateAmendDate.label","إلى تاريخ الإنشاء / المعدل"},
		{"eBL.ItemType.label","نوع الصنف"},
		{"eBL.Drugs.label","الادوية"},
		{"eBL.Consumables.label","مستهلكات"},
		{"eBL.Status.label","الحالة"},
		{"eBL.TradeNameorBatch.label","حسب الاسم التجارى / الدفعة"},
		{"eBL.FromItemCode.label","من كود الصنف"},
		{"eBL.ToItemCode.label","الى كود الصنف"},
		{"eBL.ItemName.label","اسم الصنف"},
		{"eBL.ItemCodeTitle.label","كود الصنف"},
		{"eBL.CreatedAmendedName.label","اسم"},
		{"eBL.CreatedAmendedCode.label","الكود"},
		{"eBL.Users.label","المستخدمون"},
		{"eBL.report_list.label","قائمة التقارير"},
		{"eBL.posted.label","تم الترحيل"},
		{"eBL.unposted.label","غير مرحل"},
		{"eBL.posted_mth/Yr_frm.label","تاريخ النشر شهر / سنة من"},
		{"eBL.posted_mth/Yr_To.label","أرسلت شهر / سنة إلى"},
		{"eBL.stat_date_frm.label","تاريخ كشف الحساب من"},
		{"eBL.stat_date_To.label","تاريخ البيان إلى"},
		{"eBL.Visit_period_frm.label","فترة الزيارة من"},
		{"eBL.Visit_period_To.label","فترة الزيارة إلى"},
		{"eBL.disc_period_frm.label","فترة الخروج من"},
		{"eBL.disc_period_To.label","فترة الخروج إلى"},
		{"eBL.BilledDate.label","تاريخ الفاتورة"},
		{"eBL.PreviousInterimBillDocNo.label","مشروع قانون مؤقت سابق رقم"},
		{"eBL.UnBilledAmount.Label","مبلغ غير مفوتر"},
		{"eBL.SelectAll.Label","اختر الكل"},
		{"eBL.Reason.Label","السبب"},
		{"eBL.ReasonCode.Label","الكود"},
		{"eBL.MembershipID.Label","كود العضوية"},
		{"eBL.CouponCode.Label","كود الكوبون"},
		{"eBL.CouponCodes.Label","كود القسيمة"},
		{"eBL.Find.Label","تجد"},
		{"eBL.long_name.label","اسم العميل الطويل"},
		{"eBL.long_desc.label","الاسم الطويل لمجموعة العملاء"},
		{"eBL.description.label","الاسم المختصر لمجموعة العملاء"},
		{"eBL.IncludeHomeMedication.label","تشمل الأدوية المنزلية"},
		{"eBL.includeHomeMedication.label","تشمل الأدوية المنزلية"},
		{"eBL.InclHomeMedication.label","تشمل الأدوية المنزلية"},
		{"eBL.cust_group_long_name.label","وصف طويل"},
		{"eBL.CUSTOMER_PAYABLE_AMT.label","مبلغ العميل المستحق"},
		{"eBL.FrombillNumber.label","نوع / رقم مستند الفاتورة"},
		{"eBL.From_doc_type_code.label","من كود نوع المستند"},
		{"eBL.To_doc_type_code.label","لتوثيق نوع الكود"},
		{"eBL.SetDefaultValue.label","تعيين القيمة الافتراضية"},
		{"eBL.PATIENT_FIN_DTLS.label","البيانات المالية للمريض"},
		{"eBL.ENCOUNTER_FIN_DTLS.label","التفاصيل المالية"},
		{"eBL.AMOUNT_REND.label","مبلغ المناقصة"},
		{"eBL.USE_DEFAULT_REASON.label","استخدم السبب الافتراضي"},
		{"eBL.Special_Clinic.label","عيادة خاصة"}, 
		{"eBL.Exempted_Amount.label","Exempted Amount"}, 
		{"eBL.RePrint_Bill.label","Reprint Bill"},
		{"eBL.Reprint_Bill_Item_Wise.label","Reprint Bill-Item Wise"}, 
		{"eBL.Reprint_Bill_Date_Wise.label","Reprint Bill-Date Wise"}, 
		{"eBL.Include_Zero_Bill.label","Include Zero Bill"},
		{"eBL.Arabic.Label","Arabic"} ,	//Added against V210517
		{"eBL.modify.label"," تعديل"}, //V210727
		{"eBL.copypolicy.label","سياسة النسخ"}, //V210727
		{"eBL.Gross/Net.label","الإجمالي / الصافي "}, //V210727
		{"eBL.DeleteRecord.label","حذف سجل"} ,//V210727
		{"eBL.PrimRecNo.label","رقم السكن الأساسي"},//V210727
		{"eBL.NRIC.label","الرقم القومي"},//V210727
		{"eBL.UnderChargePatient.label","مريض قيد التحميل"},
		{"eBL.UnderChargeOnly.label","قيد التحميل فقط"},
		{"eBL.FilterBy.label","تصنيف بواسطة"},
		{"eBL.Processed.label","تمت معالجتها"},
		{"eBL.Availablepatdeposit.label","الإيداعات المتاحة للمريض"},
		{"eBL.Availablepatprepay.label","الدفعات المقدمة المتاحة للمريض"},
		{"eBL.InpatientBillType.label","الدفعات المقدمة المتاحة للمريض"},
		{"eBL.Availablepatprepay.label","الدفعات المقدمة المتاحة للمريض"},
		{"eBL.PendingInterimBill.label","فاتورة مؤقتة معلقة"},
		{"eBL.PendingDischargeBill.label","فاتورة خروج معلقة"},
		{"eBL.PendingUnderchargeBill.label","فاتورة قيد التحميل"},
		{"eBL.Adjust.label","اضبط"},
		{"eBL.BillGenOption.label","اختيار إنشاء فاتورة"},
		{"eBL.PrepayAmount.label","مبلغ الدفع المسبق"},
		{"eBL.ExpectedDischargeDate.label","تاريخ الخروج المتوقع"},
		{"eBL.Draft.label","مسودة"},
		{"eBL.Service/Package.label","الخدمة/ مجموعة الخدمات"},
		{"eBL.GenerateBillCumReceipt.label","إنشاء إيصال استلام الفاتورة"},
		{"eBL.OtherUnbilledOutstanding.label","المعلقة الأخرى غير المسددة"},
		{"eBL.UnConfirmedServices.label","الخدمات غير المؤكدة"},
		{"eBL.EncounterBillingDetails.label","تفاصيل الزيارة حسابيا"},
		{"eBL.checkOut.label"," تاريخ/ وقت الدفع "},
		{"eBL.Visit.label","تاريخ/ وقت يزور"},
		{"eBL.Discharge.label","وقت إبراء الذمة"},
		{"eBL.Admission.label","تاريخ/ وقت الدخول"}
	};
}
