
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eCP.EvaluateCarePlan.EvaluateCarePlanManager
package eCP.EvaluateCarePlan;

/**
 * Local interface for EvaluateCarePlan
 */
public interface EvaluateCarePlanLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap AddModify(java.util.Properties properties, java.util.HashMap hashmap);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
