
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteHomeInterfacePlugin from eCP.EvaluateCarePlan.EvaluateCarePlanManager
package eCP.EvaluateCarePlan;

/**
 * Home interface for EvaluateCarePlan
 */
public interface EvaluateCarePlanHome
extends javax.ejb.EJBHome {
    public static final String COMP_NAME = "java:comp/env/ejb/EvaluateCarePlanRemote";
    public static final String JNDI_NAME = "EvaluateCarePlanRemote";

    eCP.EvaluateCarePlan.EvaluateCarePlanRemote create() throws javax.ejb.CreateException, java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
