
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eCP.EvaluateCarePlanMarkError.EvaluateCarePlanMarkErrorManager
package eCP.EvaluateCarePlanMarkError;

/**
 * Local interface for EvaluateCarePlanMarkError
 */
public interface EvaluateCarePlanMarkErrorLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap AddModify(java.util.Properties properties, java.util.HashMap hashmap);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
