/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eFM.FMIssueFiles.FMIssueFilesManager
package eFM.FMIssueFiles;

/**
 * Local interface for FMIssueFiles
 */
public interface FMIssueFilesLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap createIssueFiles(java.util.Properties p, java.util.HashMap htIssueFiles, webbeans.eFM.FMFilesIssueCart FMIssueFilesBean, java.util.ArrayList newArrayListTransMode, java.util.ArrayList newArrayListCarried, java.util.ArrayList newArrayListRetDate, java.util.ArrayList newArrayListreturndatehidden, java.util.ArrayList newArrayListreturncriteria, java.util.ArrayList newArrayListdischargedatetime); 
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
