
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eIP.IPCancelTransferPatientIn.IPCancelTransferPatientInManager
package eIP.IPCancelTransferPatientIn;

/**
 * Local interface for IPCancelTransferPatientIn
 */
public interface IPCancelTransferPatientInLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap insertCancelTransferPatientIn(java.util.Properties p, java.util.HashMap hashData);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
