/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eAM.resources;

import java.util.*;

public class  Labels  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
			{"eAM.AccountingDepartmentCostCenter.label","Accounting Department / Cost Center"},
			{"eAM.AcctDeptforRoom.label","Acct Dept for Room"},
			{"eAM.AddModifyRange.label","Add/Modify Range"},
			{"eAM.AdminFacilityID.label","Admin Facility ID"},
			{"eAM.AdmitPatientwithBed.label","Admit Patient with Bed"},
			{"eAM.AllowChangingNursingUnitinAssignBed.label","Allow Changing Nursing Unit in Assign Bed"},
			{"eAM.AllowDirectordersfor.label","Allow Direct orders for"},
			{"eAM.AllowForcedinAppointment.label","Allow Forced-in Appointment"},
			{"eAM.AllowGlobalBooking.label","Allow Global Booking"},
			{"eAM.AnatomicalSiteCode.label","Anatomical Site Code"},
			{"eAM.Ancillary.label","Ancillary"},
			{"eAM.AncillaryMedicalService.label","Ancillary Medical Service"},
			{"eAM.APCNo.label","APC No."},
			{"eAM.ApplicableCategoriesAll.label","Applicable  Categories   All"},
			{"eAM.ApplicableForInpatients.label","Applicable For Inpatients"},
			{"eAM.ApplicableForOutpatients.label","Applicable For Outpatients"},
			{"eAM.ApplicableForOutpatientsInpatients.label","Applicable For Outpatients/Inpatients"},
			{"eAM.ApplicablePeriodFrom.label","Applicable Period From"},
			{"eAM.ApplicabletoISS.label","Applicable to ISS"},
			{"eAM.ApplUserID.label","Appl User ID"},
			{"eAM.AppointmentScheduling.label","Appointment Scheduling"},
			{"eAM.ArrivalCode.label","Arrival Code"},
			{"eAM.AssignUnassigned.label","Assign Unassigned"},
			{"eAM.AssignUnassignedPatient.label","Assign Unassigned Patient"},
			{"eAM.AssociatedEnterpriseFacilityforReferral.label","Associated Enterprise Facility for Referral"},
			{"eAM.AssociatedPanelElements.label","Associated Panel Elements"},
			{"eAM.AssociateScore.label","Associate Score"},
			{"eAM.AvailableClasses.label","Available Classes"},
			{"eAM.AvailableEquipment.label","Available Equipment"},
			{"eAM.BackdatedAdmission.label","Backdated Admission"},
			{"eAM.BatteryID.label","Battery ID"},
			{"eAM.BedClasschange.label","Bed Class change"},
			{"eAM.BedMaintenance.label","Bed Maintenance"},
			{"eAM.BlockSchedule.label","Block Schedule"},
			{"eAM.BookAppointmentwithoutPatientID.label","Book Appointment without Patient ID"},
			{"eAM.BuildinginFacility.label","Building in Facility"},
			{"eAM.ByLocationType.label","By Location Type"},
			{"eAM.ByPerson.label","By Person"},
			{"eAM.CancelTransferOut.label","Cancel Transfer Out"},
			{"eAM.CancelVisit.label","Cancel Visit"},
			{"eAM.CareLocationCode.label","Care Location Code"},
			{"eAM.CareLocationType.label","Care Location Type"},
			{"eAM.ChartSection.label","Chart Section"},
			{"eAM.CheckInCheckOutLodger.label","Check In/Check Out Lodger"},
			{"eAM.CheckoutPatient.label","Check out Patient"},
			{"eAM.ClickonanyotherColumnnumbertoreposition.label","Click on any other Column number to reposition"},
			{"eAM.Closest.label","Closest"},
			{"eAM.ComplaintCode.label","Complaint Code"},
			{"eAM.ConditionalCode.label","Conditional Code"},
			{"eAM.ConfirmonCreatebooking.label","Confirm on Create booking"},
			{"eAM.ConfirmRequest.label","Confirm Request"},
			{"eAM.ContactPersonDetails.label","Contact Person Details"},
			{"eAM.ContactReasonCode.label","Contact Reason Code"},
			{"eAM.CriticalCare.label","Critical Care"},
			{"eAM.CurrentlySelectedComponentismarkforrepositioning.label","Currently Selected Component is mark for repositioning."},
			{"eAM.CurrentTime.label","Current Time"},
			{"eAM.Dec.label","Dec"},
			{"eAM.DeceasedIndicator.label","Deceased Indicator"},
			{"eAM.DefineGrid.label","Define Grid"},
			{"eAM.DefineMatrix.label","Define Matrix"},
			{"eAM.Definition.label","Definition"},
			{"eAM.DemoCall.label","Demo Call"},
			{"eAM.Dischargechecklist.label","Discharge checklist"},
			{"eAM.Discrete.label","Discrete"},
			{"eAM.DiscreteID.label","Discrete ID"},
			{"eAM.DiscretePanel.label","Discrete Panel"},
			{"eAM.DocumentTypeDetails.label","Document Type Details"},
			{"eAM.DonorPrefixforidentifyingSource.label","Donor Prefix for identifying Source"},
			{"eAM.ElectroCardiogram.label","Electro Cardiogram"},
			{"eAM.ElectroEncephelogram.label","Electro Encephelogram"},
			{"eAM.EmployerStatus.label","Employer Status"},
			{"eAM.EncounterNumberingControl.label","Encounter Numbering Control"},
			{"eAM.EquipmentOtherResource.label","Equipment   Other Resource"},
			{"eAM.EquipmentOtherResourceTypes.label","Equipment   Other Resource Types"},
			{"eAM.EquivalentUnitofMeasure.label","Equivalent Unit of Measure"},
			{"eAM.EscortType.label","Escort Type"},
			{"eAM.EveryFrequencyType.label","Every Frequency Type"},
			{"eAM.ExamProcedureUnit.label","Exam / Procedure Unit"},
			{"eAM.ExistingRange.label","Existing Range"},
			{"eAM.ExternalPractitionerforReferralSource.label","External Practitioner for Referral Source"},
			{"eAM.ExternalReferral.label","External Referral"},
			{"eAM.ExternalReferralSource.label","External /  Referral Source"},
			{"eAM.FacilityforAcctDept.label","Facility for Acct Dept"},
			{"eAM.FileRelated.label","File Related"},
			{"eAM.FloorDescription.label","Floor Description"},
			{"eAM.FloorinFacility.label","Floor in Facility"},
			{"eAM.FollowupofReferral.label","Follow up of Referral"},
			{"eAM.formatBlock.label","Format Block"},
			{"eAM.ForText.label","For Text"},
			{"eAM.FreeDocumentation.label","Free Documentation"},
			{"eAM.FreeText.label","Free Text"},
			{"eAM.FreeTextTemplate.label","Free Text Template"},
			{"eAM.FrequencySchedule.label","Frequency Schedule"},
			{"eAM.FromHealthCareSettingType.label","From HealthCare Setting Type"},
			{"eAM.FromHlthcare.label","From Healthcare"},
			{"eAM.FromHours.label","From Hours"},
			{"eAM.FromMins.label","From Mins"},
			{"eAM.GovernmentEmployees.label","Government Employees"},
			{"eAM.HD.label","HD"},
			{"eAM.HealthCareSettingTypeRestrictions.label","HealthCare Setting Type Restrictions"},
			{"eAM.HistoryTypeDirectRecording.label","History Type(Direct Recording)"},
			{"eAM.Hour.label","Hour"},
			{"eAM.InfusionPump.label","Infusion Pump"},
			{"eAM.InLocalLanguage.label","In Local Language"},
			{"eAM.InpatientManagement.label","Inpatient Management"},
			{"eAM.InpatientReferral.label","Inpatient Referral"},
			{"eAM.InstructionID.label","Instruction ID"},
			{"eAM.IntensiveCare.label","Intensive Care"},
			{"eAM.Interval.label","Interval"},
			{"eAM.IntervalDura.label","Interval Duration"},
			{"eAM.IntervalDuraType.label","Interval Duration Type"},
			{"eAM.IntervalFrequencyValue.label","Interval Frequency Value"},
			{"eAM.IPReferral.label","IP Referral"},
			{"eAM.IVPump.label","IV Pump"},
			{"eAM.LiftBlockonSchedule.label","Lift Block on Schedule"},
			{"eAM.LinkStandardValue.label","Link Standard Value"},
			{"eAM.LocationforOperatorStation.label","Location for Operator Station"},
			{"eAM.ManufacturerStatus.label","Manufacturer Status"},
			{"eAM.MaximumAge.label","Maximum Age"},
			{"eAM.MeasureID.label","Measure ID"},
			{"eAM.MinValue.label","Min Value"},
			{"eAM.MnemonicforShiftID.label","Mnemonic for Shift ID"},
			{"eAM.MnemonicKey.label","Mnemonic Key"},
			{"eAM.MotorVehicleAccidentFund.label","Motor Vehicle Accident Fund"},
			{"eAM.NationalIDNo.label","National ID No"},
			{"eAM.NextNumber.label","Next Number"},
			{"eAM.NextReferralNumber.label","Next Referral Number"},
			{"eAM.NoofBeds.label","No of Beds"},
			{"eAM.NoofRanges.label","No of Ranges"},
			{"eAM.NotesTemplate.label","Notes Template"},
			{"eAM.NumericDetails.label","Numeric Details"},
			{"eAM.NumericMapDigits.label","Numeric Map Digits"},
			{"eAM.NumericValue.label","Numeric Value"},
			{"eAM.NWD.label","NWD"},
			{"eAM.OnCall.label","On Call"},
			{"eAM.OneTime.label","One - Time"},
			{"eAM.OperationTheatreAll.label","Operation Theatre (All)"},
			{"eAM.OperationTheatrespec.label","Operation Theatre (Spec)  "},
			{"eAM.OperatorStationDescription.label","Operator Station Description"},
			{"eAM.OperatorStationID.label","Operator Station ID"},
			{"eAM.OperatorStationRestriction.label","Operator Station Restriction"},
			{"eAM.OperatorStationType.label","Operator Station Type"},
			{"eAM.OPReferral.label","OP Referral"},
			{"eAM.OtherStaffForFacility.label","Other Staff For Facility"},
			{"eAM.OtherStaffID.label","Other Staff ID"},
			{"eAM.OutpatientManagement.label","Outpatient Management"},
			{"eAM.OutpatientReferral.label","Outpatient Referral"},
			{"eAM.OverbookAppointment.label","Overbook Appointment"},
			{"eAM.OverrideAllocationRuleforBookAppointment.label","Override Allocation Rule for Book Appointment"},
			{"eAM.OverrideAllocationRuleforTransferAppointment.label","Override Allocation Rule for Transfer Appointment"},
			{"eAM.Oxygen.label","Oxygen"},
			{"eAM.Pager.label","Pager"},
			{"eAM.PatientCarePanel.label","Patient Care Panel"},
			{"eAM.PatientClassDesc.label","Patient Class Desc"},
			{"eAM.PatientMovementTracking.label","Patient Movement Tracking"},
			{"eAM.PatientPrefixforidentifyingSource.label","Patient Prefix for identifying Source"},
			{"eAM.PatientRelated.label","Patient Related"},
			{"eAM.PatientTypeClass.label","Patient Type Class"},
			{"eAM.PersonName.label","Person Name"},
			{"eAM.PractitionerforFacility.label","Practitioner for Facility"},
			{"eAM.PractitionerforTeam.label","Practitioner for Team"},
			{"eAM.PractitionrerName.label","Practitionrer Name"},
			{"eAM.Precision.label","Precision"},
			{"eAM.PrefMode.label","Pref Mode"},
			{"eAM.PrivacyLevel.label","Privacy Level"},
			{"eAM.Productive.label","Productive"},
			{"eAM.ProfessionalQualification.label","Professional Qualification"},
			{"eAM.ProgramID.label","Program ID"},
			{"eAM.ProgramName.label","Program Name"},
			{"eAM.ProgramType.label","Program Type"},
			{"eAM.QuarterHour.label","Quarter Hour"},
			{"eAM.RangeID.label","Range ID"},
			{"eAM.Ranges.label","Ranges"},
			{"eAM.RangeType.label","Range Type"},
			{"eAM.ReasonforDepart.label","Reason for Depart"},
			{"eAM.ReasonforRecall.label","Reason for Recall"},
			{"eAM.RecordAmendLeave.label","Record/Amend Leave"},
			{"eAM.RecordingChart.label","Recording Chart"},
			{"eAM.RecordingVital.label","Recording Vital"},
			{"eAM.ReferenceRanges.label","Reference Ranges"},
			{"eAM.ReferenceRangesNumericDetails.label","Reference Ranges - Numeric Details"},
			{"eAM.ReferralIDNumbering.label","Referral ID Numbering"},
			{"eAM.ReferralManagement.label","Referral Management"},
			{"eAM.RegisterNewbornforIP.label","Register Newborn for IP"},
			{"eAM.RegisterPatientFromAdmitPatient.label","Register Patient From Admit Patient"},
			{"eAM.RegisterPatientfromRegisterVisit.label","Register Patient from Register Visit"},
			{"eAM.RegisterReferral.label","Register Referral"},
			{"eAM.RegisterWalkIn.label","Register Walk-In"},
			{"eAM.ReimbursementType.label","Reimbursement Type"},
			{"eAM.RejectionofReferral.label","Rejection of Referral"},
			{"eAM.ReleaseBedBay.label","Release Bed/Bay"},
			{"eAM.RepeatFrequencyType.label","Repeat Frequency Type"},
			{"eAM.RepeatFrequencyValue.label","Repeat Frequency Value"},
			{"eAM.RepeatsPer.label","Repeat(s) Per "},
			{"eAM.RepFacility.label","Rep Facility"},
			{"eAM.RepFacilityID.label","Rep Facility ID"},
			{"eAM.ReportFacility.label","Report Facility"},
			{"eAM.ReserveBedBay.label","Reserve Bed/Bay"},
			{"eAM.ResidentStay.label","Resident Stay"},
			{"eAM.ResourceDescription.label","Resource  Description"},
			{"eAM.ResourceNarration.label","Resource Narration"},
			{"eAM.ResourceTypecode.label","Resource Type code"},
			{"eAM.ResourceTypeDescription.label","Resource Type Description"},
			{"eAM.ResultTemplateID.label","Result Template ID"},
			{"eAM.RoundTo.label","Round To"},
			{"eAM.Scheduled.label","Scheduled"},
			{"eAM.Seconds.label","Seconds"},
			{"eAM.SectioninFacility.label","Section in Facility"},
			{"eAM.SelectedClasses.label","Selected Classes"},
			{"eAM.SeriesforDonorNumbering.label","Series for Donor Numbering"},
			{"eAM.SeriesforExtPatNumbering.label","Series for Ext Pat Numbering"},
			{"eAM.ServiceinFacility.label","Service in Facility"},
			{"eAM.SetgCode.label","Setting Code"},
			{"eAM.ShiftforLocationType.label","Shift for Location Type"},
			{"eAM.ShiftforPosition.label","Shift for Position"},
			{"eAM.ShiftID.label","Shift ID"},
			{"eAM.ShiftMnemonic.label","Shift Mnemonic"},
			{"eAM.ShiftTimings.label","Shift Timings"},
			{"eAM.ShowFacilities.label","Show Facilities"},
			{"eAM.SpecialtyforCatalog.label","Speciality for Catalog"},
			{"eAM.SpecialtyforExternalReferralSource.label","Specialty for External Referral Source"},
			{"eAM.SpecimenRelated.label","Specimen Related"},
			{"eAM.StandardComp.label","Standard Comp"},
			{"eAM.StandardValueRef.label","Standard Value Ref"},
			{"eAM.StandardValueReference.label","Standard Value Reference"},
			{"eAM.StartTimeAssignment.label","Start Time Assignment"},
			{"eAM.StatID.label","Stat ID"},
			{"eAM.StatisticsGroupDetail.label","Statistics Group Detail"},
			{"eAM.StatisticsGroupforProgram.label","Statistics Group for Program"},
			{"eAM.StatisticsGroupID.label","Statistics Group ID"},
			{"eAM.StudyLocation.label","Study Location"},
			{"eAM.SubServiceCode.label","Sub Service Code"},
			{"eAM.SubServiceinFacility.label","Sub-Service in Facility"},
			{"eAM.Suction.label","Suction"},
			{"eAM.SwapBed.label","Swap Bed"},
			{"eAM.Team.label","Team"},
			{"eAM.TelephoneNumber.label","Telephone Number"},
			{"eAM.Temporary.label","Temporary"},
			{"eAM.TestObservID.label","Test Observe ID"},
			{"eAM.TimeRoundedto.label","Time-Rounded to"},
			{"eAM.TissueCollection.label","Tissue Collection"},
			{"eAM.ToHealthCareSettingType.label","To HealthCare Setting Type"},
			{"eAM.ToHlthcare.label","To Healthcare"},
			{"eAM.ToHours.label","To Hours"},
			{"eAM.ToMins.label","To Mins"},
			{"eAM.TransferIn.label","Transfer In"},
			{"eAM.UsablebyRadiationImplantPatients.label","Usable by Radiation Implant Patients"},
			{"eAM.UseasExternalReferralDestinationat.label","Use as External / Referral Destination at"},
			{"eAM.UseasExternalReferralSourceat.label","Use as External / Referral Source at"},
			{"eAM.UseasExternalReferralSourcefordirectordering.label","Use as External / Referral Source for direct ordering"},
			{"eAM.UseasExternalReferralSourceforTissueCollection.label","Use as External / Referral Source for Tissue Collection"},
			{"eAM.UseasReferralDestinationat.label","Use as Referral Destination at"},
			{"eAM.UseasReferralSourceat.label","Use as Referral Source at"},
			{"eAM.UseatDischarge.label","Use at Discharge"},
			{"eAM.UseatVisitConclusion.label","Use at Visit Conclusion"},
			{"eAM.UseforMaternalDeath.label","Use for Maternal Death"},
			{"eAM.UserforOperatorStation.label","User for Operator Station"},
			{"eAM.Ventilator.label","Ventilator"},
			{"eAM.VisitAnalysisCode.label","Visit Analysis Code"},
			{"eAM.VisitConclusion.label","Visit Conclusion"},
			{"eAM.VisitingSpecialist.label","Visiting Specialist"},
			{"eAM.VistingSpecialist.label","Visting Specialist"},
			{"eAM.WD.label","WD"},
			{"eAM.WebSite.label","Web-Site"},
			{"eAM.WorkmenCompensationFund.label","Workmen's Compensation Fund"},
			{"eAM.WorkStationNo.label","Work Station No"},
			{"eAM.10thminute.label","10th minute"},
			{"eAM.5thminute.label","5th minute"},
			{"eAM.Hourly.label","Hourly"},
			{"eAM.NumberofBedsAllowed.label", "Number of Beds Allowed"},
			{"eAM.AddNewPanelElement.label","Add New Panel Element"},
			{"eAM.ModifyExisitingPanelElement.label","Modify Exisiting Panel Element"},
			{"eAM.Unscheduled.label","Unscheduled"},
			{"eAM.SpecialtyForModule.label","Speciality For Module"}	,
			{"eAM.SpecialityModule.Label","Speciality Module"},	
			{"eAM.AssociatedSpecialities.Label","Associate Speciality"},
			{"eAM.SequenceNumber.label","Sequence Number"},
			{"eAM.ChangeAdmDtls.label","Change Admission Details"},
			{"eAM.RowColumnHeader.label","Row / Column Header"},
			{"eAM.InstructionDescript.label","Instruction Description"},
			{"eAM.PatInstructions.label","Patient Instructions"},
			{"eAM.Repeat.label","Repeat"},
			{"eAM.DiscreteTypeIndicator.label","Discrete Type Indicator"},		
			{"eAM.EveryFrequencyValue.label","Every Frequency Value"},	
			{"eAM.EveryIntervalValue.label","Every Interval Value"},	
			{"eAM.EveryIntervalType.label","Every Interval Type"},
			{"eAM.LateDischarge.label","Late Discharge"},
			{"eAM.Multispeciality.label","Multi Speciality"},
			{"eAM.AbscondedIndicator.label","Absconded Indicator"}, //Added by Sangeetha on 5-Jan-17 for ML-MMOH-CRF-0630
            {"eAM.CancelTransferIn.label","Cancel Transfer In"}, //Added by Mano on 29-Mar-17
            {"eAM.Transfer.label","Transfer"},		//Added by Mano on 29-Mar-17	 
			{"eAM.TfrPatientOut.label","IP Transfer Patient Out"}, //Added by Thamizh selvi on 4th May 2017 for ML-MMOH-CRF-0617
			//Added by Sangeetha on 3rd Jul 2017 for ML-MMOH-CRF-0345.2
			{"eAM.Cycle.label","Cycle"},
			{"eAM.MaxCycle.label","Max No of Cycle"},
			{"eAM.ApplicableForMedicalReport.label","Applicable for Medical Report"}, // added by mujafafr ML-MMOH-CRF-0716
			{"eAM.CallNotAroundIndicator.label","Call Not Around Indicator"},  //added by Mano aganist ML-MMOH-CRF-0783
			{"eAM.MMCNO.label","MMC No"},
			{"eAM.EnableCDRIcon.label","Enable CDR Icon"},  //Added by Dharma
			{"eAM.FacilityAccess.label","With All Facility Access"}, //Added by Suji Keerthi for MOHE-CRF-0021
			{"eAM.WithRepFacility.label","With Reporting Facility"}, //Added by Suji Keerthi for MOHE-CRF-0021
			{"eAM.Supervisor.label","Supervisor"}, //Added by Dharma on 19th Aug 2020 against AAKH-CRF-0122.4
			{"eAM.ExternalAppl.label","External Appointment"}, //Added by Ashwini on 11-Aug-2021 for ML-BRU-CRF-0628.1
			//Below Added by Suji Keerthi for NMC-JD-CRF-0130
			{"eAM.RefPriorityCode.label","Referral Priority Code"}, 
			{"eAM.EmployeeServiceNumber.label","Employee Service Number"},  // Added by lakshmanan For MO-CRF-20183.2 US001
			{"eAM.MasterPatientIndex.label","Master Patient Index"}, // Added by lakshmanan for ML-MMOH-CRF-1955
			{"eAM.ReasontoMarkMLC.label","Reason to Mark MLC"}, // Added by lakshmanan for ML-MMOH-CRF-1955
			{"eAM.ReasontoMarkNonMLC.label","Reason to Mark Non-MLC"},  // Added by lakshmanan for ML-MMOH-CRF-1955
			{"eAM.RefPriorityDesc.label","Referral Priority Description"},
			{"eAM.ReasonForBiometricRejection.label","Reason for Biometric Rejection"}, //<!--Added by Himanshu Saxena on 30-Jun-2023 for AAKH-CRF-0175-->
			{"eAM.NoteTemplateCharAllowed.label", "Note Template Characters Allowed"} //Added by Gunasekar for ML-MMOH-CRF-0579
			
};
}
