/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eDR.resources;

import java.util.*;

public class  Labels_ar  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
{"eDR.AbortProcess.label","إحباط العملية"},
{"eDR.AdministerSearchProcess.label","إدارة عملية البحث"},
{"eDR.AuditData.label","بيانات التدقيق"},
{"eDR.ByEncounter.label","من خلال اللقاء"},
{"eDR.ByRegistrationDate.label","حسب تاريخ التسجيل"},
{"eDR.CloseProcess.label","إغلاق العملية"},
{"eDR.CriteriaforCurrentSearch.label","معايير البحث الحالي"},
{"eDR.CriteriaforSuggestedMainPatient.label","معايير المريض الأساسي المقترح"},
{"eDR.Dateandtime.label","التاريخ والوقت"},
{"eDR.DateofMerge.label","تاريخ الدمج"},
{"eDR.DateofUnMerge.label","تاريخ إلغاء الدمج"},
{"eDR.DefaultCriteria.label","المعايير الافتراضية"},
{"eDR.DefaultSearchCriteria.label","معايير البحث الافتراضية"},
{"eDR.DemographicData.label","البيانات الديموغرافية"},
{"eDR.DoNotConsider.label","لا تنظر"},
{"eDR.DRParameter.label","معلمة DR"},
{"eDR.Duplicate.label","مكرر"},
{"eDR.DuplicateGroups.label","مجموعات مكررة"},
{"eDR.DuplicateDetails.label","تفاصيل مكررة"},
{"eDR.DuplicateSearchCriteria.label","معايير البحث المكررة"},
{"eDR.ExcludedPossibleDuplicates.label","استبعاد التكرارات المحتملة"},
{"eDR.ExcludePossibleDuplicates.label","استبعاد التكرارات المحتملة"},
{"eDR.ExecutionEndDate.label","تاريخ انتهاء التنفيذ"},
{"eDR.ExecutionStartDate.label","تاريخ بدء التنفيذ"},
{"eDR.ExistingSeriesDetails.label","تفاصيل السلسلة الموجودة"},
{"eDR.FileLocation.label","مكان الملف"},
{"eDR.ForMergeProcess.label","لعملية الدمج"},
{"eDR.ForUnmergeProcess.label","لعملية عدم الدمج"},
{"eDR.IdentifyMainDuplicatePatients.label","تحديد المرضى الرئيسيين المكررة"},
{"eDR.IdentifyMainDuplicates.label","تحديد التكرارات الرئيسية"},
{"eDR.IDNo.label","رقم بطاقة الهوية"},
{"eDR.IDSeries.label","سلسلة المعرف"},
{"eDR.IDSeriesDetails.label","تفاصيل سلسلة المعرف"},
{"eDR.IDType.label","نوع الهوية"},
{"eDR.LastDuplicateCheckDate.label","تاريخ آخر تحقق مكرر"},
{"eDR.MainPatientID.label","معرف المريض الرئيسي"},
{"eDR.ManuallyEnteredDuplicates.label","التكرارات التي تم إدخالها يدويًا"},
{"eDR.Merge.label","دمج"},
{"eDR.MergedBy.label","تم دمجها بواسطة"},
{"eDR.MergedDate.label","تاريخ الدمج"},
{"eDR.MergedGroups.label","المجموعات المدمجة"},
{"eDR.MergePatientEndTime.label","دمج وقت انتهاء المريض"},
{"eDR.MergePatientOnlyDuring.label","دمج المريض فقط أثناء"},
{"eDR.MergePatientStartTime.label","دمج وقت بدء المريض"},
{"eDR.MergeProcessDetails.label","تفاصيل عملية الدمج"},
{"eDR.MultipleMRN.label","متعددة MRN's"},
{"eDR.NameinLocalLanguage.label","الاسم باللغة المحلية"},
{"eDR.NextExecutionDate.label","تاريخ التنفيذ القادم"},
{"eDR.NonDuplicates.label","غير مكرر"},
{"eDR.NotMergedGroups.label","المجموعات غير المدمجة"},
{"eDR.OfficeFax.label","فاكس المكتب"},
{"eDR.OfficeTel.label","هاتف المكتب"},
{"eDR.OrderByforCycle.label","ترتيب حسب للدورة"},
{"eDR.OtherContactNo.label","رقم جهة اتصال أخرى"},
{"eDR.ParametersForSearchProcess.label","معلمات لعملية البحث"},
{"eDR.PatientFileDetails.label","تفاصيل ملف المريض"},
{"eDR.PatientID1.label","معرف المريض 1"},
{"eDR.PatientID2.label","معرف المريض 2"},
{"eDR.PlaceofBirth.label","مكان الميلاد"},
{"eDR.PossibleDuplicates.label","التكرارات المحتملة"},
{"eDR.PossibleDuplicatesDetails.label","تفاصيل التكرارات الممكنة"},
{"eDR.PreviousCriteria.label","المعايير السابقة"},
{"eDR.ProcessAuditData.label","بيانات تدقيق العملية"},
{"eDR.RebuildDictionaryBeforeMerge.label","أعد بناء القاموس قبل الدمج"},
{"eDR.RegnFacility.label","مرفق ريجن"},
{"eDR.ReplacementDate.label","تاريخ الاستبدال"},
{"eDR.ReportPossibleDuplicates.label","الإبلاغ عن التكرارات المحتملة"},
{"eDR.ResettoMergeProcess.label","إعادة التعيين إلى عملية الدمج"},
{"eDR.ResTelNo.label","إعادة تعيين رقم الهاتف"},
{"eDR.RightsforDRProcesses.label","حقوق عمليات DR"},
{"eDR.Running.label","ادارة"},
{"eDR.ScheduledBy.label","مجدولة بواسطة"},
{"eDR.ScheduledFrom.label","مجدول من"},
{"eDR.ScopeofSearch.label","نطاق البحث"},
{"eDR.SearchAcrossFacility.label","البحث عبر المنشأة"},
{"eDR.SearchinallFacilities.label","بحث في جميع المرافق"},
{"eDR.SearchProcessDetails.label","تفاصيل عملية البحث"},
{"eDR.SearchType.label","نوع البحث"},
{"eDR.SelectAllCurrentPage.label","حدد الكل (الصفحة الحالية)"},
{"eDR.SoundexAlgorithm.label","خوارزمية Soundex"},
{"eDR.StartLater.label","ابدأ لاحقًا"},
{"eDR.StartNow.label","ابدأ الآن"},
{"eDR.SubmissionDate.label","تاريخ التقديم"},
{"eDR.Sug.MainPatientID.label","أقترح معرف المريض الرئيسي"},
{"eDR.SuggestedMainPatientID.label","رقم تعريف المريض الرئيسي المقترح"},
{"eDR.SuspensionStatusRemarks.label","حالة التعليق / الملاحظات"},
{"eDR.TotalNoofGroups.label","إجمالي عدد المجموعات"},
{"eDR.TransactionID.label","رقم المعاملة"},
{"eDR.UnMergedDate.label","تاريخ غير مدمج"},
{"eDR.UnmergedTransactionsforPatient.label","المعاملات غير المدمجة للمريض"},
{"eDR.UnMergeDuplicates.label","فك التكرارات"},
{"eDR.UnmergeTransactionsforPatient.label","إلغاء دمج المعاملات للمريض"},
{"eDR.UserRights.label","حقوق المستخدم"},
{"eDR.ViewRecordDetails.label","عرض تفاصيل السجل"},
{"eDR.WarningErrorBeforeUnmerge.label","تحذير / خطأ قبل إلغاء الدمج"},
{"eDR.IdentifyDuplicate.label","تحديد مكرر"},
{"eDR.ReviewMergeProcessErrors.label","مراجعة أخطاء عملية الدمج"},
{"eDR.MotherMaidenName.label","اسم الأم قبل الزواج"},
{"eDR.MergedOn.label","تم الاندماج في"},
{"eDR.DupPatientID.label","معرف المريض مكرر"},
{"eDR.TotNoofExcludePosDupRecords.label","إجمالي عدد السجلات المكررة المستبعدة المحتملة"},
{"eDR.SuggestedValidPatient.label","اقترح مريض صالح"},
{"eDR.ReasonforNotMerging.label","سبب عدم الدمج"},
{"eDR.Identifiedstatus.label","الحالة المحددة"},
{"eDR.Merge.label","دمج"},
{"eDR.MergedRecords.label","السجلات المدمجة"},
{"eDR.UnMergedRecords.label","السجلات غير المدمجة"}

			}; 
}
