/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eDR.resources;

import java.util.*;

public class  Labels_th  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
		{"eDR.AbortProcess.label","ย�?เลิ�?�?ระบวน�?าร"},
		{"eDR.AdministerSearchProcess.label","�?ระบวน�?ารค้นหา�?ารจัด�?าร"},
		{"eDR.AuditData.label","�?ารตรวจข้อมูล"},
		{"eDR.ByEncounter.label","โดย�?ารบริ�?าร"},
		{"eDR.ByRegistrationDate.label","โดยวันที่ลงทะเบียน"},
		{"eDR.CloseProcess.label","ปิด�?ระบวน�?าร"},
		{"eDR.CriteriaforCurrentSearch.label","เงื่อนไข�?ารค้นหาในปัจจุบัน"},
		{"eDR.CriteriaforSuggestedMainPatient.label","เ�?ณฑ์สำหรับผู้ป่วยที่ค้นหาได้"},
		{"eDR.Dateandtime.label","วัน �?ละเวลา"},
		{"eDR.DateofMerge.label","วันที่รวม"},
		{"eDR.DateofUnMerge.label","วันที่ย�?เลิ�?�?ารรวม"},
		{"eDR.DefaultCriteria.label","เ�?ณฑ์เบื้องต้น"},
		{"eDR.DefaultSearchCriteria.label","เ�?ณฑ์ค้นหาตั้งต้น"},
		{"eDR.DemographicData.label","ข้อมูลประชา�?ร"},
		{"eDR.DoNotConsider.label","ไม่พิจารณา"},
		{"eDR.DRParameter.label","พารามิเตอร์ของ DR"},
		{"eDR.Duplicate.label","ซ้ำ"},
		{"eDR.DuplicateGroups.label","�?ลุ่มรายชื่อซ้ำ"},
		{"eDR.DuplicateDetails.label","รายละเอียด�?ารลงทะเบียนซ้ำ"},
		{"eDR.DuplicateSearchCriteria.label","เ�?ณฑ์ค้นหารายชื่อซ้ำ"},
		{"eDR.ExcludedPossibleDuplicates.label","ไม่รวมรายชื่อที่อาจซ้ำ"},
		{"eDR.ExcludePossibleDuplicates.label","ไม่รวมรายชื่อที่อาจซ้ำ"},
		{"eDR.ExecutionEndDate.label","วันสิ้นสุดดำเนิน�?าร"},
		{"eDR.ExecutionStartDate.label","วันเริ่มดำเนิน�?าร"},
		{"eDR.ExistingSeriesDetails.label","รายละเอียดของ"},
		{"eDR.FileLocation.label","สถานที่�?ฟ้มข้อมูล"},
		{"eDR.ForMergeProcess.label","สำหรับ�?ระบวน�?ารรวม"},
		{"eDR.ForUnmergeProcess.label","สำหรับย�?เลิ�?�?ระบวน�?ารรวม"},
		{"eDR.IdentifyMainDuplicatePatients.label","ค้นพบผู้ป่วยซ้ำ"},
		{"eDR.IdentifyMainDuplicates.label","ระบุต้นฉบับ/จำลอง"},
		{"eDR.IDNo.label","หมายเลขประจำตัว"},
		{"eDR.IDSeries.label","ชุดเลขประจำตัว"},
		{"eDR.IDSeriesDetails.label","รายละเอียดชุดเลขประจำตัว"},
		{"eDR.IDType.label","ชนิดของเลขประจำตัว"},
		{"eDR.LastDuplicateCheckDate.label","วันที่ตรวจสอบข้อมูลซ้ำครั้งสุดท้าย"},
		{"eDR.MainPatientID.label","หมายเลขประจำตัวผู้ป่วยหลั�?"},
		{"eDR.ManuallyEnteredDuplicates.label","บันทึ�?ข้อมูลซ้ำด้วยมือ"},
		{"eDR.Merge.label","รวม"},
		{"eDR.MergedBy.label","ทำ�?ารรวม โดย"},
		{"eDR.MergedDate.label","วันที่รวม"},
		{"eDR.MergedGroups.label","�?ลุ่มที่รวม"},
		{"eDR.MergePatientEndTime.label","เวลาสิ้นสุด�?ารรวมข้อมูลผู้ป่วย"},
		{"eDR.MergePatientOnlyDuring.label","รวมผู้ป่วยเฉพาะระหว่าง"},
		{"eDR.MergePatientStartTime.label","เวลาเริ่มต้น�?ารรวมข้อมูลผู้ป่วย"},
		{"eDR.MergeProcessDetails.label","รายละเอียด�?ระบวน�?ารรวม"},	 		
		{"eDR.MultipleMRN.label","หมายเลขเวชระเบียน"},
		{"eDR.NameinLocalLanguage.label","ชื่อตามภาษาท้องถิ่น"},
		{"eDR.NextExecutionDate.label","วันดำเนิน�?ารครั้งต่อไป"},
		{"eDR.NonDuplicates.label","ไม่จำลอง"},
		{"eDR.NotMergedGroups.label","�?ลุ่มที่ไม่ได้รวม/ไม่สามารถรวมได้"},
		{"eDR.OfficeFax.label","เบอร์โทรสารที่ที่ทำงาน"},
		{"eDR.OfficeTel.label","เบอร์โทรศัพท์ที่ที่ทำงาน"},
		{"eDR.OtherContactNo.label","หมายเลขติดต่ออื่น"},
		{"eDR.ParametersForSearchProcess.label","ตัว�?ปรสำหรับ�?ระบวน�?ารค้นหา"},
		{"eDR.PatientFileDetails.label","รายละเอียดของ�?ฟ้มผู้ป่วย"},
		{"eDR.PatientID1.label","หมายเลขประจำตัวผู้ป่วย�?ร�?"},
		{"eDR.PatientID2.label","หมายเลขประจำตัวผู้ป่วยที่สอง"},
		{"eDR.PlaceofBirth.label","สถานที่เ�?ิด"},
		{"eDR.PossibleDuplicates.label","อาจซ้ำ"},
		{"eDR.PossibleDuplicatesDetails.label","รายละเอียดที่จำลองได้"},
		{"eDR.PreviousCriteria.label","เ�?ณฑ์ที่ผ่านมา"},
		{"eDR.ProcessAuditData.label","ดำเนิน�?ารตรวจสอบข้อมูล"},
		{"eDR.RebuildDictionaryBeforeMerge.label","สร้างพจนานุ�?รม�?่อนรวม"},
		{"eDR.RegnFacility.label","สถานพยาบาลที่ลงทะเบียน"},
		{"eDR.ReplacementDate.label","วันที่ทด�?ทน"},
		{"eDR.ReportPossibleDuplicates.label","รายงานข้อมูลที่อาจซ้ำ"},
		{"eDR.ResettoMergeProcess.label","ตั้งค่าขั้นตอน�?ารรวมข้อมูลใหม่"},
		{"eDR.ResTelNo.label","หมายเลขโทรศัพท์บ้าน"},
		{"eDR.RightsforDRProcesses.label","สิทธิสำหรับ�?ระบวน�?าร DR"},
		{"eDR.Running.label","�?ำลังดำเนิน�?ารอยู่"},
		{"eDR.ScheduledBy.label","นัดโดย"},
		{"eDR.ScheduledFrom.label","นัดจา�?"},
		{"eDR.ScopeofSearch.label","ขอบเขต�?ารค้นหา"},
		{"eDR.SearchAcrossFacility.label","ค้นหาระหว่างสถานพยาบาล"},
		{"eDR.SearchinallFacilities.label","ค้นหาทุ�?สถานพยาบาล"},
		{"eDR.SearchProcessDetails.label","รายละเอียด�?ระบวน�?ารค้นหา"},
		{"eDR.SearchType.label","ชนิด�?ารค้นหา"},
		{"eDR.SelectAllCurrentPage.label","เลือ�?ทั้งหมด ( หน้าปัจจุบัน)"},
		{"eDR.SoundexAlgorithm.label","ระบบดัชนีเสียงพ้อง"},
		{"eDR.StartLater.label","�?ระทำภายหลัง"},
		{"eDR.StartNow.label","�?ระทำขณะนี้"},
		{"eDR.SubmissionDate.label","วันที่ส่ง/บันทึ�?"},
		{"eDR.Sug.MainPatientID.label","เลขประจำตัวผู้ป่วย...."},
		{"eDR.SuggestedMainPatientID.label","เลขประจำตัวผู้ป่วยที่ค้นหาได้"},
		{"eDR.SuspensionStatusRemarks.label","สถานะหยุดชั่วคราว/หมายเหตุ"},
		{"eDR.TotalNoofGroups.label","จำนวนทั้งหมดของ�?ลุ่ม"},
		{"eDR.TransactionID.label","เลขประจำตัวธุร�?รรม"},
		{"eDR.UnMergedDate.label","วันที่ย�?เลิ�?�?ารรวม"},
		{"eDR.UnmergedTransactionsforPatient.label","�?ารย�?เลิ�?�?ารรวมผู้ป่วย"},
		{"eDR.UnMergeDuplicates.label","ย�?เลิ�?�?ารรวมข้อมูลซ้ำ"},
		{"eDR.UnmergeTransactionsforPatient.label","�?ารย�?เลิ�?�?ารรวมผู้ป่วย"},
		{"eDR.UserRights.label","สิทธิของผู้ใช้"},
		{"eDR.ViewRecordDetails.label","ดูรายละเอียดของข้อมูล"},
		{"eDR.WarningErrorBeforeUnmerge.label","คำเตือน/เ�?ิดความผิดพลาด�?่อน�?ารย�?เลิ�?�?ารรวม"},
		{"eDR.MergedOn.label","th_Merged On"},
		{"eDR.DupPatientID.label","th_Dup Patient ID"}
	};
}
