/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eDR.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eDR.AbortProcess.label","ä¸­æ­¢è¿›ç¨‹"},
		{"eDR.AdministerSearchProcess.label","æ?œç´¢è¿‡ç¨‹ç®¡ç?†"},
		{"eDR.AuditData.label","å®¡è®¡æ•°æ?®"},
		{"eDR.ByEncounter.label","é€šè¿‡åº§è°ˆä¼š"},
		{"eDR.ByRegistrationDate.label","ç™»è®°æ—¥æœŸ"},
		{"eDR.CloseProcess.label","å…³é—­è¿›ç¨‹"},
		{"eDR.CriteriaforCurrentSearch.label","ç›®å‰?æŸ¥æ‰¾æ ‡å‡†"},
		{"eDR.CriteriaforSuggestedMainPatient.label","ä¸ºä¸»è¦?ç—…äººæ ‡å‡†ï¼Ÿ"},
		{"eDR.Dateandtime.label","æ—¥æœŸå’Œæ—¶é—´"},
		{"eDR.DateofMerge.label","å?ˆå¹¶æ—¥æœŸ"},
		{"eDR.DateofUnMerge.label","å?–æ¶ˆæ—¥æœŸ"},
		{"eDR.DefaultCriteria.label","é»˜è®¤æ ‡å‡†"},
		{"eDR.DefaultSearchCriteria.label","é»˜è®¤æ?œç´¢æ ‡å‡†"},
		{"eDR.DemographicData.label","äººå?£èµ„æ–™"},
//		{"eDR.DoNotConsider.label","Do Not Consider"},
		{"eDR.DRParameter.label","åŒ»ç”Ÿå?‚æ•°ï¼Ÿ"},
		{"eDR.Duplicate.label","é‡?å¤?"},
		{"eDR.DuplicateGroups.label","é‡?å¤?ç»„"},
		{"eDR.DuplicateDetails.label","é‡?å¤?çš„è¯¦ç»†èµ„æ–™"},
		{"eDR.DuplicateSearchCriteria.label","é‡?å¤?çš„æ?œç´¢æ ‡å‡†"},
		{"eDR.ExcludedPossibleDuplicates.label","æŽ’é™¤å?¯èƒ½çš„é‡?å¤?"},
		{"eDR.ExcludePossibleDuplicates.label","æŽ’é™¤å?¯èƒ½çš„é‡?å¤?"},
		{"eDR.ExecutionEndDate.label","æ‰§è¡Œç»“æ?Ÿæ—¥æœŸ"},
		{"eDR.ExecutionStartDate.label","æ‰«è¡Œå¼€å§‹æ—¥æœŸ"},
		{"eDR.ExistingSeriesDetails.label","å­˜åœ¨çš„åº?åˆ—æ˜Žç»†"},
		{"eDR.FileLocation.label","æ–‡ä»¶ä½?ç½®"},
		{"eDR.ForMergeProcess.label","å?ˆå¹¶è¿›ç¨‹"},
		{"eDR.ForUnmergeProcess.label","å?–æ¶ˆè¿›ç¨‹"},
		{"eDR.IdentifyMainDuplicatePatients.label","è¯†åˆ«ä¸»è¦?é‡?å¤?æ‚£è€…"},
		{"eDR.IdentifyMainDuplicates.label","è¯†åˆ«ä¸»è¦?/é‡?å¤?"},
		{"eDR.IDNo.label","ç¼–å?·"},
		{"eDR.IDSeries.label","ç¼–å?·ç³»åˆ—"},
		{"eDR.IDSeriesDetails.label","ç¼–å?·ç³»åˆ—æ˜Žç»†"},
		{"eDR.IDType.label","ç¼–å?·ç±»åž‹"},
		{"eDR.LastDuplicateCheckDate.label","æœ€å?Žé‡?å¤?æ£€æŸ¥æ—¥æœŸ"},
		{"eDR.MainPatientID.label","ä¸»è¦?ç—…äººç¼–å?·"},
		{"eDR.ManuallyEnteredDuplicates.label","æ‰‹åŠ¨è¾“å…¥é‡?å¤?"},
		{"eDR.Merge.label","å?ˆå¹¶"},
		{"eDR.MergedBy.label","å?ˆå¹¶é€šè¿‡"},
		{"eDR.MergedDate.label","å?ˆå¹¶æ—¥æœŸ"},
		{"eDR.MergedGroups.label","å?ˆå¹¶ç»„"},
		{"eDR.MergePatientEndTime.label","å?ˆå¹¶ç—…äººç»“æ?Ÿæ—¶é—´"},
		{"eDR.MergePatientOnlyDuring.label","å?ªå?ˆå¹¶ç—…äºº"},
		{"eDR.MergePatientStartTime.label","å?ˆå¹¶ç—…äººå¼€å§‹æ—¶é—´"},
		{"eDR.MergeProcessDetails.label","å?ˆå¹¶è¿‡ç¨‹çš„ç»†èŠ‚"},		
		{"eDR.MultipleMRN.label","å¤šç—…åŽ†å?·çš„"},
		{"eDR.NameinLocalLanguage.label","åœ¨å½“åœ°è¯­è¨€ä¸­çš„å??ç§°"},
		{"eDR.NextExecutionDate.label","ä¸‹ä¸€æ­¥æ‰§è¡Œæ—¥æœŸ"},
		{"eDR.NonDuplicates.label","ä¸?é‡?å¤?"},
//		{"eDR.NotMergedGroups.label","Not Merged Groups"},
		{"eDR.OfficeFax.label","åŠžå…¬å®¤ä¼ çœŸ"},
		{"eDR.OfficeTel.label","åŠžå…¬å®¤ç”µè¯?"},
		{"eDR.OrderByforCycle.label","å‘¨æœŸé¡ºåº?"},
		{"eDR.OtherContactNo.label","æ— è?”ç³»å?·ç ?"},
		{"eDR.ParametersForSearchProcess.label","æŸ¥æ‰¾è¿›ç¨‹å?‚æ•°"},
		{"eDR.PatientFileDetails.label","ç—…äººçš„æ¡£æ¡ˆæ•°æ?®"},
		{"eDR.PatientID1.label","ç—…äººå­—å?·1"},
		{"eDR.PatientID2.label","ç—…äººå­—å?·2"},
		{"eDR.PlaceofBirth.label","å‡ºç”Ÿåœ°ç‚¹"},
		{"eDR.PossibleDuplicates.label","å?¯èƒ½é‡?å¤?"},
		{"eDR.PossibleDuplicatesDetails.label","å?¯èƒ½é‡?å¤?çš„ç»†èŠ‚"},
		{"eDR.PreviousCriteria.label","å‰?æ ‡å‡†"},
		{"eDR.ProcessAuditData.label","è¿‡ç¨‹å®¡è®¡èµ„æ–™"},
		{"eDR.RebuildDictionaryBeforeMerge.label","æ”¹é€ å‰?å?ˆå¹¶è¯?å…¸"},
//		{"eDR.RegnFacility.label","Regn Facility"},
		{"eDR.ReplacementDate.label","æ›´æ?¢æ—¥æœŸ"},
		{"eDR.ReportPossibleDuplicates.label","å?¯èƒ½é‡?å¤?çš„æŠ¥å‘Š"},
		{"eDR.ResettoMergeProcess.label","é‡?å?¯å?ˆå¹¶è¿›ç¨‹"},
//		{"eDR.ResTelNo.label","Res. Tel. No."},
		{"eDR.RightsforDRProcesses.label","åŒ»ç”Ÿè¿›ç¨‹æ?ƒåˆ©ï¼Ÿ"},
		{"eDR.Running.label","è¿?è¡Œ"},
		{"eDR.ScheduledBy.label","é¢„å®š"},
		{"eDR.ScheduledFrom.label","å®šäºŽ"},
		{"eDR.ScopeofSearch.label","æ?œç´¢èŒƒå›´"},
		{"eDR.SearchAcrossFacility.label","æ?œç´¢å¤šå?°è®¾å¤‡"},
		{"eDR.SearchinallFacilities.label","æ?œç´¢æ‰€æœ‰è®¾æ–½"},
		{"eDR.SearchProcessDetails.label","æ?œç´¢è¿‡ç¨‹ä¸­çš„ç»†èŠ‚"},
		{"eDR.SearchType.label","æ?œç´¢ç±»åž‹"},
		{"eDR.SelectAllCurrentPage.label","å…¨é€‰ï¼ˆå½“å‰?é¡µï¼‰"},
//		{"eDR.SoundexAlgorithm.label","Soundex Algorithm"},
		{"eDR.StartLater.label","å?Žæ?¥å¼€å§‹"},
		{"eDR.StartNow.label","çŽ°åœ¨å¼€å§‹"},
		{"eDR.SubmissionDate.label","æ??äº¤æ—¥æœŸ"},
		{"eDR.Sug.MainPatientID.label","æ??äº¤ä¸»è¦?ç—…äººç¼–å?·"},
		{"eDR.SuggestedMainPatientID.label","å»ºè®®çš„ä¸»è¦?ç—…äººç¼–å?·"},
		{"eDR.SuspensionStatusRemarks.label","æ‚¬æµ®çŠ¶æ€?/å¤‡æ³¨"},
		{"eDR.TotalNoofGroups.label","æ€»ç¾¤å?·"},
		{"eDR.TransactionID.label","äº¤æ˜“å?·"},
		{"eDR.UnMergedDate.label","ä¸?å?ˆå¹¶æ—¥æœŸ"},
		{"eDR.UnmergedTransactionsforPatient.label","ç—…äººä¸?å?ˆå¹¶äº¤æ˜“"},
		{"eDR.UnMergeDuplicates.label","å?–æ¶ˆé‡?å¤?"},
		{"eDR.UnmergeTransactionsforPatient.label","å?–æ¶ˆäº¤æ˜“çš„ç—…äºº"},
		{"eDR.UserRights.label","ç”¨æˆ·æ?ƒåˆ©"},
		{"eDR.ViewRecordDetails.label","æŸ¥çœ‹è¯¦ç»†è®°å½•"},
		{"eDR.WarningErrorBeforeUnmerge.label","å?–æ¶ˆå‰?è­¦å‘Šï¼?é”™è¯¯æ??ç¤º"},
		{"eDR.IdentifyDuplicate.label","æ ‡è¯†é‡?å¤?"},
		{"eDR.ReviewMergeProcessErrors.label","å®¡æŸ¥å?ˆå¹¶è¿‡ç¨‹ä¸­çš„é”™è¯¯"},
		{"eDR.MotherMaidenName.label","æ¯?äº²æœ¬å§“"},
//Newly added legends on 21/01/09
		{"eDR.DoNotConsider.label","ä¸?è€ƒè™‘ç—…äººçš„å?ˆå¹¶"},
		{"eDR.NotMergedGroups.label","ä¸?å?ˆå¹¶ç»„"},
		{"eDR.RegnFacility.label","æ³¨å†ŒåŒ»é™¢"},
		{"eDR.ResTelNo.label","ä½?å®…ç”µè¯?"},
		{"eDR.SoundexAlgorithm.label","æŽ¢æµ‹ç®—æ³•"},


	};
}
