package eDS.SupplementaryOrder.dao;
import java.sql.Connection;
import java.util.List;

import eDS.SupplementaryOrder.model.PlaceSupplementaryMealOrderRequest;
import eDS.SupplementaryOrder.model.PlaceSupplementaryMealOrderResponse;
import eDS.SupplementaryOrder.model.SupplementaryPlaceOrderRequest;
import eDS.SupplementaryOrder.model.SupplementaryPlaceOrderResponse;
import eDS.SupplementaryOrder.model.SupplementaryProcessRequest;

public interface SupplementaryPlaceOrderDAO {
	public SupplementaryPlaceOrderResponse getSupplementayPlaceSearch(SupplementaryPlaceOrderRequest request,Connection Con);
	public String insertSupplementaryMealOrder(PlaceSupplementaryMealOrderRequest request,Connection con);
	public  List<PlaceSupplementaryMealOrderResponse> getSupplementaryMealOrder(PlaceSupplementaryMealOrderRequest request,Connection connection);
	public  List<PlaceSupplementaryMealOrderResponse> getOldSupplementaryMealOrder(PlaceSupplementaryMealOrderRequest request,Connection connection);
	public SupplementaryPlaceOrderResponse getProcessSupplementaryOrderList(SupplementaryProcessRequest request,Connection connection);
	public String updateSupplementaryMealOrder(SupplementaryProcessRequest request,Connection connection);
}
