/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eIP.resources;


import java.util.*;

public class  Labels  extends ListResourceBundle implements java.io.Serializable
{
	public Object[][] getContents() 
	{
         return contents;
    }

	static final Object[][] contents = 
	{
		{"eIP.AbortCancel.label","Abort Cancel"},
		{"eIP.AbortCancellation.label","Abort Cancellation"},
		{"eIP.AbortDischarge.label","Abort Discharge"},
		{"eIP.AbortRevision.label","Abort Revision"},
		{"eIP.AbortSwap.label","Abort Swap"},
		{"eIP.Absconded.label","Absconded"},
		{"eIP.AbscondedDetails.label","Absconded Details"},
		{"eIP.AbscondedFrom.label","Absconded From"},
		{"eIP.AbscondedRemarks.label","Absconded Remarks"},
		{"eIP.Absconding.label","Absconding"},
		{"eIP.AbscondingDate.label","Date of Absconding"},
		{"eIP.AbscondingDateTime.label","Absconding Date/Time"},
		{"eIP.AbscondingDetails.label","Absconding Details"},
		{"eIP.Accident.label","Accident"},
		{"eIP.AccompanyingPerson.label","Accompanying Person"},
		{"eIP.AccompanyingPersonDetails.label","Accompanying Person Details"},
		{"eIP.AccompanyingPersonID.label","Accompanying Person ID"},
		{"eIP.AccompanyingPersonName.label","Accompanying Person Name"},
		{"eIP.AccompanyingPersons.label","Accompanying Persons"},
		{"eIP.AcctDeptService.label","Acct Dept/Service"},
		{"eIP.ActiononExceedingMaxLeave.label","Action on Exceeding Max Leave"},
		{"eIP.ActiveBooking.label","Active Booking"},
		{"eIP.Activity.label","Activity"},
		{"eIP.ActivityReason.label","Activity Reason"},
		{"eIP.AdditionalDepositAmount.label","Additional Deposit Amount"},
		{"eIP.AdditionalDepositRequired.label","Additional Deposit Required"},
		{"eIP.AdditionalDischargeDetails.label","Additional Discharge Details"},
		{"eIP.AdditionalServices.label","Additional Services"},
		{"eIP.AdmDateFrom.label","Admission Date From"},
		{"eIP.DischargeReport.label","Discharge Report"},
		{"eIP.AdmissionReport.label","Admission Report"},
		{"eIP.AdmDateTo.label","Admission Date To"},
		{"eIP.AdmissionFor.label","Admission For"},
		{"eIP.AdmissionHistory.label","Admission History"},
		{"eIP.Admissions.label","Admissions"},
		{"eIP.AdmissionTypeCode.label","Admission Type Code"},
		{"eIP.AdmissionWithBed.label","Admission With Bed"},
		{"eIP.AdmissionWithoutBed.label","Admission Without Bed"},
		{"eIP.AdmissionWorkupChargeFee.label","Admission Workup Charge Fee"},
		{"eIP.AdmissionYear.label","Admission Year"},
		{"eIP.AdmittedDate.label","Admitted Date"},
		{"eIP.Admitting.label","Admitting"},
		{"eIP.AdmittingPractitioner.label","Admitting Practitioner"},
		{"eIP.AdmMonthFrom.label","Admission Month From"},
		{"eIP.AdviceGivenTo.label","Advice Given to"},
		{"eIP.AdviceonContcare.label","Advice on Continuous care given to Parent"},
		{"eIP.AgeGender.label","Age/Gender"},
		{"eIP.AgeGroupBedClass.label","AgeGroup-Bed Class"},
		{"eIP.AllowablePeriodforIssue.label","Allowable Period for Issue"},
		{"eIP.AllowBedSwap.label","Allow Bed Swap"},
		{"eIP.AllowBookingforUnregisteredPatients.label","Allow Booking for Unregistered Patients"},
		{"eIP.AllowedAdmission.label","Allowed Admission"},
		{"eIP.AllowedBooking.label","Allowed Booking"},
		{"eIP.AllowLeaveCancellationWithin.label","Allow Leave Cancellation Within"},
		{"eIP.AllowNewbornRegn.label","Allow Newborn Regn"},
		{"eIP.AllowPatientCheckin.label","Allow Patient Check-in"},
		{"eIP.AllowPseudoBeds.label","Allow Pseudo Beds"},
		{"eIP.AllowTransferWOReq.label","Allow Transfer W/O Request"},
		{"eIP.AllSPLTY.label","All Specialties"},
		{"eIP.AmbulanceReqdDateTime.label","Ambulance Reqd Date/Time"},
		{"eIP.AmendInpatientLeave.label","Amend Inpatient Leave"},
		{"eIP.AnalDilatation.label","Anal Dilatation"},
		{"eIP.ApplFixturesDocuments.label","Appl./Fixtures Documents"},
		{"eIP.assignbedmarkpatientarrival.label","Assign Bed / Mark Patient Arrival"},
		{"eIP.Assisting.label","Assisting"},
		{"eIP.Attendant.label","Attendant"},
		{"eIP.AuthorizationDateTime.label","Authorization Date/Time"},
		{"eIP.AuthorizedPractitioner.label","Authorized Practitioner"},
		{"eIP.AutoFileTransfer.label","Auto File Transfer"},
		{"eIP.AvailNursUnit.label","Available Nurs Unit"},
		{"eIP.BabiesBeds.label","Babies Beds"},
		{"eIP.BabyDetails.label","Baby Details"},
		{"eIP.BabyToMotherDetails.label","Baby to Mother Details"},
		{"eIP.BedAllocationDateTime.label","Bed Allocation Date/Time"},
		{"eIP.BedAvailabilityChart.label","Bed Availability Chart"},
		{"eIP.BedBlockDetails.label","Bed Block Details"},
		{"eIP.BedBlocking.label","Bed Blocking"},
		{"eIP.BedBlockingPeriod.label","Bed Blocking Period"},
		{"eIP.BedBlockleduntil.label","Bed Blocked Until"},
		{"eIP.BedBookingSerialControl.label","Bed Booking Serial Control"},
		{"eIP.BedCharge.label","Bed Charge"},
		{"eIP.BedClassCode.label","Bed Class Code"},
		{"eIP.BedClassCodeFrom.label","Bed Class Code From"},
		{"eIP.BedClassification.label","Bed Classification"},
		{"eIP.BedDetails.label","Bed Details"},
		{"eIP.BedLayoutForFloor.label","Bed Layout for Floor/Cubicle"},
		{"eIP.BedOccupancyByNursingUnit.label","Bed Occupancy By Nursing Unit"},
		{"eIP.BedOccupancybySpecialty.label","Bed Occupancy by Specialty"},
		{"eIP.Beds.label","Beds"},
		{"eIP.BedsBlocked.label","Beds Blocked"},
		{"eIP.Bedside.label","Bedside"},
		{"eIP.BedsideReferralSeenDate.label","Bedside Referral Seen Date"},
		{"eIP.BedsOccupied.label","Beds Occupied"},
		{"eIP.BedsVacant.label","Beds Vacant"},
		{"eIP.BedTypeCode.label","Bed Type Code"},
		{"eIP.BedLayout.label","Bed Layout"},
		{"eIP.BelongingsReturned.label","Belongings Returned"},
		{"eIP.BillingParameter.label","Billing Parameter"},
		{"eIP.BillType.label","Bill Type"},
		{"eIP.BlackListed.label","Black Listed"},
		{"eIP.BlockBed.label","Block Bed"},
		{"eIP.BlockBedDetails.label","Block Bed Details"},
		{"eIP.BlockBedonDischarge.label","Block Bed on Discharge"},
		{"eIP.BlockedBedNo.label","Blocked Bed No"},
		{"eIP.BlockedFrom.label","Blocked From"},
		{"eIP.BlockedFromDate.label","Blocked From Date"},
		{"eIP.BlockedRemarks.label","Blocked Remarks"},
		{"eIP.BlockedThrough.label","Blocked Through"},
		{"eIP.BlockedType.label","Blocked Type"},
		{"eIP.BlockingDetail.label","Blocking Detail"},
		{"eIP.BlockingFunction.label","Blocking Function"},
		{"eIP.BlockingPeriod.label","Blocking Period"},
		{"eIP.BlockingRefNo.label","Blocking Ref No"},
		{"eIP.BlockingType.label","Blocking Type"},
		{"eIP.BlockingTypeCode.label","Blocking Type Code"},
		{"eIP.BlockPeriod.label","Block Period"},
		{"eIP.BlockType.label","Block Type"},
		{"eIP.BloodandMedication.label","Blood and Medication"},
		{"eIP.BodyReleasedtoMortuary.label","Body Released to Mortuary"},
		{"eIP.BodyReleasedtoMortuaryDate.label","Body Released to Mortuary Date"},
		{"eIP.BookedBlocked.label","Booked/Blocked"},
		{"eIP.BookedFrom.label","Booked From"},
		{"eIP.BookedUntil.label","Booked Until"},
		{"eIP.BookingAdmissionDetails.label","Booking Admission Details"},
		{"eIP.BookingDateTime.label","Booking Date/Time"},
		{"eIP.BookingDetails.label","Booking Details"},
		{"eIP.BookingLimitByAgeGroupBedClass.label","Booking Limit By Age Group - Bed Class"},
		{"eIP.BookingLimitByNursingUnitBedClass.label","Booking Limit By Nursing Unit - Bed Class"},
		{"eIP.BookingorReferral.label","Booking or Referral"},
		{"eIP.BookingRef.label","Booking Ref"},
		{"eIP.BookingReferenceLookup.label","Booking Reference Lookup"},
		{"eIP.BookingRelatedSetup.label","Booking Related Setup"},
		{"eIP.Bookings.label","Bookings"},
		{"eIP.BookingSerialDetails.label","Booking Serial Details"},
		{"eIP.BookingType.label","Booking Type"},
		{"eIP.BreastFeeding.label","Breast Feeding"},
		{"eIP.BreastFeedingExpressedbreastmilk.label","Breast Feeding/Expressed breast milk"},
		{"eIP.ByNursingUnit.label","By Nursing Unit"},
		{"eIP.ByPractitioner.label","By Practitioner"},
		{"eIP.CalculatedAmount.label","Calculated Amount"},
		{"eIP.CalculatePercentageOn.label","Calculate Percentage On"},
		{"eIP.CancelLeave.label","Cancel Leave"},
		{"eIP.CancelLeaveDetails.label","Cancel Leave Details"},
		{"eIP.CancelledAdmission.label","Cancelled Admission"},
		{"eIP.CancelledByID.label","Cancelled By ID"},
		{"eIP.CancelledDate.label","Cancelled Date"},
		{"eIP.CancelledDateTo.label","Cancelled Date To"},
		{"eIP.CancelledReason.label","Cancelled Reason"},
		{"eIP.CancelledRequest.label","Cancelled Request"},
		{"eIP.CancelledTransferOut.label","Cancelled Transfer Out"},
		{"eIP.CancelReasonDescription.label","Cancel Reason Description"},
		{"eIP.CancelRequestForTransfer.label","Cancel Request For Transfer"},
		{"eIP.CancelTransferPatientOut.label","Cancel Transfer Patient Out"},
		{"eIP.CareofCatheters.label","Care of Catheters"},
		{"eIP.CareofEye.label","Care of Eye"},
		{"eIP.CareofPOP.label","Care of POP"},
		{"eIP.CareOfPretermbaby.label","Care of Preterm Baby"},
		{"eIP.CareofSkin.label","Care of Skin"},
		{"eIP.CareOfStoma.label","Care of Stoma"},
		{"eIP.CareofTube.label","Care of Tube"},
		{"eIP.CareofumbilicusStump.label","Care of Umbilicus Stump"},
		{"eIP.CensusDate.label","Census Date Range From"},
		{"eIP.CensusDate1.label","Census Date Range To"},
		{"eIP.CensusMonth.label","Census Month"},
		{"eIP.CensusMonthYear.label","Census Month Year"},
		{"eIP.CertificateNumber.label","Certificate Number"},
		{"eIP.ChangeofNasogastricTube.label","Change of Nasogastric Tube"},
		{"eIP.ChangeofUrinaryCatheter.label","Change of Urinary Catheter"},
		{"eIP.ChargesIncurredonDischargeDay.label","Charges Incurred on Discharge Day"},
		{"eIP.CheckBookingLimitBasedon.label","Check Booking Limit Based on"},
		{"eIP.CheckforSameSexinRoom.label","Check for Same Sex in Room"},
		{"eIP.CheckInAccompanyingPerson.label","Check in Accompanying Person"},
		{"eIP.CheckInDateFrom.label","Check-In Date From"},
		{"eIP.CheckInDateTime.label","Check-In Date/Time"},
		{"eIP.CheckInlodger.label","Check-In Lodger"},
		{"eIP.checkoutaccomperson.label","Check-out Accompanying Person"},
		{"eIP.checkoutdatetime.label","Check out Date/Time"},
		{"eIP.checkoutlodger.label","Check-out Lodger"},
		{"eIP.ChkdInDt.label","Checked-in Date"},
		{"eIP.ClinicalDocFilm.label","Clinical Doc/Film"},
		{"eIP.ColorSchemeTable.label","Color Scheme Table"},
		{"eIP.ColourCodeScheme.label","Colour Code Scheme"},
		{"eIP.ConfirmBedClassChange.label","Confirm Bed Class Change"},
		{"eIP.ConfirmBookingDetails.label","Confirm Booking Details"},
		{"eIP.ConfirmCancellation.label","Confirm Cancellation"},
		{"eIP.ConfirmCancelReviseBooking.label","Confirm/Cancel/Revise Booking"},
		{"eIP.ConfirmDetails.label","Confirm Details"},
		{"eIP.ConfirmDischarge.label","Confirm Discharge"},
		{"eIP.ConfirmRequestforTransfer.label","Confirm Request for Transfer"},
		{"eIP.ConfirmSwap.label","Confirm Swap"},
		{"eIP.ConfirmSwapBeds.label","Confirm Swap Beds"},
		{"eIP.ConsumableBillingService.label","Consumable Billing Service"},
		{"eIP.ConsumableFee.label","Consumable Fee"},
		{"eIP.CostCenter.label","Cost Center"},
		{"eIP.CreatePseudoBed.label","Create Pseudo Bed"},
		{"eIP.CurrentEncounterDetails.label","Current Encounter Details"},
		{"eIP.CurrentInpatientsOnly.label","Current Inpatients Only"},
		{"eIP.CurrentLodgers.label","Current Lodgers"},
		{"eIP.CurrentOccupancy.label","Current Occupancy"},
		{"eIP.CurrentValidityDetails.label","Current Validity Details"},
		{"eIP.DailyAdmissions.label","Daily Admissions"},
		{"eIP.DailyBookingsByMedicalServiceGroup.label","Daily Bookings By Medical Service Group"},
		{"eIP.DailyBookingsByNursingUnit.label","Daily Bookings By Nursing Unit"},
		{"eIP.DailyCharge.label","Daily Charge"},
		{"eIP.DailyCharges.label","Daily Charges"},
		{"eIP.DailyMonthlyBookings.label","Daily/Monthly Bookings"},
		{"eIP.DailyRate.label","Daily Rate"},
		{"eIP.DateTimeOfAuthTransfer.label","Date/Time of Authorized Transfer"},
		{"eIP.DateTimeReturned.label","Date/Time Returned"},
		{"eIP.DaycareUnitforNursingUnit.label","Daycare Unit for Nursing Unit"},
		{"eIP.DeactivatePseudoBed.label","Deactivate Pseudo Bed"},
		{"eIP.DeathTransactionTime.label","Death Transaction Time"},
		{"eIP.DeceasedDateFrom.label","Deceased Date From"},
		{"eIP.DeceasedDateTo.label","Deceased Date To"},
		{"eIP.DefaultBedBlockingPeriodonTransferDischargeofInfectiousDiseasePatients.label","Default Bed Blocking Period on Transfer / Discharge of Infectious Disease Patients"},
		{"eIP.DefaultPeriodforNormal.label","Default Period for Normal"},
		{"eIP.DepositAmount.label","Deposit Amount"},
		{"eIP.DepositApplicable.label","Deposit Applicable"},
		{"eIP.DesignationTitle.label","Designation/Title"},
		{"eIP.Diet.label","Diet"},
		{"eIP.DischargeAdviceReport.label","Discharge Advice Report"},
		{"eIP.DischargeBookGiven.label","Discharge Book Given"},
		{"eIP.DischargeCheckList.label","Discharge Check List"},
		{"eIP.DischargeCheckListApplicable.label","Discharge Check List Applicable"},
		{"eIP.DischargeChecklistExpiryPeriod.label","Discharge Checklist Expiry Period"},
		{"eIP.DischargeDateFrom.label","Discharge Date From"},
		{"eIP.DischargeDateTo.label","Discharge Date To"},
		{"eIP.DischargeDetails.label","Discharge Details"},
		{"eIP.DischargedHome.label","Discharged/Home"},
		{"eIP.DischargeDiagnosis.label","Discharge Diagnosis"},
		{"eIP.DischargeFunction.label","Discharge Function"},
		{"eIP.DischargeRemarks.label","Discharge Remarks"},
		{"eIP.DischargeSummarySigned.label","Discharge Summary Signed"},
		{"eIP.DischargeTypeCode.label","Discharge Type Code"},
		{"eIP.DischargeTypeIndicator.label","Discharge Type Indicator"},
		{"eIP.DischargingPractitioner.label","Discharging Practitioner"},
		{"eIP.DiscSummaryPrepared.label","Disc Summary Prepared"},
		{"eIP.DrainageCatheters.label","Drainage Catheters"},
		{"eIP.EmergencyDetail.label","Emergency Detail"},
		{"eIP.EmergencyTransfer.label","Emergency Transfer"},
		{"eIP.EscortAmbulanceService.label","Escort/Ambulance Service"},
		{"eIP.ExistingMedication.label","Existing Medication"},
		{"eIP.ExpdaysofStay.label","Expected Days of Stay"},
		{"eIP.ExpectedDischarge.label","Expected Discharge"},
		{"eIP.ExpectedDischargeDateTime.label","Expected Discharge Date/Time"},
		{"eIP.ExpectesDischargeDate.label","Expected Discharge Date"},
		{"eIP.ExpiryPeriodUnit.label","Expiry Period Unit"},
		{"eIP.ExpiryRequired.label","Expiry Required"},
		{"eIP.FatherIDNo.label","Father ID No"},
		{"eIP.Fever.label","Fever"},
		{"eIP.FinancialClassification.label","Financial Classification"},
		{"eIP.FitForDutyon.label","Fit For Duty on"},
		{"eIP.FloorPlanLayout.label","Floor Plan Layout"},
		{"eIP.FollowupAppointments.label","Follow up Appointments"},
		{"eIP.Formulamilk.label","Formula Milk"},
		{"eIP.FromBedType.label","From Bed Type"},
		{"eIP.FromBedTypeAmount.label","From Bed Type Amount"},
		{"eIP.FromBedTypeCode.label","From Bed Type Code"},
		{"eIP.FromDetails.label","From Details"},
		{"eIP.FromYear.label","From Year"},
		{"eIP.Gastrotomyfeeding.label","Gastrotomy feeding"},
		{"eIP.GenerateBookingNumber.label","Generate Booking Number"},
		{"eIP.GraceperiodforAbscondPatient.label","Grace period for Abscond Patient"},
		{"eIP.GraceperiodforNoShow.label","Grace period for No Show"},
		{"eIP.GracePeriodforRevisionofBooking.label","Grace Period for Revision of Booking"},
		{"eIP.guardian.label","Guardian"},
		{"eIP.HandedovertoPatient.label","Handed over to Patient"},
		{"eIP.HealthEducation.label","Health Education"},
		{"eIP.HospitalOccupancy.label","Hospital Occupancy"},
		{"eIP.ImmunizationSchedule.label","Immunization Schedule"},
		{"eIP.InclDiscPatients.label","Incl Disc Patients"},
		{"eIP.IncludeBedtobereleasedin.label","Include Bed to be released in"},
		{"eIP.IncludeforHospitalCalculation.label","Include for Hospital Calculation"},
		{"eIP.IncludeforHospitalOccupancyCalculations.label","Include for Hospital Occupancy Calculations"},
		{"eIP.Informed.label","Informed"},
		{"eIP.InformedDetails.label","Informed Details"},
		{"eIP.InformedOthers.label","Informed Others"},
		{"eIP.InformedPatientRelatives.label","Informed Patient Relatives"},
		{"eIP.InformedTo.label","Informed To"},
		{"eIP.InformedToName.label","Informed To Name"},
		{"eIP.InsuranceExpiryWarning.label","Insurance Expiry Warning"},
		{"eIP.Interward.label","Inter ward"},
		{"eIP.Intraward.label","Intra ward"},
		{"eIP.IPMiscsetup.label","IP Misc setup"},
		{"eIP.IssuingPractitioner.label","Issuing Practitioner"},
		{"eIP.IVCatheters.label","IV Catheters"},
		{"eIP.Jaundice.label","Jaundice"},
		{"eIP.LabourAndDelivery.label","Labour and Delivery"},
		{"eIP.LastTransactionDateTime.label","Last Transaction Date/Time"},
		{"eIP.LeaveDatefrom.label","Leave Date from"},
		{"eIP.leavedatetime.label","Leave Date/Time"},
		{"eIP.LeaveDetails.label","Leave Details"},
		{"eIP.LeaveExpiry.label","Leave Expiry"},
		{"eIP.LeaveRemarks.label","Leave Remarks"},
		{"eIP.LeaveWardAccompaniedBy.label","Leave Ward Accompanied by"},
		{"eIP.LengthofStay.label","Length of Stay"},
		{"eIP.LodgerAccompanyingPersonReference.label","Lodger/Accompanying Person Reference"},
		{"eIP.LodgerDetails.label","Lodger Details"},
		{"eIP.LodgerId.label","Lodger ID"},
		{"eIP.LodgerName.label","Lodger Name"},
		{"eIP.LodgerPersonID.label","Lodger Person ID"},
		{"eIP.LodgerReferenceMaxSrlNo.label","Lodger Reference Max Srl No"},
		{"eIP.LodgerReferenceNextSrlNo.label","Lodger Reference Next Srl No"},
		{"eIP.MainBedNo.label","Main Bed No"},
		{"eIP.MaternalDeath.label","Maternal Death"},
		{"eIP.MaxAllowableBackdatedAdmission.label","Max Allowable Backdated Admission"},
		{"eIP.MaxAllowableBackdatedDischarge.label","Max Allowable Backdated Discharge"},
		{"eIP.MaxAllowableBedblockingPeriod.label","Max Allowable Bed blocking Period"},
		{"eIP.MaxAllowableLeavePeriod.label","Max Allowable Leave Period"},
		{"eIP.MaxAllowablePeriodforAdvanceBedBooking.label","Max Allowable Period for Advance Bed Booking "},
		{"eIP.MaxAllowablePeriodforDischarge.label","Max Allowable Period for Discharge"},
		{"eIP.MaxAllowablePeriodforNormal.label","Max Allowable Period for Normal"},
		{"eIP.MaxAllowablePeriodforTransferOut.label","Max Allowable Period for Transfer Out"},
		{"eIP.MaxAllowedAccompanyingPersons.label","Max. Allowed Accompanying Persons"},
		{"eIP.MaxAllowedPeriodofStayforLodgerAccompanyingPerson.label","Max Allowed Period of Stay for Lodger/Accompanying Person"},
		{"eIP.MaxDailyBooking.label","Max Daily Booking"},
		{"eIP.MaxDailyBookingLimit.label","Max Daily Booking Limit"},
		{"eIP.MaxFemaleDailyBookingLimit.label","Maximum Female Daily Booking Limit"},
		{"eIP.MaximumParameterValue.label","Maximum Parameter Value"},
		{"eIP.MaxMaleDailyBookingLimit.label","Maximum Male Daily Booking Limit"},
		{"eIP.MaxMonthlyBooking.label","Max Monthly Booking"},
		{"eIP.MaxNo.label","Max No"},
		{"eIP.MaxPeriodafterDischargeforCheckinLodger.label","Max Period after Discharge for Check-in Lodger"},
		{"eIP.MaxUnknownDailyBookingLimit.label","Maximum Unknown Daily Booking Limit"},
		{"eIP.MedicalCertificate.label","Medical Certificate"},
		{"eIP.MedicalDetails.label","Medical Details"},
		{"eIP.MedicalEquipment.label","Medical Equipment"},
		{"eIP.MedicalServiceGroup.label","Medical Service Group"},
		{"eIP.MonthlyAdmission.label","Monthly Admission"},
		{"eIP.MonthlyBookingsByMedicalServiceGroup.label","Monthly Bookings By Medical Service Group"},
		{"eIP.MonthlyBookingsByNursingUnit.label","Monthly Bookings By Nursing Unit"},
		{"eIP.MotherIDNo.label","Mother ID No"},
		{"eIP.MRI.label","MRI"},
		{"eIP.MVRegnNo.label","MV Regn No"},
		{"eIP.NasogastricTube.label","Nasogastric Tube"},
		{"eIP.NewMedicine.label","New Medicine"},
		{"eIP.NextNo.label","Next No"},
		{"eIP.Nonoverrideable.label","Non-overrideable"},
		{"eIP.NormalBeds.label","Normal Beds"},
		{"eIP.NormalDefaultBedBlockingPeriod.label","Normal Default Bed Blocking Period"},
		{"eIP.NoShowsCancelledBooking.label","No Shows / Cancelled Booking"},
		{"eIP.NoLayoutExit.label","No Layout Definition Exits"},
		{"eIP.NoofRows.label","No.of Rows"},
		{"eIP.NoofCols.label","No.of Columns"},
		{"eIP.NursingTypeCode.label","Nursing Type Code"},
		{"eIP.NursingUnitBedClass.label","Nursing Unit-Bed Class"},
		{"eIP.NursingUnitDescription.label","Nursing Unit Description"},
		{"eIP.NursingUnitFrom.label","Nursing Unit From"},
		{"eIP.NursingUnitSetup.label","Nursing Unit Setup"},
		{"eIP.NursingUnitType.label","Nursing Unit Type"},
		{"eIP.NursingUnitTypeforMedicalServiceGroup.label","Nursing Unit Type for Medical Service Group"},
		{"eIP.Nutrition.label","Nutrition"},
		{"eIP.OcccupiedDeparted.label","Occupied - Departed"},
		{"eIP.OccupancyDetails.label","Occupancy Details"},
		{"eIP.OccupyingPatientID.label","Occupying Patient ID"},
		{"eIP.OtherAppliancesFixtures.label","Other Appliances/Fixtures"},
		{"eIP.OtherDocuments.label","Other Documents"},
		{"eIP.OthersSpecify.label","Others Specify"},
		{"eIP.OutpatientLocation.label","Outpatient Location"},
		{"eIP.OutstandingAmountexceeds.label","When Outstanding Amount exceeds limit Credit Authorization Required"},
		{"eIP.OutstandingamountLimit.label","Outstanding amount Limit"},
		{"eIP.Overrideable.label","Overrideable"},
		{"eIP.OverstayDays.label","Overstay Days"},
		{"eIP.OverStayPatients.label","Over Stay Patients"},
		{"eIP.PaediatricDetails.label","Paediatric Details"},
		{"eIP.Pamphlets.label","Pamphlets"},
		{"eIP.PastOpenBookings.label","Past Open Bookings"},
		{"eIP.PatientBelongings.label","Patient Belongings"},
		{"eIP.PatientFamilyDetails.label","Patient Family Details"},
		{"eIP.PatientReferral.label","Patient Referral"},
		{"eIP.PatientsNotReturnedfromleave.label","Patients Not Returned from leave"},
		{"eIP.PatientsReAdmittedonthesameday.label","Patients Re Admitted on the same day"},
		{"eIP.PatientTransfer.label","Patient Transfer"},
		{"eIP.PercentageonDepositAmount.label","Percentage on Deposit Amount   "},
		{"eIP.PercentAmount.label","Percent/Amount"},
		{"eIP.PercentAmountIndicator.label","Percent/Amount Indicator"},
		{"eIP.PersonalHygiene.label","Personal Hygiene"},
		{"eIP.PersonID.label","Person ID"},
		{"eIP.PhysicalLocationforNursingUnit.label","Physical Location for Nursing Unit"},
		{"eIP.Physio.label","Physio"},
		{"eIP.POP.label","POP"},
		{"eIP.PopCare.label","Pop Care"},
		{"eIP.PorterageDetails.label","Porterage Details"},
		{"eIP.PorterageReceived.label","Porterage Received"},
		{"eIP.PorterageRemarks.label","Porterage Remarks"},
		{"eIP.PostMortemReqd.label","Post Mortem Reqd"},
		{"eIP.PostMortemRequested.label","Post Mortem Requested"},
		{"eIP.PractitionerDesignation.label","Practitioner Designation"},
		{"eIP.PractitionerforNursingUnit.label","Practitioner for Nursing Unit"},
		{"eIP.Preview.label","Preview"},
		{"eIP.PrefAdmDateTime.label","Preferred Admission Date/Time"},
		{"eIP.PreferredAdmissionDate.label","Preferred Admission Date"},
		{"eIP.PreferredDateTime.label","Preferred Date/Time"},
		{"eIP.PreferredDateTo.label","Preferred Date To"},
		{"eIP.PreferredMonthFrom.label","Preferred Month From"},
		{"eIP.PreferredMonthTo.label","Preferred Month To"},
		{"eIP.PrepareDischargeAdvice.label","Prepare Discharge Advice"},
		{"eIP.PreviousBedDetails.label","Previous Bed Details"},
		{"eIP.PreviousIPStay.label","Previous IP Stay"},
		{"eIP.PreviousOccupancy.label","Previous Occupancy"},
		{"eIP.PrintCertificate.label","Print Certificate"},
		{"eIP.PrintOn.label","Print On"},
		{"eIP.PrintTransferDetails.label","Print Transfer Details"},
		{"eIP.ProcedureSurgeryDateTime.label","Procedure/Surgery Date/Time"},
		{"eIP.Properties.label","Properties"},
		{"eIP.Pseudo.label","Pseudo"},
		{"eIP.PseudoBabyBeds.label","Pseudo/Baby Beds"},
		{"eIP.PseudoBed.label","Pseudo Bed"},
		{"eIP.RangeinDays.label","Range in Days"},
		{"eIP.ReasonforAdmissionBooking.label","Reason for Admission/Booking"},
		{"eIP.ReasonforBlocking.label","Reason for Blocking"},
		{"eIP.ReasonforCancel.label","Reason for Cancel"},
		{"eIP.ReasonforLodgerStay.label","Reason for Lodger Stay"},
		{"eIP.ReasonForLodgerStayCode.label","Reason For Lodger Stay Code"},
		{"eIP.ReasonforStay.label","Reason for Stay"},
		{"eIP.ReasonForSwap.label","Reason For Swap"},
		{"eIP.ReasonforTransfer.label","Reason for Transfer"},
		{"eIP.ReasonforTurnDownAdmission.label","Reason for Turn Down Admission"},
		{"eIP.ReceivedinFull.label","Received in Full"},
		{"eIP.ReceivedPartially.label","Received Partially"},
		{"eIP.ReceivedPartiallyFully.label","Received Partially/Fully"},
		{"eIP.RecordNoShow.label","Record No Show"},
		{"eIP.RecordNoShowDateTime.label","Record No Show Date/Time"},
		{"eIP.RecordNoShowDetails.label","Record No Show Details"},
		{"eIP.RecordProcedureSurgeryDate.label","Record Procedure/Surgery Date"},
		{"eIP.RecordReturn.label","Record Return"},
		{"eIP.RecordReturnDetails.label","Record Return Details"},
		{"eIP.RecordsDocuments.label","Records & Documents"},
		{"eIP.ReferralLetter.label","Referral Letter"},
		{"eIP.ReferredDetails.label","Referred Details"},
		{"eIP.ReferredType.label","Referred Type"},
		{"eIP.RegisterNewBornForIP.label","Register New Born for Inpatient"},
		{"eIP.ReleaseBedonLeave.label","Release Bed on Leave"},
		{"eIP.RemovalOf.label","Removal of"},
		{"eIP.RejectedBy.label","Rejected By"},
		{"eIP.RejectedDate.label","Rejected Date"},		
		{"eIP.RemovedBy.label","Removed By"},
		{"eIP.RenewalOfGatePass.label","Renewal of Gate Pass"},
		{"eIP.RenewalValidityDetails.label","Renewal Validity Details"},
		{"eIP.renewgatepass.label","Renew Gate Pass"},
		{"eIP.ReplyLetter.label","Reply Letter"},
		{"eIP.ReportedTo.label","Reported To"},
		{"eIP.RequestBedClassChange.label","Request Bed Class Change"},
		{"eIP.RequestforBedClassChange.label","Request for Bed Class Change"},
		{"eIP.RequestInpatientConfirmed.label","Request/Inpatient"},
		{"eIP.RequestPlaced.label","Request Placed"},
		{"eIP.RequestTransfer.label","Request Transfer"},
		{"eIP.ReturnedRemarks.label","Returned Remarks"},
		{"eIP.Resolution.label","Resolution"},
		{"eIP.ReviseBookingDetails.label","Revise Booking Details"},
		{"eIP.ReviseLeave.label","Revise Leave"},
		{"eIP.ReviseLeaveDetails.label","Revise Leave Details"},
		{"eIP.reviseperiodfrom.label","Revise Period From"},
		{"eIP.reviseperiodto.label","Revise Period To"},
		{"eIP.RoleEndDate.label","Role End Date"},
		{"eIP.RoleStartDate.label","Role Start Date"},
		{"eIP.RoomCubicleDescription.label","Room/Cubicle Description"},
		{"eIP.RoomCubicleforNursingUnit.label","Room / Cubicle for Nursing Unit"},
		{"eIP.RoundingBillingService.label","Rounding Billing Service"},
		{"eIP.RoundingFee.label","Rounding Fee"},
		{"eIP.Scan.label","Scan"},
		{"eIP.Seizure.label","Seizure"},
		{"eIP.ServicesforNursingUnit.label","Services for Nursing Unit"},
		{"eIP.ServiceTeam.label","Service Team"},
		{"eIP.SetupBillingDtls.label","Setup Billing Dtls"},
		{"eIP.SexSpecInd.label","Sex Spec Ind"},
		{"eIP.SpecialBedType.label","Special Bed Type"},
		{"eIP.SpecialtyforNursingUnit.label","Specialty for Nursing Unit"},
		{"eIP.StayPeriod.label","Stay Period"},
		{"eIP.STO.label","STO"},
		{"eIP.StockMedicine.label","Stock Medicine"},
		{"eIP.StomaCare.label","Stoma Care"},
		{"eIP.StoolColour.label","Stool Colour"},
		{"eIP.StoolFrequency.label","Stool Frequency"},
		{"eIP.SupportiveCare.label","Supportive Care at Home"},
		{"eIP.SwapBeds.label","Swap Beds"},
		{"eIP.SwapPatientBeds.label","Swap Patient Beds"},
		{"eIP.TakeHomeMedicine.label","Take Home Medicine"},
		{"eIP.TakeHomeNewMedicine.label","Take Home/ New Medicine"},
		{"eIP.Takencareby.label","Taken Care by"},
		{"eIP.TeachingLocation.label","Teaching Location"},
		{"eIP.TemporaryLocation.label","Temporary Location"},
		{"eIP.ToBedType.label","To Bed Type"},
		{"eIP.ToBedTypeAmount.label","To Bed Type Amount"},
		{"eIP.ToBedTypeCode.label","To Bed Type Code"},
		{"eIP.ToDateTime.label","To Date/Time"},
		{"eIP.ToDetails.label","To Details"},
		{"eIP.ToptoToe.label","Top to Toe"},
		{"eIP.TotalAdmission.label","Total Admission"},
		{"eIP.TotalBeds.label","Total Beds"},
		{"eIP.ToYear.label","To Year"},
		{"eIP.TransactionDateFrom.label","Transaction Date From"},
		{"eIP.TransactionDateTime.label","Transaction Date/Time"},
		{"eIP.TransactionMonthYear.label","Transaction Month/Year"},
		{"eIP.TransferBookingDate.label","Transfer Booking Date"},
		{"eIP.TransferCharge.label","Transfer Charge"},
		{"eIP.TransferChargeable.label","Transfer Chargeable"},
		{"eIP.TransferChargeDetails.label","Transfer Charge Details"},
		{"eIP.TransferConfirmation.label","Transfer Confirmation"},
		{"eIP.TransferedOut.label","Transferred Out"},
		{"eIP.TransferFunction.label","Transfer Function"},
		{"eIP.TransferInStatus.label","Transfer In Status"},
		{"eIP.TransferPatientIn.label","Transfer Patient In"},
		{"eIP.TransferPatientOut.label","Transfer Patient Out"},
		{"eIP.TransferPriority.label","Transfer Priority"},
		{"eIP.TransferredIn.label","Transferred In"},
		{"eIP.TransferRequest.label","Transfer Request"},
		{"eIP.TransferringPractitioner.label","Transferring Practitioner"},
		{"eIP.TransferServiceCharge.label","Transfer Service Charge"},
		{"eIP.TransferType.label","Transfer Type"},
		{"eIP.TransferTypeCode.label","Transfer Type Code"},
		{"eIP.Transport.label","Transport"},
		{"eIP.TransportArranged.label","Transport Arranged"},
		{"eIP.Tubefeeding.label","Tube feeding"},
		{"eIP.Tubes.label","Tubes"},
		{"eIP.TurnDown.label","Turn Down"},
		{"eIP.UntilDateTime.label","Until Date/Time"},
		{"eIP.UrinaryCatheter.label","Urinary Catheter"},
		{"eIP.ValuablesReturned.label","Valuables Returned"},
		{"eIP.WorkupBillingService.label","Workup Billing Service"},
		{"eIP.WoundCare.label","Wound Care"},
		{"eIP.Xray.label","X-ray"},
		{"eIP.RejoinedFromLeave.label","Rejoined from Leave"},
		{"eIP.Transferred.label","Transferred"},
		{"eIP.RecordInpatientLeaveAbscond.label","Record Inpatient Leave/Abscond"},
		{"eIP.EncounterLocation.label","Encounter Location"},
		{"eIP.ServiceSubService.label","service / subservice"},
		{"eIP.LastAdmissionDateTime.label","Last Admission Date/Time"},
		{"eIP.LastDischargeDateTime.label","Last Discharge Date/Time"},
		{"eIP.RequestedForRecordDocument.label","Requested For Record Document"},
		{"eIP.RequestingNursingUnit.label","Requesting Nursing Unit"},
		{"eIP.AdmittedPatientIntoBuilding.label","Admitted Patient Into Building"},
		{"eIP.BedAlloter.label","Bed Alloter"},
		{"eIP.FirstPortionForDoctor.label","1st Portion For Doctor"},
		{"eIP.InvestigationHappenedBeforeAdmission.label","Investigation Happened Before Admission"},
		{"eIP.PatientRelativeContactPlace.label","Patient/Relative's Contact Place"},
		{"eIP.SecondPortionForAdmissionCenterStaff.label","2nd Portion For Admission Center / Staff"},
		{"eIP.SpecialRequirement.label","Special Requirement"},
		{"eIP.ThirdPortionForPatient.label","3rd Portion For Patient"},
		{"eIP.NotSpecified.label","Not Specified"},
		{"eIP.MaximumAllowed.label","Maximum Allowed"},
		{"eIP.AdmitableDate.label","Admittable Date"},
		{"eIP.CurrentlyPatientIsAt.label","Currently patient is at" },
		{"eIP.Faculty.label","Faculty"},
		{"eIP.SpecialMulBedRoom.label","Special multiple bed room"},
		{"eIP.SpecialPvtRoom.label","Special private room"},
		{"eIP.HealthDistrict.label","Health District"},
		{"eIP.InfoRequestor.label","Info/Request Receiver"},
		{"eIP.OtherIdentificationNo.label","Other Identification No"},
		{"eIP.FamilyHealthOfficer.label","Family Health Officer"},
		{"eIP.GravidaParity.label","Gravida/parity"},
		{"eIP.MatDeathInvOfficer.label","Maternal Death Investigation Officer"},
		{"eIP.NationalRegnNo.label","National Registration Number"},
		{"eIP.StateHealthDepartment.label","State Health Department"},
		{"eIP.AbscondFromDateTime.label","Abscond from Date/Time"} ,
		{"eIP.ClinicalInformation.label","Clinical Information"} ,
		{"eIP.RequestedFor.label","Requested For "} ,
		{"eIP.ActiveProblemsDiagnosis.label","Active Problems/Diagnosis"},
		{"eIP.ClinicalSummary.label","Clinical Summary"},
		{"eIP.LastAdmissionDate.label","Last Admission Date"},
		{"eIP.LastAdmissionLocation.label","Last Admission Location"},
		{"eIP.NewProblemsDiagnosis.label","New Problems/Diagnosis"},
		{"eIP.Stamp.label","stamp"},
		{"eIP.GatePassValidity","GatePass Validity"},
		{"eIP.AdmittedForTreatment.label","Admitted For Treatment"},
		{"eIP.ScheduledOperationDate.label","Scheduled Operation Date"},
		{"eIP.ScheduledSpecialCheckupDate.label","Scheduled Special Checkup Date"},
		{"eIP.ContactPlaceOfDoctor.label","Contact Place Of Doctor"},
		{"eIP.SocialSecurity.label","Social Security"},
		{"eIP.LifeInsurance.label","Life Insurance"},
		{"eIP.SelfPayment.label","Self Payment"},
		{"eIP.DateAssignedForOperation.label","Date Assigned For Operation"},
		{"eIP.HospitalAdmissionCenter.label","Hospital Admission Center"},
		{"eIP.IncaseOfQuestionOrChangeRequest.label","Incase Of Question Or Change Request"},
		{"eIP.UnConfirmed.label","UnConfirmed"},
		{"eIP.EstimateCost.label","Estimate Cost"},
		{"eIP.OverReimbursable.label","Over Reimbursable Cost"},
		{"eIP.LeavePass.label","Leave Pass"},
		{"eIP.ValuableBelongTo.label","Valuable belong to"},
		{"eIP.Pieces.label.label","Pieces"},
		{"eIP.LastUpdateFileLocation.label","Last Update File Location"},
		{"eIP.LocationPriorToLastUpdate.label","Location Prior to Last Update"},
		{"eIP.PatientGender.label","Patient Gender"},
		{"eIP.GenderType.label","Gender Type"},
		{"eIP.BedGender.label","Bed Gender"},
		{"eIP.BedAvailablibilityDate.label","Bed Availability Date"},
		{"eIP.ReserveBedDetails.label","Reserve Bed Details"},
		{"eIP.ReserveBed.label","Reserve Bed"},
		{"eIP.ReasonforReserveBed.label","Reason for Reserve Bed"},
		{"eIP.ReservedBeds.label","Reserved Beds"},
		{"eIP.ReserveBedWhileTransfer.label","Reserve Bed While Transfer"},
		{"eIP.MultipleBookingforPatients.label","Multiple Booking for Patients"},
		{"eIP.ViewOpenBookings.label","View Open Bookings"},
		{"eIP.MotherBedNo.label","Mother Bed No"},
		{"eIP.IncludeReservedBeds.label","Include Reserved Beds"},
		{"eIP.AssignPractitionerBedsideReferral.label","Assign Practitioner for Bedside Referral"},
		{"eIP.StatisticsBy.label","Statistics By"},
		{"eIP.ChangeInpatientService.label","Change Inpatient Service"},
		{"eIP.BookedOverrideableConfirmed.label","Booked Overrideable Confirmed"},
		{"eIP.BookedOverrideableUnConfirmed.label","Booked Overrideable UnConfirmed"},
		{"eIP.BookedNonOverrideableConfirmed.label","Booked Non-Overrideable Confirmed"},
		{"eIP.BookedNonOverrideableUnConfirmed.label","Booked Non-Overrideable UnConfirmed"},
		{"eIP.PreOpPreparationDays.label","Pre-Op Preparation Days"},
		{"eIP.BlockBedBasedon.label","Block Bed based on"},
		{"eIP.CancelDischargeApplicable.label","Cancel Discharge Applicable"},
		{"eIP.CancelDischargePatient.label","Cancel Discharge Patient"},
		{"eIP.AbortCancelDischarge.label","Abort Cancel Discharge"},
		{"eIP.BookingRemarks.label","Booking Remarks"},
		{"eIP.InvokeAdmFromNewBornReg.label","Invoke Admission from New Born Registration"},
		{"eIP.DischargeStatus.label","Discharge Status"},
		{"eIP.CompleteRecovery.label","Complete Recovery"},
		{"eIP.PartialRecovery.label","Partial Recovery"},
		{"eIP.StatusQuo.label","Status Quo"},
		{"eIP.ConditionWorse.label","Condition Worse"},
		{"eIP.DischargeStatusIndicator.label","Discharge Status Indicator"},
		{"eIP.Deceasedperiod.label","Deceased Period"},
		{"eIP.CensusDateRange.label","Census Date Range"},
		{"eIP.PercentageofOccupancy.label","Percentage of Occupancy"},
		{"eIP.AllowMultipleBedsForReserving.label","Allow Multiple Beds For Reserving"},
		{"eIP.AllowBookingoccupiedbedswithoutEDD.label","Allow Booking for Current Occupied Beds without EDD"},
		{"eIP.AllowBookingoccupiedbedswithEDD.label","Allow Booking for Current Occupied Beds with EDD"},
		{"eIP.TypeOfBooking.label","Type of Booking"},
		{"eIP.IndicateFutureBooking.label","Indicate Future Booking"},
		{"eIP.NumberofdaysBefore.label","Number of Days Before"},
		{"eIP.ConsiderEDDBeforeStop.label","Consider EDD Before Stop"},
		{"eIP.ActiononBookingadmission.label","Action on Booking/Admission"},
		{"eIP.ConfirmedOverridable.label","Confirmed Overridable"},
		{"eIP.UnConfirmedOverridable.label","Un-Confirmed Overridable"},
		{"eIP.ConfirmedNonOverridable.label","Confirmed Non-Overridable"},
		{"eIP.UnConfirmedNonOverridable.label","Un-Confirmed Non-Overridable"},
		{"eIP.GrcprdforAsgnBed.label","Grace Period for Assign Bed/Mark Arrival"},
		{"eIP.ReasonforChangeAdmission.label","Reason for Change Admission"},
		{"eIP.CurrentAdmissionDetails.label","Current Admission Details"},
		{"eIP.ChangeAdmissionDetails.label","Change Admission Details"},
		{"eIP.AdmissionAuditDetails.label","Admission Audit Details"},
		{"eIP.modifieddatefrom.label","Modified Date From"},
		{"eIP.modifieddateto.label","Modified Date To"},
		{"eIP.ReasonForModification.label","Reason For Modification"},
		{"eIP.BookingRefList.label","Booking Referrence List"},
		{"eIP.InvokeDthReginDisAdv.label","Allow invoking Maintain Death Register in Prepare Discharge Advice"},
		{"eIP.RevisonReason.label","Revision Reason"},
		{"eIP.DisplayNoShowstatusinConfirmBookingAfter.label","Display No Show status in Confirm booking after "},//Added for Bru-HIMS-CRF-153 [IN:030273] by Srinivas
		// Reports purpose added these Lables.

		    {"eIP.Complement.label","Complement"},
			{"eIP.OccupancyRate.label","Occupancy Rate"},
			{"eIP.Pref.label","Pref"},
			{"eIP.Proc.label","Proc"},
			{"eIP.Occupancy.label","Occupancy"},
			{"eIP.Stay.label","Stay"},
			{"eIP.Turnover.label","Turnover"},
			{"eIP.OneDayStays.label","One Day Stays"},
			{"eIP.DischIncldeaths.label","Disch. (Incl deaths)"},
			{"eIP.BedComp.label","Bed Comp"},
			{"eIP.Adm.label","Adm"},
			{"eIP.TfrIn.label","Tfr In"},
			{"eIP.TfrOut.label","Tfr Out"},
			{"eIP.TotOneDayStay.label","Tot One Day Stay"},
			{"eIP.NoOfAdmissions.label","No Of  Admissions"},
			{"eIP.BkgLstRefNo.label","Bkg Lst Ref No"},
			{"eIP.TotPatientDays.label","Tot Patient Days"},
			{"eIP.PercentAvgOccup.label","Percent Avg Occup."},
			{"eIP.Labour.label","Labour"},
			{"eIP.Full.label","Full"},
			{"eIP.Jan.label","Jan"},
			{"eIP.Feb.label","Feb"},
			{"eIP.Mar.label","Mar"},
			{"eIP.Apr.label","Apr"},
			{"eIP.Jun.label","Jun"},
			{"eIP.Jul.label","Jul"},
			{"eIP.Aug.label","Aug"},
			{"eIP.Sep.label","Sep"},
			{"eIP.Oct.label","Oct"},
			{"eIP.Nov.label","Nov"},
			{"eIP.May.label","May"},
			{"eIP.Dec.label","Dec"},
			{"eIP.DaysOverstayed.label","Days Overstayed"},
			{"eIP.RefType.label","Ref Type"},
			{"eIP.RefLocn.label","Ref Locn"},
			{"eIP.RefSplty.label","Ref Splty"},
			{"eIP.RefPract.label","Ref Pract"},
			{"eIP.Occup.label","Occup"},
			{"eIP.morbidity&mortality.label","Morbidity & Mortality"},
			{"eIP.mortality.label","Mortality"},
			{"eIP.deathsbynationality.label","Deaths by Nationality"},
			{"eIP.externalcauseofdeath.label","External Cause of Death"},
			{"eIP.agerange.label","Age Range"},
			{"eIP.Reasonforbooking.label","Reason For Booking"},
			{"eIP.Reasonforrevision.label","Reason For Revision"},
			{"eIP.IntraHospitalBooking.label","Intra Hospital Booking"},
			{"eIP.ExternalHospitalBooking.label","External Hospital Booking"},
			{"eIP.AdmnMonth.label","Admn. Month"},
			{"eIP.AverageInPatientsPerDay.label","Average In-Patients Per Day"},
			{"eIP.BedCapacity.label","Bed Capacity"},
			{"eIP.BedComplement.label","Bed Complement"},
			{"eIP.BedOccupancyRate.label","Bed Occupancy Rate"},
			{"eIP.Deaths.label","Deaths"},
			{"eIP.DischargeMonth.label","Discharge Month"},
			{"eIP.Discharges.label","Discharges"},
			{"eIP.Diseases.label","Diseases"},
			{"eIP.ExcludingDeaths.label","Excluding Deaths"},
			{"eIP.HospitalAdmissions.label","Hospital Admissions"},
			{"eIP.HospitalDischarges.label","Hospital Discharges"},
			{"eIP.HospitalStatistics.label","Hospital Statistics"},
			{"eIP.IncludingDeaths.label","Including Deaths"},
			{"eIP.IPBDTNAT_REPORT_TEXT1.label","Discharges (Inc Dth) (Inc Maternal & Neo-Natal) By Age & Sex"},
			{"eIP.MeanLengthofStay.label","Mean Length of Stay"},
			{"eIP.OfficialBedStrength.label","Official Bed Strength"},
			{"eIP.TotalBedCountDays.label","Total Bed Count Days"},
			{"eIP.TotalInPatientServiceDays.label","Total In-Patient Service Days"},
			{"eIP.TotalLengthofStay.label","Total Length of Stay"},
			{"eIP.RequestingClinic.label","Requesting Clinic"},
			{"eIP.RequestingName.label","Requesting Name"},
			{"eIP.Blue.label","Blue"},
			{"eIP.White.label","White"},
			{"eIP.Red.label","Red"},
			{"eIP.PatientWristBandLabel.label","Patient Wrist Band Label"},
			{"eIP.ExcludeNonPDA.label","Patients With Discharge Advice"},
			{"eIP.DsplyDisPatLst.label","Display Discharge Patient List"},
			{"eIP.AllPatients.label","All Patients"},
			{"eIP.OnlyPatPDA.label","Only Patient with Discharge Advice"},
			{"eIP.DischargebillPrepared.label","Discharge Bill Prepared"},
			{"eIP.CheckForPendingOrdersBerforeDischargeAdvice.label","Check for Pending Orders before Discharge Advice"},
			{"eIP.IfOrdersArePending.label","If Orders are Pending"},
			{"eIP.DonotallowdischargeAdvice.label","Do not Allow Discharge Advice"},
			{"eIP.AllowDischargeAdvice.label","Allow Discharge Advice"},
			{"eIP.SlNo.label","Sl.No"},
			{"eIP.ReportName.label","Report Name"},
			{"eIP.Count.label","Count"},
			{"eIP.TotNoInPat.label","Total no of In-Patients"},
			{"eIP.TotNoForPat.label","Total no of Foreign Patients"},
			{"eIP.TotNoDisAdvPat.label","Total no of Patients Discharge Advice Prepared"},
			{"eIP.TotNoCorPat.label","Total no of Corporate Patients"},
			{"eIP.TotNoInsPat.label","Total no of Insurance Patients"},
			{"eIP.TotNoFrePat.label","Total no of Free Case Patients"},
			{"eIP.TotNoCasPat.label","Total no of Cash Patients"},
			{"eIP.ConsentText.label","Consent Text"},
			{"eIP.FutureAppointments.label","View Future Bookings/Appointments"},
			{"eIP.inpatientbookings.label","Inpatient Bookings"},
			{"eIP.CheckForPendingOrdersBerforeDischarge.label","Check for Pending Orders before Discharge"},
			{"eIP.Donotallowdischarge.label","Do not Allow Discharge"},
			{"eIP.AllowDischarge.label","Allow Discharge"},
			{"eIP.AllowReasonForLateDischarge.label","Enable Reason For Late Discharge"},
			{"eIP.ReasonForLateDischarge.label","Reason For Late Discharge"},
			{"eIP.Mandatory.label","Mandatory"},
			{"eIP.NotMandatory.label","Non Mandatory"},
			{"eIP.otherReason.label","Other Reason"},
			{"eIP.CancelledDateTime.label","Cancelled Date/Time"},
			{"eIP.AlertReadmitPatient.label","Alert Re-admission of the Patient Within"},
			{"eIP.ConfigureFloor.label","Configure Floor"},
			{"eIP.ConfigureRooms.label","Configure Rooms"},
			{"eIP.ConfigureBeds.label","Configure Beds"},
			{"eIP.ConfigureColors.label","Configure Bed Dimension"},
			{"eIP.SurgeryOrder.label","Surgery Order"},
			{"eIP.SurgeryDate.label","Surgery Date"},
			{"eIP.InpatientDetails.label","Inpatient Details"},
			{"eIP.GeneralDetails.label","General Details"},
			{"eIP.DefaultReferringPractitioner.label","Default Referring Practitioner in Bedside Referral"},
            {"eIP.LoginPractitioner.label","Login Practitioner"},	//this line Added for this CRF Bru-HIMS-CRF-354
            {"eIP.TransferWODelink.label","Allow transfer without baby delink"},//Added for the CRF - HSA-CRF-0035
			{"eIP.PreDischargeApplicable.label","Enable Initiate Pre-Discharge"},//Added for the CRF - KDAH-CRF-0104 
			{"eIP.PreDischargeInitiated.label","Pre-Discharge Initiated"},//Added for the CRF - KDAH-CRF-0104
			// this line added for Graphical Bed Management sub module
            {"eIP.ArrivedDateTime.label","Arrived Date/Time"},
			{"eIP.ReasonForAdmMandatory.label","Reason For Admission Mandatory"},//Added for MMS-QH-CRF-0144
			{"eIP.Readmissionwithin.label","Readmission within"},//Added for MMS-QH-CRF-0088
			{"eIP.Daysofdischarge.label","Days of discharge"},//Added for MMS-QH-CRF-0088
			//Added for this CRF HSA-CRF-146.1
			{"eIP.AllowMultipleBedsideReview.label","Allow Multiple Bedside Referral Review"},
			{"eIP.SeenandTobeReviewedAgain.label","Seen and To Be Reviewed Again"},
			{"eIP.SeenandClosed.label","Seen and Closed"},
			{"eIP.WeightOnAdmission.label","Weight on Admission"},/*Added by Dharma on Oct 17th against HSA-CRF-0181 [IN:049541]*/
			{"eIP.History.label","History"}, //Added for this CRF HSA-CRF-0146
			{"eIP.PerformedBy.label","Performed By"}, //Added for this CRF HSA-CRF-0146
			{"eIP.Performed.label","Performed Date Time"}, //Added for this CRF HSA-CRF-0146
			{"eIP.NotSeenandClosed.label","Not Seen and Closed"}, //Added for this CRF HSA-CRF-263.1
			{"eIP.RestrictReserveBedinIntraWardTrnsfr.label","Restrict Reserving for Intra-Ward Transfer"},
			{"eIP.EnableRecordingofReferralLetterNotewithReferralRequest.label","Enable Recording of Referral Letter Note with Referral Request"},//Added by Rameswar on 29-Jan-16 for ML-MMOH-CRF-0362
			{"eIP.CheckInDate.label","Check-In Date"},//Added by Sangeetha against GDOH-CRF-0076 
			{"eIP.ReleaseBookedBedForAdmission.label","Release Booked Bed if Admitted into Different Bed"},//Added by Rameswar PMG2016-CRF-0002 on  23rd Aug 2016
			{"eIP.RestrictDischargeAdviceForPendingReturns.label","Restrict Discharge Advice if Return Medication is pending"},//Added by Thamizh selvi on 7th Nov 2016 against GHL-CRF-0412.2
			{"eIP.RemovedDoneby.label","Removed/Done by"},//Added by Ashwini on 30-Jan-2017 for ML-MMOH-CRF-0620
			{"eIP.PlannedAdmission.label","Planned Admission"},//Added by Ashwini on 31-Jan-2017 for ML-MMOH-CRF-0620
			{"eIP.DateOfPlannedAdmission.label","Date of Planned Admission"},//Added by Ashwini on 31-Jan-2017 for ML-MMOH-CRF-0620
			
			/*Added by Thamizh selvi on 5th May 2017 for ML-MMOH-CRF-0617 Start*/
			{"eIP.InformedDtlsMand.label","Make Informed details mandatory"},
			{"eIP.AutoCnrmTfrReq.label","Auto Confirmation request for transfer"},
			{"eIP.InformedName.label","Informed Name"},
			/*End*/
			{"eIP.CensusBed.label","Census Bed"}, //Added by Mano on 15-5-2017 for CRF-GHL-0418
			{"eIP.DispBedClsChangeRec.label","Display Bed Class change Authorization details in Current Encounter Details and Admission History"}, //Added by Thamizh selvi on 10th Nov 2017 against ML-MMOH-CRF-0866
			{"eIP.BlockedBy.label","Blocked By"}, //Added by Mano against ML-MMOH-CRF-1052
			{"eIP.PsychiatryForm.label","PF"},//Added by Ashwini on 22-Jan-2018 for ML-MMOH-CRF-0779
			{"eIP.AllowUserToModifyDischargeTypeStatus.label","Modify Discharge Type/Status"}, // added by mujafar for ML-MMOH-CRF-0659
			{"eIP.Keep.label","Keep"}, //Added by Ashwini on 25-Apr-2018 for ML-MMOH-CRF-1142
			{"eIP.RestrictDischargePatientIfBTOrdersPending.label","Restrict Discharge Patient if BT orders are pending"},//Added by Shanmukh on 22nd-MAY-2018 for ML-MMOH-CRF-1135
			//Added by Dharma on 23rd May 2018 against ML-MMOH-CRF-0898 [IN:064757] Start
			{"eIP.RestrictTransferForUnfinalizedNewbornRecords.label","Restrict Transfer for Unfinalized New Born Records"},
			{"eIP.AssistedBy.label","Assisted By"},
			{"eIP.WitnessedBy1.label","Witnessed By 1"},
			{"eIP.WitnessedBy2.label","Witnessed By 2"},
			//Added by Dharma on 23rd May 2018 against ML-MMOH-CRF-0898 [IN:064757] End
			{"eIP.ItemOnLoan.label","Items on Loan"}, //Added by Ashwini on 25-Apr-2018 for ML-MMOH-CRF-1142
			{"eIP.MedicalCertificateNumber.label","Medical Certificate Number (MC)"}, //Added by Ashwini on 02-Aug-2018 for ML-MMOH-CRF-1048
			{"eIP.ValidateNatIDDurIPAdmsn.label","Validate existence of National ID during IP Admission"}, //Added by Ashwini on 06-Mar-2019 for MO-CRF-20148
			{"eIP.RestrictDischargeAdviceIfSaleReturnPending.label","Restrict Discharge Advice if Sale/Issue or Sale Return pending to be finalized"},
			{"eIP.RestrictIfOTRecordsPending.label","Restrict, if OT Record Surgical Note / Operation / Procedure are pending"},
			{"eIP.Allowgatepassinpredisadvice.label","Allow Gate Pass entry in Prepare Discharge Advice"}, // added by mujafar for MO-CRF-20157
			{"eIP.EnableDischargeDiagInPrepareDischargeAdvice.label","Enable Discharge Diagnosis in Prepare Discharge Advice"}, //ADDED BY SUJI KEERTHI ON 24-MAR-2020 FOR MOHE-CRF-0014
			{"eIP.HeightOnAdmission.label","Height on Admission"},// Added by Kamatchi S for ML-MMOH-CRF-1527 on 22-JUN-2020
			{"eIP.EnableHeightandBmiforPatienClass.label","Enable Height on Admission and BMI for Patient Class"},// Added by Kamatchi S for ML-MMOH-CRF-1527 on 22-JUN-2020
			{"eIP.DaycareandInpatient.label","Inpatient and Day care"},// Added by Kamatchi S for ML-MMOH-CRF-1527 on 22-JUN-2020
			{"eIP.OtherHospital.label","OtherHospital"},// Added by Kamatchi S for ML-MMOH-CRF-1527 on 22-JUN-2020
			{"eIP.DischargeTo.label","Discharge To"},// Added by Kamatchi S for ML-MMOH-CRF-1527 on 22-JUN-2020
			{"eIP.VacantNormalBeds.label","Vacant Nomal Beds"}, //Added By Suji Keerthi for MOHE-CRF-0038 US002
            {"eIP.OccupiedNormalBeds.label","Occupied Normal Beds"}, //Added By Suji Keerthi for MOHE-CRF-0038 US002
            {"eIP.VacantPseudoBabyBeds.label","Vacant Pseudo/Baby Beds"}, //Added By Suji Keerthi for MOHE-CRF-0038 US002
            {"eIP.OccupiedPseudoBabyBeds.label","Occupied Pseudo/Baby Beds"}, //Added By Suji Keerthi for MOHE-CRF-0038 US002
            {"eIP.Readmission.label","Readmission(s)"},
            // Added by lakshmanan for ML-MMOH-CRF-1972 US007 on 07/07/2023 start 
            {"eIP.ReasonForCancellation.label","Reason For Cancellation"}, 
            {"eIP.CancelledBy.label","Cancelled By"}, 
            {"eIP.CancelForAdmission.label","Cancel For Admission"},  
            // Added by lakshmanan for ML-MMOH-CRF-1972 US007 on 07/07/2023 end 
			{"eIP.AdmissionApprovalDtls.label","Admission Approval Details"}, //Added by Suji Keerthi for MMS-DM-CRF-0191 ON DEC 2021  
			{"eIP.CoderClearance.label","Coder Clearance"}, //Maheshwaran K added for TH-KW-CRF-0141.1
			{"eIP.DischargeBill.label","Discharge Bill"}, //Maheshwaran K added for TH-KW-CRF-0141.1
			{"eIP.DischargeClearance.label","Discharge Clearance"},  //Maheshwaran K added for TH-KW-CRF-0141.1
			{"eIP.DischargeAdvicePending.label","Discharge Advice Pending"},  //Maheshwaran K added for TH-KW-CRF-0141.1
			{"eIP.DischargeAdvicePrepared.label","Discharge Advice Prepared"},  //Maheshwaran K added for TH-KW-CRF-0141.1
			{"eIP.PayementStatus.label","Payment Status"}, // Added by Lakshmanan ML-MMOH-CRF-1611
			{"eIP.AllowRegOfNewRefInIPAdmFunc.label","Allow Registration of New Referrals in Inpatient Admission Function"} // Added by Kamatchi S for MOHE-CRF-0154
	};

}






