/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eIP.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eIP.AbortCancel.label","中止�?�消"},
		{"eIP.AbortCancellation.label","中止�?�消"},
		{"eIP.AbortDischarge.label","中止出院"},
		{"eIP.AbortRevision.label","中止修订"},
		{"eIP.AbortSwap.label","中止互�?�"},
		{"eIP.Absconded.label","潜逃"},
		{"eIP.AbscondedDetails.label","潜逃详情"},
		{"eIP.AbscondedFrom.label","从潜逃"},
		{"eIP.AbscondedRemarks.label","潜逃备注"},
		{"eIP.Absconding.label","潜逃"},
		{"eIP.AbscondingDate.label","潜逃日期"},
		{"eIP.AbscondingDateTime.label","潜逃的日期/时间"},
		{"eIP.AbscondingDetails.label","潜逃详情"},
		{"eIP.Accident.label","事故"},
		{"eIP.AccompanyingPerson.label","陪�?�人员"},
		{"eIP.AccompanyingPersonDetails.label","陪�?�的人细节"},
		{"eIP.AccompanyingPersonID.label","陪�?�的人编�?�"},
		{"eIP.AccompanyingPersonName.label","陪�?�的人的�??字"},
		{"eIP.AccompanyingPersons.label","陪�?�人员"},
		{"eIP.AcctDeptService.label","会计部/�?务"},
//		{"eIP.ActiononExceedingMaxLeave.label","Action on Exceeding Max Leave"},
		{"eIP.ActiveBooking.label","积�?预订"},
		{"eIP.Activity.label","活动"},
		{"eIP.ActivityReason.label","活动的原因"},
		{"eIP.AdditionalDepositAmount.label","附加存款金�?"},
		{"eIP.AdditionalDepositRequired.label","需�?�?外存款"},
		{"eIP.AdditionalDischargeDetails.label","附加出院细节"},
		{"eIP.AdditionalServices.label","附加�?务"},
		{"eIP.AdmDateFrom.label","登记日期"},
		{"eIP.AdmDateTo.label","登记日期"},
		{"eIP.AdmissionFor.label","登记"},
		{"eIP.AdmissionHistory.label","入院历�?�"},
		{"eIP.Admissions.label","入院"},
		{"eIP.AdmissionTypeCode.label","入院类型代�?"},
		{"eIP.AdmissionWithBed.label","有床入院"},
		{"eIP.AdmissionWithoutBed.label","无床入院"},
//		{"eIP.AdmissionWorkupChargeFee.label","Admission Workup Charge Fee"},
		{"eIP.AdmissionYear.label","入院年份"},
		{"eIP.AdmittedDate.label","入院日期"},
		{"eIP.Admitting.label","承认"},
		{"eIP.AdmittingPractitioner.label","�?�纳从业人员"},
		{"eIP.AdmMonthFrom.label","入院月份"},
//		{"eIP.AdviceGivenTo.label","Advice Given to"},
		{"eIP.AdviceonContcare.label","给病人�?续的关注"},
		{"eIP.AgeGender.label","年龄/性别"},
		{"eIP.AgeGroupBedClass.label","床�?类型分类"},
//		{"eIP.AllowablePeriodforIssue.label","Allowable Period for Issue"},
		{"eIP.AllowBedSwap.label","�?许床互�?�"},
		{"eIP.AllowBookingforUnregisteredPatients.label","�?许未登记的病人预订"},
		{"eIP.AllowedAdmission.label","�?许入院"},
		{"eIP.AllowedBooking.label","�?许预订"},
//		{"eIP.AllowLeaveCancellationWithin.label","Allow Leave Cancellation Within"},
//		{"eIP.AllowNewbornRegn.label","Allow Newborn Regn"},
//		{"eIP.AllowPatientCheckin.label","Allow Patient Check-in"},
/*		{"eIP.AllowPseudoBeds.label","Allow Pseudo Beds"},
		{"eIP.AllowTransferWOReq.label","Allow Transfer W/O Request"},
		{"eIP.AllSPLTY.label","All Specialities"},
		{"eIP.AmbulanceReqdDateTime.label","Ambulance Reqd Date/Time"},
		{"eIP.AmendInpatientLeave.label","Amend Inpatient Leave"},
		{"eIP.AnalDilatation.label","Anal Dilatation"},
		{"eIP.ApplFixturesDocuments.label","Appl./Fixtures Documents"},
		{"eIP.assignbedmarkpatientarrival.label","Assign Bed / Mark Patient Arrival"},
		{"eIP.Assisting.label","Assisting"},
		{"eIP.Attendant.label","Attendant"},
		{"eIP.AuthorizationDateTime.label","Authorization Date/Time"},
		{"eIP.AuthorizedPractitioner.label","Authorized Practitioner"},*/
		{"eIP.AutoFileTransfer.label","自动档传输"},
		{"eIP.AvailNursUnit.label","�?许护�?�级别"},
		{"eIP.BabiesBeds.label","婴儿床"},
		{"eIP.BabyDetails.label","婴儿明细"},
		{"eIP.BabyToMotherDetails.label","婴儿到�?亲的细节"},
		{"eIP.BedAllocationDateTime.label","床�?分�?的日期/时间"},
		{"eIP.BedAvailabilityChart.label","床�?�?�用性图表"},
		{"eIP.BedBlockDetails.label","床�?�?定细节"},
		{"eIP.BedBlocking.label","床�?�?定"},
		{"eIP.BedBlockingPeriod.label","床�?�?定期间"},
		{"eIP.BedBlockleduntil.label","床�?�?定直到"},
		{"eIP.BedBookingSerialControl.label","床�?预订�?列控制"},
		{"eIP.BedCharge.label","床�?费用"},
		{"eIP.BedClassCode.label","床�?分类"},
		{"eIP.BedClassCodeFrom.label","床类代�?"},
		{"eIP.BedClassification.label","床�?分类"},
		{"eIP.BedDetails.label","床�?明细"},
		{"eIP.BedOccupancyByNursingUnit.label","病床护�?�级别"},
		{"eIP.BedOccupancybySpecialty.label","病床所属科别"},
		{"eIP.Beds.label","床�?"},
		{"eIP.BedsBlocked.label","床�?被�?定"},
//		{"eIP.Bedside.label","Bedside"},
//		{"eIP.BedsideReferralSeenDate.label","Bedside Referral Seen Date"},
		{"eIP.BedsOccupied.label","�?�床"},
		{"eIP.BedsVacant.label","空床"},
		{"eIP.BedTypeCode.label","床�?类型代�?"},
		{"eIP.BelongingsReturned.label","物�?返回"},
		{"eIP.BillingParameter.label","结算�?�数"},
		{"eIP.BillType.label","账�?�类型"},
//		{"eIP.BlackListed.label","Black Listed"},
		{"eIP.BlockBed.label","�?定床�?"},
		{"eIP.BlockBedDetails.label","床�?�?定细节"},
//		{"eIP.BlockBedonDischarge.label","Block Bed on Discharge"},
		{"eIP.BlockedBedNo.label","�?定床�?员"},
		{"eIP.BlockedFrom.label","�?�?"},
		{"eIP.BlockedFromDate.label","�?�?日期"},
		{"eIP.BlockedRemarks.label","�?�?备注"},
		{"eIP.BlockedThrough.label","通过�?�?"},
		{"eIP.BlockedType.label","�?�?类型"},
		{"eIP.BlockingDetail.label","阻断详情"},
		{"eIP.BlockingFunction.label","阻断功能"},
		{"eIP.BlockingPeriod.label","�?闭期"},
		{"eIP.BlockingRefNo.label","�?闭�?�数�?�"},
		{"eIP.BlockingType.label","�?�?类型"},
		{"eIP.BlockingTypeCode.label","�?�?类型代�?"},
		{"eIP.BlockPeriod.label","�?�?期"},
		{"eIP.BlockType.label","�?�类型"},
//		{"eIP.BloodandMedication.label","Blood and Medication"},
//		{"eIP.BodyReleasedtoMortuary.label","Body Released to Mortuary"},
//		{"eIP.BodyReleasedtoMortuaryDate.label","Body Released to Mortuary Date"},
		{"eIP.BookedBlocked.label","预订/�?�?"},
		{"eIP.BookedFrom.label","从预订"},
		{"eIP.BookedUntil.label","预订直到"},
		{"eIP.BookingAdmissionDetails.label","预订入院细节"},
		{"eIP.BookingDateTime.label","预订的日期/时间"},
		{"eIP.BookingDetails.label","预订详情"},
		{"eIP.BookingLimitByAgeGroupBedClass.label","预定�?制年龄层次的床�?类型"},
		{"eIP.BookingLimitByNursingUnitBedClass.label","预订�?制护�?�级别的床�?类型"},
		{"eIP.BookingorReferral.label","预订或查询"},
		{"eIP.BookingRef.label","预订编�?�"},
		{"eIP.BookingReferenceLookup.label","预订�?�考查询"},
//		{"eIP.BookingRelatedSetup.label","Booking Related Setup"},
		{"eIP.Bookings.label","预订"},
		{"eIP.BookingSerialDetails.label","预订系列明细"},
		{"eIP.BookingType.label","预订类型"},
		{"eIP.BreastFeeding.label","�?乳喂养"},
		{"eIP.BreastFeedingExpressedbreastmilk.label","�?乳喂养/?"},
		{"eIP.ByNursingUnit.label","护�?�级别"},
		{"eIP.ByPractitioner.label","医生"},
		{"eIP.CalculatedAmount.label","计算金�?"},
		{"eIP.CalculatePercentageOn.label","关于计算百分比"},
		{"eIP.CancelLeave.label","�?�消休�?�"},
		{"eIP.CancelLeaveDetails.label","�?�消休�?�细节"},
		{"eIP.CancelledAdmission.label","�?�消入院"},
		{"eIP.CancelledByID.label","�?�消了编�?�"},
		{"eIP.CancelledDate.label","作废日期"},
		{"eIP.CancelledDateTo.label","作废日期"},
		{"eIP.CancelledReason.label","�?�消的原因"},
		{"eIP.CancelledRequest.label","�?�消请求"},
		{"eIP.CancelledTransferOut.label","�?�消转出"},
		{"eIP.CancelReasonDescription.label","�?�消的原因说明"},
		{"eIP.CancelRequestForTransfer.label","�?�消请求转让"},
		{"eIP.CancelTransferPatientOut.label","�?�消了转移病人"},
		{"eIP.CareofCatheters.label","导管的护�?�"},
		{"eIP.CareofEye.label","眼部护�?�"},
		{"eIP.CareofPOP.label","�?久性有机污染物的护�?�"},
		{"eIP.CareOfPretermbaby.label","护�?�早产婴儿"},
		{"eIP.CareofSkin.label","皮肤护�?�"},
		{"eIP.CareOfStoma.label","护�?�气孔"},
		{"eIP.CareofTube.label","护�?�管"},
		{"eIP.CareofumbilicusStump.label","护�?��?残端"},
		{"eIP.CensusDate.label","普查日期"},
		{"eIP.CensusMonth.label","人�?�普查月"},
		{"eIP.CensusMonthYear.label","普查日期"},
		{"eIP.CertificateNumber.label","�?书�?��?"},
		{"eIP.ChangeofNasogastricTube.label","更�?�鼻胃管"},
		{"eIP.ChangeofUrinaryCatheter.label","更�?�导尿管"},
//		{"eIP.ChargesIncurredonDischargeDay.label","Charges Incurred on Discharge Day"},
//		{"eIP.CheckBookingLimitBasedon.label","Check Booking Limit Based on"},
		{"eIP.CheckforSameSexinRoom.label","检查房间是�?�全部�?�一性别"},
		{"eIP.CheckInAccompanyingPerson.label","�?�?�检查的人"},
		{"eIP.CheckInDateFrom.label","入�?日期"},
		{"eIP.CheckInDateTime.label","入�?时间"},
		{"eIP.CheckInlodger.label","入�?人"},
		{"eIP.checkoutaccomperson.label","离开陪护人员"},
		{"eIP.checkoutdatetime.label","离开日期/时间"},
		{"eIP.checkoutlodger.label","离开人"},
		{"eIP.ChkdInDt.label","检查日期"},
//		{"eIP.ClinicalDocFilm.label","Clinical Doc/Film"},
//		{"eIP.ColorSchemeTable.label","Color Scheme Table"},
//		{"eIP.ColourCodeScheme.label","Colour Code Scheme"},
		{"eIP.ConfirmBedClassChange.label","确认床�?类型转�?�"},
		{"eIP.ConfirmBookingDetails.label","�?�消预认详情"},
		{"eIP.ConfirmCancellation.label","确认�?�消"},
		{"eIP.ConfirmCancelReviseBooking.label","确认/�?�消/修改预订"},
		{"eIP.ConfirmDetails.label","确认明细"},
		{"eIP.ConfirmDischarge.label","确认出院"},
		{"eIP.ConfirmRequestforTransfer.label","确认转�?�需求"},
		{"eIP.ConfirmSwap.label","确认交�?�"},
		{"eIP.ConfirmSwapBeds.label","确认�?�床"},
		{"eIP.ConsumableBillingService.label","耗�??结算�?务"},
		{"eIP.ConsumableFee.label","耗�??费"},
		{"eIP.CostCenter.label","�?本中心"},
//		{"eIP.CreatePseudoBed.label","Create Pseudo Bed"},
		{"eIP.CurrentEncounterDetails.label","当�?�?�到的细节"},
		{"eIP.CurrentInpatientsOnly.label","�?�是当�?�?院病人"},
		{"eIP.CurrentLodgers.label","当�?入�?人"},
		{"eIP.CurrentOccupancy.label","当�?�?�用"},
		{"eIP.CurrentValidityDetails.label","目�?有效明细"},
		{"eIP.DailyAdmissions.label","�?日入院"},
		{"eIP.DailyBookingsByMedicalServiceGroup.label","�?日预订的医疗�?务组"},
		{"eIP.DailyBookingsByNursingUnit.label","�?天预定的护�?�级别"},
		{"eIP.DailyCharge.label","日费用"},
		{"eIP.DailyCharges.label","�?日费用"},
		{"eIP.DailyMonthlyBookings.label","日/月预订"},
		{"eIP.DailyRate.label","�?日费率"},
		{"eIP.DateTimeOfAuthTransfer.label","日期/时间的授�?�转移"},
		{"eIP.DateTimeReturned.label","日期/时间返回"},
//		{"eIP.DaycareUnitforNursingUnit.label","Daycare Unit for Nursing Unit"},
//		{"eIP.DeactivatePseudoBed.label","Deactivate Pseudo Bed"},
		{"eIP.DeathTransactionTime.label","死亡时间"},
		{"eIP.DeceasedDateFrom.label","死者日期"},
		{"eIP.DeceasedDateTo.label","死者日期"},
//		{"eIP.DefaultBedBlockingPeriodonTransferDischargeofInfectiousDiseasePatients.label","Default Bed Blocking Period on Transfer / Discharge of Infectious Disease Patients"},
//		{"eIP.DefaultPeriodforNormal.label","Default Period for Normal"},
		{"eIP.DepositAmount.label","存款金�?"},
		{"eIP.DepositApplicable.label","存款适用"},
		{"eIP.DesignationTitle.label","指定/标题"},
		{"eIP.Diet.label","饮食"},
		{"eIP.DischargeAdviceReport.label","出院通知报告"},
		{"eIP.DischargeBookGiven.label","预出院"},
		{"eIP.DischargeCheckList.label","出院检查列表"},
		{"eIP.DischargeCheckListApplicable.label","适用出院检查列表"},
		{"eIP.DischargeChecklistExpiryPeriod.label","出院检查期满"},
		{"eIP.DischargeDateFrom.label","出院日期 从"},
		{"eIP.DischargeDateTo.label","出院日期 到"},
		{"eIP.DischargeDetails.label","出院明细"},
		{"eIP.DischargedHome.label","出院/回家"},
		{"eIP.DischargeDiagnosis.label","出院诊断"},
		{"eIP.DischargeFunction.label","出院功能"},
		{"eIP.DischargeRemarks.label","出院备注"},
		{"eIP.DischargeSummarySigned.label","出院�?结签�??"},
		{"eIP.DischargeTypeCode.label","出院类型代�?"},
		{"eIP.DischargeTypeIndicator.label","出院类型指标"},
		{"eIP.DischargingPractitioner.label","出院医生"},
		{"eIP.DiscSummaryPrepared.label","出院�?结准备"},
		{"eIP.DrainageCatheters.label","排水导管"},
		{"eIP.EmergencyDetail.label","急诊明细"},
		{"eIP.EmergencyTransfer.label","急诊转移"},
		{"eIP.EscortAmbulanceService.label","护�?/救护车�?务"},
		{"eIP.ExistingMedication.label","现有�?�物"},
		{"eIP.ExpdaysofStay.label","预计�?�留天数"},
		{"eIP.ExpectedDischarge.label","预出院"},
		{"eIP.ExpectedDischargeDateTime.label","预出院日期/时间"},
		{"eIP.ExpectesDischargeDate.label","预出院日期/时间"},
//		{"eIP.ExpiryPeriodUnit.label","Expiry Period Unit"},
//		{"eIP.ExpiryRequired.label","Expiry Required"},
//		{"eIP.FatherIDNo.label","Father ID No"},
//		{"eIP.Fever.label","Fever"},
//		{"eIP.FinancialClassification.label","Financial Classification"},
//		{"eIP.FitForDutyon.label","Fit For Duty on"},
		{"eIP.FollowupAppointments.label","�?�续预约"},
		{"eIP.Formulamilk.label","�?方奶粉"},
		{"eIP.FromBedType.label","床�?类型"},
		{"eIP.FromBedTypeAmount.label","床�?类型金�?"},
		{"eIP.FromBedTypeCode.label","床�?类型代�?"},
		{"eIP.FromDetails.label","明细"},
		{"eIP.FromYear.label","年"},
		{"eIP.Gastrotomyfeeding.label","胃造瘘术喂养"},
		{"eIP.GenerateBookingNumber.label","生�?预订�?��?"},
		{"eIP.GraceperiodforAbscondPatient.label","宽�?期潜逃病人"},
		{"eIP.GraceperiodforNoShow.label","未显示宽�?期"},
		{"eIP.GracePeriodforRevisionofBooking.label","修订预订宽�?期"},
//		{"eIP.guardian.label","Guardian"},
		{"eIP.HandedovertoPatient.label","移交给病人"},
		{"eIP.HealthEducation.label","�?�康教育"},
		{"eIP.HospitalOccupancy.label","医院�?�用"},
		{"eIP.ImmunizationSchedule.label","�?疫计划"},
		{"eIP.InclDiscPatients.label","包括出院病人"},
		{"eIP.IncludeBedtobereleasedin.label","包括床将在"},
		{"eIP.IncludeforHospitalCalculation.label","包括医院计算"},
		{"eIP.IncludeforHospitalOccupancyCalculations.label","包括医院�?�用计算"},
		{"eIP.Informed.label","知情"},
		{"eIP.InformedDetails.label","通报详情"},
		{"eIP.InformedOthers.label","通知其它"},
		{"eIP.InformedPatientRelatives.label","通知病人亲属"},
		{"eIP.InformedTo.label","通知"},
		{"eIP.InformedToName.label","通知�??称"},
		{"eIP.InsuranceExpiryWarning.label","�?险有效期报警"},
		{"eIP.Interward.label","病区外"},
		{"eIP.Intraward.label","病区内"},
//		{"eIP.IPMiscsetup.label","IP Misc setup"},
//		{"eIP.IssuingPractitioner.label","Issuing Practitioner"},
//		{"eIP.IVCatheters.label","IV Catheters"},
		{"eIP.Jaundice.label","黄疸"},
		{"eIP.LabourAndDelivery.label","劳动和交付"},
		{"eIP.LastTransactionDateTime.label","最�?�交易日期/时间"},
		{"eIP.LeaveDatefrom.label","休�?�日期"},
		{"eIP.leavedatetime.label","休�?�日期/时间"},
		{"eIP.LeaveDetails.label","休�?�详情情"},
		{"eIP.LeaveExpiry.label","休�?�期满"},
		{"eIP.LeaveRemarks.label","休�?�备注"},
		{"eIP.LeaveWardAccompaniedBy.label","离开病房的陪�?�下"},
		{"eIP.LengthofStay.label","�?院天数"},
		{"eIP.LodgerAccompanyingPersonReference.label","房客/陪�?�人员�?�考"},
		{"eIP.LodgerDetails.label","房客详细资料"},
		{"eIP.LodgerId.label","房客编�?�"},
		{"eIP.LodgerName.label","房客姓�??"},
		{"eIP.LodgerPersonID.label","房客编�?�"},
		{"eIP.LodgerReferenceMaxSrlNo.label","房客最大�?列�?�"},
		{"eIP.LodgerReferenceNextSrlNo.label","房客下一�?列�?�"},
//		{"eIP.MainBedNo.label","Main Bed No"},
		{"eIP.MaternalDeath.label","产妇"},
//		{"eIP.MaxAllowableBackdatedAdmission.label","Max Allowable Backdated Admission"},
//		{"eIP.MaxAllowableBackdatedDischarge.label","Max Allowable Backdated Discharge"},
//		{"eIP.MaxAllowableBedblockingPeriod.label","Max Allowable Bed blocking Period"},
		{"eIP.MaxAllowableLeavePeriod.label","�?许休�?�最高期�?"},
		{"eIP.MaxAllowablePeriodforAdvanceBedBooking.label","床�?�??�?预订的最多时间"},
//		{"eIP.MaxAllowablePeriodforDischarge.label","Max Allowable Period for Discharge"},
//		{"eIP.MaxAllowablePeriodforNormal.label","Max Allowable Period for Normal"},
//		{"eIP.MaxAllowablePeriodforTransferOut.label","Max Allowable Period for Transfer Out"},
		{"eIP.MaxAllowedAccompanyingPersons.label","�?许陪�?�的最多人员"},
		{"eIP.MaxAllowedPeriodofStayforLodgerAccompanyingPerson.label","�?许为病人�?留床�?的最大日期"},
		{"eIP.MaxDailyBooking.label","日常最高预订�?"},
		{"eIP.MaxDailyBookingLimit.label","日常最高预订�?制"},
		{"eIP.MaxFemaleDailyBookingLimit.label","日常最高预订女性�?制"},
		{"eIP.MaximumParameterValue.label","最大�?�数值"},
		{"eIP.MaxMaleDailyBookingLimit.label","日常最高预订男性�?制"},
		{"eIP.MaxMonthlyBooking.label","�?月最大预订�?"},
		{"eIP.MaxNo.label","最大数"},
		{"eIP.MaxPeriodafterDischargeforCheckinLodger.label","为出院病人检查的最长时间"},
		{"eIP.MaxUnknownDailyBookingLimit.label","未知的�?日最高预订�?�?"},
		{"eIP.MedicalCertificate.label","医疗�?书"},
		{"eIP.MedicalDetails.label","医疗信�?�"},
		{"eIP.MedicalEquipment.label","医疗设备"},
		{"eIP.MedicalServiceGroup.label","医疗�?务组"},
		{"eIP.MonthlyAdmission.label","�?月入院数"},
		{"eIP.MonthlyBookingsByMedicalServiceGroup.label","通过医疗�?务组的�?月预订数"},
		{"eIP.MonthlyBookingsByNursingUnit.label","通过护�?��?��?的�?月预订数"},
		{"eIP.MotherIDNo.label","�?亲编�?�"},
//		{"eIP.MRI.label","MRI"},
//		{"eIP.MVRegnNo.label","MV Regn No"},
		{"eIP.NasogastricTube.label","鼻胃管"},
		{"eIP.NewMedicine.label","新医学"},
		{"eIP.NextNo.label","下一步"},
		{"eIP.Nonoverrideable.label","�?��?载"},
		{"eIP.NormalBeds.label","正常的床"},
		{"eIP.NormalDefaultBedBlockingPeriod.label","正常的默认床期间"},
		{"eIP.NoShowsCancelledBooking.label","�?显示/�?�消预订"},
		{"eIP.NursingTypeCode.label","护�?�类型代�?"},
		{"eIP.NursingUnitBedClass.label","床�?类型对应的护�?�级别"},
		{"eIP.NursingUnitDescription.label","护�?�级别�??述"},
		{"eIP.NursingUnitFrom.label","护�?�级别"},
		{"eIP.NursingUnitSetup.label","护�?�级别设置"},
		{"eIP.NursingUnitType.label","护�?�级别类型"},
		{"eIP.NursingUnitTypeforMedicalServiceGroup.label","医疗�?务组的护�?�级别类型"},
		{"eIP.Nutrition.label","�?�养"},
//		{"eIP.OcccupiedDeparted.label","Occupied - Departed"},
		{"eIP.OccupancyDetails.label","�?�用详情"},
		{"eIP.OccupyingPatientID.label","�?�领病人编�?�"},
		{"eIP.OtherAppliancesFixtures.label","其它设备/装置"},
		{"eIP.OtherDocuments.label","其它文件"},
		{"eIP.OthersSpecify.label","其它指定"},
		{"eIP.OutpatientLocation.label","门诊�?置"},
		{"eIP.OutstandingAmountexceeds.label","未付金�?高于信用�?��?度"},
		{"eIP.OutstandingamountLimit.label","未缴金�?上�?"},
		{"eIP.Overrideable.label","�?载"},
		{"eIP.OverstayDays.label","逾期天"},
		{"eIP.OverStayPatients.label","在�?宿患者"},
		{"eIP.PaediatricDetails.label","儿科详情"},
		{"eIP.Pamphlets.label","�?册�?"},
		{"eIP.PastOpenBookings.label","过去开放预订"},
		{"eIP.PatientBelongings.label","病人财物"},
		{"eIP.PatientFamilyDetails.label","病人家庭明细"},
		{"eIP.PatientReferral.label","病人转诊"},
//		{"eIP.PatientsNotReturnedfromleave.label","Patients Not Returned from leave"},
		{"eIP.PatientsReAdmittedonthesameday.label","病人在�?�一天�?入院"},
		{"eIP.PatientTransfer.label","病人转移"},
		{"eIP.PercentageonDepositAmount.label","存款金�?百分比"},
		{"eIP.PercentAmount.label","百分比/金�?"},
		{"eIP.PercentAmountIndicator.label","百分比/金�?指标"},
		{"eIP.PersonalHygiene.label","个人�?�生"},
		{"eIP.PersonID.label","个人编�?�"},
		{"eIP.PhysicalLocationforNursingUnit.label","护�?�级别的物�?��?置？？？"},
		{"eIP.Physio.label","生�?�"},
		{"eIP.POP.label","�?久性有机污染物"},
		{"eIP.PopCare.label","�?行护�?�"},
		{"eIP.PorterageDetails.label","�?��?详情"},
		{"eIP.PorterageReceived.label","�?��?收稿"},
		{"eIP.PorterageRemarks.label","�?��?备注"},
		{"eIP.PostMortemReqd.label","验尸请求"},
		{"eIP.PostMortemRequested.label","验尸报告�?求"},
		{"eIP.PractitionerDesignation.label","医生�?�称"},
		{"eIP.PractitionerforNursingUnit.label","护�?�级别的执行者"},
		{"eIP.PrefAdmDateTime.label","推�??入院的日期/时间"},
		{"eIP.PreferredAdmissionDate.label","推�??入院日期"},
		{"eIP.PreferredDateTime.label","推�??日期/时间"},
		{"eIP.PreferredDateTo.label","推�??日期"},
		{"eIP.PreferredMonthFrom.label","本月推�??"},
		{"eIP.PreferredMonthTo.label","本月推�??"},
		{"eIP.PrepareDischargeAdvice.label","预出院通知"},
		{"eIP.PreviousBedDetails.label","之�?床�?情况"},
		{"eIP.PreviousIPStay.label","之�?�?院病人"},
		{"eIP.PreviousOccupancy.label","之�?�?�用"},
		{"eIP.PrintCertificate.label","打�?��?书"},
		{"eIP.PrintOn.label","打�?�"},
		{"eIP.PrintTransferDetails.label","打�?�转让细节"},
		{"eIP.ProcedureSurgeryDateTime.label","程�?/外科手术日期时间"},
		{"eIP.Properties.label","属性"},
		{"eIP.Pseudo.label","临时空床"},
		{"eIP.PseudoBabyBeds.label","婴儿床"},
		{"eIP.PseudoBed.label","�?�床"},
		{"eIP.RangeinDays.label","范围"},
		{"eIP.ReasonforAdmissionBooking.label","入院/预订原因"},
		{"eIP.ReasonforBlocking.label","阻塞的原因"},
		{"eIP.ReasonforCancel.label","�?�消的原因"},
		{"eIP.ReasonforLodgerStay.label","房客�?�留原因"},
		{"eIP.ReasonForLodgerStayCode.label","房客�?�留原因"},
		{"eIP.ReasonforStay.label","�?�留原因"},
		{"eIP.ReasonForSwap.label","�?�床原因"},
		{"eIP.ReasonforTransfer.label","转床原因"},
		{"eIP.ReasonforTurnDownAdmission.label","拒�?入院�?�由"},
		{"eIP.ReceivedinFull.label","全�?"},
		{"eIP.ReceivedPartially.label","收到的部分"},
		{"eIP.ReceivedPartiallyFully.label","收到的部分/全部"},
		{"eIP.RecordNoShow.label","没有记录显示"},
		{"eIP.RecordNoShowDateTime.label","记录没有显示日期/时间"},
		{"eIP.RecordNoShowDetails.label","记录没有显示详情"},
		{"eIP.RecordProcedureSurgeryDate.label","记录程�?/外科手术日期"},
		{"eIP.RecordReturn.label","记录返回"},
		{"eIP.RecordReturnDetails.label","返回详细记录"},
		{"eIP.RecordsDocuments.label","记录与文件"},
		{"eIP.ReferralLetter.label","推�??信"},
		{"eIP.ReferredDetails.label","�??到详情"},
		{"eIP.ReferredType.label","�??到类型"},
		{"eIP.RegisterNewBornForIP.label","新出生登记�?院"},
		{"eIP.ReleaseBedonLeave.label","休�?�时空出床�?"},
		{"eIP.RemovalOf.label","去除"},
		{"eIP.RemovedBy.label","删除"},
//		{"eIP.RenewalOfGatePass.label","Renewal of Gate Pass"},
		{"eIP.RenewalValidityDetails.label","更新有效性细节"},
//		{"eIP.renewgatepass.label","Renew Gate Pass"},
		{"eIP.ReplyLetter.label","回函"},
		{"eIP.ReportedTo.label","报告"},
		{"eIP.RequestBedClassChange.label","�?求床级�?�更"},
		{"eIP.RequestforBedClassChange.label","�?求床级�?�更"},
		{"eIP.RequestInpatientConfirmed.label","请求/�?院"},
		{"eIP.RequestPlaced.label","�?求放置"},
		{"eIP.RequestTransfer.label","请求转让"},
		{"eIP.ReturnedRemarks.label","返回备注"},
		{"eIP.ReviseBookingDetails.label","修改预订详情"},
		{"eIP.ReviseLeave.label","修改休�?�"},
		{"eIP.ReviseLeaveDetails.label","修改离开细节"},
		{"eIP.reviseperiodfrom.label","修改期间"},
		{"eIP.reviseperiodto.label","修订期"},
		{"eIP.RoleEndDate.label","角色的结�?�日期"},
		{"eIP.RoleStartDate.label","作用开始日期"},
		{"eIP.RoomCubicleDescription.label","室/柜说明"},
		{"eIP.RoomCubicleforNursingUnit.label","房间护�?�级别"},
		{"eIP.RoundingBillingService.label","四�?五入的结算�?务"},
		{"eIP.RoundingFee.label","修费"},
		{"eIP.Scan.label","扫�??"},
//		{"eIP.Seizure.label","Seizure"},
		{"eIP.ServicesforNursingUnit.label","护�?�级别的�?务"},
		{"eIP.ServiceTeam.label","�?务�?组"},
//		{"eIP.SetupBillingDtls.label","Setup Billing Dtls"},
//		{"eIP.SexSpecInd.label","Sex Spec Ind"},
//		{"eIP.SpecialBedType.label","Special Bed Type"},
		{"eIP.SpecialtyforNursingUnit.label","护�?�科室"},
//		{"eIP.StayPeriod.label","Stay Period"},
//		{"eIP.STO.label","STO"},
//		{"eIP.StockMedicine.label","Stock Medicine"},
//		{"eIP.StomaCare.label","Stoma Care"},
//		{"eIP.StoolColour.label","Stool Colour"},
//		{"eIP.StoolFrequency.label","Stool Frequency"},
//		{"eIP.SupportiveCare.label","Supportive Care at Home"},
		{"eIP.SwapBeds.label","�?�床"},
		{"eIP.SwapPatientBeds.label","交�?�病人床�?"},
//		{"eIP.TakeHomeMedicine.label","Take Home Medicine"},
		{"eIP.TakeHomeNewMedicine.label","带回家/新医�?�"},
		{"eIP.Takencareby.label","照顾的"},
		{"eIP.TeachingLocation.label","教学地点"},
		{"eIP.TemporaryLocation.label","临时�?置"},
		{"eIP.ToBedType.label","床�?类型"},
		{"eIP.ToBedTypeAmount.label","床�?收费类型"},
		{"eIP.ToBedTypeCode.label","床�?类型代�?"},
		{"eIP.ToDateTime.label","日期/时间"},
		{"eIP.ToDetails.label","细节"},
		{"eIP.ToptoToe.label","从头到脚"},
		{"eIP.TotalAdmission.label","共计入院数"},
		{"eIP.TotalBeds.label","共计床�?数"},
		{"eIP.ToYear.label","年"},
		{"eIP.TransactionDateFrom.label","交易日期"},
		{"eIP.TransactionDateTime.label","交易日期/时间"},
		{"eIP.TransactionMonthYear.label","交易月/年"},
		{"eIP.TransferBookingDate.label","转�?�预约的日期"},
		{"eIP.TransferCharge.label","转�?�费用"},
		{"eIP.TransferChargeable.label","转让收费"},
		{"eIP.TransferChargeDetails.label","转让收费详情"},
		{"eIP.TransferConfirmation.label","确认交易"},
		{"eIP.TransferedOut.label","转出"},
		{"eIP.TransferFunction.label","功能转让"},
		{"eIP.TransferInStatus.label","转让状�?"},
		{"eIP.TransferPatientIn.label","病人转入"},
		{"eIP.TransferPatientOut.label","病人转出"},
		{"eIP.TransferPriority.label","转让优先�?�"},
		{"eIP.TransferredIn.label","转让"},
		{"eIP.TransferRequest.label","转移申请"},
		{"eIP.TransferringPractitioner.label","转移执业"},
		{"eIP.TransferServiceCharge.label","转让�?务费"},
		{"eIP.TransferType.label","传输类型"},
		{"eIP.TransferTypeCode.label","转移类型代�?"},
		{"eIP.Transport.label","�?输"},
		{"eIP.TransportArranged.label","�?输安排"},
		{"eIP.Tubefeeding.label","�?�食"},
		{"eIP.Tubes.label","管"},
		{"eIP.TurnDown.label","谢�?"},
		{"eIP.UntilDateTime.label","直到日期时间"},
		{"eIP.UrinaryCatheter.label","导尿管"},
		{"eIP.ValuablesReturned.label","贵�?物�?返回"},
//		{"eIP.WorkupBillingService.label","Workup Billing Service"},
		{"eIP.WoundCare.label","伤�?�护�?�"},
		{"eIP.Xray.label","X光"},
		{"eIP.RejoinedFromLeave.label","休�?��?��?新加入"},
		{"eIP.Transferred.label","转移"},
		{"eIP.RecordInpatientLeaveAbscond.label","记录�?院离开/缺席"},
		{"eIP.EncounterLocation.label","�?�到�?置"},
		{"eIP.ServiceSubService.label","�?务/ 二级�?务"},
		{"eIP.LastAdmissionDateTime.label","上次入院日期时间"},
		{"eIP.LastDischargeDateTime.label","上次出院日期时间"},
		{"eIP.RequestedForRecordDocument.label","�?求记录文件"},
		{"eIP.RequestingNursingUnit.label","护�?�需求"},
/*		{"eIP.AdmittedPatientIntoBuilding.label","Admitted Patient Into Building"},
		{"eIP.BedAlloter.label","Bed Alloter"},
		{"eIP.FirstPortionForDoctor.label","1st Portion For Doctor"},
		{"eIP.InvestigationHappenedBeforeAdmission.label","Investigation Happened Before Admission"},
		{"eIP.PatientRelativeContactPlace.label","Patient/Relative's Contact Place"},
		{"eIP.SecondPortionForAdmissionCenterStaff.label","2nd Portion For Admission Center / Staff"},
		{"eIP.SpecialRequirement.label","Special Requirement"},
		{"eIP.ThirdPortionForPatient.label","3rd Portion For Patient"},
		{"eIP.NotSpecified.label","Not Specified"},
		{"eIP.MaximumAllowed.label","Maximum Allowed"},
		{"eIP.AdmitableDate.label","Admitable Date"},
		{"eIP.CurrentlyPatientIsAt.label","Currently patient is at"},
		{"eIP.Faculty.label","Faculty"},*/
		{"eIP.SpecialMulBedRoom.label","特别多床房"},
		{"eIP.SpecialPvtRoom.label","特别�?人房间"},
		{"eIP.HealthDistrict.label","�?�生区"},
		{"eIP.InfoRequestor.label","信�?�/�?求接收"},
		{"eIP.OtherIdentificationNo.label","其它识别�?�"},
		{"eIP.FamilyHealthOfficer.label","家庭�?�?�人员"},
		{"eIP.GravidaParity.label","孕妇/平价"},
		{"eIP.MatDeathInvOfficer.label","产妇死亡的调查人员"},
		{"eIP.NationalRegnNo.label","全国注册�?��?"},
		{"eIP.StateHealthDepartment.label","国家�?�生署"},
		{"eIP.AbscondFromDateTime.label","缺席的日期时间"},
		{"eIP.ClinicalInformation.label","临床信�?�"},
		{"eIP.RequestedFor.label","�?求"},
		{"eIP.ActiveProblemsDiagnosis.label","主动问题/诊断;"},
		{"eIP.ClinicalSummary.label","临床总结"},
		{"eIP.LastAdmissionDate.label","上次入院日期"},
		{"eIP.LastAdmissionLocation.label","上次入院医院？"},
		{"eIP.NewProblemsDiagnosis.label","新的问题�?诊断"},
		{"eIP.Stamp.label","邮票"},
//		{"eIP.GatePassValidity","GatePass Validity"},
		{"eIP.AdmittedForTreatment.label","入院治疗"},
		{"eIP.ScheduledOperationDate.label","手术日期排定"},
		{"eIP.ScheduledSpecialCheckupDate.label","特别检查预定日期"},
		{"eIP.ContactPlaceOfDoctor.label","�?�系地点的医生"},
		{"eIP.SocialSecurity.label","社会�?障"},
		{"eIP.LifeInsurance.label","人寿�?险"},
		{"eIP.SelfPayment.label","自付款"},
		{"eIP.DateAssignedForOperation.label","择期手术"},
		{"eIP.HospitalAdmissionCenter.label","�?院中心"},
//		{"eIP.IncaseOfQuestionOrChangeRequest.label","Incase Of Question Or Change Request"},
		{"eIP.UnConfirmed.label","未�?�?实的"},
		{"eIP.EstimateCost.label","估计�?本"},
		{"eIP.OverReimbursable.label","在�?�还费用"},
		{"eIP.LeavePass.label","�?�通行�?"},
//		{"eIP.ValuableBelongTo.label","Valuable belong to"},
//		{"eIP.Pieces.label.label","Pieces"},
		{"eIP.LastUpdateFileLocation.label","最�?�更新文件的�?置"},
//		{"eIP.LocationPriorToLastUpdate.label","Location Prior to Last Update"},
		{"eIP.PatientGender.label","病人性别"},
		{"eIP.GenderType.label","性别类型"},
		{"eIP.BedGender.label","床�?性别"},
		{"eIP.BedAvailablibilityDate.label","床�?�?�以�?院的日期"},
		{"eIP.ReserveBedDetails.label","�?留床细节"},
		{"eIP.ReserveBed.label","�?留床"},
		{"eIP.ReasonforReserveBed.label","�?留床原因"},
		{"eIP.ReservedBeds.label","�?留床"},
		{"eIP.ReserveBedWhileTransfer.label","转移时�?留床�?"},
		{"eIP.MultipleBookingforPatients.label","病人多次预订"},
		{"eIP.ViewOpenBookings.label","查看开放预订"},
		{"eIP.MotherBedNo.label","�?亲床�?�"},
		{"eIP.IncludeReservedBeds.label","包括预留病床"},
//		{"eIP.AssignPractitionerBedsideReferral.label","Assign Practitioner for Bedside Referral"},
		{"eIP.StatisticsBy.label","统计资料"},
		{"eIP.ChangeInpatientService.label","更�?��?院�?务"},
		{"eIP.BookedOverrideableConfirmed.label","预订�?载确认"},
		{"eIP.BookedOverrideableUnConfirmed.label","未�?�?实的预订�?载"},
		{"eIP.BookedNonOverrideableConfirmed.label","预订�?��?载确认"},
		{"eIP.BookedNonOverrideableUnConfirmed.label","预订�?��?载未�?�?实"},
//		{"eIP.PreOpPreparationDays.label","Pre-Op Preparation Days"},
//		{"eIP.BlockBedBasedon.label","Block Bed based on"},
		{"eIP.CancelDischargeApplicable.label","�?�消�?院适用"},
		{"eIP.CancelDischargePatient.label","�?�消出院病人"},
		{"eIP.AbortCancelDischarge.label","中止�?�消出院"},
		{"eIP.BookingRemarks.label","预订备注"},
		{"eIP.InvokeAdmFromNewBornReg.label","新生儿登记调用入院"},
		{"eIP.DischargeStatus.label","出院状�?"},
		{"eIP.CompleteRecovery.label","完全�?��?"},
		{"eIP.PartialRecovery.label","部分�?��?"},
		{"eIP.StatusQuo.label","现状"},
		{"eIP.ConditionWorse.label","更糟糕的�?�件"},
		{"eIP.DischargeStatusIndicator.label","出院状�?指示"},
		{"eIP.Deceasedperiod.label","死亡期"},
		{"eIP.CensusDateRange.label","普查日期范围"},
		{"eIP.PercentageofOccupancy.label","�?�用的百分比"},
		{"eIP.Nodaysallowtoresbed.label","没有几天�?�预留病床"}

	};
}
