
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eCP.ReviseCarePlan.ReviseCarePlanManager
package eCP.ReviseCarePlan;

/**
 * Remote interface for ReviseCarePlan
 */
public interface ReviseCarePlanRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap AddModify(java.util.Properties properties, java.util.HashMap hashmap) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
