<!DOCTYPE html>
<% 
/*
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Date		            Edit History	        Name			INC Number       Rev.Date		     Rev.Name			     Description
-------------------------------------------------------------------------------------------------------------------------------------------------------------

27/10/2014				HSA-CRF-0171			Sakti Sankar		48543											In Issue Return,Remove the validation 
																													of Issue Doc.Type.Users just need to 
																													find the Issue Doc No. Once user select item 
																													to be returned in the list, system should 
																													auto default the value of Issue Doc. Type
--------------------------------------------------------------------------------------------------------------------------------------------------------------
*/
%>
<%@page import="java.util.HashMap,java.util.ArrayList,java.util.Properties,eST.*" contentType="text/html;charset=UTF-8"%>
<%@ include file="../../eCommon/jsp/GetPersistenceBean.jsp" %>
<%@include file="../../eCommon/jsp/CommonBean.jsp" %>
<%@ include file="../../eCommon/jsp/CommonInclude.jsp"%>
<html>
	<head>
	<%
			request.setCharacterEncoding("UTF-8");
			String locale				=		(String)session.getAttribute("LOCALE");
		
			String sStyle				=		(session.getAttribute("PREFERRED_STYLE")!=null)||(session.getAttribute("PREFERRED_STYLE")!="")?(String)session.getAttribute("PREFERRED_STYLE"):"IeStyle.css";
%>

		<link rel='StyleSheet' href='../../eCommon/html/<%=sStyle%>' type='text/css' ></link>
		<script language="javascript" src="../../eCommon/js/common.js"></script>
		<script language="javascript" src="../../eCommon/js/CommonResult.js"></script>
		<script language="javascript" src="../../eCommon/js/ValidateControl.js"></script>
		<script language='javascript' src='../../eST/js/StCommon.js'></script>
		<script language="javascript" src="../../eST/js/IssueReturn.js"></script>
		<script language="JavaScript" src="../../eCommon/js/DateUtils.js"></script>
<script src='../../eCommon/js/showModalDialog.js' language='JavaScript'></script>



	</head>
	<body>
	<%
		String doc_type_code		=		request.getParameter("doc_type_code");
		String doc_no				=		request.getParameter("doc_no");
		String frm_doc_date			=		request.getParameter("frm_doc_date");
		frm_doc_date				=		com.ehis.util.DateUtils.convertDate(frm_doc_date,"DMY",locale,"en");
		String to_doc_date			=		request.getParameter("to_doc_date");
		to_doc_date					=		com.ehis.util.DateUtils.convertDate(to_doc_date,"DMY",locale,"en");
		String fm_store				=		request.getParameter("frm_store_code");
		String to_store				=		request.getParameter("to_store_code");
		String item_code = request.getParameter("item_code");
		String classvalue			=		"";
		boolean searched			=		(request.getParameter("searched") == null) ?false:true;
		HashMap sqlMap				=		new HashMap();
		HashMap funcMap				=		new HashMap();
		ArrayList displayFields		=		new ArrayList();
		ArrayList chkFields			=		new ArrayList();
		ArrayList result			=		new ArrayList();
		ArrayList records			=		new ArrayList();

		IssueReturnBean bean		=		(IssueReturnBean) getBeanObject("issueReturnBean", "eST.IssueReturnBean", request);  
		bean.setLanguageId(locale);
		//ArrayList alParam           =	new ArrayList();
		//alParam.add(bean.getLoginFacilityId());
		//alParam.add(doc_type_code);

		String batch_id        =  CommonBean.checkForNull(request.getParameter("batch_id"),"");
		String expiry_date     =  CommonBean.checkForNull(request.getParameter("expiry_date"),"");	
		String trade_id        =  CommonBean.checkForNull(request.getParameter("trade_id"),"");	
		String binlocation     =  CommonBean.checkForNull(request.getParameter("binlocation"),"");	
		String barcode_yn     =	  CommonBean.checkForNull(bean.getBarcodeApplicable(),"N");
	
		try{
			CommonBean.setLoginFacilityId((String) session.getValue("facility_id"));
			//doc_type_code				   =		CommonBean.checkForNull(doc_type_code); //Comented by Sakti against HSA-CRF-0171 Inc# 48543
			doc_type_code				   =		CommonBean.checkForNull(doc_type_code,"%"); //Added by Sakti against HSA-CRF-0171 if null to get % value Inc# 48543
			doc_no						   =		CommonBean.checkForNull(doc_no,"%");
			frm_doc_date				   =		CommonBean.checkForNull(frm_doc_date);
			to_doc_date					   =		CommonBean.checkForNull(to_doc_date);
			fm_store					   =		CommonBean.checkForNull(fm_store);
			to_store					   =		CommonBean.checkForNull(to_store);
			item_code					   =		CommonBean.checkForNull(item_code,"%");


				/* IN020780 */
		//sqlMap.put("sqlData","SELECT HDR.DOC_NO ISSUE_DOC_NO,HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,DECODE (REQUEST_STATUS,'', 'Urgent Issue','E', 'Request Entered','W', 'Authorized at req by store','A', 'authorized at issue store','P', 'Partially Issued','C', 'Fully Issued','L','Closed Upon Issue') REQUEST_STATUS FROM ST_ISSUE_HDR HDR,ST_ISSUE_DTL DTL,MM_ITEM_LANG_VW MM,ST_REQUEST_HDR RHDR,ST_ISSUE_DTL_EXP DTL_EXP,ST_ACKNOWLEDGE_TRN_DTL ACK,ST_ACKNOWLEDGE_TRN_DTL ACK1,ST_ISSUE_RET_DTL_EXP RETEXP,ST_ACC_ENTITY_PARAM STP WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE  DECODE(STP.TRN_ACROSS_FACILITY_YN,'Y','%',?) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY') AND TO_DATE (NVL (?,TO_CHAR (SYSDATE, 'DD/MM/YYYY')),'DD/MM/YYYY')) AND TO_CHAR (HDR.DOC_NO) LIKE ? AND MM.ITEM_CODE = DTL.ITEM_CODE AND DTL.ITEM_CODE LIKE ? AND ('URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C','L')) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+) AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+)=DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+)=DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? HAVING SUM (  NVL (ACK.RECEIVED_QTY, DTL_EXP.ISS_ITEM_QTY)- NVL (ACK1.RECEIVED_QTY, DTL_EXP.RET_ITEM_QTY)) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS,HDR.SEQ_NO ORDER BY HDR.DOC_NO,SEQ_NO");
    	//sqlMap.put("sqlData","SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC, TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE, DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) REQUEST_STATUS FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY') AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY') ), 'DD/MM/YYYY' ) ) AND TO_CHAR (HDR.DOC_NO) LIKE ? AND MM.ITEM_CODE = DTL.ITEM_CODE AND DTL.ITEM_CODE LIKE ? AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (REQUEST_STATUS = 'A' AND  DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+) AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0   HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL(BATCH.COMMITTED_QTY,0) THEN NVL (BATCH.QTY_ON_HAND, 0)- NVL(BATCH.COMMITTED_QTY,0) ELSE NVL (DTL_EXP.ISS_ITEM_QTY, 0) END ) ) - NVL (ACK1.RECEIVED_QTY, DTL_EXP.RET_ITEM_QTY)  ) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS,  HDR.SEQ_NO,BATCH.QTY_ON_HAND ORDER BY HDR.DOC_NO, SEQ_NO");
		//sqlMap.put("sqlData","SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,(CASE WHEN (    REQUEST_STATUS IN ('A','P','L') AND (DTL.ISS_ITEM_QTY >= DTL.AUTHORIZED_ITEM_QTY) AND RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO ) THEN 'FULLY ISSUED' WHEN (    REQUEST_STATUS IN( 'A','P','L') AND (DTL.AUTHORIZED_ITEM_QTY - DTL.ISS_ITEM_QTY > 0) and RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO) THEN 'PARTIALLY ISSUED' WHEN REQUEST_STATUS IN ('', 'E', 'W', 'A', 'P', 'C', 'L') THEN DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) END ) REQUEST_STATUS,HDR.FACILITY_ID FACILITY_ID FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH, ST_FACILITY_PARAM ST WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY' ) AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY')  ), 'DD/MM/YYYY' ) ) AND TO_CHAR (HDR.DOC_NO) LIKE ? AND MM.ITEM_CODE = DTL.ITEM_CODE AND DTL.ITEM_CODE LIKE ? AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (   DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+)      AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.bin_location_code = DTL_EXP.to_bin_location_code    AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0 HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) THEN   NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) ELSE NVL (DTL_EXP.ISS_ITEM_QTY, 0) END ) ) - NVL (ACK1.RECEIVED_QTY, DTL_EXP.RET_ITEM_QTY) ) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS, HDR.SEQ_NO, BATCH.QTY_ON_HAND, DTL.ISS_ITEM_QTY, DTL.AUTHORIZED_ITEM_QTY, RHDR.ISSUE_SEQ_NO,HDR.FACILITY_ID ORDER BY HDR.DOC_NO, SEQ_NO  ");
		//sqlMap.put("sqlData","SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,(CASE WHEN (    REQUEST_STATUS IN ('A','P','L') AND (DTL.ISS_ITEM_QTY >= DTL.AUTHORIZED_ITEM_QTY) AND RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO ) THEN 'FULLY ISSUED' WHEN (    REQUEST_STATUS IN( 'A','P','L') AND (DTL.AUTHORIZED_ITEM_QTY - DTL.ISS_ITEM_QTY > 0) and RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO) THEN 'PARTIALLY ISSUED' WHEN REQUEST_STATUS IN ('', 'E', 'W', 'A', 'P', 'C', 'L') THEN DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) END ) REQUEST_STATUS,HDR.FACILITY_ID FACILITY_ID FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH, ST_FACILITY_PARAM ST WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY' ) AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY')  ), 'DD/MM/YYYY' ) ) AND TO_CHAR (HDR.DOC_NO) LIKE ? AND MM.ITEM_CODE = DTL.ITEM_CODE AND DTL.ITEM_CODE LIKE ? AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (   DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+)      AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.bin_location_code = DTL_EXP.to_bin_location_code    AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0 HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) THEN   NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0)  ELSE NVL (dtl_exp.iss_item_qty, 0) - NVL (ack1.received_qty, dtl_exp.ret_item_qty) END ) )-  (CASE WHEN NVL(ack.received_qty,0) = 0 THEN 0 ELSE NVL (ack1.received_qty, dtl_exp.ret_item_qty) END)) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS, HDR.SEQ_NO, BATCH.QTY_ON_HAND, DTL.ISS_ITEM_QTY, DTL.AUTHORIZED_ITEM_QTY, RHDR.ISSUE_SEQ_NO,HDR.FACILITY_ID ORDER BY HDR.DOC_NO, SEQ_NO  ");

		//sqlMap.put("sqlData","SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,(CASE WHEN (    REQUEST_STATUS IN ('A','P','L') AND (DTL.ISS_ITEM_QTY >= DTL.AUTHORIZED_ITEM_QTY) AND RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO ) THEN 'FULLY ISSUED' WHEN (    REQUEST_STATUS IN( 'A','P','L') AND (DTL.AUTHORIZED_ITEM_QTY - DTL.ISS_ITEM_QTY > 0) and RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO) THEN 'PARTIALLY ISSUED' WHEN REQUEST_STATUS IN ('', 'E', 'W', 'A', 'P', 'C', 'L') THEN DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) END ) REQUEST_STATUS,HDR.FACILITY_ID FACILITY_ID FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH, ST_FACILITY_PARAM ST WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY' ) AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY')  ), 'DD/MM/YYYY' ) ) AND TO_CHAR (HDR.DOC_NO) LIKE ? AND MM.ITEM_CODE = DTL.ITEM_CODE AND DTL.ITEM_CODE LIKE ? AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (   DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+)      AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.bin_location_code = DTL_EXP.to_bin_location_code    AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0  and nvl(dtl_exp.iss_item_qty,0) - nvl(dtl_exp.ret_item_qty,0) > 0 HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) THEN   NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0)  ELSE NVL (dtl_exp.iss_item_qty, 0) - NVL (ack1.received_qty, dtl_exp.ret_item_qty) END ) )-  (CASE WHEN NVL(ack.received_qty,0) = 0 THEN 0 ELSE NVL (ack1.received_qty, dtl_exp.ret_item_qty) END)) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS, HDR.SEQ_NO, BATCH.QTY_ON_HAND, DTL.ISS_ITEM_QTY, DTL.AUTHORIZED_ITEM_QTY, RHDR.ISSUE_SEQ_NO,HDR.FACILITY_ID ORDER BY HDR.DOC_NO, SEQ_NO  ");

		//sqlMap.put("sqlData","SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,(CASE WHEN (    REQUEST_STATUS IN ('A','P','L') AND (DTL.ISS_ITEM_QTY >= DTL.AUTHORIZED_ITEM_QTY) AND RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO ) THEN 'FULLY ISSUED' WHEN (    REQUEST_STATUS IN( 'A','P','L') AND (DTL.AUTHORIZED_ITEM_QTY - DTL.ISS_ITEM_QTY > 0) and RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO) THEN 'PARTIALLY ISSUED' WHEN REQUEST_STATUS IN ('', 'E', 'W', 'A', 'P', 'C', 'L') THEN DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) END ) REQUEST_STATUS,HDR.FACILITY_ID FACILITY_ID FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH, ST_FACILITY_PARAM ST WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY' ) AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY')  ), 'DD/MM/YYYY' ) ) AND TO_CHAR (HDR.DOC_NO) LIKE ? AND MM.ITEM_CODE = DTL.ITEM_CODE AND DTL.ITEM_CODE LIKE ? AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (   DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+)      AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.bin_location_code = DTL_EXP.to_bin_location_code    AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0  and nvl(dtl_exp.iss_item_qty,0) - nvl(dtl_exp.ret_item_qty,0) > 0 HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) THEN   NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0)  ELSE NVL (dtl_exp.iss_item_qty, 0) - NVL (ack1.received_qty, dtl_exp.ret_item_qty) END ) )-  (CASE WHEN NVL(ack.received_qty,0) = 0 THEN 0 ELSE NVL (ack1.received_qty, dtl_exp.ret_item_qty) END)) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS, HDR.SEQ_NO, BATCH.QTY_ON_HAND, DTL.ISS_ITEM_QTY, DTL.AUTHORIZED_ITEM_QTY, RHDR.ISSUE_SEQ_NO,HDR.FACILITY_ID  UNION SELECT ihr.doc_no issue_doc_no,ihr.seq_no seq_no, mmitm.short_desc item_desc, TO_CHAR (ihr.doc_date, 'DD/MM/YYYY') doc_date, (CASE  WHEN (    request_status IN ('A', 'P', 'L')  AND (idtl.iss_item_qty >= idtl.authorized_item_qty)  AND rhdr.issue_seq_no != ihr.seq_no )  THEN 'FULLY ISSUED'  WHEN (    request_status IN ('A', 'P', 'L')  AND (idtl.authorized_item_qty - idtl.iss_item_qty > 0)  AND rhdr.issue_seq_no != ihr.seq_no)  THEN 'PARTIALLY ISSUED'  WHEN request_status IN ('', 'E', 'W', 'A', 'P', 'C', 'L')  THEN DECODE (request_status,'', 'URGENT ISSUE','E', 'REQUEST ENTERED','W', 'AUTHORIZED AT REQ BY STORE','A', 'AUTHORIZED AT ISSUE STORE','P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE')  END)  request_status, ihr.facility_id facility_id   FROM st_issue_dtl_exp ide, st_issue_hdr ihr, mm_bin_location mmb, st_issue_dtl idtl, mm_item mmitm, am_trade_name amtrade,st_request_hdr rhdr WHERE ide.facility_id = ?  AND idtl.item_code = mmitm.item_code   AND ide.trade_id = amtrade.trade_id(+)  AND (    ide.facility_id = ihr.facility_id  AND ide.doc_type_code = ihr.doc_type_code  AND ide.doc_no = ihr.doc_no  AND ide.seq_no = ihr.seq_no )  AND ihr.finalized_yn = 'Y'  AND ihr.fm_store_code = ?  AND ihr.to_store_code = ?  AND (ide.iss_item_qty - NVL (ide.ret_item_qty, 0)) >= 0  AND (    ihr.fm_store_code = mmb.store_code  AND ide.bin_location_code = mmb.bin_location_code )  AND idtl.facility_id = ide.facility_id  AND idtl.doc_type_code = ide.doc_type_code  AND idtl.doc_no = ide.doc_no  AND idtl.seq_no = ihr.seq_no   AND idtl.item_code = ide.item_code  AND ihr.doc_no = rhdr.doc_no(+)  AND ihr.doc_type_code = rhdr.doc_type_code(+)  AND ihr.facility_id = rhdr.facility_id(+)  AND ide.item_code like ?  AND IDTL.STOCK_ITEM_YN ='N'  AND ihr.doc_no like ? AND ihr.doc_type_code = ?   AND ihr.doc_date BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY')  AND TO_DATE (NVL (?,TO_CHAR (SYSDATE, 'DD/MM/YYYY')),'DD/MM/YYYY') AND NVL (ide.iss_item_qty, 0) - NVL (ide.ret_item_qty, 0) > 0 ORDER BY issue_doc_no, seq_no  ");

	//Comented by Sakti against HSA-CRF-0171 query changed below Inc# 48543
		//String sql = "SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,(CASE WHEN (    REQUEST_STATUS IN ('A','P','L') AND (DTL.ISS_ITEM_QTY >= DTL.AUTHORIZED_ITEM_QTY) AND RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO ) THEN 'FULLY ISSUED' WHEN (    REQUEST_STATUS IN( 'A','P','L') AND (DTL.AUTHORIZED_ITEM_QTY - DTL.ISS_ITEM_QTY > 0) and RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO) THEN 'PARTIALLY ISSUED' WHEN REQUEST_STATUS IN ('', 'E', 'W', 'A', 'P', 'C', 'L') THEN DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) END ) REQUEST_STATUS,HDR.FACILITY_ID FACILITY_ID FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH, ST_FACILITY_PARAM ST WHERE HDR.DOC_TYPE_CODE = ? AND HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY' ) AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY')  ), 'DD/MM/YYYY' ) ) AND MM.ITEM_CODE = DTL.ITEM_CODE  AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (   DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+)      AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.bin_location_code = DTL_EXP.to_bin_location_code    AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0  and nvl(dtl_exp.iss_item_qty,0) - nvl(dtl_exp.ret_item_qty,0) > 0 ";

		//Added by Sakti against HSA-CRF-0171 query changed to get doc_type_code and description doc_type_code parameter comented to pass the same dynamically Inc# 48543
		String sql = "SELECT  HDR.DOC_NO ISSUE_DOC_NO, HDR.SEQ_NO SEQ_NO, MM.SHORT_DESC ITEM_DESC,hdr.doc_type_code issue_doc_type,(select  short_desc from  SY_DOC_TYPE_MASTER_lang_vw where DOC_TYPE_CODE=hdr.doc_type_code and language_id=? )doc_type_desc,TO_CHAR (HDR.DOC_DATE, 'DD/MM/YYYY') DOC_DATE,(CASE WHEN (    REQUEST_STATUS IN ('A','P','L') AND (DTL.ISS_ITEM_QTY >= DTL.AUTHORIZED_ITEM_QTY) AND RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO ) THEN 'FULLY ISSUED' WHEN (    REQUEST_STATUS IN( 'A','P','L') AND (DTL.AUTHORIZED_ITEM_QTY - DTL.ISS_ITEM_QTY > 0) and RHDR.ISSUE_SEQ_NO!=HDR.SEQ_NO) THEN 'PARTIALLY ISSUED' WHEN REQUEST_STATUS IN ('', 'E', 'W', 'A', 'P', 'C', 'L') THEN DECODE (REQUEST_STATUS, '', 'URGENT ISSUE', 'E', 'REQUEST ENTERED', 'W', 'AUTHORIZED AT REQ BY STORE', 'A', 'AUTHORIZED AT ISSUE STORE', 'P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE' ) END ) REQUEST_STATUS,HDR.FACILITY_ID FACILITY_ID FROM ST_ISSUE_HDR HDR, ST_ISSUE_DTL DTL, MM_ITEM_LANG_VW MM, ST_REQUEST_HDR RHDR, ST_ISSUE_DTL_EXP DTL_EXP, ST_ACKNOWLEDGE_TRN_DTL ACK, ST_ACKNOWLEDGE_TRN_DTL ACK1, ST_ISSUE_RET_DTL_EXP RETEXP, ST_ACC_ENTITY_PARAM STP, ST_ITEM_BATCH BATCH, ST_FACILITY_PARAM ST WHERE /*HDR.DOC_TYPE_CODE = ? AND*/ HDR.FM_STORE_CODE = ? AND HDR.TO_STORE_CODE = ? AND HDR.FINALIZED_YN = 'Y' AND HDR.FACILITY_ID LIKE DECODE (STP.TRN_ACROSS_FACILITY_YN, 'Y', '%', ? ) AND (HDR.DOC_DATE BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY' ) AND TO_DATE (NVL (?, TO_CHAR (SYSDATE, 'DD/MM/YYYY')  ), 'DD/MM/YYYY' ) ) AND MM.ITEM_CODE = DTL.ITEM_CODE  AND (   'URG' = (SELECT TRN_TYPE FROM ST_TRN_DOC_TYPE DOC WHERE DOC.DOC_TYPE_CODE = HDR.DOC_TYPE_CODE AND DOC.FACILITY_ID = HDR.FACILITY_ID) OR REQUEST_STATUS IN ('P', 'C', 'L') OR (   DTL.ISS_ITEM_QTY IS NOT NULL AND HDR.FINALIZED_YN = 'Y' ) ) AND HDR.DOC_NO = DTL.DOC_NO AND HDR.SEQ_NO = DTL.SEQ_NO AND HDR.DOC_TYPE_CODE = DTL.DOC_TYPE_CODE AND HDR.FACILITY_ID = DTL.FACILITY_ID AND HDR.DOC_NO = RHDR.DOC_NO(+) AND HDR.DOC_TYPE_CODE = RHDR.DOC_TYPE_CODE(+) AND HDR.FACILITY_ID = RHDR.FACILITY_ID(+) AND DTL.FACILITY_ID = DTL_EXP.FACILITY_ID AND DTL.DOC_NO = DTL_EXP.DOC_NO AND DTL.DOC_TYPE_CODE = DTL_EXP.DOC_TYPE_CODE AND DTL.SEQ_NO = DTL_EXP.SEQ_NO AND DTL.DOC_SRL_NO = DTL_EXP.DOC_SRL_NO AND DTL.ITEM_CODE = DTL_EXP.ITEM_CODE AND DTL_EXP.FACILITY_ID = ACK.FACILITY_ID(+) AND DTL_EXP.DOC_NO = ACK.DOC_NO(+) AND DTL_EXP.DOC_TYPE_CODE = ACK.DOC_TYPE_CODE(+) AND DTL_EXP.DOC_SRL_NO = ACK.DOC_SRL_NO(+)      AND DTL_EXP.ITEM_CODE = ACK.ITEM_CODE(+) AND DTL_EXP.SEQ_NO = ACK.SEQ_NO(+) AND DTL_EXP.BATCH_ID = ACK.BATCH_ID(+) AND DTL_EXP.TRADE_ID = ACK.TRADE_ID(+) AND DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE = ACK.EXPIRY_DATE_OR_RECEIPT_DATE(+) AND RETEXP.ORG_DOC_NO(+) = DTL_EXP.DOC_NO AND RETEXP.ORG_SEQ_NO(+) = DTL_EXP.SEQ_NO AND RETEXP.ITEM_CODE(+) = DTL_EXP.ITEM_CODE AND RETEXP.BATCH_ID(+) = DTL_EXP.BATCH_ID AND RETEXP.ORG_DOC_TYPE_CODE(+) = DTL_EXP.DOC_TYPE_CODE AND RETEXP.FACILITY_ID = ACK1.FACILITY_ID(+) AND RETEXP.DOC_NO = ACK1.DOC_NO(+) AND RETEXP.DOC_TYPE_CODE = ACK1.DOC_TYPE_CODE(+) AND RETEXP.BATCH_ID = ACK1.BATCH_ID(+) AND RETEXP.ITEM_CODE = ACK1.ITEM_CODE(+) AND LANGUAGE_ID = ? AND STP.ACC_ENTITY_ID = ? AND BATCH.STORE_CODE = HDR.TO_STORE_CODE AND BATCH.ITEM_CODE = DTL_EXP.ITEM_CODE AND BATCH.BATCH_ID = DTL_EXP.BATCH_ID AND TRUNC (BATCH.EXPIRY_DATE_OR_RECEIPT_DATE) = TRUNC (DTL_EXP.EXPIRY_DATE_OR_RECEIPT_DATE) AND BATCH.bin_location_code = DTL_EXP.to_bin_location_code    AND BATCH.TRADE_ID = DTL_EXP.TRADE_ID AND BATCH.QTY_ON_HAND - BATCH.COMMITTED_QTY > 0  and nvl(dtl_exp.iss_item_qty,0) - nvl(dtl_exp.ret_item_qty,0) > 0 ";
		
		if(doc_no != "%")
		{	
		sql = sql + " and HDR.doc_no = " + "'"+doc_no+"'" ;
		}
		if(item_code != "%")
		{	
		sql = sql + " and DTL.item_code = " + "'"+item_code+"'" ;
		}
		//Added by Sakti against HSA-CRF-0171 to pass the below parameter dynamically based on availability Inc# 48543
		if(doc_type_code != "%")
		{	
		sql = sql + " and hdr.doc_type_code = " + "'"+doc_type_code+"'" ;
		}
		//Added ends
		if(barcode_yn.equals("Y") && item_code != "%"){ 
		if(batch_id != "")
		{	
		sql = sql + " and dtl_exp.batch_id = " + "'"+batch_id+"'" ;
		}
		if(expiry_date != "")
		{	
		sql = sql + " and to_char(dtl_exp.expiry_date_or_receipt_date,'dd/mm/yyyy') = "+"'"+expiry_date+"'";
		}
		if(trade_id != "")
		{	
		sql = sql + " and dtl_exp.trade_id = " + "'"+trade_id+"'" ;
		}
		if(binlocation != "")
		{	
		sql = sql + " and dtl_exp.bin_location_code = " + "'"+binlocation+"'" ;
		}
		}

		//Comented by Sakti against HSA-CRF-0171 query changed below Inc# 48543
		//sql = sql + " HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) THEN   NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0)  ELSE NVL (dtl_exp.iss_item_qty, 0) - NVL (ack1.received_qty, dtl_exp.ret_item_qty) END ) )-  (CASE WHEN NVL(ack.received_qty,0) = 0 THEN 0 ELSE NVL (ack1.received_qty, dtl_exp.ret_item_qty) END)) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS, HDR.SEQ_NO, BATCH.QTY_ON_HAND, DTL.ISS_ITEM_QTY, DTL.AUTHORIZED_ITEM_QTY, RHDR.ISSUE_SEQ_NO,HDR.FACILITY_ID  UNION  SELECT ihr.doc_no issue_doc_no,ihr.seq_no seq_no, mmitm.short_desc item_desc, TO_CHAR (ihr.doc_date, 'DD/MM/YYYY') doc_date, (CASE  WHEN (    request_status IN ('A', 'P', 'L')  AND (idtl.iss_item_qty >= idtl.authorized_item_qty)  AND rhdr.issue_seq_no != ihr.seq_no )  THEN 'FULLY ISSUED'  WHEN (    request_status IN ('A', 'P', 'L')  AND (idtl.authorized_item_qty - idtl.iss_item_qty > 0)  AND rhdr.issue_seq_no != ihr.seq_no)  THEN 'PARTIALLY ISSUED'  WHEN request_status IN ('', 'E', 'W', 'A', 'P', 'C', 'L')  THEN DECODE (request_status,'', 'URGENT ISSUE','E', 'REQUEST ENTERED','W', 'AUTHORIZED AT REQ BY STORE','A', 'AUTHORIZED AT ISSUE STORE','P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE')  END)  request_status, ihr.facility_id facility_id   FROM st_issue_dtl_exp ide, st_issue_hdr ihr, mm_bin_location mmb, st_issue_dtl idtl, mm_item mmitm, am_trade_name amtrade,st_request_hdr rhdr WHERE ide.facility_id = ?  AND idtl.item_code = mmitm.item_code   AND ide.trade_id = amtrade.trade_id(+)  AND (    ide.facility_id = ihr.facility_id  AND ide.doc_type_code = ihr.doc_type_code  AND ide.doc_no = ihr.doc_no  AND ide.seq_no = ihr.seq_no )  AND ihr.finalized_yn = 'Y'  AND ihr.fm_store_code = ?  AND ihr.to_store_code = ?  AND (ide.iss_item_qty - NVL (ide.ret_item_qty, 0)) >= 0  AND (    ihr.fm_store_code = mmb.store_code  AND ide.bin_location_code = mmb.bin_location_code )  AND idtl.facility_id = ide.facility_id  AND idtl.doc_type_code = ide.doc_type_code  AND idtl.doc_no = ide.doc_no  AND idtl.seq_no = ihr.seq_no   AND idtl.item_code = ide.item_code  AND ihr.doc_no = rhdr.doc_no(+)  AND ihr.doc_type_code = rhdr.doc_type_code(+)  AND ihr.facility_id = rhdr.facility_id(+)  AND IDTL.STOCK_ITEM_YN ='N'  AND ihr.doc_type_code = ?  AND ihr.doc_date BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY')  AND TO_DATE (NVL (?,TO_CHAR (SYSDATE, 'DD/MM/YYYY')),'DD/MM/YYYY') AND NVL (ide.iss_item_qty, 0) - NVL (ide.ret_item_qty, 0) > 0 " ;

		//Added by Sakti against HSA-CRF-0171 query changed to get doc_type_code and description doc_type_code parameter comented to pass the same dynamically Inc# 48543
		sql = sql + " HAVING SUM (  NVL (ACK.RECEIVED_QTY, (CASE WHEN NVL (DTL_EXP.ISS_ITEM_QTY, 0) > NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0) THEN   NVL (BATCH.QTY_ON_HAND, 0) - NVL (BATCH.COMMITTED_QTY, 0)  ELSE NVL (dtl_exp.iss_item_qty, 0) - NVL (ack1.received_qty, dtl_exp.ret_item_qty) END ) )-  (CASE WHEN NVL(ack.received_qty,0) = 0 THEN 0 ELSE NVL (ack1.received_qty, dtl_exp.ret_item_qty) END)) > 0 GROUP BY HDR.DOC_NO, MM.SHORT_DESC, HDR.DOC_DATE, REQUEST_STATUS, HDR.SEQ_NO, BATCH.QTY_ON_HAND, DTL.ISS_ITEM_QTY, DTL.AUTHORIZED_ITEM_QTY, RHDR.ISSUE_SEQ_NO,HDR.FACILITY_ID,hdr.doc_type_code  UNION  SELECT ihr.doc_no issue_doc_no,ihr.seq_no seq_no, mmitm.short_desc item_desc,IHR.DOC_TYPE_CODE iss_doc_type_code,(select  short_desc from  SY_DOC_TYPE_MASTER_lang_vw where DOC_TYPE_CODE=ihr.doc_type_code and language_id=? )doc_type_desc, TO_CHAR (ihr.doc_date, 'DD/MM/YYYY') doc_date, (CASE  WHEN (    request_status IN ('A', 'P', 'L')  AND (idtl.iss_item_qty >= idtl.authorized_item_qty)  AND rhdr.issue_seq_no != ihr.seq_no )  THEN 'FULLY ISSUED'  WHEN (    request_status IN ('A', 'P', 'L')  AND (idtl.authorized_item_qty - idtl.iss_item_qty > 0)  AND rhdr.issue_seq_no != ihr.seq_no)  THEN 'PARTIALLY ISSUED'  WHEN request_status IN ('', 'E', 'W', 'A', 'P', 'C', 'L')  THEN DECODE (request_status,'', 'URGENT ISSUE','E', 'REQUEST ENTERED','W', 'AUTHORIZED AT REQ BY STORE','A', 'AUTHORIZED AT ISSUE STORE','P', 'PARTIALLY ISSUED', 'C', 'FULLY ISSUED', 'L', 'CLOSED UPON ISSUE')  END)  request_status, ihr.facility_id facility_id   FROM st_issue_dtl_exp ide, st_issue_hdr ihr, mm_bin_location mmb, st_issue_dtl idtl, mm_item mmitm, am_trade_name amtrade,st_request_hdr rhdr WHERE ide.facility_id = ?  AND idtl.item_code = mmitm.item_code   AND ide.trade_id = amtrade.trade_id(+)  AND (    ide.facility_id = ihr.facility_id  AND ide.doc_type_code = ihr.doc_type_code  AND ide.doc_no = ihr.doc_no  AND ide.seq_no = ihr.seq_no )  AND ihr.finalized_yn = 'Y'  AND ihr.fm_store_code = ?  AND ihr.to_store_code = ?  AND (ide.iss_item_qty - NVL (ide.ret_item_qty, 0)) >= 0  AND (    ihr.fm_store_code = mmb.store_code  AND ide.bin_location_code = mmb.bin_location_code )  AND idtl.facility_id = ide.facility_id  AND idtl.doc_type_code = ide.doc_type_code  AND idtl.doc_no = ide.doc_no  AND idtl.seq_no = ihr.seq_no   AND idtl.item_code = ide.item_code  AND ihr.doc_no = rhdr.doc_no(+)  AND ihr.doc_type_code = rhdr.doc_type_code(+)  AND ihr.facility_id = rhdr.facility_id(+)  AND IDTL.STOCK_ITEM_YN ='N'  /*AND ihr.doc_type_code = ?*/  AND ihr.doc_date BETWEEN TO_DATE (NVL (?, '01/01/1901'), 'DD/MM/YYYY')  AND TO_DATE (NVL (?,TO_CHAR (SYSDATE, 'DD/MM/YYYY')),'DD/MM/YYYY') AND NVL (ide.iss_item_qty, 0) - NVL (ide.ret_item_qty, 0) > 0 ";

		if(doc_no != "%")
		{	
		sql = sql + " and ihr.doc_no = " + "'"+doc_no+"'" ;
		}
		if(item_code != "%")
		{	
		sql = sql + " and ide.item_code = " + "'"+item_code+"'" ;
		}
		//Added by Sakti against HSA-CRF-0171 to pass the below parameter dynamically based on availability Inc# 48543
		if(doc_type_code != "%")
		{	
		sql = sql + " and ihr.doc_type_code = " + "'"+doc_type_code+"'" ;
		}
		//Added ends
		

		if(barcode_yn.equals("Y") && item_code != "%"){ 
		if(batch_id != "")
		{	
		sql = sql + " and ide.batch_id = " + "'"+batch_id+"'" ;
		}
		if(expiry_date != "")
		{	
		sql = sql + " and to_char(ide.expiry_date_or_receipt_date,'dd/mm/yyyy') = "+"'"+expiry_date+"'";
		}
		if(trade_id != "")
		{	
		sql = sql + " and ide.trade_id = " + "'"+trade_id+"'" ;
		}
		if(binlocation != "")
		{	
		sql = sql + " and ide.bin_location_code = " + "'"+binlocation+"'" ;
		}
		}
		sql = sql + "  ORDER BY issue_doc_no, seq_no ";

		System.out.println("sql==>"+sql);

		

		sqlMap.put("sqlData",sql);
		
			
			displayFields.add("ISSUE_DOC_NO");
			displayFields.add("ITEM_DESC");
			displayFields.add("DOC_DATE");
			displayFields.add("REQUEST_STATUS");
			displayFields.add("SEQ_NO");
			displayFields.add("FACILITY_ID");
			displayFields.add("ISSUE_DOC_TYPE"); //Added by Sakti against HSA-CRF-0171 to get ISSUE_DOC_TYPE_CODE Inc# 48543
			displayFields.add("DOC_TYPE_DESC");	 //Added by Sakti against HSA-CRF-0171 to get DOC_TYPE_DESC Inc# 48543
	

			//chkFields.add(doc_type_code); //Comented by Sakti against HSA-CRF-0171 Inc# 48543
			chkFields.add(locale);
			chkFields.add(to_store);
			chkFields.add(fm_store);
			chkFields.add(CommonBean.getLoginFacilityId());
 			chkFields.add(frm_doc_date);
 			chkFields.add(to_doc_date);
 			//chkFields.add(doc_no);
 			//chkFields.add(item_code);
 			chkFields.add(locale); //Added by Sakti against HSA-CRF-0171 Inc# 48543
 			chkFields.add((String)session.getAttribute("ACC_ENTITY_ID"));
			chkFields.add(locale); //Added by Sakti against HSA-CRF-0171 Inc# 48543
			chkFields.add(CommonBean.getLoginFacilityId());	
			chkFields.add(to_store);
			chkFields.add(fm_store);
			//chkFields.add(item_code);
			//chkFields.add(doc_no);
			//chkFields.add(doc_type_code); //comented by Sakti against HSA-CRF-0171 Inc# 48543
			chkFields.add(frm_doc_date);
 			chkFields.add(to_doc_date);

			
			funcMap.put("displayFields", displayFields);
			funcMap.put("chkFields", chkFields);
			result=(ArrayList)CommonBean.getQueryResultPage(pageContext,sqlMap, funcMap, request);
		
			if((result.size()>=3) && (!(((String) result.get(0)).equals("0")))){
	%>
			<table cellpadding=0 cellspacing=0 width="100%" align=center>
			<tr>
				<td width="80%" class="white">&nbsp;</td>
				<td width="20%" class="white">&nbsp;
				<%
					out.println(result.get(1));
				%>
				</td>
			</tr>
			</table>
			<div  style='height:80%'>
			<table border="1" cellpadding="0" cellspacing="0" width="100%" align=center>
				<tr>
					
					<th width='125'><fmt:message key="Common.DocNo.label" bundle="${common_labels}"/> / Seq No</th>
					<th width='125'><fmt:message key="Common.DocType.label" bundle="${common_labels}"/></th> <!--Added by Sakti against HSA-CRF-0171 Inc# 48543 -->
					<th width='125'><fmt:message key="Common.DocDate.label" bundle="${common_labels}"/></th>
					<th width='125'><fmt:message key="Common.item.label" bundle="${common_labels}"/></th>
					<th width='125'><fmt:message key="eST.ReqStatus.label" bundle="${st_labels}"/></th>

					
                </tr>		
   		<%
			for(int recCount=2; recCount<result.size(); recCount++) {
				if (recCount % 2 == 0)
					classvalue = "QRYEVEN" ;
				else
					classvalue = "QRYODD" ;
		%>
				<tr  >
		<%
				records=(ArrayList) result.get(recCount);
		
		%>
				<td class="<%=classvalue%>" onmouseover="changeCursor(this);"  onClick="Modify_doc('<%=(String)records.get(0)%>','<%=(String)records.get(4)%>','<%=(String)records.get(5)%>','<%=(String)records.get(6)%>');" ><font class='HYPERLINK'><%=(String)records.get(0)%>/<%=(String)records.get(4)%> </font></td>
				<td class="<%=classvalue%>" onclick="disableClick(event);"><%=records.get(7)%></td> <!--Added by Sakti against HSA-CRF-0171 Inc# 48543 -->
				<td class="<%=classvalue%>" onclick="disableClick(event);"><%=com.ehis.util.DateUtils.convertDate((String)records.get(2),"DMY","en",locale)%></td>
				<td class="<%=classvalue%>" onclick="disableClick(event);"><%=records.get(1)%></td>
				<td class="<%=classvalue%>" onclick="disableClick(event);"><%=CommonBean.checkForNull((String)records.get(3),"Fully Issued")%></td>
					</tr>
		<%	}		%>
		<tr>
		<td ></td>
		<td ></td>
		<td ></td>
		</tr>
		</table>
		</div>
		<table border="0" cellpadding="0" cellspacing="0" width="100%" height="10%">
		<tr>

		<td align="right"><input type=reset name='cancel' id='cancel'align='right' nowrap value='<fmt:message key="Common.cancel.label" bundle="${common_labels}"/>' onClick='parent.window.close()' class='Button'>
		</td>
		</tr>
		</table>
		<%
			out.flush();
		} 
		else{
		%>
			<script>
				alert(getMessage("NO_RECORD_FOUND_FOR_CRITERIA","Common"));
				document.location.href="../../eCommon/html/blank.html";
						</script>
		<%
		}
		out.println(CommonBean.setForm (request ,"../../eST/jsp/IssueReturnDocNoSearchResult.jsp", searched));
	}
	catch(Exception e) {
		out.print("Exception @ Result JSP :"+e.toString());
	}finally{
			sqlMap.clear();	
			funcMap.clear();
			displayFields.clear();
			chkFields.clear();		
			result.clear();		
			records.clear();		
	}
%>
</body>
</html>

