
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eCP.PositionForIntervention.PositionForInterventionManager
package eCP.PositionForIntervention;

/**
 * Remote interface for PositionForIntervention
 */
public interface PositionForInterventionRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap SpecialityAddModify(java.util.Properties properties, java.util.HashMap hashtable) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
