/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalHomeInterfacePlugin from eOP.QmgmtRe_AssignPract.QmgmtRe_AssignPractManager
package eOP.QmgmtRe_AssignPract;

/**
 * Local-Home interface for QmgmtRe_AssignPractManager
 */
public interface QmgmtRe_AssignPractLocalHome
extends javax.ejb.EJBLocalHome {
    public static final String COMP_NAME = "java:comp/env/ejb/QmgmtRe_AssignPractManagerLocal";
    public static final String JNDI_NAME = "QmgmtRe_AssignPractManagerLocal";

    eOP.QmgmtRe_AssignPract.QmgmtRe_AssignPractLocal create() throws javax.ejb.CreateException;
// ----------------------------------------------------------------
// Define your custom append code in a file called local-home-custom.vm
// and place it in your merge directory.
// ----------------------------------------------------------------
}
