
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eCP.AssessmentCriteriaScores.AssessmentCriteriaScoresManager
package eCP.AssessmentCriteriaScores;

/**
 * Remote interface for AssessmentCriteriaScores
 */
public interface AssessmentCriteriaScoresRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap AddModify(java.util.Properties properties, java.util.ArrayList assess_main) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
