/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eMP.TerminalDigit.TerminalDigitManager
package eMP.TerminalDigit;

/**
 * Remote interface for TerminalDigit
 */
public interface TerminalDigitRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap insertTerminalDigit(java.util.Properties p, java.lang.String addedAtWorkstation, java.lang.String addedFacilityId, java.util.HashMap tabdata, java.util.HashMap tabdata1) throws java.rmi.RemoteException;
    java.util.HashMap deleteTerminalDigit(java.util.Properties p, java.util.HashMap tabdata) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
