/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eCP.resources;

import java.util.*;

public class  Labels_zh extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eCP.AssociatedMeasures.label","相关措施"},
//		{"eCP.Associate.label","Associate"},
//		{"eCP.Associated.label","Associated"},
		{"eCP.Alt.label","备选"},
//		{"eCP.AssociateTermCode.label","Associate Term Code"},
//		{"eCP.AssessmentCategoryCode.label","Assessment Category Code"},
//		{"eCP.AssessmentCriteria.label","Assessment Criteria"},
//		{"eCP.AssessmentCategory.label","Assessment Category"},
//		{"eCP.AssessmentCategoryDescription.label","Assessment Category Description"},
//		{"eCP.AssessmentNoteDescription.label","Assessment Note Description"},
//		{"eCP.AssessmentNote.label","Assessment Note"},
//		{"eCP.AssessmentNoteId.label","Assessment Note Id"},
//		{"eCP.AssessmentCriteriaScoresQueryResult.label","AssessmentCriteriaScoresQueryResult"},
//		{"eCP.Abnormal25.label","Abnormal 2-5"},
//		{"eCP.AssessBasedDepClassification.label","AssessBasedDepClassification"},
//		{"eCP.AccuracyforCarePlan.label","Accuracy for Care Plan"},
//		{"eCP.Atleast1InterventionOutcomeexist.label","Atleast 1 Intervention/Outcome must exist in a Group"},
//		{"eCP.Atleast1InterventionOutcomeassociated.label","Atleast 1 Intervention/Outcome Group must be associated"},
//		{"eCP.Atleast1Goalassociated.label","Atleast 1 Goal must be associated"},
//		{"eCP.Atleast1Terminologyassociated.label","Atleast 1 Terminology code must be associated"},
//		{"eCP.AssessmentBasedDependencyClassification.label","Assessment Based Dependency Classification"},
//		{"eCP.AssessmentBasedTerminologyCode.label","Assessment Based Terminology Code"},
//		{"eCP.AssessmentCriteriaScore.label","Assessment Criteria Score"},
//		{"eCP.AssessmentCategoryforAssessmentNote.label","Assessment Category for Assessment Note"},
		{"eCP.AgeGroupforAssessmentNote.label","年龄组的评估说明"},
		{"eCP.BuildLibrary.label","建图书馆"},
//		{"eCP.CaseTypeNature.label","Case Type Nature"},
		{"eCP.CaseTypeCode.label","案件类型代�?"},
		{"eCP.CaseTypeDescription.label","案件类型�??述"},
		{"eCP.CaseType.label","案例类型"},
		{"eCP.CutOffScore.label","切断评分"},
		{"eCP.CategoryCode.label","目录编�?"},
		{"eCP.CategoryDescription.label","目录说明"},
		{"eCP.CriticallyAbnormal69.label","�?��?异常6-9"},
		{"eCP.CriteriaDescription.label","标准�??述"},
		{"eCP.ClassificationLevel.label","分类级别"},
		{"eCP.CarePlanScope.label","护�?�计划范围"},
		{"eCP.CarePlanAdminSetup.label","护�?�计划管�?�体制"},
		{"eCP.CriteriaforAssessmentCategory.label","评估的标准类"},
		{"eCP.CarePlanSetup.label","护�?�计划安装"},
		{"eCP.Draft.label","�?�稿"},
//		{"eCP.Dep.label","Dep"},
		{"eCP.DependencyCode.label","�?赖�?"},
		{"eCP.DependencyDescription.label","�?赖�??述"},
//		{"eCP.DiscreteMeasureforDependency.label","Discrete Measure for Dependency"},
//		{"eCP.DiscreteMeasures.label","Discrete Measures"},
		{"eCP.ExpectedOutcome.label","预期�?果"},
		{"eCP.FindStage.label","查找阶段"},
		{"eCP.FindTerminologySetForFacility.label","查找术语一套设施"},
		{"eCP.FindCaseType.label","案件类型查找"},
		{"eCP.FindAssessmentCategory.label","查找评估类"},
		{"eCP.FindAgeGroupForAssessNote.label","寻找医生类型的评估说明"},
		{"eCP.FindService.label","查找�?务"},
		{"eCP.FindReason.label","查找原因"},
		{"eCP.FindLevelofCareForDependency.label","查找一级护�?��?赖"},
		{"eCP.FindSpecialtyForAssessmentNote.label","寻找专业的评估说明"},
		{"eCP.FindDependency.label","查找�?赖"},
		{"eCP.Guideline.label","准则"},
		{"eCP.Guidelines.label","指�?�"},
		{"eCP.Goal.label","目标"},
		{"eCP.GoalDescription.label","目标�??述"},
		{"eCP.GoalDefinitionLevel.label","目标定义级别"},
		{"eCP.InterventionsOutcomes.label","干预/�?果"},
		{"eCP.Interventions.label","干预"},
		{"eCP.Intervention.label","干预"},
		{"eCP.InterventionDescription.label","干预�??述"},
		{"eCP.lllness.label","疾病？"},
		{"eCP.LibraryBasis.label","图书馆的基础"},
		{"eCP.LibraryDetails.label","图书馆详细数�?�"},
		{"eCP.LibraryID.label","图书馆编�?�"},
		{"eCP.LibraryDescription.label","图书馆说明"},
		{"eCP.Library.label","图书馆"},
		{"eCP.LOOKUP.label","查找"},
		{"eCP.LibrarySearch.label","图书馆�?�索"},
		{"eCP.LibraryforCaseType.label","图书馆的案件类型"},
		{"eCP.Months.label","本月"},
		{"eCP.MinScore.label","最低分"},
		{"eCP.MaxScore.label","最高分"},
		{"eCP.MedicationAdministrationTasks.label","�?��?管�?�任务"},
		{"eCP.NoteID.label","注�?编�?�"},
		{"eCP.NotApplicable0.label","�?适用0"},
		{"eCP.Normal1.label","正常值1"},
		{"eCP.OutcomeDescription.label","�?果说明"},
		{"eCP.Outcomes.label","�?果"},
		{"eCP.OutcomeIndicator.label","结果指标"},
		{"eCP.OutcomeCode.label","结果�?"},
		{"eCP.OutcomeEvaluationMeasures.label","�?果评价措施"},
		{"eCP.PreAdmit.label","预先接纳"},
		{"eCP.PostAdmit.label","�?�接纳"},
		{"eCP.PostDischarge.label","�?�出院"},
		{"eCP.PatientClassApplicable.label","患者级适用"},
		{"eCP.PractTypeforAssessmentNote.label","实用型的评估说明"},
		{"eCP.PatientClassforStage.label","患者级阶段"},
		{"eCP.RelativeStart.label","相对开始"},
		{"eCP.ReassessmentInterval.label","�?估区间"},
		{"eCP.ReassessmentUnit.label","�?估�?��?"},
		{"eCP.StageDescription.label","阶段�??述"},
		{"eCP.StageIndicator.label","期指标"},
		{"eCP.SexSpecific.label","性别特异性"},
		{"eCP.SubSection.label","分节"},
		{"eCP.SpecialtyForAssessmentNote.label","专业的评估说明"},
		{"eCP.TargetPeriod.label","目标期�?"},
		{"eCP.TaskforMedicationAdministration.label","任务�?�物管�?�"},
		{"eCP.TerminologySetType.label","术语设置类型"},
		{"eCP.TerminologyCodeSearch.label","术语代�?�?�索"},
		{"eCP.TerminologyCodeEvaluationMeasures.label","术语评价法典措施"},
		{"eCP.TerminologyCodeforCaseType.label","术语规范案件类型"},
		{"eCP.VersionDetails.label","版本详情"},
		{"eCP.VersionRemarks.label","版本备注"},
		{"eCP.VersionNo.label","版本�?�"},
		{"eCP.VarianceCauseCode.label","差异原因代�?"},
		{"eCP.VarianceCause.label","差异原因"},
		{"eCP.VarianceCauseDescription.label","差异原因说明"},
		{"eCP.VarianceCode.label","差异�?"},
		{"eCP.VarianceDescription.label","差异说明"},
		{"eCP.VarianceReasonCode.label","差异原因代�?"},
		{"eCP.VarianceReasonDescription.label","差异的原因说明"},
		{"eCP.Version.label","版本"},
		{"eCP.VarianceReason.label","差异原因"},
		{"eCP.Weeks.label","星期"},
		{"eCP.AssignNewCarePlanManager.label","指派新的护�?�计划�?�?�"},
		{"eCP.Achieved.label","实现"},
		{"eCP.ActionPlan.label","行动计划"},
		{"eCP.AdhocIntervention.label","特设干预"},
		{"eCP.ActivePlans.label","活动计划"},
		{"eCP.AllPlans.label","所有计划"},
		{"eCP.AssessmentDetailat.label","在详细评估"},
		{"eCP.AddNew.label","新增"},
		{"eCP.AddInterventions.label","新增干预"},
		{"eCP.AsEvidencedByFactors.label","�?明：因素："},
		{"eCP.BackdatingLimit.label","回溯�?制"},
		{"eCP.BackdateLimitForResultingOfTasks.label","回溯�?制造�?的任务"},
		{"eCP.CareManager.label","管�?�员护�?�"},
		{"eCP.CarePlanStartDate.label","护�?�计划开始日期"},
		{"eCP.CarePlanTargetDate.label","护�?�计划目标日期"},
		{"eCP.CarePlanManager.label","护�?�计划�?�?�"},
		{"eCP.CarePlanStage.label","护�?�计划阶段"},
		{"eCP.Cause.label","原因"},
		{"eCP.CutOff.label","截断"},
		{"eCP.CareManagerName.label","管�?�员护�?��??称"},
		{"eCP.CarePlanManager.label","管�?�员护�?�计划"},
		{"eCP.CarePlanManagerId.label","护�?�计划管�?�编�?�"},
		{"eCP.CarePlanId.label","护�?�计划编�?�"},
		{"eCP.CarePlans.label","护�?�计划"},
/*		{"eCP.DurationUnit.label","Duration Unit"},
		{"eCP.DurationBeforeStartTimeWhenTaskBecomesDue.label","Duration before start time when task becomes due"},
		{"eCP.DurationAfterStartTimeWhenTaskBecomesOverDue.label","Duration after start time when task becomes overdue"},
		{"eCP.DurationToPerformIntervention.label","Duration to perform Intervention"},
		{"eCP.DurationAfterEndTimeForMarkingTasksAsExpired.label","Duration after end time for marking tasks as expired"},
		{"eCP.DoYouWantAssociateOutcomeEvaluationMeasures.label","Do you want to associate outcome evaluation measures?"},
		{"eCP.DurationBeforeStartTime.label","Duration before start time"},
		{"eCP.DurationAfterStartTime.label","Duration after start time"},
		{"eCP.DurationAfterEndTime.label","Duration after end time"},
		{"eCP.d.label","(D)"},
		{"eCP.DepLvl.label","Dep Lvl"},
		{"eCP.DefinePlanScope.label","Define Plan Scope"},*/
		{"eCP.DiagnosisCaseType.label","诊断�?案例类型"},
/*		{"eCP.DefiningCharacteristics.label","Defining Characteristics:"},
		{"eCP.EndOn.label","End On"},
		{"eCP.EvaluationErrors.label","Evaluation Errors"},
		{"eCP.EvaluationErrorDate.label","Evaluation Error Date"},
		{"eCP.EvaluationRemarks.label","Evaluation Remarks"},
		{"eCP.E.label","#E"},
		{"eCP.EvaluationScore.label","Evaluation Score"},
		{"eCP.EvaluatedBy.label","Evaluated By"},
		{"eCP.EvaluatePlan.label","Evaluate Plan"},
		{"eCP.EvaluationDate.label","Evaluation Date"},
		{"eCP.EvaluationHistory.label","Evaluation History"},*/
		{"eCP.EligibleDiagnosisforCarePlan.label","�?��?�的诊断护�?�计划"},
//		{"eCP.EligibleCaseTypeforCarePlan.label","Eligible Case Type for Care Plan"},
//		{"eCP.FindInterventionType.label","Find InterventionType"},
		{"eCP.FrequencyForIntervention.label","频率的干预"},
		{"eCP.GoalStatement.label","目标声明"},
		{"eCP.Graphical.label","图解"},
		{"eCP.GuidelinesToPerformIntervention.label","准则进行干预"},
		{"eCP.GeneratePlanPreview.label","生�?计划-预览"},
		{"eCP.GeneratePlanDetail.label","生�?计划-详细"},
		{"eCP.IntermediateStatusDependency.label","中间状�?的�?赖"},
		{"eCP.InterventionCode.label","干预�?"},
		{"eCP.InterventionTypeDescription.label","干预类型�??述"},
		{"eCP.LastRevision.label","修订"},
		{"eCP.LastEvaluation.label","最�?�评价"},
		{"eCP.ListofVariances.label","�?�数列表"},
		{"eCP.MarkEvaluationError.label","标识错误"},
		{"eCP.Nex.label","下一页"},
		{"eCP.NoStandardCarePlanAvailable.label","没有标准护�?�计划�??供....."},
		{"eCP.NewAssessment.label","新的评估"},
//		{"eCP.NoofRevns.label","No of Revns"},
//		{"eCP.NoOfEvals.label","No. of Evals"},
		{"eCP.NotAchieved.label","没有实现"},
		{"eCP.OutcomeTargetDate.label","�?果目标日期"},
		{"eCP.PlanDetail.label","计划详情"},
		{"eCP.PlannedIntervention.label","计划干预"},
		{"eCP.Prev.label","�?一页"},
		{"eCP.PeriodUpto.label","期达"},
		{"eCP.PlanNo.label","计划�?�"},
		{"eCP.PartiallyAchieved.label","部分实现"},
		{"eCP.PlanSummary.label","计划摘�?"},
		{"eCP.PatientAssessmentError.label","病人评估错误"},
		{"eCP.PatientAssessmentResult.label","病人评估结果"},
		{"eCP.PatientAssessment.label","病人评估"},
		{"eCP.PatientAssessmentDiagnosis.label","病人评估诊断"},
		{"eCP.PatientAssessmentAddModify.label","病人评估新增�?修改"},
		{"eCP.PositionNote.label","�?置说明"},
		{"eCP.PositionForIntervention.label","�?置的干预"},
		{"eCP.PlanID.label","计划编�?�"},
		{"eCP.RecordButton.label","录制按钮"},
		{"eCP.ReviseCareplan.label","修改护�?�计划"},
		{"eCP.RecordPlan.label","记录计划"},
		{"eCP.ReasonForVariance.label","差异的原因"},
		{"eCP.RecordVariance.label","记录差异"},
		{"eCP.ResultMeasure.label","测�?结果"},
		{"eCP.RecClinicalNotesPrintPreviewView.label","眼科临床笔记打�?�预览"},
//		{"eCP.R.label","#R"},
		{"eCP.StartOn.label","开始"},
		{"eCP.StandardCarePlans.label","标准护�?�计划"},
		{"eCP.StandardCarePlan.label","标准护�?�计划"},
		{"eCP.SystemSuggested.label","系统建议"},
		{"eCP.SelectDiagnosistoGenerateCareplan.label","选择生�?诊断护�?�计划"},
		{"eCP.TargetDate.label","目标日期"},
//		{"eCP.Textual.label","Textual"},
		{"eCP.UserDefinedDiagnoses.label","用户定义的诊断"},
		{"eCP.UnitsFor.label","�?��?"},
		{"eCP.UseAsAdHocIntervention.label","使用特设的干预"},
		{"eCP.VarianceDate.label","差异日期"},
//		{"eCP.DurationBeforeStartTimeWhenTaskConsideredDue.label","Duration before start time when task is considered due"},
//		{"eCP.DurationAfterStartTimeWhenTaskConsideredOverdue.label","Duration after start time when task is considered overdue"},
//		{"eCP.DurationAfterEndTimeWhenTaskExpired.label","Duration after end time when task gets expired"},
//		{"eCP.BackdatingLimitForTaskResulting.label","Backdating limit for task resulting"}
//Newly added legends on 21/01/09
{"eCP.Abnormal25.label","异常2~5"},
{"eCP.AccuracyforCarePlan.label","正确的护�?�计划"},
{"eCP.AssessBasedDepClassification.label","�?赖分类的评估基础"},
{"eCP.AssessmentBasedDependencyClassification.label","基于�?赖水平的评估"},
{"eCP.AssessmentBasedTerminologyCode.label","基于术语分类评估"},
{"eCP.AssessmentCategory.label","评价分类"},
{"eCP.AssessmentCategoryCode.label","评估分类代�?"},
{"eCP.AssessmentCategoryDescription.label","评估分类�??述"},
{"eCP.AssessmentCategoryforAssessmentNote.label","评估说明的评估分类"},
{"eCP.AssessmentCriteria.label","评价标准"},
{"eCP.AssessmentCriteriaScore.label","评分标准进行评估"},
{"eCP.AssessmentCriteriaScoresQueryResult.label","查询评估标准,获得结果"},
{"eCP.AssessmentNote.label","评估说明"},
{"eCP.AssessmentNoteDescription.label","评估说明"},
{"eCP.AssessmentNoteId.label","评估说明编�?�"},
{"eCP.Associate.label","链接"},
{"eCP.Associated.label","链接于"},
{"eCP.AssociateTermCode.label","链接长期代�?"},
{"eCP.Atleast1Goalassociated.label","至少选定一个目标"},
{"eCP.Atleast1InterventionOutcomeassociated.label","至少指定一个结果组"},
{"eCP.Atleast1InterventionOutcomeexist.label","至少指定一组中的一个结果"},
{"eCP.Atleast1Terminologyassociated.label","指少选定一个术语代�?"},
{"eCP.BackdatingLimitForTaskResulting.label","任务返回�?制"},
{"eCP.CaseTypeNature.label","案例类型"},
{"eCP.d.label","D"},
{"eCP.DefinePlanScope.label","定义计划范围"},
{"eCP.DefiningCharacteristics.label","定义特�?"},
{"eCP.Dep.label","部门"},
{"eCP.DepLvl.label","部门级别"},
{"eCP.DiscreteMeasureforDependency.label","离散分�?"},
{"eCP.DiscreteMeasures.label","离散分�?"},
{"eCP.DoYouWantAssociateOutcomeEvaluationMeasures.label","需�?连接结果评价�?�?"},
{"eCP.DurationAfterEndTime.label","过期时间"},
{"eCP.DurationAfterEndTimeForMarkingTasksAsExpired.label","任务结�?�时间"},
{"eCP.DurationAfterEndTimeWhenTaskExpired.label","Duration after end time when task gets expired"},
{"eCP.DurationAfterStartTime.label","Duration after start time"},
{"eCP.DurationAfterStartTimeWhenTaskBecomesOverDue.label","Duration after start time when task becomes overdue"},
{"eCP.DurationAfterStartTimeWhenTaskConsideredOverdue.label","Duration after start time when task is considered overdue"},
{"eCP.DurationBeforeStartTime.label","Duration before start time"},
{"eCP.DurationBeforeStartTimeWhenTaskBecomesDue.label","Duration before start time when task becomes due"},
{"eCP.DurationBeforeStartTimeWhenTaskConsideredDue.label","Duration before start time when task is considered due"},
{"eCP.DurationToPerformIntervention.label","执行周期"},
{"eCP.DurationUnit.label","�?续期�?"},
{"eCP.E.label","护�?�计划"},
{"eCP.EligibleCaseTypeforCarePlan.label","选择护�?�计划"},
{"eCP.EndOn.label","超过"},
{"eCP.EvaluatedBy.label","评估"},
{"eCP.EvaluatePlan.label","评估计划"},
{"eCP.EvaluationDate.label","评估时期"},
{"eCP.EvaluationErrorDate.label","评估错误日期"},
{"eCP.EvaluationErrors.label","错误评估"},
{"eCP.EvaluationHistory.label","历�?�评估"},
{"eCP.EvaluationRemarks.label","评估备注"},
{"eCP.EvaluationScore.label","评分"},
{"eCP.FindInterventionType.label","干预类型"},
{"eCP.NoOfEvals.label","评估编�?�"},
{"eCP.NoofRevns.label","修改编�?�"},
{"eCP.R.label","护�?�计划数"},
{"eCP.Textual.label","文本"},
{"eCP.PatientInstructionsIntervention.label","Patient Instructions for Intervention"} //IN030473

	};
}
