/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eCP.resources; 

import java.util.*;

public class  Labels_ar  extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
		return contents;
	} 

	static final Object[][] contents = {
		{"eCP.AssociatedMeasures.label","القياسات المترابطة"},
		{"eCP.Associate.label","مساعد"},
		{"eCP.Associated.label","مساعد"},
		{"eCP.Alt.label","بديل"},
		{"eCP.AssociateTermCode.label","كود المصطلح المساعد"},
		{"eCP.AssessmentCategoryCode.label","كود فئة التقييم"},
		{"eCP.AssessmentCriteria.label","معايير التقييم"},
		{"eCP.AssessmentCategory.label","فئة التقييم"},
		{"eCP.AssessmentCategoryDescription.label","وصف فئة التقييم"},
		{"eCP.AssessmentNoteDescription.label","وصف مذكرة التقييم"},
		{"eCP.AssessmentNote.label","مذكرة التقييم"},
		{"eCP.AssessmentNoteId.label","كود تعريف مذكرة التقييم"},
		{"eCP.AssessmentCriteriaScoresQueryResult.label","نتيجة الاستعلام درجات معايير التقييم"},
		{"eCP.Abnormal25.label","غير طبيعي 2-5"},
		{"eCP.AssessBasedDepClassification.label","تقييم التصنيف على مستوى القسم"},
		{"eCP.AccuracyforCarePlan.label","دقة خطة الرعاية"},
		{"eCP.Atleast1InterventionOutcomeexist.label","يجب أدخل نتيجة واحدة على الأقل في مجموعة"},
		{"eCP.Atleast1InterventionOutcomeassociated.label","يجب أدخال مجموعة تدخل / نتائج واحدة على الأقل"},
		{"eCP.Atleast1Goalassociated.label","يجب ربط هدف واحد على الأقل"},
		{"eCP.Atleast1Terminologyassociated.label","يجب أن يقترن رمز المصطلحات بواحد على الأقل"},
		{"eCP.AssessmentBasedDependencyClassification.label","تصنيف التبعية على مستوى التقييم"},
		{"eCP.AssessmentBasedTerminologyCode.label","كود المصطلحات القائمة على التقييم"},
		{"eCP.AssessmentCriteriaScore.label","نقاط معايير التقييم"},
		{"eCP.AssessmentCategoryforAssessmentNote.label","فئة التقييم لملاحظة التقييم"},
		{"eCP.AgeGroupforAssessmentNote.label","الفئة العمرية لملاحظة التقييم"},
		{"eCP.BuildLibrary.label","المكتبة"},
		{"eCP.CaseTypeNature.label","نوع طبيعة الحالة"},
		{"eCP.CaseTypeCode.label","كود طبيعة الحالة"},
		{"eCP.CaseTypeDescription.label","وصف طبيعة الحالة"},
		{"eCP.CaseType.label","طبيعة الحالة"},
		{"eCP.CutOffScore.label","الحد الاقصى للرقم"},
		{"eCP.CategoryCode.label","كود الفئة"},
		{"eCP.CategoryDescription.label","وصف الفئة"},
		{"eCP.CriticallyAbnormal69.label","حالة خطرة -غير طبيعي 6-9"},
		{"eCP.CriteriaDescription.label","وصف المعايير"},
		{"eCP.ClassificationLevel.label","مستوى التصنيف"},
		{"eCP.CarePlanScope.label","نطاق خطة الرعاية"},
		{"eCP.CarePlanAdminSetup.label","إعداد إدارة خطة الرعاية"},
		{"eCP.CriteriaforAssessmentCategory.label","معايير فئة التقييم"},
		{"eCP.CarePlanSetup.label","إعداد خطة الرعاية"},
		{"eCP.Draft.label","مسودة"},
		{"eCP.Dep.label","الاعتماد"},
		{"eCP.DependencyCode.label","كود الاعتماد"},
		{"eCP.DependencyDescription.label","وصف الاعتماد"},
		{"eCP.DiscreteMeasureforDependency.label","تحديد الاجراءات الاعتمادية"},
		{"eCP.DiscreteMeasures.label","تحديد الاجراءات"},
		{"eCP.ExpectedOutcome.label","النتيجة المتوقعة"},
		{"eCP.FindStage.label","البحث عن المرحلة"},
		{"eCP.FindTerminologySetForFacility.label","البحث عن مجموعة المصطلحات للمنشأة"},
		{"eCP.FindCaseType.label","بحث نوع الحالة"},
		{"eCP.FindAssessmentCategory.label","البحث عن فئة التقييم"},
		{"eCP.FindAgeGroupForAssessNote.label","بحث نوع الطبيب لملاحظة التقييم"},
		{"eCP.FindService.label","البحث عن الخدمة"},
		{"eCP.FindReason.label","البحث عن سبب"},
		{"eCP.FindLevelofCareForDependency.label","البحث عن مستوى رعاية التبعية"},
		{"eCP.FindSpecialtyForAssessmentNote.label","البحث عن تخصص لملاحظة التقييم"},
		{"eCP.FindDependency.label","البحث بالتبعية"},
		{"eCP.Guideline.label","التوجيه"},
		{"eCP.Guidelines.label","التوجيه"},
		{"eCP.Goal.label","الاهداف"},
		{"eCP.GoalDescription.label","وصف الهدف"},
		{"eCP.GoalDefinitionLevel.label","مستوى تعريف الهدف"},
		{"eCP.InterventionsOutcomes.label","التدخلات / النتائج"},
		{"eCP.Interventions.label","التدخلات"},
		{"eCP.Intervention.label","التداخل"},
		{"eCP.InterventionDescription.label","وصف التداخل"},
		{"eCP.lllness.label","مرض"},
		{"eCP.LibraryBasis.label","أساس المكتبة"},
		{"eCP.LibraryDetails.label","تفاصيل المكتبة"},
		{"eCP.LibraryID.label","معرف المكتبة"},
		{"eCP.LibraryDescription.label","وصف المكتبة"},
		{"eCP.Library.label","مكتبة"},
		{"eCP.LOOKUP.label","ابحث عن"},
		{"eCP.LibrarySearch.label","البحث في المكتبة"},
		{"eCP.LibraryforCaseType.label","مكتبة لنوع الحالة"},
		{"eCP.Months.label","شهر/شهور"},
		{"eCP.MinScore.label","الحد الادنى من النقاط"},
		{"eCP.MaxScore.label","الحد الاقصى من النقاط"},
		{"eCP.MedicationAdministrationTasks.label","تسجيل تناول الدواء"},
		{"eCP.NoteID.label","كود الملاحظة"},
		{"eCP.NotApplicable0.label","لا ينطبق "},
		{"eCP.Normal1.label","طبيعى"},
		{"eCP.OutcomeDescription.label","وصف النتيجة"},
		{"eCP.Outcomes.label","النتائج"},
		{"eCP.OutcomeIndicator.label","مؤشر النتيجة"},
		{"eCP.OutcomeCode.label","كود النتيجة"},
		{"eCP.OutcomeEvaluationMeasures.label","مقياس  تقييم النتائج"},
		{"eCP.PreAdmit.label","قبول مسبق"},
		{"eCP.PostAdmit.label","بعد القبول"},
		{"eCP.PostDischarge.label","ما بعد الخروج"},
		{"eCP.PatientClassApplicable.label","فاعلية فئة المريض"},
		{"eCP.PractTypeforAssessmentNote.label","نوع الطبيب لملاحظة التقييم"},
		{"eCP.PatientClassforStage.label","مرحلة فئة المريض"},
		{"eCP.RelativeStart.label","البداية النسبية"},
		{"eCP.ReassessmentInterval.label","الفاصل الزمني لإعادة التقييم"},
		{"eCP.ReassessmentUnit.label","وحدة إعادة التقييم"},
		{"eCP.StageDescription.label","وصف المرحلة"},
		{"eCP.StageIndicator.label","مؤشر المرحلة"},
		{"eCP.SexSpecific.label","حدد النوع"},
		{"eCP.SubSection.label","القسم الفرعي"},
		{"eCP.SpecialtyForAssessmentNote.label"," التخصص لمذكرة للتقييم"},
		{"eCP.TargetPeriod.label","الفترة المستهدفة"},
		{"eCP.TaskforMedicationAdministration.label","مهام تناول الدواء"},
		{"eCP.TerminologySetType.label","نوع مجموعة المصطلحات"},
		{"eCP.TerminologyCodeSearch.label","البحث برمز المصطلحات"},
		{"eCP.TerminologyCodeEvaluationMeasures.label","كود مصطلح تقييم القياس "},
		{"eCP.TerminologyCodeforCaseType.label","رمز المصطلحات لنوع الحالة"},
		{"eCP.VersionDetails.label","تفاصيل الإصدار"},
		{"eCP.VersionRemarks.label","ملاحظات الإصدار"},
		{"eCP.VersionNo.label","رقم الإصدار"},
		{"eCP.VarianceCauseCode.label","كود حالة التباين"},
		{"eCP.VarianceCause.label"," حالة التباين"},
		{"eCP.VarianceCauseDescription.label","وصف حالة التباين"},
		{"eCP.VarianceCode.label","كود التباين"},
		{"eCP.VarianceDescription.label","وصف التباين"},
		{"eCP.VarianceReasonCode.label","كود  سبب التباين"},
		{"eCP.VarianceReasonDescription.label","وصف سبب التباين"},
		{"eCP.Version.label","الإصدار"},
		{"eCP.VarianceReason.label"," سبب التباين"},
		{"eCP.Weeks.label","اسبوع/اسابيع"},
		{"eCP.AssignNewCarePlanManager.label","تعيين مدير جديد لخطة الرعاية"},
		{"eCP.Achieved.label","حقق"},
		{"eCP.ActionPlan.label","خطة عمل"},
		{"eCP.AdhocIntervention.label","التدخل المخصص"},
		{"eCP.ActivePlans.label","الخطط الفعالة"},
		{"eCP.AllPlans.label","جميع الخطط"},
		{"eCP.AssessmentDetailat.label","تفاصيل التقييم في"},
		{"eCP.AddNew.label","اضف جديد"},
		{"eCP.AddInterventions.label","أضف التدخلات"},
		{"eCP.AsEvidencedByFactors.label","كما يتضح من: العوامل:"},
		{"eCP.BackdatingLimit.label","حد الرجوع إلى الخلف"},
		{"eCP.BackdateLimitForResultingOfTasks.label","حد الرجوع للخلف لتنفيذ المهام"},
		{"eCP.CareManager.label","مدير الرعاية"},
		{"eCP.CarePlanStartDate.label","تاريخ بداية خطة الرعاية"},
		{"eCP.CarePlanTargetDate.label","التاريخ المستهدف لخطة الرعاية"},
		{"eCP.CarePlanManager.label","مدير خطة الرعاية"},
		{"eCP.CarePlanStage.label","حالة خطة الرعاية"},
		{"eCP.Cause.label","سبب"},
		{"eCP.CutOff.label","توقف"},
		{"eCP.CareManagerName.label","أسم مدير الرعاية"},
		{"eCP.CarePlanManager.label","مدير خطة الرعاية"},
		{"eCP.CarePlanManagerId.label","كود مدير خطة الرعاية"},
		{"eCP.CarePlanId.label","كود خطة الرعاية"},
		{"eCP.CarePlans.label","خطط الرعاية"},
		{"eCP.DurationUnit.label","وحدة المدة"},
		{"eCP.DurationBeforeStartTimeWhenTaskBecomesDue.label","المدة قبل وقت البدء عندما تصبح المهمة مستحقة"},
		{"eCP.DurationAfterStartTimeWhenTaskBecomesOverDue.label","المدة بعد وقت البدء عندما تصبح المهمة متأخرة"},
		{"eCP.DurationToPerformIntervention.label","المدة اللازمة لأداء التدخل"},
		{"eCP.DurationAfterEndTimeForMarkingTasksAsExpired.label","المدة التي تلي وقت الانتهاء لوضع علامة على المهام باعتبارها منتهية الصلاحية"},
		{"eCP.DoYouWantAssociateOutcomeEvaluationMeasures.label","هل تريد ربط مقاييس تقييم النتائج؟"},
		{"eCP.DurationBeforeStartTime.label","المدة قبل وقت البدء"},
		{"eCP.DurationAfterStartTime.label","المدة بعد وقت البدء"},
		{"eCP.DurationAfterEndTime.label","المدة بعد وقت الانتهاء"},
		{"eCP.d.label","(D)"},
		{"eCP.DepLvl.label","مستوى الاعتماد"},
		{"eCP.DefinePlanScope.label","تعريف نتيجة الخطة"},
		{"eCP.DiagnosisCaseType.label","التشخيص/نوع الحالة"},
		{"eCP.DefiningCharacteristics.label","تحديد الخصائص:"},
		{"eCP.EndOn.label","انتهى فى "},
		{"eCP.EvaluationErrors.label"," خطأ فى  التقييم"},
		{"eCP.EvaluationErrorDate.label"," خطأ فى تاريخ التقييم"},
		{"eCP.EvaluationRemarks.label","ملاخظات التقييم"},
		{"eCP.E.label","#E"},
		{"eCP.EvaluationScore.label","نتيجة التقييم"},
		{"eCP.EvaluatedBy.label","تقييم بواسطة"},
		{"eCP.EvaluatePlan.label","الخطة تقييم "},
		{"eCP.EvaluationDate.label","تاريخ التقييم"},
		{"eCP.EvaluationHistory.label","تاريخ التقييم"},
		{"eCP.EligibleDiagnosisforCarePlan.label","التشخيص المؤهل لخطة الرعاية"},
		{"eCP.EligibleCaseTypeforCarePlan.label","نوع الحالة المؤهلة لخطة الرعاية"},
		{"eCP.FindInterventionType.label","بحث عن نوع التدخل"},
		{"eCP.FrequencyForIntervention.label","تردد المدخلات"},
		{"eCP.GoalStatement.label","بيان الهدف"},
		{"eCP.Graphical.label","بياني / تخطيطي"},
		{"eCP.GuidelinesToPerformIntervention.label","مبادئ توجيهية لأداء التدخل"},
		{"eCP.GeneratePlanPreview.label","إنشاء خطة - مراجعة"},
		{"eCP.GeneratePlanDetail.label","إنشاء خطة - التفاصيل"},
		{"eCP.IntermediateStatusDependency.label","حالة التبعية المتوسطة"},
		{"eCP.InterventionCode.label","كود التدخل"},
		{"eCP.InterventionTypeDescription.label","وصف نوع التدخل"},
		{"eCP.LastRevision.label","آخر مراجعة"},
		{"eCP.LastEvaluation.label","آخر تقييم"},
		{"eCP.ListofVariances.label","قائمة الفروق"},
		{"eCP.MarkEvaluationError.label","علامة خطأ في التقييم"},
		{"eCP.Nex.label","التالى"},
		{"eCP.NoStandardCarePlanAvailable.label","لا توجد خطة رعاية  متوفرة ....."},
		{"eCP.NewAssessment.label","تقييم جديد"},
		{"eCP.NoofRevns.label","No of Revns"},
		{"eCP.NoOfEvals.label","No. of Evals"},
		{"eCP.NotAchieved.label","غير منجز"},
		{"eCP.OutcomeTargetDate.label","تاريخ النتيجة المستهدفة "},
		{"eCP.PlanDetail.label","تفصيل الخطة"},
		{"eCP.PlannedIntervention.label","خطة التدخل "},
		{"eCP.Prev.label","السابق"},
		{"eCP.PeriodUpto.label","فترة تصل الى"},
		{"eCP.PlanNo.label","رقم الخطة"},
		{"eCP.PartiallyAchieved.label","أُنجز جزئياً"},
		{"eCP.PlanSummary.label","ملخص الخطة"},
		{"eCP.PatientAssessmentError.label","خطأ في تقييم المريض"},
		{"eCP.PatientAssessmentResult.label","نتيجة تقييم المريض"},
		{"eCP.PatientAssessment.label"," تقييم المريض"},
		{"eCP.PatientAssessmentDiagnosis.label","تقييم تشخيص المريض"},
		{"eCP.PatientAssessmentAddModify.label"," إضافة / تعديل تقييم المريض"},
		{"eCP.PositionNote.label","ملاحظات على الوضع"},
		{"eCP.PositionForIntervention.label","وضع للتدخل"},
		{"eCP.PlanID.label","كود الخطة"},
		{"eCP.RecordButton.label","زر التسجيل"},
		{"eCP.ReviseCareplan.label","مراجعة خطة الرعاية"},
		{"eCP.RecordPlan.label","تسجيل الخطة"},
		{"eCP.ReasonForVariance.label","سبب التباين"},
		{"eCP.RecordVariance.label","سجل التباين"},
		{"eCP.ResultMeasure.label","قياس النتيجة"},
		{"eCP.RecClinicalNotesPrintPreviewView.label","سجل الملاحظات السريرية معاينة قبل الطباعة"},
		{"eCP.R.label","#R"},
		{"eCP.StartOn.label","ابدأ في"},
		{"eCP.StandardCarePlans.label","خطط العلاج الاساسية"},
		{"eCP.StandardCarePlan.label","خطة العلاج الاساسية"},
		{"eCP.SystemSuggested.label","اقترح النظام"},
		{"eCP.SelectDiagnosistoGenerateCareplan.label","تحديد تشخيص لإنشاء خطة رعاية"},
		{"eCP.TargetDate.label","التاريخ المستهدف"},
		{"eCP.Textual.label","نصي"},
		{"eCP.UserDefinedDiagnoses.label","تشخيصات من تحديد المستخدم"},
		{"eCP.UnitsFor.label","وحدات لـ"},
		{"eCP.UseAsAdHocIntervention.label","استخدم كتدخل للإعلان"},
		{"eCP.VarianceDate.label","تاريخ التباين"},
		{"eCP.DurationBeforeStartTimeWhenTaskConsideredDue.label","المدة قبل وقت البدء عندما تعتبر المهمة مستحقة"},
		{"eCP.DurationAfterStartTimeWhenTaskConsideredOverdue.label","المدة بعد وقت البدء عندما تعتبر المهمة متأخرة"},
		{"eCP.DurationAfterEndTimeWhenTaskExpired.label","المدة بعد وقت الانتهاء عند انتهاء صلاحية المهمة"},
		{"eCP.BackdatingLimitForTaskResulting.label","حد الرجوع إلى الخلف للمهمة الناتجة"},
		{"eCP.PatientInstructionsIntervention.label","تعليمات المريض للتدخل"}
	};
}