/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eSS.resources;

import java.util.*;

public class  Labels_zh  extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }


	static final Object[][] contents = {
		{"eSS.DocNo.label","档编�?�生�?"},
		{"eSS.DocDate.label","檔日期"},
		{"eSS.ServiceLocation.label","�?务定�?"},
		{"eSS.SurgeryType.label","手术类型"},
		{"eSS.GroupType.label","集团类型"},
		{"eSS.UsageType.label","使用类型"},
		{"eSS.AlternateGroupCode.label","集团代�?备用"},
		{"eSS.GroupCode.label","集团代�?"},
		{"eSS.GroupDescription.label","集团�??述"},
		{"eSS.AlternateGroupDescription.label","替�?�组说明"},
		{"eSS.TrayNo.label","托盘�?�"},
//		{"eSS.BinLocation.label","Bin Location"},
		{"eSS.DocRef.label","文件编�?�"},
		{"eSS.TotalValue.label","总价值"},
		{"eSS.CutoffDate.label","截止日期"},
//		{"eSS.AutoclaveUnit.label","Autoclave Unit"},
		{"eSS.SterilizationType.label","�?��?�型"},
		{"eSS.LoadNo.label","无负�?�"},
		{"eSS.UnitType.label","�?��?类型"},
		{"eSS.LongDesc.label","长�??述"},
		{"eSS.ShortDesc.label","短�??述"},
		{"eSS.Temperature.label","温度"},
		{"eSS.UnitCondition.label","�?��?�?�件"},
		{"eSS.AutoclaveWashTest.label","�?��?�/清洗试验"},
		{"eSS.BatchID.label","批�?编�?�"},
		{"eSS.TestResult.label","试验结果"},
		{"eSS.ResultDate.label","结果日期"},
		{"eSS.AutoclaveWashUnit.label","�?��?�/清洗�?��?"},
		{"eSS.TestDate.label","测试日期"},
		{"eSS.EnteredBy.label","进入"},
		{"eSS.EntryCompleted.label","输入完�?"},
		{"eSS.Pass.label","通行�?"},
		{"eSS.Fail.label","失败"},
		{"eSS.Entry.label","输入"},
		{"eSS.Notcompleted.label","未完�?"},
		{"eSS.AutoclaveWashUnit.label","�?��?�/清洗�?��?"},
		{"eSS.AutoclaveWashingUnit.label","�?��?�/清洗�?��?"},
		{"eSS.Autoclave.label","�?��?�？"},
		{"eSS.Washing.label","洗衣机"},
		{"eSS.AutoclaveDate.label","�?��?�日期"},
//		{"eSS.LoadStatus.label","Load Status"},
//		{"eSS.OldLoadNo.label","Old Load No"},
//		{"eSS.ROFDocType.label","ROF Doc Type"},
//		{"eSS.ROFDocNo.label","ROF Doc No"},
//		{"eSS.AutoclavingUnit.label","Autoclaving Unit"},
//		{"eSS.LoadNumber.label","Load Number"},
		{"eSS.AutoclavingDate.label","�?��?�日期"},
//		{"eSS.PhysicalInvId.label","Physical Inv Id"},
		{"eSS.OwnerStore.label","店主"},
		{"eSS.CurrentStore.label","目�?商店"},
		{"eSS.Owner.label","所有者"},
		{"eSS.RequestedQuantity.label","�?求数�?"},
		{"eSS.IssuedQuantity.label","�?�行数�?"},
		{"eSS.RequestedOn.label","�?求"},
		{"eSS.RequestType.label","申请类型"},
		{"eSS.CancellationRemarks.label","�?�消备注"},
		{"eSS.RequisitionbyStore.label","�?用的店铺"},
		{"eSS.RequisitiononStore.label","�?用的店铺"},
		{"eSS.RequestedbyStore.label","�?求店铺"},
		{"eSS.RequestedonStore.label","�?求店铺"},
//		{"eSS.OldBinLocation.label","Old Bin Location"},
//		{"eSS.NewBinLocation.label","New Bin Location"},
		{"eSS.GroupType.label","组类型"},
		{"eSS.TraySearch.label","托盘�?�索"},
		{"eSS.Set.label","设置"},
		{"eSS.Tray.label","托盘"},
//		{"eSS.SoftPack.label","Soft Pack"},
		{"eSS.AutoclaveWashingTest.label","�?��?�/清洗试验"},
		{"eSS.WriteoffReason.label","注销原因"},
		{"eSS.SubClassification.label","�?组分类"},
		{"eSS.SterilizationProcessStage.label","消毒过程阶段"},
		{"eSS.WashingType.label","洗衣机类型"},
		{"eSS.StatisticalGroup.label","统计组"},
		{"eSS.CSSDStore.label","消毒商店"},
		{"eSS.CSSDItem.label","消毒项目"},
		{"eSS.CSSDGroup.label","消毒组"},
		{"eSS.SterilizationCost.label","�?��?��?本"},
		{"eSS.AlternateGroup.label","人物组"},
		{"eSS.GroupforStore.label","�?组的店铺"},
		{"eSS.ConfirmAuthorize.label","确认授�?�"},
		{"eSS.ConfirmCancel.label","确认�?�消"},
		{"eSS.ConfirmDelete.label","确认删除"},
		{"eSS.DeleteAllItems.label","删除所有项目"},
		{"eSS.ConfirmFinalize.label","确认完�?"},
		{"eSS.Finalize.label","最�?�"},
		{"eSS.DescrepancyEnteredAt.label","差异输入"},
		{"eSS.Discrepancy.label","差异"},
		{"eSS.DiscrepancyQty.label","数�?差异"},
		{"eSS.DiscrepancyType.label","差异类型"},
		{"eSS.DiscrepancyReason.label","差异原因"},
		{"eSS.BillingType.label","结算类型"},
		{"eSS.EnteredAt.label","输入"},
//		{"eSS.SterReqDocType.label","Ster Req Doc Type"},
//		{"eSS.SterReqDocNo.label","Ster Req Doc No"},
		{"eSS.Contaminated.label","污染"},
		{"eSS.Sterilization.label","�?��?�"},
		{"eSS.Hold.label","�?有"},
		{"eSS.Dispatch.label","调度"},
		{"eSS.DispatchDate.label","调度日期"},
		{"eSS.ReturnFrom.label","退回"},
		{"eSS.ReturnTo.label","退回"},
		{"eSS.PrintSterilizationRequest.label","打�?��?��?��?求"},
		{"eSS.WithDiscrepancy.label","有差异"},
		{"eSS.WithoutDiscrepancy.label","无差异"},
		{"eSS.AlphaCode.label","阿尔法�?"},
		{"eSS.Non-returnable.label","�?��?�回收"},
		{"eSS.ItemClass.label","专案分类"},
		{"eSS.ItemAnalysis.label","项目分�?"},
		{"eSS.Packing.label","包装"},
		{"eSS.PackItem.label","包装项目"},
		{"eSS.PackItemQty.label","包装项目数�?"},
		{"eSS.PackAddlCost.label","包装�?本"},
		{"eSS.ItemQty.label","项目数�?"},
		{"eSS.Association.label","�??会"},
		{"eSS.StoreCode.label","存储代�?"},
		{"eSS.StoreDescription.label","存储说明"},
		{"eSS.Surgery.label","手术"},
		{"eSS.Usage.label","用法"},
		{"eSS.NonReturable.label","�?�?�回收"},
		{"eSS.Instrument.label","仪器"},
		{"eSS.DiscrepancyQuantity.label","数�?差异"},
		{"eSS.Del.label","删除"},
		{"eSS.InstrumentDescription.label","仪器说明"},
		{"eSS.TrayNoSearch.label","查询托盘�?�"},
		{"eSS.ReqGroup.label","请求组"},
		{"eSS.AuthGroup.label","认�?组"},
		{"eSS.IssueGroup.label","�?�行组"},
		{"eSS.IssueCost.label","�?�行�?本"},
		{"eSS.ReqDocType.label","请求档类型"},
		{"eSS.ReqDocNo.label","请求档�?�"},
		{"eSS.IssueStore.label","�?�出库房"},
		{"eSS.ReceivingStore.label","接收库房"},
		{"eSS.PendingIssues.label","悬而未决的问题"},
		{"eSS.Consumable.label","耗�??"},
		{"eSS.Chargeable.label","�?收"},
		{"eSS.Remarks.label","备注"},
		{"eSS.ProcessStage.label","进程阶段"},
		{"eSS.ProcessRemarks.label","进程备注"},
		{"eSS.UserAccessforStoreList.label","用户访问的库房�??�?�"},
		{"eSS.TrayDetails.label","托盘详情"},
		{"eSS.InstrumentsusedforPatientsList.label","用于患者�??�?�的仪器"},
		{"eSS.TrayValues.label","托盘值"},
		{"eSS.DepartmentChargeDetails.label","部门收费详情"},
		{"eSS.ChargesSummary.label","收费综述"},
		{"eSS.AgeingAnalysis.label","�?龄化问题分�?"},
		{"eSS.PackCost.label","包装�?本"},
		{"eSS.HoldReason.label","�?�?�?�性"},
		{"eSS.PackingDate.label","包装日期"},
		{"eSS.Cost.label","�?本"},
		{"eSS.DiscrepancyDetails.label","差异详情"},
		{"eSS.Sterilize.label","消毒"},
		{"eSS.Wash.label","洗"},
		{"eSS.Update.label","更新"},
		{"eSS.PackQty.label","包装数�?"},
		{"eSS.CurrentProcessingMonthYear.label","当�?处�?�月/年"},
		{"eSS.Billing.label","账�?�"},
		{"eSS.BillingService.label","结算�?务"},
		{"eSS.GeneralLedger.label","总�?"},
		{"eSS.PrepareGroup.label","编写组"},
		{"eSS.RequestGroup.label","�?求组"},
		{"eSS.ReturnGroup.label","返回组"},
		{"eSS.ReturnInstrument.label","返回仪器"},
		{"eSS.TrayDiscrepancy.label","托盘差异"},
		{"eSS.WriteOff.label","注销"},
		{"eSS.Variance.label","差异"},
		{"eSS.ProcessSterilizationRequest.label","�?��?�工艺�?求"},
		{"eSS.SterileLife.label","无�?�生活"},
		{"eSS.ItemImagePath.label","项目图片路径"},
		{"eSS.GenerateSterilizationRequestwhilepreparing.label","准备生�?无�?��?求"},
		{"eSS.Interface.label","界�?�"},
		{"eSS.DefaultDocumentTypes.label","默认文件类型"},
		{"eSS.OtherDefaults.label","其它默认"},
		{"eSS.StoreforPrepareGroup.label","准备组的库房"},
		{"eSS.CurrentProcessMonthYear.label","目�?的进程月/年"},
		{"eSS.CountSheetDate.label","计数表日期"},
		{"eSS.PhyInvID.label","物�?�库存�?�"},
		{"eSS.AutoclavedDate.label","清洗日期"},
		{"eSS.Finalized.label","完�?"},
		{"eSS.AutoclaveWashTest.label","高压清洗试验"},
		{"eSS.AutoclaveWashUnitCode.label","高压清洗�?��?代�?"},
		{"eSS.ReportOrder.label","报告订�?�"},
		{"eSS.CutoffDate.label","截止日期"},
		{"eSS.InstrumentStatus.label","仪器状�?"},
//		{"eSS.SterReqStatus.label","Ster Req Status"},
		{"eSS.StoreType.label","库房类型"},
		{"eSS.TrayStatus.label","托盘状�?"},
		{"eSS.Unsterilized.label","未�?消毒的"},
		{"eSS.Sterilized.label","�?��?�"},
		{"eSS.AtServiceLocation.label","�?务�?置"},
		{"eSS.DocTypeCode.label","档类别代�?"},
		{"eSS.EntryStatus.label","输入状�?"},
		{"eSS.FinalizedStatus.label","定稿状�?"},
		{"eSS.ReqQuantity.label","请求�?"},
		{"eSS.AvailableSterilizedQuantity.label","消毒�?�用数�?"},
		{"eSS.Authorization.label","授�?�"},
		{"eSS.Issue.label","问题"},
		{"eSS.ReqByStore.label","请求店铺"},
		{"eSS.ReqOnStore.label","请求商店"},
		{"eSS.Requestquantity.label","申请�?"},
		{"eSS.RequestDetails.label","申请明细"},
		{"eSS.Entered.label","输入"},
		{"eSS.Issued.label","�?�出"},
		{"eSS.NotIssued.label","未�?�出"},
		{"eSS.FullyIssued.label","完全�?�出"},
		{"eSS.PartiallyIssued.label","部分�?�出"},
		{"eSS.Expired.label","过期"},
		{"eSS.ChargeConsumables.label","耗�??费用"},
		{"eSS.ReturnableInstrument.label","回收仪器"},
		{"eSS.ChargeOption.label","费用�?作"},
		{"eSS.ReceiptReference.label","�?�考收�?�"},
		{"eSS.Charge.label","费用"},
//		{"eSS.Deposit.label","Deposit"},
//		{"eSS.ChgConsum.label","Chg Consum"},
		{"eSS.ReturnFromStore.label","返回库房"},
		{"eSS.ReturnToStore.label","返回库房"},
		{"eSS.SelectTrays-ReturnGroup.label","选择托盘-返回组"},
		{"eSS.FromStore.label","从库房"},
		{"eSS.ToStore.label","库房类型"},
		{"eSS.UnFinalized.label","未完�?"},
		{"eSS.GroupTrayNoItem.label","组/托盘�?�/项目"},
		{"eSS.Damaged.label","�?��??"},
		{"eSS.ReturnQty.label","返回数�?"},
		{"eSS.ReturningStore.label","返回商店"},
//		{"eSS.EnteredDt.label","Entered Dt"},
//		{"eSS.CheckedDt.label","Checked Dt"},
//		{"eSS.WashedDt.label","Washed Dt"},
//		{"eSS.PackedDt.label","Packed Dt"},
//		{"eSS.AutoclavedDt.label","Autoclaved Dt"},
//		{"eSS.DispatchedDt.label","Dispatched Dt"},
//		{"eSS.Ack.Dt.label","Ack.Dt"},
		{"eSS.CheckedBy.label","检查"},
		{"eSS.WashedBy.label","洗"},
		{"eSS.PackedBy.label","装"},
//		{"eSS.AutoclavedBy.label","Autoclaved By"},
		{"eSS.DispatchedBy.label","派�?�"},
//		{"eSS.Ack.By.label","Ack.By"},
		{"eSS.SterilizationRequestUserDetail.label","用户详细的�?��?��?求"},
		{"eSS.ImagePreview.label","图�?预览"},
		{"eSS.ImageURL.label","图片网�?�"},
		{"eSS.InvalidPageCall.label","无效的页�?�调用"},
		{"eSS.Countbycomponents.label","组件计算"},
		{"eSS.Countby.label","计算"},
		{"eSS.Components.label","组件"},
		{"eSS.MonthlyServiceStatistics.label","�?月�?务统计"},
		{"eSS.MonthlyServiceStatisticsByStores.label","库房的�?月�?务统计"},
		{"eSS.GroupMovementStatistics.label","Group Movement Statistics"},
		{"eSS.TraysUsageStatistics.label","托盘使用统计"},
		{"eSS.AutoclavingLoadFailureStatistics.label","高压清洗故障统计"},
		{"eSS.TrayDiscrepancyStatistics.label","托盘出入统计"},
		{"eSS.MonthlyServiceStatisticsByGroups.label","�?月的�?务统计组"},
		{"eSS.SterileType.label","无�?�类型"},
		{"eSS.SterileCost.label","无�?��?本"},
		{"eSS.SterileTypeDescription.label","无�?�类型�??述"},
		{"eSS.SterilizationRequestList.label","无�?��?求清�?�"},
		{"eSS.PackingCheckList.label","包装清�?�"},
		{"eSS.SterileLabel.label","无�?�标签"},
		{"eSS.DispatchList.label","调度列表"},
//		{"eSS.AcknowledgementList.label","Acknowledgement List"},
		{"eSS.PackLabel.label","包装标签"},
//		{"eSS.AutoclavingLoadDetails.label","Autoclaving Load Details"},
//		{"eSS.AutoclaveWashUnitTestDetails.label","Autoclave/Wash Unit Test Details"},
//		{"eSS.AutoclavingLoadSummary.label","Autoclaving Load Summary"},
//		{"eSS.RequestOrderTraysStatus.label","Request Order Trays Status"},
//		{"eSS.RequestOrderTraysStatusSummary.label","Request Order Trays Status Summary"},
		{"eSS.SterilizationRequestProcessTimingDetails.label","�?��?��?求的时间详细过程"},
		{"eSS.UseWithin.label","内部使用"},
		{"eSS.InServiceLocation.label","在�?务�?置"},
		{"eSS.SterilizationRequest.label","�?��?��?求"},
		{"eSS.Transaction.label","交易"},
		{"eSS.DiscReason.label","折扣原因"},
		{"eSS.Returnable.label","�?�回收"},
		{"eSS.Nonreturnable.label","�?��?�回收"},
		{"eSS.AtUnits.label","�?��?"},
		{"eSS.AtOwner.label","所有者"},
		{"eSS.TRNType.label","TRN Type"},
		{"eSS.DocTypeDescription.label","档类型�??述"},
//		{"eSS.TRNTypeDescription.label","TRN Type Description"},
		{"eSS.Prepare.label","准备"},
		{"eSS.Return.label","返回"},
		{"eSS.Write.label","写"},
		{"eSS.Physical.label","物�?�"},
		{"eSS.SterilizationRequestProcessing.label","�?��?��?求处�?�"},
		{"eSS.UserAccessforStoreListing.label","用户访问的库房列表"},
		{"eSS.Instruments.label","仪器"},
//		{"eSS.off.label","off"},
		{"eSS.ReturnInstruments.label","返回仪器"},
		{"eSS.PhysicalVariance.label","物�?�差异"},
		{"eSS.WashingUnit.label","洗涤�?��?"},
		{"eSS.WashingCompleted.label","洗涤完�?"},
		{"eSS.SterilizationTypeDescription.label","�?��?�类型�??述"},
		{"eSS.WriteOffCost.label","注销费用"},
		{"eSS.FailureCount.label","故障计数"},
		{"eSS.Lowest.label","最低"},
		{"eSS.Highest.label","最高"},
		{"eSS.NoOfTraysPertainingTo.label","相关的托盘�?�"},
		{"eSS.Before.label","之�?"},
		{"eSS.Passed.label","通过"},
		{"eSS.Failed.label","失败"},
		{"eSS.TestCode.label","测试代�?"},
		{"eSS.TestDescription.label","测试�??述"},
		{"eSS.Autoclave.label","高压清洗"},
		{"eSS.GrandTotal.label","总计"},
		{"eSS.InsCost.label","内部�?本"},
//		{"eSS.ConsCost.label","Cons Cost"},
		{"eSS.DepartmentTotal.label","总门总计"},
		{"eSS.StoreTotal.label","库房总数"},
		{"eSS.GrpType.label","组类型"},
		{"eSS.Expiry.label","过期"},
		{"eSS.ReceivedBy.label","收到的"},
		{"eSS.QtyOnHand.label","目�?数�?"},
		{"eSS.GroupRemarks.label","组备注"},
		{"eSS.PackComponents.label","包组件"},
		{"eSS.PrepareDate.label","编写日期"},
		{"eSS.SterileCount.label","无�?�计算"},
		{"eSS.LastIssueDate.label","上次�?�出日期"},
//		{"eSS.PresentSterCount.label","Present Ster. Count"},
		{"eSS.RequestOn.label","�?求"},
		{"eSS.IssueDate.label","�?�行日期"},
		{"eSS.ImagFile.label","图�?文件"},
		{"eSS.AuthorizedSignatory.label","授�?��?�签署"},
//		{"eSS.ItemsPacksProcessedandIssuedDuringthePeriod .label","Items/Packs Processed and Issued During the Period"},
		{"eSS.OverallItemsPacksProcessed.label","整体项目包装/加工"},
		{"eSS.TotalNoofSterilizationCycles.label","共计消毒周期"},
		{"eSS.DetailsoftheItemsPacksProcessed.label","物�?详情/包装过程"},
		{"eSS.DetailsOftheTotalNumberofSterilizationCycles.label","�?��?�周期的详情总数"},
		{"eSS.NoofCycles.label","循环�?�"},
		{"eSS.SubClass.label","�?类"},
		{"eSS.QuantitySterilized.label","�?��?�数�?"},
		{"eSS.Instrument.label","仪器"},
		{"eSS.IssueDate.label","�?�出日期"},
		{"eSS.TotalQty.label","总数�?"},
		{"eSS.ReturnedQty.label","返回数�?"},
		{"eSS.PendingQty.label","数�?待定"},
		{"eSS.ReturnEnteredBy.label","返回输入"},
//		{"eSS.PhysicalBinLocation.label","Physical Bin Location"},
		{"eSS.SystemStock.label","系统库存"},
		{"eSS.PhysicalStock.label","实物库存"},
		{"eSS.Surgery.label","手术"},
		{"eSS.Usage.label","用法"},
		{"eSS.Cons.label","�?守派"},
		{"eSS.StandQty.label","标准数�?"},
		{"eSS.CurrQty.label","当�?数�?"},
		{"eSS.OT.label","手术"},
//		{"eSS.IN.label","IN"},
//		{"eSS.OUT.label","OUT"},
		{"eSS.CSSD.label","消毒系统"},
		{"eSS.EncounterLabel.label","�?�到标签"},
		{"eSS.PatientLabel.label","病人标签"},
		{"eSS.Theater.label","手术室"},
		{"eSS.Surgeon.label","外科医生"},
//		{"eSS.PackedOn.label","Packed On"},
		{"eSS.RequestQty.label","申请数�?"},
		{"eSS.IssueQty.label","�?�出数�?"},
		{"eSS.WashEnteredDate.label","清洗输入日期"},
		{"eSS.WashCompletedDate.label","清洗完�?日期"},
		{"eSS.LoadedDate.label","装载日期"},
		{"eSS.LoadCompletedDate.label","装载完�?日期"},
		{"eSS.AcknowledgementDate.label","确认日期"},
		{"eSS.CheckingDt.label","检查�?�物疗法"},
		{"eSS.Sterilize.label","消毒"},
		{"eSS.NoofTrays.label","托盘�?�"},
		{"eSS.SterilizedBy.label","消毒"},
		{"eSS.AllowedTransactions.label","�?许交易"},
//		{"eSS.ProcessROF.label","Process ROF"},
		{"eSS.Returnable.label","�?�回收"},
		{"eSS.PreparedOn.label","编写"},
		{"eSS.PreparedBy.label","准备"},
		{"eSS.MonthYear.label","月/年"},
		{"eSS.SterilizeCount.label","消毒计数"},
		{"eSS.SurgeryCode.label","手术代�?"},
//		{"eSS.ConsValue.label","Cons Value"},
//		{"eSS.InsValue.label","Ins Value"},
		{"eSS.SurgeryTypeDescription.label","手术类型�??述"},
		{"eSS.ServiceLocationDescription.label","�?务定�?�??述"},
		{"eSS.AutoclaveWashUnitDescription.label","�?��?�/清洗�?��?�??述"},
		{"eSS.NonOwner.label","�?�所有者"},
		{"eSS.Store.label","存储"},
		{"eSS.SterileLife.label","无�?�生活"},
		{"eSS.UseWithin.label","内部使用"},
		{"eSS.Readytouse.label","准备使用"},
		{"eSS.Notreadytouse.label","�?准备使用"},
		{"eSS.AutoclaveWashingTestDescription.label","高压清洗/清洗试验说明"},
		{"eSS.TotalTray(s).label","共计托盘"},
		{"eSS.WriteoffReasonDiscrepancy.label","注销原因/差异"},
		{"eSS.WriteoffReasonDiscrepancyDescription.label","注销原因/差异说明"},
		{"eSS.UsageTypeDescription.label","使用类型�??述"},
		{"eSS.SubClassificationCode.label","�?分类代�?"},
		{"eSS.SubClassificationDescription.label","�?分类说明"},
		{"eSS.ProcessStageCode.label","进程阶段代�?"},
		{"eSS.ProcessStageDescription.label","进程阶段�??述"},
		{"eSS.WashingTypeDescription.label","洗涤类型�??述"},
		{"eSS.StatisticalGroupCode.label","统计组代�?"},
		{"eSS.StatisticalGroupDescription.label","统计�?组�??述"},
		{"eSS.Pack.label","包装"},
		{"eSS.ImageFile.label","图�?文件"},
		{"eSS.NonConsumable.label","�?�消耗�?"},
		{"eSS.NonChargeable.label","�?收费"},
		{"eSS.Only.label","仅仅"},
		{"eSS.UserID.label","用户�?�"},
		{"eSS.UserName.label","用户�??"},
		{"eSS.AutoclaveWashUnit.label","高压清洗�?��?"},
//		{"eSS.TRNDocType.label","TRN doc type"},
		{"eSS.Requestor.label","申请人"},
		{"eSS.Inactive.label","无效"},
		{"eSS.UnitStatus.label","�?��?状�?"},
		{"eSS.IssueCount.label","�?�出计数"},
		{"eSS.SystemDefined.label","系统定义"},
		{"eSS.Positive.label","积�?"},
		{"eSS.Negative.label","负"},
//		{"eSS.Descrepancy.label","Descrepancy"},
		{"eSS.System.label","系统"},
		{"eSS.Missing.label","缺少的"},
		{"eSS.Moved.label","移动"},
		{"eSS.CurrentProcessingMonth.label","当�?处�?�月"},
		{"eSS.CurrentProcessingYear.label","当�?处�?�月"},
		{"eSS.UserAccessforStore.label","用户库房访问"},
//		{"eSS.ImageURL.label","Image URL:"},
//		{"eSS.WashUnit.label","Wash Unit"},
//		{"eSS.Required.label","Required"},
//		{"eSS.Requestby.label","Request By"}
//Newly added legends on 21/01/09
{"eSS.Ack.By.label","认�?�人"},
{"eSS.Ack.Dt.label","认�?�日期"},
{"eSS.AcknowledgementList.label","所有认�?�列表"},
{"eSS.AutoclavedBy.label","高压�?��?�人"},
{"eSS.AutoclavedDt.label","高压�?��?�日期"},
{"eSS.AutoclaveUnit.label","高压�?��?��?��?"},
{"eSS.AutoclaveWashUnitTestDetails.label","高压�?��?�测试明细"},
{"eSS.AutoclavingLoadDetails.label","�?个高压负�?�"},
{"eSS.AutoclavingLoadSummary.label","高压负�?�汇总"},
{"eSS.AutoclavingUnit.label","高压�?��?��?��?"},
{"eSS.BinLocation.label","存�?��?置"},
{"eSS.CheckedDt.label","检查日期"},
{"eSS.ChgConsum.label","消耗费用"},
{"eSS.ConsCost.label","消耗�?本"},
{"eSS.ConsValue.label","消耗值"},
{"eSS.Deposit.label","押金明细"},
{"eSS.DispatchedDt.label","分�?�项目日期"},
{"eSS.EnteredDt.label","输入项目日期"},
{"eSS.GroupMovementStatistics.label","统计移动组"},
{"eSS.ImageURL.labelImage URL:","图�?链接"},
{"eSS.IN.label","IN"},
{"eSS.InsValue.label","Ins Value"},
{"eSS.ItemsPacksProcessedandIssuedDuringthePeriod .label","期间内的项目处�?�以�?��?�出"},
{"eSS.LoadNumber.label","负�?�数"},
{"eSS.LoadStatus.label","负载状�?"},
{"eSS.NewBinLocation.label","新的存储�?置"},
{"eSS.off.label","去除"},
{"eSS.OldBinLocation.label","旧的存储�?置"},
{"eSS.OldLoadNo.label","旧的�?��?"},
{"eSS.OUT.label","输出"},
{"eSS.PackedDt.label","消毒日期"},
{"eSS.PackedOn.label","包装日期"},
{"eSS.PhysicalBinLocation.label","物�?��?置"},
{"eSS.PhysicalInvId.label","物�?�库存�?�"},
{"eSS.PresentSterCount.label","当�?消毒计数"},
{"eSS.ProcessROF.label","ROF进程"},
{"eSS.Requestby.labelRequest By","请求人"},
{"eSS.RequestOrderTraysStatus.label","请求托盘状�?"},
{"eSS.RequestOrderTraysStatusSummary.label","请求托盘状�?�?结"},
{"eSS.Required.labelRequired","必须的"},
{"eSS.ROFDocNo.label","ROF文档�?�"},
{"eSS.ROFDocType.label","ROF文档类型"},
{"eSS.SoftPack.label","手术包"},
{"eSS.SterReqDocNo.label","消毒请求文档�?�"},
{"eSS.SterReqDocType.label","消毒请求文档类型"},
{"eSS.SterReqStatus.label","消毒请求状�?"},
{"eSS.TRNDocType.label","TRN文档类型"},
{"eSS.TRNType.label","TRN类型"},
{"eSS.TRNTypeDescription.label","TRN类型�??述"},
{"eSS.WashedDt.label","清洗日期"},
{"eSS.WashUnit.labelWash Unit","清洗�?��?"},


};
}
