
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eCP.CriteriaForAssessmentCategory.CriteriaForAssessmentCategoryManager
package eCP.CriteriaForAssessmentCategory;

/**
 * Local interface for CriteriaForAssessmentCategory
 */
public interface CriteriaForAssessmentCategoryLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap AddModify(java.util.HashMap tabData);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
