/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
/* 
-----------------------------------------------------------------------
Date       Edit History   Name        Description
-----------------------------------------------------------------------
?             100         ?           created
25/8/2011     IN029071    Akbar       Added two new Time Based Rule in 
									  'Ordering Rule by Patient Class' function for MEDICITY
28/10/2011    IN029395    Chowminya G Incident No: IN029395 - <system default preferred surgery date issue> 
14/11/2011    IN028981    Dinesh T    Added labels for KDAH-CRF-41
03/01/2012	  IN028417	  Menaka V	  The registered lab samples can be discontinued from CA-OR even though
									  the discontinuation reasons are not defined for lab module.
20/01/2012	IN029143	  Menaka V	  <JD-CRF-0111 This option is available in HIS 2.x and KAUH needs to be in
									  EM version. In the current workflow the option is being used frequently. When a physician selects the patient, system will ask to enter the PIN Code. Physician needs to authenticate in the Prescription screen using the PIN code. This will prevent from unauthorised access while the physician is on rounds>.									  
23/02/2012	  IN030589	  Menaka V	  System should check & prompt for unbilled lab orders at Manage specimen.  
05/07/2012    IN029935/IN033610      Akbar S	 Add NPB Request Form, Notification alert  		
06/09/2011  IN31901       NijithaS    Incident No: IN31901 - Bru-HIMS-CRF-263	
30/10/2012	CRF-0160	Karthi L	Bru-HIMS-CRF-0160
15/11/2012	IN030472		Ramesh G	Bru-HIMS-CRF-031[Patient instructions to be printed on demand] 
07/02/2013	  IN029949	  Chowminya G  In the Practitioner Homepage under Orders to include “On Hold Medication” 
18/04/2013    IN038336    Chowminya G  In the Existing Order, there are yellow box that which not reflecting with any colour coding in the legend. 
01/12/2013	IN038787		Ramesh G			Bru-HIMS-CRF-358
10/03/2014	  IN024984	  Chowminya	   Duplicate order recording with reason - new mandatory option	
12/03/2014	  IN041644	  Nijitha	   Bru HIMS CRF 385	
23/04/2014    IN042962	  Chowminya    CRF:Print Order Sheet From Existing Orders
05/02/2014 	  IN047918	  Nijitha	   KDAH-CRF-0284
06/08/2014	  IN049419	  Akbar		   HSA-CRF-0147.1
29/08/2014	  IN050209	  Chowminya   MMS-CRF-194.1 Unbilled services will be regrouped into a new order
11/07/2014	  IN048467	  Karthi L	  To have an indicator to skip the authorization process if the priority for that order is urgent.
14/04/2015	IN052649	Ramesh G		Previous orders - Default filter to be filtered by All or by specialty. 	
28/05/2015	IN052230		Karthi L	Order Management-Missing specimens-Dispatch Slip	
06/10/2015	IN055737		Karthi L		IN055737 HSA-CRF-0250.1 - Dispatch Slip
21/10/2015	  IN057196	   	Ramesh G	Recording Of Consent Form
15/03/2016	IN055027		Raja S		MMS-QH-CRF-0216
24/03/2016	IN058811		Raja S		MO-CRF-20107 :National ID to be captured in any orderable (ALL 
										Order Categories) is a national requirement.
10/05/2016	IN051135		Karthi L	MO-CRF-20085 [IN051135]		
22/08/2016	IN060590		Karthi L	HAAD Colour coding for Identification of Infectious disease in Patient BANNER[AAKH-CRF-0083.1].									
22/12/2016	IN062669		Vijayakumar K									ML-MMOH-CRF-0728 [IN:062669]							
08/05/2017	IN063816		Vijayakumar K									GHL-CRF-0445.1 [IN:063816]						
-----------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------
Date       Edit History      Name        		Rev.Date		Rev.Name		Description
----------------------------------------------------------------------------------------------------------------------------------------------------------
09/06/2017	IN063816		Krishna Gowtham J	09/06/2017		Ramesh G		GHL-CRF-0445.1				
10/07/2017	IN061903		Krishna Gowtham J 	10/07/2017		Ramesh G		ML-MMOH-CRF-0555
03/08/2017	IN062992		Dinesh T			07/08/2017		Ramesh G		ML-MMOH-CRF-0345.1
26/07/2017	IN064835		Vijayakumar K										ML-MMOH-CRF-0578.1 [IN:064835]			
28/08/2017	IN065091		Krishna Gowtham J 	29/08/2017		Ramesh G		GHL-CRF-0440.1
22/09/2017	IN063813		Raja S				10/10/2017			Ramesh G			AAKH-CRF-0095
26/10/2017	IN061892		Prakash C			31/10/2017		Ramesh G		ML-MMOH-CRF-0544
14/11/2017	IN063974		Prakash C			31/10/2017		Ramesh G		SS-CRF-0059
27/11/2017  IN061890		Kamalakannan G		27/11/2017		Kamalakannan G	ML-MMOH-CRF-0542
05/12/2017  IN065925		Kamalakannan G		05/12/2017		Kamalakannan G	PMG2017-GHL-CRF-0006
15/12/2017	IN065942	Dinesh T	15/12/2017	Ramesh G	In Nuclear medicine  department we required the barcode 																	functionality at the time of Registration of order,required patient 															Id,patient name,age,sex,register date and name of study.
15/01/2018	IN065844		Sharanraj							Ramesh G		ML-MMOH-CRF-1000											
06/02/2018	IN065642		Prathyusha P				 		GHL-CRF-0487 [IN:065642]										
26/02/2018	IN066119		Raja S				26/02/2018		Ramesh G		ML-MMOH-CRF-1024									
18/04/2018  IN064980        Shivabagyam   18/04/2018       Ramesh G 	    ML-MMOH-CRF-0956[IN064980]			 												
28/05/2018  IN066548        Kamalakannan   28/05/2018       Ramesh G 	    ML-MMOH-CRF-1076[IN066548]			 												
17/07/2018	IN064543		Kamalakannan 17/07/2018		Ramesh G					ML-MMOH-CRF-0776		 												
01/08/2018	IN64543			Dinesh T		01/08/2018	Ramesh G		ML-MMOH-CRF-0776
08/10/2018	  IN063719		Kamalakannan 	08/10/2018	Ramesh G		GHL-CRF-0419
25/01/2019    IN068673    DineshT           25/01/2019    Ramesh G      ML-MMOH-CRF-1263
4/02/2019   IN066453        Ramya Maddena   6/02/2019   Ramesh G		ML-BRU-CRF-0491
28/02/2019  IN068370    Dinesh T      28/02/2019    Ramesh G    PMG2018-GHL-CRF-0014
28/02/2019  IN068373    Dinesh T      28/02/2019    Ramesh G    PMG2018-GHL-CRF-0015
24/12/2019	IN068314	Nijitha S      24/12/2019	  Ramesh G			ML-MMOH-CRF-1229
23/04/2020	IN071618	Nijitha S	 										PMG2019-MMS-CRF-0004
06/07/2020	IN072654	Nijitha S	06/07/2020	Ramesh G	MMS-KH-CRF-0029.4
15/08/2020	IN071361	Nijitha S	15/08/2020	Ramesh G	AAKH-CRF-0116
07/09/2020	7540		Nijitha S		07/12/2020		Nijitha S		PMG2019-MMS-CRF-0004.1
24/12/2021	6868		Ramesh G		24/12/2021		Ramesh G 		AAKH-CRF-0125
28/02/2022	IN27705		Suji Keerthi G		28/02/2022		Ramesh G 		SKR-CRF-0052
02/11/2022  35142       Krishna Pranay  03/11/2022  Ramesh G        TH-KW-CRF-0020.6
13/10/2022  37018           Venkat S                                     PMG2021-COMN-CRF-0080-US001
16/05/2022     29147      krishna pranay       17/05/2023     Ramesh Goli              MO-CRF-20183
18/07/2023     40016      Ranjith P R       19/07/2023          Ramesh Goli              ML-MMOH-CRF-1823  
----------------------------------------------------------------------------------------------------------------------------------------------------------
*/

package eOR.resources;

import java.util.*;

public class Labels extends ListResourceBundle implements java.io.Serializable
{
	public Object[][] getContents() 
	{
		return contents;
	}

	static final Object[][] contents = 
	{
		{"eOR.Actioned By.label","Actioned By"},
		{"eOR.AccessionNumberingRules.label","Accession Numbering Rules"},
		{"eOR.AcknolwedgetheResults.label","Acknolwedge the Results"},
		{"eOR.ActionwhenPreparationDurationnotmet.label","Action when Preparation Duration not met"},
		{"eOR.Actionstakentoresolvecomplications.label","Actions taken to resolve complications"},
		{"eOR.ActiveOrders.label","Active Orders"},
		{"eOR.ActivityType.label","Activity Type"},
		{"eOR.ActivityTypeCode.label","Activity Type Code"},
		{"eOR.AgeSex.label","Age/Sex"},
		{"eOR.AheadPeriod.label","Ahead Period"},
		{"eOR.AlertDept.label","Alert Dept"},
		{"eOR.Alphanumeric.label","Alphanumeric"},
		{"eOR.AncillaryDept.label","Ancillary Dept"},
		{"eOR.Anesthesia.label","Anesthesia"},
		{"eOR.ApplicabilityofOrderPrivileges.label","Applicability of Order Privileges"},
		{"eOR.ApplicationUser.label","Application User"},
		{"eOR.AppointmentBooked.label","Appointment Booked"},
		{"eOR.AppointmentLocation.label","Appointment Location"},
		{"eOR.AppointmentRescheduled.label","Appointment Rescheduled"},
		{"eOR.ApptRequired.label","Appt. Required"},
		{"eOR.AssignPrivileges.label","Assign Privileges"},
		{"eOR.AssistingSurgeon.label","Assisting Surgeon"},
		{"eOR.Atresulting.label","At resulting"},
		{"eOR.AuthorisationInfo.label","Authorisation Info "},
		{"eOR.AuthorizeOrders.label","Authorize Orders"},
		{"eOR.AutoClosingRulesforPendingOrders.label","Auto Closing Rules for Pending Orders"},
		{"eOR.AutoLink.label","Auto Link"},
		{"eOR.AutoRegistration.label","Auto Registration"},
		{"eOR.AutoRegistrationReqd.label","Auto Registration Reqd."},
		{"eOR.AutoUpdateCollectionDateTime.label","Auto Update Collection Date Time"},
		{"eOR.AutoLinktoCatalogCode.label","AutoLink to Catalog Code"},
		{"eOR.BehindPeriod.label","Behind Period"},
		{"eOR.Biochemistry.label","Biochemistry"},
		{"eOR.BloodTransfusion.label","Blood Transfusion "},
		{"eOR.BloodTransfusionHistory.label","Blood Transfusion History"},
		{"eOR.BodyOrgan.label","Body Organ"},
		{"eOR.ByYearandJulianDate.label","By Year and Julian Date"},
		{"eOR.CatalogDescription.label","Catalog Description"},
		{"eOR.CatalogName.label","Catalog Name"},
		{"eOR.CatalogSearch.label","Catalog Search"},
		{"eOR.CatalogSynonym.label","Catalog Synonym"},
		{"eOR.CatalogSynonymType.label","Catalog Synonym Type"},
		{"eOR.ChangeChargeType.label","Change Charge Type "},
		{"eOR.ChangePerformingLocation.label","Change Performing Location"},
		{"eOR.ChangeQtydose.label","Change Qty/dose"},
		{"eOR.ChargeDtls.label","Charge Dtls."},
		{"eOR.ChargeType.label","Charge Type"},
		{"eOR.ChargeTypeCode.label","Charge Type Code"},
		{"eOR.ChargeTypeDescription.label","Charge Type Description"},
		{"eOR.ClinicalSrv.label","Clinical Srv"},
		{"eOR.CloseInProcessOrdersafter.label","Close In Process Orders after"},
		{"eOR.CloseUnprocessedOrdersafter.label","Close Unprocessed Orders after"},
		{"eOR.Cmts.label","Cmts"},
		{"eOR.CoSignLevel.label","Co Sign Level"},
		{"eOR.CollectionDateAndTime.label","Collection Date And Time"},
		{"eOR.CollectionDetails.label","Collection Details"},
		{"eOR.CollectionList.label","Collection List"},
		{"eOR.CollectionStage.label","Collection Stage"},
		{"eOR.Columns.label","Columns"},
		{"eOR.CommonLookUps.label","Common LookUps"},
		{"eOR.CompleteRemarks.label","Complete Remarks"},
		{"eOR.CompletionDateFrom.label","Completion Date From"},
		{"eOR.ConfirmAuthorise.label","Confirm Authorise"},
		{"eOR.ConflictExam.label","Conflict Exam"},
		{"eOR.ConflictExamDateTime.label","Conflict Exam Date/Time"},
		{"eOR.ConflictExamDescription.label","Conflict Exam Description"},
		{"eOR.ConflictswithItem.label","Conflicts with Item"},
		{"eOR.ConsentForms.label","Consent Forms"},
		{"eOR.ConsentInfo.label","Consent Info"},
		{"eOR.ConsentNotes.label","Consent Notes"},
		{"eOR.ConsentOrder.label","Consent Order"},
		{"eOR.ConsentRequiredfromthePatient.label","Consent Required from the Patient"},
		{"eOR.ConsentRefusal.label","Consent/Refusal"},
		{"eOR.ConsentRefusalReferralNotes.label","Consent/Refusal/Referral Notes"},
		{"eOR.ConsentedDateandTime.label","Consented Date and Time"},
		{"eOR.Consults.label","Consults "},
		{"eOR.ContMed.label","Cont.Med."},
		{"eOR.Contain.label","Contain"},
		{"eOR.ContraSysModule.label","Contra Sys Module"},
		{"eOR.CopyOrders.label","Copy Orders"},
		{"eOR.CopyPrevious.label","Copy Previous"},
		{"eOR.CopyPrev.label","Copy Prev"},
		{"eOR.CosignOrders.label","Cosign Orders"},
		{"eOR.CreateasContinuingOrder.label","Create as Continuing Order"},
		{"eOR.CultureTest.label","Culture Test"},
		{"eOR.CurrentEncounterOrders.label","Current Encounter Orders"},
		{"eOR.DateofReceipt.label","Date of Receipt"},
		{"eOR.DateofReferral.label","Date of Referral"},
		{"eOR.DateofRegistration.label","Date of Registration"},
		{"eOR.DayAfterAdmVist.label","Day After Adm/Vist"},
		{"eOR.DefaultAutoReport.label","Default Auto Report"},
		{"eOR.DefaultNumber.label","Default Number"},
		{"eOR.DefaultOrderRepeats.label","Default Order Repeats"},
		{"eOR.DefaultTiming.label","Default Timing"},
		{"eOR.DepartmentInstruction.label","Department Instruction"},
		{"eOR.DepartmentInstructions.label","Department Instructions"},
		{"eOR.DepartmentalDiagnostics.label","Departmental Diagnostics"},
		{"eOR.Dependent.label","Dependent"},
		{"eOR.DeptLocation.label","Dept Location"},
		{"eOR.Diagnostic.label","Diagnostic"},
		{"eOR.DirectCare.label","Direct Care "},
		{"eOR.DischargeIndicator.label","Discharge Indicator"},
		{"eOR.DiscontinuedOrders.label","Discontinued Orders"},
		{"eOR.DiscontinuedCancelled.label","Discontinued/Cancelled"},
		{"eOR.DispatchDateTime.label","Dispatch Date Time"},
		{"eOR.DispatchDetails.label","Dispatch Details"},
		{"eOR.DispatchMode.label","Dispatch Mode"},
		{"eOR.DisplayLocation.label","Display Location"},
		{"eOR.DonotPrint.label","Do not Print"},
		{"eOR.DoyouwanttoPlaceanRapidOrder.label","Do you want to Place an Rapid Order"},
		{"eOR.Done.label","Done"},
		{"eOR.DosageUnit.label","Dosage/Unit"},
		{"eOR.DrawingTool.label","Drawing Tool"},
		{"eOR.AppmtBooked.label","Appt. Booked"},
		{"eOR.DuplicateCheck.label","Duplicate Check "},
		{"eOR.Editor.label","Editor"},
		{"eOR.EditorPreview.label","Editor Preview"},
		{"eOR.Effective.label","Effective"},
		{"eOR.EffectiveWithComplications.label","Effective With Complications"},
		{"eOR.EqualsTo.label","Equals To"},
		{"eOR.ExamConflicts.label","Exam Conflicts"},
		{"eOR.ExceptionIdentifier.label","Exception Identifier"},
		{"eOR.ExceptionType.label","Exception Type"},
		{"eOR.ExistingCharge Type.label","Existing Charge Type"},
		{"eOR.ExistingOrderable.label","Existing Orderable"},
		{"eOR.ExistingProcedure.label","Existing Procedure"},
		{"eOR.ExistingRefusal.label","Existing Refusal"},
		{"eOR.ExpiredOrders.label","Expired Orders"},
		{"eOR.ExternalDetails.label","External Details"},
		{"eOR.ExternalOrder.label","External Order"},
		{"eOR.ExternalOrders.label","External Orders"},
		{"eOR.FieldMnemonic.label","Field Mnemonic"},
		{"eOR.FieldType.label","Field Type"},
		{"eOR.Formats.label","Formats"},
		{"eOR.ForwardedBy.label","Forwarded By"},
		{"eOR.FreqDurn.label","Freq/Durn"},
		{"eOR.FrequencyApplicable.label","Frequency Applicable"},
		{"eOR.FrequencyDesc.label","Frequency Desc"},
		{"eOR.FrequencyRequired.label","Frequency Required"},
		{"eOR.FrequencyScope.label","Frequency Scope"},
		{"eOR.FromLocation.label","From Location"},
		{"eOR.FromOrderCategory.label","From Order Category"},
		{"eOR.FromOrderStatus.label","From Order Status"},
		{"eOR.FromOrderType.label","From Order Type"},
		{"eOR.FutureOrder.label","Future Order"},
		{"eOR.FutureOrderRule.label","Future Order Rule"},
		{"eOR.GenerateLabel.label","Generate Label"},
		{"eOR.GenerationLookAhead.label","Generation Look Ahead"},
		{"eOR.GraceTimeforInclusioninActiveOrders.label","Grace Time for Inclusion in Active Orders"},
		{"eOR.GreaterThan.label","Greater Than"},
		{"eOR.GroupID.label","Group ID"},
		{"eOR.Haematology.label","Haematology"},
		{"eOR.Hint.label","Hint"},
		{"eOR.HoldDiscontinue.label","Hold / Discontinue"},
		{"eOR.HoldResume.label","Hold/ Resume"},
		{"eOR.HotSpot.label","HotSpot"},
		{"eOR.HotspotDesc.label","Hotspot Desc"},
		{"eOR.HotspotId.label","Hotspot Id"},
		{"eOR.HourAfterAdmVist.label","Hour After Adm.Vist"},
		{"eOR.ImageHotspot.label","Image Hotspot"},
		{"eOR.ImageHotspotLink.label","Image Hotspot Link"},
		{"eOR.ImageId.label","Image Id"},
		{"eOR.ImageLinkId.label","Image Link Id"},
		{"eOR.IncludeStatReport.label","Include Stat Report"},
		{"eOR.Index.label","Index"},
		{"eOR.IndexOrderCare Set.label","Index Order Care Set"},
		{"eOR.IndexOrderCatalog.label","Index Order Catalog"},
		{"eOR.IndexOrderSet.label","Index Order Set"},
		{"eOR.IndexTickSheet.label","Index Tick Sheet"},
		{"eOR.Ineffective.label","Ineffective"},
		{"eOR.IneffectiveWithComplications.label","Ineffective With Complications"},
		{"eOR.InitialSerialNumber.label","Initial Serial Number"},
		{"eOR.Injections.label","Injections"},
		{"eOR.Instruction.label","Instruction"},
		{"eOR.InstructionbyAgeSex.label","Instruction by Age/Sex"},
		{"eOR.InstructionDetails.label","Instruction Details"},
		{"eOR.InstructionsMode.label","Instructions Mode"},
		{"eOR.InterfaceParticulars.label","Interface Particulars"},
		{"eOR.IntraProceduralComplications.label","Intra   Procedural Complications"},
		{"eOR.LaboratorySite.label","Laboratory Site"},
		{"eOR.Loc1.label","Loc1"},
		{"eOR.Loc2.label","Loc2"},
		{"eOR.LookAheadMin.label","Look Ahead Min"},
		{"eOR.Mainsurgeon.label","Main Surgeon"},
		{"eOR.MatrixColumn.label","Matrix Column"},
		{"eOR.MatrixColumnCode.label","Matrix Column Code"},
		{"eOR.MatrixColumnDesc.label","Matrix Column Desc"},
		{"eOR.MatrixRow.label","Matrix Row"},
		{"eOR.MatrixRowCode.label","Matrix Row Code"},
		{"eOR.MatrixRowDesc.label","Matrix Row Desc"},
		{"eOR.MaxValueDurnType.label","Max Value/Durn Type"},
		{"eOR.MeasureDrugName.label","Measure/Drug Name"},
		{"eOR.Microbiology.label","Microbiology"},
		{"eOR.MiscellaneousService Location.label","Miscellaneous Service Location"},
		{"eOR.modalwindow.label","modal window"},
		{"eOR.Multi.label","Multi"},
		{"eOR.MultiFacilityProcessing.label","Multi Facility Processing"},
		{"eOR.MultiSelect.label","Multi Select"},
		{"eOR.MultiPatientOrdersHdr.label","MultiPatientOrdersHdr"},
		{"eOR.MultiPatientOrdersHdrResult.label","MultiPatientOrdersHdrResult"},
		{"eOR.MultiPatientOrdersTool.label","MultiPatientOrdersTool"},
		{"eOR.Nebuliser.label","Nebuliser"},
		{"eOR.NewChargeType.label","New Charge Type"},
		{"eOR.NewList.label","New List"},
		{"eOR.NewProcedureTabs.label","New Procedure Tabs"},
		{"eOR.NewRefusal.label","New Refusal"},
		{"eOR.NextAccessionNumber.label","Next Accession Number"},
		{"eOR.NoofReschedules.label","No of Reschedules"},
		{"eOR.NoofOrdersPlacedforDepartment.label","No. of Orders Placed for Department"},
		{"eOR.NonApplicable.label","Non Applicable"},
		{"eOR.NormalHigh.label","Normal High"},
		{"eOR.NormalLow.label","Normal Low"},
		{"eOR.NormalcyIndicator.label","Normalcy Indicator"},
		{"eOR.NurseCollect.label","Nurse Collect"},
		{"eOR.NURSECOLLECTYN.label","NURSE_COLLECT_YN"},
		{"eOR.ObtainedByPractitioner.label","Obtained By Practitioner"},
		{"eOR.ActionDateTime.label","Action Date Time"},
		{"eOR.OnHold[Activate ].label","On Hold[Activate ]"},
		{"eOR.OperatingTheatre.label","Operating Theatre"},
		{"eOR.OptionalPreSelected.label","Optional/Pre Selected"},
		{"eOR.ORParameter.label","OR Parameter"},
		{"eOR.ORParameterforFacility.label","OR Parameter for Facility"},
		{"eOR.ORPrintingRules.label","OR Printing Rules"},
		{"eOR.OrderCatalogtoProcedureLink.label","Order Catalog to Procedure Link"},
		{"eOR.OrderCatalogs.label","Order Catalogs"},
		{"eOR.OrderCategory ID.label","Order Category ID"},
		{"eOR.OrderEntryCalendarButton.label","Order Entry Calendar Button"},
		{"eOR.OrderEntryCareSetSearch.label","Order Entry Care Set Search"},
		{"eOR.OrderEntryCriteriaDetail.label","Order Entry Criteria Detail"},
		{"eOR.OrderEntryCriteriaHeader.label","Order Entry Criteria Header"},
		{"eOR.OrderEntryCriteriaMain.label","Order Entry Criteria Main"},
		{"eOR.OrderEntryFormat.label","Order Entry Format"},
		{"eOR.OrderEntryFormatItem.label","Order Entry Format Item"},
		{"eOR.OrderEntryFrequentAccessedPractitionerItems.label","Order Entry Frequent Accessed Practitioner Items"},
		{"eOR.OrderEntryImagePanels.label","Order Entry Image Panels"},
		{"eOR.OrderEntryMain.label","Order Entry Main"},
		{"eOR.OrderEntryPreview.label","Order Entry Preview"},
		{"eOR.OrderEntryResultMain.label","Order Entry Result Main"},
		{"eOR.OrderEntryTickSheet.label","Order Entry Tick Sheet"},
		{"eOR.OrderEntryTickSheetItems.label","Order Entry Tick Sheet Items"},
		{"eOR.OrderForm.label","Order Form"},
		{"eOR.OrderFormat.label","Order Format"},
		{"eOR.OrderFormatLine.label","Order Format Line"},
		{"eOR.OrderForms.label","Order Forms"},
		{"eOR.OrderLineFormat.label","Order Line Format"},
		{"eOR.OrderLineNo.label","Order Line No"},
		{"eOR.OrderPlacedBy.label","Order Placed By"},
		{"eOR.OrderPriorityApplicable.label","Order Priority Applicable"},
		{"eOR.OrderReviews.label","Order Reviews"},
		{"eOR.OrderSet.label","Order Set"},
		{"eOR.OrderSetCode.label","Order Set Code"},
		{"eOR.OrderSetComponents.label","Order Set Components"},
		{"eOR.OrderSetDesc.label","Order Set Desc"},
		{"eOR.OrderStage.label","Order Stage"},
		{"eOR.OrderStatistics.label","Order Statistics"},
		{"eOR.OrderStatusCode.label","Order Status Code"},
		{"eOR.OrderStatusDesc.label","Order Status Desc"},
		{"eOR.OrderStatusFrom.label","Order Status From"},
		{"eOR.ExternalDtls.label","External Dtls."},
		{"eOR.InstructionMode.label","Instruction Mode"},
		{"eOR.OrderStatusType.label","Order Status Type"},
		{"eOR.OrderTypebyClass.label","Order Type by Class"},
		{"eOR.OrderTypeCategory.label","Order Type Category"},
		{"eOR.OrderTypeCope.label","Order Type Cope"},
		{"eOR.OrderTypeDesc.label","Order Type Desc"},
		{"eOR.OrdertypeforOrderableDtl.label","Order type for Orderable Dtl"},
		{"eOR.OrderTypeFrom.label","Order Type From"},
		{"eOR.OrderTypesforOrderableMain.label","Order Types for Orderable Main"},
		{"eOR.Orderables.label","Orderables"},
		{"eOR.OrderablesbyPerformingLocation.label","Orderables by Performing Location"},
		{"eOR.OrderedAt.label","Ordered At"},
		{"eOR.OrderingRulebyPatientClass.label","Ordering Rule by Patient Class"},
		{"eOR.OrdersProcessed.label","Orders Processed"},
		{"eOR.OrdersTab.label","Orders Tab"},
		{"eOR.OTAppointment.label","OT Appointment"},
		{"eOR.OtherMnemonic.label","Other Mnemonic"},
		{"eOR.ParametersforSingleContinuingOrders.label","Parameters for Single Continuing Orders"},
		{"eOR.Partial.label","Partial"},
		{"eOR.PatInstrn.label","Pat. Instrn"},
		{"eOR.SplitDosage.label","Split Dosage"},
		{"eOR.PatientEvent.label","Patient   Event"},
		{"eOR.PatientClassApplicability.label","Patient Class Applicability"},
		{"eOR.PatientLoc.label","Patient Loc"},
		{"eOR.PatientOrderbyLocation.label","Patient Order by Location"},
		{"eOR.PatientOrderDetail.label","Patient Order Detail"},		
		{"eOR.PatientOrdersView.label","Patient Orders View"},
		{"eOR.PatientDiagnosis.label","Patient/Diagnosis  %"},
		{"eOR.PendingForAuthorization.label","Pending For Authorization"},
		{"eOR.PerformingDepartmentLocationCode.label","Performing Department Location Code"},
		{"eOR.PerformingDepartmentLocationType.label","Performing Department Location Type"},
		{"eOR.PerformingLocationCode.label","Performing Location Code"},
		{"eOR.PerformingLocationDescription.label","Performing Location Description"},
		{"eOR.PerformingLocations.label","Performing Locations"},
		{"eOR.PeriodAhead.label","Period Ahead"},
		{"eOR.PeriodBehind.label","Period Behind"},
		{"eOR.PeriodRangeFrom.label","Period Range From"},
		{"eOR.PeriodType.label","Period Type"},
		{"eOR.PlaceOrderFrameSet.label","Place Order FrameSet"},
		{"eOR.Plain.label","Plain"},
		{"eOR.PreparationDuration.label","Preparation Duration"},
		{"eOR.PreparatoryInstruction.label","Preparatory Instruction"},
		{"eOR.Preps.label","Preps"},
		{"eOR.PrepsInstructions.label","Preps Instructions"},
		{"eOR.PreselectOrderType.label","Preselect Order Type"},
		{"eOR.Press.label","Press"},	
		{"eOR.PresslinktoAuthorize.label","Press link to Authorize"},
		{"eOR.PrimaryOrder Type.label","Primary Order Type"},
		{"eOR.PrintatDepartment.label","Print at Department"},
		{"eOR.PrintatDestination.label","Print at Destination"},
		{"eOR.PrintatOtherLocation.label","Print at Other Location"},
		{"eOR.PrintatSource.label","Print at Source"},
		{"eOR.PrintLocation.label","Print Location"},
		{"eOR.PrintLocationforDischargedPatients.label","Print Location for Discharged Patients"},
		{"eOR.Print Results.label","Print Results"},
		{"eOR.Privilege.label","Privilege"},
		{"eOR.PrivilegeExceptionDetail.label","Privilege Exception Detail"},
		{"eOR.PrivilegeExceptionHead.label","Privilege Exception Head"},
		{"eOR.PrivilegeExceptionMain.label","Privilege Exception Main"},
		{"eOR.PrivilegeGroup.label","Privilege Group"},
		{"eOR.ProcedureLink.label","Procedure Link"},
		{"eOR.ProductDetails.label","Product Details"},
		{"eOR.PromptAlert.label","Prompt Alert"},
		{"eOR.PromptMessage.label","Prompt Message"},
		{"eOR.QtyDose.label","Qty/Dose"},
		{"eOR.R.label","R"},
		{"eOR.RadioGroup.label","Radio Group"},
		{"eOR.RadiologyAppointments.label","Radiology Appointments"},
		{"eOR.ReactivateonHoldPeriodAhead.label","Reactivate on Hold  Period Ahead"},
		{"eOR.ReasonforRapidOrders.label","Reason for Rapid Orders"},
		{"eOR.ReasonType.label","Reason Type"},
		{"eOR.ReceiveResult.label","Receive Result"},
		{"eOR.ReceivedRemarks.label","Received Remarks"},
		{"eOR.ReceivingPractitioner.label","Receiving Practitioner"},
		{"eOR.RecordCollection.label","Record Collection"},
		{"eOR.RecordDispatch.label","Record Dispatch"},
		{"eOR.RecordProcedure.label","Record Procedure"},
		{"eOR.RecordCancellation.label","Record Cancellation"},
		{"eOR.ReferralForm.label","Referral Form"},
		{"eOR.ReferralForms.label","Referral Forms"},
		{"eOR.ReferralPractitioner.label","Referral Practitioner"},
		{"eOR.ReferralText.label","Referral Text"},
		{"eOR.RefusalDateTime.label","Refusal Date/Time"},
		{"eOR.RefusalEditor.label","Refusal Editor"},
		{"eOR.RefusalForm.label","Refusal Form"},
		{"eOR.RefusalForms.label","Refusal Forms"},
		{"eOR.RefusalID.label","Refusal ID"},
		{"eOR.RefusalOrder.label","Refusal Order"},
		{"eOR.RefusalText.label","Refusal Text"},
		{"eOR.RefusalType.label","Refusal Type"},
		{"eOR.RelationId.label","Relation Id"},
		{"eOR.RelationName.label","Relation Name"},
		{"eOR.Remark.label","Remark"},
		{"eOR.RenewPeriodBehind.label","Renew  Period Behind"},
		{"eOR.RenewOrders.label","Renew Orders"},
		{"eOR.Replaced.label","Replaced"},
		{"eOR.ReplaceOrderable.label","Replace Orderable"},
		{"eOR.ReplaceableOrderCatalog.label","Replaceable Order Catalog"},
		{"eOR.ReplaceableOrderCatalogCode.label","Replaceable Order Catalog Code"},
		{"eOR.ReplaceableOrderCatalogDescription.label","Replaceable Order Catalog Description"},
		{"eOR.ReplaceableOrderable.label","Replaceable Orderable"},
		{"eOR.ReplaceableOrderableCatalog.label","Replaceable Orderable Catalog"},
		{"eOR.ReportedAt.label","Reported At"},
		{"eOR.Reporting.label","Reporting"},
		{"eOR.ReportingandAuthorizing.label","Reporting and Authorizing"},
		{"eOR.ReportingDate.label","Reporting Date"},
		{"eOR.ReportingPractitioner.label","Reporting Practitioner"},
		{"eOR.ReportingTime.label","Reporting Time"},
		{"eOR.ReprintDispatchSlip.label","Reprint Dispatch Slip"},
		{"eOR.ReqdOpt.label","Reqd/Opt"},
		{"eOR.RequestforAuthorize.label","Request for Authorize"},
		{"eOR.RestrictPerformingLocation.label","Restrict Performing Location"},
		{"eOR.ResultComment.label","Result Comment"},
		{"eOR.ResultComments.label","Result Comments"},
		{"eOR.ResultCompletionStatistics.label","Result Completion Statistics"},
		{"eOR.ResultEntry.label","Result Entry"},
		{"eOR.ResultEntryTemplate.label","Result Entry Template"},
		{"eOR.ResultReports.label","Result Reports"},
		{"eOR.ResultStatus.label","Result Status"},
		{"eOR.Results.label","Results"},
		{"eOR.ReviewRemarks.label","Review Remarks"},
		{"eOR.ReviewType.label","Review Type"},
		{"eOR.RoutineOrderStage.label","Routine Order Stage"},
		{"eOR.ScheduleApplicable.label","Schedule Applicable"},
		{"eOR.ScheduleFrequency.label","Schedule Frequency"},
		{"eOR.SearchFor.label","Search For"},
		{"eOR.SearchForOrderingPractitioner.label","Search For Ordering Practitioner"},
		{"eOR.SearchForPractitioner.label","Search For Practitioner"},
		{"eOR.SecondaryOrder.label","Secondary Order"},
		{"eOR.SecondaryTaskPrep.label","Secondary Task/Prep"},
		{"eOR.SecurityLevel.label","Security Level"},
		{"eOR.SelectAllSpecificOrder.label","Select All/Specific Order"},
		{"eOR.SelectedOrderables.label","Selected Orderables"},
		{"eOR.SemiCritical.label","Semi Critical"},
		{"eOR.SendOut.label","Send Out"},
		{"eOR.SentPractitioner.label","Sent Practitioner"},
		{"eOR.SentRemarks.label","Sent Remarks"},
		{"eOR.SeqNum.label","Seq Num."},
		{"eOR.ServiceCategory.label","Service Category"},
		{"eOR.ServiceDesc.label","Service Desc"},
		{"eOR.ServiceTypeCode.label","Service Type Code"},
		{"eOR.Settings.label","Settings"},
		{"eOR.SingleMulti.label","Single/Multi"},
		{"eOR.SoftStopforInpatients.label","Soft Stop for Inpatients"},
		{"eOR.SourceCode.label","Source Code"},
		{"eOR.SourceDesc.label","Source Desc"},
		{"eOR.SourceFrom.label","Source From"},
		{"eOR.SourceLocation.label","Source Location"},
		{"eOR.SpecialApprovalLevel.label","Special Approval Level"},
		{"eOR.SpecificLoc.label","Specific Loc"},
		{"eOR.SpecimenLabelGeneration.label","Specimen Label Generation"},
		{"eOR.SpecimenNo.label","Specimen No"},
		{"eOR.SpecimenOrder.label","Specimen Order"},
		{"eOR.TickSheetDesc.label","Tick Sheet Desc"},
		{"eOR.SplApproval.label","Spl Approval"},
		{"eOR.Spl.ApprovalReqd.label","Spl. Approval Reqd."},
		{"eOR.Split.label","Split"},
		{"eOR.StandardInstruction.label","Standard Instruction"},
		{"eOR.StartFrom.label","Start From"},
		{"eOR.StatOrderStage.label","Stat Order Stage"},
		{"eOR.StatusByCategory.label","Status By Category"},
		{"eOR.StatusByPriority.label","Status By Priority"},
		{"eOR.StatusRemark.label","Status Remark"},
		{"eOR.StatusType.label","Status Type"},
		{"eOR.StopOnAppt.label","Stop On Appt"},
		{"eOR.Synonyms.label","Synonyms"},
		{"eOR.TabName.label","Tab Name"},
		{"eOR.TaskStatus.label","Task Status"},
		{"eOR.TemplateType.label","Template Type"},
		{"eOR.TermSetCode.label","Term Set Code"},
		{"eOR.Text Type.label","Text Type"},
		{"eOR.Therapeutic.label","Therapeutic"},
		{"eOR.TickSheet.label","Tick Sheet"},
		{"eOR.TickSheetID.label","Tick Sheet ID"},
		{"eOR.TickSheetSection.label","Tick Sheet Section"},
		{"eOR.TickSheetSection Code.label","Tick Sheet Section Code"},
		{"eOR.TimeBasedRule.label","Time Based Rule"},
		{"eOR.TimeFrame.label","Time Frame"},
		{"eOR.TimePeriodforOrdersResults.label","Time Period for Orders / Results"},
		{"eOR.Timing.label","Timing"},
		{"eOR.ToLocation.label","To Location"},
		{"eOR.ToOrderCategory.label","To Order Category"},
		{"eOR.ToOrderStatus.label","To Order Status"},
		{"eOR.ToOrderType.label","To Order Type"},
		{"eOR.ToolTip.label","Tool Tip"},
		{"eOR.TreatmentLocation.label","Treatment Location"},
		{"eOR.TurnAroundTimeForPriority.label","Turn Around Time For Priority"},
		{"eOR.Uncoded.label","Uncoded"},
		{"eOR.Unprocessed.label","Unprocessed"},
		{"eOR.UpdateOrders.label","Update Orders"},
		{"eOR.UrgStat.label","Urg/Stat"},
		{"eOR.Urgency.label","Urgency"},
		{"eOR.UrgentOrderStage.label","Urgent Order Stage"},
		{"eOR.UserDefinedTabName.label","User Defined Tab Name"},
		{"eOR.UsersforOrderReview.label","Users for Order Review"},
		{"eOR.UsersforResultReporting.label","Users for Result Reporting"},
		{"eOR.ViewAfterDispatchSlip.label","View After Dispatch Slip"},
		{"eOR.ViewAppointmentDetails.label","View Appointment Details"},
		{"eOR.ViewAuditTrail.label","View Audit Trail"},
		{"eOR.ViewOrderBy.label","View Order By"},
		{"eOR.VisitAdmTime.label","Visit Adm Time"},
		{"eOR.WaitTimeforGreen.label","Wait Time for Green"},
		{"eOR.WaitTimeForPendingOrdersTab.label","Wait Time For Pending Orders Tab"},
		{"eOR.WaitTimeforRed.label","Wait Time for Red"},
		{"eOR.WaitTimeforYellow.label","Wait Time for Yellow"},
		{"eOR.WaitingTime.label","Waiting Time"},
		{"eOR.WarnOnAppt.label","Warn On Appt"},
		{"eOR.Wing.label","Wing"}, 
		{"eOR.Y.label","Y"},
		{"eOR.ActiveBookings.label","Active Bookings"},
		{"eOR.PatientHistory.label","[Patient History]"},
		{"eOR.R.label","[R]"},
		{"eOR.S.label","[S]"},
		{"eOR.Tobegenerated.label","[To be generated]"},
		{"eOR.U.label","[U]"},
		{"eOR.ActiveRenew.label","Active[Renew?]"},
		{"eOR.AppointmentRequired.label","Appointment Required"},
		{"eOR.AttendPractitioner.label","Attend. Practitioner"},
		{"eOR.AuditTrial.label","Audit Trial"},
		{"eOR.AuthorizationRequired.label","Authorization Required"},
		{"eOR.AutoUpdateCollectionDateTime.label","Auto-Update Collection Date & Time"},
		{"eOR.CancelReason.label","Cancel Reason"},
		{"eOR.CatalogComments.label","Catalog Comments:-"},
		{"eOR.ConsentBy.label","Consent By"},
		{"eOR.ConsentInformation.label","Consent Information"},           
		{"eOR.CosignReqdlabel.label","Cosign Reqd."},
		{"eOR.CriticalAbnormal.label","Critical Abnormal"},
		{"eOR.DateandTime.label","Date and Time"},
		{"eOR.DeptInstrn.label","Dept. Instrn."},
		{"eOR.DurnValueType.label","Durn Value/Type"},
		{"eOR.ElapsedOrder.label","Elapsed Order"},
		{"eOR.ExpiredRenew.label","Expired[Renew?]"},
		{"eOR.hasbeenSuspendedInvalid.label","has been Suspended/Invalid."},
		{"eOR.HoldDateTime.label","Hold Date/Time"},
		{"eOR.Hrs.label","Hrs."},
		{"eOR.IntraProceduralComplications&nbsp.label","Intra - Procedural Complications&nbsp;"},
		{"eOR.isAlreadySelectedinthePanel.label","is Already Selected in the Panel."},
		{"eOR.Jb.label","Jb"},
		{"eOR.MaxPeriodtoBackDateOrders.label","Max.Period to Back - Date Orders"},
		{"eOR.MaxPeriodtoBackDateResults.label","Max. Period to Back -Date Results"},
		{"eOR.MaxPeriodtoFutureDateOrders.label","Max. Period to Future -Date Orders"},
		{"eOR.Meaning.label","Meaning"},
		{"eOR.Mins.label","Mins."},
		{"eOR.MultiFacilityProcessingHeader.label","Multi Facility Processing Header"},
		{"eOR.MultiPatientOrdersHdrDtl.label","MultiPatientOrdersHdrDtl"},
		{"eOR.MultiSession.label","Multi-Session;"},
		{"eOR.NonOrderable.label","Non-Orderable"},
		{"eOR.Occurrance.label","Occurrance"},
		{"eOR.OnHoldActivate.label","On-Hold[Activate?]"},
		{"eOR.OptionalDeSelected.label","Optional/De- Selected"},
		{"eOR.OrderApproval.label","Order Approval"},
		{"eOR.OrderAuthorization.label","Order Authorization"},
		{"eOR.OrderCatalogbyTickSheetSection.label","Order Catalog by Tick Sheet  Section"},
		{"eOR.OrderConsent.label","Order Consent"},
		{"eOR.OrderCosign.label","Order Cosign"},
		{"eOR.OrderEntry.label","Order Entry"},
		{"eOR.OrderEntryDrawingToolItems.label","Order Entry Drawing Tool  Items"},
		{"eOR.OrderRegistration.label","Order Registration"},
		{"eOR.OrderRequestfor.label","Order Request for"},
		{"eOR.OrderTab.label","Order Tab"},
		{"eOR.OrderableNonOrderable.label","Orderable/Non-Orderable"},
		{"eOR.OrderingBy.label","Ordering By&nbsp;"},
		{"eOR.OutstandingOrders.label","Outstanding Orders"},
		{"eOR.PartiallyResulted.label","Partially Resulted"},
		{"eOR.Instrn.label","Instrn"},
		{"eOR.PatientDetail.label","Patient Detail"},
		{"eOR.PatientNameOrderables.label","Patient Name / Orderables"},
		{"eOR.PendingReviews.label","Pending Reviews"},
		{"eOR.PreselectOrderCategory.label","Pre-select : Order Category"},
		{"eOR.PressLinkto.label","Press Link to :"},
		{"eOR.ReportNotRequested.label","Report Not Requested"},
		{"eOR.ReScheduled.label","Re-Scheduled"},
		{"eOR.ResultModified.label","Result Modified"},
		{"eOR.ResultModifiedA.label","Result Modified (Abn) "},
		{"eOR.Resulted.label","Resulted"},
		{"eOR.ResumeOrder.label","Resume  Order"},
		{"eOR.ReviewLineStatus.label","Review Line Status"},
		{"eOR.ReviewOrderStatus.label","Review Order Status"},
		{"eOR.Schd.label","Schd"},
		{"eOR.ApptDetails.label","Appt.Dtls"},
		{"eOR.SecondaryOrderExists.label","Secondary Order Exists"},
		{"eOR.SSelfOrder.label","S-Self Order"},
		{"eOR.NNotApplicable.label","N-Not Applicable"},
		{"eOR.AAllOrders.label","A-All Orders"},
		{"eOR.TermGroupDescription.label","Term Group Description"},
		{"eOR.TermGroupID.label","Term Group ID"},
		{"eOR.TickSheetDescription.label","Tick Sheet Description"},
		{"eOR.TotalAmount.label","Total Amount:"},
		{"eOR.MMedicalTeam.label","M-MedicalTeam"},
		{"eOR.referralunits.label","Referral Units"},
		{"eOR.ticksheetoption.label","tickSheetOption"},
		{"eOR.sectionoption.label","sectionOption"},
		{"eOR.SectionDesc.label","Section Desc"},
		{"eOR.explodebyday.label","Explode By Day"},
		{"eOR.chargetypeapplicable.label","Charge Type Applicable"},
		{"eOR.resultmatrix.label","Result Matrix"},
		{"eOR.manuallink.label","Manual-Link"},
		{"eOR.activebookings.label","Active Bookings"},
		{"eOR.absolute.label","Absolute"},
		{"eOR.minmax.label","Min.Max"},
		{"eOR.ContinuingOrder.label","Continuing Order"},
		{"eOR.ConsentNoteTextID.label","Consent Note Text ID"},
		{"eOR.AdditionalSearch.label","Additional Search"},
		{"eOR.TickSheets.label","Tick Sheets"},
		{"eOR.OrderSets.label","Order Sets"},
		{"eOR.ExistingOrders.label","Existing Orders"},
		{"eOR.FrequentOrders.label","Frequent Orders"},
		{"eOR.DiscreteMeasureID.label","Discrete Measure ID"},
		{"eOR.DiscreteMeasureDesc.label","Discrete Measure Desc"},
		{"eOR.SeqNo.label","Seq.No"},
		{"eOR.DurnValue/DurnType.label","Durn Value/Durn Type"},
		{"eOR.Pre-selectOrderType.label","Pre-select Order Type"},
		{"eOR.BySource.label","By Source"},
		{"eOR.CollectionDateTime.label", "Collection Date Time"},
		{"eOR.MovementLocation.label","Movement Location"},
		{"eOR.ByYear.label","By Year"},
		{"eOR.CosignRequired.label","Cosign Required"},
		{"eOR.ActivityTypeDesc.label","Activity Type Desc"},
		{"eOR.ResultMatrixType.label","Result Matrix Type"},
		{"eOR.PerformingDepartmentLocationDesc.label","Performing Department Location Desc"},
		{"eOR.MatrixDesc.label","Matrix Desc"},
		{"eOR.GroupIdentifier.label","Group Identifier"},
		{"eOR.MMedicalTeam.label","M-Medical Team"},
		{"eOR.ByAgeSex.label","By Age/Sex"},
		{"eOR.Msg.label","Msg"},
		{"eOR.DiagnosisDesc.label","Diagnosis Desc"},
		{"eOR.ReasonText.label","Reason Text"},
		{"eOR.ImageDesc.label","Image Desc"},
		{"eOR.ImageLink.label","Image Link"},
		{"eOR.Charting.label","Charting"},
		{"eOR.DefaultValueInProcess.label","Default Value: User-defined 'In Process' Status:"},
		{"eOR.MaxPeriodtoBackDateOrders.label","Max. Period to Back - Date Orders"},
		{"eOR.ByExceptionSpecificity.label","By Exception / Specificity"},
		{"eOR.RenewPeriodBehind.label","Renew: Period Behind"},
		{"eOR.ReactivateonHoldPeriodAhead.label","Reactivate on Hold: Period Ahead"},
		{"eOR.ContinousFrequencyAction.label","Continous Frequency Action"     },
		{"eOR.AllowRefills.label", "Allow Refills"    },
		{"eOR.BeforeOrderRegistration.label",  "Before Order Registration"  },
		{"eOR.BeforeOrderRelease.label","Before Order Release"     },
		{"eOR.RefusalNoteText.label", "Refusal Note Text"    },
		{"eOR.DepartmentOnly.label", "Department Only"    },
		{"eOR.CompleteonOrder.label", "Complete on Order"    },
		{"eOR.AutoReport.label", "Auto Report"    },
		{"eOR.ChartApplicable.label", "Chart Applicable"    },
		{"eOR.ChartingCharacteristics.label",  "Charting Characteristics"  },
		{"eOR.ChartResultType.label", "Chart Result Type"    },
		{"eOR.DispenseAuthRequired.label", "Dispense Auth. Required"    },
		{"eOR.BehindAction.label", "Behind Action"    },
		{"eOR.PrivilegeLevel.label", "Privilege Level"},
		{"eOR.RoutineUrgent.label","Routine&Urgent"},
		{"eOR.StatusConsidered.label","Status Considered"},
		{"eOR.AheadAction.label","Ahead Action"},
		{"eOR.DispatchLocation.label","Dispatch Location"},
		{"eOR.PatientEvent.label","Patient & Event"},
		{"eOR.Coding.label","Coding"},
		{"eOR.Coded.label","Coded"},
		{"eOR.ByTimeframeCategory.label","By Time-frame/Category"},
		{"eOR.ByCategoryTimeframe.label","By Category/Time-frame"},
		{"eOR.Matrix.label","Matrix"},
		{"eOR.FrequentOrdersPlacedby.label","Frequent Orders Placed by"},
		{"eOR.FrequentOrdersPlacedfor.label","Frequent Orders Placed for"},
		{"eOR.Occurance.label","Occurance"},
		{"eOR.Front.label","Front"},
		{"eOR.Dietary.label","Dietary"},
		{"eOR.NursingCare.label","Nursing Care"},
		{"eOR.RadiologyDept.label","Radiology Dept"},
		{"eOR.RecordConsent.label","Record Consent"},
		{"eOR.CompleteReview.label","Complete Review"},
		{"eOR.ResultedP.label","Resulted(P)"},
		{"eOR.AbnormalP.label","Abnormal(P)"},
		{"eOR.CriticalLow.label","Critical Low"},
		{"eOR.CriticalHigh.label","Critical High"},
		{"eOR.LabResults.label","Lab Results"},
		{"eOR.DrugDetails.label","Drug Details"},
		{"eOR.ReplacewithOrderable.label","Replace with Orderable"},
		{"eOR.Fields.label","Fields"},
		{"eOR.CopyPreviousOrders.label","Copy Previous Orders"},
		{"eOR.OtherTeam.label","Other Team"},
		{"eOR.TeamsofAttendingPractitioner.label","Teams of Attending Practitioner"},
		{"eOR.SequenceNumber.label","Sequence Number"},
		{"eOR.MatrixRowDescription.label","Matrix Row Description"},
		{"eOR.MatrixColumnDescription.label","Matrix Column Description"},
		{"eOR.ReferralDateTime.label","Referral Date/Time"},
		{"eOR.Responsibilty.label","Responsibilty"},
		{"eOR.PatientSearch.label","Patient Search"},
		{"eOR.FindTeam.label","Find Team"},
		{"eOR.ConsentNoteType.label","Consent Note Type"},
		{"eOR.FrequenctScope.label","Frequenct Scope"},
		{"eOR.OrderTypeCategory.label","OrderTypeCategory"},
		{"eOR.FromOrderDate.label","From Order Date"},
		{"eOR.ToOrderDate.label","To Order Date"},
		{"eOR.Billable.label","Billable"},	
		{"eOR.AppointmentReferenceNumber.label","Appointment Reference Number:"},
		{"eOR.AppointmentLocation.label","Appointment Location:"},
		{"eOR.Attending.label","Attending"},
		{"eOR.Renew.label","Renew"},
		{"eOR.Resume.label","Resume"},
		{"eOR.ActivateOrders.label","Activate Orders"},
		{"eOR.CareSet.label","Care Set"},
		{"eOR.NoofColumns.label","No. of Columns"},
		{"eOR.TableNo.label","Table No."},
		{"eOR.RowNotobedeleted.label"," Row No. to be deleted"},
		{"eOR.RowNo.label","Row No."},
		{"eOR.ColumnNo.label","Column No."},
		{"eOR.OrderCompletion.label","Order Completion"},
		{"eOR.RedirectOrder.label","Redirect Order"},
		{"eOR.Refusal.label","Refusal"},
		{"eOR.Decimal.label","Decimal"},
		{"eOR.Integer.label","Integer"},
		{"eOR.EnterLocation.label","Enter Location"},
		{"eOR.Dtls.label","Dtls."},
		{"eOR.UnOfficialReport.label","Un-Official Report"},
		{"eOR.EventDateTime.label","Event Date Time"},
		{"eOR.SexAge.label"," Sex/Age :"},
		{"eOR.OrderEntryExternalOrder.label"," Order Entry(External Order)"},
		{"eOR.OrderEntryMultiPatientOrders.label"," Order Entry(Multi Patient Orders)"},
		{"eOR.Completion.label","Completion"},
		{"eOR.Reqd.label","Reqd."},//Add by Prasad on 7/11/2006 
		{"eOR.AddlInfo(Mandatory).label","Addl. Info. (Mandatory)"},
		{"eOR.AddlInfo(Optional).label","Addl. Info.(Optional)"},
		{"eOR.OrderCatalogByOrderType.label","Order Catalog by Order Type"},
		{"eOR.NoCheck.label","No Check"},
		{"eOR.ActiveGeneric.label","Active Generic"},
		{"eOR.ActiveOrderableStatus.label","Active Orderable Status"},
		{"eOR.AnyOrderableStatus.label","Any Orderable Status"},
		{"eOR.ByOrderable.label","By Orderable"},
		{"eOR.ByActivityType.label","By Activity Type"},
		{"eOR.DepartmentalService.label","Departmental Service"},//added on 9/01/2007
		{"eOR.FieldMnemonicDesc.label","Field Mnemonic Desc"},
		{"eOR.Expires/ExpiredOrderforRenewing.label","Expires/Expired Order for Renewing"},
		{"eOR.PendingForSpecimenCollection.label","Pending For Specimen Collection"},
		{"eOR.CompletedOrders.label","Completed Orders"},
		{"eOR.ID:.label","ID:"},
		{"eOR.Encounter Dtls:.label","Encounter Dtls:"},
		{"eOR.ReasonForReplace.label","Reason for Replace"},
		{"eOR.View/Edit.label","View / Edit"},
		{"eOR.BillingChargesDetails.label","Billing Charges Details"},
		{"eOR.TotalCharge.label","Total Charge"},
		{"eOR.ApprovalReqd.label","Approval Reqd"},
		{"eOR.ConsentFormList.label","Consent Form List"},
		{"eOR.MultipleConsent.label","Multiple Consent"},
		{"eOR.NumberOfConsentRequired.label","Number Of Consent Required"},
		{"eOR.ConsentForCatalog.label","Consent for Catalog"},
		{"eOR.PractitionerForConsent.label","Practitioner for Consent"},
		{"eOR.PractitionerList.label","Practitioner List"},
		{"eOR.Limitto.label","Limit To"},
		{"eOR.PendingDefine.label","Pending Define"},
		{"eOR.ConsentDetailfortheCatalog.label","Consent Detail for the Catalog"},
		{"eOR.BOReq.label","BO Req"},
		{"eOR.BRReq.label","BR Req"},
		{"eOR.andBRReq.label","and BR Req"},
		{"eOR.DefaultForm.label","Default Form"},
		{"eOR.OrderSeq.label","Order Seq"},
		{"eOR.CatalogListfortheOrderCategory.label","Catalog List for the Order Category"},
		{"eOR.andOrderType.label","and Order Type"},
		{"eOR.DefinitionExists.label","Definition Exists"},
		{"eOR.PractForConsentHeader.label","Pract For Consent Header"},
		{"eOR.PractForConsent.label","Pract For Consent"},
		{"eOR.RequiredCount.label","Required Count"},
		{"eOR.ConsentFormforBeforeOrder.label","Consent Form for Before Order"},
		{"eOR.ConsentRequiredfor.label","Consent Required for"},
		{"eOR.AssociateConsent.label","Associate Consent"},
		{"eOR.SNO.label","S. No"},
		{"eOR.Redefine.label","Redefine"},
		{"eOR.ViewConsents.label","View Consents"},
		{"eOR.LinkConsent.label","Link Consent"},
		{"eOR.Consents.label","Consents"},
		{"eOR.Existing.label","Existing"},
		{"eOR.BeforeOrder.label","Before Order"},
		{"eOR.Release.label","Release:"},
		{"eOR.RecordedConsent.label","Recorded Consent -"},
		{"eOR.GenExternalApplicationAccessionNum.label","Gen External Application Accession Num"},
		{"eOR.AllowMultiPatientResulting.label","Allow Multi Patient Resulting"},
		{"eOR.ConsentFormforBeforeOrderRegistration.label","Consent Form for Before Order Registration"},
		{"eOR.ConsentFormforBeforeOrderRelease.label","Consent Form for Before Order Release"},
		{"eOR.ItemNarration.label","Item Narration"},
		{"eOR.IVPrep.label","IV Prep"},
		{"eOR.NoOfRefills.label","No. of Refills"},
		{"eOR.ClickLinkToPrintConsentDetails.label","Click the Link to Print Consent Details"}	,
		{"eOR.ClickonCatalogtoViewIndividualDetails.label","Click on Catalog to View Individual Details"} ,
		{"eOR.SpecimenForOrderable.label","Specimen For Orderable"} ,
		{"eOR.AssignPrivilegeGroup.label","Assign Privilege Group"} ,
		{"eOR.PrivilegeGroupID.label","Privilege Group ID"} ,
		{"eOR.PrivilegeGroupDescription.label","Privilege Group Description"} ,
		{"eOR.Viewing.label","Viewing"} ,
		{"eOR.Authorizing.label","Authorizing"} ,
		{"eOR.Spl-Approving.label","Spl-Approving"} ,
		{"eOR.Co-Signing.label","Co-Signing"} ,
		{"eOR.Resulting.label","Resulting"} ,
		{"eOR.Recording.label","Recording"} ,
		{"eOR.CopyFrom.label","Copy From"} ,
		{"eOR.SelectOrderCategory.label","Select Order Category"} ,
		{"eOR.SelectOrderType.label","Select Order Type"} ,
		{"eOR.SelectOrderCatalog.label","Select Order Catalog"} ,
		{"eOR.SelfOrder.label","Self Order"} ,
		{"eOR.ScheduleTime.label","ScheduleTime"}, //Added by Anjaneya Prasad for order catalog
		{"eOR.ClickLinkToViewConsentDetails.label","Click the Link to View Consent Details"},	//Added by Anjaneya Prasad for consent details in Existing Orders 
		{"eOR.BillNow.label","BillNow"},
		{"eOR.RecordedDate.label","RecordedDate"},
		{"eOR.AddedfacilityID.label","Added Facility"},
		{"eOR.LastRecoredDate.label","Last Modified Date"},
		{"eOR.ModifiedFacilityID.label","Modified Facility"},
		{"eOR.ConsentName.label","Consent Name"},
		{"eOR.DefaultCheck.label","Default Check"},
		{"eOR.BillLater.label","Bill Later"},
		{"eOR.OrderingRuleByPractitionerType.label","Ordering Rule By Practitioner Type"},
		{"eOR.ForceAuthorization.label","Force Authorization"},
		{"eOR.ForceCo-Sign.label","Force Co-Sign"},
		{"eOR.OrderDeptOnlyCatalogs.label","Order 'Dept Only' Catalogs"},
		{"eOR.PendingAppointment.label","Pending Appointment"},
		{"eOR.ConsentsneedtobeattachforthisCatalog.label","There is no Consent linked for this catalog"},
		{"eOR.Linktocurrentencounter.label","Link to Current Encounter"},
		{"eOR.ChildOrder.label","Child Orders"},
		{"eOR.SentOut.label","Sent Out"},
		{"eOR.ReprintSpecimen.label","Reprint Specimen"},
		{"eOR.SpecimenDispatch.label","Specimen Dispatch"},
		{"eOR.IfmoduleisinstalledthenCloseInProcessOrdersafterruleisnotused.label","If module is installed then defined 'In Process Order' rule  wont be used"}, 
		//{"eOR.ExplanatoryText.label","Explanatory Text"},
		//{"eOR.Associate.label","Associate"},// remaining label are to be removed.
		{"eOR.A.label","A"},
		{"eOR.Abnormal.label","Abnormal"},
		{"eOR.AcceptOption.label","Accept Option"},
		{"eOR.ActiveBookings.label","Active Bookings"},
		{"eOR.ActiveProblems.label","Active Problems"},
		{"eOR.Allorders.label","All orders"},
		{"eOR.AllOrders.label","All Orders"} ,
		{"eOR.Amend.label","Amend"},
		{"eOR.Applicableto.label","Applicable to"},
		{"eOR.Appointment.label","Appointment"},						
		{"eOR.AppointmentDate.label","Appointment Date"},
		{"eOR.AppointmentDate.label","Appointment Date:"},
		{"eOR.AppointmentDetails.label","Appointment Details"},
		{"eOR.Approve.label","Approve"},
		{"eOR.approved.label","Approved"},
		{"eOR.Ason.label","As on"},
		{"eOR.Associate.label","Associate"},
		{"eOR.AttendingPractitioner.label","Attending Practitioner"},
		{"eOR.AuditTrail.label","Audit Trail"},
		{"eOR.Authorization.label","Authorization"},
		{"eOR.AuthorizationLevel.label","Authorization Level"},
		{"eOR.AuthorizationReqd.label","Authorization Reqd."},
		{"eOR.Back.label","Back"},
		{"eOR.Between.label","Between"},
		{"eOR.BillDetails.label","Bill Details"},
		{"eOR.Billing.label","Billing"},
		{"eOR.BodyPart.label","Body Part"},
		{"eOR.BookAppointment.label","Book Appointment"},
		{"eOR.Catalog.label","Catalog"},
		{"eOR.Characteristics.label","Characteristics"},
		{"eOR.Charge.label","Charge"},
		{"eOR.ClinicalComments.label","Clinical Comments"},
		{"eOR.Code.label","Code"},
		{"eOR.CodeLevel.label","Code Level"},
		{"eOR.CollectedBy.label","Collected By"},
		{"eOR.Confidential.label", "Confidential"    },
		{"eOR.Consent.label","Consent"},
		{"eOR.Consent.label","Consent"} ,
		{"eOR.ConsentDetails.label","ConsentDetails"},
		{"eOR.ConsentDetails.label","Consent Details"},
		{"eOR.ConsentDetails.label","Consent Details"},
		{"eOR.ConsentForm.label","Consent Form"},
		{"eOR.ConsentNote.label","Consent Note"},
		{"eOR.ConsentNote.label","Consent Note"     },
		{"eOR.ConsentRequired.label", "Consent Required"    },
		{"eOR.ConsentStage.label", "Consent Stage"    },
		{"eOR.ConsentStage.label","Consent Stage"},
		{"eOR.Consenttype.label","Consent type"},
		{"eOR.Continuous.label","Continuous"},
		{"eOR.Copy.label","Copy"},
		{"eOR.Cosign.label","Cosign"},
		{"eOR.CosignReqd.label","Cosign Reqd"},
		{"eOR.Cosigned.label","Cosigned"},
		{"eOR.CriticallyAbnormal.label","Critically Abnormal"},
		{"eOR.DateofBirth.label","Date of Birth"},
		{"eOR.DateofReporting.label","Date of Reporting"},
		{"eOR.DateTime.label","Date/Time"},
		{"eOR.Define.label","Define"},
		{"eOR.DefinitionType.label","Definition Type"},
		{"eOR.Demographics.label","Demographics"},
		{"eOR.Departmental.label","Departmental"},
		{"eOR.Dependency.label","Dependency"},
		{"eOR.Description.label","Description"},
		{"eOR.Detail.label","Detail"},
		{"eOR.Discontinue.label","Discontinue"},
		{"eOR.DiscontinueReason.label","Discontinue Reason"},
		{"eOR.DispatchedBy.label","Dispatched By"},
		{"eOR.DosageBy.label","Dosage By"},
		{"eOR.dose.label","Dose"},
		{"eOR.Dressing.label","Dressing"},
		{"eOR.DrugProfile.label","Drug Profile"},
		{"eOR.Due.label","Due"},
		{"eOR.DurationType.label","Duration Type"},
		{"eOR.Encounter.label","Encounter"},
		{"eOR.EventStatus.label","Event Status"},
		{"eOR.EventStatus.label","Event&Status"},
		{"eOR.ExecuteQuery.label","Execute Query"},
		{"eOR.ExplanatoryText.label","Explanatory Text"},
		{"eOR.ExternalPractitioner.label","External Practitioner"},
		{"eOR.FacilityID.label","Facility ID"},
		{"eOR.FacilityName.label","Facility Name"},
		{"eOR.Fixed.label","Fixed"},
		{"eOR.Form.label","Form"},
		{"eOR.FormatItem.label","Format Item"},
		{"eOR.FormatItem.label","Format Item"},
		{"eOR.Forward.label","Forward"},
		{"eOR.ForwardtoPractitioner.label","Forward to Practitioner"},
		{"eOR.Frequency.label","Frequency"},
		{"eOR.FrequencyCode.label","Frequency Code"},
		{"eOR.Function.label","Function"},
		{"eOR.Green.label","Green"},
		{"eOR.GroupName.label","Group Name"},
		{"eOR.Header.label","Header"},
		{"eOR.Hold.label","Hold"},
		{"eOR.HoldReason.label","Hold Reason"},
		{"eOR.HoldReason.label","Hold Reason"},
		{"eOR.Holiday.label","Holiday"},
		{"eOR.HourAfterDischarge.label","Hour After Discharge"},
		{"eOR.Image.label","Image"},
		{"eOR.InProcess.label","In Process"},
		{"eOR.Included.label","Included"},
		{"eOR.IndexType.label","Index Type"},
		{"eOR.Individual.label","Individual"},
		{"eOR.Intravenous.label", "Intravenous"   },
		{"eOR.LabelText.label","Label Text"},
		{"eOR.Laboratory.label","Laboratory"},
		{"eOR.LastRecordedBy.label","Last Modified By"},
		{"eOR.LessThan.label","Less Than"},
		{"eOR.Level.label","Level"},
		{"eOR.Line.label","Line"},
		{"eOR.LocationDesc.label","Location Desc"},
		{"eOR.LocationFrom.label","Location From"},
		{"eOR.LongDesc.label","Long Desc"},
		{"eOR.Mandatory.label","Mandatory"},
		{"eOR.Max.label","Max"},
		{"eOR.MaxAge.label","Max Age"},
		{"eOR.MedicalTeam.label","Medical Team"} ,
		{"eOR.MedicationAdministration.label","Medication Administration"},
		{"eOR.Min.label","Min"},
		{"eOR.MinAge.label","Min Age"},
		{"eOR.Miscellaneous.label","Miscellaneous"},
		{"eOR.Nature.label","Nature"},
		{"eOR.NetAmount.label","Net Amount"},
		{"eOR.NewOrders.label","New Orders"},
		{"eOR.None.label","None"},
		{"eOR.NotApplicable.label","Not Applicable"},
		{"eOR.note.label","Note"},
		{"eOR.NoteType.label","Note Type"     },
		{"eOR.Old.label","Old"},
		{"eOR.Operator.label","Operator"},
		{"eOR.Option.label","Option"},
		{"eOR.Order.label","Order"},
		{"eOR.Order.label","Order"},
		{"eOR.OrderCatalog.label","Order Catalog"},
		{"eOR.OrdercatalogCode.label","Order catalog Code"},
		{"eOR.OrderCatalogDesc.label","Order Catalog Desc"},
		{"eOR.OrderCatalogDescription.label","Order Catalog Description"},
		{"eOR.OrderDate.label","Order Date"},
		{"eOR.OrderDateFrom.label","Order Date From"},
		{"eOR.OrderDatetime.label","Order Date time"},
		{"eOR.OrderDetails.label","Order Details"},
		{"eOR.OrderEntryTabs.label","Order Entry Tabs"},
		{"eOR.OrderId.label","Order ID"},
		{"eOR.OrderLocation.label","Order Location"},
		{"eOR.OrderNo.label","Order No"},
		{"eOR.OrderTypeCode.label","Order Type Code"},
		{"eOR.Orderable.label","Orderable"},
		{"eOR.Orderable.label","Orderable"},
		{"eOR.OrderedBy.label","Ordered By"},
		{"eOR.Ordering.label","Ordering"} ,
		{"eOR.OrderingFacility.label","Ordering Facility"},
		{"eOR.OrderingFacilityId.label","Ordering Facility Id"},
		{"eOR.OrderingFacilityName.label","Ordering Facility Name"},
		{"eOR.OrderingLocation.label","Ordering Location"},
		{"eOR.OrderingPractitioner.label","Ordering Practitioner"},
		{"eOR.OrganizationType.label","Organization Type"},
		{"eOR.OutpatientAppointments.label","Outpatient Appointments"},
		{"eOR.Outstanding.label","Outstanding"},
		{"eOR.Panel.label","Panel"},
		{"eOR.PartiallyCompleted.label","Partially Completed"},
		{"eOR.Patient.label","Patient"},
		{"eOR.PatientCare.label","Patient Care"},
		{"eOR.PatientClassDescription.label","Patient Class Description"},
		{"eOR.PatientInstruction.label","Patient Instruction"},
		{"eOR.PatientInstructions.label","Patient Instructions"},
		{"eOR.PatientPaid.label","Patient Paid"},
		{"eOR.PatientPayable.label","Patient Payable"},
		{"eOR.patientspecific.label","Patient Specific"},
		{"eOR.Pending.label","Pending"},
		{"eOR.PendingforReviews.label","Pending for Reviews"},
		{"eOR.PerformedOn.label","Performed On"},
		{"eOR.PerformingFacility.label","Performing Facility"},
		{"eOR.PerformingFacilityID.label","Performing Facility ID"},
		{"eOR.PerformingFacilityName.label","Performing Facility Name"},
		{"eOR.PerformingLocation.label","Performing Location"},
		{"eOR.PlaceOrder.label","Place Order"},
		{"eOR.Presentation.label","Presentation"},
		{"eOR.Preview.label","Preview"},
		{"eOR.PrintAt.label","Print At"},
		{"eOR.Printing.label","Printing"},
		{"eOR.PriorityApplicable.label", "Priority Applicable"    },
		{"eOR.Procedure.label","Procedure"},
		{"eOR.Proceed.label","Proceed"},
		{"eOR.Profile.label","Profile"},
		{"eOR.Prompt.label","Prompt"},
		{"eOR.Qty.label","Qty"},
		{"eOR.QtyUnit.label","Qty Unit"},
		{"eOR.QueryCriteria.label","Query Criteria"},
		{"eOR.Radiology.label","Radiology"},
		{"eOR.ReasonCode.label","Reason Code"},
		{"eOR.ReasonDescription.label","Reason Description"},
		{"eOR.RecordedBy.label","Recorded By"},
		{"eOR.Red.label","Red"},
		{"eOR.ReferralFacility.label","Referral Facility"},
		{"eOR.ReferralFacility.label","Referral   Facility"},
		{"eOR.ReferredDate.label","Referred Date"},
		{"eOR.ReferredPractitioner.label","Referred Practitioner"},
		{"eOR.Register.label","Register"},
		{"eOR.Registered.label","Registered"},
		{"eOR.Registration.label","Registration"},
		{"eOR.Reject.label","Reject"},
		{"eOR.Replace.label","Replace"},
		{"eOR.ReportCriteria.label","Report Criteria"},
		{"eOR.ReportedBy.label","Reported By"},
		{"eOR.Reprint.label","Reprint"},
		{"eOR.RescheduledReason.label","Rescheduled Reason"},
		{"eOR.RestrictbyService.label","Restrict by Service"},
		{"eOR.ResultReporting.label","Result Reporting"},
		{"eOR.ResultTemplate.label","Result Template"},
		{"eOR.ResultType.label","Result Type"},
		{"eOR.Review.label","Review"},
		{"eOR.Route.label","Route"},
		{"eOR.ScrubNurse.label","Scrub Nurse"},
		{"eOR.Selected.label","Selected"},
		{"eOR.Selection.label","Selection"},
		{"eOR.SelfRelated.label","Self Related"},
		{"eOR.Separate.label","Separate"},
		{"eOR.SequenceNo.label","Sequence No"},
		{"eOR.ServiceCode.label","Service Code"},
		{"eOR.ServiceDescription.label","Service Description"},
		{"eOR.Sex.label","Sex"},
		{"eOR.ShortDesc.label","Short Desc"},
		{"eOR.SlidingScale.label","Sliding Scale"},
		{"eOR.SoftStop.label","Soft Stop"},
		{"eOR.SourceType.label","Source Type"},
		{"eOR.SpecialApproval.label","Special Approval"},
		{"eOR.SpecialApprovalReqd.label","Special Approval Reqd"},
		{"eOR.SpecialApprovalRequired.label","Special Approval Required"},
		{"eOR.SpecimenCollection.label","Specimen Collection"},
		{"eOR.SpecimenDetails.label","Specimen Details"},
		{"eOR.SpecimenType.label","Specimen Type"},
		{"eOR.Stage.label","Stage"},
		{"eOR.Standard.label","Standard"},
		{"eOR.Stat.label","Stat"},
		{"eOR.Stat.label","Stat"},
		{"eOR.Stop.label","Stop"},
		{"eOR.Strength.label","Strength"},
		{"eOR.Summary.label","Summary"},
		{"eOR.Suspended.label","Suspended"},
		{"eOR.SystemDefined.label","System Defined"},
		{"eOR.Taper.label","Taper"},
		{"eOR.Task.label","Task"},
		{"eOR.TDMDetails.label","TDM Details"},
		{"eOR.TemplateID.label","Template ID"},
		{"eOR.TemplateName.label","Template Name"},
		{"eOR.TermCode.label","Term Code"},
		{"eOR.TermCodeDescription.label","Term Code Description"},
		{"eOR.TermSet.label","Term Set"},
		{"eOR.TermSetDescription.label","Term Set Description"},
		{"eOR.TermSetID.label","Term Set ID"},
		{"eOR.Text.label","Text"},
		{"eOR.Text Block.label","Text Block"},
		{"eOR.Title.label","Title"},
		{"eOR.TitleText.label","Title Text"},
		{"eOR.Top.label","Top"},
		{"eOR.Total.label","Total"},
		{"eOR.TransfusionsHistory.label","Transfusion History"},
		{"eOR.Treatment.label","Treatment"},
		{"eOR.Ultrasound.label","Ultrasound"},
		{"eOR.Unit.label","Unit"},
		{"eOR.UOM.label","UOM"},
		{"eOR.Up.label","Up"},
		{"eOR.UserDefined.label","User Defined"},
		{"eOR.Values.label","Values"},
		{"eOR.Variable.label","Variable"},
		{"eOR.Variance.label","Variance"},
		{"eOR.ViewDetails.label","View Details"},
		{"eOR.VisitAdmDate.label","Visit Adm Date"},
		{"eOR.Warn.label","Warn"},
		{"eOR.Warning.label","Warning"},
		{"eOR.Years.label","Years"},
		{"eOR.Yellow.label","Yellow"},
		{"eOR.YesNo.label","Yes/No"},
		{"eOR.RoundOffStartTime.label","Round Off Start Time"},
		{"eOR.SpecifictoCatalog.label","Specific to Catalog"},
		{"eOR.ConsentList.label","Consent List"},
		{"eOR.RequestComment.label","Request Comment"},
		{"eOR.ClinicalCommentMandatory.label","Clinical Comment Mandatory"},
		{"eOR.SpecialityForOrderable.label","Speciality For Orderable"},
		{"eOR.PlaceOrdersForOtherPractitioners.label","Place Orders For Other Practitioners"},
		{"eOR.AllowedType.label","Allowed Type"} ,
		{"eOR.InvestigationCheckList.label","Investigation Check List"} ,
		{"eOR.ServiceDateFrom.label","Service Date From"} ,
		{"eOR.IncludeCancelledTests.label","Include Cancelled tests"} ,
		{"eOR.IncludedOnlyBilledTests.label","Included only billed tests"} ,
		{"eOR.Discard.label","Discard"},
		{"eOR.IncludeBilledTests.label","Include Billed Tests"}, 
		{"eOR.Rectime.label","Rec.Time"}, 
		{"eOR.Disdate.label","Dis.Date"},
		{"eOR.Distime.label","Dis.Time"}, 
		{"eOR.OrderSetBillingDetails.label","Order Set Billing Details"},
		{"eOR.NonSpecific.label","Non Specific"},
		{"eOR.DuplicateOrders.label","Duplicate Orders"},
		{"eOR.EmailPreview.label","Email Preview"},
		{"eOR.AddlSearch.label","Addl. Search"},
		{"eOR.TimeRoundedto.label","Time-Rounded to:"},
		{"eOR.QuarterHour.label","Quarter Hour"},
		{"eOR.OrderDetails.label","Order Details"},
		{"eOR.CloseBilledOrder.label","Close Billed Order"},
		{"eOR.IgnoreOrdersPlacedWithin.label","Ignore Orders Placed Within"},
		{"eOR.ReverseCharge.label","Reverse Charge"},
		{"eOR.AutoCloseUseBillingRule.label","Auto Close  Use Billing Rule"},
		{"eOR.OrderStartDate.label","Order Start Date"},
		{"eOR.DefaultResultValues.label","Default Result Values"},
		{"eOR.ValueDifferedFromDefaultResult.label","Value differed from the Default Result value"},
		{"eOR.StartDateTime.label","Start Date Time"},
		{"eOR.OtherResultFormats.label","Other Result Formats"},
		{"eOR.ResultFormat.label","Result Format"},
		{"eOR.OrderStartPeriod.label","Order Start Period"},
		{"eOR.ExternalPatientOrder.label","External Patient Order"},
		{"eOR.AllowMultiPatientResulting.label","Allow Multi Patient Resulting"},
		{"eOR.FillDetails.label","Fill Details"},
		{"eOR.ElapsedOrders.label","Elapsed Orders"},
		{"eOR.ResultTypeDisplayControl.label","Result Type Display Control"},
		{"eOR.BackToMultiPatientOrders.label","<< Back to Multi Patient Orders"},
		{"eOR.AppointmentFromPerformingFacility.label","Book Appointment is possible only from Performing Facility"},
		{"eOR.RescheduleFromPerformingFacility.label","Reschedule is possible only from Performing Facility"},
		{"eOR.LinkFutureOrderToCurrentEncounter.label","Link future order to the current encounter during visit registration/admission applicable"},
		{"eOR.ControlByPrivilegeGroupSetup.label","Control by privilege group setup"},
		{"eOR.OrderAuthorisation.label","Order Authorisation"},
		{"eOR.DelinkCurrentSetup.label","Delink Current Setup"},
		{"eOR.ChangeCurrentSetup.label","Change Current Setup"},
		{"eOR.LimitToMyApplicableCatalogs.label","Limit to My Applicable Catalogs"},
		{"eOR.MySpeciality.label","My Speciality"},
		{"eOR.FutureOrderLinking.label","Future Order Linking Applicability"},
		{"eOR.PostedToFolioButNotBilledReceipted.label","Posted to Folio but not Billed / Receipted"},
		{"eOR.BilledButNotReceipted.label","Billed but not Receipted"},	
		{"eOR.MaxAllowedPeriodFromCurrentDay.label","Max allowed Period from Current Day"},	
		{"eOR.LinkedVaccineName.label","Linked Vaccine Name"},
		{"eOR.Repeat.label","Repeat"},
		{"eOR.AllCategories.label","All Categories"},
		{"eOR.AuthorizeForceAuthorization.label","Authorize Force Authorization"},
		{"eOR.AuthorizationApplicable.label","Authorization Applicable"},
		{"eOR.IncludeForceAuthorization.label","Include Force Authorization"},
		{"eOR.MyPatientAndMyRelatedPatient.label","My Patient and My Related Patient"},
		{"eOR.MyPatientAndMyLocationPatient.label","My Patient and My Location Patient"},
		{"eOR.MyPatient.label","My Patient"},
		{"eOR.MyRelatedPatient.label","My Related Patient"},
		{"eOR.MyLocationPatient.label","My Location Patient"},
		{"eOR.CGItemCode.label","CG Item Code"},
		{"eOR.Baht.label","Baht"},
		{"eOR.PrintedDateTime.label","Printed Date/Time"},
		{"eOR.InvokeSettlementScreenForPatClass.label","Invoke Settlement Screen For Patient Class"},
		{"eOR.InvokePrintReportForBilling.label","Invoke Print Report For Billing"},
		{"eOR.DefaultRefundOptionForDiscontinueOrder.label","Default Refund Option For Discontinue Order"},
		{"eOR.NOSCHEDULE.label","No Schedule set for selected frequency"},
		{"eOR.ExternalApplicationAccessionNo.label","External Application Accession No :"},
		{"eOR.ReportType.label","Report Type"},
		{"eOR.GroupingCode.label","Grouping Code"},
		{"eOR.GroupingDescription.label","Grouping Description"},
		{"eOR.PrintReportFormat.label","Print Report Format"},
		{"eOR.ApplicableOrderType.label","Applicable Order Type"},
		{"eOR.multipleRepPract.label","Multiple reporting practitioners available"},
		{"eOR.repPractNotSpc.label","Reporting Practitioner is not specified"},
		{"eOR.OrderFormatSheet.label","Order Format Sheet"},
		{"eOR.OrderSheetForLaboratory.label","Order Sheet For Laboratory"},
		{"eOR.OrderSheetForBT.label","Order Sheet For BT"},
		{"eOR.OrderSheetForOthers.label","Order Sheet For Others"},
		{"eOR.Duration.label","Duration"},
		{"eOR.Week(s).label","Week(s)"},
		{"eOR.Day(s).label","Day(s)"},
		{"eOR.Month(s).label","Month(s)"},
		{"eOR.Year(s).label","Year(s)"},
		{"eOR.OrderedFromRadiology.label","Ordered From Radiology"},
		{"eOR.Reason.label","Reason"},
		{"eOR.PasteDetails.label","Paste Details"},
		{"eOR.CollectionTime.label","Collection Time"},
		/*Added by Uma on 1/12/2010 for IN017231 PMG20089-CRF-0830*/
		{"eOR.RejectOrders.label","Reject Orders"},
		{"eOR.WarningOrders.label","Warning Orders"},
		/*Ends Here*/
		/*Added by Uma on 1/12/2010 for IN017231 PMG20089-CRF-0829*/
		{"eOR.MyRelatedPatients.label","My Related Patients"},
		{"eOR.OrderedPatients.label","Ordered Patients"},
		{"eOR.MyPatients.label","My Patients"},
		/*Ends Here*/
		/*Added by Sridhar Reddy on 21/01/2010 for IN014775 PMG20089-CRF-0791*/
		{"eOR.SpecimenNoFormat.label","Specimen No Format"},
		{"eOR.SpecimenLabelFormat.label","Specimen Label Format"},
		{"eOR.SpecimenFormatType.label","Specimen Format Type"},
		{"eOR.ExternalApplication.label","External Application"},
		{"eOR.IBARL.label","IBARL"},
		{"eOR.IBAOR.label","IBAOR"},
		{"eOR.RunningSerialNo.label","Running Serial No"},
		/*End*/
		/*Added by Uma on 1/29/2010 for IN016226 PMG20089-CRF-0804*/
		{"eOR.CompletionRemarksMandatory.label","Completion Remarks Mandatory"},
		{"eOR.OrderClinicalNoteResultType.label","Order Clinical Note Result Type"},
		{"eOR.RestrictAutoCompleteForClinicalNote.label","Restrict auto complete of result status to $ upon sign for clinical note result type"},
		{"eOR.ResultComplete.label","Resulted-Complete"},
		/*Ends Here*/
		/*Added by Uma on 2/2/2010 for CRF 39 &412*/
		{"eOR.Dx.label","Dx"},
		{"eOR.AN.label","AN"},
		/*Ends Here*/
		{"eOR.ValidPeriod.label","Valid Period"},
		{"eOR.PackageRef.label","Package Ref"},
		{"eOR.ConsultDate.label","Consult Date"},
		{"eOR.IncludeSystemCancelledOrders.label","Include System Cancelled Orders"},
		{"eOR.ViewReplacedOrder.label","View Replaced Order"},
		{"eOR.ViewOriginalOrder.label","View Original Order"},
		{"eOR.OrderSetLevel.label","Order Set Level"},
		{"eOR.OrderableLevel.label","Orderable Level"},
		{"eOR.Chargable.label","Chargeable"},
		/*Added by Arvind  on 4/19/2010 for CRF 804 */
		{"eOR.PerformedOnly.label","Completed - Results Only"},
		{"eOR.MaxPeriodtoModifyCompletedResults.label","Max. Period to Modify Completed-Results"},
		{"eOR.By24Hrs.label","By 24 Hrs."},
		/*Ends Here*/
		/*PMG20089-CRF-0791*/
		{"eOR.SeqStartsWith.label","Starts With"},
		{"eOR.SeqMaxNo.label","Max No"},
		{"eOR.DateDDMMYY.label","Date (DDMMYY)"},
		{"eOR.DateDDMMYYYY.label","Date (DDMMYYYY)"},		
		{"eOR.SpecimenCollectedTime.label","Specimen Collected Time"},		
		{"eOR.IncludeCheckedOutPatients.label","Include Checked Out Patients"},						
		/*End Here*/
		{"eOR.PromptforBookApptonOrder.label","Prompt for Book Appt on Order"},
		//---[IN029071]/start---
		{"eOR.DayAfterDisAdv.label","Day After Discharge Advice"},
		{"eOR.HourAfterDisAdv.label","Hour After Discharge Advice"},
		//---[IN029071]/end-----
		//--[IN029395]--Start
		{"eOR.OTPreferredSurgery.label","OT Surgery Order"},
		{"eOR.OTPreferredDate.label","Preferred Surgery Date Ahead"},
		//--[IN029395]--End
		{"eOR.ChkPendingOrders.label","Check for Pending Orders before Discharge Advice"},//IN028981
		{"eOR.Hold/Discontinue.label","Reason code for Hold/Discontinue is Mandatory"},//IN028417
		{"eOR.SecurePINPlaceOrder.label","PIN number for Placing Orders"},//IN029143
		{"eOR.AUTH_SCREEN.label","Authorisation Screen"},//IN029143
		{"eOR.PractitionerName.label","Practitioner Name"},//IN029143
		{"eOR.Unbilled.label","Unbilled"},//IN030589
		{"eOR.OrderFrequency.label","Order Frequency"},//Menaka
		{"eOR.GroupBy.label","Group By"},//Menaka
		{"eOR.SingleOrder.label","One day Orders"},//Menaka
		{"eOR.ContinuousOrder.label","Continuous orders"},//Menaka
		{"eOR.All.label","All"},//Menaka
		{"eOR.DispCustCat.label","Custom Category Yes/No"},//DineshT
		{"eOR.OrderName.label","Order Name"},//DineshT
		{"eOR.CustCat.label","Custom Category"},//Menaka
		{"eOR.ChkPendOrders.label","Check for Pending Orders before Discharge"}, //IN028763
		{"eOR.NPBRequestForm.label","NPB Request Form"},  // IN029935
		{"eOR.NotifyAlert.label","Notification - Alert"},  //IN033610 
		{"eOR.NonOTRooms.label","Non OT Rooms"},//CRF 31901		
		{"eOR.PlaceOrders.label","Place Orders"},//CRF-0160	
		{"eOR.ViewAllOrders.label","View All Orders"},//CRF-0160		
		{"eOR.PostMortemAppl.label","Post Mortem Applicability"},//CRF-0160		
		{"eOR.PostMortemType.label","Post Mortem Type"},//CRF-0160			
		{"eOR.OrderCategoryCode.label","Order Category Code"}, // CRF-0160
		{"eOR.PostMortem.label","Post Mortem"} ,//CRF-0160
		{"eOR.appl.label","Applicability"}, //CRF-0160
		{"eOR.Type.label","Type"}, //CRF-0160
		{"eOR.PatientInterventions.label","Patient Instructions for Interventions"}, //IN030473
		{"eOR.Intervention.label","Intervention"}, //IN030473
		{"eOR.PatientInstructionsPrintPreview.label","Patient Instructions Print Preview"}, //IN030472
		{"eOR.FollowVisitType.label","Follow Visit Type"}, //IN031304
		{"eOR.SelectrowtoRemove.label","Select row to Remove"}, //CRF-0160
		{"eOR.AllowOrdersforDeceased.label","Allow Orders"}, //CRF-0160
		{"eOR.OnHoldRemarks.label","On Hold - Remarks"}, //IN029949
		{"eOR.dispbillinginfo.label","Display Billing Information"}, //IN035929
		{"eOR.MARStatus.label","MAR Status"}, //IN038336
		{"eOR.OrderSearchResultDisplayinVerticalOrder.label","Order Search Results Display in Vertical Order"}, //IN038787
		{"eOR.dupoverridereason.label","Dup Override Reason"}, //	IN024984
		{"eOR.ExternalLink.label","External Link"}, // IN047204
		{"eOR.DuplicateReasonRequired.label","Duplicate Override Reason Required"}, //IN024984
		{"eOR.DurationValue.label","Duration Value"}, //IN041644
		{"eOR.PrintOption.label","Print Option"}, //IN042962
		{"eOR.SilentAlert.label","Silent Alert"}, //IN042962
		{"eOR.ConfirmAlert.label","Confirm Alert"}, //IN042962
		{"eOR.OfflineAlert.label","Offline Alert"}, //IN042962
		{"eOR.PrintOrderSheet.label","Print Order Sheet"}, //IN042962
		{"eOR.CurrentIPList.label","Current IP List"}, //IN047918
		{"eOR.routineurgent.label","Routine/Urgent"}, //IN048467
		{"eOR.routinestat.label","Routine/STAT"}, //IN048467
		{"eOR.urgentstat.label","Urgent/STAT"}, //IN048467
		{"eOR.routineurgentstat.label","Routine/Urgent/STAT"}, //IN048467
		{"eOR.skipauthorization.label","Skip Authorization based on priority"}, //IN048467
		{"eOR.ServiceUnbilled.label","Service Unbilled"}, //IN050209
		//IN049419 - Start
		{"eOR.AmendOrder.label","Amend"}, 
		{"eOR.amenddate.label","Amended Date"},
		{"eOR.amendby.label","Amended By"},
		{"eOR.amendreason.label","Amended Reason"},
		{"eOR.amendreason1.label","Amend Reason"},
		{"eOR.auditforamendorders.label","Audit Applicable for Amending Orders"},
		{"eOR.amendreasonreqd.label","Order Amending Reason Required"},
		{"eOR.amendreasonmand.label","Order Amending Reason Mandatory"},
		{"eOR.OrderFormatAuditTrail.label","View Audit Trail - Order Format"},
		{"eOR.OrderFormatLineAuditTrail.label","View Audit Trail - Order Format Line"},
		//IN049419 - End
		//IN052649 - Start
		{"eOR.others.label","Others"},
		{"eOR.orderingspecialitycopypreviousorder.label","Specialty Filter in Copy Previous Orders"},//IN054122
		{"eOR.notapplicable.label","Not Applicable"},
		{"eOR.primaryspeciality.label","Primary Specialty"},//IN054122
		{"eOR.encounterspeciality.label","Encounter Specialty"},//IN054122
		{"eOR.defaultperiodincopypreviousorders.label","Default Period in Copy Previous Orders"},
		//IN052649 - End.
		{"eOR.comments.label","Comments"}, //IN052230
		{"eOR.dispslipbarcodesearch.label","Allow Dispatch Slip Barcode Search"}, //IN055737 HSA-CRF-0250.1 
		{"eOR.recordConsentFormWithOrder.label","Record Consent Form With Order"}, //IN057196
		//IN055027 - Starts
		{"eOR.rptshift1.label","Statistics report by Practitioner"},
		{"eOR.rptshift2.label"," Statistics report by year/month"},
		{"eOR.practitionerfrom.label","Practitioner From"},
		{"eOR.practitionerto.label","Practitioner To"},
		//IN055027 - Ends
		{"eOR.NationalId.label","National ID"}, //IN058811
		{"eOR.CompletedOrderStatus.label","Completed Order Status"}, //MO-CRF-20085 [IN051135]
		{"eOR.ApplyOrdPrivRuleOnly.label","Apply Order privilege Rules only"}, //ML-MMOH-CRF-0493 [IN059086]
		{"eOR.diseasecode.label","Disease Code(HAAD)"}, //AAKH-CRF-0083.1 [IN060590]
		{"eOR.ordmultselnonmandat.label","Multiselect List Item is Mandatory"},  // ML-MMOH-CRF-0508.1 [IN062319] 
		{"eOR.ResultsViewed.label","Results Viewed"},//IN062669
		{"eOR.Applicability.label","Applicability"},//IN062669
		{"eOR.BarcodeRequired.label","Barcode Required"},//IN063816
		{"eOR.BarcodePrintButton.label","Barcode Reprint"}, //IN063816
		{"eOR.BarcodePrint.label","Barcode Reprint"}, //IN063816
		{"eOR.NOTDONE.label","Not Done"}, //IN061903
		{"eOR.NotDoneReasonMand.label","Reason code for Not Done is Mandatory"}, //IN061903
		{"eOR.NotDoneReason.label","Not Done Reason "}, //IN061903
		{"eOR.DosageType.label","Dosage Type"},//IN062992
		{"eOR.M2.label","M2"},//IN062992
		{"eOR.Kg.label","Kg"},//IN062992
		{"eOR.Age.label","Age"},//IN062992
		{"eOR.OncoRegimenFreq.label","Oncology Regimen Freq"},//IN062992
		{"eOR.AgeGroupDef.label","Age Group Definition(Min, Max)"},//IN062992
		{"eOR.Applicable.label","Applicable"},//IN062992
		{"eOR.ReRoutePrinter.label","Re-Route Printer"},//IN064835
		{"eOR.AckOrder.label","Acknowledged Order"}, //IN065091
		{"eOR.PrintRegStatus.label","Print Label for registered order"},//IN065942
		{"eOR.RegisterLabel.label","Register Label"},//IN065942		
		{"eOR.RefRange.label","Reference Range"}, //IN063813
		{"eOR.LabSpecimenNotRegister.label","Lab Specimen - Not Registered"},//ML-MMOH-CRF-0544 IN061892
		{"eOR.TimeFrameAlertForLab.label","Time frame to alert Urgent/Stat Lab Specimen"},//ML-MMOH-CRF-0544 IN061892
		{"eOR.SpeciDateTime.label","Specimen Dispatch Date/Time"},//ML-MMOH-CRF-0544 IN061892
		{"eOR.PatientPhoto.label","Patient Photo"},//IN063974
		//{"eOR.ReplaceThroughTermSet.label","Replace Order through Term Set"},  //IN061890 commented for ML-MMOH-CRF-1076[IN066548] 
		{"eOR.ReplaceThroughTermSetAndCategory.label","Replace Order through Term Set wise / Category wise"},// added for ML-MMOH-CRF-1076[IN066548]
		{"eOR.InActiveOrders.label","Inactive Orders"},//IN065925
		{"eOR.CancelOption.label","Cancel option for Daycare & Inpatient"},//IN065925
		{"eOR.RejectedRemarks.label","Rejected Remarks"},//IN061893
		{"eOR.RejectedDateTime.label","Rejected Date/Time"},//IN061893
		{"eOR.ViewAmndReason.label","View Amend Reasons"}, //IN065844
		{"eOR.AmndDate.label","Amend Date/time"}, //IN065844
		{"eOR.AmndOrdId.label","Amend Order Id"}, //IN065844
		{"eOR.AmndReason.label","Amend Reason"}, //IN065844
					//added for IN065642 START
{"eOR.sNo.label","S.No"},
{"eOR.ExamStatus.label","Exam Status"},
 {"eOR.PerformingBy.label","Performing By"},
 {"eOR.Date.label","Date"},
{"eOR.ViewRemarks.label","View Remarks"},
{"eOR.OnHold.label","On Hold"},
 {"eOR.Prelim.label","Prelim"},

{"eOR.radiologist.label","Radiologist"}, //IN065642
{"eOR.assigndiag.label","Assign"},
{"eOR.HideSpecimenTypeInResults.label","Hide Specimen Type In Results"},//IN066119
{"eOR.HideReportingPractitioner.label","Hide Reporting Practitioner In Results"},//IN066119
{"eOR.DisSelectAllOptn.label","Disable Select All Option Applicable"},  //IN064980
{"eOR.ReplaceOrderableType.label","Replace orderable type"},//IN066548
{"eOR.CategoryWise.label","Category wise"},//IN066548
{"eOR.InvokeInstructionWindow.label","Invoke Instruction Window"},//IN064543
{"eOR.InstrnContentType.label","Instruction Content Type"},//IN64543
{"eOR.RestrictAEEncounters.label","Restrict placing order against OP/ER encounter, if IP/DC open encounter exists"},//IN063719
{"eOR.DosageTypeDefn.label","Dosage Type Defn"},//IN68241
{"eOR.OccurranceNo.label","Occurrance No"},//IN68241
{"eOR.ByDosageTypeDefn.label","By Dosage Type Definition"},//IN68241
{"eOR.OrderSetSearch.label","OrderSet Search"},//IN009063
{"eOR.PendingAuth.label","Pending Authorization"},//IN068673
{"eOR.SecSpecialitiesForMySpecialty.label","Secondary Specialty applicable for My Specialty Filter."},//IN068673
{"eOR.CategoryNo.label","Category No"},//IN066453
{"eOR.Facilities.label","Facilities"},//IN068370,IN068373
{"eOR.ApplicableFacilities.label","Applicable Facilities"}, //IN068370,IN068373
//IN068778 Start.
{"eOR.UploadImagesVideos.label","Upload Associate Images/Videos"}, //IN70146
{"eOR.Sno.label","S.No"},	
{"eOR.Jpg.label","JPG"},	//IN70146
{"eOR.Gif.label","GIF"}, 	
{"eOR.Pdf.label","PDF"}, 	
{"eOR.Mp4.label","MP4"},
//IN068778 End.
{"eOR.VideoFileList.label","Video File List"},//IN068314
{"eOR.NONFPPPATIENT.label","Non Fully Paying Patient"},//IN068314
{"eOR.FPPPATIENT.label","Fully Paying Patient"},//IN068314
{"eOR.Simple.label","Simple"},//IN068314
{"eOR.Medium.label","Moderate"},//IN068314
{"eOR.Complex.label","Complex"},//IN068314
{"eOR.FPPCATEGORYS.label","Applicable FPP Category"},//IN068314
{"eOR.FPPDETAILS.label","FPP Details"},//IN068314
{"eOR.FilterByFPP.label","Filter By FPP"},//IN068314
{"eOR.FPPCATEGORY.label","FPP Category"},//IN068314
{"eOR.Fully/Partial.label","Fully/Partial billed or paid"},//IN071618//IN072654
{"eOR.InteractionDtls.label","Interaction Dtls"},//IN072654
{"eOR.PractTypeTimeBasedRule.label","Apply Time Based Rules applicable in Ordering Rule By Practitioner Type"},//IN071361
{"eOR.DayAfterDischargeAdvice.label","Day After Discharge Advice"},//IN071361
{"eOR.HourAfterDischargeAdvice.label","Hour After Discharge Advice"},//IN071361
{"eOR.FreqOrderAsIndividualOrders.label","Frequency Orders Considered As Individual Orders"},//7540
{"eOR.BillingStatus.label","Billing Status"},//19112
{"eOR.PrimaryDiagnosisMandatory.label","Primary Diagnosis Mandatory"}, //6868
{"eOR.DefaultOrderStatus.label","To Default Order Status in One Day and Continue Order"}, //IN27705
{"eOR.OneDayContOrder.label","One Day And Continuous Order"}, //IN27705
{"eOR.ApplyOrderingRulesByPractitionerType.label","Apply Ordering Rules by Practitioner Type to Restrict Departmental Orders from Copy Previous order"},//37018 
{"eOR.QuePkiCode.label","Queue PKID"}, //35142
{"eOR.Quotalimit.label","Quota Limit Approval"}, //40016
{"eOR.RestrictPlacingOrdersForSelf.label","Restrict Placing Orders For Self"},//29147
{"eOR.RestrictPlacingOrdersForFamilyMembers.label","Restrict Placing Orders For Family Members"}, //29147
{"eOR.Quota.ApprovalReqd.label","Quota. Approval Reqd."},//40016
	};
}
