/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eOR.resources; 

import java.util.*;

public class  Labels_ar  extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
		return contents;
	} 

	static final Object[][] contents = {
		{"eOR.ActionedBy.label","حركة بواسطة"},
		{"eOR.AccessionNumberingRules.label","قواعد ترقيم رقم الوصول"},
		{"eOR.AcknolwedgetheResults.label","تأكيد النتائج"},
		{"eOR.ActionwhenPreparationDurationnotmet.label","الإجراء في حال تعدي مدة التحضير "},
		{"eOR.Actionstakentoresolvecomplications.label","الإجراء لحل المضاعفات"},
		{"eOR.ActiveOrders.label","أوامر نشطة"},
		{"eOR.ActivityType.label","نوع النشاط"},
		{"eOR.ActivityTypeCode.label","كود نوع النشاط"},
		{"eOR.AgeSex.label","العمر / الجنس"},
		{"eOR.AheadPeriod.label","الفترة القادمة"},
		{"eOR.AlertDept.label","قسم التنبيهات"},
		{"eOR.Alphanumeric.label","ترقيم ابجدى رقمى"},
		{"eOR.AncillaryDept.label","قسم الإضافات"},
		{"eOR.Anesthesia.label","تخدير"},
		{"eOR.ApplicabilityofOrderPrivileges.label","إمكانية تحديد صلاحيات الأوامر"},
		{"eOR.ApplicationUser.label","مستخدم التطبيق"},
		{"eOR.AppointmentBooked.label","تم حجز الموعد"},
		{"eOR.AppointmentLocation.label","مكان الموعد"},
		{"eOR.AppointmentRescheduled.label","تغير ميعاد الحجز"},
		{"eOR.ApptRequired.label","مطلوب"},
		{"eOR.AssignPrivileges.label","امتيازات"},
		{"eOR.AssistingSurgeon.label","جراح مساعد"},
		{"eOR.Atresulting.label","عند ظهور النتيجة"},
		{"eOR.AuthorisationInfo.label","بيانات التصريح"},
		{"eOR.AuthorizeOrders.label","تصريح الأوامر"},
		{"eOR.AutoClosingRulesforPendingOrders.label","قواعد انهاء الأوامر المعلقة"},
		{"eOR.AutoLink.label","رابط آلى"},
		{"eOR.AutoRegistration.label","تسجيل آلى"},
		{"eOR.AutoRegistrationReqd.label","طلب التسجيل الآلى"},
		{"eOR.AutoUpdateCollectionDateTime.label","تحديث تلقائى للوقت والتاريخ"},
		{"eOR.AutoLinktoCatalogCode.label","ربط آلى لأكواد الكتالوج"},
		{"eOR.BehindPeriod.label","فترة سابقة"},
		{"eOR.Biochemistry.label","الكيمياء الحيوية"},
		{"eOR.BloodTransfusion.label","نقل الدم"},
		{"eOR.BloodTransfusionHistory.label","تاريخ نقل الدم"},
		{"eOR.BodyOrgan.label","عضو بالجسد"},
		{"eOR.ByYearandJulianDate.label","باستخدام تقويم جوليان "},
		{"eOR.CatalogDescription.label","وصف الكتالوج"},
		{"eOR.CatalogName.label","اسم الكتالوج"},
		{"eOR.CatalogSearch.label","بحث الكاتالوج"},
		{"eOR.CatalogSynonym.label","مرادف الكتالوج"},
		{"eOR.CatalogSynonymType.label","نوع مرادف الكتالوج"},
		{"eOR.ChangeChargeType.label","تغيير نوع النفقات"},
		{"eOR.ChangePerformingLocation.label","تغيير مكان تأدية الخدمة"},
		{"eOR.ChangeQtydose.label","تغيير الكمية / الجرعة"},
		{"eOR.ChargeDtls.label","تفاصيل النفقات"},
		{"eOR.ChargeType.label","نوع النفقات"},
		{"eOR.ChargeTypeCode.label","كود نوع النفقات"},
		{"eOR.ChargeTypeDescription.label","وصف نوع النفقات"},
		{"eOR.ClinicalSrv.label","خدمة سريرية"},
		{"eOR.CloseInProcessOrdersafter.label","إغلاق الأوامر الجارية بعد"},
		{"eOR.CloseUnprocessedOrdersafter.label","إغلاق الأوامر الغير جارية بعد"},
		{"eOR.Cmts.label","وسائط"},
		{"eOR.CoSignLevel.label","مستوى توقيع مشترك"},
		{"eOR.CollectionDateAndTime.label","تجميع الوقت والتاريخ"},
		{"eOR.CollectionDetails.label","تفاصيل التجميع"},
		{"eOR.CollectionList.label","قائمة التجميع"},
		{"eOR.CollectionStage.label","مرحلة التجميع"},
		{"eOR.Columns.label","أعمدة"},
		{"eOR.CommonLookUps.label","أبحاث مشتركة"},
		{"eOR.CompleteRemarks.label","ملاحظات كاملة"},
		{"eOR.CompletionDateFrom.label","موعد الاكتمال من"},
		{"eOR.ConfirmAuthorise.label","تأكيد الصلاحية"},
		{"eOR.ConflictExam.label","اختبار التعارض"},
		{"eOR.ConflictExamDateTime.label","موعد/ توقيت اختبار التعارض"},
		{"eOR.ConflictExamDescription.label","وصف اختبار التعارض"},
		{"eOR.ConflictswithItem.label","متعارض مع عنصر"},
		{"eOR.ConsentForms.label","نموذج الإقرار"},
		{"eOR.ConsentInfo.label","بيانات الإقرار"},
		{"eOR.ConsentNotes.label","ملاحظات الإقرار"},
		{"eOR.ConsentOrder.label","أمر الإقرار"},
		{"eOR.ConsentRequiredfromthePatient.label","نموذج الإقرار مطلوب من المريض"},
		{"eOR.ConsentRefusal.label","إقرار/ رفض"},
		{"eOR.ConsentRefusalReferralNotes.label","إقرار/ رفض/ ملاحظات التحويل"},
		{"eOR.ConsentedDateandTime.label","موعد وتوقيت الإقرار"},
		{"eOR.Consults.label","استشارات"},
		{"eOR.ContMed.label","استئشارة طبية"},
		{"eOR.Contain.label","يحتوى"},
		{"eOR.ContraSysModule.label","أوامر نظام مضادة"},
		{"eOR.CopyOrders.label","نسخ الأوامر"},
		{"eOR.CopyPrevious.label","نسخ السابق"},
		{"eOR.CopyPrev.label","نسخ السابق"},
		{"eOR.CosignOrders.label","أوامر ذات توقيعات مشتركة"},
		{"eOR.CreateasContinuingOrder.label","إنشاء كأوامر مستمرة"},
		{"eOR.CultureTest.label","تحليل مزرعة"},
		{"eOR.CurrentEncounterOrders.label","وامر الزيارة الجارية"},
		{"eOR.DateofReceipt.label","تاريخ اللإيصال"},
		{"eOR.DateofReferral.label","تاريخ التحويل"},
		{"eOR.DateofRegistration.label","تاريخ التسجيل"},
		{"eOR.DayAfterAdmVist.label","يوم بعد الدخول / الزيارة"},
		{"eOR.DefaultAutoReport.label","التقرير الآلى الافتراضى"},
		{"eOR.DefaultNumber.label","الرقم الافتراضى"},
		{"eOR.DefaultOrderRepeats.label","الأوامر المكررة افتراضيا"},
		{"eOR.DefaultTiming.label","التوقيت الافتراضى"},
		{"eOR.DepartmentInstruction.label","تعليمات القسم"},
		{"eOR.DepartmentInstructions.label","تعليمات الأقسام"},
		{"eOR.DepartmentalDiagnostics.label","تشخيصات الأقسام"},
		{"eOR.Dependent.label","مستقل"},
		{"eOR.DeptLocation.label","موقع القسم"},
		{"eOR.Diagnostic.label","تشخيصى"},
		{"eOR.DirectCare.label","رعاية مباشرة"},
		{"eOR.DischargeIndicator.label","مؤشر الخروج"},
		{"eOR.DiscontinuedOrders.label","أوامر غير مستمرة"},
		{"eOR.DiscontinuedCancelled.label","غير مستمرة / ملغاة"},
		{"eOR.DispatchDateTime.label","موعد وتوقيت الإفادة"},
		{"eOR.DispatchDetails.label","بيانات الإفادة"},
		{"eOR.DispatchMode.label","وضع الإفادة"},
		{"eOR.DisplayLocation.label","موقع العرض"},
		{"eOR.DonotPrint.label","غير مسموح بالطباعة"},
		{"eOR.DoyouwanttoPlaceanRapidOrder.label","هل تريد وضع امر سريع"},
		{"eOR.Done.label","تم"},
		{"eOR.DosageUnit.label","جرعة / وحدة"},
		{"eOR.DrawingTool.label","آداة رسم"},
		{"eOR.AppmtBooked.label","تم حجز الموعد"},
		{"eOR.DuplicateCheck.label","فحص التكرار"},
		{"eOR.Editor.label","المحرر"},
		{"eOR.EditorPreview.label","معاينة التحرير"},
		{"eOR.Effective.label","فعال"},
		{"eOR.EffectiveWithComplications.label","فعال مع المضاعفات"},
		{"eOR.EqualsTo.label","مساوى لــ"},
		{"eOR.ExamConflicts.label","تعارضات الاختبار"},
		{"eOR.ExceptionIdentifier.label","معرف استثنائى"},
		{"eOR.ExceptionType.label","نوع الاستثناء"},
		{"eOR.ExistingChargeType.label","نوع النفقات الحالية"},
		{"eOR.ExistingOrderable.label","متاحة يمكن طلبها"},
		{"eOR.ExistingProcedure.label","إجراء حالى"},
		{"eOR.ExistingRefusal.label","رفض حالى"},
		{"eOR.ExpiredOrders.label","وامر منتهية الصلاحية"},
		{"eOR.ExternalDetails.label","تفاصيل خارجية"},
		{"eOR.ExternalOrder.label","أمر خارجى"},
		{"eOR.ExternalOrders.label","أوامر خارجية"},
		{"eOR.FieldMnemonic.label","حقل تذكيرى"},
		{"eOR.FieldType.label","نوع الحقل"},
		{"eOR.Formats.label","أنساق"},
		{"eOR.ForwardedBy.label","دفع بواسطة"},
		{"eOR.FreqDurn.label","التكرار / المدة"},
		{"eOR.FrequencyApplicable.label","تكرار قابل لللتطبيق"},
		{"eOR.FrequencyDesc.label","وصف التكرار"},
		{"eOR.FrequencyRequired.label","التكرار المطلوب"},
		{"eOR.FrequencyScope.label","نطاق التكرار"},
		{"eOR.FromLocation.label","من موقع"},
		{"eOR.FromOrderCategory.label","من كتالوج أوامر"},
		{"eOR.FromOrderStatus.label","من حالة الامر"},
		{"eOR.FromOrderType.label","من نوع الامر"},
		{"eOR.FutureOrder.label","امر مستقبلى"},
		{"eOR.FutureOrderRule.label","قاعدة الامر المستقبلي"},
		{"eOR.GenerateLabel.label","اصدار ملصق"},
		{"eOR.GenerationLookAhead.label","اصدار ملصق مستقبلي"},
		{"eOR.GraceTimeforInclusioninActiveOrders.label","فترة السماح لحسم الأوامر المعلقة"},
		{"eOR.GreaterThan.label","أكبر من"},
		{"eOR.GroupID.label","مجموعة رقم"},
		{"eOR.Haematology.label","أمراض الدم"},
		{"eOR.Hint.label","لمحة"},
		{"eOR.HoldDiscontinue.label","وقف / عدم استمرار"},
		{"eOR.HoldResume.label","وقف / استمرار"},
		{"eOR.HotSpot.label","نقطة إتصال"},
		{"eOR.HotspotDesc.label","وصف نقطة الإتصال"},
		{"eOR.HotspotId.label","رقم نقطة الإتصال"},
		{"eOR.HourAfterAdmVist.label","ساعة بعد الحجز/ الدخول"},
		{"eOR.ImageHotspot.label","نقطة إتصال الصور"},
		{"eOR.ImageHotspotLink.label","رابط نقطة إتصال الصور"},
		{"eOR.ImageId.label","محدد الصور"},
		{"eOR.ImageLinkId.label","محدد رابط الصور"},
		{"eOR.IncludeStatReport.label","إدراج تقرير الحالة "},
		{"eOR.Index.label","فهرست"},
		{"eOR.IndexOrderCareSet.label","فهرست أوامر مجموعة العناية"},
		{"eOR.IndexOrderCatalog.label","فهرست أوامر كتالوج العناية"},
		{"eOR.IndexOrderSet.label","فهرست ضبط الأوامر"},
		{"eOR.IndexTickSheet.label","فهرست ورقة وضع العلامات"},
		{"eOR.Ineffective.label","غير فعال"},
		{"eOR.IneffectiveWithComplications.label","غير فعال مع مضاعفات"},
		{"eOR.InitialSerialNumber.label","تدشين المسلسل الرقمى"},
		{"eOR.Injections.label","حقن"},
		{"eOR.Instruction.label","تعليمات"},
		{"eOR.InstructionbyAgeSex.label","تعليمات بالجنس / العمر"},
		{"eOR.InstructionDetails.label","تفاصيل التعليمات"},
		{"eOR.InstructionsMode.label","وضع التعليمات"},
		{"eOR.InterfaceParticulars.label","تفاصيل الواجهة"},
		{"eOR.IntraProceduralComplications.label","المضاعفات داخل الإجراءات"},
		{"eOR.LaboratorySite.label","موقع المعمل"},
		{"eOR.Loc1.label","موقع 1"},
		{"eOR.Loc2.label","موقع 2"},
		{"eOR.LookAheadMin.label","أقل مدى للنظر للأمام"},
		{"eOR.Mainsurgeon.label","الجراح الرئيسى "},
		{"eOR.MatrixColumn.label","عمود المصفوفة"},
		{"eOR.MatrixColumnCode.label","كود عمود المصفوفة"},
		{"eOR.MatrixColumnDesc.label","وصف عمود المصفوفة"},
		{"eOR.MatrixRow.label","صفوف المصفوفة"},
		{"eOR.MatrixRowCode.label","كود صفوف المصفوفة"},
		{"eOR.MatrixRowDesc.label","وصف صفوف المصفوفة"},
		{"eOR.MaxValueDurnType.label","نوع أقصى قيمة للمدة الزمنية"},
		{"eOR.MeasureDrugName.label","إسم أقصى قيمة للمدة الزمنية"},
		{"eOR.Microbiology.label","علم الأحياء الدقيقة"},
		{"eOR.MiscellaneousServiceLocation.label","مواقع خدمات متنوعة"},
		{"eOR.modalwindow.label","نافذة الإتصال"},
		{"eOR.Multi.label","متعدد"},
		{"eOR.MultiFacilityProcessing.label","معالجة متعددة المرافق"},
		{"eOR.MultiSelect.label","مختارات متعددة"},
		{"eOR.MultiPatientOrdersHdr.label","أوامر المرضى المتعددة "},
		{"eOR.MultiPatientOrdersHdrResult.label","نتائج أوامر المرضى المتعددة "},
		{"eOR.MultiPatientOrdersTool.label","أدوات أوامر المرضى المتعددة "},
		{"eOR.Nebuliser.label","بخاخ / مبخر"},
		{"eOR.NewChargeType.label","نوع نفقات جديدة"},
		{"eOR.NewList.label","قائمة جديدة"},
		{"eOR.NewProcedureTabs.label","مدخلات إجراءات جديدة"},
		{"eOR.NewRefusal.label","رفض جديد"},
		{"eOR.NextAccessionNumber.label","رقم الوصول التالى"},
		{"eOR.NoofReschedules.label","عدد إعادات المواعيد"},
		{"eOR.NoofOrdersPlacedforDepartment.label","عدد الأوامر الموضوعة للقسم"},
		{"eOR.NonApplicable.label","غير قابل للتطبيق"},
		{"eOR.NormalHigh.label","ارتفاع طبيعى "},
		{"eOR.NormalLow.label","انخفاض طبيعى"},
		{"eOR.NormalcyIndicator.label","مؤشر سي طبيعي"},
		{"eOR.NurseCollect.label","جمع التمريض"},
		{"eOR.NURSECOLLECTYN.label","تجميع ممرضة"},
		{"eOR.ObtainedByPractitioner.label","تم بواسطة الممارس الطبي"},
		{"eOR.ActionDateTime.label","تاريخ ووقت الحركة"},
		{"eOR.OnHold[Activate].label","متوقف / ( تفعيل )"},
		{"eOR.OperatingTheatre.label","غرفة العمليات"},
		{"eOR.OptionalPreSelected.label","اختيارى / محدد مسبقا"},
		{"eOR.ORParameter.label","اعدادات العمليات"},
		{"eOR.ORParameterforFacility.label","اعدادات ملف بالمستشفى"},
		{"eOR.ORPrintingRules.label","قواعد الطباعة بالعمليات"},
		{"eOR.OrderCatalogtoProcedureLink.label","كتالوج الأوامر لرابط العملية"},
		{"eOR.OrderCatalogs.label","كتالوج الأوامر"},
		{"eOR.OrderCategoryID.label","رقم تعريف كتالوج الأوامر"},
		{"eOR.OrderEntryCalendarButton.label","زر التقويم لتسجيل الأوامر"},
		{"eOR.OrderEntryCareSetSearch.label","إدخال بحث في أوامر مجموعة العناية "},
		{"eOR.OrderEntryCriteriaDetail.label","تفاصيل معايير تسجيل الأوامر"},
		{"eOR.OrderEntryCriteriaHeader.label","مقدمة معايير  تسجيل الأوامر"},
		{"eOR.OrderEntryCriteriaMain.label","معايير  تسجيل الأوامر الأساسية"},
		{"eOR.OrderEntryFormat.label","إدخال بحث في أوامر مجموعة العناية "},
		{"eOR.OrderEntryFormatItem.label","صيغة تسجيل الأوامر"},
		{"eOR.OrderEntryFrequentAccessedPractitionerItems.label","عناصر تسجيل الأوامر يتم إستعمالها بشكل متكرر"},
		{"eOR.OrderEntryImagePanels.label","مجموعات الصور لتسجيل الأوامر"},
		{"eOR.OrderEntryMain.label","تسجيل الأوامر الأساسية"},
		{"eOR.OrderEntryPreview.label","معاينة الأوامر المسجلة"},
		{"eOR.OrderEntryResultMain.label","نتائج الأوامر المسجلة الأساسية"},
		{"eOR.OrderEntryTickSheet.label","ورقة وضع العلامات لتسجيل الأوامر"},
		{"eOR.OrderEntryTickSheetItems.label","معاينة الأوامر المسجلة"},
		{"eOR.OrderForm.label","نموذج الأمر"},
		{"eOR.OrderFormat.label","تنسيق الامر"},
		{"eOR.OrderFormatLine.label","خط تنسيق الامر"},
		{"eOR.OrderForms.label","نماذج الامر"},
		{"eOR.OrderLineFormat.label","تنسيق خط الأمر"},
		{"eOR.OrderLineNo.label","رقم خط الأمر"},
		{"eOR.OrderPlacedBy.label","طلب الأمر بواسطة"},
		{"eOR.OrderPriorityApplicable.label","أولوية الأمر / قابل للتطبيق"},
		{"eOR.OrderReviews.label","مراجعة الأوامر"},
		{"eOR.OrderSet.label","مجموعة أوامر"},
		{"eOR.OrderSetCode.label","كود مجموعة الأوامر"},
		{"eOR.OrderSetComponents.label","محتويات مجموعة الأوامر"},
		{"eOR.OrderSetDesc.label","وصف مجموعة الأوامر"},
		{"eOR.OrderStage.label","مرحلة الأوامر"},
		{"eOR.OrderStatistics.label","احصائيات الأوامر"},
		{"eOR.OrderStatusCode.label","كود حالة الوامر"},
		{"eOR.OrderStatusDesc.label","وصف حالة الأوامر"},
		{"eOR.OrderStatusFrom.label","نموذج حاالة الأوامر"},
		{"eOR.ExternalDtls.label","تفاصيل خارجية"},
		{"eOR.InstructionMode.label","وضع التعليمات"},
		{"eOR.OrderStatusType.label","نوع حالة الامر"},
		{"eOR.OrderTypebyClass.label","نوع الأوامر حسب الدرجة"},
		{"eOR.OrderTypeCategory.label","فئة نوع الأوامر"},
		{"eOR.OrderTypeCope.label","كود نوع الامر "},
		{"eOR.OrderTypeDesc.label","وصف نوع الامر"},
		{"eOR.OrdertypeforOrderableDtl.label","نوع الطلب للتفاصيل القابلة للطلب"},
		{"eOR.OrderTypeFrom.label","نوع الامر من"},
		{"eOR.OrderTypesforOrderableMain.label","نوع الطلب للتفاصيل القابلة للطلب الأساسية"},
		{"eOR.Orderables.label","قابل للطلب"},
		{"eOR.OrderablesbyPerformingLocation.label","الطلبات من خلال الموقع المنفذ"},
		{"eOR.OrderedAt.label","طلب في "},
		{"eOR.OrderingRulebyPatientClass.label","قواعد الطلب تبعآ  لدرجة المريض"},
		{"eOR.OrdersProcessed.label","تم معالجة الأوامر"},
		{"eOR.OrdersTab.label","نافذة الأوامر"},
		{"eOR.OTAppointment.label","موعد"},
		{"eOR.OtherMnemonic.label","ذاكرة أخرى"},
		{"eOR.ParametersforSingleContinuingOrders.label","متغيرات الأمر الفردى المستمر"},
		{"eOR.Partial.label","جزئى"},
		{"eOR.PatInstrn.label","تعليمات المرضى"},
		{"eOR.SplitDosage.label","جرعة مقتسمة"},
		{"eOR.PatientEvent.label","حدث المريض"},
		{"eOR.PatientClassApplicability.label","قابلية تطبيق مستويات المرضى"},
		{"eOR.PatientLoc.label","موقع المريض"},
		{"eOR.PatientOrderbyLocation.label","أوامر المرضى بحسب الموقع"},
		{"eOR.PatientOrderDetail.label","تفاصيل أوامر المريض"},
		{"eOR.PatientOrdersView.label","استعراض أوامر المريض"},
		{"eOR.PatientDiagnosis.label","مريض / تشخيص %"},
		{"eOR.PendingForAuthorization.label","معلق بسبب التصريح"},
		{"eOR.PerformingDepartmentLocationCode.label","كود موقع الإدارة المؤدية للاوامر"},
		{"eOR.PerformingDepartmentLocationType.label","نوع موقع الإدارة المؤدية للاوامر"},
		{"eOR.PerformingLocationCode.label","كود الموقع المؤدى للأوامر"},
		{"eOR.PerformingLocationDescription.label","وصف الموقع المؤدى للأوامر"},
		{"eOR.PerformingLocations.label","المواقع المؤدية للأوامر"},
		{"eOR.PeriodAhead.label","فترة مستقبلية"},
		{"eOR.PeriodBehind.label","فترة منقضية"},
		{"eOR.PeriodRangeFrom.label","في الفترة من "},
		{"eOR.PeriodType.label","نوع الفترة"},
		{"eOR.PlaceOrderFrameSet.label","وضع مجموعة الإطارات للأوامر"},
		{"eOR.Plain.label","بدون إضافات"},
		{"eOR.PreparationDuration.label","مدة التحضير"},
		{"eOR.PreparatoryInstruction.label","تعليمات تحضيرية"},
		{"eOR.Preps.label","تحضيرات"},
		{"eOR.PrepsInstructions.label","تعليمات التحضير"},
		{"eOR.PreselectOrderType.label","نوع الأوامر المختارة مسبقا"},
		{"eOR.Press.label","ضغط"},
		{"eOR.PresslinktoAuthorize.label","اضغط الرابط للتصريح"},
		{"eOR.PrimaryOrderType.label","نوع الامر الرئيسى"},
		{"eOR.PrintatDepartment.label","الطباعة في القسم"},
		{"eOR.PrintatDestination.label","وجهة الطباعة"},
		{"eOR.PrintatOtherLocation.label","الطباعة في موقع آخر"},
		{"eOR.PrintatSource.label","الطباعة بالمصدر"},
		{"eOR.PrintLocation.label","موقع الطباعة"},
		{"eOR.PrintLocationforDischargedPatients.label","موقع الطباعة لخروج المرضى"},
		{"eOR.PrintResults.label","نتائج الطباعة"},
		{"eOR.Privilege.label","امتياز"},
		{"eOR.PrivilegeExceptionDetail.label","بيانات امتياز استثنائى"},
		{"eOR.PrivilegeExceptionHead.label","مقدمة امتياز استثنائى"},
		{"eOR.PrivilegeExceptionMain.label","امتياز استثنائى أساسي"},
		{"eOR.PrivilegeGroup.label","مجموعة امتيازات استثنائىة"},
		{"eOR.ProcedureLink.label","رابط الإجراء"},
		{"eOR.ProductDetails.label","بيانات المنتج"},
		{"eOR.PromptAlert.label","تنبيه عاجل"},
		{"eOR.PromptMessage.label","رسالة عاجلة"},
		{"eOR.QtyDose.label","كمية / جرعة"},
		{"eOR.R.label","R"},
		{"eOR.RadioGroup.label","مجموعة إذاعة"},
		{"eOR.RadiologyAppointments.label","مواعيد أشعة"},
		{"eOR.ReactivateonHoldPeriodAhead.label","إعادة تنشيط فترة مقبلة معلقة"},
		{"eOR.ReasonforRapidOrders.label","سبب الأوامر السريعة"},
		{"eOR.ReasonType.label","نوع السبب"},
		{"eOR.ReceiveResult.label","استلام النتيجة"},
		{"eOR.ReceivedRemarks.label","ملاحظات الاستلام"},
		{"eOR.ReceivingPractitioner.label","الطبيب المستلم"},
		{"eOR.RecordCollection.label","تسجيل المختارات"},
		{"eOR.RecordDispatch.label","تسجيل الإفادة"},
		{"eOR.RecordProcedure.label","تسجيل الاجراء"},
		{"eOR.RecordCancellation.label","تسجيل الإلغاء"},
		{"eOR.ReferralForm.label","نموذج التحويل"},
		{"eOR.ReferralForms.label","نماذج التحويل"},
		{"eOR.ReferralPractitioner.label","الطبيب المحول"},
		{"eOR.ReferralText.label","نص التحويل"},
		{"eOR.RefusalDateTime.label","موعد / وقت الرفض"},
		{"eOR.RefusalEditor.label","تعديل الرفض"},
		{"eOR.RefusalForm.label","نموذج الرفض"},
		{"eOR.RefusalForms.label","نماذج الرفض"},
		{"eOR.RefusalID.label","معرف الرفض"},
		{"eOR.RefusalOrder.label","الأوامر المرفوضة"},
		{"eOR.RefusalText.label","نص الرفض"},
		{"eOR.RefusalType.label","نوع الرفض"},
		{"eOR.RelationId.label","معرف العلاقة"},
		{"eOR.RelationName.label","اسم العلاقة"},
		{"eOR.Remark.label","ملاحظة"},
		{"eOR.RenewPeriodBehind.label","تجديد فترة منقضية"},
		{"eOR.RenewOrders.label","تجديد الأوامر"},
		{"eOR.Replaced.label","إعادة وضع"},
		{"eOR.ReplaceOrderable.label","إعادة وضع القابل للطلب"},
		{"eOR.ReplaceableOrderCatalog.label","كتالوج الأوامر القابلة لإعادة الطلب"},
		{"eOR.ReplaceableOrderCatalogCode.label","كود كتالوج الأوامر القابلة لإعادة الطلب"},
		{"eOR.ReplaceableOrderCatalogDescription.label","وصف كتالوج الأوامر القابلة لإعادة الطلب"},
		{"eOR.ReplaceableOrderable.label","الأوامر القابلة لاعادة الطلب"},
		{"eOR.ReplaceableOrderableCatalog.label","كتالوج الأوامر القابلة لإعادة الطلب"},
		{"eOR.ReportedAt.label","بلغ لدى"},
		{"eOR.Reporting.label","تقرير"},
		{"eOR.ReportingandAuthorizing.label","تقرير وتفويض"},
		{"eOR.ReportingDate.label","تاريخ التقرير"},
		{"eOR.ReportingPractitioner.label","الطبيب المقرر"},
		{"eOR.ReportingTime.label","تاريخ التقرير"},
		{"eOR.ReprintDispatchSlip.label","إعادة طباعة شريط الإفادة"},
		{"eOR.ReqdOpt.label","الخيارات المطلوبة"},
		{"eOR.RequestforAuthorize.label","طلب تفويض"},
		{"eOR.RestrictPerformingLocation.label","تحديد المؤسسة المؤدية"},
		{"eOR.ResultComment.label","تعليق النتيجة"},
		{"eOR.ResultComments.label","تعليقات النتيجة"},
		{"eOR.ResultCompletionStatistics.label","احصائيات استكمال النتائج"},
		{"eOR.ResultEntry.label","ادخال نتيجة"},
		{"eOR.ResultEntryTemplate.label","قالب ادخال النتيجة"},
		{"eOR.ResultReports.label","تقارير النتيجة"},
		{"eOR.ResultStatus.label","حالة النتيجة"},
		{"eOR.Results.label","النتائج"},
		{"eOR.ReviewRemarks.label","مراجعة الملاحظات"},
		{"eOR.ReviewType.label","نوع المراجعة"},
		{"eOR.RoutineOrderStage.label","مرحلة الأوامر الاعتيادية"},
		{"eOR.ScheduleApplicable.label","قابل للجدولة"},
		{"eOR.ScheduleFrequency.label","جدول التكرار"},
		{"eOR.SearchFor.label","بحث عن"},
		{"eOR.SearchForOrderingPractitioner.label","البحث عن طالب الأمر"},
		{"eOR.SearchForPractitioner.label","البحث عن طبيب"},
		{"eOR.SecondaryOrder.label","أمر ثانوى"},
		{"eOR.SecondaryTaskPrep.label","وصفة / مهمة ثانوية"},
		{"eOR.SecurityLevel.label","مستوى الحماية"},
		{"eOR.SelectAllSpecificOrder.label","تحديد الكل / أمر محدد"},
		{"eOR.SelectedOrderables.label","مختارات قابلة للطلب"},
		{"eOR.SemiCritical.label","شبه حرجة"},
		{"eOR.SendOut.label","إرسال"},
		{"eOR.SentPractitioner.label","الطبيب المرسل"},
		{"eOR.SentRemarks.label","ملاحظات مرسلة"},
		{"eOR.SeqNum.label","رقم تسلسلى"},
		{"eOR.ServiceCategory.label","فئة الخدمة"},
		{"eOR.ServiceDesc.label","وصف الخدمة"},
		{"eOR.ServiceTypeCode.label","كود نوع الخدمة"},
		{"eOR.Settings.label","اعدادات"},
		{"eOR.SingleMulti.label","مفرد / متعدد"},
		{"eOR.SoftStopforInpatients.label","توقف مؤقت للمرضى الداخليين"},
		{"eOR.SourceCode.label","كود المصدر"},
		{"eOR.SourceDesc.label","وصف المصدر"},
		{"eOR.SourceFrom.label","مصدر من"},
		{"eOR.SourceLocation.label","موقع المصدر"},
		{"eOR.SpecialApprovalLevel.label","مستوى خاص من الموافقات"},
		{"eOR.SpecificLoc.label","موقع معين"},
		{"eOR.SpecimenLabelGeneration.label","تخليق ملصق العينات"},
		{"eOR.SpecimenNo.label","عينة رقم"},
		{"eOR.SpecimenOrder.label","طلب عينة"},
		{"eOR.TickSheetDesc.label","وصف ورقة وضع العلامات"},
		{"eOR.SplApproval.label","موافقة خاصة"},
		{"eOR.Spl.ApprovalReqd.label","تم عمل موافقة خاصة"},
		{"eOR.Split.label","تقسيم"},
		{"eOR.StandardInstruction.label","تعليمات قياسية"},
		{"eOR.StartFrom.label","بدءا من"},
		{"eOR.StatOrderStage.label","مرحلة الأوامر العاجلة"},
		{"eOR.StatusByCategory.label","الحالة بالفئة"},
		{"eOR.StatusByPriority.label","الحالة بالأولوية"},
		{"eOR.StatusRemark.label","ملاحظة حالة"},
		{"eOR.StatusType.label","نوع الحالة"},
		{"eOR.StopOnAppt.label","التوقف عن المواعيد"},
		{"eOR.Synonyms.label","مرادفات"},
		{"eOR.TabName.label","اسم النافذة"},
		{"eOR.TaskStatus.label","حالة المهمة"},
		{"eOR.TemplateType.label","نوع القالب"},
		{"eOR.TermSetCode.label","رمز مجموعة المصطلحات"},
		{"eOR.TextType.label","نوع النص"},
		{"eOR.Therapeutic.label","علاجية"},
		{"eOR.TickSheet.label","ورقة وضع العلامات"},
		{"eOR.TickSheetID.label","رقم ورقة وضع العلامات"},
		{"eOR.TickSheetSection.label","قسم ورقة وضع العلامات"},
		{"eOR.TickSheetSectionCode.label","كود قسم ورقة وضع العلامات"},
		{"eOR.TimeBasedRule.label","قاعدة البناء على الوقت"},
		{"eOR.TimeFrame.label","إطار زمنى"},
		{"eOR.TimePeriodforOrdersResults.label","الفترة الزمنية للاوامر /  النتائج"},
		{"eOR.Timing.label","توقيت"},
		{"eOR.ToLocation.label","الى موقع"},
		{"eOR.ToOrderCategory.label","الى فئة أوامر"},
		{"eOR.ToOrderStatus.label","إلى حالة الأوامر"},
		{"eOR.ToOrderType.label","إلى نوع أوامر"},
		{"eOR.ToolTip.label","تلميح عن الآداة"},
		{"eOR.TreatmentLocation.label","موقع الخدمة العلاجية"},
		{"eOR.TurnAroundTimeForPriority.label","تحويل الوقت للأولوية"},
		{"eOR.Uncoded.label","غير مكود"},
		{"eOR.Unprocessed.label","غير معالج"},
		{"eOR.UpdateOrders.label","أوامر محدثة"},
		{"eOR.UrgStat.label","طارئ / عاجل"},
		{"eOR.Urgency.label","عاجلة"},
		{"eOR.UrgentOrderStage.label","مرحلة الوامر العاجلة"},
		{"eOR.UserDefinedTabName.label","اسم نافذة تعريف المستخدم"},
		{"eOR.UsersforOrderReview.label","مستخدمين لمراجعة الأوامر"},
		{"eOR.UsersforResultReporting.label","مستخدمين لتبليغ نتائج الأوامر"},
		{"eOR.ViewAfterDispatchSlip.label","عرض بعد الإفادة"},
		{"eOR.ViewAppointmentDetails.label","عرض تفاصيل الموعد"},
		{"eOR.ViewAuditTrail.label","عرض مسار المراجعة"},
		{"eOR.ViewOrderBy.label","ترتيب عرض الأوامر"},
		{"eOR.VisitAdmTime.label","وقت الزيارة / الدخول"},
		{"eOR.WaitTimeforGreen.label","مدة انتظار للأخضر"},
		{"eOR.WaitTimeForPendingOrdersTab.label","فترة الانتظار في نافذة الأوامر المعلقة"},
		{"eOR.WaitTimeforRed.label","مدة انتظار للأحمر"},
		{"eOR.WaitTimeforYellow.label","مدة انتظار للأصفر"},
		{"eOR.WaitingTime.label","فترة الانتظار"},
		{"eOR.WarnOnAppt.label","تحذير على الموعد"},
		{"eOR.Wing.label","جناح"},
		{"eOR.Y.label","Y"},
		{"eOR.ActiveBookings.label","الحجوزات النشطة"},
		{"eOR.PatientHistory.label","[تاريخ المريض]"},
		{"eOR.R.label","[R]"},
		{"eOR.S.label","[S]"},
		{"eOR.Tobegenerated.label","[جاهزة للتخليق]"},
		{"eOR.U.label","[U]"},
		{"eOR.ActiveRenew.label","نشط [تجديد؟]"},
		{"eOR.AppointmentRequired.label","مطلوب موعد"},
		{"eOR.AttendPractitioner.label","طبيب مقيم"},
		{"eOR.AuditTrial.label","مسار المراجعة والتدقيق"},
		{"eOR.AuthorizationRequired.label","مطلوب تفويض"},
		{"eOR.AutoUpdateCollectionDateTime.label","تاريخ  / وقت التجميع المحدث تلقائيا"},
		{"eOR.CancelReason.label","سبب الإلغاء"},
		{"eOR.CatalogComments.label","كتالوج التعليقات"},
		{"eOR.ConsentBy.label","أقر بواسطة"},
		{"eOR.ConsentInformation.label","معلومات الإقرار"},
		{"eOR.CosignReqdlabel.label","مطلوب امضاء ثانوية"},
		{"eOR.CriticalAbnormal.label","غير طبيعى بشكل حرج"},
		{"eOR.DateandTime.label","تاريخ ووقت"},
		{"eOR.DeptInstrn.label","تعليمات القسم"},
		{"eOR.DurnValueType.label","قيمة/نوع المدة الزمنية"},
		{"eOR.ElapsedOrder.label","الأوامر المنقضية"},
		{"eOR.ExpiredRenew.label","منتهى [ تجديد ؟ ]"},
		{"eOR.hasbeenSuspendedInvalid.label","معلق / غير مؤكد"},
		{"eOR.HoldDateTime.label","وقت / تاريخ الوقوف"},
		{"eOR.Hrs.label","ساعات"},
		{"eOR.IntraProceduralComplications&nbsp.label","المضاعفات أثناء العملية"},
		{"eOR.isAlreadySelectedinthePanel.label","تم اختياره بالإجراءباللوحة"},
		{"eOR.Jb.label","Jb"},
		{"eOR.MaxPeriodtoBackDateOrders.label","الفترة القصوى لإرجاع تاريخ الأوامر"},
		{"eOR.MaxPeriodtoBackDateResults.label","الفترة القصوى لإرجاع تاريخ النتائج"},
		{"eOR.MaxPeriodtoFutureDateOrders.label","الفترة القوصى لتقديم تاريخ الأوامر"},
		{"eOR.Meaning.label","معنى"},
		{"eOR.Mins.label","دقائق"},
		{"eOR.MultiFacilityProcessingHeader.label","معالجة المؤسسات المتعددة الرأسية"},
		{"eOR.MultiPatientOrdersHdrDtl.label","تفاصيل رأسية ال,امر المتعددة للمرضى"},
		{"eOR.MultiSession.label","جلسات متعددة"},
		{"eOR.NonOrderable.label","غير قابل للطلب"},
		{"eOR.Occurrance.label","حدث"},
		{"eOR.OnHoldActivate.label","قيد الوقوف [ تنشيط؟]"},
		{"eOR.OptionalDeSelected.label","اختيارى / الغاء التحديد"},
		{"eOR.OrderApproval.label","الموافقة على الأوامر"},
		{"eOR.OrderAuthorization.label","صلاحية الأوامر"},
		{"eOR.OrderCatalogbyTickSheetSection.label","ترتيب كتالوج عن طريق ورقة وضع العلامات"},
		{"eOR.OrderConsent.label","إقرار الأوامر"},
		{"eOR.OrderCosign.label","توقيع ثانوى للأوامر"},
		{"eOR.OrderEntry.label","ادخال الأوامر"},
		{"eOR.OrderEntryDrawingToolItems.label","عناصر أداة رسم تسجيل الأوامر"},
		{"eOR.OrderRegistration.label","تسجيل الأوامر"},
		{"eOR.OrderRequestfor.label","مطلوب أمر لــ"},
		{"eOR.OrderTab.label","نافذة الأوامر"},
		{"eOR.OrderableNonOrderable.label","قابل للطلب / غير قابل للطلب"},
		{"eOR.OrderingBy.label","ترتيب تبعا ل "},
		{"eOR.OutstandingOrders.label","أوامر متميزة"},
		{"eOR.PartiallyResulted.label","نتيجة جزئية"},
		{"eOR.Instrn.label","تعليمات"},
		{"eOR.PatientDetail.label","بيانات المريض"},
		{"eOR.PatientNameOrderables.label","اسم المريض / قابل للطلب"},
		{"eOR.PendingReviews.label","مراجعات معلقة"},
		{"eOR.PreselectOrderCategory.label","كتالوج أوامر مختارة مسبقا"},
		{"eOR.PressLinkto.label","اضغط على الرابط لــــ"},
		{"eOR.ReportNotRequested.label","تقرير غير مطلوب"},
		{"eOR.ReScheduled.label","اعيد جدولته"},
		{"eOR.ResultModified.label","نتيجة معدلة"},
		{"eOR.ResultModifiedA.label","نتيجة معدلة "},
		{"eOR.Resulted.label","له نتيجه"},
		{"eOR.ResumeOrder.label","استكمال الأوامر"},
		{"eOR.ReviewLineStatus.label","مراجعة حالة الخط"},
		{"eOR.ReviewOrderStatus.label","مراجعة حالة الأوامر"},
		{"eOR.Schd.label","جدول"},
		{"eOR.ApptDetails.label","بيانات الموعد"},
		{"eOR.SecondaryOrderExists.label","أوامر ثانوية موجودة"},
		{"eOR.SSelfOrder.label","طلب ذاتى - S"},
		{"eOR.NNotApplicable.label","غير قابل للتطبيق - N"},
		{"eOR.AAllOrders.label","كل الأوامر - A"},
		{"eOR.TermGroupDescription.label","وصف مجموعة المصطلحات"},
		{"eOR.TermGroupID.label","رقم مجموعة المصطلحات"},
		{"eOR.TickSheetDescription.label","وصف ورقة وضع العلامات"},
		{"eOR.TotalAmount.label","اجمالى المبلغ"},
		{"eOR.MMedicalTeam.label","الفريق الطبي - M"},
		{"eOR.referralunits.label","الوحدة المحول اليها"},
		{"eOR.ticksheetoption.label","خيارات ورقة وضع العلامات"},
		{"eOR.sectionoption.label","قسم اختيارات"},
		{"eOR.SectionDesc.label","وصف القسم"},
		{"eOR.explodebyday.label","تنفجر في يوم"},
		{"eOR.chargetypeapplicable.label","نفقة قابلة للتطبيق"},
		{"eOR.resultmatrix.label","مخطوطة النتائج"},
		{"eOR.manuallink.label","رابط يدوى"},
		{"eOR.activebookings.label","حجوزات نشطة"},
		{"eOR.absolute.label","مطلق"},
		{"eOR.minmax.label","أقل.أقصى"},
		{"eOR.ContinuingOrder.label","أوامر مستمرة"},
		{"eOR.ConsentNoteTextID.label","معرف نص ملاحظات الإقرار"},
		{"eOR.AdditionalSearch.label","بحث اضافى"},
		{"eOR.TickSheets.label","ورق تجزئة"},
		{"eOR.OrderSets.label","مجموعات أوامر"},
		{"eOR.ExistingOrders.label","أوامر متواجدة "},
		{"eOR.FrequentOrders.label","أوامر متكررة"},
		{"eOR.DiscreteMeasureID.label","معرف قياس التكتيم"},
		{"eOR.DiscreteMeasureDesc.label","وصف قياس التكتيم"},
		{"eOR.SeqNo.label","الرقم التسلسلى"},
		{"eOR.DurnValue/DurnType.label","قيمة المدة / نوع المدة"},
		{"eOR.Pre-selectOrderType.label","أنواع الأوامر المختارة مسبقاَ"},
		{"eOR.BySource.label","حسب المصدر"},
		{"eOR.CollectionDateTime.label","وقت وتاريخ التجميع"},
		{"eOR.MovementLocation.label","موقع الحركة"},
		{"eOR.ByYear.label","بسنة"},
		{"eOR.CosignRequired.label","مطلوب توقيع مشترك"},
		{"eOR.ActivityTypeDesc.label","وصف نوع النشاط"},
		{"eOR.ResultMatrixType.label","نوع مخطوطة النتائج"},
		{"eOR.PerformingDepartmentLocationDesc.label","وصف موقع القسم المؤدى للخدمة"},
		{"eOR.MatrixDesc.label","وصف المخطوطة"},
		{"eOR.GroupIdentifier.label","مجموعة تعريفات"},
		{"eOR.MMedicalTeam.label","الفريق الطبي - M"},
		{"eOR.ByAgeSex.label","بحسب العمر / الجنس"},
		{"eOR.Msg.label","رسالة"},
		{"eOR.DiagnosisDesc.label","وصف التشخيص"},
		{"eOR.ReasonText.label","نص السبب"},
		{"eOR.ImageDesc.label","وصف الصورة"},
		{"eOR.ImageLink.label","رابط الصورة"},
		{"eOR.Charting.label","تخطيط"},
		{"eOR.DefaultValueInProcess.label","لقيمة الافتراضية: معرّفة من قبل المستخدم في حالة العملية"},
		{"eOR.MaxPeriodtoBackDateOrders.label","الفترة القصوى لارجاع تاريخ الأوامر"},
		{"eOR.ByExceptionSpecificity.label","بحسب الاستثناء / الخصوصية"},
		{"eOR.RenewPeriodBehind.label","تجديد : فترة منقضية"},
		{"eOR.ReactivateonHoldPeriodAhead.label","إعادة التنشيط قيد الانتظار : فترة مقبلة"},
		{"eOR.ContinousFrequencyAction.label","الإجراءالتكرار المستمر"},
		{"eOR.AllowRefills.label","السماح بإعادة الصرف"},
		{"eOR.BeforeOrderRegistration.label","قبل تسجيل الأوامر"},
		{"eOR.BeforeOrderRelease.label","قبل اصدار الأوامر"},
		{"eOR.RefusalNoteText.label","نص ملاحظة الرفض"},
		{"eOR.DepartmentOnly.label","للقسم فقط"},
		{"eOR.CompleteonOrder.label","اكمال عند الطلب"},
		{"eOR.AutoReport.label","تقرير تلقائي"},
		{"eOR.ChartApplicable.label","الرسم البياني متاح"},
		{"eOR.ChartingCharacteristics.label","خصائص التخطيط"},
		{"eOR.ChartResultType.label","نوع نتيجة المخطط"},
		{"eOR.DispenseAuthRequired.label","مطلوب صلاحية للصرف"},
		{"eOR.BehindAction.label","الإجراءسابقة"},
		{"eOR.PrivilegeLevel.label","مستوى الامتياز"},
		{"eOR.RoutineUrgent.label","اعتيادى / عاجل"},
		{"eOR.StatusConsidered.label","الحالة وضعت في الإعتبار"},
		{"eOR.AheadAction.label","الإجراء المستقبلي"},
		{"eOR.DispatchLocation.label","موقع الإفادة"},
		{"eOR.PatientEvent.label","المريض والحدث"},
		{"eOR.Coding.label","تكويد"},
		{"eOR.Coded.label","كود"},
		{"eOR.ByTimeframeCategory.label","بحسب الاظار الزمنى / الفئة"},
		{"eOR.ByCategoryTimeframe.label","بحسب الفئة / الاطار الزمنى"},
		{"eOR.Matrix.label","مخطوطة"},
		{"eOR.FrequentOrdersPlacedby.label","تكرار الأوامر وضعت بواسطة"},
		{"eOR.FrequentOrdersPlacedfor.label","تكرار الأوامر وضعت لـــ"},
		{"eOR.Occurance.label","حدث"},
		{"eOR.Front.label","امامى"},
		{"eOR.Dietary.label","غذائي"},
		{"eOR.NursingCare.label","رعاية تمريضية"},
		{"eOR.RadiologyDept.label","قسم الاشعة"},
		{"eOR.RecordConsent.label","سجل الإقرار"},
		{"eOR.CompleteReview.label","عرض الاكتمال"},
		{"eOR.ResultedP.label","له نتيجة"},
		{"eOR.AbnormalP.label","غير طبيعى"},
		{"eOR.CriticalLow.label","منخفض بشكل حرج"},
		{"eOR.CriticalHigh.label","مرتفع بشكل حرج"},
		{"eOR.LabResults.label","نتائج المعمل"},
		{"eOR.DrugDetails.label","تفاصيل الدواء"},
		{"eOR.ReplacewithOrderable.label","إستبدل بـأمر متاح"},
		{"eOR.Fields.label","مجالات"},
		{"eOR.CopyPreviousOrders.label","نسخ الأوامر السابقة"},
		{"eOR.OtherTeam.label","فريق آخر"},
		{"eOR.TeamsofAttendingPractitioner.label","فريق الأطاباء المقيمين"},
		{"eOR.SequenceNumber.label","رقم تسلسلى"},
		{"eOR.MatrixRowDescription.label","وصف صف المخطوطة"},
		{"eOR.MatrixColumnDescription.label","وصف عمود المخطوطة"},
		{"eOR.ReferralDateTime.label","وقت / تاريخ التحويل"},
		{"eOR.Responsibilty.label","مسؤلية"},
		{"eOR.PatientSearch.label","بحث المرضى"},
		{"eOR.FindTeam.label","إيجاد فريق"},
		{"eOR.ConsentNoteType.label","نوع ملاحظة الإقرار"},
		{"eOR.FrequenctScope.label","نطاق التكرار"},
		{"eOR.OrderTypeCategory.label","فئة نوع الامر"},
		{"eOR.FromOrderDate.label","من تاريخ الأمر"},
		{"eOR.ToOrderDate.label","الى تاريخ الامر"},
		{"eOR.Billable.label","قابل للفوترة"},
		{"eOR.AppointmentReferenceNumber.label","الرقم المرجعى للميعاد"},
		{"eOR.AppointmentLocation.label","موقع الميعاد"},
		{"eOR.Attending.label","حضور"},
		{"eOR.Renew.label","تجديد"},
		{"eOR.Resume.label","تكملة"},
		{"eOR.ActivateOrders.label","تنشيط الأوامر"},
		{"eOR.CareSet.label","مجموعة الرعاية"},
		{"eOR.NoofColumns.label","عدد الاعمدة "},
		{"eOR.TableNo.label","جدول رقم"},
		{"eOR.RowNotobedeleted.label","صف رقم .جاهز للحذف"},
		{"eOR.RowNo.label","صف رقم"},
		{"eOR.ColumnNo.label","عمود رقم"},
		{"eOR.OrderCompletion.label","استكمال الأوامر"},
		{"eOR.RedirectOrder.label","إعادة توجيه الأوامر"},
		{"eOR.Refusal.label","رفض"},
		{"eOR.Decimal.label","عدد عشرى"},
		{"eOR.Integer.label","عدد صحيح"},
		{"eOR.EnterLocation.label","دخول موقع"},
		{"eOR.Dtls.label","تفاصيل"},
		{"eOR.UnOfficialReport.label","تقرير غير رسمي"},
		{"eOR.EventDateTime.label","وقت وتاريخ الحدث"},
		{"eOR.SexAge.label","النوع / العمر:"},
		{"eOR.OrderEntryExternalOrder.label","ادخال أوامر ( أوامر خارجية )"},
		{"eOR.OrderEntryMultiPatientOrders.label","ادخال أوامر ( أوامر متعددة للمريض )"},
		{"eOR.Completion.label","اكتمال"},
		{"eOR.Reqd.label","مطلوب"},
		{"eOR.AddlInfo(Mandatory).label","معلومات إضافية [ الزامية ]"},
		{"eOR.AddlInfo(Optional).label","معلومات إضافية [ اختيارية ]"},
		{"eOR.OrderCatalogByOrderType.label","كتالوج الأوامر بحسب نوع الأوامر"},
		{"eOR.NoCheck.label","لم يتم الاختيار"},
		{"eOR.ActiveGeneric.label","العلمي / الفعال"},
		{"eOR.ActiveOrderableStatus.label","حالة الأوامر القابلة للطلب"},
		{"eOR.AnyOrderableStatus.label","أي حالة امر قابل للطلب"},
		{"eOR.ByOrderable.label","بحسب الأوامر القابلة للطلب"},
		{"eOR.ByActivityType.label","بحسب نوع الأنشطة"},
		{"eOR.DepartmentalService.label","خدمة خاصة بقسم"},
		{"eOR.FieldMnemonicDesc.label","وصف المجال التذكيرى"},
		{"eOR.Expires/ExpiredOrderforRenewing.label","تجديد الأوامر المنتهية / ستنتهى"},
		{"eOR.PendingForSpecimenCollection.label","معلقة لجمع العينات"},
		{"eOR.CompletedOrders.label","الأوامر المكتملة"},
		{"eOR.ID:.label","معرف / محدد:"},
		{"eOR.EncounterDtls:.label","تفاصيل الزيارة:"},
		{"eOR.ReasonForReplace.label","سبب أعادة الوضع"},
		{"eOR.View/Edit.label","عرض / تعديل"},
		{"eOR.BillingChargesDetails.label","تفاصيل فاتورة النفقات"},
		{"eOR.TotalCharge.label","اجمالى النفقات"},
		{"eOR.ApprovalReqd.label","مطلوب الموافقة"},
		{"eOR.ConsentFormList.label","قائمة نماذج الإقرار"},
		{"eOR.MultipleConsent.label","اقرارات متعددة"},
		{"eOR.NumberOfConsentRequired.label","عدد الاقرارات المطلوبة"},
		{"eOR.ConsentForCatalog.label","موافقة على كتالوج"},
		{"eOR.PractitionerForConsent.label","أطباء للاقرارات"},
		{"eOR.PractitionerList.label","قائمة الأطباء"},
		{"eOR.Limitto.label","محدد على"},
		{"eOR.PendingDefine.label","معلق للتعريف"},
		{"eOR.ConsentDetailfortheCatalog.label","تفاصيل الإقرار للكتالوج"},
		{"eOR.BOReq.label","طلب BO"},
		{"eOR.BRReq.label","طلب BR"},
		{"eOR.andBRReq.label","و طلب BR"},
		{"eOR.DefaultForm.label","النموذج الافتراضى"},
		{"eOR.OrderSeq.label","تسلسل الأوامر"},
		{"eOR.CatalogListfortheOrderCategory.label","قائمة الكتالوج الخاصة بكتالوج الأوامر"},
		{"eOR.andOrderType.label","ونوع الأمر"},
		{"eOR.DefinitionExists.label","التعريف موجود"},
		{"eOR.PractForConsentHeader.label","الممارس الطبي يقوم بالحصول على مقدمة إقرار المريض"},
		{"eOR.PractForConsent.label","الحصول على إقرار المريض"},
		{"eOR.RequiredCount.label","العدد المطلوب"},
		{"eOR.ConsentFormforBeforeOrder.label","نموذج الإقرار لما قبل الطلب"},
		{"eOR.ConsentRequiredfor.label","مطلوب الإقرار لــ"},
		{"eOR.AssociateConsent.label","إقرار تعاون"},
		{"eOR.SNO.label","الرقم التسلسلى"},
		{"eOR.Redefine.label","إعادة تعريف"},
		{"eOR.ViewConsents.label","عرض الاقرارات"},
		{"eOR.LinkConsent.label","ربط الاقرارات"},
		{"eOR.Consents.label","اقرارات"},
		{"eOR.Existing.label","متواجد"},
		{"eOR.BeforeOrder.label","قبل الطلب"},
		{"eOR.Release.label","اصدار :"},
		{"eOR.RecordedConsent.label","إقرار مسجل"},
		{"eOR.GenExternalApplicationAccessionNum.label","انشاء رقم وصول لتطبيق خارجى"},
		{"eOR.AllowMultiPatientResulting.label","السماح بنتائج متعددة للمريض"},
		{"eOR.ConsentFormforBeforeOrderRegistration.label","نموذج الإقرار لما قبل تسجيل الطلب"},
		{"eOR.ConsentFormforBeforeOrderRelease.label","نموذج الإقرار لما قبل اصدار الطلب"},
		{"eOR.ItemNarration.label","سرد العناصر"},
		{"eOR.IVPrep.label","وصفة وريدية"},
		{"eOR.NoOfRefills.label","عدد إعادة الصرف"},
		{"eOR.ClickLinkToPrintConsentDetails.label","اضغط على الرابط لطباعة تفاصيل الإقرار"},
		{"eOR.ClickonCatalogtoViewIndividualDetails.label","اضغط عىل الكتالوج لاستعراض التفاصيل الفردية"},
		{"eOR.SpecimenForOrderable.label","عينة للأوامر القابلة للطلب"},
		{"eOR.AssignPrivilegeGroup.label","تعيين مجموعة امتيازات"},
		{"eOR.PrivilegeGroupID.label","محدد مجموعة الامتيازات "},
		{"eOR.PrivilegeGroupDescription.label","وصف مجموعة الامتيازات"},
		{"eOR.Viewing.label","استعراض"},
		{"eOR.Authorizing.label","تفويض"},
		{"eOR.Spl-Approving.label","موافقة التخصص"},
		{"eOR.Co-Signing.label","توقيعات ثانوية"},
		{"eOR.Resulting.label","استنتاج"},
		{"eOR.Recording.label","تسجيل"},
		{"eOR.CopyFrom.label","نسخ من"},
		{"eOR.SelectOrderCategory.label","اختر فئة الأوامر"},
		{"eOR.SelectOrderType.label","اختر نوع الأوامر"},
		{"eOR.SelectOrderCatalog.label","اختر كتالوج الأوامر"},
		{"eOR.SelfOrder.label","أمر ذاتى"},
		{"eOR.ScheduleTime.label","توقيت مجدول"},
		{"eOR.ClickLinkToViewConsentDetails.label","اضغط على الرابط لاستعراض تفاصيل الإقرار"},
		{"eOR.BillNow.label","فوتر الآن"},
		{"eOR.RecordedDate.label","تاريخ التسجيلات"},
		{"eOR.AddedfacilityID.label","مؤسسة مضافة"},
		{"eOR.LastRecoredDate.label","تاريخ آخر تعديل"},
		{"eOR.ModifiedFacilityID.label","المؤسسة المعدلة"},
		{"eOR.ConsentName.label","اسم الإقرار"},
		{"eOR.DefaultCheck.label","فحص افتراضى"},
		{"eOR.BillLater.label","فوتر لاحقا"},
		{"eOR.OrderingRuleByPractitionerType.label","قاعدة الأوامر بحسب نوع الطبيب"},
		{"eOR.ForceAuthorization.label","إجبار تفويض"},
		{"eOR.ForceCo-Sign.label","إجبار توقيع ثانوى"},
		{"eOR.OrderDeptOnlyCatalogs.label","كتالوج أوامر القسم فقط"},
		{"eOR.PendingAppointment.label","موعد معلق"},
		{"eOR.ConsentsneedtobeattachforthisCatalog.label","لا يوجد إقرار مربوط لهذا الكتالوج"},
		{"eOR.Linktocurrentencounter.label","ربط بالزيارة الحالية"},
		{"eOR.ChildOrder.label","أوامر أطفال"},
		{"eOR.SentOut.label","أرسل"},
		{"eOR.ReprintSpecimen.label","إعادة طباعة العينات"},
		{"eOR.SpecimenDispatch.label","ارسال العينات"},
		{"eOR.IfmoduleisinstalledthenCloseInProcessOrdersafterruleisnotused.label","اذا تم تنصيب وتعريف الوحدة النمطية فلن يتم استغدام قاعدة 'معالجة الأوامر'"},
		{"eOR.A.label"," A"},
		{"eOR.Abnormal.label","غير طبيعى"},
		{"eOR.AcceptOption.label","خيار القبول"},
		{"eOR.ActiveBookings.label","الحجوزات النشطة"},
		{"eOR.ActiveProblems.label","المشاكل النشطة"},
		{"eOR.Allorders.label","كل الأوامر"},
		{"eOR.AllOrders.label","كل الأوامر"},
		{"eOR.Amend.label","تعديل"},
		{"eOR.Applicableto.label","ينطبق على"},
		{"eOR.Appointment.label","موعد"},
		{"eOR.AppointmentDate.label","تاريخ الموعد"},
		{"eOR.AppointmentDate.label","تاريخ الموعد:"},
		{"eOR.AppointmentDetails.label","تفاصيل الموعد"},
		{"eOR.Approve.label","موافقة"},
		{"eOR.approved.label","تم الموافقة"},
		{"eOR.Ason.label","ملف Ason"},
		{"eOR.Associate.label","تعاون"},
		{"eOR.AttendingPractitioner.label","طبيب مقيم"},
		{"eOR.AuditTrail.label","مسار المراجعة والتدقيق"},
		{"eOR.Authorization.label","تفويض"},
		{"eOR.AuthorizationLevel.label","مستوى التفويض"},
		{"eOR.AuthorizationReqd.label","طلب تفويض"},
		{"eOR.Back.label","عودة"},
		{"eOR.Between.label","بين"},
		{"eOR.BillDetails.label","تفاصيل الفاتورة"},
		{"eOR.Billing.label","فوترة"},
		{"eOR.BodyPart.label","جزء من الجسد"},
		{"eOR.BookAppointment.label","احجز موعد"},
		{"eOR.Catalog.label","كتالوج"},
		{"eOR.Characteristics.label","سمات"},
		{"eOR.Charge.label","نفقة"},
		{"eOR.ClinicalComments.label","تعليقات سريرية"},
		{"eOR.Code.label","كود"},
		{"eOR.CodeLevel.label","مستوى الكود"},
		{"eOR.CollectedBy.label","جمعت بواسطة"},
		{"eOR.Confidential.label","سرى"},
		{"eOR.Consent.label","إقرار"},
		{"eOR.Consent.label","إقرار"},
		{"eOR.ConsentDetails.label","تفاصيل الإقرار"},
		{"eOR.ConsentDetails.label","تفاصيل الإقرار"},
		{"eOR.ConsentDetails.label","تفاصيل الإقرار"},
		{"eOR.ConsentForm.label","نموذج الإقرار"},
		{"eOR.ConsentNote.label","ملاحظات الإقرار"},
		{"eOR.ConsentNote.label","ملاحظات الإقرار"},
		{"eOR.ConsentRequired.label","إقرار مطلوب"},
		{"eOR.ConsentStage.label","مرحلة الإقرار"},
		{"eOR.ConsentStage.label","مرحلة الإقرار"},
		{"eOR.Consenttype.label","نوع الإقرار"},
		{"eOR.Continuous.label","مستمر"},
		{"eOR.Copy.label","نسخ"},
		{"eOR.Cosign.label","توقيع مشترك"},
		{"eOR.CosignReqd.label","مطلوب توقيع إضافي/ثانوي"},
		{"eOR.Cosigned.label","تم التوقيع الإضافي"},
		{"eOR.CriticallyAbnormal.label","غير اعتيادى بشكل حرج"},
		{"eOR.DateofBirth.label","تاريخ الميلاد"},
		{"eOR.DateofReporting.label","تاريخ التقرير"},
		{"eOR.DateTime.label","تاريخ / وقت"},
		{"eOR.Define.label","حدد"},
		{"eOR.DefinitionType.label","نوع التعريف"},
		{"eOR.Demographics.label","التركيبة السكانية"},
		{"eOR.Departmental.label","إداري"},
		{"eOR.Dependency.label","استقلالية"},
		{"eOR.Description.label","وصف"},
		{"eOR.Detail.label","تفاصيل"},
		{"eOR.Discontinue.label","عدم استكمال"},
		{"eOR.DiscontinueReason.label","سبب عدم الاستكمال"},
		{"eOR.DispatchedBy.label","مرسل بواسطة"},
		{"eOR.DosageBy.label","جرعة بواسطة"},
		{"eOR.dose.label","جرعة"},
		{"eOR.Dressing.label","غيار"},
		{"eOR.DrugProfile.label","الملف الدوائى"},
		{"eOR.Due.label","مستحق"},
		{"eOR.DurationType.label","نوع المدة"},
		{"eOR.Encounter.label","زيارة"},
		{"eOR.EventStatus.label","حالة الحدث"},
		{"eOR.EventStatus.label","الحدث و الحالة"},
		{"eOR.ExecuteQuery.label","تنفيذ الاستعلام"},
		{"eOR.ExplanatoryText.label","نص توضيحى"},
		{"eOR.ExternalPractitioner.label","طبيب غير مقيم"},
		{"eOR.FacilityID.label","معرف المؤسسة"},
		{"eOR.FacilityName.label","اسم المؤسسة"},
		{"eOR.Fixed.label","ثابت"},
		{"eOR.Form.label","نموذج"},
		{"eOR.FormatItem.label","عنصر تنسيق"},
		{"eOR.FormatItem.label","عنصر تنسيق"},
		{"eOR.Forward.label","إرسال لآخر"},
		{"eOR.ForwardtoPractitioner.label","ارسل إلى الممارس"},
		{"eOR.Frequency.label","تكرار"},
		{"eOR.FrequencyCode.label","كود التكرار"},
		{"eOR.Function.label","وظيفة"},
		{"eOR.Green.label","أخضر"},
		{"eOR.GroupName.label","اسم المجموعة"},
		{"eOR.Header.label","مقدمة"},
		{"eOR.Hold.label","وقوف"},
		{"eOR.HoldReason.label","سبب الوقوف"},
		{"eOR.HoldReason.label","سبب الوقوف"},
		{"eOR.Holiday.label","إجازة"},
		{"eOR.HourAfterDischarge.label","ساعدة بعد الخروج"},
		{"eOR.Image.label","صورة"},
		{"eOR.InProcess.label","معالجة"},
		{"eOR.Included.label","مضاف"},
		{"eOR.IndexType.label","نوع الفهرس"},
		{"eOR.Individual.label","فردى"},
		{"eOR.Intravenous.label","وريد"},
		{"eOR.LabelText.label","نص الملصق"},
		{"eOR.Laboratory.label","معمل"},
		{"eOR.LastRecordedBy.label","آخر تعديل تم بواسطة"},
		{"eOR.LessThan.label","أقل من"},
		{"eOR.Level.label","مستوى"},
		{"eOR.Line.label","خط"},
		{"eOR.LocationDesc.label","وصف الموقع"},
		{"eOR.LocationFrom.label","من موقع"},
		{"eOR.LongDesc.label","وصف طويل"},
		{"eOR.Mandatory.label","إجبارى"},
		{"eOR.Max.label","أكبر"},
		{"eOR.MaxAge.label","أكبر عمر"},
		{"eOR.MedicalTeam.label","الفريق الطبي"},
		{"eOR.MedicationAdministration.label","تناول الأدوية"},
		{"eOR.Min.label","أقل"},
		{"eOR.MinAge.label","أقل عمر"},
		{"eOR.Miscellaneous.label","متنوع"},
		{"eOR.Nature.label","طبيعة"},
		{"eOR.NetAmount.label","صافى القيمة"},
		{"eOR.NewOrders.label","أوامر جديدة"},
		{"eOR.None.label","لا شيء"},
		{"eOR.NotApplicable.label","غير متاح"},
		{"eOR.note.label","ملاحظة"},
		{"eOR.NoteType.label","نوع الملاحظة"},
		{"eOR.Old.label","قديم"},
		{"eOR.Operator.label","مشغل"},
		{"eOR.Option.label","خيار"},
		{"eOR.Order.label","أمر"},
		{"eOR.Order.label","أمر"},
		{"eOR.OrderCatalog.label","كتالوج الأوامر"},
		{"eOR.OrdercatalogCode.label","كود كتالوج الطلب"},
		{"eOR.OrderCatalogDesc.label","وصف كتالوج الطلب"},
		{"eOR.OrderCatalogDescription.label","وصف كتالوج الطلب"},
		{"eOR.OrderDate.label","تاريخ الطلب "},
		{"eOR.OrderDateFrom.label","تاريخ الطلب من"},
		{"eOR.OrderDatetime.label","وقت تاريخ الطلب"},
		{"eOR.OrderDetails.label","تفاصيل الطلب"},
		{"eOR.OrderEntryTabs.label","ترتيب الدخول"},
		{"eOR.OrderId.label","رقم تعريف الطلب"},
		{"eOR.OrderLocation.label","موقع الطلب"},
		{"eOR.OrderNo.label","رقم الطلب"},
		{"eOR.OrderTypeCode.label","نوع رمز الطلب"},
		{"eOR.Orderable.label","قابل لطلب"},
		{"eOR.Orderable.label","قابل لطلب"},
		{"eOR.OrderedBy.label","تم الطلب بواسطه"},
		{"eOR.Ordering.label","ترتيب"},
		{"eOR.OrderingFacility.label","المنشأه الطالبه"},
		{"eOR.OrderingFacilityId.label","رقم تعريف المنشأه الطالبه"},
		{"eOR.OrderingFacilityName.label","اسم المنشأه الطالبه"},
		{"eOR.OrderingLocation.label","موقع الطلب"},
		{"eOR.OrderingPractitioner.label","ممارس الطلب"},
		{"eOR.OrganizationType.label","نوع المنظمة"},
		{"eOR.OutpatientAppointments.label","مواعيد العيادات الخارجية"},
		{"eOR.Outstanding.label","المعلقه"},
		{"eOR.Panel.label","مجموعه من الاصناف"},
		{"eOR.PartiallyCompleted.label","أنجزت جزئيا"},
		{"eOR.Patient.label","مريض"},
		{"eOR.PatientCare.label","رعاية المرضى"},
		{"eOR.PatientClassDescription.label","وصف فئة المريض"},
		{"eOR.PatientInstruction.label","تعليمات المريض"},
		{"eOR.PatientInstructions.label","تعليمات المريض"},
		{"eOR.PatientPaid.label","دفع المريض"},
		{"eOR.PatientPayable.label","يدفع المريض"},
		{"eOR.patientspecific.label","خاص بالمريض"},
		{"eOR.Pending.label","قيد الانتظار"},
		{"eOR.PendingforReviews.label","في انتظار التعليقات"},
		{"eOR.PerformedOn.label","تجرى على"},
		{"eOR.PerformingFacility.label","منشأه الاداء"},
		{"eOR.PerformingFacilityID.label","رقم تعريف منشأه الاداء"},
		{"eOR.PerformingFacilityName.label","اسم منشأه الاداء"},
		{"eOR.PerformingLocation.label","موقع الاداء"},
		{"eOR.PlaceOrder.label","تقديم الطلب"},
		{"eOR.Presentation.label","عرض"},
		{"eOR.Preview.label","معاينة"},
		{"eOR.PrintAt.label","طباعة في"},
		{"eOR.Printing.label","طباعه "},
		{"eOR.PriorityApplicable.label","الأولوية المطبقة"},
		{"eOR.Procedure.label","إجراء"},
		{"eOR.Proceed.label","نفذ"},
		{"eOR.Profile.label","الملف الشخصي"},
		{"eOR.Prompt.label","فوري"},
		{"eOR.Qty.label","الكميه"},
		{"eOR.QtyUnit.label","وحده الكميه"},
		{"eOR.QueryCriteria.label","معايير الاستعلام"},
		{"eOR.Radiology.label","الاشعه"},
		{"eOR.ReasonCode.label","رمز السبب"},
		{"eOR.ReasonDescription.label","وصف الطلب"},
		{"eOR.RecordedBy.label","تم التسجيل بواسطه"},
		{"eOR.Red.label","احمر"},
		{"eOR.ReferralFacility.label","منشأه الإحاله"},
		{"eOR.ReferralFacility.label","منشأه الإحاله"},
		{"eOR.ReferredDate.label","تاريخ الإحاله"},
		{"eOR.ReferredPractitioner.label","ممارس الإحاله"},
		{"eOR.Register.label","تسجيل"},
		{"eOR.Registered.label","مسجل"},
		{"eOR.Registration.label","التسجيل"},
		{"eOR.Reject.label","رفض"},
		{"eOR.Replace.label","استبدال"},
		{"eOR.ReportCriteria.label","معايير التقرير"},
		{"eOR.ReportedBy.label","تم عمل تقرير بواسطة"},
		{"eOR.Reprint.label","إعاده الطبع"},
		{"eOR.RescheduledReason.label","سبب مُعاد جدولته"},
		{"eOR.RestrictbyService.label","تقييد حسب الخدمة"},
		{"eOR.ResultReporting.label","نتيجه التقارير"},
		{"eOR.ResultTemplate.label","نموذج النتيجة"},
		{"eOR.ResultType.label","نوع النتيجة"},
		{"eOR.Review.label","مراجعة"},
		{"eOR.Route.label","مسار"},
		{"eOR.ScrubNurse.label","ممرضة تدليك"},
		{"eOR.Selected.label","المحدد"},
		{"eOR.Selection.label","اختيار"},
		{"eOR.SelfRelated.label","ذات الصلة"},
		{"eOR.Separate.label","منفصل"},
		{"eOR.SequenceNo.label","رقم التسلسل"},
		{"eOR.ServiceCode.label","رمز الخدمة"},
		{"eOR.ServiceDescription.label","وصف الخدمة"},
		{"eOR.Sex.label","الجنس"},
		{"eOR.ShortDesc.label","وصف قصير"},
		{"eOR.SlidingScale.label","مقياس متدرج"},
		{"eOR.SoftStop.label","توقف ناعم"},
		{"eOR.SourceType.label","نوع المصدر"},
		{"eOR.SpecialApproval.label","الموافقة الخاصة"},
		{"eOR.SpecialApprovalReqd.label","مطلوب موافقة خاصة"},
		{"eOR.SpecialApprovalRequired.label","مطلوب موافقة خاصة"},
		{"eOR.SpecimenCollection.label","جمع العينات"},
		{"eOR.SpecimenDetails.label","تفاصيل العينة"},
		{"eOR.SpecimenType.label","نوع العينه"},
		{"eOR.Stage.label","مرحله"},
		{"eOR.Standard.label","اساسي"},
		{"eOR.Stat.label","ثابت"},
		{"eOR.Stat.label","ثابت"},
		{"eOR.Stop.label","قف"},
		{"eOR.Strength.label","قوة"},
		{"eOR.Summary.label","ملخص"},
		{"eOR.Suspended.label","معلق"},
		{"eOR.SystemDefined.label","معرّف من قبل النظام"},
		{"eOR.Taper.label","تفتق"},
		{"eOR.Task.label","مهمة"},
		{"eOR.TDMDetails.label","تفاصيل TDM"},
		{"eOR.TemplateID.label","رقم تعريف النموذج"},
		{"eOR.TemplateName.label","اسم النموذج"},
		{"eOR.TermCode.label","كود المصطلح"},
		{"eOR.TermCodeDescription.label","وصف رمز المصطلح"},
		{"eOR.TermSet.label","مجموعة المصطلح"},
		{"eOR.TermSetDescription.label","وصف مجموعة المصطلحات"},
		{"eOR.TermSetID.label","رقم تعريف مجموعه المصطلحات"},
		{"eOR.Text.label","نص"},
		{"eOR.TextBlock.label","كتلة النص"},
		{"eOR.Title.label","عنوان"},
		{"eOR.TitleText.label","نص العنوان"},
		{"eOR.Top.label","أعلى"},
		{"eOR.Total.label","مجموع"},
		{"eOR.TransfusionsHistory.label","تاريخ نقل الدم"},
		{"eOR.Treatment.label","علاج"},
		{"eOR.Ultrasound.label","الموجات فوق الصوتية"},
		{"eOR.Unit.label","وحدة"},
		{"eOR.UOM.label","وحده القياس"},
		{"eOR.Up.label","فوق"},
		{"eOR.UserDefined.label","تعريف المستخدم"},
		{"eOR.Values.label","القيم"},
		{"eOR.Variable.label","متغير"},
		{"eOR.Variance.label","اختلافات"},
		{"eOR.ViewDetails.label","عرض التفاصيل"},
		{"eOR.VisitAdmDate.label","تاريخ قبول الزيارة"},
		{"eOR.Warn.label","حذر"},
		{"eOR.Warning.label","تحذير"},
		{"eOR.Years.label","سنوات"},
		{"eOR.Yellow.label","اصفر"},
		{"eOR.YesNo.label","نعم/لا"},
		{"eOR.RoundOffStartTime.label","وقت بدء الجولة"},
		{"eOR.SpecifictoCatalog.label","خاص بالكتالوج"},
		{"eOR.ConsentList.label","قائمة الموافقة"},
		{"eOR.RequestComment.label","طلب تعليق"},
		{"eOR.ClinicalCommentMandatory.label","التعليق السريري إلزامي"},
		{"eOR.SpecialityForOrderable.label","التخصص للطلب"},
		{"eOR.PlaceOrdersForOtherPractitioners.label","تقديم الطلبات لممارسين آخرين"},
		{"eOR.AllowedType.label","النوع المسموح به"},
		{"eOR.InvestigationCheckList.label","قائمة تدقيق من التحقيق"},
		{"eOR.ServiceDateFrom.label","تاريخ الخدمة من"},
		{"eOR.IncludeCancelledTests.label","تضمين الاختبارات الملغاة"},
		{"eOR.IncludedOnlyBilledTests.label","شملت فقط فواتير الاختبارات"},
		{"eOR.Discard.label","تجاهل"},
		{"eOR.IncludeBilledTests.label","تشمل الاختبارات التي تمت فوترتها"},
		{"eOR.Rectime.label","تسجيل الوقت"},
		{"eOR.Disdate.label","تاريخ الخروج"},
		{"eOR.Distime.label","وقت الخروج"},
		{"eOR.OrderSetBillingDetails.label","طلب تعيين تفاصيل الفواتير"},
		{"eOR.NonSpecific.label","غير محدد"},
		{"eOR.DuplicateOrders.label","طلبات مكررة"},
		{"eOR.EmailPreview.label","معاينة البريد الإلكتروني"},
		{"eOR.AddlSearch.label","بحث إضافي"},
		{"eOR.TimeRoundedto.label","تقريب الوقت إلى:"},
		{"eOR.QuarterHour.label","ربع ساعة"},
		{"eOR.OrderDetails.label","تفاصيل الطلب"},
		{"eOR.CloseBilledOrder.label","إغلاق الطلب المفوتر"},
		{"eOR.IgnoreOrdersPlacedWithin.label","تجاهل الطلبات المقدمه خلال"},
		{"eOR.ReverseCharge.label","التحمل العكسي"},
		{"eOR.AutoCloseUseBillingRule.label","إغلاق تلقائي استخدام قاعدة الفواتير"},
		{"eOR.OrderStartDate.label","تاريخ بدء الطلب"},
		{"eOR.DefaultResultValues.label","قيم النتائج الافتراضية"},
		{"eOR.ValueDifferedFromDefaultResult.label","اختلفت القيمة عن قيمة النتيجة الافتراضية"},
		{"eOR.StartDateTime.label","وقت تاريخ البدء"},
		{"eOR.OtherResultFormats.label","تنسيقات النتائج الأخرى"},
		{"eOR.ResultFormat.label","تنسيق النتيجة"},
		{"eOR.OrderStartPeriod.label","فترة بدء الطلب"},
		{"eOR.ExternalPatientOrder.label","طلب المريض الخارجي"},
		{"eOR.AllowMultiPatientResulting.label","السماح بالنتائج المتعددة للمرضى"},
		{"eOR.FillDetails.label","تفاصيل التعبئة"},
		{"eOR.ElapsedOrders.label","الطلبات المنقضية"},
		{"eOR.ResultTypeDisplayControl.label","نتيجة نوع التحكم في العرض"},
		{"eOR.BackToMultiPatientOrders.label","العودة إلى أوامر تعدد المرضى"},
		{"eOR.AppointmentFromPerformingFacility.label","موعد الحجز ممكن فقط من منشأة الأداء"},
		{"eOR.RescheduleFromPerformingFacility.label","إعادة الجدولة ممكنة فقط من خلال منشأة الأداء"},
		{"eOR.LinkFutureOrderToCurrentEncounter.label","ربط الطلب المستقبلي باللقاء الحالي أثناء تسجيل الزيارة / القبول المعمول به"},
		{"eOR.ControlByPrivilegeGroupSetup.label","التحكم عن طريق إعداد مجموعة الامتياز"},
		{"eOR.OrderAuthorisation.label","إذن الطلب"},
		{"eOR.DelinkCurrentSetup.label","فك ارتباط الإعداد الحالي"},
		{"eOR.ChangeCurrentSetup.label","تغيير الإعداد الحالي"},
		{"eOR.LimitToMyApplicableCatalogs.label","الحد من الكتالوجات القابلة للتطبيق"},
		{"eOR.MySpeciality.label","تخصصي"},
		{"eOR.FutureOrderLinking.label","إمكانية تطبيق ربط الطلبات المستقبلية"},
		{"eOR.PostedToFolioButNotBilledReceipted.label","تم النشر على Folio ولكن لم يتم إرسال الفاتورة / الاستلام"},
		{"eOR.BilledButNotReceipted.label","تمت الفواتير ولكن لم يتم استلامها"},
		{"eOR.MaxAllowedPeriodFromCurrentDay.label","أقصى فترة مسموح بها من اليوم الحالي"},
		{"eOR.LinkedVaccineName.label","اسم اللقاح المرتبط"},
		{"eOR.Repeat.label","كرر"},
		{"eOR.AllCategories.label","جميع الفئات"},
		{"eOR.AuthorizeForceAuthorization.label","تفويض التفويض بالقوة"},
		{"eOR.AuthorizationApplicable.label","إذن ينطبق"},
		{"eOR.IncludeForceAuthorization.label","تضمين الإذن الإجباري"},
		{"eOR.MyPatientAndMyRelatedPatient.label","مريضي ومريضي ذات الصلة"},
		{"eOR.MyPatientAndMyLocationPatient.label","مريضي ومريض موقعي"},
		{"eOR.MyPatient.label","مريضي"},
		{"eOR.MyRelatedPatient.label","مريضي ذات الصلة"},
		{"eOR.MyLocationPatient.label","موقع مريضي"},
		{"eOR.CGItemCode.label","كود الصنف CG"},
		{"eOR.Baht.label","ملف Baht"},
		{"eOR.PrintedDateTime.label","التاريخ / الوقت المطبوع"},
		{"eOR.InvokeSettlementScreenForPatClass.label","استدعاء شاشة التسوية لفئة المريض"},
		{"eOR.InvokePrintReportForBilling.label","استدعاء طباعة التقرير للفواتير"},
		{"eOR.DefaultRefundOptionForDiscontinueOrder.label","خيار الاسترداد الافتراضي لطلب التوقف"},
		{"eOR.NOSCHEDULE.label","لم يتم تعيين جدول زمني للتردد المحدد"},
		{"eOR.ExternalApplicationAccessionNo.label","رقم انضمام التطبيق الخارجي:"},
		{"eOR.ReportType.label","نوع التقرير"},
		{"eOR.GroupingCode.label","رمز التجميع"},
		{"eOR.GroupingDescription.label","وصف التجميع"},
		{"eOR.PrintReportFormat.label","طباعة تنسيق التقرير"},
		{"eOR.ApplicableOrderType.label","نوع الطلب المعمول به"},
		{"eOR.multipleRepPract.label","يتوفر العديد من ممارسي التقارير"},
		{"eOR.repPractNotSpc.label","لم يتم تحديد 'ممارس التقارير'"},
		{"eOR.OrderFormatSheet.label","ورقه تنسيق الطلبات"},
		{"eOR.OrderSheetForLaboratory.label","ورقة طلب للمختبر"},
		{"eOR.OrderSheetForBT.label","ورقة طلب للحصول على عينة دم"},
		{"eOR.OrderSheetForOthers.label","ورقة طلب للآخرين"},
		{"eOR.Duration.label","المدة الزمنية"},
		{"eOR.Week(s).label","أسبوع (أسابيع)"},
		{"eOR.Day(s).label","يوم (ايام)"},
		{"eOR.Month(s).label","شهر (شهور)"},
		{"eOR.Year(s).label","سنه (سنين)"},
		{"eOR.OrderedFromRadiology.label","طلبت من قسم الأشعة"},
		{"eOR.Reason.label","سبب"},
		{"eOR.PasteDetails.label","تفاصيل اللصق"},
		{"eOR.CollectionTime.label","وقت التجميع"},
		{"eOR.RejectOrders.label","رفض الطلبات"},
		{"eOR.WarningOrders.label","أوامر التحذير"},
		{"eOR.MyRelatedPatients.label","المرضى المرتبطين بي"},
		{"eOR.OrderedPatients.label","ترتيب المرضى"},
		{"eOR.MyPatients.label","مرضاي"},
		{"eOR.SpecimenNoFormat.label","تنسيق رقم العينة"},
		{"eOR.SpecimenLabelFormat.label","تنسيق تسمية العينة"},
		{"eOR.SpecimenFormatType.label","نوع تنسيق العينة"},
		{"eOR.ExternalApplication.label","التطبيق الخارجي"},
		{"eOR.IBARL.label","ملف IBARL"},
		{"eOR.IBAOR.label","ملف IBAOR"},
		{"eOR.RunningSerialNo.label","تشغيل الرقم التسلسلي"},
		{"eOR.CompletionRemarksMandatory.label","ملاحظات الإنجاز إلزامية"},
		{"eOR.OrderClinicalNoteResultType.label","طلب نوع نتيجة الملاحظة السريرية"},
		{"eOR.RestrictAutoCompleteForClinicalNote.label","تقييد الإكمال التلقائي تبعاآ لنتائج الملاحظات السريرية"},
		{"eOR.ResultComplete.label","الناتج - كامل"},
		{"eOR.Dx.label","ملف Dx"},
		{"eOR.AN.label","ملف AN"},
		{"eOR.ValidPeriod.label","فترة صالحة"},
		{"eOR.PackageRef.label","حزمة المرجع"},
		{"eOR.ConsultDate.label","تاريخ الاستشارة"},
		{"eOR.IncludeSystemCancelledOrders.label","تضمين أوامر النظام الملغاة"},
		{"eOR.ViewReplacedOrder.label","عرض الطلب المستبدل"},
		{"eOR.ViewOriginalOrder.label","عرض الطلب الأصلي"},
		{"eOR.OrderSetLevel.label","ترتيب تعيين المستوى"},
		{"eOR.OrderableLevel.label","المستوى القابل للطلب"},
		{"eOR.Chargable.label","خاضع للرسوم"},
		{"eOR.PerformedOnly.label","مكتمل - النتائج فقط"},
		{"eOR.MaxPeriodtoModifyCompletedResults.label","المدة القصوى للتعديل مكتملة - النتائج"},
		{"eOR.By24Hrs.label","بحلول 24 ساعة."},
		{"eOR.SeqStartsWith.label","ابدا ب"},
		{"eOR.SeqMaxNo.label","أقصى عدد"},
		{"eOR.DateDDMMYY.label","التاريخ (اليوم - الشهر - السنة)"},
		{"eOR.DateDDMMYYYY.label","التاريخ (اليوم - الشهر - السنة)"},
		{"eOR.SpecimenCollectedTime.label","وقت جمع العينة"},
		{"eOR.IncludeCheckedOutPatients.label","تضمين المرضى الذين تم تسجيلهم"},
		{"eOR.PromptforBookApptonOrder.label","موجه لحجز موعد عند الطلب"},
		{"eOR.DayAfterDisAdv.label","يوم بعد نصيحة الخروج"},
		{"eOR.HourAfterDisAdv.label","ساعة بعد نصيحة الخروج"},
		{"eOR.OTPreferredSurgery.label","طلب جراحة العيادات الخارجية"},
		{"eOR.OTPreferredDate.label","التاريخ المفضل للجراحة المقبلة"},
		{"eOR.ChkPendingOrders.label","تحقق من الأوامر المعلقة قبل إشعار الخروج"},
		{"eOR.Hold/Discontinue.label","كود سبب الحجز / التوقف إلزامي"},
		{"eOR.SecurePINPlaceOrder.label","الرقم السري الخاص بإدخال الطلبات"},
		{"eOR.AUTH_SCREEN.label","شاشة التفويض"},
		{"eOR.PractitionerName.label","اسم الممارس"},
		{"eOR.Unbilled.label","غير مفوتر"},
		{"eOR.OrderFrequency.label","تردد الطلب"},
		{"eOR.GroupBy.label","مجموعة من"},
		{"eOR.SingleOrder.label","طلبات يوم واحد"},
		{"eOR.ContinuousOrder.label","أوامر مستمرة"},
		{"eOR.All.label","الكل"},
		{"eOR.DispCustCat.label","فئة مخصصة نعم / لا"},
		{"eOR.OrderName.label","اسم الطلب"},
		{"eOR.CustCat.label","فئة مخصصة"},
		{"eOR.ChkPendOrders.label","تحقق من الأوامر المعلقة قبل الخروج"},
		{"eOR.NPBRequestForm.label","نموذج طلب NPB"},
		{"eOR.NotifyAlert.label","إعلام - تنبيه"},
		{"eOR.NonOTRooms.label","غرف لغير مرضى العيادات الخارجية"},
		{"eOR.PlaceOrders.label","تقديم الطلبات"},
		{"eOR.ViewAllOrders.label","عرض كل الطلبات"},
		{"eOR.PostMortemAppl.label","قابلية تطبيق ما بعد الوفاة"},
		{"eOR.PostMortemType.label","نوع ما بعد الوفاة"},
		{"eOR.OrderCategoryCode.label","كود فئة الطلب"},
		{"eOR.PostMortem.label","بعد الوفاة"},
		{"eOR.appl.label","القابلية للتطبيق"},
		{"eOR.Type.label","نوع"},
		{"eOR.PatientInterventions.label","تعليمات المريض للتدخلات"},
		{"eOR.Intervention.label","تدخل"},
		{"eOR.PatientInstructionsPrintPreview.label","معاينة إرشادات المريض قبل الطباعة"},
		{"eOR.FollowVisitType.label","اتبع نوع الزيارة"},
		{"eOR.SelectrowtoRemove.label","حدد صفًا لإزالته"},
		{"eOR.AllowOrdersforDeceased.label","السماح بالطلبات"},
		{"eOR.OnHoldRemarks.label","في الانتظار - ملاحظات"},
		{"eOR.dispbillinginfo.label","عرض معلومات الفواتير"},
		{"eOR.MARStatus.label","حاله سجل إدارة الدواء"},
		{"eOR.OrderSearchResultDisplayinVerticalOrder.label","عرض نتائج البحث بالترتيب العمودي"},
		{"eOR.dupoverridereason.label","سبب تجاوز مكرر"},
		{"eOR.ExternalLink.label","رابط خارجي"},
		{"eOR.DuplicateReasonRequired.label","مطلوب سبب تجاوز مكرر"},
		{"eOR.DurationValue.label","قيمة المدة"},
		{"eOR.PrintOption.label","خيار الطباعة"},
		{"eOR.SilentAlert.label","تنبيه صامت"},
		{"eOR.ConfirmAlert.label","تأكيد التنبيه"},
		{"eOR.OfflineAlert.label","تنبيه دون اتصال"},
		{"eOR.PrintOrderSheet.label","طباعة ورقة الطلب"},
		{"eOR.CurrentIPList.label","قائمة المرضى الداخليين الحاليين"},
		{"eOR.routineurgent.label","روتيني / عاجل"},
		{"eOR.routinestat.label","روتيني / ثابت"},
		{"eOR.urgentstat.label","عاجل / ثابت"},
		{"eOR.routineurgentstat.label","روتيني / عاجل / ثابت"},
		{"eOR.skipauthorization.label","تخطي التفويض على أساس الأولوية"},
		{"eOR.ServiceUnbilled.label","الخدمة غير مفوتره"},
		{"eOR.AmendOrder.label","عدّل"},
		{"eOR.amenddate.label","التاريخ المعدل"},
		{"eOR.amendby.label","عدل بواسطة"},
		{"eOR.amendreason.label","سبب التعديل"},
		{"eOR.amendreason1.label","تعديل السبب"},
		{"eOR.auditforamendorders.label","التدقيق المطبق على الطلبات المعدله"},
		{"eOR.amendreasonreqd.label","مطلوب سبب تعديل الطلب"},
		{"eOR.amendreasonmand.label","سبب تعديل الطلب إلزامي"},
		{"eOR.OrderFormatAuditTrail.label","عرض مسار التدقيق - تنسيق الطلب"},
		{"eOR.OrderFormatLineAuditTrail.label","عرض مسار التدقيق - سطر تنسيق الطلب"},
		{"eOR.others.label","الآخرين"},
		{"eOR.orderingspecialitycopypreviousorder.label","تصفيه التخصص في نسخ الطلبات السابقة"},
		{"eOR.notapplicable.label","لا ينطبق"},
		{"eOR.primaryspeciality.label","التخصص الأساسي"},
		{"eOR.encounterspeciality.label","لقاء التخصص"},
		{"eOR.defaultperiodincopypreviousorders.label","الفترة الافتراضية في نسخ الأوامر السابقة"},
		{"eOR.comments.label","تعليقات"},
		{"eOR.dispslipbarcodesearch.label","السماح بإرسال البحث عن قسيمة الباركود "},
		{"eOR.recordConsentFormWithOrder.label","تسجيل نموذج الموافقة مع الطلب"},
		{"eOR.rptshift1.label","تقرير إحصائي من قبل الممارس"},
		{"eOR.rptshift2.label","تقرير احصائي بالسنة / الشهر"},
		{"eOR.practitionerfrom.label","ممارس من"},
		{"eOR.practitionerto.label","ممارس ل"},
		{"eOR.NationalId.label","الهوية الوطنية"},
		{"eOR.CompletedOrderStatus.label","حالة الطلب مكتملة"},
		{"eOR.ApplyOrdPrivRuleOnly.label","تطبيق قواعد امتياز الطلب فقط"},
		{"eOR.diseasecode.label","كود المرض (HAAD)"},
		{"eOR.ordmultselnonmandat.label","عنصر قائمة متعدد التحديد إلزامي"},
		{"eOR.ResultsViewed.label","عرض النتائج"},
		{"eOR.Applicability.label","القابلية للتطبيق"},
		{"eOR.BarcodeRequired.label","الباركود مطلوب"},
		{"eOR.BarcodePrintButton.label","إعادة طباعة الباركود"},
		{"eOR.BarcodePrint.label","إعادة طباعة الباركود"},
		{"eOR.NOTDONE.label","لم يتم التنفيذ"},
		{"eOR.NotDoneReasonMand.label","كود سبب عدم التنفيذ إلزامي"},
		{"eOR.NotDoneReason.label","سبب عدم التنفيذ"},
		{"eOR.DosageType.label","نوع الجرعة"},
		{"eOR.M2.label","M2"},
		{"eOR.Kg.label","كيلوجرام"},
		{"eOR.Age.label","العمر"},
		{"eOR.OncoRegimenFreq.label","تردد نظام الأورام"},
		{"eOR.AgeGroupDef.label","تعريف الفئة العمرية (الحد الأدنى ، الحد الأقصى)"},
		{"eOR.Applicable.label","قابل للتطبيق"},
		{"eOR.ReRoutePrinter.label","إعادة توجيه الطابعة"},
		{"eOR.AckOrder.label","الطلب المعترف به"},
		{"eOR.PrintRegStatus.label","طباعة ملصق للطلب المسجل"},
		{"eOR.RegisterLabel.label","تسجيل الملصق"},
		{"eOR.RefRange.label","مجموعة المرجعية"},
		{"eOR.LabSpecimenNotRegister.label","عينة المختبر - غير مسجلة"},
		{"eOR.TimeFrameAlertForLab.label","الإطار الزمني لتنبيه عينة المختبر العاجل / الثابت "},
		{"eOR.SpeciDateTime.label","تاريخ / وقت إرسال العينة"},
		{"eOR.PatientPhoto.label","صورة المريض"},
		{"eOR.ReplaceThroughTermSetAndCategory.label","استبدال الطلب من خلال مجموعة الحكمة / الفئة الحكيمة"},
		{"eOR.InActiveOrders.label","طلبات غير نشطة"},
		{"eOR.CancelOption.label","خيار الإلغاء للرعاية النهارية والمرضى الداخليين"},
		{"eOR.RejectedRemarks.label","ملاحظات مرفوضة"},
		{"eOR.RejectedDateTime.label","التاريخ / الوقت المرفوض"},
		{"eOR.ViewAmndReason.label","عرض أسباب التعديل"},
		{"eOR.AmndDate.label","تاريخ / وقت التعديل"},
		{"eOR.AmndOrdId.label","تعديل رقم تعريف الطلب"},
		{"eOR.AmndReason.label","سبب التعديل"},
		{"eOR.sNo.label","الرقم التسلسلي"},
		{"eOR.ExamStatus.label","حالة الاختبار"},
		{"eOR.PerformingBy.label","الأداء بواسطه"},
		{"eOR.Date.label","التاريخ"},
		{"eOR.ViewRemarks.label","عرض الملاحظات"},
		{"eOR.OnHold.label","قيد الانتظار"},
		{"eOR.Prelim.label","التمهيد"},
		{"eOR.radiologist.label","أخصائي أشعة"},
		{"eOR.assigndiag.label","تعيين"},
		{"eOR.HideSpecimenTypeInResults.label","إخفاء نوع العينة في النتائج"},
		{"eOR.HideReportingPractitioner.label","إخفاء ممارس التقارير في النتائج"},
		{"eOR.DisSelectAllOptn.label","تعطيل تحديد كل الخيارات المطبقة"},
		{"eOR.ReplaceOrderableType.label","استبدال النوع القابل للطلب"},
		{"eOR.CategoryWise.label","فئة الحكمة"},
		{"eOR.InvokeInstructionWindow.label","استدعاء نافذة التعليمات"},
		{"eOR.InstrnContentType.label","نوع محتوى التعليمات"},
		{"eOR.RestrictAEEncounters.label","تقييد تقديم الطلب لزيارة العيادات الخارجيه/الطوارئ ، في حالة وجود زيارة مفتوحة لمريض الداخلي"},
		{"eOR.DosageTypeDefn.label","تعريف نوع الجرعة"},
		{"eOR.OccurranceNo.label","رقم الحدوث"},
		{"eOR.ByDosageTypeDefn.label","حسب تعريف نوع الجرعة"},
		{"eOR.OrderSetSearch.label","البحث في مجموعه الطلب"},
		{"eOR.PendingAuth.label","تصريح معلق"},
		{"eOR.SecSpecialitiesForMySpecialty.label","ينطبق التخصص الثانوي على مرشح التخصص الخاص بي."},
		{"eOR.CategoryNo.label","رقم الفئه"},
		{"eOR.Facilities.label","منشأت"},
		{"eOR.ApplicableFacilities.label","المنشأت المعمول بها"},
		{"eOR.UploadImagesVideos.label","تحميل الصور / مقاطع الفيديو"},
		{"eOR.Sno.label","الرقم التسلسلي"},
		{"eOR.Jpg.label","ملف JPG"},
		{"eOR.Gif.label","ملف GIF"},
		{"eOR.Pdf.label","ملف PDF"},
		{"eOR.Mp4.label","ملف MP4"},
		{"eOR.VideoFileList.label","قائمة ملفات الفيديو"},
		{"eOR.NONFPPPATIENT.label","مريض لا يدفع الثمن بالكامل"},
		{"eOR.FPPPATIENT.label","المريض يدفع الثمن الكامل"},
		{"eOR.Simple.label","بسيط"},
		{"eOR.Medium.label","معتدل"},
		{"eOR.Complex.label","معقد"},
		{"eOR.FPPCATEGORYS.label","متاح لفئة FPP"},
		{"eOR.FPPDETAILS.label","تفاصيل FPP"},
		{"eOR.FilterByFPP.label","تصفية تبعآ ل FPP"},
		{"eOR.FPPCATEGORY.label","فئة FPP"},
		{"eOR.Fully/Partial.label","فاتورة كاملة / جزئية أو مدفوعة"},
		{"eOR.InteractionDtls.label","تفاصيل التفاعل"},
		{"eOR.PractTypeTimeBasedRule.label","تطبيق القواعد المستندة إلى الوقت المطبقة في ترتيب القاعدة حسب نوع الممارس"},
		{"eOR.DayAfterDischargeAdvice.label","اليوم التالي لأمر الخروج"},
		{"eOR.HourAfterDischargeAdvice.label","الساعة التالية لأمر الخروج "},
		{"eOR.FreqOrderAsIndividualOrders.label","أوامر التردد التي تعتبر أوامر فردية"},//7540
		{"eOR.BillingStatus.label","حالة الفوترة"},//19112
		{"eOR.PrimaryDiagnosisMandatory.label","التشخيص الأولي إلزامي"}//6868
	};
}