/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.LocalInterfacePlugin from eIP.IPPatientEmergencyTransfer.IPPatientEmergencyTransferManager
package eIP.IPPatientEmergencyTransfer;

/**
 * Local interface for IPPatientEmergencyTransfer
 */
public interface IPPatientEmergencyTransferLocal 
extends javax.ejb.EJBLocalObject {
    java.util.HashMap insertIPPatientEmergencyTransfer(java.util.Properties p, java.util.HashMap hashData);
// ----------------------------------------------------------------
// Define your custom append code in a file called local-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
