/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eSM.resources;

import java.util.*;

public class  Labels extends ListResourceBundle{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
			{"eSM.AccessLevel.label","Access Level"},
			{"eSM.AccessRightsforMenu.label","Access Rights for Menu"},
			{"eSM.AccessRightsForMenuFunctions.label","Access Rights For Menu-Functions"},
			{"eSM.AccessRightsforMenuSubFunctions.label","Access Rights for Menu - Sub-Functions"},
			{"eSM.AccountEntLongname.label","Accounting Entity Long Name"},
			{"eSM.AccountEntShortname.label","Accounting Entity Short Name"},
			{"eSM.AccountingEntityID.label","Accounting Entity ID"},
			{"eSM.AccountingParameters.label","Accounting Parameters"},
			{"eSM.AddNewFunctions.label","Add New Functions"},
			{"eSM.AdhocMenu.label","Adhoc Menu"},
			{"eSM.AdhocMenuEffectiveDate.label","Adhoc Menu Effective Date"},
			{"eSM.ApplicationGroup.label","Application Group"},
			{"eSM.ApplicationSecurity.label","Application Security"},
			{"eSM.ApplicationServerIPAddress.label","Application Server IP Address"},
			{"eSM.AssociatedFacilities.label","Associated Facilities"},
			{"eSM.AssociatedMenuFunctions.label","Associated Menu Functions"},
			{"eSM.AssociatedResponsibilities.label","Associated Responsibilities"},
			{"eSM.AssociatedUsers.label","Associated Users"},
			{"eSM.BackGroundProcesses.label","BackGround Processes"},
			{"eSM.Bitmap.label","Bitmap"},
			{"eSM.BitMappedReports.label","Bitmapped Reports"},
			{"eSM.ByAccountEntity.label","By Accounting Entity"},
			{"eSM.ByResponsibility.label","By Responsibility"},
			{"eSM.Changes.label","Changes"},
			{"eSM.ChangeWSIdentificationatFacilityLevel.label","Change WS Identification at Facility Level"},
			{"eSM.Character.label","Character"},
			{"eSM.ClinicalSupport.label","Clinical Support"},
			{"eSM.ConstructMenu.label","Construct Menu"},
			{"eSM.CoreApplications.label","Core Applications"},
			{"eSM.CreateMenu.label","Create Menu"},
			{"eSM.CurrencyName.label","Currency Name"},
			{"eSM.CurrentFunctions.label","Current Functions"},
			{"eSM.DatabaseResourceGroup.label","Database Resource Group"},
			{"eSM.DatabaseRoles.label","Database Roles "},
			{"eSM.DateDesc.label","Date (Desc)"},
			{"eSM.DayNo.label","Day No"},
			{"eSM.DecimalName.label","Decimal Name"},
			{"eSM.DefaultFileFormat.label","Default File Format"},
			{"eSM.DefaultPrinter.label","Default Printer"},
			{"eSM.DefaultReportMode.label","Default Report Mode"},
			{"eSM.DeleteAllowed.label","Delete Allowed"},
			{"eSM.DepartmentLength.label","Department Length"},
			{"eSM.DestCode.label","Destination Code"},
			{"eSM.DestDesc.label","Destination Description"},
			{"eSM.DestLocn.label","Dest Locn"},
			{"eSM.DisplaySiteName.label","Display Site Name"},
			{"eSM.DMP.label","DMP"},
			{"eSM.down.label","Down"},
			{"eSM.EffectiveFromDate.label","Effective From Date"},
			{"eSM.EffectiveToDate.label","Effective To Date"},
			{"eSM.EnterpriseAdmin.label","Enterprise Admin"},
			{"eSM.ExcludeRemoveSubmenuFunction.label","Exclude/Remove Submenu/Function"},
			{"eSM.Executable.label","Executable"},
			{"eSM.ExpirationPeriod.label","Expiration Period"},
			{"eSM.ExternalInterfaces.label","External Interfaces"},
			{"eSM.Facilities.label","Facilities"},
			{"eSM.FacilitiesforUser.label","Facilities for User"},
			{"eSM.FacilitybasedReport.label","Facility based Report"},
			{"eSM.FacilitybasedReportParameters.label","Facility based Report Parameters"},
			{"eSM.FailedLoginAttempts.label","Failed Login Attempts"},
			{"eSM.FailedProcessID.label","Failed Process ID"},
			{"eSM.FinancialManagement.label","Financial Management"},
			{"eSM.FinancialSetup.label","Financial Setup"},
			{"eSM.Forms.label","Forms"},
			{"eSM.FrequentlyAccessedList.label","Frequently Accessed List"},
			{"eSM.FunctionalName.label","Functional Name"},
			{"eSM.FunctionalRoleDetails.label","Functional Role Details"},
			{"eSM.FunctionalRoleType.label","Functional Role Type"},
			{"eSM.FunctionalType.label","Functional Type"},
			{"eSM.Functionsby.label","Functions by "},
			{"eSM.FunctionsbyResponsibilityGroup.label","Functions by Responsibility Group"},
			{"eSM.GenerateFile.label","Generate File"},
			{"eSM.GraceTime.label","Grace Time"},
			{"eSM.HeadoftheUnit.label","Head of the Unit"},
			{"eSM.HolidayorWorkingday.label","Holiday or Working day"},
			{"eSM.HumanResourceManag.label","Human Resource Management"},
			{"eSM.Inkjet.label","Inkjet"},
			{"eSM.InsertAllowed.label","Insert Allowed"},
			{"eSM.InternalRequest.label","Internal Request"},
			{"eSM.IPAddress.label","IP Address"},
			{"eSM.Java.label","Java"},
			{"eSM.JobQueue.label","Job Queue"},
			{"eSM.LabelPrinter.label","Label Printer"},
			{"eSM.Laser.label","Laser"},
			{"eSM.LicenseNo.label","License No"},
			{"eSM.ListofFunctions.label","List of Functions"},
			{"eSM.ListofSubmenus.label","List of Submenus"},
			{"eSM.Logo.label","Logo"},
			{"eSM.MasterName.label","Master Name"},
			{"eSM.MaterialsManagement.label","Materials Management"},
			{"eSM.MenuAdminID.label","Menu Admin ID"},
			{"eSM.MenuAdministrator.label","Menu Administrator"},
			{"eSM.MenuAdminName.label","Menu Admin Name"},
			{"eSM.MenuName.label","Menu Name"},
			{"eSM.MenuPreview.label","Menu Preview"},
			{"eSM.MenuRestrictforResponsSubFunction.label","Menu Restriction for Responsibility Sub-Functions"},
			{"eSM.MenuRestrictionfor.label","Menu Restriction for"},
			{"eSM.MenuRestrictionforResponsibility.label","Menu Restriction for Responsibility"},
			{"eSM.Menus.label","Menus"},
			{"eSM.NextExecutionDateTime.label","Next Execution Date/Time"},
			{"eSM.NonTranslated.label","Non-Translated"},
			{"eSM.NoofAccountingPeriods.label","No. of Accounting Periods"},
			{"eSM.NumberofCopies.label","Number of Copies"},
			{"eSM.NumberofDecimals.label","Number of Decimals"},
			{"eSM.Operational.label","Operational"},
			{"eSM.OperationalStatus.label","Operational Status"},
			{"eSM.OrderofArea.label","Order of Area"},
			{"eSM.OrderofLine.label","Order of Line"},
			{"eSM.OrderofPostalCode.label","Order of Postal Code"},
			{"eSM.OrderofRegion.label","Order of Region"},
			{"eSM.OrderofTown.label","Order of Town"},
			{"eSM.PasswordControl.label","Password Control"},
			{"eSM.PasswordLockPeriod.label","Password Lock Period"},
			{"eSM.PINNo.label","PIN No"},
			{"eSM.PreferredLanguage.label","Preferred Language"},
			{"eSM.PrefixDepartmentbyFacilityID.label","Prefix Department by Facility ID"},
			{"eSM.PrintAllowed.label","Print Allowed"},
			{"eSM.Printer.label","Printer"},
			{"eSM.PrinterDetails.label","Printer Details"},
			{"eSM.PrinterID.label","Printer ID"},
			{"eSM.PrinterName.label","Printer Name"},
			{"eSM.Printers.label","Printers"},
			{"eSM.PrinterType.label","Printer Type"},
			{"eSM.PrintRouting.label","Print Routing"},
			{"eSM.ProhibitReuse.label","Prohibit Reuse"},
			{"eSM.Prompts.label","Prompts"},
			{"eSM.PurgePeriod.label","Purge Period"},
			{"eSM.PurgeProcessDetails.label","Purge Process Details"},
			{"eSM.Queries.label","Queries"},
			{"eSM.QueryAllowed.label","Query Allowed"},
			{"eSM.QueryonResponsibility.label","Query on Responsibility "},
			{"eSM.QueryonUsers.label","Query on Users"},
			{"eSM.QueueName.label","Queue Name"},
			{"eSM.ReenterNewPassword.label","Re-enter New Password"},
			{"eSM.ReportDetails.label","Report Details"},
			{"eSM.ReportGroup.label","Report Group"},
			{"eSM.ReportGroupDesc.label","Report Group Description"},
			{"eSM.ReportGroupID.label","Report Group ID"},
			{"eSM.ReportNature.label","Report Nature"},
			{"eSM.ReportOutputDirectory.label","Report Output Directory"},
			{"eSM.Reports.label","Reports"},
			{"eSM.ReportService.label","Report Service"},
			{"eSM.ReportServiceID.label","Report Service ID"},
			{"eSM.ReportServiceName.label","Report Service Name"},
			{"eSM.ResourceGroup.label","Resource Group"},
			{"eSM.ResourceGroupID.label","Resource Group ID"},
			{"eSM.ResourceGroupName.label","Resource Group Name"},
			{"eSM.ResponsibilityforFacility.label","Responsibility for Facility"},
			{"eSM.ResponsibilityforUser.label","Responsibility for User"},
			{"eSM.ResponsibilityGroup.label","Responsibility Group"},
			{"eSM.ResponsibilityGroupID.label","Responsibility Group ID"},
			{"eSM.ResponsibilityGroupName.label","Responsibility Group Name"},
			{"eSM.ResponsibilityIDFrom.label","Responsibility ID From"},
			{"eSM.ResponsibilityList.label","Responsibility List"},
			{"eSM.RestrictedSubmenuFunctionDetls.label","Restricted Submenu/Function Details"},
			{"eSM.Reuse.label","Reuse"},
			{"eSM.ReuseOption.label","Reuse Option"},
			{"eSM.RoleName.label","Role Name"},
			{"eSM.SearchFacility.label","Search Facility"},
			{"eSM.SearchResponsibility.label","Search Responsibility"},
			{"eSM.SelectFacility.label","Select Facility"},
			{"eSM.SiteID.label","Site ID"},
			{"eSM.SMMasterCodeList.label","SM Master Code List"},
			{"eSM.SpecialtyServices.label","Specialty Services"},
			{"eSM.StartFiscalMonth.label","Start Fiscal Month"},
			{"eSM.StatusChangeAllowed.label","Status Change Allowed"},
			{"eSM.SubFunctionName.label","Sub-Function Name"},
			{"eSM.Submenu.label","Submenu"},
			{"eSM.Tool.label","Tool"},
			{"eSM.ToolUsed.label","Tool Used"},
			{"eSM.TransactionBased.label","Transaction Based"},
			{"eSM.TransBased.label","Trans Based"},
			{"eSM.Translated.label","Translated"},
			{"eSM.TranslatedLanguage.label","Translated Language"},
			{"eSM.TranslationManager.label","Translation Manager"},
			{"eSM.UpdateAllowed.label","Update  Allowed"},
			{"eSM.UserIDFrom.label","User ID From"},
			{"eSM.UserList.label","User List"},
			{"eSM.UserResponsibilityAccessList.label","User/Responsibility Access List"},
			{"eSM.Users.label","Users"},
			{"eSM.WeekAppl.label","Week Appl"},
			{"eSM.WorkStationIdentification.label","WorkStation Identification"},
			{"eSM.WorkstationIdentificationBy.label","Workstation Identification By"},
			{"eSM.ReportServerIPAddress.label","Report Server IP Address"},
			{"eSM.ForeignCurrency.label","Foreign Currency"},
			{"eSM.GenActPeriod.label","Generate Accounting Period"},
			{"eSM.MaintainActPeriod.label","Maintain Accounting Period"},
			{"eSM.CancelledDocuments.label","Cancelled Documents"},
			{"eSM.DocumentTypes.label","Document Type"},
			{"eSM.AcctEntity.label","Acct Entity"},
			{"eSM.SysGenDocNo.label","System Generated Document Number"},
			{"eSM.DocNoGen.label","Document Number Generation"},
			{"eSM.StartDocNo.label","Start Doc Number"},
			{"eSM.NextDocNo.label","Next Doc Number"},
			{"eSM.AutoPrint.label","Automatic Print"},
			{"eSM.EntryMode.label","Entry Mode"},
			{"eSM.Online.label","Online"},
			{"eSM.DocNumber.label","Doc Number"},
			{"eSM.AccountYear.label","Accounting Year"},
			{"eSM.AccountPeriodYear.label","Accounting Period Year"},
			{"eSM.AccountPeriodMonth.label","Accounting Period Month"},
			{"eSM.AccountPeriodSdate.label","Accounting Period Start Date"},
			{"eSM.AccountPeriodEdate.label","Accounting Period End Date"},
			{"eSM.AccountPeriodDesc.label","Accounting Period Description"},
			{"eSM.CalenderYear.label","Calendar Year"},
			{"eSM.CalenderMonth.label","Calendar Month"},
			{"eSM.CurrencyCode.label","Currency Code"},
			{"eSM.ConversionRate.label","Conversion Rate"},
			{"eSM.ConversionOperator.label","Conversion Operator"},
			{"eSM.ProductLineCode.label","Product Line Code"},
			{"eSM.ProductGroupCode.label","Product Group Code"},
			{"eSM.DepartmentCode.label","Department Code"},
			{"eSM.SubLedgerLineCode.label","Sub Ledger Line Code"},
			{"eSM.SubLedgerGroupCode.label","Sub Ledger Group Code"},
			{"eSM.MainAccountCode2.label","Main Account Code2"},
			{"eSM.MainAccountCode1.label","Main Account Code1"},
			{"eSM.FacImgFileName.label","Facility Logo Image File Name"},
			{"eSM.LoginScrnImgFileName.label","Login Screen Image File Name"},
			{"eSM.SiteLogoLoginScreen.label","Site Logo(Login Screen)"},
			{"eSM.HeaderLogoImageFileName.label","Header Logo Image File Name"},
			{"eSM.SiteLogoPageHeader.label","Site Logo(Page Header)"},
			{"eSM.SelectContentsLayout.label","Select Contents For Layout"},
			{"eSM.ContentType.label","Content Type"},
			{"eSM.Desktop.label","Desktop"},
			{"eSM.Summary.label","Summary"},
			{"eSM.SummaryDetls.label","Summary Details"},
			{"eSM.Navigation.label","Navigation"},
			{"eSM.Links.label","Links"},
			{"eSM.Non.label","Non"},
			{"eSM.Show.label","Show"},
			{"eSM.Type.label","Type"},
			{"eSM.Customisation.label","Customisation"},
			{"eSM.Selected.label","Selected"},
			{"eSM.FacilityCategoryCode.label","Facility Category Code"},
			{"eSM.FacilityCategoryDesc.label","Facility Category Desc"},
			{"eSM.PostalCodeLinkRequired.label","Postal Code Link Required"},
			{"eSM.DisplayUserNameApplHeader.label","Display User Name in Application Header"},
			{"eSM.ReportConfigKey.label","Report Config Key"},
			{"eSM.ActiveDirectoryID.label","Active Directory ID"},
			{"eSM.EnforcePasswordPolicy.label","Enforce Password Policy"},
			{"eSM.CaseSensitivePassword.label","Case Sensitive Password"},
			{"eSM.AllowSplCharInPassword.label","Allowed Special Characters in Password"},
			{"eSM.PASSWORD_POLICY.label","Password Policy#"},
			{"eSM.PASSWORD_POLICY1.label","Password should start with Alphabet and followed either by Numeric values or these Special characters "},
			{"eSM.PasswordExpiryAlert.label","Password Expiry Alert"},			
			{"eSM.ChangePasswordFirstLogin.label","Change Password during First Login"},
			{"eSM.ChangePasswordMandatory.label","Change Password Mandatory"},
			{"eSM.MultipleLoginAllowed.label","Multiple Login Allowed"},
			{"eSM.UnlockUserSessionAfter.label","Unlock User Session After"},
			{"eSM.ReleaseLockdUserSession.label","Release Locked User Session"},
			{"eSM.VatNo.label","VAT No"}, //added by Mano aganist MMS-DM-CRF-0118.3
			{"eSM.SrhCrtForSpltyAndNursingUnit.label","search criteria option for Specialty & Nursing unit"},//Added by Shanmukh on 7th-AUG-2018for ML-MMOH-CRF-1115
			{"eSM.NatIDMandForCitizenInPractAndOtherStaff.label","National Id Field Mandatory For Citizen In Practitioner And Other Staff"}, //Added by Suji Keerthi for MOHE-CRF-0011 on 21-Apr-2020
			{"eSM.UserCreationMasterAccess.label","User Creation Master Access"}, //Added by Afruddin for MOHE-CRF-0024 US0001 on 10-Jun-2020
			{"eSM.UserIDDifferedWithPractStaffID.label","User ID differed with Pract/Staff ID"}, //Added by Afruddin for MOHE-CRF-0024 US0001 on 10-Jun-2020
			{"eSM.UserMoreThan1Facility.label","User more than 1 Facility"}, //Added by Afruddin for MOHE-CRF-0024 US0001 on 10-Jun-2020
			{"eSM.InventoryDocOption.label","Inventory Document Option"},//Added by Kamatchi S for MO-CRF-20171.1
			{"eSM.DocStorageOption.label","Document Storage Option"},//Added by Kamatchi S for MO-CRF-20171.1
			{"eSM.DataBaseExist.label","Database(Existing)"},//Added by Kamatchi S for MO-CRF-20171.1
			{"eSM.SharedPath.label","Shared Path"},//Added by Kamatchi S for MO-CRF-20171.1
			{"eSM.AutoDisbleInactiveUser.label","Auto-Disable Inactive User Access"},//Added by Kamatchi S for ML-BRU-CRF-0594
			{"eSM.AutoDisbleDate.label","Auto-Disabled Date"},//Added by Kamatchi S for ML-BRU-CRF-0594
			{"eSM.Auth_Screen.label","Authorization Screen"},
			{"eSM.LinkActDirUser.label","Link Active Directory User"}//Added by kamatchi S for ML-MMOH-CRF-1844
	};
}
