/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.ejb.interfaces.RemoteInterfacePlugin from eAM.UserForOperator.UserForOperatorManager
package eAM.UserForOperator;

/**
 * Remote interface for UserForOperator
 */
public interface UserForOperatorManagerRemote 
extends javax.ejb.EJBObject {
    java.util.HashMap insertUserForOperator(java.util.HashMap hashmap) throws java.rmi.RemoteException;
    java.util.HashMap modifyOperator(java.util.HashMap hashmap) throws java.rmi.RemoteException;
    java.util.HashMap deleteUserForOperator(java.util.HashMap hashmap) throws java.rmi.RemoteException;
// ----------------------------------------------------------------
// Define your custom append code in a file called remote-custom.vm 
// and place it in your merge directory.
// ----------------------------------------------------------------
}
