/*******************************************************************************
 * Copyright 1999-2015, Computer Sciences Corporation. All rights reserved.
 *  
 * Warning: This computer program is protected by copyright law and international treaties.
 * Unauthorized reproduction or distribution of this program, or any portion of it, 
 * may result in severe civil and criminal penalties, and will be prosecuted to 
 * the maximum extent possible under the law.
 ******************************************************************************/
package eMP.resources;

import java.util.*;

public class Labels_th extends ListResourceBundle implements java.io.Serializable{
	public Object[][] getContents() {
         return contents;
    }

	static final Object[][] contents = {
			{"eMP.AcceptAlphanumeric.label","ยอมรับตัวเลข/ตัวอักษร"},
			{"eMP.AcceptApptRefNoReferralIDinRegisterPatient.label","ยอมรับหมายเลขอ้างอิงการนัดหมาย/ หมายเลขการส่งตัวผู้ป่วยในการลงทะเบียน"},
			{"eMP.AcceptExpiryDate.label","ยอมรับวันหมดอายุ"},
			{"eMP.AcceptforOtherPatientSeries.label","ยอมรับลำดับเลขชุดอื่นสำหรับผู้ป่วย "},
			{"eMP.AcceptOtherAltID.label","ยอมรับหมายเลขประจำตัวอื่น"},
			{"eMP.AcceptPatientNameasMultiparts.label","ยอมรับชื่อผู้ป่วย "},
			{"eMP.AcceptPatientNameinLocalLanguage.label","ยอมรับชื่อผู้ป่วย ในภาษาท้องถิ่น"},
			{"eMP.AccessRightsforViewPatientPhoto.label","มีสิทธิในการดูรูปผู้ป่วย"},
			{"eMP.ActivateInactivatePatient.label","ผู้ป่วยที่ยังติดต่อ/ ขาดการติดต่อ กับโรงพยาบาล"},
			{"eMP.ActivateInactivateReason.label","เหตุผลการติดต่อ การขาดการติดต่อ"},
			{"eMP.activationremarks.label","หมายเหตุของการใช้งาน"},
			{"eMP.ActiveStatus.label","กำลังใช้งาน"},
			{"eMP.AddedDetails.label","รายละเอียดเพิ่มเติม"},
			{"eMP.AdditionalFields.label","ฟิลด์เพิ่มเติม"},
			{"eMP.AgeLimitofMother.label","อายุที่จำกัดสำหรับการเป็นมารดา"},
			{"eMP.AliasName.label","นามแฝง"},
			{"eMP.AllowRegistrationWithin.label","อนุญาติการลงทะเบียน ภายในระยะเวลา"},
			{"eMP.AllowseparateMRN.label","อนุญาติการแยกหมายเลขเวชระเบียน"},
			{"eMP.Allseries.label","ทุกเลขชุด"},
			{"eMP.Alone.label","คนเดียว"},
			{"eMP.AlphabetsandSpecialCharecters.label","ตัวอักษรและอักขระพิเศษ"},
			{"eMP.AlternateIDChecks.label","เลือกหมายเลขประจำตัวอื่น"},
			{"eMP.AlternateIDSeries.label","ชุดหมายเลขบัตรประจำตัวอื่น"},
			{"eMP.AlternateIDType.label","ชนิดหมายเลขบัตรประจำตัวอื่น"},
			{"eMP.AlternateIDTypeforMembershipID.label","ชนิดหมายเลขบัตรประจำตัวอื่น สำหรับ หมายเลขสมาชิกภาพ                                                                                                "},
			{"eMP.Ambulance.label","รถพยาบาล"},
			{"eMP.AnteNatalCare.label","การฝากครรภ์"},
			{"eMP.AntenatalCareDetails.label","รายละเอียดการดูแลทารก"},
			{"eMP.ApplyEligibilityRulesbyPatientCategory.label","ใช้กฏที่เหมาะสมกับเกณฑ์การแบ่งประเภทผู้ป่วย"},
			{"eMP.apptreferraldtls.label","รายละเอียดของการนัด/การส่งตัวเพื่อการรักษาต่อ"},
			{"eMP.ApptSch.label","การนัดหมายผู้ป่วยนอก"},
			{"eMP.AreaDesc.label","คำอธิบายของสถานที่"},
			{"eMP.Arrangement.label","การจัดการ"},
			{"eMP.AttendingMidwife.label","ผดุงครรภ์ที่ดูแล"},
			{"eMP.AttendingNurse.label","พยาบาลผู้ดูแล"},
			{"eMP.Atthelevelof.label","ที่ระดับของ"},
			{"eMP.AuditTrailParameterSettings.label","การตั้งค่า parameter"},
			{"eMP.Baby.label","ทารก"},
			{"eMP.BabyName.label","ชื่อทารก"},
			{"eMP.BabySex.label","เพศของทารก"},
			{"eMP.BabySuffix.label","คำต่อท้ายทารก"},
			{"eMP.BCG.label","วัคซีนบีซีจี"},
			{"eMP.BeforeArrival.label","ก่อนมาถึง"},
			{"eMP.BirthAttendant.label","การเฝ้าคลอด"},
			{"eMP.BirthCertificateNo.label","หมายเลขสูติบัตร"},
			{"eMP.BirthDateFrom.label","วันที่เกิด ตั้งแต่"},
			{"eMP.BirthOrder.label","ลำดับของการเกิด"},
			{"eMP.BirthPlaceCode.label","รหัสสถานที่เกิด"},
			{"eMP.BirthPlaceDesc.label","คำอธิบายสถานที่เกิด"},
			{"eMP.BirthWeight.label","น้ำหนักแรกคลอด"},
			{"eMP.Bornat.label","เกิดที่…."},
			{"eMP.BornBeforeArrival.label","คลอดก่อนมาถึงโรงพยาบาล"},
			{"eMP.BornWhere.label","สถานที่เกิด"},
			{"eMP.Bottle.label","ขวด"},
			{"eMP.Breast.label","เต้านม"},
			{"eMP.ByName.label","โดยชื่อ..."},
			{"eMP.CapturePatientPhoto.label","จับภาพผู้ป่วย"},
			{"eMP.categoryexpirydate.label","วันหมดอายุของประเภทของผู้ป่วย"},
			{"eMP.Changeallowedforseries.label","อนุญาติให้เปลี่ยนแปลงชุดเลขลำดับ"},
			{"eMP.ChangeDemographics.label","เปลี่ยนแปลงประวัติทั่วไป"},
			{"eMP.ChartMaintenance.label","การรักษาแฟ้มประวัติผู้ป่วย"},
			{"eMP.CheckDigit.label","ตรวจสอบตัวเลข"},
			{"eMP.CheckDigitScheme.label","ตรวจสอบแบบแผนตัวเลข"},
			{"eMP.CheckDigitSchemeID.label","ตรวจสอบหมายเลขประจำแบบแผนตัวเลข"},
			{"eMP.CheckDigitSchemeName.label","ตรวจสอบชื่อแบบแผนตัวเลข"},
			{"eMP.CheckExp.label","ตรวจสอบวันหมดอายุ"},
			{"eMP.CheckUnique.label","ตรวจสอบความจำเพาะ"},
			{"eMP.ChestCircum.label","เส้นรอบวงของหน้าอก"},
			{"eMP.ChestCirumference.label","รอบอก"},
			{"eMP.ChgPatDtl.title.label","เปลี่ยนแปลงรายละเอียดของผู้ป่วย"},
			{"eMP.child.label","เด็ก"},
			{"eMP.ChildBirthDateFrom.label","วันเกิดเด็ก ตั้งแต่"},
			{"eMP.ChildBirthDateTo.label","วันเกิดทารกถึง"},
			{"eMP.clinicaldetails.label","รายละเอียดทางคลินิก"},
			{"eMP.Combination.label","การรวม"},
			{"eMP.ComplicationsOfDeliveryCode.label","รหัสภาวะแทรกซ้อนของการคลอด"},
			{"eMP.ComplicationsOfDeliveryDesc.label","คำอธิบายภาวะแทรกซ้อนของการคลอด"},
			{"eMP.CompofDelivery.label","ภาวะแทรกซ้อนจากการคลอด"},
			{"eMP.CongenitalAnomalies.label","ความผิดปกติแต่กำเนิด"},
			{"eMP.CongenitalAnomaliesCode.label","รหัสความพิการแต่กำเนิด"},
			{"eMP.CongenitalAnomaliesDesc.label","คำอธิบายความพิการแต่กำเนิด"},
			{"eMP.ContactAddresses.label","ที่อยู่ผู้ป่วย"},
			{"eMP.ContactModes.label","ประเภทของการติดต่อ"},
			{"eMP.ContactPersonName.label","ชื่อบุคคลที่สามารถติดต่อได้"},
			{"eMP.CopyFirsttoNotify.label","คัดลอกข้อมูลผู้ที่ติดต่อได้"},
			{"eMP.CopyHeadofFamily.label","คัดลอกหัวหน้าครอบครัว"},
			{"eMP.CopyNextofKin.label","คัดลอกข้อมูลญาติใกล้ชิด"},
			{"eMP.CopyPatient.label","คัดลอกผู้ป่วย"},
			{"eMP.CopyPatientAddress.label","คัดลอกจากทะเบียนบ้าน"},
			{"eMP.CopyResidenceAddress.label","คัดลอกจากทะเบียนบ้าน"},
			{"eMP.CountryCode.label","รหัสประเทศ"},
			{"eMP.CountryName.label","ชื่อประเทศ"},
			{"eMP.CreateFileduring.label","สร้างแฟ้ม ขณะ"},
			{"eMP.CreatePatientFile.label","สร้างแฟ้มผู้ป่วย"},
			{"eMP.CutOffPeriod.label","ระยะเวลาที่สิ้นสุด"},
			{"eMP.Deceasedonly.label","เฉพาะที่เสียชีวิต"},
			{"eMP.deceasedremarks.label","หมายเหตุของการเสียชีวิต"},
			{"eMP.DefaultAltID1ValueinEmp.ID.label","หมายเลขบัตรประจำตัวอื่น"},
			{"eMP.DefaultSoundexType.label","ชนิดเสียงคล้ายเบื้องต้น"},
			{"eMP.DeliveryIndication.label","ข้อบ่งชี้ของการคลอด"},
			{"eMP.DeliveryIndicationCode.label","รหัสข้อบ่งชี้ของการคลอด"},
			{"eMP.DeliveryIndicationDesc.label","คำอธิบายข้อบ่งชี้ของการคลอด"},
			{"eMP.DeliverySurgicalClassification.label","กรแยกประเภทการผ่าตัดคลอด"},
			{"eMP.DeliverySurgicalClassificationCode.label","รหัสการแยกประเภทการผ่าตัดคลอด"},
			{"eMP.DeliverySurgicalClassificationDesc.label","คำอธิบายการแยกประเภทการผ่าตัดคลอด"},
			{"eMP.DeliveryType.label","ชนิดการคลอด"},
			{"eMP.DeliveryTypeDesc.label","คำอธิบายชนิดของการคลอด"},
			{"eMP.demographicdetails.label","ข้อมูลทั่วไปของผู้ป่วย"},
			{"eMP.DesignatedRoyalties.label","เชื้อพระวงศ์"},
			{"eMP.District.label","อำเภอ"},
			{"eMP.DistrictCode.label","รหัสอำเภอ"},
			{"eMP.DistrictCodeFrom.label","รหัสอำเภอ จาก"},
			{"eMP.Doyouwanttochangethevalues.label","คุณต้องการเปลี่ยนค่าหรือไม่"},
			{"eMP.DuplicateMaster.label","ข้อมูลผู้ป่วยซึ่งตัดผู้ป่วยที่ซ้ำกันออก"},
			{"eMP.EducationLevel.label","ระดับการศึกษา"},
			{"eMP.EM.label","ฉุกเฉิน"},
			{"eMP.EmergencySeries.label","ชุดเลขลำดับผู้ป่วยฉุกเฉิน"},
			{"eMP.emerpatregn.label","ลงทะเบียนผู้ป่วยฉุกเฉิน"},
			{"eMP.EmerRegn.label","ลงทะเบียนฉุกเฉิน"},
			{"eMP.EnterPatientID.label","ใส่หมายเลขประจำตัวผู้ป่วย"},
			{"eMP.EntitlementApplicability.label","สามารถให้สิทธิได้"},
			{"eMP.EntitlementBy.label","ให้สิทธิโดย"},
			{"eMP.EntitlementPlan.label","แผนการให้สิทธิ"},
			{"eMP.EstateWorkers.label","ระดับผู้ปฏิบัติงาน"},
			{"eMP.EthnicGroupCode.label","รหัสกลุ่มเชื้อชาติ"},
			{"eMP.EthnicGroupDescription.label","คำอธิบายกลุ่มเชื้อชาติ"},
			{"eMP.ethnicity.label","กลุ่มชาติพันธุ์"},
			{"eMP.EthnicityCode.label","รหัสเชื้อชาติ"},
			{"eMP.EthnicityDesc.label","คำอธิบายเชื้อชาติ"},
			{"eMP.EthnicSubGroup.label","กลุ่มย่อยเชื้อชาติ"},
			{"eMP.EthnicSubGroupCode.label","รหัสกลุ่มเชื้อชาติย่อย"},
			{"eMP.EthnicSubGroupDesc.label","คำอธิบายกลุ่มเชื้อชาติย่อย"},
			{"eMP.examclinicalfindings.label","การตรวจพบทางคลินิก"},
			{"eMP.expiration.label","หมดอายุ"},
			{"eMP.ExpiryApplicable.label","วันหมดอายุสามารถใช้ได้"},
			{"eMP.externalhospital.label","โรงพยาบาลอื่น"},
			{"eMP.ExternalPatientDonorSeries.label","ผู้ป่วยจากนอกโรงพยาบาล /ชุดเลขลำดับผู้บริจาค"},
			{"eMP.ExternalReferralSource.label","แหล่งส่งตัวนอกโรงพยาบาล"},
			{"eMP.ExternalSourceSeries.label","ชุดเลขลำดับการส่งตัวจากนอกโรงพยาบาล"},
			{"eMP.family.label","ครอบครัว"},
			{"eMP.FamilyLink.label","เชื่อมโยงครอบครัว"},
			{"eMP.FamilyNameinOtherLanguage.label","ชื่อสกุล ในภาษาอื่น"},
			{"eMP.FamilyNo.label","หมายเลขประจำตัวครอบครัว"},
			{"eMP.fatherdetails.label","รายละเอียดของบิดา"},
			{"eMP.fathername.label","ชื่อบิดา"},
			{"eMP.fatherremarks.label","หมายเหตุเกี่ยวกับบิดา"},
			{"eMP.Feeding.label","การให้อาหาร"},
			{"eMP.FieldName.label","ชื่อพื้นที่"},
			{"eMP.FieldSize.label","ขนาดพื้นที่"},
			{"eMP.FieldTitle.label","คำนำหน้าพื้นที่"},
			{"eMP.File.label","แฟ้ม"},
			{"eMP.FileMaintenance.label","การดูแลแฟ้ม"},
			{"eMP.FileStorageLocn.label","สถานที่เก็บแฟ้ม"},
			{"eMP.FileTypeCode.label","รหัสชนิดแฟ้มข้อมูล"},
			{"eMP.ForBaby.label","สำหรับทารก"},
			{"eMP.Foreigner.label","ต่างชาติ"},
			{"eMP.ForEnglish.label","สำหรับภาษาอังกฤษ"},
			{"eMP.ForLocLang.label","สำหรับภาษาไทย"},
			{"eMP.Fresh.label","สดใหม่"},
			{"eMP.FullTimeEmployed.label","พนักงานประจำ"},
			{"eMP.FullTimeStudent.label","นักศึกษาภาคปกติิ"},
			{"eMP.GeneralSeries.label","ชุดเลขลำดับทั่วไป"},
			{"eMP.GeneratedFileNo.label","หมายเลขแฟ้มที่ออกแล้ว"},
			{"eMP.GeneratePatientID.label","ออกหมายเลขประจำตัวผู้ป่วย"},
			{"eMP.GenerateSl.No.forUnknownPatients.label","ออกหมายเลขประจำตัวผู้ป่วยที่ไม่ทราบชื่อ"},
			{"eMP.Gestation.label","ระยะเวลาของการตั้งครรภ์"},
			{"eMP.given.label","นามสกุล"},
			{"eMP.GovtEmployee.label","ข้าราชการ/ลูกจ้างของรัฐ"},
			{"eMP.GraceDays.label","จำนวนวันที่ผ่อนผัน"},
			{"eMP.Gravida.label","จำนวนครั้งของการตั้งครรถ์"},
			{"eMP.GroupCount.label","จำนวนกลุ่ม"},
			{"eMP.headfamilydetails.label","รายละเอียดของหัวหน้าครอบครัว"},
			{"eMP.HeadofFamilyPatientID.label","หมายเลขประจำตัวของหัวหน้าครอบครัวของผู้ป่วย"},
			{"eMP.headpatientdetails.label","รายละเอียดของหัวหน้าครอบครัว"},
			{"eMP.HeadPatientID.label","หมายเลขประจำตัวของหัวหน้าครอบครัว"},
			{"eMP.HepatitisB.label","โรคไวรัสตับอักเสบบี"},
			{"eMP.holder.label","ผู้ถือ/เจ้าของบัตร"},
			{"eMP.identitydetails.label","รายละเอียดของข้อมูลจำเพาะบุคคล"},
			{"eMP.in10Min.label","ภายใน 10 นาที"},
			{"eMP.in1Min.label","ภายใน 1 นาที"},
			{"eMP.in5Min.label","ภายใน 5 นาที"},
			{"eMP.inactivationremarks.label","หมายเหตุของการที่ยังไม่ได้ใช้งาน"},
			{"eMP.Inactiveonly.label","เฉพาะที่ระงับการใช้งาน"},
			{"eMP.IndicatorMark.label","ข้อบ่งชี้"},
			{"eMP.InFacility.label","ในหน่วยงาน/สถานพยาบาล"},
			{"eMP.Informant.label","ผู้ให้ข้อมูล"},
			{"eMP.InformantRemarks.label","หมายเหตุของผู้ให้ข้อมูล"},
			{"eMP.inhospital.label","ภายในโรงพยาบาล"},
			{"eMP.InternalRequestReport.label","รายงานการร้องขอภายใน"},
			{"eMP.InternalRequestReportDesc.label","คำอธิบายรายงานคำร้องภายใน"},
			{"eMP.InternalRequestReportId.label","หมายเลขประจำรายงานคำร้องภายใน"},
			{"eMP.InvokeChangePatientDetailsinNewbornRegn.label","อ้างถึงการเปลี่ยนแปลงรายละเอียดผู้ป่วยในการลงทะเบียนทารก"},
			{"eMP.InvokeRoutine.label","อ้างถึงเป็นประจำ"},
			{"eMP.IPAdmission.label","รับผู้ป่วยไว้ในโรงพยาบาล"},
			{"eMP.IpBooking.label","การจองเตียงผู้ป่วยใน"},
			{"eMP.KeepFileNumbersameasPatientID.label","เก็บหมายเลขแฟ้มเป็นเลขเดียวกับหมายเลขประจำตัวผู้ป่วย"},
			{"eMP.KeepMRNsameasPatientID.label","เก็บหมายเลขเวชระเบียนเป็นเลขเดียวกับหมายเลขประจำตัวผู้ป่วย"},
			{"eMP.lastcontact.label","การติดต่อครั้งสุดท้าย"},
			{"eMP.LastName.label","ชื่อสกุล"},
			{"eMP.LastNameinOtherLanguage.label","ชื่อสกุลในภาษาต่างชาติ"},
			{"eMP.LastPurgedDate.label","วันที่ปรับปรุงครั้งสุดท้าย"},
			{"eMP.latestmodifieddetails.label","รายละเอียดการแก้ไขครั้งล่าสุด"},
			{"eMP.LegalName.label","ชื่อตามกฎหมาย"},
			{"eMP.LegalNames.label","ชื่อตามกฏหมาย"},
			{"eMP.Legend.label","ชื่อเดิม"},
			{"eMP.LegendforLocLang.label","ชื่อเดิมในภาษาไทย"},
			{"eMP.LengthofBaby.label","ความยาวของทารก"},
			{"eMP.Live.label","มีชีวิต"},
			{"eMP.Livingarrangement.label","การจัดหาที่อยู่อาศัยให้"},
			{"eMP.Macerated.label","เนื้อเยื่อเปื่อยยุ่ย"},
			{"eMP.mailing.label","การส่งจดหมาย"},
			{"eMP.MaintainFamilyLink.label","รักษาความเชื่อมโยงของครอบตรัว"},
			{"eMP.MaintainOrganizationMembership.label","รักษาสมาชิกภาพขององค์กร"},
			{"eMP.manual.label","การทำเองโดยใช้มือ/คู่มือ"},
			{"eMP.maritalstatus.label","สถานะภาพสมรส"},
			{"eMP.MaritalStatusCode.label","รหัสสถานะสมรส"},
			{"eMP.MaritalStatusDesc.label","คำอธิบายสถานะสมรส"},
			{"eMP.MaxPatientAge.label","ค่าสูงสุดของอายุผู้ป่วย"},
			{"eMP.mcno.label","หมายเลขใบรับรองแพทย์"},
			{"eMP.Meconium.label","สิ่งขับถ่ายสีเขียวเข้มของทารก"},
			{"eMP.MedicalEntitlement.label","สิทธิทางการแพทย์"},
			{"eMP.MedicalRecordAdministration.label","การจัดการเวชระเบียน"},
			{"eMP.MedicalRecordNumber.label","หมายเลขเวชระเบียน"},
			{"eMP.MedicalRecordsAdministration.label","การจัดการเวชระเบียน"},
			{"eMP.MedicalSupervisionReqd.label","ต้องการการกำกับดูแลทางการแพทย์"},
			{"eMP.membership.label","สมาชิกภาพ"},
			{"eMP.MembershipDetails.label","รายละเอียดสมาชิกภาพ"},
			{"eMP.MinCutOff.label","จุดแบ่งต่ำสุด"},
			{"eMP.MinimumAgeofFather.label","อายุที่น้อยที่สุดสำหรับการเป็นบิดา"},
			{"eMP.MotherBabyLink.label","ความสัมพันธ์ของมารดาและทารก"},
			{"eMP.motherdetails.label","รายละเอียดของมารดา"},
			{"eMP.mothername.label","ชื่อมารดาของทารก"},
			{"eMP.mothernameinothlang.label","ชื่อมารดาที่เป็นภาษาอื่น"},
			{"eMP.motherpatientid.label","หมายเลขประจำตัวของมารดาของผู้ป่วย"},
			{"eMP.MotherPatientName.label","ชื่อมารดาผู้ป่วย"},
			{"eMP.motherpmino.label","หมายเลขประจำตัวของมารดา ( PMI )"},
			{"eMP.motherremarks.label","หมายเหตุเกี่ยวกับมารดา"},
			{"eMP.mothers.label","ของมารดา"},
			{"eMP.MPAuditTrailParameter.label","Parameter ของการติดตามประวัติผู้ป่วย"},
			{"eMP.MPInternalRequestReportRule.label","ระเบียบรายงานร้องขอภายในของดัชนีผู้ป่วยหลัก"},
			{"eMP.MPParameter.label","Paremeter ของดัชนีผู้ป่วยหลัก"},
			{"eMP.MPParameterforFacility.label","Paremeter ของดัชนีผู้ป่วยหลักสำหรัยสถานบริการหลัก"},
			{"eMP.MPTerminalDigit.label","ดัชนีผู้ป่วยหลัก"},
			{"eMP.MRAdministrationBy.label","การจัดการเวชระเบียน โดย"},
			{"eMP.MRSectionNotDefinedForthisSeries.label","หน่วยเวชระเบียนไม่ได้ระบุสำหรับชุดเลขลำดับนี้"},
			{"eMP.MultipleBirth.label","คลอดบุตรหลายครั้ง/คลอดแฝด"},
			{"eMP.NameDerivationLogic.label","รูปแบบชื่อ"},
			{"eMP.NamePrefixinOtherLanguage.label","คำนำหน้าชื่อ ภาษาต่างประเทศ"},
			{"eMP.names.label","ชื่อ"},
			{"eMP.namesearchby.label","ค้นหาชื่อโดย"},
			{"eMP.NameSuffixinOtherLanguage.label","คำต่อท้ายชื่อ ภาษาต่างประเทศ"},
			{"eMP.NationalID.label","หมายเลขบัตรประจำตัวประชาชน"},
			{"eMP.NationalIDChecks.label","ตรวจสอบหมายเลขบัตรประจำตัวประชาชน"},
			{"eMP.NationalIDHolder.label","ผู้ถือบัตรประชาชน"},
			{"eMP.NationalIDSeries.label","ชุดเลขหมายเลขบัตรประจำตัวประชาชน"},
			{"eMP.natureofdelivery.label","วิธีการคลอด"},
			{"eMP.NewBorn.label","ทารกแรกเกิด"},
			{"eMP.newborndetails.label","รายละเอียดของทารก"},
			{"eMP.NewBornSeries.label","ชุดหมายเลขทารกแรกเกิด"},
			{"eMP.newvalues.label","ค่าใหม่"},
			{"eMP.NODType.label","ชนิด"},
			{"eMP.NODTypeCode.label","รหัสชนิด NOD"},
			{"eMP.NODTypeDesc.label","คำอธิบายชนิด NOD"},
			{"eMP.nonorganizationmember.label","สมาชิกที่ไม่ใช่บุคลากรในองค์กร"},
			{"eMP.NoofGroups.label","จำนวนกลุ่ม"},
			{"eMP.noofmultiplebirths.label","จำนวนของการมีบุตรหลายคน/แฝด"},
			{"eMP.NoofPositions.label","จำนวนตำแหน่ง"},
			{"eMP.NoofTerminalDigits.label","จำนวนหมายเลข"},
			{"eMP.NotPatent.label","ไม่เปิดโล่ง"},
			{"eMP.NumberingControl.label","ควบคุมโดย"},
			{"eMP.occupation.label","อาชีพ"},
			{"eMP.OccupationClass.label","กลุ่มอาชีพ"},
			{"eMP.OccupationClassCode.label","รหัสประเภทอาชีพ"},
			{"eMP.OccupationClassDesc.label","คำอธิบายประเภทอาชีพ"},
			{"eMP.OccupationEmployer.label","นายจ้าง"},
			{"eMP.OccupationofthePerson.label","อาชีพของบุคคล"},
			{"eMP.OldFileNo.label","หมายเลขแฟ้มเดิม"},
			{"eMP.OldReferrals.label","การส่งต่อเพื่อรับการรักษาครั้งก่อน"},
			{"eMP.oldvalues.label","ค่าเดิม"},
			{"eMP.OPVisitRegistration.label","การลงทะเบียนตรวจผู้ป่วยนอก"},
			{"eMP.OrderableProcedure.label","คำสั่งการรักษาที่ใช้ได้/กระบวนการ"},
			{"eMP.Ordernumber.label","หมายเลขการรักษา"},
			{"eMP.OrganizationID.label","หมายเลขประจำองค์กร"},
			{"eMP.organizationmember.label","สมาชิกขององค์กร"},
			{"eMP.OrganizationMembership.label","สมาชิกภาพองค์กร"},
			{"eMP.OrganizationSubUnit.label","หน่วยย่อยองค์กร"},
			{"eMP.OtherAltNo.label","เลขเอกสารอื่น/เอกสารที่ขาด"},
			{"eMP.OtherDocAttached.label","เอกสารแนบอื่นๆ"},
			{"eMP.othermodes.label","วิธีการติดต่ออื่นๆ"},
			{"eMP.OtherModesofTpt.label","วิธีการส่งต่อ"},
			{"eMP.OtherName.label","ชื่ออื่นๆ"},
			{"eMP.OtherNamOtherLang.label","ชื่อในภาษาอื่น"},
			{"eMP.parentdetails.label","รายละเอียดของบิดามารดา"},
			{"eMP.Parity.label","จำนวนบุตรที่มีชีวิต"},
			{"eMP.PartTimeEmployed.label","พนักงานไม่เต็มเวลา"},
			{"eMP.PartTimeStudent.label","นักศึกษาภาคพิเศษ"},
			{"eMP.PatCatbyOrg.Membership.label","เกณฑ์การแบ่งประเภทผู้ป่วยโดยเป็นเจ้าหน้าที่"},
			{"eMP.PatencyofAnus.label","ภาวะการเปิดของช่องทวาร"},
			{"eMP.Patent.label","เปิด/ไม่ตัน"},
			{"eMP.PatientCardTitle.label","คำนำหน้าบัตรผู้ป่วย"},
			{"eMP.PatientDateofBirth.label","วันเกิดผู้ป่วย"},
			{"eMP.PatientIDFrom.label","หมายเลขประจำตัวผู้ป่วยตั้งแต่"},
			{"eMP.PatientIDLength.label","ความยาวของหมายเลขประจำตัวผู้ป่วย"},
			{"eMP.PatientMaster.label","ข้อมูลการกรอกรายละเอียดของผู้ป่วยทั้งหมด"},
			{"eMP.PatientNameDerivationLogic.label","รูปแบบชื่อผู้ป่วย"},
			{"eMP.PatientNameinLocLang.Required.label","ชื่อผู้ป่วย(ภาษาไทย)"},
			{"eMP.PatientNumbering.label","หมายเลขผู้ป่วย"}, 
			{"eMP.PatientRegistrationTitle.label","การลงทะเบียนผู้ป่วย"},
			{"eMP.PatientSearchResultFormat.label","รูปแบบผลการสืบค้นหาผู้ป่วย"},
			{"eMP.PatientSerieDesc.label","คำอธิบายชุด/ประเภทผู้ป่วย"},
			{"eMP.PatientSeries.label","ชุดเลขHNของผู้ป่วย"},
			{"eMP.PatientSeriesCode.label","รหัสชุด/ประเภทผู้ป่วย"},
			{"eMP.PatientSeriesSameAsMotherSeries.label","ชุดผู้ป่วยเหมือนกันชุดมารดา"},
			{"eMP.PatientSex.label","เพศผู้ป่วย"},
			{"eMP.PatientSuspension.label","การเลื่อนผู้ป่วย"},
			{"eMP.Pensioner.label","ข้าราชการบำนาญ"},
			{"eMP.Periodbetweentwodeliveries.label","ระยะเวลาระหว่างการคลอด"},
			{"eMP.personaldetails.label","รายละเอียดส่วนตัว"},
			{"eMP.PersonUnderPoliceCustody.label","บุคคลภายใต้การดูแลของตำรวจ"},
			{"eMP.photo.label","ภาพถ่าย"},
			{"eMP.PlaceOfIssue.label","สถานที่ที่ออกเอกสาร"},
			{"eMP.PopulateFrom.label","นำเข้าข้อมูลจาก"},
			{"eMP.Postal.label","รหัสไปรษณีย์"},
			{"eMP.postalcode.label","รหัสไปรษณีย์"},
			{"eMP.PostalDesc.label","คำอธิบายเกี่ยวกับไปรษณีย์"},
			{"eMP.PrefFacility.label","หน่วยงานที่เลือก"},
			{"eMP.prefix.label","คำนำหน้า"},
			{"eMP.PrefixRequired.label","ต้องระบุคำนำหน้า"},
			{"eMP.PrefixSex.label","คำนำหน้าเพศ"},
			{"eMP.primaryresidenceno.label","หมายเลขประจำตัวของผู้อาศัยหลัก"},
			{"eMP.Prisoners.label","นักโทษ"},
			{"eMP.ProcedureClassification.label","การแบ่งประเภทหัตถการ"},
			{"eMP.ProcedureClassificationCode.label","รหัสการแยกประเภทหัตถการ"},
			{"eMP.ProcedureClassificationDesc.label","คำอธิบายการแยกประเภทหัตถการ"},
			{"eMP.PromptforoldMRN.label","พร้อมสำหรับเลขเวชระเบียนเก่า"},
			{"eMP.PurgeAudit.label","ลบล้างการตรวจสอบ"},
			{"eMP.PurgeChangesupto.label","เปลี่ยนแปลงการลบล้าง ขึ้นอยู่กับ"},
			{"eMP.PurgeDate.label","วันที่ลบล้าง"},
			{"eMP.PurgedDateFrom.label","วันที่ลบล้าง ตั้งแต่"},
			{"eMP.PurgedDateTo.label","วันที่ลบล้าง ถึง"},
			{"eMP.PurgedUntil.label","ลบล้าง จนกระทั้ง"},
			{"eMP.RaceCode.label","รหัสสีผิว/เชื้อชาติ"},
			{"eMP.RaceCodes.label","รหัสสัญชาติ"},
			{"eMP.RaceDesc.label","คำอธิบายสีผิว/เชื้อชาติ"},
			{"eMP.RaceGroup.label","กลุ่มของเชื้อชาติ"},
			{"eMP.RangeValues.label","ช่วงค่า"},
			{"eMP.rapidregn.label","การลงทะเบียนด่วน"},
			{"eMP.RdAppts.label","การนัดหมายของภาควิชารังสีวิทยา"},
			{"eMP.ReasonforActive.label","เหตุผลการติดต่อ"},
			{"eMP.ReasonforActiveInactive.label","เหตุผลการติดต่อ การขาดการติดต่อ"},
			{"eMP.ReasonforSuspension.label","เหตุผลการล่าช้า"},
			{"eMP.RecordPatientDeath.label","บันทึกผู้ป่วยเสียชีวิต"},
			{"eMP.RecordRevokePatientDeath.label","บันทึก แก้ไขการถึงแก่กรรมของผู้ป่วย"},
			{"eMP.Reference.label","แหล่งที่มา/อ้างอิง"},
			{"eMP.ReferralLetterNo.label","หมายเลขของเอกสารการส่งต่อผู้ป่วยเพื่อการรักษา"},
			{"eMP.ReferralNotes.label","บันทึกการส่งต่อผู้ป่วยเพื่อการรักษา"},
			{"eMP.ReferredForIP.label","การส่งต่อผู้ป่วยเพื่อการรักษาในโรงพยาบาล"},
			{"eMP.region.label","ภูมิภาค"},
			{"eMP.Regioncode.label","รหัสภูมิภาค"},
			{"eMP.RegionDesc.label","คำอธิบายภูมิภาค"},
			{"eMP.RegisteredDisabled.label","การลงทะเบียนที่ทำแล้ว ไม่สามารถใช้งานได้"},
			{"eMP.RegisterPatient.label","ลงทะเบียนผู้ป่วย"},
			{"eMP.RegisterPatientReferral.label","ลงทะเบียนการส่งต่อผู้ป่วยเพื่อการรักษา"},
			{"eMP.RegisterReferraldetails.label","รายละเอียดการลงทะเบียนการส่งตัว"},
			{"eMP.RegistrationOutput.label","ผลลัพธ์การลงทะเบียน"},
			{"eMP.RegistrationSource.label","แหล่งที่มาของการลงทะเบียน"},
			{"eMP.RegnDateFrom.label","วันที่ลงทะเบียน ตั้งแต่"},
			{"eMP.RegnDateTo.label","ถึงวัน"},
			{"eMP.RegNewBorn.label","การลงทะเบียนเด็กแรกคลอด"},
			{"eMP.regnfacility.label","หน่วยงานเวชระเบียน"},
			{"eMP.RegnMonthFrom.label","เดือนที่ลงทะเบียน ตั้งแต่"},
			{"eMP.RegnMonthTo.label","ถึงเดือน"},
			{"eMP.RegnType.label","ชนิดการลงทะเบียน"},
			{"eMP.regntypeno.label","รูปแบบ/เลขที่ของการลงทะเบียน"},
			{"eMP.RegnYearFrom.label","ปีที่ลงทะเบียน ตั้งแต่"},
			{"eMP.RegnYearTo.label","ถึงปี"},
			{"eMP.reinstatementremarks.label","หมายเหตุ"},
			{"eMP.relatedcontacts.label","บุคคลที่ใช้ติดต่อ / อาชีพ"},
			{"eMP.relatedmemberfamily.label","คนใกล้ชิดในครอบครัวเดียวกัน"},
			{"eMP.relatedmembernonfamily.label","คนใกล้ชิดที่ไม่ได้อยู่ในครอบครัวเดียวกัน"},
			{"eMP.RelationshipCode.label","รหัสความสัมพันธ์"},
			{"eMP.RelationshipDesc.label","คำอธิบายความสัมพันธ์"},
			{"eMP.RelationshipforOrganizationMember.label","ความสัมพันธ์ สำหรับสมาชิกในองค์กร"},
			{"eMP.RelationshiptoHeadofFamily.label","ความสัมพันธ์กับหัวหน้าของครอบครัว"},
			{"eMP.relationshipwithpatient.label","ความสัมพันธ์กับผู้ป่วย"},
			{"eMP.relative.label","ญาติพี่น้อง"},
			{"eMP.ReligionDesc.label","คำอธิบายศาสนา"},
			{"eMP.remarksonrevoking.label","หมายเหตุในการแก้ไขข้อมูลที่ได้รับการเลือกมาแล้วก่อนหน้านี้"},
			{"eMP.repository.label","แหล่งเก็บข้อมูล"},
			{"eMP.RequiredforAllSeries.label","ร้องขอทุกชุดเลขลำดับ"},
			{"eMP.residenceaddress.label","ตามทะเบียนบ้าน"},
			{"eMP.ResidenceArea.label","ถิ่นพำนัก"},
			{"eMP.ResidenceTown.label","เมืองที่อยู่"},
			{"eMP.Resident.label","ผู้พักอาศัย"},
			{"eMP.ResidentialArea.label","พื้นที่สำหรับพักอาศัย"},
			{"eMP.ResidentialTown.label","เมืองสำหรับพักอาศัย"},
			{"eMP.ReviewMotherbabylinkbeforeRegn.label","ดูความเชื่อมโยงมารดา-ทารกก่อนลงทะเบียน"},
			{"eMP.RevokePatientDeath.label","เพิกถอนการเสียชีวิตของผู้ป่วย"},
			{"eMP.RoutineName.label","ชื่อประจำ"},
			{"eMP.searchfamilyname.label","ค้นหานามสกุล"},
			{"eMP.searchothername.label","ค้นหาชื่ออื่นๆ"},
			{"eMP.Second.label","ลำดับที่ 2"},
			{"eMP.SectionType.label","ชนิดของ section"},
			{"eMP.SelectSeries.label","การเลือกประเภท"},
			{"eMP.SelfEmployed.label","ทำกิจการส่วนตัว"},
			{"eMP.Semigovernment.label","กึ่งรัฐบาล"},
			{"eMP.SerialNumberNext.label","เลขลำดับต่อไป"},
			{"eMP.SerialNumberStart.label","เลขลำดับเริ่มต้น"},
			{"eMP.SeriesType.label","ชนิดชุดเลขลำดับ"},
			{"eMP.SiteFacility.label","สถานที่/สถานบริการหลัก"},
			{"eMP.SiteFacilityID.label","สถานที่/ หมายเลขFacility"},
			{"eMP.SiteFacilityName.label","สถานที่/ ชื่อ Facility"},
			{"eMP.SmallChildren.label","เด็กเล็กๆ"},
			{"eMP.SpecialCharacters.label","อักขระพิเศษ"},
			{"eMP.SpecialityDesc.label","คำอธิบายความเชี่ยวชาญ"},
			{"eMP.SpouseDependent.label","คู่สมรสที่ต้องเลี้ยงดู"},
			{"eMP.spouseonly.label","คู่สมรสเท่านั้น"},
			{"eMP.Sr.Resident.label","ลำดับผู้พักอาศัย"},
			{"eMP.StandardFamilyName.label","ชื่อสกุลมาตรฐาน"},
			{"eMP.StandardOtherName.label","ชื่ออื่นที่เป็นมาตรฐาน"},
			{"eMP.StateCode.label","รหัสรัฐ"},
			{"eMP.StateCodeFrom.label","รหัสรัฐ ตั้งแต่"},
			{"eMP.StillBorn.option.label","ตายคลอด"},
			{"eMP.Stools.label","อุจจาระ "},
			{"eMP.Student.label","นักเรียน"},
			{"eMP.Stump.label","stump"},
			{"eMP.Stumps.label","โคนที่เหลือจากการตัดสายสะดือ"},
			{"eMP.suborgn.label","องค์กรย่อย"},
			{"eMP.SubsequentRegnofMultipleBirthWithin.label","ลงทะเบียนทารกแฝดคนถัดไป ภายใน"},
			{"eMP.SubUnit.label","หน่วยย่อย"},
			{"eMP.SubUnitDetails.label","รายละเอียดหน่วยย่อย"},
			{"eMP.SubUnitID.label","หมายเลขรายละเอียดหน่วยย่อย"},
			{"eMP.Suffix.label","คำต่อท้าย"},
			{"eMP.SummarizationRange.label","ช่วงการสรุป"}, 
			{"eMP.Suspendedonly.label","เฉพาะที่งดใช้ชั่วคราว"},
			{"eMP.SuspendingofService.label","ระงับการบริการไว้ก่อน"},
			{"eMP.SuspendingServicetoPatient.label","ระงับการบริการผู้ป่วยไว้ก่อน"},
			{"eMP.SuspendReinstatePatient.label","ระงับบริการ/ ให้การบริการผู้ป่วย"},
			{"eMP.suspensionremarks.label","หมายเหตุของการงดใช้ชั่วคราว"},
			{"eMP.suspstatusremarks.label","สถานะการงดใช้ชั่วคราว/หมายเหตุ"},
			{"eMP.telephoneres.label","โทรศัพท์ที่ลงทะเบียนไว้"},
			{"eMP.TerminalDigitBy.label","Terminal Digit โดย"},
			{"eMP.TerminalDigitCount.label","การนับTerminal Digit"},
			{"eMP.TerminalDigitDerivationLogic.label","รูปแบบ Terminal Digit"},
			{"eMP.TerminalDigitLevel.label","ระดับ Terminal Digit"},
			{"eMP.TerminalDigitsPosition.label","ตำแหน่งหลัก"},
			{"eMP.Third.label","ลำดับที่ 3"},
			{"eMP.ThirdName.label","ชื่อที่สาม"},
			{"eMP.TotalSelection.label","รวมการเลือก"},
			{"eMP.TownCodeFrom.label","รหัสเมือง ตั้งแต่"},
			{"eMP.TownDesc.label","คำอธิบายเมือง"},
			{"eMP.UmbCordCutBy.label","ตัดสายสะดือโดย"},
			{"eMP.UmbilicalCord.label","สายสะดือ"},
			{"eMP.Unemployed.label","ว่างงาน"},
			{"eMP.UnmarriedIndicator.label","ตัวชี้วัด (ผู้ป่วย)ไม่แต่งงาน"},
			{"eMP.UnrestrictedSeries.label","ชุดเลขลำดับที่ ไม่จำกัด"},
			{"eMP.UsedStatus.label","สถานะที่ใช้"},
			{"eMP.vaccinationdetails.label","รายละเอียดการให้วัคซีน"},
			{"eMP.VaccSite.label","บริเวณที่ฉีดวัคซีน"},
			{"eMP.VaginalDeliveryType.label","รูปแบบของการคลอดปกติ"},
			{"eMP.VaginalDeliveryTypeCode.label","รหัสชนิดการคลอดทางช่องคลอด"},
			{"eMP.VaginalDeliveryTypeDesc.label","คำอธิบายชนิดการคลอดทางช่องคลอด"},
			{"eMP.ValidforHeadPatientID.label","ค่าเริ่มต้นหมายเลขบัตรประจำตัวผู้ป่วย ถูกต้อง"},
			{"eMP.viewbirthregdtls.label","ดูรายละเอียดสูติบัตร"},
			{"eMP.ViewMotherBabyLink.label","ดูการเชื่อมโยง มารดา-ทารก"},
			{"eMP.ViewPatientDetails.label","ดูรายละเอียดของผู้ป่วย"},
			{"eMP.ViewPatientPhoto.label","ดูภาพผู้ป่วย"},
			{"eMP.VitaminK.label","วิตามินเค"},
			{"eMP.WalkUp.label","เดินเข้าห้องตรวจ"},
			{"eMP.WeightRange.label","ช่วงน้ำหนัก"},
			{"eMP.WelcometoeHIS.label","ยินดีต้อนรับสู่ระบบ eHIS"},
			{"eMP.WithAlternateID.label","ด้วยหมายเลข"},
			{"eMP.WithNationalID.label","ด้วยหมายเลขบัตรประจำตัวประชาชน"},
			{"eMP.YellowSoft.label","เหลืองอ่อน"},
			{"eMP.LinkRelatedFamilyMembers.label","โยงแผงผังครอบครัว"},
			{"eMP.CurrentAddress.label","ที่อยู่ปัจจุบัน"},
			{"eMP.NearByPlace.label","สถานที่ใกล้เคียง"},
			{"eMP.SpouseName.label","ชื่อคู่สมรส"},
			{"eMP.CongenitalDisease.label","โรคประจำตัว"},
			{"eMP.DrugAndOtherDisease.label","ประวัติการแพ้ยาและสารอื่น ๆ"},
			{"eMP.HospitalInformation.label","ข้อมูลของโรงพยาบาล"},
			{"eMP.ToBeFilledByHospitalStaff.label","กรอกโดยเจ้าหน้าที่โรงพยาบาล"},
			{"eMP.SocialWelfareInformation.label","บันทึกของงานสังคมสงเคราะห์"},
			{"eMP.ContactPerson.label","ชื่อผู้ติดต่อได้"},
			{"eMP.FatherMotherName.label","ชื่อบิดา/มารดา"},
			{"eMP.Tumbon.label","ตำบล"},
			{"eMP.Province.label","จังหวัด"},
			{"eMP.Father.label","บิดา"},
			{"eMP.CitizenId.label","เลขบัตรประชาชน"},
			{"eMP.ICertfiedAllInfo.label","ข้าพเจ้าขอรับรองว่าเป็นข้อมูลส่วนบุคคลและรูปภาพของ"},
			{"eMP.TrueAndValid.label","จริง"},
			{"eMP.DLAUserID.label","DLA UserID"},
			{"eMP.SelfDeputy.label","ผู้ป่วย/ผู้แทน"},
			{"eMP.RegistrationMode.label","ประเภทการลงทะเบียน"},
			{"eMP.CurrentPatientClass.label","ประเภทของผู้ป่วยขณะค้นหา"},
			{"eMP.ReqStatDesc.label","Req status desc: "},
			{"eMP.PatientNameInLocalLang.label","ชื่อผู้ป่วย(ภาษาไทย)"},
			{"eMP.DeceasedStatus.label","สถานะของการเสียชิวิต"},
			{"eMP.PrematureCutOffPeriod.label","Cut-off period for Pre-mature Births"},
			{"eMP.GestationPeriod.label","Gestation Period"},

			/* Patient Front Sheet Report specific Legends */

			{"eMP.maritalstatus_fs.label","สถานภาพ"},
			{"eMP.residenceaddress_fs.label","ที่อยู่ตามทะเบียนบ้าน"},

			/* End of Patient Front Sheet Report specific Legends */

			{"eMP.PatientListforAltIdNo1.label","Patient List for #"},
			{"eMP.Complicationsin1stStage.label","Complications in 1st stage of labour"},
			{"eMP.Complicationsin2ndStage.label","Complications in 2nd stage of labour"},
			{"eMP.Complicationsin3rdStage.label","Complications in 3rd stage of labour"},
			{"eMP.DeliveryIndicator.label","Delivery Indicator"},
			{"eMP.CSection.label","C Section"},	
			{"eMP.RelatedtoPregnancy.label","Related to Pregnancy"},				
			{"eMP.ComplicationsofPregnancy.label","เจ็บป่วยจากการตั้งครรภ์"},
			{"eMP.ComplicationsofPregnancyCode.label","Complications of Pregnancy Code"},
			{"eMP.ComplicationsofPregnancyDesc.label","Complications of Pregnancy Description"},
			{"eMP.SingleStageNewBornRegnAppl.label","Single Stage New Born Registration Applicable"},
			{"eMP.ControlNo.label","เลขควบคุม"},
			{"eMP.Host.label","เจ้าบ้านผู้มอบอำนาจ"},
			{"eMP.Representative.label","ผู้รับมอบอำนาจให้ไป"},
			{"eMP.SingleBirth.label","เกิดเดี่ยว"},
			{"eMP.FamilyStatus.label","สถานภาพของครอบครัว"},
			{"eMP.BirthCertificateOfficer.label","ผู้ออกหนังสือ"},
			{"eMP.SpecialDelivery.label","ทำคลอดด้วยวิธีพิเศษ"},
			{"eMP.ComplicationsnotrelatedtoPregnancy.label","เจ็บป่วยไม่เกี่ยวกับครรภ์"},
			{"eMP.Mothersillness.label","เจ็บป่วยของมารดา"},
			{"eMP.BirthInjury.label","บาดเจ็บเนื่องจากการคลอด"},
			{"eMP.Waning.label","แรม"},
			{"eMP.Waxing.label","ขึ้น"},
			{"eMP.Moon.label","ค่ำ"},
			{"eMP.PlaceofIssuingCertificate.label","สถานที่ออกหนังสือรับรอง"},
			{"eMP.HospitalName.label","ชื่อสถานพยาบาล"},
			{"eMP.BirthLevel.label","เป็นบุตรลำดับที่"},

			/* Birth Certificate Report specific Legends */

			{"eMP.Day_bc.label","ตรงกับวัน"},
			{"eMP.Address_bc.label","อยู่บ้านเลขที่"},
			{"eMP.PractitionerType_bc.label","เป็น"},
			{"eMP.Practitioner_bc.label","ผู้ทำคลอด"},
			{"eMP.Year_bc.label","พ.ศ."},
			{"eMP.Name_bc.label","ชื่อตัว"},
			{"eMP.Child_bc.label","บุตร"},	
			{"eMP.Address1_bc.label","บ้านเลขที่"},	
			{"eMP.CongenitalAnomalies_bc.label","ร่างกายวิปริตมาแต่กำเนิด"},
			{"eMP.BirthWeight_bc.label","น้ำหนักเด็ก____กรัม"},		
			{"eMP.Gestation_bc.label","อยู่ในครรภ์นาน"},
			{"eMP.BirthOrder_bc.label","เกิดแฝดลำดับที่"},
			{"eMP.MultipleBirth_bc.label","เกิดแฝด"},
			{"eMP.NewBorn_bc.label","เด็กที่เกิด"},
			{"eMP.No_bc.label","ที่"},
			{"eMP.ComplicationsofDelivery.label","เจ็บป่วยเนื่องจากการคลอด"},
			{"eMP.PlaceofBirth_th.label","ชื่อสถานที่เกิด"},
			{"eMP.Estimated.label","(EBD)"},
			{"eMP.ComplicationsRelatedPregnancy.label","Complications Related to Pregnancy"},
			{"eMP.ComplicationsNotRelatedPregnancy.label","Complications not Related to Pregnancy"},
			{"eMP.NameOfHospitalIssuedTheDeathCertification.label", "สถานพยาบาลที่ออกหนังสือรับรอง"},
			{"eMP.Tambon.label", "ตำบล/แขวง "},
			{"eMP.Amphur.label", "อำเภอ/เขต"},
			{"eMP.TreatedPhysicianBeforeDecease.label",  "ผู้รักษาก่อนตาย"},
			{"eMP.DiagnosisCauseOfDeath.label"  ,   "โรคที่เป็นสาเหตุการตาย (เขียนเป็นภาษาอังกฤษตัวพิมพ์ใหญ่)"},
			{"eMP.CapitalLetters.label"   ,  "CAPITAL LETTERS"},
			{"eMP.TheDurationFromTheIllnessStartToDecease.label"  ,  "ระยะเวลาตั้งแต่เริ่มเป็นโรค จนกระทั่งเสียชีวิต"},
			{"eMP.OtherDiseaseOrComplicationsThatSupportTheCauseOfDeath.label" , "โรคหรือภาวะอื่นที่เป็นเหตุหนุน"},
			{"eMP.IfTheDiseasedPersonIsFemale.label", "หากผู้เสียชีวิตเป็นสตรี"},
			{"eMP.DeceasedLocation.label" , "สถานที่ตาย"},
			{"eMP.NameOfDeceaseLocation.label" , "ชื่อสถานที่ โรงพยาบาลศิริราช"},
			{"eMP.ParentOfDeceasePerson.label"  , "มารดา บิดา ของผู้ตาย"},
			{"eMP.PersonCertifiedTheDecease.label"  , "ผู้รับรองการตาย"},
			{"eMP.Profession.label"  , "เป็น"},
			{"eMP.MPDTHCER_REPORT_TEXT1.label" , "สาเหตุการตายที่ระบุในหนังสือรับรองการตายฉบับนี้ ระบุไว้ตามเกณฑ์บัญชีจำแนกโรคระหว่างประเทศ เพื่อรวบรวมข้อมูลทะเบียนราษฏร ทำสถิติการตายของประเทศ และใช้ในการวางแผนป้องกันและแก้ไขปัญหาสาธารณสุขเท่านั้น จึงอาจแตกต่างจากใบรับรองทางกฏหมายช นิดอื่นๆ (เช่น ใบชันสูตรพลิกศพ) ได้"},
			{"eMP.MPDTHCER_REPORT_TEXT2.label" , "ขอรับรองว่ารายการข้างต้นถูกต้อง"},
			{"eMP.CertifiedPerson.label" , "ผู้รับรองการตาย"},
			{"eMP.PublicHealthWorker.label" , "เจ้าหน้าที่สาธารณสุข"},
			{"eMP.DeceasedPersonDetail.label" , "ผู้ตาย"},
			{"eMP.DocumentRunningNumber.label", "ที่..................../ ๒๕................"},
			{"eMP.SurnameOfCertifiedPerson.label", "ชื่อสกุล"},
			{"eMP.ThaiTraditionalMedicine.label",  "แพทย์แผนโบราณ"},
			{"eMP.DeceasedPatient.label",  "๒. คนตาย"},
			{"eMP.DateOfDeceased.label",  "๒.๔ ตายเมื่อวันที่  เดือน  พ.ศ."},
			{"eMP.PlaceOfDeceased.label",  "๒.๕ สถานที่ตาย บ้านเลขที่ หมู่ที่ ซอย ถนน ตำบล อำเภอ จังหวัด"},
			{"eMP.NameOfMother.label",  "๓.๑ ชื่อตัว"},
			{"eMP.SurnameOfMother.label", "ชื่อสกุล"},
			{"eMP.PregnancyPeriod.label", "๓.๔ อยู่ในครรภ์นาน      เดือน           สัปดาห์"},
			{"eMP.MainCauseOfDeath.label", "ก. เหตุการตายโดยตรง"},
			{"eMP.OtherCauseOfDeath.label",  "ข. เหตุนำแทรก"},
			{"eMP.OldCauseOfDeath.label",  "ค. เหตุนำเดิม(สาเหตุ) "},
			{"eMP.AssociatedCauseOfDeath.label",  "๒. ภาวะสำคัญอื่นที่เป็นเหตุหนุน"},
			{"eMP.BodyHasToBeAutopsy.label",  "๔.๒ การผ่าตัดตรวจศพ"},
			{"eMP.AutopsyNotRequired.label",  "ไม่ได้ทำ"},
			{"eMP.SurnameOfFather.label",  "สกุล บิดาของเด็กที่คลอด"},


			/* End of Birth Certificate Report specific Legends */

			{"eMP.NotPregnant.label"," ไม่ตั้งครรภ์"},
			{"eMP.PregnantNotMoreThan6Weeks.label","Pregnant Not More Than 6 Weeks"},
			{"eMP.surname.label" ,"ชื่อสกุล"},
			{"eMP.PregnancyPeriod1.label", "อยู่ในครรภ์นาน"},
			{"eMP.CauseOfDeath.label","เหตุการตาย"},
			{"eMP.LicenseNo.label","ทะเบียนเลขที่"},
			{"eMP.Accoucheuse.label","เป็นหมอตำแย"},
			{"eMP.MidwifeAssistance.label","พนักงานผดุงครรภ์"},
			{"eMP.Physician.label","แพทย์แผนปัจจุบัน"},
			{"eMP.AutopsyRequried.label","ทำคือ"},
			{"eMP.Specialty.label" ,"ผู้ประกอบโรคศิลปสาขา"},
			{"eMP.FullNameofCertifiedPractitioner.label", "ชื่อ-สกุลผู้รับรอง"},
			{"eMP.WebCam.label","Web Cam"},
			{"eMP.ChangePatientPhoto.label","เปลี่ยนภาพถ่ายผู้ป่วย"},
			{"eMP.PatientPhoto.label","ภาพถ่ายผู้ป่วย"}

	}; 
}
